### ISSUE TITLE
Cannot compile console app on .NET 5.0

### ISSUE THREAD

**Issue by kant2002** [dotnet/fsharp#10012]
Please provide a succinct description of the issue.

**Repro steps**

1. Expected file "obj\Debug\net5.0\ref\
2. `<TargetFramework>net5.0</TargetFramework>`
3. dotnet build

**Expected behavior**

Build ok

**Actual behavior**

C:\Program Files\dotnet\sdk\5.0.100-rc.1.20426.3\Microsoft.Common.CurrentVersion.targets(4243,5): error : Expected file "obj\Debug\net5.0\ref\fsc-10009.dll" does not exist.

**Related information**

Provide any related information (optional):

```
> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20426.3
 Commit:    48301f6f77
```

**Comment by cartermp** [comment]
fixed in https://github.com/dotnet/sdk/pull/13085, this is an issue with the SDK
