### ISSUE TITLE
build -testScripting always fails

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#10019]
I've come to understand that certain tests can only be run from the commandline when you pass `-ci -bl` (or `-nobl`, ~but that's failing again #9814~ EDIT: nope, works), or if you specify Release build with `-c Release`. However, I can't find any way to run the `-testScripting` tests successfully.

**Repro steps**

Try any of these commands:

```
build -testScripting 
build -testScripting -c Release
build -testScripting -c Debug
build -testScripting -c Release -ci -bl
build -testScripting -c Release -ci -nobl
```

**Expected behavior**

At least one of above combinations should succeed.

**Actual behavior**

Each gives three failing tests (of 50 tests total), here's one such test:

```
  X Multiple Instances of DependencyProvider should be isolated [1s 563ms]
  Error Message:
     Expected: True
  But was:  False

  Stack Trace:
     at FSharp.DependencyManager.UnitTests.DependencyManagerInteractiveTests.Multiple Instances of DependencyProvider should be isolated() in D:\Projects\OpenSource\FSharp\tests\FSharp.Compiler.Private.Scripting.UnitTests\DependencyManagerInteractiveTests.fs:line 136
```

**Known workarounds**

None

**Comment by KevinRansom** [comment]
That's wierd it always passes for me.

**Comment by KevinRansom** [comment]
okay I just ran each of those commands and they all work and pass.  I think I have seen the error you pasted before, and I think it happens when I switch branches, and haven't done a git clean -fxdq.  I will just try that out, and report back.

**Comment by KevinRansom** [comment]
nope that didn't repro the error either.

**Comment by abelbraaksma** [comment]
@KevinRansom, thanks for looking into this, I just realized I was on a feature branch `release/dev16.7`, without knowing it. I'm cleaning & rebuilding now with latest `main`, see if it still reproduces.

**Comment by abelbraaksma** [comment]
Verified: works fine on `main` branch. Guess there's not much use to fix it for the older `dev16.7` branches, so I'll close this.
