### ISSUE TITLE
Creating a "docs" directory

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#10011]
I'd like us to consider creating a docs directory in this repo.  I can do it, I just want to discuss it first

Principles:

1. Content is nothing but markdown and literate fsx scripts like other F# repos

2. This includes the existing F# compiler guide, FSharp.Compiler.Service, contribution guide, testing guide and any future compiler style guide.  (It is not the language spec or anything like that)

3. We use `fsdocs` over the content and generate API documentation, automated in CI on each push to master pushing to `gh-pages` branch like in other repos (people can just read the markdown too)

4. Docs will appear on github pages at https://dotnet.github.io/fsharp

This is related to https://github.com/dotnet/docs/pull/19881/

Note: Visual F# Tools docs should probably be separated into `visualfsharp/docs` - it's important long term to keep that separation I think.

**Comment by cartermp** [comment]
Note that the FCS docs are now here: https://github.com/dotnet/fsharp/tree/main/docsrc

We should rename this and adjust things as necessary.

cc @baronfel and @KevinRansom, since we all got together to discuss this kind of thing as it relates to yeeting the fcs folder out of existence and publishing FCS directly as a part of our builds

**Comment by baronfel** [comment]
I'm in favor. I actually started doing this over at https://github.com/baronfel/fsharp/tree/fcs-docs/, and have only been blocked because FSharp.Formatting lacks support for multiple languages (active discussion over at https://github.com/fsprojects/FSharp.Formatting/issues/593)

**Comment by cartermp** [comment]
Oh, bummer

**Comment by dsyme** [comment]
> I'm in favor. I actually started doing this over at https://github.com/baronfel/fsharp/tree/fcs-docs/, and have only been blocked because FSharp.Formatting lacks support for multiple languages (active discussion over at fsprojects/FSharp.Formatting#593)

It's good - that drives the addition of that feature to FSharp.Formatting, which I will make sure happens 👍
