### ISSUE TITLE
Why I can't execute fsc.exe?

### ISSUE THREAD

**Issue by Alvin-Seville** [dotnet/fsharp#10028]
**Repro steps**

1. Found `fsc.exe` at `C:\Program Files\dotnet\sdk\3.1.401\FSharp` and added it to `PATH`.
2. Bothered execute: `fsc` and obtained: `bash: /c/Program Files/dotnet/sdk/3.1.401/FSharp/fsc: cannot execute binary file: Exec format error`.
Why it's going on? How to fix it?

Provide any related information:

* Operating system - Windows
* .NET Runtime kind - .NET Core 3.1

**Comment by cartermp** [comment]
This is currently by design. To build projects with .NET Core, you need to use `dotnet build`. I believe there may be an issue on the .NET SDK to allow for direct compiler invocations.

**Comment by Alvin-Seville** [comment]
It would be useful I think.

**Comment by baronfel** [comment]
you can actually invoke the .net core compiler, you just use `dotnet <path to fsc.dll> <args>` instead of using fsc.exe. you _may_ be able to `dotnet <path to fsc.exe>`, but as a *nix person I can't verify that easily.

I do this all the time to tinker with specific compiler flags.

**Comment by abelbraaksma** [comment]
Note that the `fsc.exe` as found when opening a "Developer Command Prompt" in Windows just works. Afaik, any modules you'll compile will be valid .NET Core as long as you make sure to reference the proper libraries (though this is the normal approach for .NET Framework, and I think the approach mentioned above is the preferred approach for .NET Core).
