### ISSUE TITLE
fsi 10.9.1.0 for F# 4.7 reference dll ok but 10.10.0.0 for F# 4.7 not ok

### ISSUE THREAD

**Issue by ingted** [dotnet/fsharp#10021]
**Repro steps**

Provide the steps required to reproduce the problem:

1. fsi 10.9.1.0 for F# 4.7: 
   #r @"C:\Users\aniba\Downloads\mdcdev\packages\Akkling.Cluster.Sharding.0.9.3\lib\net452\Akkling.Cluster.Sharding.dll"
2. fsi 10.10.0.0 for F# 4.7:
   #r @"C:\Users\aniba\Downloads\mdcdev\packages\Akkling.Cluster.Sharding.0.9.3\lib\net452\Akkling.Cluster.Sharding.dll"

**Expected behavior**

1. --> Referenced 'C:\Users\aniba\Downloads\mdcdev\packages\Akkling.Cluster.Sharding.0.9.3\lib\net452\Akkling.Cluster.Sharding.dll' (file may be locked by F# Interactive process)

2. 1. --> Referenced 'C:\Users\aniba\Downloads\mdcdev\packages\Akkling.Cluster.Sharding.0.9.3\lib\net452\Akkling.Cluster.Sharding.dll' (file may be locked by F# Interactive process)

**Actual behavior**

1. --> Referenced 'C:\Users\aniba\Downloads\mdcdev\packages\Akkling.Cluster.Sharding.0.9.3\lib\net452\Akkling.Cluster.Sharding.dll' (file may be locked by F# Interactive process)

2. error FS0192: internal error: internal error: Fixup: the ccu thunk for assembly System.Collections.Immutable not delayed!

**Known workarounds**

So far no...

**Related information**

* Operating system: Windows Server 2019 
* .NET Runtime kind: .NET Framework 4.8
* Editing Tools: Visual Studio 2019 community 16.7.2 with Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

**Comment by ingted** [comment]
same machine, newer fsi would throw exception when #r dll file. old one not

**Comment by KevinRansom** [comment]
I can repro this, will take a look.

````
c:\kevinransom\fsharp>fsi --langversion:preview

Microsoft (R) F# Interactive version 10.10.0.0 for F# 4.7
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> #r "nuget:Akkling.Cluster.Sharding,0.9.3";;
> let _=();;
[Loading C:\Users\codec\AppData\Local\Temp\nuget\18332--56d5fe23-f574-4524-9ebe-47461a803f6f\Project.fsproj.fsx]


error FS0192: internal error: internal error: Fixup: the ccu thunk for assembly System.Collections.Immutable not delayed!

> #quit;;
````

**Comment by kMutagene** [comment]
Related: https://github.com/fslaborg/Deedle/issues/508

**Comment by ingted** [comment]
Cool!!!! ^^
