### ISSUE TITLE
Build f# project with netstandard and net45 for .net core 5 preview 8

### ISSUE THREAD

**Issue by wallymathieu** [dotnet/fsharp#10040]
I'm trying to build a project that uses netstandard and net45

**Repro steps**

Provide the steps required to reproduce the problem:

1. Create a project that uses netstandard2.0 and net45
2. Use F# core version 4.6.2

**Expected behavior**

Expected the project to compile

**Actual behavior**

```
FSC : error FS0078: Unable to find the file 'netstandard.dll' in any of /Users/mathieu/.nuget/packages/microsoft.netframework.referenceassemblies.net45/1.0.0/build/.NETFramework/v4.5 /Users/mathieu/.nuget/packages/microsoft.netframework.referenceassemblies.net45/1.0.0/build/.NETFramework/v4.5/Facades /Users/mathieu/src/fs/dual-netcore-project /usr/local/share/dotnet/sdk/5.0.100-preview.8.20417.9/FSharp/ [/Users/mathieu/src/fs/dual-netcore-project/dual-netcore-project.fsproj]
```

**Related information**

Provide any related information (optional):

* Operating system: macOS Catalina 10.15.6
* .net core version 5.0.100-preview.8.20417.9, Mono JIT compiler version 6.12.0.90 (2020-02/d3daacdaa80 Thu Jul 30 16:18:06 EDT 2020)

[dual-netcore-project.zip](https://github.com/dotnet/fsharp/files/5148277/dual-netcore-project.zip)

**Comment by dsyme** [comment]
This looks like https://github.com/dotnet/fsharp/issues/10009 but is more severe beause FSharp.Core 4.6.2 is being used explicitly.

@KevinRansom this is important to fix

**Comment by cartermp** [comment]
Note that this is not the same as https://github.com/dotnet/fsharp/issues/10009#issuecomment-681019355, since that was intentionally using an FSharp.Core that only supports .NET Standard

**Comment by cartermp** [comment]
Note that I see this on my machine but do not have mono installed, so I would not expect to be able to build the netframework target that way.

**Comment by wallymathieu** [comment]
Seems to be working on the previous iteration (global.json) : 
```
{
  "sdk": {
    "version": "5.0.100-preview.7.20366.6"
  }
}
```

**Comment by KevinRansom** [comment]
This is a compiler bug, for desktop builds the compiler assumes that you are targeting a netstandard capable framework, this is a bit optimistic of us, and so I destroyed the ability to target downlevel frameworks.  I will fix this by relaxing the requirement that netstandard forwarders need to exist.

**Comment by wallymathieu** [comment]
I guess this is not released in the RC?

I get the same error (here on Windows 10):

```
FSC : error FS0078: Unable to find the file 'netstandard.dll' in any of↔ C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5↔ C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades↔ C:\Users\osge\Documents\GitHub\FSharpPlus\src\FSharpPlus↔ C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\FSharp\ [C:\Users\osge\Documents\GitHub\FSharpPlus\src\FSharpPlus\FSharpPlus.fsproj]
```

**Comment by cartermp** [comment]
No, this will likely be in RC2. The RC cutoff was 2 or more weeks ago.

**Comment by wallymathieu** [comment]
Thanks @cartermp !

**Comment by cartermp** [comment]
Specifically, our own cutoff will likely be early next week, so whichever update that rolls into will have the fix.
