### ISSUE TITLE
Enable usage of Active Patterns and Discriminated Union matching in if and if/else blocks

### ISSUE THREAD

**Issue by Horusiath** [dotnet/fsharp#10056]
**Is your feature request related to a problem? Please describe.**

At the moment Active Patterns and Discriminated Unions are allowed in several places, like `match .. with`, in variable or parameter bindings. However out of these places only `match` is safe one: others will fail with our input doesn't match the provided case.

Quite common scenario to look for is to perform safe a case/match for only one of the available cases. This is extremely common in case of options:

```fsharp
let response = getData request
match response with
| None -> ()
| Some r -> processResponse r
```

As presented above this approach is correct, however it obfuscates intent and it's quite verbose (by F# standards).

**Describe the solution you'd like**

My proposition is to enable use of pattern match bindings in scope of `if` statements and `if/else` expressions like:

```fsharp
if Some resp = getData request then
  processResponse resp

let muted = if Ok value = response then Some value else None
```

Here, the if's inner block would be executed only when the condition (returned value of `getData` being `Some`) would pass. Otherwise it would be skipped. This approach could be extended over any application of Discriminated Union or Active Pattern we use in `let` bindings today.

**Describe alternatives you've considered**

This is already doable using `match` expression. However it's more about ergonomics and expressing an intent in concise and clear way.

**Comment by cartermp** [comment]
Currently code like this runs:

```fsharp
let getData r = None

let f resp request = 
    if Some resp = getData request then
        printfn "yes"
    else
        printfn "no"

f 12 12 // no
```

But I'm not aware of a way to make active patterns usable in an `if` block as the suggestion states. Separately, there's no completeness checking involved. Saying "matching" could imply some kind of completeness checking, is that what you're after for the DU case?

Either way I think this should be filed here: https://github.com/fsharp/fslang-suggestions

A related suggestion worth considering is here as well Something like https://github.com/fsharp/fslang-suggestions/issues/705
