### ISSUE TITLE
Renamed 'master' to 'main' (broken git pull)

### ISSUE THREAD

**Issue by Nirmal4G** [dotnet/fsharp#10064]
For all those who can't pull `master`, it has renamed to `main`.

To preserve refspec to patches and branches, just changing the `heads/master` to `heads/main` should work.

```diff
[remote "origin"]
	url = https://github.com/dotnet/fsharp
-	fetch = +refs/heads/master:refs/remotes/origin/master
+	fetch = +refs/heads/main:refs/remotes/origin/master
	tagopt = --no-tags
[branch "master"]
	remote = origin
-	merge = refs/heads/master
+	merge = refs/heads/main
```

> Putting this out there, if anyone else facing similar issue with git.

**Comment by Nirmal4G** [comment]
Alternative to #9925. For those who **cannot** change the default branch for _obvious_ 😉 reasons.

**Comment by cartermp** [comment]
Thanks for the tip! I'll close this out since there isn't an action for us to take in this repo specifically, but it's great to have this documented and searchable. I'll rename the issue to be a little more of a how-to.
