### ISSUE TITLE
Create a new signed file causes VS to crash and restart.

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#10101]
Repro:
1.    Create a new F# dotnet sdk project
2.    Right mouse click on the new dialog and select the properties option on the context menu that appears
3.    Select the signing tab
4.    Select the Sign the assembly check box
5.    In the drop down below the check box, select <New...>
6.    Observe VS crash and restart.

This repros on:
    VS   16.7.3 and the latest dogfood.

**Comment by cartermp** [comment]
Is there a stack trace anywhere? Maybe a dump file will reveal something.

**Comment by dsyme** [comment]
Closing this as it seems to be fixed
