### ISSUE TITLE
Figure out up-to-date failures

### ISSUE THREAD

**Issue by brettfo** [dotnet/fsharp#10103]
I turned off the up-to-date check in #10094 because it's been flaky.  Just so we don't loose the information gathered, it seems to always be the following assemblies:

- ~~D:\a\1\s\artifacts\bin\FSharp.Compiler.UnitTests\Release\net472\CSharp_Analysis.dll~~
- ~~D:\a\1\s\artifacts\bin\FSharp.Compiler.Service.Tests\Release\net472\CSharp_Analysis.dll~~
- D:\a\1\s\artifacts\bin\FSharp.Compiler.UnitTests\Release\netcoreapp3.1\FSharp.Compiler.UnitTests.dll
- D:\a\1\s\artifacts\bin\FSharp.Compiler.Service.Tests\Release\net472\FSharp.Compiler.Service.Tests.dll
- ~~D:\a\1\s\artifacts\bin\FSharp.Compiler.UnitTests\Release\netcoreapp3.1\CSharp_Analysis.dll~~
- D:\a\1\s\artifacts\bin\FSharp.Compiler.UnitTests\Release\net472\FSharp.Compiler.UnitTests.dll

Edit: #10135 will remove the `CSharp_Analysis` project which only leaves one real culprit.

**Comment by dsyme** [comment]
😢 would love to have this check back, I don't want to suffer rebuilds again :-)
