### ISSUE TITLE
Errors on opening solution

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#10129]
I've done `git clone` and `./build.cmd` with no errors. Trying to open FSharp.sln results in errors about missing SDK.
This happens on a machine that previously could open FSharp.Compiler.Service.sln and VisualFSharp.sln fine and seem to have all requirements met.

Visual Studio (FSharp.sln):
<img width="1163" alt="Screenshot 2020-09-16 at 13 23 34" src="https://user-images.githubusercontent.com/3923587/93325681-53652180-f820-11ea-9973-116791b21729.png">

Rider (FSharp.Compiler.Service.slnf):
<img width="574" alt="Screenshot 2020-09-16 at 13 24 03" src="https://user-images.githubusercontent.com/3923587/93325760-78f22b00-f820-11ea-8918-35110a0dce73.png">

**Comment by auduchinok** [comment]
Counter-intuitively, it seems to be due to dotnet SDK version mismatch. https://github.com/dotnet/fsharp/pull/10130 Fixes it for me.

**Comment by cartermp** [comment]
This is a dupe of https://github.com/dotnet/fsharp/issues/10073

**Comment by auduchinok** [comment]
#10073 is closed, though, and this issue still remains. Either of the issues should be reopened I guess. Readme says .NET Core SDK 3 is required and I clearly have it installed.

**Comment by auduchinok** [comment]
@cartermp Should I file another issue instead, since the issue is not fixed?

**Comment by cartermp** [comment]
That's on @KevinRansom and @brettfo to resolve
