### ISSUE TITLE
Package and publish FSharp.DependencyManager.Nuget at the same cadence as FSharp.Compiler.Service

### ISSUE THREAD

**Issue by baronfel** [dotnet/fsharp#10133]
**Is your feature request related to a problem? Please describe.**

Consumers of FCS that want to provide a matching script experience (or even just typechecking!) in line with their version of FCS need to also build and consume the version of FSharp.DependencyManager.Nuget that matches their FCS. We used to publish this package from the community FCS packaging, and we need this to be restored before FSAC can begin to consume the FCS published from this repo.

**Describe the solution you'd like**
I'd like to see a version of FSharp.DependencyManager.Nuget, with the same versioning strategy as FCS, published at the same cadence as FCS.

**Describe alternatives you've considered**
Theoretically consumers could build the dll themselves, but if we wanted them to do that why are we packaging and publishing FCS?

**Additional context**
I've attempted this myself already, mirroring the setup used for FCS (the variable to specify a packagereference on FSharp.Core, adding IsPackable and a nuspec, etc) but I get compilation failures because the EmbeddedText task for the localization resources seems to register the same source twice in the build.

**Comment by baronfel** [comment]
After #10137 I'd like the FSharp.DependencyManager.Nuget in the FCS solution as well, since both are end-user distributables as well as in-box inclusions.

**Comment by baronfel** [comment]
Bumparoony on this one, it's blocking FSAC moving to packages pushed from the nightly feed/testing the whole FCS publishing process.

**Comment by cartermp** [comment]
@KevinRansom @jonsequitur ?

**Comment by KevinRansom** [comment]
Microsoft.DependencyManager.dll is compiled into FSharp.Core, I assume you are actually wanting the nuget PackageManager dll?
````FSharp.DependencyManager.Nuget.dll````

I think we should just add it to the FCS nuget package.  There really are no scenarios when we need to ship them in separate nuget packages.  The Microsoft.Dotnet.DependencyManager package, is primarily to allow us to inject the dependency manager into the notebook build.

**Comment by baronfel** [comment]
Yeah, the DLL would be ideal. I suppose it would be ok to bundle it with FCS, that would just also increase the library size for those that didn't want the handler.  It would nicely sidestep issues like @praeclarum saw when running the new FCS with no dependencymanager handlers under mono (see https://github.com/fsharp/FSharp.Compiler.Service/issues/956 for details there).

**Comment by cartermp** [comment]
doin' @KevinRansom a ping on here since he's back from vacation

**Comment by cartermp** [comment]
I think this can be closed now that FCS pulls it in as a dependency
