### ISSUE TITLE
nameof on operators still yields the compiled name on .NET 5 RC

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#10143]
With.NET 5 RC1:

```
dotnet fsi --langversion:preview
nameof (+)
  val it: "op_Addition"
```

It is the same in a compiled project.

As per the spec, this is incorrect: https://github.com/fsharp/fslang-design/blob/master/preview/FS-1003-nameof-operator.md#names-of-operators-reveal-the-name-of-the-symbol-in-source

We supposedly test this here: https://github.com/dotnet/fsharp/blob/main/tests/fsharp/core/nameof/preview/test.fsx#L241

Why no worky?

**Comment by dsyme** [comment]
Fixed in #10154
