### ISSUE TITLE
FCS solution requires install of globals.json .NET SDK version to open

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#10150]
<img width="477" alt="Screenshot 2020-09-19 at 12 47 36" src="https://user-images.githubusercontent.com/3923587/93664293-58bba980-fa76-11ea-8ee8-cfa8e725601a.png">

I can workaround it by either allowing more SDK versions (#10130) or by installing the particular SDK version from global.json. Since the latter is not required in readme/devguide, other people, especially newcomers, will likely also get hit by it. I think we should allow any suitable SDK version to be used locally to reduce developer pain.

**Comment by auduchinok** [comment]
Ah, it seems it's that specific SDK again.

**Comment by abelbraaksma** [comment]
This appears to be true now for all solutions in the F# repo, see #10193. This is quite the blocker for working with the F# solutions. How are others dealing with this, nobody using VS anymore? 

This behavior is only so since a few days/weeks afaik, what change caused this? Seeing that #10130 was canceled, I wonder how others are dealing with this.

**Comment by auduchinok** [comment]
> This is quite the blocker for working with the F# solutions. How are others dealing with this, nobody using VS anymore?

We've been using an older branch from August for the recent PRs and rebased the changes on main. The inability to use `dotnet build` is a much bigger blocker for us, since it's what Rider uses to build solution (to have reproducible builds in console/CI), and we're just waiting when we'll be able to contribute to FCS normally again.

**Comment by abelbraaksma** [comment]
@auduchinok, at least for VS I found a manageable workaround with an undocumented environment variable: https://github.com/dotnet/fsharp/issues/10193#issuecomment-699947205.

Though as of yet, I don't seem to have `dotnet build` working, nor `.dotnet\dotnet build` (using the one installed on build), at least not on my machine, but I don't know if it ever worked for me, tbh: I just use VS and/or `build.cmd`.

**Comment by cartermp** [comment]
This should now be resolved since, finally, the build machines we rely on were updated.
