### ISSUE TITLE
dotnet fsi is using implementation assemblies

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#10169]
When `dotnet fsi` is run it is using implementation assemblies, not the relevant pack of framework assemblies

There are three relevant versions involved

* SDK version, `C:\Program Files\dotnet\sdk\3.1.40` , found via the currently running tool e.g. `C:\Program Files\dotnet\sdk\3.1.401\FSharp\fsc.exe`

* Runtime version used by that SDK: `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7`, found via the directory number of the implementation assemblies

* Packs version used by that SDK: `C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0`

The problem is that we are not finding the packs version - [we are assuming that the packs version is simply the runtime version](https://github.com/dotnet/fsharp/blob/main/src/fsharp/DotNetFrameworkDependencies.fs#L68).  As a result we drop through to the [getImplementationReferences() case](https://github.com/dotnet/fsharp/blob/main/src/fsharp/DotNetFrameworkDependencies.fs#L358)

**Comment by abelbraaksma** [comment]
Could that cause mysterious type errors like this? https://github.com/dotnet/fsharp/issues/10184

**Comment by baronfel** [comment]
What's the reasoning behind closing this? I think it's relevant, and in fact we have similar issues logged in FSAC about not making this same assumption.

**Comment by KevinRansom** [comment]
It's fixed. in 16.9

**Comment by KevinRansom** [comment]
Well ... it is doing what it is supposed to do ... anyway.

**Comment by baronfel** [comment]
Oh, I see. Do you know what PR solved it (for personal inspection/edification purposes)?

**Comment by KevinRansom** [comment]
Several different PR's addressed pieces of it, but essentially:


https://github.com/dotnet/fsharp/pull/10163
and
https://github.com/dotnet/fsharp/pull/10839
