### ISSUE TITLE
'None' in debugger windows renders poorly

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#10168]
https://github.com/dotnet/fsharp/pull/10090 addressed a problem that made it so that `Some x` would not render, which is great. However, an unintended consequence was that `None` now renders funny:

![image](https://user-images.githubusercontent.com/6309070/93813965-c26bbd00-fc08-11ea-8b6a-cee19b986b4b.png)

**Comment by abelbraaksma** [comment]
To be fair, `None` never rendered properly, it displayed as `null`...

**Comment by dsyme** [comment]
Closing this as covered by #2544 - we surely need to do an F#-specific expression evaluator for this (unless we go hack a special case into the C# expression evaluator)
