### ISSUE TITLE
F# Interactive Window in warning message of VS 2019 Preview

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#10186]
It's a little surprising to see my beloved FSI being tagged by VS as having bad startup performance. This can be a genuine message, but it doesn't look well for F# if this is the first that people see:

![image](https://user-images.githubusercontent.com/16015770/94295274-47383d00-ff61-11ea-9efb-2c50635a210a.png)

It may well be hidden for most people if they have plenty of add-ins that are slower than FSI. This was seen on latest VS 2019 16.8 Preview 3.1, right after installation. The default windows in my case are Solution Expl, Team Expl, Toolbox, Properties, Search and FSI.

**Comment by cartermp** [comment]
Unfortunately there's nothing that can be done about this. FSI, along with several other windows, does impact VS startup performance and this banner is quite accurate in saying that. It's just a choice that the platform team made to notify people about this kind of stuff.

**Comment by abelbraaksma** [comment]
I figured as much, just wanted to be sure. Thanks.
