### ISSUE TITLE
fsharp.data can not upload file size bigger than 2GB

### ISSUE THREAD

**Issue by mocxi** [dotnet/fsharp#10194]
I'm trying to upload a file size 10GB.

I follow this [document](https://fsharp.github.io/FSharp.Data/library/Http.html) to handling multipart form data.

After doing some tests, I can upload ok if the file is smaller than 2GB, but the server will receive nothing if the file is bigger than 2GB.

* Operating system
* .NET Core 3.1

**Comment by cartermp** [comment]
This would be an FSharp.Data issue to file here: https://github.com/fsharp/FSharp.Data

Though I would probably pick a different library for dealing with very large file sizes like that, usually libraries that specialize in that kind of stuff handling that kind of operation better. FSharp.Data is more general purpose (and thus less suited to more specialized things)
