### ISSUE TITLE
TaskCommandLineEventArgs not used, generic BuildMessageEventArgs

### ISSUE THREAD

**Issue by dukedagmor** [dotnet/fsharp#10205]
I am currently using https://github.com/daveaglick/Buildalyzer to get the output of corecompile for a given C# / F# project. (sourcefiles and references)
For C# it checks if an TaskCommandLineEventArgs event is thrown. For F# however I had to implement my own solution that checks every BuildMessageEventArgs for the output of corecompile.

is this an F# issue or just corecompile not taking F# into account?
thanks in advance!

**Comment by cartermp** [comment]
@kevinransom any thoughts?

**Comment by dukedagmor** [comment]
@cartermp, @KevinRansom is there someone else who has knowledge about the implementation of MSBuild and F#?
Is there another forum I can try to get an answer?

Thanks in advance!

**Comment by cartermp** [comment]
@KevinRansom is _the_ person for this topic (much to his chagrin 😄 )

**Comment by dukedagmor** [comment]
is this something for the F# backlog or will this remain open till someone with the desired knowledge takes a look at it?

**Comment by cartermp** [comment]
Yep, the policy is to leave them open unless there's information indicating they should be closed.

**Comment by KevinRansom** [comment]
Recently checked in a fix
