### ISSUE TITLE
No need to type check implementation files when an .fsi file exists

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#10201]
Will has the details, and can fill this out more.  There is a tremendous peformance gain when we don't typecheck implementation files that are not open.

**Comment by abelbraaksma** [comment]
This would help sooooo much in large projects wrt tooling perf, and would be an extra benefit for adding fsi files (I usually don't).

**Comment by smoothdeveloper** [comment]
Waiting for this optimization to land before opening again TypeChecker.fs 😄.

**Comment by heronbpv** [comment]
> This would help sooooo much in large projects wrt tooling perf, and would be an extra benefit for adding fsi files (I usually don't).

This. Never saw any reason to make a .fsi file, until now. Always seemed like redundant work.

**Comment by KevinRansom** [comment]
@heronbpv, I'm with you, I don't like them when creating apps, however, if you are creating libraries for public consumption, they are very useful for controlling the visibility of the types and functions in the libraries.
