### ISSUE TITLE
 System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Core, Version=5.0.0.0

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#10215]
Targeting `netstandard2.0` in a multi-targeted project in VS 2019 Preview compiles fine but gives a runtime _"FileNotFoundException: FSharp.Core.dll"_ when running.

**Repro steps**

1. Start a .NET Core 3.1 project
2. Add some non-trivial code that uses FSharp.Core at least
3. Change the `fsproj` file to include the TFM `netstandard2.0`. Notice the NS SDK added.
4. Restart VS (or reload the whole sln)
5. Compile & run

![image](https://user-images.githubusercontent.com/16015770/94993934-a961f500-0594-11eb-8e51-2e9fe0cb7567.png)

**Expected behavior**

A successful compile should, preferably, lead to a successful run.

**Actual behavior**

The following error is shown in the console window:

> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Core, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Known workarounds**

None yet, but I expect to find a way.

**Related information**

Currently seen on: Visual Studio 2019, 16.8.0 Preview 3.1.

Will attach project file once I've limited the code such that it's a simple repo.

**Comment by KevinRansom** [comment]
So you've multi-targetted net472;net50;netcoreapp3.1;netstandard20 is that correct?

**Comment by abelbraaksma** [comment]
Yep, that's indeed correct.

**Comment by cartermp** [comment]
This shouldn't be an illegal combination in practice, no. But such a combination is likely to be extremely rare.

**Comment by cartermp** [comment]
I don't reproduce this with the internal VS 16.9 builds. This is my output log:

```
Rebuild started...
1>------ Rebuild All started: Project: ConsoleApp24, Configuration: Debug Any CPU ------
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>ConsoleApp24 -> C:\Users\phcart\source\repos\ConsoleApp24\ConsoleApp24\bin\Debug\netstandard2.0\ConsoleApp24.dll
1>ConsoleApp24 -> C:\Users\phcart\source\repos\ConsoleApp24\ConsoleApp24\bin\Debug\net472\ConsoleApp24.exe
1>ConsoleApp24 -> C:\Users\phcart\source\repos\ConsoleApp24\ConsoleApp24\bin\Debug\net5.0\ConsoleApp24.dll
1>ConsoleApp24 -> C:\Users\phcart\source\repos\ConsoleApp24\ConsoleApp24\bin\Debug\netcoreapp3.1\ConsoleApp24.dll
1>ConsoleApp24 -> C:\Users\phcart\source\repos\ConsoleApp24\ConsoleApp24\bin\Debug\netstandard2.1\ConsoleApp24.dll
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

The F# toolset in this build is the same as the latest insertion we did for VS 16.8 preview (unclear if that same toolset is what is in Preview 3.1 or Preview 4).

**Comment by KevinRansom** [comment]
I see it:
@cartermp you have to run the netstandard2.0 version of the project.

````

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Core, Version=4.7.0.0, Cul
ture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Program.main(String[] argv)

C:\Users\codec\source\repos\ConsoleApp31\ConsoleApp31\bin\Debug\netstandard2.0\ConsoleApp31.dll (process 3348) exited wi
th code -532462766.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the conso
le when debugging stops.
Press any key to close this window . . .
````
I don't really think it's supposed to work.  It wouldn't have occured to me that someone would try to execute a netstandard app.  Since the build does not generate a ````.deps.json```` and ```runtimeconfig.json````

I will dig in a bit, but my expectation is this is by design.

**Comment by KevinRansom** [comment]
@abelbraaksma , I am afraid this is by design.  Possibly it can be considered a bug in the DotNet sdk.

For coreclr targets:
- netcoreapp2.1 thru net5.
  The net sdk builds a deps.json, which tells the coreclr where to resolve dependent libraries from.
-net4.5 thru net48
  The net sdk build an bin directory with all of the build dependencies contained in it.
-- netstandard2.0
  The dotnet sdk does not build a deps.json file, and does not copy the dependent assemblies.

Even if the netsdk created a deps.json file the debugger starts the netstandard2.0 app with the desktop framework, and that knows nothing about deps.json anyway, so it needs the dependencies copied.

The work around for netstandard2.0, is simply to use the net48 target anyway, and given the debugger doesn't do the right thing and start it as a net coreapp, I doubt if there is any apetite to make any changes.

So I'm going to go with this won't be fixed.

@wli3 , do you have any thoughts?

**Comment by abelbraaksma** [comment]
@KevinRansom, thanks for the analysis. Tbh, I never used "netstandard2.0" TFM before, and since it's listed as accepted TFM in the VS docs, I assumed it would "just work". It's a little surprising it doesn't, but your rundown makes sense: that it's effectively a NET Core app (though, iirc, it could be run with any other compatible .NET Framework).

**Comment by abelbraaksma** [comment]
> The dotnet sdk does not build a deps.json file, and does not copy the dependent assemblies.

I did notice the sdk being linked in VS, which lulled me into thinking this was "how it's supposed to work". It also shows the dependencies in the tree view, as can be seen in the screenshot. But perhaps they're there from the deps.json that was created for the other project TFM's.

**Comment by KevinRansom** [comment]
@abelbraaksma , It builds the dll fine, it just doesn't prepare it for execution.  I think the developers had the idea that it was for libraries rather than applications, and therefore didn't need to built with the dependencies for execution.  I can't say I disagree.

**Comment by cartermp** [comment]
Yes, there is no support for .NET Standard for unit test projects. Just noticed the icon for this being a unit test.

**Comment by abelbraaksma** [comment]
> that it was for libraries rather than applications, and therefore didn't need to built with the dependencies for execution. I can't say I disagree.

That makes sense (though I would expect a different error then, like when you try to run a classical dll, but that's another discussion).

**Comment by abelbraaksma** [comment]
@cartermp, I'll close this, the comments from @kevinransom clarified it. Can you remove "needs repro"?
