### ISSUE TITLE
fsc.exe - Parallel Type-Checking of implementation files if signature files exist

### ISSUE THREAD

**Issue by TIHan** [dotnet/fsharp#10214]
Building on the ideas of https://github.com/dotnet/fsharp/issues/10201 - there might be a way we can do parallel type-checking for implementation files that have backing signature files. This requires a bit more research to see if this is possible, but in theory it should be.

The compiler would do a pass at type-checking all files minus the implementation files that have a corresponding signature file. After that pass completes, then we type-check those implementation files and continue.

**Comment by cartermp** [comment]
https://github.com/dotnet/fsharp/pull/11152 implements this

**Comment by T-Gro** [comment]
This has been done.
