### ISSUE TITLE
Internal reactor queue blocks further type-checking of currently type-checked file

### ISSUE THREAD

**Issue by TIHan** [dotnet/fsharp#10211]
Whenever we save a file, incremental builder picks up on the file change and invalidates all files that depend on it, and potentially it will invalidate other incremental builds(projects).  An IDE may request analysis on the files that depended on the one that was changed; this blocks the reactor queue from processing anything until all the requests for analyses have been finished. The result is that the tooling stops being functional in the file that you currently saved and are editing, even though the information exists.

- [x] Make incremental builder cache be accessed on any thread https://github.com/dotnet/fsharp/pull/10292
- [x] Make data structures, such as `Dictionary`, be `ConcurrentDictionary` in parts of the compiler. https://github.com/dotnet/fsharp/pull/10308
- [x] Lock type provider calls to be single-threaded (no parallel TP calls). https://github.com/dotnet/fsharp/pull/10310
- [x] Start removing requirements of reactor-queue for data that exists. https://github.com/dotnet/fsharp/pull/10292

As part of 10292 we will do all of these:

* [x] All of the FSharpCheckFileResults operations will no longer use the Reactor and hence no longer by async.  
* [x] The four operations `Get*UsesOfAllSymbolsIn*`  were only async to support cancellation. For clarity these will no no longer by async and instead accept an optional cancellation token
* [x] `userOpName` is removed from all the operations which are no longer async (it is there for async causality tracing)
* [x] `StructuredDescriptionTextAsync` and `DescriptionTextAsync` no longer used the Reactor thread. They are marked as obsolete, and instead synchronous `StructuredDescriptionText` and `DescriptionText` should be used
* [x] The caches `scriptClosureCache` and `incrementalBuildersCache` are now usable from any thread
* [x] The optional argument `hasTextChangedSinceLastTypecheck` is removed from FSharpChecker API as it no longer needed by Visual F# Tools since 2017 rewrite 
* [x] The optional argument `textSnapshotInfo` is removed from FSharpChecker API as it only existed to pass back to `hasTextChangedSinceLastTypecheck`

**Comment by auduchinok** [comment]
Seems to be related to https://github.com/dotnet/fsharp/issues/4537.

**Comment by dsyme** [comment]
@auduchinok  @saul I've added notes about the further work to remove the reliance on the reactor in #10292 , will also copy them over there.  This leads to API changes in FCS, see the notes.

**Comment by auduchinok** [comment]
@dsyme This is fantastic news, I'm looking forward to seeing how it works!
