### ISSUE TITLE
Inconsistent name resolution for delegate constructor

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#10228]
Delegate type declaration doesn't seem to shadow existing types, unlike other declarations.

In the example below `Delegate` type is expected to shadow `System.Delegate`.
```fsharp
open System

type Delegate = delegate of int -> int
Delegate(fun _ -> 1)

type Delegate1 = delegate of int -> int
Delegate1(fun _ -> 1)
```
`Delegate` is resolved to `System.Delegate` instead, producing an error about no accessible constructors (note `UnusedOpens` doesn't seem to account it):
<img width="371" alt="Screenshot 2020-10-06 at 22 32 13" src="https://user-images.githubusercontent.com/3923587/95251228-eabc0400-0823-11eb-87e5-37d482ed03dc.png">

Removing `open` helps (but should not have any effect):
<img width="380" alt="Screenshot 2020-10-06 at 22 32 25" src="https://user-images.githubusercontent.com/3923587/95251247-ef80b800-0823-11eb-8359-d3bed83127f1.png">

Adding `new` also helps:
<img width="393" alt="Screenshot 2020-10-06 at 22 32 36" src="https://user-images.githubusercontent.com/3923587/95251255-f3143f00-0823-11eb-808a-2f75abcc5be2.png">

**Comment by TIHan** [comment]
Certainly seems like a bug to me. I agree that it should be shadowing.
