### ISSUE TITLE
FSharp unexpected loads

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#10226]
Ryan Molden from the VS Team took a deeper look, at the  unexpected, F# loads and provided this analysis.  There are a bunch of things for us to do.  The bug numbers are internal devdiv bugs, I will port them to this repo at some point.

---

I have analyzed some FSharp loaded unexpectedly scenarios and they seem to break into a few broad categories:

1)	Load in order to get resource, which is then cached preventing similar loads in future sessions.
a.	Tools->Options
b.	New Project Dialog
c.	New File Dialog
2)	Load in order to get resource which is NOT cached, continuing the same load in every subsequent session that repeats the action
a.	About Box
3)	MEF - MEF loads
a.	MEF loads to extract metadata that is cached preventing similar loads in future sessions
i.	Fonts and Colors information
b.	MEF loads due to the MEF cache being stale/missing (normally after an update / fresh install)
i.	FSharp.ProjectSystem.Base.ni.dll - 1,763,840
ii.	FSharp.Editor.dll 1,257,864
iii.	FSharp.Core.ni.dll - 9,541,120
iv.	FSharp.Compiler.Private.dll (17,134,984 IL / 55 megs NI)
v.	FSharp.VS.FSI.ni.dll - 555,008
vi.	FSharp.PatternMatcher.dll - 78,728
vii.	FSharp.UIResources.ni.dll - 85,504

Proposed solutions:

For class 1 the only solution is to make the loading session a non-productive sessions, i.e. move the loading to make cache resident into something like /updateConfiguration, which runs and exits, as opposed to the first time the dialogs are shown (which tend to happen in ‘real use’ sessions and thus trigger the loads + the dll sticking around for the entire session. @Ashok Kamath, who owns the dialogs in questions? I suspect @Jeff Kelly’s team owns the Tools Options dialog, do they also own the general infrastructure for the new Project/File dialogs? Or is that @Michael Eng’s team?

Leaving aside a possible bug discussed above (about making /updateConfiguration do more of the caching work) I have created 7 bugs :

-	1226054 Assigned to the editor to try and be a bit more parsimonious with their loads since this case seems to be getting an F&C entry that won’t be used (as the editor in question is the output window pane for the Git provider)

-	1226051 On the Git team because force creating a Output window pane (and its associated editor + all the other stuff) on startup just to write a single line of text is kind of obnoxious

-	1226058 On the FSharp team to consider refactoring their MEF exports. For one having a MEF export in a FSharp.Compiler.Private seems like a very bad idea given its size. Mapping that dll in for the entirety of a session is really bad if it can be avoided. But more generally if you had a small stub ‘MEF exports’ dll that could possibly proffer your exports in a way that didn’t require loading the 7 dlls listed above, that would be FAR more ideal

-	1226060 On the FSharp team to consider combining all of their resources into a single UI resource dll (like the one your apparently already have) so that if we need to fetch a resource to populate a cache we only need to load 1, small dll, not numerous, much larger dlls.

-	1226059 On the FSharp team to stop NGENing their UI resource dll (I doubt this gains anything and likely makes the image 57% larger)

-	1226064 On my plate, because it’s an easy fix with no SME knowledge required, to make the About Box use the caching resource manager

-	1226065 On the FSharp team to stop using the app domain assembly resolver to resolve FSharp.PatternMatcher.dll

Ryan

**Comment by cartermp** [comment]
Closing this out as @TIHan addressed the root of the problem and this is done in 16.9.
