### ISSUE TITLE
Build on FSharp.Compiler.Service

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#10223]
So ... 

- VS/FSI/FSC build on FSharp.Compiler.Private
- Dotnet interactive builds On FSharp.Compiler.Private.Scripting / FSharp.Compiler.Private

We have no intention of publishing FSharp.Compiler.Private.Scripting publically, and want to move away FSharp.Compiler.Private.dll

We want to rework the dependencies so that F# builds on FCS.

**Comment by KevinRansom** [comment]
Todo:
- FCS, should build net472 version of the FSharp.Compiler.Service, will not add it to the package
- Add back to FCS the missing FSharp.Compiler.Private APIs
- Replace FSharp.Compiler.Private with FSharp.Compiler.Service everywhere
- Re-align FSharp.Compiler.Private.Scripting APIs with FSharp.CompilerService scripting APIS
- Remove FSharp.Compiler.Private.Scripting and FSharp.Compiler.Service

Cheer

**Comment by cartermp** [comment]
So pumped for this.

**Comment by cartermp** [comment]
Closing as completed
