### ISSUE TITLE
New magic in "New project" in VS Preview, adding reference to non-existing, yet downloadable FSharp.Core/5.0.0-beta.20504.3

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#10232]
This is more of a question than a bug. After this (https://github.com/dotnet/fsharp/issues/10231), I managed to add a new F# .NET Core 3.1 project to a solution and found that the `FSharp.Core` reference showed an exclamation mark. Curious as I am, I checked the version and the `json` config and found that it referenced `FSharp.Core/5.0.0-beta.20504.3`, and had `"fileVersion": "5.0.20.50403`.

The _build date_ or _sign date_ was yesterday (Oct 5, 2020).

![image](https://user-images.githubusercontent.com/16015770/95259745-f3163e00-0827-11eb-920b-1990a079e42d.png)

![image](https://user-images.githubusercontent.com/16015770/95260016-543e1180-0828-11eb-9515-f3f8d22523bf.png)

How/where does VS find this, is this _on purpose/by design_, why is there an excl. mark (the file is signed)?

**Repro steps**

In VS 2019 16.8 Preview 3.1, add a new F# .NET Core project.

**Expected behavior**

Well, I _expected_ one of the publicly available releases, including the pre-releases, but as of this writing, the latest is [FSharp.Core/5.0.0-beta.20417.1](https://www.nuget.org/packages/FSharp.Core/5.0.0-beta.20417.1).

**Actual behavior**

The latest build (I think)? I'm actually happily surprised, don't get me wrong, but I'm not sure this is on purpose. I couldn't even figure out where this NuGet source is located. My listed NuGet sources under Options just list the official one.

**Related information**

It's possible that at some point I may have altered with certain system or preview-edition settings to make development of the F# compiler easier, but I do not recall how or what I did and cannot readily find a setting that causes this. Just as well, this is a new feature of the VS Preview release and it somehow knows to go to a different NuGet source. 

The source of the generated `json` file:

```json
{
  "runtimeTarget": {
    "name": ".NETCoreApp,Version=v3.1",
    "signature": ""
  },
  "compilationOptions": {},
  "targets": {
    ".NETCoreApp,Version=v3.1": {
      "TestProject/1.0.0": {
        "dependencies": {
          "FSharp.Core": "5.0.0-beta.20504.3"
        },
        "runtime": {
          "TestProject.dll": {}
        }
      },
      "FSharp.Core/5.0.0-beta.20504.3": {
        "runtime": {
          "lib/netstandard2.0/FSharp.Core.dll": {
            "assemblyVersion": "5.0.0.0",
            "fileVersion": "5.0.20.50403"
          }
        },
        "resources": {
          "lib/netstandard2.0/cs/FSharp.Core.resources.dll": {
            "locale": "cs"
          },
          "lib/netstandard2.0/de/FSharp.Core.resources.dll": {
            "locale": "de"
          },
          "lib/netstandard2.0/es/FSharp.Core.resources.dll": {
            "locale": "es"
          },
          "lib/netstandard2.0/fr/FSharp.Core.resources.dll": {
            "locale": "fr"
          },
          "lib/netstandard2.0/it/FSharp.Core.resources.dll": {
            "locale": "it"
          },
          "lib/netstandard2.0/ja/FSharp.Core.resources.dll": {
            "locale": "ja"
          },
          "lib/netstandard2.0/ko/FSharp.Core.resources.dll": {
            "locale": "ko"
          },
          "lib/netstandard2.0/pl/FSharp.Core.resources.dll": {
            "locale": "pl"
          },
          "lib/netstandard2.0/pt-BR/FSharp.Core.resources.dll": {
            "locale": "pt-BR"
          },
          "lib/netstandard2.0/ru/FSharp.Core.resources.dll": {
            "locale": "ru"
          },
          "lib/netstandard2.0/tr/FSharp.Core.resources.dll": {
            "locale": "tr"
          },
          "lib/netstandard2.0/zh-Hans/FSharp.Core.resources.dll": {
            "locale": "zh-Hans"
          },
          "lib/netstandard2.0/zh-Hant/FSharp.Core.resources.dll": {
            "locale": "zh-Hant"
          }
        }
      }
    }
  },
  "libraries": {
    "TestProject/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    },
    "FSharp.Core/5.0.0-beta.20504.3": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-9kvpFVOCb9cLSm6ihNLb+LRz9YOQpEsrWwzSSCLGEYEzbXZACcjLhJadueGdKZAYZe7fULpnOPZGA0rDA6DUvw==",
      "path": "fsharp.core/5.0.0-beta.20504.3",
      "hashPath": "fsharp.core.5.0.0-beta.20504.3.nupkg.sha512"
    }
  }
}
```

**Comment by cartermp** [comment]
I think this is just a point-in-time thing with the current latest preview. The built FSharp.Core deployed with VS happens to just be ahead of NuGet. This is due to the .NET SDK, NuGet, and VS all having orthogonal release schedules.

**Comment by abelbraaksma** [comment]
@cartermp Ok... Buuut, this doesn't match any release under "releases" (the ones in github, I mean). And Preview 3.1 is several weeks old (I installed it a while ago), I didn't install any sdk since (afaik), yet the FSharp.Core reference is from yesterday. How's that even possible?

I can certainly see this as a feature, but I do like to know how to control this. Esp since it doesn't match up with any release that I could find, not even a nightly build (I think), so I'm wondering how this works. 

(and the exclamation mark is weird too)

**Comment by cartermp** [comment]
Dunno. Likely some restore from our internal feed? I also do not see the yellow triagle on the latest preview. So I don't suspect a real issue here other than some point-in-time weirdness.

**Comment by TIHan** [comment]
I'm having this problem as well. It's basically made the preview unusable.

**Comment by TIHan** [comment]
@abelbraaksma I found a weird solution to it. If you try to update the package to use the correct version, and then remove the package entry in the project file, it will now work. Very weird.

**Comment by KevinRansom** [comment]
@abelbraaksma , It is on purpose and yes there is msbuild magic going on.  I don't know why you get the yellow exclamation mark.  I don't see that with my build.

![image](https://user-images.githubusercontent.com/5175830/95508097-52c73300-0967-11eb-9ebe-6a3d61be68e3.png)

Preview builds of FSharp Projects now use the latest preview build of FSharp.Core ... from the latest signed build of the Dev18 branch.

If you want to reset back to the RTM FSharp.Core add this to your project file.
````
<PropertyGroup>
   <DisableFSharpCorePreviewCheck>true</DisableFSharpCorePreviewCheck>
</PropertyGroup>
````

The source is specified:  
https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSharp.Build/Microsoft.FSharp.NetSdk.targets#L57

**Comment by KevinRansom** [comment]
There have been circumstances where the design time build doesn't fire off.  Which version of the preview, is it the one on visualstudio.com?

**Comment by KevinRansom** [comment]
@abelbraaksma ,
I'm pretty sure that this happens because of this issue:
https://github.com/NuGet/Home/issues/10005

and It is fixed in more recent builds.  I imagine I don't see this because I have a more recent net sdk.

I will just try to confirm this.

**Comment by KevinRansom** [comment]
@abelbraaksma, 

I just installed VS Preview 2 from VisualStudio.com on a clean sandbox, and created a new project, with no yellow triangle.

![image](https://user-images.githubusercontent.com/5175830/95514861-8ad37380-0971-11eb-910b-b3c2dd3e1286.png)

The version of the dotnet sdk installed is:  C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10

What happens if you open a console window at the directory containing the project and type dotnet restore?

Thanks

Kevin

**Comment by abelbraaksma** [comment]
> Preview builds of FSharp Projects now use the latest preview build of FSharp.Core ... from the latest signed build of the Dev18 branch.

That's what I would expect, but the latest public preview build (to be found in nuget, or in the sdk downloaded with VS preview), this file isn't there. 

The version in your screenshot is even newer than mine(!) 

So we're really linking a **nightly build**, not a public **preview build**. This difference is important for reporting and reproducing bugs. It's a petty there's no public location where all these versions are (again, mainly needed for research or repro of bugs). You showed me how to disable this behavior, I'll try that when I'm back behind my desk, same for trying to restore. Tx!

**Comment by abelbraaksma** [comment]
We should probably update the instructions in devguide.md. With this feature in place, it's easier for people to use latest FSharp.Core.dll (though the instructions for nightly of VS tooling needs to remain, I think).

**Comment by abelbraaksma** [comment]
> `<DisableFSharpCorePreviewCheck>true</DisableFSharpCorePreviewCheck>`

The name of this tag is confusing, though, since it isn't really the preview version anymore (which I take as centrally shipped with the rest of the VS Preview and sdk), but the absolute latest build of the main/vX.Y branch.

**Comment by KevinRansom** [comment]
No it is preview.  This turns off the "Am I a preview" build logic.  Dotnet SDK preview builds ship with a flag that says they are previews.

If the F# compiler is shipped in a preview it returns :  **{{FSCorePackageVersion}}** 
Set here:  https://github.com/dotnet/fsharp/blob/release/dev16.8/eng/Versions.props#L15
**5.0.0**

If the compiler is not a preview then it uses:  **{{FSharpCorePreviewPackageVersion}}**
Set here:  https://github.com/dotnet/fsharp/blob/release/dev16.8/eng/Versions.props#L35
**5.0.0-beta-some date thingy**

If the compiler is in a preview sdk and a developer sets that flag then it sets the version to: **{{FSharpCoreShippedPackageVersion}}**
Set here:  https://github.com/dotnet/fsharp/blob/release/dev16.8/eng/Versions.props#L33
**4.7.2**

The goal was to use 5.0.0 in RTM builds, 5.0.0-beta-something in previews, and give developers the ability to toggle back to the rtm shipped FSharp.Core 4.7.2 when developing with preview SDKs.

My head exploded when trying to figure this stuff out.  But I am relatively satisfied with where we landed.

Kevin

**Comment by abelbraaksma** [comment]
@KevinRansom That clears up a lot more, that's valuable documentation. But still doesn't explain why "I am preview" causes VS to download latest build, and not the preview version in the nuget feed, which also exists.

Now each new project (in VS Preview) will have a new version of FSharp.Core each day, as your screenshot also showed. 

I can understand that this is designed this way and has its merits, but it just means that people have to very aware of this, as you may run into conflicts if you create several dependent projects over several days in this preview mode. 

But from what you explain, it seems to me you suggest this isn't meant to get **latest nightly** (it does, or something very similar to that), but that this is meant to get latest preview from whatever you've configured as your nuget feed (in my case, the public feed). That is **not** how it currently works (check the creation or sign date of your FSharp.Core from your screenshot and compare with mine, they're both **newer** then 16.8 Preview 3.1, or any sdk or public nuget package).

**Comment by abelbraaksma** [comment]
> If the compiler is a preview then it uses: {{FSharpCorePreviewPackageVersion}}
> Set here: > https://github.com/dotnet/fsharp/blob/release/dev16.8/eng/Versions.props#L35
> 5.0.0-beta-*

Basically, this is the scenario we're talking about. I'm still confused whether what's intended here is in line with what I reported. I think there are basically two choices: latest beta on nuget (it's published there, I checked, it's like a month old), or latest build from github (which is what seems to happen now, what I had, and you had, was a day old).

Also, curious what feed it uses here. Maybe this is a VS thing that bypasses the default config of the nuget feed?

**Comment by KevinRansom** [comment]
The intent is to get the latest preview FSharp.Core from the feed, but they may well not be the right choice.  I went back and forth on whether to pin it to a specific version or to do a nuget wild card load.  It is true that we will cause an FSharp.Core package to be downloaded every day, which suggests that we should in fact pin it to a specific version.

@brettfo question 4 ya mate:  Do the nuget packages in the coreclr feed get cleaned up?  If we were to load a fixed version rather than a wild card version would older FSharp.Core nuget packages get deleted from that feed?

@abelbraaksma , if you was forced to make a call, which way do you think would be more useful for you, wild card selection so you always get the latest FSharp.Core, or pin it so you get a specific FSharp.Core package.

It should be noted, that nuget and the build should cope fine with many versions of the FSharp.Core package.  The main disadvantage, is that the more you use the preview, the more fsharp.core packages you download?

It should be further noted that a developer can always control using PackageReference update= the specific version they require.

No feed bypassing is in operation, nuget just picks the version with the highest version number.  You shouldn't use the version on nuget in the preview, it is only there, because we didn't have a way for preview users to use FSharp 5  features when using VS2019.8 preview 1, because we didn't have the automagic wired up.

Kevin

**Comment by KevinRansom** [comment]
When the dotnet sdk is in preview we always add the nuget source: 

````https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json````

here:  https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSharp.Build/Microsoft.FSharp.NetSdk.targets#L57

This means you will always get the latest built preview of FSharp.Core package unless you add this to your project file:
````
<PackageReference Update="FSharp.Core" Version="5.0.0-beta-20508.1" />
````
As I said, I am quite easily persuadable for us to pin the version, I expect we can still make that work, and that would stop the frequent nuget downloads which I didn't really consider, especially since I have a pretty great connection, but I will need to confirm the packages won't get deleted arbitrarily.

Kevin

**Comment by brettfo** [comment]
@KevinRansom the coreclr feeds never get cleaned up.

**Comment by cartermp** [comment]
This was an artifact of preview stuff that's long since been addressed.
