### ISSUE TITLE
Adding more functor, monad, and applicatable functions to base types

### ISSUE THREAD

**Issue by ZergRushJoe** [dotnet/fsharp#10266]
**Is your feature request related to a problem? Please describe.**
Add monadic functions to async, result, and option

**Describe the solution you'd like**
Async, result, and option to have a new member to support map, bind and apply

**Describe alternatives you've considered**
I built them myself

**Additional context**
why don't they have it already?
![image](https://user-images.githubusercontent.com/7153267/96299030-660a7c00-0fc1-11eb-9bc4-202c18f3c51d.png)
example of what I'm looking for. I will do a pr for this if needed

**Comment by cartermp** [comment]
Additions to the F# core library are handled in the design repo here: https://github.com/fsharp/fslang-suggestions

If you'd like, please do file a suggestion if you can't find one that maps to this one. We'd like to have people discuss the ramifications of inclusion in the core library there. We are typically quite conservative on what we include.
