### ISSUE TITLE
InvalidProgramException when attempting to set C# 9 init-only properties

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/fsharp#10261]
**Repro steps**

Given a net5.0 C# class library:

```csharp
namespace ClassLibrary1
{
    public class CSharpClass
    {
        public int X { get; init; }
    }
}
```

and a net5.0 F# console app consuming it

```fsharp
open ClassLibrary1

[<EntryPoint>]
let main argv =
    let _ = CSharpClass(X = 42);
    0
```

**Expected behavior**

The program should execute successfully or fail at compile time.

**Actual behavior**

Program crashes with InvalidProgramException.

**Known workarounds**

None known.

**Addition Information**

Attaching the [reproducing solution](https://github.com/dotnet/fsharp/files/5388081/ConsoleApp3.zip).

SDK version: `5.0.100-rc.1.20452.10`

### C# Codegen

```csharp
public static CSharpClass Test() => new CSharpClass { X = 42 };

//IL_0000: newobj instance void ClassLibrary1.CSharpClass::.ctor()
//IL_0005: dup
//IL_0006: ldc.i4.s 42
//IL_0008: callvirt instance void modreq([System.Runtime] System.Runtime.CompilerServices.IsExternalInit) ClassLibrary1.CSharpClass::set_X(int32)
//IL_000d: nop
//IL_000e: ret
```

### F# Codegen

```fsharp
let test () = CSharpClass(X = 42)

//IL_0000: newobj instance void [ClassLibrary1]ClassLibrary1.CSharpClass::.ctor()
//IL_0005: stloc.0
//IL_0006: ldloc.0
//IL_0007: ldc.i4.s 42
//IL_0009: callvirt instance void modreq([System.Runtime]System.Runtime.CompilerServices.IsExternalInit) [ClassLibrary1]ClassLibrary1.CSharpClass::set_X(int32)
//IL_000e: pop
//IL_000f: ldloc.0
//IL_0010: ret
```

**Comment by abelbraaksma** [comment]
I wonder is this is in part because the compiler is not yet built as .NET 5, since the `IsExternalInit` wasn't available before then: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.isexternalinit?view=net-5.0.

I mean, we'll need a way to recognize that attribute, possibly without committing the whole compiler to change to .NET 5 (we currently have a netfx and netcore build).

**Comment by cartermp** [comment]
This is tracked here: https://github.com/fsharp/fslang-suggestions/issues/904

Will likely have a chat with @dsyme about the next steps to handle new interop-y features from .NET 5 now that core language work has settled.
