### ISSUE TITLE
Colorization of names in VS 2019

### ISSUE THREAD

**Issue by jimfoye** [dotnet/fsharp#10271]
I now have a weird colorization issue in 16.7.6, I believe this started a couple of versions ago, but I'm not sure when exactly. It happens in all my VS instances (W7 and W10). Here are some screenshots. Here 'pool', 'socket', 'msg', and 'server' are all getting colorized incorrectly. But elsewhere in these files the names are colorized as expected.

![image](https://user-images.githubusercontent.com/4249676/96376032-3d5dc000-1142-11eb-9d37-45883e4eddd6.png)

![image](https://user-images.githubusercontent.com/4249676/96376177-f3c1a500-1142-11eb-8d06-482f8d604bb6.png)

![image](https://user-images.githubusercontent.com/4249676/96376203-24a1da00-1143-11eb-9740-59ca017df84d.png)

![image](https://user-images.githubusercontent.com/4249676/96376058-68e0aa80-1142-11eb-8f2d-084c9b19de28.png)

But, I do not see this in Rider (either Windows or Linux).

(Note: I previously reported this at https://developercommunity.visualstudio.com/content/problem/1216972/f-sometimes-colorizes-names-like-types.html)

**Comment by cartermp** [comment]
Can you see if this is the same in VS 16.8 preview? A series of fixes for various coloring and coloring settings quirks are queued up for VS 16.8.

**Comment by jimfoye** [comment]
Seems to be fixed in 16.8 preview, thanks. And now I think I see the pattern on this - disposable types.

BTW I had a dream last night that one day you guys will put a search or autocomplete in the Fonts and Colors page. Even better, if we could point to some text and have Visual Studio tell us what that text is considered for colorization purposes...but I'd search for autocomplete on the DisplayItems list for now.

**Comment by cartermp** [comment]
Yep, it was the disposable colorization. We now distinguish between disposable values and non-disposable values, but backed off on the default different colorization for now.

> BTW I had a dream last night that one day you guys will put a search or autocomplete in the Fonts and Colors page

That would be nice, I agree. Unfortunately it's one of the oldest and most complex parts of Visual Studio and so I kind of have doubts that it would be done without a revamp of the entire options system.

**Comment by cartermp** [comment]
I'll close this as resolved for 16.8
