### ISSUE TITLE
outref and byref with OutAttribute in SRTPs 

### ISSUE THREAD

**Issue by habib-sadullaev** [dotnet/fsharp#10286]
I get `runtime error FS0193` and `compile error FS0001` when using `'a outref`  and `[<Out>] 'a byref` in `SRTP`s 

**Repro steps**

```fsharp
open System.Runtime.InteropServices

type C1() = static member M([<Out>] arg: C1 byref) = arg <- C1(); true
type C2() = static member M(arg: C2 outref) = arg <- C2(); true

let inline getByRef<'a when 'a: (static member M: 'a byref -> bool)> () =
    let mutable res = Unchecked.defaultof<_>
    if (^a: (static member M: ^a byref -> bool) &res) then Some res else None

let inline getOutRef<'a when 'a: (static member M: 'a outref -> bool)> () =
    let mutable res = Unchecked.defaultof<_>
    if (^a: (static member M: ^a outref -> bool) &res) then Some res else None

getByRef<C1>() //works
getByRef<C2>() //runtime error FS0193: internal error: Cannot get TypeToken for a ByRef type.

getOutRef<C1>() //compile error FS0001: Type constraint mismatch. The type 'outref<C1>' is not compatible with type 'byref<C1>'
getOutRef<C2>() //runtime error FS0193: internal error: Cannot get TypeToken for a ByRef type.

//works
match C1.M() with
| true, value -> Some value
| false, _ -> None

//works
match C2.M() with
| true, value -> Some value
| false, _ -> None
```

**Expected behavior**

compiles and runs without any issues
I'm not sure about following:

- `getByRef<C2>()` - should we expect compile error in this case?
- `getOutRef<C1>()` - is compile error in this case correct?

**Actual behavior**

compiles and runs with errors

**Known workarounds**

None

[fsharp-byref-compiler-issue.zip](https://github.com/dotnet/fsharp/files/5407163/fsharp-byref-compiler-issue.zip)

**Comment by habib-sadullaev** [comment]
@cartermp but it's not simple `byref`, this arg has `Out` attribute, So `[<Out>] 'a byref` is not identical to `outref`?

**Comment by cartermp** [comment]
No, they aren't the same thing. `outref` is functionally equivalent to a `byref` (aside from this mini type heirarchy between byref kinds), but it is not the same as the `Out` attribute that you could apply before these concepts existed in F# (or C#).

**Comment by TIHan** [comment]
`getByRef<C2>()` and `getOutRef<C2>()` are bugs. Looks like the code gen isn't doing the proper thing here, but interesting that it only happens on `outref<'T>`. 

My suspicion is the 2 types of byrefs: `byref<'T>` and `byref<'T, 'ByRefKind>`. Compiler has special knowledge of these byref types to make them equivalent, but we can still make distinctions between them; which might be why they have different behavior in this case.

**Comment by vzarytovskii** [comment]
So, right now the following code

```fsharp
open System.Runtime.InteropServices

type C1() = static member M([<Out>] arg: C1 byref) = arg <- C1(); true
type C2() = static member M(arg: C2 outref) = arg <- C2(); true

let inline getByRef<'a when 'a: (static member M: 'a byref -> bool)> () =
    let mutable res = Unchecked.defaultof<_>
    if (^a: (static member M: ^a byref -> bool) &res) then Some res else None

let inline getOutRef<'a when 'a: (static member M: 'a outref -> bool)> () =
    let mutable res = Unchecked.defaultof<_>
    if (^a: (static member M: ^a outref -> bool) &res) then Some res else None
``` 

Gives 
```
let inline getOutRef<'a when 'a: (static member M: 'a outref -> bool)> () =
  ----------------------------------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error FS3532: A trait may not specify optional, in, out, ParamArray, CallerInfo or Quote arguments
```

I will close this particular issue, if any change in behaviour is desired, it's better to open discussion/langauge suggestion (however due to nature of both SRTPs and byrefs I don't think it will be possible to inline those).
