### ISSUE TITLE
runtime error when splicing expr into query

### ISSUE THREAD

**Issue by habib-sadullaev** [dotnet/fsharp#10287]
**Repro steps**

```fsharp
let pred = <@ fun _ -> true @>

let q = query { for x in 1..10 do if (%pred) x then yield x }
List.ofSeq q
```

**Expected behavior**

works without issue if possible, or won't compile otherwise

**Actual behavior**

runtime error: `System.InvalidOperationException: first class uses of '%' or '%%' are not permitted`

**Known workarounds**

```fsharp
let q = query.Run <@ query.For(query.Source [1..10], fun x -> if (%pred) x then query.Yield x else query.Zero()) @>
List.ofSeq q
```
or
```fsharp
let q = query.Run <@ query.Source (seq { for x in 1..10 do if (%pred) x then x }) @>
List.ofSeq q
```

**Comment by cartermp** [comment]
The design of quotations doesn't permit this to be a compilation error, and it's not clear if it _should_ be, since there's all kinds of code you can write that would fail at runtime. So this would be by design.
