### ISSUE TITLE
Support Inline Hints

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#10289]
Implementing this API: https://github.com/dotnet/roslyn/tree/master/src/Tools/ExternalAccess/FSharp/InlineHints

Checking things like:

* Inferred types on bindings
* Parameter name hints

**Comment by cartermp** [comment]
It's actually very possible and works very well: https://github.com/dotnet/fsharp/pull/10295

The remaining work is to wire up roslyn-based options into this.

**Comment by cartermp** [comment]
I'm going to push this out to dev17.

**Comment by psfinaki** [comment]
Closing in favor of https://github.com/dotnet/fsharp/issues/14157.
