### ISSUE TITLE
Support Ctrl + U/W shortcuts on FSI

### ISSUE THREAD

**Issue by Swoorup** [dotnet/fsharp#10299]
Linux, mac users will appreciate if Ctrl/Control keys works in FSI

The usual norm is 
* `Ctrl` + U -> Cut all characters from the cursor to the beginning of the line
* `Ctrl` + W -> Cut word from the cursor backwards

What works: 
Ctrl + A -> Move cursor to beginning works
Ctrl + E -> Move cursor to end of line works

Currently it just prints out weird characters on pressing those keywords:
![image](https://user-images.githubusercontent.com/3408009/96721491-ed0f8800-13f7-11eb-82aa-372ad48ef6c4.png)

**Comment by cartermp** [comment]
I think this would be fine. Would you like to submit a PR? The code would likely live here: https://github.com/dotnet/fsharp/blob/main/src/fsharp/fsi/console.fs
