### ISSUE TITLE
Show parameter info not works for F# functions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#10302]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Show-parameter-info-not-works-for-F-fun/1229157?preview=true)._

---
[severity:It's more difficult to complete my work]
In my keyboard settings `Edit.ParameterInfo` is set to `Ctrl+Shift+Space` and it works fine with C# but it doesn't work with F#.

---
### Original Comments
(no comments)

**Comment by cartermp** [comment]
I will spike on seeing what it could take to add support for this
