### ISSUE TITLE
ParseAndCheckFileInProject fails

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#10303]
Running `FSharpChecker.ParseAndCheckFileInProject` fails with creation error returned:
```
Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

It happens due to extra FCS dependencies were added in https://github.com/dotnet/fsharp/pull/9870: https://github.com/dotnet/fsharp/pull/9870/files#diff-f80f13c95d4e5cb2e376c9f82051683af78316220d065db8470e4894b096c46fR731-R733

Removing the references (and moving the [related code](https://github.com/dotnet/fsharp/pull/9870/files#diff-8e07e3cb296d9538332afd88a5c5c73fa6c9a39bbc81e729892270a77b2df8d1R58) to `#if` makes it work as expected (since the moved declarations aren't used in `netsandard2.0` FCS anyway).

I believe FCS should not depend on MSBuild directly like this, since it quite constraints the environment FCS could be used in.

**Comment by dsyme** [comment]
I'm hitting this failure as well when updating FSHarp.Formatting to use latest FCS

> I believe FCS should not depend on MSBuild directly like this, since it quite constraints the environment FCS could be used in.

I agree

@baronfel Have you noticed this issue with people using latest FCS?

**Comment by baronfel** [comment]
Yes, many consumers have had to add this package (including things like sharplab and xunit).

**Comment by auduchinok** [comment]
We've had to workaround it by temporarily deleting the references and related code in our FCS build.

**Comment by cartermp** [comment]
I take it this still an issue with FCS 38.0.2? I don't think we can get rid of the dependency but it should at least be added to the nuspec.

**Comment by cartermp** [comment]
Closing out older issue due to needs more info
