### ISSUE TITLE
Add Async.CatchResult to FSharp.Core

### ISSUE THREAD

**Issue by brettrowberry** [dotnet/fsharp#10304]
`Async.Catch` is really handy:
https://github.com/dotnet/fsharp/blob/ec5bad3a391357e03ff2286a264f0e4faf7d840d/src/fsharp/FSharp.Core/async.fsi#L109
https://github.com/dotnet/fsharp/blob/ec5bad3a391357e03ff2286a264f0e4faf7d840d/src/fsharp/FSharp.Core/async.fs#L1129

It has the signature: 
`Async<'T> -> Async<Choice<'T,exn>>`

Would it be all right to add an 
`Async.CatchResult` with signature: 
`Async<'T> -> Async<Result<'T,exn>>`?

**Comment by cartermp** [comment]
Closing in favor of https://github.com/fsharp/fslang-suggestions/issues/930
