### ISSUE TITLE
Improve string caching

### ISSUE THREAD

**Issue by TIHan** [dotnet/fsharp#10312]
At the moment, we don't do anything sophisticated with caching strings. 

It could be improved upon by the following:

- Having a global shared cache along with a local cache - think of L1 and L2 cache. Roslyn does this: http://sourceroslyn.io/#Microsoft.CodeAnalysis/InternalUtilities/StringTable.cs

- Instead of allocating a string every time we parse, we could look at the span of characters in a source text to determine if we could use a string from a cache. This might be a little tricky as it could incur some performance overhead, but it would be useful from an allocation and memory standpoint.

**Comment by dsyme** [comment]
Closing out this old issue
