### ISSUE TITLE
Building fsharp.sln can raise curious errors on some VS 2019 versions

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#10339]
Building `FSharp.sln` on Windows 10, VS 16,.7.3 raises FS0229 "Error opening binary file: Index was outside the bounds of the array" and FS3160 "Problem reading assembly":

```
12>FSC : error FS0229: Error opening binary file 'D:\Repos\fsharp\artifacts\bin\FSharp.Compiler.Service\Debug\netstandard2.0\FSharp.Compiler.Service.dll': Index was outside the bounds of the array.
12>FSC : error FS3160: Problem reading assembly 'D:\Repos\fsharp\artifacts\bin\FSharp.Compiler.Service\Debug\netstandard2.0\FSharp.Compiler.Service.dll': The exception has been reported. This internal exception should now be caught at an error recovery point on the stack. Original message: Error opening binary file 'D:\Repos\fsharp\artifacts\bin\FSharp.Compiler.Service\Debug\netstandard2.0\FSharp.Compiler.Service.dll': Index was outside the bounds of the array.)
12>Done building project "FSharp.Compiler.Service.Tests.fsproj" -- FAILED.
```

**Repro steps**

* Get latest repo or `git clean -xdf` if you already have it
* Run `build.cmd` and wait for success
* Open `fsharp.sln` in VS 16.7.3 (possibly anything before 16.7.5)

**Expected behavior**

Either a meaningful error or a success.

**Actual behavior**

The error posted above. Those errors are very confusing and don't give any hint on where to even begin looking for a solution.

**Known workarounds**

This can be fixed by upgrading VS to 16.7.6 (Oct 13, 2020 version)

**Related information**

We stumbled upon this during a co-session of setting up the F# compiler env for @kerry-perret. The solution is clear (upgrade VS). I'm posting this so there's a record for people that may also stumble upon this and search here for a solution.

And perhaps there's something we can do to raise a more meaningful error, like "Expected VS version X, please upgrade", though I don't know how easy/hard it would be to have that in, plus that it'll have to be maintained each time the minimal supported version changes.

**Comment by cartermp** [comment]
Closing this as this shouldn't be an issue now.

**Comment by abelbraaksma** [comment]
Yeah, it was probably a temporary fluke, I don't see it anymore.
