### ISSUE TITLE
F#5 Nameof unclear behaviour

### ISSUE THREAD

**Issue by En3Tho** [dotnet/fsharp#10348]
Please provide a succinct description of the issue.

nameof function does not see names of "incomplete" functions

Provide the steps required to reproduce the problem:

let f x = nameof x - works, nameof sees variable "x" as viable identifier
let f x = nameof f |> x - doesn't work, nameof can't see "f" as viable identifier

**Expected behavior**

nameof function can see "f" as viable identifier and report it's name

**Actual behavior**

nameof function cannot see "f" as viable identifier

**Known workarounds**

use literals instead or provide a private object with same function names and use nameof on them

**Related information**

C# nameof can do this, if matters

Provide any related information (optional):
Tested in JBRider EAP 2020.3, langversion preview

**Comment by cartermp** [comment]
This is by design. Referring to a function symbol within the function itself is recursive, and you need to make the function a `let rec` to accomplish that. It's the same as if you were to call `f` recursively.
