### ISSUE TITLE
Expose the augmented methods Is"Case" of discriminated unions

### ISSUE THREAD

**Issue by snuup** [dotnet/fsharp#10359]
### Problem

I occasionally need a simple way to distinguish cases of DUs and write code like

    type Animal =
        | Rabbit
        | Lion
        with member o.IsRabbit with get() = o |> function Rabbit -> true | _ -> false 
        with static member IsRabbit o =     o |> function Rabbit -> true | _ -> false // alternative

This raises FS0023 however: _"The member 'IsRabbit' can not be defined because the name 'IsRabbit' clashes with the default augmentation of the union case 'Rabbit' in this type or module"_

This is unlucky: I am not allowed to define IsRabbit but I am also not allowed to use the already existing augmented method.

### Suggested Solution
Expose the augmented method IsRabbit.

Benefits:
The coder is **no longer prohibited from writing** IsRabbit.
The coder does **not even need to write** IsRabbit.
The coder can **use** IsRabbit.

### Current workaround
So now I use

    type Animal =
        | Rabbit
        | Lion
        with member o.IsRabbit_ with get() = o |> function Rabbit -> true | _ -> false

which is a shame, since it adds code that already exists in the assembly and is ugly with the underscore.

### Reasoning
The only argument I can see against my suggestion is that the augmented operation would go up into the exposed interface and could not be changed in the future. I believe however that this augmented operation is stable since the beginning of F#.

**Comment by cartermp** [comment]
Thanks for the suggestion. This is tracked in the language suggestions repo here: https://github.com/fsharp/fslang-suggestions/issues/222

There is also an approved design here: https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1079-union-properties-visible.md

If you're interested in submitting a proposed implementation of the design, that would be quite welcome!
