### ISSUE TITLE
Named and secondary string arguments for type providers require space before '@'

### ISSUE THREAD

**Issue by reinux** [dotnet/fsharp#10358]
A `@` not preceded by whitespace in a type provider argument causes a compiler error which differs from the one that occurs when the `@` is the first token in the argument list.

This isn't a very severe issue, but it does cause Fantomas to bork (because it behaves correctly by removing the whitespace when it shouldn't be necessary).

**Repro steps**

```
type Graphml = XmlProvider<Schema=@"http://graphml.graphdrawing.org/xmlns/1.0/graphml-structure.xsd" >
type Graphml = XmlProvider<A=1, Schema=@"http://graphml.graphdrawing.org/xmlns/1.0/graphml-structure.xsd" >
```

**Expected behavior**

Compiles, or at least provides the same error as for when the argument immediately follows the `<` (FS1243: "Unexpected quotation operator '<@' in type definition. If you intend to pass a verbatim string as a static argument to a type provider, put a space between the '<' and '@' characters.")

**Actual behavior**

Errors:

> FS0010	Unexpected infix operator in type arguments. Expected ',' or other token.
> FS1241	Expected type argument or static argument

**Known workarounds**

Place a space before `@`:

```
type Graphml = XmlProvider<A=1, Schema= @"http://graphml.graphdrawing.org/xmlns/1.0/graphml-structure.xsd" >
```

Currently, Fantomas won't do this.

Provide any related information (optional):

* Windows 10 Pro
* .NET Core 5 RC2
* Visual Studio 2019 16.8.0 Preview 6.0

**Comment by cartermp** [comment]
Seems like a reasonable thing to adjust in the compiler.

**Comment by dsyme** [comment]
It's by design = `=@` is a token, as is `>=`, `=?` and some other cases where people might be surprised by this

Please file an issue at fslang-suggestions.

**Comment by cartermp** [comment]
the biggest one is `<^`, which i believe was treated as "this is really just a bug but is technically by design". Should this be treated the same way?

**Comment by reinux** [comment]
Huh. Turns out this is all valid:

```
let (=@) a b =
  a + b
let (<^) a b = a + b
let (>^) a b = a * b

3=@4

3<^4>^5
```

So I guess it's best not to touch this one.
