### ISSUE TITLE
Problem with Applicative CEs and 'Zero'

### ISSUE THREAD

**Issue by gusty** [dotnet/fsharp#10379]
**Repro steps**

This script works fine, but when we uncomment the `BindReturn` member it fails because it seems it doesn't use the `Zero` method.

```
type Builder () =
    member        __.ReturnFrom (expr) = expr                                  : seq<'T>
    member inline __.Return (x: 'T) = Seq.singleton x                          : seq<'T>
    member inline __.Yield  (x: 'T) = Seq.singleton x                          : seq<'T>
    member inline __.Bind (p: seq<'T>, rest: 'T->seq<'U>) = Seq.collect rest p : seq<'U>

    member inline __.Delay (expr: _->seq<'T>) = Seq.delay expr : seq<'T>
    member        __.Run f = f : seq<'T>

    member inline __.Zero () = Seq.empty : seq<'T>

    // member inline __.BindReturn   (x : seq<'T>, f: 'T -> 'U) : seq<'U> = Seq.map f x

let seqbuilder= new Builder ()

let _pythags = seqbuilder {
  let! z = seq [1..50]
  let! x = seq [1..z]
  let! y = seq [x..z]
  if (x*x + y*y = z*z) then return (x, y, z) }
```

**Expected behavior**

Compile fine with the `BindReturn` member

**Actual behavior**

Doesn't compile with the  `BindReturn` member

**Known workarounds**

Add an else branch. but still looks like a regression.

**Related information**

F# 5.0

**Comment by dsyme** [comment]
Yes, this code (with the BindReturn uncommented) compiles with `--langversion:4.7` but not `--langversion:5.0`

**Comment by dsyme** [comment]
@cartermp I guess this isn't totally a regression (or at least not such a severe one), since we don't really expect `BindReturn` methods to be present unless people are using 5.0.  So it's more a bug in the applicatives feature.  

I'll fix it now neverthelss but change the priority

**Comment by gusty** [comment]
@dsyme It's true that it's not 100% a regression, but it hit us. In F#+ we started using it, and it worked fine.

But suddenly, our CIs upgraded to F# 5 and some tests started failing, then we realized that by shipping this optimization we included a breaking change. So we did an emergency release to take it out for the moment.

**Comment by gusty** [comment]
@dsyme @cartermp  Any update on this ?
F# 5 is a thing now.

**Comment by cartermp** [comment]
None to share this time. I'll update the milestone to be a shipping one since @dsyme indicated he'd take a look.

**Comment by dsyme** [comment]
I've got this properly tracked in my work log now to take a look

**Comment by gusty** [comment]
> @dsyme @cartermp Any update on this ?
> F# 5 is a thing now.

Now F#6 is released. Still no updates?

**Comment by dsyme** [comment]
@gusty No update, but sent myself another reminder....

**Comment by gusty** [comment]
@dsyme just curious why did you remove the Regression label?

As per your comments above

> Yes, this code (with the BindReturn uncommented) compiles with --langversion:4.7 but not --langversion:5.0

Is there any chance this will be fixed anytime soon ? 🤔

**Comment by T-Gro** [comment]
> @dsyme just curious why did you remove the Regression label?
> 
> As per your comments above
> 
> > Yes, this code (with the BindReturn uncommented) compiles with --langversion:4.7 but not --langversion:5.0
> 
> Is there any chance this will be fixed anytime soon ? 🤔

I will check what is needed for a fix.
I might get stuck, so cannot give a promise yet.
