### ISSUE TITLE
Discontinuing Nightly Releases for Visual F# Tools

### ISSUE THREAD

**Issue by brettfo** [dotnet/fsharp#10387]
Over 3.5 years ago @cartermp [announced](https://devblogs.microsoft.com/dotnet/announcing-nightly-releases-for-the-visual-f-tools/) the nightly releases for Visual F# tools.  Unfortunately this release channel will shortly be discontinued for a period.

I've added a few of what I expect to be common questions, but feel free to ask more in the comments.  I'll consolidate/summarize new questions and place them in this top post.

## FAQ

Q. Why?
A. The various parts of the dotnet team's infrastructure is being consolidated.  Most of the produced artifacts from dotnet builds are in the form of NuGet packages and those have all been migrated over to Azure DevOps, F# included.  The one outlier has been the nightly build of `VisualFSharpFull.vsix` which is what provides the F# editor to Visual Studio.  Visual Studio VSIX feeds are different from NuGet feeds; in fact, they're single-item Atom/RSS feeds, and that's not a scenario that Azure DevOps currently supports.  As it stands, the only remaining item on the custom dotnet.myget.org instance is the F# nightlies.

Q. How do I still get regular updates?
A. The recommended way to always have fresh F# bits is to install the [preview versions of Visual Studio](https://visualstudio.microsoft.com/vs/preview/).  Every build from our release branches (currently `release/dev16.9`) gets automatically inserted into the main VS tree, so whenever there's an update to a preview version of Visual Studio, you automatically get the latest F#, too.

Q. What if I want _really_ fast updates?
A. You can still clone and build this repo directly.  From a clean repo, the following commands should build and launch Visual Studio with all the local F# changes:

```
.\build.cmd
devenv.exe /RootSuffix RoslynDev
```

Q. Have you considered [insert-custom-solution-here]?
A. Yes and the overhead to maintain this for a single team (F#) is too high, but we've been pushing for these and similar infrastructure changes higher up.

Q. Will the nightly releases ever come back?
A. I hope and think so.  Given that the feed format is simple Atom/RSS I suspect that we'll eventually have a similar mechanism in the future and it'll be just as easy to get frequent updates.

**Comment by cartermp** [comment]
Closing old announcement

**Comment by realvictorprm** [comment]
@cartermp This is still case right now, right?

**Comment by realvictorprm** [comment]
Many thanks for the answer! Such a bummer, I liked the nightlies :) however
I totally understand the issues being outlined here etc.

Phillip Carter ***@***.***> schrieb am Do., 13. Mai 2021,
16:41:
