### ISSUE TITLE
Some strange when I create an object in a inline function. 

### ISSUE THREAD

**Issue by greatim** [dotnet/fsharp#10388]
I write some code as below:
```
type CollectionEx = 

        static member inline Union(a, b) = 
            let r =new ^t( )
            for x in a do 
                (^t: (member Add: _ -> unit)(r, x))                
            for x in b do 
                (^t: (member Add: _ -> unit)(r, x))                
            r
    
    let inline (+) a b = 
        let inline union a b (_: ^t) = ((^t or ^a or ^b or ^c): (static member Union: ^a * ^b -> ^c) (a, b))
        Unchecked.defaultof<CollectionEx> |> union a b

    let foo (a: List<_>, b: List<_>): List<_> = a + b
```
It generate the function `foo`:

```
public static List<a> foo<a>(List<a> a, List<a> b)
{
	List<a> list = Activator.CreateInstance<List<a>>();
	foreach (a item in (IEnumerable<a>)a)
	{
		list.Add(item);
	}
	foreach (a item2 in (IEnumerable<a>)b)
	{
		list.Add(item2);
	}
	return list;
}
```

And then I fix `new ^t()` to ` (^t: (new: unit -> ^t)())`, It generate the `foo` as :
```
public static List<a> foo<a>(List<a> a, List<a> b)
{
	List<a> list = new List<a>();
	foreach (a item in (IEnumerable<a>)a)
	{
		list.Add(item);
	}
	foreach (a item2 in (IEnumerable<a>)b)
	{
		list.Add(item2);
	}
	return list;
}
```
why `new ^t()` is compiled into `Activator.CreateInstance<List<a>>()`  
and  `(^t: (new: unit -> ^t)())` to `new List<a>()` ? 
It doesn't make sense.

**Comment by smoothdeveloper** [comment]
As you point, you need to invoke the constructor through SRTP for the generated code to be what you expect:

```fsharp
let r = (^t : (new : unit -> ^t) ())
```

It seems according to the spec (§ 6.4.2) that `new 'typeparam` (which I guess applies to `new ^typeparam` in absence of SRTP member invocation syntax) lowers to `Activator.CreateInstance`:

> The expression elaborates to a call to
FSharp.Core.LanguagePrimitives.IntrinsicFunctions.CreateInstance<ty>(), which in turn calls
System.Activator.CreateInstance<ty>(), which in turn uses CLI reflection to find and call the
null object constructor method for type ty. On return from this function, any exceptions are
wrapped by using System.TargetInvocationException.

**Comment by dsyme** [comment]
Yes this is by design, as per the spec.
