### ISSUE TITLE
Type checking issue in quotations with generic constraints.

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/fsharp#10389]
I discovered an issue in F# 5.0 which is probably related to [this change](https://github.com/fsharp/fslang-design/blob/master/preview/FS-1071-witness-passing-quotations.md).

**Repro steps**

Consider the following function:

```fsharp
let isNullQuoted (ts : 't[]) =
    <@
        match ts with
        | null -> true
        | _ -> false
    @>
```

In F# 4 this compiles without issue and has type signature `'t[] -> Expr<bool>`. However in F# 5.0 this yields the following type checking error:

```
error FS0193: A type parameter is missing a constraint 'when 't : equality'
```

While this behaviour could technically be considered correct (since the quotation tree uses `op_Equality` to check for null), I feel it is worth reporting for a few reasons:

* The `'t : equality` constraint could have been inferred by the type checker.
* The equivalent non-quoted function type checks without issue (and without forcing any constraints on the `'t` parameter).
* It is a regression compared to F# 4.0 behaviour ([code that used to compile](https://github.com/eiriktsarpalis/TypeShape/blob/d12bf60d0bfef462eafbb7f19e7c1eb3138dc011/samples/TypeShape.Samples/equality-staged.fs#L36) now doesn't).

### Known Workarounds

```fsharp
let isNullQuoted (ts : 't[]) =
    <@
        match ts with
        | _ when isNull ts -> true
        | _ -> false
    @>
```

compiles without issue, as does

```fsharp
let isNullQuoted (ts : 't[] when 't : equality) =
    <@
        match ts with
        | null -> true
        | _ -> false
    @>
```

**Comment by cartermp** [comment]
I agree with this:

> The `'t : equality` constraint could have been inferred by the type checker.

@dsyme what are your thoughts?
