### ISSUE TITLE
streams and compilation

### ISSUE THREAD

**Issue by dukedagmor** [dotnet/fsharp#10414]
I'm currently working on mutationtesting for F#, with mutationtesting is is quite valuable to not have to write to disk but instead be able to compile to memory, for performance reasons. I've read that the ```CompileToDynamicAssembly``` does not support streams in the way I would like to.

My suggestion: change ```CompileToDynamicAssembly``` or create a new ```CompileToStream``` which keeps the stream intact and available after compile so the entire process runs in memory.

Similar issues: https://github.com/fsharp/FSharp.Compiler.Service/issues/266 , https://github.com/fsharp/fslang-suggestions/issues/369

**Comment by cartermp** [comment]
@dukedagmor We'd be unlikely to change the existing API, but I think we'd be happy to review a proposed change that surfaces as an overload that accepts a stream. No idea how deep that work would be, though.

**Comment by dsyme** [comment]
I think compiling to a temporary file and picking up the bytes then loading them from memory is adequate for this - the performance difference will not, I think, be noticeable.
