### ISSUE TITLE
Quick action to explicitly annotate a `let` binding

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#10421]
Given code like this:

```fsharp
let myFunc x = x.ToString()
```

There should be a quick action available to convert it to this:

```fsharp
let myFunc (x: 'a) : string = x.ToString()
```

This would require some work to get the inferred types of the `let`-bound value(s) and each parameter if it's a function, and their ranges.

**Comment by kerams** [comment]
Where should the action pop up? With caret within the function identifier?

On a related note how are quick actions actually triggered? They don't have associated diagnostic IDs like code fixes, so does Roslyn iterate over all registered providers on every hover/caret move to see if they return anything actionable at the location?

**Comment by cartermp** [comment]
This would be added as a refactoring provider here: https://github.com/dotnet/fsharp/tree/main/vsintegration/src/FSharp.Editor/Refactor

**Comment by cartermp** [comment]
Refactoring Providers and quick fixes are different. The former is run periodically in the editor and whenever one is applicable it is triggered to run asynchronously. The latter are triggered based off of diagnostics.

**Comment by psfinaki** [comment]
https://github.com/dotnet/fsharp/assets/5451366/c024e13d-8153-49ae-ba88-bfa2ff4031fd

So this is half-there - works for parameters but not return types. Keeping the ticket, created a separate area for this to distinguish it from code fixes.

**Comment by psfinaki** [comment]
I wonder if we want to fully annotate everything we can right away.
I'd rather have separate things for suggesting explicit types for parameters (maybe also for all of them) and explicit types for return values. As in:
- add type annotation
- add type annotations for all parameters
- add return type annotation

I'll close this ticket and create new ones for 2 and 3.
