### ISSUE TITLE
Potential regression in overload resolution for Async.Sleep

### ISSUE THREAD

**Issue by Evangelink** [dotnet/fsharp#10424]
**Describe the problem**

I do hope I am reporting to the correct repository. The following code (Elmish WPF) works with VS2019

```fsharp
let frameDuration =
	getFrameRate model
	|> Option.defaultValue(10</s>)
	|> fun rate -> 1 / rate * 1000<ms/s>
	|> int
Cmd.batch [
	Cmd.ofMsg NextFrame
	Cmd.OfAsync.perform Async.Sleep frameDuration (fun () -> AutoPlayNextFrame)
]
```

but does not work with VS2019 Preview and needs to be tweaked as followed

```fsharp
let frameDuration =
	getFrameRate model
	|> Option.defaultValue(10</s>)
	|> fun rate -> 1 / rate * 1000<ms/s>
	|> int
Cmd.batch [
	Cmd.ofMsg NextFrame
	Cmd.OfAsync.perform (fun (x:int) -> Async.Sleep x) frameDuration (fun () -> AutoPlayNextFrame)
]
```

**Related information**

Provide any related information (optional):

* Operating system: Win 10
* .NET Runtime kind: net48
* Editing Tools: Visual Studio 2019 vs VS2019 Preview

--- EDIT ---
![image](https://user-images.githubusercontent.com/11340282/98793834-b4683a80-2408-11eb-9e77-9d68db069564.png)

**Comment by cartermp** [comment]
This is by design, as it's an additional overload on the type. Unfortunately when passing values to methods, if you rely on type inference, you'll run the risk of experiencing a break.

**Comment by Evangelink** [comment]
I am pretty new to fsharp so I might be missing something but if I get things right, there was only the int overload and now there are both int and TimeSpan but since the value passed is int, I don't understand why the compiler doesn't resolve the int overload. Am I missing something?

**Comment by cartermp** [comment]
Ah, in this case you're passing this static member as if it were a first-class function to something accepting a function as a parameter. Yeah, that's also something that doesn't jive with methods and overloading. All the `Async` "functions" aren't functions, but static methods.
