### ISSUE TITLE
FSharp.Core conflict warnings during build (after VS 16.8 upgrade)

### ISSUE THREAD

**Issue by nbevans** [dotnet/fsharp#10440]
We are seeing these warnings emitted from many of our projects during build:

```
warning MSB3277: Found conflicts between different versions of "FSharp.Core" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
```

It seems that it is necessary to upgrade to the FSharp.Core 5.0.0 NuGet in all projects straight away after installing VS 16.8 - because doing so will make this warning go away.

Is this intentional behaviour?

Is there a way to allow VS 16.8 and FSharp.Core 4.7 NuGet to co-exist without build warnings?

**Comment by cartermp** [comment]
I'm not sure what the circumstances are that could lead to this, so we'll likely need a repro to understand further. It could depend on how you reference FSharp.Core and for what purpose, the project type, the environment, etc.

**Comment by nbevans** [comment]
Okay I will reinstall VS 16.8 and try to repro it in some sort of isolated .sln + .fsproj.

Will try to post something here tomorrow.

**Comment by KevinRansom** [comment]
@nbevens can you provide a repro of your failing project or run 
````
dotnet build your.fsproj /bl
````
And add msbuild.binlog to this issue so I can take a look.

Thanks

**Comment by nbevans** [comment]
Well it's a mix of netframework and netstandard2.0 projects really. We haven't moved to netcore / net5 yet.

I will try to make a repro today. More soon

**Comment by nbevans** [comment]
Okay well in the process of trying to make a repro .sln I think I discovered the cause.

We added a new .fsproj to our .sln in late October. This inadvertently took a reference on FSharp.Core 5.0.0 NuGet without us realising - I didn't realise 5.0.0 was even out back then!

After setting an explicit NuGet reference as follows:

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="4.7.2" />
  </ItemGroup>

The problem went away.

So that's that. **Sorry for the false alarm!**

We need to do some additional work (upgrading our WebSharper NuGets etc) before we can move to 5.0.0.

**Comment by cartermp** [comment]
Yep, mixing and matching is generally going to lead to this. It's best to just either not specify it at all (sdk approach, for apps) or pin the version everywhere (the paket approach, for libraries shipping to nuget). Glad it was just this and not a bug!

**Comment by nbevans** [comment]
Our .sln dates from 2014, so it combines non-SDK-style .fsproj, newer SDK-style .fsproj, and some of these are netstandard2.0 and some are netframework .fsproj (again both a mixture of SDK-style and non-SDK-style .fsproj!) Prior to netstandard those projects were "PCL" projects. I won't even mention the Xamarin.Android, Xamarin.iOS and the UWP (which is some variant of netcore) projects in the .sln.

So indeed, "mix and match" seems an apt description. We're converting them to SDK-style as and when, but this may have to speed up for .NET 5 transition work.

Our normal approach is to always explicitly include the FSharp.Core NuGet - but obviously with the implicit reference generated by SDK-style .fsproj we missed one in October. Oops.

Thanks
