### ISSUE TITLE
Cannot specify all DateTime formatting options in interpolated string

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#10449]
Consider the following interpolated strings:

```fsharp
let date = System.DateTime.Now
let str = $"{date}"
let str2 = $"{date:HH}"
let str3 = $"{date:HH:mm}"
```

The first two work, but the third one fails to compile because it gets confused by the second `:`.

cc @dsyme

**Comment by nbevans** [comment]
What if you do ${date:HH':'mm}" ?

In theory, you are actually meant to wrap literal text in a date format using single quotes like that.

**Comment by cartermp** [comment]
Yeah, there's no workaround that you can apply within the interpolated string itself. Need to use the `ToString()` overload.

**Comment by nbevans** [comment]
let ``my date with a : in it`` = System.DateTime.Now
let str = $"{``my date with a : in it``:HH}"

FWIW - colons in the let binding name itself do work okay.

**Comment by chillitom** [comment]
This is a workaround: `$"{System.DateTime.UtcNow:``yyyy-MM-dd``}"`

**Comment by dsyme** [comment]
@chillitom impressive!

**Comment by dsyme** [comment]
Clarified in the RFC here: https://github.com/fsharp/fslang-design/pull/654.  I'll make a clarification in the F# docs as well

This is an adequate workaround
