### ISSUE TITLE
FSI Loading of Nuget Packages Confuses Dotnet Versions

### ISSUE THREAD

**Issue by 7enderhead** [dotnet/fsharp#10466]
**Repro steps**

1. machine has .NET SDKs 3.1.xxx and 5.0.xxx (RC1)
2. explicitly starting FSI for 3.1.xxx to be able to work with nuget packages that target 3.1
3. using `/langversion:preview` feature to load nuget packages into FSI
4. FSI uses resources from 5.0 SDKs, which confuses nuget sources, see transcript below
5. uninstalling SDK 5.0 helps

```
$dotnet "C:\Program Files\dotnet\sdk\3.1.402\FSharp\fsi.exe" /langversion:preview

Microsoft (R) F# Interactive version 10.10.0.0 for F# 4.7
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> fsi.PrintLength <- 500
-
- #r "nuget:include=Microsoft.ML"
- open System
- open System.IO
- open Microsoft.ML
- open Microsoft.ML.Data
- open Microsoft.ML.Trainers
- open Microsoft.ML.Transforms
- open Microsoft.ML.Transforms.Text
- ;;
val it : unit = ()

Microsoft (R) Build Engine version 16.8.0-preview-20451-02+51a1071f8 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Retrying 'FindPackagesByIdAsync' for source 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/d1622942-d16f-48e5-bc83-96f4539e7601/nuget/v3/flat2/microsoft.ml/index.json'.
  Response status code does not indicate success: 503 (Service Unavailable).
  Retrying 'FindPackagesByIdAsync' for source 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/d1622942-d16f-48e5-bc83-96f4539e7601/nuget/v3/flat2/microsoft.ml/index.json'.
  Response status code does not indicate success: 503 (Service Unavailable).
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\NuGet.targets(130,5): error : Failed to retrieve information about 'Microsoft.ML' from remote source 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/d1622942-d16f-48e5-bc83-96f4539e7601/nuget/v3/flat2/microsoft.ml/index.json'. [C:\Users\atw12aq5\AppData\Local\Temp\nuget\9496--4678552f-c77a-4425-ba95-740cce31a130\Project.fsproj]
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\NuGet.targets(130,5): error :   Response status code does not indicate success: 503 (Service Unavailable). [C:\Users\atw12aq5\AppData\Local\Temp\nuget\9496--4678552f-c77a-4425-ba95-740cce31a130\Project.fsproj]
```

**Expected behavior**

Loading of nuget packages works.

**Actual behavior**

Loading of nuget package fails due to dotnet sdk 5.0.xxx resources being used.

**Known workarounds**

Uninstalling dotnet sdk 5.0.xxx from machine.

**Related information**

Provide any related information (optional):

* Windows 10
* installed .NET sdks: 2.1.517, 3.1.402 and 5.0.100-rc.1.20452.10

**Comment by KevinRansom** [comment]
@7enderhead  --- did you use a global.json fike to specify which dotnet sdk version you wanted?

**Comment by 7enderhead** [comment]
No, I just started the command line with the explicit 3.1 fsi version.

**Comment by cartermp** [comment]
@7enderhead can you try with a global.json? It works for me in a repo where the global.json specified .NET Core SDK 3.1.x.

In general, it is not supported to mix and match the way that you have. You need to pin your toolset via global.json if you want to use a specific version of FSI. What you specified will load a specific FSI against a different set of assemblies and toolsets that were not built with that version of FSI.

**Comment by cartermp** [comment]
Closing out as the correct approach here is to use `global.json` to load things from a specific toolset. Crossing streams across toolsets will unfortunately just lead to issues that we can't resolve.
