### ISSUE TITLE
nameof picks private DU case over type and fails to compile with FS1093 "the union cases or fields of type Y are not accessible from this code location"

### ISSUE THREAD

**Issue by cmeeren** [dotnet/fsharp#10494]
**Repro steps**

```f#
 module X =

    type Y = private Y of int

  open X

  let x = nameof Y
//               ^ FS1093
```

![image](https://user-images.githubusercontent.com/7766733/99500445-ab341c00-297a-11eb-89ec-4adb3892721c.png)

**Expected behavior**

I'm undecided on whether it should pick the DU type or case, but it should compile anyway.

**Actual behavior**

Fails to compile.

**Known workarounds**

None.

**Related information**

* VS 16.8.1
* `FSharp.Core` 5.0.0

**Comment by cartermp** [comment]
This would be by design. There is no accessible symbol named `Y` outside of the module `X`, so it's not possible to take a name of this construct outside of that module.

As for why it picks the `Y` case name - this is just how name resolution works for DU cases in F#. When there is an accessible union case with the name it is picked over the name of the type declaration.

**Comment by cmeeren** [comment]
> This would be by design.

I get that it's by design that the case constructor is not accessible. But is it by design that `nameof` doesn't work with it? Or at least, by design that it doesn't pick the type name since, after all, the case constructor isn't accessible? Would this be possible to work around in the way `nameof` works?

**Comment by cartermp** [comment]
Yes, it's also by design for `nameof`. `nameof` intentionally just follows normal F# name resolution rules. If something is resolvable in F# code, you can take a name of it. But if it's not, we don't allow it.

**Comment by cmeeren** [comment]
Thanks for the clarification. It's understandable, though regrettable. Constrained types using single-case DUs with private constructors is a common idiom in F#, and it would be useful to be able to use `nameof` to get the name of those types.

Thanks anyway!
