### ISSUE TITLE
inconsistent behaviour between `fsi` and `dotnet fsi` with string interpolation

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#10507]
```fsharp
let iii = 2020
printfn $"%04i{iii}"
```

on fsi.exe (from VS 2019 16.8):

> 2020

on dotnet fsi (from dotnet sdk 5.0.100):

> test.fsx(2,9): error FS1160: This token is reserved for future use
> test.fsx(2,9): error FS1156: This is not a valid numeric literal. Valid numeric literals include 1, 0x1, 0o1, 0b1, 1l (int), 1u (uint32), 1L (int64), 1UL (uint64), 1s (int16), 1y (sbyte), 1uy (byte), 1.0 (float), 1.0f (float32), 1.0m (decimal), 1I (BigInteger).

AFAIU, fsi.exe is the correct one.

**Comment by dsyme** [comment]
I don't see this behaviour with the `dotnet fsi` on my machine

**Comment by dsyme** [comment]
```
E:\GitHub\dsyme\dsharp-models>dotnet fsi

Microsoft (R) F# Interactive version 11.0.0.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> let iii = 2020;;
val iii : int = 2020

> printfn $"%04i{iii}";;
2020
val it : unit = ()

> #q;;
```

**Comment by smoothdeveloper** [comment]
Doh! I was running from a folder with pinned sdk to older version with F# 4.7.

> Microsoft (R) F# Interactive version 10.10.0.0 for F# 4.7
> Copyright (c) Microsoft Corporation. All Rights Reserved.
