### ISSUE TITLE
"main" not working with current VS RTM dev 16.8/16.8.2

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#10513]
@KevinRansom informs me that main" has an incorrect dependency on a latest Roslyn version that should have been put into a release branch,

At the moment this means "main" will not work with the latest VS RTM version 16.8/16.8.2

If you need to do IDE work then either

1. base it off the `release/dev16.8` branch and use a 16.8 version of VS, and let CI integrate the work forward into main

2. base it off `main` and use a 16.9 preview of VS

**Comment by cartermp** [comment]
To be clear, it works just fine for development unless you are building a hive of VS to test VS tooling. You need VS preview for that. The Roslyn dependency is not wrong, it's just a dependency for VS tooling.

Also it isn't a good idea to base work off of rel/dev16.8. It's going to create merge issues soon enough.

We should just update the readme.

**Comment by dsyme** [comment]
Well, our policy is that main should work with VS current non-preview RTM for making VS tooling, so we should ideally fix this (and try to make sure it doesn't happen again...)

If we can't let's make it a temporary restriction

**Comment by dsyme** [comment]
(Concretely, my instructions to collaborators about how to use DiffSharp live checking tooling no longer work, see https://github.com/DiffSharp/DiffSharp/pull/207#issue-497947907)

**Comment by cartermp** [comment]
I'm for updating the readme/devguide for now and just leaving it as-is. Unrolling that also means unrolling back to ~1.5 years ago in terms of our VS dependencies, and we'll have to just deal with even more dependency uptake pain at some point when we're required to update.

**Comment by cartermp** [comment]
This doesn't mean we can't have the same policy in the future but I'm quite reluctant to back out changes and just push off another "in dependency hell" update to sometime in the future.

**Comment by dsyme** [comment]
Strange, I thought 16.8 was more recent - I was happily developing on it a month ago

Methodologically main should always run on current VS RTM (not preview). But maybe we're at an inflection point where this is not possible

**Comment by cartermp** [comment]
Oh it's always been possible, but the closure of our VS dependencies used to be ~1.5 years old or older. It's a testament to Roslyn and VS that it can still load dependencies that are that old.

**Comment by cartermp** [comment]
Closing out as we were able to find a package closure that wasn't too horrible
