### ISSUE TITLE
Internal F# code throws "System.InvalidOperationException: Collection was modified; enumeration operation may not execute"

### ISSUE THREAD

**Issue by cmeeren** [dotnet/fsharp#10512]
I frequently (many times per day) get the following from a production system:

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at bool System.Collections.ArrayList+ArrayListEnumeratorSimple.MoveNext()
   at bool Microsoft.FSharp.Collections.Internal+IEnumerator.next@193<T>(FSharpFunc<T, bool> f, IEnumerator<T> e, FSharpRef<bool> started, Unit unitVar0) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 194
   at bool Microsoft.FSharp.Collections.Internal+IEnumerator+filter@188.System.Collections.IEnumerator.MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 196
   at bool Microsoft.FSharp.Collections.Internal+IEnumerator.next@193<T>(FSharpFunc<T, bool> f, IEnumerator<T> e, FSharpRef<bool> started, Unit unitVar0) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 194
   at bool Microsoft.FSharp.Collections.Internal+IEnumerator+filter@188.System.Collections.IEnumerator.MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 196
   at bool Microsoft.FSharp.Collections.SeqModule.Exists<T>(FSharpFunc<T, bool> predicate, IEnumerable<T> source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 531
   at <user code>
```

This happens several places in my code. Occasionally this line is present in the stack just above the user code (otherwise the top of the stack trace is identical):

```
   at FSharpOption<T> Microsoft.FSharp.Collections.ListModule.TryFind<T>(FSharpFunc<T, bool> predicate, FSharpList<T> list) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 391
```

I am using FSharp.Core 5, but I'm fairly sure it happened with 4.7, too.

I am targeting .NET Framework 4.7.2.

I have tried my best to create a minimal repro, but the error is intermittent at the best of times, and I have not been able to reproduce the error outside of the system. (Heck, not even inside the system; it happens often, but not when I want it to.) I am posting this issue in the hopes that the stack trace above may help you figure out what is wrong.

In case it helps, my code is similar to this:

```f#
type DU = A | B | C


module DU =

  let allCases =
    Reflection.FSharpType.GetUnionCases(typeof<DU>)
    |> Array.map (fun c -> Reflection.FSharpValue.MakeUnion(c, [||]) :?> DU)
    |> Array.toList


let isCaseRelevant _param1 case _param2 =
  let i = Random().Next(1, 5)  // Simulate decisions on param1 and param2
  match case with
  | A -> i = 1
  | B -> i = 2
  | C -> i = 3


let firstRelevantCase param1 param2 =
  DU.allCases |> List.tryFind (fun r -> isCaseRelevant param1 r param2)
```

The `firstRelevantCase` function may be called from several threads, but I am not able to reproduce the error using the code above if I call it using the following code:

```f#
[<EntryPoint>]
let main argv =

  // Call firstRelevantCase from many threads
  async {
    let start = DateTimeOffset.Now
    while DateTimeOffset.Now < start.AddSeconds 5. do
      firstRelevantCase () () |> ignore
  }
  |> List.replicate 20
  |> Async.Parallel
  |> Async.RunSynchronously
  |> ignore<unit []>

  0
```

This exception is so deep inside internal F# code that I can't see how anything in my user code could cause problems, but do let me know if I have overlooked something.

**Comment by cmeeren** [comment]
I see this was tagged as "needs repro", which is of course correct. I'm just wondering, does that mean it will not be considered until there is a repro? I do not currently see how I will be able to repro it, and as I said, my hope is that the stack trace may be useful on its own and may point to some perhaps-easy-to-spot thread-unsafe code inside FSharp.Core.

**Comment by cartermp** [comment]
Yes, that's correct. I quickly tried something out but couldn't arrive at anything. The stack trace unfortunately doesn't give any causality aside from the source of the error, but that could have been triggered by any number of circumstances unrelated to your issue.

**Comment by cmeeren** [comment]
Thank you for the response and clarification.

> The stack trace unfortunately doesn't give any causality aside from the source of the error, but that could have been triggered by any number of circumstances unrelated to your issue.

I'm not following. Are you saying that the error can be triggered by something unrelated to the FSharp.Core stack trace I posted? In other words, may the error may in fact be directly caused by something in my code that is not as it should be, and not just due to my bug triggering a bug somewhere deep in the FSharp.Core stack trace I shared?

(I should perhaps mention that `param1` and `param2` are mutable objects and that, while I try to be adamant using semaphores/mutexes in this case, I may have overlooked something, meaning that the objects may be theoretically mutated while the function I posted is being called. But given the stack trace and the example code, I fail to see how the bug can be caused by user code. Please enlighten me if you think I'm wrong!)

**Comment by cartermp** [comment]
Yes, there's no indicator in the stack trace that a particular coding pattern is what generated this issue. That's the lack of causality. There's a lot of perfectly valid (compile-time) F# code that could lead to this scenario but it's unclear if this is just valid code being subtly wrong at runtime, or if there's is an actual bug where some code shouldn't compile.

**Comment by cmeeren** [comment]
> There's a lot of perfectly valid (compile-time) F# code that could lead to this scenario

Are you talking in general, or are you thinking of something specific? If so, would you be able to share an example or two?

**Comment by dsyme** [comment]
> Are you talking in general, or are you thinking of something specific? If so, would you be able to share an example or two to aid my understanding?

It would be code that is modifying a System.Collections.ArrayList while it is being iterated

**Comment by cmeeren** [comment]
Thanks for the clarification. Given that I am using mutable business objects in this case (and the problem was reduced by locking more thoroughly), it may be that this is in user code, and the stack trace has me fooled or part of it is optimized away. The `firstRelevantCase` function is the topmost user code in the stack trace, but perhaps the top is really something inside `isCaseRelevant` where the mutable business objects are actually used. I can't immediately see how that makes sense, given my code, but generally that's a pretty normal starting position for debugging.

**Comment by cmeeren** [comment]
By the way, feel free to close this issue if you don't think this is useful to keep open.

**Comment by cartermp** [comment]
Okay, that sounds fine. I don't think there's any action we can take right now.
