### ISSUE TITLE
Error while reading F# metadata from inlined functions with version 4.7.2

### ISSUE THREAD

**Issue by TysonMN** [dotnet/fsharp#10536]
**Succinct description of the issue**

When depending on `FSharp.Core` 4.7.2, some inlined functions lead to malformed F# metadata when read from another project.

**Steps required to reproduce the problem**

1. Create an F# project, add a dependency on `FSharp.Core` 4.7.2, and put the code below these steps into some module.
2. Create a second F# project with a project reference to the first and a dependency on `FSharp.Core` 4.7.2.  There is no need to reference any of the code in the first project.

```fsharp
type Point<'a> =
  { pX: 'a
    pY: 'a } with
  static member inline (-) ((a: Point<'s>), (b: Point<'s>)) : Vector<'s> =
    { vX = a.pX - b.pX; vY = a.pY - b.pY }

and Vector<'a> =
  { vX: 'a
    vY: 'a } with
  static member inline (+) ((p: Point<'s>), (v: Vector<'s>)) : Point<'s> =
    { pX = p.pX + v.vX; pY = p.pY + v.vY }
  // warning when the next line is commented in
  static member inline (*) (s, v) = { vX = s * v.vX; vY = s * v.vY }
  // expected behavior when the next line is commented in
  //static member inline (*) ((s: 's), (v: Vector<'s>)) : Vector<'s> = { vX = s * v.vX; vY = s * v.vY }

let inline linearCombination (a: Point<'s>) (b: Point<'s>) (s: 's) =
  a + s * (b - a)
```

Or, instead of following those steps, just obtain the solution in this ZIP file.

[MWE.zip](https://github.com/dotnet/fsharp/files/5587515/MWE.zip)

**Expected behavior**

There are no warnings.

**Actual behavior**

There are two warnings.
```
1>------ Build started: Project: ClassLibrary2, Configuration: Debug Any CPU ------
1>C:\Users\twilliams\source\repos\ClassLibrary1\ClassLibrary2\unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 53 in table 'itypars' of assembly 'ClassLibrary1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
1>C:\Users\twilliams\source\repos\ClassLibrary1\ClassLibrary2\unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 54 in table 'itypars' of assembly 'ClassLibrary1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
1>ClassLibrary2 -> C:\Users\twilliams\source\repos\ClassLibrary1\ClassLibrary2\bin\Debug\netcoreapp3.1\ClassLibrary2.dll
1>Done building project "ClassLibrary2.fsproj".
========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
```

**Known workarounds**

As stated in the code comments, commenting out the line without type annotations and commenting in the line with type annotations is a workaround.  However, this workaround doesn't work for me in my case because then I encounter issue #9386.

Depending on version 5.0.0 of `FSharp.Core` is _not_ a workaround because attempting to do so results in another reproduction of issue #9382.

**Related information**

* Windows operating system
  - Edition: Windows 10 Enterprise
  - Version: 1909
  - OS build: 18363.1198
* SDK: .NET 5.0.100
* Visual Studio
  - Edition: Enterprise 2019
  - Version: 16.8.2

**Comment by TIHan** [comment]
I think this might be related to witness passing. Will need to look a bit further.

**Comment by dsyme** [comment]
I think we have to treat this as a point-in-time problem, where inlined potentially-witness-passing code may need to be recompiled to be correctly consumed by later versions of the compiler and language.
