### ISSUE TITLE
./configure --prefix=whatever ; make ; make install ?

### ISSUE THREAD

**Issue by jwaldmann** [dotnet/fsharp#10539]
How can I build a shared installation of fsharp under GNU/Linux, in a non-standard location (for students to use in a computer pool - of course, currently with remote access)

This seems related: https://github.com/fsharp/fsharp/issues/865 but I don't know where (what repo) "src/buildfromsource.cmd/sh" is supposed to be.

I have a working install from 2017 but never managed after that.

**Comment by cartermp** [comment]
Since F# is not standalone (runtime and libraries all need to be built as well), you'll need to follow instructions here: https://github.com/dotnet/source-build
