### ISSUE TITLE
Type alias for DU doesn't bring the members in scope

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#10544]
Consider those files:

**ns.fs**
```fsharp
namespace Foo

[<NoComparison;NoEquality>]
type SliceType<'a when 'a : comparison> =
  | All
  | Equals of 'a
  | GreaterThan of 'a
  | GreaterOrEqual of 'a

namespace Bar.Foo

open System
[<Obsolete("Use types in Foo namespace instead of Bar.Foo")>]
type SliceType<'a when 'a : comparison> = Foo.SliceType<'a>
```

and a test script loading it

```fsharp
#load "ns.fs"
open Bar.Foo

let b = SliceType.GreaterOrEqual
let a = GreaterOrEqual // The value or constructor 'GreaterOrEqual' is not defined.
```

I'd expect a and b to be the same but the compiler fails to resolve qualification for `GreaterOrEqual` on it's own.

This makes type alias not so useful for DU as you can't construct it, remains only the possibility to use the DU name in type annotations.

I'd like to know if this is expected and if not, is it worth fixing or a language suggestion.

**Comment by smoothdeveloper** [comment]
The issue seems to have a workaround so you can selectively import the cases in a module.

```fsharp
[<AutoOpen>]
module AutoOpen =
  let GreaterThan = SliceType.GreaterThan
  let GreaterOrEqual = SliceType.GreaterOrEqual
```

**Comment by dsyme** [comment]
This is by design.  I don't think this one will change either.
