### ISSUE TITLE
[Localization] Assistance with translation

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/fsharp#10549]
. | .
-- | --
String Resource ID | 0; "customOperationTextLikeZip"
Source String | {0} var in collection
Filename | fsharp\xlf\FSComp.txt.xlf
Question | We left this string in Eng because it seems it is a part of the below syntax.{0} var in collection {1} (outerKey = innerKey)Please check if it's OK to leave it in Eng.

**Comment by cartermp** [comment]
This should be okay to leave in as-is.
