### ISSUE TITLE
Support viewing expanded F# type in FSI

### ISSUE THREAD

**Issue by Swoorup** [dotnet/fsharp#10595]
**Is your feature request related to a problem? Please describe.**
When working with fsi for prolonged period of time, it can be harmful. 
For example consider the following:
![image](https://user-images.githubusercontent.com/3408009/100953993-d1a3ab00-3567-11eb-92a3-3bb75bcc9ec4.png)

There appears to be no way to view the type of `a` in expanded and unabbreviated form which is of F# type i.e `int * int`.

**Describe the solution you'd like**
A possibility would be to introduce a switch using `:type a` in the console which prints `int * int`. It would be nice we could expanded all abbreviations within the type, (records, anonymous records, unions, etc)

**Describe alternatives you've considered**
`typeof<A>.Name` This however gives the IL name.

**Comment by cartermp** [comment]
I swear this was a language suggestion at some point, or perhaps was just in the discussion of one. I'd rather track it here since it's fundamentally a tooling feature. We can move things around if needed.

**Comment by cartermp** [comment]
FWIW I think a `:type`-like command would be wonderful to add.

**Comment by dsyme** [comment]
I'm closing this - it's just too corner case to have something to specifically expand type abbreviations in FSI - the IDE allows you to click on them and see the definitions of the type abbreviations, that is sufficient.
