### ISSUE TITLE
self-built FSI crashing when using `alt (⌥)+F` or `alt (⌥)+B` macosx.

### ISSUE THREAD

**Issue by Swoorup** [dotnet/fsharp#10600]
Pressing the following key combos on mac throws an exception in FSI. I can't confirm whether the equivalent crashes in other operation system.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Launch `dotnet fsi`
2. Press either `alt (⌥)+F` or `alt (⌥)+B`

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

**Expected behavior**

It should not crash fsi.

**Actual behavior**

Crash.

**Known workarounds**

Don't use the keys

**Related information**

Provide any related information (optional):
![image](https://user-images.githubusercontent.com/3408009/100982254-ee59d600-359b-11eb-8b2c-425334e5dbec.png)

System Info:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /Users/swoorup.joshi/.dotnet/sdk/3.1.302/

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7
```

**Comment by Swoorup** [comment]
nvm

**Comment by Swoorup** [comment]
This appears to happen only when building locally and as of main. I am not sure what is causing it.

**Comment by Swoorup** [comment]
This is more to do with MacOSX inserting non-standard character. The terminal preferences needs to be changed to replace (⌥) with Meta to make it happy.
It's a low priority

**Comment by KevinRansom** [comment]
I love the workaround: 'don't use the keys' outstanding :-)

**Comment by vzarytovskii** [comment]
I can't seem to reproduce it on main anymore:
<img width="410" alt="image" src="https://github.com/dotnet/fsharp/assets/1260985/e3adb685-f3e7-40c0-9b54-5929385a54dd">

Going to close it
