### ISSUE TITLE
Match completeness in isInstance clause

### ISSUE THREAD

**Issue by Swoorup** [dotnet/fsharp#10615]
match statement does seem to be aware that cases are complete in specific situation such as testing for base interface instance.

**Repro steps**

1. Run the following script

```fsharp
type I = interface end
type A = inherit I
let a: A = Unchecked.defaultof<_>
match a with 
| :? I -> ()
```
2. Observe the warning	
![image](https://user-images.githubusercontent.com/3408009/101193428-abd5ed80-36b0-11eb-8380-e258e3fba4ea.png)

**Expected behavior**

`match` shouldn't warn when they are no clauses to fill?

**Actual behavior**
	
```
warning FS0025: Incomplete pattern matches on this expression. For example, the value '( some-other-subtype )' may indicate a case not covered by the pattern(s)
```

**Known workarounds**

Ignore it or Place a never reaching wildcard clause.

**Comment by En3Tho** [comment]
I think the observed behaviour is somewhat right and somewhat wrong. It's a type test pattern and A is not sealed thus in runtime there could be more classes inheriting from A. On the other hand this pattern should always succeed and should shadow any other patterns that go after it anyway.

**Comment by charlesroddie** [comment]
Expected behaviour. Completeness checking obeys quite limited rules. The code `match () with () when true -> ()`, which involves only the most proper constructs, also gives a completeness warning.

**Comment by Swoorup** [comment]
I believe the second warning should not occur as it is upcasting without a when clause. Only down-casting should.

`a :> I` is fine without warning however. It should be a simple check I believe. The wording for first warning message also appears to be off. 

It should likely be `warning FS0067: This type test or upcast will always hold`.

**Comment by cartermp** [comment]
I think this is by design because we don't do exhaustiveness checking on subtype polymorphism (by design, not just as coincidence). So while in theory this shouldn't need it, it's just not something we really do in the compiler. Same can be said for several other corners of the language.
