### ISSUE TITLE
Inconsistency between nameof and normal method invocation when unused generic type parameter is concerned

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#10621]
Consider the following:

```fsharp
type A<'a>() =
    static member P = ()

// Succeeds; no warning, no error
A<_>.P

// Error
nameof A<_>.P |> ignore
```

I cannot take a name of `P` despite being able to call it without issue.

Note that if I remove the type argument, I get this warning:

> The instantiation of the generic type 'A' is missing and can't be inferred from the arguments or return type of this member. Consider providing a type instantiation when accessing this type, e.g. 'A<_>'.

Which is obviously incorrect.

Is the `nameof` behavior by design @dsyme?

**Comment by dsyme** [comment]
Yes this looks like a bug, it should be fixed
