### ISSUE TITLE
Is this fsharpqa testing behaviour expected

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#10623]
@vzarytovskii ,

When running : build -c release -testfsharpqa

I see this output, is it expected?

````
0 tests passed (0%)
0 tests failed (0%)
0 tests were cascaded failures (0%)
0 tests returned "no result" (0%)
0 tests timed out (0%)
0 tests had test errors (0%)
========
0 Total executed tests

72 tests were skipped
========
72 Total tests (executed & skipped)

1s Total time

c:\kevinransom\fsharp>
````

**Comment by vzarytovskii** [comment]
No, that is not expected.
I may have messed up .lst files and runner doesn't "understand" them now.

I would revert my merge for now.

**Comment by vzarytovskii** [comment]
@KevinRansom I have created a revert PR, https://github.com/dotnet/fsharp/pull/10624

Will take a look why it's failing tomorrow.
