### ISSUE TITLE
Active pattern is allowed in `[<Literal>]` binding

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#10647]
Use of an active pattern is allowed in bindings compiled as compile-time literals (and seem to have no effect):
```fsharp
let (|A|) x = x + 1
let [<Literal>] (A x) = 1
```

```
> let (|A|) x = x + 1;;
val ( |A| ) : x:int -> int

> let [<Literal>] (A x) = 1;;
val x : int = 1
```

**Comment by cartermp** [comment]
As per the spec this shouldn't be allowable I guess

**Comment by ErikSchierboom** [comment]
I've opened #10816 to fix this.

**Comment by edgarfgp** [comment]
@vzarytovskii I think this can be closed as the fix has been merged ?
