### ISSUE TITLE
System.String.Split is not available while running fsx with F# 5 code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#10658]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/SystemStringSplit-is-not-available-whi/1278665)._

---
[severity:It's more difficult to complete my work]
Hello!

It looks like System.String.Split method: https://docs.microsoft.com/en-us/dotnet/api/system.string.split?view=net-5.0 is not available for F# REPL (fsx) (VS ver 16.8.2). Here is example script:

```
#r "nuget: Hopac"
#r "nuget: Http.fs"

open Hopac
open HttpFs.Client

let url = "https://www.microsoft.com"

let response =
    Request.createUrl Get url
    |> Request.responseAsString
    |> run
```

Hitting Alt+Enter to run the script gives the following exception:
```
> System.Exception: Exception raised by job ---> System.MissingMethodException: Method not found: 'System.String[] System.String.Split(Char, System.StringSplitOptions)'.
   at *@yyyString cookie)
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 497
   at HttpFs.Client.DotNetWrapper.getCookiesAsMap(HttpResponseMessage response)
   at HttpFs.Client.x2yJ@1-4(HttpResponseMessage response, Stream _arg1)
   at Hopac.Core.ContBind`2.DoCont(Worker& wr, X x) in C:\projects\hopac\Libs\Hopac.Core\Flow\Job.cs:line 49
   at Hopac.Core.TaskToJob`1.DoJob(Worker& wr, Cont`1 xK) in C:\projects\hopac\Libs\Hopac.Core\External\Tasks.cs:line 136
   at Hopac.Core.Worker.RunOnThisThread(Scheduler sr, Work work) in C:\projects\hopac\Libs\Hopac.Core\Engine\Worker.cs:line 100
   --- End of inner exception stack trace ---
   at Hopac.Scheduler.run[x](Scheduler sr, Job`1 xJ) in C:\projects\hopac\Libs\Hopac\Hopac.fs:line 489
```

Having the code above without "#r"s run as a console project works without issues.

---
#### Feedback Bot on 12/6/2020, 11:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by cartermp** [comment]
This one needs to be investigated (cc @KevinRansom)

The packages brought in do not target .NET 5. They are .NET Standard 2.0. And yet an overload only found on .NET Core (and .NET 5) is picked at runtime, leading to a failure.

**Comment by cartermp** [comment]
Tentatively marking as a bug

**Comment by KevinRansom** [comment]
Looking in mscorlib these are the String.Split overloads.
````
public string[] Split(char[] separator, int count);
public string[] Split(char[] separator, StringSplitOptions options);
public string[] Split(string[] separator, StringSplitOptions options);
public string[] Split(char[] separator, int count, StringSplitOptions options);
public string[] Split(string[] separator, int count, StringSplitOptions options);
````

According to [this documentation: ](https://docs.microsoft.com/en-us/dotnet/api/system.string.split?view=net-5.0#System_String_Split_System_Char_System_Int32_System_StringSplitOptions_) the API that takes a char argument was introduced in dot netstandard 2.1 

![image](https://user-images.githubusercontent.com/5175830/101666201-c38bd980-3a02-11eb-8ea4-9f8ef0214fff.png)

Given that the dll references look like standard net472 references and it's an F# assembly, I wonder how it was compiled.

I would say that fsi.exe is doing the right thing by failing, however, it there seems like there may have been an issue in building "C:\Users\codec\.nuget\packages\http.fs\5.4.0\lib\net471\HttpFs.dll" in the first place.

**Comment by KevinRansom** [comment]
Interestingly enough, the F# compiler seems to auto-promote '=' into an array for this Api.

````
open System

[<EntryPoint>]
let main argv =
    let x = "Hello, World"
    let y = x.Split ','
    printfn "%A" y
    0 // return an integer exit code
````

Produces this:
````
    string[] strArray; 
    PrintfFormat<FSharpFunc<string[], Unit>, TextWriter, Unit, Unit> format;
    char[] chArray1 = new char[1]; 
    chArray1[0] = 0x2c;
    strArray = "Hello, World".Split(chArray1);
    format = new PrintfFormat<FSharpFunc<string[], Unit>, TextWriter, Unit, Unit, string[]>("%A");     
    PrintfModule.PrintFormatLineToTextWriter<FSharpFunc<string[], Unit>>(Console.get_Out(), format).Invoke(strArray);
````

This is the code from HttpFs.dll that fails.

````
public override Unit Invoke(string cookie)
{
    string[] strArray;
    strArray = cookie.Split(0x3b, 0);
    this.container.Add(Client.DotNetWrapper.createCookie(this.response.RequestMessage.get_RequestUri(), strArray));
    return null;
}
````
I think whatever the bug is it happened when HttpFs was compiled.

**Comment by cartermp** [comment]
Gotcha, yes this does appear to be an issue in the package itself. A console app targeting .NET Framework 4.7.2 fails with the same error at runtime.

**Comment by KevinRansom** [comment]
Someone from the community should investigate the HttpFs project build, because it is an F# project, and it builds incorrect code that is concerning to me.

**Comment by cartermp** [comment]
Okay, makes sense. I filed this on their end here: https://github.com/haf/Http.fs/issues/172

**Comment by KevinRansom** [comment]
Outstanding.
