### ISSUE TITLE
Parallel.For link broken in Array.Parallel Module in FSharp.Core docs

### ISSUE THREAD

**Issue by nikofeyn** [dotnet/fsharp#10652]
Please provide a succinct description of the issue.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Navigate [here](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-arraymodule-parallel.html).
2. Click any of the Parallel.For links. They all point to a [404](https://docs.microsoft.com/en-us/dotnet/api/system.threading.parallel).

**Expected behavior**

The link should take one to the Parallel.For documentation.

**Actual behavior**

A 404.

**Known workarounds**

Manually search for [Parallel.For](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.parallel.for?view=net-5.0).

**Related information**

The FSharp.Core docs are pulled from the [`array.fsi`](https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSharp.Core/array.fsi) file. The first instance of the Parallel.For reference is [here](https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSharp.Core/array.fsi#L1406).

It looks like the entries of `cref="M:System.Threading.Parallel.For"` should be `cref="M:System.Threading.Tasks.Parallel.For"`, but that's a guess. If it's correct, I don't mind making the change and submitting a pull request.

**Comment by cartermp** [comment]
Thanks @nikofeyn, it's definitely a bug. These should be pointing to `System.Threading.Tasks.Parallel.For`. We'd happily accept a PR!

**Comment by dsyme** [comment]
I'd love to add cref resolution and validation to the doc checking!

**Comment by cartermp** [comment]
Closing as fixed in #10655
