### ISSUE TITLE
CE gives type error, while manual translation does not

### ISSUE THREAD

**Issue by csgordon** [dotnet/fsharp#10660]
F# seems to sometimes give type errors for computation expressions when a manual expansion does not.

**Repro steps**

Example: Compile the following:
```fsharp
type ResultBuilder() =
    member __.Return<'T,'TError>(x:'T) : Result<'T,'TError> = Ok x
    member __.Bind<'TError>(a:Result<string,'TError>, b:string -> Result<unit,'TError>) = 
        match a with
        | Error x -> Error x
        | Ok foo -> b foo

let result = ResultBuilder()

let stuff =
    result {
        do! (Ok "hello") // <-- TYPE ERROR HERE
        return ()
    }
let explicitStuff = result.Bind(Ok "hello", fun _ -> Ok ())
```

**Expected behavior**

I would expect this to compile without issue.

**Actual behavior**

Instead, F# issues two errors on the indicated line of the computation expression:
```
This expression was expected to have type
    'string'    
but here has type
    'unit'    F# Compiler(1)
```
and
```
Incomplete pattern matches on this expression.F# Compiler(25)
```

**Known workarounds**

Manually doing the translation, as in the ```explicitStuff``` line above, makes the error go away. This isn't always workable though; my original use case involved custom operations, and those expansions don't seem to be clearly documented anywhere.

**Related information**

Provide any related information (optional):

* Operating system: MacOS Catalina 15.6
* .NET Runtime kind: .NET Core 5, 5.0.100 with Ionide for VSCode

**Comment by dsyme** [comment]
This is by design, the manual expansion is as follows:

```
let stuff =
    result {
        let! _ = (Ok "hello") 
        return ()
    }
```
