### ISSUE TITLE
Editor (but not compiler) incorrectly flags public auto property with FS1182

### ISSUE THREAD

**Issue by jimfoye** [dotnet/fsharp#10690]
Perhaps this is related to the Find References bug(s) that I constantly hit in VS. 

Here's my property definition:

![image](https://user-images.githubusercontent.com/4249676/101952189-db5b8d00-3bbd-11eb-8752-8bdd68373a4f.png)

It's flagged as unused in the editor, but it is referenced elsewhere and the code compiles with no warnings.

For completeness, here's the result of Find References (which is wrong, obviously)

![image](https://user-images.githubusercontent.com/4249676/101952290-0b0a9500-3bbe-11eb-9dac-67879b75213c.png)

This is Visual Studio 16.8.3 running on W7, the application targets .NET Framework 4.7.2.

Signed,
Caveman Lawyer

**Comment by cartermp** [comment]
This particular case is unrelated to find refs, which is tracked here: https://github.com/dotnet/fsharp/issues/9984

Note that the behavior for the autoprop in find refs is:

* Find usages when you are at one of the usages, but shows no definition
* Does not find usages if you execute it from the definition

**Comment by jimfoye** [comment]
Super, thanks for the quick fix!
