### ISSUE TITLE
Implementing quick actions/lightbulbs à la C#

### ISSUE THREAD

**Issue by kerams** [dotnet/fsharp#10702]
@cartermp's [post](https://phillipcarter.dev/posts/how-to-make-an-fsharp-codefixer.html) describes the implementation of code fixers that appear to only trigger on specific warning/error IDs. My question is how I'd go about creating a quick action not tied to a warning, but which would pop up and the user would be able to click based on the caret position/context.

In C# for instance, moving the caret onto `GiveMe5` in this snippet

```csharp
public int GiveMe5()
{
    return 5;
}
```

triggers the `To expression body` quick action, which refactors the method into this when clicked

```csharp
public int GiveMe5() => 5;
```

In F# you could for example define a refactoring that would turn a tuple-arged function into its curried form (and try to change every callsite accordingly)

```fsharp
let add3 (a, b, c) = a + b + c
// turns into
let add3 a b c = a + b + c
```

Are the necessary APIs at all available to FSharp.Editor?

**Comment by cartermp** [comment]
Those aren't quick fixes, they're actually refactorings. It would be possible to implement by creating a new component that inherits from [`CodeRefactoringProvider`](http://sourceroslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeRefactorings/CodeRefactoringProvider.cs,30a74d793255b8d7). It just hasn't been done yet.

**Comment by kerams** [comment]
So one just has to inherit from `CodeRefactoringProvider`, use `ExportCodeRefactoringProviderAttribute` and `context.RegisterRefactoring`. Everything else from your blog post can then be reused to produce a context lightbulb with a refactoring action. Very cool, thanks.

**Comment by cartermp** [comment]
So I do have some bad news, sadly: https://github.com/dotnet/fsharp/issues/3750#issuecomment-745728280

It won't exactly be easy to support refactorings.

**Comment by kerams** [comment]
Yes, I understood we're at the mercy of half-assed syntax tree to range to text replacements for edits.
