### ISSUE TITLE
Add invalidation debug info to type check results

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#10739]
It'd really help diagnose type checker results invalidation/reuse if FSharpCheckFileResults provided info like

* previous info is reused
* invalidated files/projects due to timestamp changes
* actual check timestamp (not changed if previous results are used)
* timestamp of previous files/projects in the graph

@TIHan how difficult would it be to add it to the new background builder framework?

**Comment by dsyme** [comment]
Closing this old issue - @auduchinok if you'd like something like this please submit a PR for it? thanks :)

**Comment by auduchinok** [comment]
> @auduchinok if you'd like something like this please submit a PR for it? 

@dsyme Thanks, it might be very useful to have such diagnostics for some investigations, but after https://github.com/dotnet/fsharp/pull/9300 I'm afraid it's likely that such APIs will have to be maintained in an FCS fork, and right now we don't have a strong enough need for it to worth diverging from upstream even further.
