### ISSUE TITLE
F# 5.0 regression, FS5 sample project no longer builds.  CE's broken.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#10734]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/F-50-regression-FS5-sample-project-no/1286065)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:16.8.3]
Visual Studio 16.9.0 Preview 2 can no longer build the fs5sample project (https://github.com/cartermp/fs5-samples.git) as custom keywords in computation expressions (CE's) no longer seem to support optional parameters.

Intellisense is also showing the errors.

But the project will build successfully from the command line (dotnet build), using the installed .net 5.0.200-preview.20601.7

And the same project will also edit and build ok using Visual Studio 16.8.3

---
#### Feedback Bot on 12/13/2020, 09:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by cartermp** [comment]
Confirmed on latest dogfood as well, something has regressed here. cc @KevinRansom and @dsyme , who coordinated to make the feature preview and resolve some problems with it
