### ISSUE TITLE
[Loc] Localization issue

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/fsharp#10757]
. | .
-- | --
String Resource ID | 0; "RemoveYieldBang"
Source String | Remove yield!'
Filename | src\FSharp.Editor\xlf\FSharp.Editor.xlf
Question | It seems to be missing a beginning "'". Could you either remove the quote or insert the quote at the beginning? Or is it  partial string (and what would be the entire text)?

**Comment by cristianosuzuki77** [comment]
vcq 349584

**Comment by cartermp** [comment]
@cristianosuzuki77 thanks, there is a missing `'` for `'yield!'`. I have a fix coming.
