### ISSUE TITLE
Updating library versions in fsproj (outside of VS?) cause NU1603

### ISSUE THREAD

**Issue by BentTranberg** [dotnet/fsharp#10767]
My solution use VisualSVN as VCS in VS 2019. After upgrading from DevExpress WPF 20.2.3 to 20.2.4 on one computer, then committing that change in VisualSVN, and then updating with VisualSVN on another computer, I get this when I try to compile in VS on that other computer.

![image](https://user-images.githubusercontent.com/15068882/102766213-14de8600-437e-11eb-9201-40478f19af1e.png)

TdKlient.Models and TdDocConv are F# libraries. TdKlient is a C# WPF application that uses TdKlient.Models.

I try a Rebuild, but still get the same. I try to delete bin and obj folders, but still get the same. Then I try to restart VS. That finally solves the issue - no errors or warnings.

I believe I've seen the same behavior with other libraries coming through NuGet, so I don't think this is related to the DevExpress WPF library that is installed.

I am not at all convinced that VisualSVN is causing the problem directly. I am thinking that although this happens after updating the source using VisualSVN, what has happened is only that files on disk has been modified. Unlike some weird VCS's, and like GIT, VisualSVN doesn't meddle with your local source files in any way at all when you are not explicitly running a command.

I suspect the problem is rather that VS itself somehow remember the old version of the DevExpress library, until VS is restarted. It is possible then that VisualSVN is causing the problem by not doing something that should have been done. Not doing a refresh or something like that.

Next time this happens, I intend to update the source files outside of VS in order to update the DevExpress library in the fsproj files, while the solution is open in VS. Then I will compile or rebuild in VS. This can give a better indication of whether VisualSVN is somehow directly involved by messing up something, or just not doing a refresh or whatever.

Why do I report this in the dotnet/fsharp repo? Because there is a long history with other issues with similar complications here, and so I have a rather strong feeling this can be tied to F# in VS, and not just VS in general. To be fair, VisualSVN already has other issues specific to F#.

TargetFramework is netcoreapp3.1

FSharp.Core is v 5.0.0

**Comment by cartermp** [comment]
I think this is more likely to be an issue related to VS nuget tooling than anything else, but I can't say for sure

**Comment by BentTranberg** [comment]
Give me a chance to do some more research on this before I'm back at work on 4th Jan. Hoping I'll find the time. I'll create a minimal repro with a solution with independent F# and C# projects, not using VisualSVN, and using a free library from NuGet. This way it should be possible to reproduce this repeatedly without hassle. If the problem only surfaces for an F# project, and not a C# project, then I guess it will be of interest here. Otherwise I guess next stop will be another repo/team.

**Comment by BentTranberg** [comment]
This seems to happen when updates to libraries comes from new package sources, which is the case when I upgrade the DevExpress libraries with installers. I agree, it's likely VS nuget tooling. I'm closing this.
