### ISSUE TITLE
Where is the List module documentation?

### ISSUE THREAD

**Issue by rlundy** [dotnet/fsharp#10764]
I could swear there used to be a separate documentation page for each List module function, such as List.fold or List.rev, explaining clearly what the function does and giving examples.

Now, in December 2020, for anything I search, e.g. `f# list fold`, I get this page:

https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/lists

That page doesn't have anything about the List module.  In the first paragraph it has a link to this page:

https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-listmodule.html

But this page just has the same info as Intellisense, so it's no help at all.

Does that detailed documentation not exist anymore?  Or am I just imagining that it ever did?

**Comment by ScottHutchinson** [comment]
The page https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/lists **does** have a lot of information about functions in the List module. However, I think you are correct that there was probably documentation on the old MSDN site that has not been migrated to the new site. And I don't know how to find that information anymore. It would definitely help us to improve the new documentation, if we had a link to the old MSDN docs to use as a draft.

**Comment by cartermp** [comment]
The API reference doesn't have samples, but it is the API reference. There used to be an old MSDN site that was built for FSharp.Core 4.0 but it was shut down with the rest of MSDN. The way forward is to continue to improve the existing conceptual documentation you've linked (which does have an explanation and example of folds) and work with https://github.com/fsharp/fsharp-core-docs to figure out how to embed samples into the API reference if it makes sense.

**Comment by rlundy** [comment]
@cartermp For anyone using VS, the API reference is useless, because there's no additional information in it.  I believe **undocumentation** is the popular term.  We go to documentation to find out things we _couldn't_ know from the IDE.
