### ISSUE TITLE
FSI appears to have a 4097 char line limit

### ISSUE THREAD

**Issue by jwosty** [dotnet/fsharp#10765]
Please provide a succinct description of the issue.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Write (or generate :) ) a line of code that is over 4097 characters long (for example: https://gist.github.com/jwosty/7c24c13380fd06f515d9ff980f2d57e7)
2. Send the line to FSI and observe it stop parsing at char 4097, effectively cutting the line short

**Expected behavior**

FSI successfully parses and evaluates the line just like the F# compiler does.

**Actual behavior**

In this case, FSI says:

    Warning: line too long, ignoring some characters

      ;;
      ^^

    Script.fsx(20,4097): error FS0010: Unexpected infix operator in binding. Expected '|]' or other token.

If you do this in VS Code (Ionide) or paste it directly into a ``dotnet fsi`` session in a terminal, this shows up before the error:

    Warning: line too long, ignoring some characters

**Known workarounds**

Break the line onto multiple lines like a normal person, or load the script in question in with ``#load``.

**Related information**

Provide any related information (optional):

* Windows 10
* .NET 5
* Visual Studio Community 2019, Visual Studio Code (Ionide), ``dotnet fsi``

**Comment by jwosty** [comment]
Seems that there are dedicated error messages for this. Is this documented somewhere, or technically a bug?

**Comment by cartermp** [comment]
Yeah, I think this is a core issue in fslex itself. @dsyme can you confirm that if there is a fix required here, it would be in fslex?

**Comment by cartermp** [comment]
Will close this out as external to this repo, please feel free to take a look at fslexyacc. I can look at a PR and perhaps tag more folks there.
