### ISSUE TITLE
#r nuget-referenced assemblies aren't added to `FSharpProjectContext.GetReferencedAssemblies()`

### ISSUE THREAD

**Issue by baronfel** [dotnet/fsharp#10762]
I was working on expanding FSAC support for offering `open` codefixes for namespaces that contain extension members when you use the extension members without having the proper namespace opened and I found during my testing that references added via `#r nuget` aren't added to the list of `FSharpAssembly` items that are available from `FSharpProjectContext.GetReferencedAssemblies()`.

Direct references are made available.

**Repro steps**

Attached is a small self-contained repro that illustrates the problem. You'll have to change the file path in the #r in `Scripts/ScriptR.fsx` to your home directory after you perform a `dotnet restore` in order to get the library in the correct location, but after that a `dotnet run` should show that the Dapper dll is in `ScriptR.fsx` but not `ScriptNuget.fsx`.

**Expected behavior**

#r nuget dependencies are part of the logical project's assemblies for the script file.

**Actual behavior**

#r  nuget dependencs cannot be found for a script file

**Known workarounds**

Don't use #r nuget in script files (kinda defeats the point)

**Related information**

Provide any related information (optional):

* Operating system: MacOS (the one before big sur)
* .NET Runtime kind: .net 5.0.100
* Editing Tools: VS Code, Ionide 5 preview 3 (though that's not relevant because the repo is in FCS)

[demo.zip](https://github.com/dotnet/fsharp/files/5718877/demo.zip)

**Comment by baronfel** [comment]
It _seems_ like the `Resolutions` from the `IResolveDependenciesResult` should be added to the `tcConfigB` in or around the same places that `Roots` and `SourceFiles` from the same type are (perhaps [in FSI](https://github.com/dotnet/fsharp/blob/main/src/fsharp/fsi/fsi.fs#L1500-L1509) or in [ScriptClosure](https://github.com/dotnet/fsharp/blob/main/src/fsharp/ScriptClosure.fs#L256-L273)) but I'm not sure if this is the best place.  If I can get a pointer to where the appropriate place (or the general mechanism for adding more references to tcConfigB?) is I'd be willing to work on the fix.

**Comment by cartermp** [comment]
Looks like there's a legit bug here, the quick fix does not trigger in latest VS dogfood bits for 16.9 either:

![image](https://user-images.githubusercontent.com/6309070/102680318-03259480-416c-11eb-8539-51206c50f76b.png)

**Comment by cartermp** [comment]
cc @KevinRansom

**Comment by cartermp** [comment]
https://github.com/dotnet/fsharp/pull/10763 fixes the underlying issue, so I'll close. As mentioned in the PR, once FCS knows about the underlying dll, it will then know the symbols it can forward to any code fixer.
