### ISSUE TITLE
Using latest FCS and Microsoft.Build.Locator can lead an a warning

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#10792]
I got this when trying to build the latest FSAutoComplete on my machine, which also has Microsoft.Build.Locator, leads to this issue:

`
Error: C:\Users\phcart\.nuget\packages\microsoft.build.locator\1.3.2\build\Microsoft.Build.Locator.targets(20,5): error : A PackageReference to Microsoft.Build.* without ExcludeAssets="runtime" exists in your project. This will cause MSBuild assemblies to be copied to your output directory, causing your application to load them at runtime. To use the copy of MSBuild registered by MSBuildLocator, set ExcludeAssets="runtime" on the MSBuild PackageReferences. To disable this check, set the property DisableMSBuildAssemblyCopyCheck=true in your project file (not recommended as you must distributed all of MSBuild + associated toolset). Package(s) referenced: Microsoft.Build.Tasks.Core
`

I'm not sure if this is an issue or not.

**Comment by baronfel** [comment]
Latest FCS includes an msbuild dependency that we have to add an explicit 'copy_local: true' for like the other msbuild deps, since we'll be delegating to the users installed msbuild.  The exact package  is MS.Build.Tasks.Core, after you add it the build will work.
