### ISSUE TITLE
F# #r nuget failure in Visual Studio

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#10803]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/F-r-nuget-failure-in-Visual-Studio/1294175)._

---
[severity:It bothers me. A fix would be nice]
I'm using Visual Studio 16.8.3. I have an F# script that starts like this: 

#r "nuget: System.DirectoryServices.AccountManagement"
open System.DirectoryServices.AccountManagement

It yields the following error:
error FS0039: The namespace 'DirectoryServices' is not defined.

---
#### Feedback Bot on 12/22/2020, 06:42 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by cartermp** [comment]
cc @dsyme and @KevinRansom 

I confirmed that with 16.9 previews with .NET Core scripting turned on I can actually execute this code in FSI, but the editor still shows red squiggles. So we have some kind of a mismatch going on still.

**Comment by cartermp** [comment]
A relevant detail is that this package is multi-targeted and will prefer the netcoreapp2.0 target rather than the .NET Standard target

**Comment by KevinRansom** [comment]
Works now, must have been fixed.

````
c:\Temp>dotnet fsi

Microsoft (R) F# Interactive version 12.0.0.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> #r "nuget: System.DirectoryServices.AccountManagement"
- open System.DirectoryServices.AccountManagement
-
- ;;
[Loading C:\Users\codec\AppData\Local\Temp\nuget\19300--94361ee8-3bb7-42c3-8bc2-d25a91bb4de0\Project.fsproj.fsx]
namespace FSI_0002.Project

>
````
