### ISSUE TITLE
Gaps in XML Documentation validity checking around pattern-parameters and constructor args

### ISSUE THREAD

**Issue by baronfel** [dotnet/fsharp#10809]
It is possible to write legal code that fails XML documentation validation

**Repro steps**

given the following script saved as `script.fsx`

```fsharp

type Thing = Inner of string

/// <summary>does the thing</summary>
/// <param name="s">the thing to do!</param>
let doer (Thing.Inner s) = ()

/// <summary>gives you a friendly greeting</summary>
/// <param name="pal">your good mate</param>
type Buddy(pal: string) = 
    do
        printfn $"hi, {pal}"
```

and the fsi in the .net 5.0.100 SDK, the command `dotnet fsi --warnon:3390 script.fsx` results in two spurious warnings:

```
/script.fsx(3,1): warning FS3390: This XML comment is invalid: unknown parameter 's'
/script.fsx(7,1): warning FS3390: This XML comment is invalid: unknown parameter 'pal'
```

One for the mismatched parameter in the pattern-matched function argument, and one for the constructor parameter.

**Expected behavior**

No errors are printed.

**Actual behavior**

The above warnings are printed.

**Known workarounds**

The first error can be worked around by performing the extraction inside the function body.
The second error cannot be worked around in code, to my knowledge.
Both can be mitigated by turning 3390 off for the file, though this is a scattershot approach in my view.

**Related information**

Provide any related information (optional):

* Operating system: MacOS
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .Net 5.0.101
* Editing Tools (e.g. Visual Studio Version, Visual Studio): only dotnet fsi

**Comment by cartermp** [comment]
Closin'
