### ISSUE TITLE
point free style fails at type inference

### ISSUE THREAD

**Issue by pangwa** [dotnet/fsharp#10813]
Please provide a succinct description of the issue.

**Repro steps**
below code can't compiles
```fsharp
// let unwordList list = list |> List.map (fun v -> v.ToString()) |> String.concat " " // this line works
let unwordList = List.map (fun v -> v.ToString()) >> String.concat " "

type AList = 
    | NestList of List<AList>
    | ANumber of int32

        override this.ToString () = 
            match this with
            | ANumber n -> sprintf "%d" n
            | NestList l -> unwordList l

```
[hello-world.zip](https://github.com/dotnet/fsharp/files/5749352/hello-world.zip)

**Expected behavior**
This should compiled like the non point-free version.

**Actual behavior**
Compile failed with FS0966

```
hello-world/Program.fs(8,6): error FS0966: 类型“AList”的使用方式无效。“AList”之前的值具有一个与“AList”相关的推理类型，这是无效的前向引用。 [hello-world/hello-world.fsproj]
```
**Known workarounds**

Provide a description of any known workarounds.
Using the non point-free version could compile.

**Related information**

Provide any related information (optional):

* Operating system
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .Net Framework 5.0.101

**Comment by cartermp** [comment]
This is by design as a value restriction error. You can read more about it here:

https://kwangyulseo.com/2015/01/23/value-restriction-of-f/
https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/generics/automatic-generalization#value-restriction
