### ISSUE TITLE
Is the il generated by this fixed code normal?

### ISSUE THREAD

**Issue by 2A5F** [dotnet/fsharp#10832]
Is the il generated by this fixed code normal?

```fs
let some (arr: int array) =
    use ptr = fixed arr
    printf $"{ptr}"
    ()
```
![a](https://user-images.githubusercontent.com/13982338/103459556-5b06f280-4d4b-11eb-8df5-41ebc504499b.png)
![b](https://user-images.githubusercontent.com/13982338/103459558-5d694c80-4d4b-11eb-9f7e-758a115e1580.png)

<details>
<summary>ILCode</summary>

```il
// Token: 0x06000001 RID: 1 RVA: 0x00002050 File Offset: 0x00000250
.method public static 
	void some (
		int32[] arr
	) cil managed 
{
	// Header Size: 12 bytes
	// Code Size: 74 (0x4A) bytes
	// LocalVarSig Token: 0x11000004 RID: 4
	.maxstack 7
	.locals init (
		[0] native int ptr,
		[1] int32& pinned,
		[2] class [FSharp.Core]Microsoft.FSharp.Core.PrintfFormat`4<class [FSharp.Core]Microsoft.FSharp.Core.Unit, class [System.Runtime]System.IO.TextWriter, class [FSharp.Core]Microsoft.FSharp.Core.Unit, class [FSharp.Core]Microsoft.FSharp.Core.Unit>
	)

	/* (6,5)-(6,24) D:\Proj\NetProj\TestNet5\TestNet5Fs\Library.fs */
	/* 0x0000025C 02           */ IL_0000: ldarg.0
	/* 0x0000025D 2C17         */ IL_0001: brfalse.s IL_001A

	/* (hidden)-(hidden) D:\Proj\NetProj\TestNet5\TestNet5Fs\Library.fs */
	/* 0x0000025F 02           */ IL_0003: ldarg.0
	/* 0x00000260 8E           */ IL_0004: ldlen
	/* 0x00000261 69           */ IL_0005: conv.i4
	/* 0x00000262 2C0D         */ IL_0006: brfalse.s IL_0015

	/* (hidden)-(hidden) D:\Proj\NetProj\TestNet5\TestNet5Fs\Library.fs */
	/* 0x00000264 02           */ IL_0008: ldarg.0
	/* 0x00000265 16           */ IL_0009: ldc.i4.0
	/* 0x00000266 8F10000001   */ IL_000A: ldelema   [System.Runtime]System.Int32
	/* 0x0000026B 0B           */ IL_000F: stloc.1
	/* 0x0000026C 07           */ IL_0010: ldloc.1
	/* 0x0000026D D3           */ IL_0011: conv.i
	/* (hidden)-(hidden) D:\Proj\NetProj\TestNet5\TestNet5Fs\Library.fs */
	/* 0x0000026E 00           */ IL_0012: nop
	/* 0x0000026F 2B08         */ IL_0013: br.s      IL_001D

	/* (hidden)-(hidden) D:\Proj\NetProj\TestNet5\TestNet5Fs\Library.fs */
	/* 0x00000271 16           */ IL_0015: ldc.i4.0
	/* 0x00000272 D3           */ IL_0016: conv.i
	/* (hidden)-(hidden) D:\Proj\NetProj\TestNet5\TestNet5Fs\Library.fs */
	/* 0x00000273 00           */ IL_0017: nop
	/* 0x00000274 2B03         */ IL_0018: br.s      IL_001D

	/* (hidden)-(hidden) D:\Proj\NetProj\TestNet5\TestNet5Fs\Library.fs */
	/* 0x00000276 16           */ IL_001A: ldc.i4.0
	/* 0x00000277 D3           */ IL_001B: conv.i
	/* (hidden)-(hidden) D:\Proj\NetProj\TestNet5\TestNet5Fs\Library.fs */
	/* 0x00000278 00           */ IL_001C: nop

	/* (hidden)-(hidden) D:\Proj\NetProj\TestNet5\TestNet5Fs\Library.fs */
	/* 0x00000279 0A           */ IL_001D: stloc.0
	/* (7,5)-(7,20) D:\Proj\NetProj\TestNet5\TestNet5Fs\Library.fs */
	/* 0x0000027A 7201000070   */ IL_001E: ldstr     "%P()"
	/* 0x0000027F 17           */ IL_0023: ldc.i4.1
	/* 0x00000280 8D01000001   */ IL_0024: newarr    [System.Runtime]System.Object
	/* 0x00000285 25           */ IL_0029: dup
	/* 0x00000286 16           */ IL_002A: ldc.i4.0
	/* 0x00000287 06           */ IL_002B: ldloc.0
	/* 0x00000288 8C11000001   */ IL_002C: box       [netstandard]System.IntPtr
	/* 0x0000028D A401000001   */ IL_0031: stelem    [System.Runtime]System.Object
	/* 0x00000292 14           */ IL_0036: ldnull
	/* 0x00000293 730B00000A   */ IL_0037: newobj    instance void class [FSharp.Core]Microsoft.FSharp.Core.PrintfFormat`5<class [FSharp.Core]Microsoft.FSharp.Core.Unit, class [System.Runtime]System.IO.TextWriter, class [FSharp.Core]Microsoft.FSharp.Core.Unit, class [FSharp.Core]Microsoft.FSharp.Core.Unit, native int>::.ctor(string, object[], class [System.Runtime]System.Type[])
	/* 0x00000298 0C           */ IL_003C: stloc.2
	/* 0x00000299 280C00000A   */ IL_003D: call      class [netstandard]System.IO.TextWriter [netstandard]System.Console::get_Out()
	/* 0x0000029E 08           */ IL_0042: ldloc.2
	/* 0x0000029F 280100002B   */ IL_0043: call      !!0 [FSharp.Core]Microsoft.FSharp.Core.PrintfModule::PrintFormatToTextWriter<class [FSharp.Core]Microsoft.FSharp.Core.Unit>(class [System.Runtime]System.IO.TextWriter, class [FSharp.Core]Microsoft.FSharp.Core.PrintfFormat`4<!!0, class [System.Runtime]System.IO.TextWriter, class [FSharp.Core]Microsoft.FSharp.Core.Unit, class [FSharp.Core]Microsoft.FSharp.Core.Unit>)
	/* 0x000002A4 26           */ IL_0048: pop
	/* (8,5)-(8,7) D:\Proj\NetProj\TestNet5\TestNet5Fs\Library.fs */
	/* 0x000002A5 2A           */ IL_0049: ret
} // end of method Test::some
```

</details>

**Related information**

* .Net 5
* Decompiled by dnSpy 6.1.8

**Comment by abelbraaksma** [comment]
What is the part that you but don't find normal? It looks typical to me, and comforting that the code prevents you from getting the address of an empty array (which wouldn't be very meaningful). But maybe I misunderstand what the part is that you're confused about ;).

**Comment by vzarytovskii** [comment]
As @abelbraaksma said, it looks fine, maybe a bit "verbose" with nested if conditions, which can be joined, since the else branch is the same.

Is there something in particular which looks wrong to you?

**Comment by 2A5F** [comment]
@abelbraaksma @vzarytovskii 
The fixed block is too short to include the following use

**Comment by abelbraaksma** [comment]
Not sure why, but on my mobile I don't see anything after the words "following use". So I can't quite get what you mean (and how "too short" relates to this, surely you don't want more verbosity?)

**Comment by 2A5F** [comment]
Maybe because of Google Translate
I expect 
```cs
fixed (ptr = array) {
  printf(ptr)
}
```

**Comment by vzarytovskii** [comment]
Interesting, it seems it's different codegen for arrays since it works for strings (i.e. puts everything in fixed block):

```fsharp
let some (a: string) =
    use ptr = fixed a
    printfn "%A" ptr
    ()
```
resulted in
```csharp
public unsafe static void some(string a)
{
    fixed (char* ptr = a)
    {
        IntPtr func = (IntPtr)(void*)((a == null) ? a : ((object)((long)(IntPtr)(void*)a + (long)RuntimeHelpers.OffsetToStringData)));
        PrintfFormat<FSharpFunc<IntPtr, Unit>, TextWriter, Unit, Unit> format = new PrintfFormat<FSharpFunc<IntPtr, Unit>, TextWriter, Unit, Unit, IntPtr>("%A");
        PrintfModule.PrintFormatLineToTextWriter(Console.Out, format).Invoke(func);
    }
}
```

However for any array type, it is resulting in different code:
```fsharp
let some (a: char[]) =
    use ptr = fixed a
    printfn "%A" ptr
    ()
```

```csharp
public unsafe static void some(char[] a)
{
    IntPtr intPtr;
    if (a != null)
    {
        if (a.Length != 0)
        {
            reference = ref a[0];
            intPtr = (IntPtr)(&reference);
        }
        else
        {
            intPtr = (IntPtr)0;
        }
    }
    else
    {
        intPtr = (IntPtr)0;
    }
    IntPtr func = intPtr;
    PrintfFormat<FSharpFunc<IntPtr, Unit>, TextWriter, Unit, Unit> format = new PrintfFormat<FSharpFunc<IntPtr, Unit>, TextWriter, Unit, Unit, IntPtr>("%A");
    PrintfModule.PrintFormatLineToTextWriter(Console.Out, format).Invoke(func);
}
```

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEAzAzgHwxgBcACXCAWxlIAoBDEc4qASwDsBzASlIF4AsAChSo0gFdcNAA4t+pbKwQwAJqXrCxpaW3bFs7UgCIApAEEj2lprG1uQA

**Comment by greatim** [comment]
> Interesting, it seems it's different codegen for arrays since it works for strings (i.e. puts everything in fixed block):
> 
> ```fsharp
> let some (a: string) =
>     use ptr = fixed a
>     printfn "%A" ptr
>     ()
> ```
> 
> resulted in
> 
> ```cs
> public unsafe static void some(string a)
> {
>     fixed (char* ptr = a)
>     {
>         IntPtr func = (IntPtr)(void*)((a == null) ? a : ((object)((long)(IntPtr)(void*)a + (long)RuntimeHelpers.OffsetToStringData)));
>         PrintfFormat<FSharpFunc<IntPtr, Unit>, TextWriter, Unit, Unit> format = new PrintfFormat<FSharpFunc<IntPtr, Unit>, TextWriter, Unit, Unit, IntPtr>("%A");
>         PrintfModule.PrintFormatLineToTextWriter(Console.Out, format).Invoke(func);
>     }
> }
> ```
> 
> However for any array type, it is resulting in different code:
> 
> ```fsharp
> let some (a: char[]) =
>     use ptr = fixed a
>     printfn "%A" ptr
>     ()
> ```
> 
> ```cs
> public unsafe static void some(char[] a)
> {
>     IntPtr intPtr;
>     if (a != null)
>     {
>         if (a.Length != 0)
>         {
>             reference = ref a[0];
>             intPtr = (IntPtr)(&reference);
>         }
>         else
>         {
>             intPtr = (IntPtr)0;
>         }
>     }
>     else
>     {
>         intPtr = (IntPtr)0;
>     }
>     IntPtr func = intPtr;
>     PrintfFormat<FSharpFunc<IntPtr, Unit>, TextWriter, Unit, Unit> format = new PrintfFormat<FSharpFunc<IntPtr, Unit>, TextWriter, Unit, Unit, IntPtr>("%A");
>     PrintfModule.PrintFormatLineToTextWriter(Console.Out, format).Invoke(func);
> }
> ```
> 
> https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEAzAzgHwxgBcACXCAWxlIAoBDEc4qASwDsBzASlIF4AsAChSo0gFdcNAA4t+pbKwQwAJqXrCxpaW3bFs7UgCIApAEEj2lprG1uQA

No, I think it's only because you didn't accessed the `IntPtr`, and print it's value only. Try this:

```
   let foo(x: int[]) =
      use x = fixed x
      Console.WriteLine x
```
It generate：
```
public unsafe static void foo2(int[] x)
{
	nint num;
	IntPtr x2;
	if (x != null)
	{
		if (x.Length != 0)
		{
			fixed (int* ptr = &x[0])
			{
				num = (x2 = (nint)ptr);
				Console.WriteLine(x2);
			}
			return;
		}
		num = 0;
	}
	else
	{
		num = 0;
	}
	x2 = num;
	Console.WriteLine(x2);
}
```
`fixed` should minimize the scope of `Pin`. Different results mean that F# can determine that `printf` is read-only.

**Comment by vzarytovskii** [comment]
@greatim thanks for checking it, I thought something like this may be happening. 
Gonna look tomorrow, how is it working exactly.

**Comment by 2A5F** [comment]
@greatim 

It’s not actually generated like that

```cs
public unsafe static void some(int[] a)
    {
        IntPtr intPtr;
        if (a != null)
        {
            if (a.Length != 0)
            {
                reference = ref a[0];
                intPtr = (IntPtr)(&reference);
            }
            else
            {
                intPtr = (IntPtr)0;
            }
        }
        else
        {
            intPtr = (IntPtr)0;
        }
        IntPtr intPtr2 = intPtr;
        Console.WriteLine(intPtr2);
    }
```

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEAzAzgHwgAcYA7AAgGUBPXAFxgFsBYAKHI/LYxjvNwiMY5ABQBDEOQCWpOgG0AugEpyAXjadyAV1zCidKGvLYpCGABNyYjZwDCEUgJ4A6AOpQpDADIy9BmxwiSkA

**Comment by greatim** [comment]
@2A5F 
I don't know [sharplab.io](https://sharplab.io/) how working.
But on my local computer, it is like this
```
public unsafe static void some(int[] a)
{
	nint num;
	IntPtr ptr;
	if (a != null)
	{
		if (a.Length != 0)
		{
			fixed (int* ptr2 = &a[0])
			{
				num = (ptr = (nint)ptr2);
				Console.WriteLine(ptr);
			}
			return;
		}
		num = 0;
	}
	else
	{
		num = 0;
	}
	ptr = num;
	Console.WriteLine(ptr);
}
```

**Comment by greatim** [comment]
![image](https://user-images.githubusercontent.com/5526875/103474416-9ef70780-4dde-11eb-956d-5bf4c97b52e2.png)

**Comment by abelbraaksma** [comment]
Don't compare C# decompiling as gospel. There are many ways to write the same code in C# that gives (roughly or precisely) the same IL.

I'm still wondering what's wrong with the code. What part is causing problems? Do note that F# is mostly null+safe. Comparing it one to one with C# is comparing apples with pears. Comparing transpiled C# with direct C# is comparing an apple turned to mush and reconfigured to look like a pear ;).

That said, it's perfectly possible there's something amiss here, but then let's focus on the IL and specifically the part that you think should be done differently and why.
