### ISSUE TITLE
January 2021 rough work list

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#10844]
And we're back with the new year. Here it is:

Stuff that matters w.r.t shipping:

- [x] Ensure dotnet/sdk and dotnet/installer are up to date with actual updated compiler bits to align with .NET and VS update (https://github.com/dotnet/sdk/pull/15020)
- [x] Finalize https://github.com/dotnet/fsharp/milestone/29 closed issues and ensure they are in 16.9 release
- [x] Complete the remaining open items in https://github.com/dotnet/fsharp/milestone/38
- [x] Ensure loc changes are in and stable

Non-16.9 to work on:

- [ ] @cartermp - get inline hints completed with options
- [x] @tihan - Explore implementing union case generation in pattern match expressions - spike on the pieces needed to build this correctly are
- [ ] @vzarytovskii - complete file system shim refactoring work and explore snapshot-based work with aims to help https://github.com/dotnet/fsharp/issues/2204
- [x] @KevinRansom - work towards building on FSharp.Compiler.Service
- [ ] Burn down https://github.com/dotnet/fsharp/milestone/39 to 0
- [x] Bug fix work as it comes in

**Comment by kerams** [comment]
Does the second item in the second list have to do with https://github.com/dotnet/fsharp/discussions/10758 to a certain extent? How much priority (approximately) does it have in the wider context of things to do?

**Comment by cartermp** [comment]
@kerams yes it does. It's quite high priority, since we need to spike on a complicated feature like that to identify all of the gaps we have in the compiler service and build out the necessary infrastructure.

**Comment by cartermp** [comment]
Closing out
