### ISSUE TITLE
Reconsider indentation warnings inside pattern match destructing.

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#10851]
**Is your feature request related to a problem? Please describe.**
I'm not 100% sure if this is a bug or a feature but I wish to report a case where I question the warnings that are generated by the compiler.
This is a follow-up to the conversation in https://github.com/dotnet/docs/issues/22197.

Recap:
The indentation is of `timestamp` in the example below is now dictated by the length of `CaseEvent`:
```fsharp
let (|IsCustomerAnsweredTreatmentsQuestion|_|) =
    function
    | CaseEvent (caseId,
                 timestamp,
                 CaseEventType.CustomerAnsweredTreatmentsQuestion (questionId,
                                                                   healthcareProviders)) ->
        Some(caseId, timestamp, (questionId, healthcareProviders))
    | _ -> None
```

The style guide does not recommend this and would more go for something like:

```fsharp
let (|IsCustomerAnsweredTreatmentsQuestion|_|) =
    function
    | CaseEvent(
          caseId,
          timestamp,
          CaseEventType.CustomerAnsweredTreatmentsQuestion(
              questionId,
              healthcareProviders
          )
      ) -> Some(caseId, timestamp, (questionId, healthcareProviders))
    | _ -> None
```

The indentation of `timestamp` is now not related to the length of any chosen name.
However, this leads to the following warnings in F#:
![image](https://user-images.githubusercontent.com/2621499/104002073-d7149680-51a0-11eb-8aa1-705490aee9db.png)

**Describe the solution you'd like**
I'm wondering if we can remove the warnings generated in this case. As the AST tree can be constructed without a problem.

**Describe alternatives you've considered**
Accept what we have today and document this in the F# style guide.

**Additional context**
Related Fantomas issue: https://github.com/fsprojects/fantomas/issues/1303

**Comment by auduchinok** [comment]
Seems related to https://github.com/dotnet/fsharp/pull/6808.

**Comment by nojaf** [comment]
This was fixed by @Happypig375. [See example](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQ2wAuYAFAB8AkmgDCAVzQ9WAW1gAnAILI0Ad0WxoAFQWwqPech5oAihPQ9ErZIID6ggJRgAvAB0Fb5BAjwJyZisbDy8fMEEwMSp6AFEAN1hjfhDvMLTmaNhhaFwUtLSreWkqWQAHXM9U-Igo2ITjbQBPUtgAOklpOUUVdU0dPQMjE3NLa2RkyurqgEcLaTHsitCptIALfRoeVYy9AAUFVjjEOAU0PJXHc7DnAFoAPjAAZS7%2BDPpFsELLEvKBWdGbB91rQtjtYPtDsdFGhHJdJj4InYwPcwAA5GywSAgAC%2BQA).

Thanks again for this!
