### ISSUE TITLE
Consider bumping the FSharp.Core version requirement for the FCS published on the Nightly Feed

### ISSUE THREAD

**Issue by baronfel** [dotnet/fsharp#10850]
Right now it is very hard to consume the nightly FCS (version 39.x) from FSAC for testing because it depends on a prerelease of FSharp.Core 5.0.  This buts up against the version constraints of other libraries like Fantomas, FSharplint, or Ionide.ProjInfo that require minimums of 5.0 (which the stable FCS binds to as well), because 5.0 prerelease doesn't satisfy the constraint `[5.0, )`.

**Describe the solution you'd like**
I'd like the nightly FSharp.Core packages to be published with a prerelease 5.0.1 (or 5.1.0, or whatever the expected version next stable version will be) so that they satisfy the `[5.0, )` constraint.

**Describe alternatives you've considered**
Alternatively, the nightly FCS could pin to 5.0 stable, but as noted in a few other threads that would be...interesting if there were features that stretched across FSharp.Core and the compiler (like string interpolation, for example).

**Comment by baronfel** [comment]
Did a bit of research on the nightly feed: https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/d1622942-d16f-48e5-bc83-96f4539e7601/nuget/v3/registrations2-semver2/FSharp.Compiler.Service

The FCS being published has an explicit nuget version bound for FSharp.Core that's not open at the top end, so it doesn't float to use the most recent FSharp.Core prerelease available from the feed. This would need to change in my view.

**Comment by cartermp** [comment]
cc @KevinRansom 

This prevents dependent projects from adopting the nightly releases

**Comment by cartermp** [comment]
@baronfel can you confirm that in the FCS 39 bits this is addressed or no? Wasn't quite sure based on your comment

**Comment by baronfel** [comment]
I can update to the FCS39 pre-releases just fine now, yep! This'll be fun :)

<img width="163" alt="Screen Shot 2021-02-06 at 4 09 23 PM" src="https://user-images.githubusercontent.com/573979/107130728-1c0e1480-6896-11eb-8bca-bb7051b46517.png">

**Comment by cartermp** [comment]
![image](https://user-images.githubusercontent.com/6309070/107131086-8fa92500-6888-11eb-8de1-f037a1f496ed.png)
