### ISSUE TITLE
Cache #r nuget references in F# Interactive

### ISSUE THREAD

**Issue by reinux** [dotnet/fsharp#10874]
**Is your feature request related to a problem? Please describe.**
I hope this isn't a duplicate, but loading packages from nuget each time F# Interactive is reloaded is a pretty significant time sink, especially when using the Execute Notebook button in .NET Interactive/Juypter, since you can't exclude the `#r`s.

**Describe the solution you'd like**
It would be great if F# Interactive could cache nuget packages somewhere (`%homepath%\.nuget`/`~/.nuget`?), although I don't know how frequently it should check for new versions -- each load? Once a day? In the background? That would be cool.

**Describe alternatives you've considered**
I'm using paket load scripts for packages that I use frequently. It's inconvenient, but it does the job.

**Comment by reinux** [comment]
Wait... Is it already caching?

**Comment by KevinRansom** [comment]
@reinux , this is an interesting request, however, package management is very sensitive to the environment and what has been uploaded to nuget.

The packages are already cached locally by nuget, although every time we resolve nuget, probably goes to the network to see if there are later or better matches.  We have from time to time considered adding a feature that makes use of lock files, that cache the results of the schedule pressure and priorities have pushed it down the priorities list up until now.  For sure it is how we would likely implement this.

**Comment by cartermp** [comment]
> nuget probably goes to the network to see if there are later or better matches

It does this but only if you don't have a version specified.

**Comment by KevinRansom** [comment]
@cartermp , yeah, that's where the 'probably' came from.

It's early and I'm feeling snarky  :-)

**Comment by reinux** [comment]
> It does this but only if you don't have a version specified.

Hm... having just checked it out in Fiddler, it doesn't seem to be hitting nuget at all unless I add a new package that I was certain I hadn't used in a long time.

Which means it is caching. My bad. I wonder why it seems to take so much longer than just a straight local `#r` then.

**Comment by KevinRansom** [comment]
@reinux , the package and assembly resolution that is done by the build is huge.

**Comment by reinux** [comment]
Ahh, right, I remember asking about that. So this is a situation that'll improve if/when incremental builds becomes a thing.

**Comment by cartermp** [comment]
Closing out the issue, as nuget references are cached.
