### ISSUE TITLE
Hello world in 10 minutes failing

### ISSUE THREAD

**Issue by johndrummond** [dotnet/fsharp#10875]
Problem encountered on https://dotnet.microsoft.com/learn/languages/fsharp-hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

all good until I get to
dotnet new console -lang F# -o myFSharpApp

when I get
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on myFSharpApp\myFSharpApp.fsproj...
  Determining projects to restore...

and it hangs

I note the directory and two files Program.fs and myFSharpApp.fsproj are in it.
Windows 10 del xps15

**Comment by johndrummond** [comment]
Ah after some time it comes back with 
Running 'dotnet restore' on myFSharpAp\myFSharpAp.fsproj...
  Determining projects to restore...
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\wip\shell\dotnet\myFSharpAp\myFSharpAp.fsproj]
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [C:\wip\shell\dotnet\myFSharpAp\myFSharpAp.fsproj]
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [C:\wip\shell\dotnet\myFSharpAp\myFSharpAp.fsproj]
Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'

Running dotnnet restore manually gives
Determining projects to restore...
and eventually
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\wip\shell\dotnet\myFSharpApp\myFSharpApp.fsproj]
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [C:\wip\shell\dotnet\myFSharpApp\myFSharpApp.fsproj]
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [C:\wip\shell\dotnet\myFSharpApp\myFSharpApp.fsproj]

I can see https://api.nuget.org/v3/index.json with a web browser
And I don't understand what's happening with the error about EOF or 0 bytes

**Comment by KevinRansom** [comment]
@johndrummond , ouch!!!! ... nuget restore usually just works ... unless there is a service outage, that would likely not impact the web server and so allow the browser to reach the uri.

The service looks to be up right now, can you give it another shot:

thanks

Kevin
````
c:\Temp\c>date
The current date is: Thu 01/14/2021
Enter the new date: (mm-dd-yy)

c:\Temp\c>time
The current time is:  9:26:24.96
Enter the new time:

c:\Temp\c>dotnet build -restore
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  c -> c:\Temp\c\bin\Debug\net5.0\c.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.71
````

**Comment by johndrummond** [comment]
hmm
I deleted the directories
I ran
dotnet new console -lang "F#" -o myFSharpApp

it waited then  gave the same error messages as before.

you typed dotnet build -restore rather than the dotnet restore in the message
it seems to do the same thing though
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET                                                                                                                     
Copyright (C) Microsoft Corporation. All rights reserved.                                                                                                                        
                                                                                                                                                                                 
  Determining projects to restore...                                                                                                                                             
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\wip\shell\dotnet\myFSharpA
pp\myFSharpApp.fsproj]                                                                                                                                                           
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [C:\wip\shell\dotnet\myFSharpApp\myFSharpAp
p.fsproj]                                                                                                                                                                        
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [C:\wip\shell\dotnet\myFSharpApp\myFSharpAp
p.fsproj]                                                                                                                                                                        
                                                                                                                                                                                 
Build FAILED.                                                                                                                                                                    
                                                                                                                                                                                 
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\wip\shell\dotnet\myFSharpA
pp\myFSharpApp.fsproj]                                                                                                                                                           
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [C:\wip\shell\dotnet\myFSharpApp\myFSharpAp
p.fsproj]                                                                                                                                                                        
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [C:\wip\shell\dotnet\myFSharpApp\myFSharpAp
p.fsproj]                                                                                                                                                                        
    0 Warning(s)                                                                                                                                                                 
    1 Error(s)                                                                                                                                                                   
                                                                                                                                                                                 
Time Elapsed 00:03:03.77                                                                                                                                                         
                                                   
but
C:\wip\shell\dotnet\myFSharpApp>curl https://api.nuget.org/v3/index.json
{
  "version": "3.0.0",
  "resources": [
    {
      "@id": "https://azuresearch-usnc.nuget.org/query",
      "@type": "SearchQueryService",
      "comment": "Query endpoint of NuGet Search service (primary)"
    },
    {
      "@id": "https://azuresearch-ussc.nuget.org/query",
      "@type": "SearchQueryService",
      "comment": "Query endpoint of NuGet Search service (secondary)"
....

so it's possible to connect and as you point out nuget is up
Any thoughts on something I should try? I'm just trying to follow hello world and failing...

**Comment by vzarytovskii** [comment]
@johndrummond that is curious. 

Is it possible that your browser uses different connection settings (proxy for example)?

Also, if you're running from powershell, can you please try running 
`Invoke-WebRequest -Uri https://api.nuget.org/v3/index.json` and see if you get normal response?

**Comment by vzarytovskii** [comment]
Does the same issue happen if you add `--disable-parallel` flag when running `dotnet restore`?

**Comment by johndrummond** [comment]
curl was from the command prompt, not even via a browser
I wasn't using powershell - I'll try
PS C:\Users\johnh> Invoke-WebRequest -Uri https://api.nuget.org/v3/index.json

StatusCode        : 200
StatusDescription : OK
Content           : {
                      "version": "3.0.0",
                      "resources": [
                        {
                          "@id": "https://azuresearch-usnc.nuget.org/query",
                          "@type": "SearchQueryService",
                          "comment": "Query endpoint of NuGet Search serv...
RawContent        : HTTP/1.1 200 OK
                    Access-Control-Allow-Origin: *
                    Access-Control-Expose-Headers:
                    x-ms-request-id,Server,x-ms-version,Content-Length,Date,Transfer-Encoding
                    Age: 97
                    Content-MD5: tc9apvjfvXbpHaJ1DHi7MQ=...
Forms             : {}
Headers           : {[Access-Control-Allow-Origin, *], [Access-Control-Expose-Headers,
                    x-ms-request-id,Server,x-ms-version,Content-Length,Date,Transfer-Encoding], [Age, 97],
                    [Content-MD5, tc9apvjfvXbpHaJ1DHi7MQ==]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : System.__ComObject
RawContentLength  : 8543

 dotnet build -restore still has the same issue in powershell.

**Comment by KevinRansom** [comment]
@johndrummond , could you make a C# project and try restore on that?

**Comment by johndrummond** [comment]
@vzarytovskii 
dotnet build -restore --disable-parallel
still gives
PS C:\wip\shell\dotnet\myFSharpApp> dotnet build -restore --disable-parallel
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\wip\shell\dotnet\myFSharpApp\myFSharpApp.fsproj]
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [C:\wip\shell\dotnet\myFSharpApp\myFSharpApp.fsproj]
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [C:\wip\shell\dotnet\myFSharpApp\myFSharpApp.fsproj]

Build FAILED.

C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\wip\shell\dotnet\myFSharpApp\myFSharpApp.fsproj]
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [C:\wip\shell\dotnet\myFSharpApp\myFSharpApp.fsproj]
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [C:\wip\shell\dotnet\myFSharpApp\myFSharpApp.fsproj]
    0 Warning(s)
    1 Error(s)
I"ll have a go with a c# project

**Comment by KevinRansom** [comment]
I think the cert chain is invalid for the ssl connection.  I think the nuget guys will have to help out with this.  Let me point you first to Will he can figure out who best to talk to.

@wli3 

Will, John is seeing issues with dotnet build, the restore is failing when trying to establish the ssl connection.  Can you help him?

Thanks

Kevin

**Comment by johndrummond** [comment]
The c# works fine
PS C:\wip\shell\dotnet> dotnet new console -o myApp
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on myApp\myApp.csproj...
  Determining projects to restore...
  Restored C:\wip\shell\dotnet\myApp\myApp.csproj (in 66 ms).
Restore succeeded.

PS C:\wip\shell\dotnet> cd .\myApp\
PS C:\wip\shell\dotnet\myApp> dotnet run
Hello World!
PS C:\wip\shell\dotnet\myApp>

**Comment by KevinRansom** [comment]
Really?   That's bizarre ...

**Comment by NinoFloris** [comment]
@KevinRansom @johndrummond that's probably because there's nothing to restore for a C# hello world, F# on the other hand will fetch FSharp.Core

**Comment by KevinRansom** [comment]
Yes I was about to suggest adding a package to restore.

**Comment by NinoFloris** [comment]
@johndrummond have you tried going to [https://api.nuget.org/v3/index.json](https://api.nuget.org/v3/index.json) in your browser to see what it thinks about the ssl cert?

**Comment by johndrummond** [comment]
it says it's fine; expires 17th September
that's for both firefox and edge

**Comment by KevinRansom** [comment]
Could you please add this to your C# project and then build thanks
````
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.8.0" />
  </ItemGroup>
````
````
dotnet build -restore -v n
````

**Comment by johndrummond** [comment]
yes, it's not language specific.

Now I get the same issue
PS C:\wip\shell\dotnet\myApp> dotnet build -restore -v n
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2021-01-14 19:44:34.
     1>Project "C:\wip\shell\dotnet\myApp\myApp.csproj" on node 1 (Restore target(s)).
     1>_GetAllRestoreProjectPathItems:
         Determining projects to restore...
       Restore:
         Restoring packages for C:\wip\shell\dotnet\myApp\myApp.csproj...
     1>C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\wip\shell\dotnet\myApp\myApp.csproj]
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [C:\wip\shell\dotnet\myApp\myApp.csproj]
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [C:\wip\shell\dotnet\myApp\myApp.csproj]
     1>Done Building Project "C:\wip\shell\dotnet\myApp\myApp.csproj" (Restore target(s)) -- FAILED.

Build FAILED.

       "C:\wip\shell\dotnet\myApp\myApp.csproj" (Restore target) (1) ->
       (Restore target) ->
         C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\wip\shell\dotnet\myApp\myApp.csproj]
       C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [C:\wip\shell\dotnet\myApp\myApp.csproj]
       C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [C:\wip\shell\dotnet\myApp\myApp.csproj]

    0 Warning(s)
    1 Error(s)

**Comment by johndrummond** [comment]
vscode wanted to try restoring the missing dependency. 
but VScode has failed as well to restore.

**Comment by NinoFloris** [comment]
In that case please try to clear your nuget caches via `dotnet nuget locals all --clear`

**Comment by johndrummond** [comment]
I restarted the laptop to see if it made any difference. Nope.
I'm running Windows 10 Pro Insider Preview
I'm using the standard windows anti virus and 
curl https://api.nuget.org/v3/index.json still works

clearing the caches doesn't work
C:\wip\shell\dotnet\myApp>dotnet nuget locals all --clear                                                                                                                                 
Clearing NuGet HTTP cache: C:\Users\johnh\AppData\Local\NuGet\v3-cache                                                                                                                    
Clearing NuGet global packages folder: C:\Users\johnh\.nuget\packages\                                                                                                                    
Clearing NuGet Temp cache: C:\Users\johnh\AppData\Local\Temp\NuGetScratch                                                                                                                 
Clearing NuGet plugins cache: C:\Users\johnh\AppData\Local\NuGet\plugins-cache                                                                                                            
Local resources cleared.                                                                                                                                                                  
                                                                                                                                                                                          
C:\wip\shell\dotnet\myApp>dotnet build -restore -v n                                                                                                                                      
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET                                                                                                                              
Copyright (C) Microsoft Corporation. All rights reserved.                                                                                                                                 
                                                                                                                                                                                          
Build started 2021-01-14 20:02:31.                                                                                                                                                        
     1>Project "C:\wip\shell\dotnet\myApp\myApp.csproj" on node 1 (Restore target(s)).                                                                                                    
     1>_GetAllRestoreProjectPathItems:                                                                                                                                                    
         Determining projects to restore...                                                                                                                                               
       Restore:                                                                                                                                                                           
         Restoring packages for C:\wip\shell\dotnet\myApp\myApp.csproj...                                                                                                                 
     1>C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\wip\shell\dotnet\myApp\myApp
csproj]                                                                                                                                                                                   
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [C:\wip\shell\dotnet\myApp\myApp.csproj]            
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [C:\wip\shell\dotnet\myApp\myApp.csproj]            
     1>Done Building Project "C:\wip\shell\dotnet\myApp\myApp.csproj" (Restore target(s)) -- FAILED.                                                                                      
                                                                                                                                                                                          
Build FAILED.                                                                                                                                                                             
                                                                                                                                                                                          
       "C:\wip\shell\dotnet\myApp\myApp.csproj" (Restore target) (1) ->                                                                                                                   
       (Restore target) ->                                                                                                                                                                
         C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\wip\shell\dotnet\myApp\myA
p.csproj]                                                                                                                                                                                 
       C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [C:\wip\shell\dotnet\myApp\myApp.csproj]     
       C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [C:\wip\shell\dotnet\myApp\myApp.csproj]     
                                                                                                                                                                                          
    0 Warning(s)                                                                                                                                                                          
    1 Error(s)                                                                                                                                                                            
                                                                                                                                                                                          
Time Elapsed 00:03:03.72

**Comment by johndrummond** [comment]
I'm sure it's something really simple, but I've no idea. I'm grateful for your suggestions, thank you.

**Comment by debugnik** [comment]
@johndrummond  You're running Windows Insider, right? A past build introduced a regression in HttpClient that caused your same issue when restoring NuGet packages. The latest Insider builds have supposedly fixed it, but [there's also a workaround by editing the registry](https://github.com/dotnet/runtime/issues/40679#issuecomment-673675486).

**Comment by KevinRansom** [comment]
@debugnik , nice info thanks

**Comment by KevinRansom** [comment]
@johndrummond , did @debugnik 's suggestion help? can you let us know and close the issue if it is no longer a problem


Thanks

Kevin

**Comment by johndrummond** [comment]
Yes that worked - many thanks all.
Note I need to restart before the registry changes took effect.
