### ISSUE TITLE
Does anyone use key containers when signing f# assemblies.

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#10878]
We would like to deprecate the support for signing using keycontainer.
signing using a keycontainer can currently be done using the KeyContainerAttribute or the --keycontainer command line switch. 
However, this is not supported on the dotnet framework, the visual studio tooling emphasis a keyfile rather than the registry based keyname.  On F# the signing page crashes VS because we need to implement a handler for the signing dialog.

On the coreclr, we have no access to the key container Api's and anyway, there is no common alternative on non-windows platforms.  So ... we would like to deprecate the mechanism even on windows, with a warning that it will not work cross platform.

**Comment by cartermp** [comment]
Closing old announcement. This will be deprecated.
