### ISSUE TITLE
Type abbreviation for struct DU shadows DU case constructor

### ISSUE THREAD

**Issue by debugnik** [dotnet/fsharp#10873]
Adding a type abbreviation for a struct DU shadows any DU case constructor of the same name. The shadowed case doesn't need to be part of said struct DU, just any DU in scope before the abbreviation. Trying to use the case constructor fails to compile, but the case is still in scope as a pattern. The type parameter arities involved don't seem to matter.

**Repro steps**

Compile this snippet as a script or at module level:

```F#
[<Struct>]
type Foo<'T> = Foo of 'T

type Foo = Foo<int>

let foo = Foo 0 // FS1133
```

**Expected behavior**

The snippet compiles successfully.

**Actual behavior**

Compilation fails with error FS1133 at the use of the case constructor. The error reads as if the abbreviation had aliased a constructorless class instead of a DU.

**Known workarounds**

Remove/rename the abbreviation or turn the struct DU into a reference type.

**Related information**

* .NET SDK 5.0.102
* `<LangVersion>5.0</LangVersion>`

**Comment by cartermp** [comment]
@dsyme can you confirm if this is a bug?

**Comment by cartermp** [comment]
This seems like it would fall under the umbrella of https://github.com/fsharp/fslang-suggestions/issues/907 and so I'll close in favor of that
