### ISSUE TITLE
Apply map and set optimizations to tagged internal collections

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#10889]
See here:

https://github.com/dotnet/fsharp/pull/10860
https://github.com/dotnet/fsharp/pull/10845

These optimizations should also get applied to the internal TaggedCollections equivalents so that the F# compiler can benefit from them.

**Comment by dsyme** [comment]
Closing as it's an internal engineering thing.  It would be a good thing to do but doesn't have to be specifically tracked
