### ISSUE TITLE
Latest VS 16.8.4 hangs if F# console project TargetFramework set to netcore5.0

### ISSUE THREAD

**Issue by BentTranberg** [dotnet/fsharp#10897]
I am reporting this here because although it is a problem in VS, it only happens with F# projects, not C# projects. I have also reported this through the feedback system in VS.

**Repro steps**

1. Create a solution with a project of type Console App (.NET Core) F#
2. Change the project file's TargetFramework from netcoreapp3.1 to netcore5.0

Note! The TargetFramework value is wrong, and that's what cause problems.

**Expected behavior**

VS should not go berserk. It should be possible to recover the situation by correcting the TargetFramework.

**Actual behavior**

VS goes berserk as soon as the change is saved to disk.

A panel appears above the editor panels, showing this message.

The project 'Test3' ran into a problem during the last operation: The expression "[System.Version]::Parse('')" cannot be evaluated. Version string portion was too short or too long.  C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets You may need to reload the solution after fixing the problem. 

An error can possibly appear in the error list pane.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4184	The expression "[System.Version]::Parse('')" cannot be evaluated. Version string portion was too short or too long.	TestCaFs	C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	47	

Trying to compile won't produce any error in the Error List pane.

Trying to run the program will make a dialog box appear with the first error message.

Trying to correct the error by changing the TargetFramework to net5.0 will cause VS to hang.

Trying to kill and then restart VS and open the solution, will cause the solution to be opened with the project unloaded. The project file is not available for editing by clicking the project. Trying to Reload Project will not work. I am reasonably sure I've also had cases where VS would hang sooner than described here, so that there was no other way out than to edit the project file outside of VS to work around the problem.

**Known workarounds**

After reopening solution in VS

A : In Solution Explorer, it is possible to Edit Project File even though the project is not loaded. Fix the error in the source, then reload the project.

B : If this fails for some reason, e.g. VS hangs before or while editing, edit away the source error in e.g. Notepad instead.

**Comment by cartermp** [comment]
tagging this as external because there's nothing in the F# targets that emits this

**Comment by KevinRansom** [comment]
Having VS hang even  though it is a user supplied error is still pretty bad.  The error banner that appears above the text editor is correct, however, when VS becoming non-responsive and requiring a process restart is not going to be seen as a good experience.

**Comment by KevinRansom** [comment]
I think this belongs with the project system team:  https://github.com/dotnet/project-system.  F# is not in any of the VS stacks.
