### ISSUE TITLE
Implicit cast from 't to Some of 't

### ISSUE THREAD

**Issue by reinux** [dotnet/fsharp#10892]
**Is your feature request related to a problem? Please describe.**
`Some x` adds a lot of noise without, as far as I can tell, adding much useful type information, especially when it needs to be bracketed so it can be used as an argument to a curried function.

I think this can be a bit of an impediment to adoption, as most languages, even the ones that don't have nullability as default, do this cast automatically.

**Describe the solution you'd like**
When an `Option<'t>` is expected and a `'t` is provided, automatically cast from `'t` to `Some 't` .

From what thought I've put into it, I don't think this should break any existing code. Method overloading, in cases where one overload accepts `Option<'t>` and another accepts `'t`, I'm pretty sure can be resolved by simply using the `'t` version.

One concern might be that this could end up being a slippery slope toward having implicit casts in places it isn't as appropriate, but I think `Option<'t>` is so ubiquitous that it could be justified having some syntactic (type checker?) sugar.

Especially for data entry tasks (I'm doing a ton in F# so I can take advantage of UoM), this would be a real time saver, and it would make the language feel a bit "nicer" (tm) for hopefully not too much cost.

**Comment by charlesroddie** [comment]
F# only does implicit upcasting, and is likely to expand that in small or large ways, but 't to 't option is not a cast. This is very unlikely to happen so I don't think it's worth making a language suggestion out of this. One problem is that if `None:unit option option` becomes ambiguous, either staying as itself or getting changed to `Some None`.

**Comment by dsyme** [comment]
Agreed with @charlesroddie - feel free to make a language suggestion but this one feels unlikely to happen

**Comment by reinux** [comment]
> One problem is that if None:unit option option becomes ambiguous, either staying as itself or getting changed to Some None.

It seems like the natural and non-breaking thing to do would in this situation would be to just leave it as `None` if it's already a `None`. Then if you need a `Some None`, you can always call it that.
