### ISSUE TITLE
F# interactive (VS) fails to reference nuget package with no .NET framework compatibility

### ISSUE THREAD

**Issue by halcwb** [dotnet/fsharp#10902]
It is not possible to load a netcore only library using `#r "nuget: ...`. See also this [stackoverflow post](https://stackoverflow.com/questions/64927489/f-interactive-fails-to-reference-nuget-package-with-no-net-framework-compatibi).

**Repro steps**

Provide the steps required to reproduce the problem:

1. Add `#r "nuget: Informedica.Utils.Lib"` 
2. Run the script in the FSI

> NugetTest.fsx(2,1): error FS3217: AppData\Local\Temp\nuget\26268--718db5b2-2b95-43ea-8139-0d6af226a61d\Project.fsproj : error NU1202: Package Informedica.Utils.Lib 1.0.0 is not compatible with net48 (.NETFramework,Version=v4.8). Package Informedica.Utils.Lib 1.0.0 supports: net5.0 (.NETCoreApp,Version=v5.0)

**Expected behavior**

Be able to reference the dll. The same reference works in VSCode.

**Actual behavior**

The above error message.

**Known workarounds**

None

**Related information**

Provide any related information (optional):

Microsoft Visual Studio Community 2019
Version 16.8.4
VisualStudio.16.Release/16.8.4+30907.101
Microsoft .NET Framework
Version 4.8.04084

**Comment by KevinRansom** [comment]
Yeah ... sorry the desktop dotnet framework 4.8 cannot run net5.0 assemblies you will need to run the coreclr version of fsi.

The next Preview of Visual Studio will carry a preview of coreclr scripting which can run them.   Alternatively from the command line you can run ````dotnet fsi```  and you will be able to type and run scripts that use dotnet 5.0 only packages.

I hope this helps

Kevin

**Comment by halcwb** [comment]
@KevinRansom Thanks, I need to be patient ;-)
