### ISSUE TITLE
Compiler or runtime use wrong variable for fsisession

### ISSUE THREAD

**Issue by ingted** [dotnet/fsharp#10912]
**Repro steps**
```
        let orz = 2

        let fsiSession : FsiEvaluationSession= 
            FsiEvaluationSession.Create (
                fsiConfig, 
                arg01, 
                System.Console.In, 
                System.Console.Out,
                System.Console.Error, 
                collectible=false, 
                legacyReferenceResolver=legacyReferenceResolver)

        fsiSession.EvalInteractionNonThrowing ("""
        let orz = 1
        """) |> ignore
        fsiSession.EvalInteractionNonThrowing ("""
        printfn "ENV: %A" orz
        """) |> ignore

```

**Expected behavior**

```
ENV: 1 
```
should be printed

**Actual behavior**

```
ENV: 2 
```
should be printed

**Known workarounds**

Use different variable name outside of the fsisession

**Related information**

* Operating system: Server 2019
* .NET Runtime: .NET 5.0 (F# 5)
* Editing Tools: Visual Studio 2019 16.9.0 Preview 1.0

**Comment by KevinRansom** [comment]
@ingted , this looks very bizarre, I am confident, that we do not find the value from the orz instance defined externaly to the session, since the notebook code relies on the session encapsulation.  Anyway, I will look at this in the afternoon, and try get back to you with an explanation.

Thanks

Kevin

**Comment by KevinRansom** [comment]
@ingted ,

Okay I tried to repro this, and it behaved as expected, it Produced a 1 for the value env.

I used the latest public FSharp.CompilerService package:

      <PackageReference Include="FSharp.Compiler.Service" Version="38.0.2" />

![image](https://user-images.githubusercontent.com/5175830/105928416-bf3f6e00-5ffa-11eb-9d2c-ce8fd47c9a1c.png)


Please reopen if you are still seeing an issue.

Thanks

Kevin

**Comment by ingted** [comment]
Oops!!! Not compiler service project....
But FSharp.Compiler.Private

**Comment by ingted** [comment]
Let me make a reproduce project for it.
It is part of my private project...

**Comment by KevinRansom** [comment]
FSharp.Compiler.Private has been renamed to FSharp.Compiler.Service, they were basically the same just with different dll names.
