### ISSUE TITLE
Warning only when function application is inside SynExpr.IfThenElse

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#10929]
Consider the following code example:
![image](https://user-images.githubusercontent.com/2621499/105501987-33a9a280-5cc5-11eb-9535-bdcbbfd7bb74.png)

```fsharp
let a =
  System.Text.RegularExpressions.Regex.IsMatch(
    "myInput",
    """^[a-zA-Z][a-zA-Z0-9']+$"""
   )

if System.Text.RegularExpressions.Regex.IsMatch(
    "myInput",
    """^[a-zA-Z][a-zA-Z0-9']+$"""
   ) then
  ()
```

I get an indentation warning when the function call is inside the if condition.
But not when it is used in a let binding body.

**Expected behavior**

I would expect both cases not to show any warnings.

**Actual behavior**

Warning for the expression inside the if/then/else

**Known workarounds**

Wrap the if condition inside parenthesises.

```fsharp
if (System.Text.RegularExpressions.Regex.IsMatch(
     "myInput",
      """^[a-zA-Z][a-zA-Z0-9']+$"""
   )) then
  ()
```

**Related information**

Provide any related information (optional):

* Operating system: Win 10
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .NET 5
* Editing Tools (e.g. Visual Studio Version, Visual Studio): FCS 38.0.0

Related Fantomas bug: https://github.com/fsprojects/fantomas/issues/1349

**Comment by cartermp** [comment]
Other workaround :)

```fsharp
if System.Text.RegularExpressions.Regex.IsMatch(
                                                "myInput",
                                                """^[a-zA-Z][a-zA-Z0-9']+$"""
                                               ) then
  ()
```

I know that @dsyme has preferred these to be tracked as RFCs for some reason but it just kinda feels like a bug to me at this point.

**Comment by nojaf** [comment]
Yeah, then the next lad complains that the max line length is not respected 🙃.
I can't win in these situations 😋.

Anyway, Don if this needs an RFC, please let me know.

**Comment by nojaf** [comment]
This also happens in match expressions.
For example:
```fsharp
let b ="True"
let foo () =
    match Boolean.TryParse (
            b
          ) with
    | true, i -> Some i
    | false, _ -> failwith ""
```

![image](https://user-images.githubusercontent.com/2621499/107032262-d37e2a80-67b3-11eb-8d41-74751fcb9ae1.png)

@cartermp, @dsyme how do you want to see this fixed? If it should be fixed at all of course.

**Comment by dsyme** [comment]
This relaxation should be tracked by a language suggestion, which we can consdier approved-in-principle.

**Comment by dsyme** [comment]
Fixed in preview https://github.com/dotnet/fsharp/pull/11772
