### ISSUE TITLE
Dotnet build fails but MSBuild doesn't on FSharpCore compatibility

### ISSUE THREAD

**Issue by halcwb** [dotnet/fsharp#10936]
Please provide a succinct description of the issue.

I have referenced FSharp.Core in my project using paket pinning this to 4.7.1. When I build the project using VS than the build succeeds when I try this with dotnet build then I get: 

> D:\Development\MetaVision\Temp\src\Informedica.MetaVisionServices.Lib\Informedica.MetaVisionServices.Lib.fsproj : error NU1202: Package FSharp.Core 5.0.0 is not compatible with net45 (.NETFramework,Version=v4.5). Package FSharp.Core 5.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0) [D:\Development\MetaVision\Temp\MetaVisionServices.sln]

Provide the steps required to reproduce the problem:

I cannot exactly reproduce the problem. I think it is because one of my dependencies uses a 5.0 version of FSharp.Core? 

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

**Expected behavior**

Be able to use dotnet build when MSBuild succeeds.

**Actual behavior**

See above error message.

**Known workarounds**

Using MSBuild. However this disables my CI.

**Related information**
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by cartermp** [comment]
Another workaround is to upgrade from net45 to net472. We recommend making that the minimum .NET Framework version used for all .NET development if you can, since so many components only support .NET Standard 2.0.

**Comment by halcwb** [comment]
@cartermp Thanks for the quick answer. My project depends on FSharp.Data.TypeProviders. Therefore, it is difficult to add a repro as the project build depends on direct access to a database. I also posted an [issue](https://github.com/fsprojects/FSharp.Data.TypeProviders/issues/39) relating to whether the TypeProviders will be [maintained](https://github.com/fsprojects/FSharp.Data.TypeProviders/issues/42) in the future.

**Comment by KevinRansom** [comment]
@halcwb , FSharp.Core is no longer compatible with dotnet 45 thru net4.6.2.  FSharp.Core version 5.0.0 and up are compatible with netstandard2.0, which means the minimum desktop version you can use them with is net472.

If you need to target old versions of the desktop framework then, pin your project to use: FSharp.Core, Version=4.7.2.  However, some new language features will not be available to you.

I hope this helps,
Kevin

**Comment by KevinRansom** [comment]
I am closing this, please reopen if you believe it was closed in error.

**Comment by auduchinok** [comment]
> FSharp.Core is no longer compatible with dotnet 45 thru net4.6.2. FSharp.Core version 5.0.0 and up are compatible with netstandard2.0, which means the minimum desktop version you can use them with is net472.

AFAIK `netstandard2.0` can be used in `net461` and newer, not `net472` and newer.

**Comment by cartermp** [comment]
As per nuget resolution they can, but in practice you should use `net472` or higher because there are subtle issues with type forwarders in .NET Framework versions lower than that

**Comment by KevinRansom** [comment]
@auduchinok , net472 is the recommended platform for netstandard2.0 compatibility.  If you go lower than that, then if it works, then all is well, if it doesn't well ... it's not recommended so we probably won't make any changes to accommodate it.    However, FSharp.Core, Version=4.7.2 can be used for downlevel platforms, at the cost of newer FSharp compiler features..
