### ISSUE TITLE
'IntelliSense on Functions' tooltip does not appear when in parentheses related to other construct

### ISSUE THREAD

**Issue by JordanMarr** [dotnet/fsharp#10941]
I have found a few scenarios where the new functions parameter tooltip does not work using VS 16.9 preview 3:
- Computation Expressions
- Lambda Expressions

**Repro steps**

## Computation Expressions
The new preview IntelliSense context tooltip does not appear within computation expressions. 
I've verified this against the following CEs:
- async
- asyncResult
- Fable.GroupingPanel

## Lambda Expressions
It also does not appear when placed within the body of a lambda expression.
**This works:** 
```fsharp
let add n1 n2 = n1 + n2
let sum = add 1 2 // The new tooltip correctly appears
```

**This does not work:**
```fsharp
let lst = [1; 2; 3]
let mapped = 
    lst |> List.map (fun n ->
        let sum = add 1 2 // New tooltip does not appear; instead, shows old tooltip
        n.ToString()
    )
```

**Expected behavior**

Should always show the new function parameter preview that shows all parameters.

**Actual behavior**

Sometimes reverts to the old preview that only shows the current parameter.

* Windows 10
* Tested on .NET Core 3.1 and .NET Standard projects
* Visual Studio Professional 16.9 Preview 3

**Comment by cartermp** [comment]
Computation expressions is covered here: https://github.com/dotnet/fsharp/pull/10835

Should be in the 16.9 full release, unsure about a specific preview

Within parens in a lambda is an interesting issue that I anticipated would arise but wasn't sure of the impact. Should be fun to take a look

**Comment by cartermp** [comment]
Just to add a screenshot, this is what's going on:

![image](https://user-images.githubusercontent.com/6309070/105890116-c9924580-5fc3-11eb-9400-46b0aa35e69c.png)

This is because `TryRangeOfFunctionOrMethodBeingApplied` has a bug where it picks `List.map` rather than `sum`.

**Comment by cartermp** [comment]
Marking this here for now, a quirk I noticed when editing code int he compiler. I can't say if it's related yet:

![image](https://user-images.githubusercontent.com/6309070/105927360-b188e900-5ff8-11eb-8999-6a7d54273d55.png)

**Comment by cartermp** [comment]
Using https://github.com/dotnet/fsharp/issues/10957 to track the issue I noticed and another.

**Comment by cartermp** [comment]
Thanks for the report. The issue as-reported is fixed here: https://github.com/dotnet/fsharp/pull/10954

We're nearing a code freeze for VS 16.9 so I'll see if I can cherry pick the fix into the release. If not, then this would be in the 16.10 previews.

There are a few other quirks tracked in https://github.com/dotnet/fsharp/issues/10957 - if you notice additional issues, please file new ones or comment on that thread. I can move things around/create issues as needed.

**Comment by JordanMarr** [comment]
> Hmm, I'm actually going to re-open this because the "old" tooltip will still trigger for me.

Here's another scenario: the tooltip doesn't show -- it appears to be related to the generic argument being present:

```
    /// Tries to cast an object to a given type; throws with the given error message if it fails.
    let tryConvert<'T> (descriptor: string) (value: obj) : 'T =
        try
            Convert.ChangeType(value, typeof<'T>) :?> 'T
        with ex ->
            let msg = sprintf "Unable to convert '%s' with value %A" descriptor value
            raise (new Exception(msg, ex))

    // Tooltip does NOT show when the generic argument is present:
    let result= (box 123) |> tryConvert<string> "numbers"

    // Tooltip does show properly here:
    let result : string = (box 123) |> tryConvert "numbers"
```

**Comment by JordanMarr** [comment]
I have another one for you: tooltip doesn't appear for composed functions.

```
    let prependStar (txt: string) = "*" + txt
    let appendStar (txt: string) = txt + "*"
    let addStars = prependStar >> appendStar

    // Good
    let result1 = prependStar "ABC"

    // Good
    let result2 = appendStar "ABC"

    // Bad - No Intellisense tooltip
    let result3 = addStars "ABC" 

```

**Comment by cartermp** [comment]
Yeah, that's not going to be reasonable to do compared with the other cases. I'll file an issue for this but it'll probably just be low priority since it's not a common occurrence + much more difficult to pull off.

**Comment by JordanMarr** [comment]
Another one that I noticed that's maybe not worth messing with, but I might as well mention it now: 
it doesn't show the tooltip if there is a character directly after the cursor, like an end paren.

```
let doStuff (txt: string) = printfn txt
let doStuffLazy = lazy (doStuff ) // <-- hitting space here while the cursor is touching the end paren prevents tooltip
```

The workaround is pretty easy though -- just make sure to add a space before the closing paren.

**Comment by cartermp** [comment]
This is also fixed in #11200:

![sighelp1](https://user-images.githubusercontent.com/6309070/110577466-8b865680-8117-11eb-905b-1601e74d71f8.gif)

**Comment by JordanMarr** [comment]
Yessss!

**Comment by cartermp** [comment]
Closing out again since https://github.com/dotnet/fsharp/pull/11200 is merged
