### ISSUE TITLE
Make .NET Core scripting the default in VS Tools

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#10975]
For the 16.10 release we should make .NET Core scripting the default. Just have to toggle this flag I believe: https://github.com/dotnet/fsharp/blob/main/vsintegration/src/FSharp.VS.FSI/sessions.fs#L67

**Comment by cartermp** [comment]
This is of course barring any significant feedback from 16.9 users turning it on and having problems with it.

**Comment by dsyme** [comment]
Sounds good!

**Comment by dsyme** [comment]
Done for VS2022
