### ISSUE TITLE
Init auto-implemented property not supported

### ISSUE THREAD

**Issue by vukovinski** [dotnet/fsharp#11068]
Referencing a .NET 5 C# library, from F# code, will throw a runtime exception:

Invalid program exception - Common Language Runtime detected an invalid program.

Just before instantiating a class with init auto-implemented properties.

**remedy**

If you control the library, you could change the init to set.

**Comment by cartermp** [comment]
Will close this in favor of https://github.com/fsharp/fslang-suggestions/issues/904
