### ISSUE TITLE
Disposable values not highlighted

### ISSUE THREAD

**Issue by peder86** [dotnet/fsharp#11098]
In `Tools -> Options -> Fonts and Colors -> Display items` there are options for highlighting `IDisposable` values with a custom color. 
![image](https://user-images.githubusercontent.com/3354932/107619548-a1594680-6c53-11eb-9367-476e1a9d78ab.png)
Only the disposable types themselves get properly highlighted, not the `let/use` bound values
![image](https://user-images.githubusercontent.com/3354932/107619779-f9904880-6c53-11eb-8f90-550acb7f9be5.png)
Same for other framework/library defined disposable types.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Go to `Tools -> Options -> Fonts and Colors -> Display items` and choose custom item color for `F# Disposable Types`, `F# Disposable Values (locals)` and `F# Disposable Values (top-level)`
2. Instantiate an instance of a type that implements `System.IDisposable`
```fsharp
type MyDisposable() =
  interface IDisposable with
    member _.Dispose() = printfn "Disposed"

let dispose() =
  use d1 = new MyDisposable()
  use d2 = { new IDisposable with member _.Dispose() = printfn "Disposed" }
  ()
```

**Expected behavior**

The `let/use` bound value should be highlighted in the color chosen in step 1 above.

**Actual behavior**

The value appears like any other value

**Known workarounds**

None

* Windows 10 pro, 20H2
* Microsoft Visual Studio Professional 2019 Version 16.8.5, fresh install, dark color theme

**Comment by cartermp** [comment]
Huh, must have gotten smashed somewhere along the line. I implemented this and it worked but perhaps some bugfixes for classification regressed this.

The relevant routine that classifies things is here: https://github.com/dotnet/fsharp/blob/main/src/fsharp/service/SemanticClassification.fs#L165

Unsure how likely I'll get to this, but it's not terribly challenging to debug and tweak if you're interested in contributing a fix. The main quirk is that the order of the match expressions matters, so quickly fixing one case could potentially regress something else.

**Comment by baronfel** [comment]
One thing that might be worth looking into is separating the kind of value from the modifiers applied to the value. LSP went this way, and as a result you can tag all the 'variables' tokentypes you want, and then have a separate tokenmodifier 'disposable' as well. Then in the editor you'd apply your fancy disposable color scheme to the 'disposable' modifier as opposed to a specific token type.  Here's an example of this using the current classification responses from FCS: https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete/LspHelpers.fs#L418-L511

**Comment by peder86** [comment]
I'd be happy to give an attempt. Would it be feasible to add tests for this case?
If so, it this the right place:
https://github.com/dotnet/fsharp/blob/main/vsintegration/tests/UnitTests/SemanticColorizationServiceTests.fs

**Comment by cartermp** [comment]
I think so, yes. That would be the file. Sometimes the tests can't be run in visual studio though, not without a restart in VS. It's annoying and related to a particular type provider we have under test and we haven't really gotten to the bottom of why it acts the way it does.

**Comment by peder86** [comment]
The `IDisposable` semantic classification is working as expected. The issue was instead in 
https://github.com/dotnet/fsharp/blob/main/vsintegration/src/FSharp.Editor/Classification/ClassificationDefinitions.fs#L32
where the classification was just not used properly. PR opened [here](https://github.com/dotnet/fsharp/pull/11116).
