### ISSUE TITLE
We are going to make fsc and fsi.exe AnyCPU

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#11090]
The desktop build of future F# deployments will be AnyCPU, that means they will run as 64 bit apps rather than 32 bit by preference on 64 bit operating systems, they will fall back to 32 bit on 32 bit Operating Systems.

We will continue to deploy FsiAnyCpu.exe, in order to ensure existing scripts that rely on the name continue to work, but it will be a duplicate of fsi.exe.

**Comment by abelbraaksma** [comment]
I assume this won't change the fact that fsi inside VS still runs by default as x86, because VS runs in that mode? Or will that run as x64 as well?

**Comment by KevinRansom** [comment]
Fsi in VS will be net5.0 and 64 bit.  For a while there will be a desktop option, but we expect that to be deprecated.
