### ISSUE TITLE
PathMap not supported by F#?

### ISSUE THREAD

**Issue by njlr** [dotnet/fsharp#11100]
**Repro steps**

I want to have deterministic builds, regardless of the folder that the project is checked-out into. 

Following information found [here](https://gist.github.com/aelij/b20271f4bd0ab1298e49068b388b54ae), I added a `PathMap` property to my `fsproj`:

```xml
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Deterministic>true</Deterministic>
    <DeterministicSourcePaths>true</DeterministicSourcePaths>
    <PathMap>$(EnlistmentRoot)=/home/runner/</PathMap>
  </PropertyGroup>
```

**Expected behavior**

Deterministic builds

**Actual behavior**

```bash
$ dotnet build
usr/share/dotnet/sdk/5.0.103/FSharp/Microsoft.FSharp.Targets(281,9): error MSB6006: "dotnet" exited with code 134.
```

**Known workarounds**

Unknown

**Related information**

```bash
$ dotnet --version 
5.0.103

$ lsb_release -a 
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

**Comment by njlr** [comment]
Misread instructions...

**Comment by baronfel** [comment]
I implemented support for this in the compiler in https://github.com/dotnet/fsharp/pull/9874, so we should be good to go.

**Comment by njlr** [comment]
@baronfel Thanks for responding! I am finding documentation a little sparse. Suppose I have many `.fsproj` files that are part of a single `.sln`. What is the best way to enable deterministic paths for all projects?

**Comment by baronfel** [comment]
What about setting the Deterministic property to true in a Directory.Build.props file?

**Comment by njlr** [comment]
I have already set these properties in my `.fsproj` files:

```xml
    <Deterministic>true</Deterministic>
    <DeterministicSourcePaths>true</DeterministicSourcePaths>
```

However, if I `cat` the output `.dll` I can see the absolute paths to the source files in there.

**Comment by NinoFloris** [comment]
It needs a <SourceRoot Include="path"> to actually strip away everything until the root of the project, Source Link simplifies this by figuring out the SourceRoot based on your vcs info. https://github.com/dotnet/sourcelink

**Comment by njlr** [comment]
> It needs a `<SourceRoot Include="path">` to actually strip away everything until the root of the project, Source Link simplifies this by figuring out the SourceRoot based on your vcs info. https://github.com/dotnet/sourcelink

Sorry, I am not familiar with all of this stuff. What would `path` be in this case?
