### ISSUE TITLE
mono/wasm cannot handle list comprehensions.

### ISSUE THREAD

**Issue by amieres** [dotnet/fsharp#11113]
This may be an issue with mono/WASM but it is related to a construct unique for F# (C# does not have it, I think).

While in interpreted mode FCS mostly works with very few issues. In AOT-Interpreted mode which combines
AOT mode and interpreted code some things do not work like this code in IlxGen.fs:

````
let HashRangeSorted (ht: IDictionary<_, (int * _)>) =
    [ for KeyValue(_k, v) in ht -> v ] |> List.sortBy fst |> List.map snd
````

produces a abnormal termination in mono-WASM.

Changing it to:

````
let HashRangeSorted (ht: IDictionary<_, (int * _)>) =
    ht |> Seq.map(fun kvp -> kvp.Value) |> Seq.sortBy  fst |> Seq.map  snd |> Seq.toList
````

Which is equivalent, runs with no problems.

There are a few other places where Lists comprehensions are used in FCS that also do not run.

So the question is: what is it with list comprehensions that could be causing this issue?

**Comment by KevinRansom** [comment]
@amieres, I'm afraid I am not familiar with how to get F# and mono wasm working, could you provide a list of the steps, that I would need to follow to see the issue.  Once I can, then I will take a look.

Thanks mate

Kevin

**Comment by dsyme** [comment]
> So the question is: what is it with list comprehensions that could be causing this issue?

It is probably the generation of branching "goto" statements in the generated IL.  This must be a bug in mono WASM

**Comment by cartermp** [comment]
Will close this out as it's most defintiely a mon-wasm issue.
