### ISSUE TITLE
.NET Core script editing reference resolution problems in master and internal preview

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#11115]
Something seems to have gone awry recently with .NET Core reference resolution when editing scripts in Visual Studio

1. Set ".NET Core Script editing" to True in F# Tools options
2. Take a script containing .NET Core scripting text and put it in a directories (with and without a global.json)
 
       #r "netstandard.dll"

       // A .netcoreapp3.1 api
       let f x = System.Runtime.InteropServices.NativeLibrary.Free(x)

3. Then open `devenv.exe on the script, e.g.

    c:\>   devenv c:\misc\tests\netcore-script.fsx

We appear to have two problems - one in 16.9.0 and one in master:

### Internal preview (Visual F# Tools   16.9.0-beta.21052.1+77c36dad3d5702c4eb3cf51f99d8643d4069a758)

- resolves correctly if global.json 5.0.101 is there
- resolve **incorrectly** to .NETFramework otherwise

### master branch 

- resolve **incorrectly** to .NETFramework regardless of presence of global.json

### 16.8.4

(.NET Core scripting not available)

#### Context

```
C:\>dotnet --list-sdks
2.1.300 [C:\Program Files\dotnet\sdk]
2.1.521 [C:\Program Files\dotnet\sdk]
3.1.302 [C:\Program Files\dotnet\sdk]
3.1.406 [C:\Program Files\dotnet\sdk]
5.0.102 [C:\Program Files\dotnet\sdk]
5.0.103 [C:\Program Files\dotnet\sdk]
5.0.200-preview.20614.14 [C:\Program Files\dotnet\sdk]
```

**Comment by cartermp** [comment]
Why is `#r "netstandard.dll"` used?

**Comment by KevinRansom** [comment]
@cartermp, it's not significant, especially since the Ai is a netcoreapp3, but it does no harm either.

**Comment by dsyme** [comment]
There are two separate bugs

- the FxResolver is being created with assumeDotNetFramework=true and later a method is passed assumeDotNetFramework=false but the old value is still being captured. I'm fixing that

- If you have a preview SDK as the latest SDK on your machine it will be selected as the version to usem but this line filters out any directories containing `-preview`

                let sdkDir =
                    DirectoryInfo(sdksDir).GetDirectories()
                    |> Array.filter (fun di -> di.Name |> Seq.forall (fun c -> Char.IsDigit(c) || c = '.'))

I will remove this line 

@cartermp This means in VS 16.9 there will be an issue along these lines:

> "If you enable preview F# .NET Core scripting editing in VS and install a preview .NET SDK as the latest .NET SDK on the machine then .NET Core scripting editing will not function correctly and .NET Framework scripting will be used. This will not affect script execution.   You can work around this be adding a global.json to the directory containing the script selecting the exact non-preview .NET SDK  to use in conjunction with editing and execution.  "

**Comment by cartermp** [comment]
https://github.com/dotnet/fsharp/pull/11120
