### ISSUE TITLE
 Error when loading type provider copy into .NET 5 projects

### ISSUE THREAD

**Issue by DedSec256** [dotnet/fsharp#11135]
1. Create a solution with 2 projects targeting net5 (and MSBuild from net5 sdk)
2. Add `FSharp.Text.RegexProvider v2.1.0` to each project

**Expected:**
No errors

**Actual:** 
The first open project is successfully type-checked, the second project is open with the message _"The type 'Regex' is not defined"_ 
But both projects are built successfully.

Reproduced in Rider (FCS netstandard 2.0, with type providers hosted in .NET 5.0.3 runtime) 
and VS Code Ionide 5.3.2

![image](https://user-images.githubusercontent.com/26364714/108624944-282ed000-7459-11eb-9ba9-aa4213809b55.png)
![image](https://user-images.githubusercontent.com/26364714/108624954-3381fb80-7459-11eb-97a0-74fdf8ae9377.png)

When FCS tries to instantiate the type provider for the second project, [ this code ](https://github.com/dotnet/fsharp/blob/main/src/fsharp/utils/CompilerLocationUtils.fs#L292) fails with _"Assembly with same name is already loaded"_

Repro:
[net5repro.zip](https://github.com/dotnet/fsharp/files/6017692/net5repro.zip)

**Comment by cartermp** [comment]
Labeling as a bug for now, but this may be unexpectedly by design because it's type providers

**Comment by KevinRansom** [comment]
@DedSec256  We believe this has been fixed.  Please reopen this issue if you still see it repro with newer builds.

Thanks

Kevin

**Comment by DedSec256** [comment]
@KevinRansom, the issue is still open, since this [code](https://github.com/dotnet/fsharp/blob/97651b3456a7fa23369e189e1365cb38490e2d23/src/Compiler/Facilities/CompilerLocation.fs#L170-L176) for loading an assembly with type providers will not allow loading the same assembly of different versions in single AssemblyLoadContext. Also, this issue is not related to the dotnet version and can be reproduced in any solution with several different versions of the same package with providers.

**Comment by auduchinok** [comment]
This still reproduces, please see [RIDER-127413](https://youtrack.jetbrains.com/issue/RIDER-127413).
