### ISSUE TITLE
FSI: Could not load type MyType from assembly FSI-ASSEMBLY

### ISSUE THREAD

**Issue by lfr** [dotnet/fsharp#11133]
The following code generates a cryptic error message "_Could not load type TextError from assembly FSI-ASSEMBLY_" in F# interactive.

**Full script**

```fsharp
#r "nuget: FSharp.Domain.Validation"

open FSharp.Domain.Validation
open System

type TextError =
    | IsMissingOrBlank

type TextBox = inherit IBox<string, TextError>

/// Single or multi-line text without additional validation
type FreeText = private FreeText of string with
    interface TextBox with
        member _.Validate =
            fun s ->
                [if String.IsNullOrWhiteSpace s then IsMissingOrBlank]

Box.validate<FreeText> "John Doe"
```

**Expected behavior**

Expected successful execution

**Actual behavior**

I get the following error:

```
System.TypeLoadException: Could not load type 'TextError' from assembly 'FSI-ASSEMBLY, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

**Known workarounds**

I was able to make this code work in a Visual Studio project.

**Related information**

Provide any related information (optional):

* Windows 10
* .NET Runtime 5.0.103
* VS Code Insiders (notebook)

**Comment by lfr** [comment]
I've reduced it to a much smaller and simpler script that still generates the same error, and updated the original issue with it.

**Comment by cartermp** [comment]
Executing the entire script fails, but doing each line one at a time does not. So there's something quirky here.

**Comment by KevinRansom** [comment]
@cartermp --- good observation mate:

This works
````
#r "nuget: FSharp.Domain.Validation"

open FSharp.Domain.Validation
open System

type TextError =
    | IsMissingOrBlank

type TextBox = inherit IBox<string, TextError>

/// Single or multi-line text without additional validation
type FreeText = private FreeText of string with
    interface TextBox with
        member _.Validate =
            fun s ->
                [if String.IsNullOrWhiteSpace s then IsMissingOrBlank]
;;
Box.validate<FreeText> "John Doe"
;;
````
And produces this result:
````
Binding session to 'C:\Users\codec\.nuget\packages\fsharp.domain.validation\0.9.78\lib\net5.0\FSharp.Domain.Validation.dll'...
val it : Result<FreeText,TextError list> = Ok FreeText "John Doe"
````

There is certainly a bug here ...

**Comment by KevinRansom** [comment]
And also ...
executing it in a script is also an issue ...
````
c:\kevinransom\fsharp>dotnet fsi --exec foo.fsx


error FS0193: internal error: Could not load type 'FSI_0002' from assembly 'FSI-ASSEMBLY, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.


````

**Comment by dsyme** [comment]
Fixed by `--multiemit+` which is on by default for .NET Core (because the ilwrite.fs backend is used instead of ilreflect.fs)
