### ISSUE TITLE
FSharp.Core 5.0.1 should not have FSharp.Core.xml in contentFiles

### ISSUE THREAD

**Issue by johnendev** [dotnet/fsharp#11143]
The FSharp.Core 5.0.1 package contains the FSharp.Core.xml file under contentFiles. This means Visual Studio shows that file as being part of every FSharp project with that package version installed. This was not an issue in 5.0.0.

**Repro steps**

1. Create an F# project
1. Install FSharp.Core 5.0.1
1. Open the project in Visual Studio
1. Notice that FSharp.Core.xml is shown as a file in the project
1. Downgrade to 5.0.0
1. Notice that FSharp.Core.xml doesn't show anymore

[example.zip](https://github.com/dotnet/fsharp/files/6039962/example.zip)

**Comment by cartermp** [comment]
Repro looks like this on my machine:

![image](https://user-images.githubusercontent.com/6309070/109091830-56671680-76ca-11eb-81cb-857bd0fab3a1.png)

**Comment by cartermp** [comment]
PR that causes this: https://github.com/dotnet/fsharp/pull/10579

**Comment by KevinRansom** [comment]
This behaviour is by design.  Developers of tools who want to ship FSharp.Core with it's associated msbuild file have to perform msbuild FU to deploy the FSharp.Core.xml file.

For developers who do not want to deploy the content file with their projects can use this mechanism:
````
  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="5.0.1">
      <ExcludeAssets>contentFiles</ExcludeAssets>
    </PackageReference>
  </ItemGroup>
```` 
![image](https://user-images.githubusercontent.com/5175830/109101675-0abd6880-76dc-11eb-954d-23a7a4ecf8db.png)

**Comment by KevinRansom** [comment]
@cartermp , we could modify the automagic reference, to have : <ExcludeAssets>contentFiles</ExcludeAssets>
And have a switch to include it on something like:

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <FSharpCoreIncludeDocFileInOutput>true</FSharpCoreIncludeDocFileInOutput>
  </PropertyGroup>

**Comment by johnendev** [comment]
Yes I think having it as opt-in rather than opt-out would be better

**Comment by dsyme** [comment]
Yes I'm seeing FSharp.Core.xml actually added to any project that references FSharp.Core 5.0.1.  It has to be opt-in, very few people want to distribute this

**Comment by cartermp** [comment]
Yeah, the description from the PR is this:

> This changes the xmldoc comments file for FSharp.Core into a nuget contentFile. Following this change, build and publish will deploy the FSharp.Core.xml doc comment file to the output directory, without the build author having to do any extra work.

Which seems reasonable. But should _not_ result in XML docs being included in the solution tree at the file level. `bin`/`obj` items aren't displayed in the tree. So I think this is the wrong solution used to address the problem.

**Comment by cartermp** [comment]
Note I kept this as severy-high because starting with 16.9, my understanding is everyone will see this, including new projects. Is that accurate?

**Comment by dsyme** [comment]
> Note I kept this as severy-high because starting with 16.9, my understanding is everyone will see this, including new projects. Is that accurate?

Yes I'm seeing it everywhere

**Comment by baronfel** [comment]
If people are still seeing this, they may be using Paket, which doesn't honor the defaults set for this implicit package reference.

If you're using Paket, there is no _current_ solution, but after [this PR](https://github.com/fsprojects/Paket/pull/4040) is merged, you can use `content: none` on the group, package, or individual reference level to hide content files from packages, including FSharp.Core.

**Comment by charlesroddie** [comment]
I'm finding that this isn't resolved and that, if FSharp.Core is explicitly referenced, it needs
```
<PackageReference Include="FSharp.Core" Version="6.0.3">
  <ExcludeAssets>contentFiles</ExcludeAssets>
</PackageReference>
```
