### ISSUE TITLE
March rough work list

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#11167]
And we're back with another month. Here it is:

VS 16.10 work:

- [x] Burn down https://github.com/dotnet/fsharp/milestone/39
- [ ] @TIHan - Complete parallelization work in the compiler

Non-16.9 to work on:

- [x] @TIHan - Complete dotnet/performance work to track F# perf scenarios around build/rebuild, typechecking, etc.
- [x] @KevinRansom - dev17 setup packaging work
- [x] @KevinRansom - preliminary investigations into debugging improvements
- [x] @vzarytovskii - complete file system shim refactoring work and explore snapshot-based work with aims to help https://github.com/dotnet/fsharp/issues/2204
- [x] Bug fix work as it comes in

**Comment by Smaug123** [comment]
@vzarytovskii Hi - just checking in on how the filesystem shim refactor went. Before I start wading into the code, do you think it'll be true as of the next release of FCS that we should be fully able to shim out the filesystem? When I tried a few months ago to consume FCS with an in-memory filesystem, I hit a problem where I just couldn't stop FCS from trying to memory-map a (naturally nonexistent!) file on the *real* filesystem. I see there's now a `useMemoryMappedFile : bool` optional argument to `OpenFileForReadShim`, which looks very encouraging; do you know of any problems left which might force us to use a real filesystem? Thanks!

**Comment by vzarytovskii** [comment]
> @vzarytovskii Hi - just checking in on how the filesystem shim refactor went. Before I start wading into the code, do you think it'll be true as of the next release of FCS that we should be fully able to shim out the filesystem? When I tried a few months ago to consume FCS with an in-memory filesystem, I hit a problem where I just couldn't stop FCS from trying to memory-map a (naturally nonexistent!) file on the _real_ filesystem. I see there's now a `useMemoryMappedFile : bool` optional argument to `OpenFileForReadShim`, which looks very encouraging; do you know of any problems left which might force us to use a real filesystem? Thanks!

@Smaug123 

Hey Patrick, I've changed most of the places to use IFileSystem (with exception of dependency manager).

Only two places where we use MMF directly are `SemanticClassificationKey` and `ItemKey`, but solely for having MMF as a backing storage (i.e. we create new one) for big objects, instead of having them in memory.
