### ISSUE TITLE
Setting ApplicationIcon does not work in fsproj

### ISSUE THREAD

**Issue by 8** [dotnet/fsharp#11164]
I am trying to use an application icon in a fsharp project, but I don't get it to show up.

**Repro steps**

1. Create a new fsharp project
2. Copy an ico file to the project
3. Reference the ico file in the fsproject file
````xml
  ...
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>
  ...
````
4. Build the project
5. Notice that the output .exe does not have an application icon

I have attached a sample solution consisting of an f# and an c# application that both set the application icon in their corresponding project file.

**Expected behavior**

The specified icon file is used just like in the C# Application, that is it is embedded in the executable and

- visible in the windows taskbar when the application is running
- shown in the left upper corner of the window (if the application window uses the titlebar icon)
- visible in windows explorer when viewing the output .exe

**Actual behavior**

The default icon is shown.

**Known workarounds**

I am not aware of any.

**Related information**

Provide any related information (optional):

* Operating system - Win10
* .NET Runtime kind - .NET Core
[IconTest.zip](https://github.com/dotnet/fsharp/files/6067919/IconTest.zip)

**Comment by 8** [comment]
Oh, just found that it's already a known issue :-|
#10065

**Comment by cartermp** [comment]
No worries! Will close as a duplicate: https://github.com/dotnet/fsharp/issues/10065
