### ISSUE TITLE
Bug in IDE checking using VIsualFSharp.sln on main

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#11176]
"main" has a bug where opening VIsualFSharp.sln (after installing into RoslynDev ) reveals an error:

![image](https://user-images.githubusercontent.com/7204669/109825355-a8132200-7c31-11eb-910e-8860c7998d7b.png)

There are many other errors later in the solution as well, e.g. here in range.fs

![image](https://user-images.githubusercontent.com/7204669/109825522-ced15880-7c31-11eb-8eb8-dd8ade5ada4a.png)

It's a very strange problem, I will try to determine the source of the issue now. 

#### Repro

1. Build "main"

       .\build -c Release -deploy

2. Open VisualFSharp.sln

       devenv VisualFSharp.sln /RootSuffix RoslynDev

3. Open "lib.fs" and "range.fs" and see if the above errors occur (they shouldn't)

**Comment by dsyme** [comment]
I'm going to do a binary chop on the commit history to determine where this bug crept in

Starting with 178ec2f75337eaebe38cc92f486c7b01f9a73481 as a random point in time

**Comment by auduchinok** [comment]
This is what I see in Rider with an FCS build based on [`718d3c4`](https://github.com/dotnet/fsharp/commit/718d3c4970011dc0d8253572adbf529c87623d75):
<img width="1125" alt="Screenshot 2021-03-03 at 18 44 03" src="https://user-images.githubusercontent.com/3923587/109831399-7493c000-7c50-11eb-99a9-b25255e27ce8.png">

**Comment by dsyme** [comment]
Binary chop

- 178ec2f (18 days ago) - ok
