### ISSUE TITLE
FSharp.Core 5.0.2-beta.21102.10 and FSharp.Compiler.Service 39.0.3-preview.21102.10 are preview bits to unblock .NET Interactive

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#11171]
Quick update on these package versions if anyone has a question about them:

https://www.nuget.org/packages/FSharp.Core/5.0.2-beta.21102.10
https://www.nuget.org/packages/FSharp.Compiler.Service/39.0.3-preview.21102.10

Due to how package dependencies intersect with .NET tools, to unblock .NET Interactive we need to publish beta/preview versions of these packages (with wonky version numbers) to unblock .NET Interactive.

If we did not do this, then any use of a newer .NET Interactive would require every user to specify `#i` and a nuget source to be able to execute code.

**Don't depend on these beta/preview versions for your production systems!**

Or rather, just do so at your own risk.

In the future, this won't be a problem. But it comes with the territory of being a core dependency of a preview product, I suppose :)

**Comment by psantoro** [comment]
What's still confusing is that the product version of the FSharp.Core.dll files may still contain the word "beta".  For example, the following nuget releases have "beta" in their FSharp.Core.dll product versions (i.e. in Windows, right click on the DLL file, properties, details):

https://www.nuget.org/packages/FSharp.Core/5.0.0
https://www.nuget.org/packages/FSharp.Core/5.0.1

What am I missing here?

**Comment by cartermp** [comment]
Closing out announcement.

@psantoro what you're noticing is unrelated and has been the case since VS 2017. It's a requirement to allow updating through the VS extension marketplace for nightly builds. We disabled those recently though, so I guess it could be changed. But it doesn't seem to be much of a problem.
