### ISSUE TITLE
FSharp.Core package haven't IsImplicitlyDefined property

### ISSUE THREAD

**Issue by Rizzen** [dotnet/fsharp#11181]
I'm using F# with Visual Studio and there is FSharp.Core SDK package, which is implicitly referenced by SDK and automatically resolves its version. But isn't marked as such in contrast with, for example, NETStandard.Library and does not have ```IsImplicitlyDefined = true``` property in Microsoft.FSharp.NetSdk.props. So we can upgrade its version without an actual SDK upgrade.

Is it intended behavior or bug? Because I'd expect this package have ```IsImplicitlyDefined``` property set to true like NETStandard.Library.

**Comment by cartermp** [comment]
It's currently by design to not do this. See this comment for more information: https://github.com/dotnet/fsharp/pull/6730#issuecomment-492812881
