### ISSUE TITLE
IntelliSense popups can't be dismissed via Esc key

### ISSUE THREAD

**Issue by brianberns** [dotnet/fsharp#11183]
**Repro steps**

1. Using Visual Studio 16.9.0, type `Seq.m` in an F# source file.
2. Two popups appear. One lists functions in the `Seq` module, and the other shows the signature of `Seq.map` in particular.
3. Press the Esc key on the keyboard.
4. Nothing happens. Neither popup disappears.

**Expected behavior**

The Esc key should dismiss all IntelliSense popups.

**Actual behavior**

The Esc key fails to dismiss any IntelliSense popups.

**Known workarounds**

I have to move my hand to the mouse, and click on the background in order to dismiss the popups.

**Related information**

* Windows 10
* Visual Studio 16.9.0

**Comment by cartermp** [comment]
Hmm, I cannot reproduce this either in 16.9 or a preview of 16.10 build on my machine. Tested both in a script file and a new project:

* Somewhere in source (a valid location) type `Seq.m`
* Notice IntelliSense and the tooltip

![image](https://user-images.githubusercontent.com/6309070/110159791-01995f00-7da0-11eb-91cd-03fbbe4dd0a0.png)

* hit `Esc`
* Everything disappears

**Comment by cartermp** [comment]
Do you have a repro project you can share?

**Comment by brianberns** [comment]
Hmm, that's interesting. Maybe I have a bad install or something. Repro is trivial for me, in Program.fs:

```
[<EntryPoint>]
let main argv =
    Seq.m
    0
```

I will try to the same thing on another machine and report back.

**Comment by cartermp** [comment]
It dismissed it for me in the `main` function as well. Could you also perhaps have a setting toggled in an expected way? I'm not aware of any settings that would impact this though.

**Comment by brianberns** [comment]
I just tried it on another machine and the Esc key works fine there, so it must be something specific to this one box. You can go ahead and close this one and I'll open a different issue if I'm able to figure out what's causing it. Thanks for your help.

**Comment by cartermp** [comment]
Thanks for confirming! Strange that one machine does this though. Hopefully it doesn't come up again.

**Comment by brianberns** [comment]
FWIW, rebooting the problematic machine fixed the problem, so it was definitely just something weird about the state of that box.
