### ISSUE TITLE
Different behavior between .net 4.8 and .net 5.0

### ISSUE THREAD

**Issue by ingted** [dotnet/fsharp#11186]
1. git clone https://github.com/ingted/dotnet5mail
2. Modify the address and gmail app password
3. Build it and execute with a "The server response was: 5.7.0 Authentication Required" error. (.net 5.0)
4. Build it and execute without any error. (.net 4.8)
5. Execute the code in Fsi.exe (.net 4.8), and the email would be successfully sent.
6. Execute the code in Fsi.exe (.net 5.0), and the email would be failed to send.

**Expected behavior**

Both of them should be successful.

**Actual behavior**

Only .net 4.8 would successfully send the email.

**Known workarounds**

So far no.

**Related information**

Provide any related information (optional):

* Operating system: Windows Server 2019
* .NET Runtime: .net 5.0/ .net framework 4.8
* Editing Tools: 
   VS 16.9.0 PREVIEW 1.0 
   Microsoft (R) F# Interactive version 11.0.0.0 for F# 5.0

**Comment by ingted** [comment]
I use .net 4.8 to build the application. The email successfully sent.
So I guess the problem is caused by .net 5.0.

**Comment by cartermp** [comment]
I will close this out as external, as it appears this API isn't under active development and the recommendation is to use a different library.
