### ISSUE TITLE
Compiler generates debug symbol document record 'unknown'

### ISSUE THREAD

**Issue by marklam** [dotnet/fsharp#11195]
Inlining (some complicated) code from another assembly causes the pdb symbols to contain a reference to a file called 'unknown'.
This breaks code coverage tools like coverlet, because it skips the assembly when it can't find an on-disk file called 'unknown'.

**Repro steps**

1. Create some very complicated code to inline
2. Reference that code from another assembly
3. Check the Documents in the debug metadata

I've created a repo which does these steps and put it in github: https://github.com/marklam/FSharpPdbUnknown
(If a zip is preferred, https://github.com/marklam/FSharpPdbUnknown/archive/master.zip should do it)

**Expected behavior**

The documents in the PDB (which the referenced project can automatically list) should only contain 'Program.fs'

**Actual behavior**

The documents include 'Program.fs' and 'unknown'

**Known workarounds**

Dropping an empty file called 'unknown' in the source directory will make Coverlet happy about producing coverage for the assembly.

**Related information**

* Operating system Windows 10
* .NET Runtime kind .net core 5
* Editing Tools Visual Studio 16.9

**Comment by baronfel** [comment]
Worth noting that this file comes from uses of the `range0` member (eg from anonymous record codegen), but would likely come from anywhere the `rangeStartup` or `rangeCommandLineArgs` members were exposed as well. I'm not sure if there's a reasonable workaround from the compiler's point of view for these cases...

**Comment by dsyme** [comment]
I checked the repro and it no longer generates `unknown` using `main`

The problem may still be around though - looking at the code it's a FeeFee debug point with file name `unknown` 

I'll close this until we get another repro
