### ISSUE TITLE
Display.any_to_layout not available after .net 5 (5.0.3) upgraded

### ISSUE THREAD

**Issue by ingted** [dotnet/fsharp#11192]
**Repro steps**

1. Start fsi with command

```
dotnet "C:\Program Files\dotnet\sdk\5.0.200\FSharp\fsi.dll"
```

and execute
```
#r @"C:\Program Files\dotnet\sdk\5.0.200\FSharp\FSharp.Compiler.Private.dll"
open FSharp.Compiler.Text
open Microsoft.FSharp.Text.StructuredPrintfImpl
let a x = x + 1
Display.any_to_layout FormatOptions.Default (a, a.GetType())
```

It would have result
```
--> Referenced 'C:\Program Files\dotnet\sdk\5.0.200\FSharp\FSharp.Compiler.Private.dll' (file may be locked by F# Interactive process)


  Display.any_to_layout FormatOptions.Default (a, a.GetType());;
  ^^^^^^^

stdin(14,1): error FS0039: The value, namespace, type or module 'Display' is not defined.
```

2. Start fsi with command

```
dotnet "C:\Program Files\dotnet\sdk\5.0.102\FSharp\fsi.exe"
```

and execute
```
#r @"C:\Program Files\dotnet\sdk\5.0.102\FSharp\FSharp.Compiler.Private.dll"
open Internal.Utilities.StructuredFormat
Display.any_to_layout FormatOptions.Default (a, a.GetType());;
```

and get result
```
--> Referenced 'C:\Program Files\dotnet\sdk\5.0.102\FSharp\FSharp.Compiler.Private.dll' (file may be locked by F# Interactive process)

val a : x:int -> int
val it : Internal.Utilities.StructuredFormat.Layout =
  Leaf
    (false, Internal.Utilities.StructuredFormat.TaggedTextOps+mkTag@119, false)
```

**Expected behavior**

In first step, module Display should be available like in step 2.

**Actual behavior**

module Display with latest .net distribution is not available.

**Known workarounds**

None

**Related information**

Provide any related information (optional):

* Operating system: windows server 2019
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .net 5 (5.0.2) (5.0.3)
* Editing Tools (e.g. Visual Studio Version, Visual Studio): 
*
Microsoft (R) F# Interactive version 11.0.0.0 for F# 5.0
Microsoft (R) F# Interactive version 11.3.2.0 for F# 5.0

**Comment by cartermp** [comment]
This is by design, and in the future you won't be able to reference the private `.dll` either since it will just be `FSharp.Compiler.Service`. This was a major version change in FCS to clean up the API with aims to make it binary compatible in the future.

**Comment by ingted** [comment]
But FCS is so old?! The last commit f73e30f was on Aug 8, 2020...

**Comment by baronfel** [comment]
You might be looking at the old, no longer maintained fsharp/fsharp.compiler.service repository. For some months now, FCS has been published from this repository alongside the compiler and other tooling.

**Comment by ingted** [comment]
Hi @baronfel, 
Excuse me, so if I want to print a function easily... which API should I use in the future? And what namespaces/module should I open?

**Comment by cartermp** [comment]
You'll need to clarify what you mean by "print a function easily". Are you looking for a signature? Or an evaluated result? The example you provided in the issue text doesn't do either.

In the case of a signature, you can use FCS APIs to extract symbol information from source text and print things based on the kind of symbol you're working with. For an evaluated result, just using `%A` is sufficient and correct.
