### ISSUE TITLE
Re-enable XML doc comment generation

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#11202]
XML doc comment generation was disabled in the leadup to VS 2019 16.0 because we were experiencing severe perf problems for larger codebases. The current implementation would allocate a large string on the UI thread and potentially cause a long UI delay, which would be greatly exacerbated by the perf issues at the time. This context is no longer relevant, so we should re-enable it and see if there's some improvements to make.

**Comment by abelbraaksma** [comment]
This would be great! There are quite a few related reports, probably more than just the ones i know:

https://github.com/dotnet/fsharp/issues/7844
https://github.com/dotnet/fsharp/issues/3213
https://github.com/fsharp/fslang-suggestions/issues/948
https://github.com/fsharp/fslang-design/blob/master/tooling/FST-1031-xmldoc-extensions.md

**Comment by abelbraaksma** [comment]
Looking at the PR, I think I was mistaken. This enables inline generation of the tags, but doesn't fix the generation of the doc comments for display in the editor, the latter being the focus of the other bugs.
