### ISSUE TITLE
Pattern matching codegen bug?

### ISSUE THREAD

**Issue by En3Tho** [dotnet/fsharp#11211]
Is it me or this code simply does not do what it's expected to do?

1. Does build and I think that the bug is that IT DOES build...
``` fsharp
let test = "/"
match test with
| "/"
| _ as path when path.Contains "a" ->
    printf "%s" path
    true
| other ->
    printf "%s" other
    false
```

2. Doesnt' build -> this is ok
``` fsharp
let test = "/"
match test with
| "/"
| path when path.Contains "a" ->
    printf "%s" path
    true
| other ->
    printf "%s" other
    false
```

3. This does build and looks ok, but does generate something completely unexpected
``` fsharp
let test = "/"
match test with
| "/"
| _ when test.Contains "a" ->
    true
| other ->
    printf "%s" other
    false
```

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEAzAzgHwgAcYA7AAgGUBPXAFxgFsBYAKAxjvIfvIF5yAIgD0gtuQmSJbDlx50AYgFdSARgAUASn7lhw8gAsIAd3IATCDFzcDAS2swAbmXLAltjGYD85AOp1scntyAHMyGCgAQwZvcUlGaLADbisuY1s6AziJfCFRbPJcgH1ySOsiaOTjAxcKzIA6AGEIUjpI21JrQUjBcjgAPgKpOiglGALciEyIvsHWKSkiKA6AoQBSXF6pmqghyWxIjFxx1jY9G2CLK3JSKdd3TzQgugByawgAazP9WRT6ZVIACYtDoCnoEnQkn80hksvNJHpciIxPCJIjyHUqjUKJimi02h0uj1ZmD9JIlitAoINr1MaThqMTlJ0dsZgN6eTlq0qTTyKzdqjdGSJAcjkyFtJ2JxoQCAMwggTnfyBYJhUgRaIwWKCiFQ+TkdKZCZ5FFSYoG7HQvGtdqdITE9mChljY382YSyUe8ii45AA=

**Comment by Lanayx** [comment]
A related issue when brackets lead to the same result, but I can't interpret what is going on
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEAzAzgHwgAcYA7AAgGUBPXAFxgFsBYAKAxjvIfvIF5yARjYcu1fm3JTyjAIZ0wAC24xeAdwCWdRZOn5yACkHl9ggJTk1isit4CATOTgA+blACuMXVP0B9J67Yshi4MEA

**Comment by En3Tho** [comment]
Not a bug. Soz.

**Comment by auduchinok** [comment]
I'd say the first example should not build due to different bound name sets on the side of `|` (i.e. `[]` and `[path`]).

**Comment by TheJayMann** [comment]
The first one is just fine, build wise, as only one `as` clause is permitted per pattern matching group, thus, the `path` value is assigned both cases of `"\"` and `_`.  Essentially, the first example would have the same result as the following.
```fsharp
match test with
| "/" as path when path.Contains "a" ->
    printf "%s" path
    true
| _ as path when path.Contains "a" ->
    printf "%s" path
    true
| other ->
    printf "%s" other
    false
```
