### ISSUE TITLE
Rewrite skipped tests involving disposal/cancellation/etc.

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#11219]
This PR disabled some bad tests: https://github.com/dotnet/fsharp/pull/11218

These tests are _not good_ because they ultimately rely on some kind of timing invariant (explicit or implicit) and that invariant doesn't hold on the degraded pools we're running on for CI now.

These tests need to be rewritten.

**Comment by cartermp** [comment]
Another one: https://github.com/dotnet/fsharp/pull/11225

**Comment by dsyme** [comment]
Disabled tests now covered by single tracking issue: https://github.com/dotnet/fsharp/issues/10958
