### ISSUE TITLE
Broken Map Documentation link.

### ISSUE THREAD

**Issue by nhirschey** [dotnet/fsharp#11210]
The Map type link is broken.

**Repro steps**
1. Go to the [Map Module](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-mapmodule.html) documentation page.
2. Click on the "Map" link in the sentence at the top "Contains operations for working with values of type [Map](https://docs.microsoft.com/en-us/dotnet/api/microsoft.fsharp.collections.map-2)." 
3. Arrive at a [404](https://docs.microsoft.com/en-us/dotnet/api/microsoft.fsharp.collections.map-2)

**Expected behavior**
I expect to arrive at this page: https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-fsharpmap-2.html

I am not sure, but it is possible that the fix is to change this linked line to say 
```fsharp see cref="T:Microsoft.FSharp.Collections.FSharpMap`2"/>```
instead of  
```fsharp see cref="T:Microsoft.FSharp.Collections.Map`2"/>```

https://github.com/dotnet/fsharp/blob/2b7517d5a7cc65cc79a109953bf91293054932ef/src/fsharp/FSharp.Core/map.fsi#L97

I looked into making a pull request, but I was not sure how to build the docs so I am unable to check if the fix works.

**Comment by cartermp** [comment]
Hmm, yes that's probably the right change. Same would need to be done for Set, perhaps others?

**Comment by cartermp** [comment]
@dsyme which is the correct fix?

**Comment by baronfel** [comment]
Should FSharp.Formatting be able to handle type name _and_ compiled name for references like this? How much of a burden do we want to put on authors vs implementors?

**Comment by cartermp** [comment]
YEAH, IT SHOULD BE ABLE TO HANDLE BOTH

**Comment by cartermp** [comment]
oh, oops, caps

**Comment by cartermp** [comment]
It should be able to handle both

**Comment by dsyme** [comment]
Fixed in https://github.com/dotnet/fsharp/pull/12899 and general issue of CompiledName tracked by https://github.com/fsprojects/FSharp.Formatting/issues/741
