### ISSUE TITLE
Add range of SynConst value to SynEnumCase

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#11226]
**Is your feature request related to a problem? Please describe.**
Hello, I would like to extend the SyntaxTree with the range of [SynConst](https://fsharp.github.io/FSharp.Compiler.Service/reference/fsharp-compiler-syntaxtree-synconst.html) in a [SynEnumCase](https://fsharp.github.io/FSharp.Compiler.Service/reference/fsharp-compiler-syntaxtree-synenumcase.html).

Imagine the following:
```fsharp
type Foo =
    | One =  0x00000001
    | Two = 0x00000002
```

```fsharp
Simple
  (Enum
     ([EnumCase
         ([], One, Int32 1,
          PreXmlDoc ((2,5), FSharp.Compiler.XmlDoc+XmlDocCollector),
          tmp.fsx (2,6--2,23) IsSynthetic=false);
       EnumCase
         ([], Two, Int32 2,
          PreXmlDoc ((3,5), FSharp.Compiler.XmlDoc+XmlDocCollector),
          tmp.fsx (3,6--3,22) IsSynthetic=false)],
      tmp.fsx (2,4--3,22) IsSynthetic=false),
   tmp.fsx (2,4--3,22) IsSynthetic=false)
```

**Describe the solution you'd like**
The range of EnumCase spans across `One =  0x00000001`, I'd like to know the range of `0x00000001`.

**Describe alternatives you've considered**
Checking the tokens might work, but it does involve a lot of jumps to check this.

**Additional context**
FCS 39.0.0

**Comment by cartermp** [comment]
Seems like a reasonable addition.
