### ISSUE TITLE
Working list of F# version of Roslyn feature APIs to open up

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#11238]
Roslyn defines many interfaces and APIs that allow for certain visual studio features to light up.

Today, we get to access these via a shim layer. This avoids proliferation of IVTs and keeps the F# tools from breaking whenever Roslyn changes an internal API that affects us.

However, it does mean that if we want to light up a capability in VS that depends on one of those internal APIs, we need to add to the shim layer and rev our Roslyn depdendency.

This is a working list of APIs to get access to:

* `IOption2` - http://sourceroslyn.io/#Microsoft.CodeAnalysis.Workspaces/IOption2.cs,451e09f76344ba9d - lets us use Roslyn's option API for VS options. Currently a requirement for us to ever have Inline Hints.
* `ITodoCommentService` - http://sourceroslyn.io/#Microsoft.CodeAnalysis.Features/TodoComments/ITodoCommentService.cs,e9b881986ac3af0b - required for us to ever implement support for Task List
* A hook into custom document diagnostic analyzers, so we can hook in our own analyzers
* A hook into codelens, if possible?

**Comment by dsyme** [comment]
Closing this as it was an old tracking issue, and the future movement will be towards LSP
