### ISSUE TITLE
NuGet MSBuild/dotnet probing may not work properly outside VS/VS Code

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#11247]
The package manager [utility](https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSharp.DependencyManager.Nuget/FSharp.DependencyManager.Utilities.fs) may not be able to find .NET SDK and/or MSBuild due to variables like `VSAPPIDDIR` and `VSINSTALLDIR` may not be set in a process hosting FCS.

It also checks current runtime it's loaded into to decide between .NET/.NET Core + dotnet and .NET Framework + MSBuild to be used for evaluating the generated project. It doesn't look right since tools like VS/Rider may run on .NET Framework and use .NET/.NET Core scripting. For a .NET Framework process it makes the utility try to locate MSBuild instead of dotnet which it fails to do due to reason above.

@KevinRansom I'd like to work on a fix for this, but I'd appreciate your opinion here before proceeding. Can we add more parameters that FCS would pass to the package manager? A string for SDK/MSBuild path and/or a bool for core runtime seems OK.

**Comment by cartermp** [comment]
cc @KevinRansom

**Comment by cartermp** [comment]
Hmmm, using the latest 16.10 previews on my machine, with scripting set to netcore, design-time all works as expected when referencing various packages (e.g., Suave which is netstandard2.1). Is there an issue you've noticed with Rider here?

**Comment by KevinRansom** [comment]
@auduchinok ... I hate that probing code ... I have an idea to eliminate it, but it's not going to happen soon.

What exactly is going wrong?  we no longer use msbuild.exe in package management, only dotnet.exe.  Those environment variables should not be used or useful.  Add the directory containing dotnet.exe to the path environment variable or set the DOTNET_HOST_PATH to the path to dotnet.exe (only when running on the coreclr though).

The best and most reliable mechanism is to ensure that dotnet.exe is in the path or dotnet is in the path on linux.  It just makes everything simple.

**Comment by KevinRansom** [comment]
@auduchinok ... the most recent FSharp.CompilerServce libraries do still have a dependence on msbuild which is unfortunate.

**Comment by KevinRansom** [comment]
FCS 40.0.0 will be the package you want.   Dev16.8 does not have the change.

**Comment by KevinRansom** [comment]
We will try to publish a preview.

**Comment by KevinRansom** [comment]
Published:  https://www.nuget.org/packages/FSharp.Compiler.Service/40.0.0

**Comment by auduchinok** [comment]
@KevinRansom Sorry, I've added a workaround and haven't seen the replies. I'll see if we can do a change that will remove the workaround and will get back to you if there's anything to share. Thanks!

**Comment by KevinRansom** [comment]
@auduchinok thanks mate,
