### ISSUE TITLE
Left arrow doesn't work in VS FSI on 16.10 previews

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#11251]
Using latest 16.10 previews, open VS FSI (.NET Core version)

1. Type some code
2. Use the left arrow

![image](https://user-images.githubusercontent.com/6309070/111375840-f70e7d80-865b-11eb-8fa0-e3102f9fae2d.png)

It doesn't work.

ctrl+left arrow does work.

**Comment by asik** [comment]
I'm seeing the same thing in 16.9.2. FSI version is `Microsoft (R) F# Interactive version 11.3.2.0 for F# 5.0`
