### ISSUE TITLE
F# type hints display , when wrapping code they dont collapse

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#11257]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F-type-hints-display--when-wrapping-co/1367097)._

---
[severity:It bothers me. A fix would be nice]
when collapsing a code section, type displays are a bit scattered in the page, and don't collapse propertly

! [image.png] (https://aka.ms/dc/image?name=Bdc9db7309a5a4e2ab84f873baf634445637510634119255476_20210311-134305-image.png&tid=dc9db7309a5a4e2ab84f873baf634445637510634119255476)

---
#### Feedback Bot on 3/11/2021, 07:10 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by dsyme** [comment]
The image is no longer available, will close
