### ISSUE TITLE
Disable diagnostics in temporary metadata document

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#11279]
We now support Go to Def on external .NET symbols in a temporary document. However, diagnostics are still triggered for the document. This creates red squiggles in (often) lots of locations, but these are useless and unactionable.

@tihan had mentioned that it would be tricky to figure this out though.

**Comment by dsyme** [comment]
I'm not seeing these diagnostics in VS2022

F12 on HtmlAttributeExtensions here:
```
#r "nuget: FSharp.Data"

type A = FSharp.Data.HtmlAttributeExtensions
```
