### ISSUE TITLE
Supporting going to F#-defined metadata items and printing out a signature-like document

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#11278]
We can Go to Definition on an externally-defined symbol now, but only if it is a non-F# symbol. We should support showing a metadata view for these as well.

This is actually fairly easy to enable today, and with a small amount of work in FCS could be robust. But that's not the hard part. The current system uses a decompiler, and the decompiled view of F# code (especially from FSharp.Core) looks **terrible**.

To get around this, we really need an F# signature-like view like in https://github.com/dotnet/fsharp/pull/2658

This shouldn't be too challenging to hook up now that we have all the difficult quirks around a temporary document worked out.

cc @TIHan

**Comment by NinoFloris** [comment]
Why wouldn't the view first try to use source link? This is at least what rider does and it works well for packages that do support it

**Comment by baronfel** [comment]
Yep, that's what we do in ionide as well and it works great! There are still same gaps around typechecking the new file (we'd need to add support for writing the source files' compile flags to the pdb, for example) but overall it works well

**Comment by cartermp** [comment]
Yeah, good point. We should have that hooked up. But we do need to handle the case where there aren't sources linked.

**Comment by dsyme** [comment]
This was implemented quite a while back
