### ISSUE TITLE
Investigate graphMode for solution build

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#11281]
In several larger solutions, I've seen `graphMode:True` reduce total build times from the command line. We should see if it's possible to use here and if it improves things.

**Comment by cartermp** [comment]
Also investigate `-isolate` but I doubt it would work: https://github.com/dotnet/runtime/issues/41975#issuecomment-728331107

**Comment by vzarytovskii** [comment]
> In several larger solutions, I've seen `graphMode:True` reduce total build times from the command line. We should see if it's possible to use here and if it improves things.

@cartermp do you mean msbuild project graph? If yes, I can look at it, I've been experimenting with it recently.

**Comment by cartermp** [comment]
Yep. If you'd like to look into it that'd be cool too. I was planning on:

* `dotnet build` on FSharp.sln
* `dotnet build -graph` on FSharp.sln
* Compare to see if the difference is meaningful
* Add /graphBuild:True to `Build.ps1` and check timings as well
* If things work out to be faster generally (even if not that much faster) add a `Directory.build.rsp` file with the switch added

Additionally I was planning on laughing at how many errors would occur with `-isolate`

**Comment by dsyme** [comment]
`dotnet build` = 3min 42sec
`dotnet build -graph` = 3min 30sec

I think I'll close this since this isn't so dramatic.  @cartermp @TIHan @brettfo @vzarytovskii @KevinRansom Please submit a PR if you'd like to proceed with this?

**Comment by cartermp** [comment]
That's actually pretty good. 5% reduction in build times just by adding a switch, so saving a full build's worth of compute every ~15 builds.

**Comment by cartermp** [comment]
we'll see what happens here: https://github.com/dotnet/fsharp/pull/13019
