### ISSUE TITLE
FCS Nightly / Prerelease

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#11285]
Hello, this might be an expectation problem on my end but the last preview NuGet package (on https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json) seems to date from last month.

![image](https://user-images.githubusercontent.com/2621499/111899909-ccdc0780-8a2f-11eb-825d-e532e4a23d1c.png)

Could I find a newer one somehow?

**Comment by baronfel** [comment]
I can verify this issue, something going wonky with the nightly build?

**Comment by baronfel** [comment]
Figured it out: `main` has 39.0.0 version tags in Version.props, which are behind the publiclly-published 39.0.2 versions on Nuget.

**Comment by nojaf** [comment]
Thanks Chet!

**Comment by baronfel** [comment]
@nojaf it might be good to keep this open and let the resolution be bumping the versions to 40.0.0 in `main` so that 40.x prereleases start getting made. What do you think?

**Comment by nojaf** [comment]
Good idea, would be easier to have a semantically correcter version.

**Comment by cartermp** [comment]
cc @KevinRansom

**Comment by baronfel** [comment]
This can be closed now that 40.0.0 nightlies are being made

**Comment by KevinRansom** [comment]
thanks mate.

**Comment by baronfel** [comment]
working like a charm now, thank you :)

![image](https://user-images.githubusercontent.com/573979/114276530-9cfba080-99ec-11eb-806c-2cdaac62961d.png)
