### ISSUE TITLE
Non-F# warning from <WarningsAsErrors> breaks compilation of F# projects

### ISSUE THREAD

**Issue by asik** [dotnet/fsharp#11300]
Our solution is a mix of C# and F#. I was trying to convert a nuget warning into a nuget error by changing a common `.props` file that is imported by all our projects, and would contain the following:
```xml
<PropertyGroup>
    <WarningsAsErrors>$(WarningsAsErrors);NU1702</WarningsAsErrors>
</PropertyGroup>
```

This does convert the warning to an error, and C# projects keep building fine. However, all F# projects now fail with:
`error FS0241: 'NU1702' is not a valid integer argument`

I assume that what C# does is ignore codes it doesn't recognize. Is there a workaround for F#, or shouldn't it be doing to same thing?

**Comment by cartermp** [comment]
Tracking as a feature request since this isn't really part of the core design. Would certainly welcome a PR in this area.

**Comment by KevinRansom** [comment]
This should work, that it doesn't is a bug.  We certainly support non numeric error numbers for --nowarn:  We even have a test for it cos we are that good :-)

https://github.com/dotnet/fsharp/blob/d6a1195f978943b3f34d85c22ae98eee95cd563c/tests/fsharpqa/Source/CompilerOptions/fsc/warn/env.lst#L14
