### ISSUE TITLE
Differentiate between signature and implementation files in Go to All results

### ISSUE THREAD

**Issue by kerams** [dotnet/fsharp#11317]
When looking up `mknull` with Ctrl+T, the results look like this
![devenv_uk7BiHtE2J](https://user-images.githubusercontent.com/5063478/112750542-7a6b8f80-8fc9-11eb-898e-dc771543bcf0.png)

There's no way to tell which results corresponde to implementations and which to signatures. (And the order of `QuotationPickler.mkNull` results is a bit weird)

What's worse, the first `mkMutableCompGenLocal` result when searching for `mkmut` always takes me to the signature file, but when searching for `mkmuta` the implementation is the first. In other words, where you're navigating is a coin toss and it gets even more annoying when I reopen Go to All and proceed to select the same option again thinking I chose the other one previously...

**Describe the solution you'd like**
Perhaps the bottom line could say `signature for module FSharp.Compiler.TypedTreeOps` instead of `module FSharp.Compiler.TypedTreeOps` or something along those lines.

**Describe alternatives you've considered**
Always order implementation and signature in the same manner, so that I know if I select the first of the 2, I will always be taken to signature for instance.

**Comment by smoothdeveloper** [comment]
I feel the physical location (filename, or more to disambiguate, possibly highlighting the differences for result bearing identical identifier) would be the most effective, the suggestion "signature for" feels it would add more contextual noise than signal compared to just the physical location.

I like how resharper does it, it even brings the line number and is very compact, so it may be worth to draw inspiration from there too.

**Comment by cartermp** [comment]
Could be done like this? 
![image](https://user-images.githubusercontent.com/6309070/112899641-43fc4600-9097-11eb-8141-507631bc745a.png)

**Comment by smoothdeveloper** [comment]
Worth the improvement for a next VS update 🙂

**Comment by cartermp** [comment]
This looks better IMO, will go with this:

![image](https://user-images.githubusercontent.com/6309070/112908247-136ed900-90a4-11eb-8452-cae96d74a376.png)

There's some more fancy stuff that might be possible with tagged text, but I think this is clear enough.

**Comment by kerams** [comment]
Kickass!
