### ISSUE TITLE
Invalid code in Optimizer.fs

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#11321]
Hello,

I couldn't help but noticing the following function in [Optimizer.fs](https://github.com/dotnet/fsharp/blob/d7778adec2cfc8fb2b072a50828c82e180b06751/src/fsharp/Optimizer.fs)

https://github.com/dotnet/fsharp/blob/d7778adec2cfc8fb2b072a50828c82e180b06751/src/fsharp/Optimizer.fs#L513-L523

If `CHECKED` is passed a compiler define than this doesn't appear to be valid code.

Context:
I'm trying to format all source code with Fantomas and when it encounters `#if FOO` expressions in the source, it will format the code multiple times with different define combination. My problem occurred when create an Untyped AST tree with `CHECKED` for Optimizer.fs.

Would you accept a PR to fix this? Or is there some other clean-up I can perform?

**Comment by cartermp** [comment]
I think we'd definitely look at a PR and see if anything breaks :)

**Comment by kerams** [comment]
Incidentally, has that `env` just been forgotten after a round of refactoring/changes or is it a parameter for a specific reason that eludes me?
