### ISSUE TITLE
Record field inref/byref don't work when record is defined in another assembly 

### ISSUE THREAD

**Issue by thinkbeforecoding** [dotnet/fsharp#11335]
Please provide a succinct description of the issue.

When types are defined in the same assembly, & can be used to get a reference to a record field. But when another assembly, it doesn't compile.
[reftest.zip](https://github.com/dotnet/fsharp/files/6239281/reftest.zip)

Provide the steps required to reproduce the problem:

define structs in an assembly AsmX:

```
module AsmX
open System
[<Struct>]
type A =
    { x: int
      y: int }
[<Struct>]
type B =
    { a: A
      b: int } 
```

Try to create reference to record field in an assembly AsmY referencing AsmX:
```
module AsmY
open AsmX

let readA (a: A inref) =
    printfn "%d %d" a.x a.y


let read (b: B inref) =
    readA &b.a


let test() =
    let  b= { a = { x = 1; y = 2}; b = 3 }
    read &b
```

AsmY doesn't compile:
error FS3236: Cannot take the address of the value returned from the expression. Assign the returned value to a let-bound value before taking the address.

When defining types in the same assembly, it compiles and behave correctly. The same this happens for byref references.

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.
A zip is attached to reproduce the problem

**Expected behavior**

This code should compile the same way it does when types are defined in the assembly.

It emits an error:
error FS3236: Cannot take the address of the value returned from the expression. Assign the returned value to a let-bound value before taking the address.

**Known workarounds**

Copy types in the assembly (rarely doable), passing structs by value (costly when structs are large)

**Related information**

* Operating system Irelevant
* .NET Runtime kind net 4.5 netcore3.1 net5.0
* Editing Tools VisualStudio 2019/VSCode + ionide

**Comment by thinkbeforecoding** [comment]
I found this:

https://github.com/dotnet/fsharp/blob/main/src/fsharp/TypedTreeOps.fs#L6248

```
let CanTakeAddressOfRecdFieldRef (g: TcGlobals) m (rfref: RecdFieldRef) tinst mut =
    // We only do this if the field is defined in this assembly because we can't take addresses across assemblies for immutable fields
```
Which seems to indicate that it's by design.
But what is the reason ?

**Comment by NinoFloris** [comment]
Because public record fields are actually properties – the fields are internal – and you can't take an address on a property.

**Comment by thinkbeforecoding** [comment]
Makes sense.. And backing fields are internal?

**Comment by cartermp** [comment]
Yeah, this would be by design. Perhaps this could be revisited at some point.
