### ISSUE TITLE
Add Range member for SynModuleOrNamespaceSig

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#11346]
[SynModuleOrNamespaceSig](https://fsharp.github.io/FSharp.Compiler.Service/reference/fsharp-compiler-syntaxtree-synmoduleornamespacesig.html) has no `Range` member while [SynModuleOrNamespace](https://fsharp.github.io/FSharp.Compiler.Service/reference/fsharp-compiler-syntaxtree-synmoduleornamespace.html) does have one. 
Would it be ok to add this?

**Comment by cartermp** [comment]
Yep, feel free to send a PR.
