### ISSUE TITLE
When executing dotnet fsi from an xcopy deployed dotnet sdk

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#11358]
unknown(1,1): warning FS3384: The .NET SDK for this script could not be determined. If the script is in a directory using a 'global.json' then ensure the relevant .NET SDK is installed. Unexpected error 'Could not find a part of the path 'C:\kevinransom\sdk\artifacts\bin\redist\Debug\dotnet\packs\Microsoft.NETCore.App.Ref\0.0.0.0\ref'.'.

**Comment by teo-tsirpanis** [comment]
I also experienced it when running `fsi` on an installed .NET 6 Preview 3 SDK on Windows.

**Comment by KevinRansom** [comment]
@teo-tsirpanis --- this is fixed in dotnetsdk 6.0-preview5+

https://github.com/dotnet/installer#installers-and-binaries
