### ISSUE TITLE
Invalid code in QueueList.fs

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#11369]
Hello,

Similar to #11321, I found that 

https://github.com/dotnet/fsharp/blob/d7778adec2cfc8fb2b072a50828c82e180b06751/src/fsharp/QueueList.fs#L83-L91

does not appear to be valid code when `QUEUE_LIST_UNITTESTS` is enabled.
The closing `*)` does not appear to have a matching opening `(*`.
Could this block be removed?

**Comment by vzarytovskii** [comment]
Not sure why it's even there :) I'm pretty sure there was a good reason, but I think we should clean it up.

**Comment by cartermp** [comment]
Yes, this can definitely be removed. I imagine it is old, old, old code that is long since unecessary. Feel free to submit a PR!
