### ISSUE TITLE
Dotnet fail with code 139

### ISSUE THREAD

**Issue by MarcCoquand** [dotnet/fsharp#11365]
When trying to run dotnet build on a fresh project on Linux, I get the issue:

/usr/share/dotnet/sdk/5.0.201/FSharp/Microsoft.FSharp.Targets(281,9): error MSB6006: "dotnet" exited with code 139. [/home/marc/Projects/FSharpProject/src/Test.fsproj]

Build FAILED.

/usr/share/dotnet/sdk/5.0.201/FSharp/Microsoft.FSharp.Targets(281,9): error MSB6006: "dotnet" exited with code 139. [/home/marc/Projects/FSharpProject/src/Test.fsproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:04.33

1. Use ubuntu 20.10 and dotnet version 5.0.201
2. Try to build a normal project in vscode

I expected the project to build, what's odd is that it actually builds for Ionide and I get syntax highlighting. I can also get it to build on my docker image which uses alpine linux.

Instead, the build failed with the error message above.

**Actual behavior**

Provide a description of the actual behaviour observed. 

**Known workarounds**

I could use docker instead to continue the development and run the project locally. However, it's not ideal since I want to do dotnet watch.

```
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.10
 OS Platform: Linux
 RID:         ubuntu.20.10-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.201/

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  5.0.201 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by cartermp** [comment]
No idea what this could be (I have several ubuntu environments where this doesn't repro), but did you happen to install via snap?

**Comment by MarcCoquand** [comment]
I did not install via snap, I followed the instructions on the webpage. However, I did reinstall it and then it started working again. Very confused. :sweat_smile:

**Comment by vzarytovskii** [comment]
> I did not install via snap, I followed the instructions on the webpage. However, I did reinstall it and then it started working again. Very confused. :sweat_smile: 

It sounds like it was corrupted dotnet installation. 
Good thing that the fix was as easy as just reinstalling the sdk :)
