### ISSUE TITLE
FxResolver doesn't determine TargetFrameworkMoniker correctly when app has been built with a RuntimeIdentifier

### ISSUE THREAD

**Issue by nosami** [dotnet/fsharp#11389]
Please provide a succinct description of the issue.

I have built a self-contained, single file executable containing all the dotnet framework assemblies using `osx.10.11-x64` as the `RuntimeIdentifier`. This file will eventually be the backend process for F# Interactive running inside of VS Mac.

My deps.json file contains the following at the top

```json
{
  "runtimeTarget": {
    "name": ".NETCoreApp,Version=v3.1/osx.10.11-x64",
    "signature": ""
  },

```
There seems to be a bug in FxResolver here https://github.com/dotnet/fsharp/blob/0794281d0bf6f879aa2ed2bccbadb166268f91b3/src/fsharp/FxResolver.fs#L337-L346

 as it determines the TFM to be `netcoreapp3.1/osx.10.11-x64` when it should be `netcoreapp3.1`. I guess the code should look for either `/` or `"` when parsing and stop at whichever comes first.

This in turn causes the following error when trying to resolve a package using the new `#r` syntax

```
 #r "nuget: Octokit";;
/usr/local/share/dotnet/sdk/5.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(92,5): error NETSDK1013: The TargetFramework value 'netcoreapp3.1/osx.10.11-x64' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly. [/var/folders/bt/bfcvw15x1k78bkc284cnjz9c0000gn/T/nuget/49995--3b2566bd-d269-4f1a-8cdf-e1ea003e8cb6/Project.fsproj] at 2,0
```

**Comment by cartermp** [comment]
cc @KevinRansom

**Comment by KevinRansom** [comment]
The code has changed several times since this bug was issued.
