### ISSUE TITLE
Incovenient (and inconsistent) cursor positioning after entering new line between brackets

### ISSUE THREAD

**Issue by ArtemyB** [dotnet/fsharp#11401]
**Repro steps**

The issue can be seen when entering some of the F# brackets ( `(`, `[`, `{`, `[|`) on the indentation level greater then initial (sorry for this strange wording -- the GIF given below should make my message clear).

![Issue demo](https://i.imgur.com/q4FW4lM.gif)

**Expected behavior**

The expected behavior (by me, and that seems to me being the convenient one) for all these bracket variants should be the same as it is for the anonymous record bracket (`{|`) -- when the cursor is positioned right before the closing bracket, which, in turn, is placed on the indentation level of the current block. This behavior also could be seen in the GIF given above.

**Actual behavior**

In case of the brackets `()`, `[]`, `{}`, `[||]` the cursor (that initially is located between opening and closing ones) after entering new line moves to the zero indentation level (to the start of new line) while the closing bracket is being correctly positioned on the current block's indentation level.

**Known workarounds**

To place the cursor in the right position manually :)

**Related information**

Provide any related information (optional):

* Windows 10 Pro v2004
* Microsoft Visual Studio Community 2019 Version 16.9.3
* Visual F# Tools 16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a

**Comment by dsyme** [comment]
I'm closing this - the code is too non-idiomatic for this to be a case we should consider, and the idiomatic case works well
