### ISSUE TITLE
Units of measure not displayed in reduced form in VS Code

### ISSUE THREAD

**Issue by misterspeedy** [dotnet/fsharp#11419]
When using VS Code (in my specific case for a .NET Interactive notebook) units of measure involving divisions/multiplications are not displayed in the simplest form in type signatures. Instead lots of `MeasureProduct` and `MeasureInverse` items are displayed

**Repro steps**

1. In VS Code, install Ionide + .NET Interactive Notebooks 
2. CTRL+SHIFT+P .NET Interactive: Create new blank notebook.
3. Change cell type to F#
4. Add the following code:

   ```fsharp
    type [<Measure>]s
    type [<Measure>]m
    let distance = 5.<m>
    let time = 1.<s>
    let speed = distance/time
   ```

5.  Hover over 'speed'

Provide a description of the expected behavior.

Type signature `float<m/s>`.

Provide a description of the actual behaviour observed. 

Type signature `float<MeasureProduct<m,MeasureInverse<s>>>`

**Known workarounds**

Use Visual Studio and express as an .fsx script instead of a notebook.

**Related information**

Provide any related information (optional):

**Comment by vzarytovskii** [comment]
@jonsequitur @colombod do you know how does interactive get type info for tooltips?

**Comment by baronfel** [comment]
This should probably get moved over to the FSAC repo, as it's an ionide report. This is something I've wanted to fix for a while, just haven't gotten around to it

**Comment by cartermp** [comment]
This isn't a dotnet/fsharp issue, as the core tooltip routine we have in FCS shows this data:

![image](https://user-images.githubusercontent.com/6309070/114424486-03a7c800-9b6d-11eb-9a39-723554a90102.png)

This is an issue in both Ionide and .NET Interactive because both use the same tip formatter code.

**Comment by baronfel** [comment]
Opened https://github.com/fsharp/FsAutoComplete/issues/758 in FSAC to address this on the ionide side of things.

**Comment by brettfo** [comment]
Opened dotnet/interactive#1238 to track against .NET Interactive notebooks.

**Comment by misterspeedy** [comment]
Thanks so much everybody for getting on this so fast.
