### ISSUE TITLE
voidptr should be an unmanaged type

### ISSUE THREAD

**Issue by krauthaufen** [dotnet/fsharp#11424]
Currently F# does not treat `voidptr` as an unmanaged type. 
Therefore types like `nativeptr<voidptr>`, etc. cause compiler errors.

However on IL level this works and C# libraries (e.g. Silk.NET.OpenGL) expose methods expecting this kind of argument (which currently can't be created in F# due the above)

**Expected behavior**

`voidptr` should be treated as an unmanaged type

**Known workarounds**

Sadly I couldn't come up with a workaround. If anyone has an idea I would be glad to hear it!

**Related information**

Tested on VS2019 with .NET5 and FSharp.Core 5.0.0

**Comment by zpodlovics** [comment]
The base library pointer types (e.g.: System.Int32*) including System.Void* are not a value types. So it seems that void** functionality is not yet available (as of https://github.com/dotnet/runtime/issues/44968)

```fsharp
> System.Type.GetType("System.Int32*").IsValueType;;
val it : bool = false
```

```fsharp
> System.Type.GetType("System.Void*").IsValueType;;
val it : bool = false
```

however System.IntPtr is:

```fsharp
> System.Type.GetType("System.IntPtr").IsValueType;;
val it : bool = true
```

**Comment by krauthaufen** [comment]
In F# `nativeptr<int>` is treated as an unmanaged type and i have a C# library here exposing a `void**` so this can't be entirely true...

**Comment by zpodlovics** [comment]
nativeptr<int> is just s syntactic sugar around System.IntPtr (intptr). What is missing is the System.Void (notice there is no pointer at the end) aka the ```void``` type in F#. However the integration will be challenging due the unit type mapping / overlap (e.g.: chkSystemVoidOnlyInTypeof does not seems to be accidental as it will allow only the typeof<System.Void> usage).

```fsharp
> typeof<nativeptr<int>>.FullName;;
val it : string = "System.IntPtr"
```

```fsharp
> typeof<System.Void>.IsValueType;;    
val it : bool = true

```

**Comment by krauthaufen** [comment]
Okay then maybe just allow `nativeptr<voidptr>` (and still not allowing voidptr inside unmanaged structs/etc.) since it gets compiled to `nativeint` anyways? The Problem I'm currently facing is actually quite severe since there is a C# method I simply can't invoke from F# (expecting a `nativeptr<voidptr>`)
Any thoughts?

**Comment by zpodlovics** [comment]
You can always store an untyped pointer (nativeint) in the struct and have some helper methods / functions to map it to a proper type (worst case scenario is to call for an C# helper). What is the C# signature that you want to call (you can use simplified struct and some generic names)?

**Comment by krauthaufen** [comment]
I didn't look at the source yet but the F# type hover shows me a `nativeptr<voidptr>` which seems to be impossible to produce from F#

**Comment by krauthaufen** [comment]
I can certainly work around that using a micro C# library but nonetheless it would be great to see that fixed somewhen...
What's really ironic is, that I only want to pass a null pointer 😜

**Comment by dsyme** [comment]
This is by design for F# 6, so perhaps add a language suggestion
