### ISSUE TITLE
dotnet fsi segment fault on Ubuntu linux 21.04

### ISSUE THREAD

**Issue by wli3** [dotnet/fsharp#11427]
@netroby commented on [Mon Apr 12 2021](https://github.com/dotnet/sdk/issues/16870)

I am using gdb to run dotnet , and the log was below
```
[Inferior 1 (process 15260) exited with code 0201]
(gdb) run fsi
Starting program: /snap/dotnet-sdk/120/dotnet fsi
warning: File "/snap/core18/1997/lib/x86_64-linux-gnu/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
[New LWP 15281]
[New LWP 15282]
[Detaching after fork from child process 15283]
[New LWP 15284]
[New LWP 15285]
[New LWP 15286]
[New LWP 15287]
[New LWP 15288]
[New LWP 15289]
[New LWP 15290]
[New LWP 15291]
[New LWP 15292]
[New LWP 15293]
[New LWP 15294]
[New LWP 15295]
[New LWP 15296]
[New LWP 15297]

Thread 10 ".NET ThreadPool" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 15290]
0x00007ffff7ddfc78 in ?? () from /snap/core18/current/lib64/ld-linux-x86-64.so.2

```

I installed dotnet via snap
```
sudo snap install dotnet-sdk
```

---

@dotnet-issue-labeler[bot] commented on [Mon Apr 12 2021](https://github.com/dotnet/sdk/issues/16870#issuecomment-818483024)

I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one area label.

**Comment by vzarytovskii** [comment]
I think, it's the sdk issue, I've seen something similar in omnisharp when running build.

Following issues may be related: https://github.com/dotnet/fsharp/issues/11387

**Comment by cartermp** [comment]
Yep, this is an SDK issue.
