### ISSUE TITLE
Shading doesn't work

### ISSUE THREAD

**Issue by anthony-mi** [dotnet/fsharp#11431]
**Repro steps**

1. Extract files from the attached archive. `introspection.json`, `snowflaqe.json`, and `Queries` should be in the same folder with `snowflaqe.exe`.
2. Run snowflaqe --config ./snowflaqe.json --generate.

**Archive**

[shading_issue.zip](https://github.com/dotnet/fsharp/files/6310414/shading_issue.zip)

**Expected behavior**

At line 535 in Snowflaqe.Program.fs `files` value should be shaded.

**Actual behavior**

After execution of line 535 in Snowflaqe.Program.fs object `files` still hold previous data.

**Comment by cartermp** [comment]
I can't build this repro due to some custom config that isn't present, but my expectation would be that there is an error in this program and not an issue with shadowing. The value is shadowed - `files` refers to the definition on line 535 after line 535, which meets the definition of shadowing.

**Comment by anthony-mi** [comment]
Application launching requires only a config file that contains the path to the scheme and to the folder with gql-files. It doesn't need any more data. snowflaqe.json is the config file. introspection.json - schema. `Queries` folder contains gql-files. All these file system elements present in the archive which was attached in the first message.

**Comment by anthony-mi** [comment]
This screenshot shows the value of the `files` before the shading attempt.
![Screenshot_128](https://user-images.githubusercontent.com/65635298/114758848-19cca880-9d66-11eb-9755-7ae707d63178.png)

**Comment by anthony-mi** [comment]
As you can see, after shading, the data has not changed. Still 3 elements.
![Screenshot_127](https://user-images.githubusercontent.com/65635298/114758963-3ff24880-9d66-11eb-9ae5-16722792e2de.png)

**Comment by anthony-mi** [comment]
Here I have moved away from shading and just changed the value identifier. As you can see, here it already only stores 1 item.
![Screenshot_126](https://user-images.githubusercontent.com/65635298/114759157-7a5be580-9d66-11eb-9a79-6f7a686260e5.png)

**Comment by cartermp** [comment]
Okay, so this is a debug value display issue. In this case this would be the same issue as: https://github.com/dotnet/fsharp/issues/3704

**Comment by anthony-mi** [comment]
Really. I couldn't check this, because an exception was thrown and the application was not completed to the end. During debugging, I noticed this problem. Now the application is being finalized and the shading works correctly. So the issue is closed.
