### ISSUE TITLE
Spurious compiler error with less than symbol

### ISSUE THREAD

**Issue by glchapman** [dotnet/fsharp#11443]
The attached program throws several compiler errors when attempting to build (dotnet build -- I have dotnet 5.0.202 installed). From the error, it appears the compiler thinks it is handling a type argument when it is not.

The program will compile successfully in each of the following cases:
  1) Put a space after the 'x' in the match expression; I.e.
```
match x <4, y<4 with
| _, _ -> 0
```

  2) Remove the y from the match, I.e.
```
match x<4 with
| _ -> 0
```
  3) Change the ensuing right shift to a left shift, I.e.:
```
let shift x =
    x <<< 4
```
[temp.zip](https://github.com/dotnet/fsharp/files/6329896/temp.zip)

**Comment by KevinRansom** [comment]
temp.zip is invalid, please supply an example of the code that fails, and reopen this issue.

Thanks

Kevin
