### ISSUE TITLE
Base constructor call referencing self produces code which always fails in runtime

### ISSUE THREAD

**Issue by Szer** [dotnet/fsharp#11450]
Calling self with a global alias in base constructor call produces code which will always fail in runtime.
I think it should throw compiler error

**Repro steps**

Run this code
```fsharp
type Foo(a: int) = class end

type Bar() as self =
    inherit Foo(self.A)
    member val A = 10 with get, set

Bar() |> ignore
```

[SharpLab](https://sharplab.io/#v2:DYLgZgzgNAJiDUAfALgTwA4FMAEAxA9vgBQCGI2AlgHbICU2AvNgMbAkQTaZUwCwAUALRZsAIRIAnIvXbYImYGEYDsqylQAWmCRWR5CReYoB0AQVoq1AW0xWARtuwA3EsGynG2AIwAGbAHddDWwAc0xkKDlwgQFxKXpEAD5KEKp8CUwgA===)

**Expected behavior**

It should not compile. I referenced uninitialized fields in base constructor call

**Actual behavior**

It compiles and crash in runtime with 
```
System.InvalidOperationException: The initialization of an object or value resulted in an object or value being accessed recursively before it was fully initialized.
```

**Known workarounds**

Don't write such code!

**Related information**

Constructor contains pretty weird code with FSharpRef and lazy initialization?
```fsharp
FSharpRef<Bar> fSharpRef = new FSharpRef<Bar>(null);
base..ctor(LanguagePrimitives.IntrinsicFunctions.CheckThis(fSharpRef.contents).A);
fSharpRef.contents = this;
```

**Comment by vzarytovskii** [comment]
Here's what has been generated (roughly):
```csharp

public class Foo
{
    public Foo(int a)
    {
    }
}

public class Bar : Foo
{
    internal int a;
    internal int init;
    public int A
    {
        get
        {
            if (init < 1)
            {
                LanguagePrimitives.IntrinsicFunctions.FailInit();
            }
            return a;
        }
        set
        {
            if (init < 1)
            {
                LanguagePrimitives.IntrinsicFunctions.FailInit();
            }
            a = value;
        }
    }

    public Bar()
    {
        FSharpRef<Bar> fSharpRef = new FSharpRef<Bar>(null);
        base..ctor(LanguagePrimitives.IntrinsicFunctions.CheckThis(fSharpRef.contents).A);
        fSharpRef.contents = this;
        A = 10;
        init = 1;
    }
}

```

**Comment by vzarytovskii** [comment]
Just for the reference, call to the compiler's `CheckThis` is generated here: https://github.com/dotnet/fsharp/blob/main/src/fsharp/CheckExpressions.fs#L2626
And call to `FailInit` in the field is getting generated here https://github.com/dotnet/fsharp/blob/main/src/fsharp/CheckExpressions.fs#L10714

**Comment by smoothdeveloper** [comment]
Additional reference in a suggestion around self identifiers:

https://github.com/fsharp/fslang-suggestions/issues/501#issuecomment-536153797

I'd really like some of the self identifiers to be optimized away when they don't require stuff related to initialization soundness and other troubles related to them.

They incur extra allocation and runtime checks while in many cases, I suppose they could be elided.

**Comment by et1975** [comment]
Is there a workaround? Hit it trying to use a C# lib that does something like this:
```fsharp
type Base() as this =
    do
        this.Do()
    abstract Do: unit -> unit
    default __.Do() = printf "Base.Do"
type Derived() as this =
    inherit Base()
    override __.Do() =
        printfn "Derived.Do"
Derived()
```

**Comment by dsyme** [comment]
This is by design. You can't access the `this` pointer unsafely during initiailization. 

It would be reasonable to allow "unsafe" access. Please add a suggestion to https://github.com/fsharp/fslang-suggestions.
