### ISSUE TITLE
32-bit F# Interactive .NET Core session not possible with Visual Studio

### ISSUE THREAD

**Issue by peder86** [dotnet/fsharp#11455]
The F# Interactive session does not respect the `64-bit F# Interactive` option when using .NET Core scripting

**Repro steps**

1. Open `Tools -> Options -> F# Tools -> F# Interactive`
2. Set `Use .NET Core Scripting` to true and `64-bit F# Interactive` to false

![image](https://user-images.githubusercontent.com/3354932/115539701-91866000-a29d-11eb-81f3-d1d95827a97b.png)

**Expected behavior**

The process of the expected interactive session should be 32-bit as reported by e.g. `Task Manager` or when executing `Environment.Is64BitProcess`:
```fsharp
> Environment.Is64BitProcess;;
val it : bool = false
```

**Actual behavior**

The `fsi` process runs as 64 bit no matter the value of `64-bit F# Interactive`, `Environment.Is64BitProcess` returns true.
```fsharp
> Environment.Is64BitProcess;;
val it : bool = true
```

**Known workarounds**

A 32-bit `fsi` process can be started from the command line using the 32-bit version of `dotnet`, but this does not integrate with Visual Studio (e.g. when working with `*.fsx` files).

**Related information**

The issue might be related to #6219 but that discussion doesn't seem to address this specific issue.

* Operating system: Windows 10, version 10.0.19042
* Installed .NET Runtimes: .NET Core 5.0.2 (both 32 and 64 bit versions), .NET Framework 4.8
* Visual Studio 16.9.4

**Comment by cartermp** [comment]
This works fine for me, but you do need to reset the interactive se4ssion. FSI launches a particular executable and when you change this setting you have to reset it, since it will re-launch a different executable.

**Comment by cartermp** [comment]
Does resetting it do what you expect?

**Comment by peder86** [comment]
I had reset the session and even restarted Visual Studio, but still not 32-bit `fsi`. The issue remains when I try with the latest Visual Studio preview.

**Comment by cartermp** [comment]
Hmm. I cannot reproduce this as you've described in the latest build of 16.10 that I have (internal). So I'll tag this as needs-repro.

**Comment by peder86** [comment]
Just tried with a local build from the latest `main` branch I and get the same unexpected behavior.
I notice that in [determineFsiPath](https://github.com/dotnet/fsharp/blob/dbf9a625d3188184ecb787a536ddb85a4ea7a587/vsintegration/src/FSharp.VS.FSI/sessions.fs#L131) the value of `useAnyCpuVersion` is not checked when `fsiUseNetCore = true`. On my system the environment variable `ProgramW6432` is `C:\Program Files` no matter the bitness of the process that gets that value.
Anything I can do to investigate further on my part?

**Comment by KevinRansom** [comment]
Yes -- this is by design.

The ability to switch between 64 and 32 bit FSI only applies to the desktop version of FSI.
