### ISSUE TITLE
Attributes not included in the range of the parent node

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#11486]
Following up on previous AST related issues.
I still found some constructs where the range of the attributes is not included in the parent node.

```fsharp
[<Foo>] // SynModuleDecl.Let / SynBinding
let a = 0

[<Foo2>] // SynTypeDefn
type Bar =
    [<Foo4>] // SynMemberDefn.LetBindings / SynBinding
    let x = 8
    [<Foo2>]  // SynMemberDefn.Member / SynBinding
    member this.Something () = ()

[<Foo5>] // SynModuleDecl.NestedModule
module Nested =
    ()
```

See [AST Viewer](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQDaAPMa6wB8AXTAB6MWADKAT2QBZdgFcasACKxmNAHQAZWABdx0uQCEU0FAHMAOgCcbyVUapgAvGAAM9xz%2BS9%2BVgAmEXFJWWQAFRkAB3UEZD8DWNgwUyo7dz8ICACBABZQiRMFWABbACNYOw14ZD1Dc2RLZCs0YwimltsHZBywZzAAD3cwAA5snLzg0LCS%2BXKqmoTtBcrqjrMLa0mIMsWNgwALIm0pVn3j6zAACgBKUfu-P2mAViLwuUVoFXitbQAcugDLBoN9fn4yspVGAgWgQdAsr1%2Bk9epAQABfIA).

**Expected behaviour**

Attributes are included.

**Actual behaviour**

They are not.

**Known workarounds**

Parse the tree to construct a correct range.

**Related information**

FCS 39.

**Comment by cartermp** [comment]
Seems like a reaosnable addition
