### ISSUE TITLE
XmlDoc is allowed before `and` in type definitions

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#11489]
```fsharp
type A = class end

/// Bbb
and
    B = class end
```

<img width="374" alt="Screenshot 2021-04-27 at 17 21 18" src="https://user-images.githubusercontent.com/3923587/116257931-26e19280-a77d-11eb-9a67-1d805b4b14f0.png">

**Comment by auduchinok** [comment]
Another case with wrong range would be:

```fsharp
type A = class end

/// Bbb
and
/// 123
    B = class end
```

**Comment by cartermp** [comment]
What would you expect the result to be? I don't personally think it's an issue that you see `Bbb` when hovering over `B`

**Comment by auduchinok** [comment]
I'd not expect anything before `and` to belong to the declaration.
Maybe it's due to I'm used to quite strict C# rules for these comments.

**Comment by cartermp** [comment]
I guess it's a little hard to make a call when you write it like this:

![image](https://user-images.githubusercontent.com/6309070/116287511-5d9bb680-a745-11eb-88a6-7a5b3fc8bf15.png)

I often do that, and so it feels consistent to me. But I can understand why it's weird that you can write XML docs in both places such as your sample.

**Comment by auduchinok** [comment]
OK, how about more preceding things? 🙂 

<img width="399" alt="Screenshot 2021-04-28 at 00 06 27" src="https://user-images.githubusercontent.com/3923587/116312824-a4c19000-a7b5-11eb-8da1-6d6b8d328018.png">

C# rules would only use the last doc comment block, i.e. `/// world` here.

**Comment by cartermp** [comment]
Yeah, in that case it's a quirk to be sure. But I wouldn't agree with eliminating the one with the union case either. I'll label this an improvement.

**Comment by dsyme** [comment]
This was fixed by https://github.com/dotnet/fsharp/pull/11973
