### ISSUE TITLE
after installing VS.net  Version 16.10.0 Preview 2.1 fsharp projects stopped working

### ISSUE THREAD

**Issue by ghostinside** [dotnet/fsharp#11496]
when open solution the project is unloaded, when try to load 

d:\work\Shipping\Mappings\Mappings.fsproj : error  : The application for the project is not installed.

d:\work\Shipping\Mappings\Mappings.fsproj : error  : The imported project "c:\program files (x86)\microsoft visual studio\2019\preview\common7\ide\commonextensions\microsoft\fsharp\Microsoft.FSharp.targets" was not found. Confirm that the expression in the Import declaration "c:\program files (x86)\microsoft visual studio\2019\preview\common7\ide\commonextensions\microsoft\fsharp\Microsoft.FSharp.targets" is correct, and that the file exists on disk.  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v16.0\FSharp\Microsoft.FSharp.Targets

Mappings.fsproj

[fsproj.txt](https://github.com/dotnet/fsharp/files/6391656/fsproj.txt)

**Comment by ghostinside** [comment]
can be closed, the update brokes the system, delete & install vs fix the issue

**Comment by cartermp** [comment]
Thanks for the update!
