### ISSUE TITLE
How to correctly reference FSharp.Core ?

### ISSUE THREAD

**Issue by goswinr** [dotnet/fsharp#11527]
[nuget.org](https://www.nuget.org/packages/FSharp.Core/) suggest to use 
<PackageReference **Include**="FSharp.Core" Version="5.0.1" />
[the docs](https://github.com/dotnet/fsharp/blob/main/docs/fsharp-core-notes.md) suggest:
<PackageReference **Update**="FSharp.Core" Version="5.0.1" />
Shall I use `Update `or `Include` ? 
Did I miss some other docs?
Does `Update` mean pinning down the version?

**Comment by NinoFloris** [comment]
The dotnet sdk brings in an implicit reference to `FSharp.Core` (which nuget doesn't know about) so to affect any change you have to do Update instead of Include. Include is only respected for the first instance of a package reference.

**Comment by baronfel** [comment]
For your enjoyment, the actual reference addition can be seen [here](https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSharp.Build/Microsoft.FSharp.NetSdk.props#L83-L109).

**Comment by goswinr** [comment]
So the snippet on nuget.org should actually be changed?

**Comment by baronfel** [comment]
It would likely be infeasible to push such a change to nuget.org, as this would be one of only a very very few (perhaps the only?) such package reference to use that syntax.

**Comment by NinoFloris** [comment]
Easier would be to add something to the package description

**Comment by goswinr** [comment]
> It would likely be infeasible to push such a change to nuget.org

yes, the `Include`is hard coded: https://github.com/NuGet/NuGetGallery/blob/f248171208356b66499810ddd502276784157422/src/NuGetGallery/Views/Packages/DisplayPackage.cshtml#L101

**Comment by cartermp** [comment]
We have some guidance on the topic here: https://github.com/dotnet/fsharp/blob/main/docs/fsharp-core-notes.md#guidance-for-package-authors
