### ISSUE TITLE
signature help for function application shows wrong signature when tuples are present in function signature

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#11520]
Notice how `b` and `c` show as separate parameters:

![image](https://user-images.githubusercontent.com/87944/117007475-00c27200-acea-11eb-88f0-13a33ac48e19.png)

```fsharp
let f a (b,c) = ()

f // completing here
```

Related: #10518
Environment: VS 16.9.3

**Comment by cartermp** [comment]
This is fixed in https://github.com/dotnet/fsharp/pull/11264
