### ISSUE TITLE
Nightly FSharp.Core versions are a bit out of whack again

### ISSUE THREAD

**Issue by baronfel** [dotnet/fsharp#11549]
The versions of FCS build on May 4th and May 10th have different patch version bounds for FSharp.Core in a way that is unexpected and I think incorrect.

May 4th (FCS 40.0.0-preview.21253.4):
<img width="320" alt="image" src="https://user-images.githubusercontent.com/573979/117867170-9f585100-b25d-11eb-839d-9ae92e7be69c.png">

May 10th (FCS 40.0.0-preview.21260.2):
![image](https://user-images.githubusercontent.com/573979/117866528-dbd77d00-b25c-11eb-9256-3d64ec7a92f4.png)

Note that the more recent package has a lower version of FSharp.Core.

I think the FSharp.Core version in Versions.props has gotten out of sync.

tagging @KevinRansom because he's usually the man for these sorts of things.

**Comment by baronfel** [comment]
Over the last 24 hours two versions have populated in the feed that have the correct version number:

* 40.0.0-preview.21261.3 (May 11), depending on FSharp.Core 5.0.2-beta.21261.3, and
* 40.0.0-preview.21262.7 (May 12), depending on FSharp.Core 5.0.2-beta.21262.7

so I can only infer that this was a point-in-time error that has been addressed

**Comment by cartermp** [comment]
Most likely!

**Comment by KevinRansom** [comment]
This happens when different branches have official builds.  

main is on 5.0.1
release/dev16.10 is on 5.0.2
release/dev17.0 is  also on 5.0.2 for now, although it will be updated to 5.0.3 soon.

I sort of don't think that main should prop packages to dotnet-tools, I will chat with brett to see what we want to achieve.
