### ISSUE TITLE
Visual Studio For Mac throwing errors FS3031 and FS3005. While VSCode has no issue for the same project

### ISSUE THREAD

**Issue by SnoCold** [dotnet/fsharp#11557]
Please provide a succinct description of the issue.
I created the default FSBolero template project using dotnet CLI. Opening it in VSCode using the Ionide extension suite works ok. 

But If I open the same project in Visual Studio for Mac, I get FS3031 and FS3005 errors (Screenshot attached)

**Repro steps**

Provide the steps required to reproduce the problem:

1. dotnet new -i Bolero.Templates
2. dotnet new bolero-app -o HelloWorld
3. Open the Project in Visual Studio For Mac.
4. Get Error FS3031 and FS3005, found by hovering on top level module

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

**Expected behavior**

There should not be any such compiler error

**Actual behavior**

FS3031 and FS3005 Compiler Errors in the Project

**Related information**

Provide any related information (optional):

* Operating system `Mac OS Catalina 10.15.7`
* .NET Runtime kind (.NET 5.0 that comes by default with latest Visual Studio for Mac. However it Installs Mono)
* Editing Tools (Visual Studio Community, 8.9.9)
<img width="1452" alt="Screenshot 2021-05-12 at 10 49 30 PM" src="https://user-images.githubusercontent.com/15018167/118017498-52b36980-b374-11eb-8f37-ada3ce156101.png">

**Comment by cartermp** [comment]
This doesn't reproduce on VS Windows (build and intellisense all work), so this is likely just a VS Mac issue. I recommend using the Report a Problem tool there to file this issue.
