### ISSUE TITLE
Infinite loop in CheckOneFileImpl

### ISSUE THREAD

**Issue by TIHan** [dotnet/fsharp#11569]
In VS, at certain times I will not get any colorization until I make an edit in the editor. It turns out, `CheckOneFileImpl` is caught in an infinite loop due to us removing some of the reactor queue dependency on checking foreground files; it's a concurrency issue.

We either need to make a full-on lock when checking foreground results or come up with some sort of `AsyncLazy` construct.

**Comment by smoothdeveloper** [comment]
I think I've seen this, and restarted VS to work around (I know...), I'll try if it is just edit and it shows or just another thing altogether.

**Comment by TIHan** [comment]
This PR: https://github.com/dotnet/fsharp/pull/11573 will address this issue when it's complete.
