### ISSUE TITLE
FSharpOption<T> Implicilty casts to Some(null) instead of None

### ISSUE THREAD

**Issue by michaeloyer** [dotnet/fsharp#11565]
When implicitly assigning a null variable of `T` to an `FSharpOption<T>`, the value will be of `Some(null)` instead of `None` (which is `null`). However doing this with a `null` constant produces `None` as expected.

**Repro steps**

Run the C# code below with an FSharp Record (Attached is a zipped project with the same code, just `dotnet run ConsoleAppCS`)

```
using System;
using Newtonsoft.Json;
using JsonSerializer = System.Text.Json.JsonSerializer;
using ProgramFS.Types;
string nullMiddleName = null;

// F# Type
// type Person = {
//     First: string
//     Middle: string option
//     Last: string
// }

Console.WriteLine("--- Newtonsoft.Json ---");
Console.WriteLine(JsonConvert.SerializeObject(new Person("FirstName", nullMiddleName, "LastName")));
// {"First":"FirstName","Middle":{"Case":"Some","Fields":[null]},"Last":"LastName"}
Console.WriteLine(JsonConvert.SerializeObject(new Person("FirstName", null, "LastName")));
// {"First":"FirstName","Middle":null,"Last":"LastName"}

Console.WriteLine("--- System.Text.Json ---");
Console.WriteLine(JsonSerializer.Serialize(new Person("FirstName", nullMiddleName, "LastName")));
// {"First":"FirstName","Middle":{"Value":null},"Last":"LastName"}
Console.WriteLine(JsonSerializer.Serialize(new Person("FirstName", null, "LastName")));
// {"First":"FirstName","Middle":null,"Last":"LastName"}
```

[ConsoleAppExample.zip](https://github.com/dotnet/fsharp/files/6473574/ConsoleAppExample.zip)

**Expected behavior**

The value should be null, i.e. `{"First":"FirstName","Middle":null,"Last":"LastName"}`

**Actual behavior**

These are printed instead: 
**Newtonsoft**
{"First":"FirstName","Middle":**{"Case":"Some","Fields":[null]}**,"Last":"LastName"}
**System.Text.Json**
{"First":"FirstName","Middle":**{"Value":null}**,"Last":"LastName"}

**Known workarounds**

Provide a description of any known workarounds.

Checking for null and putting it into an FSharpOption<T> will work, but there isn't any compile time or code analysis run to warn you it's going into an F# Option, so those unfamiliar will take a hit at runtime.

Provide any related information (optional):

* .NET Runtime kind 
**.NET 5, nuget: FSharp.Core 5.0.1**

**Comment by charlesroddie** [comment]
The null representation is an implementation detail, and it's logical that (pre-NRTs) if there is an implicit operator `string -> option<string>` , it will be used on the `string` `null`.

> warn

Switch on NRTs in your C# projects. Then you will get a warning on this line:

```csharp
string nullMiddleName = null;
```

**Comment by michaeloyer** [comment]
Thanks! Nullable Reference Types would help with the example I provided. Where we actually bumped into the problem was with one of our C# models in an ASP.NET Core POST method. I tried it out on an ASP.NET core controller method and sadly don't see any warnings.

```
#nullable enable
using Lib;
using Microsoft.AspNetCore.Mvc;

namespace Web
{
    [ApiController]
    [Route("[controller]/[action]")]
    public class TestController : ControllerBase
    {
        [HttpPost]
        public IActionResult Do([FromBody] PostModel postModel)
        {
            // F# Core model type:
            // type CoreModel = {
            //     Name: string option
            // }
            var model = new CoreModel(postModel.Name);
            // model.Name = Some(null)
            
            return Ok();
        }
    }

    public class PostModel
    {
        public string? Name { get; set; }
    }
}
```

**Comment by charlesroddie** [comment]
Unfortunately there is no F# support for NRTs yet. So F# libraries are treated as ["null-oblivious"](https://devblogs.microsoft.com/dotnet/embracing-nullable-reference-types/#what-happens-when-you-call-libraries-that-have-not-enabled-the-feature).

NRT support is in https://github.com/dotnet/fsharp/pull/6804 but that PR has been open a long time.

**Comment by auduchinok** [comment]
I've also just got hit by this quite hard in a place that used to work just fine before.

**Comment by dsyme** [comment]
There may seems to have been some kind of change here, which is disturbing, possible due to a C# compiler change, or some interaction with nullable reference types.

**Comment by cartermp** [comment]
Tagging as a regression for now, we'll see what the actual deal is when investigated

**Comment by dsyme** [comment]
I don't think this is a regression, it is by design.

* If you want a `None`, you have to use a `null` of type `FSharpOption<string>`

* If you want a `Some(null)`, you have to use a `null` of type `string` which will apply the `op_Implicit` conversion from `string` to `FSharpOption<string>`

* If you want a `Some(s)`, you can provide either a `string` (which will apply the `op_Implicit` conversion from `string` to `FSharpOption<string>`) or an `FSharpOption<string>`

Thus because of the wonders of `op_Implicit` the `null` literal at a method call will have a different effect to a `null` value of type `string`.

The C# interop with FSharpOption is really imperfect but this is how it is, and as I understand it is is by design without regression.

**Comment by auduchinok** [comment]
> I don't think this is a regression, it is by design.

Hasn't it worked differently previously, though? We have never encountered the NREs that I had to workaround recently and there was no changes to the code around that could introduce these NREs.

**Comment by dsyme** [comment]
> Hasn't it worked differently previously, though? We have never encountered the NREs that I had to workaround recently and there was no changes to the code around that could introduce these NREs.

I'm not sure how it could of changed for the example in the repro.  If you start with 

    string nullMiddleName = null;

then from a C# overload resolution perspective that's still going to be a `string` and thus the `op_Implicit: string -> FSharpOption<string>`  will kick in, and will always have done that.  Likewise an explicit untyped `null` will be taken as an `FSharpOption<string>` value meaning `None`.

If you think there's a sample where it's changed please outline what you remember of that case?

**Comment by auduchinok** [comment]
> If you think there's a sample where it's changed please outline what you remember of that case?

Sure. Our repro was a bit different, and here's the the change I had to make: https://github.com/JetBrains/resharper-fsharp/commit/dfbc35e5ea70633268242b7789ee3b8ba85af5a2.

**Comment by dsyme** [comment]
@auduchinok Hmmm, again I don't understand how that would have worked before, the change simply looks correct in any previous circumstance.  It could actually be that the code _consuming_ the invalid `Some(null)` somehow changed to detect the null (and previously it was treating it as `None`)

**Comment by michaeloyer** [comment]
I kind of feared that end up being the case. At least I've now learned what op_Implicit does. I'm going to go out on a pretty naive limb and ask if there would be any possibility of any of these in Future F# versions?:

* Changing the Implementation to `Option.ofObj`
* Remove op_Implicit
* Mark as Obsolete

Or perhaps I'm best off figuring out if I could make an analyzer to highlight it so it can hopefully get changed when someone is writing in the C# layer.

Thanks for looking into it!

**Comment by auduchinok** [comment]
> Hmmm, again I don't understand how that would have worked before

@dsyme Previously it was somehow converted to `None` instead of `Some(null)`. Maybe the change is actually related to changes of types in `ParseResults` and `ParseTree`, and not to C# compiler changes.

**Comment by dsyme** [comment]
@michaeloyer Please add an fslang-suggestion to mark `op_Implicit: T -> T option` as obsolete?  However I suspect it is used a lot, we'd need what to recommend instead.  There's no easy choice.

I would indeed like to change the implementation of `op_Implicit` to test for `null` but it would be a breaking change unfortunately, I don't think it's possible for compat reasons.

**Comment by psfinaki** [comment]
Since next F# might have more breaking changes anyway, can we revise this decision here as well? This has recently been raised [here](https://stackoverflow.com/q/75288473/3232646).

**Comment by vzarytovskii** [comment]
> Since next F# might have more breaking changes anyway, can we revise this decision here as well? This has recently been raised [here](https://stackoverflow.com/q/75288473/3232646). @vzarytovskii Vlad Zarytovskii FTE

No, this will be a huge silent breaking change. Most new "breaking changes" are either new diagnostics, which are sound, or an implementation detail change which is considered a fix.
