### ISSUE TITLE
debugging TcGlobals is hard in VS (evaluating local variables...)

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#11568]
Some of you may be familiar with this dialog:

![image](https://user-images.githubusercontent.com/87944/118207194-fb1b0980-b418-11eb-8c9b-f9aa81bea7d8.png)

Some of you may be familiar with having a breakpoint in [TcGlobals.fs](https://github.com/dotnet/fsharp/blob/ac3681029cad369b592d6770f02ba1427b80cfce/src/fsharp/TcGlobals.fs#L179-L1645) and the above.

I have a suggestion, on the hypothesis that the number of fields at same level is what is hurting F# contributors that have to put a breakpoint at initialisation of a variable and of using Visual Studio as debugger 

* we could break [TcGlobals.fs](https://github.com/dotnet/fsharp/blob/ac3681029cad369b592d6770f02ba1427b80cfce/src/fsharp/TcGlobals.fs#L179-L1645) into several pieces, that are individually, less than the sum of it
* once we've split the [God object](https://en.wikipedia.org/wiki/God_object), one day, we will submit an issue to VS Feedback, and let them know we'd like a progress counter for the dialog that prompted this issue, to help with large god objects in `*.designer.cs` files (have to make it sound more important than "F# compiler debugging is, sometimes, very slow due to it and just the counter is enough, there are 500+ variables there")
* it may be worth to profile what takes long to evaluate and render in the debugger, maybe the F# code can be optimised

[🎉] If you encounter this issue at day work when debugging [TcGlobals.fs](https://github.com/dotnet/fsharp/blob/ac3681029cad369b592d6770f02ba1427b80cfce/src/fsharp/TcGlobals.fs#L179-L1645) 
[👍] If you encounter this dialog when debugging with devenv.exe, without having to put a breakpoint in [TcGlobals.fs](https://github.com/dotnet/fsharp/blob/ac3681029cad369b592d6770f02ba1427b80cfce/src/fsharp/TcGlobals.fs#L179-L1645) to be an expert at staring at it thinking it will just take 2 seconds
[🚀] If you encounter this issue not at day work when debugging [TcGlobals.fs](https://github.com/dotnet/fsharp/blob/ac3681029cad369b592d6770f02ba1427b80cfce/src/fsharp/TcGlobals.fs#L179-L1645)
[😄] you don't want C# compiler devs know prominent F# developers fall into the trap of putting more fields into a [God object](https://en.wikipedia.org/wiki/God_object) than can be indexed with a single byte (they anyway know, they read telemetry reports, and when they see Microsoft.FSharp in them, from machine on same Active Directory, it is a colleague debugging [TcGlobals.fs](https://github.com/dotnet/fsharp/blob/ac3681029cad369b592d6770f02ba1427b80cfce/src/fsharp/TcGlobals.fs#L179-L1645) if the elapsed time is more than few minutes)
[👀] If you are Kevin Ransom and would rather "just use notepad.exe and windbg.exe"
[❤️] If you are Don Syme, and despite running own endo-CLR with no need to debug, you'd like contributors to fsc.exe that rely on Visual Studio to not see this dialog for too long but would rather say "F# compiler code is fine, Microsoft will improve Visual Studio, we may not need to break [TcGlobals.fs](https://github.com/dotnet/fsharp/blob/ac3681029cad369b592d6770f02ba1427b80cfce/src/fsharp/TcGlobals.fs#L179-L1645) into children objects if they'd do so"

**Comment by cartermp** [comment]
Perhaps splitting it up could be reasonable, but that would likely be a rather invasive code change as well. I don't really know if there's much to be done here, since it's squarely a VS debugger slowdown and not really anything we're doing on our side other than having a lot of locals to evaluate for a given scope.

**Comment by dsyme** [comment]
I'd say this is due to formatting a lot of properties that return things that take a long time to format.

We could either

1. reduce time taken to format things like TType and TyconRef

2. replace some of the many properties on TcGlobals with methods.
