### ISSUE TITLE
Unable to parse char literal '\0' as a char

### ISSUE THREAD

**Issue by baronfel** [dotnet/fsharp#11570]
The following code fails to compile with a pretty verbose set of errors:

```fsharp
let c = '\0'
```

**Repro steps**

**Expected behavior**

The user can easily write the `\0` char literal

**Actual behavior**

You get three different errors:

* `FS0010:  Unexpected quote symbol in binding` on the first `'` character range
* `FS1156: This is not a valid numeric literal` on the `0'` character range
* `1FS0010:  Incomplete structured construct at or before this point in interaction` on the `0'` character range

**Known workarounds**

The following forms work and compile to the `\0` char as expected:

```fsharp
let c' = '\000' // works, compiles to '\0'
let c'' = '\x00' // works, compiles to '\0'
```

**Additional Info***

@mdl thought it might be the escape_chars in the lexer: https://github.com/dotnet/fsharp/blob/main/src/fsharp/lex.fsl#L310

**Comment by dsyme** [comment]
This is by design - the workarounds listed are the correct way to do this
