### ISSUE TITLE
System.Type.GetType() returns null for F# string list

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#11571]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SystemTypeGetType-returns-null-for-F/1380849)._

---
let x = ["string"]

let myTypeMeta = x.GetType(). FullName

// FSI returns Microsoft.FSharp.Collections.FSharpList`1[System.String]
// net5.0 returns Microsoft.FSharp.Collections.FSharpList`1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
// (note double bracket and additional metadata)

System.Type.GetType(myTypeMeta) 
// returns null in both FSI and net5.0

let y = [|" string"|]

System.Type.GetType(y.GetType(). FullName)
// string array does work

---
#### Feedback Bot on 3/24/2021, 11:22 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Phillip Carter [MSFT] on 4/1/2021, 02:52 PM: 

<p>Hello,</p>
<p>This has been the behavior for F# lists for quite some time (at least since F# 4.5, but likely far before then - don’t have an older compiler around just yet). This is because F# lists are unions under the covers, and reflection with F# union types typically requires using the <code>FSharp.Reflection</code> namespace. For example, you can call <code>FSharpType.GetUnionCases(x.GetType())</code> and it will yield an array of two elements, <code>Empty</code> and <code>Cons</code>.</p>
<p>Is this something you’ve observed not to be true in the past?</p>

#### Jack Fox on 4/3/2021, 09:19 AM: 

<p>I caught this when upgrading 6 year old production F# to net5.0.<br>
Before upgrading this program required Visual F# Tools 4.0 RTM to run. So yeah, this worked before F# 4.5.</p>
<p>I have a crappy work around in place, so this is not a show stopper.</p>
<p>The point I want to make is System.Type.GetType() inverses x.GetType().FullName for x in all System and some FSharp.Core types. I see now Map has a similar problem. It would make sense for this to work on all the core types.</p>

---
### Original Solutions
(no solutions)

**Comment by cartermp** [comment]
This is reported to be a regression, but I can't say how severe at this time.

**Comment by BillHally** [comment]
Using `AssemblyQualifiedName` instead of `FullName` works. For example:

```fsharp
let x = ["string"]
let myTypeMeta = x.GetType().AssemblyQualifiedName
System.Type.GetType(myTypeMeta)
```

outputs the following in the .NET 5.0.203 version of `fsi`:

```
val x : string list = ["string"]
val myTypeMeta : string =
  "Microsoft.FSharp.Collections.FSharpList`1[[System.String, Sys"+[168 chars]
val it : System.Type =
  Microsoft.FSharp.Collections.FSharpList`1[System.String]
```

**Comment by cartermp** [comment]
Confirmed this is not just an FSI thing, it reproduces in a console app.

**Comment by dsyme** [comment]
This is not anything we can fix - this is related to changes to `System.Type.GetType` in .NET Framework and .NET Core - we would expect the user to need to use `AssemblyQualifiedName`
