### ISSUE TITLE
Why the module seems to "warm up" at the beginning ?

### ISSUE THREAD

**Issue by RickyYChan** [dotnet/fsharp#11576]
I'm tring to make a simple wrapper  like this:
```fs
open Microsoft.Xna.Framework
module Matrix =     
    type mat = 
        struct
            ...
            static member inline toMgMat (this:float32 [,]) = 
                Matrix(
                    this.[0, 0], this.[0, 1], this.[0, 2], this.[0, 3],
                    this.[1, 0], this.[1, 1], this.[1, 2], this.[1, 3],
                    this.[2, 0], this.[2, 1], this.[2, 2], this.[2, 3],
                    this.[3, 0], this.[3, 1], this.[3, 2], this.[3, 3]
                    )    
            ...
        end
```
when testing the performacne, i found it too slow.
test code 1:
```fs
open type Matrix.mat
open System.Diagnostics
open Microsoft.Xna.Framework
let x = 
    [
        [1; 2; 3; 4]
        [2; 3; 4; 0]
        [1; 2; 5; 0]
        [1; 5; 0; 1]
    ] |> mat |> float32
let sw = Stopwatch()
// test 0
sw.Start()
x |> toMgMat |> ignore
sw.Stop()
printfn $"No 0: {sw.Elapsed.TotalMilliseconds} -- transform matrix x to monogame matrix4 use function in my module."
sw.Reset()

// test1 
x.[0, 0] <- 1f
x.[3, 3] <- 2f
sw.Start()
x |> toMgMat |> ignore
sw.Stop()
printfn $"No 1: {sw.Elapsed.TotalMilliseconds} -- transform matrix x to monogame matrix4 again."
sw.Reset()

// test2
sw.Start()
Matrix(
    x.[0, 0], x.[0, 1], x.[0, 2], x.[0, 3],
    x.[1, 0], x.[1, 1], x.[1, 2], x.[1, 3],
    x.[2, 0], x.[2, 1], x.[2, 2], x.[2, 3],
    x.[3, 0], x.[3, 1], x.[3, 2], x.[3, 3]
    ) |> ignore
sw.Stop()
printfn $"No 2: {sw.Elapsed.TotalMilliseconds} -- construct the monogame matrix4 outside the module."
sw.Reset()
```
```
No 0: 0.4622 -- transform matrix x to monogame matrix4 use function in my module.
No 1: 0.0005 -- transform matrix x to monogame matrix4 again.
No 2: 0.0008 -- construct the monogame matrix4 outside the module.
```

first, i thought the problem will accur on the stopwatch class, so i add a slice of code like this:
```fs
// test -2
sw.Start()
sw.Stop()
printfn $"No -2: {sw.Elapsed.TotalMilliseconds} -- just start the stopwatch."
sw.Reset()
```
```
No -2: 0.0048 -- just start the stopwatch.
No 0: 0.4619 -- transform matrix x to monogame matrix4 use function in my module.
No 1: 0.0004 -- transform matrix x to monogame matrix4 again.
No 2: 0.0004 -- construct the monogame matrix4 outside the module.
```

And nothing helps.
Then i'm trying to test the function which is the same to the function inside the module, and found it will be faster.
So i'm trying to "warm up" the module:
```fs
// test -1
sw.Start()
x |> trans |> ignore
sw.Stop()
printfn $"No -1: {sw.Elapsed.TotalMilliseconds} -- transpose the matrix to \"warm up\" my module."
sw.Reset()
```
```
No -2: 0.0026 -- just start the stopwatch.
No -1: 0.3358 -- transpose the matrix to "warm up" my module.
No 0: 0.1226 -- transform matrix x to monogame matrix4 use function in my module.
No 1: 0.0003 -- transform matrix x to monogame matrix4 again.
No 2: 0.0006 -- construct the monogame matrix4 outside the module.
```

and the program is faster now after "warming up".
So what is the problem actually?

**Comment by kerams** [comment]
All .NET code is compiled at runtime from IL to machine code by the JIT. What you're seeing is not only the execution time of the function, but also the time it takes for the JIT to compile the function the first time it is called.

https://docs.microsoft.com/en-us/dotnet/standard/managed-execution-process#compilation-by-the-jit-compiler
https://www.geeksforgeeks.org/what-is-just-in-time-jit-compiler-in-dot-net/

**Comment by RickyYChan** [comment]
> All .NET code is compiled at runtime from IL to machine code by the JIT. What you're seeing is not only the execution time of the function, but also the time it takes for the JIT to compile the function (that's the "warmup" here) the first time it is called.
> 
> https://docs.microsoft.com/en-us/dotnet/standard/managed-execution-process#compilation-by-the-jit-compiler
> https://www.geeksforgeeks.org/what-is-just-in-time-jit-compiler-in-dot-net/
> 
> A robust benchmarking framework like https://github.com/dotnet/BenchmarkDotNet will automatically account for things like this.

Thanks for your answer! So .Net 6 with aot will change the situation?

**Comment by cartermp** [comment]
Maybe. Not clear. But this is a JIT thing, not anything inherent to F#. You can avoid warmup costs in a running app in lots of different ways, depending on your use case.

**Comment by kerams** [comment]
I suppose it might, but it won't happen magically by updating to .NET 6. There are tradeoffs when enabling it, such as trading the portability of your application since you need to compile the executables for specific platforms (you need to provide this information) separately.

**Comment by RickyYChan** [comment]
> I suppose it might, but it won't happen magically by updating to .NET 6. There are tradeoffs when enabling it, such as trading the portability of your application since you need to compile the executables for specific platforms (you need to provide this information) separately.

Thank you!

**Comment by RickyYChan** [comment]
> Maybe. Not clear. But this is a JIT thing, not anything inherent to F#. You can avoid warmup costs in a running app in lots of different ways, depending on your use case.

Thank you!

**Comment by RickyYChan** [comment]
I think the problem is clearly so i close the issue. :) 
Thanks all the guys and have a good time! :)
