### ISSUE TITLE
Type-inference broken on prefix operators

### ISSUE THREAD

**Issue by adam-nathan** [dotnet/fsharp#11585]
Following up on the SO [question](https://stackoverflow.com/questions/67500947/can-someone-explain-these-f-type-inference-oddities), it would appear there is a bug.

```
type Foo<'T>(v:'T) =
    member __.Value = v // 'T
    static member (~~) (foo:Foo<_>) = foo.Value // Foo<'a> -> 'a
```

The ~~ prefix operator can infer the correct type, however when calling on a Foo argument it fails to give the correct type:

`let value (u:Foo<_>) = ~~u                      // Foo<obj> -> obj`

Interestingly, this also fails:

```
let inline (~~) (x:^a) : ^b = 
    (^a : (static member (~~) : ^a -> ^b) x)    // ^a -> ^b
let value (u:Foo<_>) = ~~u                      // Foo<obj> -> obj
```
In contrast, using a non-generic return type works:

```
let inline (~~) (x:^a) : 'b = 
    (^a : (static member (~~) : ^a -> 'b) x)    // ^a -> 'b
let value (u:Foo<_>) = ~~u        
```    

I'm assuming this is a bug.

**Comment by dsyme** [comment]
IIRC when you use a completely anonymous operator as in your first example, e.g

    ~~a

or

    a ++++ b

then the types of a, b and the overall return type get marked as "must be statically known". So this is per-specficiation, even if a little pessimistic

For the second case I'm pretty sure you need to annotate the third line as follows:

```
type Foo<'T>(v:'T) =
    member __.Value = v // 'T
    static member (~~) (foo:Foo<'T>) : 'T = foo.Value // Foo<'T> -> 'T

let inline (~~) (x:^a) : ^b = 
    (^a : (static member (~~) : ^a -> ^b) x)    // ^a -> ^b
let value (u:Foo<_>) = ~~u                      // Foo<T> -> T
```

**Comment by dsyme** [comment]
So this is per specification, please open a fslang-suggestion for the first part if you wish
