### ISSUE TITLE
Array.average vs Seq.average when input is empty.

### ISSUE THREAD

**Issue by MNie** [dotnet/fsharp#11599]
I'm not sure if this is really a bug or maybe it is by design but:

```fsharp
let emptyArray: float [] = [||]
Array.average emptyArray
```

returns an [error](https://try.fsharp.org/#?code=LYewJgrgNgpgBAFRBATgOgGIQHYGMAuAliNgM4CwAUFaJLHAEoy6qmEBuMWeRJpcAXipU4ouPhQBPEWNmx8cAIYoAXHABmUEIoUBtALqC4ugD4n9M2aIAOKQtnzrscAESkQwGPgAW9gOZqAKQAgi5wABTBKCiKkmiKnDF+8MoAlJZwAO6EPnDwALQAfBmytvaOzi4ARlCKNYpBoXnC1JRAA&html=DwCwLgtgNgfAsAKAAQqaApgQwCb2ag4CdMTJcMABwFp0BHAVwEsA3AXgCIBhAewDsw6AdQAqAT0roOSAMb9BAzoIAeYAPThoAbhkhMAJwDOJNgzAAzagA4OeQhqy5EhAEY9sYu6mBq3HvD6asEA&css=Q), [while](https://try.fsharp.org/#?code=LYewJgrgNgpgBAFRBATgOgGIQHYGMAuAliNgM4CwAUFaJLHAEoy6qmEBuMWeRJpcAXipU4ouPhQBPEWNmx8cAIYoAXHABmUEIoWkYAR0FwA2gB9TAXTimAfHACCKFIslp8IAMoGZs0QAcUQmx8dWw4ACJSEGAYfAALIIBzNQBSe3C4AAovfTRFTmdE+GUASh84AHdCeLh4AFobctkAoJCw8IAjKEUuxVT02uFqSiA&html=DwCwLgtgNgfAsAKAAQqaApgQwCb2ag4CdMTJcMABwFp0BHAVwEsA3AXgCIBhAewDsw6AdQAqAT0roOSAMb9BAzoIAeYAPThoAbhkhMAJwDOJNgzAAzagA4OeQhqy5EhAEY9sYu6mBq3HvD6asEA&css=Q):

```fsharp
let emptyArray: float seq = [||] |> Array.toSeq
Seq.average emptyArray
```

Works okay.

Provide the steps required to reproduce the problem:

**Expected behavior**

I assume [Seq.average](https://github.com/dotnet/fsharp/blob/dbf9a625d3188184ecb787a536ddb85a4ea7a587/src/fsharp/FSharp.Core/seq.fs#L1185) and [Array.average](https://github.com/dotnet/fsharp/blob/dbf9a625d3188184ecb787a536ddb85a4ea7a587/src/fsharp/FSharp.Core/array.fs#L1152) should work the same way (don't throw an exception when array/seq is empty or we throw it when seq or array is empty).

**Actual behavior**

Array.average -> throw Exception when array is empty,
Seq.average -> don't throw Exception when seq is empty.

**Known workarounds**

```fsharp
if emptyArray = [||] then 0.
else Array.average emptyArray
```

instead of:

```fsharp
Array.average emptyArray
```

**Related information**

Provide any related information (optional):

* Operating system: Windows 10/MacOS Catalina
* .NET Runtime kind: .NET Core 3.1
* Editing Tools: JetBrains Rider 2020, VS Code.

**Comment by kerams** [comment]
TryFSharp appears to be running on Fable, so the issue belongs there. Both functions throw in fsi.

**Comment by MNie** [comment]
@kerams Thanks, I will create an issue there : )
