### ISSUE TITLE
Constructing a record with `yield` keyword

### ISSUE THREAD

**Issue by Alkasai** [dotnet/fsharp#11616]
Currently to update a field or number of fields you can construct a record by form another record and modifying just the fields that you need:
``` fsharp
{ foo with
    X = fooX
    Y = fooY
    Z = fooZ }
```

However, if you need to update fields only if a condition is satisfied it becomes a bit verbose:
``` fsharp
{ foo with
    X = fooX
    Y = if blah then fooY else foo.Y
    Z = if blah then fooZ else foo.Z }
```

It would be nice to be able to use a `yield` keyword in this case:
``` fsharp
{ foo with
    X = fooX
    if blah then
        yield (Y = fooY)
        yield (Z = fooZ) }
```
OR
``` fsharp
{ foo with
    X = fooX
    if blahY then
        yield (Y = fooY)
    if blahZ then
        yield (Z = fooZ) }
```

**Comment by ly29** [comment]
This sounds like language suggestion, they go to this repository https://github.com/fsharp/fslang-suggestions

**Comment by Alkasai** [comment]
> This sounds like language suggestion, they go to this repository https://github.com/fsharp/fslang-suggestions

Thank you!
Moved it here https://github.com/fsharp/fslang-suggestions/issues/1016
