### ISSUE TITLE
Type inference can't infer type of member in recursive types

### ISSUE THREAD

**Issue by Szer** [dotnet/fsharp#11629]
This code throws compilation error
`error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.`

```fsharp
type A(b: B) =
  let _ = b.X.Length // error here on b.X.Length
and B() =
  member _.X = ""
```

[AST](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQAuAngA6wwAQQAUAI2wAhAJRgAvAB0ATguQQasLmAD68sGIB0ADQMAZWMgDmXABbLVVZNDCSRsxSrVgAtrG9jYJR1jPQVIMPtkSBAAXyA)

However, if you'll put concrete type instead of inferred one in B, everything will be ok

```fsharp
type A(b: B) =
  let _ = b.X.Length
and B() =
  member _.X: string = "" // manual typing
```
[AST](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQAuAngA6wwAQQAUAI2wAhAJRgAvAB0ATguQQasLmAD68sGIB0ADQMAZWMgDmXABbLVVZNDCSRsxSrVgAtrG9jYJR1jbDQuJRRLPQVIGPtkSBAAXyA)

[AST diff](https://www.diffchecker.com/yVbK2zdH)
[SharpLab](https://sharplab.io/#v2:DYLgZgzgPgLgngBwKYAICCAKARiFAhAShQF4BYAKBRWCRhQH0SUsA6ADRYBkkA7AcxgALCgEMeAE3wYiZSigC2SeViQAnBuyYAiLRSp6UFeMhQBhDONwARGQZp1GxFOPZdeA4eTGSr0kgcVlNQ02XAgYVQBLfm0tIA==)

Not sure if it is a bug in the first place or easily fixable.
AST clearly lacks `SynBindingReturnInfo`, but for me as a user **this is confusing**

**Comment by cartermp** [comment]
Not entirely sure if this is considered by design, since there are several related ways to triggers this kind of behavior where tooling has more info than a compiler pass, leading to a weird case where the tools could technically make this work, but the compiler poops out. It tends to usually happen when members are involved like this.

I assigned myself to see if the recently-added code fixer can be used to add the type annotation.

**Comment by cartermp** [comment]
Okay, took a look at the code fixer and it definitely doesn't help 🙃 

I would say that I think this _should_ compile as-is since the member is unambiguous in the sample.

**Comment by dsyme** [comment]
This is by design.  X doesn't have a known type without analyzing its implementation.  And that comes later in the inference.
