### ISSUE TITLE
Consuming C# records in F# doesn't work as expected.

### ISSUE THREAD

**Issue by stevenbrix** [dotnet/fsharp#11676]
Consuming C# records in F# doesn't work as expected.

C#:
```csharp
public record Foo(String A, String B)
{
   public string C {get; init; } = A + B;
}
```

F#:
```fsharp
let bar = Foo("a", "b")
let baz = { bar with C = "z" }
```

this produces FS0039: `The record label 'C' is not defined`

You can successfully (and incorrectly) compile this:

```fsharp
let bar = Foo("a", "b")
bar.C <- "z"
```

but this leads to a runtime exception:  `Common Language Runtime detected an invalid program.`

**Comment by stevenbrix** [comment]
this also seems like it should work, but doesn't:

```fsharp
type FooF(A, B) =
    inherit Foo(A, B)
    do
      base.C <- "z"
```
it results in the same runtime exception, which is weird, you'd think that init properties would be settable from the constructor. 
the equivalent record in C# works just fine:

```csharp
public record FooF : Foo
{
   public FooF(string A, string B) : base(A, B)
   {
       C = "z";
   }
}

**Comment by cartermp** [comment]
This is tracked across two suggestions here:

https://github.com/fsharp/fslang-suggestions/issues/904
https://github.com/fsharp/fslang-suggestions/issues/683
