### ISSUE TITLE
Unreliable VS 16.10.1 Rename

### ISSUE THREAD

**Issue by BentTranberg** [dotnet/fsharp#11675]
I wanted to create a minimal repro about a bug in Rename in Visual Studio. That I can't do, because there's another bug when I try to create that minimal repro. So I'm just going to explain the two bugs.

### First problem

This is the first problem, that I'm having when I try to rename properties in my large solution. The source initially looks like this.

`    member bunt.antallBiter with get () = List.length bunt.Biter`

And when I try to do a rename, it becomes this.

`    member bunt.AntallBiter with AntallBiter () = List.length bunt.Biter`

This pattern happens consistently, in my large solution.

### Second problem

I start with this

![image](https://user-images.githubusercontent.com/15068882/121685274-04eb6780-cac0-11eb-8418-bc55bdb2d2ed.png)

Then I place the cursor at member getMyString, and try to do a rename with Ctrl-R+R. This is what shows. (edit: I did compile before the rename attempt.)

![image](https://user-images.githubusercontent.com/15068882/121685460-3ebc6e00-cac0-11eb-9a2c-8cd253bc1120.png)

(edit: Line 1 was blank also in the first snippet.)

If I press Esc, everything reverts, and is fine. If I do go on typing to try to rename, it just quits rename mode, and starts ordinary editing in my original source, which was not corrupted after all.

VS 16.10.1  and  .NET 5.0.301

I know that there are other older reports about (VS?) Rename problems. It's just that I found it interesting that there seemed to be a simple and consistent behavior in that first. The second is possibly a VS only issue, and maybe recently introduced. In any case I hope both are easily reproed, though for me the second shadows the first.

**Comment by dsyme** [comment]
This did not repro for me typing in the code shown above and renaming.  

It might e that it repros in a larger solution. In any case will close now
