### ISSUE TITLE
Two problems with recent tuple elimination

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#11689]
Recent tuple elimination improvements have two problems

1. More heap allocations are happening because some locals are labelled mutable
2. Good user-facing variable names are being replaced by `patternInput1` names etc.

See https://github.com/dotnet/fsharp/pull/11407#issuecomment-863157932

First is fixed by #11687.  The second is fixed by https://github.com/dotnet/fsharp/pull/11690

**Comment by cartermp** [comment]
Closing :)
