### ISSUE TITLE
Adding F# source file to library in VS -> file has open statements for Android development.

### ISSUE THREAD

**Issue by BentTranberg** [dotnet/fsharp#11680]
When adding a new F# source file to an F# library, this is what the file looks like initially.

![image](https://user-images.githubusercontent.com/15068882/122036736-30c66000-cdd4-11eb-83de-18668e2d8a0f.png)

I've never done any Android development on this machine. How can this suddenly happen?

The machine was recently reinstalled completely from scratch, and no mobile development has been done on this machine or in this solution. No experimentation has been going on that can explain this. The only explanation I can find, is that some recent update to VS may have caused this.

Did somebody perhaps recently add a new source file type to Android development, and happen to choose the same name as the "plain file", causing this to happen? Just a thought.

The Add New Item dialog in VS looks like this.

![image](https://user-images.githubusercontent.com/15068882/122037597-02955000-cdd5-11eb-8fd6-b58dd168aa37.png)

There are two identical items for F# source file. The details pane for both of them just says "A blank F# source file (.fs)". I have not noticed two items for adding an F# source file earlier.

When clicking on Android, one of these items is visible in the list - in fact it's the only item in the list. So apparently the top item that I chose happened to add a new file for Android development, and possibly the second item adds a plain file as I'm used to.

VS 16.10.1

**Comment by cartermp** [comment]
Yes, this is likely due to installing Xamarin tooling for VS.

We do not own that item template in this repo. I recommend filing an issue with the VS Report a Problem tool and emphasize that this is a Xamarin issue (so that it doesn't go right back to us).

**Comment by charlesroddie** [comment]
Yes this is very annoying so great if you can repost in Xamarin.Android @BentTranberg .

**Comment by shawn-martin** [comment]
I went through the VS Report a Problem tool as Phillip suggested.
