### ISSUE TITLE
nameof(..  ..) outputs "op_RangeStep" but not ".. .."

### ISSUE THREAD

**Issue by Happypig375** [dotnet/fsharp#11697]
nameof(..  ..) outputs "op_RangeStep" but not ".. .."

**Repro steps**

```
Microsoft (R) F# Interactive version 11.4.2.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> nameof( .. .. );;
val it : string = ".. .."

> nameof( ..  .. );;
val it : string = "op_RangeStep"

> nameof( ..   .. );;
val it : string = "op_RangeStep"
```

**Expected behavior**

```
> nameof( .. .. );;
val it : string = ".. .."
```

**Actual behavior**

```
> nameof( ..  .. );;
val it : string = "op_RangeStep"
```

**Known workarounds**

```
> nameof( .. .. );;
val it : string = ".. .."
```

**Related information**

Provide any related information (optional)::

* Operating system: Windows 10
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .NET Framework FSI
* Editing Tools (e.g. Visual Studio Version, Visual Studio): VS16.10.2

**Comment by vzarytovskii** [comment]
After a short discussion with @dsyme, we'll probably gonna be more strict and produce a warning if there are more than one space in the middle of operator. I'll have the PR ready.
