### ISSUE TITLE
nameof(*) outputs "op_Multiply" but not "*"

### ISSUE THREAD

**Issue by Happypig375** [dotnet/fsharp#11696]
nameof(\*) outputs "op_Multiply" but not "*"

**Repro steps**

```
Microsoft (R) F# Interactive version 11.4.2.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> nameof(*);;
val it : string = "op_Multiply"

> nameof( *);;
val it : string = "*"

> nameof( * );;
val it : string = "*"
```

**Expected behavior**

```
> nameof(*);;
val it : string = "*"
```

**Actual behavior**

```
> nameof(*);;
val it : string = "op_Multiply"
```

**Known workarounds**

```
> nameof( * );;
val it : string = "*"
```

**Related information**

Provide any related information (optional)::

* Operating system: Windows 10
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .NET Framework FSI
* Editing Tools (e.g. Visual Studio Version, Visual Studio): VS16.10.2

**Comment by dsyme** [comment]
Sigh. Good catch.

**Comment by vzarytovskii** [comment]
(*) is a special case in parser, and we capture `(` and `)` in range, and don't properly demangle op name.
We'll need to compensate position (start and end column) when we parse it and then create ident.
Gonna prepare the PR.
