### ISSUE TITLE
VS2019 visualized file order is different with the order defined in the project file

### ISSUE THREAD

**Issue by albertwoo** [dotnet/fsharp#11700]
![image](https://user-images.githubusercontent.com/8017681/122696637-1f6ad100-d276-11eb-8ba5-88486fb82c05.png)

**Repro steps**
https://github.com/slaveOftime/Fun.Blazor

**Expected behavior**

Visualized file orders in vs should be the same as in the project file

**Actual behavior**

Mess

**Known workarounds**

Rename to avoid some strange confliction

**Comment by dsyme** [comment]
I think this bug should be moved to https://github.com/dotnet/project-system

**Comment by vzarytovskii** [comment]
Actually, I cannot reproduce it in dev17 on https://github.com/slaveOftime/Fun.Blazor/tree/fa24ef3cc2d883eac6f967705ebf15c2299927b8:
![image](https://user-images.githubusercontent.com/1260985/122787654-d5a1db00-d2b5-11eb-9b60-e0e714346ac4.png)

**Comment by albertwoo** [comment]
Strange. I tried vs2019 and vs2022. And tried on two machines. The issue still exist.

Anyway I will move this issue to project-system.
