### ISSUE TITLE
UWP and .NET native compiler crash

### ISSUE THREAD

**Issue by xperiandri** [dotnet/fsharp#11742]
Some time ago there was an issue about inability to compile F# with .NET native
https://github.com/dotnet/corert/issues/6055#issuecomment-421050834

> The .NET Native compiler will emit a couple warnings about unsupported LDTOKEN instructions to stdout (there's several places in FSharp.Core.dll where the IL is doing LDTOKEN of an uninstantiated generic method, such as in static System.Void <StartupCode$FSharp-Core>.$Query..cctor() - this is not currently supported by the native code generator backend we use. Then the compiler will crash with an internal error.

> We can likely fix this easily in a future FSharp.Core (e.g. change to emit ldtoken of an instantiated generic method and then call GetGenericMethodDefinition() )

Was it fixed?
As .NET native compiler still crashes.

**Repro steps**

1. Clone https://github.com/xperiandri/Elmish.Uno/tree/template_fixes
2. Switch to branch `template_fixes`
3. Open `SolutionTemplate.sln`
4. Switch to `Release`
5. Enable .NET native toolchain in UWP project properties
6. Build

**Expected behavior**

Builds successfully

**Actual behavior**

Compiler crashes

**Related information**

* .NET Core SDK 5.0
* FSharp.Core 5.0.1
* Visual Studio 2019 16.10
* .NET native 2.2.9

**Comment by Happypig375** [comment]
https://github.com/fsharp/fslang-suggestions/issues/919#issuecomment-855800637
> These are bugs in the .NET native systems - TBH I'm not a fan of buggy and incomplete implementations of things calling themselves .NET that are not .NET, and feeel it's a bit of a waste of time trying to chase them down. That said, it makes sense to make the codegen independent of printf for performance reasons alone. :)

**Comment by charlesroddie** [comment]
@xperiandri so far the only reproduction of a .net netnative compiler crash is when compiling x86 (as discussed in the linked thread). I can see references to x86 in your project file. I don't know much about builds but perhaps removing these references would work. If you can confirm that the crash happens outside x86, or want to discuss x86 support, then best to comment in that thread.

**Comment by dsyme** [comment]
This doesn't appear to be a bug in this repo, and the general topic is covered at https://github.com/fsharp/fslang-suggestions/issues/919#issuecomment-855800637
