### ISSUE TITLE
Disable some tests on Dev17.0 branch

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#11752]
These tests are failing on release/dev17.0 with with VS 16.10.3
Something changed we don't know what.

- Failed Regression.NoError.Timestamps.Bug3368b
-  Regression.ModulesFromExternalLibrariesBug5785

We need to understand why, and ensure these tests execute.

**Comment by dsyme** [comment]
I think @TIHan put in a fix for these

**Comment by TIHan** [comment]
That fix doesn't resolve those tests. However, in main, we disabled both tests. I'm not convinced the tests are reliable and do the right; meaning the tests failing may not represent a symptom.
