### ISSUE TITLE
[dev17] Semantic coloring doesn't work in latest dev17.0 preview

### ISSUE THREAD

**Issue by brettfo** [dotnet/fsharp#11776]
The identifier `EntryPoint` should be teal and function identifiers (e.g., `from`, `sprintf`, etc.) should be light yellow.

![image](https://user-images.githubusercontent.com/926281/124316540-f9291900-db32-11eb-8c23-84138105a9ce.png)

**Comment by KevinRansom** [comment]
@brettfo , do you still see this?
