### ISSUE TITLE
Implicit conversion to .NET delegates broken on spliced quotations

### ISSUE THREAD

**Issue by blaulaub** [dotnet/fsharp#11780]
**Repro steps**

In F# REPL, compare the direct quotation
```
<@ System.Func<int,int>( fun x -> x+1 ) @>
```
to the spliced quotation
```
<@ fun x -> x+1 @> |> fun e -> <@ System.Func<int,int>( %e ) @>
```

**Expected behavior**

Both should produce a .NET delegate (`Expr.NewDelegate`).

**Actual behavior**

The spliced quotation produces a lambda (`Expr.Lambda`)

**Known workarounds**

My current workaround is _not_ to use splicing but to do it programmatically:
```
<@ fun x -> x+1 @>
|> function
| Patterns.Lambda(v, body) -> Expr.NewDelegate(typeof<System.Func<int,int>>, [v], body)
| _ as other -> failwith (sprintf "unsupported case %A" other)
|> fun e -> Expr.Cast<System.Func<int, int>>(e)
```

**Related information**

* first raised on StackOverflow https://stackoverflow.com/questions/68228386/why-does-direct-code-quotation-of-system-func-yield-a-delegate-and-spliced-quota
* Windows 10, .NET Core 5

**Comment by dsyme** [comment]
We will treat this as by design. 

The second produces
```fsharp
> <@ fun x -> x+1 @> |> fun e -> <@ System.Func<int,int>( %e ) @>
- ;;
val it: Quotations.Expr<System.Func<int,int>> =
  NewDelegate (Func`2, delegateArg0,
             Application (Lambda (x, Call (None, op_Addition, [x, Value (1)])),
                          delegateArg0))
```

Splicing isn't an entirely syntactic process - it is done with respect to elaborated forms.  In particular `System.Func<int,int>(f)` is elaborated to `System.Func<int,int>(fun x -> f x)`.
