### ISSUE TITLE
Address-of doesn't work when taking an immutable value for inref

### ISSUE THREAD

**Issue by Happypig375** [dotnet/fsharp#11794]
Address-of doesn't work when taking an immutable value for inref

**Repro steps**

```fs
let f (x: inref<int>) = ()
let a = 1
f (&a)
```
```
error FS3230: A value defined in a module must be mutable in order to take its address, e.g. 'let mutable x = ...'
```

**Expected behavior**

Works.

**Actual behavior**

Errors.

**Known workarounds**

Making it mutable.

**Related information**

Provide any related information (optional):

* Operating system: Windows
* .NET Runtime kind (.NET Core, .NET Framework, Mono): SharpLab
* Editing Tools (e.g. Visual Studio Version, Visual Studio): SharpLab

**Comment by dsyme** [comment]
This is by design for a thing defined in a module (note "A value defined in a module...") .  F# just doesn't guarantee that there will be a backing field for `a` whose address can be taken.  Instead you can use a local, for example:

```fsharp
let f (x: inref<int>) = ()
let g() =
    let a = 1
    f (&a)
```
or a static in a class
```fsharp
let f (x: inref<int>) = ()
type C() = 
    static let a = 1
    static member Run() = f (&a)
```
