### ISSUE TITLE
July 2021 rough issue worklist

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#11801]
And we're back with another month-ish of work. Here it is:
- [x] @vzarytovskii - #11532

- [x] @vzarytovskii - #11803 

- [ ] @TIHan - #11802

- [x] @kevinransom - #11800

- [ ] @kevinransom - #11804
       

Note: 16.11 is a servicing-only release for us. We will not include any fixes unless they are high priority/regressions. All other feature work and bugs will be targeted for .NET 6/dev17.

**Comment by charlesroddie** [comment]
No reference assemblies @TIHan ?

**Comment by baronfel** [comment]
I'd expect that to be targeted for .NET 6 based on the fact that it's a new feature, not a high priority bugfix or regression.

**Comment by KevinRansom** [comment]
@charlesroddie not at this time.

**Comment by nojaf** [comment]
Any chance any of this will produce a new stable FCS package?
40 did not quite hit the mark for me. ([Regression](https://github.com/dotnet/fsharp/issues/11732), that one [last range bug](https://github.com/dotnet/fsharp/issues/11734) I forgot).

**Comment by charlesroddie** [comment]
> @charlesroddie not at this time.

That's a shame because it was in the last two months' worklists and the feature would be the most impactful development for us in F# for the last few years, since it would reduce average compilation times by a factor of 2-3.

**Comment by KevinRansom** [comment]
@nojaf - I think we can release a 40.0.1 what bugs do you need fixed and in the release?

**Comment by KevinRansom** [comment]
@charlesroddie priorities change all of the time.  The feature may well come back, before long.

**Comment by nojaf** [comment]
@KevinRansom if possible I'd like #11732 and #11734 to be in there.
One small caveat: this involves three PRs: #11736, #11733 and #11795.
#11781 would also be nice to have but is less blocking.

**Comment by vzarytovskii** [comment]
Yeah, we had a bunch of fixes in since the last release, I guess it makes sense to release a new one. WDYT @KevinRansom?

**Comment by nojaf** [comment]
Any update on a potential new FCS release @vzarytovskii @KevinRansom?

**Comment by dsyme** [comment]
Closing out since August plan is up
