### ISSUE TITLE
Update the use of optional parameters in the FCS public API so that optional arguments are exposed as C#-compatible default arguments

### ISSUE THREAD

**Issue by baronfel** [dotnet/fsharp#11817]
**Is your feature request related to a problem? Please describe.**

As a reference, see [this twitter thread](https://twitter.com/bradwilson/status/1413687831394877442) with Brad Wilson of xunit.

Non-F# consumers of FCS are forced to supply every optional parameter to common entry points like FSharpChecker.Create ([example](https://github.com/xunit/xunit/blob/main/src/xunit.v3.runner.utility.tests/Compilation/FSharpAcceptanceTestAssembly.cs#L36-L46)), whereas in F# we do not ([example](https://github.com/dotnet/fsharp/blob/a940bd53c3114ef03a13619454635adb6b67a8aa/src/fsharp/service/service.fs#L1013)).

**Describe the solution you'd like**

 To play nice in the ecosystem we should expose these optional parameters per the mechanisms described in the F# documentation for [interop with non-F# languages](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/parameters-and-arguments#optional-parameters). This would prevent C# (and presumably VB) consumers (like xunit, nunit, sharplab, etc) from being forced to reference types like LegacyReferenceResolver that are obsolete directly, which causes warnings in their build processes.

This _might_ be a binary-breaking change, but from an implementation perspective the default values for these parameters would be `null` (as it is today), and since `'t option` has `null` as the representation for `None` this may not even be a big deal.

**Describe alternatives you've considered**

* We could not do this work, and non-F# consumers would continue to have to specify every parameter on these callsites.
* We could provide overloads of Create (and possibly other common entrypoints) that don't have this explicit reference to the obsolete LegacyReferenceResolver type, so that non-F# consumers have a path towards using the library without touching obsolete code.

**Comment by baronfel** [comment]
This might be more difficult than I was thinking, due to some interactions between option-typed member parameters and the DefaultParameterAttribute:

* Adding Optional and DefaultParameterAttributes to a member makes F#-usages that lack those parameters error (eg the static let checker linked above)
* It's impossible to add a `DefaultParameterAttribute(null: int option)` for example, because while `null` is a valid value of the None case of an option, trying this yields `error FS0043: The type 'int option' does not have 'null' as a proper value` and friends.

**Comment by dsyme** [comment]
I'm going to close this, as the FCS API isn't particularly designed for use from C#
