### ISSUE TITLE
file type .fsx should be associate with fsi.exe on windows.

### ISSUE THREAD

**Issue by cnmade** [dotnet/fsharp#11829]
For linux user ,who want to run FSharp script ,they can using Shebang, like

```
#!/usr/bin/env -S dotnet fsi
printfn "Hello FSharper"
```

But for windows, it is more hard.

If the fsi.exe can handle each .fsx type. When user double click file , it will execute the script. 

Current we do many script on windows with python. Double click .py file, will execute it with python.exe

If fsi support direct run .fsx file, we can replace our script with FSharp. No more python needed. That's awesome

**Comment by dsyme** [comment]
The problem is there is no global installer for F# except the .NET SDK, and I know given their design goals they won't want to register file associations. Their aim is always to be able to have multiple installs of the .NET SDK, potentially in different locations. It's true that the version shim `dotnet.exe` is on the path, but I just am certain that global file associations will not be an option.

**Comment by Happypig375** [comment]
@dsyme Do you think that `dotnet fsi` can have a command line option to execute https://stackoverflow.com/a/2697804 and register itself?

**Comment by dsyme** [comment]
> @dsyme Do you think that dotnet fsi can have a command line option to execute https://stackoverflow.com/a/2697804 and register itself?

It could in theory but I don't think we'd expect to go down that path - e.g. scripts breaking on .NET SDK version updates (with removal of previous versions).

If there's some precedent in the .NET universe for this then that would be good to know, e.g. registrations of `dotnet tool` command line tools.  I'd rather see one global solution working for any .NET command line tool in a consistent way.

**Comment by cnmade** [comment]
I love FSharp, It is really good language  and tools. I like it very much .But as you said ,It really depends on dotnet. 
So the problem  seems ugly. What can we say , Fuck Microsoft?

**Comment by vzarytovskii** [comment]
@cnmade Please, keep it civil.

**Comment by cnmade** [comment]
@vzarytovskii thanks, i re edit my comment.

**Comment by Happypig375** [comment]
>It could in theory but I don't think we'd expect to go down that path - e.g. scripts breaking on .NET SDK version updates (with removal of previous versions).

The current workaround of `#!/usr/bin/env -S dotnet fsi` doesn't pin the version either. Given .NET's promise of minimal breaking changes, I'd say it is okay to allow this.

**Comment by dsyme** [comment]
FWIW I'm was a bit shocked by that reply.... Yes let's please keep this discussion technical.

Firstly, I do not want F# to result in the same mess as Python, where double-clicking an a Python script runs a more-or-less what seems to me to be a random version of Python that almost certainly cooperates badly with other versions lying around.  

> The current workaround of #!/usr/bin/env -S dotnet fsi doesn't pin the version either. Given .NET's promise of minimal breaking changes, I'd say it is okay to allow this.

This is different, for three crucial reasons

1. It is finding `dotnet` via the path,. Once you have `dotnet`, it is actually possible to specify the desired .NET SDK version for an F# script through a global.json.

2. It is on Linux, which is very often run in buttoned-down containers, indeed may have just installed the .NET SDK desired.

3. It requires no global install to set up the association - it's right there in the script.

On Windows, however, things are just not so simple on any of these points

1. A double-click file association is genuinely global

2. Windows systems are less likely to be in a tight container

3. Installing global file associations on Windows is really troublesome, as it needs a global install via a **securely-signed** MSI produced by someone with the right certificate.  That means a reliable ultra long-term delivery channel **whose owners are willing to sign up to installing these and making sure, once installed, they will always work**.  

That is, neither the F# community nor even the Visual F# team at Microsoft produce a signed MSI of the kind you're after to set up this association.   The .NET team do, in the form of the .NET SDK.  Hence it's right to ask them what they think of this in general.  

Finally, users can always set up the association themselves.  If someone could paste the instructions into this thread that would be great.

**Comment by dsyme** [comment]
As part of the history, we used to install an file association for Windows back in the day when F# was not part of the .NET SDK and had its own MSI for .NET Framework scripting.  I'm really glad to no longer be doing this, and simply delivering F# out via more standard routes instead

I am however perfectly fine with 
1. giving people clear instructions about how to set up the association
2. asking the .NET SDK delivery team (and @KevinRansom) what they think about having such an association for .NET Core scripting

**Comment by MiloDC** [comment]
So... is anyone going to type up those clear instructions for setting up the association?

**Comment by dsyme** [comment]
@MiloDC There's a guide here: https://stackoverflow.com/questions/27003963/how-to-get-f-scripts-files-and-other-script-languages-to-work-like-exe-cmd
