### ISSUE TITLE
Obsolete attribute is ignored in constructor property assignment

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/fsharp#11868]
Given code like
```fs
    System.Text.Json.JsonSerializerOptions(
                    JsonSerializerDefaults.Web,
                    IgnoreNullValues = true)
```

`IgnoreNullValues` is obsolete but does not trigger a warning.

Writing `System.Text.Json.JsonSerializerOptions().IgnoreNullValues` does properly warn.

**Comment by brianrourkeboll** [comment]
I wonder if there is something wonky with settable constructor parameters. I noticed recently that I could set a settable constructor parameter... when I wasn't even in a constructor.

Note that this script compiles (!) and runs (!!) in .NET 5.0.302:

```fsharp
#r "nuget: Microsoft.Data.SqlClient"

open System
open System.Data
open Microsoft.Data.SqlClient

let f connectionString =
    use connection = new SqlConnection (connectionString)
    connection.Open ()
    use command = new SqlCommand ("select @Param", connection, CommandType=CommandType.Text)
    ignore <| command.Parameters.Add ("@Param", SqlDbType.DateTimeOffset, Value=3)
    command.ExecuteScalar () :?> int // Returns 3.
```

This also compiles and runs:

```fsharp
ignore <| command.Parameters.Add ("@Param", SqlDbType.DateTimeOffset, Value=DateTimeOffset.Now)
command.ExecuteScalar () :?> DateTimeOffset // Returns the current date and time.
```

If I do

```fsharp
ignore <| command.Parameters.Add ("@Param", SqlDbType.DateTimeOffset, Value=DateTimeOffset.Now, Direction=ParameterDirection.Output)
command.ExecuteScalar () :?> DateTimeOffset // Throws "System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.DateTimeOffset'."
```

, I get a runtime exception, etc.

Nowhere [among the overloads of `SqlParameterCollection.Add`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlparametercollection.add?view=sqlclient-dotnet-standard-3.0) is there one taking `Value` (with a capital V), or `Direction`, or any of a variety of other settable properties of `SqlParameter`, all of which indeed seem to be somehow settable just by calling `SqlParameterCollection.Add`.

In this case, it seems as though the compiler is somehow augmenting the overload `Add(string, SqlDbType)` with the constructor of `SqlParameter`, a type that has its own overload `Add(SqlParameter)`. Or, given that

```fsharp
command.Parameters.Add ("@Param", SqlDbType.DateTimeOffset, Value=3)
```

behaves identically to

```fsharp
command.Parameters.Add (SqlParameter ("@Param", SqlDbType.DateTimeOffset, Value=3))
```

, it seems like the first overload (taking `SqlParameter`) is somehow being used, with the actual constructor name `SqlParameter` elided.

Note however that the editor tooling (Visual Studio 16.10.4) tells me that I am using the overload `Add(string, SqlDbType)`:

![image](https://user-images.githubusercontent.com/14795984/126582445-6aee4e90-e152-4182-ba1a-672330999c60.png)

and that the `Value` parameter pertains to the `System.Data.Common.DbParameter` type:

![image](https://user-images.githubusercontent.com/14795984/126582419-26177608-ec4d-40d0-9c8d-c707021c9640.png)

I wasn't able to reproduce it with my own types in a few minutes of experimenting, but it struck me as quite odd that the above should compile and run the way it does...

Unless there is something obvious going on here that I am missing?

**Comment by edgarfgp** [comment]
@NinoFloris I have been looking at some of the Obsolete attributes bugs and I was looking into this one .

- I have added some test in [Obsolete Attribues Tests](https://github.com/dotnet/fsharp/blob/main/tests/FSharp.Compiler.ComponentTests/Language/ObsoleteAttributeCheckingTests.fs)
- I think F# reports error / warnings when you access properties/ fields (except records that is not consistent ATM)
- Checked with C# and it does not raise errors/warning on constructor property assignment 

I think this more like a Feature request rather that a BUG.  

Please correct if Im wrong. Happy to find a solution for this :)

**Comment by NinoFloris** [comment]
In the first example IgnoreNullValues is a property that is being set in the constructor. As such it should warn similarly, it's just a missed case. As the normal property setter does warn.

@dsyme would likely be best able to tell us whether this would be a feature request.

**Comment by vzarytovskii** [comment]
> In the first example IgnoreNullValues is a property that is being set in the constructor. As such it should warn similarly, it's just a missed case. As the normal property setter does warn.
> 
> @dsyme would likely be best able to tell us whether this would be a feature request.

This would be a bugfix, however I'm not sure if it should go under a language flag. We hid init-only properties check under F# 7, though it was a fix (but it produces an error instead of warning).
This should probably be treated as the rest of obsolete fixes - like a bugfix.

**Comment by edgarfgp** [comment]
@vzarytovskii will create a Draft with the bug fix 😀

**Comment by vzarytovskii** [comment]
> @vzarytovskii will create a Draft with the bug fix 😀

Great, thanks, could you also please check if it is ignored in case of normal methods setting properties, i.e.:
```fsharp
instance.Method(ObsoleteProperty=123)
```
In this case, probably should also be checked, the check probably belongs somewhere here:
https://github.com/dotnet/fsharp/blob/30b3a8fa53bf48da2b79492cddd98b4d219336a3/src/Compiler/Checking/CheckExpressions.fs#L9785-L9786
as well as calling `set_PropName` explicitly (in case if we don't produce warning), we can either check the method's property somewhere here (like it's done for init-only):
https://github.com/dotnet/fsharp/blob/30b3a8fa53bf48da2b79492cddd98b4d219336a3/src/Compiler/Checking/CheckExpressions.fs#L8936-L8937

Or, when we codegen the Obsolete property, also set Obsolete attribute on its get_* and set_* methods
