### ISSUE TITLE
Update F# Tooling, Language and F# Core version numbers

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#11877]
**The next major release of F# will be Dev 17.0**

- Language F# Language Version will be 6.0
- FSharp.Core.dll version will be 6.0.0.0
- FSharp.Core nuget package will be 6.0.0

**Language version 6.0 will be added and will have enabled:**

- LanguageFeature.OverloadsForCustomOperations, languageVersion60
- LanguageFeature.ExpandedMeasurables, languageVersion60
- LanguageFeature.ResumableStateMachines, languageVersion60
- LanguageFeature.StructActivePattern, languageVersion60
- LanguageFeature.PrintfBinaryFormat, languageVersion60
- LanguageFeature.UseBindingValueDiscard, languageVersion60
- LanguageFeature.NonVariablePatternsToRightOfAsPatterns, languageVersion60
- LanguageFeature.AttributesToRightOfModuleKeyword, languageVersion60

**And also this active PR**
- [Additional type directed conversions](https://github.com/dotnet/fsharp/pull/10884)

**And possibly these active PRs**
- [type resolved arr[idx]](https://github.com/dotnet/fsharp/pull/11749)
- [RFC FS-1108 - Undentation frenzy](https://github.com/dotnet/fsharp/pull/11772)

**Comment by Happypig375** [comment]
Ayy, will we have F# 7 for .NET 7 too?

**Comment by En3Tho** [comment]
[OverloadsForCustomOperations] (https://github.com/fsharp/fslang-design/blob/main/preview/FS-1056-allow-custom-operation-overloads.md)
[ExpandedMeasurables] (https://github.com/fsharp/fslang-design/blob/main/preview/FS-1091-Extend-Units-of-Measure.md)
[ResumableStateMachines]  (https://github.com/fsharp/fslang-design/blob/main/preview/FS-1087-resumable-code.md)
[StructActivePattern] (https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1039-struct-representation-for-active-patterns.md)
[PrintfBinaryFormat] (https://github.com/fsharp/fslang-design/blob/main/preview/FS-1100-Printf-binary.md)
[UseBindingValueDiscard] (https://github.com/fsharp/fslang-design/blob/main/preview/FS-1102-discards-on-use-bindings.md)
[NonVariablePatternsToRightOfAsPatterns] (https://github.com/fsharp/fslang-design/blob/main/preview/FS-1105-Non-variable-patterns-to-the-right-of-as-patterns.md)
[AttributesToRightOfModuleKeyword] (https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1107-Allow-attributes-after-the-module-keyword.md)

**Comment by dsyme** [comment]
> Ayy, will we have F# 7 for .NET 7 too?

🤣 🤣 🤣 🤣  One thing at a time :)

**Comment by DalekBaldwin** [comment]
Since FSharp.Core will now target both netstandard2.0 and netstandard2.1, it may help to have some guidance on new best practices for linking and building projects against it.

**Comment by dsyme** [comment]
> Since FSharp.Core will now target both netstandard2.0 and netstandard2.1, it may help to have some guidance on new best practices for linking and building projects against it.

All this is handled automatically.  If you are making a `netstandard2.0` library, or a `net472` library, then `netstandard2.0` facade is used.  If making a `netstandard2.1` or `net5.0` thing then `netstandard2.1` is used.

I'm not sure any specific guidance is needed, just as we don't give any specific guidance for other .NET components

**Comment by dsyme** [comment]
All done 👍
