### ISSUE TITLE
should be able to apply Array operations like map, fold, etc directly to IList<'a> collections

### ISSUE THREAD

**Issue by sanikolov** [dotnet/fsharp#11876]
**Is your feature request related to a problem? Please describe.**

Kind of. It's a performance issue.

**Describe the solution you'd like**

suppose we have a `SortedList<'a,'b> slist`. Currently I write:
```
slist.Values |> Seq.map func |> Array.ofSeq
```
I should be able to write this faster alternative instead
```
slist.Values |> Array.map func
```

**Describe alternatives you've considered**

Since performance is important I've considered going imperative and cloaking the implementation by a functional interface.
Also referred to as `benign effects` by some.

**Additional context**

None

**Comment by cartermp** [comment]
I think that this should go here instead: https://github.com/fsharp/fslang-suggestions/

That being said, I think it's fairly unlikely to be supported, since arrays don't implement the generic `IList` interface.

**Comment by dsyme** [comment]
Just write a library with an `IList.map` etc. ?

**Comment by auduchinok** [comment]
> Just write a library with an IList.map etc. ?

@dsyme I, too, sometimes think it would be so much easier to interop with external code if there was such a module in FSharp.Core.

**Comment by dsyme** [comment]
> @dsyme I, too, sometimes think it would be so much easier to interop with external code if there was such a module in FSharp.Core.

To be honest its use is rare enough that I believe it should be in a separate community library

**Comment by dsyme** [comment]
Closing as this should be either a community library or added to fslang-suggestions
