### ISSUE TITLE
Odd method overload/settable constructor parameter interaction (?)

### ISSUE THREAD

**Issue by brianrourkeboll** [dotnet/fsharp#11871]
I noticed recently that I could (seemingly) set a settable constructor parameter... when I wasn't even in a constructor.

Note that this script compiles (!) and runs (!!) in .NET 5.0.302:

```fsharp
#r "nuget: Microsoft.Data.SqlClient"

open System
open System.Data
open Microsoft.Data.SqlClient

let f connectionString =
    use connection = new SqlConnection (connectionString)
    connection.Open ()
    use command = new SqlCommand ("select @Param", connection, CommandType=CommandType.Text)
    ignore <| command.Parameters.Add ("@Param", SqlDbType.DateTimeOffset, Value=3)
    command.ExecuteScalar () :?> int // Returns 3.
```

This also compiles and runs:

```fsharp
ignore <| command.Parameters.Add ("@Param", SqlDbType.DateTimeOffset, Value=DateTimeOffset.Now)
command.ExecuteScalar () :?> DateTimeOffset // Returns the current date and time.
```

If I do

```fsharp
ignore <| command.Parameters.Add ("@Param", SqlDbType.DateTimeOffset, Value=DateTimeOffset.Now, Direction=ParameterDirection.Output)
command.ExecuteScalar () :?> DateTimeOffset // Throws "System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.DateTimeOffset'."
```

, I get a runtime exception, etc.

Nowhere [among the overloads of `SqlParameterCollection.Add`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlparametercollection.add?view=sqlclient-dotnet-standard-3.0) is there one taking `Value` (with a capital V), or `Direction`, or any of a variety of other settable properties of `SqlParameter`, all of which indeed seem to be somehow settable just by calling `SqlParameterCollection.Add`.

In this case, it behaves as though the compiler is somehow augmenting the overload `Add(string, SqlDbType)` with the constructor of `SqlParameter`, a type that has its own overload `Add(SqlParameter)`. Or, given that

```fsharp
command.Parameters.Add ("@Param", SqlDbType.DateTimeOffset, Value=3)
```

behaves identically to

```fsharp
command.Parameters.Add (SqlParameter ("@Param", SqlDbType.DateTimeOffset, Value=3))
```

, it seems like the first overload (taking `SqlParameter`) is somehow being used, with the actual constructor name `SqlParameter` elided.

Note however that the editor tooling (Visual Studio 16.10.4) tells me that I am using the overload `Add(string, SqlDbType)`:

![image](https://user-images.githubusercontent.com/14795984/126582445-6aee4e90-e152-4182-ba1a-672330999c60.png)

and that the `Value` parameter pertains to the `System.Data.Common.DbParameter` type:

![image](https://user-images.githubusercontent.com/14795984/126582419-26177608-ec4d-40d0-9c8d-c707021c9640.png)

I wasn't able to reproduce it with my own types in a few minutes of experimenting (which does give me some pause), but it struck me as quite odd that the above should compile and run the way it does...

Unless there is something obvious going on here that I am missing?

**Comment by dsyme** [comment]
> I noticed recently that I could (seemingly) set a settable constructor parameter... when I wasn't even in a constructor.

This is by-design, settable properties can be set using syntax like

**Comment by brianrourkeboll** [comment]
I did not know that! And yes, with that understanding it is indeed easily reproducible:

```fsharp
type T () =
    member val X = 0 with get, set
    member _.M () = T ()

let t = T().M(X=4)
```

I'll close this issue.

**Comment by baronfel** [comment]
This is a bit of a mind-bender. I had no idea this syntax was possible either.

**Comment by brianrourkeboll** [comment]
> I had no idea this syntax was possible either.

Yeah, I don't think I'd seen it documented anywhere, though sure enough it's in the spec (§8.13.4, §14.4).
