### ISSUE TITLE
Improve the default console app template

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#11883]
I would like us to consider changing the current console template to

```fsharp
// For more information: [link to learning material and explanation of console app main]
printfn "Hello from F#"
```
The .NET 6 C# template is:
```csharp
// For more information: [link to explanation of why things changed]

Console.WriteLine("Hello World!");
```

The link should include 

* guidance on how to access command line arguments.
* guidance on writing an explicit entry point
* There is a technical issue with the way F# compiles the entry point for top-level definitions for .EXE which affects unit testing and requires the use of a main if you unit-test functions in the Program.fs, this needs explanation

**Comment by dsyme** [comment]
VS template is here vsintegration\ProjectTemplates\ConsoleProject\Template

@KevinRansom Could you link to the code for the F# templates in the .NET SDK please?

**Comment by cartermp** [comment]
Code lives here: https://github.com/dotnet/templating/tree/main/template_feed/Microsoft.DotNet.Common.ProjectTemplates.6.0/content/ConsoleApplication-FSharp

It's the same templates that will flow into VS.

The current ones were set up to demonstrate calling a function, since there were some user studies that showed a big thing for people without F# experience did _not_ expect that the function had to come before its caller (mix of go, java, python folks).

**Comment by dsyme** [comment]
> The current ones were set up to demonstrate calling a function, since there were some user studies that showed a big thing for people without F# experience did not expect that the function had to come before its caller (mix of go, java, python folks).

OK thanks.  We can also solve this with a better error message when people use function before its definition.

**Comment by cartermp** [comment]
Yeah, the better error message would be awesome.

**Comment by dsyme** [comment]
https://github.com/dotnet/templating/pull/3536

I will follow up with better error message and we also need to author content for the aka.ms link

**Comment by dsyme** [comment]
Are the VS templates in our tree still installed by our tooling, given the existence of the .NET SDK templates in VS menus these days?

**Comment by cartermp** [comment]
These VS templates are still installed, yes, but only for targeting .NET Framework via the .NET SDK. We don't have any more templates that use the old style project format

**Comment by cartermp** [comment]
"we" heh

**Comment by dsyme** [comment]
Done
