### ISSUE TITLE
Named arguments for functions

### ISSUE THREAD

**Issue by the-not-mad-psychologist** [dotnet/fsharp#11897]
Partial function application has greatly increased my productivity, but I must frequently use lambdas or homebrew functions to rearrange arguments for built-in functions in special cases--for example, when I want to use `List.map`, but happen to have the list handy before the mapping function. What if I could partially apply any argument I wanted, regardless of order? I think this feature would allow modern programmers, by avoiding even more unnecessary code, to write yet more ingenious programs.

(I know that member functions have this feature, but if I wanted to wrap all my functions in classes I would be using Java.)

**Comment by cartermp** [comment]
This is a language feature request, tracked here: https://github.com/fsharp/fslang-suggestions/issues/151

Just for future reference, language and core library feature requests are not tracked in this repository. Some exceptions are related to the delivery/packaging of those features (e.g., feedback about the `LangVersion` switch or the packaging for FSharp.Core).
