### ISSUE TITLE
IDE0005 is not fixed solution-wise in F# in 17p2.1

### ISSUE THREAD

**Issue by TIHan** [dotnet/fsharp#11892]
Reported by @WhiteBlackGoose

Version Used: 17p2.1

Steps to Reproduce:

Create an empty F# console app:
```fsharp
open System

printfn $"Hello world {5}"
```
Go to System, Ctrl+. and remove it document-wise, project-wise or solution-wise. All of those will do nothing (although it will remove the current open if you press enter).

**Comment by psfinaki** [comment]
Duplicate of #14967 (or rather the other way round) and was fixed by @T-Gro recently. Works in VS preview as of now. Closing.
