### ISSUE TITLE
Inconsistencies among forward piping, backward piping, and direction invocation of method in group

### ISSUE THREAD

**Issue by TysonMN** [dotnet/fsharp#11918]
When a method is overloaded, it is possible to call a particular overload by forward piping in its arguments.  However, it is not possible to call the same method overload using a backwards pipe.  If calling without a pipe operator, then it possible when passing in a just-constructed tuple.  However, it is not possible when passing in a reference to a tuple.

**Repro steps**

```fsharp
let pair = (1, 2)
type Foo() =
  static member add(a: int, b: int) = a + b

(1, 2) |> Foo.add |> ignore // compiles
Foo.add (1, 2) |> ignore    // compiles
Foo.add <| (1, 2) |> ignore // compiles

pair |> Foo.add |> ignore   // compiles
Foo.add pair |> ignore      // compiles
Foo.add <| pair |> ignore   // compiles

type Bar() =
  static member add(a: int, b: int) = a + b
  static member add(a: int, b: int, c: int) = a + b + c

(1, 2) |> Bar.add |> ignore // compiles
Bar.add (1, 2) |> ignore    // compiles
Bar.add <| (1, 2) |> ignore // Error FS0505 The member or object constructor 'add' does not take 1 argument(s). An overload was found taking 2 arguments.

pair |> Bar.add |> ignore   // compiles
Bar.add pair |> ignore      // Error FS0505 The member or object constructor 'add' does not take 1 argument(s). An overload was found taking 2 arguments.
Bar.add <| pair |> ignore   // Error FS0505 The member or object constructor 'add' does not take 1 argument(s). An overload was found taking 2 arguments.
```
**Expected behavior**

In each group of three lines, I expected them to either all compile or for none of them to compile.  Baring that, in each group of three lines, I expected the two lines that use a pipe operator to either both compile or for neither of them to compile.

**Actual behavior**

The actual behavior is given above in the comments and deviates from my expectation.  I thought the behavior would be more consistent.

**Related information**

* Windows operating system
  - Edition: Windows 10 Enterprise
  - Version: 10.0.18363
  - Build 18363
* SDK: .NET 5.0.302
* Visual Studio
  - Edition: Enterprise 2019
  - Version: 16.10.4

**Comment by dsyme** [comment]
This is going to be by design I'm sure - the flow of type information matters and will affect the resolution since overload resolution is type-directed based on partial type information. So there's no expectation that `x |> f` is symmetric with `f <| x` 

Specifically this case
```
Bar.add pair |> ignore      // Error FS0505 The member or object constructor 'add' does not take 1 argument(s). An overload was found taking 2 arguments.
```
correctly fails as overload resolution of immediately applied members will not deconstruct `pair`.  This is deliberate to give decent error messages (and yes it results in the perveived non-uniformity)
