### ISSUE TITLE
Visual Studio Online

### ISSUE THREAD

**Issue by ShalokShalom** [dotnet/fsharp#11912]
Codespaces moved from Azure to Github, and the link is semi-broken. 

New accounts can not be registered. And on Github, it seems to be in early access. 
Removing the [section](https://github.com/dotnet/fsharp/#visual-studio-online-quickstart) for now?

**Comment by cartermp** [comment]
Yeah, it should just get removed now. Eventually GitHub Codespaces will move out of private preview (maybe?) in which case this option for development is a lot more real for folks.

**Comment by ShalokShalom** [comment]
Let this open, until this happens?

**Comment by KevinRansom** [comment]
Closing, because merge fixed it.

**Comment by ShalokShalom** [comment]
Oh, I assumed it's fixed, when Github Codespace becomes public.
