### ISSUE TITLE
Community feedback ticket:   F# type initialization exception (JIT Compiler encountered an internal limitation) when debugging code with type annotations (let x = 1.0<_>)

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#11915]
We recieved this community feedback ticket: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1363623

Reported by:   Aaron Cutright

We will manage it here:
**[severity:I’m unable to use this version]**
Debugging tests in an F# project (run through the VS test runner and NUnit nuget package) causes an exception in the JIT compiler. This is a brand new issue after since I updated VS2019 yesterday.

````let suctionGauge= 0.<_>````

leads to

````System.TypeInitializationException: ‘The type initializer for ‘suctionGauge@287’ threw an exception.’
InvalidProgramException: JIT Compiler encountered an internal limitation.
````

**Comment by dsyme** [comment]
This is fixed by https://github.com/dotnet/fsharp/pull/11763

**Comment by dsyme** [comment]
Fixed bu https://github.com/dotnet/fsharp/pull/11763
