### ISSUE TITLE
Early bird builds of FSharp.Core and FSharp.Compiler.Service packages

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#11925]
We publish our nightly (they aren't really nightly anymore but hey ...) builds to public feeds.

**Comment by baronfel** [comment]
One thing that's hit me a few times in FSAC is that the branch the nightlies are published from isn't necessarily the same as the official FCS release branch. What this means is that when a new stable does come out, it contains some subset of the API that the nightly had (and possibly some intermediate APIs that were changed in an evolving fashion between the new FCS stable and the nightly), and so it becomes fairly difficult to revert when going from a nightly to a stable (for example if I were tracking nightly to reduce the integration burden or act as a canary for testing or AST differences.

**Comment by KevinRansom** [comment]
Sorry I pressed the button early, I was trying to organize my thoughts.  I don't want to rely on internal feeds they are too ad-hoc.

I will soon propose a schedule for publishing builds.  But first I have to figure out what won't kill us.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by baronfel** [comment]
Really lovely mate. Looking forward to the full proposal 👍

**Comment by vzarytovskii** [comment]
It would be really awesome if we could publish nightlies periodically, so people can test and adapt to changes quicker. Thanks a lot, Kevin!
