### ISSUE TITLE
Program crashes when using Excel

### ISSUE THREAD

**Issue by JohnyL** [dotnet/fsharp#11928]
This issue is the continuation of [this](https://github.com/dotnet/fsharp/issues/9864) issue. This time everything happens on totally another computer. I'm using Excel 2019.

### F#
```fsharp
open Microsoft.Office.Interop

[<EntryPoint>]
let main argv =
  let app = new Excel.ApplicationClass(Visible = true)
  let book = app.Workbooks.Add();
  let sheet = book.Worksheets.[1] :?> Excel.Worksheet;
  sheet.Range["A1"].Value <- "Hello from .NET 5!";
```

### C#
```csharp
static void Main(string[] args)
{
  var app = new Excel.Application { Visible = true };
  var book = app.Workbooks.Add();
  var sheet = book.Worksheets[1] as Excel.Worksheet;
  sheet.Range["A1"].Value = "Hello from .NET 5!";
}
```

### C#
![image](https://user-images.githubusercontent.com/7391680/128568483-90bf957b-b556-489a-ba5f-275056f3cfe9.png)

### F#
![image](https://user-images.githubusercontent.com/7391680/128568584-599d82e6-6387-4852-ad86-335803503896.png)

### C#
![image](https://user-images.githubusercontent.com/7391680/128568758-1428e4b2-b8c1-4d4b-b26e-878b58f1d2cf.png)

### F#
![IL_FSharp_Excel](https://user-images.githubusercontent.com/7391680/128569037-33d2fbb4-efe7-4712-b4dc-66caf1d4020d.png)

## .csproj File (F# and C#)
```xml
<ItemGroup>
  <COMReference Include="Microsoft.Office.Interop.Excel">
    <WrapperTool>primary</WrapperTool>
    <VersionMinor>9</VersionMinor>
    <VersionMajor>1</VersionMajor>
    <Guid>00020813-0000-0000-c000-000000000046</Guid>
    <Lcid>0</Lcid>
    <Isolated>false</Isolated>
    <EmbedInteropTypes>True</EmbedInteropTypes>
  </COMReference>
</ItemGroup>
```

As you can see, Excel types were not embedded into F# assembly as opposed to C# one. Moreover, as you can see on the screenshot, F# uses Excel 15.0 (Excel 2013) for some reason, although it was _never_ installed on the computer. In C# all works perfectly.

Provide any related information (optional):

* Operating system: Windows 10 Home x64 21H1 build 19043.1151
* .NET Runtime: .NET 6.0.100-preview.6.21355.2
* Editing Tools: Visual Studio 2022 17.0.0 Preview 2.1
* Excel 2019

**Comment by JohnyL** [comment]
@KevinRansom Why did you close this? I changed `EmbedInteropTypes` to `false` and it still tries to open Excel 2013, so the problem remains.

**Comment by JohnyL** [comment]
@KevinRansom Beg your pardon, but it was very rude from your side to close this issue without further investigation. You were not interested in it and were in rush to close it. I am very disappointed that I can't launch Excel already for YEAR!!!!! This is just sucks.

**Comment by dsyme** [comment]
@JohnyL 

The problem is that the fact that Excel 2013 gets opened won't be anything to do with F# per se - it will be the default behaviour of either 

1. MSBuild assembly referencing in the build process
2. the Excel interop libraries themselves.

Neither are in this repo, and so I think it's right to close the issue, even if it only manifests itself from F#.  That is, this repo has no specific logic with regard to either of these things - the assembly resolution process is part of MSBuild, and as far as we know we use the same process as C#. Assuming that's not the problem, then why the Excel interop libraries choose 2013 I don't know.  It is probably by design for some compat reason.

I'd encourage you to experiment with adding a small C# project to your solution that orchestrates the right launch of Excel, and then you should I think be able to use F# for the rest of your code?

Best
Don

**Comment by dsyme** [comment]
> When you could launch Excel last year, what version of Excel did you have?

I haven't launched Excel - that's not what I was saying :)

> I see "as far as we know", "assuming", "probably". These are all inaccurate terms. If you say that MSBuild resolution process is the same as of C#, then why it doesn't work? 

To be honest I don't know.  I'm really just saying that as fasr as we know it's nothing to do with anything in this repo (that is, when EmbedInteropTypes=false).  I could be wrong.

> If you pay attention to the screenshot, then you'll see that PublicKeyToken is not something like "000-000000", but of Excel 2013. Do you think it's "embedded" into MSBuild resolution process?
> Should I open an issue on appropriate repository dedicated to MSBuild?
> I'll say this way: All my work is with Excel, and I wanted to use F# for processing it, but this thing is show-stopper....

Have you asked and searched on stackoverflow?  That's possibly the best sort of place to find answers to "I have a problem using technology X with technology Y" questions.

**Comment by dsyme** [comment]
Answers like https://stackoverflow.com/questions/36017672/cant-see-some-properties-in-excel-interop-from-f may be of help fpr example.

**Comment by JohnyL** [comment]
Thanks for tips! I'll give it a try! 😎

> I haven't launched Excel - that's not what I was saying :)

Then what do [these words](https://github.com/dotnet/fsharp/issues/9864#issuecomment-684968051) mean? :)
> Hmmm I was able to start an Excel application using this

**Comment by JohnyL** [comment]
As it turned out, `dotnet build` is of no help here:
> C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Microsoft.Common.CurrentVersion.targets(2829,5): error : MSB4803: The task "ResolveComReference" is not supported on the .NET Core version of MSBuild. Please use the .NET Framework version of MSBuild. See https://aka.ms/msbuild/MSB4803 for further details.

**Comment by JohnyL** [comment]
Here's what Visual Studio output says:
> 1>  Done executing task "MakeDir".
1>  Using "ResolveComReference" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
1>  Task "ResolveComReference"
1>    Using cache file at "obj\Debug\net6.0\FSharpConsole.fsproj.ResolveComReference.cache".
1>    Resolving COM reference for item "Microsoft.Office.Interop.Excel" with a wrapper "tlbimp".
1>    Determining dependencies of the COM reference "Microsoft.Office.Interop.Excel".
1>    Resolving COM reference dependency "00020430-0000-0000-c000-000000000046" version 2.0.
1>    Resolved COM reference dependency "00020430-0000-0000-c000-000000000046" version 2.0: "C:\Windows\assembly\GAC\stdole\7.0.3300.0__b03f5f7f11d50a3a\stdole.dll"
1>    Resolving COM reference dependency "2df8d04c-5bfa-101b-bde5-00aa0044de52" version 2.8.
1>    Resolved COM reference dependency "2df8d04c-5bfa-101b-bde5-00aa0044de52" version 2.8: "C:\Windows\assembly\GAC_MSIL\Office\15.0.0.0__71e9bce111e9429c\Office.dll"
1>    Resolving COM reference dependency "0002e157-0000-0000-c000-000000000046" version 5.3.
1>    Resolved COM reference dependency "0002e157-0000-0000-c000-000000000046" version 5.3: "C:\Windows\assembly\GAC_MSIL\Microsoft.Vbe.Interop\15.0.0.0__71e9bce111e9429c\Microsoft.Vbe.Interop.dll"
1>    Resolved COM reference for item "Microsoft.Office.Interop.Excel": "obj\Debug\net6.0\Interop.Microsoft.Office.Interop.Excel.dll".
1>  Done executing task "ResolveComReference".

**Comment by dsyme** [comment]
You'll need logs for identical C# and F# compilations.

> Then what do these words mean? :) https://github.com/dotnet/fsharp/issues/9864#issuecomment-684968051

Yeah I read that and I actually have no recollection of trying that out.  I mean I don't have Excel 2013 on my machine but I guess the version I do have started, it must have been `"C:\Program Files (x86)\Microsoft Office\root\Office16\EXCEL.EXE"`

**Comment by JohnyL** [comment]
So, I've got "good" news. I have copied `COMReference` entry from F# .csproj file to C# one, and... boom! Same error! Same logs! So, the problem is somehow connected with interop embedding.
P.S. For the record: I have tried several combinations like:
1. `Microsoft.Office.Interop.Excel` and `Microsoft.Office.Interop.Excel.dll`
2. `<WrapperTool>tlbimp</WrapperTool>` and `<WrapperTool>primary</WrapperTool>`

Here's C# logs:
> 1>  Using "ResolveComReference" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
1>  Task "ResolveComReference"
1>    Using cache file at "obj\Debug\net6.0-windows\ConsoleExcel.csproj.ResolveComReference.cache".
1>    Resolving COM reference for item "Microsoft.Office.Interop.Excel" with a wrapper "tlbimp".
1>    Determining dependencies of the COM reference "Microsoft.Office.Interop.Excel".
1>    Resolving COM reference dependency "00020430-0000-0000-c000-000000000046" version 2.0.
1>    Resolved COM reference dependency "00020430-0000-0000-c000-000000000046" version 2.0: "C:\Windows\assembly\GAC\stdole\7.0.3300.0__b03f5f7f11d50a3a\stdole.dll"
1>    Resolving COM reference dependency "2df8d04c-5bfa-101b-bde5-00aa0044de52" version 2.8.
1>    Resolved COM reference dependency "2df8d04c-5bfa-101b-bde5-00aa0044de52" version 2.8: "C:\Windows\assembly\GAC_MSIL\Office\15.0.0.0__71e9bce111e9429c\Office.dll"
1>    Resolving COM reference dependency "0002e157-0000-0000-c000-000000000046" version 5.3.
1>    Resolved COM reference dependency "0002e157-0000-0000-c000-000000000046" version 5.3: "C:\Windows\assembly\GAC_MSIL\Microsoft.Vbe.Interop\15.0.0.0__71e9bce111e9429c\Microsoft.Vbe.Interop.dll"
1>    Resolved COM reference for item "Microsoft.Office.Interop.Excel": "obj\Debug\net6.0-windows\Interop.Microsoft.Office.Interop.Excel.dll".
1>  Done executing task "ResolveComReference".

**Comment by FoggyFinder** [comment]
> All my work is with Excel, and I wanted to use F# for processing it, but this thing is show-stopper....

I know it's old issue but someone mentioned it in [Announcing F# 7](https://devblogs.microsoft.com/dotnet/announcing-fsharp-7/)

I suggest using [Open XML SDK](https://github.com/OfficeDev/Open-XML-SDK) instead of struggling with Interop. Of course, not directly, it would be a nightmare, but there are libraries on top of it.

**Comment by JohnyL** [comment]
@FoggyFinder It was me who mentioned it. )))) I _would_ like to learn F#, but thing doesn't let me do it. If someone would help, I'd really appreciate it!!!

**Comment by FoggyFinder** [comment]
> I would like to learn F#, but thing doesn't let me do it. If someone would help, I'd really appreciate it!!!

@JohnyL There're many places where you can ask Qs, some links:

[F# Slack](https://fsharp.org/guides/slack/) - I was inactive lately but I think it's still the best one
[F# Discord](https://discord.com/invite/R6n7c54)

if you prefer QA format rather than chat

[F# Community Forum](https://forums.fsharp.org/)](https://forums.fsharp.org)
[F# StackOverFlow](https://stackoverflow.com/questions/tagged/f%23)
[F# subreddit](https://www.reddit.com/r/fsharp/)
[CoDidact: Software Development](https://software.codidact.com/)

if it's not what you're looking for feel free to clarify

**Comment by JohnyL** [comment]
@FoggyFinder I have already [asked a question](https://www.reddit.com/r/fsharp/comments/p34pxf/f_doesnt_want_to_launch_excel/) on Reddit, but got... not so polite answer. ))) Anyway, thanks for links!

**Comment by FoggyFinder** [comment]
@JohnyL it was year ago. Do you consider option to use OpenXML as I suggested before? What task are you trying to solve?
