### ISSUE TITLE
FSI fails with "error FS3217: No such file or directory"

### ISSUE THREAD

**Issue by pkese** [dotnet/fsharp#11923]
**Repro steps**

I'm having a small `Test.fsx` file containing just:

```fsharp
#r "nuget: Ply, 0.3.1"
open FSharp.Control.Tasks
printfn "hello world"
```
The result of running the script is:
```sh
> dotnet fsi Test.fsx 
/home/peter/Test.fsx(1,1): error FS3217: No such file or directory
```
However if I run it as sudo, it works fine:
```
> sudo dotnet fsi Test.fsx 
hello world
```

I assume that the problem is that somehow running `dotnet fsi` once in the past as a `sudo` user,  
mesed up the environment in a way that non-root user's `fsi` now can't access packages any more.

But I can't fix this situation. I've tried to:
- apt remove --purge and reinstall dotnet-sdk
- rm -rf ~/.local/share/NuGet ~/.local/share/Nuget ~/.nuget ~/.dotnet /tmp/NuGetScratch
- dotnet nuget locals all --clear

This is happening on:   
Ubuntu 21.04 with  
dotnet-sdk-5.0                                5.0.302-1

**Comment by pkese** [comment]
It would also be very helpful if the reported error contained some more useful information (e.g. explaining which file is missing).

**Comment by pkese** [comment]
Just to be more explicit:

No `dotnet fsi` script whatsoever runs any more.  
In addition Visual Studio Code's Intellisense isn't working on `.fsx` files, because it can't access `#r "..."` referenced packages.

Normal F# projects with a proper `.fsproj` files however work fine.

**Comment by dsyme** [comment]
@KevinRansom This looks severe, do we know what's going on? thanks

**Comment by KevinRansom** [comment]
I will look at this week.

**Comment by KevinRansom** [comment]
@ppkese ---

I installed the recommended dotnet sdk build from here: https://dotnet.microsoft.com/download/dotnet/5.0

Using these instructions:  https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2104-

Your repro script worked fine ...

````
kevinr@kevinr-work:/mnt/c/Users/codec$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.400/

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  5.0.400 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
kevinr@kevinr-work:/mnt/c/Users/codec$ dotnet fsi

Microsoft (R) F# Interactive version 11.4.2.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> #r "nuget: Ply, 0.3.1"
- open FSharp.Control.Tasks
- printfn "hello world";;
[Loading /tmp/nuget/216--caa7779f-289a-4274-ae0d-eb7b290fae42/Project.fsproj.fsx]
namespace FSI_0002.Project

hello world
val it : unit = ()

>
````
I guess we need some more information:
1. Can you please run ````dotnet --info```` and provide the output.
2. Also could you ensure that the folder ````/tmp```` is available.
3. Using dotnet fsi run this snippet and provide the output
    ````printfn "%s" typeof<int>.Assembly.Location;;````


````
kevinr@kevinr-work:/mnt/c/Users/codec$ dotnet fsi

Microsoft (R) F# Interactive version 11.4.2.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> printfn "%s" typeof<int>.Assembly.Location;;
/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Private.CoreLib.dll
val it : unit = ()

>
````
Thanks

Kevin

**Comment by vzarytovskii** [comment]
I guess the problem is with `sudo`, when you launch it once, it probably writes somewhere with specific permissions, which mess it up for normal user. I can test it tomorrow.

**Comment by vzarytovskii** [comment]
@pkese Could you please try removing `/tmp/nuget` (given it exists)?

**Comment by pkese** [comment]
Sorry for latency in my responses (I'm on vacation somewhere without electricity).

And yes indeed, cleaning up `/tmp/nuget` fixed the problem.  
It also makes things reproducible (running a .fsx script as root messes things up, cleaning `/tmp/nuget` fixes it).

Thanks. It is not a perfect solution, and possibly some other folks might also encounter it in the future, but at least it allows _me_ to keep going.  
The _root_ of my problem is that I wrote a .fsx a system maintenance script that I have put into crontab and it runs as root. I'll need to find a workaround for that.

Ohterwise my `dotnet --info` says
```
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  21.04
 OS Platform: Linux
 RID:         ubuntu.21.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.400/

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  5.0.400 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

Also:
```
peter@tuf:~$ dotnet fsi

Microsoft (R) F# Interactive version 11.4.2.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> printfn "%s" typeof<int>.Assembly.Location;;
/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Private.CoreLib.dll
val it : unit = ()
```

**Comment by dsyme** [comment]
Yes, it's like any `root` or `sudo` should be using a completely different nuget packages directory
