### ISSUE TITLE
Can't import module for the F# Getting Started tutorial?

### ISSUE THREAD

**Issue by JansthcirlU** [dotnet/fsharp#11924]
I'm trying to follow along with the [F# tutorial](https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-vscode) and it's very usef-friendly, but in the [second part of the tutorial](https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-vscode#turn-the-console-app-into-a-pig-latin-generator), you need to put all the logic inside a module within the `Program.fs` file.

The intended file looks like this:

```fsharp
// Learn more about F# at http://docs.microsoft.com/dotnet/fsharp

open System

module PigLatin =
    let toPigLatin (word: string) =
        let isVowel (c: char) =
            match c with
            | 'a' | 'e' | 'i' | 'o' | 'u'
            | 'A' | 'E' | 'I' | 'O' | 'U' -> true
            | _ -> false
        if isVowel word.[0] then
            word + "yay"
        else
            word.[1..] + string(word.[0]) + "ay"

[<EntryPoint>]
let main argv =
    for name in argv do
        let newName = PigLatin.toPigLatin name
        printfn "%s in Pig Latin is: %s" name newName
    0 // return an integer exit code
```

I figured I could create a different file called `PigLatin.fs` and define the module there (instead of inside `Program.fs`) and call it directly with its name, but I get a **The value, namespace, type or module 'PigLatin' is not defined.F# Compiler39** error. Using `open PigLatin` inside `Program.fs` also doesn't work.

My folder structure looks like this:

```txt
FirstIonideProject
├── FirstIonideProject.fsproj
├── MyFirstScript.fsx
├── PigLatin.fs
├── Program.fs
├── bin
│    └─ ...
└── obj
     └─ ...
```
Is there no straightforward way to import namespaces and modules from other files?

**Comment by baronfel** [comment]
This is probably because when you added the `PigLatin.fs` file, you didn't add it to the `FirstIonideProject.fsproj` project file, above the `Program.fs` file. I'm don't know your background but in .Net projects, sources must be included in the project file as `Compile` elements. In C# this is done implicitly, but in F# our dependencies must be explicitly ordered in the file.

**Comment by JansthcirlU** [comment]
@baronfel thanks, I am used to using C# so I never realised those files were added to the project file like that.

My current project file looks like this:

```fsproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <WarnOn>3390;$(WarnOn)</WarnOn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="PigLatin.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
```
But what I find strange is that I can now open the module but I still have to call its name to access its members like this (in `Program.fs`):

```fs
// Learn more about F# at http://docs.microsoft.com/dotnet/fsharp

open System
open PigLatin

[<EntryPoint>]
let main argv =
    for name in argv do
        let newName = PigLatin.toPigLatin name // Why does just 'toPigLatin name' not compile?
        printfn "%s in Pig Latin is: %s" name newName
    0 // return an integer exit code
```

**Comment by baronfel** [comment]
@JansthcirlU can you provide the whole content of `PigLatin.fs` here for context?  There are a couple subtleties to module declaration that can result in a 'wrapper' namespace around the module.

**Comment by JansthcirlU** [comment]
@baronfel oh my bad, I called both the namespace and the module `PigLatin` so by using `open PigLatin` to open the namespace, I still need to call the `PigLatin` module to access its method.

```fs
namespace PigLatin
    module PigLatin =
        let toPigLatin (word: string) =
            let isVowel (c: char) =
                match c with
                | 'a' | 'e' | 'i' | 'o' | 'u'
                | 'A' | 'E' | 'I' | 'O' | 'U' -> true
                | _ -> false
            if isVowel word.[0] then
                word + "yay"
            else
                word.[1..] + string(word.[0]) + "ay"
```
So what I expected to happen would be accomplished by dropping the namespace and using a top-level module declaration like so, right?
```fs
module PigLatin
    let toPigLatin (word: string) =
      ...
```

**Comment by baronfel** [comment]
Exactly that. That's pretty much what I expected to see when I asked :)

**Comment by JansthcirlU** [comment]
Thanks for the help! Even though it's a simple fix, I do hope they'll add automatic file addition and dependency checks so that the F# community can steal away more C# devs in the future ;)
