### ISSUE TITLE
Build FSharp.Compiler.Service solution in CI

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#11933]
Build FSharp.Compiler.Service solution in CI.

Shall we build it with stable SDK as well (and separate global.json)?
@brettfo @KevinRansom I know you have strong opinions about that.
@auduchinok Mentioned that using latest SDKs is a pain when working with service.

**Comment by brettfo** [comment]
I don't think this is something we can reasonably support.  As a part of the contract of us being included in the .NET SDK is that we need to support the exact same build mechanism that they do, and that means we have exactly one build entry point, which is `build.cmd`/`build.sh` and we also have to use the same last-known-good SDK to bootstrap.  We can't support multiple/different SDKs and global.json configurations.  Even our partners at Red Hat that do a sourec build of the entire SDK (including F#) need to go through this same path.

The closest scenario we can offer is an existing CI step we call `Plain_Build_Linux` which first calls the common build entry point of `build.sh`, but then simply calls `dotnet build FSharp.sln`.  We could add a CI step that first calls `build.sh` but then calls `dotnet build FSharp.Compiler.Service.sln`.

**Comment by auduchinok** [comment]
> @auduchinok Mentioned that using latest SDKs is a pain when working with service.

It was specifically about relying on preview SDKs in FCS solution.

> We could add a CI step that first calls build.sh but then calls dotnet build FSharp.Compiler.Service.sln.

Would it be possible to be a separate check/build that would, like you suggest, call `build.sh` and then build the solution, but it'd use a stable SDK?

**Comment by auduchinok** [comment]
@brettfo @vzarytovskii  Would it be possible to have a stable SDK version + rollforward in global.json and use the preview one in Arcade/CI?

**Comment by vzarytovskii** [comment]
> @brettfo @vzarytovskii Would it be possible to have a stable SDK version + rollforward in global.json and use the preview one in Arcade/CI?

The problem is that Arcade manages our main global.json.

Let me think of something, I have one solution in mind, need to discuss it with Brett.

**Comment by vzarytovskii** [comment]
Done in #11963
