### ISSUE TITLE
Revert Visual Studio Default to the desktop compiler

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#11941]
Here it is identified that the Coreclr compiler startup time is slower:   https://github.com/dotnet/fsharp/issues/11907

So we should go back to using the ngened desktop compiler, until the performance issue is addressed.

It's a regression in the performance of Visual Studio, even though the coreclr has behaved this way for a long time.

**Comment by vzarytovskii** [comment]
This is done
