### ISSUE TITLE
Private types with public members

### ISSUE THREAD

**Issue by stmax82** [dotnet/fsharp#11953]
There seems to be a discrepancy between C# and F# when access modifiers are put on members of private types.

The following C# code outputs:

```
Publics:
  X
Privates:
```

```csharp
using System;
using System.Reflection;

class Program {
    // private class with public property
    private class Foo {
        public string X { get => "foo"; }
    }

    static void Main(string[] args) {
        var t = typeof(Foo);

        Console.WriteLine("Publics:");
        var publics = t.GetProperties(BindingFlags.Public | BindingFlags.Instance);
        foreach (var x in publics)
            Console.WriteLine($"  {x.Name}");

        Console.WriteLine("Privates:");
        var privates = t.GetProperties(BindingFlags.NonPublic | BindingFlags.Instance);
        foreach (var x in privates)
            Console.WriteLine($"  {x.Name}");
    }
}
```

Semantically the same F# code outputs:

```
Publics:
Privates:
  X
```

```fsharp
open System
open System.Reflection

// private class with public property
type private Foo() =
    member public this.X with get() = "foo"

[<EntryPoint>]
let main argv =
    let t = typeof<Foo>

    Console.WriteLine("Publics:")
    let publics = t.GetProperties(BindingFlags.Public ||| BindingFlags.Instance)
    for x in publics do
        Console.WriteLine($"  {x.Name}")

    Console.WriteLine("Privates:")
    let privates = t.GetProperties(BindingFlags.NonPublic ||| BindingFlags.Instance);
    for x in privates do
        Console.WriteLine($"  {x.Name}")

    0
```

Since property Foo.X is marked as public in both cases, I'd expect it to be public in both cases, but it turns out as private in F#.

The same problem happens with private records that should have public labels:

```fsharp
type private Foo = public { X: string }
```

Here `typeof<Foo>.GetProperties(...)` also shows that property X is private, even though the record's labels are marked as public.

This causes problems in all places where private types (no matter if classes or records) are processed using reflection.

For example with Dapper: it is not possible to use private F# types as SQL parameter objects because Dapper uses Type.GetProperties(), which by default only returns public properties:

```fsharp
type private DbRow = public {
    A: string
    B: int
}

cnn.Execute("INSERT INTO Foo (A, B) VALUES (@A, @B)", { A = "foo"; B = 42 })
```

... throws some exception because it doesn't find values for the SQL parameters A and B.

**Comment by dsyme** [comment]
I created a language suggestion here https://github.com/fsharp/fslang-suggestions/issues/1057

Because of compat concerns it's likely that we'd need a `CLIPublic` attribute

**Comment by dsyme** [comment]
I'll close this because it's currently by-design and is tracked by the suggestion above, which I've marked approved-in-principle.

If you'd like to work on the RFC or implementation please let me know

Thanks!

**Comment by robitar** [comment]
@dsyme re `private` types having a `public` interface in C#, is this not meaningful for a nested type? The type itself is a private member, but it has some control over the members it exposes to its enclosing type:

```c#
class Thing {
	private class ImplementationDetail {
		public void Frob() {
			//...
		}

		private int state;
	}

	public Thing() {
		var inner = new ImplementationDetail();
		inner.Frob();

		Console.WriteLine(inner.state); //CS0122: inaccassable
	}
}
```

Probably not something you'd want to make a lot of use of, but handy for keeping things like inner state machines/cursors neat.

**Comment by dsyme** [comment]
@robitar Yes, you are right that in that case the `public` means "public up to Thing, which is internal", and does affect the logical accessibility. There is no way to explicitly declare that otherwise, though you could just use "assembly" (same as Thing) 

Roughly equiv F# code:
```fsharp
module internal Thing =
    // Means "private to the enclosing module"
    type private ImplementationDetail() =
        
        // Logical accessibility is "Thing"
        member internal _.Frob() = ()

        // Logical accessibility is ImplementationDetail - constrained by "Thing"
        member private _.Glob() = ()

    let create() = 
        let inner = new ImplementationDetail()
        inner.Frob()
        inner.Glob() // not accessible
```

**Comment by robitar** [comment]
Yes interesting, it's very close. Just to be sure I follow the point about `Frob` in your example there (I was trying to grok it above as well), that the combination of `private` on the type and `internal` on the member constrains its accessibility further - as in a sort of intersection of assembly visibility, and that of the containing type, which is effectively equivalent to the containing type?

I'm guessing from the original request here that it's not possible or desirable to make `Frob` public, because it would be confusing to see `public` nested in a scope more restrictive than itself.

I do recall having to learn the approach C# takes, back in the day; it wasn't immediately intuitive, but once it clicks, it makes some sense to treat the accessibility modifiers in terms of 'local space only'. I also quite like your example above (if I'm understanding it) which allows you to do a kind of logical constraints-based approach.

I can see both sides all right, it's very interesting to see the design philosophies manifesting in these edge cases.

**Comment by dsyme** [comment]
> as in a sort of intersection of assembly visibility, and that of the containing type, which is effectively equivalent to the containing type?

Yes, that's right, that's the way to compute the logical accessiblity.

Given that F# includes several logical accessibilities that don't have .NET equivalents (e.g. "private" on a type means "private to the enclosing namespace fragment or module") it always seemed best to just emit either "public" or "internal" as the .NET accessibility.  We emitted "public" if the logical accessibility was public, and "internal" if not. 

Anyway all in all I think it's right to use `CLIPublic` for this particular corner-case.

**Comment by robitar** [comment]
Yes that makes sense.

Thanks for taking the time to clarify!
