### ISSUE TITLE
GetHashCode() on Set may fail because of Math.Abs

### ISSUE THREAD

**Issue by goswinr** [dotnet/fsharp#11964]
`GetHashCode()` on `Set` fails for 
```fsharp
let s = Set.singleton 2147483017
s.GetHashCode() 
```
with
```
Runtime Error:
System.OverflowException: Negating the minimum value of a twos complement number is invalid.
   at System.Math.AbsHelper(Int32 value)
   at Microsoft.FSharp.Collections.FSharpSet`1.ComputeHashCode() in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\set.fs:line 732
   at <StartupCode$FSI_0023>.$FSI_0023.main@()
```
this is because of `abs` in https://github.com/dotnet/fsharp/blob/dbf9a625d3188184ecb787a536ddb85a4ea7a587/src/fsharp/FSharp.Core/set.fs#L732
fails on `Int32.MinValue`. Maybe the `abs `can just be removed ?

**Comment by dsyme** [comment]
Yes, we can fix this, thank you for the report

**Comment by goswinr** [comment]
on the internal Set probably too: 
https://github.com/dotnet/fsharp/blob/dbf9a625d3188184ecb787a536ddb85a4ea7a587/src/fsharp/utils/TaggedCollections.fs#L585

**Comment by dsyme** [comment]
@goswinr I reopened as it seems to be a real issue?

**Comment by goswinr** [comment]
@dsyme sure, OK! (i just thought it's tracked in the PR)
