### ISSUE TITLE
Build VisualFSharp.sln fails with FSharpEmbedResXSource" task failed unexpectedly.

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#11962]
This is due to mismatched FSharp.Cores.

The VisualFSharp solution loads: A Version of FSharp.Core that doesn't have the api: ArrayCollector<T>

![image](https://user-images.githubusercontent.com/5175830/129288418-d2ba9e4b-2109-4dec-ad3b-6349839c77ea.png)

It's not clear to me how to fix this.  I shall have to sleep on it.

**Comment by deviousasti** [comment]
I'm getting a similar error in VS 2022 Preview 3 for a solution targeting .net core 3.1.
```
MSB4062	The "FSharpEmbedResXSource" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\3.1.404\FSharp\FSharp.Build.dll. Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	Stormbreaker.Legacy.Tests	C:\Program Files\dotnet\sdk\3.1.404\FSharp\Microsoft.FSharp.Targets	184	
```

**Comment by KevinRansom** [comment]
@deviousasti I believe that your issue is due to a seperate problem ... I opened a seperate issue here: https://github.com/dotnet/fsharp/issues/11967
