### ISSUE TITLE
Unable to parse some embedded IL

### ISSUE THREAD

**Issue by En3Tho** [dotnet/fsharp#11987]
https://github.com/dotnet/fsharp/blob/main/src/fsharp/absil/illex.fsl
and
https://github.com/dotnet/fsharp/blob/main/src/fsharp/absil/ilascii.fs
are out of sync
Tables generated by illex corrupt parsing of il tokens: "ldarg.0" becomes just "ldarg", there is no corresponding value in ilascii.fs
While "ldarga.0" is supported and is parsed as "ldarga.0" but again there is no such value in corresponding table in ilascii.fs

This is applicable to other IL tokens too.

I would like to fix this but I need to know what are "official" names of tokens in F# CoreLib, eg "ldarg.0" as in ilascii.fs or "ldarga.0" as in illex.fs.

Also, what about just "ldarg (ushort)", "ldarg_s", "ldc.r8" (which is even mentioned in comment at illex.fsl) etc ?

@dsyme

**Comment by dsyme** [comment]
Hi Igor,  I don't think we should make any changes here.   Embedded IL is for FSharp.Core and while it can be used for similar code snippets outside it's not something we add any more instructions to.  It is what it is.

Thanks
Don




Thanks
