### ISSUE TITLE
Intellisense shows Private Fields from Record Types 

### ISSUE THREAD

**Issue by pblasucci** [dotnet/fsharp#1198]
I think I've stumbled upon a regression in the code emitted for records. Specifically, it looks as though the `private` modifier no longer follows the specification. Though it's possible I've misread the specification. 

Submitting here for review/discussion.
#### Repro steps
1. Define a library containing the following types:

```
namespace Test

module Types =

  type MyUnion =
    private 
    | Case1 of int
    | Case2 of string

  type MyRecord =
    private
       { Field1 :int
         Feild2 : string }
```
1. Consume the library from step 1 in a different library/application/script
#### Expected behavior

Neither the cases of `MyUnion` nor the fields of `MyRecord` should be visible to the consuming code.
#### Actual behavior

`MyUnion` behaves as expected. However, the fields of `MyRecord` are still accessible. 
#### Known workarounds

Currently, I'm working around this by using signature files for hiding.
#### Related information
- Windows 8.1
- fsc.exe v4 (shipped with Visual Studio 2015)
- using `Fsharp.Core.dll` v4.4.0.0 (via Paket+NuGet)
- .NET Runtime v4.5
- Visual Studio 2015 Enterprise
- Severity: low

**Comment by dsyme** [comment]
@pblasucci Could you fill in step 2 of the repro please?  I tried with this and couldn't repro:

```fsharp

open Test.Types

let f (x:MyRecord) = x.Field1

let f2 () = { Field1 = 1; Feild2 = "abc" }


let f3(x:MyRecord) = { f2() with Field1 = 4 }

```

It gave:

```
r2.fs(3,22): error FS1093: The union cases or fields of the type 'MyRecord' are
not accessible from this code location

r2.fs(5,13): error FS1093: The union cases or fields of the type 'MyRecord' are
not accessible from this code location

r2.fs(5,13): error FS1093: The union cases or fields of the type 'MyRecord' are
not accessible from this code location

r2.fs(5,13): error FS1093: The union cases or fields of the type 'MyRecord' are
not accessible from this code location

r2.fs(5,13): error FS1093: The union cases or fields of the type 'MyRecord' are
not accessible from this code location

r2.fs(8,22): error FS1093: The union cases or fields of the type 'MyRecord' are
not accessible from this code location

r2.fs(8,22): error FS1093: The union cases or fields of the type 'MyRecord' are
not accessible from this code location

r2.fs(8,22): error FS1093: The union cases or fields of the type 'MyRecord' are
not accessible from this code location
```

**Comment by pblasucci** [comment]
Ah, @dsyme, I think I made a mistake. You are correct in that it does not successfully compile. I was stopping at the fact the it showed up in intellisense (and when generating API docs). I should've tried the actual compilation.

Sorry. My bad.  :-(

The compiler does the right thing. So, I'll close this issue. But the behavior of the Intellisense (and FSharp.Formatting) is... counter-intuitive. Should I open an issue elsewhere? If so, where?

Thanks!  :-)

**Comment by dsyme** [comment]
Reopening and adjusting title to reflect this is about intellisense

**Comment by pblasucci** [comment]
Thanks, @dsyme.

**Comment by dsyme** [comment]
Closing this old issue
