### ISSUE TITLE
Improve VS Debugging experience for F#

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#12004]
This issue will collect for planning purposes the issues related to F# debugging:

- [ ] - https://github.com/dotnet/fsharp/issues/12005
- [ ] - https://github.com/dotnet/fsharp/issues/12003
- [ ] - https://github.com/dotnet/fsharp/issues/12002
- [ ] - https://github.com/dotnet/fsharp/issues/12001
- [ ] - https://github.com/dotnet/fsharp/issues/12000
- [ ] - https://github.com/dotnet/fsharp/issues/11980
- [ ] - https://github.com/dotnet/fsharp/issues/7456
- [ ] - https://github.com/dotnet/fsharp/issues/3866
- [ ] - https://github.com/dotnet/fsharp/issues/3327
- [ ] -

**Comment by dsyme** [comment]
We could just use https://github.com/dotnet/fsharp/labels/Area-Debug??

**Comment by vzarytovskii** [comment]
> We could just use https://github.com/dotnet/fsharp/labels/Area-Debug??

Yeah, it makes sense.

**Comment by dsyme** [comment]
@KevinRansom If it's ok I'll close this in favour of just using the label, thanks
