### ISSUE TITLE
Match expression inside match expression leads to offside error.

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#12011]
I believe I found a regression when it comes to the offside warnings.

**Repro steps**

When getting the untyped AST from the following example:
```fsharp
let u = ""

match!
    match! u with
    | null -> ""
    | s -> s
    with
| "" -> x
| _ -> failwith ""
```

An offside error will be reported. `[|tmp.fsx (9,1)-(9,2) parse warning Possible incorrect indentation: this token is offside of context started at position (5:5). Try indenting this token further or using standard formatting conventions.|]`

This does not occur when the match expression is multiline but without a match expression.
```fsharp
let u = ""

match!
    someLongFunctionApplication
        arg1
        arg2
        arg3
    with
| "" -> x
| _ -> failwith ""
```

**Expected behavior**

In FCS 39 no warnings were produced.

**Actual behavior**

Offside errors only in the cases where the match expression is a match (bang) expression.

**Known workarounds**

The indentation of the original code could be changed to get around this warning:
```fsharp
let u = ""

match!
    match! u with
    | null -> ""
    | s -> s
with
| "" -> x
| _ -> failwith ""
```

This is also valid but not in the current version of F#.

**Related information**

Provide any related information (optional):

FSharp.Compiler.Service 40.0.1-preview.21418.3

I suspect the recent changes of @Happypig375 might be related here.
//cc @dsyme

**Comment by dsyme** [comment]
Thanks for the report!

**Comment by dsyme** [comment]
Note I'm only seeing this on `main` with `/langversion:preview`

Strictly speaking this doesn't make it a regression but rather a bug in the preview feature

@Happypig375 Could you take a look?


```
C:\GitHub\dsyme\fsharp>fsc b.fs --parseonly
Microsoft (R) F# Compiler version 11.4.2.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

warning FS0075: The command-line option '--parseonly' is for test purposes only

C:\GitHub\dsyme\fsharp>artifacts\bin\fsc\Debug\net472\fsc.exe b.fs --parseonly
Microsoft (R) F# Compiler version 11.3.3.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

warning FS0075: The command-line option '--parseonly' is for test purposes only

C:\GitHub\dsyme\fsharp>artifacts\bin\fsc\Debug\net472\fsc.exe b.fs --parseonly --langversion:preview
Microsoft (R) F# Compiler version 11.3.3.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

warning FS0075: The command-line option '--parseonly' is for test purposes only

b.fs(8,1): warning FS0058: Possible incorrect indentation: this token is offside of context started at position (4:5). Try indenting this token further or using standard formatting conventions.
```

**Comment by nojaf** [comment]
Hmm, I got this when parsing text via `dotnet fsi`.

My script:
```fsharp
#i "nuget:https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json"
#r "nuget:FSharp.Compiler.Service, 40.0.1-preview.21418.3"

open FSharp.Compiler.Text
open FSharp.Compiler.CodeAnalysis

let fileName = "tmp.fsi"
let checker = FSharpChecker.Create()

let parsingOptions =
    { FSharpParsingOptions.Default with
          SourceFiles = [| fileName |] }

let getAst fileName source =
    async {
        let! tree = checker.ParseFile(fileName, source |> SourceText.ofString, parsingOptions)
        if tree.Diagnostics.Length > 0 then printfn "%A" tree.Diagnostics
        return tree.ParseTree
    }
    |> Async.RunSynchronously

getAst
    "tmp.fsx"
    """
let u = ""

match!
    match! u with
    | null -> ""
    | s -> s
    with
| "" -> x
| _ -> failwith ""
    """
```

**Comment by Happypig375** [comment]
My F# compiler setup has been wonky ever after the requirement of .NET 6 builds. My Visual Studio 2019 won't show IntelliSense, builds fail, etc. I would need to fix it before looking into this issue.

**Comment by auduchinok** [comment]
@Happypig375 JFYI it's now possible to use .NET 5 again, if you open `./service/FSharp.Compiler.Servive.sln` solution instead.

**Comment by vzarytovskii** [comment]
> Strictly speaking this doesn't make it a regression but rather a bug in the preview feature

It is in [`langaugeVersion60`](https://github.com/dotnet/fsharp/blob/release/dev17.0/src/fsharp/LanguageFeatures.fs#L88) in `dev17.0`.
Looking at it. It's due to changes when we calculate offset for `| _, CtxtMatch offsidePos :: _` when feature is enabled I think.

**Comment by dsyme** [comment]
@Happypig375 Have you had a chance to look at this?  Thanks

**Comment by Happypig375** [comment]
Nope, been busy

**Comment by Happypig375** [comment]
Nope, been busy, sorry

**Comment by Happypig375** [comment]
Nope, been busy, sorry

**Comment by dsyme** [comment]
@Happypig375 OK. 

Since this is a regression in F# 6.0 it's important to get to the bottom of it :) It would be really helpful if you can help us with that.

**Comment by dsyme** [comment]
@DalekBaldwin Thanks. Could you give us some sample code?  Also does the problem resolve with `/langversion:5.0`?

Thanks

**Comment by DalekBaldwin** [comment]
Looking at all the places it popped up in our project, it's a bit more interesting. Like the OP, it only seems to be happening in places where the `try` body ends with a match expression, but unlike the OP, it gives an error, not a warning.

A minimal case:

```fsharp
let tryWithTest () =
    try
        match true with
        | true -> "true"
        | false -> "false"
        with
        | ex -> ex.Message
```

Microsoft (R) F# Interactive version 12.0.0.0 for F# 6.0: `error FS0010: Incomplete structured construct at or before this point in binding. Expected incomplete structured construct at or before this point or other token.`

With `/langversion:5.0`: no problem

But using the same indentation for pure match expressions compiles fine on either version, without even a warning:

```fsharp
let matchTest () =
    match
        match true with
        | true -> "true"
        | false -> "false"
        with
        | s -> s
```

**Comment by dsyme** [comment]
This is fixed
