### ISSUE TITLE
Broken documentation links shown in VS Code from Ionide that is generated by F# Compiler

### ISSUE THREAD

**Issue by Jaimeloeuf** [dotnet/fsharp#12017]
**Issue:**
The links generated by F# compiler and passed to VS Code Ionide links are broken and links to a `404 - Page not found`

---

**Expected behavior**
Expected link to be valid

---

**Actual behavior**
- When there are code issues detected, an error message is shown: `The non-generic type 'Program.Example' does not expect any type arguments, but here is given 1 type argument(s) F# Compiler(33)`
- Where `33` is an underlined link that can be clicked, and upon clicking it, it brings me to <https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/compiler-messages/fs0033> and this is a invalid link, below attached is a screen shot of the site.
![Screenshot of site](https://user-images.githubusercontent.com/44993072/130469727-90296f49-1015-4676-9269-4371e9264556.png)
- The full error message generated is
![image](https://user-images.githubusercontent.com/44993072/130471508-ffb39250-b639-470e-b069-80f820db4551.png)

I assume this issue is with F# compiler since I was unable to find any references to the documentation site by searching around in the Ionide repo, but was able to find references to the error message within this repo, thus am opening here. Do let me know if this is the wrong place!

---

**Repro steps**
1. Create F# project in VS Code
2. Write some invalid code and wait for compiler to show error
3. Click on link to learn more to see the error site

This works with all the errors I had so far, not just error 33.

I am not too sure how to fix this too, but do let me know if this is something I can help fix and make a PR too.

---

**Related information**
- Windows 10
- `dotnet --version` gives 5.0.300
- Visual Studio Code `1.59.1  3866c3553be8b268c8a7f8c0482c0c0177aa8bfa  x64`
- Ionide `v5.7.1`

**Comment by baronfel** [comment]
This should not be raised here, these links are entirely generated by Ionide. We made the decision to not check if the link is valid (ie an entry doesn't exist for that error), because that list changes over time.

In general though, those error docs are entirely open source, and in fact we have a nice automated script in the `dotnet/docs` repo here for adding to them. We'd love any and all community effort on fleshing out the missing entries.

Separately, @cartermp do you know if dotnet/docs supports a custom catch-all route? It might be nice to redirect viewers of error codes that don't exist to some kind of call-to-action to contribute docs for that error.

**Comment by cartermp** [comment]
> do you know if dotnet/docs supports a custom catch-all route? 

Not sure, but I'd definitely create an issue.

**Comment by baronfel** [comment]
Logged an issue at dotnet/docs#25769

**Comment by Jaimeloeuf** [comment]
@baronfel and @cartermp thanks for getting back on this so quickly!

@baronfel I didnt know that these are not generated here, but thanks to your suggestion, I went to dig abit more and might have possibly found the errors in `fsharp/FsAutoComplete`. I couldn't find any references to this in Ionide so I assume these are the ones.

Here are some links and lines of code I think the issue might be at, if they are, let me know and I can go ahead to make issues on those repos instead!

- <https://github.com/fsharp/FsAutoComplete/blob/4123902d8968cd393a60ba1c0cb8006bbb2baab8/src/FsAutoComplete.BackgroundServices/Program.fs#L62>
- <https://github.com/fsharp/FsAutoComplete/blob/4123902d8968cd393a60ba1c0cb8006bbb2baab8/src/FsAutoComplete/LspHelpers.fs#L104>

Also side note, after looking through dotnet/docs I dont think the docs are from there, since they look more like the docs used for things like getting started and all, didnt really seem to find anything related to compiler error messages, but might have missed them.

**Comment by baronfel** [comment]
The docs [do live at dotnet/docs](https://github.com/dotnet/docs/tree/main/docs/fsharp/language-reference/compiler-messages/), it's just that for that specific error code there's no content there. IMO there's no error in FSAC as far as the URL is concerned, it's again just a lack of content. That's why I raised an issue on that repo about having a page-of-last-resort for this sort of situation, since the set of compiler messages can and will change with time.

**Comment by Jaimeloeuf** [comment]
@baronfel ohh I see, haha I just assumed that if there was an error code assigned, there would probably be docs for it already up 😂😅

Should I just close this issue then? Anything I can do to help I guess?

Thanks for the help anyways, appreciate it!

**Comment by baronfel** [comment]
Unfortunately there's no direct mapping between diagnostic codes as defined in this repo and reported by the compiler, and docs being written for them. There's been some talk about generating that content somehow, but nothing's really got off the ground.

_However_, if you're interested, the process for writing docs for a new diagnostic is pretty straightforward, @brettrowberry even wrote a [blog post](https://brett-rowberry.medium.com/f-compiler-messages-24da6589d796) about it about 9 months ago. I'd be happy to provide any assistance you need if you'd like to make one for fs0033!

**Comment by Jaimeloeuf** [comment]
@baronfel found the subrepo, it is this <https://github.com/dotnet/docs/tree/main/docs/fsharp/language-reference/compiler-messages> right? Wow seems like docs are quite lacking now for compiler messages, a catch all would be great since there is such a huge gap!

**Comment by Jaimeloeuf** [comment]
> Unfortunately there's no direct mapping between diagnostic codes as defined in this repo and reported by the compiler, and docs being written for them. There's been some talk about generating that content somehow, but nothing's really got off the ground.

Regarding this, is there anyway to at least generate a full toc (with all possible error codes and a simple 1 line title) from this repo? Because the current toc only seems to include codes that already have docs written for them. So perhaps something to show a full list of error codes might be good? Im not sure if this is already done somewhere or what not, but perhaps if not, you can help to point me in a direction, where I can try to contribute something to do this?

> _However_, if you're interested, the process for writing docs for a new diagnostic is pretty straightforward, @brettrowberry even wrote a [blog post](https://brett-rowberry.medium.com/f-compiler-messages-24da6589d796) about it about 9 months ago. I'd be happy to provide any assistance you need if you'd like to make one for fs0033!

Thanks! I will look into the article and its references first. To me I guess I am not so interested in fs0033 specifically, I just mainly felt that the lack of docs esp regarding compiler messages was abit weird and jarring, thus raised this issue.

**Comment by Jaimeloeuf** [comment]
@baronfel I just skimmed through the blog post and saw your answer here <https://github.com/dotnet/docs/issues/16177#issuecomment-724426546>, does it makes sense then to generate the toc with all possible error codes using <https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSComp.txt> ?

I see that items in FSComp.txt is indeed manually updated every time, so perhaps a CI/CD pipeline to generate a new TOC everytime this gets updated and make a PR on the dotnet/docs repo?

Would love to help on this, but this will probably need help from the team since it involves some CI stuff... if needed I can take a stab at creating a script to parse the file first.

**Comment by dsyme** [comment]
I'll close this issue, could you reopen in dotnet/docs or FsAutoComplete please? Thank you

**Comment by Jaimeloeuf** [comment]
@dsyme understood, thanks

**Comment by baronfel** [comment]
@Jaimeloeuf FSComp.txt is a partial list of the diagnostics that the compiler can issue, the remainder can be seen in [this explicit match expression](https://github.com/dotnet/fsharp/blob/main/src/fsharp/CompilerDiagnostics.fs#L219-L351). So between the two sources it might be possible to auto-generate some amount of this, at the very least the catch-all 'sorry, we don't have content for this error' page described in a [comment on the issue I raised](https://github.com/dotnet/docs/pull/20069)
