### ISSUE TITLE
Visual Studio F# Interactive gives red-squigglies if you reference an extension method on `MemberInfo`

### ISSUE THREAD

**Issue by Smaug123** [dotnet/fsharp#12031]
F# Interactive Intellisense in Visual Studio complains if you try and open a namespace containing an extension method on `System.Reflection.MemberInfo`.

**Repro steps**

Either unzip the attached [Program.zip](https://github.com/dotnet/fsharp/files/7040236/Program.zip), or create a C# project which adds an extension method to `System.Reflection.MemberInfo`.

Then:
1. Set Visual Studio to use .NET Core FSI. (I believe this step is optional.)
2. Build the C# project.
3. `#I` the build output, and `#r` the DLL containing the extension method. (In the zip file, this is `Script.fsx`.
4. `open` the namespace of the C# project.

**Expected behavior**

The FSX file parses cleanly and can be executed in Visual Studio.

**Actual behavior**

The FSX file can indeed be executed, but it has a red squiggly on the namespace open (FS1109: A reference to the type 'System.Reflection.MemberInfo' in assembly 'System.Runtime' was found, but the type could not be found in that assembly). Additionally the following lines appear in the error list:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	FS0193	The module/namespace 'System.Reflection' from compilation unit 'System.Runtime' did not contain the namespace, module or type 'MemberInfo'	F# Miscellaneous Files	C:\Users\Patrick\source\repos\Repro\Script.fsx	1	Active
Error	FS1109	A reference to the type 'System.Reflection.MemberInfo' in assembly 'System.Runtime' was found, but the type could not be found in that assembly	F# Miscellaneous Files	C:\Users\Patrick\source\repos\Repro\Script.fsx	3	Active
```

**Known workarounds**

* Change the extension method to an ordinary static method.
* Use Rider, which does not suffer the problem as of 2021.1.2 (but which I believe used to show the problem in one of the 2020 versions).

**Related information**

* Operating system: observed on Windows only, but I haven't tried to reproduce in VS for Mac.
* .NET Runtime: observed in .NET 5 and .NET 6.
* Editing Tools: Visual Studio 16.10.4 with Visual F# Tools 16.10.0-beta.21262.7+1b23bbeda..., or Visual Studio 16.9.6 with Visual F# Tools 16.9.0-beta.21102.9+7ce7132...

**Comment by dsyme** [comment]
I checked and this doesn't repro in latest VS2022
