### ISSUE TITLE
Missing from contributor list

### ISSUE THREAD

**Issue by jBarrineau** [dotnet/fsharp#12058]
Hello,

I fixed some documentation and made a pull request which was merged.  I don't see myself on the contributor list.

If there is a minimum bar for contributions, and my PR meets it, could I please be added to the contributor list?

https://github.com/dotnet/fsharp/pull/11447

Thanks!

**Comment by jBarrineau** [comment]
No worries.

**Comment by dsyme** [comment]
We will make sure you're there :))

**Comment by vzarytovskii** [comment]
> @vzarytovskii It shows top-100, sorting them by commits count.

Oh, I see, thanks. Good to know.

**Comment by jBarrineau** [comment]
@vzarytovskii thanks for investigating.  The dotnet/fsharp team has much bigger fish to fry, plus I am now seeing "Contributor" next to my name on this issue so I think things are OK now.  It's very possible I had something wrong with my setup when I first contributed, as I'm new to open source.

I'm closing the issue since I am identified as a Contributer now.  I really do appreciate everyone's time and I hope to contribute to fsharp in the future.
