### ISSUE TITLE
CI fails with "Unknown framework version" errors

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#12059]
https://dev.azure.com/dnceng/public/_build/results?buildId=1327921&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=4607427e-2085-572d-4b25-975ef0413f8f&l=2397

<img width="967" alt="Screenshot 2021-08-30 at 14 49 03" src="https://user-images.githubusercontent.com/3923587/131334562-1a802748-4244-4d1e-8c73-3077f8531282.png">

**Comment by vzarytovskii** [comment]
> https://dev.azure.com/dnceng/public/_build/results?buildId=1327921&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=4607427e-2085-572d-4b25-975ef0413f8f&l=2397
> 
> 
> 
> <img width="967" alt="Screenshot 2021-08-30 at 14 49 03" src="https://user-images.githubusercontent.com/3923587/131334562-1a802748-4244-4d1e-8c73-3077f8531282.png">
> 
> 
It's usually caused by failing tests, not sure why the runner is failing with this error.

Here's the actual error:
```

Failed Active pattern 01 - Named args [1 s]
  Error Message:
     Expected: ["(5,2--5,17): Foo is an active pattern and cannot be treated as a discriminated union case with named fields."]
Actual: ["(5,2--5,16): Foo is an active pattern and cannot be treated as a discriminated union case with named fields."]
  Expected and actual are both <Microsoft.FSharp.Collections.FSharpList`1[System.String]>

  Stack Trace:
     at FSharp.Compiler.Service.Tests.PatternMatchCompilationTests.Active pattern 01 - Named args() in /home/vsts/work/1/s/tests/service/PatternMatchCompilationTests.fs:line 265

```

**Comment by auduchinok** [comment]
@vzarytovskii OK, I see, thanks! Will continue investigating the test.

**Comment by vzarytovskii** [comment]
I will play a bit with runner to see why it isn't happy with the "framework version" when test fails
