### ISSUE TITLE
Support `DefaultInterpolatedStringHandler`

### ISSUE THREAD

**Issue by xperiandri** [dotnet/fsharp#12069]
Will F# support the same feature?
https://devblogs.microsoft.com/dotnet/string-interpolation-in-c-10-and-net-6/

**Comment by vzarytovskii** [comment]
I guess this should rather be in https://github.com/fsharp/fslang-suggestions/
Will also probably need an RFC if approved. 
Cc @dsyme.

**Comment by dsyme** [comment]
Yes, it should be moved there.  We need to think it over - it's a lot of bespoke engineering for strings alone and I don't necessarily feel it's right for F#, but let's think about it.

**Comment by vzarytovskii** [comment]
I don't have permissions to move issues there. @cartermp maybe you do?

**Comment by dsyme** [comment]
Unfortunately it seems transfers can only happen within in org, I'm not sure why

**Comment by vzarytovskii** [comment]
> Unfortunately it seems transfers can only happen within in org, I'm not sure why

Oh yeah, that's right. Let me create a new issue there.

**Comment by vzarytovskii** [comment]
Closing in favour of https://github.com/fsharp/fslang-suggestions/issues/1108
