### ISSUE TITLE
Implement tooltips for keywords

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#12062]
Hovering over F# keywords in Visual Studio and VS Code does not give a tooltip.

This is one of our best ways to help educate newcomers about the correct use of the F# language, e.g. both with a good tooltip and also aka.ms links to good articles in the .NET documentation (e.g. the main article on pattern matching for the `match` keyword)

Some basic information about keywords is already available in `KeywordsWithDescription` but we can give more information that this

**Comment by baronfel** [comment]
We do support keyword tooltips in FSAC/Ionide:

![image](https://user-images.githubusercontent.com/573979/131412918-1a42ad1f-d316-4eba-8887-5ea97cfb965b.png)

We take the list of keywords and descriptions to power this, so any enhancements here will seamlessly flow down. I'm all for it!

**Comment by dsyme** [comment]
OK thanks, yes I didn't get that when I tried in Ionide but I think the project context wasn't loaded correctly

**Comment by dsyme** [comment]
@vzarytovskii @KathleenDollard Reviewing things, this seems like really low hanging fruit for improving VS

**Comment by T-Gro** [comment]
Proposal: Renders the keyword itself (if the configured coloring for keywords), and below it the longer description as text.
I am checking the keyword descriptions, but so far they seem to be fit.

<img width="446" alt="image" src="https://user-images.githubusercontent.com/46543583/191696879-831f4893-4f38-4251-8656-241e07217eed.png">

**Comment by psfinaki** [comment]
Looks good. What about the icon? Do we need it?

**Comment by T-Gro** [comment]
The icon was not appropriate, you are right and I am not a person with a good visual judgement.

This one makes it look more like a keyword:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/46543583/191742119-01e97e38-00f7-49eb-98fe-2cbbc74ecb0e.png">
