### ISSUE TITLE
F# Error When Adding suggested open is added on top of namespace and this breakes compilation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12083]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F-Error-When-Adding-suggested-open-is-a/1445740)._

---
[severity:It's more difficult to complete my work]
The suggestion for adding the open breakes the compilation as open is added on top, before naspace declaration.

![Be0fd1685dcd74debbc06120d1cb18200637588307375219896_20210609-121812-image (1)](https://user-images.githubusercontent.com/7204669/131725279-bb968f44-2c20-483b-a136-0f785df44a97.png)

![B97ca4cb923f541e2b7eb3d065d49496d637588307481538076_20210609-121908-image](https://user-images.githubusercontent.com/7204669/131725316-5098820f-b1a3-4688-972a-53efb01e2115.png)
---
#### Feedback Bot on 6/9/2021, 07:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by vzarytovskii** [comment]
This only reproduces when namespace in on the 1st line of the document, because of this:
https://github.com/dotnet/fsharp/blob/76e65ac5b724fe23bcb47ae90c868c724df20714/src/fsharp/service/ServiceParsedInputOps.fs#L1665-L1677

I'm not entirely sure why this is the logic, maybe @cartermp remembers?

**Comment by cartermp** [comment]
I didn't write that code so I'm not sure. I know that it was a bit tricky to debug though. Shouldn't the code also try to insert an `open` where other `open`s already are? So isn't the case here that it's (a) a namespace decl up top, and (2) no `open` decls as well?

If so I also think this should really be bumped down in priority, and it's also not a regression

**Comment by vzarytovskii** [comment]
> I didn't write that code so I'm not sure. I know that it was a bit tricky to debug though. Shouldn't the code also try to insert an `open` where other `open`s already are? So isn't the case here that it's (a) a namespace decl up top, and (2) no `open` decls as well?
> 
> If so I also think this should really be bumped down in priority, and it's also not a regression

It first tries to determine where to insert the open, for that it either
 a. If it's _not_ the 1st line, then it will try to find the `namespace` decl in the `0..currentLine` and return the line for `open` after it.
 b. if it's 1st line it will just return `1` (which I think is incorrect).

I have added the check if we are on the first line - if it's the `namespace` line, return next one, otherwise, return `1` (as it was before).

**Comment by baronfel** [comment]
Aha! I think this caused some regressions for opens in FSAC as well during our FCS 41 update!

**Comment by vzarytovskii** [comment]
It does try to align with existing opens, later on, after it calculates the line to insert to first time.

**Comment by vzarytovskii** [comment]
This is my version of the fix: https://github.com/dotnet/fsharp/pull/12443/files. Probably could be simplified with removing the codnition alltogether.
I've tested it on:
- namespace on 1st line
- namespace is not on 1st line
- with existing opens
- without opens
- without namespace.
