### ISSUE TITLE
F# type initialization exception (JIT Compiler encountered an internal limitation) when debugging code with type annotations (let x = 1.0<_>)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12080]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F-type-initialization-exception-JIT-Co/1491462)._

---
[severity:I'm unable to use this version]
Debugging tests in an F# project (run through the VS test runner and NUnit nuget package) causes an exception in the JIT compiler. This is a brand new issue after since I updated VS2019 yesterday.

`let suctionGauge= 0. <_>`

leads to

System.TypeInitializationException: 'The type initializer for 'suctionGauge@287' threw an exception.'
InvalidProgramException: JIT Compiler encountered an internal limitation.

---
#### Feedback Bot on 8/1/2021, 07:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Kevin Ransom [MSFT] on 8/4/2021, 00:04 PM: 

<p>Aaron,</p>
<p>Thank you for providing details of this issue.  I just tried the repro on an older build of VisualStudio: 2019.4.24 and it produced the same result</p>
<p><img src="https://aka.ms/dc/image?name=B0cf372f317da477dae528d25a4001cbb637636995040425005_20210804-114504-image.png&amp;tid=0cf372f317da477dae528d25a4001cbb637636995040425005" alt="image.png"></p>
<p>so, I don’t think it’s a regression.  Can you please confirm that you were able to debug through that code in an earlier version.</p>
<p>There is still an issue here and we will manage it at github, to involve the wider community:  <a target='_blank' href="https://github.com/dotnet/fsharp/issues/11915">https://github.com/dotnet/fsharp/issues/11915</a></p>
<p>Thanks</p>
<p>Kevin</p>

---
### Original Solutions
(no solutions)

**Comment by dsyme** [comment]
This was fixed recently in https://github.com/dotnet/fsharp/pull/11349
