### ISSUE TITLE
F# provided types (using swagger provider) not building in referenced project in IDE

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12082]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F-provided-types-using-swagger-provide/1449076)._

---

![Bfd30f7d7b22c426ea41ebfc43a39939d637592550482012643_20210614-101049-image](https://user-images.githubusercontent.com/7204669/131725550-d4c551aa-ae34-4b8e-9827-5e8b2c8c5cd9.png)

Build of dependent project is successful, and project is referenced

![B2c1016102d0b424e96d3508f17cc6849637592550764874773_20210614-101117-image](https://user-images.githubusercontent.com/7204669/131725418-feaf1d9d-5a2a-407c-99b6-2c3af4811a36.png)

![B65fc33fda0fb49f98422503b1ccb3d95637592552406894331_20210614-101401-image](https://user-images.githubusercontent.com/7204669/131725473-19b80352-1a9c-4385-83aa-b0b15aa02e17.png)

---
#### Feedback Bot on 6/14/2021, 10:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by KevinRansom** [comment]
We need a more complete repro, before we can dig into this more.
