### ISSUE TITLE
.NET 5 Debug in interactive: breakpoints not being hit

### ISSUE THREAD

**Issue by MaxWilson** [dotnet/fsharp#12084]
[.NET 5] VS 2019 "Debug in interactive" F# not stopping on breakpoints.

**Repro steps**

1.) Open Visual Studio 2019, Version 16.11.2

2.) Open an .fsx file, e.g. ScriptDebugging.fsx:

```
let x() = 5
x()
```

3.) Ensure that Debug | Options | F# Tools | F# Interactive | Enable script debugging is set to true.

![image](https://user-images.githubusercontent.com/6829565/131726844-34d9779b-1727-4008-8fa1-d0e5bb47eae1.png)

4.) Set a breakpoint.

5.) Highlight code, right-click and Debug In Interactive.

![image](https://user-images.githubusercontent.com/6829565/131727506-a48513a6-7e60-48aa-b7ff-35e3b350933d.png)

**Expected behavior**

Execution stops on breakpoint.

**Actual behavior**

Breakpoint is not hit, is marked as disabled, "No symbols have been loaded for this document". Code runs to completion and outputs results (in this case, 5).

![image](https://user-images.githubusercontent.com/6829565/131727765-1c1e1e67-8358-4e80-ad05-9aedd40555b6.png)

**Note:** explicitly calling System.Diagnostics.Debugger.Break() also does not work.

**Known workarounds**

1.) Use a different debugging method, instead of the debugger, such as executing one function at a time.
2.) Create a console project, copy your code into it, and run it normally instead of via FSI interactive.
3.) Set Use .NET Core Scripting = false.

**Related information**

Visual Studio 2019, Version 16.11.2
.NET Core 5
Windows

**Comment by vzarytovskii** [comment]
> I was under the impression that script debugging was not supported in .net core and .net 5? Maybe that's why.

@KevinRansom so you have more details on that perhaps?

**Comment by MaxWilson** [comment]
> I was under the impression that script debugging was not supported in .net core and .net 5? Maybe that's why.

Ah, you are right. I'll add that as another workaround: 3.) Set Use .NET Core Scripting = false.

**Comment by heronbpv** [comment]
> Ah, you are right. I'll add that as another workaround: 3.) Set Use .NET Core Scripting = false.

Damn, I wish I wasn't. Developing and debugging forms in a script was very, very nice.
I remember we lost this capability because of the removal of thread abort from the runtime. Wonder were is the implementation alternative that was being discussed back then, something to do with a debug API, I think.
In the meanwhile, see if you can use .NET 4.8, I believe the desktop FSI still has the capability on VS 2019.

**Comment by MaxWilson** [comment]
Maybe a good solution in this case would be to just change the VS dialog so you can't set both Use .NET Core Scripting and Enable Script Debugging at the same time.

I've already solved my particular issue that I was debugging (by running the code in a separate project) but I will keep the .NET Framework workaround in mind next time I have a complex bug that's hard to reproduce standalone.

**Comment by dsyme** [comment]
Closing as duplicated of #5457
