### ISSUE TITLE
XML Doc for Char.TryParse not being found

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#12098]
XML doc being found for other System.Char methods but not TryParse. I'd expect a problem with byrefs in the XML Doc lookup sig

![image](https://user-images.githubusercontent.com/7204669/131912653-4cb011b1-a0da-455f-998a-7fe743cb8702.png)

**Comment by inosik** [comment]
Looks like a duplicate of #6310.

**Comment by dsyme** [comment]
Fixed in #12072
