### ISSUE TITLE
F# Console Template on preview 4 has additional whitespace at the top of the file

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#12104]
Note that C# comment for the console app starts on line 1, whereas F# starts on Line 3.

![image](https://user-images.githubusercontent.com/5175830/132062528-19dc09ca-1a0f-424a-ab76-d879c4b46089.png)

Expected:
Template text to start on line 1

**Comment by dsyme** [comment]
This must be my habit.  I guess I'm always expecting to add a copyright at the top of the file

**Comment by dsyme** [comment]
Thsi was fixed
