### ISSUE TITLE
F# interactive for .net framework in VS2019 fails with StackOverflow

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#12111]
```fsharp
#r "nuget: rtmidi.core"
```

Running with dotnet framework, this crashes with 

> Microsoft (R) F# Interactive version 11.4.2.0 for F# 5.0
> Copyright (c) Microsoft Corporation. All Rights Reserved.
> 
> For help type #help;;
> 
> > 
> Process is terminated due to StackOverflowException.
> Session termination detected.

It somehow works with dotnet core runtime.

Maybe related #12075

Environment: VS2019 Version 16.10.0, windows 11.

**Comment by markpattison** [comment]
Possibly the same issue as #12033

**Comment by KevinRansom** [comment]
Fixed
