### ISSUE TITLE
F# Interactive displays enums unnecessarily verbosely.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/fsharp#12127]
On .NET 6 SDK Preview 7, .NET SDK 5.0.400 and .NET Core SDK 3.1.412, writing something like

```
System.Char.GetUnicodeCategory 'a';;
```

will display

```
val it : System.Globalization.UnicodeCategory = LowercaseLetter {value__ = 1;}
```

while it could display

```
val it : System.Globalization.UnicodeCategory = LowercaseLetter
```

I persume it is a side-effect of #5002. It does not happen when using `sprintf "%A"`.

**Comment by smoothdeveloper** [comment]
I personally find the additional information useful, maybe it could pretty printed while retaining the actual value, keeping how `it` behaves when displayed in FSI versus what "%A" does.

**Comment by dsyme** [comment]
This should be fixed, we don't intend to show `value__`

**Comment by joshuapassos** [comment]
@dsyme, if I change the pattern matching by adding the enum type check, can maybe I resolve the problem?

https://github.com/dotnet/fsharp/blob/c50b294db96d2400842d6537fe82ea4ce7e1790d/src/fsharp/utils/sformat.fs#L1247-L1272


```fsharp
  | :? Enum -> 
    countNodes 1
    Layout.objL obj
```

**Comment by dsyme** [comment]
Yes! :)
