### ISSUE TITLE
Unresolved symbols in FCS solution

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#12142]
This line now produces an error (despite the project actually building fine):
https://github.com/dotnet/fsharp/blob/4ee281652c6c3905c00e3e7d46dfd6ee117b13dd/src/fsharp/absil/illib.fs#L1157

It probably happens due to a recent `Map` change in FSharp.Core. I thought we were trying to be able to use the released FSharp.Core package in FCS, so this error is unexpected. It's also interesting why the project builds (i.e. what FSharp.Core it actually uses?) and why the tooling behaves differently?

Rider:
<img width="816" alt="Screenshot 2021-09-13 at 17 15 59" src="https://user-images.githubusercontent.com/3923587/133100230-4e28a7fd-6e35-41b7-a926-cb2c292f214e.png">

Visual Studio 2019:
<img width="882" alt="Screenshot 2021-09-13 at 17 15 37" src="https://user-images.githubusercontent.com/3923587/133100238-3701d5a2-874c-4786-9e50-276659260886.png">

**Comment by vzarytovskii** [comment]
@KevinRansom cc

**Comment by auduchinok** [comment]
@dsyme @KevinRansom What FSharp.Core version these changes are going to land to? Will it be 5.0.3 or 6.0?
When FSharp.Core 5.0.3 is going to be released?

Right now working on FCS is much harder due to these errors. Also, we'd prefer to keep using stable FSharp.Core versions and update when needed (there's some additional work we have to do update the bundled FSharp.Core).

**Comment by dsyme** [comment]
It looks like
```
  <ItemGroup Condition="'$(FSHARPCORE_USE_PACKAGE)' == 'true'">
    <PackageReference Include="FSharp.Core" Version="$(FSharpCorePreviewPackageVersion)" />
  </ItemGroup>
```
should be
```
  <ItemGroup Condition="'$(FSHARPCORE_USE_PACKAGE)' == 'true'">
    <PackageReference Include="FSharp.Core" Version="$(FSharpCoreShippedPackageVersionProperty)" />
  </ItemGroup>
```

**Comment by dsyme** [comment]
I mean, if we're using a package it should be a shipped package.

**Comment by auduchinok** [comment]
@dsyme Could you reopen it?

**Comment by vzarytovskii** [comment]
It seems that #12149 didn't fix it, going to reopen it.

**Comment by dsyme** [comment]
@auduchinok Could you give me steps to repro this?  I open `service/FSharp.Compiler.Service.sln` in VS2022 preview and the errors aren't appearing.

There is however a warning marker on this 5.0.2 FSharp.Core references which I don't understand (and can't work out what warning that is referring to)

![image](https://user-images.githubusercontent.com/7204669/134324808-786a99ac-08a2-46e8-9fd4-ab008e95eb23.png)

**Comment by auduchinok** [comment]
> I open service/FSharp.Compiler.Service.sln in VS2022 preview and the errors aren't appearing.

They do appear for me in VS2019 and Rider 2021.3 preview. I've reproduced it roughly like this:

```
cd fsharp
git clean -dfx
./build.cmd
```

and then open the FCS solution in an IDE.

What I've managed to discover is the conditional FSharp.Core reference is being ignored completely here, and another one transitively comes from FSharp.DependencyManager.Nuget project, where it's not conditional and always references the project output. I suspect the warning you see could be related here. The workaround that helps me is changing the reference in that project.

**Comment by dsyme** [comment]
> What I've managed to discover is the conditional FSharp.Core reference is being ignored completely here, and another one transitively comes from FSharp.DependencyManager.Nuget project, where it's not conditional and always references the project output.

I see, yes, that makes sense, we should adjust that too
