### ISSUE TITLE
dotnet 6.0 rc1 breaks #r "nuget: .."

### ISSUE THREAD

**Issue by thinkbeforecoding** [dotnet/fsharp#12152]
Please provide a succinct description of the issue.

Once updated to dotnet 6.0 rc1, scripts using #r "nuget: ..." break with error:
```
error NU1102: Unable to find package FSharp.Core with version (>= 6.0.0)
```

Provide the steps required to reproduce the problem:

1. Create a test.fsx script
2. start it with  ```#r "nuget: FSharp.Data"```

execute this line. boom.

**Expected behavior**

It should load the nuget without error

**Actual behavior**

Loading the nuget fails with the error:
```
error NU1102: Unable to find package FSharp.Core with version (>= 6.0.0)
```

**Known workarounds**

Load nuget from disk cache (but you have to load all dependencies manually too).

**Related information**

it was working on dotnet 6.0-preview7

* windows 11 beta
* dotnet 6.0.100-rc1
* Visual Studio 2019/2022 preview 4/VSCode + Ionide/fsi

**Comment by thinkbeforecoding** [comment]
Other way to reproduce.

1. Open a command line
2. run 'dotnet fsi'
3. type '#r "nuget: FSharp.Data";;

the error happens

**Comment by vzarytovskii** [comment]
FSharp.Core 6 is not published to nuget yet
cc @brettfo @KevinRansom

**Comment by thinkbeforecoding** [comment]
The same error happen on linux (wsl2/ubuntu)
@vzarytovskii , Yes it seems the rc1 is referenceing a v6.0.0 of FSharp.Core that is no publicly deployed on nuget.

**Comment by vzarytovskii** [comment]
FSharp.Core 6.0 has been uploaded to nuget: https://www.nuget.org/packages/FSharp.Core/
Closing the issue
