### ISSUE TITLE
The solution explorer displays some files out of order for F# projects.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12155]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-solution-explorer-displays-some-file/1494531)._

---
The solution explorer displays some files out of order for F# projects.
For example, this ordering in the *.fsproj file will not fully be respected by the solution explorer:

```
  <ItemGroup>
    <Compile Include="A\Library.fs" />
    <Compile Include="A.fs" />
    <Compile Include="B\C\Library.fs" />
    <Compile Include="B.fs" />
    <Compile Include="C\Library.fs" />
    <Compile Include="C.fs" />
  </ItemGroup>
```

The file "B.fs" will be displayed after the directory "C" in this case. See the image.

! [vs.jpg] (https://aka.ms/dc/image?name=Bdee0a2637253437b9dcf412822b9f3dc637636737557264392_vs.jpg&tid=dee0a2637253437b9dcf412822b9f3dc637636737557264392)

As in this case, this happens when you have files and directories with the same name and names repeat in other nested directories. The display order is restored to normal if you rename the nested "B\C" directory to any distinct name, for example to "B\D".

---
#### Feedback Bot on 8/4/2021, 10:46 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by albertwoo** [comment]
I also have these kind of issue in VS:
```
other fs folder and files
workflow\domain1\foo1.fs
ui\domain1\foo2.fs
```

**Comment by vzarytovskii** [comment]
I was unable to reproduce it in latest VS. If it's still the case, it needs to be reported via VS feedback and routed to CPS/Solution explorer team, since we don't control it.
