### ISSUE TITLE
Sometimes gets stuck on solution loading

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12159]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Sometimes-gets-stuck-on-solution-loading/1515210)._

---
Sometimes Visual Studio 2022 3.1 gets stuck on solution loading.
Solution mostly contains F# projects.

! [image.png] (https://aka.ms/dc/image?name=Be09f96c7cbdb4a0488f5446fb7eeeb42637655903884190011_20210826-115948-image.png&tid=e09f96c7cbdb4a0488f5446fb7eeeb42637655903884190011)

---
#### Feedback Bot on 8/26/2021, 10:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by TIHan** [comment]
In preview 4, this seems to be resolved. Fix was probably https://github.com/dotnet/fsharp/pull/11805

**Comment by 0-gravity** [comment]
Confirm. In preview 4 is not observed.
