### ISSUE TITLE
F# Project Fails to Build in Visual Studio 2022 - System.Data.SqlClient is not supported on this platform

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12160]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F-Project-Fails-to-Build-in-Visual-Stud/1518584)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.11.2]
**Version**
Microsoft Visual Studio Community 2022 Preview (64-bit)
Version 17.0.0 Preview 3.1

**Steps**
1. Create an F# Console Application (I used .NET 5)
2. Install the "SQLProvider" and "System.Data.SqlClient" Nuget Packageds
3. Instantiate a type of the SqlDataProvider with an active MS SQL Server Connection
4. Attempt to build the project
```fsharp
open System
open FSharp.Data
open FSharp.Data.Sql

// NOTE: the below is line 20 an onwards in my project file
type sql = SqlDataProvider<
            ConnectionString = someConnectionString,
            DatabaseVendor = Common.DatabaseProviderTypes.MSSQLSERVER,
            IndividualsAmount = 1000,
            UseOptionTypes = true>

let ctx = sql. GetDataContext()
```

**Expected**
- The project builds successfully

**Actual**
- I receive the following error message

```
1>Program.fs(20,12): error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: System.Data.SqlClient is not supported on this platform.
```

**Notes**
I would assume this is an issue with a NuGet package or a configuration issue. However, this project builds as expected and can be debugged in Visual Studio 2019. However, in Visual Studio 2022, this project does not build for the errors above. What is further strange is that in Visual Studio 2022, I can proper Intellisense from the type provider, and there are no seen issues in the editor itself.

---
#### Feedback Bot on 9/1/2021, 02:05 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by brettfo** [comment]
VS 2019 used the framework (net472) compiler by default and VS 2022 now uses the SDK (net5.0/net6.0) compiler.  The issue is that the `System.Data.SqlClient` package was built incorrectly (and by extension, the `SQLProvider` package by taking that dependency) and that assembly isn't loadable by the runtime.

To force Visual Studio to use the older framework compiler, add the property `FSharpPreferNetFrameworkTools` to the project file like so:

``` xml
...
<PropertyGroup>
  <TargetFramework>net5.0</TargetFramework>
  <FSharpPreferNetFrameworkTools>true</FSharpPreferNetFrameworkTools><!-- this is the line to add -->
</PropertyGroup>
...
```

**Comment by dsyme** [comment]
@brettfo What will be required after the recent updates?

**Comment by KevinRansom** [comment]
I believe this is fixed, needs verification.
Hypothesis:  Doesn't build with coreclr compiler, because typeprovider is not coreclr.

**Comment by dsyme** [comment]
> Hypothesis: Doesn't build with coreclr compiler, because typeprovider is not coreclr.

I'm sure this is the problem
