### ISSUE TITLE
Can't implementing a generic interface define by C# where has special constraints with variance.

### ISSUE THREAD

**Issue by jing8956** [dotnet/fsharp#12206]
(google translate)
I am writing a [jellyfin](https://github.com/jellyfin/jellyfin) plugin in F#. Translate the sample code from C# to F#. 
The number of lines of code is reduced by 50%, and the logic is clearer. F# is the best language in .Net. ❤
But when I implemented `MediaBrowser.Controller.Providers.IRemoteMetadataProvider<'TItemType,'TLookupInfoType>`, a compilation error FS0001 occurred. 
I simplified the code and found that I cannot solve this problem directly.

**Repro steps**
1. Create a C# class library and compile this:
``` csharp
public class BaseItem : IGetInfo<BaseItemInfo> { }
public class BaseItemInfo { }

public class ItemA : BaseItem, IGetInfo<ItemInfoA> { }
public class ItemInfoA : BaseItemInfo { }

public interface IGetInfo<out T> where T : BaseItemInfo { }
public interface IProvider<T, in U> 
    where T : BaseItem, IGetInfo<U> 
    where U : BaseItemInfo { }
```

**Expected behavior**

2. If Implementing IProvider<ItemA, ItemInfoA> by C#,  the following code will compile succeed.
``` csharp
public class ImplementProvider : IProvider<ItemA, ItemInfoA> { }
```

**Actual behavior**

3. But when using F#, a compilation error occurred:
``` fsharp
type ImplementProvider() =
    interface IProvider<ItemA, ItemInfoA>
```
```
error FS0001: This expression was expected to have type    'BaseItemInfo'    but here has type    'ItemInfoA' 
error FS0909: All implemented interfaces should be declared on the initial declaration of the type 
```
![image](https://user-images.githubusercontent.com/20148769/135830940-2ab97577-9d85-45dc-8e8d-96fd9a218f07.png)

**Known workarounds**

I will try to implement IProvider<ItemA, BaseItemInfo> and explicitly convert the member parameter BaseItemInfo to ItemInfoA, and then test whether it works. It will most likely fail if jellyfin has a code that specifies the use of IProvider<ItemA, ItemInfoA>.

**Related information**

4. I tried define the IProvider<T, U> by F#. A warning FS0064 and error FS0663 occurred
``` fsharp
type IProvider<'T, 'U 
    when 'T:> BaseItem and 'T :> IGetInfo<'U>
    and 'U:> BaseItemInfo> = interface end
```
```
warning FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'U has been constrained to be type 'BaseItemInfo'.
error FS0663: This type parameter has been used in a way that constrains it to always be 'BaseItemInfo'.
```
![image](https://user-images.githubusercontent.com/20148769/135834149-f1da14e4-76a2-42bf-84c4-1392d0de5b8d.png)

It may be that the F# compiler adds covariance and contravariance to the 'U at the same time, so a derived class of BaseItemInfo cannot be passed into 'U. 

5. Compilation succeeded after removing BaseItem. I don't know the reason.
``` csharp
public class BaseItemInfo { }

public class ItemA : IGetInfo<ItemInfoA> { }
public class ItemInfoA : BaseItemInfo { }

public interface IGetInfo<out T> where T : BaseItemInfo { }
public interface IProvider<T, in U> 
    where T : IGetInfo<U> 
    where U : BaseItemInfo { }
```

* Operating system: Windows 10 Pro 21H1 (19043.1237)
* .NET Runtime kind: .NET 5.0.401
* Editing Tools: Microsoft Visual Studio Community 2019 Version 16.11.3

**Comment by vzarytovskii** [comment]
Related: https://github.com/fsharp/fslang-suggestions/issues/162

**Comment by dsyme** [comment]
The language suggestion covers this
