### ISSUE TITLE
October 2021 work list

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/fsharp#12219]
- [x] @vzarytovskii #12011
- [x] @TIHan #12156
- [x] @KevinRansom #12033
- [ ] @KevinRansom #12158
- [x] @TIHan, @vzarytovskii The path to LSP and Analyzers - #11588
- [ ] @dsyme with community #12124 
- [ ] @vzarytovskii come up with plan (and docs) for performance testing for the compiler and runtime. What kind of tests do we need - we want to test compiler perf as well as runtime (GC, JIT) when we make changes to compiler.
- [ ] @KevinRansom is going to look at the current state of the VS prototype for CodeLensAnnotations (see below)

In longer range planning, we also looked at the big bucket items that appear to be dropping out of the the "Simplifying F# On Ramp" work by @KathleenDollard and @dsyme - these are in no priority order:

* [ ] Debug - The Debug experience (opens, autos, debug engine, E&C, Hot Reload)
* [ ] CodeLensAnnotations - inline automatic type annotations done like Ionide - get the prototype into shape and ready for wider adoption
* [ ] Diagnostics - Focused work, starting with "supplying the wrong number and/or currying/tupling of parameters"
* [ ] Fantomas - Come up with a plan to incorporate into Fantomas into VS tools as our implementation of Ctrl-K+Ctrl-F formatting
* [ ] FsLint - Come up with a plan to incorporate FsLint into VS tools to utilise some of its soft advice/diagnostics

**Comment by dsyme** [comment]
Closing old planning issue
