### ISSUE TITLE
Add support for configurable hashing for source checksums

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#1223]
Internal thread:

From: Mike Lai 
Sent: Monday, May 23, 2016 3:44 PM
To: Kevin Ransom Kevin.Ransom@microsoft.com
Cc: Michael Fanning (DEVDIV) Michael.Fanning@microsoft.com; Tomas Matousek Tomas.Matousek@microsoft.com
Subject: RE: F# Compiler (fsc.exe)

I see, Kevin.  Would you mind to consider our request to make SHA256 as one of available sections, please?

All the following compilers support SHA256 today. 

Thanks
Mike

•             cl.exe /ZH:SHA_256 
•             ml.exe /ZH:SHA_256 
•             ml64.exe /ZH:SHA_256 
•             armasm.exe -gh:SHA_256 
•             armasm64.exe -gh:SHA_256 
•             csc.exe /checksumalgorithm:SHA256

From: Kevin Ransom 
Sent: Monday, May 23, 2016 3:40 PM
To: Mike Lai mikelai@microsoft.com
Cc: Michael Fanning (DEVDIV) Michael.Fanning@microsoft.com; Tomas Matousek Tomas.Matousek@microsoft.com
Subject: Re: F# Compiler (fsc.exe)

Not selectable  and  MD5

https://github.com/Microsoft/visualfsharp/blob/master/src/absil/ilwritepdb.fs#L126

Kevin
From: Mike Lai mikelai@microsoft.com
Date: Monday, May 23, 2016 at 3:30 PM
To: Kevin Ransom Kevin.Ransom@microsoft.com
Cc: "Michael Fanning (DEVDIV)" Michael.Fanning@microsoft.com, Tomas Matousek Tomas.Matousek@microsoft.com
Subject: RE: F# Compiler (fsc.exe)

Hi Kevin --  It is about the hashes of compiled source files being written by the compiler to the pdb files?  

What kind (SHA1 or SHA256) of hashes does the F# Compiler (fsc.exe) put in the pdb files ? 

CSC.exe can put either based on the “/checksumalgorithm:<alg>” switch.  I am wondering if fsc.exe can support the same please? 

Thanks 

Mike 

From: Kevin Ransom 
Sent: Monday, May 23, 2016 3:26 PM
To: Mike Lai mikelai@microsoft.com
Cc: Michael Fanning (DEVDIV) Michael.Fanning@microsoft.com; Tomas Matousek Tomas.Matousek@microsoft.com
Subject: Re: F# Compiler (fsc.exe)

Hey Mike,

Can you let me know what this is about?

Thanks

Kevin

From: Mike Lai mikelai@microsoft.com
Date: Monday, May 23, 2016 at 2:10 PM
To: Kevin Ransom Kevin.Ransom@microsoft.com
Cc: "Michael Fanning (DEVDIV)" Michael.Fanning@microsoft.com, Tomas Matousek Tomas.Matousek@microsoft.com
Subject: RE: F# Compiler (fsc.exe) 

Thanks Tomas for the introduction!  Hi Kevin – please find enclosed the background information on why we are driving this.    Please feel free to let me know if you have additional questions. 

Thanks
Mike

From: Tomas Matousek 
Sent: Monday, May 23, 2016 1:56 PM
To: Kevin Ransom Kevin.Ransom@microsoft.com
Cc: Michael Fanning (DEVDIV) Michael.Fanning@microsoft.com; Mike Lai mikelai@microsoft.com
Subject: RE: F# Compiler (fsc.exe) 

Kevin, F# needs “/checksumalgorithm:<alg>” command line switch to set the algorithm to calculate document hash saved to PDB.
Mike is driving the effort to get the option to all compilers.

Thanks,
Tomas

**Comment by tmat** [comment]
@KevinRansom Can we do this work for 15.7?

**Comment by KevinRansom** [comment]
@tmat I will add it to my list

**Comment by tmat** [comment]
> The default in Roslyn is currently SHA1. We are considering switching to SHA256.

We did switch Roslyn to SHA256. F# should also default to SHA256.
