### ISSUE TITLE
F# Debug in interactive could not be setup

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12269]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F-Debug-in-interactive-could-not-be-set/1527155)._

---
Selecting Debug in Interactive gives a confusing message. See video. 

I found "script debugging" in Tools/Options (if that is the answer, then update text in the box)

I set this to true. I still got the message box. 
I closed and reopened the FSI window. Still got the message box.
I closed and reopened VS and still got the same message box. 

I either didn't enable the right thing (in which case I could not find the right thing) or there is another problem with Debug in Interactive.

---
#### Feedback Bot on 9/12/2021, 07:37 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by dsyme** [comment]
Closing as duplicate
