### ISSUE TITLE
Try catch aliases

### ISSUE THREAD

**Issue by jkone27** [dotnet/fsharp#12277]
**currently throw keyword is not used in F#**

currently ``throw`` keyword is not used in F#, could make people transitioning from other langs easier for exception handling by aliasing some keywords

**Create keywords aliases for try/catch statement**

If there was a way to alias catch = with within a try/with expression and throw=raise (in general), that could help developers transitioning and reckognize what code does, even without ML or F# background

```
try


catch ex -> //an alias of try-with
     System.Console.WriteLine(ex.Message)
     throw // or throw ex or throw new MyException(), alias of raise

```

**Describe alternatives you've considered**

The alternative is to keep using raise and try/with

**Comment by dsyme** [comment]
This should go in https://github.com/fsharp/fslang-suggestions.  

It's not a bad suggestion in terms of "simplification" along the lines of `expr[idx]`, but the use of `throw` is not as ubiquitous as the use of `expr[idx]`.  Still it would be good to record the suggestion
