### ISSUE TITLE
Determine how to deal with testing against a stable SDK

### ISSUE THREAD

**Issue by mmitche** [dotnet/fsharp#12289]
In the F# SDK, the version of F# packages implicitly referenced in an F# product varies based on the state of the current SDK. If the SDK is preview, then a preview (presumably the version of F# inserted into the SDK) version of FSharp.Core is referenced. If the current SDK is RTM, then the reference is switched to an RTM version. But from the installer's standpoint, this version may not be available because:
- It may not yet be produced
- Even if it was produced, it was not flowed into the SDK repo (and thus the isolated feed containing the packages is not available).

This does introduce some risk, as it means that .NET cannot test the SDK against the shipping packages until release day, or at least not without any jumping through hoops. We should resolve this so that the transition is cleaner.

Options that come to mind:
- Do not key the F# version off of the SDK's version. This is not a great assumption to make in the first place. Instead, have F# set the version of FSharp.Core based on what is currently being produced. When a stable build is produced, then that will flow into the SDK, with the associated isolated feed containing the candidate packages, and everything will be fine. The final branded build can still be produced multiple times if needed.
- ...

**Comment by KevinRansom** [comment]
Solved.
