### ISSUE TITLE
Stop producing executable `fsc` and `fsi` during source-build

### ISSUE THREAD

**Issue by dagood** [dotnet/fsharp#12282]
`fsc` and `fsi` target `net5.0` and have output type Exe, so when building with/for a 6.0 SDK, they download `Microsoft.NETCore.App.Host.linux-x64/5.0.9` as a prebuilt dependency in order to generate the framework-dependent executable (FDE):

https://github.com/dotnet/fsharp/blob/bb7c79990545f81bf81a543f7522de867d00487c/src/fsharp/fsc/fsc.fsproj#L5-L15

In a Microsoft-built SDK, the FDEs don't seem to be shipped, just the framework dependent assemblies:

```
$ find . -iname fsi*
./sdk/6.0.100-rc.2.21505.57/FSharp/fsi.deps.json
./sdk/6.0.100-rc.2.21505.57/FSharp/fsi.dll
./sdk/6.0.100-rc.2.21505.57/FSharp/fsi.runtimeconfig.json
$ find . -iname fsc*
./sdk/6.0.100-rc.2.21505.57/FSharp/fsc.runtimeconfig.json
./sdk/6.0.100-rc.2.21505.57/FSharp/fsc.dll
./sdk/6.0.100-rc.2.21505.57/FSharp/fsc.deps.json
```

* Is it safe to add to `<UseAppHost>false</UseAppHost>` to these projects during source-builds, to remove the FDE and the prebuilt?
* Can this change be made even when source-build isn't involved? Or are these FDEs used in some other scenario that's specific to the Microsoft-built output?

@brettfo 

In the past, source-build would have upgraded F# to `net6.0` to get around this prebuilt, but this is no longer the preferred way to go about this. (We'd rather keep TFM parity with the Microsoft build.)

---

* For https://github.com/dotnet/source-build/issues/2526
* Related, I'm asking the same thing about `csi` here: https://github.com/dotnet/roslyn/issues/57233. (`csc` already has no FDE.)

**Comment by brettfo** [comment]
@KevinRansom what are your thoughts about `<UseAppHost>false</UseAppHost>`?  I vaguely remember needing it to be true, but I don't remember why.

**Comment by dagood** [comment]
After removing the apphost from `fsc`/`fsi` in a local build, I still see this prebuilt--tracked it down to the bootstrapping builds of `fsyacc`, `AssemblyCheck`, and `fslex`, which also build apphosts. The bootstrapping build steps don't save binlogs, so it was harder to spot.

It looks like those apphosts might be unused (using the DLL instead), so I'll try removing them too:

https://github.com/dotnet/fsharp/blob/bb7c79990545f81bf81a543f7522de867d00487c/src/buildtools/buildtools.targets#L23

**Comment by dsyme** [comment]
This was completed in #12286
