### ISSUE TITLE
Determine how to deal with pre-release builds

### ISSUE THREAD

**Issue by mmitche** [dotnet/fsharp#12290]
In F# pre-release builds, the dotnet-tools feed is added implicitly to restore sources via the F# SDK (https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSharp.Build/Microsoft.FSharp.NetSdk.targets#L57). This is used to ease some dogfooding pain, as it means that users consuming daily builds won't have to add this feed. This gets turned off implicitly in RTM.

But:
- Preview builds that we **do** release to customers will still get this feed added implicitly to their restores (because the SDK is preview). This is not great.
- RTM builds still shouldn't expose the internals of .NET's daily build structure in the shipping product.

Ideally this line either goes away entirely or is designed in such a way as to not include the dotnet-tools feed if we could be producing a build for customers. That would boil down to either a functional change in the build process, or a functional change in dogfooding/testing education.

**Comment by KevinRansom** [comment]
@mmitchie, I believe this is done, please reopen if you think it needs work.
