### ISSUE TITLE
Compiler Services documentation needs updating with new namespace

### ISSUE THREAD

**Issue by JustinGrote** [dotnet/fsharp#12297]
https://fsharp.github.io/FSharp.Compiler.Service/compiler.html

It took me far too long to discover the breaking change that `FSharp.Compiler.Services` namespace has moved to `FSharp.Compiler.CodeAnalysis`. There should be a hero notice at the top of this page.

**Comment by nojaf** [comment]
@baronfel, what would I need to execute to do this manually?
I have faint memories of doing this once back when it was in `fsharp/fsharp`.
Would be interested in having up to date docs of 41 stable.

**Comment by dsyme** [comment]
I think we should auto-publish docs from builds in this repo using fsdocs

I am asking people how we run "fsdocs" and "fantomas" tools in the repo as there is no https://nuget.org package source by default for software supply chain reasons.

**Comment by dsyme** [comment]
Alternatively I could do what we do for https://github.com/fsharp/fsharp-core-docs in https://github.com/fsharp/FSharp.Compiler.Service?

**Comment by baronfel** [comment]
I like the latter idea, especially if we can set up some sort of auto-flow.  I'm leery of getting too much of MS Engineering into what should be a pretty conceptually simple process, and the community fsharp core docs have been pretty easy to iterate on and hands-off once set up.

**Comment by dsyme** [comment]
> I like the latter idea, especially if we can set up some sort of auto-flow. I'm leery of getting too much of MS Engineering into what should be a pretty conceptually simple process, and the community fsharp core docs have been pretty easy to iterate on and hands-off once set up.

I'll set it up now, it should be easy.

**Comment by dsyme** [comment]
@baronfel I've nuked the contents of https://github.com/fsharp/FSharp.Compiler.Service repo and replaced it with a doc build. Docs should appear at https://fsharp.github.io/FSharp.Compiler.Service after build is successful

**Comment by nojaf** [comment]
@dsyme looks like something wrong happened, the Core docs were published instead.

**Comment by baronfel** [comment]
Looks like this has been fixed @nojaf

**Comment by JustinGrote** [comment]
Looks good to me! THank you for the effort!

**Comment by dsyme** [comment]
The docs will republish daily based on the content in this repo, particularly https://github.com/dotnet/fsharp/tree/main/docs/fcs and the XML help in the DLL

Some of the content in https://github.com/dotnet/fsharp/tree/main/docs/fcs is out-of-date but I've tried to flush the worst of it in #12332 .  Better to delete than have out-of-date stuff.

**Comment by dsyme** [comment]
The docs will now be at https://github.com/fsharp/fsharp-compiler-docs

This will include the entire compiler guide under "docs" + generated API docs.

**Comment by dsyme** [comment]
The docs are mucked up until I fix a few things

**Comment by nojaf** [comment]
Thanks for tackling this, looking forward to this!
