### ISSUE TITLE
CompileToDynamicAssembly -I not picking up assemblies

### ISSUE THREAD

**Issue by JustinGrote** [dotnet/fsharp#12302]
I'm attempting to make a cmdlet similar to `Add-Type` but for FSharp in PowerShell. It currently works well however I have to specify `"-I"; "C:/Program Files/dotnet/sdk/6.0.100-rc.2.21505.57/Microsoft/Microsoft.NET.Build.Extensions/net461/lib"` or else it complains. Interestingly these libs all seem to be .NET 5 libraries based on their Version number, not net461 libs.

All the assemblies down to their publicKeyToken are also available in Powershell 7, so I thought I could just do `"-I"; "C:/Program Files/PowerShell/7"` and it should work fine, however it still complains it can't find the assembly, e.g.:

`Add-FSharpType: startup (1,1)-(1,1) typecheck error The type 'BigInteger' is required here and is unavailable. You must add a reference to assembly 'System.Runtime.Numerics, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.`

Howeer, if I specify the dll directly, with reference, then it works fine:
`"-r"; "C:/Program Files/PowerShell/7/System.Runtime.Numerics.dll"`

I don't understand why -I works for that net461 lib folder and not for PS, but the -r does.

```fsharp
namespace PoshFSharp

module AddFSharpType =
  open System
  open System.IO
  open FSharp.Compiler.CodeAnalysis

  /// This is basically the compiler so we name it that way
  let compiler = FSharpChecker.Create()

  let AddFromFile (sourceFile : string) =
    let destination = "ThisIsIgnoredForDynamicAssemblyCompliation.dll"
    let initializeOpts = Some(stderr, stdout)
    let errors, exitCode, assembly =
      compiler.CompileToDynamicAssembly([|
        "fsc.dll"
        "--noframework"
        "-a"; sourceFile
        "-o"; destination
        "-I"; "C:/Program Files/PowerShell/7"
        "-r"; "C:/Program Files/PowerShell/7/System.Runtime.Numerics.dll"
        "-r"; "C:/Program Files/PowerShell/7/System.Runtime.dll"
        // "-I"; "C:/Program Files/dotnet/sdk/6.0.100-rc.2.21505.57/Microsoft/Microsoft.NET.Build.Extensions/net461/lib"
      |], initializeOpts)
      |> Async.RunSynchronously
    // TODO: Better error handling
    if exitCode > 0 then raise (InvalidOperationException(errors.[0].ToString()))
    assembly.Value
```

**Comment by dsyme** [comment]
@KevinRansom Is this a regression?

**Comment by JustinGrote** [comment]
My problem was I needed --targetprofile netcore, which is undocumented.
https://github.com/dotnet/docs/issues/27076
