### ISSUE TITLE
In a F# script file #I __SOURCE_DIRECTORY__ no longer working 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12306]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/In-a-F-script-file-I-__SOURCE_DIRECTOR/1546342)._

---
This used to work: `#I __SOURCE_DIRECTORY__`

However, now I get an error message and I have to give the literal path.

---
#### Feedback Bot on 10/8/2021, 00:17 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by vzarytovskii** [comment]
> I believe this is a duplicate of #11732 and has been fixed in #11733.

Yeah, that should be fixed already, closing it.
