### ISSUE TITLE
Mono Bug: Error message when attempting to observe a newly assigned value after mutating an object member

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12308]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Mono-Bug:-Error-message-when-attempting-/1103633)._

---
https://stackoverflow.com/questions/62583282/mono-bug-error-message-when-attempting-to-observe-a-newly-assigned-value-after/62584027#62584027

I'm observing an error message on a data-tip when attempting to observe a newly assigned value after mutating an object member.

**Viewmodel:**

I'm trying to mutate the header member of a viewmodel object.

    let mutable header : NavBarItem option = None

    member x.Header      with get()  = header
                         and  set(v) = header       <- v
                                       base.NotifyPropertyChanged(<@ x.Header @>)
    ...
    //----------------------------------
    // THE FOLLOWING ERRORS
    //----------------------------------
    member x.LoadAsync(panelId:PanelId) =

       let items = seq [NavBarItem() :> UITemplate]

       let result = items  |> Seq.map (fun v -> v :?> NavBarItem)
                           |> Seq.tryHead // Error recovering value

       x.Header <- result

**Error:**

Here's the error after I hover my cursor over x.Header:

> Incorrect number or types of arguments Parameter name: arguments

[![enter image description here][1]][1]
Here's a [bug report][2] that I observed after researching the error message.

**UPDATE:**

I attempted to serialize the sequence of objects that I did have access to so that I could deserialize the json and access an individual item.

That also failed:

       let temp = seq [NavBarItem() :> UITemplate] |> filterToNavBarItems 
                                                   |> Seq.cast<NavBarItem>
    
       let json  = JsonConvert.SerializeObject(temp)
       let items = JsonConvert.DeserializeObject<NavBarItem seq>(json)
       let item  = items |> Seq.tryHead

       x.Header <- item // Error recovering value

Json:

    [{"MeasureId":"some_navbar_id","Header":"Dashboard","Subheader":"Trauma Alerting","EmblemLabel":"","IsEmblemAttached":false,"EmblemBGColor":"","EmblemFGColor":""}]

**Appendix:**

    type UITemplate =
        abstract member ToString   : unit -> string
        abstract member OrderIndex : int with get, set

    type NavBarItem() =

        inherit ViewModelBase()

        let mutable header = ""

        interface UITemplate with 
            member x.ToString() = "NavBarItem"
            member val OrderIndex = -1 with get,set

        member x.Header  with get()  = header
                         and  set(v) = header <- v
                                       base.NotifyPropertyChanged(<@ x.Header @>)

    
    type ViewModelBase () =
    
        let propertyChanged = Event<PropertyChangedEventHandler,PropertyChangedEventArgs>()
            
        let getPropertyName = function 
            | PropertyGet(_,pi,_) -> pi.Name
            | _ -> invalidOp "Expecting property getter expression"
            
        interface INotifyPropertyChanged with
    
            [<CLIEvent>]
            member this.PropertyChanged = propertyChanged.Publish
            
        member this.NotifyPropertyChanged propertyName = 
            propertyChanged.Trigger(this,PropertyChangedEventArgs(propertyName))
    
        member this.NotifyPropertyChanged quotation = 
            quotation |> getPropertyName |> this.NotifyPropertyChanged

  [1]: https://i.stack.imgur.com/zZfH6.png
  [2]: https://xamarin.github.io/bugzilla-archives/46/4659/bug.html

---
#### Feedback Bot on 7/6/2020, 11:49 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/27/2020, 02:56 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Thays Tagliaferri de Grazia [MSFT] on 7/27/2020, 09:21 AM: 

<p>Hi, Scott Nimrod, could you please share a sample that reproduces it? I was trying to investigate it but unfortunately I couldn't reproduce yet.</p>

#### Scott Nimrod on 7/27/2020, 11:39 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by dsyme** [comment]
Closing as this is too specific to be of concern in this repo and Mono-related
