### ISSUE TITLE
op_Implicit auto casting does not work with pipe operator

### ISSUE THREAD

**Issue by En3Tho** [dotnet/fsharp#12325]
**Repro steps**

![image](https://user-images.githubusercontent.com/37334640/139870395-bab98c22-7c90-4a9a-9145-97375005d49f.png)

**Expected behavior**

op_impicit auto-casting respects pipe operator as it's one of the most used operators in language

**Actual behavior**

op_impicit auto-casting does not respect pipe operator

**Known workarounds**

Do not use pipe operator

P.S.
It works with backward pipe and (^) operator, but not all the time:

![image](https://user-images.githubusercontent.com/37334640/139872906-e4d31f00-b6db-4684-bf4c-9e597554fa65.png)

**Comment by dsyme** [comment]
This is by design.   Type-directed conversions don't work like this. 

You should simply not use type directed conversions in conjunction with piping and other such language features.  If you wish to disable type-directed conversions altogether, use the warnings specified here: https://docs.microsoft.com/en-us/dotnet/fsharp/whats-new/fsharp-6#optional-warnings-for-implicit-conversions

**Comment by En3Tho** [comment]
@dsyme Sorry to hear this. Is this compiler type-inference or inline function unwinding related? Or it is precisely by design in a sense of how you imagined it would work?

 A person I know posted a somewhat related issue to this ling time ago:
 https://github.com/dotnet/machinelearning/issues/1737

I think the ability to use this feature with pipes can come in handy for cases like this.

**Comment by dsyme** [comment]
> @dsyme Sorry to hear this. Is this compiler type-inference or inline function unwinding related? Or it is precisely by design in a sense of how you imagined it would work?

I'm considering what to do about this. It may be we add more warnings when type-directed conversions for numeric widening kick in - to bring them into line with op_Implicit conversions, where the only place we don't give a warning is for method calls.  This would mean it is less of a surprise.

With regard to APIs like ML.NET, we really expect those to be based on members and not pipelining to `let`-defined functions

**Comment by En3Tho** [comment]
@dsyme I see. Thank you for clarification.
