### ISSUE TITLE
Good first issue

### ISSUE THREAD

**Issue by omppye** [dotnet/fsharp#12330]
Hi!
I would like to contribute with the codebase; I've tried the #12067 but seems a pretty sensitive issue which probably should be solved by a org member.

Because of that I would like to know if the issues have a tag for beginners, something like a "good first issue"

**Comment by Happypig375** [comment]
https://github.com/dotnet/fsharp/issues?q=is%3Aopen+is%3Aissue+label%3A%22Up+for+Grabs%22

**Comment by omppye** [comment]
> https://github.com/dotnet/fsharp/issues?q=is%3Aopen+is%3Aissue+label%3A%22Up+for+Grabs%22

Mostly very old issues. I algo tried to get some of them like #10042
The point is this tag is still being actively used?

**Comment by vzarytovskii** [comment]
Yeah, `Up for Grabs` does not always mean it will be a good first issue/entry level issue. We didn't do labeling for such issues in a while. We probably should.

**Comment by charlesroddie** [comment]
> @vzarytovskii, you can view this as my answer to https://twitter.com/vzarytovskii/status/1449772959841796101 ;)

Good question which is worth creating an issue about in this repo.

Two things related to open RFCs that may be relatively manageable:

- Parse `[: :]` to an ImmutableArray. It may be doable as it duplicates the current parsing of `[| |]` to an Array. Part of [FS-1094-block](https://github.com/fsharp/fslang-design/blob/a5ba3a3624f90cf2fd326dd68cbe2989ba8b46b2/RFCs/FS-1094-block.md)
- Allow access to record constructors. These things exist and the work is to find the mechanism that makes them invisible in F# code. [FS-1073-record-constructors](https://github.com/fsharp/fslang-design/blob/a5ba3a3624f90cf2fd326dd68cbe2989ba8b46b2/RFCs/FS-1073-record-constructors.md)

**Comment by smoothdeveloper** [comment]
@omppye I have some experience tackling issues related to #1103 (improving error messages).

This is, in my experience, the most effective way to dip into the compiler codebase, and having an effect on it, that helps all users of the language (they face compiler error messages pretty often 🙂).

The workflow is pretty simple as you just need a minimum code sample, and debug fsi process, figuring where the error is thrown, and seeing what can be worked on from the context you have where it occurs.

If you or anyone wants to give it a shot, you can ping me on the fsharp slack or just engage in the #compiler channel there.

Aside, organisationally, wrt. to triaging issues for potential contributors, having classification of issues like done in #1103 and #11481 would help the "potentially up for grabs" ones to find contributors who've gained skilled on the area (parsing, type checking, error reporting, code transformation/optimisation/emission, ...) to easily find the activity / discussions / code changes related to a set of related issues.
