### ISSUE TITLE
Define and apply coding standards for this repo 

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#12339]
This is a tracking issue about being better about having coding standards for this repo.

* We have #12119 for adopting fantomas formatting bit by bit
* We also have some standards with respect to naming, e.g. the table of abbreviations here https://fsharp.github.io/fsharp-compiler-docs/coding-standards.html
* The compiler code base lacks consistency. We should continue to make incremental progress on this
* Consider standards/goals with respect to reduction in single-character identifiers. For example set goals like “reduce single character identifiers by 50%” 
* Consider XML documentation for all types, members and cross-module functions

**Comment by auduchinok** [comment]
> Consider XML documentation for all types, members and cross-module functions

Can it be defined as something less mandatory for cases where a good symbol name would explaing it well enough? There're many comments in FCS APIs that don't seem to add much value, like the comment for `IsPublic` here: https://github.com/dotnet/fsharp/blob/129aa5fb902ca7a43f48c53d12d2d6277258f8bb/src/fsharp/symbols/Symbols.fsi#L32-L37

It'd be sad if similar comments became required.

**Comment by dsyme** [comment]
I think everything public in the FCS should have `///` for sure. For example, there are subtleties about `public` and signature files. They can be mentioned.  In the long terms FCS needs to be as well documented as Roslyn

**Comment by KevinRansom** [comment]
in progress
