### ISSUE TITLE
Member access when using expr[idx] indexer syntax

### ISSUE THREAD

**Issue by kevmal** [dotnet/fsharp#12358]
Cannot access members of elements without brackets or reverting back to `expr.[idx]` syntax. `a[1].` accesses members of the list `[1]` and not the 2nd item of `a`. 

![image](https://user-images.githubusercontent.com/7281367/140942837-f26d5c75-0fc8-4dec-9b8a-594faeac67c8.png)

**Comment by dsyme** [comment]
This is by design for F# 6.0.  You should parenthesize in this situation.

```
("ab"[0..1]).Trim();;
```

I will document this in the RFC.

**Comment by kevmal** [comment]
My case was `Path.GetFileName(file)[0..2]`, realized I needed a trim and got an error on `Path.GetFileName(file)[0..2].Trim('_')`... Seems easier in my mind to just stick to `expr.[idx]` syntax instead of backtracking to add parens.

**Comment by dsyme** [comment]
Yes, the use of `.[idx]` is totally fine.

**Comment by auduchinok** [comment]
@dsyme What if we allowed it for cases where expression types allow indexing, like in the `""[1]` or `x.ToString()[1]` examples?

**Comment by dsyme** [comment]
@auduchinok Both of those are allowed.

There is a difference between
* adjacent applications `F` `X` where expressions `F` and `X` are together, no whitespace
* high-precedence adjacent applications `F` `X` where expressions `F` and `X` are together, no whitespace, and `F` is an identifier.

Adjacent applications that are **not** high-precedence are rare, however they do occur if `F` ends in `)` or `]` or is a constant like `"abc"`.  Call these AA-not-HP.  For compat reasons, AA-not-HP do not bind their argument tightly. So for:

```fsharp
"ab"[0..1].Trim()
(f x)[0..1].Trim()
"ab"[0..1].Length
(f x)[0..1].Length
```

Here for legacy reasons the `"ab"[` and `(f x)[...` are adjacent applications but not-high-precedence. This means `.Trim()` binds more tightly (higher precedence) than the application, and logically these are parsed as
```fsharp
"ab"[0..1].Trim()
    ^^^^^^^^^
(f x)[0..1].Trim()
     ^^^^^^^^^
"ab"[0..1].Length
    ^^^^^^^^^
(f x)[0..1].Length
     ^^^^^^^^^
```

In all these cases either the explicit `expr.[idx]` should be used or parentheses added:
```fsharp
"ab".[0..1].Trim()
(f x).[0..1].Trim()
"ab".[0..1].Length
(f x).[0..1].Length
```
or
```fsharp
("ab"[0..1]).Trim()
((f x)[0..1]).Trim()
("ab"[0..1]).Length
((f x)[0..1]).Length
```
or bound using `let`
```fsharp
let v = "ab"[0..1]
v.Trim()
```
etc.

In RFC FS-1110 we didn't try to eliminate all AA-not-HP - it is very tricky to do - and to be honest they are rare in code, and mostly found in "let's try this out" examples. However in some far future revision of the language we may eliminate AA-not-HP or give warnings for them all, always asking people to add spaces for any existing ones that represent valid application code.
