### ISSUE TITLE
'enum' type constraint error isn't reported anymore when other errors exist

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#12375]
The `enum` constraint errors aren't reported anymore when other errors exist. Consider solution with F# and C# projects:

```csharp
public class Class
{
}

public enum EnumShort : short
{
    A,
    B
}
```

```fsharp
let _: Class = enum 0 // no error is reported while the error below exists
let _: EnumShort = enum 0 // error: The type 'int32' does not match the type 'int16'
```

If the other error is removed, the enum-related ones are reported:
```
Could not resolve the ambiguity in the use of a generic construct with an 'enum' constraint at or near this position
Type constraint mismatch when applying the default type 'Class' for a type inference variable. The type 'Class' is not a CLI enum type Consider adding further type constraints
```

Previously all errors would be reported by FCS as expected, though there was a single error with a different text:
```
The type 'Class' is not a CLI enum type
```

An interesting note: errors ranges are different when using a type from a C# project output and from BCL:
```
// `enum 0` expression range is reported
let _: Class = enum 0

// only `enum` range is reported
let _: obj = enum 0
let _: System.Object = enum 0
let _: string = enum 0
```

The behaviour changed somewhere between https://github.com/dotnet/fsharp/commit/85fe2809db9c106d3c630c74dbe806eb8b9b09c9 and https://github.com/dotnet/fsharp/commit/eccf87b7c8ea1a62dbb9481f12c5ba02ca80b8e6.

**Comment by dsyme** [comment]
@auduchinok I'm not sure this counts as a bug.  We do phase some error reporting - for example if errors occur during "Check" we suppress the "PostInferenceChecks" phase 

I assume what happened is that the default constraint application got phased in a slightly different way.

**Comment by auduchinok** [comment]
@dsyme Thanks, that's what I suspected. Is there any reason to cancel that phase if there're any errors prior to it? Is it to try to minimize cascade errors?

Maybe we could try to do some of the analysis anyway? Not reporting an error that exist and that was previously reported does look like a regression/bug to me. I'd be happier if we removed such cases and not added them. 🙂

**Comment by dsyme** [comment]
I'd have to look at the exact cause of the change.  I think it's the fix to check constraints that were being missed in type checking:
```
    // Run any additional checks registered to be run before applying defaults
    do 
      for check in cenv.css.GetPostInferenceChecksPreDefaults() do
        try  
            check()
        with e -> 
            errorRecovery e m
```

In any case, this particular cases of phasing isn't significant enough given there are quite a few other cases of it, and we don't consider those bugs.  So I will close this, thanks

**Comment by auduchinok** [comment]
> In any case, this particular cases of phasing isn't significant enough given there are quite a few other cases of it, and we don't consider those bugs. 

Wouldn't it be better to try to eliminate cases where errors aren't reported? I consider it similar to other error recovery where we try to report things and not fail early.
