### ISSUE TITLE
Struct representations for active patterns limitations

### ISSUE THREAD

**Issue by kevmal** [dotnet/fsharp#12389]
I would expect to be able to simply switch an existing active pattern to use structs but it seems limited. Any reason for restricting use to top level active patterns? Would be nice to be able to do the following:

```fsharp 
let f1() = 
    [<return: Struct>]
    let (|AP|_|) (x : int) = 
         ...
    ...
```
or
```fsharp
let f2 ([<return: Struct>] ``|AP|_|``) = 
    ...
```

**Comment by Happypig375** [comment]
The first one is https://github.com/fsharp/fslang-suggestions/issues/848 while the second one can already be done:
```fs
let f2 ((|AP|_|): _ -> _ voption) = 
    match 1 with AP 1 -> 1 | _ -> 2
```

**Comment by kevmal** [comment]
It's great that `f2` works, and it's actually preferable to an attribute but it seems a bit inconsistent... I can (and probably will) do

```fsharp
let f1() = 
    match 
        (fun x -> 
            if x > 100 then 
                ValueSome 1 
            else 
                ValueNone
        ) with 
    | ``|AP|_|`` ->
    match 1 with AP 1 -> 1 | _ -> 2
```

yet a simple let binding would give an error.

**Comment by dsyme** [comment]
I'll close this per @Happypig375's comment https://github.com/dotnet/fsharp/issues/12389#issuecomment-968768968

**Comment by Happypig375** [comment]
@kevmal
```fs
let f1() =
    fun x ->
        if x > 100 then 
            ValueSome 1 
        else 
            ValueNone
    |> fun (|AP|_|) ->
    match 1 with AP 1 -> 1 | _ -> 2
```

**Comment by kevmal** [comment]
@dsyme Does that mean https://github.com/fsharp/fslang-suggestions/issues/848 is approved?

**Comment by dsyme** [comment]
Ah my mistake, I thought the link was referring to the idea of simply inferring structness from return type here https://github.com/fsharp/fslang-suggestions/issues/1041#issuecomment-944912476
