### ISSUE TITLE
VS 2022 Preview 1 broken reference to FSharp.Core >= 6.0.2

### ISSUE THREAD

**Issue by whb07** [dotnet/fsharp#12393]
Please provide a succinct description of the issue.

VS2022 is broken on a clean new install. References a missing library. Cannot run F# projects.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Download new copy of VS 2022
2. Attempt to create a new project with F#.

**Expected behavior**
Should build / run fine.

**Actual behavior**
An error raised "... FSharp.Core >= 6.0.2 required"

Provide a description of the actual behaviour observed. 

**Known workarounds**
I tried messing around with the sdk in "C:/Program Files" to no avail. Yes I do have a .net 6.0 sdk 

Provide a description of any known workarounds.

**Related information**
https://developercommunity.visualstudio.com/t/fsharp-projects-dont-compile-in-vs2022-after-upgra/1577963

Provide any related information (optional):

Seems perhaps from the scrounging around the internet that Nuget's latest FSharp.Core package version is 6.0.1. Somehow VS2022 attempts to reference a later version....perhaps this is the problem?

* Operating system Windows11
* .NET Runtime kind (.NET `Coe,` .NET Framework, Mono) .NET6
* Editing Tools (e.g. Visual Studio Version, Visual Studio) VS2022

**Comment by dsyme** [comment]
Note this is Version 17.1.0 Preview 1.0 according to the linked bug

**Comment by dsyme** [comment]
@whb07 Can you confirm you are also using Preview 17.1.0 Preview 1.  

I think this might be expected behaviour of some kind for the previews on occasion. I note the linked bug says "It compiles fine from dotnet CLI then it uses 6.0.1."  .  @KevinRansom will know the details

**Comment by whb07** [comment]
![image](https://user-images.githubusercontent.com/15861355/141810299-faf16b2c-ec31-4a61-ad53-440fe4fd77c4.png)
![image](https://user-images.githubusercontent.com/15861355/141810409-be80e7b1-af39-4877-a975-a7fbb2762b00.png)

So the CLI tool runs fine. I think the issue is like I commented in the ticket, that perhaps there is a definition somewhere within VS2022 that attempts to fetch the non-existing nuget package version? Idk where the code exists and i don't know my way VS very well to figure out the logs unfortunately...

**Comment by vzarytovskii** [comment]
It is known, fix should be merged already and will be in the next preview.

**Comment by realparadyne** [comment]
@whb07  As a workaround until the next release, add this to all .fsproj files.

```
  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="6.0.1" />
  </ItemGroup>
```
