### ISSUE TITLE
Diagnostics 3390, 3391 reused

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#12417]
We have incorrectly reused diagnostic numbers 3390, 3391.  

Warning diagnostic 3390 is off by default and this is currently intended for both its meanings `tcImplicitConversionUsedForMethodArg` and `xmlDocBadlyFormed`, and in both cases this is documented [here](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/xml-documentation#compile-time-checking) and [here](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/casting-and-conversions#summary-of-warnings-related-to-conversions).  

Proposal:
1. We re-number `tcImplicitConversionUsedForMethodArg `, update the documentation.
2. We re-number `tcLiteralAttributeCannotUseActivePattern` just to avoid the conflict.
3. I also propose we turn on `xmlDocBadlyFormed` by default but that's a separate matter.

```
3390,tcImplicitConversionUsedForMethodArg,"This expression uses the implicit conversion '%s' to convert type '%s' to type '%s'."
3391,tcImplicitConversionUsedForNonMethodArg,"This expression uses the implicit conversion '%s' to convert type '%s' to type '%s'. 3390,xmlDocBadlyFormed,"This XML comment is invalid: '%s'"
3391,tcLiteralAttributeCannotUseActivePattern,"A [<Literal>] declaration cannot use an active pattern for its identifier"
```

**Comment by auduchinok** [comment]
@dsyme Would it make sense to also check 193 error number? It's currently also reused by multiple diagnostics.

**Comment by dsyme** [comment]
Yes, though 3390 was particularly problematic because it is an "opt-in" warning

**Comment by dsyme** [comment]
FWIW the problem with "193" is this code in the (very) old way of assigning numbers to diagnostics

      | _ -> 193

**Comment by auduchinok** [comment]
> FWIW the problem with "193" is this code in the (very) old way of assigning numbers to diagnostics

Yes, I've seen this code, thanks. 🙂
I just thought we were aiming at preserving the numbers so I haven't brought it up before.
