### ISSUE TITLE
Syntax Tree Trivia

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#12418]
**Is your feature request related to a problem? Please describe.**

In order to have better results in Fantomas, we require more information in the syntax tree about certain specifics.
Examples are locations of certain tokens or keywords. 

**Describe the solution you'd like**

In the past, we added this information directly to the syntax tree nodes.
However, this can lead to a lot of overhead as discussed in #12400.
 
As a compromise, we could instantiate a new object/record/structure per syntax tree node to bundle these.
The proposal would be to have them as the last item in a DU case.

Example:

`SyntaxTrivia.fs`:

```fsharp
namespace FSharp.Compiler.Syntax.Trivia // or SyntaxTrivia ?

type SynTryWithTrivia =
    { TryKeyword: Range
      WithKeyword: Range }
```

`SyntaxTree.fs`:

```fsharp
type SynExpr =
    | TryWith of
        tryExpr: SynExpr *
        tryRange: range *
        withCases: SynMatchClause list *
        withRange: range *
        tryDebugPoint: DebugPointAtTry *
        withDebugPoint: DebugPointAtWith
        range: range *
        trivia: SynTryWithTrivia 
```

**Describe alternatives you've considered**

The alternative is to have all extra information unbundled in the Syntax tree.

**Additional context**

related: #11481
<strike>
I'm not really fixed on the `appendix` name, I would like to avoid using any `trivia` terminology.
Trivia is used as a concept in Fantomas to add additional information found in the tokens to the tree.

In this case, we really are enriching the tree. So to avoid any confusion I would go with a different name.
Let me know what you think.
</strike>

//cc @dsyme @auduchinok @baronfel

**Comment by dsyme** [comment]
Looks fine to me.  In your example are `tryRange` and `withRange` then in the appendix, rather than the node as you've shown?

TBH I'd kind of like to use trivia, even if it conflicts with Fantomas

**Comment by dsyme** [comment]
The name should be `SynExprTryWithAppendix` (or `SynExprTryWithTrivia`).  All the types in SyntaxTree get `Syn`, and in some cases we will need to disambiguate from `SynPat`.

**Comment by nojaf** [comment]
>  In your example are tryRange and withRange then in the appendix, rather than the node as you've shown?

This is from the original code that is already there, so I left that unchanged. 
I'm fine with moving those, either way, I don't really know what is being done with those.

**Comment by dsyme** [comment]
I see.  Yes, they should really be renamed to `tryToWithRange` and `withToEndRange`.  Looks like they are used for error reporting and to choose whether to look inside for syntax tree traversal I guess they should go into trivia.

If we could use the name Trivia I've be grateful, it is the standard terminology for what all this is.

**Comment by nojaf** [comment]
> If we could use the name Trivia I've be grateful, it is the standard terminology for what all this is.

Sure thing, I'll get over it in the morning 😅.

**Comment by dsyme** [comment]
This has largely been addressed by @nojaf's PRs linked above
