### ISSUE TITLE
Generic constructor is always shadowed by non-generic one when not specifying generic type explicitly

### ISSUE THREAD

**Issue by TimLariviere** [dotnet/fsharp#12415]
While exploring a lot of ideas for a new DSL for Fabulous, I found something that feels inconsistent in the way F# resolves constructors and I'm wondering if I'm just getting it wrong or if it's a limitation in F#.

Today, when declaring a generic constructor, you can call it without having to include the generic type.
The F# compiler infers it automatically.
But when you include another namespace / module declaring another non-generic class of the same name, the previous code no longer compiles.

```fs
module A =
    type MyClass() = class end

module B =
    type MyClass<'T>(value: 'T) = class end
```
```fs
open B

// Compiles
let c = MyClass(10) // B.MyClass<int>(10)
```
```fs
// The order of open statements has no effect. MyClass<'T> is always inaccessible.
open A
open B

// Doesn't compile.
let c = MyClass(10)
// Error FS0501: The object constructor 'MyClass' takes 0 argument(s) but is here given 1. The required signature is 'new : unit -> MyClass'.
```

Also I noticed if you use `open type` with a static member to instantiate the correct type, it works without having to declare the generic type explicitly.

```fs
[<AbstractClass; Sealed>]
type Ext private () =
    static member inline MyClass<'T>(value) = B.MyClass<'T>(value)

open A
open B
open type Ext

// Compiles
let c = MyClass(10) // B.MyClass<int>(10)
```

**Repro steps**

1. Install dotnet 6.1.100
2. `dotnet new classlib -lang F# -n Repro`
3. Write the following code
```fs
namespace Repro

module A =
    type MyClass() = class end

module B =
    type MyClass<'T>(value: 'T) = class end

module Test =
    open A
    open B

    let x = MyClass(10)
```
4. `dotnet build`

**Expected behavior**

Accessing the generic constructor without specifying explicitly the generic type should work when there's no directly conflicting non-generic constructors.
E.g.

```fs
type MyClass() = (...)
type MyClass<'T>(value: 'T) = (...)
let c = MyClass(10) // Should compile because only 1 ctor is matching
```

**Actual behavior**

```fs
type MyClass() = (...)
type MyClass<'T>(value: 'T) = (...)
let c = MyClass(10) // Doesn't compile. 
// Error FS0501: The object constructor 'MyClass' takes 0 argument(s) but is here given 1. The required signature is 'new : unit -> MyClass'.
```

**Known workarounds**

There's several workarounds, each implies to be more specific.
```fs
let c = A.MyClass(10)
let c = MyClass<int>(10)
```

Also the use of `open type` + static member can help working around it (see top)

**Related information**

Seems to be affecting all version of F#

**Comment by dsyme** [comment]
This is by design, it is normal to have multiple type names in scope that differ by generic arity, c.f. System.Action. You can disambiguate like this:

```
    let x = MyClass< >()
    let x = MyClass<_>(10)
```

If not generic parameters are given then the non-generic is preferred.
