### ISSUE TITLE
Pipeline following certain matches with cases on new lines does not depend on indentation

### ISSUE THREAD

**Issue by the-not-mad-psychologist** [dotnet/fsharp#12422]
When I continue piping at the proper level of indentation after a match expression with case results specified on separate lines, the compiler sometimes apparently interprets my following code as applying to the last case of the match rather than to the whole.

This example function
```F#
let foo a =
  match a with
  | true ->
    (+)
  | false ->
    (-)
  <| 1
```

is apparently equivalent to
```F#
let foo a =
  match a with
  | true -> (+)
  | false -> (-) <| 1
```

rather than to
```F#
let foo a =
  (match a with
   | true ->
     (+)
   | false ->
     (-))
  <| 1
```

**Expected behavior**

`val foo: bool -> int -> int` with the returned value incremented by one if the `bool` argument is `true` or decremented by one otherwise.

**Actual behavior**

The `(-)` function shows this compiler error: `The type ''a -> 'b' does not match the type 'int'`. Further, `foo` appears neither to have a type signature nor to be defined thereafter in the code.

I would expect this behavior had I indented the last line differently:
```F#
let foo a =
  match a with
  | true ->
    (+)
  | false ->
    (-)
    <| 1
```

**Known workarounds**

Add the code following the expression to each case individually.

**Comment by dsyme** [comment]
This is actually by design as things stand - it's related to the processing of infix operators and some leeway that is given for those. 

There is an open design suggestion to give a warning for this, see https://github.com/fsharp/fslang-suggestions/issues/806

My recommendation would be to use 4-space indentation (which is really recommended anyway) as it is very difficult to trigger this if you do

**Comment by the-not-mad-psychologist** [comment]
> This is actually by design as things stand - it's related to the processing of infix operators and some leeway that is given for those.

Thank you for the information! For future reference, where could I have checked to find that this wasn't a bug?

**Comment by dsyme** [comment]
> Thank you for the information! For future reference, where could I have checked to find that this wasn't a bug?

IIRC the language specification does cover this but it's too detailed to follow

We should document this at https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/match-expressions and https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/conditional-expressions-if-then-else I guess.  I'll put in an edit for this

**Comment by the-not-mad-psychologist** [comment]
For any future readers, I found [an article that explains this rule](https://fsharpforfunandprofit.com/posts/fsharp-syntax/).

**Comment by dsyme** [comment]
Thanks, yes, we can reference that

**Comment by dsyme** [comment]
I've made a note of this here: https://github.com/dotnet/docs/issues/26813  and asked Scott Wlaschin if we can just lift his content across into docs.microsoft.com/dotnet/fsharp
