### ISSUE TITLE
Test is flaky in `main`

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#12447]
[`type check neg132`](https://github.com/dotnet/fsharp/blob/main/tests/fsharp/tests.fs#L3113) is flaky in `main`, but passes in PR branches and locally. 

Started failing when seemingly unrelated change was merged: https://github.com/dotnet/fsharp/pull/12350, and is failing in every other commit in main since then.

(https://dev.azure.com/dnceng/public/_build/results?buildId=1483455&view=logs&j=966222a4-f29d-5ec0-88cc-1b798728906e&t=052eabf8-67e2-5f29-745c-00cc34aa0e02&l=14740)

**Comment by vzarytovskii** [comment]
Probably related to weird/mixed line endings introduced in one of the PRs.

**Comment by dsyme** [comment]
Seems to be stable now
