### ISSUE TITLE
F# 6.0 warning 3390

### ISSUE THREAD

**Issue by psantoro** [dotnet/fsharp#12444]
https://devblogs.microsoft.com/dotnet/announcing-f-5/ - describes warning 3390 as "checks XML documentation against the 
signatures they document if you opt into it"

https://devblogs.microsoft.com/dotnet/whats-new-in-fsharp-6/ - describes warning 3390 as "/warnon:3390 (op_Implicit at method arguments)"

Did the meaning of warning 3390 change for F# 6.0 or am I missing something here?

What clued me into this difference was that one of my existing F# 5.0/.net 5.0 projects now behaves differently at build time.  The fsproj template contains:

<TargetFramework>net5.0</TargetFramework>
<WarnOn>3390;$(WarnOn)</WarnOn>

which was added by default when using dotnet new console.  Note that the above WarnOn entry is not added when creating an F# 6 console fsproj file.

When I recently recompiled this project (dotnet build) from my Visual Studio 2019 command prompt , I got the following unexpected warning for F# 5:

main.fs(55,53): warning FS3390: This expression uses the implicit conversion 'StringValues.op_Implicit(values: StringValues) : string' to convert type 'StringValues' to type 'string'. [C:\Users\Peter\work\ctdrs\fsharp\core\5.0\sots2ctax\sots2ctax.fsproj] 

Here's line 55:

client.DefaultRequestHeaders.Add("X-App-Token", StringValues(opts.apptoken))

Note that I recently installed Visual Studio 2022 along side Visual Studio 2019.  I've attached screen shots of both command prompts.  Note that both command prompts display the following:

Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET

On another PC with only Visual Studio 2019 installed, I don't get the 3390 warning using the identical project (uses Build Engine 16.11.2+f32259642).  Perhaps this is related to the fact that I have 2 versions of Visual Studio installed and I'm doing something incorrectly?  It also appears that there may be more than one issue going on here (VS2019 command prompt build appears to be using VS2022 tooling and warning 3390 appears to work differently in F# 5 vs F# 6).

![msvs2022](https://user-images.githubusercontent.com/1687878/143093374-188f3a19-6697-4329-afd7-6ff7f5d33984.png)
![msvs2019](https://user-images.githubusercontent.com/1687878/143093377-12eb159c-c484-429c-8fc6-69cdb713c937.png)

**Comment by dsyme** [comment]
See #12417 .  We are in the process of changing the new warning number to 3395.
