### ISSUE TITLE
`WarningsNotAsErrors` is not forwarded to the compiler

### ISSUE THREAD

**Issue by rodion999** [dotnet/fsharp#12452]
Seems like that `WarningsNotAsErrors` is not forwarded to FSC. I think it's missed here: https://github.com/dotnet/fsharp/blob/d45c9e518bc785047699c53db9ee3975443cf0c8/src/fsharp/FSharp.Build/Microsoft.FSharp.Targets#L366

**Repro steps**

```fsharp
[<System.Obsolete>]
let dummy = 42

printfn $"{dummy}"
```

```powershell
dotnet build -p:TreatWarningsAsErrors=true -p:WarningsNotAsErrors=FS0044
```

**Expected behavior**

`FS0044` is not treated as an error.

**Actual behavior**

`FS0044` is treated as an error.

**Related information**

.NET 6.0.100

**Comment by vzarytovskii** [comment]
Yeah, it should be adding `--warnaserror-:...` to the fsc `FSharpCommandLineBuilder`. We should be passing it.

**Comment by baronfel** [comment]
@vzarytovskii I think it means that the [already existing WarningsNotAsErrors msbuild prop in the FSC task](https://github.com/dotnet/fsharp/blob/dbf9a625d3188184ecb787a536ddb85a4ea7a587/src/fsharp/FSharp.Build/Fsc.fs#L521-L523) needs to be hooked up in the targets approximately where @rodion999 has pointed.

**Comment by vzarytovskii** [comment]
> @vzarytovskii I think it means that the [already existing WarningsNotAsErrors msbuild prop in the FSC task](https://github.com/dotnet/fsharp/blob/dbf9a625d3188184ecb787a536ddb85a4ea7a587/src/fsharp/FSharp.Build/Fsc.fs#L521-L523) needs to be hooked up in the targets approximately where @rodion999 has pointed, because the [commandlinebuilder work is already done](https://github.com/dotnet/fsharp/blob/dbf9a625d3188184ecb787a536ddb85a4ea7a587/src/fsharp/FSharp.Build/Fsc.fs#L224-L227).

Yeah, that's what I meant. We already doing the `WarningsNotAsErrors` -> `--warnaserror-:`, and we need to take it into account in targets.

**Comment by baronfel** [comment]
@rodion999 are you interested in adding this fix? we'd be happy to help you through it.

**Comment by rodion999** [comment]
@baronfel I would do it with great joy

**Comment by baronfel** [comment]
Great! It should be a straightforward addition to the targets file as you've identified, so if you want to go ahead and send a PR with that that'll at least get the pipelines going. The larger question of testing is still a bit ambiguous - there's not any testing currently for the Fsc task itself, and there's also not any for the larger props/targets mechanism overall, where your change actually would be.  So I'm not entirely sure what the best way of adding tests for this, if any, is. @KevinRansom do you have any ideas?

**Comment by rodion999** [comment]
@baronfel 
[https://github.com/dotnet/fsharp/pull/12453](url)

Please excuse me if I did something wrong.
This is my first issue
