### ISSUE TITLE
Building VisualFsharpFull or VisualFsharpDebug vsix' with VS2022 fail to install

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#12457]
- Sync the repo
- checkout main branch
- build

Try to install the VisualFsharpFull or VisualFsharpDebug vsix

![image](https://user-images.githubusercontent.com/5175830/143538525-51db7dd4-f743-4f97-87a5-b6f831f281b6.png)

**Comment by dsyme** [comment]
Tried it and it now installs fine for me
