### ISSUE TITLE
CodeLens is not shown in the right place for bindings with attributes

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#12476]
Note it is displayed to the right of the attribute, which makes sense but is just weird to look at.
![image](https://user-images.githubusercontent.com/5175830/144178230-c84771b5-d0cc-447f-942f-06d8334c195a.png)

Expected:
when preceeded by attributes, the annotation to appear aligned with the binding

**Comment by psfinaki** [comment]
Weird stuff. The Lens should be shown to the right of the line anyway.
![image](https://user-images.githubusercontent.com/5451366/194323021-1f474a43-1175-46cf-9513-718fd6963c6b.png)
