### ISSUE TITLE
Blazor WebAssembly publish problem

### ISSUE THREAD

**Issue by krauthaufen** [dotnet/fsharp#12470]
When publishing a blazor-wasm project (`dotnet publish` and Visual Studio 2022 Preview 7.0) that references `Microsoft.AspNetCore.Components.WebAssembly` the output-folder does not contain the dll and a simple static HTTP-server (nginx in my case) can't serve the app. Also publishing to Azure doesn't work.

Using nginx i get:
![image](https://user-images.githubusercontent.com/6370801/139721818-038bb443-081e-464f-90f6-31eedd91cde0.png)

I originally submitted the issue in [dotnet](https://github.com/dotnet/aspnetcore/issues/37994) but they seem to think it's F# specific.

Any Help would be greatly appreciated.

Here's a small [repro](https://github.com/krauthaufen/BlazorPublishProblem) for the problem

**Expected behavior**

publish should include all relevant DLLs

**Actual behavior**

doesn't

**Known workarounds**

none

**Related information**

dotnet 6.0

**Comment by vzarytovskii** [comment]
> Okay, thanks for the hint. I just found [fsprojects/Paket#2887](https://github.com/fsprojects/Paket/issues/2887) and [fsprojects/Paket#3999](https://github.com/fsprojects/Paket/issues/3999) which sadly seem to be related and sadly rather inactive.
> 
> I'll try to revive the discussion there..

Yeah, those issues look relevant. I will close this one meanwhile, if you're okay with it.

Please feel free ping me here if it needs to be reopened.
