### ISSUE TITLE
F# Codelens -- change configuration option does not change the display until  the file is closed and reopened

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#12475]
Display after having deselected use colour and closed and re-opened the configuration dialog.

Note it is still using colours to display the annotations.
![image](https://user-images.githubusercontent.com/5175830/144177410-326d8938-139d-444d-9cf6-cc5ea7140897.png)

After closing and reopening file, note that annotations are now grey:
![image](https://user-images.githubusercontent.com/5175830/144177811-eaa56c44-3811-447f-a692-21eff1cdc88a.png)

Expected:
changing an option to immediately impact rendering.

**Comment by psfinaki** [comment]
Yep, this still applies
