### ISSUE TITLE
F# Codelens configuration screen redraw broken.

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#12474]
The Codelens configuration screen redraw is intermittently broken

E.g
![image](https://user-images.githubusercontent.com/5175830/144176178-32c5a52f-6e08-41c7-ac2b-e595a0c14f71.png)

and
![image](https://user-images.githubusercontent.com/5175830/144176361-197940e9-875a-4675-9c0f-4320a3f19a09.png)

Expected:
Redraw to work reliably

**Comment by 0101** [comment]
Cannot reproduce
