### ISSUE TITLE
FSI Debugging with .NET Core Scripting enabled not hitting breakpoints

### ISSUE THREAD

**Issue by blfuentes** [dotnet/fsharp#12485]
Whenever I try to debug a .fsx script file within VS 2022 with the flag "Use .NET Core Scripting" under Options>F# Tools>F# Interactive set to true, the breakpoints are not hit by the debugger.

**Repro steps**

1. Enable "Script Debugging" and "Use .NET Core Scripting" under Options > F# Tools > F# Interactive
![image](https://user-images.githubusercontent.com/5121778/144638797-ad475487-3e3d-4cb4-8000-ad483f43e3ea.png)

2. Reset Interactive Session of FSI
3. Set a breakpoint in the code of a .fsx file and try to debug (Alt+Enter/Right Click> Debug in Interactive)
4. Breakpoint will not be hit
![image](https://user-images.githubusercontent.com/5121778/144639037-ff657c9e-156f-45f5-86d2-edd9c446785e.png)

**Expected behavior**

Debugging of .fsx files on VS should be working with "Use .NET Core Scripting" enabled.

**Actual behavior**

Debugging of .fsx files on VS is working only with "Use .NET Core Scripting" disabled.

**Related information**

Don't know if related to this [Produce debug information in .NET Core fsi] https://github.com/dotnet/fsharp/issues/5457

* Windows 10 21H1 (OS Build 19043.1387)
* .NET 6.0 (6.0.100)
* Visual Studio Enterprise 2022 17.0.2
* F# Interactive version 12.0.0.0 for F# 6.0

**Comment by vzarytovskii** [comment]
> Don't know if related to this [Produce debug information in .NET Core fsi] #5457

Yep, it is related to that, we should use a different mechanisms on coreclr

**Comment by vzarytovskii** [comment]
I'm gonna close this one since it's technically a duplicate
