### ISSUE TITLE
Address FSharp.Core 6.0.1 prebuilt appearing in release/6.0.2xx source-build

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/fsharp#12499]
FSharp.Core 6.0.1 is being reported as a source-build prebuilt in release/6.0.2xx.
    release/6.0.2xx source-build - https://dev.azure.com/dnceng/public/_build/results?buildId=1502520&view=results
    release/6.0.2xx source-build prebuilt report - https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvOWVlNmQ0NzgtZDI4OC00N2Y3LWFhY2MtZjZlNmQwODJhZTZkL2J1aWxkSWQvMTUwMjUyMC9hcnRpZmFjdE5hbWUvQnVpbGQrVGFyYmFsbCtGZWRvcmEzMy1PbmxpbmVfQnVpbGRMb2dzX0F0dGVtcHQx0/content?format=file&subPath=%2Fartifacts%2Fprebuilt-report%2Fprebuilt-usage.xml
    
This is also showing up in the [local fsharp source-build leg's prebuilt report](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvOWVlNmQ0NzgtZDI4OC00N2Y3LWFhY2MtZjZlNmQwODJhZTZkL2J1aWxkSWQvMTUwMzAzNC9hcnRpZmFjdE5hbWUvQnVpbGRMb2dzX1NvdXJjZUJ1aWxkX01hbmFnZWRfQXR0ZW1wdDE1/content?format=file&subPath=%2Fartifacts%2Fsource-build%2Fself%2Fprebuilt-report%2Fprebuilt-usage.xml) although the report is polluted with other false prebuilts.

If the FSharp team can explain where/how this prebuilt is coming in the source-build team can help identify the best way to address it.

**Comment by MichaelSimons** [comment]
cc @brettfo

**Comment by KevinRansom** [comment]
@MichaelSimons , what is the quickest way of reproducing this?

**Comment by MichaelSimons** [comment]
>what is the quickest way of reproducing this?

From your local Linux environment run:

``` console
> ./build.sh -c Release --restore --build --pack /p:ArcadeBuildFromSource=true -bl
> cat artifacts/source-build/self/prebuilt-report/prebuilt-usage.xml | grep '"FSharp.Core"'
```

**Comment by KevinRansom** [comment]
@MichaelSimons , thanks

**Comment by dsyme** [comment]
@KevinRansom Says "It was a targets file bug I believe."
