### ISSUE TITLE
Strange `RandomNumberGenerator.Fill` behaviour when returning `Span<T>` from a function

### ISSUE THREAD

**Issue by peterhirn** [dotnet/fsharp#12491]
Running the following console application a few times will eventually create a zero guid (00000000-0000-0000-0000-000000000000) in sample1 list (where allocation happens in a separate function). The C# compiler prevents me from returning `Span<T>` from a function. Does that mean spans should never be returned from a function?

```fsharp
let allocate length =
    let pointer =
        NativePtr.stackalloc<byte> length
        |> NativePtr.toVoidPtr

    Span<byte>(pointer, length)

let guid1 () =
    let span = allocate 16
    RandomNumberGenerator.Fill span
    Guid(span)

let guid2() =
    let pointer =
        NativePtr.stackalloc<byte> 16
        |> NativePtr.toVoidPtr

    let span = Span<byte>(pointer, 16)
    RandomNumberGenerator.Fill span
    Guid(span)

[<EntryPoint>]
let main argv =
    let samples1 = List.init 3 (ignore >> guid1)
    printfn "%A" samples1

    let samples2 = List.init 3 (ignore >> guid2)
    printfn "%A" samples2

    0
```

**Expected behavior**

Random guids.

**Actual behavior**

[00000000-0000-0000-0000-000000000000; b769467f-d804-8dd5-12e3-cc64dc507429; b105ba1b-541e-e606-e5ce-76f0b5d88b5a]
[373d8056-e77c-9fe5-45c6-eb68ef03d051; 689817b0-2b61-18bb-5ff5-861f05045ad3; 9f5027ad-aba8-3303-0c1f-c9308ce7e44f]

**Related information**

https://github.com/GoogleCloudPlatform/functions-framework-dotnet/issues/232

**Comment by dsyme** [comment]
This is by design.  The use of NativePtr.stackalloc in this code is invalid - you get a warning here and the onus is on you to make sure you don't return a pointer (or a Span containing that pointer) from the function where the stackalloc occurs:
```
stdin(34,9): warning FS0009: Uses of this construct may result in the generation of unverifiable .NET IL code. This warning can be disabled using '--nowarn:9' or '#nowarn "9"'.
```

I guess the warning could be more explicit about "do not return any reference to this pointer".

**Comment by peterhirn** [comment]
Thanks for the explanation. I now realized that I'm asking for a stack-pointer to be returned from a function, a typical C beginner error. Guess I forgot that these are real functions, not magic.
