### ISSUE TITLE
In F# 6 fsi, a `float -> float` function dynamically casts `int` input to `float`

### ISSUE THREAD

**Issue by nhirschey** [dotnet/fsharp#12523]
**Repro steps**
This could be known but I could not find this in open or closed recent issues. A float function acts like F# does not have static types when operating on integers.

Using dotnet 6.0.101 or 6.0.100

```fsharp
let f x = x + 1.0
let g (x: float) = x ** 2.0

f 1 // evaluates to 2.0
g 2 //  evaluates to 4.0
f 1m // type error expected float but got decimal

// even with assigned values
let z: int = 3 // val z: int = 3
g z              // evaluates to val it: float = 9.0
```

<img width="514" alt="image" src="https://user-images.githubusercontent.com/5226115/146638867-2ec9d05b-b4fd-490e-a014-6c5543151419.png">

**Expected behavior**

Type error as you get in F# 5.0

<img width="502" alt="image" src="https://user-images.githubusercontent.com/5226115/146638879-e5b63ea6-d27e-4d2c-b791-62fbe9c7ac1c.png">

**Actual behavior**

Dynamic instead of static types.

**Related information**

Provide any related information (optional):

* Windows 11
* dotnet 6.0.1XX
* Editing environment: Seen in fsi command line tool and dotnet interactive notebooks.

**Comment by vzarytovskii** [comment]
It's a new F# feature for type directed conversions.

Here's a link to RFC: https://github.com/fsharp/fslang-design/blob/main/FSharp-6.0/FS-1093-additional-conversions.md

**Comment by nhirschey** [comment]
Thank you for kindly pointing me to the RFC. I now also see that the F# 6.0 announcement very clearly discusses implicit integer conversions. Apologies for missing those.

I get nervous when numeric types start converting because I have code that expects an integer to be an integer. But reading the RFC and experimenting, it's clear a lot of care was put into choosing which conversions were implemented in order to avoid bugs. 

The type system will be a bit harder to explain to beginners (e.g., `3=3.0` vs `3.0=3`), but the change seems to be a net benefit. Thanks again for the explanation.
