### ISSUE TITLE
`task` CE: upcast static coercion failure 

### ISSUE THREAD

**Issue by melanore** [dotnet/fsharp#12554]
Upcast conversion up the hierarchy results in compiler error when used within `task` CE. 
Static cast via `:>` operator works. Ply CE is able to resolve it correctly.

![image](https://user-images.githubusercontent.com/12952261/147660003-6a516a2b-9c8b-4425-8062-516a01798564.png)

**Repro steps**
Minimal reproduce of this issue can be found in this repository - https://github.com/melanore/FSharp6.Tasks.BugReport/blob/master/FSharp6.Tasks.BugReport.Upcast/Program.fs

```
open System.IO
open System.Threading.Tasks

let getMemoryStream () : Task<MemoryStream> =
    let ms = new MemoryStream()
    Task.FromResult ms

let getFileContentStream () : Task<Stream> =
    task {
        let! stream = getMemoryStream()
        return upcast stream
    }
        
let getFileContentStreamWorkaround () : Task<Stream> =
    task {
        let! stream = getMemoryStream()
        return stream :> Stream
    }
```

**Expected behavior**

Compiler is able to figure conversion up the hierarchy within new `task` CE, similarly to Ply.

**Actual behavior**
```
  Program.fs(15, 20): [FS0013] The static coercion from type
    MemoryStream    
to 
    'a    
 involves an indeterminate type based on information prior to this program point. Static coercions are not allowed on some types. Further type annotations are needed.
```

**Related information**

* Operating system: Windows 10
* .NET Runtime: 6.0.100

**Comment by dsyme** [comment]
This is by design, and is a difference to Ply.  I agree it would be nice if you didn't have to to that, but the way type inference works out in the task CE just means the target type is not known to the `upcast`.
