### ISSUE TITLE
Old-style `taskResult` CE based on new `task` CE: transaction scope flow is not respected, resulting in partially committed transactions

### ISSUE THREAD

**Issue by melanore** [dotnet/fsharp#12556]
We use custom `taskResult` CE within company. When we've upgraded to .NET 6, I've decided to switch it's implementation to native `task` instead of depending on `Ply` library. However [TransactionScope](https://docs.microsoft.com/en-us/dotnet/api/system.transactions.transactionscope?view=net-6.0) class from `System.Transactions` stopped working correctly - inner transaction scopes seem to be unaware of outer scope. This issue prevents us from dropping `Ply` in favor of native `task`.

I've managed to reproduce this issue, - not sure whether it's related to incorrect implementation of `taskResult` or indeed a bug within `task` CE implementation. `taskResult` CE is written in old builder style, without [Resumable Code](https://github.com/fsharp/fslang-design/blob/main/FSharp-6.0/FS-1087-resumable-code.md), however it depends on `task` beneath it. Long term plan is to rewrite `taskResult` and other custom `task` dependent CE to Resumable Code version, once best practices for that are settled - https://github.com/dotnet/fsharp/issues/12456, but I assume old style should still work as expected.

**Repro steps**
Minimal reproduce of this issue can be found in this repository - https://github.com/melanore/FSharp6.Tasks.BugReport/tree/master/FSharp6.Tasks.BugReport.TransactionScope

`taskResult` CE builder with minimum methods required for reproduce:

```
module Net6.TaskResult

open System
open System.Threading.Tasks

type TaskResultBuilder() =

    member inline _.Source(task : Task<Result<'a, 'e>>) : Task<Result<'a, 'e>> =
        task

    member inline _.Zero() : Task<Result<unit, 'e>> =
        () |> Result.Ok |> Task.FromResult

    member inline _.Bind(taskResult : Task<Result<'a, 'e>>, binder : 'a -> Task<Result<'b, 'e>>) : Task<Result<'b, 'e>> =
        task {
            match! taskResult with
            | Error e ->
                return Error e
            | Ok d ->
                return! binder d
        }

    member inline _.Delay(generator : unit -> Task<Result<'a, 'e>>) : unit -> Task<Result<'a, 'e>> =
        generator

    member inline _.Using(resource : 'a :> IDisposable, binder : 'a -> Task<Result<'b, 'e>>) : Task<Result<'b, 'e>> =
        task {
            let res = resource
            try
                let! result = binder res
                return result
            finally
                res.Dispose()
        }
        
    member inline _.Run(f : unit -> Task<'m>) = f ()
    
let taskResult = TaskResultBuilder()

// Having members as extensions gives them lower priority in
// overload resolution between Task<'a> and Task<Result<'a, 'e>>.
[<AutoOpen>]
module TaskResultCEExtensions =
    type TaskResultBuilder with
        member inline _.Source(source : Task<'a>) : Task<Result<'a, 'e>> =
            task {
                let! s = source
                return Result.Ok s
            }
```

Example uses Postgres database with Npgsql library. There are 4 transaction scopes, nested within each other.

```
module Main

open System.Transactions
open Npgsql
open Net6.TaskResult

module Db =
    let connectionString = "Host=localhost;Username=postgres;Password=postgres;Database=postgres;Pooling=true"
    
    let openConnectionAsync() = 
        task {
            let conn = new NpgsqlConnection(connectionString)
            do! conn.OpenAsync(Async.DefaultCancellationToken)
            return conn
        }
    
    let createTransactionScope () =
        let opt = TransactionOptions(IsolationLevel=IsolationLevel.ReadCommitted, Timeout=TransactionManager.MaximumTimeout)
        new TransactionScope(TransactionScopeOption.Required, opt, TransactionScopeAsyncFlowOption.Enabled)
       
    let logCurrentCurrentTransactionId (context : string) =
        task {
            use! connection = openConnectionAsync()
            use cmd = connection.CreateCommand()
            cmd.CommandText <- "SELECT txid_current() AS transaction_id;"
            use! reader = cmd.ExecuteReaderAsync()
            let! _more = reader.ReadAsync()
            let transactionId = reader.GetInt64(0)
            printfn $"%s{context}: transaction_id=%i{transactionId}."
        }

let performScopedWork context =
    // TODO: change to taskResult here to change transaction scope behavior
    taskResult {
        use scope = Db.createTransactionScope()
        do! Db.logCurrentCurrentTransactionId $"%s{context}"
        scope.Complete()
    }

let scope3 () =
    taskResult {
        use scope = Db.createTransactionScope()
        do! performScopedWork "scope3"
        scope.Complete()
    }
    

let scope2 () =
    taskResult {
        use scope = Db.createTransactionScope()
        do! performScopedWork "scope2"
        do! scope3 ()
        scope.Complete()
    }
    

let scope1 () =
    taskResult {
        use scope = Db.createTransactionScope()
        do! performScopedWork "scope1"
        do! scope2()
        scope.Complete()
    }

[<EntryPoint>]
let main _argv =
    printfn "Native task computation."
    let _ = scope1().GetAwaiter().GetResult()
    0
```

Execution should result in opening a new ambient transaction once first connection to database was established, and commit of that transaction once outer scope is completed. Instead, each scope results in a brand new transaction.
Notice `performScopedWork` function - in case it uses `task` CE instead of `taskEither` - transaction scope works correctly.

![task_transaction_scope_problem](https://user-images.githubusercontent.com/12952261/147825387-37112681-2946-4141-9be9-abfb6f4394c5.gif)

Problem seems to be somehow correlated with `Delay` method implementation in `taskEither` builder:

Version with bug:

```
member inline _.Delay(generator : unit -> Task<Result<'a, 'e>>) : unit -> Task<Result<'a, 'e>> =
        generator
```

Version without bug:

```
member inline _.Delay(generator : unit -> Task<Result<'a, 'e>>) : unit -> Task<Result<'a, 'e>> =
        fun () -> task {
            let! s = generator ()
            return s
        }
```

![task_transaction_scope_delay_workaround](https://user-images.githubusercontent.com/12952261/147825397-3c128ac4-404b-479a-9868-b9182b566d88.gif)

My only guess regarding Delay workaround is - await of passed generator by accident happens on the same thread where transaction scope was originally defined, resulting in a 'fix', however that's a long shot. It also doesn't answer the question why AsyncLocal is not handled correctly in execution context...

* Operating system: Windows 10
* .NET Runtime: 6.0.100

**Comment by teo-tsirpanis** [comment]
Hello @melanore, I suspect it has something to do with the `ExecutionContext` not being correctly flowed. Can you also provide an equivalent C# code example in that repository to verify it is F#'s problem?

**Comment by melanore** [comment]
@teo-tsirpanis, original reproduce implementation contained bug. The issue is still there, but it's rather related to custom `taskResult` CE when it's implemented using native `task`.  I've adjusted reproduce repo with correct version as well as fixed description in this ticket. Sorry!

**Comment by melanore** [comment]
up

**Comment by dsyme** [comment]
Please see this repo for examples of how to define CEs using resumable code, also please contribute to it: https://github.com/TheAngryByrd/IcedTasks
