### ISSUE TITLE
Preview Build 17.1.0 Preview 3.0 [32104.457.main] doubles up on displaying findall references results.

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#12573]
A project with this source code:

````fsharp
let aValue = 10
let anotherValue = aValue + 4

// For more information see https://aka.ms/fsharp-console-apps
printfn "Hello from F#"
````

Find all references for ````aValue```` produces these results.

![image](https://user-images.githubusercontent.com/5175830/148298957-7dc0c212-fc02-4b89-ba9b-735c3fad6938.png)

Note the enthusiastic doubling of each part of the reported line.

This does not reproduce on Visual Studio 2022: Version 17.0.4

![image](https://user-images.githubusercontent.com/5175830/148299233-d8d0be12-74b7-4d47-b6e4-28becddc1024.png)

**Comment by vzarytovskii** [comment]
I can't reproduce it on `17.1.0 Preview 3.0 [32112.464.d17.1]` (latest `main`):
![image](https://user-images.githubusercontent.com/1260985/149369483-769f76a9-4364-422c-914f-9ee6ca573901.png)

**Comment by vzarytovskii** [comment]
I can't reproduce it on `17.1.0 Preview 3.0 [32112.464.d17.1]` (today's `main`) anymore:
![image](https://user-images.githubusercontent.com/1260985/149369780-8cfa5763-6169-406d-8dd8-76218063ffb7.png)
