### ISSUE TITLE
OR pattern treated as AND pattern when combined with SRTP and active patterns

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#12600]
Consider the following code:

```fsharp
module M =
    let inline private (|HasName|) x = (^a : (member Name: string) x)
    let inline private (|HasAge|) x = (^a : (member Age: int) x)
    let inline private (|HasAge2|) x = (^a : (member Age: string) x)

    let inline printNameAndAge (HasName name & HasAge age) = printfn $"{name} : {age}"
    
    let inline printNameOrAge (HasName x | HasAge2 x) = printfn $"{x}"

M.printNameAndAge {| Name = "a"; Age = 12; Banana = true |} // Prints "A : 12", works as expected

M.printNameOrAge {| Name = "a"; Banana = true |} // Error, does not work as expected
```

**Expected output**: 

```
"a : 12"
"a"
```

**Actual output**:

```
FS0001 The type {| Banana: 'a; Name: 'b |} does not support the operator 'get_Age' (line 12)
```

**What's going on?**

It appears that this definition:

```fsharp
let inline printNameOrAge (HasName x | HasAge2 x) = printfn $"{x}"
```

Has the exact same constraint applied to it as if it were an AND pattern:

![image](https://user-images.githubusercontent.com/6309070/149202583-6f7078cc-e795-42b7-9b7c-cea3a4b49039.png)

I'm not sure if this is expected behavior in some convoluted way, but it's certainly not the way I'd expect the constraint to be resolved. Since the function using `&` (an AND pattern) works as expected, I'd expect this one with `|` (an OR pattern) that satisfies the requirements of an OR pattern to work as if it were an OR pattern.

That is to say, I expect to be able to do the following:

```fsharp
M.printNameOrAge {| Name = "a"; Banana = true |} // Compiles, prints "a"
M.printNameOrAge {| Age= "12"; Banana = true |} // Compiles, prints "12"
```

(note that `Name` and `Age` must be bound to the same name and type in the definition as per pattern matching rules)

**Why?**

* Consistency / Orthogonality - since I can use these active patterns as AND patterns (as far as I can tell), I should be able to use them as OR patterns
* There's certainly a use case here, although it starts to encroach upon the use cases for ad-hoc union types

**Alternative expectation**

I don't think it's possible to encode an `or`-based constraint that it equivalent today:

```fsharp
// This compiles fine
let inline printNameOrAge'< ^a when ^a : (member Name: string) and ^a : (member Age: int)> x = ()

// Unexpected keyword: 'or'
let inline printNameOrAge'< ^a when ^a : (member Name: string) or ^a : (member Age: int)> x = ()
```

If there is no desire to allow `or` constraints, then maybe disallowing the `|` syntax here altogether would be appropriate for consistency's sake. I should be able to get rid of any active patterns and write the same constraints out manually, but I can't do that today unless I remember that the `|` is actually equivalent to `&`, and write out an `and`-based constraint.

**Comment by GratianPlume** [comment]
It's not a bug, Consider the following code:
```
let inline printNameOrAge x =
   match x with
   | HasName x -> printfn $"{x}" // must have `Name`
   | HasAge2 x  -> printfn $"{x}" // must have `Age`

**Comment by dsyme** [comment]
Yes, this is by-design.  Maybe add a language suggestion?

**Comment by cartermp** [comment]
It's certainly not by design that writing code with that pattern, which isn't allowed, still compiles and rewrites it as a different pattern, yes?
