### ISSUE TITLE
Auto implemented static propertis are not allowed on types without constructor

### ISSUE THREAD

**Issue by jl0pd** [dotnet/fsharp#12614]
Static types with and auto-implemented static property and without default constructor fail to compile

**Repro steps**

Declare static class with auto-implemented static property

```fsharp
[<AbstractClass; Sealed>]
type B =
     static member val C = 1
```

**Expected behavior**

Type should be compiled

**Actual behavior**

FS3133 is raised:
`error FS3133: 'member val' definitions are only permitted in types with a primary constructor. Consider adding arguments to your type definition, e.g. 'type X(args) = ...'.`

**Known workarounds**

Add default constructor to type

```fsharp
[<AbstractClass; Sealed>]
type B() =
     static member val C = 1
```

Or use `module`
```fsharp
module B =
    let C = 1
```

**Related information**

* Operating system: Windows 10.0.19042
* .NET Runtime kind: net6.0.1

**Comment by dsyme** [comment]
This is by design for F# 6, as identified by the error message

There's no reason why the restriction can't be lifted - likeiwse with things like allowing static fields in record and union types. 
 Please add a suggestion to fslang-suggestions to track, and I consider it pre-approved
