### ISSUE TITLE
Code scrollbar at bottom frequently hidden 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12624]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-scrollbar-at-bottom-frequently-hidd/1527262)._

---
I frequently use split screen and the priority of appearance of items at the bottom is a problem. 

Other topics, including the history of the code, takes precedence over the bottom (left/right in code) scroll bar. This is the most important thing in the bottom and should never be fully hidden. I am fine with it being a bit small, but I would prefer to be able to set its size and let other things change size around it. OK, that is probably too hard, just give it a minimum size and have it always appear please. 

I attached a screen shot, but I'm not sure how to circle things on it. Note the left pane has no scroll bar at the bottom of the code window, while the right does.

---
#### Feedback Bot on 9/13/2021, 00:41 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/4/2022, 00:01 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by dsyme** [comment]
Closing as this is not an F#-specific thing
