### ISSUE TITLE
F# CodeLens cannot show annotations when set to be above the line

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12625]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F-CodeLens-cannot-show-annotations-when/1530038)._

---
[severity:It bothers me. A fix would be nice]
F# CodeLens could only show annotations when they are set to the right of each line, which would make a line of code visually too long. But when change the setting to show annotations above the line, nothing shows up.

# Repro:
-- In "Options - Text Editor - F# - CodeLens", check "Enable CodeLens" and uncheck "Show annotation to the right instead of above the line".
-- Close and reopen a F# code file.

# Expect:
-- Observe that type signature annotations show up above the line of a variable is defined.

# Actual:
-- Observe that no type signature annotation shows up.

---
#### Feedback Bot on 9/16/2021, 02:02 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/4/2022, 00:01 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by Mic43** [comment]
Feature just does not work - Impact-Low.
This is a joke? Shameful

**Comment by vzarytovskii** [comment]
> Feature just does not work - Impact-Low.
> This is a joke? Shameful

Feature is still experimental and disabled by default, hence the impact. We're still working on proper rendering for it

**Comment by psfinaki** [comment]
Confirming this is broken.

**Comment by vzarytovskii** [comment]
Ok, closing this one, since "above the line" code lens feature was removed (clearly was a bad experiment), we will properly plan the replacement for it.
