### ISSUE TITLE
F# compiler bug: MatchFailureException when parameter name in a let binding is a literal elsewhere

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12623]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F-compiler-bug:-MatchFailureException-w/1606505)._

---
[severity:It's more difficult to complete my work]
This code compiles, but the compiler is doing something strange with the parameter in the let binding, testing it against the literal value of the same name defined elsewhere. This causes the code to be compiled incorrectly, in my opinion. It's not difficult to work around, but the lack of information in the error message / stack trace makes this fairly obscure to track down.

```fsharp
open System
open System.Collections.Generic

[<AutoOpen>]
module MyLibrary =
   [<Literal>]
   let MyLiteral = 1.0

type MyTestFixture() =
   let myfunc (a: float) (b: float) (c: int) (d: float) (MyLiteral: float) =
     let dummy = 0 // so we can set a breakpoint in the function in the debugger
     42 // throws a MatchFailureException on this line: "The match cases were incomplete"
   
member __. MyTest() =
     // do some things
     let res = myfunc 1.0 2.0 3 4.0 5.0 // throws exception within MyFunc
     assert (res = 42)
```

Looking at the lowered code this generates on [sharplab.io](sharplab.io), we can see what happened:

```csharp
using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using Microsoft.FSharp.Core;

[assembly: FSharpInterfaceDataVersion(2, 0, 0)]
[assembly: AssemblyVersion("0.0.0.0")]
[CompilationMapping(SourceConstructFlags.Module)]
public static class @_
{
    [Serializable]
    [CompilationMapping(SourceConstructFlags.ObjectType)]
    public class MyTestFixture
    {
        public void MyTest()
        {
            int num = myfunc(1.0, 2.0, 3, 4.0, 5.0);
        }

[CompilationArgumentCounts(new int[] { 1, 1, 1, 1, 1 })]
        [CompilerGenerated]
        internal int myfunc(double a, double b, int c, double d, double _arg1)
        {
            if (_arg1 == 1.0)
            {
                return 42;
            }
            throw new MatchFailureException("_.fs", 10, 57);
        }
    }

[AutoOpen]
    [CompilationMapping(SourceConstructFlags.Module)]
    public static class MyLibrary
    {
        [Literal]
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        public const double MyLiteral = 1.0;
    }
}
namespace <StartupCode$_>
{
    internal static class $_
    {
    }
}
```

---
#### Feedback Bot on 12/7/2021, 07:30 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by dsyme** [comment]
This is by design.  Note `(MyLiteral: float) ` is a pattern matching only `1.0`.

Once something is in scope as a literal, then when it is used in a pattern it will be matching that thing only.  

Compiling the code gives a warning indicating the problem:
```
a.fs(10,58): warning FS0025: Incomplete pattern matches on this expression. For example, the value '0.0' may indicate a case not covered by the pattern(s).
```
