### ISSUE TITLE
Incorrect docs/constraints for LanguagePrimitives.PhysicalHash

### ISSUE THREAD

**Issue by cmeeren** [dotnet/fsharp#12629]
The [doc comment for `LanguagePrimitives.PhysicalHash`](https://github.com/dotnet/fsharp/blob/f860e782f10ba4e750e53df216ce8ff96b570e01/src/fsharp/FSharp.Core/prim-types.fsi#L1277-L1283) says:

> The physical hash. Hashes on the object identity, except for value types, where we hash on the contents.

In other words, it seems like this function should work for both reference and value types. However, the constraints (as linked to above) require the input to be a reference type.

One of them should be fixed.

In the meantime, how can this be worked around? I am in need of a function that works as `LanguagePrimitives.PhysicalHash` is currently documented to work (but does not actually work).

**Comment by dsyme** [comment]
Fixed in https://github.com/dotnet/fsharp/pull/12791
