### ISSUE TITLE
Unexpected priority of Implicit casting in expressions

### ISSUE THREAD

**Issue by En3Tho** [dotnet/fsharp#12630]
**Repro steps**
![image](https://user-images.githubusercontent.com/37334640/150501120-ff0bf515-22df-46ee-a923-9052a5e34391.png)

**Expected behavior**

Imlicit casting works after plus is applied (at least with parentheses)

**Actual behavior**

Implicit casting gets applied only to a part of expression and of whole expression. Adding parentheses to indicate a whole expression doesn't help either.

**Known workarounds**

listed in picture above

**Comment by vzarytovskii** [comment]
Interestingly enough, it works fine with normal function applications:
```fsharp
type A = { Value: System.Nullable<int> }
let foo (a: int) = a
let test (value: int) = { Value = foo 1 }
```
Or even
```fsharp
type A = { Value: System.Nullable<int> }
let add (a: int) (b:int) = a + b
let test (value: int) = { Value = add 1 2 }
```

but the following doesn't work:
```fsharp
type A = { Value: System.Nullable<int> }
let test (value: int) = { Value = (+) 1 1 }
```
resulting in:
```
let test (value: int) = { Value = (+) 1 1 };;
  ----------------------------------------^

stdin(27,41): error FS0001: The type 'System.Nullable<int>' does not match the type 'int'
```

**Comment by dsyme** [comment]
This is by design - the ambiguity of "+" gets resolved at the "let".

Implicit casting has many such quirks when combined with generic operations such as "+" and works most reliably at method calls.  The warnings for its use are given for a reason and generally should be heeded
