### ISSUE TITLE
Can't restore an F# console project in VS2022

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12656]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cant-restore-an-F-console-project-in-V/1574555)._

---
[regression] [worked-in:17.1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1102	Unable to find package FSharp.Core with version (>= 6.0.2)
  - Found 47 version(s) in nuget.org [ Nearest version: 6.0.1 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in C:\Program Files\dotnet\library-packs	ConsoleApp2

---
#### Feedback Bot on 11/8/2021, 10:32 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by dsyme** [comment]
This is a duplicate, it has been fixed recently cc @KevinRansom
