### ISSUE TITLE
FSharp projects don't compile in VS2022 after upgrading to latest version.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12658]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/FSharp-projects-dont-compile-in-VS2022-/1577963)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:Not sure]
Hi. I upgraded to the latest version of VS 2022 
Version 17.1.0 Preview 1.0

F# projects no longer compile for me with this error:

```
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
2>C:\code\nogithub\FsGravity\FsGravity\FsGravity.fsproj : error NU1102: Unable to find package FSharp.Core with version (>= 6.0.2)
2>C:\code\nogithub\FsGravity\FsGravity\FsGravity.fsproj : error NU1102:   - Found 47 version(s) in nuget.org [ Nearest version: 6.0.1 ]
2>C:\code\nogithub\FsGravity\FsGravity\FsGravity.fsproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
```

It compiles fine from dotnet CLI then it uses 6.0.1. 

I have seen the same problem on two machines.

I live in Scandinavia just FYI in case there's a CDN problem?

---
#### Feedback Bot on 11/10/2021, 06:40 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### william bright on 11/15/2021, 06:42 AM: 

<p>I also have the same issue. It appears the issue I’ve seen comes around the fact that somehow VS references the 6.0.2 version which isn’t live yet in nuget, and so it breaks. The latest version as of time of writing is 6.0.1.</p>

#### Alessandro Piccione on 12/8/2021, 03:19 AM: 

<blockquote>
<p>somehow VS references the 6.0.2 version</p>
</blockquote>
<p>True, but <strong>why?</strong></p>
<p>A simple solution with a simple ConsoleApp.fsproj like this does not refer to any specific version, where the nuget behavior is defined?</p>
<pre><code class="language-xml"><span class="hljs-tag">&lt;<span class="hljs-name">Project</span> <span class="hljs-attr">Sdk</span>=<span class="hljs-string">"Microsoft.NET.Sdk"</span>&gt;</span>
  <span class="hljs-tag">&lt;<span class="hljs-name">PropertyGroup</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-name">OutputType</span>&gt;</span>Exe<span class="hljs-tag">&lt;/<span class="hljs-name">OutputType</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-name">TargetFramework</span>&gt;</span>net6.0<span class="hljs-tag">&lt;/<span class="hljs-name">TargetFramework</span>&gt;</span>
  <span class="hljs-tag">&lt;/<span class="hljs-name">PropertyGroup</span>&gt;</span>
  <span class="hljs-tag">&lt;<span class="hljs-name">ItemGroup</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-name">Compile</span> <span class="hljs-attr">Include</span>=<span class="hljs-string">"Program.fs"</span> /&gt;</span>
  <span class="hljs-tag">&lt;/<span class="hljs-name">ItemGroup</span>&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-name">Project</span>&gt;</span>
</code></pre>
<p><img src="https://aka.ms/dc/image?name=Ba9512c1060b64c96a28a348168a397aa637745591009564467_20211208-111819-image.png&amp;tid=a9512c1060b64c96a28a348168a397aa637745591009564467" alt="image.png"></p>

---
### Original Solutions
(no solutions)

**Comment by dsyme** [comment]
This is a duplicate, see also https://github.com/dotnet/fsharp/issues/12656, it has been fixed recently by including FSharp.Core with .NET SDK
