### ISSUE TITLE
Cannot Disable Most Recent Items In Settings > General

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12655]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cannot-Disable-Most-Recent-Items-In-Sett/1567748)._

---
[severity:It bothers me. A fix would be nice]
I don't use this feature in any software that offers it. It has no value for me. 

There is no mechanism to enable me to disable it or set the number of items it tracks to 0.

---
#### Feedback Bot on 11/1/2021, 01:26 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by dsyme** [comment]
This is not an F#-specific issue
