### ISSUE TITLE
F# 6.0.2 not found error when creating a new F# project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12659]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F-602-not-found-error-when-creating-a/1584397)._

---
[regression] [worked-in:17.1.0 Preview 1.0]
New project is looking for F# version 6.0.2 which does not seem to exist.

Changing the reference to 6.0.1 works but there me a packaging issue that needs to be addressed.

---
#### Feedback Bot on 11/15/2021, 07:02 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by dsyme** [comment]
This is a duplicate, see also #12656, it has been fixed recently by including FSharp.Core with .NET SDK
