### ISSUE TITLE
Continuously get an error when building a project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12651]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Continuously-get-an-error-when-building-/1619164)._

---
[severity:It bothers me. A fix would be nice]
Please see the screenshot. Every time I build I get the error banner below the top toolbar. The build is successful and everything works, but it is quite annoying and it doesn't clarify what's wrong.  I also attach the linked logfile.

---
#### Feedback Bot on 12/21/2021, 07:09 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by dsyme** [comment]
There is no screenshot, I will close this as more info is needed
