### ISSUE TITLE
Incorrect Importing of Namespaces in F# Source Files 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12660]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Incorrect-Importing-of-Namespaces-in-F-/1595724)._

---
[severity:I'm unable to use this version]
So when you create a file such as

```
namespace MyNamespace

module MyModule =
    ()
```

If you write some code that imports a namespace

```
namespace MyNamespace

module MyModule =
    let getGuid = Guid.NewGuid()
```

If you import that namespace using the `ctrl+.` stuff, it will do this

```
open System

namespace MyNamespace

module MyModule =
```

which is incorrect, it needs to be:

```
namespace MyNamespace

open System

module MyModule =
```

---
#### Feedback Bot on 11/25/2021, 09:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by dsyme** [comment]
Looks like the thing fixed by #12443
