### ISSUE TITLE
Cannot quote a TryParse

### ISSUE THREAD

**Issue by Happypig375** [dotnet/fsharp#12672]
**Repro steps**

```
Microsoft (R) F# Interactive version 12.0.0.0 for F# 6.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> <@ fun (x: string) -> System.DateTime.TryParse x @>;;

  <@ fun (x: string) -> System.DateTime.TryParse x @>;;
  ----------------------^^^^^^^^^^^^^^^^^^^^^^^^^^

stdin(1,23): error FS0462: Quotations cannot contain this kind of type

> 
```

**Expected behavior**

Since there is no byref involved, instead a tuple, this quotation should succeed.

**Actual behavior**

Quotation fails.

**Known workarounds**

```fs
let f = System.DateTime.TryParse: string -> _
<@ fun (x:string) -> f x @>
```
but this creates free variables.

**Related information**

Provide any related information (optional):

* Operating system Windows
* .NET Runtime kind (.NET Core, .NET Framework, Mono) .NET 6
* Editing Tools (e.g. Visual Studio Version, Visual Studio) VS2022

**Comment by dsyme** [comment]
This is by design.  The desugaring of ` <@ fun (x: string) -> System.DateTime.TryParse x @>` contains an address-of operation involving a byref.  In the case
```fsharp
let f = System.DateTime.TryParse: string -> _
<@ fun (x:string) -> f x @>
```
the desugaring is outside the quotation.
