### ISSUE TITLE
List Iteration more efficient than Recursive Tail Call

### ISSUE THREAD

**Issue by liboz** [dotnet/fsharp#1267]
Iterating a list with a for loop is more efficient than using a recursive tail call because the recursive tail call does 2 calls to the function TailOrNull.
#### Repro steps

Here's a simple timing script demonstrating the behavior (Release build 32-bit VS 2015):

```
open System.Diagnostics

let stopWatch =
  let sw = Stopwatch ()
  sw.Start ()
  sw

let timeIt (name : string) (alist: int list) (iterations: int) (a : int list -> int) : unit = 
  let t = stopWatch.ElapsedMilliseconds
  let v = a (alist)
  for i = 1 to iterations do
    a alist |> ignore
  let d = stopWatch.ElapsedMilliseconds - t
  printfn "%s, elapsed %d ms, result %A" name d v

let add_rec xs =
    let rec add xs acc =
        match xs with
        | [] -> acc
        | h::t -> add t (acc + 1)
    add xs 0

let add_mutable (xs: 'T list) =
    let mutable count = 0
    for x in xs do
        count <- count + 1
    count

[<EntryPoint>]
let main argv =
  let iterations = 1000000
  let testList = [1..1000]
  timeIt "recursion" testList iterations add_rec
  timeIt "mutable" testList iterations add_mutable
  0
```

gives the following result:

```
recursion, elapsed 1425 ms, result 1000
mutable, elapsed 1156 ms, result 1000
```

Decompiling to IL shows that the recursive tail version calls get_TailOrNull twice per iteration.
#### Expected behavior

The performance should be effectively equivalent.
#### Actual behavior

The tail recursive implementation is 300ms slower.
#### Known workarounds

Use the iteration instead or 64bit.
#### Related information
- Operating system - Windows 7/10
- Branch - F# 4.0
- .NET Runtime, CoreCLR or Mono Version - 4.5.2/4.6/4.61
- Editing Tools (e.g. Visual Studio Version) - VS 2015
- Links to performance testing scripts - included in issue body

Decompiled info:

add:

```
.method assembly static 
    int32 add@18<b> (
        class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!!b> xs,
        int32 acc
    ) cil managed 
{
    // Method begins at RVA 0x20d8
    // Code size 28 (0x1c)
    .maxstack 5
    .locals init (
        [0] class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!!b>
    )

    // loop start
        IL_0000: ldarg.0
        IL_0001: call instance class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!0> class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!!b>::get_TailOrNull()
        IL_0006: brfalse.s IL_001a

        IL_0008: ldarg.0
        IL_0009: stloc.0
        IL_000a: nop
        IL_000b: ldloc.0
        IL_000c: call instance class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!0> class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!!b>::get_TailOrNull()
        IL_0011: ldarg.1
        IL_0012: ldc.i4.1
        IL_0013: add
        IL_0014: starg.s acc
        IL_0016: starg.s xs
        IL_0018: br.s IL_0000
    // end loop

    IL_001a: ldarg.1
    IL_001b: ret
} // end of method Program::add@18

```

add_mutable:

```
.method public static 
    int32 add_mutable<T> (
        class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!!T> xs
    ) cil managed 
{
    // Method begins at RVA 0x210c
    // Code size 36 (0x24)
    .maxstack 4
    .locals init (
        [0] int32 count,
        [1] class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!!T>,
        [2] class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!!T>
    )

    IL_0000: nop
    IL_0001: ldc.i4.0
    IL_0002: stloc.0
    IL_0003: ldarg.0
    IL_0004: stloc.1
    IL_0005: ldloc.1
    IL_0006: call instance class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!0> class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!!T>::get_TailOrNull()
    IL_000b: stloc.2
    // loop start (head: IL_000c)
        IL_000c: ldloc.2
        IL_000d: ldnull
        IL_000e: cgt.un
        IL_0010: brfalse.s IL_0022

        IL_0012: ldloc.0
        IL_0013: ldc.i4.1
        IL_0014: add
        IL_0015: stloc.0
        IL_0016: ldloc.2
        IL_0017: stloc.1
        IL_0018: ldloc.1
        IL_0019: call instance class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!0> class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!!T>::get_TailOrNull()
        IL_001e: stloc.2
        IL_001f: nop
        IL_0020: br.s IL_000c
    // end loop

    IL_0022: ldloc.0
    IL_0023: ret
} // end of method Program::add_mutable

```

**Comment by forki** [comment]
wow. interesting.

From dotpeek:

![image](https://cloud.githubusercontent.com/assets/57396/16155943/05cc6fc2-34b2-11e6-9be6-1877f5040e4d.png)

**Comment by forki** [comment]
@dsyme I guess there is a reason for this to satisfy the general case, but maybe we can apply optimization for common looping patterns?

**Comment by liboz** [comment]
It appears switching to 64bit brings the 2 implementations to parity (but also slows both of them down compared to 32bit). Maybe its what the JIT does. 

The code for the iteration loop appears to be [here](https://github.com/Microsoft/visualfsharp/blob/7ff92d4c984a6a074da7a797538b256b6499c0fb/src/fsharp/TastOps.fs#L7853). Perhaps the recursive implementation could also just use that instead?

**Comment by dsyme** [comment]
I believe this is related to ``#if OPTIMIZE_LIST_MATCHING`` in PatternMatchCompilation.fs.  There is a comment:

```
// This is an initial attempt to remove extra typetests/castclass for simple list pattern matching "match x with h::t -> ... | [] -> ..."
// The problem with this technique is that it creates extra locals which inhibit the process of converting pattern matches into linear let bindings.
```
I'd need to look more closely to see what the exact problems are - i.e. are the extra locals a problem for perf or for some logical part of compilation.

Fixing this would improve (or not) _all_ list pattern matching, not just recursive iteration loops, so it's A Good Thing if we get it right.

It's interesting that the 64-bit JIT doesn't suffer from the duplicated call, perhaps it's doing good CSE. Would be good to get an assembly code expert to look. But in any case, producing cleaner IL with manifestly better performance properties is nearly always a good thing.

**Comment by forki** [comment]
that OPTIMIZE_LIST_MATCHING doesn't compile, but I will try if I can get it working

**Comment by forki** [comment]
In #1268 I tried to activate that switch and fixed compile errors.

This is what the compile is producing now:
![image](https://cloud.githubusercontent.com/assets/57396/16170224/e040df8c-354b-11e6-8e27-8758f88200cf.png)

**Comment by forki** [comment]
so it looks like we only have one call to get_TailOrNull, but we now call get_HeadOrDefault whichout using the value.

    PS> .\ConsoleApplication2.exe
    recursion, elapsed 1430 ms, result 1001
    mutable, elapsed 1145 ms, result 1000

**Comment by forki** [comment]
I guess https://github.com/Microsoft/visualfsharp/pull/1268/files#diff-7a1d0e70c7e2c5f8998fca7b3244565fR515 is not correct. I assume it was just not implemented.

**Comment by forki** [comment]
Wow just saw that applying the "optimization" also changes the result ;-)

**Comment by forki** [comment]
If anyone has an idea, I'd would be up for testing things out.

**Comment by cartermp** [comment]
Just to note, with this test they seem to be pretty much the same CPU and memory-wise:

```fsharp
// Learn more about F# at http://fsharp.org

open BenchmarkDotNet.Attributes
open BenchmarkDotNet.Running

let add_rec xs =
    let rec add xs acc =
        match xs with
        | [] -> acc
        | h::t -> add t (acc + 1)
    add xs 0

let add_mutable (xs: 'T list) =
    let mutable count = 0
    for x in xs do
        count <- count + 1
    count

[<MemoryDiagnoser>]
type Bench() =
    let testList = [1..1000]

    [<Benchmark(Baseline=true)>]
    member __.MutableAdd() =
        add_mutable testList |> ignore
    [<Benchmark>]
    member __.RecusiveAdd () =
        add_rec testList |> ignore

[<EntryPoint>]
let main argv =
    let summary = BenchmarkRunner.Run<Bench>()
    printfn "%A" summary
    0 // return an integer exit code
```

``` ini

BenchmarkDotNet=v0.11.5, OS=macOS Mojave 10.14.5 (18F132) [Darwin 18.6.0]
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.0.100-preview4-011223
  [Host]     : .NET Core 3.0.0-preview4-27615-11 (CoreCLR 4.6.27615.73, CoreFX 4.700.19.21213), 64bit RyuJIT DEBUG
  DefaultJob : .NET Core 3.0.0-preview4-27615-11 (CoreCLR 4.6.27615.73, CoreFX 4.700.19.21213), 64bit RyuJIT


```
|      Method |     Mean |     Error |    StdDev | Ratio | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------ |---------:|----------:|----------:|------:|------:|------:|------:|----------:|
|  MutableAdd | 1.144 us | 0.0151 us | 0.0141 us |  1.00 |     - |     - |     - |         - |
| RecusiveAdd | 1.144 us | 0.0101 us | 0.0089 us |  1.00 |     - |     - |     - |         - |

While it's true that the `get_TailOrNull` call is emitted 2x as often, it doesn't seem to have an effect in practice.

**Comment by dsyme** [comment]
Closing this based on @cartermp 's analysis
