### ISSUE TITLE
Invalid old XML might remain in XML doc files.

### ISSUE THREAD

**Issue by goswinr** [dotnet/fsharp#12702]
using dotnet 6.0.101:

Invalid old XML might remain in XML doc files when overall length gets reduced.

Starting with   `dotnet new classlib -lang "F#"` and adding some comments, the XML looks OK: 
![image](https://user-images.githubusercontent.com/884885/152677937-dffce023-dc59-4142-92dc-c8f735cb19d6.png)

But after deleting the comments and rebuilding, they remain in the XML file. The XML structure becomes invalid:
![image](https://user-images.githubusercontent.com/884885/152677962-08359e8b-9915-444e-a63b-7c7ae55b3492.png)
The solution might be to just clear the XML file before writing to it again during the build process.

**Comment by dsyme** [comment]
Ugh, looks like we're mistakenly creating the XML file in overwrite mode, not clearing it if it already exists

@vzarytovskii This may have been to do with file system rejigging ?

**Comment by dsyme** [comment]
NIce

**Comment by goswinr** [comment]
Thanks for the fix, I just tried with dotnet SDK 6.0.201 from March 8. There seems to be still a problem. Should this fix be in dotnet SDK 6.0.201 ?

**Comment by goswinr** [comment]
The problem is still there in SDK `6.0.201` from March 8.
But its fixed in SDK `7.0.100-preview.2.22153.17`

**Comment by jcmrva** [comment]
Is there a plan to include this in SDK 6.* at some point? We have a post-build step that uses the xml file & have to run `dotnet clean` to make it work.
