### ISSUE TITLE
Don't ship the FSharp.Core XmlDocs as Content in the nuget package

### ISSUE THREAD

**Issue by baronfel** [dotnet/fsharp#12706]
**Is your feature request related to a problem? Please describe.**

The current FSharp.Core nuget package ships the xmldocs for the library in contentFiles, in addition to the lib folder. This results in the xmldocs being added as Content to users' projects.

This change was made for .NET 5 I believe at my request to make tooltips for F# Scripts in Ionide better, but I think there is another way to get the desired effect.

**Describe the solution you'd like**

I'd like the xmldocs to be not marked as content anymore in the shipped FSharp.Core package.

**Describe alternatives you've considered**

Keep shipping the xmldocs as content.

**Additional context**

Current layout: 
![image](https://user-images.githubusercontent.com/573979/152844113-babb3ffe-6732-49d5-b0a6-df2009da7818.png)

**Comment by dsyme** [comment]
THis is surely a bug, that file really shouldn't be appearing as content?

**Comment by nojaf** [comment]
Hello, I believe this matters. A while ago I encountered this:

``` https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/duplicate-files-in-output while dotnet pack.
 C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets(112,5): error NETSDK1152: Found multiple publish output files with the same relative path: C:\Users\nojaf\.nuget\packages\fsh
 arp.core\6.0.1\contentFiles\any\netstandard2.0\FSharp.Core.xml, C:\Users\nojaf\.nuget\packages\fsharp.core\6.0.1\contentFiles\any\netstandard2.1\FSharp.Core.xml. [C:\Users\nojaf\Projects\fantomas\src\Fantomas.CoreGlobalTool\Fantomas.
 CoreGlobalTool.fsproj]
```

I'm not going to claim I remember the full details but it was something something multiple targets and then the error above.

**Comment by baronfel** [comment]
@nojaf you set the project file property flag to disable the warning to get around this, right? if so I might dig in a bit more later to see how the resolution is happening. The implicit FSharp.Core reference added by the fsharp SDK targets strips the content file, so projects that use Paket to manage FSharp.Core would be the ones that see this.

**Comment by dsyme** [comment]
> The implicit FSharp.Core reference added by the fsharp SDK targets strips the content file, so projects that use Paket to manage FSharp.Core would be the ones that see this.

What about projects that use an explicit reference?
