### ISSUE TITLE
Type provider design-time assembly loading from `lib/net6.0` instead of `typeproviders/fsharp41/net6.0`

### ISSUE THREAD

**Issue by mettekou** [dotnet/fsharp#12715]
My type provider https://github.com/mettekou/FSharp.Data.Tdms breaks as a NuGet dependency for a project or script using the .NET 6 SDK on Linux. The design-time assembly seems to be loading from the wrong directory.

**Repro steps**

The easiest way to reproduce the issue is to use an F# script:

```fsharp
#r "nuget:FSharp.Data.Tdms,1.0.0-alpha.68"

open FSharp.Data

(* The code below is irrelevant, the issue occurs before the type provider loads *)

type CurrentSweep = TdmsProvider< Sample = @"/home/mettekou/Downloads/CurrentSweep_35barProp.tdms", WriteIndex = false >

let sample = CurrentSweep(@"/home/mettekou/Downloads/CurrentSweep_35barProp.tdms", false)

printfn "%A" sample.Current.M_TSIM_CUR_I1.Data
```

Alternatively, add the package as a NuGet dependency for a project.

**Expected behavior**

The F# interactive correctly loads the design-time assembly from `typeproviders/fsharp41/net6.0` and the script runs.

**Actual behavior**

The F# interactive attempts to load the design-time assembly from `lib/net6.0` instead of from `typeproviders/fsharp41/net6.0`, failing with the following error:

```
/tmp/nuget/96672--2c3bf598-55c8-4718-92c5-caccd738cd3e/Project.fsproj.fsx(11,1): error FS3031: The type provider '/home/mettekou/.nuget/packages/fsharp.data.tdms/1.0.0-alpha.73/lib/net6.0/FSharp.Data.Tdms.dll' reported an error: Assembly attribute 'TypeProviderAssemblyAttribute' refers to a designer assembly 'FSharp.Data.Tdms.DesignTime.dll' which cannot be loaded from path '/home/mettekou/.nuget/packages/fsharp.data.tdms/1.0.0-alpha.73/lib/net6.0/FSharp.Data.Tdms.DesignTime.dll'. The exception reported was: System.IO.FileNotFoundException - Could not load file or assembly '/home/mettekou/.nuget/packages/fsharp.data.tdms/1.0.0-alpha.73/lib/net6.0/FSharp.Data.Tdms.DesignTime.dll'. The system cannot find the file specified.
```

**Known workarounds**

Copying the design-time assembly and its dependencies to the `lib/net6.0` directory in the NuGet package resolves the issue for .NET SDK builds and interactive use on Linux, but causes builds to break for projects in Visual Studio 2022 on Windows. Visual Studio complains about duplicate type definitions across the run-time and design-time assemblies, as per https://github.com/mettekou/FSharp.Data.Tdms/issues/10.

```Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'File' exists in both 'FSharp.Data.Tdms.DesignTime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'FSharp.Data.Tdms, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'	ConsoleApp1	C:\Users\mettekou\source\repos\ConsoleApp1\ConsoleApp1\Program.cs	1	Active
```

**Related information**

* .NET SDK 6.0.100 on Arch Linux, kernel 5.16.8
* Visual Studio 17.0.6 on Windows 10 21H2 (also reproducible on 17.0.5, have not checked for earlier versions)

**Comment by dsyme** [comment]
@mettekou What happens if you build the DesignTime assembly as netstandard2.0 or net5.0?  TBH we'd always recommend netstandard2.0 so the TP can be used in conjunction with editor tooling such as Visual Studio

Looking over the compiler code, this looks a little suspicious, though I'm not sure it's relevant, this should now be 6.0 I believe.
```
                // Running on coreclr but no deps.json was deployed with the host so default to 5.0
                Some "net5.0"
```

**Comment by dsyme** [comment]
> Edit: spoke too soon, targeting net5.0 does not resolve the issue in Visual Studio 2022, only for .NET SDK builds.

To use a type provider from within both VS2022 and .NET SDK compilation you will need to have your design-time component target netstandard2.0.  VS2022 runs .NET Framework code.

**Comment by dsyme** [comment]
> @dsyme Thank you, targeting net5.0 resolved the issue for me. Tangential question: will my uses of task { ... } computation expressions still be compiled to state machines when compiling with the .NET 6 SDK, even when my F# projects target net5.0?

Task compilation will work when targeting netstandard2.0+, net5.0+, net48+ with FSharp.Core 6.0.0 and F# 6.

**Comment by mettekou** [comment]
> > Edit: spoke too soon, targeting net5.0 does not resolve the issue in Visual Studio 2022, only for .NET SDK builds.
> 
> To use a type provider from within both VS2022 and .NET SDK compilation you will need to have your design-time component target netstandard2.0 (or net48+net5.0). VS2022 runs .NET Framework code.

Sadly, I need some methods on `’t Span` and friends which aren’t available on .NET Standard 2.0, so this isn’t an option for me.

**Comment by KevinRansom** [comment]
@mettekou , the Visual Studio IDE process that hosts the F# Editor still targets the Windows Desktop Framework and so design time components for Visual Studio are required to be netstandard2.0.  We hope to be able to do something to solve this eventually, but there are are no firm plans to address this right now.

I am sorry for the inconvenience.

Kevin

**Comment by dsyme** [comment]
I will close this as the issue can only be resolved by targeting netstandard2.0
