### ISSUE TITLE
Type deduction error occurs when using multiple `Computation Expressions` consecutively

### ISSUE THREAD

**Issue by GratianPlume** [dotnet/fsharp#12712]
Consider the following code:
```
type Builder1 =
   | Builder1 of int

   member __.Yield x = x
   member __.Delay f = f()

type Builder2 =
   | Builder2
   member __.Yield x = Builder1 x
   member __.Delay f = f()

  let foo1() = (Builder2{ yield 9 }){ yield 0}
  let foo2() = Builder2{ yield 9 }{ yield 0}
```
`foo1`work well, but `foo2` raise an error(fs0193) occurred while compiling.

when I change the code to:
```
type Builder1 =
   | Builder1 of int

   member __.Yield x = Builder1 x // change this row
   member __.Delay f = f()

type Builder2 =
   | Builder2
   member __.Yield x = Builder1 x
   member __.Delay f = f()

  let foo1() = (Builder2{ yield 9 }){ yield 0}
  let foo2() = Builder2{ yield 9 }{ yield 0}
```
they all work well.
I'm guessing the error occurs because, without parentheses, type inference ends the first time the expression is evaluated.

**Comment by dsyme** [comment]
This is either by design or some kind of other mistake.  At least it's not entirely clear why you'd expect this to work?  If you add a few more type annotations to the builder methods your problem will likely resolve.
