### ISSUE TITLE
❓Survey: Your experience in this repo

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#12714]
Whether you are a frequent visitor or a relatively new visitor of the repo, please tell us about your experience with our issue support and/or PR contribution process.

The survey should only take a few minutes, and you can answer for up to 3 repos:

https://www.surveymonkey.com/r/8QTQTGJ?Source=fsharp

**Comment by teo-tsirpanis** [comment]
@KevinRansom the survey is closed. This issue should be closed and unpinned.
