### ISSUE TITLE
Tokenizer errors when using static resolved type parameters.

### ISSUE THREAD

**Issue by brenoafb** [dotnet/fsharp#12725]
I am having tokenizer problems when creating types that have SRTPs. 

**Repro steps**

In [this example](https://sharplab.io/#v2:DYLgZgzgNALiBOBXAdlAJiA1AHxgTwAcBTAAgFFkBjAezSPgB4ByAQwD4SBecq2+gZRiIARgFgAUBPzEeMeHgYA9ACoSS6kgHcAFkWQkVJECQAUEGCxgBLSiQC2RO8Po8adeEdd9GB5STYAlBycahphJADeJACSyASIMAAilizGhgC+oeEa5pY29o7OHrHxMBRu9Mbl3gy+/lxZ2WEmhsYmDk4u1e6e3fS1hoEBEkA==), we get the following error:

```
error FS0010: Unexpected infix operator in type definition. Expected '(' or other token.
```

If we insert a space between the `<` and `^` characters ([here](https://sharplab.io/#v2:DYLgZgzgNALiBOBXAdlAJiA1AHxgTwAcBTAAgFFkBjAezSPgB4ByAQwD4SBecq2+gZRiIARgFgAUBPzEeMeHgYkAegBUJJDSQDuACyLJlKkiBIAKCDBYwAlpRIBbIveH0eNOvGNu+jQyTYAlByc6pphJADeJACSyASIMAAiViwmqiQAvqHhmhZWtg5OLp6x8TAU7vQmFT6K6cHZOWGm6Samjs6uNR5e3fR1RoEBEkA==)), this error goes away. However the compiler now reports another error.

```
error FS0010: Unexpected symbol ')' in expression
```

**Expected behavior**

Code should compile correctly.

**Actual behavior**

Token errors are reported.

**Known workarounds**

Haven't found any.

**Platform information**

- .NET Core 6.0.102
- Linux

**Comment by dsyme** [comment]
This is by design for F# 6 and before, please just add a space.   Record a language suggestion at https://github.com/fsharp/fslang-suggestions

The use of SRTP on the generic parameters of types is rarely possible - the code using these must be inlined.  For example:

```
type Encoder<'a> = EncoderStub

type Entry() =
         static member inline GetInputEncoder< ^U  when ^U : (static member get_Encoder : unit -> Encoder< ^U >)>() : Encoder< ^U > =
             (^U : (static member get_Encoder : unit -> Encoder< ^U >)())

```
