### ISSUE TITLE
F# Interactive pane doesn't work - just rings the bell

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12735]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F-Interactive-pane-doesnt-work---just-/1651917)._

---
[severity:I'm unable to use this version]
I have an F# solution open, and I want to enter some expressions to double check the usage of a function.  I hit Enter to start the interpreter, and I see:

Welcome to F# Interactive for .NET Core in Visual Studio. To execute code, either
      1. Use 'Send to Interactive' (Alt-Enter or right-click) from an F# script. The F# Interactive process will
         use any global.json settings associated with that script.
      2. Press 'Enter' to start. The F# Interactive process will use default settings.
    > 

Microsoft (R) F# Interactive version 12.0.0.0 for F# 6.0
    Copyright (c) Microsoft Corporation. All Rights Reserved.
    
For help type #help;;

> 

However, when I enter any expression, `let` binding, or other construct and hit *Alt-Enter*, the terminal bell rings and nothing else happens. Plain *Enter* doesn't work either.  I have tried resetting the interpreter.

---
#### Feedback Bot on 2/2/2022, 10:35 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by dsyme** [comment]
I can't repro this.  We're need more exact repro, but there's not enough to go on here.
