### ISSUE TITLE
FSharp.Compiler.Service 41.0.2 depends on the ulisted FSharp.Core 6.0.2

### ISSUE THREAD

**Issue by nightroman** [dotnet/fsharp#12753]
FSharp.Compiler.Service 41.0.2 depends on the unlisted FSharp.Core 6.0.2
Is it expected? Was this FSharp.Core unlisted for a serious reason?

> The owner has unlisted this package. This could mean that the package is deprecated, has security vulnerabilities or shouldn't be used anymore.

**Comment by dsyme** [comment]
This is fixed by @KevinRansom
