### ISSUE TITLE
Can't resolve extension method when it shadows a property on a type

### ISSUE THREAD

**Issue by baronfel** [dotnet/fsharp#12751]
**Repro steps**

Given the following F# Script that uses Spectre.Console, similar code from the C# examples cannot be compiled without a _lot_ of gymnastics:

```fsharp
#r "nuget: Spectre.Console"

open Spectre.Console

// explicit usage of the extension method works
let t = HasTableBorderExtensions.Border(Table(), TableBorder.Square)
// expected usage of the extension method fails to compile - the compiler picks the Property on the type instead, which isn't a method
// Table.Border: TableBorder with get, set
let t' = Table().Border(TableBorder.Square)
```

**Expected behavior**

The compiler chooses the extension method that is in scope from the library.

**Actual behavior**

The compiler gives FS0003 (This value is not a function and cannot be applied) because it's expecting a property rather than a method.

**Known workarounds**

See the usage directly above, but the extension method that is in scope can be used directly. This is far less than ideal because a) the entire library is built around this sort of wrapping-builder pattern, and b) Spectre.Console is a very high-profile library in .NET in the space of command-line tooling.

**Related information**

This is on F# 6 on the 6.0.200 SDK.

**Comment by baronfel** [comment]
I'm not actually sure this is a _bug_ but it may require the RFC process, as it changes the method overload resolution logic.

**Comment by vzarytovskii** [comment]
Looks like a duplicate of https://github.com/fsharp/fslang-suggestions/issues/1039

**Comment by baronfel** [comment]
Good find, I'll close this then.
