### ISSUE TITLE
Inconsistent handling of operators on newlines

### ISSUE THREAD

**Issue by chausner** [dotnet/fsharp#12754]
Based on the discussion at https://github.com/fsprojects/fantomas/issues/2107, I examined which operators in F# may be put on a new line and which don't.

For example, in the following case, the definition of `a` compiles but `b` does not:
```fsharp
let a =
    5
    + 7

let b =
    5
    % 7
```

I checked the following operators (`%%` is defined as a custom operator):

`+` `-` `*` `/` `%` `%%` `**` `<` `<=` `>` `>=` `<>` `=` `&&` `||` `&&&` `<<<` `>>>` `^^^` `|||` `~~~`

and the compiler accepted all of them on a new line except:

`%` `%%` `<` `>` `=`

For `%` and `%%`, the compiler (incorrectly?) recognizes the operators as `(~%)` and `(~%%)`, defined in https://fsharp.github.io/fsharp-core-docs/reference/fsharp-core-extratopleveloperators.html.

For `<`, `>` and `=`, the compiler fails with a more generic FS0010 error.

**Repro steps**

[repro.zip](https://github.com/dotnet/fsharp/files/8104441/repro.zip)

**Expected behavior**

Either all operators should be accepted on a newline or none, or at least the documentation should explain why certain operators are not allowed on a newline.

**Comment by heronbpv** [comment]
Does putting them between parenthesis solve it?

**Comment by chausner** [comment]
> Does putting them between parenthesis solve it?

It allows the code to compile but the compiler interprets it as ignoring the first operand and currying the operator, i.e.
```fsharp
let b: (int -> int) =
    5
    (%) 7
```

What does help, however, is indenting the operator.

**Comment by dsyme** [comment]
Given the special status of `<`, `>`, `%`, `%%`, and `=` in the grammar I think it's best to consider this by design for F# 6. Please make a language suggestion at https://github,com/fsharp/fslang-suggestions. (We can also document the restrictions better.)

**Comment by dsyme** [comment]
I'll close since this is best tracked by a language suggestion
