### ISSUE TITLE
FCS SyntaxTree: Ident after dynamic operator is represented as a string

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#12755]
Consider the following code: `x?k`

and matching AST:

```fsharp
App
                (NonAtomic, false,
                 App
                   (NonAtomic, true, Ident op_Dynamic, Ident x,
                    tmp.fsx (1,0--1,2)),
                 Const
                   (String ("k", Regular, tmp.fsx (1,2--1,3)),
                    tmp.fsx (1,2--1,3)), tmp.fsx (1,0--1,3))
```

**Expected behaviour**

I would expect `k` to be an ident node.

**Actual behaviour**

It is a SynConst.String.

Is there any reason for this? If not, could you accept a PR to fix this?

**Comment by vzarytovskii** [comment]
I think it's about op_Dynamic semantics. The second parameter is considered a string.

**Comment by nojaf** [comment]
Hmm, I feel like this should be processed as such when constructing the typed tree.
It should still be an Ident in the Untyped tree, IMHO.
What do you think?

**Comment by auduchinok** [comment]
I totally agree with @nojaf, the syntax info shouldn't be lost prior to the type check stage.

**Comment by nojaf** [comment]
Another example:

```fsharp
x?v <- 2
```

```
              App
                (NonAtomic, false,
                 App
                   (NonAtomic, false,
                    App
                      (NonAtomic, true, Ident op_DynamicAssignment, Ident x,
                       tmp.fsx (1,0--1,8)),
                    Const
                      (String ("v", Regular, tmp.fsx (1,2--1,3)),
                       tmp.fsx (1,2--1,3)), tmp.fsx (1,0--1,8)),
                 Const (Int32 2, tmp.fsx (1,7--1,8)), tmp.fsx (1,0--1,8)),
```

**Comment by vzarytovskii** [comment]
> Another example:
> 
> ```fsharp
> x?v <- 2
> ```
> 
> ```
>               App
>                 (NonAtomic, false,
>                  App
>                    (NonAtomic, false,
>                     App
>                       (NonAtomic, true, Ident op_DynamicAssignment, Ident x,
>                        tmp.fsx (1,0--1,8)),
>                     Const
>                       (String ("v", Regular, tmp.fsx (1,2--1,3)),
>                        tmp.fsx (1,2--1,3)), tmp.fsx (1,0--1,8)),
>                  Const (Int32 2, tmp.fsx (1,7--1,8)), tmp.fsx (1,0--1,8)),
> ```

Yeah, dynamic assignment has same semantics.

**Comment by nojaf** [comment]
So, can we have an Ident instead in the untyped tree? Would the team accept such a PR?

**Comment by auduchinok** [comment]
Speaking of `x?k`, I think it should be a separate `SynExpr.Dynamic` case that type checker would internally convert to the application one.
The `x?v <- 2` case should probably be parsed as `SynExpr.Set(SynExpr.Dynamic _, SynExpr.Const _, _)`.

These conversions will require some changes across the type checker but it seems to be the most correct representation to me.

**Comment by vzarytovskii** [comment]
It is very special case, although it will be, technically, a breaking change, I personally don't mind changing it.
But it's mostly up to @dsyme.

@nojaf  are you trying to codegen the AST back to code, and have to deduce that it's ident and not string?

**Comment by nojaf** [comment]
A breaking change in the syntax tree 😅 well that would be a first 🙈.
Sorry, jokes aside, yes that is my use-case indeed to construct source code from the AST.

I do like @auduchinok his proposal of `SynExpr.Dynamic` to represent the code.

**Comment by vzarytovskii** [comment]
> A breaking change in the syntax tree 😅 well that would be a first 🙈.

I meant a braking change for the API users of course. I.e. if they were relying on current representation of op_Dynamic for example.

**Comment by dsyme** [comment]
I agree this desugaring should be done in the type checker and a SynExpr.Dynamic introduced (also for setting x?id <- v)

**Comment by nojaf** [comment]
Thanks all, I'll create a proposal PR for this in the weeks to come.
We can further discuss it once I have something.
