### ISSUE TITLE
error FS0073: internal error: Undefined or unsolved type variable when using records with generic type variables and backgroundTask

### ISSUE THREAD

**Issue by moinessim** [dotnet/fsharp#12761]
Getting internal error when trying to compile generic type that uses backgroundTask expression.

```F#
open System.Text.Json

type Dto = {
    DtoValue : string
    Key : string
}

type MyGenericType<'Key,'Value> = {
    Value : 'Value
    Key : 'Key
}

type ProblematicType<'Key, 'Value, 'Dto, 'E>( fromDto : 'Dto -> Result<MyGenericType<'Key,'Value>,'E> ) =
    let myTask = 
        backgroundTask {
            let dto =  """{"DtoValue":"1","Key":"key1"}""" |> JsonSerializer.Deserialize<'Dto>
            return fromDto dto |> printfn "%A"
        }
    member __.ContainsKey = fun (key: 'Key) -> true


type MyType = MyGenericType<string,int>

module MyType =
    let fromDto (dto: Dto)  =
        try
            {
                Value = int dto.DtoValue
                Key = dto.Key
            } 
            |> Ok
        with | e -> Error e


let problem = ProblematicType<string,int,Dto,exn>(MyType.fromDto)

```

Provide the steps required to reproduce the problem:

1. Execute above code in FSI or try to compile in console app with `dotnet build`.

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

**Expected behavior**

It should compile and run successfully.

**Actual behavior**

          backgroundTask {
  --------^^^^^^^^^^^^^^

error FS0073: internal error: Undefined or unsolved type variable: 'Key

**Known workarounds**

Use `task` instead of `backgroundTask` expression.

**Related information**

.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.5
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /nix/store/nwyx15pwbkfqxl818q2nhh3cmnmvygik-dotnet-sdk-6.0.100/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [/nix/store/nwyx15pwbkfqxl818q2nhh3cmnmvygik-dotnet-sdk-6.0.100/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/nix/store/nwyx15pwbkfqxl818q2nhh3cmnmvygik-dotnet-sdk-6.0.100/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [/nix/store/nwyx15pwbkfqxl818q2nhh3cmnmvygik-dotnet-sdk-6.0.100/shared/Microsoft.NETCore.App]

**Comment by dsyme** [comment]
Here's a much smaller repro:
```fsharp
let TestFunction<'Dto>() =
        backgroundTask {
            let dto = Unchecked.defaultof<'Dto>
            System.Console.WriteLine(dto)
        }
```

**Comment by TheAngryByrd** [comment]
This is also affecting `cancellableTask` and `coldTask` in [IcedTasks](https://github.com/TheAngryByrd/IcedTasks). It is also affecting `backgroundTaskResult` `backgroundTaskOption` and `cancellableTaskResult` in [FsToolkit.ErrorHandling](https://github.com/demystifyfp/FsToolkit.ErrorHandling). Oddly it is not affecting `taskResult` and `taskOption`.

**Comment by et1975** [comment]
What's the correct workaround here, if any?

**Comment by JohSand** [comment]
I ran into this recently, and it seems that it happens when the byref<ResumableStateMachine<>> is captured in a closure in the AfterCode<_,_>. So Task.Run for backgroundTask, and the closures crated for cancellableTask and coldTask. I have no idea how to work around it though. Main issue is providing a ref of the statemachine to AsyncMethodBuilder.Start(**)

**Comment by dsyme** [comment]
@JohSand @et1975 @TheAngryByrd I have pushed a fix for this.  I apologise for not getting to this earlier.  

@JohSand is correct that the problem happens when `ResumableStateMachine<>` is used in a closure in the `AfterCode<,>`.

I don't think there's any workaround if it is necessary to capture the `ResumableStateMachine` struct type in a closure of the AfterCode.  For example, in this code for `backgroundTask` I couldn't find a workaround (when defining a generic `backgroundTask`).

```fsharp
                        let sm = sm // copy contents of state machine so we can capture it

                        Task.Run<'T>(fun () ->
                            let mutable sm = sm // host local mutable copy of contents of state machine on this thread pool thread
                            sm.Data.MethodBuilder <- AsyncTaskMethodBuilder<'T>.Create ()
                            sm.Data.MethodBuilder.Start(&sm)
                            sm.Data.MethodBuilder.Task)))
```

**Comment by dsyme** [comment]
Note that the bug only manifests itself for generic code producing tasks where generic type parameters do not appear in the type of the thing returned by the task.  So this is ok:
```fsharp
let TestFunction<'Dto>() : Task<'Dto>=
        backgroundTask {
            let dto = Unchecked.defaultof<'Dto>
            System.Console.WriteLine(dto)
            return dto
        }
```
but this is not:
```fsharp
let TestFunction<'Dto>() : Task<unit> =
        backgroundTask {
            let dto = Unchecked.defaultof<'Dto>
            System.Console.WriteLine(dto)
        }
```

**Comment by TheAngryByrd** [comment]
@dsyme Thanks for the fix! It looks like 6.0.6 fixes this however I'm still concerned about your statement:

> Note that the bug only manifests itself for generic code producing tasks where generic type parameters do not appear in the type of the thing returned by the task.

Something like this doesn't work:

```fsharp
    let stringy (someObj) = cancellableTask {
        do! fun ct -> Task.Delay(100, ct)
        return string someObj
    }
```

While this is to be expected based on your comment, this still seems quite limiting to what you can do with these functions.

**Comment by vzarytovskii** [comment]
> @dsyme Thanks for the fix! It looks like 6.0.6 fixes this 

Surprised that it does, fix was not inserted into 17.3/6.x branch, only in 17.4/7

**Comment by dsyme** [comment]
> While this is to be expected based on your comment, this still seems quite limiting to what you can do with these functions.

Oh yes, it's a highly problematic bug for `backgroundTask` - but if you fully annotate I guess there's a methodology to work around it, if painfully

**Comment by TheAngryByrd** [comment]
So the current work around is always return what was passed into a function that uses `backgroundTask`?

Something like: 

```fsharp
    let stringy2<'a> (someObj : 'a) : Task<string * 'a> = backgroundTask {
        do! Task.Delay(100)
        return string someObj,someObj
    }
```

**Comment by TheAngryByrd** [comment]
hmm maybe the fix you pushed isn't out on 6.0.6? Maybe i'm not comparing the right thing

**Comment by TheAngryByrd** [comment]
It doesn't seem like `6.0.6` or `7.0.0-beta.22427.1` works with

```fsharp
let stringy<'a> (someObj : 'a) : Task<string> = backgroundTask {
    do! Task.Delay(100)
    return string someObj
}
```

So it seems like the only  work around is always return what was passed in.

**Comment by sonicbhoc** [comment]
> So it seems like the only work around is always return what was passed in.

I'm running into this everywhere in my code right now. I implemented IAsyncDisposable on one of my classes, and that's having the same issue because the type itself is generic. I'm hoping this gets fixed sooner than later; I don't want to have to sprinkle `ConfigureAwait(false)` everywhere in my code.

**Comment by et1975** [comment]
I'm confused, why is this resolved if we're still getting this error in 6.0.6?

**Comment by vzarytovskii** [comment]
Does the release of 7.0 solve that?

**Comment by et1975** [comment]
SDK 7.0.100 works!

**Comment by et1975** [comment]
@vzarytovskii any plans to fix this in v6 (LTS) SDK?

**Comment by vzarytovskii** [comment]
> @vzarytovskii any plans to fix this in v6 (LTS) SDK?

Not as for now, it didn't hit the bar when we were trying to backport it last time, let's see if I can do anything now.
