### ISSUE TITLE
Incorrect pattern matching warnings (covering active patterns)

### ISSUE THREAD

**Issue by isaksky** [dotnet/fsharp#1281]
Pattern matching warnings seem to get confused by covering active patterns.
#### Repro steps

![fsharp](https://cloud.githubusercontent.com/assets/607986/16316195/90ecb5b4-3942-11e6-8287-9988b7a55a26.gif)

Code: 

``` fsharp
    type Cond = Foo | Bar | Baz
    let (|SetV|) x _ = x

    [<EntryPoint>]
    let main argv = 
        let c = Cond.Foo

        match c with
        | Baz -> 
          printfn "Baz"
        | Foo & SetV "and" kwd
        | Bar & SetV "or" kwd ->
          printfn "Keyword: %s" kwd
        | Baz -> failwith "wat"

        0 // return an integer exit code
```
#### Expected behavior

Dropping the last case, it would compile with no warnings.
#### Actual behavior

It complains about a missing case, then even when you add it, it says it will never match.
#### Related information

Windows 10, Visual Studio 2015, power tools installed

**Comment by ReedCopsey** [comment]
So, the real "error" here seems to be an inappropriate compiler warnings.

If you compile this, you get this warning:

```
Incomplete pattern matches on this expression. For example, the value 'Baz' may indicate a case not covered by the pattern(s).
```

When in reality, it's `Foo` or `Bar` that should be called out in the warning.  Adding this eliminates the warnings:

```
    match c with
    | Baz -> 
        printfn "Baz"
    | Foo & SetV "and" kwd
    | Bar & SetV "or" kwd ->
        printfn "Keyword: %s" kwd        
    | Foo | Bar -> ()  // This will "fix" the errors, since it doesn't figure out that the complete pattern above still matches
```

That being said, it would also be nice if the compiler was smart enough to realize that the `SetV` active pattern doesn't prevent it from being complete.

**Comment by dsyme** [comment]
I think this behavior is unlikely to be changed - the churn needed in the pattern match compiler is just too much consider the rarity of this problem. 

So yes, using active patterns can result in some degradation of these warnings.  The recommendation would be to just adjust your code to be plainer or add the default case in the patterns.

**Comment by isaksky** [comment]
Good to know, thanks @dsyme.

**Comment by edgarfgp** [comment]
Same here. This seems to be fixed by https://github.com/dotnet/fsharp/pull/13020

**Comment by vzarytovskii** [comment]
Yes, should be fixed, closing it for now.
