### ISSUE TITLE
Fsharp test are failing again due to Patch Tuesday

### ISSUE THREAD

**Issue by erdembayar** [dotnet/fsharp#12835]
I’m from NuGet.Client team, which owns NuGet functionality in .NET and Visual Studio.
We have Fsharp test which [start failing](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5868740&view=ms.vss-test-web.build-test-results-tab) again due to patch Tuesday dependency. `NU1102: Unable to find package FSharp.Core with version (>= 6.0.4-beta)`
Previously I was told (email thread) use [_NetCoreSdkIsPreview](https://github.com/NuGet/NuGet.Client/pull/4459) to avoid it, but still happening again. What else we can do to avoid this monthly recurring failure?

**Comment by vzarytovskii** [comment]
I think, it should've been fixed in https://github.com/dotnet/fsharp/pull/12829 cc @KevinRansom

**Comment by erdembayar** [comment]
> @KevinRansom is it failing because of built in FSharp.Core? If so, it should've been fixed in #12829

How long it takes to fix goes live in dotnet/vs? It's blocking our CI pipeline. Just wondering whether to wait for fix go live or disable tests.

**Comment by vzarytovskii** [comment]
> > @KevinRansom is it failing because of built in FSharp.Core? If so, it should've been fixed in #12829
> 
> How long it takes to fix goes live in dotnet/vs? It's blocking our CI pipeline. Just wondering whether to wait for fix go live or disable tests.

It is in 17.2, so should get in with next insertion cc @brettfo

**Comment by KevinRansom** [comment]
@erdembayar --- sorry about that, visual studio and the dotnetsdk insertions have reciever different versions of FSharp because of   different codeflow issues that the sdk team and our team had.  I checked in a fix early this morning which should flow to mondays Dogfood Visual Studio.

**Comment by KevinRansom** [comment]
@erdembayar 

We checked in a workaround yesterday:  https://github.com/dotnet/fsharp/pull/12829
This should be inserted into be in Mondays build, except insertions into vs main seem to be failing for us.  so there is that figure out.
The full fix will be managed by this issue: https://github.com/dotnet/fsharp/issues/12831

**Comment by erdembayar** [comment]
@KevinRansom  
Is it safe to re-enable F# tests now? It looks for now it's temporary fix applied.
Is there going to be permanent fix applied?  I'm wary of another F# tests failure in next month.

**Comment by erdembayar** [comment]
@KevinRansom 
Long term solution for this issue would be add test on F# side? So, this reoccurring issue prevented even before it affects us.
Test is quite simple.
1. Create F# library
2. Install package
3. Assert if installed package is there and no errors.
