### ISSUE TITLE
parser error recovery in match after last "."

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#12849]
It seems F# tooling breaks at the point the `.` is added to this code:

```fsharp    
type DU = A | B
match A with
| DU. // typing here
```

it produces:

> Incomplete structured construct at or before this point in expression. Expected identifier, '(', '(*)' or other token.

As the parsing is invalidated and not recovering from the error, we lose ability to dot into the rest of what I need to write, and I suspect it frustrates a lot of F# developers that parsing errors out there.

**Describe the solution you'd like**

* Parser should recover
* Maybe the error message could list member & type names of the last identifier actually type checks, and be tailored for this particular recovery as it seems a bit generic right now

> The `.` token before the `DU` type name is incomplete, did you meant to add `A`, ..., or `B`

Any other idea?

**Additional context**

related: #1103, #11481

**Comment by smoothdeveloper** [comment]
Interestingly, it seems to handle this:

```fsharp
type DU = A | B
do
    A(_)
    match d with
    | DU. // typing here
```

Where the tooling is still able to provide autocomplete, because somehow, there is an error above.

**Comment by kerams** [comment]
Yes, this is especially annoying with `RequireQualifiedAccess` (like in the compiler). You need to type another letter to see completions, but at that point they no longer show every DU case.
