### ISSUE TITLE
Can't properly debug VisualFSharpDebug configuration

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#12855]
When trying to run/debug VisualFSharpDebug configuration launched in Visual Studio 2022 17.1.1, the F# support seems to not be loaded properly and can't be debugged.

When trying to set breakpoint in debugee Visual Studio, breakpoint range is not highlighted (and breakpoint in ValidateBreakpointLocation isn't being hit):
<img width="683" alt="Screenshot 2022-03-18 at 18 33 53" src="https://user-images.githubusercontent.com/3923587/159033624-e6c42cbd-e509-497d-b070-67658a8b2083.png">

There's exception when trying to invoke code completion:
<img width="458" alt="Screenshot 2022-03-18 at 18 03 32" src="https://user-images.githubusercontent.com/3923587/159033253-b42371bb-7516-4fd6-ba07-8fe4a09c5bcb.png">

[ActivityLog.xml.zip](https://github.com/dotnet/fsharp/files/8305784/ActivityLog.xml.zip)

**Comment by kerams** [comment]
Related https://github.com/dotnet/fsharp/issues/12732

**Comment by auduchinok** [comment]
@kerams Ah, it's a duplicate then, thanks! I'll close this issue.

**Comment by KevinRansom** [comment]
Fixed by #12868
