### ISSUE TITLE
Breakpoint locations are not provided for top-level expressions

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#12850]
Consider the console app template:
```fsharp
// For more information see https://aka.ms/fsharp-console-apps
printfn "Hello from F#"
```

With the recent debug-related changes it's not possible to set a breakpoint at the expression. cc @dsyme

**Comment by dsyme** [comment]
@auduchinok Could you write out step-by-step repro please?  I tried the following with a recent build of main and it worked ok. to set the breakpoint both before debugging starts (ValidateBreakpointLocation) and after debugging starts (IL sequence points)

```
artifacts\bin\fsc\Debug\net472\fsc.exe --debug:portable --optimize- --tailcalls- a.fs

devenv  /RootSuffix RoslynDev /debugexe a.exe
```

**Comment by auduchinok** [comment]
@dsyme Hmmm, my repro was as simple as getting a breakpoint range via `ValidateBreakpointLocation`. Our fork is currently based on https://github.com/dotnet/fsharp/commit/1490dd5d8abfc5fe6609e56a174914cf72306179, so it should be similar to recent builds in `main`. I'll try to rebase on the latest `main` to see if it makes any difference.

Looking at
```
.\build -c Release -deploy

artifacts\bin\fsc\Debug\net472\fsc.exe --debug:portable --optimize- --tailcalls- a.fs
```
It seems a different compiler is used? I.e. the produced release build is ignored and some other (older?) debug build is used to compile the file.

**Comment by dsyme** [comment]
Oh I see, I might be hitting https://github.com/dotnet/fsharp/issues/12732 when running the Visual Studio instance.  ValidateBreakpointLocation doesn't seem to be being called at all.

**Comment by auduchinok** [comment]
@dsyme I can confirm it's broken in Visual Studio in the latest `main`. Could you please take a look?

**Comment by dsyme** [comment]
@auduchinok Fix is in the works, thanks

https://github.com/dotnet/fsharp/pull/12887

**Comment by dsyme** [comment]
@KevinRansom @vzarytovskii Note this is a regression in IDE support for setting breakpoints.  We should get it into affected release branches that aren't being auto-integrated, thanks

**Comment by auduchinok** [comment]
@dsyme Thanks for the fix!

**Comment by dsyme** [comment]
@auduchinok thanks for the timely report!!
