### ISSUE TITLE
Cannot call NumSharp comparison operator unlike C#

### ISSUE THREAD

**Issue by Happypig375** [dotnet/fsharp#12871]
**Repro steps**

```fs
#r "nuget: NumSharp"
open NumSharp
np.array([1; 2; 3]) > np.array([4; 5; 6])
```

**Expected behavior**

No compile error.

**Actual behavior**

```
Error: input.fsx (1,1)-(1,20) typecheck error The type 'NDArray' does not support the 'comparison' constraint. For example, it does not support the 'System.IComparable' interface
```

**Known workarounds**

Call it like `NDArray.(>)(np.array([1; 2; 3]), np.array([4; 5; 6]))`

**Related information**

Provide any related information (optional):

* Operating system: Windows
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .NET 6.0.101
* Editing Tools (e.g. Visual Studio Version, Visual Studio): VSCode

**Comment by charlesroddie** [comment]
If it implemented `IComparable<'T>`, and if F# added https://github.com/fsharp/fslang-suggestions/issues/816, then it would work.

Is the reason that it doesn't implement `IComparable<'T>` that the order here is a partial order?

**Comment by Happypig375** [comment]
This could be related to the comparison operators performing elementwise operations instead of returning a boolean value so F# can't handle them.

**Comment by charlesroddie** [comment]
What is the reason for saying that the expected behavour is "no compile error"? Is is that the F# > operator should work in this context (and if so, is this a feature request or something that should happen in the existing spec), or is it that opening NumSharp results in NumSharp's > operator being in scope, so that the FSharp > operator is shadowed?

**Comment by dsyme** [comment]
This is actually by design as things stand - the return type of these operators is a Tensor, not a bool, and F~ doesn't like this.

**Comment by dsyme** [comment]
@Happypig375 Please find or add a language suggestion for this? thanks
