### ISSUE TITLE
Code using records causes multiemit warning

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#12886]
The following two interactions in F# Interactive cause a multi-emit warning:
Run:
```
artifacts\bin\fsi\Release\net472\fsi.exe --multiemit
```
then 
```
type Test = { A: int; B: string };;
```
then
```
let list = [{ A = 1; B = "a" }; { A = 2; B = "b" }; { A = 3; B = "c" }]
[ for x in list do x.A ]
;;

```
Gives:
```
stdin(3,1): warning FS2303: Accessing the internal type, method or field 'A@' from a previous evaluation in F# Interactive is deprecated and may cause subsequent access errors. To enable the legacy generation of a single dynamic assembly that can access internals, use the '--multiemit-' option.
```

**Comment by dsyme** [comment]
Labelling as a regression since multiemit is on by default for .NET Core

**Comment by dsyme** [comment]
@KevinRansom This was high impact because it busted `dotnet fsi` in any scenario that uses records.

**Comment by knocte** [comment]
@dsyme can you reopen this? I've found this testcase:

someScript.fsx:
```
#load "Foo1.fs"
#load "Foo2.fs"

printfn "hello"
```

Foo1.fs:
```
namespace SomeNamespace

type SomeDU =
    | Success
    | Error of output: string

module Foo1 =
    let Bar(): SomeDU =
        failwith ""
```

Foo2.fs:
```
namespace SomeNamespace

module Foo2 =
    let private Baz()  =
        match Foo1.Bar() with
        | Error output ->
            let typeName = output.GetType().Name
            failwith typeName
        | _ -> failwith ""
```

Output when run:

```
/Users/knocte/Documents/Code/someScript.fsx(2,1): warning FS2303: Accessing the internal type, method or field '_output' from a previous evaluation in F# Interactive is deprecated and may cause subsequent access errors. To enable the legacy generation of a single dynamic assembly that can access internals, use the '--multiemit-' option.

hello
```

The only workaround I can find is placing Foo1 and Foo2 in the same file, but that's very inconvenient. Any idea about a better workaround to use until this is fixed? Thanks

**Comment by knocte** [comment]
(Just edited the comment above to make testcase simpler.)

**Comment by T-Gro** [comment]
Will retest once our December changes are merged in, this might have been fixed by @KevinRansom  in the meantime.

**Comment by knocte** [comment]
Thanks @KevinRansom , but actually I've realised that this initial bug report talked about records while I discovered it when using DUs; so I should have posted my comment in this other bug: https://github.com/dotnet/fsharp/issues/14216 (which now you might want to mark as closed).
