### ISSUE TITLE
Add getValueOrDefault on Map

### ISSUE THREAD

**Issue by lucasteles** [dotnet/fsharp#12884]
This is a common operation in dictionaries, would be nice to have a way to get a value from it, if the key does not exist return a default value.

The `Map` type already has an implementation of this for `IReadOnlyDictionary`.  I think this should be in the default methods and API for `Map`

Implementation:
```fsharp
let getOrDefault k default' map = 
    (map :> IReadOnlyDictionary<_,_>).GetValueOrDefault(k, default')


let map = Map([("a",1)])
map |> getOrDefault "a" 0  // 1
map |> getOrDefault "b" 0  // 0

```

**Comment by dsyme** [comment]
Please add such requests at https://github.com/fsharp/fslang-suggestions
