### ISSUE TITLE
Completion context computed twice for one request

### ISSUE THREAD

**Issue by kerams** [dotnet/fsharp#12894]
When getting completion items in `ProvideCompletionsAsyncAux`, `TryGetCompletionContext` is usually called twice - once directly and once inside `GetDeclarationListInfo`.

![devenv_29ULaBt4bF](https://user-images.githubusercontent.com/5063478/160687487-6869a0c2-75e3-4b3e-a3e0-e50049148c5d.png)

This means the syntax tree walker is used twice to traverse the tree to establish the context. I don't think this has a huge performance impact, but why do more work and generate garbage needlessly.

The question is how to approach this. `GetDeclarationListInfo` is a public API, so changing the signature to take an optional completion context would be a breaking change in FCS. On the other hand, duplicating the method just for this seems silly.

**Comment by dsyme** [comment]
> The question is how to approach this. GetDeclarationListInfo is a public API, so changing the signature to take an optional completion context would be a breaking change in FCS. On the other hand, duplicating the method just for this seems silly.

Make a `GetDeclarationListInfoAux` used by both
