### ISSUE TITLE
Improve Test Suite for FSI tests

### ISSUE THREAD

**Issue by jkone27** [dotnet/fsharp#12934]
To ease changes from contributors to the compiler/fsharp

The suggestion is to rethink the test suite or the unit test composition/number, maybe **creating more smaller tests** or improving expectations and assertions, in a way that is evident what's wrong without having previously worked with the project.

example of "difficult test troubleshooting"

https://github.com/dotnet/fsharp/pull/12858

**Comment by KevinRansom** [comment]
Yes, the fsharp.core test suite needs removing, we do however, have a decent suite for testing this sort of stuff.  FSharp.Component.  test suites
