### ISSUE TITLE
Signature Help shows tooltips for incorrect functions

### ISSUE THREAD

**Issue by kerams** [dotnet/fsharp#12943]
**Repro steps**

![devenv_4xyitGHGJR](https://user-images.githubusercontent.com/5063478/161736421-a8743b52-2ab5-4b4a-ba50-77b1cc451b19.png)

When props for the button are non-empty, the reported position is even stranger.

![devenv_lqybyIlvjk](https://user-images.githubusercontent.com/5063478/161736430-f4058731-5193-44a0-aa01-9a173d877af0.png)

I'm seeing this all the time when writing Fable code.
@cartermp, any idea off the top of your head what could be going wrong here?

**Expected behavior**

In both cases the tooltip should show this, and be similarly positioned with respect to the caret

![devenv_C5VkNoTgDp](https://user-images.githubusercontent.com/5063478/161737291-5d44402a-1897-4dd1-8568-80098482b398.png)

**Related information**

Provide any related information (optional):

* Win 10
* .NET 7.0.100-preview.4.22175.1
* VS 17.2 Preview 2.0

**Comment by cartermp** [comment]
This is the syntax traversal code having a problem finding the innermost function to get signature help for. I fixed some bugs in this a while back and it was a bit tricky.

IIRC this is the routine:

https://github.com/dotnet/fsharp/blob/main/src/fsharp/service/FSharpParseFileResults.fs#L171

And you'll definitely wanna put some cases under teststarting here:

https://github.com/dotnet/fsharp/blob/main/tests/service/ServiceUntypedParseTests.fs#L712

**Comment by cartermp** [comment]
Specifically this blob and the functions it calls are where it's finnicky and likely causing problems https://github.com/dotnet/fsharp/blob/main/src/fsharp/service/FSharpParseFileResults.fs#L184-L206
