### ISSUE TITLE
Escaping brackets inside a FormattableString is just painful

### ISSUE THREAD

**Issue by omppye** [dotnet/fsharp#12974]
**Is your feature request related to a problem? Please describe.**

I'm trying to escape brackets inside a `FormattableString`. At first I was thinking that will be the same syntax as F# interpolated strings, a pair of brackets - as described [here](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/interpolated-strings#remarks)

But if you do that the runtime gives me a error in the `ToString` method

```fsharp
> let T: System.FormattableString = $"{{}}";;
val T: System.FormattableString =
  <ToString exception: Input string was not in a correct format.>
```

The only way I found to make it work it's a _four_ pairs brackets 

```fsharp
> let T: System.FormattableString = $"{{{{}}}}";;
val T: System.FormattableString = {}
```

**Describe the solution you'd like**

I think the same syntax as F# interpolated strings is reasonable

**Comment by dsyme** [comment]
This is a duplicate of this: https://github.com/dotnet/fsharp/issues/11782
