### ISSUE TITLE
Inconsistent error when returning from a record member.

### ISSUE THREAD

**Issue by MatthijsPrent** [dotnet/fsharp#12971]
**Repro steps**
I noticed this problem when implementing a IValueConverter and repoduced the problem into a very simple repo.
[Demo repository](https://github.com/MatthijsPrent/RecordMemberReturnBug)

The member called `NotWorking `gives an error message:
```
Error	FS0001	Type mismatch. Expecting a
    ''a -> obj'    
but given a
    ''a -> string'    
The type 'obj' does not match the type 'string'	RecordMemberReturnBug	C:\Users\matthijs.prent\OneDrive - Salland Engineering\Documents\svn_repos\RecordMemberReturnBug\Library.fs	5	Active
```
However, member called `Working` does not give any error or warning and does work.

**Expected behavior**

I would expect both to compile and work, since they seem the same, and should both return a String, which is inherited form Object. I would at least expect the members to behave the same way.

**Actual behavior**

The first method gives an error, while the second one does not. 

**Related information**

Provide any related information (optional):

* .Net core 6.0.2
* Visual studio professional 2022

**Comment by dsyme** [comment]
This is by design for F# 6, and is related to the way `sprintf` is type-checked.  Adding a call to `|> box` is adequate as a workaround

It is however reasonable to add a suggestion at https://github.com/fsharp/fslang-suggestions for this, if you wish
