### ISSUE TITLE
'use ptr = fixed &mem' does not work in CE, 'let ptr = fixed &mem' does (but should be illegal?)

### ISSUE THREAD

**Issue by reijerh** [dotnet/fsharp#12983]
Pinning locals does not work in computation expressions (CEs) when using the `use ptr = fixed &mem` syntax, it _does_ work when using `let ptr = fixed &mem`. However, this second form should not be allowed according to the docs and error message in the compiler: https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/fixed (and it's unclear if this form is supposed to unpin the local after usage, some testing suggests it _does_)

**Repro steps**

This:
```
let fooSeq () =
    seq {
        let memory = Array.create 100 42
        use memoryPtr = fixed &memory[0]
        ()
    }
```
Results in:
`Error FS3207 : Invalid use of 'fixed'. 'fixed' may only be used in a declaration of the form 'use x = fixed expr' where the expression is an array, the address of a field, the address of an array element or a string'`

But this works:
```
let fooSeq () =
    seq {
        let memory = Array.create 100 42
        let memoryPtr = fixed &memory[0]
        ()
    }
```
And it actually seems to pin the local when I check it using:
```
        GC.Collect()
        printfn $"%d{GC.GetGCMemoryInfo().PinnedObjectsCount}"
```
The IL seems to be equal for both snippets.

**Expected behavior**

Expected the first snippet to compile, and the second version to not compile.

**Actual behavior**

First snippet does not compile, second snippet does.

**Known workarounds**

Do the pinning outside the CE or use something like `Marshal.AllocHGlobal` inside the CE.

**Related information**
Code here: https://sharplab.io/#v2:DYLgZgzgNALiCWwoBMQGoA+BbA9sgrsAKYAEAYjjgLABQtxMJYlAykQI4kAUAlCQLy0SwkhA4kA3kJEyGJLEVwAnAJ4CSAQSVKAhioB0AYyVEdMUgEYADFZIAWAEzSZw/GPmKcqgAowl6sHgADyJkEgAyBWUVAG0rAF1nF14kgF8gA==

Somewhat related: https://github.com/fsharp/fslang-design/discussions/421

**Comment by dsyme** [comment]
This is by design for F# 6, because of the way `use` is de-sugared and treated in computation expressions.  Just use a `let` or similar with a `try/finally`

I'm not clear if it could be handled differently, please open a language suggestion at https://github.com/fsharp/fslang-suggestions?

**Comment by reijerh** [comment]
Alright, I might do that.

I guess the issue is mostly about the usage/semantics being unclear here: the docs and error message state that we _have_ to use the `use` form, only by accident I discovered the `let` form (which isn't even allowed _outside_ CEs).

And this may be because I'm not very experienced with F#, but I can't see how `try/finally` would help here; `fixed` does not yield an `IDisposable`. Quick testing suggests the object _does_ already get unpinned automatically though, I don't know if that's by design or not, but perhaps usages should be clarified.

I ended up doing this:
```
type NativeMemory =
    private
    | NativeMemory of nativeint
    static member Allocate(numBytes: int) : NativeMemory =
        NativeMemory(Marshal.AllocHGlobal(numBytes))

    member this.NativePtr: nativeint =
        match this with
        | NativeMemory ptr -> ptr

    interface IDisposable with
        member this.Dispose() =
            match this with
            | NativeMemory ptr -> Marshal.FreeHGlobal ptr
```
Which can be used inside a CE as:
`use dataPtr = NativeMemory.Allocate(numBytes)`
