### ISSUE TITLE
Allow multiple shebang lines at start of fsx file

### ISSUE THREAD

**Issue by moinessim** [dotnet/fsharp#13016]
https://github.com/dotnet/fsharp/blob/2f8154178b09f21008e50e32ed58422b54b5789d/src/fsharp/lex.fsl#L927

Can we allow this multiple lines with shebangs at the start of an fsx file?

It would allow some very cool features in Unix systems, like:

```f#
#! /usr/bin/env nix-shell
#! nix-shell -i "dotnet fsi" -p dotnet-sdk_6 git bash

let callGitAndBash = ...
```

https://gist.github.com/travisbhartwell/f972aab227306edfcfea

**Comment by dsyme** [comment]
I've not seen multi-line shebangs before, is it standard? I'm ok with it if it's standard in, say, python

If so please add a suggestion and https://github.com/fsharp/fslang-suggestions and consider it pre-approved, and please also consider submitting an RFC and implementation. Thanks

**Comment by dsyme** [comment]
@moinessim Please add the feature request, I'll close this, thanks

**Comment by moinessim** [comment]
Hi @dsyme,

Thanks for considering this.

After some research, it seems that 

> ... multi-line shebangs are completely a nix invention.
https://github.com/NixOS/nix/issues/2570#issuecomment-446046269

The only reason they work in python is because they get ignored as comments, since they start with `#`.

And found a workaround to enable the mentioned  functionality by surrounding the second shebang in a multi-line comment:

```f#
#! /usr/bin/env nix-shell
(*
#! nix-shell -i "dotnet fsi" -p dotnet-sdk_6 git bash
*)

let callGitAndBash = ...

```

So I guess there's nothing to do here.

**Comment by dsyme** [comment]
@moinessim Thanks for the update!
