### ISSUE TITLE
Add Parens to SynMeasure

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#13025]
**Is your feature request related to a problem? Please describe.**

Given the following code snippet:
```fsharp
40u<hr / (staff weeks)>
```
and matching AST:
```fsharp
Const
                (Measure
                   (UInt32 40u, tmp.fsx (1,0--1,3),
                    Divide
                      (Seq
                         ([Named ([hr], tmp.fsx (1,4--1,6))], tmp.fsx (1,4--1,6)),
                       Seq
                         ([Seq
                             ([Named ([staff], tmp.fsx (1,10--1,15));
                               Named ([weeks], tmp.fsx (1,16--1,21))],
                              tmp.fsx (1,10--1,21))], tmp.fsx (1,9--1,22)),
                       tmp.fsx (1,4--1,22))), tmp.fsx (1,0--1,23))
```
there is no trace of the used parenthesis inside [SynMeasure](https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-syntax-synmeasure.html).

**Describe the solution you'd like**

I believe it would be beneficial to capture these parentheses in the parser and add the as DU case.

https://github.com/dotnet/fsharp/blob/76432f1b7689411461d0b82eadf41e08a0ba7828/src/fsharp/pars.fsy#L5503-L5511

**Describe alternatives you've considered**

/

**Additional context**

Fantomas issue: https://github.com/fsprojects/fantomas/issues/2207

related: #11481

FCS 41

**Comment by dsyme** [comment]
Agreed we should do this
