### ISSUE TITLE
`Microsoft.CodeAnalysis.Formatting.ISyntaxFormattingService` is not registered for workspace in latest dev17

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#13040]
Happens when autoformatting kicks in either automatically or triggered via \<C-Return\>
![image](https://user-images.githubusercontent.com/1260985/165080990-6f697166-6c56-4467-99e2-7d01c08584b3.png)

**Comment by vzarytovskii** [comment]
Duplicate of https://github.com/dotnet/fsharp/issues/13010

**Comment by dsyme** [comment]
Closing as duplicate
