### ISSUE TITLE
Strange backticks in auto-complete

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#13061]
The following shows strange backticks, after pressing space where the cursor is:

![image](https://user-images.githubusercontent.com/7204669/165673061-72c5e03b-2071-4bdc-b7ee-a70e08d719c2.png)

**Comment by dsyme** [comment]
This might be a gird first issue, it might be because an empty string for "no parameter name" is getting  backticks, and the parameter name is not being skipped

**Comment by vzarytovskii** [comment]
I know that @psfinaki is working on tooltips for keywords issue, might be interested in this one too?

**Comment by psfinaki** [comment]
Yeah I can jump on that shortly.

**Comment by dsyme** [comment]
@psfinaki let's chat via teams later today

**Comment by psfinaki** [comment]
Minimal repro is `let f g x = g x`
