### ISSUE TITLE
Update Microsoft Build reference to 17.3.0 for .NET 7.0

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/fsharp#13075]
Currently fsharp [references Microsoft.Build 17.0.0 ](https://github.com/dotnet/fsharp/blob/main/eng/Versions.props#L148).  As a result of this, it causes a prebuilt in .NET source-build because .NET 7.0 source-build is producing msbuild 17.3.0.  Can this fsharp be updated to reference 17.3.0?

I tried an upgrade locally and everything built cleanly.  I did have to update the MicrosoftWin32RegistryVersion as well because Microsoft.Build 17.3.0 reference 5.0.0.

cc @KevinRansom

**Comment by KevinRansom** [comment]
The latest build on nuget https://nuget.org is https://www.nuget.org/packages/Microsoft.Build.Framework/

The compiler service nuget package we build is dependent on msbuild.framework.  So we are required to reference publicly available packages.   So ... when msbuild 17.3 is published to nuget we can certainly reference it, or we need to change the version number of the package for source builds.  Which is probably not right either :-)

What do you suggest?

**Comment by MichaelSimons** [comment]
Thanks for explaining the requirement to reference publicly available packages.  

An alternative that will unblock source build would be to just upgrade the MicrosoftWin32RegistryVersion to 5.0.0.  This will prevent a package downgrade warning as error in source-build as a result of Microsoft.Build 17.3.0 flowing during source-builds.  

When Microsoft.Build 17.3.0 is public, it would be great if fsharp can pick it up.
