### ISSUE TITLE
FS0193 internal error when defining two types and putting their values into a Result in one send to FSI

### ISSUE THREAD

**Issue by theprash** [dotnet/fsharp#13107]
This was originally discovered on the [F# Forums](https://forums.fsharp.org/t/fsi-error-fs0193-internal-error-could-not-load-type-x-from-assembly/2235) in a larger code sample.

❌ Defining 2 types and putting them both inside `Result.Ok` and sending all the code to FSI at once results in an error:
```
Microsoft (R) F# Interactive version 12.0.1.0 for F# 6.0 
Copyright (c) Microsoft Corporation. All Rights Reserved.

> type A = A
- type B = B
- let x : Result<_, unit> = Ok (A, B);;

error FS0193: internal error: Could not load type 'B' from assembly 'FSI-ASSEMBLY, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

Code: 
```
type A = A
type B = B
let x : Result<_, unit> = Ok (A, B);;
```

❌ Putting the values into the Error case fails with the same error:
```fsharp
type A = A
type B = B
let x : Result<unit, _> = Error (A, B);;
```

❌ Using an anonymous record instead of a tuple inside the result give the same error:
```fsharp
type A = A
type B = B
let x : Result<_, unit> = Ok {| A = A; B = B |}
```

✔ Using a Choice1of2 instead of Result works fine:
```fsharp
type A = A
type B = B
let x : Choice<_, unit> = Choice1Of2 (A, B)
```

✔ If you send the first two lines to FSI in one step, and then send the last line to FSI as a second step, there is no error.

**Expected behavior**

All of the above code samples should compile and run without error.

**Known workarounds**

Sending the code to FSI in smaller, separate chunks.

**Related information**

Provide any related information (optional):

* Windows 10
* F# Interactive version 12.0.1.0 for F# 6.0
* Tested in VS 2022 and VS Code

**Comment by dsyme** [comment]
My understanding all these have been fixed by #5457 - that is, using multi-assembly emit with the ilwrite binary writer fixes these problems.
