### ISSUE TITLE
Visual Studio crashes in FSharp.Compiler.Service.ni.dll

### ISSUE THREAD

**Issue by stmax82** [dotnet/fsharp#13133]
VS 20222 crashes somewhere within FSharp.Compiler.Service.ni.dll when you open a file containing an async function with too many lines of code.

**Repro steps**

1. git clone https://github.com/stmax82/vs-crash.git
2. Open Kaputt.sln in VS 2022
3. Open File Bang.fs
=> VS crashes after a few seconds

We were able to reproduce this on multiple systems.

Windows Event Log shows the following:

```
Faulting application name: devenv.exe, version: 17.0.31903.59, time stamp: 0x6182abc9
Faulting module name: FSharp.Compiler.Service.ni.dll, version: 41.0.121.52202, time stamp: 0xef6b0e45
Exception code: 0xc00000fd
Fault offset: 0x00000000023ca902
Faulting process id: 0x4d98
Faulting application start time: 0x01d865e23fcb2532
Faulting application path: C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.exe
Faulting module path: C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\FSharp.Comp0c9a8de5#\e5953749aefb0cb791a2c38865cc4551\FSharp.Compiler.Service.ni.dll
Report Id: eab32086-15a2-438e-bc7d-3e59c8e3ef91
Faulting package full name: 
Faulting package-relative application ID: 
```

**Expected behavior**

VS doesn't crash.

**Actual behavior**

VS crashes.

**Known workarounds**

Write shorter tests 😄

**Comment by vzarytovskii** [comment]
I don't think issue belongs here, @brettfo @KathleenDollard do you know what would be the best place to move/create it in?
VS feedback?

**Comment by vzarytovskii** [comment]
@dsyme looking at repro https://github.com/stmax82/vs-crash/blob/main/Bang.fs#L5, it seems like it's related to https://github.com/dotnet/fsharp/pull/12420.

**Comment by vzarytovskii** [comment]
@stmax82 which VS version are you using? Is it 17.2 or 17.3?

**Comment by stmax82** [comment]
@vzarytovskii looks like I've been on an older version of VS (event log says 17.0.31903.59). I upgraded to 17.2.1 and the problem seems to be gone / cannot reproduce it any more.

Case closed?

**Comment by vzarytovskii** [comment]
> @vzarytovskii looks like I've been on an older version of VS (event log says 17.0.31903.59). I upgraded to 17.2.1 and the problem seems to be gone / cannot reproduce it any more.
> 
> Case closed?

Thanks for the update. I will check what changed and close it.

**Comment by vzarytovskii** [comment]
Can't repro it in 17.4/17.5 anymore, closing
