### ISSUE TITLE
can't AutoOpen namespace-qualified modules

### ISSUE THREAD

**Issue by jcmrva** [dotnet/fsharp#13141]
The AutoOpen attribute appears to be ignored on top-level modules that include a qualified namespace.

**Repro steps**

> Utils.fs
```
[<AutoOpen>]
module Example.Utils

let tee fn v =
    fn v
    v
```
> Library.fs
```
module Say

let hello name =
    name
    |> tee (printfn "Hello %s") // err
    |> ignore
```

**Expected behavior**

Compiles.

**Actual behavior**

FS0039 compile error `The value or constructor 'tee' is not defined.`

**Known workarounds**

- Explicitly open the module.
- Fully qualify module members.
- Don't use qualified-namespaces.

**Related information**

* OS: Win10
* .NET 6 and .NET 7 (7.0.100-preview.4.22252.9)
* Ionide and .NET CLI

**Comment by auduchinok** [comment]
@jcmrva The attribute only applied to the module itself, not to the containing namespace. The language spec says that this module will open `Utils` module automatically when a `Example` namespace is opened.

**Comment by dsyme** [comment]
@auduchinok Thanks, yes, this is correct - this is by design
