### ISSUE TITLE
FSharp does not produce all packages in source-build

### ISSUE THREAD

**Issue by lbussell** [dotnet/fsharp#13174]
It looks like recently, FSharp split its build into two solutions: `FSharp.sln`, which contains most of the projects, and `Microsoft.FSharp.Compiler.sln`, which seems to only package the files produced by `FSharp.sln`. I'm looking at https://github.com/dotnet/fsharp/pull/12628

In source build, we were previously building only `FSharp.sln` which produced all of the packages we needed. However now we are missing Microsoft.Fsharp.Compiler.nupkg when we build only `FSharp.sln`, which is expected given the changes.

We have tried to produce both solutions with the following syntax in `SourceBuild.props`:
```xml
<InnerBuildArgs>$(InnerBuildArgs) '/p:Projects="$(InnerSourceBuildRepoRoot)\FSharp.sln;$(InnerSourceBuildRepoRoot)\Microsoft.FSharp.Compiler.sln;"'</InnerBuildArgs>
```

The problem here is that these solutions end up building concurrently even though they depend on each other. Microsoft.FSharp.Compiler is looking for `fsc.dll` before FSharp is finished producing it.

How should this dependency be managed, and how does the Microsoft build of fsharp work today? Do the two solutions need to build separately, one after the other? Are there any simple changes that we could make to solve this problem for source build?

@KevinRansom @crummel @MichaelSimons

see also https://github.com/dotnet/source-build/issues/2873

**Comment by vzarytovskii** [comment]
cc @brettfo Brett, do you know what would be the easiest way of fixing it? I would say building separately is the obvious way.

**Comment by MichaelSimons** [comment]
Would it be possible to add the [ProjectReferences ](https://github.com/dotnet/fsharp/pull/12628/files#diff-a55fa587c6ad09058e95671305c44ae766baed267d1df1cca71bb94e9ff59bc5L13) back to the Microsoft.FSharp.Compiler.csproj that were removed in #12628?  This would all source-build to specify both solutions in the projects list to build.

```
/p:Projects="$(InnerSourceBuildRepoRoot)\FSharp.sln;$(InnerSourceBuildRepoRoot)\Microsoft.FSharp.Compiler.sln;"
```

**Comment by vzarytovskii** [comment]
> Would it be possible to add the [ProjectReferences ](https://github.com/dotnet/fsharp/pull/12628/files#diff-a55fa587c6ad09058e95671305c44ae766baed267d1df1cca71bb94e9ff59bc5L13) back to the Microsoft.FSharp.Compiler.csproj that were removed in #12628? This would all source-build to specify both solutions in the projects list to build.
> 
> ```
> /p:Projects="$(InnerSourceBuildRepoRoot)\FSharp.sln;$(InnerSourceBuildRepoRoot)\Microsoft.FSharp.Compiler.sln;"
> ```

cc @KevinRansom

**Comment by vzarytovskii** [comment]
@MichaelSimons I will fix it.

**Comment by KevinRansom** [comment]
@MichaelSimons , okay I have a fix, that should work well for you.

**Comment by KevinRansom** [comment]
Fixed
