### ISSUE TITLE
F# console app CPU usage profiler shows blank window

### ISSUE THREAD

**Issue by daniel-wojcik** [dotnet/fsharp#13184]
Create F# console application (.NET 6) then choose Debug/Performance Profiler and check CPU Usage checkbox. Press Start and wait until profiling finishes - instead of results blank window is shown.

Windows 10 21H2 + VS 2022 17.3 Preview 1.0

**Comment by vzarytovskii** [comment]
This is what I see in today's 17.3 `main`:
![image](https://user-images.githubusercontent.com/1260985/169872898-35b04e52-4ad3-4192-8335-570785d834b4.png)

**Comment by daniel-wojcik** [comment]
After updating graphic card drivers and/or rebooting my PC problem disappeared.
