### ISSUE TITLE
Wrong type is reported in type mismatch error

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#13192]
```fsharp
let x: int * int * int = 1, ""
```

<img width="473" alt="Screenshot 2022-05-24 at 17 23 33" src="https://user-images.githubusercontent.com/3923587/170073582-923fbbc2-d5af-4d4e-838b-df3529190dab.png">

We're trying to use the type info reported in the error and in this case it works in an unexpected way.

It would be better to have an instance of `FSharpType` contained in the error somehow but until it's not implemented it'd be good to report the correct type.

**Comment by dsyme** [comment]
I suppose that in ConstraintSolver.fs, we should report

               ErrorD(ConstraintSolverTupleDiffLengths(csenv.DisplayEnv, origl1, origl2, csenv.m, m2)) 

on length mismatch before we process the list element by element.
