### ISSUE TITLE
IL Generation: Remove useless cast instructions

### ISSUE THREAD

**Issue by thinkbeforecoding** [dotnet/fsharp#13193]
**Is your feature request related to a problem? Please describe.**

The F# compiler emit useless IL instructions for some primitive type casts like uint16 -> int32

**Describe the solution you'd like**

Change the cast inline function implementation to remove those unnecessary instructions. It would make the output IL code smaller.

**Describe alternatives you've considered**

Keeping it like this, as the result is still correct.

**Additional context**

For instance:

https://github.com/dotnet/fsharp/blob/1874b39dfa769bd3a7c9e448ca21ff593f941ed6/src/FSharp.Core/prim-types.fs#L4379

F# emits a conv.i4 for the uint16 -> int32 conversion while int16 -> int32 conversion is a no-op

Testing with sharplab, we can see that removing the explicit conversion still gives the same result and performs a zero extension as expected:

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEAzAzmgFxAENcBbAHwxgIAIwBGWgCgRFoFcBLAOwIaQBKWgF5avOggCwAKFnU6YAEws2nCQOFjmAYloAifbTUTaOwUA=

![image](https://user-images.githubusercontent.com/146717/170239271-b16a63cb-4e34-4b57-a4a6-4a184e7db76c.png)

![image](https://user-images.githubusercontent.com/146717/170239311-5a277331-e858-48b8-a580-d8078f32b463.png)

**Comment by dsyme** [comment]
If there is no change in the generated assembly code then we should close this.  Smaller IL is not a goal in itself.
