### ISSUE TITLE
SynValSig range does not include range of expression

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#13205]
Consider:

```fsharp
val y : string = ""
```

```
SynValSig
  ([], SynIdent (y, None), SynValTyparDecls (None, true),
   LongIdent (SynLongIdent ([string], [], [None])),
   SynValInfo ([], SynArgInfo ([], false, None)), false, false,
   PreXmlDoc ((1,0), FSharp.Compiler.Xml.XmlDocCollector), None,
   Some
     (Const
        (String ("", Regular, tmp.fsi (1,17--1,19)),
         tmp.fsi (1,17--1,19))), tmp.fsi (1,0--1,14),
   { ValKeyword = Some tmp.fsi (1,0--1,3)
     WithKeyword = None })
```

**Expected behavior**

I would expect the range of `SynValSig` to include the range of the optional expression.

**Actual behavior**

The range of the expression is not included.

**Known workarounds**

Provide a description of any known workarounds.

**Related information**

Provide any related information (optional):

main branch at b822e2793bd6387c40cfd5b25d604e002a253257

@dsyme do you agree this is a parser bug?
If so I'd like to take a stab at this.

**Comment by dsyme** [comment]
Yes this range should be included (and I guess the range of the `=` included in trivia?)

**Comment by nojaf** [comment]
Yes, `=` should be captured in the trivia indeed.
