### ISSUE TITLE
Culture sensitive tests

### ISSUE THREAD

**Issue by thinkbeforecoding** [dotnet/fsharp#13212]
Some tests are culture sensitive and fail on non en-US machines. It makes running test suites localy difficult when working on new PR.

Provide the steps required to reproduce the problem:

1. Run tests on a machine that is not installed with en-US culture
2. See it fail on UI message comparisons
![image](https://user-images.githubusercontent.com/146717/171132563-9120ccd6-3652-4101-a090-81fca8964b1f.png)
(yes I'm french)

**Expected behavior**

Tests pass on all machines independently of their culture.

**Actual behavior**

Tests fail.

**Known workarounds**

Change the culture of the machine (tedious). Not run test suites (dangerous). 

**Related information**

Some tests fail due to warning/error message comparison, other due to number formatting ( "5,0" <> "5.0" )

**Comment by thinkbeforecoding** [comment]
For tests that run in process, NUnit has SetCulture("en-US")/SetUICulture("en-US") attributes.
For tests that run out of process, launching fsi or fsc, the --preferreduilang:en-US flag should be specified.

**Comment by vzarytovskii** [comment]
We need to find a way of doing that for xUnit too. There is cultured fact and theory. It would be good to have same culture by default, and use specific one if needed per test basis.

**Comment by vzarytovskii** [comment]
xUnit supports setting culture via config it seems

**Comment by thinkbeforecoding** [comment]
Oh, actually it's worse than what I thought... The SR (for string resource) is autogenerated with the following code:

``` fsharp
module internal SR =
    type private C (_dummy:System.Object) = class end
    let mutable Culture = System.Globalization.CultureInfo.CurrentUICulture
    let ResourceManager = new System.Resources.ResourceManager("FSCore", C(null).GetType().GetTypeInfo().Assembly)
    let GetString(name:System.String) : System.String = ResourceManager.GetString(name, Culture)
    let GetObject(name:System.String) : System.Object = ResourceManager.GetObject(name, Culture)
```
And in the case of FSI, the initialization of a module early in the setup (and before using the preferreduilang flag) is using GetString. At that time, CurrentUICulture is still fr-FR on my machine, and it is captured in the Culture variable.

Setting the CurrentUICulture later doesn't change the captured value, so many exceptions continue to be displayed in fr-FR while CurrentUICulture is en-US.

Maybe we should call CurrentUICulture directly instead of caching it ?
