### ISSUE TITLE
Cannot make HTTP requests from `.fsx` script compiled by `FSharp.Compiler.Services` in `net48` host application

### ISSUE THREAD

**Issue by tymokvo** [dotnet/fsharp#13227]
Hello,

Thanks for making F#, it's great 😺 .

We use a closed source application which allows adding functionality via the .NET plugin system. We have been using `FSharp.Compiler.Services` to create a scripting interface to this application. This has been working very well for many of our use cases. 

However, we need to be able to make HTTP requests and it is proving to be difficult. I believe that we have a conflict between the various APIs of the dotnet target frameworks and I'm trying to figure out what the best way to resolve this is.

I asked a question in the F# slack [here](https://fsharp.slack.com/archives/C1KANN0BV/p1654013608198119), but I don't think I was able to describe the situation very well, so I'm raising it here with more background.

**Repro steps**

I can create a repo that mimics the host/plugin/script structure, but it might be misleading as the host application is closed source and I don't actually know how they implement their plugin system. At the very least, writing plugins that target `net48` is meant to have first-class support from the developer.

Provide the steps required to reproduce the problem:

1. Have .NET Framework host application using plugin framework
1. Author plugin using F#, targeting `net48`
    - Add dependency on `FSharp.Compiler.Service`
1. Create `Script.fsx` which uses `System.Net.Http.HttpClient.GetStringAsync`
1. In the plugin, call `FSharpChecker.CompileToDynamicAssembly` on `Script.fsx`

The content of the script that I cannot get to work is:
```fsharp
use client = new HttpClient()

client.GetStringAsync(uri)
|> Async.AwaitTask
|> Async.RunSynchronously
```

**Expected behavior**

The script is executed by the host application via the plugin and is able to send the content back to the host application.

**Actual behavior**

Using any of the 3 values for `--targetprofile` in the arguments for `CompileToDynamicAssembly` results in 2 different failure modes:

### `netcore`/`netstandard`
```
type 'System.Diagnostics.DebuggerNonUserCodeAttribute' not found in assembly 'System.Runtime, Version=6.0.0.0 [trimmed]
```

### `mscorlib` (Works for everything except HTTP)
```
error The namespace 'Http' is not defined [trimmed]
```

This one makes the most sense as `mscorlib` doesn't define the `System.Net.Http` namespace. But, it would be great to know if there's an accepted way to make HTTP requests when targeting `mscorlib`. 

**Known workarounds**

None yet

**Related information**

- OS: Windows 10
- Runtime: `net48`

**Comment by goswinr** [comment]
I ran this hosting fsi in a net48 process. It worked all fine : 
![image](https://user-images.githubusercontent.com/884885/173578709-e2f7ef9a-fcd4-4ed1-bab8-c16d47f44a65.png)

**Comment by edgarfgp** [comment]
By the comments in this issue . This seems to be no longer an issue . @vzarytovskii should we close this ?
