### ISSUE TITLE
"Find all references" not working for F#

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#13226]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Find-all-references-not-working-for-F/10043912)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.1]
Using Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview Version 17.3.0 Preview 1.0 (and for at least one previous version) Find All References has not been working in F#, on a multi-project solution that currently compiles correctly.

(This report is coming from a personal MSA; you can find me in the GAL as scarbeit.)

---
#### Feedback Bot on 5/17/2022, 08:07 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by vzarytovskii** [comment]
It is definitely related to https://github.com/dotnet/fsharp/issues/12982

We are trying to get to the bottom of it.

**Comment by dsyme** [comment]
The related bug is fixed
