### ISSUE TITLE
Better representation of get/set member

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#13273]
Giving the following code and AST:
```fsharp
type Foo() =
    member this.MyReadWriteProperty
        with get () =   //comment get 
            myInternalValue
        and set (value) =   // comment set
            myInternalValue <- value
```

```fsharp
SynTypeDefn
   (SynComponentInfo
      ([], None, [], [Foo],
       PreXmlDoc ((2,0), FSharp.Compiler.Xml.XmlDocCollector),
       false, None, tmp.fsx (2,5--2,8)),
    ObjectModel
      (Unspecified,
       [ImplicitCtor
          (None, [], SimplePats ([], tmp.fsx (2,8--2,10)), None,
           PreXmlDoc ((2,8), FSharp.Compiler.Xml.XmlDocCollector),
           tmp.fsx (2,5--2,8));
        Member
          (SynBinding ...
        Member
          (SynBinding ...
```

It is very confusing that there are two `SynMemberDefn.Member` created for this in the untyped tree.

**Describe the solution you'd like**

Could we have a special case in `SynMemberDefn` that represents this better?
The name `SynMemberDefn.ReadWriteProperty`comes to mind, but I'm open to suggestions.

**Describe alternatives you've considered**

Both `Member`s have the same range, so you can hack around it.

**Additional context**

related: #11481

//cc @dsyme

**Comment by dsyme** [comment]
Yes, agreed we should represent this much more directly
