### ISSUE TITLE
Rename hangs forever

### ISSUE THREAD

**Issue by Happypig375** [dotnet/fsharp#13284]
![image](https://user-images.githubusercontent.com/19922066/173244487-0ac53b49-af96-4f29-9de1-5b78475b63df.png)

**Repro steps**

1. Clone https://github.com/Happypig375/PedoApp2/tree/81368459badc25f16722a1629bf7c18c8ed16c8d
2. Open Views.fs
![image](https://user-images.githubusercontent.com/19922066/173244543-6e4c0407-2f1a-41bd-8ab0-229e970df865.png)
3. On line 164, rename `info_totalX` -> `info_totalWidth`
4. Hang
![image](https://user-images.githubusercontent.com/19922066/173244653-ddb6ceb3-1106-4113-878b-a48aded25f96.png)

**Expected behavior**

Rename succeeds.

**Actual behavior**

Rename hangs.

**Known workarounds**

Do it manually using Find and Replace.

**Related information**

Provide any related information (optional):

* Operating system Windows
* .NET Runtime kind (.NET Core, .NET Framework, Mono) .NET Standard 2.0
* Editing Tools (e.g. Visual Studio Version, Visual Studio) Visual Studio 17.2.3

**Comment by 0101** [comment]
@Happypig375 I cannot reproduce this. 

But there is a very similar issue that is reproducing for me: https://github.com/dotnet/fsharp/issues/14001 so I'm just going to continue with that one.
