### ISSUE TITLE
CodeLens in Visual Studio 2022 causes code line to disappear 

### ISSUE THREAD

**Issue by siavash-babaei** [dotnet/fsharp#13319]
I use Visual Studio 2022 Community to code in F#. 
I noticed that any sort of button press (DEL, ENTER, …) on a code line involving `let` and function definitions, or `[<Labels>]`  makes the line disappear. It isn’t really gone since if I save and reopen the file, it’s there. It just disappears from view.

After 2 days of fiddling, I figured out that disabling F# CodeLens, solves the issue.

**Comment by vzarytovskii** [comment]
Yes, current codelens implementation is quite buggy, we should be moving to the standard built-in VS one.

**Comment by KevinRansom** [comment]
Thanks for reporting this, Codelens needs a lot of work before we can turn it back on, it is on our backlog, hopefully we can raise the priority.

I am closing this issue a dupe, we currently have quite a few codelens issues :  https://github.com/dotnet/fsharp/issues?q=is%3Aissue+is%3Aopen+codelens
