### ISSUE TITLE
Renaming in VS2022 sometimes garbles rename targets

### ISSUE THREAD

**Issue by JordanMarr** [dotnet/fsharp#13344]
Renaming in Visual Studio 2022 sometimes garbles the rename targets across the codebase.

Repro:

I am not yet able to consistently reproduce this error, but I suspect that it tends to happen in medium to large code bases when you quickly type and hit enter before VS has finished scanning the codebase for the keyword.

This bug report can serve as a placeholder until I can come up with consistent steps to recreate the issue.

**Known workarounds**

There are two workarounds that I have found that seem to mostly eliminate this issue:
1) Always _Save All_ before starting the rename.
2) Pause for a moment after entering the new name in the rename dialog to avoid prematurely starting the rename process before VS has finished scanning and selecting the rename targets.

**Related information**

Provide any related information (optional):

* Operating system: **Windows 10**
* .NET Runtime kind (.NET Core, .NET Framework, Mono): **.NET Framework, .NET Core, .NET 5/6**
* Editing Tools (e.g. Visual Studio Version, Visual Studio): **Visual Studio 2022 Professional**

**Comment by 0101** [comment]
We have other renaming issues with specific repro steps. Please reopen if you can identify a concrete issue with repro steps.
