### ISSUE TITLE
SynType with single slash and type

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#13348]
Consider the following code and AST:

```fsharp
[<Measure>] type herth = / second
// Same AST
[<Measure>] type herth = 1 / second
```

AST:
```fsharp
Types
   ([SynTypeDefn
       (SynComponentInfo
          ([{ Attributes = [ ... ], None, [], [herth],
           PreXmlDoc ((1,0), FSharp.Compiler.Xml.XmlDocCollector),
           false, None, tmp.fsx (1,17--1,22)),
        Simple
          (TypeAbbrev
             (Ok,
              Tuple
                (false,
                 [(true,
                   StaticConstant (Int32 1, tmp.fsx (1,25--1,33)));
                  (false,
                   LongIdent (SynLongIdent ([second], [], [None])))], ...]
Types
   ([SynTypeDefn
       (SynComponentInfo
          ([{ Attributes = [ ... ]
              Range = tmp.fsx (3,0--3,11) }], None, [], [herth],
           PreXmlDoc ((3,0), FSharp.Compiler.Xml.XmlDocCollector),
           false, None, tmp.fsx (3,17--3,22)),
        Simple
          (TypeAbbrev
             (Ok,
              Tuple
                (false,
                 [(true,
                   StaticConstant (Int32 1, tmp.fsx (3,25--3,26)));
                  (false,
                   LongIdent (SynLongIdent ([second], [], [None])))],... ], tmp.fsx (3,0--3,35))
```

**Expected behaviour**

The AST should be different, there is no actual `1` in `/ second`.

**Actual behaviour**

I noticed a shortcut in:

https://github.com/dotnet/fsharp/blob/4be3bb5760e87ac522cd449c317016323f415467/src/Compiler/pars.fsy#L5253-L5255

Perhaps we need a new case for this in [SynType](https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-syntax-syntype.html).
I'm not quite sure if `SynType.Tuple` is quite correct to capture `a / b` in the first place.
How should this be modelled? Any Ideas @dsyme and @auduchinok?

//cc @edgarfgp

**Comment by auduchinok** [comment]
> I'm not quite sure if SynType.Tuple is quite correct to capture a / b in the first place.

Yes, the tuple doesn't sound like the appropriate case here.

> How should this be modelled? Any Ideas @dsyme and @auduchinok?

Are there any other type math cases that we could take into account?
