### ISSUE TITLE
NRE in task builder with SkipLocalsInit after certain amount of invocations in Release

### ISSUE THREAD

**Issue by kerams** [dotnet/fsharp#13386]
An ASP.NET middleware started crapping out on me under mysterious circumstances, but after a couple of hours I've managed to narrow the problem down to a combination of `SkipLocalsInit` and task builder (where the body is of certain minimal complexity).

**Repro steps**

```fsharp
module Program

open System.Threading.Tasks

[<System.Runtime.CompilerServices.SkipLocalsInit>]
let broken1 () =
    (task {
        try
            do! Task.Delay 10
        with e ->
            eprintfn "%s" (e.ToString ())
    }).Wait ()

let ok1 () =
    (task {
        try
            do! Task.Delay 10
        with e ->
            eprintfn "%s" (e.ToString ())
    }).Wait ()

[<System.Runtime.CompilerServices.SkipLocalsInit>]
let ok2 () =
    (task {
        try
            do! Task.Delay 10
        with e ->
            ()
    }).Wait ()

[<System.Runtime.CompilerServices.SkipLocalsInit>]
let ok3 () =
    async {
        try
            do! Async.Sleep 10
        with e ->
            eprintfn "%s" (e.ToString ())
    }
    |> Async.RunSynchronously

[<EntryPoint>]
let main _ =
    let mutable times = 0

    try
        for i in 1 .. 200 do
            broken1 ()
            //ok1 ()
            //ok2 ()
            //ok3 ()
            times <- i
    with e ->
        eprintfn "Invocations: %d, %s" times (e.ToString ())

    0
```

Target `net7.0`, run in Release, uncomment one function at a time to see what happens.

**Expected behavior**

No exceptions after calling `broken1` hundreds of times.

**Actual behavior**

`broken1` starts throwing every time after being invoked 30 - 40 times.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Program.broken1@7.MoveNext() in Program.fs:line 11
```

**Known workarounds**

Remove `SkipLocalsInit`.

**Related information**

* Win 10, Ubuntu 22.04
* SDK 7.0.100-preview.3.22179.4 and 7.0.100-preview.5.22307.18

**Comment by vzarytovskii** [comment]
@kerams does it only reproduce with net7 target? Or 6 too? 
Did you  try running PGO on 7 and see if it fails straight away?

It sounds like JIT kicks in and the compiled function starts failing.

@EgorBo does this, by any chance, ring a bell to you?

**Comment by kerams** [comment]
It's the same when targetting `net6`, but it doesn't manifest in Debug. Good should about JIT, when I disable tiered compilation, the task fails on the first try.

**Comment by vzarytovskii** [comment]
> It's the same when targetting `net6`, but it doesn't manifest in Debug. Good shout about JIT - when I disable tiered compilation, the task fails on the first try.

Hm, interesting, so it's some sort of combination of our codegen (when optimizations are on) and JIT. Will try to look at it on Monday.

**Comment by EgorBo** [comment]
Minimal repro:
```fsharp
module Program
open System.Threading.Tasks

[<System.Runtime.CompilerServices.SkipLocalsInit>]
[<EntryPoint>]
let main _ =
    (task {
        try
            do! Task.Delay 10
        with e ->
            e.ToString ()
    }).Wait ()
    0
```
with `DOTNET_TieredCompilation=0`
I am not sure if there a separate jit codegen bug anywhere but it looks to me that F# propagated `[<System.Runtime.CompilerServices.SkipLocalsInit>]` to not just `main` as it supposed to do but also to a state machine it emitted for `main` - `main@::MoveNext`:
![image](https://user-images.githubusercontent.com/523221/175827151-b1099087-2e0d-4c5d-9fa1-0ccd60b12799.png)

**Comment by EgorBo** [comment]
Questionable piece:
![image](https://user-images.githubusercontent.com/523221/175827885-9f4bd081-a38b-4b30-9ff5-d6819c824707.png)

**Comment by kerams** [comment]
Related codegen:

https://github.com/dotnet/fsharp/blob/50bbec3cb818f7aaeae0db4ce499855834c80205/src/Compiler/CodeGen/IlxGen.fs#L5467-L5493
