### ISSUE TITLE
Update System.Memory to verson 4.5.5

### ISSUE THREAD

**Issue by lbussell** [dotnet/fsharp#13395]
See https://github.com/dotnet/fsharp/pull/13394#issuecomment-1167984452

The latest version of System.Memory is 4.5.5: https://www.nuget.org/packages/System.Memory. Referencing version 4.5.4 causes a package downgrade error since some of fsharp's dependencies rely on the newer version. See the dependency flow from the build failure:

```
FSharp.Build -> System.Memory (>= 4.5.4)
FSharp.Build -> Microsoft.Build.Tasks.Core 17.3.0-preview-22323-15 -> Microsoft.NET.StringTools 1.0.0-preview-22323-15 -> System.Memory (>= 4.5.5)
```

Upgrading this package prevents the package downgrade error in source-build.

**Comment by T-Gro** [comment]
This was done.
