### ISSUE TITLE
Reference assemblies may be missing some properties

### ISSUE THREAD

**Issue by ncave** [dotnet/fsharp#13433]
Please feel free to ignore/close if not a real issue.
Seems to be affecting mostly properties on generic types.

Here are some of the errors I get when trying to use reference assemblies generated with `referenceAssemblyOnly = true`:
[reference_assembly_errors](https://gist.github.com/ncave/e783e27a40745f137806df3752cf5d52)

**Comment by vzarytovskii** [comment]
It seems like a bug, thanks for logging it, we'll need yo look at it.

**Comment by vzarytovskii** [comment]
I believe this was fixed by #14093
