### ISSUE TITLE
Do we still need the ENABLE_MONO_SUPPORT code

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#13443]
We have a few places in the code protected by ENABLE_MONO_SUPPORT, this is enabled for the desktop build.  But I don't think we need it.

/cc @nosami

**Comment by nosami** [comment]
I wasn't 100% sure about this so I needed to go and double check.

- VSMac itself uses the CoreCLR to host FCS for design time builds.
- Web apps typically use CoreCLR these days. I would think that any web apps using Mono would be extremely rare. None of the templates are using the Mono compiler.
- MAUI apps use the CoreCLR compiler.
- _Any Xamarin app written before MAUI uses the Mono compiler (Xamarin Forms etc). This might be an issue as I am sure there are lots of these apps still out in the wild. These apps can however be upgraded to use MAUI._

**Comment by nosami** [comment]
Some existing Xamarin Forms apps (Mono) cannot yet be ported to MAUI due to a lack of 3rd party plugins.

**Comment by KevinRansom** [comment]
I'm gonna go with removing this code then.  comments?

**Comment by Happypig375** [comment]
> _Any Xamarin app written before MAUI uses the Mono compiler (Xamarin Forms etc). This might be an issue as I am sure there are lots of these apps still out in the wild._

@TimLariviere is the expert in this area

**Comment by vzarytovskii** [comment]
> I'm gonna go with removing this code then. comments?

I am not sure we should, I know a bunch of people using Xamarin (pre-maui), don't know though how often does mono update the compiler.

**Comment by nosami** [comment]
> I am not sure we should, I know a bunch of people using Xamarin (pre-maui), don't know though how often does mono update the compiler.



I'm not really sure that it's going to matter. There are currently no plans to update Mono or the F# compiler within the Mono distribution. Everybody who worked on the Mono runtime now works on CoreCLR.



Anybody who wants to continue using the Mono F# compiler can continue to do so.



> At least, looks like this change affects at least Fabulous



Fabulous will presumably be based on MAUI in the future instead of Xamarin Forms. Xamarin Forms is no longer being developed and will no longer be supported after January 2023.

**Comment by TimLariviere** [comment]
I agree with @nosami, it's not going to matter if F# removes Mono support.
We already can't use the latest F# versions in Xamarin and Xamarin.Forms projects anyway.

The Mono F# compiler has always been late getting the latest F# versions. For example, it took 2 years just to move from F# 4.5 to 5.0, and F# 6.0 support is never going to happen.

Moving to the new `net6.0-ios` / `net6.0-android` targets already give us F# 6.0 and SDK-style projects for free.
So I think it should be fine.

My only concern is: do those new targets still rely on Mono somehow?
Or this change is really only about the compiler itself?

**Comment by KevinRansom** [comment]
@vshapenko , we don't build Mono, we don't test Mono, I can't remember the last genuine Mono bug report impacting the compiler.  As far as we understand VS4Mac takes our builds and reships them.  And we are talking about the compiler here.  So the reason for asking the question, is to identify whether this is really dead code.  And TBH it sounds an awful lot like dead code to me right now.


Kevin
