### ISSUE TITLE
last version of VS2019 fails with #I __SOURCE_DIRECTORY__

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#13467]
**Repro steps**

* Update VS2019 to latest release
* open developer command prompt
* run `fsianycpu`
* input the following code
   
    ```fsharp
    #I __SOURCE_DIRECTORY__;;
    ```
**Expected behavior**

Should work, it worked before updating.

**Actual behavior**

> stdin(1,4): error FS0010: Unexpected compiler generated literal in interaction. Expected incomplete structured construct at or before this point, ';', ';;' or other token.

**Known workarounds**

change scripts

```fsharp
#I ".";;
```

**Related**

Since this was a regression and it shipped at some point in latest update of VS2019 (breaks many customers), can we get the same fix as what went in VS2022 for it?

Related:
* #11732 
* #11733
* https://stackoverflow.com/questions/68465249/f-fsi-unexpected-compiler-generated-literal-in-interaction-with-i-source

**Comment by smoothdeveloper** [comment]
Some places where it shows in the public ecosystem:

* https://github.com/fslaborg/FSharp.Charting/blob/ae56016bbba08d42b7a1edc456f687e937a23e88/FSharp.Charting/FSharp.Charting.fsx#L18
* https://github.com/mbraceproject/MBrace.Azure/blob/1.4.1/nuget/MBrace.Azure.fsx#L1

**Comment by vzarytovskii** [comment]
I don't think this will meet the bar for the 2019

cc @KevinRansom

**Comment by smoothdeveloper** [comment]
In meantime, can we have instruction as to how to install VS2019 that doesn't have this bug, a specific version of VS2019 and buildtools?

It is not good to have regression in last release before product goes stagnant, and it being fixed only in next major release (which requires licensing, and making sure it works for shipping stuff which used VS2019 build tools for every consumer that ships bits with VS 2019 build tools).

I think the usage of this `#I __SOURCE_DIRECTORY__` is pervasive enough that it warrants the fix goes in.

**Comment by KevinRansom** [comment]
@smoothdeveloper , I'm afraid this will not make the bar for servicing VS2019.
