### ISSUE TITLE
Custom Viewer for datatable / dataset not working in F# debugger

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#13482]
**Repro steps**

In Visual Studio (2022 here)

```fsharp
open System.Data

let table = new DataTable("test")
table.Columns.Add("a", typeof<string>)
table.Columns.Add("b", typeof<int>)

table.Rows.Add("a",1) |> ignore
table.Rows.Add("b",2) |> ignore

table
```

* debug the script till point there is one record in the table
* after hovering on `table` symbol, click on view
 
**Expected behavior**

I would like it to work the same as in C# or VB.NET debugger, it should show what is described on https://docs.microsoft.com/en-us/visualstudio/debugger/dataset-visualizer-dialog-box?view=vs-2022

**Actual behavior**

It shows
> Could not load this custom viewer.

![image](https://user-images.githubusercontent.com/87944/178225747-ed97ddf0-4bed-4f47-ada5-cdf1313cd9e5.png)

**Known workarounds**

Not found.

**Related information**

* Windows 11 Pro build 22598.200
* VS 2022 17.2.0
* .NET Framework 4.8

**Comment by psfinaki** [comment]
@smoothdeveloper this can be closed now, right?

**Comment by smoothdeveloper** [comment]
@psfinaki 100% although I was just waiting to try it out in a future preview release.

I think it doesn't matter, so closing and will reopen if a future preview doesn't have it in a while.
