### ISSUE TITLE
Reference assemblies error with constructors hidden by signature

### ISSUE THREAD

**Issue by ncave** [dotnet/fsharp#13487]
Looks like generating a reference assembly can error out in certain cases when constructors are hidden by the signature file (even if the constructor is marked as internal in the implementation).

See for example #13385 (`FSharp.Core` as reference.assembly).

**Comment by vzarytovskii** [comment]
Hm, yeah, we should fix it. Should be a simple fix.

**Comment by nojaf** [comment]
Hello @ncave, I believe this problem is solved by https://github.com/dotnet/fsharp/pull/13522.
Would you mind trying this again from the latest main?

**Comment by vzarytovskii** [comment]
> @nojaf Getting this error, not sure if it's related or not:
> 
> ```
> A method in 'Microsoft.FSharp.Core.NoDynamicInvocationAttribute' had the right name but the wrong signature:
> generic arity: 0
> mdkey2: FSharp.Compiler.AbstractIL.ILBinaryWriter+MethodDefKey
> Export error: Error in pass3 for type Microsoft.FSharp.Core.Operators, error: Error in GetMethodRefAsMethodDefIdx for mref = (".ctor", "Microsoft.FSharp.Core.NoDynamicInvocationAttribute"), error: Exception of type 'FSharp.Compiler.AbstractIL.ILBinaryWriter+MethodDefNotFound' was thrown.
> A method in 'Microsoft.FSharp.Core.NoDynamicInvocationAttribute' had the right name but the wrong signature
> ```

How did you test it? It should've been fixed for attributes in `main`.

**Comment by nojaf** [comment]
Sigh, I'm getting this as well when I run `dotnet build src\FSharp.Core\FSharp.Core.fsproj` after setting ` <ProduceReferenceAssembly>true</ProduceReferenceAssembly>`.

**Comment by ncave** [comment]
@vzarytovskii 
I'm setting the `referenceAssemblyOnly = true` flag internally, but probably using `<ProduceReferenceAssembly>true</ProduceReferenceAssembly>` works too.

**Comment by vzarytovskii** [comment]
> @vzarytovskii I'm setting the `referenceAssemblyOnly = true` flag internally, but probably using `<ProduceReferenceAssembly>true</ProduceReferenceAssembly>` works too.

No, I mean which package do you use? Do you just build FCS from the repo and use the api? If I wanted to reproduce it, how would I do it exactly?

**Comment by nojaf** [comment]
Local FCS build from main, set the flag and compile FSharp.Core.

**Comment by vzarytovskii** [comment]
It seems I cannot reproduce it, are you sure it is using the latest compiler?

**Comment by vzarytovskii** [comment]
I've added similar test here:
https://github.com/dotnet/fsharp/pull/13587/files

@nojaf can you please share the FCS test with me? It will be easier for me to debug.

**Comment by nojaf** [comment]
Yes, however, I'm not able to reproduce this anymore.

Locally I have, 

commit e63d48c7906d661ddd1bf73e1654072b5e18c80c (HEAD -> main, upstream/main, origin/main, origin/HEAD)
Author: dotnet-maestro[bot] <42748379+dotnet-maestro[bot]@users.noreply.github.com>

Did a:

- `git clean -xdf`
- `.\Build.cmd -noVisualStudio`
- `dotnet build .\src\FSharp.Core\FSharp.Core.fsproj /p:ProduceReferenceAssembly=true -v n`

It created `fsharp\artifacts\obj\FSharp.Core\Debug\netstandard2.0\refint\FSharp.Core.dll` without any problems.

**Comment by ncave** [comment]
@vzarytovskii @nojaf

Strange enough, I tried it again and it now works for me too. Did something change in the mean time?

I assume #13433 still needs to be resolved before `FSharp.Core` can be actually usable as a reference assembly.

Anyway, I can close this issue. Thanks!
