### ISSUE TITLE
Do we really need NO_TYPEPROVIDERS we don't seem to set it.

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#13491]

**Comment by dsyme** [comment]
We should keep it, and I believe we should build the compiler with it in some form.   My preference is really to build Proto without TP support.

In terms of why 

1. I'm pretty certain Fable sets this for their bootstrap of the compiler into the Javascript-hosted compiler.  I don't think we should pull the plug on our small part of enabling that.

2. It's also a matter of long-term feature hygiene - TPs are so strongly tied to .NET and quotations that there will always be scope for cuts of F# that don't support them, both now and long term into the future.  For example imagine a cut of the F# compiler that compiles to native (in addition to the transpiling cuts in Fable).

**Comment by ncave** [comment]
It would be helpful to keep those, if that's possible.

Fable currently uses `NO_TYPEPROVIDERS` for compiling FCS to JavaScript for its REPL, and for `fable-compiler-js` (which is a F# to JS transpiler running on Node.js/JavaScript without .NET installed).

**Comment by dsyme** [comment]
@ncave I'm wondering if you would consider submitting an adjustment to our CI in this repo which compiles FSharp.Compiler.Service.fsproj with NO_TYPEPROVIDERS set?

**Comment by auduchinok** [comment]
@dsyme You mean as a separate build, right?

**Comment by KevinRansom** [comment]
Happy to keep it then.
