### ISSUE TITLE
Obsolete warning isn't produced for some obsolete symbol usages

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#13511]
```csharp
[Obsolete("Class is obsolete")]
public class ObsoleteClass
{
}
```
```fsharp
let c1: ObsoleteClass = null
let c2 = ObsoleteClass()
```

Two warnings are expected, but only one is produced:
<img width="348" alt="Screenshot 2022-07-14 at 13 24 24" src="https://user-images.githubusercontent.com/3923587/178971859-a45e4dd9-cbe8-488b-b843-c6eba65ced62.png">

C# compiler produces two warnings:

```csharp
ObsoleteClass c = new ObsoleteClass();
```
<img width="305" alt="Screenshot 2022-07-14 at 13 27 20" src="https://user-images.githubusercontent.com/3923587/178972345-667efe53-b14e-4b54-87f3-e569b9e7cef5.png">

**Comment by vzarytovskii** [comment]
Is it on the `main`, or latest stable? I remember @edgarfgp was doing some changes there?

**Comment by auduchinok** [comment]
It's in 6.0.301 and in FCS from ~March.

**Comment by auduchinok** [comment]
There's the same behaviour for structs and delegates:

<img width="368" alt="Screenshot 2022-07-14 at 13 43 28" src="https://user-images.githubusercontent.com/3923587/178974801-a19dde25-f089-499d-8f15-9e0cfc5eeabc.png">

**Comment by auduchinok** [comment]
```csharp
public class Class
{
    [Obsolete("Field is obsolete")] public static readonly int ObsoleteField = 1;

    [Obsolete("Method is obsolete")]
    public static void ObsoleteMethod()
    {
    }

    [Obsolete("Property is obsolete")] public static int ObsoleteProperty => 1;

    [Obsolete("Event is obsolete")] public static event EventHandler ObsoleteEvent;
}
```

No warning is produced for the event:

<img width="289" alt="Screenshot 2022-07-14 at 14 15 44" src="https://user-images.githubusercontent.com/3923587/178980468-50031860-cfc5-425c-bca0-120445367db8.png">

**Comment by edgarfgp** [comment]
I installed VS preview and I'm getting warning and errors  where they are expected I believe . Expect for
```csharp
 [Obsolete("Event is obsolete")] public static event EventHandler ObsoleteEvent;
```

```fsharp
  Class.ObsoleteEvent |> ignore
```
So I think that might be a case that still missing

**Comment by edgarfgp** [comment]
@auduchinok I believe I have covered all the cases in this issue including events 😀See https://github.com/dotnet/fsharp/blob/main/tests/FSharp.Compiler.ComponentTests/Language/ObsoleteAttributeCheckingTests.fs

**Comment by T-Gro** [comment]
> @auduchinok I believe I have covered all the cases in this issue including events 😀See https://github.com/dotnet/fsharp/blob/main/tests/FSharp.Compiler.ComponentTests/Language/ObsoleteAttributeCheckingTests.fs

Good job Edgar!

Can this issue now be closed ?
