### ISSUE TITLE
`dotnet fsi --help` does not show option help

### ISSUE THREAD

**Issue by bmitc** [dotnet/fsharp#13520]
**Repro steps**

1. Run `dotnet fsi --help` or `dotnet fsi -?` or `dotnet fsi -h` in the command line

**Expected behavior**

Options should be listed, according to https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/fsharp-interactive-options

**Actual behavior**

No options are shown, and a sort of recursive suggestion of using the same options that were used is shown.

```powershell
PS > dotnet fsi --help
Description:

Usage:
  dotnet fsi [options]

Options:
  -?, -h, --help  Show command line help.
```

**Known workarounds**

View the options here: https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/fsharp-interactive-options

**Related information**

Provide any related information (optional):

* Operating system: Windows 11 and Ubuntu (via WSL2)
* .NET Runtime kind (.NET Core, .NET Framework, Mono): F# Interactive version 12.0.4.0 for F# 6.0
* Editing Tools (e.g. Visual Studio Version, Visual Studio): n/a

**Comment by baronfel** [comment]
This should be raised in the dotnet/SDK repo. The dotnet FSI command is defined in that repo, and probably the simplest implementation would be to pass through the help on the FsiCommand there to invoke the help on FSI.dll directly.

**Comment by bmitc** [comment]
Thanks @baronfel. I tried searching and saw some FSI stuff defined here, but wasn't for sure exactly what repository it belongs in. Does anyone here have permissions in both repositories to move it over? Or should I just recreate it there?

**Comment by baronfel** [comment]
Weird, I can usually move issues between dotnet repos. Might need to log into my work machine - I can try that later if no one else has transferred it.

**Comment by abelbraaksma** [comment]
I just tried `dotnet fsi --help` on a Windows 10 and 11 machine, both in PS and on a normal command prompt, and it "just works", i.e., I get this output (which is much better than I remembered it to be):

```text
PS D:\> dotnet fsi --help
Microsoft (R) F# Interactive version 12.0.1.0 for F# 6.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

Usage: dotnet fsi <options> [script.fsx [<arguments>]]


                - INPUT FILES -
--use:<file>                             Use the given file on startup as initial input
--load:<file>                            #load the given file on startup
--reference:<file>                       Reference an assembly (Short form: -r)
--compilertool:<file>                    Reference an assembly or directory containing a design time tool (Short
                                         form: -t)
--usesdkrefs[+|-]                        Use reference assemblies for .NET framework references when available
                                         (Enabled by default).
-- ...                                   Treat remaining arguments as command line arguments, accessed using
                                         fsi.CommandLineArgs


                - CODE GENERATION -
--debug[+|-]                             Emit debug information (Short form: -g)
--debug:{full|pdbonly|portable|embedded} Specify debugging type: full, portable, embedded, pdbonly. ('pdbonly' is the
                                         default if no debuggging type specified and enables attaching a debugger to
                                         a running program, 'portable' is a cross-platform format, 'embedded' is a
                                         cross-platform format embedded into the output file).
```

I didn't try WSL2/Ubuntu though.

**Comment by baronfel** [comment]
The relevant versions would be which .net SDK - sounds like sometime in the 6.0 range the SDK improved this?

**Comment by abelbraaksma** [comment]
@baronfel, got it. Looks like my Windows system is a bit behind w.r.t. to SDK, 6.0.203. So I just installed latest on local Ubuntu on WSL 2 (following [these instructions](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2004), there's a first time for everything) and I got the same as @mbitc:

```text
~$ dotnet fsi --help
Description:

Usage:
  dotnet fsi [options]

Options:
  -?, -h, --help  Show command line help.
```

**Comment by baronfel** [comment]
Most of the other commands are implemented as actual system.commandline commands. Some, like Nuget, FSI, MSBuild, and others, forward along to other binaries shipped in the SDK. For those, we've customized help output to forward the help request to the underlying binary (as opposed to the default system.commandlime help output that you're seeing here generated for FSI).

**Comment by baronfel** [comment]
I opened a PR on the SDK target for .NET 7 to address this. It probably wouldn't be a high enough severity to make it into 6.0 servicing fixes, though.

**Comment by abelbraaksma** [comment]
>  It probably wouldn't be a high enough severity to make it into 6.0 servicing fixes, though.

To be fair, iiuc, it appears to have been broken by a servicing fix, as I show above, slightly olde .NET 6 versions don’t have this behaviour. So a servicing fix needs a servicing fix ;).

**Comment by abelbraaksma** [comment]
Btw: amazingly fast PR!

**Comment by bmitc** [comment]
Thanks so much @baronfel! It looks like your fix has already been merged. Thanks for doing that so quickly!
