### ISSUE TITLE
Some features of the new UoM support are still "this feature is experimental" warnings

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#13548]
The excellent new feature by @pblasucci (see #9978) provides support for UoM (Units of Measure) for all other primitive types (unsigned integers, native pointer types). The introduction of this has been mentioned in the [What's new in F# 6.0](https://docs.microsoft.com/en-us/dotnet/fsharp/whats-new/fsharp-6#additional-numeric-types-with-unit-annotations) post and on some conference talks.

However, the added functions in FSharp.Core that come with this feature still raise the warning that this feature is experimental:

![image](https://user-images.githubusercontent.com/16015770/180405326-11c21dbd-223c-4330-880e-a13c6c942e32.png)

**Repro steps**

Any code that uses the `LanguagePrimitives` UoM conversion functions, like this ([inspired by the RFC](https://github.com/fsharp/fslang-design/blob/main/FSharp-6.0/FS-1091-Extend-Units-of-Measure.md)):

```f#
[<Measure>] type days
let better_age: uint16<days> = LanguagePrimitives.UInt16WithMeasure(uint16 10)
```

**Expected behavior**

Usage of such code should not raise any warning.

**Actual behavior**

Users will see an "this is an experimental feature" warning in F# 6.0, telling them it requires `--langversion:preview`.

> warning FS0057: Experimental library feature, requires '--langversion:preview'. This warning can be disabled using '--nowarn:57' or '#nowarn "57"'.

**Known workarounds**

You can ignore the warning. The code appears to compile just fine without setting the `--langversion:preview`. Though I didn't check the IL (which may make little sense as the UoM doesn't lead to different IL afaik).

**Related information**

F# 6.0 with .NET 6 and FSharp.Core 6.0.5.

I also noted that it appears that the down-scaling of `land` and other OCaml operators does _not_ lead to a warning, which is contrary to what's mentioned in that same "What's new in F# 6.0" post, but I'll dig a little deeper into that and post it separately.

**Comment by dsyme** [comment]
This was fixed somewhere along the way

**Comment by abelbraaksma** [comment]
@dsyme So that means it'll be fixed in F# 7 / .NET 7? Currently, this warning is still raised (.NET 6.0, VS 2022).

Perhaps not a big issue, considering the next version is almost around the corner.
