### ISSUE TITLE
FSharp.Compiler.Service version # strategy

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#13572]
Several people have commented that it is difficult to associate an FCS nuget package with a shipped F# toolset.

Here I will propose a strawman, will it be sufficient? do we need to address it at all?

Each release of Visual Studio ships with specific dotnet sdk..
I.e.

VS2022.2.6 ships with 6.0.302
VS2022.4.1 preview ships with 7.22370.3 preview

VSCode ships with specific SDK's and the ability to upgrade.  Similarly I expect Rider and it's tooling focus' on the SDK.
So it is possible with relatively little experience to map from VS to an SDK, and from common F# editors to an SDK.

Therefore the most useful mapping is from FCS to a dotnet SDK.

1.  **We should at a minimum** update the FSharp.Compiler.Service description/readme to identify the Dotnet Sdk and VS version that matches the FCS packaged.  This is an amusing inversion but I guess the DotNet SDK and VS are slightly more well known than the F# compiler.
2.  Every new major release of the DotnetSDK, I.e 5.0, 6.0, 7.0 we will rev the Major Version # of the FSharp.Compiler.Service nuget package.
3. The Minor Version # of the package will match the major version # of the sdk
4. The Patch # of the nuget package will match the sdk patch 13549 

[How the sdk versions:](https://docs.microsoft.com/en-us/dotnet/core/versions/)
[nuget.org Fsharp.Compiler.Service](https://www.nuget.org/packages/FSharp.Compiler.Service)

So ... from VS2022.4 / dotnet sdk 7.100 onwards the nuget package for FSharp.Compiler.Service will be:

````
FCS Package                DotNet Sdk                  Visual Studio
42.7.100                       7.0.100                         2022.4
42.7.101-PreviewABC  7.0.101-PreviewDEF     2022.5-Preview1-XYZ
42.7.101                       7.0.101                         2022.5
````

1.  We can't align the Preview build numbers because, F#, the dotnetsdk and VS all have independent build and insertion mechanisms
2.  Options:
-    Update FCS package major version only on breaking change
-    Update FCS package major version every major version of the dotnet SDK
3. Regardless on the answer to 2 above we could choose to start at 42. or if we choose breaking changes for revised # we could continue with 41.7.100
4. Do none of the above stay with current mechanism, provide details in nuspec description.

Nuspec:
currently:
<description>
The F# Compiler Services package for F# 6.0 exposes additional functionality for implementing F# language bindings, additional tools based on the compiler or refactoring tools. The package also includes F# interactive service that can be used for embedding F# scripting into your applications.  Contains code from the F# Software Foundation.

This package corresponds to the tools shipped in:
     Dotnet SDK 7.0.100 [-Preview]
     Visual Studio [2022.5-Preview 1]
</description>

Thoughts, comments, is the above even literate?

Kevin

/cc @baronfel , @vzarytovskii

**Comment by baronfel** [comment]
I'm definitely in favor of having a scheme, _any scheme_ mapping between these things. From a community standpoint I'm not sure that tagging the VS release has the same amount of value as the SDK release, but if it's not too much pain I suppose its ok. Of the three main IDEs (VS, Rider, and VSCode (Ionide)), only Ionide uses the public FCS packages. So this won't directly influence @auduchinok with the Rider integration, it won't influence @nojaf for Fantomas, and it won't influence Fable, since they all use their own builds of FCS.

More broadly, I would expect the proposed scheme to help align community tools like proj-info, FSharp.Formatting, analyzers.

**Comment by KevinRansom** [comment]
Done
