### ISSUE TITLE
Not intelligible error when attempt to paste file from WSL

### ISSUE THREAD

**Issue by kant2002** [dotnet/fsharp#13581]
I did try to Ctrl+C, Ctrl+V file to VS project, and did not realise that file was inside WSL. I was presented with nice message box with error message `Invalid URI: The hostname could not be parsed.`
![image](https://user-images.githubusercontent.com/4257079/181418188-6ec66410-a2f9-4632-b82f-c528350769ea.png)

**Repro steps**

Provide the steps required to reproduce the problem:

1. Open folder from WSL in VS Code
2. Right click on any file, and press "Reveal in Explorer"
3. Ctrl+C on that file
4. Go to F# project
5. Press Ctrl+V to insert file into the project.

**Expected behavior**

Would like either proper error message, that paste from WSL is not supported, or better just copy file to the project.

**Actual behavior**

Aforementioned message box with generic error message.

**Comment by vzarytovskii** [comment]
I don't think it's problem of F#, please log it via VS internal reporting tool.
