### ISSUE TITLE
Exception names with backticks are incorrectly displayed

### ISSUE THREAD

**Issue by psfinaki** [dotnet/fsharp#13593]
Consider the following code:
```fsharp
exception SomeError of ``thing with space``: string
```
The tooltip is displayed like this:
![image](https://user-images.githubusercontent.com/5451366/181817668-d4175315-276b-4a56-a9c2-779a48fdb67b.png)
It looks strange, the backticks should be preserved in the display name.

**Comment by baronfel** [comment]
I'd push back on that - I think that tooltip formatting looks perfectly fine as is. Double backticks in the tooltip would be more visual noise (but it would align with the code written, I'll grant you that).

**Comment by psfinaki** [comment]
@dsyme?

**Comment by vzarytovskii** [comment]
> I'd push back on that - I think that tooltip formatting looks perfectly fine as is. Double backticks in the tooltip would be more visual noise (but it would align with the code written, I'll grant you that).

Yeah, i think as long as it's visually distinguishable (colour, and maybe some additional font styling/formatting, for visually impaired) should he good enough. I think backticks will bring _heaviness_ to the tooltip.

**Comment by baronfel** [comment]
Also from a selfish perspective if the backticks are added to the text portions.of the TaggedTexts then FsAutoComplete will have to do extra work to detect and remove them for tooltips, since backticks are valid markdown characters for styling purposes.

**Comment by dsyme** [comment]
The main thing here is consistency - we should do whatever we do for values, functions, methods, types, union cases, record fields.

My understanding from the deep code review is we add back ticks for tool tips in these cases, so we should make this case consistent and then deal with alternative choices systematically
