### ISSUE TITLE
Impossible to show FSI help via command line

### ISSUE THREAD

**Issue by RonaldSchlenker** [dotnet/fsharp#13611]
Trying to get command line help for FSI seems impossible.

Invoking

```PS > dotnet fsi -?```
or
```PS > dotnet fsi -h```
or
```PS > dotnet fsi --help```

always results in the default prompt:

```
Description:

Usage:
  dotnet fsi [options]

Options:
  -?, -h, --help  Hiermit wird die Hilfe zur Befehlszeile angezeigt.
```

**Info:**

dotnet --version = 6.0.302
Windows 11

**Comment by vzarytovskii** [comment]
@baronfel do you know if that's something cli does not pass to fsi.dll?

**Comment by baronfel** [comment]
This came up recently and I've already fixed it for .net 7. I don't remember if it made it on time for preview 7, but it'll definitely be in rc1 in September at the latest.

**Comment by RonaldSchlenker** [comment]
Thank you @baronfel. I close this issue then.

**Comment by baronfel** [comment]
The linked issue for this was https://github.com/dotnet/fsharp/issues/13520
