### ISSUE TITLE
Disposable resources not carried correctly to task expression.

### ISSUE THREAD

**Issue by Thorium** [dotnet/fsharp#13670]
Disposable resources not carried correctly to task expression.

**Repro steps**

1. Create disposable thing outside a `task`
2. Try to use it in a `task`

**Expected behavior**

That the resource works, and `finally` would be run after a task, if the task captures the resource.

**Actual behavior**

The object is disposed already when you try to use it.

**Known workarounds**

Create a disposable within the task, then transfer it as parameter to an external function for processing. Urgh.

**Related information**

Tested with, but not restricted to:

* Operating system: Windows 11
* .NET Runtime kind (.NET Core, .NET Framework, Mono): Dotnet 6.0
* Editing Tools (e.g. Visual Studio Version, Visual Studio): VS2022

**More details and code samples**

If you try to transfer anything disposable inside a task, it will be disposed before task executes:

```fsharp
let writetofile filename obj =
   use file1 = System.IO.File.CreateText(filename)
   task {
       printfn "wait a sec"
       do! System.Threading.Tasks.Task.Delay 500
       file1.WriteLine("{0}", obj.ToString() )
       printfn "done"
       return "ok"
   }

let myTask = writetofile @"c:\temp\abc.txt" "Humpty Dumpty sat on a wall."
myTask.Wait()
let r = myTask.Result
printfn "%O" r

// System.AggregateException: 'One or more errors occurred. 
// (Cannot write to a closed TextWriter. ObjectDisposed_ObjectName_Name)'
```

Meanwhile if you create the file within the task, then it works well:

```fsharp
let writetofile filename obj =
   task {
       use file1 = System.IO.File.CreateText(filename) //this line was moved
       printfn "wait a sec"
       do! System.Threading.Tasks.Task.Delay 500
       file1.WriteLine("{0}", obj.ToString() )
       printfn "done"
       return "ok"
   }

let myTask = writetofile @"c:\temp\abc.txt" "Humpty Dumpty sat on a wall."
myTask.Wait()
let r = myTask.Result
printfn "%O" r
// ok
```

Why this is annoying is that current best-practice is to keep tasks small, to avoid other task-state-machine-issues.

**Comment by dsyme** [comment]
This is very much by-design - tasks are a form of closure and the same would hold true for other closures.

**Comment by Thorium** [comment]
Why is the expected behaviour a runtime error and not e.g. a compiler warning?

**Comment by En3Tho** [comment]
Runtime error is an implementation detail of internal _isDisposed check, it's not really general expected behaviour. There could be another object that could silently do nothing when disposed, for example. Compiler can't really figure those tiny details out. And from compiler standpoint you're not doing anything wrong.

You're using file, doing something with it and returning result. Warning might be nice but consider this one:
``` fsharp
use file1 = ...
let file2 = doSomethingWithFile file1 // same file is returned
task {
    .... file2 // boom 
}
```

I don't think compiler can figure this one out.
