### ISSUE TITLE
Tab completion in console fsi is not working since 17.4.0

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#13705]
Tab completion in command line/console fsi is not working since 17.4.0:

1. In developer command prompt run `dotnet fsi` or `fsi`
2. Type `Sys` and press tab

Expected: completes to `System`
Actual since 17.4.0: doesn't complete.

I took a look and the completion function invoked by `Tab` appears to be being set, so I'm not sure what's up. https://github.com/dotnet/fsharp/blob/da1e3e3dca549acfc361543551d1cb8f715f8258/src/fsi/fsimain.fs#L337

**Comment by 0101** [comment]
Works for me with current `main`. In Mac terminal and Rider.

**Comment by vzarytovskii** [comment]
Reproduces for me in the latest `fsi` in the VS2022 developer PS and CMD, works fine in a normal Terminal window.

**Comment by dsyme** [comment]
This is same as #13944
