### ISSUE TITLE
FSC 32-bit and throws OutOfMemoryException when compiling large project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#13713]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/FSC-32-bit-and-throws-OutOfMemoryExcepti/10058446)._

---
[severity:I'm unable to use this version]
Trying to compile a large F# project, it throws an OutOfMemoryException once the fsc.exe process hits ~1800 MB (according to Task Manager). I noticed that the fsc.exe process is also 32-bit, but it seems excessive to use >4gb memory when compiling this project with all optimizations disabled. It is certainly possible though, there are a lot of linked dlls.

This project is somewhat excessive because it contains a large amount of generated F# code. The `GeneratedTests` folder contains ~28 MB of generated F# code.

I was able to get this project to compile by setting the largeAddressAware flag on the fsc.exe but it seems like a hack.

Is there a way we can reorganize this project to avoid excessive memory usage, or do you have better recommendations besides the hack below?

```cmd
set "common=C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7"
call "%common%\Tools\VsDevCmd.bat"
editbin /largeaddressaware "%common%\IDE\devenv.exe"
editbin /largeaddressaware "%common%\IDE\CommonExtensions\Microsoft\FSharp\Tools\fsc.exe"
```

----

Output window when trying to build
```
10>------ Build started: Project: MyProject.GeneratedTests, Configuration: Debug - testing x64 ------
10>parameter error FS0193: error : Exception of type 'System.OutOfMemoryException' was thrown.
10>Done building project "MyProject.GeneratedTests.fsproj" -- FAILED.
10>
10>Build FAILED.
```

.fsproj file:
```xml
  
    false
    x64
  
  
    true
    false
    false
    DEBUG;TRACE;DEBUG_TESTING
    prompt
    4
  
```

Project structure:
```
- packages.config
- AssemblyInfo.fs
- Helper.fs
- SomeConstantTestFile.fs
GeneratedTests/
  - Generated_AAA_Tests.fs
  - Generated_AAB_Tests.fs
  - ... about 20 of these generated files in total
```

Example of generated test file:
```fsharp
open System
open NUnit.Framework

[]
type Generated_AAA_Tests() =
  inherit TestBase.Base(System.Reflection.Assembly.GetExecutingAssembly())

  []
  member __.``MyTestCase (Arg1, Arg2, Arg3)``() =
    // ~40 lines worth of test code

  // 30-100k lines worth of more test cases, all defined like the test case above
```

---
#### Feedback Bot on 6/1/2022, 04:19 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by dsyme** [comment]
Closing this out - the builds now use 64-bit tooling by default.
