### ISSUE TITLE
fsc.exe out of memory exception

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#13716]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/fscexe-out-of-memory-exception/10078047)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.8 was OK IIRC]
I run into OutOfMemoryException during a F# project compilation, the project has a sizeable amount of assembly references to it.

I am attaching a dotmemory profile, along with the response file that compiles the project.

[fscoutofmemory.7z](https://aka.ms/dc/file?name=B6ed3d1fddb594672ad38dd67a1b349fd637915085711480341_fscoutofmemory.7z&tid=6ed3d1fddb594672ad38dd67a1b349fd637915085711480341)

![image.png](https://aka.ms/dc/image?name=Be5a3b9081a6b44dfb980ce699e2006f2637915089758561661_20220622-083615-image.png&tid=e5a3b9081a6b44dfb980ce699e2006f2637915089758561661)

---
#### Feedback Bot on 6/23/2022, 08:04 AM: 

(private comment, text removed)
#### Gauthier Segay on 6/24/2022, 11:59 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by dsyme** [comment]
I think we should close this, as it is using 32-bit tooling.  In 17.x 64-bit tooling is the default.

If there is a repro with 64-bit tooling we can follow up with that
