### ISSUE TITLE
Unfinished let error if a line of string interpolation starts with a format instructions inside of a module

### ISSUE THREAD

**Issue by MangelMaxime** [dotnet/fsharp#13728]
Please provide a succinct description of the issue.

**Repro steps**

Provide the steps required to reproduce the problem:

```fs
module T =

    let evalute path =
        if true then
            let errors = ""

            let msg =
                $"""An error occured while loading {path}
Original error:
%s{errors}"""

            printfn "%s" msg
```

![image](https://user-images.githubusercontent.com/4760796/185414056-e98dfa4c-11ca-40f3-8789-73e2c34ce737.png)

If I add at least 3 spaces at the beginning of the line `%s{errors}"""` then the error goes away.

There is no error if the function is not under a module:

![image](https://user-images.githubusercontent.com/4760796/185414372-6e46ff1d-4255-4e5b-b6f0-49a85d0c911c.png)

**Expected behavior**

No error should be reported.

**Actual behavior**

The is a compilation error.

**Known workarounds**

Use string concatenation instead of string interpolation.

**Related information**

Provide any related information (optional):

* Operating system: Windows
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .NET Code 6.0.302
* Editing Tools (e.g. Visual Studio Version, Visual Studio) VSCode + Ionide

**Comment by vzarytovskii** [comment]
@MangelMaxime does this only show in VSCode, or VS too?
cc @baronfel

**Comment by MangelMaxime** [comment]
@vzarytovskii 

The error happens in Ionide, FSI, `dotnet build` too.

![image](https://user-images.githubusercontent.com/4760796/189419830-668c7049-ddeb-484f-93a6-5aa278f555ac.png)

The code I provided in the issue should serve as a reproduction I believe.

**Comment by dsyme** [comment]
This is a non-trivial bug in the lexfilter, when processing the tokens of multi-line interpolated strings - it is interpreting one of the tokens as being offside of the `let`.

**Comment by dsyme** [comment]
I assume the fix will be to push a new LexFilter context for the duration of the processing of the `let`.  However it's not going to be a simple fix.
