### ISSUE TITLE
comments with quotes

### ISSUE THREAD

**Issue by ray440** [dotnet/fsharp#13743]
Just an FYI: I would say this is a very low-priority bug.  
The following fails to compile:
```
    let comment_bug() =
(*
        let z = 42
        // a comment with "double-double-end quotes""  
*)
        let z = 34
        ()
```

**Comment by auduchinok** [comment]
Unfortunately, it seems to work per spec: the second quotes start another string and `*)` is considered a part of a string even inside a comment.

**Comment by ray440** [comment]
Right. Even this fails:
```
 let comment_bug() =
      (*
      let s = "foo
      *)
```
So the opening `(*` is ignored?  Or the quotes take precedence...?

**Comment by auduchinok** [comment]
Nope, it's not ignored. It's an unfinished string inside an unfinished comment.

**Comment by ray440** [comment]
> Nope, it's not ignored. It's an unfinished string inside an unfinished comment.

LOL! I guess that's the interpretation according to spec.  Indeed, a possible "fix" is to complete the string and comment.

```
    let comment_bug() =
        (*
        let s = "foo
        *)"
        *)
```

**Comment by dsyme** [comment]
As noted above this is per spec
