### ISSUE TITLE
[Tracking] Consider adding a "help wanted" label

### ISSUE THREAD

**Issue by mairaw** [dotnet/fsharp#13753]
Using the **help wanted** label is especially recognized by GitHub and we're trying to get a consistent experience for newcomers. See context at https://github.com/dotnet/runtime/issues/71496

I also noticed this project already exists in up-for-grabs.net but it has the wrong label configured since the up for grabs label doesn't exist in this repo. So ideally we can add the **help wanted** label and edit the following entry:
https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/_data/projects/visualfsharp.yml

/cc @danmoseley

**Comment by vzarytovskii** [comment]
I will add the label and relabel where necessary.

**Comment by vzarytovskii** [comment]
Done, added the label

**Comment by mairaw** [comment]
Thanks. I created a PR for the label update as well: https://github.com/up-for-grabs/up-for-grabs.net/pull/3332
