### ISSUE TITLE
Signature file generation does not handle arguments in attributes

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#13759]
When generating a signature file from a type with attributes with arguments, the generated code does not contain any arugments.

**Repro steps**

```fsharp
namespace MyApp.Types

open Newtonsoft.Json
    
type SomeTypeName =
    {
        /// Some Xml doc
        FieldOne : string
        [<JsonProperty(Required=Required.Default)>]
        FieldTwo : string list
        /// Some other Xml doc
        [<JsonProperty(Required=Required.Default)>]
        FieldThree : string
    }
```

leads to

```fsharp
namespace MyApp.Types
    
    type SomeTypeName =
        {
          
          /// Some Xml doc
          FieldOne: string
          [<Newtonsoft.Json.JsonProperty>]
          FieldTwo: string list
          
          /// Some other Xml doc
          [<Newtonsoft.Json.JsonProperty>]
          FieldThree: string
        }
```

**Expected behaviour**

The generated signature should be considered equivalent to the backing source file.

**Actual behaviour**

The generated code isn't valid, warning in implementation file:

![image](https://user-images.githubusercontent.com/2621499/186121390-c06c175a-de6e-4483-bcf3-fe2b4adbef0b.png)

**Known workarounds**

Edit signature file by hand.

**Comment by alfonsogarciacaro** [comment]
I'm seeing something similar in Fable, suddenly FCS doesn't expose the attributes of arguments of `FSharpMemberOrFunctionOrValue`. Note in my case it's an implementation file and the typed AST.
