### ISSUE TITLE
Signature file generation does not handle types from a shared namespace

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#13761]
When generating a signature file from a type annotation with a type from a shared namespace, the generated code requires an additional inclusion of the shared namespace.

**Repro steps**

```fsharp
namespace Foo.Types

type Area = | Area of string * int

namespace Foo.Other

type Map<'t,'v> =
    member this.Calculate : Foo.Types.Area = failwith "todo"
```

leads to

```fsharp
namespace Foo.Types
    
    type Area = | Area of string * int
namespace Foo.Other
    
    [<Class>]
    type Map<'t,'v> =
        
        member Calculate: Types.Area
```

**Expected behaviour**

The generated signature should be considered equivalent to the backing source file.

**Actual behaviour**

The generated code isn't valid:

![image](https://user-images.githubusercontent.com/2621499/186126357-3d3e4d51-8b8b-434e-936a-919b78d3c505.png)

**Known workarounds**

Edit signature file by hand.

**Comment by KevinRansom** [comment]
@nojaf ... nice, you have found a bug farm :-)

**Comment by nojaf** [comment]
Yes, this is quite the lesser-used functionality 😸
