### ISSUE TITLE
Add optional width parameter for FSharpCheckFileResults.GetToolTip

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#13772]
**Is your feature request related to a problem? Please describe.**

When the IDE gets a tooltip via [FSharpCheckFileResults.GetToolTip](https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-codeanalysis-fsharpcheckfileresults.html#GetToolTip), it will eventually print a layout from NicePrint.

**Describe the solution you'd like**

https://github.com/dotnet/fsharp/blob/bdb64624f0ca220ca4433c83d02dd5822fe767a5/src/Compiler/Service/ServiceDeclarationLists.fs#L150-L183

To a certain degree, it is possible to control the width of a layout before it gets transformed into a tooltip.
Using `Display.squashTo 80` after `NicePrint.layoutType denv unionTy` for example.

I'd like to be able to pass in an option width that when present squashes the layout to get a better tooltip view.

**Describe alternatives you've considered**

I'm not really sure what the alternatives could be here.

**Comment by dsyme** [comment]
@nojaf Agreed this is reasonable to do
