### ISSUE TITLE
F# compilation for linux-arm (Raspberry Pi) results in System.BadImageFormatException.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#13805]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F-compilation-for-linux-arm-Raspberry-/10126267)._

---
[severity:I'm unable to use this version] [regression] [worked-in:VS 17.3.0]
Create new F# Console app in VS (Windows/Mac).
Compile targeting linux-arm, self-contained=true.
Run on a Raspberry Pi.

Result:
Unhandled exception. System.BadImageFormatException: Could not load file or assembly '/home/pi/Test.dll'. An attempt was made to load a program with an incorrect format.

File name: '/home/pi/Test.dll'
Aborted

This occurs after updating Visual Studio on both Windows and Mac to 17.3.1.
I tried using VS 17.3.0 which I haven't updated yet on my laptop, and it ran fine on a Raspberry Pi.

---
#### Feedback Bot on 8/22/2022, 08:04 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by KevinRansom** [comment]
Hmm ... did I break 32 bit arm builds. I will take a look.

**Comment by Quetzalcoatl2435** [comment]
Thanks for taking a look at this. Just wanted to add it's still broken on 17.3.2 for linux-arm. It does work for win-x86/x64 and osx-x64, though.

I currently don't have a linux-arm64 device on hand, but one should be coming in the next week or so. I'll update this when I get a chance to test it on that device.

**Comment by forki** [comment]
this is still broken in 6.0.401 - I assume the fix did not ship with that boat.

**Comment by vzarytovskii** [comment]
> this is still broken in 6.0.401 - I assume the fix did not ship with that boat.

No, fix was not ported to 6.x.x branch.

**Comment by forki** [comment]
well shit. It's rather important for us to run stuff on Raspberry Pis

**Comment by vzarytovskii** [comment]
> well shit. It's rather important for us to run stuff on Raspberry Pis

We'll see what we can do

**Comment by Quetzalcoatl2435** [comment]
> well shit. It's rather important for us to run stuff on Raspberry Pis

Same. I really need it for work where all nodes are run on Raspberry Pis. I have to compile everything on my laptop which is still on 17.3.0, so I have a fallback, but an ETA would be nice. :)

**Comment by Quetzalcoatl2435** [comment]
> > well shit. It's rather important for us to run stuff on Raspberry Pis
> 
> We'll see what we can do

Thank you!

**Comment by forki** [comment]
@vzarytovskii what about 6.0.402?

**Comment by vzarytovskii** [comment]
> @vzarytovskii what about 6.0.402?

I will need to check it after I'm back next Wednesday. If it didn't end up in 402, we'll get it in to the next one

**Comment by vzarytovskii** [comment]
> Ok since you didn't say "no" - I actually gave it a try and seems to work again.
> 
> Thanks a lot!!!

Thanks for testing it! Sorry for the inconvenience with the bug.

**Comment by Quetzalcoatl2435** [comment]
Updated VS and it didn't work for me. Still getting the same error.
Had to revert back to 304 for raspberry pis.

**Comment by vzarytovskii** [comment]
> Updated VS and it didn't work for me. Still getting the same error.
> Had to revert back to 304 for raspberry pis.

For VS - fix should be in the recent 17.4

**Comment by Quetzalcoatl2435** [comment]
> > Updated VS and it didn't work for me. Still getting the same error.
> > Had to revert back to 304 for raspberry pis.
> 
> For VS - fix should be in the recent 17.4

Ah, OK. I tried compiling from the command line and it does work. Thanks. :)
