### ISSUE TITLE
Struct `SynType.Tuple` has invalid range

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#13831]
Consider `struct` tuple type annotation:
```fsharp
let _: struct (int * int) = ()
```
After #13440 the type range doesn't include `struct (` and `)` anymore ([ast](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQ2wAuYA%2BtjQ8ATgFdmfABQo%2BAKjCyAlGAC8YKUsggAvkA)), despite they are parsed as part of the corresponding rules:
https://github.com/dotnet/fsharp/blob/bdb64624f0ca220ca4433c83d02dd5822fe767a5/src/Compiler/pars.fsy#L5284-L5287
https://github.com/dotnet/fsharp/blob/bdb64624f0ca220ca4433c83d02dd5822fe767a5/src/Compiler/pars.fsy#L5289-L5293

cc @edgarfgp @nojaf

**Comment by nojaf** [comment]
@auduchinok good catch, let me take a look at that next week.

**Comment by auduchinok** [comment]
I'm glad we have lots of tests for these things 😅
