### ISSUE TITLE
`SynType.Tuple` doesn't include leading parameter names and attributes in signatures

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#13848]
```fsharp
type T =
    member M: p1: a * p2: b -> int
```

[Ast](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmAC4BOArrPhJAMYD2cFklAngA6xgAKmAC8AHWQQIAW1jSARrGpgAstl4BGbAEMwAKjDywAWgB8YFJQmQQAXyA). It seems previously names and attributes were included, as we used the tuple type `range` field to find where parameter signature starts.

cc @nojaf

**Comment by nojaf** [comment]
Being devil's advocate here, if the type is not in a tuple it also isn't included in the `SynType` range.

[Example](https://fsprojects.github.io/fantomas-tools/#/trivia?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAKmALwA6AdhBALaJUBGiATmALJpjYAMaAzuowEsyAczAAbAXzABaAHwcAjGgCGYAFRg6M%2BUPTlIAGnBQkAMyGIeqKIeORJAMR4Dr-AK6IQAXyA)

`SynType.App` doesn't contains `p0`.

Aren't we missing a better representation in `SynType` in the case a name is present?
Would this also not simplify a lot of things?
I'm guessing you also need to piece together the `SynValInfo` with the correct `SynType` to get the information you are really after.

Looking at [implementation](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQAuAngA6wwAFTABeADrIIEKgCM0XAE5VmXMAFtY62bEVgAstjB8ADNgWKUAczA0iagLQA%2BYwEZsVMACowssM7AULkkQ5F4BMABVMUlpQLDdamZBEQB3RC4AC1i46U1tXQMwAApTcyVrW3sAShK%2BdzAqXGMAJlrRMBNIEABfIA), it uses `SynPat.Typed` to cover this case.
Could we also not have a counterpart for `SynType`?

//cc @dsyme

**Comment by nojaf** [comment]
Proposal:

Fixing the bug first as is.
And in a future PR I'd like to have something like:

```
type SynType =
    ...
    | Named of attributes: SynAttributes * qmark: range option * id: SynIdent * usedType: SynType * range: range
```

to represent `a: t`
