### ISSUE TITLE
`SynLongIdent.IdentsWithTrivia` throws exceptions

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#13842]
```fsharp
module Module

A.
```

[Ast](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQC27ArjbDABZPgIA6yCQEEAdJBABfIA). Trying to get the idents with trivia leads to the following exception:
```
Message = “difference between idents and trivia”

StackTraceString = “
  at FSharp.Compiler.Syntax.SynLongIdent.get_IdentsWithTrivia()
    in C:\Developer\fsharp-rebase\src\Compiler\SyntaxTree\SyntaxTree.fs:line 51
 at JetBrains.ReSharper.Plugins.FSharp.Psi.LanguageService.Parsing.FSharpExpressionTreeBuilder.ProcessLongIdentifierExpression(SynLongIdent lidWithDots, Range range)
    in C:\Developer\resharper-fsharp\ReSharper.FSharp\src\FSharp.Psi.Features\src\Parsing\FSharpImplTreeBuilder.fs:line 1188
```

I can make a workaround, but it's suspicious that the trivia is missing (i.e. empty list instead of `[None]`), and it should't probably throw instead of return `None` in this case.

cc @nojaf

**Comment by nojaf** [comment]
Any idea in the grammar where it is creating `A.`?
I feel like the problem is more over there that it created ident A without adding the trivia.

> and it should't probably throw instead of return None in this case.

Debatable, I don't have any strong sentiment about that part.

**Comment by auduchinok** [comment]
> Any idea in the grammar where it is creating A.?

It looks like it could be this:
https://github.com/dotnet/fsharp/blob/bdb64624f0ca220ca4433c83d02dd5822fe767a5/src/Compiler/SyntaxTree/SyntaxTreeOps.fs#L466-L471

> Debatable, I don't have any strong sentiment about that part.

With this exception this API is just too dangerous to use, as it throws on unfinished code during normal typing (I had to remove all its usages for now). Adding `None` for missing trivia items would make it much safer.

**Comment by dsyme** [comment]
@vzarytovskii Sorry was it incorrect to merge to main at the moment?
