### ISSUE TITLE
XmlDoc required for unnamed union case field

### ISSUE THREAD

**Issue by DedSec256** [dotnet/fsharp#13861]
**Repro**

```fsharp
type A =
    /// <summary>
    ///
    /// </summary>
    /// <param name="x"></param>
    | Case of int * x: int
```

![image](https://user-images.githubusercontent.com/26364714/189180256-113ca372-19a2-4273-8b2c-bd9da4e57f9e.png)

**Expected behavior**

XmlDoc is not required for the parameter

**Comment by auduchinok** [comment]
This is inconsistent to other places where anonymous top-level parameters can be declared, like parameters in functions and methods, where unnamed patterns are ignored by this check.

@dsyme @vzarytovskii Would you accept a PR making the union cases behave in line with other places?

@DedSec256 Would you like to make a PR with the change? If yes, `IsNameGenerated` from https://github.com/dotnet/fsharp/pull/4225 could be useful help here. Could you also check if there're other similar cases, e.g. unnamed parameters in exception declarations, needing an update too?

**Comment by dsyme** [comment]
Aside: the whole question of XML docs for union cases is a signficant piece of the F# documentation puzzle that hasn't been properly addressed.  The underlying problem - like a lot of corner cases in F# - is that XML docs are a .NET standard w.r.t. the compiled representation - so what does an XML doc on a union case even refer to?

For the above case - I think the warning is actually reasonable - if some of the union cases are named and documented, all of them should be.  I'd probably say the same about parameters.

But yes, for consistency we'd accept a PR for this.

**Comment by DedSec256** [comment]
Curiously, we have yet another way to specify documentation for a union case field

https://github.com/dotnet/fsharp/blob/03714a0dd69dc810445a94856afbdc11d2d6b7cd/tests/service/XmlDocTests.fs#L1170-L1184
