### ISSUE TITLE
Running FSI prints "module FSI_001" before anything else

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#13869]
Running FSI prints "module FSI_001" before anything else

This looks like a regression:

```fsharp
C:\GitHub\dsyme\fsharp>dotnet artifacts\bin\fsi\Debug\net7.0\fsi.dll

Microsoft (R) F# Interactive version 12.0.5.0 for F# 7.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> module FSI_0001
```

**Comment by dsyme** [comment]
@nojaf This may be related to your changes in module printing.

**Comment by nojaf** [comment]
This could very well be related, I'll take a look at this next week.
One question though, if this is an empty module, why is `dotnet fsi` printing it immediately to the screen? That feels like it is evaluating something before the user even entered anything.

**Comment by dsyme** [comment]
> That feels like it is evaluating something before the user even entered anything.

Yes, it evaluates a dummy, empty module to "JIT all the main code" so it's ready to compile and run user code faster.

**Comment by nojaf** [comment]
An empty anonymous module will match the `|EmptyModuleOrNamespaces|_|` active pattern.
Is there any way to detect that the module had a generated name instead of when it had a named module?
Something in `TypedTree.Entity` perhaps?

**Comment by dsyme** [comment]
Given this is a regression and we need a fix in, I guess just filtering on FsiDynamicModulePrefix is ok for now.
