### ISSUE TITLE
`dotnet fsi --help` is not helpful, can't get the list of compiler flags from command line.

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#13871]
I'd expect `dotnet fsi --help` to give the list of compiler flags that FSI understands, or maybe a link to https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/compiler-options#compiler-options-listed-alphabetically

For example, it is possible to use `dotnet fsi /warnon:1182` but I have to "discover" it, because the help output is:

```
Description:

Usage:
  dotnet fsi [options]

Options:
  -?, -h, --help  Show command line help.
```

Similarly, it would make sense to be able to invoke the compiler to obtain the actual help (online documentation may not be accurate), maybe through `dotnet fsc --help`
, but the compiler is not invokable this way, there are no clear ways to invoke the compiler out of the dotnet sdk.

**Comment by baronfel** [comment]
We should have fixed this in https://github.com/dotnet/fsharp/issues/13520, and I just tested on nightly builds for 7.0.100 rc2. So I think we should close this issue.
