### ISSUE TITLE
C# to F# go to definition navigates to metadata, and not the source code

### ISSUE THREAD

**Issue by oleksandr-bilyk** [dotnet/fsharp#13882]
Every year we have to buy Rider because Rider allows to navigate from C# code to F# method definition. 
We had big expectations that VS2022 will support such a basic feature but not.
Our team decided to use F# in solution where we have many C# and F# projects calling each other. 
This small feature is very important for future use of F# in our solutions.

**Comment by vzarytovskii** [comment]
@tmat do you have any insights on how should we approach it?

**Comment by smoothdeveloper** [comment]
@oleksandr-bilyk please consider appending your experience in this discussion: https://github.com/dotnet/csharplang/discussions/6412#discussioncomment-3536860

it is about "C#-adjacent tooling experience" from C# Language Design Meeting notes discussions.

The reverse navigation works (Go To Definition on C# member from F# code reaches), which I think came at some point in VS 2019.

**Comment by tmat** [comment]
@CyrusNajmabadi IIRC LSP should be able to handle this, correct?

**Comment by vzarytovskii** [comment]
https://github.com/dotnet/roslyn/pull/64010 is in, will experiment with it next week

**Comment by kerams** [comment]
> The reverse navigation works (Go To Definition on C# member from F# code reaches),

You said that, but it stopped working for me with yesterday's VS preview update :).

**Comment by vzarytovskii** [comment]
> > The reverse navigation works (Go To Definition on C# member from F# code reaches),
> 
> You say that, but it stopped working for me with yesterday's VS preview update :).

Works for me:
![image](https://user-images.githubusercontent.com/1260985/190377140-cb6d6801-e141-483e-8d54-9dd3b2b378c9.png)
![image](https://user-images.githubusercontent.com/1260985/190377177-83bdc45c-16f5-4d00-a033-1fd315ac2c68.png)

**Comment by kerams** [comment]
![image](https://user-images.githubusercontent.com/5063478/190377387-09c72c71-b4bb-43f9-839a-653d4702b843.png)

BCL metadata navigation. I'm pressing F12 on this to no avail (it used to work). Perhaps it's a different use case.

**Comment by vzarytovskii** [comment]
> ![image](https://user-images.githubusercontent.com/5063478/190377387-09c72c71-b4bb-43f9-839a-653d4702b843.png)
> 
> BCL/external dependency metadata navigation. I'm pressing F12 on this to no avail (it used to work). Perhaps it's a different use case.

Yep, doesn't work for me for `Newtonsoft.Json`.

**Comment by vzarytovskii** [comment]
I hopefully can fix it in one batch with C#->F# navigation.

**Comment by smoothdeveloper** [comment]
@kerams / @vzarytovskii I noticed in some F# editor "go to definition" use cases, it will generate F# signature (of C# code).

IMO, generating F# signatures is relevant, only if those cases don't resolve:
* project reference, with the source file
* assembly reference with pdb pointing to source file
* sourcelink

AND if, the assembly referenced is compiled with F#.

If it is not the case, it is probably better to do what the C# editor would do.

@vzarytovskii and @CyrusNajmabadi, thanks for giving a shot at the C# -> F# code navigation, this is going to help a lot.

**Comment by vzarytovskii** [comment]
> IMO, generating F# signatures is relevant, only if those cases don't resolve:
 
> * project reference, with the source file

I think, if we know that we have source, we will navigate to it.
 
> * assembly reference with pdb pointing to source file
> * sourcelink

Not sure about these. Will try to remember and look at it. When I navigate to "WriteLine" source code now, it brings me to the source (not sure whether via sourcelink ok pdbs).

**Comment by dsyme** [comment]
@vzarytovskii I removed the VS label - trying to keep to one most-specific Area label per issue, unless it really is across multiple areas

**Comment by dsyme** [comment]
Closing https://github.com/dotnet/fsharp/issues/3497 as a duplicate of this more recent one.  There is interesting information there on prototype attempts to address this

**Comment by vzarytovskii** [comment]
Note: new API with assembly name included: https://github.com/dotnet/roslyn/pull/64475
Will make changes once back next week.
