### ISSUE TITLE
Investigate the options of migrating to some library for parsing cmd line args

### ISSUE THREAD

**Issue by psfinaki** [dotnet/fsharp#13880]
The original [parser](https://github.com/dotnet/fsharp/blob/main/src/Compiler/Driver/CompilerOptions.fs#L259) was written long time ago, since then a bunch of libraries for arg parsing popped up, we can try switching to some.

Some libs I know of: [Argu](https://github.com/fsprojects/Argu), [CommandLineParser](https://github.com/commandlineparser/commandline).

**Comment by baronfel** [comment]
If at all possible I'd advocate for System.CommandLine - we're trying to standardize on it across the board. It powers the dotnet CLI and has a broad range of functionality, including support for tab-completions and trimmability built-in

**Comment by psfinaki** [comment]
No objections from my side - haven't used it but definitely heard some good words about it. 
The only argument for Argu would be that it's F# native and I think @dsyme was contributing to that so might have extra insight.

**Comment by vzarytovskii** [comment]
If anything, I'd vote for **not** using anything 3rd-party. System.CommandLine sounds OK to me.

**Comment by dsyme** [comment]
I think we should not do this.  What is there works, is stable, and whatever else we use will have some weird compat problems. Plus the Fable version of the F# compiler would need an implementation of that library.

In general this last point means there is a structural advantage in fully F#-implemented functionality internalized in the compiler.  We can't always do that - and reusing other libraries is good sometimes - but it's a factor to take into account.

**Comment by dsyme** [comment]
I'll close, as I think in balance we shouldn't do it, for reasons described above.
