### ISSUE TITLE
type resolution in script file doesn't work for type provider without qualified names

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#13887]
**Repro steps**
Setting "Use .NET Core Scripting" to False:

![image](https://user-images.githubusercontent.com/87944/189715105-a9d6088a-6f08-4c96-a652-037c6c02e5ec.png)

I'm facing situation with a script such as:

```fsharp
#r "nuget: FSharp.Data"
open FSharp.Data
type J = JsonProvider< """{ "a":"b", "c": 1}""">
type JQualified = FSharp.Data.JsonProvider< """{ "a":"b", "c": 1}""">
```

the first `JsonProvider` shows squiggles
> FS00039: The type `JsonProvider` is not defined.

It doesn't happen with "Use .NET Core Scripting" to True.

It doesn't affect fsianycpu.exe evaluation but just the tooling.

**Actual behavior**

the first `JsonProvider` shows squiggles
> FS00039: The type `JsonProvider` is not defined.

![image](https://user-images.githubusercontent.com/87944/189730089-12c93c9b-1ffb-4608-8af2-303117794cac.png)

**Expected behavior**

It should work disregarding the setting.

**Known workarounds**

Using qualified names, which is a bit problematic.

**Related information**

* Windows 11 Pro 22H2 22622.590
* VS 2022 17.2.6

**Comment by dsyme** [comment]
To use FSharp.Data with .NET 4.7.2 you must reference `System.Xml.Linq` in scripts:

```
#r "nuget: FSharp.Data, 5.0.2"
#r "System.Xml.Linq"
open FSharp.Data
type J = JsonProvider< """{ "a":"b", "c": 1}""">
type JQualified = FSharp.Data.JsonProvider< """{ "a":"b", "c": 1}""">
```

**Comment by smoothdeveloper** [comment]
Thanks @dsyme, there is still an issue, IMO:

* if System.Xml.Linq was required, the qualified instantiation should also fail
* user can't figure there would be a dependency missing
* it only impacts the tooling, fsianycpu is 100% fine without the extra reference

What can be done to improve the situation? I feel the squiggle should actually surface the missing dependency, if that's the actual issue.
