### ISSUE TITLE
Expose parallel typechecking option in VS options

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#13909]
Once https://github.com/dotnet/fsharp/pull/13737 is merged, we need to expose an option in VS which will be enabling it internally.

**Comment by K780420** [comment]
![image](https://user-images.githubusercontent.com/97131332/190510683-1c4bc002-b1d8-49e0-9f40-a4b91221b5f9.jpeg)

**Comment by K780420** [comment]
![image](https://user-images.githubusercontent.com/97131332/190511209-cf01b02a-99c0-440b-a913-2a7cf392e93e.jpeg)

**Comment by K780420** [comment]
![image](https://user-images.githubusercontent.com/97131332/190511837-7ab3a830-6939-429d-87a0-45550684fc83.jpeg)
