### ISSUE TITLE
Go to definition on external dependency/metadata is broken in 17.4

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#13906]
> ![image](https://user-images.githubusercontent.com/5063478/190377387-09c72c71-b4bb-43f9-839a-653d4702b843.png)
> 
> BCL/external dependency metadata navigation. I'm pressing F12 on this to no avail (it used to work). Perhaps it's a different use case.

Yep, doesn't work for me for `Newtonsoft.Json`.

_Originally posted by @vzarytovskii in https://github.com/dotnet/fsharp/issues/13882#issuecomment-1247893240_

**Comment by K780420** [comment]
![image](https://user-images.githubusercontent.com/97131332/190510865-c48a99cf-4e76-4531-98a8-99752b122b29.jpeg)

**Comment by vzarytovskii** [comment]
https://github.com/dotnet/fsharp/pull/13943 will be an intermediate fix, proper fix would be to use MetadataAsSource (https://github.com/dotnet/fsharp/issues/13951)
