### ISSUE TITLE
Ctrl+D / Ctrl+L do not work in fsi repl

### ISSUE THREAD

**Issue by abonie** [dotnet/fsharp#13944]
Ctrl+D and Ctrl+L do not work in `dotnet fsi` repl

**Repro steps**

Press Ctrl+D or Ctrl+L in an interactive session of `dotnet fsi`

**Expected behavior**

Standard cli behavior:
Ctrl+D if pressed at the beginning of a line will exit the program
Ctrl+L will clear the screen

**Actual behavior**

An EOT (^D) or Form Feed (^L) character is typed

```
 dotnet fsi

Microsoft (R) F# Interactive version 12.0.5.0 for F# 7.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> ^D^L
```

**Known workarounds**

Use `#quit` (or `exit`) and `#clear`

**Related information**

Provide any related information (optional):

* Operating system: Windows 11
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .NET Core, SDK version 7.0.100-rc.1.22431.12
* Works as expected on .NET Core, SDK version 7.0.100-preview.7.22377.5

**Comment by dsyme** [comment]
Would be good to get to the bottom of this - I looked at src/fsi/console.fs but couldn't see anything obvious. Technique should be a binary chop on commits in `main` and running

    artifacts\bin\fsi\Debug\net6.0\fsi.exe

or

    artifacts\bin\fsi\Debug\net7.0\fsi.exe


Here's what I've done so far:

```
aebdd2871e113f47aae537e138ecec97dfecbb7a - yes
2bfb60540c6def7f76ca2fcef8a48dfdc843eeac - testing
80858f017d7121a4d3f6c1228cc05b063dfe8082 - no
```

**Comment by dsyme** [comment]
Problem is here: https://github.com/dotnet/fsharp/pull/13531/files#r976515699
