### ISSUE TITLE
Instance extension methods block legitimate unqualified name resolutions

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#13965]
From @NiklasGustafsson in TorchSharp repo

If a C# type has both a nested type C.Name and there is an instance extension method called Name then the latter is always preferred, even for static unqualified resolution

Repro is something like this:

```csharp

class C {
    class Name { 
        static public void Method() ... 
    }
}

class Extensions {
    static public T Name(T this) { ... }
}

C.Name.Method()
```

Here the extension method is an instance extension method but is being used as a resolution for a static invocation.  It's being used only to report a later error - and instead we should filter on static v. instance in name resolution.

**Comment by NiklasGustafsson** [comment]
One minor detail about the repro -- all the classes in the example are `static` classes in the original problem. May not matter for the repro, but I thought it worth mentioning.

**Comment by dsyme** [comment]
Zip of repro [ClassLibrary2.zip](https://github.com/dotnet/fsharp/files/9635678/ClassLibrary2.zip)

**Comment by dsyme** [comment]
C#: 
```csharp
using System.Runtime.CompilerServices;
    
namespace ClassLibrary2
{
    public static class Extensions
    {
        static public T cuda<T>(this T x) { return x; }
    }

    public class torch
    {
        public class cuda
        {
            public static bool isAvailable() { return true; }
        }
    }
}
```

F#:
```fsharp

open ClassLibrary2

torch.cuda.isAvailable()
```
