### ISSUE TITLE
Text disabled by conditional compilation in F # with dark theme is too visible.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#13984]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Text-disabled-by-conditional-compilation/10155343)._

---
The text that does not satisfy a conditional compilation rule, although not colored, strikes the eye too much and should be less visible, more transparent and possibly there should be the possibility of being able to set it in italic.

![image](https://user-images.githubusercontent.com/1260985/192300040-bc316d22-a5da-4139-86b8-6fa04ae7d616.png)

---
#### Feedback Bot on 9/23/2022, 03:56 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by 0101** [comment]
This looks like a non-standard color scheme. Might be an issue in that.
