### ISSUE TITLE
Indentation aware raw string literals (similar to C# 11)

### ISSUE THREAD

**Issue by stefan-schweiger** [dotnet/fsharp#13995]
**Is your feature request related to a problem? Please describe.**

Currently you have to be careful about the indentation of multiline strings in your code

```fsharp
let htmlString1 = """<!DOCTYPE html>
<html lang="en">
    <head>
    </head>
    <body>
        <h1>Hello</h1>
     </body>
</html>"""

let htmlString2 = """
    <!DOCTYPE html>
    <html lang="en">
        <head>
        </head>
        <body>
            <h1>Hello</h1>
         </body>
    </html>
    """

printfn $"%b{htmlString1 = htmlString2}" // -> false
```

**Describe the solution you'd like**

With [C# 11 raw string literals](https://learn.microsoft.com/en-gb/dotnet/csharp/whats-new/csharp-11#raw-string-literals) were introduced which remove indentation depending of the position of the closing `"""` and ignores leading and trailing new lines.

E.g.

```csharp
var htmlString1 = """
    <!DOCTYPE html>
    <html lang="en">
        <head>
        </head>
        <body>
            <h1>Hello</h1>
         </body>
    </html>
    """;

var htmlString1 = """
<!DOCTYPE html>
<html lang="en">
    <head>
    </head>
    <body>
        <h1>Hello</h1>
     </body>
</html>
""";

Console.WriteLine(htmlString1 == htmlString2); // -> true
```

F# should support this as well, maybe prefixed with `@`:

```fsharp
let htmlString1 = @"""<!DOCTYPE html>
<html lang="en">
    <head>
    </head>
    <body>
        <h1>Hello</h1>
     </body>
</html>"""

let htmlString2 = @"""
    <!DOCTYPE html>
    <html lang="en">
        <head>
        </head>
        <body>
            <h1>Hello</h1>
         </body>
    </html>
    """

printfn $"%b{htmlString1 = htmlString2}" // -> true
```

**Describe alternatives you've considered**

You can create a function which looks at the number of whitespaces on the last line and removes the same number of leading whitespaces from all other lines. But it's very easy to use wrong (for example on strings which where not written as multiline in your code, but just contain "\n") and you won't get any compiler errors/warnings if your lines misalign.

**Comment by vzarytovskii** [comment]
@stefan-schweiger I think it is covered by https://github.com/fsharp/fslang-suggestions/issues/1150
Does it match what you want? If no, please create another proposal in the https://github.com/fsharp/fslang-suggestions/issues
