### ISSUE TITLE
Trim signature and optimization data from runtime dependencies which we publish to SDK/VS

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#13990]
We have the following runtime dependencies which we ship together with compiler in the SDK, for which we can safely strip signature and optimization data (unless I'm missing something):

- FSharp.Build.dll (210Kb):
    - FSharpOptimizationData: 1Kb
    - FSharpSignatureData: 53Kb
- FSharp.Compiler.Interactive.Settings.dll (75Kb):
    - FSharpOptimizationData: 2Kb
    - FSharpSignatureData: 15Kb
- FSharp.Compiler.Service.dll (34,403Kb):
    - FSharpOptimizationData: 115Kb
    - FSharpSignatureData: 2,347Kb
- FSharp.Core.dll (5,287Kb) (this one is compressed):
    - FSharpOptimizationData: 616Kb
    - FSharpSignatureData: 665Kb
- FSharp.DependencyManager.Nuget.dll (255Kb):
    - FSharpOptimizationData: 1Kb
    - FSharpSignatureData: 21Kb

Which sums up to 3836Kb, so we can potentially save up to 3Mb, which is not bad for SDK.

**Comment by 0101** [comment]
We should probably keep these in FSharp.Core, just compress them.

**Comment by KevinRansom** [comment]
I think we are now good with where we are on this.
