### ISSUE TITLE
Regression: Scripts are being edited as .NET Framework, not .NET Core 

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#13993]
In latest public preview and latest main, when opening and editing a script .NET Framework references are being used, not .NET Core references

Script: 

```fsharp
#r "nuget: FSharp.Data, 3.3.3"
```

With 17.3.3:

![image](https://user-images.githubusercontent.com/7204669/192541421-06347cf1-8065-4c38-a034-d11805adac78.png)
 
With 17.4.0 Preview 2.1 and latest main:

![image](https://user-images.githubusercontent.com/7204669/192541828-4be1794a-b237-4b2e-a1cb-1b99e69c0058.png)

Settings:

![image](https://user-images.githubusercontent.com/7204669/192541197-2fed00ee-b7ba-404c-948a-9d209ab672fa.png)

**Comment by dsyme** [comment]
@KevinRansom Regression is here: https://github.com/dotnet/fsharp/commit/dc269a93179963f5c6874eb34dc14b52229349c5#r85153150

The problem is that when this code is running in devenv.exe (running TFM = net48), the target TFM must be based on the .NET Core sdkDir for the script.

**Comment by T-Gro** [comment]
(likely have been fixed? @KevinRansom )
