### ISSUE TITLE
Bad image when calling op_Addition on interface

### ISSUE THREAD

**Issue by gusty** [dotnet/fsharp#14012]
Calling `op_Addition` on interface results in a Bad Image error.

**Repro steps**

1. `open System.Numerics;;`

2. `IAdditionOperators.op_Addition (3, 6) ;;`

**Expected behavior**

Compiles with `val it: int = 9`

**Actual behavior**

Fails compilation with:

```
> IAdditionOperators.op_Addition (3, 6) ;;
System.BadImageFormatException: Bad IL format.
   at <StartupCode$FSI_0012>.$FSI_0012.main@()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Stopped due to error
```

**Known workarounds**

Don't call directly on the interface.

**Related information**

Other operations, like `op_CheckedAddition` work fine:

```
> IAdditionOperators.op_CheckedAddition (3, 6) ;;
val it: int = 9
```

Test on:

Microsoft (R) F# Interactive version 12.0.5.0 for F# 7.0

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.4.0 Preview 2.1

**Comment by vzarytovskii** [comment]
Checked version is `virtual` member, and normal is abstract. I think it should be disallowed in general - calling methods directly on the interfaces, wdyt @dsyme?

**Comment by vzarytovskii** [comment]
> @vzarytovskii Curious, does C# allow this?  I presume not?  I assume we must be missing a check to disallow this?

Nope, it doesn't for operators. It may for normal static methods with default implementation

**Comment by vzarytovskii** [comment]
Just for historical reasons, this is why it's crashing (abstract vs virtual): 
https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Numerics/IAdditionOperators.cs,5b77e6b404819054

Check will be introduced to ensure we generate call on virtual members.
