### ISSUE TITLE
compiler can't infer type which is correctly infered in IDE

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#1402]
Type inference in IDE shows different picture than what compiler sees.
#### Repro steps

create a .fsx and open it in Visual Studio:

``` fsharp
#r "System.Threading.Tasks"
#r "System.Threading.Tasks.DataFlow"
open System.Data
open System.Threading.Tasks.Dataflow

let makeProcessor () =
  let input = BroadcastBlock<_>(fun i -> i)
  let streamTables = TransformManyBlock<_,_>(fun message ->
    seq {
      yield (new DataTable())
    }
  )
  // IDE shows 'processing : ActionBlock<DataTable>'
  let processing = ActionBlock<_>(fun message ->
    // Lookup on object of indeterminate type based on information prior to this program point. 
    // A type annotation may be needed prior to this program point to constrain the type of the object. 
    // This may allow the lookup to be resolved. 
    message.Clear() 
  )

  input.LinkTo streamTables |> ignore
  streamTables.LinkTo processing |> ignore
  input.Post
```
#### Expected behavior

no shown error
#### Actual behavior

The line with `message.Clear()` shows:

> error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
#### Known workarounds

Provide type annotation
#### Related information
- Windows 7 Pro 64 bit
- F# 4.0
- VS 2015

**Comment by dsyme** [comment]
This is known behavior and the compiler behavior is according to specification.  The IDE could perhaps give a better error message. 

IDE type inference shows the results after applying all constraints in the file, where member resolution has only applied those up to the point of use.  The error message says what to do, but it's not clear in the tooltips that the type being displayed may have been inferred from later constraints
