### ISSUE TITLE
FSI netcore not seeing System.Security.Cryptography asm

### ISSUE THREAD

**Issue by kevmal** [dotnet/fsharp#14024]
In VS Version 17.4.0 Preview 2.1 editing a fsx file with "Use .NET Core Scripting" enabled:

![image](https://user-images.githubusercontent.com/7281367/194035014-8ee8883f-f73a-4993-97fb-bba670c90f4e.png)

Not showing any types from System.Security.Cryptography asm, (`Aes`, `AesCcm`, `AesCng`, ...)

In FSI (F# Interactive version 12.0.5.0 for F# 7.0):

```
$ dotnet fsi

Microsoft (R) F# Interactive version 12.0.5.0 for F# 7.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> System.Security.Cryptography.MD5.Create();;

  System.Security.Cryptography.MD5.Create();;
  -----------------------------^^^

stdin(12,30): error FS0039: The value, constructor, namespace or type 'MD5' is not defined.

```
Yet reflection works fine: 

```
 > type ComputeHash = delegate of byte[] -> byte[]
let computeHash  =
    let asm = System.AppDomain.CurrentDomain.GetAssemblies() |> Seq.find (fun x -> x.FullName.StartsWith("System.Security.Cryptography,"))
    let md5 = asm.GetTypes() |> Seq.find (fun x -> x.Name = "MD5")
    let computeHashMeth = md5.GetMethod("ComputeHash", [| typeof<byte[]> |])
    let md5obj = md5.GetMethod("Create",[||]).Invoke(null,[||])
    let d : ComputeHash = computeHashMeth.CreateDelegate(md5obj)
    fun x -> d.Invoke x
;;
type ComputeHash =
  delegate of byte[] -> byte[]
val computeHash: (byte[] -> byte[])

> computeHash [|0uy|];;
val it: byte[] =
  [|147uy; 184uy; 133uy; 173uy; 254uy; 13uy; 160uy; 137uy; 205uy; 246uy; 52uy;
    144uy; 79uy; 213uy; 159uy; 113uy|]
```

A F# net7.0 project works fine
![image](https://user-images.githubusercontent.com/7281367/194035547-c9eafc96-6503-46b1-81e3-b468162ff540.png)

Compiles and runs. 

FSI without "Use .NET Core Scripting"  works fine.

**Comment by ThisFunctionalTom** [comment]
We have the same problem.

**Comment by shankarv42** [comment]
Same issue. None of our cryptographic .fsx scripts are running on .NET7. Works with .NET6.

**Comment by blfuentes** [comment]
Same here.

**Comment by knt141** [comment]
work around: `#r "System.Security.Cryptography"` in top of fsx

**Comment by shankarv42** [comment]
It does not work. That is the first thing I tried. 
Even a simple script shows this  --> error FS0039: The value, namespace, type or module 'RandomNumberGenerator' is not defined.

**Comment by shankarv42** [comment]
@knt141 - thanks. Work around works !

**Comment by brandedoutcast** [comment]
It's an issue with CSharp scripts as well after upgrading to .NET 7 https://github.com/dotnet/sdk/issues/29325

**Comment by iskandersierra** [comment]
I'm also having this issue with a script that generates Aes Key/IV

The following script:

```fsharp
open System
open System.Security.Cryptography

let aes = System.Security.Cryptography.Aes.Create()
let key = Convert.ToBase64String(aes.Key)
let iv = Convert.ToBase64String(aes.IV)

printfn "Algorithm: %A" "AES"
printfn "Key: %A" key
printfn "IV: %A" iv
```

Produces the error: `error FS0039: The value, constructor, namespace or type 'Aes' is not defined.`

> With the workaround from @knt141 it works fine!

In C# script, event when the vscode intellisense is giving some errors:

```csharp
using System;
using System.Security.Cryptography;

var aes = System.Security.Cryptography.Aes.Create();
var key = Convert.ToBase64String(aes.Key);
var iv = Convert.ToBase64String(aes.IV);

Console.WriteLine($"Algorithm: AES");
Console.WriteLine($"Key: {key}");
Console.WriteLine($"IV: {iv}");
```

It produces the expected result:

```
Algorithm: AES
Key: VeoHUDrkPIb5uO9Yeb7KqQWHhxTSUViAr3hr6QcOS9g=
IV: zQM9rnyieYSNLj5tlXCK8w==
```
