### ISSUE TITLE
CodeLens is terribly slow

### ISSUE THREAD

**Issue by psfinaki** [dotnet/fsharp#14034]
This:

https://user-images.githubusercontent.com/5451366/194339770-92dcf7a9-70bc-41ab-9303-40bb048b34fa.mp4

Is not acceptable.

C# experience to compare:

https://user-images.githubusercontent.com/5451366/194341168-a4148a26-dbf4-4bf4-a555-be2231a24713.mp4

I'd argue we shouldn't let CodeLens out of the experimental mode until those "movements" are visible.

**Comment by T-Gro** [comment]
Agree, the delay is too annoying to claim this "production ready".
