### ISSUE TITLE
Text for VS FSI 64-bit option confuses 

### ISSUE THREAD

**Issue by moloneymb** [dotnet/fsharp#14101]
Updated 

The option about fsiAnyCpu sets 64-bit, fine. However the description text is very unclear. It should talk about 64-bit

--------

Original 

F# Tools missing the ability to use 64-bit F# interactive 

**Repro steps**

1. Install VS 17.3.6
2. Go to Tools -> Options -> F# Tools -> F# Interactive -> Misc
3. Note that there is no option to set 64bit

**Expected behavior**

![FSharpTools2](https://user-images.githubusercontent.com/140840/195492219-322d7de8-e87a-4e29-b244-684e0277dd0b.png)

**Actual behavior**

![FSharpTools](https://user-images.githubusercontent.com/140840/195491628-636aab41-b3bf-4f68-8ac5-5593ce858734.png)

**Known workarounds**

Use an older version of Visual Studio

**Related information**

Given the description written in the tools under Use fsiAnyCpu.exe it appears that this was not an oversight but was indeed intentional. This bug is to ask whoever is in charge of this to please reconsider and add the 64bit option back in as it is necessary for my work and I presume many others.

I use 64bit native libraries which don't have a 32bit version available so this is a breaking change for me. It would be impractical for me to maintain a 32bit branch of my native code just so that I could use it from F# interactive. I think it would be very rare to find people doing primarily 32bit native in 2022. All of my work is large data processing and the lack of addressable memory would be a non-starter. In so many ways 32bit is not an option. Especially for people doing Machine Learning and Data Processing where 64bit native libraries and large datasets are the norm.

**Comment by moloneymb** [comment]
I just checked and fsiAnyCpu.exe works with 64bit libraries. So closing this issue. Do do think the description should be clearer. Platform neutral doesn't inspire confidence especially with the “Any CPU 32-bit preferred" confusion. Which is why I pin things to 64bit whenever possible. And so I have of habit I changing the FSI to 64bit mode in the tools.

**Comment by moloneymb** [comment]
Re-opened by request

**Comment by dsyme** [comment]
The option about fsiAnyCpu sets 64-bit

However the description text is very unclear. It should talk about 64-bit

**Comment by dsyme** [comment]
@moloneymb I'm confused why "Use fsiAnuCpu.exe" was set to false in the above screenshot - the default should be true.  Do you recall if you explicitly set it to false?

**Comment by T-Gro** [comment]
Closed by #14181
