### ISSUE TITLE
Syntax highlighting is broken for F#.Editor

### ISSUE THREAD

**Issue by psfinaki** [dotnet/fsharp#14138]
In the current main, any file in this project seems to have the issue, e.g. SignatureHelp:
![image](https://user-images.githubusercontent.com/5451366/196443462-dd5ec6bd-53ed-41ab-8478-fcf805facc17.png)

Compare to VS GA:
![image](https://user-images.githubusercontent.com/5451366/196443711-2d26daa6-a5ee-4473-93b0-f37e61a9e09e.png)

**Comment by abelbraaksma** [comment]
Is it possibly related to this other regression? #14124

**Comment by vzarytovskii** [comment]
> Is it possibly related to this other regression? #14124

Looks unrelated, will look at it shortly.

**Comment by vzarytovskii** [comment]
Fixed by #14189
