### ISSUE TITLE
F# / C# interop fails when upgrading to the RC2.

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#14147]
Reported here:  https://github.com/dotnet/core/issues/7865#issuecomment-1281666911

To reproduce, create a solution with two – F# Library and C# Console projects. Reference the F# project from the C# one. Add at least two types in the Library.fs file (two single case discriminated unions for simplicity…) and access THE FIRST ONE from the C# project. It will throw: ” Program.cs(1, 24): [CS0117] ‘Test.A’ does not contain a definition for ‘A'”

Repro:  https://github.com/gdar91/Rc2FsCs

**Comment by vzarytovskii** [comment]
Duplicate of https://github.com/dotnet/fsharp/issues/14088
