### ISSUE TITLE
Eliminate net5.0 TFM usage in release/dev17.0

### ISSUE THREAD

**Issue by crummel** [dotnet/fsharp#14153]
The 6.0.1xx SDK is turned on deprecation warnings for the net5.0 TFM, leading to warnings like:
```
NETSDK1138: The target framework 'net5.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
```

These warnings are treated as errors which causes the build to fail.  This may also apply to other 6.0 servicing branches.

**Comment by vzarytovskii** [comment]
Oof, I think it was quite painful to migrate from net5 to net6 tfm in one of the next branches iirc.

@KevinRansom do you think it'll be doable to just backport the change to 17.0?

**Comment by KevinRansom** [comment]
I chatted with @crummel there is a work around.  He will also review policy proposals for the future around how to manage this.
