### ISSUE TITLE
`Tracking`: F# Telemetry

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#14166]
> **Note**
> This is a "meta" issue for tracking purposes since GitHub does not support special types of issues.

F# related telemetry in Visual Studio is currently quite rudimentary. We have a few things out of the box thanks to Roslyn, e.g. general F# usage but the split of telemetry within F# (e.g. by feature) is partially broken and partially absent.

Here is the proposed strategy to get on track with this topic.

**Stage 1**

- Start talking about this
- Grab some low-hanging telemetry fruit:
  - Fix existing broken F# telemetry: #14456
  - Add telemetry for code fixes: #14457
  - Set up some telemetry for the editor features: #14872

**Stage 2**

- Make some F# telemetry design in the VS editor, aligning the effort with Roslyn, Razor and others
- Figure out permission hell with the telemetry access for the whole F# team

**Stage 3**
- Make telemetry a cross-cutting concern for implementing whatever features

Some other ideas:
- Measure F# performance: #15061
- Collect types of solutions people work on, e.g. # of projects, # of files, LOC
- Unfinished background tasks hanging around in VS
- Overly long lock waiting times
- Requests for diagnostics which do not arrive after X seconds

**Comment by psfinaki** [comment]
I have started looking into that - discussing this topic with Shen Chen. Will post updates here.

**Comment by vzarytovskii** [comment]
I wil close this, since we don't have any pending work on it, we have some perf telemetry in place as well as error reporting now.
