### ISSUE TITLE
Implicit yield and if-then when using records with similarly-named fields causes type inference error

### ISSUE THREAD

**Issue by cmeeren** [dotnet/fsharp#14213]
Consider this:

```f#
type A = { X: int }
type B = { X: int }

let _x: (A -> int) list = [
    fun a -> a.X
    if true then fun a -> a.X
]
```

This fails with a type inference error:

<img width="266" alt="image" src="https://user-images.githubusercontent.com/7766733/199472238-01257580-65be-499d-824a-606de589bf05.png">

Adding `yield` works:

```f#
let _x: (A -> int) list = [
    yield fun a -> a.X
    if true then yield fun a -> a.X
]
```

As does type annotations to both `a` parameters:

```f#
let _x: (A -> int) list = [
    fun (a: A) -> a.X
    if true then fun (a: A) -> a.X
]
```

As does removing the `if`:

```f#
let _x: (A -> int) list = [
    fun a -> a.X
    fun a -> a.X
]
```

As a developer with no knowledge of the compiler, I can't see a compelling reason why I get the error. I would expect it to work.

**Comment by abonie** [comment]
I am starting to look into this, it still repros. Simpler example:
```fsharp
type A = { X: int }
type B = { X: int }

let l: A list = [
    if true then { X = 1 }
]
```
