### ISSUE TITLE
Fragile refactoring of variables

### ISSUE THREAD

**Issue by kant2002** [dotnet/fsharp#14220]
**Repro steps**

```
type ImageInfo = { 
    name: string
}
let LoadImage path = 
    { name = path }
let AddImage image =
    image.name

let mutable fond = "<shape name>"
let background = LoadImage("fond.png")
fond <- AddImage(background)
```

Rename `background` to `fond`. That allowed and produce broken code.

**Expected behavior**

Inform developer that refactoring would break his code.

**Actual behavior**

Allow rename of variable

**Known workarounds**

Do not know any for now.

**Related information**

Provide any related information (optional):

* Operating system
* .NET Runtime kind (.NET Core, .NET Framework, Mono)
* VS Version 17.4.0 Preview 5.0

**Comment by vzarytovskii** [comment]
@0101 fyi

**Comment by 0101** [comment]
This is by design, C# does the same thing. The error is displayed after the rename.
