### ISSUE TITLE
Compiler null references trying to handle PDBs

### ISSUE THREAD

**Issue by jaredpar** [dotnet/fsharp#14228]
**Repro steps**

Provide the steps required to reproduce the problem:

1. Clone VsVim https://github.com/VsVim/VsVim
2. Build Release: `Scripts\Build.ps1 -build -config Release` 

This is effectively equivalent to `msbuild /v:m /p:Configuration=Release VsVim.sln`

**Expected behavior**

Build Succeeds

**Actual behavior**

Build issues the following warnings:

```
FSC : * warning : PDB file could not be read and will be ignored: Object reference not set to an instance of an object. [C:\Users\jar
edpar\code\VsVim\Src\VimCore\VimCore.fsproj]
FSC : * warning : PDB file could not be read and will be ignored: Object reference not set to an instance of an object. [C:\Users\jar
edpar\code\VsVim\Src\VimCore\VimCore.fsproj]
FSC : * warning : PDB file could not be read and will be ignored: Object reference not set to an instance of an object. [C:\Users\jar
edpar\code\VsVim\Src\VimCore\VimCore.fsproj]
FSC : * warning : PDB file could not be read and will be ignored: Object reference not set to an instance of an object. [C:\Users\jar
edpar\code\VsVim\Src\VimCore\VimCore.fsproj]
  VimCore -> C:\Users\jaredpar\code\VsVim\Binaries\Release\VimCore\net472\Vim.Core.dll
  VimCore -> C:\Users\jaredpar\code\VsVim\Binaries\Release\VimCore\net6.0\Vim.Core.dll
```

**Known workarounds**

None

**Related information**

Using Visual Studio 2022 (17.3.6)

**Comment by vzarytovskii** [comment]
Thanks Jared, going to look at it in this sprint.

**Comment by KevinRansom** [comment]
@jaredpar --- this works now with 17.4.4, did you fix something?

![image](https://user-images.githubusercontent.com/5175830/214783944-9ce411aa-5322-46a5-8ff5-dc39dbfe098c.png)

**Comment by jaredpar** [comment]
@KevinRansom haven't done anything here that I'm aware of which could impact this. I've been completely blocked from working on VsVim because of this.

**Comment by KevinRansom** [comment]
This seems to work now.  Please reopen if it reoccurs for you.
