### ISSUE TITLE
Compilers fails to compile module with same name as Record using Unit of Measure generic type declared before

### ISSUE THREAD

**Issue by matthewcrews** [dotnet/fsharp#14234]
Please provide a succinct description of the issue.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Copy the following code into a `.fsx` or `.fs` file:
```
type Animal<[<Measure>] 'Measure> =
    {
        Size : float
    }

module Animal =

    let create (s: float<'Measure>) : Animal<'Measure> =
        { Size = float s }
```
2. Observe that the compiler throws an error for the `Animal` module.

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

**Expected behavior**

The compiler should compile.

**Actual behavior**

Compiler says there is a duplicate definition of the `Animal` type

**Known workarounds**

Annotate the `Animal` module with the `[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]` attribute.

**Related information**

Provide any related information (optional):

* Operating system
* .NET Runtime kind (.NET Core, .NET Framework, Mono)
* Editing Tools (e.g. Visual Studio Version, Visual Studio)

**Comment by matthewcrews** [comment]
I would be happy to help with this if someone pointed me in the right direction, as I will likely be the largest beneficiary.

**Comment by T-Gro** [comment]
I think it is a timing gap around the UoM erasure.
For a classical generic record, it works fine, because you can gave class A and class A<T> in the compiled code, that works just fine and that is why it passes trough the check.
But the generic arguments gets erased eventually.
The code for building to defensive set of names (in order to add Module suffix) only collects them if they do NOT have any type argument.

**Comment by T-Gro** [comment]
In CheckDeclarations, the condition is propbably supposed to be:

if  isNil (typars |> List.filter removeErasedTypeArguments)

=> only skipping the name colelction if there remains at least 1 non-erased generic argument

https://github.com/dotnet/fsharp/blob/df393d08fef239cf9644e8af1fb57d4ae517f7ad/src/Compiler/Checking/CheckDeclarations.fs#L2504-L2514

**Comment by T-Gro** [comment]
(this function builds a set of strings, names to be checked for possible collisions with module names and therefore activating the Module suffix)

**Comment by T-Gro** [comment]
Matt:

In SyntaxTree, the **typar** (**TY**pe**AR**gument) has the following shape, with attributes on it:
[<NoEquality; NoComparison>]
type SynTyparDecl = SynTyparDecl of attributes: SynAttributes * SynTypar

So this check should be possible.


Here is what I would do:
Add new test-file by mimicing what the neighborhood tests are doing, I would place this one at :
\tests\**FSharp.Compiler.ComponentTests**\Conformance\**UnitsOfMeasure**\

Cover the following via separate test cases (in the end almost identical)
- Non-generic record + module  // erasure IS needed
- Classical generic record + module  // erasure not needed
- UoM-generic record + module // erasure IS needed
- Record having both UoM generics and regular generics + module  // erasure not needed

And add a breakpoint to the set-building function above and inspect.
Focus on the **SynComponentInfo(typeParams=TyparDecls typars** and **if isNil typars** then parts

**Comment by T-Gro** [comment]
If you look around the ComponentTests folder, you will notice that bigger test cases become their own .fs/.fsx files, and small ones  can be also added as plain strings with code.

**Comment by matthewcrews** [comment]
Thank you for this context. I'll try to figure out how to get my system setup so I can build F# and work on this bug. It looks like a good first issue and I've wanted to help 😊.

**Comment by T-Gro** [comment]
Excellent choice! Will be looking forward :)

**Comment by 0101** [comment]
This doesn't seem to reproduce anymore in latest F#/VS.
