### ISSUE TITLE
Can't event start to learn F#

### ISSUE THREAD

**Issue by Razur3** [dotnet/fsharp#14231]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/languages/fsharp-hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

running on windows 11 Home version 10.0.22000 Build 22000
Error message i get is this: 
Error: Invalid option(s): 
-f
net6.0 

I installed the SDK successfully, and i checked the stackoverflow post mentioned in the training. 
Still getting the same error. 
What am i doing wrong?

**Comment by vzarytovskii** [comment]
@Razur3 what is the output of `dotnet --info`?

**Comment by 0101** [comment]
Cannot reproduce.
