### ISSUE TITLE
printfn number formatting: inconsistent padding behavior

### ISSUE THREAD

**Issue by benjamin-thomas** [dotnet/fsharp#14247]
Hello, I'm learning F# and hit a problem that looks like a bug to me.

The problem is very easy to reproduce in a REPL, by copying the following lines:

```fsharp
printfn $">%03d{9}<\n>% 3d{9}<";;
printfn $">%03d{99}<\n>% 3d{99}<";;
printfn $">%03d{999}<\n>% 3d{999}<";;
```

Output below:

```
>009<
>  9<

>099<
> 99<

>999<
> 999<
```

**Expected behavior**

I would expect the space padding to stop once the specified threshold has been hit.

My REPL version: `F# Interactive version 12.0.4.0 for F# 6.0`
My OS: `Ubuntu 20.04.5 LTS`

**Comment by abonie** [comment]
Hi @benjamin-thomas, thanks for reporting, but I don't believe this is actually a bug. Check out F# docs here https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/plaintext-formatting#format-specifiers-for-printf, specifically the second table in the linked section of the page

Specifying space flag adds an extra space to positive numbers. If you simply want to pad with whitespace, you can just do it by skipping the `0` flag and the space flag, like so:
```fsharp
printfn $">%03d{9}<\n>%3d{9}<";;
```
output:
```
>009<
>  9<
```

**Comment by benjamin-thomas** [comment]
Hello, indeed you'r right sorry for the bother!

Also, this behavior is not fsharp specific. Here's some ruby code for ref:

```
[1] pry(main)> ap [sprintf("%03d", 99), sprintf("%3d", 99), sprintf("% 3d", 99)]
[
    [0] "099",
    [1] " 99",
    [2] " 99"
]
=> nil
[2] pry(main)> ap [sprintf("%03d", 999), sprintf("%3d", 999), sprintf("% 3d", 999)]
[
    [0] "999",
    [1] "999",
    [2] " 999"
]
=> nil
```

**Comment by abonie** [comment]
Yes, I am guessing because both are inspired by C's printf family of functions
