### ISSUE TITLE
Add parameter name hints for discriminated unions

### ISSUE THREAD

**Issue by psfinaki** [dotnet/fsharp#14257]
Basically, this:

![image](https://user-images.githubusercontent.com/5451366/200350297-5be64935-76b1-412e-a68b-ffcc73b758d7.png)

**Comment by kerams** [comment]
Would this come under `HintKind.ParameterNameHint`?  I am not sure it would make sense to introduce a new kind for case field hints (or for ctors and methods, for that matter).

**Comment by psfinaki** [comment]
Yeah so for now, on this level I'd probably only distinguish things that we want to distinguish in user options as well. But I don't want to create such an option mess that C# has (IMO), at least not to start with this, maybe later.
