### ISSUE TITLE
Minimal source-build build

### ISSUE THREAD

**Issue by crummel** [dotnet/fsharp#14273]
Source-build has been looking at improving the build time of the overall source-built SDK and F# turns out to be one of the slower repos.  We'd like to follow up on this and improve if possible, so there's some questions we can work on between us:

- What takes F# so long?
  - Suggestions that were brought up so far
    - Is the F# compiler bootstrap process necessary?  I'm going to look into a fake bootstrap-less F# that I expect would have prebuilts but might be interesting for comparison.
    - Is there a lot of native code?  (Tends to be slower)
- How much time can we save and how much effort would it take?

I still have some investigation to do on this but I wanted to bring it up so if you have any ideas we can get going on those faster.  Thanks!

**Comment by KevinRansom** [comment]
@crummel --- yes the bootstrap is sometimes necessary.  We often use new language features as soon as they are added to the compiler.  We could consider a rule to ban new language features in the compiler until after the compiler has shipped.  But that is likely to be very un-helpfull to us.

**Comment by KevinRansom** [comment]
@crummel - we can work on improving the build speed.  What are the build times you are looking at?  What command and environment can we look at optimizing?

**Comment by crummel** [comment]
Thanks, good to know we shouldn't focus on bootstrap then.  I'll get fresh timings on a source-build and hopefully have the long poles tomorrow if that's alright.

**Comment by vzarytovskii** [comment]
We for sure can shave off the parser generation, by caching it and hashing properly, like we do with xlf, and shipped apis.
It will shave a minute or two for the builds. Maybe more.

**Comment by crummel** [comment]
I pulled some binlogs from a recent source-build and I'm seeing ResolveProjectReferences take a sizeable chunk of the time - about half the entire build time.  Is there anything special going on there?  I'm wondering if this isn't really an F# build perf issue at all but actually something like how many packages source-build puts in the blob feed and the restore taking longer because of that.  I'll compare to a source-build leg of F# only to see if there's a difference.

**Comment by crummel** [comment]
I think we've gotten an answer to the original issues, which is that we do need the bootstrap build.  I logged https://github.com/dotnet/fsharp/issues/14467 for the F# team to follow up on the parser generation when you have time, and https://github.com/dotnet/source-build/issues/3175 for source-build to follow up on the restore time issue since it appears source-build specific.  I'll close this issue, let me know if anyone objects.  Thanks!
