### ISSUE TITLE
FS0192 error on use simplified SRTP call syntax

### ISSUE THREAD

**Issue by gsomix** [dotnet/fsharp#14297]
Compilation fails when use simplified SRTP call syntax on instance member.

**Repro steps**

1. Create console application:
```
$ mkdir Issue14297
$ cd Issue14297
$ dotnet new console -lang f#
```

2. Replace `Program.fs` content with:
```fsharp
type Issue14297() =
  member _.DoIt() = printfn "Done"

let inline doIt<'T when 'T : (member DoIt: unit -> unit)> (x: 'T) =
  x.DoIt()

[<EntryPoint>]
let main argv =
  let x = Issue14297()
  doIt x
  0
```

3. Build the project:
```
$ dotnet build
```

**Expected behavior**

Project successfully compiles.

**Actual behavior**

Compilation fails with error:
```
> error FS0192 : internal error : destFunTy: not a function type
```

**Known workaround**

Use old SRTP call syntax:
```fsharp
let inline doIt<'T when 'T : (member DoIt: unit -> unit)> (x: 'T) =
  (^T : (member DoIt: unit -> unit) x)
```

**Related information**
macOS 12.6, F# 7
```
$ dotnet --version
> 7.0.100
```

**Comment by T-Gro** [comment]
@vzarytovskii  See here, another issue related to new SRTP features.

**Comment by vzarytovskii** [comment]
> @vzarytovskii  See here, another issue related to new SRTP features.

Yes, I've fixed it already, going to be in the batch pr

**Comment by vzarytovskii** [comment]
Should be fixed by https://github.com/dotnet/fsharp/issues/14097, just didn't make it to rtm
