### ISSUE TITLE
Compiler does not produce an error when one leaves out keyword "static" in an implementation of IWSAM.

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#14316]
This results in methodmissingexception in runtime.

Should be an easy fix.

**Comment by edgarfgp** [comment]
Is there any code repro for this issue ?

**Comment by En3Tho** [comment]
@edgarfgp 

module StaticAbstractBug =
    type IOperation =
        static abstract member Execute: unit -> unit

    type FaultyOperation() =
        interface IOperation with
            member _.Execute() = () // no error

    type WorkingOperation() =
        interface IOperation with
            static member Execute() = ()

    let consume<'o when 'o :> IOperation>() ='o.Execute()

    let fail() = consume<WorkingOperation>()

// this is actually a different behavior than the one I've experienced before: build was successful and fail function was called but runtime error "Missing method" occured
// "obj\Release\net7.0\refint\Bugs.dll": Error in pass3 for type Program, error: Error in pass3 for type StaticAbstractBug, error: Error in pass3 for type FaultyOperation, error: Error in GetMethodRefAsMethodDefIdx for mref = ("Execute", "IOperation"), error: MethodDefNotFound
StaticAbstractBug.fail()
