### ISSUE TITLE
Error in pass2 for type MyExceptionTypeException, error: duplicate entry 'get_Message' in method table

### ISSUE THREAD

**Issue by nbevans** [dotnet/fsharp#14326]
**Repro steps**

```fsharp
    exception InitializeException of Message : string
```

**Expected behavior**

The exception type doesn't throw an exception at build time.

**Actual behavior**

It throws:

FSC : error FS2014: A problem occurred writing the binary 'C:\Sandbox\Singapore\Singapore.Mobile.Storage\obj\Debug\netstandard2.0\Singapore.Mobile.Storage.dll': **Error in pass2 for type Singapore.Mobile.Storage.Tasks, error: Error in pass2 for type DataSet, error: Error in pass2 for type InitializeException, error: duplicate entry 'get_Message' in method table** [C:\Sandbox\Singapore\Singapore.Mobile.Storage\Singapore.Mobile.Storage.fsproj]

**Known workarounds**

Change the exception type to:

```fsharp
exception InitializeException of MessageText : string
```

**Related information**
This is a regression that occurred after updating to VS 17.4.0

**Comment by vzarytovskii** [comment]
It's caused by one of the features enabled by default in F#, adding a Message property.

Should probably be a better message, or even not generate if it's already there.

**Comment by vzarytovskii** [comment]
This is very similar to 
https://github.com/dotnet/fsharp/issues/14321

We can either chose to not generate it if the field is present, or produce a similar issue. It is a breaking change, technically, but guarded by language version.

**Comment by vzarytovskii** [comment]
Interesting enough, we're checking members apparently, but it fails the check for exn it seems
```fsharp
 let ilMethodDefs =
            [ ilCtorDef
              yield! ilCtorDefNoArgs
              yield! serializationRelatedMembers
              yield! ilMethodDefsForProperties

              if not (exnc.HasMember g "get_Message" []) && not (exnc.HasMember g "Message" [])  then
                  yield! GenPrintingMethod cenv eenv "get_Message" ilThisTy m ]
```
