### ISSUE TITLE
VS 17.4.1 failed to load some .NET 6 F# sln

### ISSUE THREAD

**Issue by sangkilc** [dotnet/fsharp#14337]
After upgrading VS from 17.3 to 17.4.1,  VS fails to load some of my projects in VS (win 11 pro). VS shows a bunch of `FS0193` errors, while `dotnet build` works well without any problem. 

Particularly, I see `FS0193` errors from VS's error window, although building from a command line (`dotnet build`) will never show such errors. I noticed some projects load well, some others do not.

**Repro steps**

1. git clone https://github.com/B2R2-org/B2R2.git
2. cd B2R2; start B2R2.sln
3. From the solution explorer, open `src` -> `FrontEnd` -> `B2R2.FrontEnd.BinInterface` -> `BinHandle.fs`, and wait.
4. The error list window shows the following errors:
```
Severity	Code	Description	Project	File	Line	Suppression State
...
Error	FS0193	The module/namespace 'B2R2' from compilation unit 'B2R2.Core' did not contain the val 'ValLinkagePartialKey(GetMin)'	B2R2.FrontEnd.BinInterface	C:\dbg\B2R2\src\FrontEnd\BinInterface\BinHandle.fs	1	Active
Error	FS0193	The module/namespace 'B2R2' from compilation unit 'B2R2.Core' did not contain the val 'ValLinkagePartialKey(GetMax)'	B2R2.FrontEnd.BinInterface	C:\dbg\B2R2\src\FrontEnd\BinInterface\BinHandle.fs	1	Active
Error	FS0193	The module/namespace 'B2R2' from compilation unit 'B2R2.Core' did not contain the val 'ValLinkagePartialKey(.ctor)'	B2R2.FrontEnd.BinInterface	C:\dbg\B2R2\src\FrontEnd\BinInterface\BinHandle.fs	1	Active
Error	FS0039	The namespace 'BinFile' is not defined.	B2R2.FrontEnd.BinInterface	C:\dbg\B2R2\src\FrontEnd\BinInterface\BinHandle.fs	29	Active
...
```

**Expected behavior**

I should not see any build errors from VS as in a terminal.

**Actual behavior**

VS shows FS0193 errors and does not allow me to navigate the code.

**Known workarounds**

This error goes away when I rollback to VS 17.3.

**Related information**

* Operating system: Windows 11 pro
* dotnet --version shows: `7.0.100`
* Visual Studio 17.4.1

**Comment by vzarytovskii** [comment]
I believe it was fixed by https://github.com/dotnet/fsharp/pull/14093, so should go into 17.5, and probably next 17.4 release (if it got serviced).
As a workaround in current release, you can try setting `<ProduceReferenceAssembly>false</ProduceReferenceAssembly>` for projects.

**Comment by sangkilc** [comment]
> As a workaround in current release, you can try setting <ProduceReferenceAssembly>false</ProduceReferenceAssembly> for projects.

This is just a note. I tried setting `ProduceReferenceAssembly` to false under VS 17.4.2, but the same problem persists. I hope this issue goes away with the version 17.5.
