### ISSUE TITLE
FSharpChecker.CompileToDynamicAssembly

### ISSUE THREAD

**Issue by aciq** [dotnet/fsharp#14346]
i used this function to make in-memory dynamic assembiles from fsx scripts in 41.0.7

Does this function just no longer exist? 
Is there a replacement? 

I cant find a single thing about it in the notes

**Comment by T-Gro** [comment]
The surface area of FCS has been trimmed by https://github.com/dotnet/fsharp/issues/13242 .
For getting output of .fsx execution, FsiEvaluationSession type has a DynamicAssemblies property:

```
    /// Get all the dynamically generated assemblies
    member DynamicAssemblies: System.Reflection.Assembly[]
```

**Comment by vzarytovskii** [comment]
@T-Gro i think we will need to revert the https://github.com/dotnet/fsharp/pull/13966 and put an obsolete attribute, so it can be removed in future versions. This is how we usually do the deprecation, and should stick to it.

**Comment by vzarytovskii** [comment]
> i used this function to make in-memory dynamic assembiles from fsx scripts in 41.0.7
> 
> Does this function just no longer exist? 
> Is there a replacement? 
> 
> I cant find a single thing about it in the notes

See if replacement @T-Gro suggested works for you, we should've made it obsolete instead with instructions for migration.

**Comment by aciq** [comment]
Found a replacement. now everythings good, thanks

**Comment by ingted** [comment]
Hi @aciq,

Could you share the information of the replaced solution? Or even a hint...
I bumped into the same issue...

**Comment by SirBogman** [comment]
@ingted I just ran into this issue too and here is how I worked around it.

I modifyied my code to use `FSharpChecker.Compile` instead of `CompileToDynamicAssembly` , which writes the assembly to a file based on the `-o` flag as [described here](https://github.com/dotnet/fsharp/blob/23e22eadf193cdd7e38ea4fa68c0f76d1b14ca9b/src/Compiler/Service/service.fsi#L327).

After compiling, you can load the assembly from the file, if necessary, with `Assembly.LoadFile`.

**Comment by ingted** [comment]
@SirBogman Thank you so so so much!!!

**Comment by JustinGrote** [comment]
Is there a way to still keep it in memory and not write out to a file? That's a lot slower.

**Comment by SirBogman** [comment]
> Is there a way to still keep it in memory and not write out to a file? That's a lot slower.

I'm not an expert on this but I kind of doubt it. For my application we use tempfs on Linux so it's not a physical disk. Overall the application is 10%-20% faster than before with .NET 7 and the newest F# libs, even though I had to change it to write to the "disk".

Maybe look at FsiEvaluationSession if your application isn't just a one time compile and run like mine is.

**Comment by JustinGrote** [comment]
Thanks, my use case in this part is basically adding `Add-Type` F# support to PowerShell, so that you can dynamically compile an assembly from F# code and use it's type/objects in PowerShell code.
https://github.com/justingrote/fsharp

**Comment by T-Gro** [comment]
namespace FSharp.Compiler.IO
has:
```fsharp
[<AutoOpen>]
module public FileSystemAutoOpens =
    /// The global hook into the file system
    let mutable FileSystem: IFileSystem = DefaultFileSystem() :> IFileSystem
```

Meant for the case of opting out of standard filesystem operations, by overwriting some of IO actions happening in the compiler.
On of the methods is also what compiler uses for writing - `OpenFileForWriteShim`.

Could this be a solution for you?

**Comment by JustinGrote** [comment]
So are you suggesting override the filesystem to some kind of memory based filesystem? I really don't need it to write the file out at all, I just want it a dynamic assembly in memory that I can load in memory without hitting the disk. With SSDs this is less of an issue but it's still a very slow path compared to memory relatively. I'm also fairly inexperienced in this area.

**Comment by JustinGrote** [comment]
@T-Gro FYI docs still reference dynamic assembly:
https://fsharp.github.io/fsharp-compiler-docs/fcs/compiler.html#Compiling-to-a-dynamic-assembly

**Comment by T-Gro** [comment]
Sorry about the docs, I will remove the reference.

The suggestion above: Of course I would only do that if it is measured that disk is the real problem here - in such a case, providing an in-memory FS operation can mitigate the cost.
But normally, until seen as a bottleneck, I would stick with the regular behavior of writing the assembly to disk.

**Comment by JustinGrote** [comment]
@T-Gro No worries. Since I have to pack along the SDK to make this work, that's kind of a non-starter now unfortunately, but thanks for the response.

**Comment by ieviev** [comment]
I found this issue googling 2 years later and realized i need to set this straight and give a proper solution:
```fsharp
// minimal sample that compiles a script file to byte[]
#r "nuget: fsharp.compiler.service, 43.8.300"

open System.IO
open FSharp.Compiler.Text
open FSharp.Compiler.CodeAnalysis
open System.Reflection

type InMemoryFileSystem() =
    inherit FSharp.Compiler.IO.DefaultFileSystem()
    member val InMemoryStream = new MemoryStream()
    override this.OpenFileForWriteShim(_, _, _, _) = this.InMemoryStream

let compile (scriptFile: string) =
    task {
        // override global file system
        let filesystem = InMemoryFileSystem()
        FSharp.Compiler.IO.FileSystemAutoOpens.FileSystem <- filesystem
        let checker = FSharpChecker.Create()

        let! projOpts, _ =
            checker.GetProjectOptionsFromScript(
                scriptFile,
                SourceText.ofString (File.ReadAllText(scriptFile)),
                assumeDotNetFramework = false,
                useFsiAuxLib = true,
                useSdkRefs = true
            )

        let! compileResult, exitCode =
            checker.Compile(
                [| "fsc.exe"
                   $"--out:output.dll"
                   yield! projOpts.OtherOptions
                   yield! (projOpts.ReferencedProjects |> Array.map (fun v -> v.OutputFile))
                   yield! projOpts.SourceFiles |]
            )

        match exitCode with
        | 0 ->
            let compiledAssembly = filesystem.InMemoryStream.ToArray()
            return compiledAssembly
        | _ -> return failwith $"failed to compile: %A{compileResult}"
    }

let newAssembly: byte array = compile("myscript.fsx").Result
let asm: Assembly = Assembly.Load(newAssembly)
asm.EntryPoint.Invoke(null, [||])
```
