### ISSUE TITLE
FSI's cursor does not correctly handle full-width characters

### ISSUE THREAD

**Issue by Tangent-90** [dotnet/fsharp#14347]
FSI's cursor does not correctly handle full-width characters.

![GIF 2022-11-18 11-05-47](https://user-images.githubusercontent.com/43789618/202607698-86bb892a-99bd-40e8-820e-feca54bfddde.gif)

**Repro steps**

Provide the steps required to reproduce the problem:

1. Run `dotnet fsi`
2. Input some full-width characters
3. Move the cursor left or right

**Expected behavior**

The cursor should not appear inside the character.

**Actual behavior**

The cursor will appear inside the character.

**Known workarounds**

The `NStack.ustring` in package `NStack.Core` has a property named `ConsoleWidth`, which will be useful to fix the bug. 

![图片](https://user-images.githubusercontent.com/43789618/202608376-2367dba8-9ee5-4a49-a7b8-e3c3d9c0374a.png)

**Comment by Tangent-90** [comment]
Is there any update? Can I make a pr to fix this?

**Comment by vzarytovskii** [comment]
> Is there any update? Can I make a pr to fix this? 

Sure, we'll gladly accept PR with the fix.

**Comment by abonie** [comment]
I wanted to check something and tried to reproduce this issue, but when I run `dotnet fsi` in windows terminal, everything pastes in as question marks (halfwidth). Which is weird, because in windows terminal outside of fsi, I can paste fullwidth chars just fine... Anyone has a hint regarding what settings I need to change on my side to fix that?

**Comment by Tangent-90** [comment]
> I wanted to check something and tried to reproduce this issue, but when I run `dotnet fsi` in windows terminal, everything pastes in as question marks (halfwidth). Which is weird, because in windows terminal outside of fsi, I can paste fullwidth chars just fine... Anyone has a hint regarding what settings I need to change on my side to fix that?

Maybe you can check the encoding setting of `System.Console`. In my computer the encoding is `Codepage - 936`, which is  same encoding as terminal. 

![图片](https://user-images.githubusercontent.com/43789618/203661394-0d03f732-f114-444c-8d38-a2561bfe73e4.png)
