### ISSUE TITLE
expression is mistaken for named argument

### ISSUE THREAD

**Issue by JaggerJo** [dotnet/fsharp#14353]
**Repro steps**

```fsharp
type Util =
    static member invert (value: bool) = not value

let flag = false

Util.invert (flag = true)
```

```
error FS0495: The member or object constructor 'invert' has no argument or settable return property 'flag'. The required signature is static member Util.invert: value: bool -> bool.
```

[SharpLab](https://sharplab.io/#v2:DYLgZgzgNAJiDUAfALgTwA4FMAEBVZAlsNgLwCwAUNtdhMgIaEDG2AtpqwEaYBO2BAOwBuvZNgAUQ+sACumENk4B7JcACUpbAKVipszJUrBMYsMHoBzTWGkQDFSviIA6QSJ5jxZy5uQ85akA)

**Expected behavior**

Method is called with the result of the expression as a parameter.

**Actual behavior**

Fails to compile.

**Known workarounds**

Wrapping the expression in extra `()`
```fsharp
type Util =
    static member invert (value: bool) = not value

let flag = false

Util.invert ((flag = true))
```

[SharpLab](https://sharplab.io/#v2:DYLgZgzgNAJiDUAfALgTwA4FMAEBVZAlsNgLwCwAUNtdhMgIaEDG2AtpqwEaYBO2BAOwBuvZNgAUQ+sACumENk4B7JcACUpbAKVipszJUrBMYsMHoBzTWGkQDFSviIA6QSJ5jx4s5c3IecmpqQA=)

**Related information**

.NET 6.0.403

**Comment by Happypig375** [comment]
This is by design because parameters of methods are interpreted as named arguments before as expressions. Implicitly falling back may lead to unexpected behaviour changes when adding or removing named parameters.

**Comment by charlesroddie** [comment]
While it would be nice to have this (interpretation of `x = y` as a bool when there is no argument or settable property called `x`), it would make the parser more complex and I don't think we should do anything which makes F# slower to compile.

**Comment by JaggerJo** [comment]
@charlesroddie @Happypig375 Thanks for the clarification!

 Makes sense, but it's bit weird as a user as there is a difference between invoking a static method and invoking a function.
 
```fsharp
Util.invert (flag = true)
```

⬆️ works if [Util is a module](https://sharplab.io/#v2:DYLgZgzgNAJiDUAfAtgexgV2AUwAQFUAXAS2FwF4BYAKFztx0N2IDsA3bAJyYAo2BDYBmwhcAI1SpgASgq4WqJgKHYaNRrjDB+AczlhBEVdXXYmAfTlFSAOlYduuHlt1zCnYdKA=)

I get that there are a bunch of differences already (functions can't be called with named arguments, no optional arguments, ..) but this one seemed weird to me. 

> This is by design because parameters of methods are interpreted as named arguments before as expressions. Implicitly falling back may lead to unexpected behaviour changes when adding or removing named parameters.

Totally get this 👍
