### ISSUE TITLE
Wrong type hint for a module value containing a lambda

### ISSUE THREAD

**Issue by kerams** [dotnet/fsharp#14378]
**Repro steps**

`let func = fun () -> 3`

**Expected behavior**

Type hint containing `: (unit -> int)` (with or without the parentheses).

**Actual behavior**

![TiwQboH0iO](https://user-images.githubusercontent.com/5063478/203560991-66de05bb-b032-4c13-8bc1-2ab2bd93a72d.png)

**Related information**

* VS integration built from the current main branch

The issue originates in this function

![devenv_PFgtHiFxsT](https://user-images.githubusercontent.com/5063478/203561384-dafae3e7-fb6a-4bed-b3c3-5f7a68982985.png)

`retTy` is the `int` type, while the solution of `tau` is `unit -> int`, which is what we're looking for in the hint. I don't want to touch this, because I have no idea what ramifications it could have across the compiler.

**Comment by psfinaki** [comment]
Unassigning me for now in case someone else wants to fix this - can be a good exercise for contributors.

**Comment by psfinaki** [comment]
Doesn't repro anymore, adding some tests though.
