### ISSUE TITLE
Make Type Hints less intrusive

### ISSUE THREAD

**Issue by psfinaki** [dotnet/fsharp#14382]
So this is quite annoying:

https://user-images.githubusercontent.com/5451366/203621934-99ec33fb-d39d-4c38-9611-eb1684f79d21.mp4

Instead, I'd prefer the behavior like in C# on the right - show the type when we can provide useful information (e.g. when the equal sign is printed).

**Comment by psfinaki** [comment]
We had a brief session on this with @vzarytovskii - but our best idea so far is just to look if there are any diagnostics within the range, like don't show any hints if there is an error in the code. Seems a bit crude but better than the current situation.

@dsyme @T-Gro @kerams Maybe you have any ideas?

**Comment by kerams** [comment]
![9v7F1SdBMi](https://user-images.githubusercontent.com/5063478/203642899-e6042d95-956d-4022-8602-3ad990120012.png)

Here the typar of `b` is unsolved. Since incomplete bindings like that seem to be assigned placeholder generic type variables, mayhaps it would be a good rule of a thumb not to show generic type hints unless they are solved?

**Comment by T-Gro** [comment]
I would couple it with diagnostics - there might be diagnostical errors which work just fine with type hints.
Instead I would prevent showing useless information => if a type cannot be derived, the hint is not telling much.

**Comment by 0101** [comment]
Could we somehow get the hint to be on the other side of the cursor? I think that would help no only this case but usability in general.

**Comment by psfinaki** [comment]
Likely yes. I think this is orthogonal to the current issue, so I'll create another one :)

**Comment by vzarytovskii** [comment]
> it will take some effort to propagate it properly

I'm not sure that we should expose a type implementation detail via symbol API.

**Comment by psfinaki** [comment]
Hmhm we can probably fix at least some cases leveraging the `IsSolveAtCompileTime` prop available without much effort. Stay tuned.

**Comment by dsyme** [comment]
My main thoughts (beyond those already discussed here) are that type hints like these should not be on by default. They should show with a hot key.  That may be the default that's planned, I'm not sure?

**Comment by vzarytovskii** [comment]
> My main thoughts (beyond those already discussed here) are that type hints like these should not be on by default. They should show with a hot key. That may be the default that's planned, I'm not sure?

Yeah, they're off by default now, and can be enabled in options, toggling via hotkeys (both on press and toggle-based) will be later.

**Comment by psfinaki** [comment]
Reopening this to also handle type hints in functions:

https://user-images.githubusercontent.com/5451366/204516716-e0db2da1-8b5f-48ba-b652-3d231adda4dc.mp4

**Comment by psfinaki** [comment]
Unassigning me for now in case someone else wants to play with this as well.
