### ISSUE TITLE
`ItemKeyStore` can disappear leading to `FindBackgroundReferencesInFile` not working 

### ISSUE THREAD

**Issue by 0101** [dotnet/fsharp#14396]
**Repro steps**

Provide the steps required to reproduce the problem:

1. In VS, `FSharp.Compiler.Service` solution
2. Open [`Driver/CompilerDiagnostics.fs`](https://github.com/dotnet/fsharp/blob/main/src/Compiler/Driver/CompilerDiagnostics.fs)
3. Go to [`type PhasedDiagnostic`](https://github.com/dotnet/fsharp/blob/23e22eadf193cdd7e38ea4fa68c0f76d1b14ca9b/src/Compiler/Driver/CompilerDiagnostics.fs#LL342C15-L342C15)
4. Find All References (69 references are found)
5. Change the file (e.g. add an empty line somewhere)
6. **Save** 
7. Find All References on `PhasedDiagnostics` again

**Expected behavior**

We get the same results as the first time

**Actual behavior**

Only 63 references found this time, all results from `Driver/CompilerDiagnostics.fs` are missing. 

**Related information**

`BackgroundCompiler.FindReferencesInFile` returns an empty sequence, because `ItemKeyStore` is `None` in the check results for this file.

* Re-type checking the file (e.g. after making other changes) doesn't fix it.
* Changing a file _above_ the affected file in compilation order does seem to fix it. 
* This also affects rename functionality. 
* VS Version 17.5.0 Preview 2.0 [33127.37.main]

**Comment by T-Gro** [comment]
This is  reproducible in a big project like FCS, but I cannot reproduce it in a smaller project.
It is likely a timing gap between invalidation and re-checking.

**Comment by T-Gro** [comment]
In another project, when exploding it with thousands of expressions, I can at least get the results later. They come in asynchronously.

But in the described FSC scenario, they never come to be complete...

**Comment by vzarytovskii** [comment]
@0101 is it the same issue with https://github.com/dotnet/fsharp/issues/14411 ?
