### ISSUE TITLE
Cannot use locally built F# compiler within VS

### ISSUE THREAD

**Issue by kant2002** [dotnet/fsharp#14397]
When building F# project using custom build F# compiler with custom keywords from Visual Studio error happens
```
FSC error FS2020: The assembly 'C:\d\github\dotnet\fsharp\artifacts/bin/fsc/Debug/net7.0/fsc.dll' is listed on the command line. Assemblies should be referenced using a command line flag such as '-r'. [C:\d\github\funsharp\ісх\ВеселШарп.Бібліотека.fsproj]
```

Even if build in VS does not works, what working
- Build using `dotnet build`
- Colorization within VS. New keywords correctly highlighted.

**Repro steps**

1. Clone F# repo to `C:\d\github\dotnet\fsharp`
2. Add aliases to existing F# keywords, For example add `let` => `leet`
3. Create project which use these custom keywords.
4. Add following properties in the `Directory.Build.props` of the F# project
```xml
<PropertyGroup>
  <FSharpRoot>C:\d\github\dotnet\fsharp\</FSharpRoot>
  <DotnetFscCompilerPath>$(FSharpRoot)artifacts/bin/fsc/Debug/net7.0/fsc.dll</DotnetFscCompilerPath>
  <Fsc_DotNET_DotnetFscCompilerPath>$(FSharpRoot)artifacts/bin/fsc/Debug/net7.0/fsc.dll</Fsc_DotNET_DotnetFscCompilerPath>
   <!-- these experiments and probably do not affect anything -->
  <FSharpPreferNetFrameworkTools>false</FSharpPreferNetFrameworkTools>
  <FSharpCompilerPath>$(FSharpRoot)artifacts/bin/fsc/Debug/net7.0/</FSharpCompilerPath>
</PropertyGroup>
```
5. Open VisualFSharp.sln
6. Run VisualFSharpDebug project
7. Open F# project with custom keywords.
8. Build project in the VS

In case if this is needed.
- Custom F# compiler https://github.com/kant2002/fsharp
- Test F# solution which used custom keywords https://github.com/kant2002/funsharp/tree/%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BD%D0%B0-%D1%84%D1%88%D0%B0%D1%80%D0%BF

** Investigation **
From what I see `DotnetFscCompilerPath` passed to the `Fsc` task. And then FSC task produces 

```
C:\d\github\dotnet\fsharp\artifacts\bin\fsc\Debug\net7.0\fsc.exe C:\d\github\dotnet\fsharp\artifacts/bin/fsc/Debug/net7.0/fsc.dll -o:obj\Debug\net7.0\ВеселШарп.Бібліотека.dll
-g
...
skipped
...
```

My understanding that proper call should be 
```
dotnet.exe C:\d\github\dotnet\fsharp\artifacts/bin/fsc/Debug/net7.0/fsc.dll -o:obj\Debug\net7.0\ВеселШарп.Бібліотека.dll
-g
...
skipped
...
```

[binlog.zip](https://github.com/dotnet/fsharp/files/10104869/binlog.zip)

**Comment by vzarytovskii** [comment]
It depends on which compiler has been chosen, it should either run as `fsc.exe ... parameters` or `dotnet.exe path/to/fsc.exe ... parameters`.
Can you try removing custom compiler paths and see what gets chosen? I would imagine we point compiler to locally built one when running under VisualFSharpDebug.

**Comment by kant2002** [comment]
When I remove customization from `Directory.Build.props` Visual Studio pickup built-in Fsc task from `C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools\FSharp.Build.dll`. and cmd for FSC is following
```
C:\Program Files\Microsoft Visual Studio\2022\Preview/Common7/IDE/CommonExtensions/Microsoft/FSharp/Tools/fscAnyCpu.exe -o:obj\Debug\net7.0\ВеселШарп.Бібліотека.dll
-g
...
```

**Comment by kant2002** [comment]
I'm back to customizations temporary in `Directory.Build.props` file, at least for debugging.
Initial values
```
<PropertyGroup>
  <FSharpRoot>C:\d\github\dotnet\fsharp\</FSharpRoot>
  <DotnetFscCompilerPath>$(FSharpRoot)artifacts/bin/fsc/Debug/net7.0/fsc.dll</DotnetFscCompilerPath>
  <Fsc_DotNET_DotnetFscCompilerPath>$(FSharpRoot)artifacts/bin/fsc/Debug/net7.0/fsc.dll</Fsc_DotNET_DotnetFscCompilerPath>
```
This is what I have in the Output if enable Diagnostics mode.
```
1>Property reassignment: $(DotnetFscCompilerPath)="" (previous value: "C:\d\github\dotnet\fsharp\artifacts/bin/fsc/Debug/net7.0/fsc.dll") at C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools\Microsoft.FSharp.Targets (81,9)
```
which is comes from this block
https://github.com/dotnet/fsharp/blob/71b6329fa54e25dd6a1a823484068a7078eff018/src/FSharp.Build/Microsoft.FSharp.Targets#L73-L81

So my overrides cleared by `FSharp_Shim_Present == true` which is set here
https://github.com/dotnet/fsharp/blob/71b6329fa54e25dd6a1a823484068a7078eff018/vsintegration/shims/Microsoft.FSharp.ShimHelpers.props#L10-L15 

Setting `FSharpCompilerPath` trigger initial error which indicates that I have inconsistent parameters passed to `Fsc` MSBuild task.

**Comment by kant2002** [comment]
So far I was able to setup limited building inside VS using followingn content of the `Directory.Build.props`
```xml
<Project>
	<PropertyGroup Condition="true" Label="Shared customizations">
		<FSharpRoot>C:\d\github\dotnet\fsharp\</FSharpRoot>
	</PropertyGroup>
	
  <PropertyGroup Condition="true">
	  <FSharpCompilerPath>$(FSharpRoot)artifacts\bin\fsc\Debug\net472\</FSharpCompilerPath>
	  <FSharpPreferNetFrameworkTools>false</FSharpPreferNetFrameworkTools>
  </PropertyGroup>
	
  <PropertyGroup Condition="true">
	  <NetCoreRoot>C:\Program Files\dotnet\</NetCoreRoot>
	  <NETCoreSdkVersion>7.0.100</NETCoreSdkVersion>
  </PropertyGroup>

	<PropertyGroup Condition="true">
		<Fsc_DotNet_CompilerPath>$(FSharpCompilerPath)</Fsc_DotNet_CompilerPath>
		<Fsc_NetFramework_ToolPath>$(VsInstallRoot)/Common7/IDE/CommonExtensions/Microsoft/FSharp/Tools/</Fsc_NetFramework_ToolPath>

		<Fsc_DotNET_ToolPath>$(NetCoreRoot)</Fsc_DotNET_ToolPath>
		<Fsc_DotNET_ToolExe>dotnet.exe</Fsc_DotNET_ToolExe>
		<Fsc_DotNET__FSharpCoreLibraryPacksFolder>$(Fsc_DotNet_CompilerPath)library-packs</Fsc_DotNET__FSharpCoreLibraryPacksFolder>
		<FscToolPath>$(Fsc_Dotnet_ToolPath)</FscToolPath>
		<FscToolExe>$(Fsc_Dotnet_ToolExe)</FscToolExe>
	</PropertyGroup>
	
	<PropertyGroup Condition="true" Label="CLI customization">
		<DotnetFscCompilerPath>$(FSharpRoot)artifacts/bin/fsc/Debug/net7.0/fsc.dll</DotnetFscCompilerPath>
		<Fsc_DotNET_DotnetFscCompilerPath>$(FSharpRoot)artifacts/bin/fsc/Debug/net7.0/fsc.dll</Fsc_DotNET_DotnetFscCompilerPath>
	</PropertyGroup>
</Project>
```

I have some issues during testing, so let's this process wait a bit. I will check tomorrow, but seems to be I'm close.

**Comment by KevinRansom** [comment]
In order to do a decent implementation, will take a bit more thought.  FSharpCompilationPath is currently a VS only property for F#.  Using it to set the location the sdk targets and props files doesn't work without the vs shims.

So the canonical mechanism is going to have to be this for a while, fortunately it requires no changes.
````
    <FSharp_Shim_Present>false</FSharp_Shim_Present>
    <FscToolPath>/home/kevinr/kevinransom/fsharp/artifacts/bin/fsc/Debug/net7.0</FscToolPath>
    <FscToolExe>fsc.exe</FscToolExe>
    <DotnetFscCompilerPath></DotnetFscCompilerPath>
````

The same settings should work under VS and on the coreclr with windows, macos and linux.  The only way to specify using targets and sources from the repo is with vs installed and using msbuild <FSharpCompilerPath>C:\kevinransom\fsharp\artifacts\bin\fsc\Debug\net7.0</FSharpCompilerPath>.

**Comment by kant2002** [comment]
It seems that short version does not working. 
```
FSC : error FS2020: The assembly 'C:\Program Files\dotnet\sdk\7.0.200\FSharp\fsc.dll' is listed on the command line. Assemblies should be referenced using a command line flag such as '-r'. [C:\d\github\FSharp
.Core.Multilingual\FSharp.Core.Ukrainian\FSharp.Core.Ukrainian.fsproj]
```

**Comment by vzarytovskii** [comment]
The following works for me in both VS and CLI:
```xml
<PropertyGroup>
  <DisableAutoSetFscCompilerPath>false</DisableAutoSetFscCompilerPath>
  <DotnetFscCompilerPath>$(MSBuildThisFileDirectory)../../../artifacts/bin/fsc/Debug/net7.0/fsc.dll</DotnetFscCompilerPath>
  <FSharpPreferNetFrameworkTools>False</FSharpPreferNetFrameworkTools>
  <FSharpPrefer64BitTools>True</FSharpPrefer64BitTools>
</PropertyGroup>
```

**Comment by abonie** [comment]
It seems to be working now. Please try instructions above or include this [file](https://github.com/dotnet/fsharp/blob/main/UseLocalCompiler.Directory.Build.props) in your .fsproj file

**Comment by IS4Code** [comment]
I wanted to use a particular .NET SDK for the F# compiler but I was getting strange errors. After investigating it I found out that `DotnetFscCompilerPath` needs (at least in my VS version) quotes around the value if there are spaces. I guess some problems just never go away. 😄

If needed, this is the full incantation that worked for me:
```xml
  <PropertyGroup>
    <DisableAutoSetFscCompilerPath>true</DisableAutoSetFscCompilerPath>
    <FSharp_Shim_Present>false</FSharp_Shim_Present>
    <FscToolExe>$(ProgramFiles)\dotnet\dotnet.exe</FscToolExe>
    <DotnetFscCompilerPath>"$(ProgramFiles)\dotnet\sdk\9.0.201\FSharp\fsc.dll"</DotnetFscCompilerPath>
    <FSharpPreferNetFrameworkTools>false</FSharpPreferNetFrameworkTools>
    <FSharpPrefer64BitTools>true</FSharpPrefer64BitTools>
  </PropertyGroup>
```

**Comment by vzarytovskii** [comment]
Including this file should work:

https://github.com/dotnet/fsharp/blob/main/UseLocalCompiler.Directory.Build.props
