### ISSUE TITLE
DiagnosticSource breaks vs

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#14413]
PR which introduced diagnosticsource needs to be reverted, as it breaks VS and makes it unusable.

Affected Branch: Main
Affected Build: Version17.5 preview 2 [33129.450.main]
Affected Product Language: 
Below workloads are installed.

.NET desktop development
ASP.NET and web development
Universal Windows Platform development
Visual Studio extension development

Steps to reproduce:
1.install VS17.5 preview 2 [33129.450.main]
2.Launch VS and create a F# console project(.net7.0)

Expected result:
The F# console project can be created and running successful without errors.

Actual Result:
Error FS0193 occurred when running F# project
FSC : error FS0193: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

**Comment by T-Gro** [comment]
Resolved by #14417
