### ISSUE TITLE
Don't show parameter name hints when they coincide with argument names

### ISSUE THREAD

**Issue by psfinaki** [dotnet/fsharp#14447]
Arguably, those rather clutter the editor view than benefit it. 

Compare with C#:
![image](https://user-images.githubusercontent.com/5451366/206188606-c7163a6d-377b-4620-bfa0-cf34d4ce3b6b.png)

I believe even in our codebase that would be quite helpful:

![image](https://user-images.githubusercontent.com/5451366/206189071-b0aa2f0c-e81f-446d-ae7e-0380d569ab69.png)

**Comment by 0101** [comment]
So what should it do in the example with `TypeCheckInfo`? Just show `_sTcConfig =` and `g =`? Should there be a special case when _some_ parameters are named the same _and_ a vertical layout like that is used?

**Comment by baronfel** [comment]
We do a bunch of heuristics like this in FSAC that are inspired by rust-analyzer.  Check out https://github.com/fsharp/FsAutoComplete/pull/932 and https://github.com/fsharp/FsAutoComplete- /pull/935 for the complete set, but we do prefix/postfix matching, length minimums, etc, that include some of what you're talking about here.

**Comment by psfinaki** [comment]
Well I would be probably fine starting dumb, like just looking for a 100% match, so yeah it would be `_sTcConfig = ` and `g = ` in the example above.

But I don't have a strong opinion, just noticed this C# behavior and decided to open a discussion on this.
