### ISSUE TITLE
Targeting .NET6 with .NET7 SDK results in NU1504 and FSharp.Core 7.x

### ISSUE THREAD

**Issue by et1975** [dotnet/fsharp#14441]
Trying to target .NET6 (TargetFramework=net6.0 and explicit PackageReference FSharp.Core=6.0.6) with .NET7 SDK and getting:

> warning NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: FSharp.Core 7.0.0, FSharp.Core 6.0.6.

I don't recall this being a problem in previous SDKs. How do I work around this?

**Repro steps**

[DatatypeChannels](https://github.com/et1975/DatatypeChannels.ASB/tree/yetolmac/net7)

**Expected behavior**

Explicitly referenced version of FSharp.Core should win.

**Actual behavior**

Warning and implicit 7.x version is referenced.

**Known workarounds**

Would like to know.

**Related information**

Provide any related information (optional):

* Operating system: OSX
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .NET SDK 7.0.100
* Editing Tools (e.g. Visual Studio Version, Visual Studio): N/A

**Comment by vzarytovskii** [comment]
If you need to set FSharp.Core explicitly, you'll need to disable implicit one - `<DisableImplicitFSharpCoreReference>True</DisableImplicitFSharpCoreReference>`

**Comment by et1975** [comment]
I'm still wondering if this is the right default, but as long as there's workaround I think we can close this.

**Comment by et1975** [comment]
Reopening because this only seems to move the problem down the line.
[This package](https://www.nuget.org/packages/DatatypeChannels.ASB/1.0.35#dependencies-body-tab) was build with .NET7 SDK, but has .NET6 as the target and FSharp.Core v6 as the reference.
There are no build warnings, but when I try to use this package on .NET6 project I get the errors saying that the reference has FSharp.Core 7 as the dependency.

**Comment by KevinRansom** [comment]
@et1975 - hi, @et1975 , DisableImplicitFSharpCoreReference is the right default and the right fix.  Are you still seeing this problem? and if you can make still it happen would you please build with the /bl switch and attach the microsoft.binlog file, or provide a link to a github repo demonstrating the issue.

This behaviour shouldn't happen, and I can't figure out why it would unless you explicitly referenced something referencing fsharp.core 7, and also deployed the wrong version of FSharp.Core.

Thanks

Kevin

**Comment by et1975** [comment]
@KevinRansom  I believe this revision should give you the repro:
https://github.com/et1975/DatatypeChannels.ASB/commit/1384e738fcaa9868a735799349217eea87ad04c3

**Comment by KevinRansom** [comment]
@et1975 - the built nuget package looks fine, the references are correct and the package reference in the nuspec looks correct.

Do you have an example of using this package that will fail?

Thanks

Kevin
