### ISSUE TITLE
Cannot debug FSI with net core 7 in Visual Studio 2022 17.4.2

### ISSUE THREAD

**Issue by blfuentes** [dotnet/fsharp#14453]
**Repro steps:**
1. Create a F# project with net core 7
2. Enable FSI script debugging and reset interactive session to make settings available
![image](https://user-images.githubusercontent.com/5121778/206382667-089c11e9-2f09-4ffd-86a8-340d5741d18a.png)

3. Create a .fsx file with some code:
4. Set a breakpoint 
5. Select all , right click, debug in interactive
6. Breakpoint shows "No symbols have been loaded for this document"
![image](https://user-images.githubusercontent.com/5121778/206382506-a9bc72eb-7914-42ae-acb2-0df87a45baf7.png)

* Windows 11 22H2 22621.819
* .net core 7.0.100
* Visual Studio Enterprise 2022 17.4.2

**Comment by KevinRansom** [comment]
Looking at it.

**Comment by KevinRansom** [comment]
@blfuentes ,
This is fixed in the VS 17.6 Preview 1.0, however, watch variables do not yet work, so it is not perfect.
![image](https://user-images.githubusercontent.com/5175830/214792721-b60164e5-6e41-44a6-b23c-074b69e4b88d.png)

**Comment by blfuentes** [comment]
Thanks @KevinRansom for the amazing job!
