### ISSUE TITLE
F# Editor signals FS0193 internal error: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#14468]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F-Editor-signals-FS0193-internal-error:/10226950)._

---
[severity:It's more difficult to complete my work]
When editing a fs file, Visual Studio signals the very first letter in the source code (the m in module in my case) with a red '~'.
In the Error List window it shows: FS0193 internal error: Object reference not set to an instance of an object.
In addition, the editor paints just part of the source code.
When compiling the project the building process shows 0 errors and 0 warnings, if executing the application, it works as expected.
The same issue occurs to my workmates.
This issue started a couple versions ago, I think when version 17.4 was release. 
I thougth that upgrading to Net7 could solve the issue, so I targetted my projects to Net7 but it has not solved the problem.

---
#### Mauricio Magni on 10/12/2022, 11:36 AM: 

(private comment, text removed)
#### Feedback Bot on 12/12/2022, 07:08 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by T-Gro** [comment]
The same discussion happening here https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Ffsharp%2Fissues%2F12982%23issuecomment-1350619384&data=05%7C01%7Ctomasgrosup%40microsoft.com%7C5b401cc452e042e9344108daddacce84%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638066031544434061%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KGCEPzJeYbHL7sI6kmwridflzVG4E3HJFTlwO6DhAFg%3D&reserved=0 .
I think that latest preview solves this.

**Comment by mauriciomagni** [comment]
Tested with version 17.5.0 Preview 2.0, dotnet SDK 7.0.101 and the issue remains :)

**Comment by T-Gro** [comment]
Can you share the project which is failing please? Or anythink where it reproduces?

A few tips to narrow it down if you cannot share the project:
- The presense of .fsi files might be relevant
- The language service checks files from top to bottom in project order. So knowing when the first error happens could be binary-searched for
- It might be coming via a referenced project. I.e. an initial project typechecks fine, but any project trying to reference it might experience this issue.

**Comment by mauriciomagni** [comment]
Hello @T-Gro 
I was not able to reproduce the error in a simple solution, sorry.

- There are no .fsi files in the solution
- the definition that, apparently, raises the error is:
   ```fsharp
       let exec: Retrieve.Db.Action =
  ```
  if it is changed by the actual type definition it works as expected:
   ```fsharp
    let exec: Id.T -> Async<Validation<Entity.T voption, BizError.T>> =
 ```
- the type Retrieve.Db.Action is defined in a second project.
- This type of "Type" definition is used a lot in the application, even in the same source file, there are similar definitions that work as expected, as a sample:
  ```fsharp
    let exec: Db.ServiceWithRates =
  ``` 
- my workmates have the same problem, in the same line.
- once replaced the type definition by the actual signature, the error is raised in the next line that uses a predefined type.

**Comment by vzarytovskii** [comment]
@KevinRansom do you know how can we get full stack for said NRE?

**Comment by T-Gro** [comment]
> Hello @T-Gro I was not able to reproduce the error in a simple solution, sorry.
> 
> * There are no .fsi files in the solution
> * the definition that, apparently, raises the error is:
>   ```fsharp
>       let exec: Retrieve.Db.Action =
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   if it is changed by the actual type definition it works as expected:
>   ```fsharp
>    let exec: Id.T -> Async<Validation<Entity.T voption, BizError.T>> =
>   ```
> 
> ```
> - the type Retrieve.Db.Action is defined in a second project.
> - This type of "Type" definition is used a lot in the application, even in the same source file, there are similar definitions that work as expected, as a sample:
> ```fsharp
>    let exec: Db.ServiceWithRates =
> ```
> 
> * my workmates have the same problem, in the same line.
> * once replaced the type definition by the actual signature, the error is raised in the next line that uses a predefined type.
> 
> <img alt="image" width="826" src="https://user-images.githubusercontent.com/20417121/207583975-40af9582-f4fb-43ab-ae6f-6c39be5dc842.png">
> 
> By the way, tested in VSCode & JetBrains Rider, in both cases it works as expected.

Was it by any chance the first usage (topologically) of **any** type from the second project?
I have a feeling that the real error is not in the project where you see errors, but the one which is being referenced and it's types used.

Are you on slack or discord? We can continue privately if it makes sharing easier.

**Comment by mauriciomagni** [comment]
I am in Discord, you can find me as magma

**Comment by T-Gro** [comment]
(issue resolved, was related to double listing of a file within the same .fsproj. Checking how best to report it and if there could be any legit situation of intentionally wanting to compile the same file twice)
