### ISSUE TITLE
IsByRefLike Struct IEnumerator can't be used in a `for` loop

### ISSUE THREAD

**Issue by Smaug123** [dotnet/fsharp#14462]
An `IsByRefLike` and `Struct` enumerator appears not to be usable via `for... in...` syntax, if it explicitly implements the interface `IEnumerator<_>`. This surprised me and I think it might be a bug.

**Repro steps**

Setup:
```fsharp
[<Struct>]
[<IsByRefLike>]
type MapEnumerator<'a, 'b> =
    internal
        {
            F : 'a -> 'b
            Seq : 'a IEnumerator
            mutable CurrentInternal : 'b
        }

    interface IDisposable with
        member this.Dispose () = this.Seq.Dispose ()

    interface IEnumerator<'b> with
        member this.Current = this.CurrentInternal
        member this.get_Current () = box this.CurrentInternal
        member this.Reset () =
            this.Seq.Reset ()

        member this.MoveNext () =
            if this.Seq.MoveNext () then
                this.CurrentInternal <- this.F this.Seq.Current
                true
            else
                false

    member this.GetEnumerator () = this

[<RequireQualifiedAccess>]
module MapEnumerator =
    let make<'a, 'b> (f : 'a -> 'b) (s : 'a IEnumerator) =
        {
            F = f
            Seq = s
            CurrentInternal = Unchecked.defaultof<_>
        }
```

Then e.g.:

```fsharp
let original = seq { 1..100 }
let enum = MapEnumerator.make (fun x -> byte x + 1uy) (original.GetEnumerator ())

for output in enum do
    ()
```

**Expected behavior**

The `for` loop should have compiled.

**Actual behavior**

A build error:

>   [FS1231] The type 'MapEnumerator<int,byte>' is not a valid enumerator type , i.e. does not have a 'MoveNext()' method returning a bool, and a 'Current' property

(This is at best a misleading error message; after all, it does have a `MoveNext()` method returning a bool, and a `Current` property.)

**Known workarounds**

Note that if we simply remove the line `interface IEnumerator<'b> with`, and the `get_Current` member, and unindent the remaining members, then it compiles happily, but then you can't pass `MapEnumerator` generically as an `IEnumerator` (because it's not one).

**Related information**

Provide any related information (optional):

* .NET Runtime kind (.NET Core, .NET Framework, Mono): SDK 7.0.100, FSharp.Core v7

**Comment by T-Gro** [comment]
You should be able to define the Current + MoveNext both explicitely (outside of the interface, this is what the compiler needs) as well as via interface (which you need to pass in generically).

Have you tried that?

**Comment by Smaug123** [comment]
Ah, that does work, thanks! (I don't think I'd ever have guessed that.)

I don't suppose you have any magic tricks for avoiding "A type instantiation involves a byref type" here, when I try and do `enum.GetEnumerator() :> IEnumerator<byte>`?
