### ISSUE TITLE
Use idiomatic/canonical option type annotations in Result module

### ISSUE THREAD

**Issue by cmeeren** [dotnet/fsharp#14465]
`Result.toOption` has return type `Option<'T>`. The idiomatic/canonical notation is `'T option`. The use of `Option<'T>` here means that `Option<'T>` shows up in code/line lens and tooltips all over my codebase when using this function, whereas I would prefer `'T option`.

I haven't checked, but I am guessing that this could apply to other functions in the `Result` module, too.

For completeness, note that the same kind of issue would also apply to functions typed with `List<'T>` instead of `'T list`, and other similar types. (I haven't checked or encountered any, though.)

**Comment by 1eyewonder** [comment]
Are we asking to just update the signature file for result to show something like this or am I misunderstanding the issue? 
![image](https://user-images.githubusercontent.com/38481538/209030924-87d9154b-6cfe-4aa3-bedb-e1c478947a48.png)

**Comment by cmeeren** [comment]
I don't know much about signature files vs. implementation files, but that's the transformations I am thinking of, yes. Except you should use `voption` instead of `ValueOption`, if I recall correctly.

**Comment by cmeeren** [comment]
These replacements could be done in all signature files, by the way, not just those pertaining to the `Result` module. (I don't know of any, but search/replace should make this easy.)

If you agree, I can make a PR for this. A couple of questions:
* Apart from `option`, `voption`, and `list`, which other types have alternative canonical representations? What about `'a array`, which is also `'a []`? The code base should be consistent. I _think_ I recall having seen @dsyme mention array notation in particular someplace, but I have no idea where or even when.
* Is it OK with replacing one type per commit across all signature files?

**Comment by T-Gro** [comment]
I would recommend to limit a PR to a handful of "find/replace" operations and explain those in the PR.
That way, even if the diff is big, it will be easy to review.

Each replacement being a separate commit (with description telling which action caused it) sounds great.

Array usage has been recently unified (@edgarfgp did a lot of work there), I am not sure if there are any things left.

**Comment by edgarfgp** [comment]
Regarding `array` changes. The remaining work is tracked here https://github.com/dotnet/fsharp/issues/14329.
- Update FSharp.Core API reference
- Update docs

**Comment by cmeeren** [comment]
So I would only be changing to postfix lowercase notation for these?
* `option`
* `voption`
* `list`
* `ref`

Apart from `[]`, these are the only ones [listed in the formatting guidelines](https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#for-types-prefer-prefix-syntax-for-generics-foot-with-some-specific-exceptions), so I guess the list is complete.

**Comment by cmeeren** [comment]
Protip - GH [doesn't notify about reactions](https://github.com/isaacs/github/issues/631), so only due diligence ensured I am now aware you agree and that I can proceed 😉
