### ISSUE TITLE
Warning FS3536: "(interface) is normally used as a type constraint in generic code" for extension method on interface in .NET 7 SDK

### ISSUE THREAD

**Issue by loop-evgeny** [dotnet/fsharp#14480]
When compiling an extension method for an interface using .NET SDK 7 you now get a confusing FS3536 warning about type constraints. With .NET SDK 6 there was no such warning. I don't see anything wrong with the code, so as far as I can tell the warning is a bug.

**Repro steps**

Try to compile the following console EXE:

```
type INormalInterface =
    abstract member IntMember: int

module INormalInterfaceExtensions =
    type INormalInterface with
        static member extMethod (a: INormalInterface) =
            ()

printfn "Hello from F#"
```

Project file:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
</Project>
```

**Expected behavior**

Compiles with no warnings, same as with .NET 6 SDK.

**Actual behavior**

```
$ dotnet build
MSBuild version 17.4.0+18d5aef85 for .NET
  Determining projects to restore...
  Restored /home/em/src/FS3536/FS3536.fsproj (in 468 ms).
/home/em/src/FS3536/Program.fs(6,37): warning FS3536: 'INormalInterface' is normally used as a type constraint in generic code, e.g. "'T when ISomeInterface<'T>" or "let f (x: #ISomeInterface<_>)". See https://aka.ms/fsharp-iwsams for guidance. You can disable this warning by using '#nowarn "3536"' or '--nowarn:3536'. [/home/em/src/FS3536/FS3536.fsproj]
```

**Known workarounds**

Use .NET 6 SDK by creating a global.json file or suppress that specific warning like the message says.

* Operating system: Ubuntu 18.04
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .NET 6.0.12
* .NET SDK: 7.0.101

**Comment by vzarytovskii** [comment]
It is a consequence of supporting static abstracts in interfaces.
We should adjust conditions when we produce this warning.

**Comment by loop-evgeny** [comment]
Still happens with .NET SDK 7.0.102. Was the fix supposed to be released in that version?

**Comment by vzarytovskii** [comment]
> Still happens with .NET SDK 7.0.102. Was the fix supposed to be released in that version?

No, i think it was only inserted in 7.0.200

**Comment by loop-evgeny** [comment]
Oh, OK. When is that expected to be released? I don't really understand how .NET SDK build numbers work.

**Comment by vzarytovskii** [comment]
> Oh, OK. When is that expected to be released? I don't really understand how .NET SDK build numbers work.

I, unfortunately, am not sure when the release is scheduled on exactly.
6.0.200 was released in February last year.

**Comment by loop-evgeny** [comment]
OK, so basically it can take another year or so? So we'd better work around this by suppressing the warning and not wait for the fix?

**Comment by vzarytovskii** [comment]
> OK, so basically it can take another year or so? So we'd better work around this by suppressing the warning and not wait for the fix?

No, sorry, not what I meant.
6.0.200 was released around February last year, so I would expect 7.0.200 to be released around same time this year. I just don't know exact schedule.
