### ISSUE TITLE
fsiSession.Run() is crashing the hosting app.

### ISSUE THREAD

**Issue by goswinr** [dotnet/fsharp#14486]
I am hosting FCS in another app. (Rhino 3D)
When I create an FSI session and call Run() it crashes the App. I could not catch an exception.
Are these comments here explaining why?  The hosting app has already other active threads:
https://github.com/dotnet/fsharp/blob/main/src/Compiler/Interactive/fsi.fs#L3759

```fsharp
member x.Run() =
        progress <- condition "FSHARP_INTERACTIVE_PROGRESS"

        // Explanation: When Run is called we do a bunch of processing. For fsi.exe
        // and fsiAnyCpu.exe there are no other active threads at this point, so we can assume this is the
        // unique compilation thread.  For other users of FsiEvaluationSession it is reasonable to assume that
        // the object is not accessed concurrently during startup preparation.
        //
        // We later switch to doing interaction-by-interaction processing on the "event loop" thread

        ...
```

Skipping this call to Run() and just using the session for evaluations seems to be mostly OK. 
But I have some other not so critical issues like line numbers missing in exceptions despite using `--multiemit`. 
see  https://github.com/dotnet/fsharp/discussions/13293#discussioncomment-2949022

**What am I missing in my fsi sessions if I don't call the Run() method at the beginning ?**

**Comment by goswinr** [comment]
My current conclusion is that the fsiSession.Run() method does not need to be called when using FSI in the same process as the UI.
Is that correct ? Then please close this issue.

I made a quick tests app with WPF. Run() crashes this app too: 

```fsharp
namespace TestRunFsiSession

open System
open System.Windows
open System.Windows.Controls
open System.Threading
open System.Windows.Threading

open FSharp.Compiler.Interactive.Shell

module Win =    
    
    let code =
        """
for i = 0 to 100 do  
    System.Threading.Thread.Sleep 50
    printfn $"sync Sleeping {i}"
55
    
    """

    type LogWriter(log:Controls.Label) =
        inherit IO.TextWriter()    
        override _.Encoding = Text.Encoding.Default 
        override _.Write (s:string)  = 
            Windows.Application.Current.Dispatcher.Invoke( fun () -> log.Content <- string log.Content + s )
             
        override _.WriteLine (s:string) = 
            Windows.Application.Current.Dispatcher.Invoke( fun () ->log.Content <- string log.Content + s + "\r\n")  
        
        override _.WriteLine ()= 
            Windows.Application.Current.Dispatcher.Invoke( fun () ->log.Content <- string log.Content + "\r\n")
            
    let cts = new Threading.CancellationTokenSource()

    let fsi(log:LogWriter) =        
        async{
        let inn = new IO.StringReader("")            
        let config = FsiEvaluationSession.GetDefaultConfiguration()     
        
        log.WriteLine "creating session .."
        let session = FsiEvaluationSession.Create(config, [| "" |], inn, log, log)
        
        log.WriteLine "session.Run() .."
        session.Run() // this call craches the app

        log.WriteLine "evaluating .."
        session.EvalInteraction(code, cts.Token)
        log.WriteLine "done!"
        } |> Async.Start
            

    [<EntryPoint>]
    [<STAThread>]
    let wpf args = 
        let log = Controls.Label(Content = "FSI OUT:\r\n")
        let logwriter = new LogWriter(log)
        let button1 = Button(Content= "Run Fsi")
        button1.Click.Add ( fun _ -> fsi(logwriter))
        
        let button2 = Button(Content= "Cancel Fsi")
        button2.Click.Add ( fun _ -> cts.Cancel())
        let panel = StackPanel()
        panel.Children.Add button1 |> ignore        
        panel.Children.Add button2 |> ignore        
        panel.Children.Add log     |> ignore 
        Application().Run(Window(Content=panel))  
```

**Comment by T-Gro** [comment]
@KevinRansom : Do you mind having a look please?
This is a combination of FSI and WPF

**Comment by goswinr** [comment]
Yes, this is a simplified example. I am actually hosting FCS in process in an Avalonedit Editor (WPF). So far I am not using Run(). It works mostly OK. What am I missing if I don’t call Run?

**Comment by KevinRansom** [comment]
@goswinr 
If your app is already pumping messages 'Application.Run() starts that I believe', then yes you probably don't need fsi.Run().

Are you creating a desktop or a dotnet WPF App.

Just for background, we haven't done any work to enable FSI and dotnet WPF or WinForms projects to work from fcs, although back in the day some work was done to ensure that fsi.exe does not block message pumping.  So, from a particularly narrow view of the world the scenarios are currently unsupported.  However, they look useful and interesting, I'm sure we can try to help you work through any blockers that may exist.

Please supply the complete project file for your sample, and I will take a look over the holidays if I get a chance.

**Comment by goswinr** [comment]
@KevinRansom 

> "we haven't done any work to enable FSI and dotnet WPF or WinForms"

For now I assume I don't need to call `fsiSession.Run()` .
Do you have an idea why it crashes the WPF app?
It actually works well without since a few years now. 
I started with the Tsunami Editor as seen [here](https://www.youtube.com/watch?v=ZY-bvZZZZnE), now I am using [AvalonEdit](http://avalonedit.net/).
I am not using `fsi.exe` just the FCS nuget.
Soon I want to make my Scripting Editor public too.  
>"Are you creating a desktop or a dotnet WPF App."

For hosting in [Rhino3D ](https://www.rhino3d.com/) I use net48, for standalone scripting I use net7.
>"I'm sure we can try to help you work through any blockers that may exist."

Thanks, that's very kind of you. Only when watching the source of fsharp I see how much work you are actually putting into it.
 The biggest blocker was https://github.com/dotnet/fsharp/issues/11770 , but now I have a workaround.

- I am still [missing line numbers](https://github.com/dotnet/fsharp/issues/13290) on exceptions when hosted 
- can't get `__SOURCE_DIRECTORY__` to work yet. 
- and[ can't cancel on net7](https://github.com/dotnet/fsharp/issues/14489)

but I will try again and if unsuccessful create separate issues and samples for those.
![image](https://user-images.githubusercontent.com/884885/208882484-8b8bc508-5d2b-4ff6-81e5-633bb46cb6b9.png)
