### ISSUE TITLE
Are you interested in this AST visitor?

### ISSUE THREAD

**Issue by cmeeren** [dotnet/fsharp#14519]
I have implemented a full untyped AST traversal in [Flinter](https://github.com/cmeeren/Flinter). I originally asked if the FSharp.Analyzers.SDK maintainers were interested in accepting it in a PR, but [they suggested](https://github.com/ionide/FSharp.Analyzers.SDK/issues/44#issuecomment-1367019758) asking here instead, for integration into FCS.

The AST traversal/visitor (permalink to latest version as of writing):

https://github.com/cmeeren/Flinter/blob/e08899d4903f2d75c431d37eb71b27d157bc9e70/src/Flinter/UntypedAst.fs

Example usage (permalink to latest version as of writing):

https://github.com/cmeeren/Flinter/blob/e08899d4903f2d75c431d37eb71b27d157bc9e70/src/Flinter/Analyzers/FLN00_Test/FLN0000_FunctionParameterNaming.fs

I'm happy with it. I find this way of using visitors flexible. For example, a more complicated rule that checks for something in top-level functions but does not recurse into nested functions could either check for the presence of an outer function in the path, or (and this may be needed for even more complex rules) it could not call `base.Visit...` when it encounters a top-level function but instead create a new visitor for the current (top-level) function that performs the desired work but does not enter into (inner) functions, and call `Visit...` on that instead.

Note that I have not gotten around to a typed AST traversal. I will do that at some point, but no promises when. (I haven't looked at the typed AST at all, actually, so I don't know how complicated it will be compared to the untyped one.)

Also, the implementation would need a careful review, with specific focus on the TODOs still left in the code, which are questions I haven't found answers to. FCS isn't exactly well documented for newcomers 😅

Note that the example usage I linked to above is currently the _only_ usage of the visitor, so the design hasn't been "battle-tested".

Also note that it targets FCS 41 (because that's what FSharp.Analyzers.SDK does), so some edits would be needed for whatever is in this repo (an FCS 42 version is in the git history of that file, so it's hopefully not much work).

**Comment by cmeeren** [comment]
Note that this could of course be seen in light of the [analyzers RFC](https://github.com/fsharp/fslang-design/blob/main/tooling/FST-1033-analyzers.md).

**Comment by T-Gro** [comment]
This can be useful for consumers for untyped AST and simplify processing for common tasks.
At the same time, I think it is too hard to commit stability of this public API.

This is where a visitor is most useful:
```
If the interface you want implemented is rather static and doesn't change a lot.
If all types are known in advance, i.e. at design time all objects must be known.
```

Unfortunately, I do not see how this could be guaranteed over the course of several major versions for instance.
Easily yes as an copy-paste-able "UntypedFSharp7Visitor" snippet,  but hard to maintain it like a stable and binary-compatible ("consumers do not have to re-build") API.

**Comment by baronfel** [comment]
I don't think binary compat should necessarily be a blocker here - we already provide a very useful typed walker for the untyped tree, and any changes to the untyped AST required updates to that structure. If anything, this library is the ideal place for such a walker to ensure consistency as changes are made.

**Comment by T-Gro** [comment]
I can only imagine insurance as in 'ensuring that the walker itself is compiling'.
But not that consumer code is still compiling, or even worse, that consumer code which compiles fine is behaving semantically the same as before.

Ofc I do agree on the usefulness aspect, but it would be proper to mark such API [<Experimental>] for all uses.

**Comment by cmeeren** [comment]
I agree with @baronfel that binary compat should not be a blocker. It is just as binary compatible as the rest of the tree definitions in FSC, i.e., not much, which doesn't prevent FSC making binary breaking changes frequently. When any users of this visitor update their version of FSC, they would need to make sure to update their code to keep their desired semantics intact, just like they would have to do today if implementing a visitor themselves and updating FSC.

**Comment by kentcb** [comment]
Arrived here with same problem. Thanks for the code. Am I right in saying this still isn't supported via FCS? I can't find anything to suggest it is, but at the same time kinda surprised that it's this involved doing simple things. Does it exist as a standalone NuGet I can consume instead? I'm not using this in the context of analyzers, just some scripts I need in the short term to do analysis on a complex F# code base.
