### ISSUE TITLE
Possible bug in ServiceParseTreeWalk.fs

### ISSUE THREAD

**Issue by cmeeren** [dotnet/fsharp#14513]
While experimenting with AST traversal for a new linter and looking through existing traversal code in FCS, I came across this line:

https://github.com/dotnet/fsharp/blob/812bf3dc3a6c17dae01976629733d9c467852849/src/Compiler/Service/ServiceParseTreeWalk.fs#L597

Note that it ignores the first parameter, and binds the second parameter to `isRecursive`. However, in the definition of `LetOrUse`, the _first_ parameter is named `isRecursive`. The second one is `isUse`.

https://github.com/dotnet/fsharp/blob/812bf3dc3a6c17dae01976629733d9c467852849/src/Compiler/SyntaxTree/SyntaxTree.fs#L577

This indicates a bug somewhere. I am incluned to think it's in `ServiceParseTreeWalk.fs`.

**Comment by T-Gro** [comment]
Thanks for catching it, this is indeed a bug.
