### ISSUE TITLE
[FSI] FSI can't work with JWT.net package

### ISSUE THREAD

**Issue by OnurGumus** [dotnet/fsharp#14529]
Please provide a succinct description of the issue.

**Repro steps**

The following code fails with FSI with No overloads match for method 'RS256Algorithm'.
Known type of argument: RSA, however compiles fine in regular project:
```fsharp
#r "System.Security.Cryptography"
#r "nuget:JWT"
let rsaKey = System.Security.Cryptography.RSA.Create();
let claims =  JWT.Algorithms.RS256Algorithm(rsaKey)
printf "%A" claims
```

A project compilation with same code just works fine:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JWT" Version="10.0.0-beta9" />
    <Compile Include="Program.fs" />
  </ItemGroup>
</Project>
```
Progam.fs
```fsharp
let rsaKey = System.Security.Cryptography.RSA.Create();
let claims =  JWT.Algorithms.RS256Algorithm(rsaKey)
printf "%A" claims
```

**Expected behavior**

I expect fsi to load fine

**Actual behavior**
Fails with below error
```
error FS0041: No overloads match for method 'RS256Algorithm'.

Known type of argument: RSA

Available overloads:
 - JWT.Algorithms.RS256Algorithm(cert: X509Certificates.X509Certificate2) : JWT.Algorithms.RS256Algorithm // Argument 'cert' doesn't match
 - JWT.Algorithms.RS256Algorithm(publicKey: RSA) : JWT.Algorithms.RS256Algorithm // Argument 'publicKey' doesn't match
Provide a description of the actual behaviour observed. 
```
**Known workarounds**

No workaround

**Related information**

Has to do with JWT package. If I use RSA with another package then it works fine.

* Operating system: MacOS 13.1
* .NET Runtime kind: .NET SDK 7.0.100
* Editing Tools: VsCode

**Comment by T-Gro** [comment]
This one https://github.com/dotnet/fsharp/issues/14024

**Comment by OnurGumus** [comment]
Not sure, well the thing is System.Security.Cryptography.dll is somewhat special. It doesn't come with a nuget package but rather magical part of .net framework which abstracts some native imp.

Having that said, I have successfully used it in FSI via another lib https://github.com/dvsekhvalnov/jose-jwt

What I suspect, JWT.NET has somethings triggering this problem but couldn't find anything and I really tried hard.

**Comment by KevinRansom** [comment]
This has been fixed now:

![image](https://github.com/dotnet/fsharp/assets/5175830/61ace62b-658f-4db6-941e-757e178f62f7)
