### ISSUE TITLE
In F# editor, replace delimiters from parentheses to begin...end and vice versa

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#14545]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/In-F-editor-replace-delimiters-from-pa/10138403)._

---
Add functionality to change blocks delimited by brackets with blocks delimited by begin...end and vice versa.
Often you start writing an anonymous function in round brackets because you think you can do it in one line but then you realize that you need more lines, and a block of code of several lines is more readable if it is delimited by begin...end rather than parentheses.

![B88cb358534914838b22824456157e34c637977264289079952_be](https://user-images.githubusercontent.com/1260985/210808376-d40f7221-31fc-4542-a080-2f59a46fbdb8.gif)

**Comment by vzarytovskii** [comment]
I have moved it from the developer community feedback, however, I think `begin .. end` blocks are not used as much, would like to hear any feedback.

**Comment by ly29** [comment]
I don't think anyone uses verbose style expect end for empty things.

**Comment by 0101** [comment]
Closing because `begin .. end` is not idiomatic syntax.
