### ISSUE TITLE
Sort open declarations for F# files in Quick Actions and Refactorings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#14543]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Sort-open-declarations-for-F-files-in-Q/10213752)._

---
There's an option to remove unused open declarations but unlike with C# there's no automatic sorting.

---
#### Feedback Bot on 11/28/2022, 08:23 AM: 

(private comment, text removed)

**Comment by baronfel** [comment]
Sorting using is made more difficult for F# because of ordering - I've seen cases where the order of opens mattered because of shadowing, for example. I personally regard most of those situations as problems on the library author's part, but they do happen.

**Comment by T-Gro** [comment]
I recommend closing.

F# Style guide explicitly recommends topological sorting, which also behaves as a good default for what @baronfel  wrote above (shadowing).

https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/conventions#sort-open-statements-topologically 
![image](https://user-images.githubusercontent.com/46543583/210972761-a3d9ca26-f9d5-4519-a72f-35936d2dcbad.png)

**Comment by vzarytovskii** [comment]
Closing as per above comments
