### ISSUE TITLE
Update FsLexYacc

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#14583]
Hello @vzarytovskii and @KevinRansom, I would like to update the `fslex` and `fsyacc` build tools.
The main reason for updating these tools is that the fix of https://github.com/fsprojects/FsLexYacc/pull/154 recently got published to NuGet over at https://github.com/fsprojects/FsLexYacc.

From what I understood the compiler takes a source dependency on `FsLexYacc` instead of using the NuGet package. What would need to be done to update this?

**Comment by vzarytovskii** [comment]
I guess just updating it in the repo (copying new things over) is sufficient enough
