### ISSUE TITLE
FSharp.Core version 7.0.0 has multiple content hashes

### ISSUE THREAD

**Issue by petteripoyhtari** [dotnet/fsharp#14618]
We have now currently this same issue with the 7.0.0 package and we have trouble to pass our Azure ci/cd pipeline builds through. Some machines will get the same hash and other won't.

"Package content hash validation failed for FSharp.Core.7.0.0. The package is different than the last restore."

Could you change the package version number when you change the package contents / code, please.

![fsharp-7-hash-fail](https://user-images.githubusercontent.com/81987998/212839873-ec0a11a7-daf9-4df2-ad03-376826f3d010.png)

Same issue has apparently been before: https://github.com/NuGet/Home/issues/11610

_Originally posted by @petteripoyhtari in https://github.com/dotnet/fsharp/issues/13678#issuecomment-1384972108_

**Comment by cmeeren** [comment]
As a "workaround" (I do this permanently), could you try adding `<DisableImplicitLibraryPacksFolder>true</DisableImplicitLibraryPacksFolder>` to your project files (or to a `Directory.Build.props`)?

**Comment by vzarytovskii** [comment]
This is due to SDK insertions and package publishing are two different events and can be desynchronized.

Not entirely sure how should we deal with it.

@KevinRansom thoughts?

**Comment by cmeeren** [comment]
If it's rebuilt without changes, and the hash is different, doesn't that mean you are not using deterministic builds? If so, have you checked out e.g. [DotNet.ReproducibleBuilds](https://github.com/dotnet/reproducible-builds)?

**Comment by vzarytovskii** [comment]
> If it's rebuilt without changes, and the hash is different, doesn't that mean you are not using deterministic builds? If so, have you checked out e.g. [DotNet.ReproducibleBuilds](https://github.com/dotnet/reproducible-builds)?

It's not about determinism, it's about different packages end up published to nuget and to SDK
