### ISSUE TITLE
No FS0025 'match incomplete' error when covering all inner enum fields

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#14621]
```fsharp
type E =
    | FieldA = 1
    | FieldB = 2

type U =
    | CaseA
    | CaseB of E

match CaseA with
| CaseB E.FieldA -> ()
| CaseB E.FieldB -> ()
```

Expected: a warning about the outer `U` value:
```
FS0025: Incomplete pattern matches on this expression.
  For example, the value 'CaseA' may indicate a case not covered by the pattern(s).
```

Actual: the warning only covers the inner enum `E`:
```
warning FS0104: Enums may take values outside known cases.
  For example, the value 'CaseB (enum<E> (0))' may indicate a case not covered by the pattern(s).
```

It looks like having patterns for all enum fields prevents FCS from reporting a warning about other values, as removing the second match branch makes FCS produce a warning with expected number:
```
warning FS0025: Incomplete pattern matches on this expression.
  For example, the value 'CaseB (E.FieldB)' may indicate a case not covered by the pattern(s).
```

**Comment by charlesroddie** [comment]
Is this issue a request for warning precedence? Where the problem is that it's reporting an unimportant warning over an important warning?

**Comment by vzarytovskii** [comment]
I guess compiler takes Unchecked.defaultof<E> (which is 0) into account when it checks for exhaustiveness
