### ISSUE TITLE
Using NO_TYPEPROVIDERS in FSharp.Compiler.Service.fsproj

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#14638]
Hello,

I noticed if I add `<OtherFlags>$(OtherFlags) --define:NO_TYPEPROVIDERS</OtherFlags>` in `FSharp.Compiler.Service.fsproj` the project no longer builds.

![image](https://user-images.githubusercontent.com/2621499/213861973-b8448909-ab28-42f6-a400-e624f7984e06.png)

Should `NO_TYPEPROVIDERS` still be a thing then?

**Comment by vzarytovskii** [comment]
Yeah, we should fix it

**Comment by nojaf** [comment]
Could you tell me when this is being used? This has probably been broken for some time now.

**Comment by vzarytovskii** [comment]
> Could you tell me when this is being used? This has probably been broken for some time now.

TL;DR is that they're useful for fable

More here: https://github.com/dotnet/fsharp/issues/13491#issuecomment-1180774752

**Comment by vzarytovskii** [comment]
Update - i have the fix ready, will submit pr today

**Comment by KevinRansom** [comment]
Last time I tried to remove it @dsyme wanted it kept in.  So, yes NO_TYPEPROVIDERS should work.  I suppose we should add a build step to verify it as well.

Kevin
