### ISSUE TITLE
Compiler freezes during build and never finishes

### ISSUE THREAD

**Issue by Confuset** [dotnet/fsharp#14651]
Hi everyone,

when trying to build a [Fabulous.XamarinForms.Templates](https://github.com/fabulous-dev/Fabulous.XamarinForms) the compiler freezes.
This happens with Visual Studio 2022 and with msbuild via the commandline.

**Repro steps**

[Requirements from Fabulous.XamarinForms.Templates](https://docs.fabulous.dev/v2/getting-started/#requirements)

Provide the steps required to reproduce the problem:

1. dotnet new install Fabulous.XamarinForms.Templates
2. dotnet new fabulous-xf-vswin -n SplitApp
3. cd SplitApp
4. msbuild

**Expected behavior**

The compiler eventually finishes.

**Actual behavior**

The compiler never finishes. (Had it running for 6.30 hours..)

**Known workarounds**

Downgrade compiler from v12.0.5 to v12.0.4.

**Related information**

I already did some research at this Fabulous.XamarinForms ticket https://github.com/fabulous-dev/Fabulous.XamarinForms/issues/20
I even tried `git bisect` to further pinpoint the issue, but I can not really compile the project with my own compiler due to missing build targets:
```
"c:\Users\xxx\source\repos\SplitApp\SplitApp.sln" (default target) (1) ->
"c:\Users\xxx\source\repos\SplitApp\SplitApp.Android\SplitApp.Android.fsproj" (default target) (4) ->
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VisualStudio\v17.0\FSharp\Microsoft.FSharp
.Targets(4,3): error MSB4019: The imported project "C:\Users\xxx\source\repos\fsharp\artifacts\bin\fscAny\Debug\net47
2\Microsoft.FSharp.targets" was not found. Confirm that the expression in the Import declaration "C:\Users\xxx\source
\repos\fsharp\artifacts\bin\fscAny\Debug\net472\\Microsoft.FSharp.targets" is correct, and that the file exists on disk
. [c:\Users\xxx\source\repos\SplitApp\SplitApp.Android\SplitApp.Android.fsproj]
```

* Operating system: W10
* .NET Runtime kind: MonoAndroid/Xamarin
* Editing Tools: Visual Studio 2022

**Comment by vzarytovskii** [comment]
Repro steps don't work for me:
```
C:\Users\vlza\code\SplitApp\SplitApp.iOS\SplitApp.iOS.fsproj : error  : The imported project "C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Xamarin\iOS\Xamarin.iOS.FSharp.targets" was not found. Also, tried to find "Xamarin\iOS\Xamarin.iOS.FSharp.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (x86)\MSBuild" . These search paths are defined in "C:\Users\vlza\AppData\Local\Microsoft\VisualStudio\17.0_382f6079\devenv.exe.config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.  C:\Users\vlza\code\SplitApp\SplitApp.iOS\SplitApp.iOS.fsproj

C:\Users\vlza\code\SplitApp\SplitApp.Android\SplitApp.Android.fsproj : error  : The imported project "C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Xamarin\Android\Xamarin.Android.FSharp.targets" was not found. Also, tried to find "Xamarin\Android\Xamarin.Android.FSharp.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (x86)\MSBuild" . These search paths are defined in "C:\Users\vlza\AppData\Local\Microsoft\VisualStudio\17.0_382f6079\devenv.exe.config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.  C:\Users\vlza\code\SplitApp\SplitApp.Android\SplitApp.Android.fsproj
```

**Comment by edgarfgp** [comment]
> I presume it's a duplicate of #14336 and was fixed in #14497 (which was inserted in 17.5 and 17.6), but I can't yet confirm it, since repro steps don't work for me:
> 
> ```
> C:\Users\vlza\code\SplitApp\SplitApp.iOS\SplitApp.iOS.fsproj : error  : The imported project "C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Xamarin\iOS\Xamarin.iOS.FSharp.targets" was not found. Also, tried to find "Xamarin\iOS\Xamarin.iOS.FSharp.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (x86)\MSBuild" . These search paths are defined in "C:\Users\vlza\AppData\Local\Microsoft\VisualStudio\17.0_382f6079\devenv.exe.config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.  C:\Users\vlza\code\SplitApp\SplitApp.iOS\SplitApp.iOS.fsproj
> 
> C:\Users\vlza\code\SplitApp\SplitApp.Android\SplitApp.Android.fsproj : error  : The imported project "C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Xamarin\Android\Xamarin.Android.FSharp.targets" was not found. Also, tried to find "Xamarin\Android\Xamarin.Android.FSharp.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (x86)\MSBuild" . These search paths are defined in "C:\Users\vlza\AppData\Local\Microsoft\VisualStudio\17.0_382f6079\devenv.exe.config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.  C:\Users\vlza\code\SplitApp\SplitApp.Android\SplitApp.Android.fsproj
> ```
> 
> I guess I'm missing some components in my VS install.


Yes you are those component to be able to build this

**Comment by Confuset** [comment]
Yes. You need those components mention in the docs of Fabulous.XamarinForms.Template: https://docs.fabulous.dev/v2/getting-started/#requirements

I updated the reprosteps to point to the docs.

**Comment by vzarytovskii** [comment]
@auduchinok fyi - the repro for the IL attribute cluster reading issue.

**Comment by vzarytovskii** [comment]
I am going to close it as duplicate. Please let me know if you think it should remain opened.

**Comment by auduchinok** [comment]
> @auduchinok fyi - the repro for the IL attribute cluster reading issue.

Thanks a lot for letting me know about it!

**Comment by Confuset** [comment]
Brilliant. Thanks for the quick help on this.
Tried VS2022 17.5.0 Preview 4.0 which also fixes the issue for me :-)
