### ISSUE TITLE
Running `dotnet tool run fantomas -r .` on `main` modifies lots of files in `vsintegration\tests\FSharp.Editor.Tests`

### ISSUE THREAD

**Issue by safesparrow** [dotnet/fsharp#14667]
**Repro steps**

Run this PowerShell script:
```
git init
git remote add origin https://github.com/dotnet/fsharp.git
git fetch
git checkout origin/main
dotnet tool restore
dotnet tool run fantomas -r
git status
```

**Expected behavior**
`git status` should show no files changed.

**Actual behavior**
`git status` shows lots of files changed:
```
HEAD detached at origin/main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   vsintegration/tests/FSharp.Editor.Tests/BraceMatchingServiceTests.fs
        modified:   vsintegration/tests/FSharp.Editor.Tests/BreakpointResolutionServiceTests.fs
        modified:   vsintegration/tests/FSharp.Editor.Tests/CompletionProviderTests.fs
        modified:   vsintegration/tests/FSharp.Editor.Tests/DocumentDiagnosticAnalyzerTests.fs
        modified:   vsintegration/tests/FSharp.Editor.Tests/DocumentHighlightsServiceTests.fs
        modified:   vsintegration/tests/FSharp.Editor.Tests/EditorFormattingServiceTests.fs
        modified:   vsintegration/tests/FSharp.Editor.Tests/FsxCompletionProviderTests.fs
        modified:   vsintegration/tests/FSharp.Editor.Tests/GoToDefinitionServiceTests.fs
        modified:   vsintegration/tests/FSharp.Editor.Tests/HelpContextServiceTests.fs
        modified:   vsintegration/tests/FSharp.Editor.Tests/Helpers/RoslynHelpers.fs
        modified:   vsintegration/tests/FSharp.Editor.Tests/Hints/HintTestFramework.fs
        modified:   vsintegration/tests/FSharp.Editor.Tests/Hints/InlineParameterNameHintTests.fs
        modified:   vsintegration/tests/FSharp.Editor.Tests/Hints/InlineTypeHintTests.fs
        modified:   vsintegration/tests/FSharp.Editor.Tests/IndentationServiceTests.fs
        modified:   vsintegration/tests/FSharp.Editor.Tests/LanguageDebugInfoServiceTests.fs
        modified:   vsintegration/tests/FSharp.Editor.Tests/QuickInfoProviderTests.fs
        modified:   vsintegration/tests/FSharp.Editor.Tests/QuickInfoTests.fs
        modified:   vsintegration/tests/FSharp.Editor.Tests/SemanticClassificationServiceTests.fs
        modified:   vsintegration/tests/FSharp.Editor.Tests/SignatureHelpProviderTests.fs
        modified:   vsintegration/tests/FSharp.Editor.Tests/SyntacticColorizationServiceTests.fs
```

* Operating system - Windows 11
* NET SDK - 7.0.102

**Comment by nojaf** [comment]
What you see actually makes sense to me giving the `!vsintegration/tests/FSharp.Editor.Tests` entry in the `.fantomasignore` file. The `!` indicates that the files under `vsintegration/tests/FSharp.Editor.Tests` should not be ignored.

@psfinaki seems to be one of the main contributors to that folder. Perhaps he wasn't aware this folder is not ignored.

The other reason for this is that the azure-pipelines file is checking the code with `dotnet fantomas src -r --check`. It is only checking the `src` folder if it is formatted.

**Comment by psfinaki** [comment]
Hmm interesting - I mean I didn't fantomas-ignore it on purpose so that, well, we have Fantomas working for that. I will try to reproduce the initial issue, but generally, since this is a relatively fresh project (in its current shape), we want Fantomas there.

**Comment by nojaf** [comment]
@psfinaki I wouldn't overly look into it, to be honest.
In https://github.com/dotnet/fsharp/commit/116050994cf6cb572e28eff70ce40a55e8973317#diff-eefdab292c879e70487bb14214f59ed01c3bb4335beef841236cb03598b945bb the `.fantomasignore` file got changed but the `--check` was not extended.

And the documentation in [DEVGUIDE.md](https://github.com/dotnet/fsharp/blob/main/DEVGUIDE.md#automated-source-code-formatting) only mentions formatting `src`, so I believe that explains all of it.
