### ISSUE TITLE
IsReadOnlyAttribute is emitted even if coming from non-runtime reference

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#14700]
Ok, it seems is is a separate bug, since System.Collections.Immutable inludes its own `IsReadOnlyAttribute`:
![image](https://user-images.githubusercontent.com/1260985/216965274-c07e90f9-146c-49e8-bf11-d684d2023068.png)
And we are checking it only by namespace, we decide to emit it but not generate attribute. 

I will revert generating it altogether, until proper fix is in place (with codegen).

_Originally posted by @vzarytovskii in https://github.com/dotnet/fsharp/issues/14276#issuecomment-1418964478_

**Comment by SamuelBerger** [comment]
@vzarytovskii Will this be in the patch release of 2023-02-14 (even when it is not back ported to 17.5 #14704)?

**Comment by vzarytovskii** [comment]
> @vzarytovskii Will this be in the patch release of 2023-02-14 (even when it is not back ported to 17.5 #14704)?

Unlikely, I think by the time I've made the change, it was frozen
