### ISSUE TITLE
Intermittent 'Server Prompt' output from FSI

### ISSUE THREAD

**Issue by MaxWilsonMS** [dotnet/fsharp#14717]
**Description**

About 1 time in 20, FSI appends the string "SERVER-PROMPT>" to the output for unclear reasons.

Version: Microsoft (R) F# Interactive version 12.5.0.0 for F# 7.0 from inside Visual Studio 2022 17.5.0 Preview 4.

**Repro steps**

1. Define a debug function
```F#
type MonsterId = MonsterId of string
let debug () =
    let monsters = [[MonsterId "Vampire"]]
    monsters, "The town priest turns out to be a vampire"
debug()
```

2. Run the debug() line a bunch of times via Send To Interactive.

**EXPECTED:** It will always print 
```
    val it: MonsterId list list * string =
    ([[MonsterId "Vampire"]], "The town priest turns out to be a vampire")
```
**ACTUAL:** Sometimes it will print
```
    val it: MonsterId list list * string =
    ([[MonsterId "Vampire"]], "The town priest turns out to be a vampire")

    SERVER-PROMPT>
```

**Known workarounds**

Just ignore the issue? I'm not sure what the actual impact is beyond increasing friction during exploratory programming.

**Provide any related information (optional):**

The specific text seems to be important. I have not been able to reliably repro this issue without including the word "vampire" in the output.

* Version: Microsoft (R) F# Interactive version 12.5.0.0 for F# 7.0 from inside Visual Studio

* Operating system Windows

![image](https://user-images.githubusercontent.com/12056927/217597204-5d3981ba-f521-4cbd-84c0-4c6d6b068137.png)

**Comment by MaxWilsonMS** [comment]
I did get it to repro once with

```
val it: string * MonsterId list list =
  ("Goblin wolf riders attack the town",
   [[MonsterId "Goblin"; MonsterId "Goblin"; MonsterId "Goblin";
     MonsterId "Goblin"];
    [MonsterId "Wolf"; MonsterId "Wolf"; MonsterId "Wolf"]])

SERVER-PROMPT>
```

**Comment by vzarytovskii** [comment]
@KevinRansom i believe it was fixed, right? Caused by desync between VS and inserted SDK?

**Comment by MaxWilsonMS** [comment]
I guess the new issue is not that intermittent. I will close this issue as fixed and open a new one.
