### ISSUE TITLE
VisualFSharp.sln can't be built using `dotnet build` after using build.cmd

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#14725]
Steps to reproduce:

* clone the repo
* execute build.cmd
* try to build VisualFSharp.sln using `dotnet build` or Rider

Expected: build succeeds
Actual: build fails with errors like this:

```
C:\Program Files\dotnet\sdk\7.0.102\Microsoft.Common.CurrentVersion.targets(3312,5):
  error MSB3823: Non-string resources require the property GenerateResourceUsePreserializedResources to be set to true.
  [C:\Developer\fsharp-main\vsintegration\src\FSharp.ProjectSystem.FSharp\FSharp.ProjectSystem.FSharp.fsproj]
```

**Comment by KevinRansom** [comment]
I can only assume that the coreclr implementation of the GenerateResource  buildtask doesnot support old style resources, which sort of makes sense.  We will have to move over to pre-generated resources.  I have to assume that this scenario hasn't worked for basically ever.  So It isn't a regression or at least a recent one.

**Comment by auduchinok** [comment]
It used to work previously, as I was able to build this solution in Rider (and we follow what console builds do), but that indeed could have been some time ago.

**Comment by vzarytovskii** [comment]
I can't see the issue anymore

**Comment by ViktorHofer** [comment]
@vzarytovskii this still reproduces on main when using dotnet build. fsharp by default builds with VS msbuild which is probably why you didn't hit the issue. The VMR needs to set the property to build fsharp successfully:  https://github.com/dotnet/dotnet/blob/8ba3045c8c7df6d5aa64b87921d90fec0d77e216/repo-projects/fsharp.proj#L14
