### ISSUE TITLE
FCS 43.7.200 has odd behavior for modules with errors

### ISSUE THREAD

**Issue by baronfel** [dotnet/fsharp#14757]
While updating FsAutoComplete to [support F# 7](https://github.com/fsharp/FsAutoComplete/pull/1043) I found that something fundamental has changed in the way at least anonymous modules are parsed in the presence of errors. This leads to a large number of parse-tree-based helper methods for powering codefixes no longer functioning, and so many of the tests FSAC has validating codefix behavior are now permanently broken. For the codefixes I've directly investigated that have parallels in the VS tooling in this repo, I saw the same behavior using a VS 17.5 preview (to ensure I was on a similar FCS). Let's dig into one CodeFix in particular - the one that converts erroring single-quote string interpolation into triple-quoted interpolation.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Load up an .fsx file with the following content: `let a = $":^) {if true then "y" else "n"} d"`
2. Note that a diagnostic 3373 is triggered at the " next to the `y`.
3. Attempt to fire a codefix - none is found.
4. The code that should trigger the codefix is `TryRangeOfStringInterpolationContainingPos`
5. `TryRangeOfStringInterpolationContainingPos` isn't finding an interpolated string expression, why?
6. There are no `decls` in the `SynModuleOrNamespace`:
![image](https://user-images.githubusercontent.com/573979/219115422-26b3cdb2-d4e2-48c1-beef-600fad5ad10c.png)

This is the case for many other codefixes, and they present the same way in VS as well.

**Comment by vzarytovskii** [comment]
@nojaf @auduchinok does this ring a bell to you? I remember some changes around modules.

**Comment by vzarytovskii** [comment]
@baronfel in case if I need to bisect it, what would you say will the fastest way of doing it? Do you have a FCS api snippet by any chance?

**Comment by baronfel** [comment]
You should be able to debug it using the code string above and breakpointing [here](https://github.com/dotnet/fsharp/blob/main/vsintegration/src/FSharp.Editor/CodeFix/UseTripleQuotedInterpolation.fs#L28) - VS has a codefix for interpolation as well (which is why I used it as the example).

**Comment by auduchinok** [comment]
> @nojaf @auduchinok does this ring a bell to you? I remember some changes around modules.

Nope, sorry. Maybe it could be related to PRs like https://github.com/dotnet/fsharp/pull/14399 or https://github.com/dotnet/fsharp/issues/14434?

**Comment by nojaf** [comment]
This doesn't ring a bell, all I can say is that is happened between 7d115d56cde12006dd26a3c5babd702df451b8e8 and e30d14cb46f290050ac8e2bbea5e9b804b97bdde.

**Comment by nojaf** [comment]
Maybe https://github.com/dotnet/fsharp/pull/14182 is related. @abonie any thoughts?

**Comment by abonie** [comment]
Yes, it looks like the root cause as far as I can tell (idk how code fixes work, but second comment in that PR thread might explain how it broke it)

**Comment by 0101** [comment]
The change that caused this was reverted (but not backported to 17.5). It should work in 17.6.
