### ISSUE TITLE
FSC is verbose when reference assemblies are used

### ISSUE THREAD

**Issue by purkhusid** [dotnet/fsharp#14767]
When using FSC with reference assemblies directly I get a lot of these kinds of messages:

```
The local method '<StartupCode$Protobuf-FSharp-dll>.$Descriptor'::'get_Parser@1871-32' was referenced but not declared
generic arity: 0
The local method '<StartupCode$Protobuf-FSharp-dll>.$Descriptor'::'get_NameFieldNumber@1872-2' was referenced but not declared
generic arity: 0
The local method '<StartupCode$Protobuf-FSharp-dll>.$Descriptor'::'get_MethodFieldNumber@1873' was referenced but not declared
generic arity: 0
```

This does not happen when the project is compiled using `dotnet`

**Expected behavior**

There should be no additional output form the compiler

**Actual behavior**

There is a lot of output that looks something like this:
```
The local method '<StartupCode$options_api_events_proto-dll>.$Events'::'get_Parser@538-4' was referenced but not declared
generic arity: 0
```

**Known workarounds**

None
[repro.tar.gz](https://github.com/dotnet/fsharp/files/10768073/repro.tar.gz)

**Comment by purkhusid** [comment]
To run the repro:

1. Extract it
2. cd into the output folder
3. `./fsc.sh`

**Comment by vzarytovskii** [comment]
@purkhusid does it reproduce with `dotnet build`?

**Comment by vzarytovskii** [comment]
Minimal repro:
```fsharp
namespace RefAssembly
type Any = { mutable Field: string }
module Any =
    let internal DefaultValue = { Any.Field = "" }
```
Issue goes away if `internal` is omitted.

**Comment by vzarytovskii** [comment]
Ok in this particular case it is *intended* to *not find* it:
https://github.com/dotnet/fsharp/blob/db5aca9dfacf618a46f4c3b1ffb4bcc9e4bb3b2c/src/Compiler/AbstractIL/ilwrite.fs#L1170-L1180

I can factor the check out to the separate method, and use it in this particular place

**Comment by purkhusid** [comment]
Thanks for looking into this, especially since this isn't really a supported way of using the compiler. If you don't already know why I'm using it directly then you can find the reason here: https://github.com/bazelbuild/rules_dotnet
