### ISSUE TITLE
Update net7.0 TFM references to net8.0

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/fsharp#14765]
In order to be source-build compliant for the .NET 8.0 release.  All projects targeting a `net7.0` TFM must be upgraded to `net8.0`.  It is preferred that a new [`NetCurrent` Arcade property](https://github.com/dotnet/arcade/pull/12161) be utilized as it eliminates this type of maintenance work for every release.

**Comment by KevinRansom** [comment]
@MichaelSimons , this build requirement is solely for source build right.  Arcade builds will still be able to target net7.0 for non-source build am I  right?

**Comment by vzarytovskii** [comment]
Probably having it just for source build will be too much msbuild magic with selecting tfms. I guess it'll be easier for us to have a separate net8 release branch which inserted to net8 SDK.

**Comment by MichaelSimons** [comment]
> @MichaelSimons , this build requirement is solely for source build right. Arcade builds will still be able to target net7.0 for non-source build am I right?

Correct.

**Comment by MichaelSimons** [comment]
@KevinRansom - Any update on this?  At one time you had mentioned the possibility of targeting net8.0 just for source-build?  The NetCurrent properties were backported in arcade to if you used them, source-build would be happy.

**Comment by vzarytovskii** [comment]
> @KevinRansom - Any update on this?  At one time you had mentioned the possibility of targeting net8.0 just for source-build?  The NetCurrent properties were backported in arcade to if you used them, source-build would be happy.

We did the sdk update, and will target net8 once vs is inserting it. I believe it will in 17.7p2? Will take a look later this week if we are ok opening our solutions targeting net8.

**Comment by baronfel** [comment]
@vzarytovskii was this closed by dotnet/fsharp#15245?

**Comment by vzarytovskii** [comment]
> @vzarytovskii was this closed by dotnet/fsharp#15245?

I guess so
