### ISSUE TITLE
Why is F# Array.minby so slow, is this a bug?

### ISSUE THREAD

**Issue by 892745513** [dotnet/fsharp#14775]
open System.Diagnostics
open System.Linq
printfn "minby"

type point3d = {i:int;x:float;y:float;z:float}
let random = new System.Random()
let  max = 10000.0; 

let point1 = {i=1; x=500; y=99; z=600} 
let pos1 = [|for i in 1..100000 -> 
                {i=i; x=random.NextDouble() * max; y=random.NextDouble() * max; z= random.NextDouble() * max}|]
                 
let watch = Stopwatch ()
watch.Start()

let minValue = pos1.Min(fun n->  (n.x - point1.x) ** 2 + (n.y -  point1.y) ** 2 + (n.z -  point1.z) ** 2) 
let mins = pos1.Where(fun n->   ((n.x - point1.x) ** 2 + (n.y -  point1.y) ** 2 + (n.z -  point1.z) ** 2) = minValue)
               .ToArray()
                
watch.Stop()
printfn "%A" mins
printfn "===============%d 秒===================" (watch.ElapsedMilliseconds/1000L)

watch.Restart() 
let p2 = pos1 |> Array.minBy(fun n-> (n.x - point1.x) ** 2 + (n.y -  point1.y) ** 2 + (n.z -  point1.z) ** 2)

watch.Stop()
printfn "===============%d 秒===================" (watch.ElapsedMilliseconds/1000L)
printfn "%A" p2

The result :
minby
[|{ i = 79174
    x = 658.5646621
    y = 69.75420851
    z = 717.8190406 }|]
===============0 秒===================
===============318 秒===================
{ i = 79174
  x = 658.5646621
  y = 69.75420851
  z = 717.8190406 }

![}M1B%G`A@UDZX747}ZSK(0R](https://user-images.githubusercontent.com/25919944/220324017-1c487173-b78f-46b0-a3b5-194652ada5cb.png)

**Comment by 892745513** [comment]
I see, I went into debug mode in minBy F10, maybe there is a bug in debug mode

**Comment by cartermp** [comment]
I don't think there's a bug here. Release is faster than Debug mode. Although FWIW on my arm64 device they're pretty much identical (within 1-2ms of each other in each run)

**Comment by ShalokShalom** [comment]
> I see, I went into debug mode in minBy F10, maybe there is a bug in debug mode

what do you get in release mode, in comparison?

**Comment by vzarytovskii** [comment]
> I don't think there's a bug here. Release is faster than Debug mode. Although FWIW on my arm64 device they're pretty much identical (within 1-2ms of each other in each run)

As Phillip said, Debug doesn't involve majority of F# optimizations, mostly doesn't involve JIT.

**Comment by 0101** [comment]
@892745513 please provide a BenchmarkDotNet benchmark results running on .net7 in release configuration, which will show real performance.

**Comment by 0101** [comment]
Closing until more evidence is presented.
