### ISSUE TITLE
'eng/Versions.props' specifies wrong FSharp.Core version

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#14791]
The currently specified version is 6.0.6:
https://github.com/dotnet/fsharp/blob/30f2945b3815a082bd4f7bdd25fa976e44f70015/eng/Versions.props#L43

7.0.0 has been published a few months ago:
https://www.nuget.org/packages/FSharp.Core/7.0.0#versions-body-tab

It would be really good if these versions were synchronized, and `Versions.props` would be updated around the release dates, as part of all the version update works.

**Comment by vzarytovskii** [comment]
It has been updated in 17.6, https://github.com/dotnet/fsharp/blob/release/dev17.6/eng/Versions.props#L31
It will flow back when 17.7 will be snapped.

**Comment by auduchinok** [comment]
Would it be possible to update them in `main` and then make them flow into other branches? Or merge a release branch back to `main` as soon as the release happens?

**Comment by vzarytovskii** [comment]
> Would it be possible to update them in `main` and then make them flow into other branches? Or merge a release branch back to `main` as soon as the release happens?

If we will be merging branch back before the release, then we will be updating the rest of the packages (VS, Roslyn, etc), which will add contsraints to which VS should be used in main.
We usually are not restricting it (well, try to, I may have accidentally did it once or twice in the past).

If you're using main as your main branch and need new `FSharp.Core`, sure, feel free to update and PR it.

**Comment by auduchinok** [comment]
I thought about it once more. Yeah, we should probably keep this version lower to make things easier for other FCS consumers.
