### ISSUE TITLE
Internal error when hovering over a member with an apostrophe in the Feliz library

### ISSUE THREAD

**Issue by mrakgr** [dotnet/fsharp#14792]
Hovering over the `prop.type'` of the Feliz library gives an internal error instead of its proper description. See [related issue](https://github.com/Zaid-Ajaj/Feliz/issues/555) for more info.

**Repro steps**

First, install the Feliz.Template.

```
PS E:\Webdev\Fable\feliz-bug> dotnet new install Feliz.Template
The following template packages will be installed:
   Feliz.Template

Success: Feliz.Template::4.2.0 installed the following templates:
Template Name   Short Name  Language  Tags
--------------  ----------  --------  ------------------
Feliz template  feliz       F#        Fable/Elmish/React

PS E:\Webdev\Fable\feliz-bug> dotnet new feliz
The template "Feliz template" was created successfully.

PS E:\Webdev\Fable\feliz-bug> dotnet restore
  Determining projects to restore...
  Restored E:\Webdev\Fable\feliz-bug\src\App.fsproj (in 1.06 sec).
```

Then in one of the files put something like this:

```
module Main

open Feliz
prop.type'
```

Once you hover over `prop.type'` with the mouse you should see the error: `internal error: 'doc/members/member[@name='M:Feliz.prop.type'(System.String)']' has an invalid token.`.

**Related information**

The same error manifests in both VS and VSC.

**Comment by vzarytovskii** [comment]
What's the version of VS does this reproduce in?

**Comment by mrakgr** [comment]
Microsoft Visual Studio Community 2022
Version 17.4.4
VisualStudio.17.Release/17.4.4+33213.308
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.4.326.54890
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.4.326.54890
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.4.326.54890
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.4.0-6.22608.27+af1e46ad38d900023f8b1a2839484e471ece1502
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2246202+61cc048d36a3fc9246d2f04625988b19a18ab8f0
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62207.28050
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.10921.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.4.0-6.22608.27+af1e46ad38d900023f8b1a2839484e471ece1502
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.4.0-beta.22512.4+525d5109e389341bb90b144c24e2ad1ceec91e7b
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

**Comment by mrakgr** [comment]
Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes

**Comment by vzarytovskii** [comment]
This is in 17.6:
![image](https://user-images.githubusercontent.com/1260985/220934034-a2be39e3-387e-4b0b-8c23-4255cb5a08b9.png)

Looks like it was fiexed in https://github.com/dotnet/fsharp/pull/14311

Should be fixed in both 17.5 and 17.6

**Comment by mrakgr** [comment]
Yeah, it works fine in VS 17.5. I wonder when the patch will land in VS Code? Does it depend on the .NET SDK or something else?

Should I open an issue on the VS Code repo?

**Comment by vzarytovskii** [comment]
> Yeah, it works fine in VS 17.5. I wonder when the patch will land in VS Code? Does it depend on the .NET SDK or something else?
> 
> Should I open an issue on the VS Code repo?

It should once they'll update to latest compiler services, I think they're already in progress of doing that.

**Comment by baronfel** [comment]
Yep! We've updated the language server component and are doing testing of the Ionide plugin with the changes. I would expect a release this weekend.

**Comment by mrakgr** [comment]
Ok, thanks!
