### ISSUE TITLE
Inaccurate error in anonymous record copy-and-update

### ISSUE THREAD

**Issue by kerams** [dotnet/fsharp#14814]
**Repro steps**

```fsharp
let t3 (t1: {| gu: string; ff: int |}) = { t1 with ff = 3 }
```

or [sharplab](https://sharplab.io/#v2:DYLgZgzgPsCmAuACeBmRAKeBGEiDeUiA5gK64TwBOAlgHZEDciYYudSUAvgJSIC8+ZFkQB3avAAWzMP0RpOQA===).

**Expected behavior**

Error saying brace-pipes are required.

**Actual behavior**

Squiggly under `ff` with `The record label 'ff' is not defined.`.

**Related information**

* VSIX for F# built from main
* VS 17.6 Preview 1

**Comment by edgarfgp** [comment]
I tried fixing this on #15598 and quickly realized there seemed to be an unexpected internal error while executing the following test. Which blocks any further attempt to improve the error reporting on anonymous records :( 

**`Unexpected exception raised in compiler: destAppTy (Failure)`**

```fsharp
 [<Fact>]
     let ``This expression was expected to have an anonymous Record but has a record`` () =
         Fsx """
 let t3 (t1: {| gu: string; ff: int |}) = { t1 with ff = 3 }
         """
         |> ignoreWarnings
         |> typecheck
         |> shouldFail
```

```
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Unknown exception seen in compiler: JetBrains.ReSharper.TestRun...

System.AggregateException
One or more errors occurred. (One or more errors occurred. (Unknown exception seen in compiler: JetBrains.ReSharper.TestRunner.Logging.TraceListener+AssertionException: Unknown exception seen in compiler: JetBrains.ReSharper.TestRunner.Logging.TraceListener+AssertionException: Unknown exception seen in compiler: JetBrains.ReSharper.TestRunner.Logging.TraceListener+AssertionException: Unknown exception seen in compiler: JetBrains.ReSharper.TestRunner.Logging.TraceListener+AssertionException: Unknown exception seen in compiler: JetBrains.ReSharper.TestRunner.Logging.TraceListener+AssertionException: Unknown exception seen in compiler: JetBrains.ReSharper.TestRunner.Logging.TraceListener+AssertionException: Unexpected exception raised in compiler: destAppTy (Failure)
```

@abonie Does this rings a bell based on https://github.com/dotnet/fsharp/pull/15519 ?

**Comment by abonie** [comment]
Hmm... I don't expect these are related

**Comment by KevinRansom** [comment]
This was introduced by this PR:   https://github.com/dotnet/fsharp/pull/15214

**Comment by auduchinok** [comment]
Off-topic: I wonder if we could enable the normal record syntax for anon records too?

RFC says [this](https://github.com/fsharp/fslang-design/blob/main/FSharp-4.6/FS-1030-anonymous-records.md#copy-and-update):
> Unlike records, we do not assume that the origExpr has the same type as the overall expression.

For some reason I thought it was already working, and when the normal record syntax is used, an anonymous record of the same would be produced.
