### ISSUE TITLE
Strong name signing silently fails

### ISSUE THREAD

**Issue by timothyheron** [dotnet/fsharp#14863]
Shamelessly copying most steps from this issue, but this is a different issue: https://github.com/dotnet/fsharp/issues/11546

Repro steps

Create a new F# project:

`dotnet new classlib --language F#`

Create a new strong named key:

`sn -k sgKey.snk`

Add the following property group to the fsproj file:

```
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>sgKey.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
```

Build with `dotnet build` and all appears fine

But check the strong name and it will be invalid:

```
sn -v bin\Debug\net7.0\test.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Failed to verify assembly -- Strong name validation failed.

```

This has started happening for us when we upgraded from VS 2022 17.4 to 17.5.  We've had to workaround the issue by running sn -R to resign each assembly after it has built.  We're targeting .Net Framework but as you can see above it's a problem for .NET 7 as well.

**Comment by vzarytovskii** [comment]
@KevinRansom could you please look at it?
