### ISSUE TITLE
Let FSharp records produce CSharp records

### ISSUE THREAD

**Issue by lmorvan** [dotnet/fsharp#14918]
**Is your feature request related to a problem? Please describe.**

When I'm using a library I made with F# into a C# project, the F# records are not C# records.

**Describe the solution you'd like**

Build the F# record so that the type produced in the library is also a C# record. 

**Describe alternatives you've considered**

The built F# record is usable as a regular C# class, but it does not provide access to the `with` keyword and other facilities related to C# records.

**Additional context**

No

**Comment by kerams** [comment]
https://github.com/fsharp/fslang-suggestions/issues/903

**Comment by vzarytovskii** [comment]
Closing this, and let's keep all discussions in suggestions
