### ISSUE TITLE
When did we remove the ability to specify the path to FSI.exe?

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#1493]
We should be able to specify the path to use when running FSI from within VS.

Kevin

**Comment by dsyme** [comment]
I agree this should return. I think it got removed when we added the 64-bit flag

**Comment by KevinRansom** [comment]
It might even have been me that did it.  But I don't remember doing it.  And I don't remember why.  Old age is a terrible thing.

**Comment by cartermp** [comment]
I'll close this out because I'm not really sure it's useful or necessary anymore. It just feels like a way to have too many problems when pulling in dependencies that will work in VS, but not necessarily with some arbitrary older desktop FSI.
