### ISSUE TITLE
Dotnet fsi broken on inputs that take more than 1 line

### ISSUE THREAD

**Issue by ieviev** [dotnet/fsharp#14946]
Please provide a succinct description of the issue.

dotnet fsi breaks because it cannot read multiline expressions 

Provide the steps required to reproduce the problem:

1 run dotnet fsi
2 insert any expr taking more than 1 line in console
3 reach the bottom of console
4 the interpreter goes crazy

7.0.2xx sdk:
![dotnet-fsi](https://user-images.githubusercontent.com/36763595/226745013-90af0e32-c245-48b3-a40d-a8463b0e855b.gif)

issue does not exist in 7.0.1** sdk:
![dotnet-fsi-old](https://user-images.githubusercontent.com/36763595/226745036-9c1449ac-77c5-44f9-a14e-df656f802488.gif)

workaround is to revert back to 7.0.1
```
sudo apt-get install dotnet-sdk-7.0=7.0.104-1
```

**Comment by KevinRansom** [comment]
This repros on linux, not windows.

**Comment by NatElkins** [comment]
I also experienced this on macOS.

**Comment by sgoguen** [comment]
It appears #14365 rewrote how line advances on FSharp.Compiler.Interactive.ReadLineConsole() to accommodate East Asian Width characters per https://www.unicode.org/reports/tr11/

Unfortunately, this fix advances the next line by setting Console.BufferHeight by incrementing it:

```fsharp
        let moveCursorToNextLine c =
            let charSize = x.GetCharacterSize(c)

            if Console.CursorLeft + charSize > Utils.bufferWidth () then
                if Console.CursorTop + 1 = Console.BufferHeight then
                    Console.BufferHeight <- Console.BufferHeight + 1

                Cursor.Move(0)
 ```
 
 Taking a shot in the dark, I was able to quickly resolve the issue on my Mac tonight with the following ugly fix:
 
 ```fsharp
        let moveCursorToNextLine c =
            let charSize = x.GetCharacterSize(c)

            if Console.CursorLeft + charSize > Utils.bufferWidth () then
                if Console.CursorTop + 1 = Console.BufferHeight then
                    try
                        Console.BufferHeight <- Console.BufferHeight + 1
                    with _ ->
                        Console.WriteLine()
                    
                Cursor.Move(0)
 ```
 
 I'm not that familiar with System.Console and would appreciate any guidance if anyone would like to provide it.

**Comment by sgoguen** [comment]
The following update to console.fs to the function seems to resolve the issue on my Mac.

```fsharp
        let moveCursorToNextLine c =
            let charSize = x.GetCharacterSize(c)

            if Console.CursorLeft + charSize > Utils.bufferWidth () then
                if Console.CursorTop + 1 = Console.BufferHeight then
                    try
                        Console.BufferHeight <- Console.BufferHeight + 1
                    with _ ->
                        // If we can't increase the buffer height, just write a newline.
                        Console.WriteLine()
                        // When we add a newline, we need to reflect the change in the anchor.
                        anchor <- { anchor with top = (anchor).top - 1 }
                    
                Cursor.Move(0)
```

**Comment by MrLuje** [comment]
Got bitten by this today once again (https://github.com/dotnet/fsharp/issues/14160#issuecomment-1527527302) 😞 

@sgoguen are you going to make a PR for it ?
I confirm this fix this issue. I guess we could even get rid of the try block and only go with the with part, since only windows will go to the happy path
```fsharp
        let moveCursorToNextLine c =
            let charSize = x.GetCharacterSize(c)

            if Console.CursorLeft + charSize > Utils.bufferWidth () then
                if Console.CursorTop + 1 = Console.BufferHeight then
                    Console.WriteLine()
                    // When we add a newline, we need to reflect the change in the anchor.
                    anchor <- { anchor with top = (anchor).top - 1 }
                    
                Cursor.Move(0)
```

**Comment by MrLuje** [comment]
@vzarytovskii  Assign a long string to a variable (string longer than terminal's width) and do it enough times to hit the bottom of the terminal (to trigger the scrolling)

I was having it with RC1 this weekend, I'll try again with RC2

**Comment by athrun** [comment]
I can reproduce this bug in Homebrew's currently shipping dotnet 8 build: https://github.com/dotnet/fsharp/pull/16251#issuecomment-1859037202

**Comment by vzarytovskii** [comment]
It didn't get to release for 8.0.100 for sure, I'd expect it in 8.0.200
