### ISSUE TITLE
Ghost processes after initial build

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#14988]
Apologies for not reporting this sooner but I fear I still found a problem after https://github.com/dotnet/fsharp/pull/14677.

**Repro steps**

* Fresh clone of the repository.
* `dotnet build Fsharp.Compiler.Service.sln`
* PowerShell: `Get-Process -Name "dotnet" | Select-Object Id,Name,StartTime,CommandLine`

**Expected behavior**

There shouldn't be any lingering dotnet processes after that initial build.
When doing a rebuild or `-c Release` `fslex` could be stuck because of a lock.

**Actual behavior**

![image](https://user-images.githubusercontent.com/2621499/228232374-ea37623f-164b-4bca-9ad7-040b3a0f090e.png)

**Known workarounds**

Kill all the processes: `Get-Process -Name "dotnet" | Kill`

**Comment by vzarytovskii** [comment]
So, at this point, we don't do anything extra, just a normal `dotnet build`, no special tasks or anything, so it's likely unrelated to F#.
