### ISSUE TITLE
CLIEvent not properly exposed in certain cases when there are more than one events in a project (.NET 7 regression?)

### ISSUE THREAD

**Issue by flannelhead** [dotnet/fsharp#14996]
When exposing events from F# code to C# along these [guidelines](https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/component-design-guidelines#use-the-clievent-attribute-to-expose-net-events), in some cases some of the events fail to be exposed properly:

- When a project contains more than one module that have classes with exposed events
- When a project contains a module that has two or more classes with exposed events

In these cases, one can't use the `+=` operator on the events to add handlers in C# code. This happens only if the F# project targets `net7.0` or newer (checked also with `net8.0` preview 2).

**Repro steps**

**Case 1:**

Consider a solution with these projects:

* `LibraryWithTwoClassesAndTwoEvents` - F# lib project
* `TestApp` - C# project that consumes the interface of the lib

The lib project has the following code in a `.fs` file:
```
namespace EventTest

open System

module LibraryWithTwoClassesAndTwoEvents =
    let event = new DelegateEvent<EventHandler<EventArgs>>()
    type MyClass() =
        [<CLIEvent>]
        member this.Event = event.Publish

    let event2 = new DelegateEvent<EventHandler<EventArgs>>()
    type MyClass2() =
        [<CLIEvent>]
        member this.Event = event2.Publish
```

The `TestApp` has the following code:
```
using EventTest;

var obj1 = new LibraryWithTwoClassesAndTwoEvents.MyClass();
obj1.Event += MyEventHandler;   // This doesn't work
obj1.add_Event(MyEventHandler); // but this does

void MyEventHandler(object sender, EventArgs e)
{
    throw new NotImplementedException();
}
```

If one removes the type `MyClass2` from the lib, the above code works. It also works when the lib targets .NET 6 or lower.

**Case 2:**

Consider a solution with these projects:

* `LibraryWithTwoModulesAndTwoEvents` - F# lib project
* `TestApp` - C# project that consumes the interface of the lib

The lib project has the following code in two files:

`Module1.fs`:
```
namespace EventTest

open System

module Module1 =
    let event = new DelegateEvent<EventHandler<EventArgs>>()
    type MyClass() =
        [<CLIEvent>]
        member this.Event = event.Publish
```
`Module2.fs:`:
```
namespace EventTest

open System

module Module2 =
    let event = new DelegateEvent<EventHandler<EventArgs>>()
    type MyClass() =
        [<CLIEvent>]
        member this.Event = event.Publish
```

The `TestApp` has the following code:
```
using EventTest;

var obj1 = new Module1.MyClass();
obj1.Event += MyEventHandler;   // This works

var obj2 = new Module2.MyClass();
obj2.Event += MyEventHandler;   // This doesn't work
obj2.add_Event(MyEventHandler); // but this does

void MyEventHandler(object sender, EventArgs e)
{
    throw new NotImplementedException();
}

```

Reproducer is attached with both of the cases and also an example of a project which has two events in the same class, which builds successfully.
[repro.zip](https://github.com/dotnet/fsharp/files/11097638/repro.zip)

**Expected behavior**

Events are exposed properly to the interface to be consumed by C#.

**Actual behavior**

Events are not properly exposed - `+=` and `-+` operators can't be used to add/remove event handlers.

**Known workarounds**

When this issue occurs, using the `add_Event` and `remove_Event` methods directly seems to work.

**Comment by T-Gro** [comment]
Hi.

I have bisected the problem for the period between F# 6 and F# 8.

Interestingly enough, the problem is not related to the compiler, but is driven by the TargetFramework element.
Meaning, even the latest compiler built from main, but in a project targetting net6.0, behaves as expected.

The reason is, the .fsproj default targets for F# projects have one difference starting with F# 7 - reference assemblies are enabled by default, and the compilation of the C# project is done based on the reference assemblies (dummy assemblies for faster tooling, which however should have exactly the same public surface).

=> this is a bug in the reference assembly implementation in F# for CliEvent members, I will try to fix it.

In the meantime, this workaround for the event-producer project will do the trick:
```xml
	<ProduceReferenceAssembly>false</ProduceReferenceAssembly>
```
