### ISSUE TITLE
VS: Enable parallel type checking option is not wired up to anything.

### ISSUE THREAD

**Issue by majocha** [dotnet/fsharp#15007]
![image](https://user-images.githubusercontent.com/1760221/229088319-af842000-c38e-45ef-bfbe-d55722a485a6.png)

This does not do anything, we don't have such option in code.

IIUC this is always enabled now on the compiler side?

**Comment by vzarytovskii** [comment]
> I think setting itself doesn't do anything for tooling scenarios, and can be safely removed
