### ISSUE TITLE
VS: enable diagnostics for unopened files

### ISSUE THREAD

**Issue by majocha** [dotnet/fsharp#15008]
Currently we have no diagnostics for unopened files, despite the fact they were typechecked already.

I might be mistaken but I vaguely remember this worked in Visual Studio long time ago.

**Comment by T-Gro** [comment]
This even used to be the default (according some github archeology I did), but it was not usable for bigger solutions like we have here in the repo.

I will bring it back and see how it behaves - it could get a lot more memory intense for solutions with many projects.

**Comment by T-Gro** [comment]
Done via #15591
