### ISSUE TITLE
Can't build FSharp.Editor: duplicate "Show_Return_Type_Hints" in xlf files

### ISSUE THREAD

**Issue by majocha** [dotnet/fsharp#15032]
`Show_Return_Type_Hints` id in translation files got somehow duplicated and VS complains when trying to build FSharp.Editor.

for example

https://github.com/dotnet/fsharp/blob/0825e8cfb00515e03790d330595f11534475a78b/vsintegration/src/FSharp.UIResources/xlf/Strings.zh-Hans.xlf#L110-L119

**Comment by 0101** [comment]
Should be fixed by https://github.com/dotnet/fsharp/pull/15033
