### ISSUE TITLE
Enable FSI to b be used in a production environment where IronPython would otherwise be needed

### ISSUE THREAD

**Issue by channell** [dotnet/fsharp#15099]
**Is your feature request related to a problem? Please describe.**

F# interactive cannot currently be used for application scripting in environment at do not have the full SDK, because the scripting host module Sample.FSharp.Compiler.Interactive.Main is marked as internal and is not available as a nuget dependency.

For system test environment, scripting of .NET integration test cases need to use IronPython

**Describe the solution you'd like**

change 
`module internal Sample.FSharp.Compiler.Interactive.Main` to `module Sample.FSharp.Compiler.Interactive.Main`

**Describe alternatives you've considered**

invoking FSI by loading the assembly and calling the [<EntryPoint>] function with reflection & converting F# test case code to Python

**Additional context**

**Comment by 0101** [comment]
Unfortunately this is not a supported scenario. FSI requires the full SDK to work. Even making that module public wouldn't make it work.
