### ISSUE TITLE
Note: Deno in js resembles fsx with nuget quite a lot

### ISSUE THREAD

**Issue by jkone27** [dotnet/fsharp#15123]
Thought maybe is interesting for folks working on dotnet fsi and .fsx scripts with nuget :) 

seems deno in js ecosystem is taking a similar approach

https://deno.land/manual@v1.28.1/node/npm_specifiers

**Comment by eriawan** [comment]
@jkone27 

This is more like into discussion instead of a true/real issue.
I suggest to move this into discussion.
