### ISSUE TITLE
Parameter name hints in VS get somewhat mangled with nested function calls

### ISSUE THREAD

**Issue by abonie** [dotnet/fsharp#15138]
**Repro steps**

Not sure about minimal repro, but open SyntaxTreeTests.fs in F# compiler repo and see (around [line 115](https://github.com/dotnet/fsharp/blob/main/tests/service/SyntaxTreeTests.fs#L115) atm):
<img width="839" alt="image" src="https://user-images.githubusercontent.com/20281641/234045551-d0a4c55b-0b3a-452b-974e-11a22a3540d4.png">

**Expected behavior**

`mapping =` and `list =` hints are in the correct place

**Actual behavior**

Some hints are on a wrong line, stacked in a sequence of hints (see picture)

**Related information**

Provide any related information (optional):

* Operating system: Windows 11
* Editing Tools: VS Version 17.7.0 Preview 1.0 [33621.438.main]

**Comment by psfinaki** [comment]
Thanks, here's a small repro:

```fsharp
type X = | X of a: int list * b: string
let x = X(List.map id [ 42 ], "")
```
