### ISSUE TITLE
Task stop executing after block with Dapper async call

### ISSUE THREAD

**Issue by jindraivanek** [dotnet/fsharp#15145]
If `task {}` have certain depth it silently stop executing after `let!` block that contains [Dapper](https://github.com/DapperLib/Dapper) async call.

This is connected to Dapper library, but because I think this behavior should never happen, regardless of code inside task, I am raising issue here. 

Repro code here: https://github.com/jindraivanek/task-bug-repro

**Repro steps**

Provide the steps required to reproduce the problem:

1. Checkout repro: https://github.com/jindraivanek/task-bug-repro
2. Start MSSQL server by docker commands, or change connection string to your local MSSQL server
3. Run project, program will not end, task [complexTask](https://github.com/jindraivanek/task-bug-repro/blob/main/task-bug-repro/Program.fs#L48) will never finish, [second `let!` bock](https://github.com/jindraivanek/task-bug-repro/blob/main/task-bug-repro/Program.fs#L58) is never executed.

**Expected behavior**

Task should never silently stop executing.

**Actual behavior**

Task stop executing after first `let!` block with Dapper async call. (But not during or after Dapper call, all code in this block is executed.)

**Known workarounds**

- use synchronous variant of Dapper method
- refactor to have less depth of task
- use `async` instead of `task`
All these workaround are showcased in repro code.

**Related information**

Reproduced with MSSQL, does not reproduce with SQLite, didn't test on another databases.

* Operating system
Windows 10
* .NET Runtime kind (.NET Core, .NET Framework, Mono)
.NET 7
* Editing Tools (e.g. Visual Studio Version, Visual Studio)
not important, but Rider

**Comment by vzarytovskii** [comment]
@jindraivanek have you tested it with TaskBuilder, Ply or IcedTasks? Wondering if it works there.

**Comment by jindraivanek** [comment]
> @jindraivanek have you tested it with TaskBuilder, Ply or IcedTasks? Wondering if it works there.

Didn't test it, I can try it later today.

**Comment by jindraivanek** [comment]
Interesting, with TaskBuilder, I got exception `Unable to cast object of type 'System.Threading.Tasks.Task`1[System.String]' to type 'System.Threading.Tasks.Task`1[System.Object]'`. If I specify that `name` is `string` (by ` let updateItem (f: unit -> Task<string>) i`) it works, and also standard `task` works.

**Comment by jindraivanek** [comment]
Correction: what's important is to specify that `f` returns `Task`, this is enough: `f: _ -> Task<_>`. It seems that inferred type `f: (unit -> #Task<'b>)` cause of problem here.

**Comment by jindraivanek** [comment]
Ply and IcedTask will give compiler error unless `f` is annotated with `f: _ -> Task<_>`

**Comment by T-Gro** [comment]
This looks like it might suffer from what this PR addresses:
https://github.com/dotnet/fsharp/pull/13298

Which hurts seemingly unrelated issues, and having a warning for it would make you more aware of what might cause issues at runtime.

**Comment by jindraivanek** [comment]
After some more experimenting, it turns out that _definition_ of higher order task function is what causes the problem:

```fsharp
let repro (conn:IDbConnection) =
    task {
        let hof f = task { return! f() }
        let! _ = $"UPDATE Persons SET Name = 'BOO' WHERE Id = 1" |> conn.ExecuteAsync
        printfn $"Task completed (line {__LINE__})" // we never hit this line
        return ()
}
```

Simplified repro along with multiple workarounds now lives in `dapper` branch of my repro: https://github.com/jindraivanek/task-bug-repro/blob/dapper/task-bug-repro/Program.fs

**Comment by jindraivanek** [comment]
Also found two different problems without use of Dapper in similar scenario. Most likely it will be connected.

`async` call gives null reference exception:

```fsharp
let repro () =
    task {
        let hof f = task { return! f () }
        let! _ = async { return () }
        printfn $"Task completed (line {__LINE__})"
        return ()
    }
```

Full Stack trace:
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.FSharp.Control.TaskBuilderExtensions.HighPriority.TaskBuilderBase.BindDynamic.Static[TOverall,TResult1,TResult2](ResumableStateMachine`1& sm, Task`1 task
, FSharpFunc`2 continuation) in D:\a\_work\1\s\src\FSharp.Core\tasks.fs:line 413
   at Program.repro@4.MoveNext() in C:\dev\Repro\task-bug-repro\task-bug-repro\Program.fs:line 10
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at <StartupCode$task-bug-repro>.$Program.main@() in C:\dev\Repro\task-bug-repro\task-bug-repro\Program.fs:line 28
```

And use of `Task.delay` gives `internal error: The local field ResumptionDynamicInfo was referenced but not declared` at compile:

```fsharp
let internalError () =
    task {
        let hof f = task { return! f () }
        let! _ = Task.Delay 1000
        printfn $"Task completed (line {__LINE__})"
        return ()
    }
```

Repro for this is now in `main` branch of repro: https://github.com/jindraivanek/task-bug-repro/blob/main/task-bug-repro/Program.fs

Should I create new issue(s) for this case(s)?
