### ISSUE TITLE
The ability to specify via (let) a prefix / infix / postfix operator

### ISSUE THREAD

**Issue by Marty-Stu** [dotnet/fsharp#15161]
**The ability to specify via (let) a prefix / infix / postfix operator**

The ability to specify through (let) a prefix / infix / postfix operator ala
```
let   prefix/infix/postfix <name> <arg'1> ... <arg'N>
    = ...
```

**let   prefix/infix/postfix <name> <arg'1> ... <arg'N> = ...**

Set prefix / infix / postfix of the specified operator through let

**I did not consider alternatives (introducing a new keyword is not an option)**

─

**Additional context**

related: #11481

I repeat [I don't mind :)]:
```
let    prefix/infix/postfix <name> <arg'1> ... <arg'N>
     = ...
```

**Comment by vzarytovskii** [comment]
This should go to fslang-suggestions
