### ISSUE TITLE
Visual Studio does not show all diagnostics

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#15186]
Does not show unused warnings if other errors are present + parser error recovery does not work in some cases.

more info here: https://github.com/dotnet/fsharp/pull/15337

**Comment by auduchinok** [comment]
Many such diagnostics aren't shown due to earlier check errors as well, not only due to parser ones. Here's one example: https://github.com/dotnet/fsharp/issues/5384, and there're many other ones, some of which were also previously reported.

**Comment by vzarytovskii** [comment]
I think this one in particular is fixed with Jakub's changes to partial typechecking
