### ISSUE TITLE
`System.BadImageFormatException` on attempt to compare a `voidptr` and `IntPtr.Zero.ToPointer()`

### ISSUE THREAD

**Issue by ForNeVeR** [dotnet/fsharp#15254]
Consider this F# program:
```fsharp
open System

[<Struct>]
type Image =
    val data: voidptr

let LoadTextureFromMemory(): bool =
    let image = Unchecked.defaultof<Image>
    image.data = IntPtr.Zero.ToPointer()

let foo = LoadTextureFromMemory()
````

**Expected behavior**
This program should work and put `true` into the `foo` variable.

**Actual behavior**
```
Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
   at Program.LoadTextureFromMemory()
   at <StartupCode$ConsoleApp11>.$Program.main@() in T:\Temp\ConsoleApp11\ConsoleApp11\Program.fs:line 13
```

[See the repro on sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAGxAMwM5wC4gE4Fd4AmIA1AD4CwAUAPYAOApjAAQDKAnqhvWFVQNoAeFhjwBjDAD4AulQxsGTAJKQA5vSYBeKkx1MAbhARMCEDBBD7qUArRG9KCehiYAZahAIAVegA8MubHoAMWxqMABZbmpsNgAKAEoLYGpqIy1KXSZHZyhVdQ0mAFUYUQALelEAa3oCADoCemQIXAQMamQBZQg1CW1dXO76etMITSUYDAAFEVqALXpQ2s9qSasJhYT7bKZkFLG3D28/AODQiKiYhKA===) as well.

**Known workarounds**
```fsharp
// open Microsoft.FSharp.NativeInterop
NativePtr.ofVoidPtr<byte> image.data = NativePtr.nullPtr
```

**Related information**
* Operating system: Windows 11
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .NET SDK 7.0.302
* Editing Tools (e.g. Visual Studio Version, Visual Studio): should not matter

**Comment by KevinRansom** [comment]
Not a regression or at least not a recent one, here it fails on net5.0:
````
C:\Users\kevinr\source\repos\ConsoleApp24\ConsoleApp24>dotnet --version
5.0.408

C:\Users\kevinr\source\repos\ConsoleApp24\ConsoleApp24>dotnet run
Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
   at Program.LoadTextureFromMemory()
   at <StartupCode$ConsoleApp24>.$Program.main@() in C:\Users\kevinr\source\repos\ConsoleApp24\ConsoleApp24\Program.fs:line 11

C:\Users\kevinr\source\repos\ConsoleApp24\ConsoleApp24>
````

**Comment by KevinRansom** [comment]
````F#
open System

[<Struct>]
type Image =
    val data: voidptr

let LoadTextureFromMemory(): bool =
    let image = Unchecked.defaultof<Image>
    image.data = IntPtr.Zero.ToPointer()

let foo = LoadTextureFromMemory()
````

````F#
    image.data = IntPtr.Zero.ToPointer()
````
image is itself a null value. That was forced to null using
````F#
     let image = Unchecked.defaultof<Image>
````
There is no field .data at the value null ptr.  And so an error is to be expected.  You can't dereference null to evaluate values by definition.

We don't evaluate ptrs validity prior to use, otherwise we would likely raise a better exception like null reference exception.

Here is the body of the function:
````
public unsafe static bool LoadTextureFromMemory()
{
	Image image2 = default(Image);
	Image image = image2;
	void* data@ = image.data@;
	IntPtr zero = IntPtr.Zero;
	return LanguagePrimitives.HashCompare.GenericEqualityIntrinsic<void*>(data@, zero.ToPointer());
}
````
I am pretty sure It would be wrong to expect the function to return true.  But bad image format may not be the best either.

**Comment by ForNeVeR** [comment]
Thanks, folks, you are so quick to fix things like this one. ❤️
