### ISSUE TITLE
Error on creating F# project

### ISSUE THREAD

**Issue by tushkalusa** [dotnet/fsharp#15295]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/languages/fsharp-hello-world-tutorial/create
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Hello 

I received the below error message when running the below command (I tried with "F" also)
dotnet new console -lang F# -o MyFSharpApp -f net7.0

ERROR MESSAGE: 
Couldn't find an installed template that matches the input, searching online for one that does...
Error: Invalid parameter(s):
-f net7.0
    'net7.0' is not a valid value for -f (Framework).

Thanks for the help.

**Comment by 0101** [comment]
@tushkalusa did you successfully complete the [previous step of the tutorial](https://dotnet.microsoft.com/en-us/learn/languages/fsharp-hello-world-tutorial/install), which has you install .NET 7 SDK? 

If yes please post here the output of `dotnet --info` command.

**Comment by vzarytovskii** [comment]
@baronfel probably should be moved to sdk if really an issue?
