### ISSUE TITLE
Verify that __useResumableCode is correct

### ISSUE THREAD

**Issue by Smaug123** [dotnet/fsharp#15303]
Is it correct that `let __useResumableCode<'T> : bool = false` is generic in [resumable.fs](https://github.com/dotnet/fsharp/blob/7fd0aa568977b259a06268dc52fe6af8664ce7c1/src/FSharp.Core/resumable.fs#L86)? It gets instantiated with `'T = obj` at every call site, as far as I can tell. If it is intended, could we please have some comments around it saying why it's correct?

**Comment by vzarytovskii** [comment]
Yeah, looks ok, it's just a helper intrinsic.
