### ISSUE TITLE
Error C2086 while using F# library from CPP/CLI project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#15333]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-C2086-while-using-F-library-from-/10381721)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.6.2]
While using VS 17.7.0 Preview 1.0 and F# library from CPP/CLI project  many errors of kind:

>System::Diagnostics::CodeAnalysis::DynamicallyAccessedMemberTypes redefinition

comes in the output windows.

I've attached minimal solution to repro this issue. Using VS 17.6.2 solution builds without any problems.

---

[Error_C2086.zip](https://github.com/dotnet/fsharp/files/11676114/Error_C2086.zip)

**Comment by vzarytovskii** [comment]
It seems like CPP compiler tries to generate DynamicallyAccessedMemberTypes as well as us? Or it finds it in both SDK and our dll.

**Comment by vzarytovskii** [comment]
If it's former, we'll probably have to rollback the change which generates it for older targets, and only emit the attribute for tfm which supports it.
If it's latter, we'll probably need to fix the checks.
