### ISSUE TITLE
Incorrect error range in mixed lists with yield!

### ISSUE THREAD

**Issue by Lanayx** [dotnet/fsharp#15361]
This issue is particularly painful when writing Fable UI where lists are often generated from data sequences using yield!

**Repro steps**

Provide the steps required to reproduce the problem:
Here is the code:
```fsharp
module Test =
    let f (): int list =
        [
            1
            "wrong"
            2
            yield! [3; 4]
        ]
```

**Expected behavior**

I expect the error to be highlighted only on `"wrong"` like when there is no `yield!`

![image](https://github.com/dotnet/fsharp/assets/3329606/d6d7a3ce-e4ba-4a22-b67f-7fb7e9daa43c)

**Actual behavior**

Whole list is highlighted with red

![image](https://github.com/dotnet/fsharp/assets/3329606/f3a36b68-afd8-48bc-b26b-c026b54f714a)

Provide a description of the actual behaviour observed. 

**Known workarounds**

Not applicable

**Related information**

Provide any related information (optional):

dotnet 7.0.200

**Comment by kerams** [comment]
Sort of a duplicate of https://github.com/dotnet/fsharp/issues/7670. Pretty sure the root cause is the same.
