### ISSUE TITLE
Renaming doesn't work properly for interface members

### ISSUE THREAD

**Issue by psfinaki** [dotnet/fsharp#15371]
Demo:

https://github.com/dotnet/fsharp/assets/5451366/75c48847-fdc7-4e38-ab73-5699fcdb99d3

Code:
```fsharp
type IInterface1 = 
    abstract member Method1 : int 

type IInterface2 = 
    abstract member Method2 : int 


type internal SomeType() =
    
    interface IInterface1 with
        member _.Method1 =
            42
        
    interface IInterface2 with
        member this.Method2 =
            (this :> IInterface1).Method1
```

**Expected behavior**
Method1 is renamed everywhere.
**Actual behavior**

**Known workarounds**

Rename manually, hah.

**Comment by 0101** [comment]
Yeah it's incorrect. Self-reference has to count there, because you want to rename that as well. Which also does happen. But finding references on interface methods doesn't find their implementations, I noticed that too and it should be fixed.

**Comment by 0101** [comment]
Turns out I only fixed it for properties, not methods.
