### ISSUE TITLE
Coloring broken on operators starting with `>` in VS

### ISSUE THREAD

**Issue by 0101** [dotnet/fsharp#15388]
Related to https://github.com/dotnet/fsharp/issues/15376 https://github.com/dotnet/fsharp/pull/15386

**Expected behavior**

Same coloring as other operators

**Actual behavior**

![image](https://github.com/dotnet/fsharp/assets/217092/c6b2c53f-73d8-4ef5-a147-c2f80811adb1)

It's not visible that much on default theme, but it's also there.

**Comment by vzarytovskii** [comment]
Duplicate of https://github.com/dotnet/fsharp/issues/3462 likely

**Comment by abelbraaksma** [comment]
I cannot repro this anymore. Not sure what editor this was, from the OP, though.

![image](https://github.com/dotnet/fsharp/assets/16015770/6817e1a0-cd0e-4bba-8f26-4321db2ef257)
