### ISSUE TITLE
Unexpected inference when using seq expression

### ISSUE THREAD

**Issue by BoundedChenn31** [dotnet/fsharp#15390]
In the following code type of `x` is inferenced as `unit` for some reason.
```fs
> let foo x = seq { x };;
val foo: x: unit -> seq<'a>

> let foo x collection = seq { x } |> Seq.append collection;;
val foo: x: unit -> collection: seq<'a> -> seq<'a>
```

**Expected behavior**

`x` is generic. The same as
```fs
> let foo x = [ x ];;
val foo: x: 'a -> 'a list

> let foo x = [| x |];;
val foo: x: 'a -> 'a array
```

**Actual behavior**

Type of `x` is `unit`.

**Known workarounds**

Use explicit yield or specify type of `x` explicitly.
```fs
> let foo x = seq { yield x };;
val foo: x: 'a -> seq<'a>
```

**Related information**

F# Interactive version 12.5.0.0 for F# 7.0
.NET SDK Version: 7.0.304

**Comment by vzarytovskii** [comment]
This is covered in rfc, it seems - https://github.com/fsharp/fslang-design/blob/main/FSharp-4.7/FS-1069-implicit-yields.md

**Comment by 0101** [comment]
This is by design. Changing it would be a breaking change. And it would require a language suggestion.
