### ISSUE TITLE
Inline keyword in member is lost in signature

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#15406]
When generating a signature file the result is somewhat unexpected.

**Repro steps**

```fsharp
module Meh

type Foo() =
    member inline this.Item
        with get (i:int,j: char) : string = ""
        and set (i:int,j: char) (x:string) = printfn "%i %c" i j
```

leads to

```fsharp

module Meh

type Foo =
  
  new: unit -> Foo
  
  member Item: i: int * j: char -> string with get
```

**Expected behaviour**

It needs the `inline` keyword. There is also no setter, but that is a separate issue.

**Actual behaviour**

> Module 'Meh' contains member Foo.Item: i: int * j: char -> string with get but its signature specifies member Foo.Item: i: int * j: char -> string with get The inline flags differ

**Related information**

FCS: FSharpCheckFileResults.GenerateSignature

**Comment by kerams** [comment]
The question is whether it's not an implementation detail. Is inlining relevant to a public contract? I'm inclined to say it matters little to a consumer.
