### ISSUE TITLE
Multiple accessibilities given for property getter or setter is not raised for property

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#15423]
Get and set properties cannot have different visibility for the getter and setter

**Repro steps**

Example:

```fsharp
type Foo() =
    member f.X with internal get (key1, key2) = true and private set (key1, key2) value = ()
    member internal f.Y with get (key1, key2) = true and private set (key1, key2) value = ()
````

**Expected behavior**

Both `X` and `Y` show the same diagnostic (`FS0558`)

**Actual behavior**

`f.X` won't produce any diagnostics and will create an internal getter and setter.

![image](https://github.com/dotnet/fsharp/assets/2621499/a1c2dbfd-42a2-45e5-8d02-696c256be0d2)

While `f.Y` will produce 

![image](https://github.com/dotnet/fsharp/assets/2621499/971c1065-f95e-453f-8ebb-6ac97810d0d4)

**Known workarounds**

\/

**Related information**

Local compiler

**Comment by auduchinok** [comment]
A property declaration may also be split into two, so the getter and the setter would be analysed separately.
And then comes the fact that F# allows overloading properties, so we won't even know if two accessor declarations will belong to the same property until after type checking is done.

**Comment by T-Gro** [comment]
Will be resolved by updating the error message in https://github.com/dotnet/fsharp/pull/15424
