### ISSUE TITLE
ProposeUpperCaseLabel code fix doesn't work for unsaved files

### ISSUE THREAD

**Issue by psfinaki** [dotnet/fsharp#15500]
Repro:

https://github.com/dotnet/fsharp/assets/5451366/daa549be-d3ea-4ae9-a0bf-519e6df2c202

So yeah - once the file is saved the fix becomes applicable. This shouldn't be the case, this is not how the code fixes are supposed to work. Example:

https://github.com/dotnet/fsharp/assets/5451366/3fd6a0c2-3972-4c1e-96e7-966c5179d2ad

**Comment by vzarytovskii** [comment]
Not really a bug, it's not supposed to work, iirc. It's more of the improvement.

**Comment by psfinaki** [comment]
Yeah depends on how you look on it. Other code fixes work like this and, well, VS does offer the code fix for the unsaved document to the end user and then "nothing happens". So it least it looks like a bug :)
