### ISSUE TITLE
Static class is not visible in .fsx while it is in .fs

### ISSUE THREAD

**Issue by Lanayx** [dotnet/fsharp#15536]
Please provide a succinct description of the issue.

**Repro steps**

Create test.fsx file with the following content

```fsharp
#r "nuget: TorchSharp"
open type TorchSharp.torchvision
```

**Expected behavior**

Static class opens successfully, just like in normal .fs file placed inside regular project

**Actual behavior**

![image](https://github.com/dotnet/fsharp/assets/3329606/06056f5c-c8ca-4b2f-959d-5f076d931fc2)

**Known workarounds**

I don't know workarounds for .fsx

**Related information**

Provide any related information (optional):

* Operating system
.NET SDK:
 Version:   7.0.304
 Commit:    7e794e2806

* Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.304\

**Comment by vzarytovskii** [comment]
Both repl, vs, vscode and rider show this. Not entirely sure if it's by design, need to check rfc. Maybe @TIHan knows?

**Comment by Lanayx** [comment]
I don't think it's by design, since it works for other static classes, for example `TorchSharp.torch` is visible and it is a static class as well

**Comment by Lanayx** [comment]
Silly me, I didn't realize there is a separate nuget package for that :( Sorry for bothering, closing the issue

**Comment by Lanayx** [comment]
Silly me, I didn't realize there is a separate nuget package for that :( Sorry for bothering, closing the issue
