### ISSUE TITLE
Error number 3360 is reused for two errors

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#15593]
It seems the same number has somehow ended up being reused for two unrelated errors:
* [parsEqualsMissingInTypeDefinition](https://github.com/dotnet/fsharp/blob/c96b1892804399cf0c88fa264376f9948aa93494/src/Compiler/FSComp.txt#L1529)
* [typrelInterfaceWithConcreteAndVariable](https://github.com/dotnet/fsharp/blob/c96b1892804399cf0c88fa264376f9948aa93494/src/Compiler/FSComp.txt#L1583)

**Comment by psfinaki** [comment]
Should be fixed by #15585?

**Comment by auduchinok** [comment]
Yes, it's no longer used in the grammar. We should probably also remove it from the `FSComp` file?

**Comment by psfinaki** [comment]
I think so. Wonder if we have more duplicates like this.
