### ISSUE TITLE
Enable the new indentation rules

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#15631]
Now, when we have the most of the changes needed for https://github.com/fsharp/fslang-suggestions/issues/1273 merged, we should discuss the strategy for enabling it.

These changes allowed improving the parser significantly, and features like code completion may be further improved quite noticeably. Many of the tests and contributors in this repo use the preview language version, as well as it does the Fantomas team. We're starting to actively test these changes in Rider, and will report if there are any serious issues found. I'm also continuing the work on the parser rules and LexFilter where needed.

* **Should we make it opt-in?**
  Probably not. Doing that would mean that the most of the users, that we want to improve the tooling for, will not get these improvements in their existing daily F#-related work. Only an extremely small fraction of the users will probably enable that, and we want to target as much people as possible when improving the tooling.

* **Should we enable it in project templates only?**
  Probably not. The reasoning is the same as above. We want to improve the quality of code completion, hints, and other features for people who already use F# in their existing projects. Not enabling it in existing code will prevent these people from getting the tooling improvements. People edit existing projects much more than they create new ones, so targeting existing code is more important.

* **Should we enable it in F# 8 by default?**
  If we decide to postpone enabling it, it would mean that the most of these improvements aren't delivered to the users for more than a year from now, which would make it much harder to implement/improve various IDE features without being able to timely see people using them. I'd also make it difficult to develop things with one parsing rules in mind, while users would actually use other rules.

* **This is a breaking change, what can we do to make it easier to upgrade?**
  This change may break some old/rare code. The fix is straightforward, it only needs adding whitespaces, but it should be communicated properly. We can:
  * Write an official post describing these changes
  * Provide a link to the post in the error messages
  * Post links to the post on social media, make it easy to search and so on

**Comment by vzarytovskii** [comment]
For now they're on in F#8 for rc, it would be great if we can make a diagnostic message more detailed. Even mentioning that it can be disabled with specific flag?

wdyt @auduchinok?

**Comment by auduchinok** [comment]
> For now they're on in F#8 for rc, it would be great if we can make a diagnostic message more detailed. Even mentioning that it can be disabled with specific flag?
> 
> wdyt @auduchinok?

Sounds great, I'll think about the message.

**Comment by vzarytovskii** [comment]
> > For now they're on in F#8 for rc, it would be great if we can make a diagnostic message more detailed. Even mentioning that it can be disabled with specific flag?
> > wdyt @auduchinok?
> 
> Sounds great, I'll think about the message.

Ping to when you're back from vacation. We probably should get better explaination message + ways to opt-out before we release.

**Comment by vzarytovskii** [comment]
> What was the outcome of this? Did we turn this on by default?

I believe so, and a flag to opt out.

**Comment by nojaf** [comment]
Great!

**Comment by vzarytovskii** [comment]
> Great!

Thanks for bumping the issue, it fell off my radar it seems.
