### ISSUE TITLE
Please test on windows.vs2022preview.scoutperl.amd64.open queue

### ISSUE THREAD

**Issue by dougbu** [dotnet/fsharp#15664]
# My request

A newer StrawberryPerl version has been released but we are not moving forward w/ updating our `windows.vs*` queues all up until F# and WPF have tested with v5.38.0 RC2.

Actually, StrawberryPerl sim-shipped two versions &mdash; v5.36.1 and v5.38.0. See https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/SP_5380_5361. I'm leaning toward using v5.38.0 because RC2 of that release is already set up for testing in the windows.vs2022preview.scoutperl.amd64.open queue.

See https://helix.dot.net for details of the temporary queue. It should be identical to windows.vs2022preview.amd64.open except for the newer Perl version – 5.38.0.1-RC2 instead of 5.32.1.1.

## Details

1. create a PR that updates the YAML for any pipelines that use `perl` to switch from windows.vs2022preview.amd64.open to windows.vs2022preview.scoutperl.amd64.open
   - Note: There is no internal queue. Leave any use of windows.vs2022preview.scoutperl.amd64 alone or let @dougbu / @dotnet/dnceng know we need an internal temporary queue to test everything.
2. as mentioned in [Teams](https://teams.microsoft.com/l/message/19:a88bb61ffc1a4392ad38ebbc526c86f8@thread.skype/1687905211236?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1687204672157&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=General&createdTime=1687905211236), a few more changes should probably be included in that PR:
   - change `"perl": "5.32.1.1"` to `"perl": "latest"` in global.json
   - remove the `$env:PERL5PATH` variable and its use in eng/build.ps1
   - make sure `$env:NativeToolsOnMachine` is consistently set before calling `InitializeNativeTools`, `init-tools-native.ps1`, or `eng/common`'s `build.ps1` in PowerShell
3. depending on your confidence level, repeat the above for some or all of your live `release/*` branches
4. get all relevant pipelines running w/ the various changes

## When PRs are done

1. Merge the changes in all live `release/*` branches and 'main'. **However**, undo the queue change. The changes in (2) will work fine between now and when we update the regular Windows quues.
2. Close this issue or send email to @dougbu / @dotnet/dnceng and let us know to proceed w/ dotnet/dnceng#246.

Much appreciated❕

**Comment by KevinRansom** [comment]
@dougbu , the ci appears to work with the changes.

However, it doesn't seem as though I can download the perl on a non-domain joined machine, is that how it's supposed to work?

![image](https://github.com/dotnet/fsharp/assets/5175830/a737e6c4-93f3-4a9c-b499-5811fd3768e2)

**Comment by dougbu** [comment]
@KevinRansom sorry, I misread the code. The `latest` option is handled in eng/common/init-tools-native.ps1, not on the server, and apparently doesn't work well except when the files are already on the machine (as they are in the CI). One workaround is to make sure `perl` is on your `$env:Path` before building. A somewhat better option might be to use `5.38.0.1` as the version in global.json and only use `$env:NativeToolsOnMachine` in CI builds. Finally, I could create the blob the code looks for. That costs a bit in storage and I hesitate because it may set an expensive precedent.

Let me know if you want to use the last option.

**Comment by vzarytovskii** [comment]
> @KevinRansom sorry, I misread the code. The `latest` option is handled in eng/common/init-tools-native.ps1, not on the server, and apparently doesn't work well except when the files are already on the machine (as they are in the CI). One workaround is to make sure `perl` is on your `$env:Path` before building. A somewhat better option might be to use `5.38.0.1` as the version in global.json and only use `$env:NativeToolsOnMachine` in CI builds. Finally, I could create the blob the code looks for. That costs a bit in storage and I hesitate because it may set an expensive precedent.
> 
> Let me know if you want to use the last option.

Not being able to download perl outside of corpnet will block our external contributors, so we would prefer to have it available outside, until we get rid of perl dependency (which we're in process of doing).

**Comment by vzarytovskii** [comment]
@dougbu also, thought our normal CI is passing, all of our signed build (release, insertion) pipelines are failing due to that:
https://dev.azure.com/dnceng/internal/_build/results?buildId=2242771&view=results

**Comment by dougbu** [comment]
> Not being able to download perl outside of corpnet will block our external contributors, so we would prefer to have it available outside, until we get rid of perl dependency (which we're in process of doing).

Most of the three options I suggested do this. The first option (installing `perl` before building) is probably the least obvious though many repros have build pre-conditions. Please pick one b/c the current setup in 'main' isn't working.

> @dougbu also, thought our normal CI is passing, all of our signed build (release, insertion) pipelines are failing due to that: https://dev.azure.com/dnceng/internal/_build/results?buildId=2242771&view=results

This appears somewhat unrelated and primarily due to `$env:NativeToolsOnMachine` not being set in your internal builds. Public builds have the variable set in the AzDO UI:
![image](https://github.com/dotnet/fsharp/assets/6431421/843e88d8-20d0-4360-bed7-0d3cf232cbb5)

You could more obviously put that setting in the YAML.

**Comment by vzarytovskii** [comment]
Going to close it. It should be working now, and using machine installed perl in CI and downloaded one locally. Thanks Doug.
