### ISSUE TITLE
[SRTP] do not support fields i.e. `val` constraint

### ISSUE THREAD

**Issue by xperiandri** [dotnet/fsharp#15692]
Please provide a succinct description of the issue.

Having an SRTP constarint
``` F#
<'Number
    when 'Number: (static val MinValue: 'Number)
    and 'Number: (static val MaxValue: 'Number)>
```
will not compile

Provide the steps required to reproduce the problem:

1. Create an SRTP function with type constraint as above
2. Try to pass `Int32` as a type parameter to it

**Expected behavior**

Code build

**Actual behavior**

`FS0697	Invalid constraint`

**Known workarounds**

No

**Related information**

F# 7.0

**Comment by vzarytovskii** [comment]
SRTPs don't work on fields, in spec it mentions member, which is F# member (which is essentially a method or property).

Please create a language suggestion for supporting fields.
