### ISSUE TITLE
F# Symbol is not reported for the outer field when updating a nested field for the second time

### ISSUE THREAD

**Issue by DedSec256** [dotnet/fsharp#15696]
In https://github.com/dotnet/fsharp/pull/14821 by @kerams was implemented new syntax for nested record field copy and update. 

![image](https://github.com/dotnet/fsharp/assets/26364714/a8500585-d796-45ed-a2bd-c3f62a2edc5d)
![image](https://github.com/dotnet/fsharp/assets/26364714/28bace55-619c-4341-ad13-1bde3522e36e)

As you can see in the screenshots, all features (such as highlighting, navigation, etc.) work normally for `A` in `A.Foo`, but not for `A` in `A.Bar` -- because the F# symbol is not reported here.

**Repro steps**

```F#
type RecordA = { Foo: int; Bar: int; Zoo: int }
type RecordB = { A: RecordA }

let f (b: RecordB) = { b with A.Foo = 3; A.Bar = 3 }
```

**Related information**

* .NET 8.0.100-preview.5.23303.2 SDK

**Comment by vzarytovskii** [comment]
@kerams was it also fixed by your fix for the nested update?

**Comment by kerams** [comment]
No. Here we're losing information when merging updates. Reports to the sink happen a little bit later.
