### ISSUE TITLE
Go to definition navigates to usage

### ISSUE THREAD

**Issue by kerams** [dotnet/fsharp#15730]
**Repro steps**

![image](https://github.com/dotnet/fsharp/assets/5063478/2981e786-a2e5-4e9e-8638-970ed4f6496c)

F12

**Expected behavior**

![image](https://github.com/dotnet/fsharp/assets/5063478/25fde7bd-df91-46bf-8c94-0b019126474e)

**Actual behavior**

![image](https://github.com/dotnet/fsharp/assets/5063478/7abd1ce0-0bb4-41e0-9bb1-91a8407a99e4)

**Known workarounds**

Press F12 again, then you're taken to the actual definition point.

**Related information**

VS 17.7.0 Preview 5.0

**Comment by vzarytovskii** [comment]
> **Repro steps**
> 
> ![image](https://github.com/dotnet/fsharp/assets/5063478/2981e786-a2e5-4e9e-8638-970ed4f6496c)
> 
> F12
> 
> **Expected behavior**
> 
> ![image](https://github.com/dotnet/fsharp/assets/5063478/25fde7bd-df91-46bf-8c94-0b019126474e)
> 
> **Actual behavior**
> 
> ![image](https://github.com/dotnet/fsharp/assets/5063478/7abd1ce0-0bb4-41e0-9bb1-91a8407a99e4)
> 
> **Known workarounds**
> 
> Press F12 again, then you're taken to the actual definition point.
> 
> **Related information**
> 
> VS 17.7.0 Preview 5.0

I've noticed it as well, but couldn't catch it.

**Comment by T-Gro** [comment]
Did a few experiments:

- When it did happen, for me it jumped to the first usage of the symbol (consistently)
- I did not manage to reproduce it within a single file (i.e. file I am GTD'ing from is the same as the definition)
- I did not manage to reproduce it for a definition which is not used in its own file (only elsewheer), typically records in type-only files such as SyntaxTrivia.

**Comment by vzarytovskii** [comment]
> Did a few experiments:
> 
> * When it did happen, for me it jumped to the first usage of the symbol (consistently)
> * I did not manage to reproduce it within a single file (i.e. file I am GTD'ing from is the same as the definition)
> * I did not manage to reproduce it for a definition which is not used in its own file (only elsewheer), typically records in type-only files such as SyntaxTrivia.

Yeah, we have the logic in "go-to def", which goes to first one. We should have additional logic which prefers definition.
