### ISSUE TITLE
Unboxing ValueOption is kinda complicated

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/fsharp#15790]
```F#
let returnedValue = box ValueNone
let returnedValue2 = box (Array<byte>.empty |> ValueSome)

unbox<byte array voption> returnedValue //Exception
unbox<obj voption> returnedValue //OK

unbox<byte array voption> returnValue2 //OK
unbox<obj voption> returnValue2 //Exception
```

As demonstrated, you can't just use <obj voption> or <byte array voption> to unbox both of cases in ValueOption, which is supposed to be two sides of the same coin

Suggestion : Allow ```unbox<byte array voption> (box ValueNone)``` without throwing exception

**Comment by En3Tho** [comment]
This is a default .Net behavior, isn't it? Unbox always requires concrete type to work correctly. Here `ValueOption<Array<byte>>` is clearly not a `ValueOption<obj>`

**Comment by Happypig375** [comment]
The Type parameter of ValueOption is not covariant nor contravariant. `obj voption` is not `byte array voption`. Even if this type parameter may be considered as covariant, the CLR only allows type parameter covariance in delegates and interfaces. This is not implementable in F#.

**Comment by Xyncgas** [comment]
I truly appreciate your insights and clarifications. It's quite humbling to acknowledge that I still have much to learn. Your explanation about the nuances of the generic type parameters and how they relate to .Net behavior is enlightening. Thank you for sharing your expertise in such a considerate manner.
