### ISSUE TITLE
Char-Byte outside of ASCII range can be represented in decimal char notation

### ISSUE THREAD

**Issue by Booksbaum** [dotnet/fsharp#15868]
Byte in char form is limited to ASCII range:
```fsharp
> 'a';;
val it: char = 'a'
> int 'a';;
val it: int = 97
> 'a'B;;
val it: byte = 97uy

> 'ú';;
val it: char = 'ú'
> int 'ú';;
val it: int = 250
> 'ú'B;;
  ^^^^
stdin(17,1): error FS1157: This is not a valid byte literal
```

Same limit for UTF16 notation:
```fsharp
> '\u00FA';;
val it: char = 'ú'
> '\u00FA'B;;
  ^^^^^^^^^
stdin(24,1): error FS1157: This is not a valid byte literal
```

BUT: in decimal notation the value can span all of byte range:
```fsharp
> '\250';;
val it: char = 'ú'
> '\250'B;;
val it: byte = 250uy
```
([fable repl](https://fable.io/repl/#?code=NoWAUABFEOQF83NWAdATAVgAyMtGKArllgGICCuAuhAD4B8EADgE4CWAdgC4BmHEAIgCk5AeHCg8UeDABCSfOmxyF0oiQoqwNBs3bc+gkWLDgBcJVnVlR8sLtade-YaKA&html=Q&css=Q); [sharplab](https://sharplab.io/#v2:DYLgZgzgNAJiDUAfA2gWAFAAJuYOQC/cMc8AdAJgFYAGIrHXUgV2uoDEBBOgXU0QD5MABwBOASwB2AFzATMAIgCkHeRgxp62ArgBCxBhRq79W5q07H0vAcPHTZC5avQZ5+Q9TPsVe9DdGSMnJKKkA===))

(numbers over 255 aren't valid: `'\256'B` -> `error FS1157: This is not a valid byte literal`)

(other char notations for byte aren't currently supported. See #15867)

**Expected behavior**

decimal notation and other notations should have same range limits. 

**Actual behavior**

While char & UTF16-hex must be `<128`, decimal can be any byte-value (`<256`).

It's called `ASCII byte` in the [docs](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/literals#literal-types), so the correct range is probably `0..127`. (There's also a [test check](https://github.com/dotnet/fsharp/blob/7a0fb7db5c54ff0a93d3ac95e29960602b10b5b7/tests/fsharpqa/Source/Conformance/LexicalAnalysis/StringsAndCharacters/E_ByteChars02.fs) for error when `>= 128`) And the `255` boundary is then most likely a copy&paste error from [3-digit decimal char](https://github.com/dotnet/fsharp/blob/81c715532ccbbe577f697ae59b9edf232ef793e9/src/Compiler/lex.fsl#L521-L528) 

Though I personally would prefer char byte to allow all of byte range (`0..255`): 
* there's `\u`nicode notation which already signals there's "more" than just ASCII
* slightly strange to have a valid char with a value inside byte range -- but invalid byte char because `>= 128`
* In Byte String array values over `127` are possible: 
  ```fsharp
  > "ú\250\xFA\u00FA\U000000FA"B;;
  val it: byte array = [|250uy; 250uy; 250uy; 250uy; 250uy|]
  ```

<br/>
<br/>

Whatever is desired: I would give it a try fixing/adjusting it (together with #15867). I just need to know what range should be valid. 

<br/>
<br/>

<br/>
<br/>
<br/>

**Related information**

* Operating system: Windows 11 x64
* `dotnet --version`: `7.0.307`, `8.0.100-preview.7.23376.3`

**Comment by 0101** [comment]
Seems like it's by design, `B` denotes an ASCII char. We should probably update the error message to reflect that.
