### ISSUE TITLE
[Feature request] Polymorphism

### ISSUE THREAD

**Issue by pannous** [dotnet/fsharp#15870]
Is there any chance to ever see function polymorphism in F#?
That is the ability to define methods with several signatures:
```
let length (x: string) = x.Length
let length (x: int list) = x.Length
printfn "%A" (length "hello")
```
Polymorphism makes code much cleaner as otherwise cumbersome ad-hoc names (stringLength lengthOfString …) can be completely avoided. Functions like printfn dispatch on generic types within the code but that requires knowing all incoming types in advance. Of cause we have polymorphism through objects, but since F# is meant to be a functional language,  adding Function Polymorphism would make it complete. Could multi dispatch as in Julia ever be an option or would it be too difficult to implement at this stage?

**Comment by kerams** [comment]
I really doubt that is ever going to happen. You can use method overloads though.

```fsharp
type M =
    static member length (x: string) = x.Length
    static member length (x: int list) = x.Length

printfn "%A" (M.length "hello")
```

**Comment by pannous** [comment]
Well that's almost it, one only™ needs to transfer these mechanics to an anonymous invisible global type:
```
type Global =
    static member length (x: string) = x.Length
    static member length (x: int list) = x.Length

printfn "%A" (Global.length "hello")
printfn "%A" (length "hello") // special shorthand
```

**Comment by vzarytovskii** [comment]
I believe it was decided in F# 1.0, but feel free to create a language suggestion over the fslang-suggestions.

**Comment by Happypig375** [comment]
```fs
let inline length (x: ^T) = (^T: (member Length: int) x)
```
?
