### ISSUE TITLE
Build fails with Error FS2014, error: MethodDef not found when using static abstract stuff

### ISSUE THREAD

**Issue by En3Tho** [dotnet/fsharp#15919]
Stumbled upon this recently when trying to make C#-like task builder which only requires the user to define awaiter, builder and task types

**Repro steps**
Extract the archive, try to build the solution
[ClassLibrary1.zip](https://github.com/dotnet/fsharp/files/12504077/ClassLibrary1.zip)

Tried it with net7 and net8 without any luck

**Comment by vzarytovskii** [comment]
To add: it affects only reference assembly generation, turning refassemblies off should be a feasible workaround until it's fixed.

**Comment by En3Tho** [comment]
@vzarytovskii Maybe I did something wrong, but turning off reference assembly generation did not help but the error message changed slightly

**Comment by En3Tho** [comment]
It seems like <ProduceReferenceAssembly> is set to false by default
With explicitly set <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
```
FSC : error FS2014: Проблема при записи двоичного файла "G:\source\repos\En3Tho\FSharpExtensions\FSharpExtensions\StaticAbstractTest\obj\Debug\net7.0\StaticAbstractTest.dll"
: Error in pass3 for type StaticAbstractTest.MyValueTaskMethodBuilder`1,
error: Error in GetMethodRefAsMethodDefIdx for
mref = ("En3Tho.FSharp.ComputationExpressions.Utilities.IAsyncMethodBuilderBase<StaticAbstractTest.MyValueTas kMethodBuilder<'a>>.Create", "StaticAbstractTest.MyValueTaskMethodBuilder`1"),
error: MethodDefNotFound [G:\source\repos\En3Tho\FSharpExtensions\FSharpExtensions\StaticAbstractTest\StaticAbstractTest.fsproj]
```

With explicitly set <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
```
FSC : error FS2014: Проблема при записи двоичного файла "obj\Debug\net7.0\refint\En3Tho.FSharp.ComputationExpressions.dll"
: Error in pass3 for type En3Tho.FSharp.ComputationExpressions.Tasks.MyValueTaskMethodBuilder`1, error: Error in GetMethodRefAsMethodDefIdx
for mref = ("En3Tho.FSharp.ComputationExpressions.Utilities.IAsyncMethodBuilderBase<En3Tho.FSharp.ComputationExpressions.Tasks.MyValueTaskMethodBuilder<'a>>.Create", "En3Tho.FSharp.ComputationExpressions.Tasks.MyValueTaskMethodBuilder`1"),
error: MethodDefNotFound [G:\source\repos\En3Tho\FSharpExtensions\FSharpExtensions\En3Tho.FSharp.ComputationExpressions\En3Tho.FSharp.ComputationExpressions.fsproj]
```

Note that when producing reference assembly, the only difference is "refinit" is in the path

I'm not sure this is a regression because it's reproduceable both on .Net 7 and .Net 8.

**Comment by En3Tho** [comment]
@vzarytovskii I can confirm reference assemblies have nothing to do with this again. I've managed to come up with a minimal repro. This is a clearly compiler bug.

a minimal repro:

```
type IHasStaticAbstractBase<'a> =
    static abstract Boom: unit -> 'a

type IHasStaticAbstractChild<'a> =
    inherit IHasStaticAbstractBase<'a>

type CompilerGoesBoom<'a>() =
    interface IHasStaticAbstractChild<'a> with // this goes boom because inheritance is involved
        static member Boom() = Unchecked.defaultof<'a>

type CompilerDoesNotGoBoom<'a>() =
    interface IHasStaticAbstractBase<'a> with // this does not go boom, direct base interface
        static member Boom() = Unchecked.defaultof<'a>
```

**Comment by gusty** [comment]
Can we change the impact?
I don't think this is low impact at all, if you start using static abstracts chances are that at some point you'll find this bug.
It doesn't look like a corner case.

**Comment by vzarytovskii** [comment]
> Can we change the impact?
> 
> I don't think this is low impact at all, if you start using static abstracts chances are that at some point you'll find this bug.
> 
> It doesn't look like a corner case.

Impact is internal for our own usage only. 

It mostly means it doesn't impact any existing code.

**Comment by En3Tho** [comment]
@vzarytovskii Why do you think it's internal? As I said, reference assembly generation has nothing to do with this. Whole build simply fails if you use inheritance with static abstracts. I found this bug while writing my own code, not while tinkering with core lib or something like that

**Comment by vzarytovskii** [comment]
> Why do you think it's internal?

Why do I think that "impact" label is for internal use only? Well, because it is.

> Anyway, I don't think it's that "low".

Again, it **does not** reflect severity, or importance, or anything.

To reiterate: **PLEASE, DON'T LOOK AT IMPACT TAGS AS IS THEY REFLECT SEVERITY OF BUGS**

**Comment by vzarytovskii** [comment]
# Investigation

## Non-static abstract

### Info

```log
mref.Name: Foo.IHasStaticAbstractBase<'a>.Boom
tref.Name: Foo.CompilerGoesBoom`1
tidx: 4
mdkey.Name: Foo.IHasStaticAbstractBase<'a>.Boom
mdkey.IsStatic: false
idx: 3
```

### Mdefs

```log
{Boom}
{.ctor}
{FSI_0008.Foo.IHasStaticAbstractBase<'a>.Boom}
{main@}
```

### Writing mdefs

```log
1:
    {type FSI_0003.Foo.IHasStaticAbstractBase`1}
    {method Boom}
2:
    {type FSI_0003.Foo.CompilerGoesBoom`1}
    {method .ctor}
3:
    {type FSI_0003.Foo.CompilerGoesBoom`1}
    {method FSI_0003.Foo.IHasStaticAbstractChild<'a>.Boom}
4:
    {type <StartupCode$FSI_0003>.$FSI_0003_Repro}
    {method main@}
```

## Static abstract

### Info

```log
mref.Name: Foo.IHasStaticAbstractBase<'a>.Boom
tref.Name: Foo.CompilerGoesBoom`1
tidx: 4
mdkey.Name: Foo.IHasStaticAbstractBase<'a>.Boom
mdkey.IsStatic: true
idx:
```

### Mdefs

```log
{Boom}
{.ctor}
{FSI_0007.Foo.IHasStaticAbstractChild<'a>.Boom}
{main@}
```

### Writing mdefs

```log
1:
    {type Foo.IHasStaticAbstractBase`1}
    {method Boom}
2:
    {type FSI_0002.Foo.CompilerGoesBoom`1}
    {method .ctor}
3:
    {type FSI_0002.Foo.CompilerGoesBoom`1}
    {method Foo.IHasStaticAbstractBase<'a>.Boom}
4:
    {type <StartupCode$FSI_0002>.$FSI_0002_Repro}
    {method main@}
```
## Differences

Method getting emitted in case of `static abstract` is 

```log
{type FSI_0002.Foo.CompilerGoesBoom`1}
{method Foo.IHasStaticAbstractBase<'a>.Boom}
```

Just `abstract`:

```log
{type FSI_0003.Foo.CompilerGoesBoom`1}
{method FSI_0003.Foo.IHasStaticAbstractChild<'a>.Boom}
```

Lookup is, however, trying to search for `Foo.CompilerGoesBoom'1.Foo.IHasStaticAbstractBase<'a>.Boom`.

**Comment by vzarytovskii** [comment]
The bug is trivial, we don't generate fixups (including method name fixup for the static abstracts) here:
https://github.com/dotnet/fsharp/blob/f88d5d49f617589f4a77a8f4d51ad5c68d943ce6/src/Compiler/CodeGen/IlxGen.fs#L9214-L9221
like we do it for normal slots here:
https://github.com/dotnet/fsharp/blob/f88d5d49f617589f4a77a8f4d51ad5c68d943ce6/src/Compiler/CodeGen/IlxGen.fs#L9227-L9246

**Comment by vzarytovskii** [comment]
That would be the fix, if someone wants to make the fix + few tests:
```diff
diff --git a/src/Compiler/CodeGen/IlxGen.fs b/src/Compiler/CodeGen/IlxGen.fs
index 33b39ce7f..a987b78ab 100644
--- a/src/Compiler/CodeGen/IlxGen.fs
+++ b/src/Compiler/CodeGen/IlxGen.fs
@@ -9212,7 +9212,13 @@ and GenMethodForBinding
                             if not memberInfo.MemberFlags.IsOverrideOrExplicitImpl then
                                 mkILStaticMethod (ilMethTypars, mspec.Name, access, ilParams, ilReturn, ilMethodBody)
                             else // We want to get potential fixups and hidebysig for abstract statics:
-                                let flagFixups = [ fixupStaticAbstractSlotFlags ]
+                                let flagFixups =
+                                    [
+                                        fixupStaticAbstractSlotFlags
+                                        match ComputeMethodImplNameFixupForMemberBinding cenv v with
+                                        | Some nm -> renameMethodDef nm
+                                        | None -> ()
+                                    ]

                                 let mdef =
                                     mkILStaticMethod (ilMethTypars, mspec.Name, access, ilParams, ilReturn, ilMethodBody)
```

Otherwise, I can make it once I'm back.

**Comment by gusty** [comment]
Maybe we should a severity tag.

@vzarytovskii good job finding the root cause. I was researching it as well, but you are miles ahead. I will create a PR with a fix.

**Comment by En3Tho** [comment]
@vzarytovskii Thank you
