### ISSUE TITLE
Codefix improvement for missing `open` directive

### ISSUE THREAD

**Issue by atsapura** [dotnet/fsharp#15920]
When an `open` directive is missing, the first suggestion upon hitting `ctrl+space` is "Convert To Anonymous Record", which rarely is the needed option. Ordering by priority could greatly improve this experience.

**Comment by psfinaki** [comment]
@atsapura okay so good news - this got recently fixed :)

This already works in VS Preview, so coming up to VS GA soon.

https://github.com/dotnet/fsharp/assets/5451366/78e1d71f-f419-4009-8c09-3afceee9344c
