### ISSUE TITLE
Getting nothing from GetAllUsesOfAllSymbols() when using DocumentSource.Custom

### ISSUE THREAD

**Issue by dawedawe** [dotnet/fsharp#15960]
Hey everyone hello @0101,

we're facing an issue with the checker API:

In tests, the `DocumentSource.Custom` is often used when creating an `FSharpChecker`.
Doing something like:
```fsharp
let checkProjectResults = checker.ParseAndCheckProject(opts) |> Async.RunSynchronously
let allSymbolUses = checkProjectResults.GetAllUsesOfAllSymbols()
```
yields no results in `allSymbolUses`.

It seems to be a caching issue, as the usage of `DocumentSource.Custom` means that `useChangeNotifications` will be set to true in the builder which affects the [slots](https://github.com/dotnet/fsharp/blob/1f37bd6a4df33e01036511856c82ec0cd32408a9/src/Compiler/Service/IncrementalBuild.fs#L967).

A workaround is calling `FSharpChecker.NotifyFileChanged` for the files in the project _before_ calling `ParseAndCheckProject()`.

Is this really the expected behaviour when using `DocumentSource.Custom` or something we should document?

**Comment by 0101** [comment]
Hey, so this happens when you check the project for the first time? In general you do need to call `NotifyFileChanged` when a file has changed when using `DocumentSource.Custom`, which is documented. But it's suspicious if you get empty symbol uses. Maybe there's a bug with IncrementalBuilder state initialization or something. I'll have a look.

**Comment by dawedawe** [comment]
> Hey, so this happens when you check the project for the first time?

Well, calling `ParseAndCheckProject` multiple times before the first call to `GetAllUsesOfAllSymbols` makes no difference in this case. The result of `GetAllUsesOfAllSymbols` is still empty.

**Comment by 0101** [comment]
After some experimentation, setting `Notified = true` [in the initial state](https://github.com/dotnet/fsharp/blob/d95e8f3e0c6341780718a30ca86acae3d28a48a6/src/Compiler/Service/IncrementalBuild.fs#L1072) seems to fix it. But I can't yet tell why exactly and if it can have some negative consequences. 

@majocha Do you remember anything about this by any chance?

**Comment by 0101** [comment]
Here's a test for it: https://github.com/dotnet/fsharp/pull/15966 

The Activity traces look the same regardless of initially setting `Notify` to `true` or `false`. Except in the first case symbols are present and in the second one they aren't.

**Comment by 0101** [comment]
Yeah it's a bit strange because everything else seems to work fine. I thought maybe this was somehow causing the bound models to be invalidated so we can't access tcExtras even though it must have been produced by the full project check. Anyway, let's make the change and see what happens :)

**Comment by dawedawe** [comment]
Thanks guys ❤️
