### ISSUE TITLE
got an erreur when running command "dotnet new console -lang F# -o MyFSharpApp -f net7.0"

### ISSUE THREAD

**Issue by Faizou-Aremou** [dotnet/fsharp#15984]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/languages/fsharp-hello-world-tutorial/create
Operating System: unbuntu 20.04

when i ran this command dotnet new console -lang F# -o MyFSharpApp -f net7.0. I got the following error: 
Error: Invalid option(s):
-f net7.0
   'net7.0' is not a valid value for -f. The possible values are:
      net6.0   - Target net6.0

How to fix it ?

**Comment by baronfel** [comment]
You only have the .net 6 SDK installed - you need to figure out how to install .net 7 SDKs onto your system.  I don't remember if .net 7 supports 20.04 from the official feeds - you may need to install Microsoft s packages feed to get .net 7.

I would suggest carefully reading our docs for Linux installs: https://learn.microsoft.com/dotnet/core/install/linux

**Comment by vzarytovskii** [comment]
Going to close it since it's not an F# bug exactly
