### ISSUE TITLE
Graph based checking error with CompilationRepresentationFlags.ModuleSuffix

### ISSUE THREAD

**Issue by kerams** [dotnet/fsharp#15985]
Create a new fsproj, add a.fs, b.fs and c.fs in this order, and enable graph based checking.

a.fs

```fsharp
namespace F.General
```

b.fs

```fsharp
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module F

let br () = ()
```

c.fs

```fsharp
module S

[<EntryPoint>]
let main _ =
    F.br ()
    0
```

Build.

**Expected behavior**

Compiles successfully.

**Actual behavior**

`c.fs(5,5): error FS0039: The value, namespace, type or module 'F' is not defined.` It looks like it has been established that c.fs does not depend on b.fs, and both files are checked in parallel.

**Known workarounds**

Disable graph based checking.

**Related information**

SDK 8.0.100-rc.1.23455.8

**Comment by kerams** [comment]
I know `ModuleSuffix` is not the most most common occurence in F# code (even though an actual project of mine is affected), but the issue seems much more severe than "Impact-Low" - you can even compile source code to 2 completely different programs with graph based checking on and off, however unlikely it is.

**Comment by nojaf** [comment]
@kerams did you extract this from a production scenario?

**Comment by nojaf** [comment]
Thanks, I was curious if you found this in the wild or more synthetically composed this.
Fable compiler won't be affected by this I assume as `--test:GraphBasedChecking` is not yet used in the FCS service layer.
