### ISSUE TITLE
[Bug][Go to metadata] Option<int> is said to be a module instead of a type

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#160]
Opened at [CodePlex]() by [Okayx6](https://www.codeplex.com/site/users/view/OkayX6)

When writing and placing the caret on Option<int>:

``` fsharp
let x: Option<int> = Some 3
```

Intellisense says that Option is a module. 

This prevents our Go to metadata feature to generate the type definition in VFPT. 

![3ae0c252-6df9-11e4-8751-42c825bfb566](https://cloud.githubusercontent.com/assets/5175830/5929043/0a023818-a635-11e4-813f-3fb4f36169fb.png)

See here  [in our Github](https://github.com/fsprojects/VisualFSharpPowerTools/issues/829)

> comments
> antofik wrote Nov 21, 2014 at 3:01 PM [x] 
> Interesting, but system correctly finds time Option<TType_var ?> when building tooltip for "Option", but then some filter function discards it with following comment: "Filter types that are explicitly suppressed from the IntelliSense (such as uppercase "FSharpList", "Option", etc.)" (see ServiceDeclaration.fs:563)
> After removing line service.fs:527 (i.e. call to the RemoveExplicitlySuppressed) everything magically begins to work as it should.
> 
> What was the reason behind this logic?

**Comment by kerams** [comment]
The underlying problem also affects coloring:

![image](https://github.com/dotnet/fsharp/assets/5063478/e6a71806-1e44-4e44-a7f3-bd6393bb6323)

All this is based on captured name resolutions, which may contain multiple values for the same range. I believe we don't report which of them was "used" during type checking back to the sink, so I don't see how we could decide to pick the right item.
