### ISSUE TITLE
Callbacks into DocumentDiagnosticAnalyzer should be determined by DiagnosticAnalyzerCategory

### ISSUE THREAD

**Issue by mavasani** [dotnet/fsharp#16008]
> I can try. But when debugging it, I saw that [AnalyzeSyntaxAsync](https://sourceroslyn.io/#Microsoft.CodeAnalysis.ExternalAccess.FSharp/Diagnostics/IFSharpDocumentDiagnosticAnalyzer.cs,4616a6f10cbf75ed,references) was still being called, just the results that we provided weren't shown.

If it was looking at capabilities then I'd expect it not to be called at all.

_Originally posted by @0101 in https://github.com/dotnet/fsharp/issues/15972#issuecomment-1727396885_

**Comment by mavasani** [comment]
@0101 Can you please port this over to Roslyn repo? I accidentally filed it here.

**Comment by vzarytovskii** [comment]
> @0101 Can you please port this over to Roslyn repo? I accidentally filed it here.

Hm, it only shows me Roslyn-tools, might be some permissions issue?

**Comment by 0101** [comment]
@mavasani we can't move it over to the roslyn repo. You'll have to do it or recreate it there.

**Comment by mavasani** [comment]
Filed https://github.com/dotnet/roslyn/issues/70312. Feel free to close this issue.
