### ISSUE TITLE
FSharp.Core package versions aren't incrementing with each SDK release

### ISSUE THREAD

**Issue by baronfel** [dotnet/fsharp#16014]
The FSharp.Core packages aren't revving with associated SDK/runtime revisions on a monthly cadence. This means that folks using tools like NuGet's lock files can get content hash errors.

A sample of the currently-published versions:

![image](https://github.com/dotnet/fsharp/assets/573979/d812a76a-6b27-4287-ba99-775839ab10a3)

What I note here is that there were 6.0.x versions that were being pushed, but in the 7.x series and onwards we lost this.

**Comment by vzarytovskii** [comment]
We usually bump it/can catch it in CI only if we make changes after previous version got released. So if there were no changes, we won't bump it.

**Comment by nojaf** [comment]
As this very much is a problem and we had to resolve to not using lock files, will there be a `7.0.401` with the fix?

**Comment by vzarytovskii** [comment]
> As this very much is a problem and we had to resolve to not using lock files, will there be a `7.0.401` with the fix?

If it gets inserted in sdk, then yes. So far it wasn't: https://github.com/dotnet/sdk/pull/35666

**Comment by nojaf** [comment]
We no longer have this problem.
