### ISSUE TITLE
Task builder produces warning if there are too many bindings inside IF branch

### ISSUE THREAD

**Issue by Szer** [dotnet/fsharp#16068]
build in **RELEASE** (debug is fine)
`dotnet build -c Release`

Reproducable on SDKs
- 7.0.401
- 8.0.100-rc.1

```fsharp
let repro() = task {
    if true then
        let c1 = failwith ""
        let c2 = failwith ""
        let c3 = failwith ""
        let c4 = failwith ""
        let c5 = failwith ""
        let c6 = failwith ""
        let c7 = failwith ""
        let c8 = failwith ""
        let c8 = failwith ""
        let c10 = failwith ""
        let c11 = failwith ""
        let c12 = failwith ""
        let c13 = failwith ""
        let c14 = failwith ""
        let c15 = failwith ""
        let c16 = failwith ""
        let c17 = failwith ""
        let c18 = failwith ""
        let c19 = failwith ""
        let c20 = failwith ""
        let c21 = failwith ""
        let c22 = failwith ""
        let c23 = failwith ""
        let c24 = failwith ""
        let c25 = failwith ""
        let c26 = failwith ""
        let c27 = failwith ""
        let c28 = failwith ""
        let c29 = failwith ""
        let c30 = failwith ""
        let c31 = failwith ""
        let c32 = failwith ""
        let c33 = failwith ""
        ()
}
```

**Expected behavior**

Code compiles fine

**Actual behavior**

warning FS3511: This state machine is not statically compilable. A resumable code invocation at '(2,14--2,18)' could not be reduced. An alternative d 
ynamic implementation will be used, which may be slower. Consider adjusting your code to ensure this state machine is statically compilable, or else suppress this warning.

**Known workarounds**

- delete ANY binding from IF
- OR delete IF

**Related information**

* Win 10
* NET SDK 7.0.401

**Comment by kerams** [comment]
https://github.com/dotnet/fsharp/issues/12839

**Comment by Szer** [comment]
@kerams there is no record though, only bindings :)

**Comment by vzarytovskii** [comment]
This particular issue is happening because we decide to split sub expression (in this case let-in) in `ComputeSplitToMethodCondition`, and don't reduce it properly in `LowerStateMachines`, and it ends up in non-reducible `ResumableCodeInvoke` at certain point. Probably additional expression reducing is the right way to go (as @kerams suggested in the other issue).
