### ISSUE TITLE
Alt+Enter does not work to run selected line in .fsx files

### ISSUE THREAD

**Issue by profhsgill** [dotnet/fsharp#16063]
Alt+Enter key combination does not cause the line (or selected code lines) to run in interactive window.

However, right clicking and then selecting "Execute in Interactive" works.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Open Visual Studio 2022 Community Edition
2. Create a new project
3. Select F# Console App
4. Give the Project any name, for example 'ConsoleApp2'
5. Click Next
6. Framework is selected as .Net 6.0
7. Click Create
8. Default Program.fs file is opened
9. It has the lines

// For more information see https://aka.ms/fsharp-console-apps
printfn "Hello from F#"

10. Put cursor on printfn line and press Alt+Enter
11. The Interactive Panel shows the printout as expected ...... Hello from F#
12. Close Visual Studio
13. Reopen Visual Studio
14. Under 'Open Recent' click on the same solution 'ConsoleApp2.sln' 
15. Program.fs opens again
16. Put the cursor on printfn "Hello from F#", and this time the line does not run in Interactive Window
However, if one right clicks and selects "Execute in Interactive" it will get executed.
The Alt+Enter combination appears next to "Execute in Interactive" but the key combination does not work.

* Operating system: Windows 10 64 bit Enterprise Edition
* .NET Runtime kind (.NET Core, .NET Framework, Mono) .Net 6 was selected during creation of solution
* Editing Tools (e.g. Visual Studio Version, Visual Studio) : Visual Studio

**Comment by abonie** [comment]
Repros with VS 17.8.0 Preview 3.0 [34124.27.main] and sdk 8.0.100-rc.1.23455.8

**Comment by gusty** [comment]
I have the same problem in: Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.8.0 Preview 2.0
It's really annoying.

**Comment by vzarytovskii** [comment]
@profhsgill @gusty could you please check if the shortcut is still in the settings? It seems that vs is resetting it for some reason?

**Comment by profhsgill** [comment]
Thank you for helping.

I have checked and the bindings are intact. I even added Alt+Enter binding under 'Global' to see if that will work, but it did not. I am attaching screen shots.

I have even uninstalled and reinstalled VS (and deleted all files manually to remove any traces of VS under AppData -> Local -> Microsoft -> VisualStudio folder), but that did not help either.

![keyboard binding](https://github.com/dotnet/fsharp/assets/87943630/9a2f8200-85e3-49a1-9da7-ceaa6a254792)

![right click](https://github.com/dotnet/fsharp/assets/87943630/eb0c6d48-fedc-40b5-abd0-19ea76d26d16)

**Comment by profhsgill** [comment]
It seems the problem is in the "Solution". In other words

1) Open VS
2) Click on "Continue without code" (Don't create any solution)
3) File -> New -> File -> F# Source File (or F# Script File)
4) type some code, for example printfn "Hello F#"
5) Alt+Enter ----- code runs
6) Save file
7) Close VS
8) Open VS, again with option "Continue without code"
9) File -> Open -> File -> Select the same file and open it
10) Alt+Enter works again and the code is run in Interactive Window.

**Comment by abonie** [comment]
@profhsgill would you please check which version of VS you have?

**Comment by profhsgill** [comment]
Here are version details

![version](https://github.com/dotnet/fsharp/assets/87943630/a6422971-8a9a-433a-90c9-c6fc10373cbb)

**Comment by abonie** [comment]
Not sure what the fix is going to be yet, but the issue seems to be related to this preview feature:
![image](https://github.com/dotnet/fsharp/assets/20281641/1046cefc-ac5f-4ad2-a1da-d86be2487028)
That is, after unchecking this flag, it no longer repros for me.

**Comment by profhsgill** [comment]
My version did not have this option box. So I updated to 17.8.0 Preview 2. However, I still do not see this option under 'Preview Features'.

Maybe we can just leave it for now and hopefully it will get fixed in a future release. I will switch to VS Code for now.

![Picture1](https://github.com/dotnet/fsharp/assets/87943630/19e03f3d-62bf-4e8f-a299-705b94699af3)

**Comment by abonie** [comment]
Thanks for checking @profhsgill , I have just realized the same (i.e. the flag is not in public preview). I am talking with VS team to help investigate this issue.

**Comment by abonie** [comment]
Turns out the fix is going to be fully on the VS team's side. We can keep this as a tracking issue, to make sure we follow up if needed.

**Comment by profhsgill** [comment]
Yes, let's please keep it as a tracking issue. Thank you for your help.

**Comment by abonie** [comment]
I believe this is fixed in VS Version 17.8.0 Preview 5.0. Closing the issue, but please @ me here if it doesn't work for you under this version.
