### ISSUE TITLE
error in documentation of List.concat

### ISSUE THREAD

**Issue by aski-codes** [dotnet/fsharp#16072]
In the example text for List.concat, semicolons are missing, it should look as below

let input = [ [1;2];
               [3;4;5];
               [6;7;8;9] ]
input |> List.concat

**Comment by Martin521** [comment]
Do you have proper indentation in line 2 and 3? What is the error message?

**Comment by aski-codes** [comment]
If I do a straight copy, I get:

"(4,2): error FS0010: Unexpected identifier in binding. Expected incomplete structured construct at or before this point or other token."

It looks exactly like the web page, but I noticed a blank starting line 4. If I remove it, so that "input" in line 4 aligns with "let" in line 1, I instead get:

"(1,15): error FS3217: This expression is not a function and cannot be applied. Did you intend to access the indexer via 'expr[index]'?"

<img width="279" alt="billede" src="https://github.com/dotnet/fsharp/assets/145867884/15cc665f-1731-478c-a6ed-2d2fea030199">

**Comment by smoothdeveloper** [comment]
I think we'd want the sample adjusted like this:
```fsharp
let input = 
  [ 
    [1;2]
    [3;4;5]
    [6;7;8;9] 
  ]
input |> List.concat
```

@aski-codes would you contribute a PR to fix the documentation?

**Comment by aski-codes** [comment]
That works, thanks!

**Comment by aski-codes** [comment]
I don't see the example in the source code, after pressing the GitHub button ?! (Sorry if this is a newbie mistake)

**Comment by Martin521** [comment]
> I think we'd want the sample adjusted like this:
> 
> ```fsharp
> let input = 
>   [ 
>     [1;2]
>     [3;4;5]
>     [6;7;8;9] 
>   ]
> input |> List.concat
> ```
> 
I agree this is nicer. However, the original is not incorrect. You just have to be careful with indentation, like this:
```
let input = [ [1;2] 
              [3;4;5] 
              [6;7;8;9] ] 
```

**Comment by vzarytovskii** [comment]
> @vzarytovskii could someone add the proper invocation of fsdocs for this repository to DEVGUIDE.md?


I'm not sure I understand the ask here

**Comment by aski-codes** [comment]
This is actually how it looks in .fsi – so that means the problem is a parsing issue somehow? I think I'm getting out of my depth here...
> 
> I agree this is nicer. However, the original is not incorrect. You just have to be careful with indentation, like this:
> 
> ```
> let input = [ [1;2] 
>               [3;4;5] 
>               [6;7;8;9] ]
> input |> List.concat
> ```
> 
> But, certainly, the error messages are confusing.

**Comment by Martin521** [comment]
It is just that in the screen shot that you pasted above, there is one additional space in each of the lines 2, 3 and 4. They make the code invalid. The three lists have to be exactly aligned and the two expressions (line 1 and 4) have to be exactly aligned.

To explain the error messages: The additional indentation of line 2 makes the second list look like an argument to a function, but [1;2] is not a function. The additional indentation of line 4 makes that line look like a continuation of the right-hand side of the let binding.

**Comment by aski-codes** [comment]
Also in the example code...

<img width="236" alt="billede" src="https://github.com/dotnet/fsharp/assets/145867884/6f23b835-a6cf-4eb1-a171-222f87b5c092">

**Comment by smoothdeveloper** [comment]
@vzarytovskii how do we run the `fsdocs` command to show up the browser with freshly compiled `FSharp.Core` documentation in this repository?

I think this should be an entry in the DEVGUIDE.md.

**Comment by Martin521** [comment]
> Also in the example code...
> <img alt="billede" width="236" src="https://user-images.githubusercontent.com/145867884/272703519-6f23b835-a6cf-4eb1-a171-222f87b5c092.png">

Wow, yes, it seems the examples are shown on fsharp.github.io in a non-fixed-width font. That's not nice. If you carefully copy and paste (including the space at the beginning of row 1), you get correct code though. But indeed a monospace font should be used, and also the extra space at the beginning of each line is not nice.

**Comment by aski-codes** [comment]
Thanks @Martin521 , that sounds sensible. Do you know how to let the authors know?

**Comment by Martin521** [comment]
AFAIK [this](https://github.com/fsprojects/FSharp.Formatting) is the tool.

**Comment by aski-codes** [comment]
Thanks! https://github.com/fsprojects/FSharp.Formatting/issues/850

**Comment by nojaf** [comment]
I guess somewhere in this repository a note could be made that the F# Core docs are hosted on https://github.com/fsharp/fsharp-core-docs/.

The release of the documentation is [currently broken](https://github.com/fsharp/fsharp-core-docs/actions), this is due to https://github.com/dotnet/fsharp/issues/16014.
We would need a proper `FSharp.Core` version first.

**Comment by aski-codes** [comment]
Looks good here, now, thanks a bunch!
