### ISSUE TITLE
Taskbuilder performance issue

### ISSUE THREAD

**Issue by Lanayx** [dotnet/fsharp#16127]
I've upgraded Pulsar.Client to .NET 8 and made some performance optimizations. However once checked published nuget version from C# and F#, there is a big performance gap, which should not exist in identical code

Reference fsharp: https://github.com/Lanayx/PulsarClientPerfTester/blob/fsExample/PulsarClientDotnet/ProducerFs/Program.fs
Reference csharp: https://github.com/Lanayx/PulsarClientPerfTester/blob/fsExample/PulsarClientDotnet/Producer/Program.cs

To reproduce:
1) Install .net8
2) Run [PerfTesterServer ](https://github.com/Lanayx/PulsarClientPerfTester/tree/fsExample/PerfTester.Server) in Release mode
3) Run the examples above in Release

On my machine I get
C# `Sent 10000000 messages in 12137ms. Speed: 823K msg/s`
F# `Sent 10000000 messages in 15864ms. Speed: 630K msg/s`

Which means F# taskbuilder is 30% slower (since the code is identical otherwise)

I'm attaching flame graphs, blue area is the effective workload, which is the same in both cases

CsharpFlame
![image](https://github.com/dotnet/fsharp/assets/3329606/a4168477-13ab-4529-8a17-caeb1dafd04d)
FsharpFlame
![image](https://github.com/dotnet/fsharp/assets/3329606/7718020d-db64-472d-8ad4-a59e8e6d2cc2)

**Comment by vzarytovskii** [comment]
It is known, was slower right from beginning, not a bug

**Comment by vzarytovskii** [comment]
I will convert it to improvement. It's not a big, just difference between codegen

**Comment by En3Tho** [comment]
Simple `for` loops are converted to additional `IEnumerables`. This might be the case.
A possible workaround is to use `let mutable x = ... while ...`. It create an `FSharpRef<int>` field instead of a just `int` but still better than an IEnumerator.

**Comment by vzarytovskii** [comment]
F# uses dynamic implementations, state machine code is not being emitted

**Comment by Lanayx** [comment]
I've change the code (extracted into module), so the warning which I didn't notice before - "This state machine is not statically compilable" went away
F# Sent 10000000 messages in 12057ms. Speed: 829K msg/s
C# Sent 10000000 messages in 12135ms. Speed: 824K msg/s
So, performance is identical, I'm good to close the ticket
