### ISSUE TITLE
`assembly.GetTypes()` now includes System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes 

### ISSUE THREAD

**Issue by Smaug123** [dotnet/fsharp#16141]
### Describe the bug

Before .NET 7, `assembly.GetTypes()` returned only types that were defined in my assembly. Now, if the assembly in question is a library and not an executable, it additionally returns `System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes` and `System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute`.

This is true as of SDK 7.0.400; I have a vague recollection that it *wasn't* true of some earlier SDKs in the 7.0 series, but not sure about that.

I'm afraid I have absolutely no idea where this issue should go; `dotnet/sdk` is my best guess.

### To Reproduce

`Lib/Library1.fsproj`:
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="Thing.fs" />
    </ItemGroup>
</Project>
```

`Lib/Thing.fs`:
```fsharp
namespace Foo
type Foo = Foo
```

`App/Program.fs`:
```
namespace Foo

module Program =
    [<EntryPoint>]
    let main _ =
        typeof<Foo>.Assembly.GetTypes ()
        |> Array.iter (fun ty -> System.Console.WriteLine ty.FullName)
        0
```

`App/App.fsproj`:
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
      <Compile Include="Program.fs"/>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Lib\Library1.fsproj" />
    </ItemGroup>
</Project>
```

Running the app gives the following output, demonstrating the problem by its final two lines:

```
Lib.ThisAssembly
Foo.Foo
<StartupCode$Lib>.$Thing
<StartupCode$Lib>.$Lib.Version
<StartupCode$Lib>.$Lib.AssemblyInfo
<StartupCode$Lib>.$.NETStandard\,Version=v2.0.AssemblyAttributes
System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes
System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute
```

### Further technical details

`dotnet --info`:

```
.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /nix/store/27hjfsgvv7bklnid729j27kifig070lb-dotnet-sdk-7.0.400/sdk/7.0.400/

Host:
  Version:      7.0.10
  Architecture: arm64
  Commit:       a6dbb800a4

.NET SDKs installed:
  7.0.400 [/nix/store/27hjfsgvv7bklnid729j27kifig070lb-dotnet-sdk-7.0.400/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.10 [/nix/store/27hjfsgvv7bklnid729j27kifig070lb-dotnet-sdk-7.0.400/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.10 [/nix/store/27hjfsgvv7bklnid729j27kifig070lb-dotnet-sdk-7.0.400/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download      
```

No IDE necessary.

**Comment by jkotas** [comment]
The new attribute types are auto-generated by F# compiler.

**Comment by vzarytovskii** [comment]
Attributes are auto generated if not found for the target sdk/runtime. We do it for multiple attributes. 

I'm not entirely sure I understand what's the issue here?

**Comment by Smaug123** [comment]
Could it be annotated with `CompilerGeneratedAttribute`?

**Comment by T-Gro** [comment]
We can.
Beware (I saw your PR in the ApiSurface PR which tries to exclude by name), there are more attributes like this which the compiler (both F# as well as Roslyn) includes conditionally, and more are coming in WIP PRs.

Have a look here:
https://sharplab.io/#v2:D4AQTAjAsAUCDMACciDCiDetE+UkALIgLIAUAlJtrgL6w1A=

The combination of:
```
    [CompilerGenerated]
    [Microsoft.CodeAnalysis.Embedded]
```
is something that can could be added (we do not generate the Embedded definition itself as of now, we would have to start doing it)

**Comment by vzarytovskii** [comment]
I don't personally think we should include `Microsoft.CodeAnalysis.Embedded` since it's entirely Roslyn thing, and part of Roslyn sdk.

**Comment by T-Gro** [comment]
Which then leaves the `CompilerGeneratedAttribute`.
I wanted to add it in, but realized it is being added already - to both the `enum` as well as the `attribute`.

@Smaug123: I think that the safest approach would be to filter out types having the `CompilerGeneratedAttribute` attribute (you should compare the namespace+type name and not via full blown System.Type identity, because the type can come from a different assembly at runtime)

**Comment by Smaug123** [comment]
I'll check this evening again, but I was pretty sure in my check last night that the DynamicDependencyAttribute did not have that attribute :/

**Comment by Smaug123** [comment]
Yeah, I just checked again, and `System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute, ApiSurface.DocumentationSample, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null` has no CustomAttributes at all. I guess that's the bug here?

**Comment by vzarytovskii** [comment]
> Yeah, I just checked again, and `System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute, ApiSurface.DocumentationSample, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null` has no CustomAttributes at all. I guess that's the bug here?

It's not generated for all custom attributes it seems, not e bug per se, but here's a pr for generating it - https://github.com/dotnet/fsharp/pull/16145
