### ISSUE TITLE
New copy-and-update warnings in minor update to 7.0.403

### ISSUE THREAD

**Issue by forki** [dotnet/fsharp#16182]
I just updated to .NET SDK 7.0.403 and we see LOTS of new warnings. Things like:

` warning FSHARP: This copy-and-update record expression changes all fields of record type 'MyRecordType'. Consider using the record construction syntax instead. (code 3560)`

Is this expected? @vzarytovskii I thought copy-and-update is scheduled for .NET 8?!

**Comment by vzarytovskii** [comment]
It supposed to, for sure, @baronfel I see that F# compiler inserted into 7.0.403 is from https://github.com/dotnet/fsharp/commit/0e4717

When I run fsi with this version, the following works:
```fsharp
> type R = { X: int };;
type R =
  { X: int }

> let x = { X=42 };;
val x: R = { X = 42 }

> let y = { x with X=41 };;
val y: R = { X = 41 }
```

**Comment by forki** [comment]
OK I think I found the issue. It's probably fable dotnet tool 4.4 - I'll reopen over there
