### ISSUE TITLE
Build error when updating nested record property with the same name as a type

### ISSUE THREAD

**Issue by landy** [dotnet/fsharp#16180]
When updating the record using the new nested update syntax, it results in a compilation error when the field has the same name as another record type.

**Repro steps**
code like this produces an error:
```
type Author = {
    Name: string
    YearBorn: int
}
type Book = {
    Title: string
    Year: int
    Author: Author
}

let oneBook = { Title = "Book1"; Year = 2000; Author = { Name = "Author1"; YearBorn = 1950 } }
let updatedBook = {oneBook with Author.Name = "Author1Updated"}
```

This code results in build error `  Program.fs(25, 19): [FS0001] This expression was expected to have type 'Book' but here has type 'Author'`

**Expected behavior**

The code should result in a successful compilation

**Actual behavior**

Build fails

**Known workarounds**

Changing the name of the field to something unique.

**Related information**

Provide any related information (optional):

* MacOS 14.0
* 8.0.0-rc.2.23479.6
* JetBrains Rider 2023.3 EAP 4
```
<PropertyGroup>
  <OutputType>Exe</OutputType>
  <TargetFramework>net8.0</TargetFramework>
  <LangVersion>preview</LangVersion>
</PropertyGroup>
```

**Comment by kerams** [comment]
This is expected, you need to qualify the property - `{ oneBook with Book.Author.Name ...`

**Comment by landy** [comment]
Aaaha ok. Thank you for the clarification

**Comment by auduchinok** [comment]
Could we do something like `{oneBook with _.Author.Name = "Author1Updated"}` as a workaround, since we have `_` for properties now? 😅

**Comment by vzarytovskii** [comment]
@T-Gro since you're on the blogpost

**Comment by T-Gro** [comment]
Will add it, also including the easier (compared to changing field names) workaround:
```fsharp
let updatedBook = {oneBook with Book.Author.Name = "Author1Updated"}
```

**Comment by DedSec256** [comment]
```F#
module A =
    type Author = {
        Name: string
        YearBorn: int
    }
    type Book = {
        Title: string
        Year: int
        Author: Author
    }

let oneBook = { A.Book.Title = "Book1"; A.Book.Year = 2000; A.Book.Author = { Name = "Author1"; YearBorn = 1950 } }
let updatedBook = {oneBook with Author.Name = "Author1Updated"}
```


It's interesting that if you put records in a separate non-imported module, the compilation will be successful.

![image](https://github.com/dotnet/fsharp/assets/26364714/8e6560e6-bf84-441c-8b5f-c30bc7bf1ce3)
