### ISSUE TITLE
Graph Typechecking issue on latest main on macOS

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#16203]
When building latest main (with rc1), I get the following issue when enabling experimental features:
```log
> FSHARP_EXPERIMENTAL_FEATURES=1 dotnet build ./FSharp.Compiler.Service.sln
FSC : error FS0193: The module/namespace 'Seq' from compilation unit 'FSharp.Core' did not contain the val 'ValLinkagePartialKey(toArray)' [/Users/u/code/fsharp/src/FSharp.Core/FSharp.Core.fsproj::TargetFramework=netstandard2.1]
    0 Warning(s)
    1 Error(s)
```

Not sure if it's related to graph type checker or anything else.

fyi @nojaf @safesparrow @0101

**Comment by nojaf** [comment]
Sounds a lot like you are trying it for FSharp.Core, we disabled this in https://github.com/dotnet/fsharp/pull/15838

**Comment by vzarytovskii** [comment]
> Sounds a lot like you are trying it for FSharp.Core, we disabled this in #15838

Alright, tried it with `rc2` and it seems to be fixed, thanks and sorry for bothering.
