### ISSUE TITLE
Object expressions don't work with IWSAMs

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#16213]
```fsharp
type IOperation =
        static abstract member Execute: unit -> unit

let _ =
    { new IOperation with
        static member Execute() = ()
        //member _.Execute() = ()
    }
```

Results in internal exception.

Should provide meaningful message instead, or parse error.

**Comment by edgarfgp** [comment]
This will be great to fix too :)

**Comment by vzarytovskii** [comment]
Well, it works with `member Foo() =` (without _ or static). But to fix it we'll need to change expressions we use (likely), which may affect a bunch of other things.

The fix should be easy, however, might affect a bunch more things.

**Comment by vzarytovskii** [comment]
Nvm it's irrelevant issue, since static method implementation doesn't make much sense in object expressions, can't access it from instance.

**Comment by 0101** [comment]
Well it still shouldn't cause an internal exception when someone writes it, rather give a proper diagnostic.

**Comment by edgarfgp** [comment]
> Well it still shouldn't cause an internal exception when someone writes it, rather give a proper diagnostic.

Agreed. We can add a similar diagnostic that https://github.com/dotnet/fsharp/pull/14555/files. Happy to help with this :)

**Comment by vzarytovskii** [comment]
> Well it still shouldn't cause an internal exception when someone writes it, rather give a proper diagnostic.

Only in debug = we don't care.

**Comment by vzarytovskii** [comment]
I actually believe in release it'll be a proper diagnostic.

**Comment by edgarfgp** [comment]
Just tried :

dotnet run -c Release
Program.fs(19,27): error FS0073: internal error: un
expected member binding [C:\Users\EdgarGonzalez\RiderProjects\ConsoleApp1\ConsoleApp1\ConsoleApp1.fsproj]

**Comment by vzarytovskii** [comment]
> Just tried :
> 
> 
> 
> dotnet run -c Release
> 
> Program.fs(19,27): error FS0073: internal error: un
> 
> expected member binding ConsoleApp1.fsproj] 

Hm, I swear I tested it just before leaving the office and it was telling me something about unexpected leyword or something.

Alright then, we should just provide something meaningful.

**Comment by edgarfgp** [comment]
Reopening this to provide a meaningful error message ?

**Comment by edgarfgp** [comment]
Will raise a PR to fix this :)
