### ISSUE TITLE
No completion for unfinished shorthand lambda

### ISSUE THREAD

**Issue by DedSec256** [dotnet/fsharp#16221]
The parser lacks recovery rules for shorthand lambdas, so completion does not work in this code. It makes writing new shorthand lambdas difficult.

```fsharp
[1] |> List.map _.
```

![image](https://github.com/dotnet/fsharp/assets/26364714/aaf771f9-02f0-4c7d-9845-b3943cdaf4b1)

**Comment by T-Gro** [comment]
Done via https://github.com/dotnet/fsharp/pull/16238
