### ISSUE TITLE
Go to definition - Source Link/decompiled source

### ISSUE THREAD

**Issue by kerams** [dotnet/fsharp#16229]
When hitting F12 on a symbol defined in an external assembly, a file with F# signatures is shown. This is fine, but more often than not, I want to see actual method bodies.

Current state in C# projects
- if Source Link is available, it is shown
- otherwise decompiled C# code is shown (even in the case of F# assemblies)

Proposal for F# projects
- if Source Link is available, show it (C# or F#, depending on the assembly)
- otherwise show decompiled C# (even in the case of F# assemblies) or F# metadata depending on a VS setting
- ideally it should also be possible to step into such code, but that's a separate concern, really

**Comment by psfinaki** [comment]
Any idea on how is this implemented in C# or where to start?

**Comment by cataggar** [comment]
I opened Develop Community [Visual F# Go to definition from Source Link](https://developercommunity.visualstudio.com/t/Visual-F-Go-to-definition-from-Source-L/10733723) in order to get a work item that I can link to as a planning dependency.
