### ISSUE TITLE
Compilation error from nested record field update

### ISSUE THREAD

**Issue by DedSec256** [dotnet/fsharp#16237]
**Repro steps**

```fsharp
type Record1 = { Foo: int; Bar: int; }

[<AutoOpen>]
module Module =
    type Record2 = { Foo: Record1 }
    let item: Record2 = Unchecked.defaultof<Record2>

ignore { item        with Foo.Foo = 3 }
ignore { Module.item with Foo.Foo = 3 }
```

![image](https://github.com/dotnet/fsharp/assets/26364714/293df83b-4edd-491f-a450-1049f4342cf5)

`{ Module.item with Foo.Foo = 3 }` should be compiled successfully, 
by analogy with  `{ item with Foo.Foo = 3 }`

**Related information**

* .NET 8.0.100-rc.2.23502.2

**Comment by psfinaki** [comment]
Hmm do you think this can be worked around in all such cases - as in the issue description example?

**Comment by kerams** [comment]
Yes, you just have to use a simple, dotless identifier - no other expression will work right now. So the workaround is to manually make a `let`-binding like in the snippet above.

**Comment by psfinaki** [comment]
Alright. Well, that's not the end of the world. But yeah it's probably worth starting collecting those into some known issues bucket, @vzarytovskii.
