### ISSUE TITLE
F# 8 cannot do math?

### ISSUE THREAD

**Issue by Thorium** [dotnet/fsharp#16256]
![image](https://github.com/dotnet/fsharp/assets/229355/282be431-bdc1-41c0-9a25-ceb5f57769a0)

Is it using ChatGTP to calculations?

Version:
Microsoft Visual Studio Professional 2022 (64-bit) 
Version 17.7.4

dotnet 8.0.100-rc.1.23463.5
.Net Framework 4.8.09032

**Comment by Happypig375** [comment]
ChatGTP 🤔

**Comment by kerams** [comment]
Integer overflow.

**Comment by Thorium** [comment]
without any warnings?

**Comment by Thorium** [comment]
I tried to teach my kid that you can use computer to do calculations... :-P

**Comment by kerams** [comment]
You get errors for literals. Operations like the above are not checked at compile time. Maybe they could if all operands are constants? I don't know. There's also `Checked.(*) 100000 100000`, which will thow.

**Comment by Happypig375** [comment]
or you can `open Checked`

**Comment by Thorium** [comment]
So better to buy a pocket calculator I guess.

**Comment by Happypig375** [comment]
@Thorium you can do `100000I * 100000I` for use of `bigint` which can do integer operations with unlimited range.

**Comment by smoothdeveloper** [comment]
also 

> dotnet fsi --checked+

**Comment by Thorium** [comment]
I think integer overflow is an excuse.
Why is performance more important than correctness by default?

Use case, when a kid tries a programming language for first time: 
> What is 2 * 3? 6, ok, what is 3 * 4 + 1? 15. Then what is 100 * 100? 10 000. Then what is 100 000 * 100 000, how many zeros? What?

Javascript doesn't have the issue:

![image](https://github.com/dotnet/fsharp/assets/229355/251c8528-883c-49bf-bf63-f7683f75d893)
I bet Python doesn't have it either. So is it just that F# is not good for beginners?

So if it's only .NET issue, let's see how C# does handle the case? Better than F#:
![image](https://github.com/dotnet/fsharp/assets/229355/4237d1e0-d59f-4776-b0d4-8e2ebe2ba84a)

**Comment by kerams** [comment]
>Javascript doesn't have the issue:

Excuse me, but that is such a dumb argument

![image](https://github.com/dotnet/fsharp/assets/5063478/adc105fd-269f-4809-9754-543bf52f2305)

**Comment by Thorium** [comment]
Defending other Javascript behaviours would be off-topic.
