### ISSUE TITLE
New case for FS3186: An error occurred while reading the F# metadata node

### ISSUE THREAD

**Issue by dgchurchill** [dotnet/fsharp#1626]
This is a new case that triggers the "FS3186: An error occurred while reading the F# metadata node..." error previously reported in #592 and #631. It's unlikely to be worth fixing this case itself but I'm reporting it in case it helps identify other corner-cases in the metadata generation.
#### Repro steps

The error can be triggered by compiling an assembly with a method that has a `[<DefaultParameterValue(null)>]` attribute on one of its parameters, and then referencing that assembly.

e.g.

Compile this:

```
namespace Namespace1
open System.Runtime.InteropServices

type Interface1 = 
    abstract Method1 : [<DefaultParameterValue(null)>] arg1 : obj -> unit
```

Then reference it in F# Interactive:

```
Microsoft (R) F# Interactive version 14.0.23413.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> #r "Bad.dll";;


unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 0 in table 'itypars' of assembly 'Bad, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.

--> Referenced 'Bad.dll'
```
#### Expected behavior

The compiler should either fail when compiling `[<DefaultParameterValue(null)>]` or produce correct metadata. However also see #96 -- `DefaultParameterValue` is not actually supported by the F# compiler. So no one can be using this, and in this case could use the `[<Optional>]` attribute and deal with `Type.Missing` anyway.
#### Related information

Tested using `Microsoft (R) F# Compiler version 14.0.23413.0`

**Comment by dsyme** [comment]
Still repros on master

**Comment by kurtschelfthout** [comment]
I bet #1812 fixes this but I will check.

**Comment by kurtschelfthout** [comment]
I was wrong; this has nothing to do with DefaultParameterValue per se. I think the compiler infers a type argument because of the `null` but half-asses it or something along those lines. This also triggers the bug:

```
namespace Namespace1
open System
open System.Runtime.InteropServices

[<AttributeUsage(AttributeTargets.All, AllowMultiple=true)>]
type FooAttribute(t:obj) =
   inherit System.Attribute()

type Interface1 = 
    abstract Method1 : [<FooAttribute(null)>] arg1 : obj -> unit
```

So really unrelated to #96, though likely would be hit in the original case (`DefaultParameterValue`) most often.

**Comment by dsyme** [comment]
@kurtschelfthout This is an old issue, but the workaround is a simple type annotation ``DefaultParameterValue(null:obj)``

```
namespace Namespace1
open System.Runtime.InteropServices

type Interface1 = 
    abstract Method1 : [<DefaultParameterValue(null:obj)>] arg1 : obj -> unit
```
I will close this as a duplicate of https://github.com/Microsoft/visualfsharp/issues/719

**Comment by Lanayx** [comment]
Hit this issue today with the following commit: https://github.com/fsharplang-ru/pulsar-client-dotnet/commit/4267a829e99bdfda25666d3f3ee8af19166d8556 (SequenceId is UMX type for uint64)

**Comment by gusty** [comment]
I also see it back after compiling and referencing F#+ with VS 2019 v. 16.7.0 Preview 1.0

**Comment by cartermp** [comment]
I think this should be re-opened since it's clearly happening in multiple codebases

**Comment by Shmew** [comment]
I'm seeing this when [building](https://ci.appveyor.com/project/Shmew/fable-signalr/builds/33805892#L659) my library, located in [this repo](https://github.com/Shmew/Fable.SignalR).

**Comment by cartermp** [comment]
@dsyme any thoughts on how to resolve this?

**Comment by jing8956** [comment]
A same warning code occurred when trying to add `[<assembly: HostingStartup(typeof<ConfigureServices>)>] `

Reference Package Microsoft.AspNetCore.Hosting.Abstractions 2.2.0
And compile this:
``` fsharp
namespace TestLibrary

open Microsoft.Extensions.DependencyInjection
open Microsoft.AspNetCore.Hosting

type HelloWrold() = member _.Message = "Hello World."

type ConfigureServices() =
    interface IHostingStartup with
        member _.Configure(builder) = 
            builder.ConfigureServices(fun services -> services.AddSingleton<HelloWrold>() |> ignore)
            |> ignore

[<assembly: HostingStartup(typeof<ConfigureServices>)>] 
do ()
```

Create a default dotnet webapi project, then reference it.
```
C:\Users\jing8956\source\TestProject\Test>dotnet build
用于 .NET 的 Microsoft (R) 生成引擎版本 16.11.0+0538acc04
版权所有(C) Microsoft Corporation。保留所有权利。

  正在确定要还原的项目…
  已还原 C:\Users\jing8956\source\TestProject\Test\Test.fsproj (用时 160 ms)。
  已还原 C:\Users\jing8956\source\TestProject\TestLibrary\TestLibrary.fsproj (用时 160 ms)。
  TestLibrary -> C:\Users\jing8956\source\TestProject\TestLibrary\bin\Debug\net5.0\TestLibrary.dll
C:\Users\jing8956\source\TestProject\Test\unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 1 in table 'itycons' of assembly 'TestLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using. [C:\Users\jing8956\source\TestProject\Test\Test.fsproj]
  Test -> C:\Users\jing8956\source\TestProject\Test\bin\Debug\net5.0\Test.dll

已成功生成。

C:\Users\jing8956\source\TestProject\Test\unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 1 in table 'itycons' of assembly 'TestLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using. [C:\Users\jing8956\source\TestProject\Test\Test.fsproj]
    1 个警告
    0 个错误

已用时间 00:00:05.83
```
.Net Core SDK Version 5.0.400

Note: I am trying [Use hosting startup assemblies in ASP.NET Core](https://docs.microsoft.com/aspnet/core/fundamentals/host/platform-specific-configuration?view=aspnetcore-5.0) 
There is no free time now. I can try to ignore this warning tomorrow morning.

**Comment by jing8956** [comment]
I ignored the warning and continued to complete the test. It works correctly.

**Comment by dsyme** [comment]
#12195 suppresses this warning by default, as it has long proved harmless. If we get a repro where it causes a problem we will fix it
