### ISSUE TITLE
type inference trips on FSharp.Stats.Seq.stDev

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#16279]
```fsharp
#r "nuget: FSharp.Stats"
open FSharp.Stats

let centralTendencyAndDispsersion values =
  let labelsAndValues =
    [
        
      "median"           , values |> Seq.median
      "mean"             , values |> Seq.mean
      "mean_geometric"   , values |> Seq.meanGeometric
      "mean_harmonic"    , values |> Seq.meanHarmonic
      "cv"               , values |> Seq.cv
      "var"              , values |> Seq.var
      "var_population"   , values |> Seq.varPopulation
      //"st_dev"           , values |> Seq.stDev
      //"st_dev_population", values |> Seq.stDevPopulation
    ]
  for label,value in labelsAndValues do
    System.Console.WriteLine $"{label} {value}"
```

If uncommenting line with `Seq.stDev` or `Seq.stDevPopulation`, the type inference is confused about values being `int seq` instead of the more flexible constraint that this should have.

> Type constraint mismatch when applying the default type 'int' for a type inference variable. The type 'int' does not support the operator 'DivideByInt' Consider adding further type constraints

I suspect it is a bug in the type inference, or I'd like to understand why [this particular function](https://github.com/fslaborg/FSharp.Stats/blob/71cd4deee22af237109d5514e34c25a84bbc0f34/src/FSharp.Stats/Seq.fs#L482-L483) produces this.

The fix is either to make the `centralTendencyAndDispsersion` function inline or to fix the type of values to something that implements `DivideByInt`.

**Comment by abonie** [comment]
This is because of how F# type checker infers types from inlined functions when used in non-inlined context. Minimum repro is something like:
```fsharp
> #r "nuget: FSharp.Stats";;
[Loading C:\Users\adboniec\.packagemanagement\nuget\Projects\169800--0ef6e479-54c0-428b-a74c-434dac94b8ef\Project.fsproj.fsx]
module FSI_0002.Project.fsproj

> open FSharp.Stats;;
> Seq.var;;

  Seq.var;;
  ^^^^^^^

stdin(4,1): error FS0071: Type constraint mismatch when applying the default type 'int' for a type inference variable. 'Seq.var' does not support the type 'int', because the latter lacks the required (real or built-in) member 'DivideByInt' Consider adding further type constraints
```

The fixes mentioned in OP is a valid way to solve this.

If there are any specific suggestions for how constraint resolution should work here, please make them in [fslang-suggestions](https://github.com/fsharp/fslang-suggestions)
