### ISSUE TITLE
Disabling default augmentation for struct DU breaks with .NET 8

### ISSUE THREAD

**Issue by hyazinthh** [dotnet/fsharp#16282]
The compiler shipped with .NET 8.0.100 fails to compile code containing discriminated unions annotated with `[<Struct>]` and `[<DefaultAugmentation(false)>]` (error `MethodDefNotFound`) . Non-struct DUs do not have this problem.

**Repro steps**

```fsharp
module Test

[<Struct>]
[<DefaultAugmentation(false)>]
type Foo =
    | Baz of int
    | Bar

    member x.IsBaz =
        match x with | Baz _ -> true | _ -> false

    member x.IsBar =
        not x.IsBaz

[<EntryPoint>]
let main argv =
    let foo = Baz 42
    printfn "%A" foo
    0
```

[test.zip](https://github.com/dotnet/fsharp/files/13364235/test.zip)

**Expected behavior**

Should compile.

**Actual behavior**

Fails with

> error FS2014: A problem occurred writing the binary 'D:\test\obj\Debug\net6.0\test.dll': Error in pass3 for type Test, error: Error in GetMethodRefAsMethodDefIdx for mref = ("NewBaz", "Foo"), error: MethodDefNotFound

**Related information**

* Windows 10
* .NET 8.0.100 SDK

**Comment by T-Gro** [comment]
It is the following line causing the failure:

```
let foo = Baz 42
```

Compiler calls the auto-generated method to MakeBaz(42).
However, because of DefaultAugmentation(false), this maker method is not existing.

**Comment by T-Gro** [comment]
The solution probably will be to still emit the MakeBaz maker method in case of DefaultAugmentation(false), but keep it internal only, instead of public.

**Comment by T-Gro** [comment]
It will have to be public, since it can be also called from another project.
Only needed in the  case of a non-nullary case (= having some fields).

**Comment by hyazinthh** [comment]
The build error no longer occurs with .NET 8.0.200 but I also noticed runtime failures when using types like above from libraries built with .NET 6.0.419:

> System.MissingMethodException: Method not found: 'Library.Foo Library.Foo.NewBaz(Int32)'

[test.zip](https://github.com/dotnet/fsharp/files/14507843/test.zip)

Steps to reproduce:

1. Build solution with .NET 8 (via VS 17.9 or change global.json accordingly)
2. Build library with .NET 6 (`dotnet build .\library\library.fsproj`)
3. `.\bin\Debug\net6.0\main.exe`

**Comment by hyazinthh** [comment]
This is where I ran into this issue: https://github.com/aardvark-platform/aardvark.media/blob/main/src/Aardvark.UI.Primitives/Animation/Core/Time.fs#L8

NuGet package: [Aardvark.UI.Primitives](https://www.nuget.org/packages/Aardvark.UI.Primitives)

It's not that much of a problem, since we will probably move to .NET 8 anyway when .NET 6 goes out of support.
