### ISSUE TITLE
Can't use static auto property in a object type without a primary constructor

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#16297]
According to F# 8 release notes, this case should be supported:

```fsharp
type T =
    static member val P = 1
```

Unfortunately, this code doesn't compile:
```
Program.fs(17, 5): [FS3133]
  'member val' definitions are only permitted in types with a primary constructor.
  Consider adding arguments to your type definition, e.g. 'type X(args) = ...'.
```

**Comment by vzarytovskii** [comment]
I am not sure whether it should be supported. What does RFC say?

**Comment by auduchinok** [comment]
@vzarytovskii There's no RFC, but according to a Slack discussion, this is considered a bug.

**Comment by T-Gro** [comment]
As the F# 8 extension goes, this should be supported for **static**.
I will amend the description, hope this is what @auduchinok  meant.

**Comment by T-Gro** [comment]
(if I made an incorrect change and this is desired ALSO for instance members, I am afraid this is not related to F# 8 and not up to me to decide the level of support => but type without a constructor has codegen for a static class, so instance autoprop is probably not allowed by design)

**Comment by auduchinok** [comment]
> As the F# 8 extension goes, this should be supported for static.
I will amend the description, hope this is what @auduchinok meant.

> (if I made an incorrect change and this is desired ALSO for instance members, I am afraid this is not related to F# 8 and not up to me to decide the level of support => but type without a constructor has codegen for a static class, so instance autoprop is probably not allowed by design)

The change is correct, thank you. I think making it work for instance members could be nice, but I intended to report the static members here indeed.
