### ISSUE TITLE
Unexpected error when refencing an F# project from a C# project

### ISSUE THREAD

**Issue by francotiveron** [dotnet/fsharp#16359]
**Version Used**: 

Microsoft Visual Studio Professional 2022
Version 17.7.7
VisualStudio.17.Release/17.7.7+34302.85
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Professional

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.7.274.37181
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.7.274.37181
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.7.274.37181
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.7.0-3.23517.17+9d4cc0304792762c34f41cbbec67a1fcd2dc764f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.23189.3
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.4.34 (main@d5ab18b)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

File Differ   3.0.49
The easiest way to diff two files directly in Solution Explorer

ILSpy.AddIn   1.0
Integration of the ILSpy Decompiler into Visual Studio.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.7.27 (547ea6f)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   17.6.34022.00
Microsoft Office Developer Tools for Visual Studio

Python - Django support   17.0.23189.3
Provides templates and integration for the Django web framework.

Python - Profiling support   17.0.23189.3
Profiling support for Python projects.

Python with Pylance   17.0.23189.3
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.7.3.2333001+0ab18affdf2a37647768d0e25f5f021bee6257a1
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.7.12.0
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Text Macros for Visual Studio 2012-2022   1.18
Brings back text-editing macro support in Visual Studio 2012-2022

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.20829.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.7.0-3.23517.17+9d4cc0304792762c34f41cbbec67a1fcd2dc764f
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.7.0-beta.23314.10+e612cf93b989503c89e3a5830090062b7ab5e143
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   17.7.0.223 (d17-7@c374b3e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.7.3.9 (remotes/origin/d17-7@796d191def)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.7.21 (150ec9f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.1.2 (d17-5/a8a26c7)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Xamarin.iOS and Xamarin.Mac SDK   16.4.0.18 (9d266025e)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Steps to Reproduce**:
1. 
Create solution with 3 projects

P2.fsproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFramework>net4.8</TargetFramework>
      <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Class2.fs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="NinjaTrader.Core">
        <HintPath>..\..\..\..\..\Program Files\NinjaTrader 8\bin\NinjaTrader.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="7.0.400-beta.23251.2" />
  </ItemGroup>

</Project>
```

P3.csproj
```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <Platforms>x64</Platforms>
	  <TargetFramework>net4.8</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <UseWPF>true</UseWPF>
	  <LangVersion>Latest</LangVersion>
	  <RootNamespace>HF</RootNamespace>
  </PropertyGroup>
	<ItemGroup>
    <Reference Include="NinjaTrader.Core">
	    <HintPath>..\..\..\..\..\Program Files\NinjaTrader 8\bin\NinjaTrader.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
```

P1.csproj
```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <Platforms>x64</Platforms>
    <TargetFramework>net4.8</TargetFramework>
  </PropertyGroup>
	<ItemGroup>
    <Reference Include="NinjaTrader.Core">
	    <HintPath>..\..\..\..\..\Program Files\NinjaTrader 8\bin\NinjaTrader.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\P2\P2.fsproj" />
    <ProjectReference Include="..\P3\P3.csproj" />
  </ItemGroup>
</Project>
```
2.  Add the single source code file, respectively

Class2.fs
```
namespace P2

open NinjaTrader.NinjaScript

type Class2(host: IndicatorBase) = class end
```

Class3.cs
```
using NinjaTrader.NinjaScript;

namespace P3 {
    public class Class3 {
        IndicatorBase _host;

        public Class3(IndicatorBase host)
        {
            _host = host;
        }
    }
}
```

Class1.cs
```
using NinjaTrader.NinjaScript;

namespace P1 {
    internal class Class1 : IndicatorBase {
        P2.Class2 _c2;
        P3.Class3 _c3;

        public Class1()
        {
            _c2 = new P2.Class2(this);
            _c3 = new P3.Class3(this);
        }
    }
}
```
Note:
- All the 3 projects reference a local DLL NinjaTrader.Core.dll (where the type IndicatorBase is defined)
- That DLL is installed as part of the application NinjaTrader, not sure if this occurs with others DLLs
- P2 and P3 both define a single class with identical shape (different names and language)
- P1 references both P2 and P3

**Expected Behavior**:
Code should compile without errors

**Actual Behavior**:
Visual studio complains on the instantiation of Class2 in Class1, but not on Class3; the error is

> Error	CS0012	The type 'IndicatorBase' is defined in an assembly that
> is not referenced. You must add a reference to assembly
> 'NinjaTrader.Core, Version=8.1.2.0, Culture=neutral,
> PublicKeyToken=0907d8af90186095'.	P1	C:\Temp\Ninja\Test1\Solution1\P1\Class1.cs

![image](https://github.com/dotnet/roslyn/assets/8280970/a16c6d3f-b12e-4ad8-8c22-92da2c01aca1)

**Comment by francotiveron** [comment]
```
PS C:\Program Files\NinjaTrader 8\bin> sn -vf NinjaTrader.Core.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

NinjaTrader.Core.dll does not represent a strongly named assembly
```

```
PS C:\Program Files\NinjaTrader 8\bin> sn -Tp NinjaTrader.Core.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

NinjaTrader.Core.dll does not represent a strongly named assembly
```

```
PS C:\Program Files\NinjaTrader 8\bin> dumpbin /clrheader NinjaTrader.Core.dll
Microsoft (R) COFF/PE Dumper Version 14.38.33130.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file NinjaTrader.Core.dll

File Type: DLL

  clr Header:

              48 cb
            2.05 runtime version
           54970 [  252AE0] RVA [size] of MetaData Directory
               1 flags
                   IL Only
               0 entry point token
          4BB98C [   48FE0] RVA [size] of Resources Directory
               0 [       0] RVA [size] of StrongNameSignature Directory
               0 [       0] RVA [size] of CodeManagerTable Directory
               0 [       0] RVA [size] of VTableFixups Directory
               0 [       0] RVA [size] of ExportAddressTableJumps Directory
               0 [       0] RVA [size] of ManagedNativeHeader Directory


  Summary

        2000 .reloc
        2000 .rsrc
      504000 .text
```

```
PS C:\Program Files\NinjaTrader 8\bin> dumpbin /headers NinjaTrader.Core.dll
Microsoft (R) COFF/PE Dumper Version 14.38.33130.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file NinjaTrader.Core.dll

PE signature found

File Type: DLL

FILE HEADER VALUES
            8664 machine (x64)
               3 number of sections
        6536447A time date stamp Mon Oct 23 21:01:30 2023
               0 file pointer to symbol table
               0 number of symbols
              F0 size of optional header
            2022 characteristics
                   Executable
                   Application can handle large (>2GB) addresses
                   DLL

OPTIONAL HEADER VALUES
             20B magic # (PE32+)
           48.00 linker version
          502C00 size of code
          503000 size of initialized data
               0 size of uninitialized data
          5049DA entry point (00000000009049DA)
            2000 base of code
          400000 image base (0000000000400000 to 0000000000909FFF)
            2000 section alignment
             200 file alignment
            4.00 operating system version
            0.00 image version
            6.00 subsystem version
               0 Win32 version
          50A000 size of image
             200 size of headers
               0 checksum
               3 subsystem (Windows CUI)
            8560 DLL characteristics
                   High Entropy Virtual Addresses
                   Dynamic base
                   NX compatible
                   No structured exception handler
                   Terminal Server Aware
          100000 size of stack reserve
            1000 size of stack commit
          100000 size of heap reserve
            1000 size of heap commit
               0 loader flags
              10 number of directories
               0 [       0] RVA [size] of Export Directory
          50496C [      57] RVA [size] of Import Directory
          506000 [     3E8] RVA [size] of Resource Directory
               0 [       0] RVA [size] of Exception Directory
               0 [       0] RVA [size] of Certificates Directory
          508000 [       C] RVA [size] of Base Relocation Directory
          5049EC [      1C] RVA [size] of Debug Directory
               0 [       0] RVA [size] of Architecture Directory
               0 [       0] RVA [size] of Global Pointer Directory
               0 [       0] RVA [size] of Thread Storage Directory
               0 [       0] RVA [size] of Load Configuration Directory
               0 [       0] RVA [size] of Bound Import Directory
            2000 [      10] RVA [size] of Import Address Table Directory
               0 [       0] RVA [size] of Delay Import Directory
            2010 [      48] RVA [size] of COM Descriptor Directory
               0 [       0] RVA [size] of Reserved Directory


SECTION HEADER #1
   .text name
  502A98 virtual size
    2000 virtual address (0000000000402000 to 0000000000904A97)
  502C00 size of raw data
     200 file pointer to raw data (00000200 to 00502DFF)
       0 file pointer to relocation table
       0 file pointer to line numbers
       0 number of relocations
       0 number of line numbers
60000020 flags
         Code
         Execute Read

  Debug Directories

        Time Type        Size      RVA  Pointer
    -------- ------- -------- -------- --------
    91AF9D82 cv            8F 00504A08   502C08    Format: RSDS, {75486FF0-67CD-4456-B436-4A5B86D8DFA7}, 1, C:\Users\Administrator\Documents\JenkinsAgentLocal\workspace\NT8\NinjaTrader.Core\obj\x64\Release\NinjaTrader.Core.pdb

SECTION HEADER #2
   .rsrc name
     3E8 virtual size
  506000 virtual address (0000000000906000 to 00000000009063E7)
     400 size of raw data
  502E00 file pointer to raw data (00502E00 to 005031FF)
       0 file pointer to relocation table
       0 file pointer to line numbers
       0 number of relocations
       0 number of line numbers
40000040 flags
         Initialized Data
         Read Only

SECTION HEADER #3
  .reloc name
       C virtual size
  508000 virtual address (0000000000908000 to 000000000090800B)
     200 size of raw data
  503200 file pointer to raw data (00503200 to 005033FF)
       0 file pointer to relocation table
       0 file pointer to line numbers
       0 number of relocations
       0 number of line numbers
42000040 flags
         Initialized Data
         Discardable
         Read Only

  Summary

        2000 .reloc
        2000 .rsrc
      504000 .text
```
P2.dll attached. P1.dll is not generated because of the error we are dealing with
[P2.zip](https://github.com/dotnet/fsharp/files/13508946/P2.zip)
NinjaTrader.Core.dll attached as well
[NinjaTrader.Core.zip](https://github.com/dotnet/fsharp/files/13508974/NinjaTrader.Core.zip)

**Comment by francotiveron** [comment]
> > @dotnet/fsharp-team-msft do you think you can take a look at this as a next step of investigation? It seems that the F# assembly is being recorded as having a reference to an assembly with a public key token, but the build shows it's getting the same input as the C# compiler. I don't see where the public key token for the reference is coming from anywhere else, so it almost feels like this is an F# compiler bug (although I don't know how!)
> 
> I'm not entirely sure how can that happen, but 17.7 ships with quite old compiler, we've had a bunch of fixes since.
> 
> Does the same issue show with 17.8/17.9?
> 
> @jasonmalinowski also - isn't Fsc task in binlog showing what was passed to it as reference when msbuild is invoking it?

@vzarytovskii now using VS 17.8,2 - error persists

**Comment by KevinRansom** [comment]
@francotiveron

Okay, I think I understand what is going on here.

I believe the ninjatrader.core.dll has been obfuscated, when we import it we think it is a strong signed assembly, even though the dumpbin shows that it is clearly not.  I'm guessing the obfuscator zero's out the strong signed flag, and the public key record as well as the KeyFile attribute filename.  So the resulting assembly doesn't look quite the same as if it was originally unsigned.

When we write out the reference because we thought it was signed when we imported it, we write the assembly reference into P2.dll with the public key set to the bytes we thought represented the public key on import. 

I don't think this is a regression, it's probably worked this way for a long time. l will try to work on a fix tomorrow, it shouldn't be too tricky. 

Thanks for persevering with the issue

Kevin 

/cc @vzarytovskii  @jasonmalinowski  @francotiveron

**Comment by francotiveron** [comment]
How do I install this version without waiting for an update of Visual Studio?

**Comment by francotiveron** [comment]
@smoothdeveloper  I am using VS 17.8.2, the latest non-preview.

**Comment by francotiveron** [comment]
I have reset the repo and now the build succeeds.
Then have Ctrl-F5 VisualFSharpDebug. It starts another instance of VS. What should I do now?
![image](https://github.com/dotnet/fsharp/assets/8280970/ec04bf89-d710-49a0-846c-5005df2e5de0)

**Comment by smoothdeveloper** [comment]
You should open the solution that were causing the issue to see if it reproduces, hopefully it got solved.

**Comment by smoothdeveloper** [comment]
@francotiveron, taking from the initial bug, it would be interesting to know what happens if your main program (with P1.Class1) was implemented in F#.

Do you see the same error in this case?

**Comment by francotiveron** [comment]
P1Fs.fsproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework> 

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarnOn>3390;$(WarnOn)</WarnOn>
  </PropertyGroup>
	<ItemGroup>
		<Reference Include="NinjaTrader.Core">
			<HintPath>..\..\..\..\..\Program Files\NinjaTrader 8\bin\NinjaTrader.Core.dll</HintPath>
		</Reference>
		<Reference Include="PresentationCore" />
		<Reference Include="PresentationFramework" />
		<Reference Include="WindowsBase" />
	</ItemGroup>

	<ItemGroup>
    <Compile Include="Class1.fs" />
  </ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\P2\P2.fsproj" />
	  <ProjectReference Include="..\P3\P3.csproj" />
	</ItemGroup>
</Project>
```

Note: I had to add references to PresentationCore, PresentationFramework, WindowsBase not required by P1.csproj.

Class1.fs
```
namespace P1Fs

open NinjaTrader.NinjaScript

type  internal Class1() as this = 
    inherit IndicatorBase()
    let _c2 = P2.Class2(this) 
    let _c3 = P3.Class3(this) 
```

P1fs.fsproj compiles without errors.
Note: of course this could have been worked even before the fix.

**Comment by vzarytovskii** [comment]
> @vzarytovskii I am confused. What do you recommend I do to get to issue fixed?

SDK with the fix should be used. So either wait for release or use nightly one from dotnet/installer repo.

**Comment by francotiveron** [comment]
@vzarytovskii   I have seen that https://github.com/dotnet/fsharp/pull/16365 has been merged. I have downloaded the latest version of Visual studio Preview (17.9.0 Preview 2.0), but I still get the error. Is this expected?

**Comment by vzarytovskii** [comment]
> @vzarytovskii   I have seen that https://github.com/dotnet/fsharp/pull/16365 has been merged. I have downloaded the latest version of Visual studio Preview (17.9.0 Preview 2.0), but I still get the error. Is this expected?

I think so. Fix was merged after preview 2 was released

**Comment by francotiveron** [comment]
> > @vzarytovskii   I have seen that #16365 has been merged. I have downloaded the latest version of Visual studio Preview (17.9.0 Preview 2.0), but I still get the error. Is this expected?
> 
> I think so. Fix was merged after preview 2 was released

@vzarytovskii  Preview 2.1 still has the issue, and it should have been release after. Can you please confirm?
