### ISSUE TITLE
Implement "Opportunistic Mutation" as seen in the Roc language

### ISSUE THREAD

**Issue by jameshulse** [dotnet/fsharp#16358]
**Describe the solution you'd like**

I propose we implement what Roc calls "[Opportunistic Mutation](https://www.roc-lang.org/functional#opportunistic-mutation)".

The basic concept is to use mutability under the hood in cases where it won't cause side-effects in the application, but where there would be a performance improvement or reduction in memory usage.

**Other Context**

I'm afraid I don't have a lot of context of whether this is already considered, or even possible, or necessary! But the neat thing is that it could be implemented gradually in the compiler e.g it finds the safest places to implement this change and then builds out the feature in future versions as it gets more confident that it won't affect user land code.

**Comment by vzarytovskii** [comment]
Please, open a language suggestion over at fslang-suggestions (there's a link to it when creating a new issue in this repo).
