### ISSUE TITLE
Internal error when abbreviating types with extension members

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#16389]
Consider these C# and F# projects:

```csharp
namespace CSharpLib;

public interface I
{
    public int P { get; }
}

public static class Ext
{
    public static void M(this I i)
    {
    }
}
```

```fsharp
open CSharpLib

module M =
    type Ext = CSharpLib.Ext

    let f (i: I) =
        i.M()
```

This fails to build when using .NET 8 SDK:
```
2>Program.fs(7,9): Error FS0073 : internal error: ImportILTypeRef: unexpected local scope
```

This is a recent regression, the same project builds fine when using .NET 7 SDK.

In addition to the failing build, it also breaks member code completion for extended type instances in a recent FCS:

<img width="339" alt="Screenshot 2023-12-05 at 17 26 33" src="https://github.com/dotnet/fsharp/assets/3923587/327b9457-7e39-47df-b12c-fce6e54e8ad9">

**Comment by auduchinok** [comment]
Slightly changed F# example shows that in .NET 7 the extension members weren't imported if abbreviated type wasn't imported:
```fsharp
module M =
    type Ext2 = CSharpLib.Ext
 
    let f (i: CSharpLib.I) =
        i.M()
```
```
2>Program.fs(5,11): Error FS0039 : The type 'I' does not define the field, constructor or member 'M'.
```

I think there's a chance it may be related to #13839 or #15687. cc @nojaf @edgarfgp

**Comment by edgarfgp** [comment]
Seems similar to https://github.com/dotnet/fsharp/issues/16321 ?

**Comment by edgarfgp** [comment]
> I think there's a chance it may be related to #13839 or #15687 

Yes it might be related. @nojaf and I were looking to fix some corner cases found on the Fabulous project codebase. See https://github.com/dotnet/fsharp/pull/16368

**Comment by auduchinok** [comment]
> Yes it might be related. @nojaf and I were looking to fix some corner cases found on the Fabulous project codebase. See https://github.com/dotnet/fsharp/pull/16368

It actually is. Please see https://github.com/dotnet/fsharp/pull/16390.
