### ISSUE TITLE
Incorrect range for SynInterpolatedStringPart.String in extended interpolated string

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#16418]
Consider parsing

```fsharp
$$$"""{{{5}}}"""
```

This will lead to 

```fsharp
SynExpr.InterpolatedString(
    SynInterpolatedStringPart.String(value = "", range = R("(1,0--1,9)")) 
    SynInterpolatedStringPart.FillExpr(fillExpr = SynExpr.Const(constant = SynConst.Int32(5), range = R("(1,9--1,10)")), qualifiers = None)
    SynInterpolatedStringPart.String(value = "", range = R("(1,12--1,16)"))
)
```

The range of the opening `SynInterpolatedStringPart.String` covers `$$$"""{{{`, while the closing `SynInterpolatedStringPart.String` only covers the range of `}"""`.

**Expected behaviour**

It should cover `}}}"""` instead.

**Actual behavior**

The range only starts from the last `}`.

**Related information**

Discovered via https://github.com/fsprojects/fantomas/issues/3012

@abonie as you worked on this, could you give me a pointer where in the lexer this could be fixed?

**Comment by abonie** [comment]
Hmm... Somewhere in [this section](https://github.com/dotnet/fsharp/blob/main/src/Compiler/lex.fsl#L902) I bet.

Thanks for reporting. Are you planning to look into it @nojaf?

**Comment by nojaf** [comment]
> Are you planning to look into it @nojaf?

Well, I took a peek at it yesterday. Indeed, around the area you suggested here, but I wasn't able to make a dent.

Would you mind skimming through it maybe?

**Comment by abonie** [comment]
I will give it at least a once-over

**Comment by nojaf** [comment]
So @abonie, did you have any fun with this 😸?

**Comment by abonie** [comment]
Yeah, no luck so far either
