### ISSUE TITLE
Build is failing after an FSComp.txt change

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#16424]
There's a new error when changing the generated errors:
```
4>Microsoft.DotNet.XliffTasks.targets(84,5): Error  :
    'xlf/FSComp.txt.cs.xlf' is out-of-date with '/Users/eugene/Developer/fsharp/artifacts/obj/FSharp.Compiler.Service/Debug/netstandard2.0/FSComp.resx'.
    Run `msbuild /t:UpdateXlf` to update .xlf files or set UpdateXlfOnBuild=true to update them on every build,
    but note that it is strongly discouraged to set UpdateXlfOnBuild=true in official/CI build environments as they should not modify source code during the build.
```

It blocks the development flow and requires you to manually do something that usually is only needed just before opening a PR, or could be done completely automatic on non-CI builds.

**Comment by auduchinok** [comment]
I can figure out the needed command, but I feel that it's going to be an issue for some other contributors, especially newcomers.

This is what I get if I try to run the command suggested in the error message:
```
eugene@Eugenes-Air:fsharp$ msbuild /t:UpdateXlf
Microsoft (R) Build Engine version 16.10.1 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.
```

The suggestion to set `<UpdateXlfOnBuild>true</UpdateXlfOnBuild>` in the project file doesn't fix the error either.

**Comment by vzarytovskii** [comment]
Likely introduced by https://github.com/dotnet/fsharp/pull/16327, I don't care much personally whether this is enabled or not, so, you'll need to agree on solution with Martin

**Comment by Martin521** [comment]
BTW I think I saw the above error message once when I tried to run `dotnet test` after a change in FSComp.txt. It went away after a `dotnet build`.

**Comment by auduchinok** [comment]
Undoing changes from #16327 fixes the build for me. `dotnet build ./src/Compiler /t:UpdateXlf` also works.

@Martin521 Could we maybe try to revert it and try to find another way to solve your issue? Is there a way to check whether the solution is being loaded in a dev container?

**Comment by Martin521** [comment]
Let me check.

**Comment by Martin521** [comment]
It seems the explicit reference is no longer needed. I will create a PR to remove it.
