### ISSUE TITLE
This declaration opens the namespace or module through a partially qualified path. Adjust this code to use the full path of the namespace. This change will make your code more robust as new constructs are added to the F# and CLI libraries.

### ISSUE THREAD

**Issue by nkosi23** [dotnet/fsharp#16446]
I am bootstrapping an app in F# using the ApplicationBuilder abstractions provided by ASP.NET Core and am hitting a nasty false positive due to clashes with the namespaces in which extension methods are defined. There are three namespaces of interest needed by my project:

- Wolverine
- Wolverine.Marten
- Marten

However only two of them are needed in this file:

- Wolverine
- Marten

However, having both the Wolverine and Marten namespaces open in the same file produce the following compiler error:

```fsharp
open Wolverine
open Marten
```

>This declaration opens the namespace or module 'Wolverine.Marten' through a partially qualified path. Adjust this code to use the full path of the namespace. This change will make your code more robust as new constructs are added to the F# and CLI libraries.

What is tricky in this situation is that I cannot use fully qualified type names since the namespaces are opened to access extension methods (and as far as i know, there is not way to access an extension method in fully qualified manner). I am therefore blocked and left scratching my head.

Is there a way to tell the compiler that the `open Marten` is actually fully qualified? (or any other workaround? i really need to get on with my work). Thanks folks

**Repro steps**

Namely provided the below:

```fsharp
namespace WebApplication1
#nowarn "20"
open System
open System.Collections.Generic
open System.IO
open System.Linq
open System.Threading.Tasks
open Microsoft.AspNetCore
open Microsoft.AspNetCore.Builder
open Microsoft.AspNetCore.Hosting
open Microsoft.AspNetCore.HttpsPolicy
open Microsoft.Extensions.Configuration
open Microsoft.Extensions.DependencyInjection
open Microsoft.Extensions.Hosting
open Microsoft.Extensions.Logging
open Wolverine
open Marten //The compiler error is raised on this line
open Weasel.Core


module Program =
    let exitCode = 0

    [<EntryPoint>]
    let main args =

        let builder = WebApplication.CreateBuilder(args)

        builder.Services.AddControllers()

        builder.Services
            .AddMarten(fun (opt: StoreOptions) ->
                opt.Connection("connectionString")
                opt.DatabaseSchemaName = "myschema"
                opt.AutoCreateSchemaObjects = AutoCreate.None
                ())
            .UseLightweightSessions()
            .IntegrateWithWolverine("myschema_messaging")
                
         // Wolverine usage is required for WolverineFx.Http
        builder.Host.UseWolverine(fun opts ->
            // This middleware will apply to the HTTP
            // endpoints as well
            opts.Policies.AutoApplyTransactions()

            // Setting up the outbox on all locally handled
            // background tasks
            opts.Policies.UseDurableLocalQueues())
            
        let app = builder.Build()

        app.UseHttpsRedirection()

        app.UseAuthorization()
        app.MapControllers()

        app.Run()

        exitCode
```

[repro-fsharp-compiler-bug-WebApplication1.zip](https://github.com/dotnet/fsharp/files/13688025/repro-fsharp-compiler-bug-WebApplication1.zip)

**Expected behavior**

The code compiles

**Actual behavior**

The following compiler error is produced:

>This declaration opens the namespace or module 'Wolverine.Marten' through a partially qualified path. Adjust this code to use the full path of the namespace. This change will make your code more robust as new constructs are added to the F# and CLI libraries.

**Known workarounds**

I am looking for a workaround

**Related information**

Provide any related information (optional):

* Operating system: Linux
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .NET Core, F# version 7
* Editing Tools (e.g. Visual Studio Version, Visual Studio): JetBrains Rider

**Comment by majocha** [comment]
Using `global` to disambiguate?
```F#
open global.Marten
```

I have no idea if this will work, though.
