### ISSUE TITLE
Unexpected FS3571 shorthand lambda atomic error

### ISSUE THREAD

**Issue by cmeeren** [dotnet/fsharp#16457]
```f#
let call (f: string -> int) x = f x

let x = call _.Length ""
```

**Expected behavior**

Compiles.

**Actual behavior**

> 0>Program.fs(10,1): Error FS0010 : Incomplete structured construct at or before this point in expression
> 0>Program.fs(10,14): Error FS3571 : _. shorthand syntax for lambda functions can only be used with atomic expressions. That means expressions with no whitespace unless enclosed in parentheses.

**Known workarounds**

Enclose shorthand lambda in parentheses:

```f#
let x = call (_.Length) ""
```

**Comment by brianrourkeboll** [comment]
I think this was fixed by #16240. That error number no longer exists in `main`.

**Comment by psfinaki** [comment]
@cmeeren can you please check this case on the latest VS or FCS?

**Comment by cmeeren** [comment]
Still happens with VS 17.8.3.

**Comment by vzarytovskii** [comment]
It won't go into 17.8.*, only in 17.9. Also not sure if 17.9 preview with the fix was released. It was inserted November 21st: https://github.com/dotnet/fsharp/issues/16320

**Comment by psfinaki** [comment]
Doesn't reproduce in 17.9.0 Preview 2.0. Should be good.
