### ISSUE TITLE
Nested record copy-and-update expression seems to fail when copying and updating a nested value

### ISSUE THREAD

**Issue by josh-degraw** [dotnet/fsharp#16466]
Trying to use the new nested record copy-and-update syntax results in a compiler error if trying to use it to extract and modify the value of a nested object rather than the root object.

**Repro steps**

1. Have some nested record types defined:
```fsharp
type MetadataDto = { Name: string; Groups: Set<string> }
type ProductDto = { Id: Guid; Metadata: MetadataDto }
type WrappedProduct = { Product: ProductDto }

let wrapped = {
    Product = {
        Id = Guid.NewGuid ()
        Metadata = {
            Name = "Some product"
            Groups = Set [ "A" ]
        }
    }
}
```

2. Try to make a copy of just a nested value while updating a value therein and there is an error
```fsharp
let newProd = {
    wrapped.Product with
        Metadata.Groups = Set.empty
}
```

Notably, this error doesn't happen if you extract the nested value before performing a copy-and-update expression on it.

![minimal repro](https://github.com/dotnet/fsharp/assets/18509575/d3538fe5-139f-4e6a-ae7b-3cdbafdb5cf4)
![compiler error message](https://github.com/dotnet/fsharp/assets/18509575/c038fe1c-f6b5-48f5-8642-20eee214b27e)

It also doesn't seem to be a problem with anonymous records, just true record types:

![anonymous records equivalent](https://github.com/dotnet/fsharp/assets/18509575/7497d42e-bac4-4cc3-8f15-bd1d76439eb1)

**Expected behavior**
I'd expect to be able to get an updated `ProductDto` with the `Groups` field of its `Metatadata` property correctly updated.

**Actual behavior**

Compiler error.

**Known workarounds**

Extract the intended value to a standalone binding before performing a copy-and-update operation on it.

**Related information**

Provide any related information (optional):

* Operating system
  * Windows
* .NET Runtime kind (.NET Core, .NET Framework, Mono)
  * .NET 8
* Editing Tools (e.g. Visual Studio Version, Visual Studio)
  * Verified in VS Code and Rider

**Comment by kerams** [comment]
https://github.com/dotnet/fsharp/issues/16237
