### ISSUE TITLE
LSP: Investigate New VSIX extension options

### ISSUE THREAD

**Issue by 0101** [dotnet/fsharp#16495]
Contact [VS.Extensibility](https://github.com/microsoft/VSExtensibility) team and talk to them about whether VS.Extensibility is a good choice for our purposes (in its current state). And if not then what would be a good choice. 

Worst case we'd have to use the same system we have for the current Vsix.

**Comment by vzarytovskii** [comment]
I suppose this one can be closed for now, since we are using new VSIX already in the lsp branch.
