### ISSUE TITLE
Avoid boxing on equality and comparison

### ISSUE THREAD

**Issue by 0101** [dotnet/fsharp#16497]
https://github.com/fsharp/fslang-suggestions/issues/1280

**Comment by vzarytovskii** [comment]
It's a duplicate of https://github.com/dotnet/fsharp/issues/526 technically, but I can't bring it back to project since it was bulk closed and archived.

**Comment by vzarytovskii** [comment]
This also needs an approval by @dsyme. Specifically - an opt-out behaviour for new default operators (and somehow make it work for fslib as well).

**Comment by psfinaki** [comment]
Restored 526 from the archive so closing this one as a duplicate.
