### ISSUE TITLE
Unexpected shorthand lambda FS3570 with nested ignored tuple elements

### ISSUE THREAD

**Issue by cmeeren** [dotnet/fsharp#16530]
I get an unexpected FS3570 when using nested ignored tuple elements:

```f#
    type A = { A: int }

    let f ((_x, y), z) = z |> Option.map _.A
```

**Expected behavior**

Compiles.

**Actual behavior**

> Error FS3570 : The meaning of _ is ambiguous here. It cannot be used for a discarded variable and a function shorthand in the same scope.

**Known workarounds**

Don't use shorthand lambda, or don't ignore nested tuple elements.

**Comment by T-Gro** [comment]
@cmeeren : 

Hi.
This issue should have been fixed with https://github.com/dotnet/fsharp/pull/16334 and hopefully available in the preview SDK.

**Comment by T-Gro** [comment]
Please let me know if it still persists, I will then reopen the issue and have a look.
