### ISSUE TITLE
Symbols: local functions don't provide parameter names and declaring type info

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#16542]
Extracts the case that is still broken from #13381.
Consider the following:

```fsharp
let f () =
    let c x = ()

    c
```

`c` symbol doesn't provide names for its parameters:

<img width="259" alt="Screenshot 2024-01-17 at 13 54 28" src="https://github.com/dotnet/fsharp/assets/3923587/e9824fb9-ab0a-4286-8934-98ea9b3137eb">

**Comment by 0101** [comment]
CC @psfinaki

**Comment by auduchinok** [comment]
So the problem here is `Val` keeps the info we need in `ValReprInfoForDisplay` instead of `ValReprInfo`, so it's inaccessible in `CurriedParameterGroups` that the features use.

Is there a reason why these two are separate?
What would happen if we always put the info into `ValReprInfo`?
