### ISSUE TITLE
Make a reflection free versions of printf/sprintf

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#16662]
printf and sprintf rely quite heavily on reflection when providing support for %A item formatting.  And it is quite a chunk of FSharp.Core

We would like to remove that dependence to allow, trim to delivery smaller self contained programs and likely to make things perform a bit zoomier.

This issue will track this feature.

**Comment by vzarytovskii** [comment]
We have it tracked in F# 9 plan, but not committed, no need for this duplicate. If you think we need to work on it, please convert existing one to issue and move to committed (and move something else to shelved).

**Comment by vzarytovskii** [comment]
This is an original issue: https://github.com/dotnet/fsharp/issues/16663
I moved it to committed, and moved some other trimming issues out
