### ISSUE TITLE
printfn is not recognized  by F#

### ISSUE THREAD

**Issue by Dn34** [dotnet/fsharp#16668]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/languages/fsharp-hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

printfn is not recognized as the name of a cmdlet, function , script filer, or operable program

**Comment by Martin521** [comment]
Ok, it seems the Microsoft tutorial page directed you here to get help.
Let me guess - you are on the page "Create your app" of the tutorial and you have entered `printfn "Hello from F#"` into PowerShell.
However, what you see in that box on the tutorial page is only the content of the file Program.fs. It is not meant to be entered at the command prompt. Just click `Continue` to proceed with the tutorial.
