### ISSUE TITLE
Attribute applied to alias is ignored

### ISSUE THREAD

**Issue by xperiandri** [dotnet/fsharp#16677]
**Repro steps**

https://sharplab.io/#v2:DYLgZgzgNAJiDUAfALgTwA4FMAEBhA9gLboCGAdqgMrIBOArgMbJ02bUnI4C8AsAFDZB2AN78h47ABFMpGskKYyyCNhDZ8AIwBW2YAEsIyMUIC+/AO57kAC2ODDHPQ2wLCGzDWwBJMlYAUAJTYXCJ2EtKy8orKwdgA2gC6YWYCQvz4WGTYlKiGmIQAdJJ6JADmZPiGThD8/HEAPNIadKWlHsUQ6MAkqH4ARH0BAHxJfGhY2cgc3HhEpBTU9EwsbFOc/EA===
``` F#
type CompanyStructureState =
    {
        Departments : obj list
    }
with
    static member Init() = {
        Departments = []
    }
    
open System.Diagnostics

[<DebuggerDisplay("")>]
type State = CompanyStructureState
```

**Expected behavior**

Either attribute is applied (if alias located in the same file) or error.
Compilation error in all the other cases.

**Actual behavior**

No error, compiled code does not contain attribute.

**Related information**

* .NET Core 8, F# 8
* Visual Studio 2022 17.8.6

**Comment by vzarytovskii** [comment]
It's by design, aliases don't exist in compiled code.

**Comment by xperiandri** [comment]
What about compile-time error then?

**Comment by xperiandri** [comment]
Warning?

**Comment by vzarytovskii** [comment]
> Warning?

Still a breaking change.
