### ISSUE TITLE
Type inference for subtypes should be improved

### ISSUE THREAD

**Issue by Lanayx** [dotnet/fsharp#16698]
**Is your feature request related to a problem? Please describe.**

I often work with Tasks and become frustrated when one can't be converted to another. For example, if the API accepts `Task` and I provide `Task<unit>` I expect them to be implicitly converted and type inference just to work. However it's not the case.

Repro: 
1. Clone [Oxpecker](https://github.com/Lanayx/Oxpecker) repository
2. Go to [handler4](https://github.com/Lanayx/Oxpecker/blob/develop/examples/Basic/Program.fs#L35) and remove explicit return type `EndpointHandler`
3. Get compiler error: `The type 'Task' does not match the type 'Task<unit>'`

**Describe the solution you'd like**

I'd like to see the type inference work and types get converted one into another

**Describe alternatives you've considered**

Alternative is to manually specify types instead of relying on type inference

**Comment by vzarytovskii** [comment]
This needs to be a specific language suggestion, please find existing one or create a new one.

**Comment by Lanayx** [comment]
@vzarytovskii There is already an approved and implemented suggestion:
https://github.com/fsharp/fslang-design/blob/main/FSharp-6.0/FS-1093-additional-conversions.md
namely
_Fewer upcasts are needed when programming with types that support subtyping_, so I'm not sure what additional language suggestion I need to create

**Comment by Lanayx** [comment]
I think this section might relate to my case
https://github.com/fsharp/fslang-design/blob/main/FSharp-6.0/FS-1093-additional-conversions.md#no-upcast-without-known-type-information, should I create language suggestion for "upcast without knowing type information"?

**Comment by vzarytovskii** [comment]
> @vzarytovskii There is already an approved and implemented suggestion:
> 
> https://github.com/fsharp/fslang-design/blob/main/FSharp-6.0/FS-1093-additional-conversions.md
> 
> namely
> 
> _Fewer upcasts are needed when programming with types that support subtyping_, so I'm not sure what additional language suggestion I need to create

@Lanayx 

The linked one is about the implicit conversion. This issue mentions type inference, which is different.

If additional conversions are needed, then it should be a small suggestion + rfc (or addition to existing rfc), since it's change to original proposal.

If change of type inference is needed, then it should be a separate bigger suggestion with details of how it supposed to work.
