### ISSUE TITLE
Extra nullness check on Option.ofObj

### ISSUE THREAD

**Issue by isaacabraham** [dotnet/fsharp#16731]
The nullness feature branch looks very good. However, I believe that the behaviour of `Option.ofObj` should be modified once this feature has been accepted to prevent code as follows:

```fsharp
let aString = "test"
let thisMakesNoSense = Option.ofObj aString
```

There is little reason going forward to keep this behaviour - it is semantically incorrect to call `Option.ofObj` on a non-nullable ref type, in the same way that this code does not compile today:

```fsharp
let aNumber = 123
let thisDoesNotCompile = Option.ofNullable aNumber // compiler error
```

I'm well aware that the mechanisms for this and the nullness one are vastly different, but from a behaviour point of view I believe we should strive for consistency, especially for newcomers to the language who will not understand why one is permitted and one is not.

**Describe the solution you'd like**
The above `Option.ofObj` code should give a nullness warning in a similar way that assigning null to a non-nullable ref type will. Turning on treating warnings as errors will provide compile-time safety against doing this.

In order to mitigate the no-breaking changes rule, my reasoning is as followed:

* This can be done as a nullness warning, not an error.
* The whole point of nullness checks is to improve soundness of code; a goal of the feature IMHO should be that the compiler should be giving *more* warnings / errors than before (assuming that those warnings / errors are legitimate, of course).
* Could an overload of `Option.ofObj` be introduced and marking the original one as obsolete? i.e. the original `'T` overload would be marked as obsolete; a new `'T | null` overload would be added.
* In the unlikely scenario that a user wishes to still retain this behaviour the following replacement can easily be utilised:

```fsharp
let x : string = "hello"
Option.ofObj x // old code
Some x // new code
```

**Describe alternatives you've considered**
Leave code as is. This may reduce confidence in the soundness of the nullability feature in F#, however.

**Comment by vzarytovskii** [comment]
We don't accept separate issues for nullness just yet, it will randomize feature development. Please, make a comment/review in the nullness PR, so it doesn't fall off of the radar

**Comment by isaacabraham** [comment]
Sorry - will do there :-)

**Comment by isaacabraham** [comment]
@vzarytovskii what PR should I put them in - there's no PR that I could find for it.

**Comment by vzarytovskii** [comment]
> @vzarytovskii what PR should I put them in - there's no PR that I could find for it.

There should be main nullabillity PR by Don. Let me try to find it.

**Comment by vzarytovskii** [comment]
https://github.com/dotnet/fsharp/issues/15181
