### ISSUE TITLE
Re-enable transparent compiler tests, when stable

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#16766]
Reenable tests disabled by following PRs once transparent compiler is stable:
https://github.com/dotnet/fsharp/pull/16763
https://github.com/dotnet/fsharp/pull/16765
https://github.com/dotnet/fsharp/pull/16850

**Comment by majocha** [comment]
Also `useTransparentCompiler` disabled in MultiProjectAnalysisTests.fs, #17652
