### ISSUE TITLE
FSharps use of CompileBefore for file ordering leads to issues with other SDK components

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#16771]
@Smaug123 added a PR to sourcelink main:  https://github.com/dotnet/sourcelink/pull/1209

It highlights a long time issue with us relying on Compile before:

Snip:

> SetEmbeddedFilesFromSourceControlManagerUntrackedFiles [only considers files if they're in @(Compile)](https://github.com/dotnet/sourcelink/blob/a22426a46745b8fe77b9d306fa4bc1d03eff44ea/src/Microsoft.Build.Tasks.Git/build/Microsoft.Build.Tasks.Git.targets#L53). In an F# project, TargetFrameworkMonikerAssemblyAttributesPath is not in @(Compile) but [is instead in @CompileBefore](https://github.com/dotnet/fsharp/blob/bc3dd9ffaaad7898a68de4828aa0a08e1bb1461b/src/FSharp.Build/Microsoft.FSharp.Targets#L436). The result is that the F# compiler never even attempts to embed obj/Release/netstandard2.0/.NETStandard,Version=v2.0.AssemblyAttributes.fs (for example), because it was never added to @(EmbeddedFiles).
> 
> It's possible that the correct fix is instead in Microsoft.FSharp.Targets. The behaviour of adding to CompileBefore rather than to Compile was added in https://github.com/dotnet/fsharp/commit/01c621c04666bf740f01eb73eb779f6fb5a2c7f1, which is extremely vague and dates back before pull requests and GitHub were a thing; so I can't find any of the context for it.
> 

The likely fix is to modify our use of CompileBefore to adding Metadata to the Compile item that tells us to place the decorated item early in the build.

**Comment by Smaug123** [comment]
Given that #17057 was reverted in #17099, am I right in thinking this is not fixed?

**Comment by vzarytovskii** [comment]
> Given that #17057 was reverted in #17099, am I right in thinking this is not fixed?

It was in https://github.com/dotnet/fsharp/pull/17103. Initial implementation broke file ordering in VS.
