### ISSUE TITLE
Support ref structs in generics

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#16800]
.NET 9 will support ref structs in generics as well as new constraint. 
A bunch of new APIs will be utilising it, hence it needs to be supported in F#

Runtime support: https://github.com/dotnet/runtime/issues/65112
C#: https://github.com/dotnet/csharplang/blob/main/proposals/ref-struct-interfaces.md

**Note:** only consuming is in scope, everything else isn't possible right now, due to lack of many ref-related features support in compiler (ref fields, escape analysis as examples).

**Comment by brianrourkeboll** [comment]
> **Note:** only consuming is in scope, everything else isn't possible right now, due to lack of many ref-related features support in compiler (ref fields, escape analysis as examples).

It's probably worth keeping in mind this feature's potential usefulness in someday addressing things like https://github.com/fsharp/fslang-suggestions/issues/688, https://github.com/fsharp/fslang-suggestions/issues/805, https://github.com/fsharp/fslang-suggestions/issues/887, https://github.com/fsharp/fslang-suggestions/issues/1140, https://github.com/dotnet/fsharp/issues/7828.

**Comment by brianrourkeboll** [comment]
Yep, I understand.

I just meant that we should try to ensure that whatever approach is taken to add support for consumption doesn't limit our options if we also someday wanted to support production, or that thinking about the latter might have the potential to inform some aspects of how the former is done.

**Comment by brianrourkeboll** [comment]
(Let me know if you'd rather I delete this here and wait to comment on the RFC.)

...The reason I linked those specific issues in https://github.com/dotnet/fsharp/issues/16800#issuecomment-1976890443 is that they present concrete scenarios where using this feature productively might be useful.

For example, do we plan to surface the new constraint in the type signature when a construct using the constraint defined in C# is consumed by F# code?

Even if we don't plan to allow producing such a constraint in F# for now, thinking about what that might look like might inform how we represent such a signature, e.g., consider:

```fsharp
let inline (|>) x (f : 'a -> 'b when :? byref<'a> and 'a :? struct) = f x
```

```fsharp
type SomeBuilder () =
    member inline _.Bind (x, [<InlineIfLambda>] f : 'a -> M<'b> when :? byref<'a> and 'a :? struct) = …
```

— which would be analogous to the C# —

```csharp
public static B op_PipeRight<A, B>(A x, Func<A, B> f) where A : allows ref struct => f(x);
```

```fsharp
public class SomeBuilder
{
    public M<B> Bind<A, B>(M<A> x, Func<A, M<B>> f) where A : allows ref struct { … }
}
```

— etc.

Using `:?` for "might be" immediately strikes me as one potential way to naturally represent `allows` in F#, by the same logic that we already use `:` for "is" and `:>` for "is convertible to" in both the grammar of types and the grammar of expressions.

**Comment by vzarytovskii** [comment]
We probably want it at some point, but currently the most important thing is to support consuming them. 

I think we should create a discussion of what are we missing from the byrefs features (both importing, checking and codegen), have a chat there, with examples and use cases from C#, and from there we should create a new suggestion for improvements (I do believe it should be one rfc, but can be multiple contributions).

**Comment by brianrourkeboll** [comment]
On the topic of supporting consumption and how that might look in F#:

I thought about this a bit more the other week — see here https://github.com/dotnet/csharplang/issues/7608#issuecomment-2005361966 for more detail — and I believe that one way to think of the addition of this "anti-constraint" to a generic type parameter is as a unioning of a constraint like `'T : byref<struct>` with the existing default constraint union implied by bare `'T`, i.e., `'T when 'T : struct or 'T : not struct`.[^1]

C#'s `where T : allows ref struct` could thus be thought of (in imaginary F# syntax) as `when 'T : struct or 'T : not struct or 'T : byref<struct>`.

I'm _not_ suggesting that we start making the existing implicit default constraint union explicit, or that we necessarily add support for constraint unions as a general feature.

I _am_ suggesting that the idea of constraint unions may help us approach the ref struct "anti-constraint" feature in a more general way than if we think of it as a one-off special case. I'm also open to the possibility that it's not helpful, but I figured I'd bring it up.

[^1]: Using `or` for constraint unions would align with the existing use of `and` for constraint intersections.

**Comment by AaronRobinsonMSFT** [comment]
Support has been added to all officially supported runtimes - CoreCLR, native AOT and mono. I believe this has made it into the latest .NET 9 Preview. There are some tricky bits to be aware as it relates to special IL sequences that are recognized by the JIT and mono - see [here](https://github.com/dotnet/runtime/blob/main/docs/design/features/byreflike-generics.md#special-il-sequences). IL based tests can be found at [here](https://github.com/dotnet/runtime/blob/main/src/tests/Loader/classloader/generics/ByRefLike/InvalidCSharp.il).

/cc @jaredpar @lambdageek @fanyang-mono
