### ISSUE TITLE
Parser tests fail in `main`

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#16830]
There're failures in `SyntaxTree` tests on my macOS machine, even after `git clean -dfx`:

<img width="1512" alt="Screenshot 2024-03-07 at 13 03 28" src="https://github.com/dotnet/fsharp/assets/3923587/ffdeb1be-e4b9-42dc-a260-b4824ec0c3dc">

It seems it may be related to the changes introduced in https://github.com/dotnet/fsharp/pull/16687.
I wonder how that could get past the CI? Could this be looked into, please?

**Comment by abonie** [comment]
We reverted the PR and created an issue to redo it with this bug in mind (#16854)
