### ISSUE TITLE
Indentation in scoped block doesn't work well with property intialization

### ISSUE THREAD

**Issue by Lanayx** [dotnet/fsharp#16834]
**Repro steps**

Here is the code
```fsharp
open System

type MyTest() =
    member val Name = "" with get, set
    
let test = MyTest(
    Name =
        (let x = "abc"
        Console.WriteLine(x)
        x)
)
```

**Expected behavior**

Code is expected to compile well

**Actual behavior**

Code doesn't compile

**Known workarounds**

It's possible to make it work by moving x to the last line with ; separator:
```fsharp
let test2 = MyTest(
    Name =
        (let x = "abc"
        Console.WriteLine(x);x)
)
```

**Related information**

.NET SDK 8.0.201

**Comment by brianrourkeboll** [comment]
I think this is just an offsides issue.

For example, if you line up the following two lines with the beginning column of `let x`, your example compiles:

```fsharp
open System

type MyTest() =
    member val Name = "" with get, set
    
let test = MyTest(
    Name =
        (let x = "abc"
         Console.WriteLine(x)
         x)
)
```

I.e.,

```diff
@@ -6,6 +6,6 @@ type MyTest() =
 let test = MyTest(
     Name =
         (let x = "abc"
-        Console.WriteLine(x)
-        x)
+         Console.WriteLine(x)
+         x)
 )
```

**Comment by Lanayx** [comment]
@brianrourkeboll I think there is some inconsistency to fix, since
this works
```fsharp
  let test = MyTest(
      Name =
          (let x = "abc"
          x)
  )
 ```
this also works
```fsharp
    let test = MyTest(
        Name =
            (let x = "abc"
             let y = x
            x)
    )
 ```
 this doesn't
 ```fsharp
     let test = MyTest(
        Name =
            (let x = "abc"
             Console.WriteLine(x)
            x)
    )
 ```

**Comment by auduchinok** [comment]
The `let` binding and its in-expression should have the same indent:
```fsharp
// allowed:
do
    let x = ()
    x


// not allowed:
do
    let x = ()
   x
```


It is indeed a bug that some of additional cases are allowed, so, for example, this case should not work:
```fsharp
let test = MyTest(
    Name =
        (let x = "abc"
        x)
)
```

It would be a breaking change to disallow more cases, though.

**Comment by brianrourkeboll** [comment]
@Lanayx yes, there are definitely some funky things allowed in multiline expressions when wrapped in parens that wouldn't be allowed otherwise:

https://github.com/dotnet/fsharp/blob/31f3d2bab270834b3c55fbc2ad654577ca49b9df/src/Compiler/Service/SynExpr.fs#L624-L638

**Comment by Lanayx** [comment]
Ok, so I'm unsure what to do with ticket :) On one hand my case shouldn't work as @auduchinok mentioned above, but on the other hand there is a special case for parenthesis that states that it should work.

**Comment by brianrourkeboll** [comment]
> but on the other hand there is a special case for parenthesis that states that it should work.

Oh, the code snippet I linked in https://github.com/dotnet/fsharp/issues/16834#issuecomment-1984495664 is just from the code in the compiler service that analyzes whether parentheses are required around a given expression — those comments are just acknowledging the existing treatment of such code, not enforcing or endorsing it. Unless you see somewhere else that talks about this? (I haven't looked.)

I haven't investigated how long such code (code whose indentation would be invalid if it were not wrapped in parentheses) has been allowed — maybe always, maybe during one of the indentation relaxations (https://github.com/fsharp/fslang-design/blob/main/FSharp-4.7/FS-1070-offside-relaxations.md) of recent years?

For what it's worth, I have noted before that, regardless of whether the additional indentation relaxations allowed for parenthesized expressions should be considered a bug, there are no such additional indentation relaxations for patterns.

But as @auduchinok points out, it would be a source-breaking change to make the existing allowed relaxations a hard error. It might be possible to add an offsides warning for them under a `langversion` switch? I haven't looked at how hard that would be, though.

**Comment by abonie** [comment]
Closing this as any changes in indentation would need to go through lang-design process first
