### ISSUE TITLE
Type with member keyword bypassed in Fsi now is not executable

### ISSUE THREAD

**Issue by ingted** [dotnet/fsharp#16859]
Please provide a succinct description of the issue.

**Repro steps**

```
type A =
    static ttc () = 123
```
For Microsoft (R) F# Interactive version 12.8.0.0 for F# 8.0
![image](https://github.com/dotnet/fsharp/assets/4289161/6fa89793-bb27-4f21-9291-59a5d0e6dfee)

For Microsoft (R) F# Interactive version 12.8.202.0 for F# 8.0
![image](https://github.com/dotnet/fsharp/assets/4289161/76bb8424-8289-400a-9c34-8fcf34cbc9bb)

**Expected behavior**

Code with bypassed member keyword should still be executable.

**Actual behavior**

Code with bypassed member keyword is not executable.

**Known workarounds**

No?!

**Related information**

**Comment by vzarytovskii** [comment]
"member" never supposed to be omitted, and always required by design.

**Comment by T-Gro** [comment]
It was an accidental bug introduced by parser recovery changes, which was "live" in some versions of F# 7 and first release of F# 8. And never announced, supported nor documented.

Was fixed with this PR: https://github.com/dotnet/fsharp/pull/16345
