### ISSUE TITLE
Error MSB6006: "fscAnyCpu.exe" exited with code -1073741571

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#16867]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-MSB6006:-fscAnyCpuexe-exited-wi/10611054)._

---
\[severity:I’m unable to use this version\] \[regression\] \[worked-in:17.8.7\]  
\[error\]C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\CommonExtensions\\Microsoft\\FSharp\\Tools\\Microsoft.FSharp.Targets(331,9): Error MSB6006: “fscAnyCpu.exe” exited with code -1073741571.  
Visual Studio 2022 build 17.9.2  
Does not happen with build 17.8.7

We have a solution consisting of over 240 projects - most are written in C#, but some (approximately 20) are written in F#.  
The automated CI/CD build ran successfully on 20th Feb against Windows image 20240211.1.0, but since then has failed.  
It always fails with the above error in **2** of the F# projects (the rest of them are fine, except where they depend on the 2 failed projects).  
It fails when I re-run the last successful build.
There have been no changes to the source code, build pipelines or scripts.

I also tried with a hosted agent where the local computer is running VS 2022 Pro build 17.9.2 - same error.

I am able to build the solution on my local computer running VS 2022 Pro build 17.8.7, but not with the automated CI/CD pipelines.

We are now unable to create product releases for our Cloud-based solution and deploy any fixes or changes.

---
#### Feedback Bot on 3/8/2024, 04:16 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by vzarytovskii** [comment]
Feedback ticket: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1991288

**Comment by semaxtremesoftware** [comment]
Hi Vlad,

Thanx for contacting me and escalating this - much appreciated.
I have managed to obtain the binary build log and have uploaded it with this message.
I am eagerly looking forward to resolution as we are currently unable to build and deploy our solution.

Thanx,
Alon

[buildLog.zip](https://github.com/dotnet/fsharp/files/14595159/buildLog.zip)

**Comment by vzarytovskii** [comment]
So, the reason is it's failing with SO
<img width="364" alt="image" src="https://github.com/dotnet/fsharp/assets/1260985/65827361-3b52-4905-abf9-d0a5b66c6b63">

Not entirely sure where specifically, but might be related to the #16869.

In the project it's failing in, do you happen to have complex expressions or something of sorts?

**Comment by vzarytovskii** [comment]
@semaxtremesoftware I have explained what's likely happening and possible workaround in https://github.com/dotnet/fsharp/issues/16869#issuecomment-1997197529, could you please try it.
If it doesn't help, could you please add `<OtherFlags>$(OtherFlags) --times</OtherFlags>` to one of the problematic `fsproj` files (to the properties), then try building it with `-v:n` **or** collecting the binlog again and sharing it here. This flag will allow us to see at which point it's getting the SO.

Thanks in advance.

**Comment by semaxtremesoftware** [comment]
Hi,
Just to state that this issue only occurred after upgrading to VS 17.9.2 - on VS 17.8.7 it is working without issues.

**Comment by semaxtremesoftware** [comment]
Me again,
Looking at the 1 project - it has 2 .fs files in it and a reference to one of the F# projects.
The referenced project is also referenced by several other projects that build without issue, so I am assuming the issue is not in that project.
The 1 .fs file only has a couple of functions in it - nothing very complex
The other file however consists of:
- an enum / type definition for icons consisting of about 4238 lines / elements / values
- a couple of simple functions
- a few (4238) calls to the simple functions to initialise variables used to display various icons

A few examples:
### Type / Enum declaration
[<StringEnum>]
type Icon =
    | [<CompiledName("fa-0")>] Fa0
    | [<CompiledName("fa-1")>] Fa1
    | [<CompiledName("fa-2")>] Fa2
...

### Functions
[<Emit("$0")>]
let inline private getClassForIcon (i: Icon) : string = jsNative

let inline createIcon id classNames icon =
    let cn = ("fal" |> cssClassNameOnly) :: (icon |> getClassForIcon |> cssClassNameOnly) :: classNames
    createIdiomaticText id cn ""

### Variable initialisation
let inline fa0Icon id classNames = createIcon id classNames Fa0
let inline fa1Icon id classNames = createIcon id classNames Fa1
let inline fa2Icon id classNames = createIcon id classNames Fa2
...

Again, this was all working on VS 2022 17.8.7

I'll try generate a new binlog file with the additional properties and upload it

**Comment by vzarytovskii** [comment]
> Hi,
> 
> Just to state that this issue only occurred after upgrading to VS 17.9.2 - on VS 17.8.7 it is working without issues.

Thanks, did setting the evnvironment I described in the other comment change anything? Or is it still crashing? Could you please also build with --times:output.csv flag instead and attach this file?

**Comment by semaxtremesoftware** [comment]
How would I set that in the Azure pipeline to build in the Cloud?
Would that just be another variable that I set and pass through to the pipeline (Library)?

I'm currently running the builds in VS 2022 on local PC and in VM - 1 has 17.8.7 and the other 17.9.2
I'll upload binlogs for both, and for the 17.9.2 version, with the different settings (50, 70 and 40) if they fail

**Comment by semaxtremesoftware** [comment]
I have tried setting the FSHARP_TcStackGuardDepth to 40, 50 and 70 - same error each time.
I also tried with --times:times.csv but that only produced a CSV file header - no actual times were logged to the file.
[times.csv](https://github.com/dotnet/fsharp/files/14611184/times.csv) - output file for timings
[NotWorking_70.zip](https://github.com/dotnet/fsharp/files/14611186/NotWorking_70.zip) - FSHARP_TcStackGuardDepth set to 70
[NotWorking_50.zip](https://github.com/dotnet/fsharp/files/14611188/NotWorking_50.zip) - FSHARP_TcStackGuardDepth set to 50
[NotWorking_40.zip](https://github.com/dotnet/fsharp/files/14611190/NotWorking_40.zip) - FSHARP_TcStackGuardDepth set to 40
[NotWorking.zip](https://github.com/dotnet/fsharp/files/14611191/NotWorking.zip) - no value set for FSHARP_TcStackGuardDepth

**Comment by semaxtremesoftware** [comment]
I have also uploaded these as well as the binlog data from my PC where it is working (VS 17.8.7) to the Secure File Exchange 2402270030000411 area.
Perhaps you can compare the binlogs from an environment where it is working, to one where it is failing and work out what the issue is from there.

Thanx again for your time and effort to get this resolved.

**Comment by vzarytovskii** [comment]
> I have tried setting the FSHARP_TcStackGuardDepth to 40, 50 and 70 - same error each time.
> 
> I also tried with --times:times.csv but that only produced a CSV file header - no actual times were logged to the file.
> 
> [times.csv](https://github.com/dotnet/fsharp/files/14611184/times.csv) - output file for timings
> 
> [NotWorking_70.zip](https://github.com/dotnet/fsharp/files/14611186/NotWorking_70.zip) - FSHARP_TcStackGuardDepth set to 70
> 
> [NotWorking_50.zip](https://github.com/dotnet/fsharp/files/14611188/NotWorking_50.zip) - FSHARP_TcStackGuardDepth set to 50
> 
> [NotWorking_40.zip](https://github.com/dotnet/fsharp/files/14611190/NotWorking_40.zip) - FSHARP_TcStackGuardDepth set to 40
> 
> [NotWorking.zip](https://github.com/dotnet/fsharp/files/14611191/NotWorking.zip) - no value set for FSHARP_TcStackGuardDepth
> 
> 

Hm, there seems to be no difference between runs, as if environment variable didn't take effect. Do you happen to reproduce it locally if you run VS17.9 on your machine? Also, is there any chance you can share project privately with any of us?

**Comment by vzarytovskii** [comment]
I tried to reproduce it locally, from description of your project, but it seems to be working for me even with 10000 enum and 10000 functions. 

Another thing to try (to make sure environment variables are set properly), please add the following to your project(s) which is(are) failing:

```xml
<UsingTask
    TaskName="SetEnvironmentVariableTask"
    TaskFactory="RoslynCodeTaskFactory"
    AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">

    <ParameterGroup>
      <Name ParameterType="System.String" Required="true" />
      <Value ParameterType="System.String" Required="true" />
    </ParameterGroup>

    <Task>
      <Using Namespace="System" />
      <Code Type="Fragment" Language="cs">
        <![CDATA[
          Environment.SetEnvironmentVariable(Name, Value);
        ]]>
      </Code>
    </Task>

  </UsingTask>

  <Target BeforeTargets="CoreCompile" Name="SetStackGuard">
    <SetEnvironmentVariableTask Name="FSHARP_DefaultStackGuardDepth" Value="50"/>
    <SetEnvironmentVariableTask Name="FSHARP_TcStackGuardDepth" Value="50" />
    <SetEnvironmentVariableTask Name="FSHARP_AccFreeVars" Value="50"/>
    <SetEnvironmentVariableTask Name="FSHARP_FindUnsolvedStackGuardDepth" Value="50"/>
    <SetEnvironmentVariableTask Name="FSHARP_DetupleRewriteStackGuardDepth" Value="50"/>
    <SetEnvironmentVariableTask Name="FSHARP_InnerLambdasToTopLevelFunctionsStackGuardDepth" Value="50"/>
    <SetEnvironmentVariableTask Name="FSHARP_LowerCallsRewriteStackGuardDepth" Value="50"/>
    <SetEnvironmentVariableTask Name="FSHARP_IlxGenStackGuardDepth" Value="50"/>
  </Target>
```

**Comment by vzarytovskii** [comment]
Also additionally, **separate from the previous comment**, if you could try adding 
```xml
<FSharpPreferNetFrameworkTools>true</FSharpPreferNetFrameworkTools>
<FSharpPrefer64BitTools>false</FSharpPrefer64BitTools>
```
To your project's properties (`PropertyGroup`) and try rebuilding, to see if it still shows.

Sorry, trying all possible combinations I can think of without repro :(

**Comment by vzarytovskii** [comment]
Third thing to try is (unless you're using some new language features) to set `<LangVersion>7</LangVersion>` property to the problematic project(s), this might reduce some codegen, and can be a workaround until we find a proper solution.

**Comment by vzarytovskii** [comment]
Hm, so, good (ish) news that it seems we managed to reproduce it (though it might be helpful to at least see the initial code to confirm we reproduce the same issue). Bad news is that I don't (yet) see an easy workaround:

Project1, 2 files: Library.fs, Functions.fs
Library.fs:
```fsharp
module Foo.Icons
type Icons =
| [<CompiledName("fa-0")>] Fa0
| [<CompiledName("fa-1")>] Fa1
| [<CompiledName("fa-2")>] Fa2
| [<CompiledName("fa-3")>] Fa3
| [<CompiledName("fa-4")>] Fa4
| [<CompiledName("fa-5")>] Fa5
/// repeated until around 4000 lines with last case being Fa4000
```
Functions.fs:
```fsharp
module Foo.Functions
open Foo.Icons
let inline createIcon id classNames icon = (id, classNames, icon)
let inline fa0Icon id classNames = createIcon id classNames Fa0
let inline fa1Icon id classNames = createIcon id classNames Fa1
let inline fa2Icon id classNames = createIcon id classNames Fa2
let inline fa3Icon id classNames = createIcon id classNames Fa3
// Also repeated around 4k times, resulting in 4k bindings
```

![image](https://github.com/dotnet/fsharp/assets/1260985/7e7f1b19-252b-4f8f-ab05-9541b1216c15)

![image](https://github.com/dotnet/fsharp/assets/1260985/c6fa1382-77a7-4033-b597-45a7c16a394e)

So it overflows while trying to check all 4000 bindings in one namespace/module. We will likely be able to "hot fix" the issue by introducing the stack guard on it, and be able to backport it to 17.9. Meanwhile - can you stick to 17.8 when building now until we release a fix?

And again - if you can privately share this one project with us - it will be a tremendous help as well, since we will be able to make sure we fixed your particular issue as well.

**Comment by vzarytovskii** [comment]
One thing to add - dotnet build is not stackovqerflowing, only compiler from VS distribution is affected (as it seems).

**Comment by vzarytovskii** [comment]
This happens because code like this
```
let foo1 = "foo1"
let foo2 = "foo2"
let foo3 = "foo3"
...
```
Compiles to something like
```fsharp
let foo1 = "foo1" in
    let foo2 = "foo2" in
        let foo3 = "foo3" ...
```

Which results in very deep recursive type checking (which exhausts the stack space available for compiler).

Workaround from the "code" perspective would be to move functions to be static members in type, instead of module, like

```fsharp
// instead of
module Foo =
  let inline foo1 x y = "foo"
  let inline foo2 x y = "foo"
// do this
type Foo =
  static member inline foo1 x y = "foo"
  static member inline foo2 x y = "foo
```
These expressions won't "nest" and will type check much faster and without overflowing.

**Comment by semaxtremesoftware** [comment]
I added the XML above to the F# project that is failing - it is still failing - attached are the binlogs.
I will see if I can change the build yaml to use dotnet build as opposed to the VSBuild task
I'm actually not the F# developer - he is away at the moment - I'm just trying to get the solution to build in the interim, so if I don't have to make any code changes it would be preferable in the interim.

[StillNotWorking.zip](https://github.com/dotnet/fsharp/files/14646136/StillNotWorking.zip)

**Comment by vzarytovskii** [comment]
> I added the XML above to the F# project that is failing - it is still failing - attached are the binlogs.
> 
> I will see if I can change the build yaml to use dotnet build as opposed to the VSBuild task
> 
> I'm actually not the F# developer - he is away at the moment - I'm just trying to get the solution to build in the interim, so if I don't have to make any code changes it would be preferable in the interim.
> 
> 
> 
> [StillNotWorking.zip](https://github.com/dotnet/fsharp/files/14646136/StillNotWorking.zip)
> 
> 

XML advise was before we figured out where is the issue. Please refer to my last comment above, it has 4 different "solutions" to the problem. I say easiest one is to make module/namespace "rec"

**Comment by semaxtremesoftware** [comment]
Hi @vzarytovskii ,
Do you have any indication as to when the patch will be included in a VS release?
While the bug has been fixed, I am still unable to build correctly until the fix finds its way into a VS release that will be included in the Windows image used by the DevOps Build Agent.

**Comment by vzarytovskii** [comment]
It will be released as part of 17.10. I described the workaround in one of the previous comments, the easiest one is to make module/namespace recursive (add rec keyword to it).

**Comment by brianrourkeboll** [comment]
> It will be released as part of 17.10. I described the workaround in one of the previous comments, the easiest one is to make module/namespace recursive (add rec keyword to it).

@semaxtremesoftware 

To make it easier: in the file with lots of `let`-bindings that is causing this problem, all you need to do is change `module Foo` to `module rec Foo`, where `Foo` is the module holding the bindings. (It could also be `module Foo.Bar.Baz` or whatever, depending; then it would become `module rec Foo.Bar.Baz`, etc.)

**Comment by semaxtremesoftware** [comment]
Hi @vzarytovskii and @brianrourkeboll 

Thanx for the suggestion - it was easy to make (4 projects in total) and the build now is completing.
We eagerly await release 17.10

Thanx for the assistance and response to this - I really appreciate it.

**Comment by vzarytovskii** [comment]
> Hi @vzarytovskii and @brianrourkeboll 
> 
> 
> 
> Thanx for the suggestion - it was easy to make (4 projects in total) and the build now is completing.
> 
> We eagerly await release 17.10
> 
> 
> 
> Thanx for the assistance and response to this - I really appreciate it.

Glad it worked and sorry for inconvenience. We'll work more on improving these parts of compiler, thanks for providing all the info!
