### ISSUE TITLE
LSP: Get command line arguments using ProjectQuery API

### ISSUE THREAD

**Issue by abonie** [dotnet/fsharp#16872]
Get compiler command line arguments to initialize workspace with. Should be possible to get through ProjectQuery API now.

**Comment by nojaf** [comment]
Hi @abonie, what is the `ProjectQuery API`?
Is it related to the workspace idea @0101 has?

**Comment by vzarytovskii** [comment]
> Hi @abonie, what is the `ProjectQuery API`?
> 
> Is it related to the workspace idea @0101 has?

It isn't, its how we ask VS about project, what proj-info does in fsac

**Comment by abonie** [comment]
As Vlad said, it is basically [this](https://learn.microsoft.com/en-us/visualstudio/extensibility/visualstudio.extensibility/project/project?view=vs-2022), more of an implementation detail I suppose.
