### ISSUE TITLE
Compiler error with iteration and units of measure in F# 17.10 preview with LangVersion Preview

### ISSUE THREAD

**Issue by marklam** [dotnet/fsharp#17025]
A for loop over units of measure can create a compiler error where compilation previously succeeded

**Repro steps**

Provide the steps required to reproduce the problem:

```f#
module Measures

// Visual Studio & F#
//    Microsoft Visual Studio Community 2022
//    Version 17.10.0 Preview 3.0
//    VisualStudio.17.Preview/17.10.0-pre.3.0+34804.81
//    Microsoft .NET Framework
//    Version 4.8.09032
//
//    Visual F# Tools   17.10.0-beta.24172.5+8d852e43d35fdac96b1ba52e3bd4b35350035914
//    Microsoft Visual F# Tools

// Compiled with
//     <TargetFramework>net8.0</TargetFramework>
//     <LangVersion>Preview</LangVersion>

type [<Measure>] m
let length = 10<m>

let tenth = length / 10

for i in tenth .. 1<m> .. (length-1<m>) do
    ()

// ...\Library.fs(22,7): error FS0073: internal error: Unrecognized numeric type '?12527 (solved)'.
```

Git repo:

https://github.com/marklam/FSharp17_10_LangVersion_Preview_MeasuresBug

**Expected behavior**

Compilation succeeds

**Actual behavior**

error FS0073: internal error: Unrecognized numeric type '?12527 (solved)'.

**Known workarounds**

**Related information**
*    Microsoft Visual Studio Community 2022
*    Version 17.10.0 Preview 3.0
*    VisualStudio.17.Preview/17.10.0-pre.3.0+34804.81
*    Microsoft .NET Framework
*    Version 4.8.09032

**Comment by vzarytovskii** [comment]
If it's preview, might be related to something @brianrourkeboll was optimizing. I can look at it next week.

**Comment by brianrourkeboll** [comment]
I'll take a look.

**Comment by brianrourkeboll** [comment]
@marklam I have a fix for this in #17040.

Thanks for giving the preview features a try — I'm glad this was found sooner rather than later!

**Comment by marklam** [comment]
@brianrourkeboll - did https://github.com/dotnet/fsharp/pull/17040 not make it into the release of 17.10?

**Comment by vzarytovskii** [comment]
> @brianrourkeboll - did #17040 not make it into the release of 17.10?

No, only 17.11, cutoff 17.10 was before the fix was made, and unfortunately, since it's langversion preview, it doesn't meet the backport bar:
<img width="399" alt="image" src="https://github.com/dotnet/fsharp/assets/1260985/9f0fae18-160d-446d-9a50-3ee21b3fd94e">

**Comment by brianrourkeboll** [comment]
@marklam it doesn't look like it: https://github.com/dotnet/fsharp/compare/release/dev17.10...main

![image](https://github.com/dotnet/fsharp/assets/14795984/198d0586-61ce-40fc-8fd4-81ef79b31885)

**Comment by vzarytovskii** [comment]
> Yes, I can confirm it's working in the 17.11 preview, so there's a choice - 17.9 or 17.11preview.
> 
> @vzarytovskii if it's not to be backported that presumably means it won't be in any 17.10.x release?

Yes, that's correct, I think by the time we move the feature to langversion=9, it will be shipping with 17.11.
