### ISSUE TITLE
The term 'fsi' is not recognized as the name of a cmdlet, function, script file,  or operable program

### ISSUE THREAD

**Issue by vrishan0** [dotnet/fsharp#17041]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/languages/fsharp-hello-world-tutorial/create
Operating System: windows
![Screenshot 2024-04-13 162031](https://github.com/dotnet/fsharp/assets/165998646/800fb5c1-c810-4c7a-a86f-8961f56fdb22)

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by vzarytovskii** [comment]
> Problem encountered on https://dotnet.microsoft.com/en-us/learn/languages/fsharp-hello-world-tutorial/create
> 
> Operating System: windows
> 
> ![Screenshot 2024-04-13 162031](https://github.com/dotnet/fsharp/assets/165998646/800fb5c1-c810-4c7a-a86f-8961f56fdb22)
> 
> 
> 
> 
> 
> Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I don't see mention of "fsi" in the linked tutorial, only "dotnet run", and in other tutorials I see "dotnet fsi". But even in this case it might not always universally work with arbitrary fs file.

**Comment by vrishan0** [comment]
i was using vscode i don't it got  glitched or not but after updating it got fixed now it is running with dotnet fsi and i fixed that extension .fsx and thx for making me know about it
