### ISSUE TITLE
Static abstract method on class or abstract class yields internal error

### ISSUE THREAD

**Issue by brianrourkeboll** [dotnet/fsharp#17044]
Declaring a static abstract method on an abstract class fails with an internal error that does not surface in the tooling (VS or Ionide).

**Repro steps**

1. Define a static abstract member in an abstract class.
2. The tooling shows no errors, but attempting to build yields an internal error.

```fsharp
#nowarn "3535"

[<AbstractClass>]
type A () =
    static abstract M : unit -> unit

type B () =
    inherit A ()
    static member M () = printfn "99"

B.M ()
```

```stderr
error FS0193: internal error: Unable to load one or more of the requested types.
Virtual Static Method.
Virtual Static Method.
```

A similar error happens for regular classes:

```fsharp
#nowarn "3535"

type A () =
    static abstract M : unit -> unit
```

```
error FS0193: internal error: Unable to load one or more of the requested types.
Abstract method in non-abstract class.
```

**Expected behavior**

I would expect an error message that explicitly disallowed static abstract methods in classes and abstract classes. I would also expect this message to show in the IDE.

**Actual behavior**

An internal error is raised in the compiler, and no error message is shown in the IDE.

**Known workarounds**

N/A.

**Related information**

This happens on current `main` (and probably earlier versions).

**Comment by edgarfgp** [comment]
I think I have fix for this in a local branch somewhere 😅. Will try and raise a PR during the week if it is still available .

**Comment by abonie** [comment]
Static abstract should be disallowed in abstract classes and only allowed in interfaces. But internal error is a bug for sure.
