### ISSUE TITLE
Transparent Compiler: Fails when signature file is not exactly next to source file

### ISSUE THREAD

**Issue by TheAngryByrd** [dotnet/fsharp#17082]
Please provide a succinct description of the issue.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Create a project with multiple files that don't depend on each other
2. Use a wildcard to add all the files. see [fsautocomplete](https://github.com/ionide/FsAutoComplete/blob/ab6a49d7e423128884ca38b17c99cb520c039a69/src/FsAutoComplete/FsAutoComplete.fsproj#L37-L38)

**Expected behavior**

Typechecking completes

**Actual behavior**

Type checking fails with "Oops!!" exception

**Known workarounds**

Comment out https://github.com/dotnet/fsharp/blob/f68d7b60cafcac940754774ee34d8cf8e90ab754/src/Compiler/Service/TransparentCompiler.fs#L1418-L1422

**Related information**

Provide any related information (optional):

* Operating system
* .NET Runtime kind (.NET Core, .NET Framework, Mono)
* Editing Tools (e.g. Visual Studio Version, Visual Studio)

**Comment by vzarytovskii** [comment]
Yeah, it's fine to remove/comment it as we do with physical file. Feel free to do it in PR.

**Comment by majocha** [comment]
The same false assumption that signature must immediately precede implementation exists in `IncrementalBuild`. It does not throw, but I think it may lead to needless type checks.
