### ISSUE TITLE
Cannot specific a SRTP property constraint as `with get, set`

### ISSUE THREAD

**Issue by Tangent-90** [dotnet/fsharp#17100]
```fsharp
let inline length (x: ^a when ^a: (member Length: int with get, set)) = x.set_Length(1);;
```

![图片](https://github.com/dotnet/fsharp/assets/43789618/8f437839-9be0-4ad6-84f3-cd9aa295bf43)

**Expected behavior**

Can build successfully.

**Actual behavior**

The compiler says that was an invalid constraint.

**Known workarounds**

divide the getter and setter apart

```fsharp
let inline length (x: ^a when ^a: (member Length: int with get) and ^a: (member Length: int with set)) = x.set_Length(1);;
```

**Comment by vzarytovskii** [comment]
That's not a bug, it's by design.

**Comment by vzarytovskii** [comment]
I wouldn't call it a bug, it's been like this forever.

**Comment by T-Gro** [comment]
Right now, one member leads to 1 constraint, and the suggested workaround is the way to go.
This would be a change in the language raised and approved via fslang-suggestions.
