### ISSUE TITLE
No compile-time error for partial implementation of interface with static abstract members

### ISSUE THREAD

**Issue by brianrourkeboll** [dotnet/fsharp#17138]
There is no compile-time error if a type only partially implements an interface with static abstract members (IWSAM). If you try to use the partial implementation, a `System.TypeLoadException` is raised at runtime.

**Repro steps**

```fsharp
#nowarn "3535"

type IFace =
    static abstract P1 : int
    static abstract P2 : int

type T =
    interface IFace with
        static member P1 = 1

let inline p1<'T & #IFace> = 'T.P1

p1<T>
```

Runtime error:

```stderr
Unhandled exception. System.TypeLoadException: Virtual static method 'get_P2' is not implemented on type 'T' from assembly 'ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at <StartupCode$ConsoleApp1>.$Program.main@()
```

**Expected behavior**

There should be a compile-time error indicating that all abstract methods on the interface must be implemented.

**Actual behavior**

There is no compile-time error; there is an error at runtime instead.

**Known workarounds**

N/A

**Related information**

.NET 8/9 preview.

**Comment by vzarytovskii** [comment]
It's a regression, since this is what 8.0.100 gives me:
```fsharp
type IFace =
    static abstract P1 : int
    static abstract P2 : int

type T =
    interface IFace with
        static member P1 = 1

let inline p1<'T & #IFace> = 'T.P1
```

**Comment by vzarytovskii** [comment]
And 8.0.201 has the issue, so it happened somewhere in-between

**Comment by edgarfgp** [comment]
I have seen this few week ago. I think we would need to remove the IsInstance check here https://github.com/dotnet/fsharp/blob/7b0586c89f8ceffe72e6c78a4a430648f45a7b27/src/Compiler/Checking/MethodOverrides.fs#L383

**Comment by vzarytovskii** [comment]
> @vzarytovskii I have seen this few week ago. I think we would need to remove the IsInstance check here
> 
> https://github.com/dotnet/fsharp/blob/7b0586c89f8ceffe72e6c78a4a430648f45a7b27/src/Compiler/Checking/MethodOverrides.fs#L383

It might be it, however PR it was introduced in wasn't in 17.9 (8.0.201).
