### ISSUE TITLE
Impossible viable fork

### ISSUE THREAD

**Issue by Adahel** [dotnet/fsharp#17183]
**Is your feature request related to a problem? Please describe.**

This is an issue I have gone into detail about in the past with Microsoft Copilot, and I believe showing the conversation will be better than any clear and concise description of the issue, but if there are one or more complaints about the lack of description I will edit and do my best to add the brief description here.

1 - Don't take the prompt I used in artificial intelligence as true; I had to distort it a little to be able to force the Microsoft Copilot to talk about the subject he didn't want to talk about. To make the prompt make a little more sense, replace the phrase backport to .NET with backport to .NET Framework 4 and it will make more sense.

2 - Microsoft Copilot did not find smooth alternative solutions for my problem, which means that I will have to use non-soft alternatives if this issue that I opened here on GitHub is not resolved.

https://sl.bing.net/he65gwPYzfM

**Describe the solution you'd like**

I only have a non-soft solution in the context of the shared Microsoft Copilot link. ← I can add the description if there are complaints, as stated above.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by baronfel** [comment]
Please extract an actual question. Your chat session link seems to say that you can't strong name sign the binaries, but it's incredibly silly to have to read a whole conversation to extract a question that you could just have easily formulated.

**Comment by vzarytovskii** [comment]
Please reopen with specific question.
