### ISSUE TITLE
[Feature request] Support solution view where projects are ordered based on number of dependent projects.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#17222]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Feature-request-Support-solution-view-/10525611)._

---
From the architectural standpoint it's useful to track the dependencies between the solution projects.
For example, F# project requires files to be ordered, and types defined in lower files are not available to the upper ones.
It would be very convenient to view projects of the solution ordered by number of dependencies.
It's debatable how to resolve the ties, but in general it should look like:

-Domain
- Infra
- App
- Api
- Api.Tests

---
#### Feedback Bot on 11/27/2023, 05:57 AM: 

(private comment, text removed)

**Comment by voroninp** [comment]
I have no clue why they moved this under F#.

I just used it as an example.:-)

**Comment by vzarytovskii** [comment]
> I have no clue why they moved this under F#.
> 
> I just used it as an example.:-)

I think rule of thumb for the triaging for them is "if in mentions F#, it goes under F#", and I apparently didn't do a great job of reading it carefully and figuring out that it's not F# specific 🤦

**Comment by abonie** [comment]
Since the original issue got closed, could you recreate it on Developer Community please (without mentioning F# maybe :D)
