### ISSUE TITLE
Provide better github.dev links for updating release notes

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#17244]
Hi, I've noticed that it's possible to create a link to a specific file in a PR, like [this](https://github.dev/dotnet/fsharp/pull/17232/docs/release-notes/.FSharp.Compiler.Service/8.0.400.md). Would it be possible to update the CI step, so links in [the comments](https://github.com/dotnet/fsharp/pull/17233#issuecomment-2126775414) would open files needing updates?

Thank you :)

**Comment by vzarytovskii** [comment]
> Hi, I've noticed that it's possible to create a link to a specific file in a PR, like [this](https://github.dev/dotnet/fsharp/pull/17232/docs/release-notes/.FSharp.Compiler.Service/8.0.400.md). Would it be possible to update the CI step, so links in [the comments](https://github.com/dotnet/fsharp/pull/17233#issuecomment-2126775414) would open files needing updates?
> 
> Thank you :)

It doesn't work in GitHub.dev, that's the first think I've tried (this is what opens when I click the link):
<img width="1508" alt="image" src="https://github.com/dotnet/fsharp/assets/1260985/294ad830-76f9-42e7-a05b-1a46a7656350">

**Comment by auduchinok** [comment]
> It doesn't work in GitHub.dev, that's the first thing I've tried when I made the check (this is what opens when I click the link)

Hm, this is strange. I get the needed tab open when I open the link:

<img width="1436" alt="Screenshot 2024-05-24 at 15 14 09" src="https://github.com/dotnet/fsharp/assets/3923587/e9bcdecf-1a40-42be-bd9b-57df037b0d91">

**Comment by vzarytovskii** [comment]
It keeps tabs from previous time you've opened github.dev, this is if you closed all editors, it only opens one:
<img width="1508" alt="image" src="https://github.com/dotnet/fsharp/assets/1260985/9ba183c7-5b4c-418e-8a44-147dfb4e3f8e">

**Comment by auduchinok** [comment]
Ah, what a shame 🙁

**Comment by vzarytovskii** [comment]
> Ah, what a shame 🙁

Yeah, I tried to reverse-engineer the way how it works (if any), and didn't succeed.
