### ISSUE TITLE
Making TypeProviders easier: FS3033 needs base exception message

### ISSUE THREAD

**Issue by Thorium** [dotnet/fsharp#17249]
When I'm using different type-providers (a lot) and they use external dependency dlls, which throw an error, the F# compiler throws generic `FS3033: The type provider '%s' reported an error: %s`

The error is typically:
"The type initializer for 'some.dll' threw an exception."

What I would like to get is, if the inner-exception is not null (usually not) then `.GetBaseException().Message` of that too, like:
`FS3033: The type provider '%s' reported an error: %s ...with details: %s`

The workaround most developers do:
- Open issue to corresponding TypeProvider's repo
- Curse both F# and TypeProviders
- And wait the author to debug, meanwhile continue writing their C#.

The workaround I do:
- Download the TypeProvider from the GitHub, 
- Compile it in debug-mode
- Replace my NuGet cache dll files with built debug-versions
- Then open the TP project and attach VS to my process throwing the error
- ...and yes I do get the error, which is typically very simple to fix once you know it. Typically just another dll missing:

![image](https://github.com/dotnet/fsharp/assets/229355/4a322b30-906a-4517-a368-268d3cc072c2)

A simple fix would already had kept many devs in F#.

**Comment by abelbraaksma** [comment]
I think this makes sense and is likely a simple change to do. I do use TPs and indeed, if they fail, it can be hard to diagnose.

**Comment by smoothdeveloper** [comment]
related to #4978

**Comment by Thorium** [comment]
I hope the merged commit will fix this.
