### ISSUE TITLE
Move to 1ES SBOM from the one we use in Arcade

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#17265]
We need to disable arcade's SBOM generation and use 1ES one in VSIX, ~~otherwise our insertions might be blocked by the end of June~~ there's no deadline as for now.

We might need to see how Roslyn does that, I presume @jjonescz might've done it for Roslyn?

**Comment by jjonescz** [comment]
> I presume @jjonescz might've done it for Roslyn?

No, we currently use [arcade's SBOM generation](https://github.com/dotnet/roslyn/blob/a775d9343e3e914e6237369631191e43fdebb0f6/azure-pipelines-official.yml#L295-L298) and have the [1ES one disabled](https://github.com/dotnet/roslyn/blob/a775d9343e3e914e6237369631191e43fdebb0f6/azure-pipelines-official.yml#L91-L92).

> We need to disable arcade's SBOM generation and use 1ES one in six

Interesting, I didn't know that. What does "in six" means in this sentence?

**Comment by T-Gro** [comment]
Probably was meant to be "vsix" ?

**Comment by vzarytovskii** [comment]
Yeah, it's VSIX, fat fingered six. I, for some reason, was under the impression that you also moved to it. We as well use arcade's one for now.

**Comment by vzarytovskii** [comment]
> No, we currently use [arcade's SBOM generation](https://github.com/dotnet/roslyn/blob/a775d9343e3e914e6237369631191e43fdebb0f6/azure-pipelines-official.yml#L295-L298) and have the [1ES one disabled](https://github.com/dotnet/roslyn/blob/a775d9343e3e914e6237369631191e43fdebb0f6/azure-pipelines-official.yml#L91-L92). But I will take a look.

Yeah, same. We use arcade's one, and 1es is disabled for us.

**Comment by jjonescz** [comment]
Is this really fixed? You still have 1ES SBOM generation disabled:

https://github.com/dotnet/fsharp/blob/a4666e226f6f37c29128b37361175a52bf09c282/azure-pipelines.yml#L73-L75

**Comment by vzarytovskii** [comment]
No, it got fixed (our sbom check was failing, but it's not yet moved to 1ES from Arcade, I will keep this one open).

**Comment by vzarytovskii** [comment]
https://vsdrop.corp.microsoft.com/file/v1/Products/internal/dotnet-fsharp/dev17.11/20240605.1;Microsoft.FSharp.vsman manifest seems to be correct though for the latest insertion.

**Comment by psfinaki** [comment]
The latest insertion was all green: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/556072
I am keeping on eye on insertions, we didn't get new ones since then, but things look hopeful.

**Comment by vzarytovskii** [comment]
> The latest insertion was all green: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/556072 I am keeping on eye on insertions, we didn't get new ones since then, but things look hopeful.

It being green might not be enough, steps need to actually check manifests, and they (manifests) have toe actually have all the sbom json files in place.

**Comment by KevinRansom** [comment]
This is fixed, our build works correctly again.  And we don't really need to move away from arcade.  The vscore guy I spoke to said "It probably does a better job than ours" which amused me.
