### ISSUE TITLE
Missing message with type error (FS0001)

### ISSUE THREAD

**Issue by glchapman** [dotnet/fsharp#17373]
Building (`dotnet build`) the attached project prints at the console an error FS0001 with a location in Program.fs, but does not print an message informative message. I would expect a message along the lines of 

foo expects a `seq<'a * 'b * 'c>`, but is called with a `seq<'a * 'b>`

I'm using compiler version 12.8.300.0 for F# 8.0. The product version of fsc.exe is "12.8.300-beta.24228.1+dd749058c91585e9b5dae62b0f8df892429ee28f"
[errmsg.zip](https://github.com/user-attachments/files/16045758/errmsg.zip)

**Comment by vzarytovskii** [comment]
Works fine in 6.x btw
<img width="1075" alt="image" src="https://github.com/dotnet/fsharp/assets/1260985/f3cc8124-3d6d-4348-b0d8-3ad7f2118546">

**Comment by edgarfgp** [comment]
I think it might be related to this PR https://github.com/dotnet/fsharp/pull/14003

**Comment by vzarytovskii** [comment]
> I think it might be related to this PR #14003

Yeah, that's our working theory rn
