### ISSUE TITLE
Floats inconsistency

### ISSUE THREAD

**Issue by 64J0** [dotnet/fsharp#17418]
I'm having this inconsistency with floats, depending on the notation used:

![image](https://github.com/user-attachments/assets/a9c29e7b-cb8b-4c53-a8c1-8232168a1cd8)

**Repro steps**

1. Open `dotnet fsi` (I'm using .NET 8.0.302).
2. Type `let a : float = 1_000_000_000_000;;`, and notice that it will throw an exception.
3. Type `let a : float = 1e180;;`, and notice that it works fine. You can even multiply this number: `a * 10.;;`. I find it weird that it throws the exception depending on the notation used.
4. @baronfel noticed that this code is valid: `let a: float32 = 1_000_000_000_000f;;`. Although here it returns `val a: float32 = 9.999999959e+11f`, which is not really the input.

**Expected behavior**

Some consistent behavior regarding floats, independent of notation.

**Actual behavior**

The actual behavior was mentioned at the description of the issue. 

**Known workarounds**

-

**Related information**

Provide any related information (optional):

* Operating system: Linux Ubuntu 22.04
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .NET 8.0.302
* Editing Tools (e.g. Visual Studio Version, Visual Studio): bash

**Comment by Martin521** [comment]
b) throws because the RHS is an invalid int literal. This has nothing to do with float.

**Comment by 64J0** [comment]
Just to know, what is RHS @Martin521 ?

**Comment by vzarytovskii** [comment]
> Just to know, what is RHS @Martin521 ?

I presume it's "right hand side", meaning right side of the expression after =
