### ISSUE TITLE
F# profile/setting is missing after installing Dev15 RC

### ISSUE THREAD

**Issue by Matteo-T** [dotnet/fsharp#1747]
1. Install Dev15 RC
2. Pick the "Data" workload (notice that F# is happily included! yay!)
3. Start Visual Studio
4. Look at the offered profile/settings

#### Expected behavior
F# is missing

#### Actual behavior
F# should be there

#### Known workarounds
None that I know of.

#### Related information 
* Operating system: Windows 10 (last Saturday's build)
* Branch: d15rel
* .NET Runtime: 4.6.20006
* Editing Tools (e.g. Visual Studio Version): 15.0.25914.0

![image](https://cloud.githubusercontent.com/assets/19174408/20337447/0ea4ac04-ab86-11e6-91e3-6fbd79cc4cf0.png)

**Comment by KevinRansom** [comment]
@brettfo  could you take look at this please mate.

**Comment by cartermp** [comment]
Note that we also have a VSTS bug about this - we should definitely get it fixed by release.

**Comment by cartermp** [comment]
Closing this out as it is a legacy project system issue, which we won't be addressing.
