### ISSUE TITLE
Disabling LanguageFeature.EnforceAttributeTargets from F# 9.0

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#17514]
This feature mysteriously causes getAllSymbols to duplicate the report some symbols until we understand why this happens and is it correct, I am reverting EnforceAttributeTargets from F# 9.0  back to preview

 Repo:
 With EnforceTargetAttributes set to F# 9.0, in VS using test explorer run the test case observe the failure.

![image](https://github.com/user-attachments/assets/25917fc1-6cd5-40f4-81ef-d0a342cbf206)

**Comment by vzarytovskii** [comment]
FYI @edgarfgp, we will look into it once done with adjusting tests and baselines for 9

**Comment by edgarfgp** [comment]
> FYI @edgarfgp, we will look into it once done with adjusting tests and baselines for 9

Not problem. The duplication of symbols most likely is due to "how in some cases the type check  is duplicated" producing 2-3 times the same errors/warning and in this case symbols.

Let me know if there is anything I can do to help.
