### ISSUE TITLE
Assembly reference 'mscorlib.dll' was not found or is invalid when inside of a Docker container

### ISSUE THREAD

**Issue by KubaZ2** [dotnet/fsharp#17557]
I have implemented F# compilation programmatically and it works locally (on Ubuntu) but it fails inside of a Docker container using `mcr.microsoft.com/dotnet/runtime:8.0` image with `FS0084 Assembly reference 'mscorlib.dll' was not found or is invalid`. I think the source code can be helpful here: [base arguments](https://github.com/KubaZ2/Sharp/blob/main/Bot%2FSharp%2FCompilation%2FFSharpCompiler.cs#L31-L32) (notice that the FilePath is only the file name, not the full path), [full argument construction](https://github.com/KubaZ2/Sharp/blob/main/Bot%2FSharp%2FCompilation%2FFSharpCompiler.cs#L38), [compilation](https://github.com/KubaZ2/Sharp/blob/main/Bot%2FSharp%2FCompilation%2FFSharpCompiler.cs#L66-L68).
You can notice that I have excluded `mscorlib.dll` from references. I have done that, because specifying it in references causes `FS0074 The type referenced through 'System.Array' is defined in an assembly that is not referenced. You must add a reference to assembly 'The system type 'System.Array' was required but no referenced system DLL contained this type'.` locally and without specifying it it works locally without any issues. Specifying it in the Docker container still causes the FS0084 with mscorlib.dll.

**Comment by vzarytovskii** [comment]
I think you're missing "--targetprofile:netcoreapp|netstandard" in the options, hence it's trying to use mscorlib, which is full clr thing. Also, you might want to use sdk docker image and not runtime.

**Comment by KubaZ2** [comment]
Thank you! Using the sdk image resolved the issue for me.

**Comment by vzarytovskii** [comment]
> Thank you! Using the sdk image resolved the issue for me.

Oh, glad it helped. We should probably do a better job documenting FCS use cases.
