### ISSUE TITLE
VS: option pages erroring.

### ISSUE THREAD

**Issue by majocha** [dotnet/fsharp#17602]
This is not the released version, but a vsix built from latest main installed into latest VS 17.12.0 Preview 1.0.

![image](https://github.com/user-attachments/assets/38b47768-45f1-41d2-b786-70266d26b855)

The first commit that breaks this for me is:

[`bc40f6a`](https://github.com/dotnet/fsharp/commit/bc40f6aaaadbe2fb999c0d5357f357fa13113603) (#17537) 

ETA:
External WPF bug: https://github.com/dotnet/wpf/issues/9582

**Comment by majocha** [comment]
![image](https://github.com/user-attachments/assets/53291dbf-89fa-4fbf-a748-a7e9dd576116)
Huh?

**Comment by vzarytovskii** [comment]
Hm, not the first issue with the options - https://github.com/dotnet/fsharp/pull/17015

**Comment by majocha** [comment]
OK it still worked before #17569. Shouldn't take long to bisect.

**Comment by vzarytovskii** [comment]
Wondering if translations are out of date

**Comment by majocha** [comment]
I think all the strings we use in XAML are bound with `x:Static` so anything missing would fail at build.

I suspect some dependencies changed and are somehow conflicting with net472 era WPF in a way that surfaces only at runtime. Roslyn uses quite a lot of XAML in the C# extension, I wonder if they're seeing this problem.

I tried to identify the exact change when this shows up.
The last commit this still works is `6cd4d59`,
the next one: [`bc40f6a`](https://github.com/dotnet/fsharp/commit/bc40f6aaaadbe2fb999c0d5357f357fa13113603) (#17537) it's broken.

**Comment by majocha** [comment]
So, the only change is the update to net9 preview 7.
This looks very much like this https://github.com/dotnet/wpf/issues/9620, but why on earth would it affect us if we're targeting net472🤔?

**Comment by majocha** [comment]
OK, this is very likely external and related to net 9 preview 7 changes.

I created a simple WPF app targeting net472:
![image](https://github.com/user-attachments/assets/073762d4-8ba3-401c-9af8-9b8af62ef640)



It works fine when built and run from stable VS (17.11.1)

but add a global.json with
```
  "sdk": {
    "version": "9.0.100-preview.7.24407.12"
  }
```

and it breaks the same way as our vsix:
![image](https://github.com/user-attachments/assets/827cf78b-7cf4-4f4a-9a6a-b744961407d8)

**Comment by vzarytovskii** [comment]
Thanks for investigating, hopefully it is fixed with rc1.

**Comment by majocha** [comment]
Fixed with 9rc1.
