### ISSUE TITLE
`InvalidProgramException` on string interpolation

### ISSUE THREAD

**Issue by bent-rasmussen** [dotnet/fsharp#17719]
Please provide a succinct description of the issue.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Create a console project with this code

```fsharp
type Foo() =

    let sb = System.Text.StringBuilder()

    member _.Bar(s: System.ReadOnlySpan<char>) = sb.Append(s) |> ignore

let foo = Foo()
let foos = "foo"
foo.Bar($"{foos} is bar")
```

2. Build and run the project

**Expected behavior**

~~`InvalidProgramException`~~

**Actual behavior**

`InvalidProgramException`

**Known workarounds**

* Use let binding for interpolated string and use that in function call
* Use `string` instead of `ReadOnlySpan<char>`
* Do not use string interpolation

**Related information**

Provide any related information (optional):

* Windows 11
* .NET 9 RC1
* Version 17.12.0 Preview 2.0

**Comment by vzarytovskii** [comment]
Yes, we should probably disallow byreflikes when we work with interpolation until we have good escape analysis.

**Comment by T-Gro** [comment]
Workaround: Adding "AsSpan()" at the callsite fixes the runtime error:

https://sharplab.io/#v2:DYLgZgzgNAJiDUAfA9gBwKYDsAEBlAnhAC7oC2AsAFBVH4bYBiyyAFAJTYC8VV2f2wdEWwQARlzyESpAHQAVdAA8iM3EQBOAS0wBzAEIBXTcBjp17HpX7ZSZUWewB9GXoCG5iCEnEyMgErorjAA8pjA+LiorpgAPADGABbuAHwcnCKiMgCCqBiYMCwQHIjJ2Jo6mMjq6JaCwmDMEkysbFR12A3IEBIARJ09VJ0u7iwAJD0A3p0QAL5l3aLuPdkQkdHsbEA==

**Comment by vzarytovskii** [comment]
Also `<LangVersion>8</LangVersion>` fixes it
