### ISSUE TITLE
Allow records to be defined by using position instead of type field names

### ISSUE THREAD

**Issue by cmdoffing** [dotnet/fsharp#17732]
Instead of:
``
let dom: Domain = { 
                    DomainId = domain.DomainId;
                    ContextId = domain.ContextId;
                    DomainName = domain.DomainName;
                    DomainDoc = domain.DomainDoc;
                    DomainDeleted = domain.DomainDeleted
                  }
``
allow:
``
let dom: Domain = { 
    domain.DomainId;
    domain.ContextId;
    domain.DomainName;
    domain.DomainDoc;
    domain.DomainDeleted
}
``

**Comment by vzarytovskii** [comment]
This should instead go to https://github.com/fsharp/fslang-suggestions

**Comment by cmdoffing** [comment]
Ok, thanks for the reply.

**Comment by charlesroddie** [comment]
There is an RFC for this feature here: https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1073-record-constructors.md

**Comment by cmdoffing** [comment]
Thanks, I'll check it out.
