### ISSUE TITLE
Nullness issue - unclear how to deal with 'T | null interop

### ISSUE THREAD

**Issue by Lanayx** [dotnet/fsharp#17734]
### Issue description

Some C# public API's currently expose `'T | null ` in signature, while F# adds additional constraints [per RFC](https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1060-nullable-reference-types.md#the-not-null-constraint). With F# it should be possible to:
1) Consume such types
2) Expose such types (without additional constraints) 

It seems that neither of those points is posssible with .NET 9 RC1. Real application is Oxpecker library where I'm unable to express [deserialize method](https://github.com/Lanayx/Oxpecker/blob/NRT/src/Oxpecker/Serializers.fs#L59) signature to match C# underlying call.

### Choose one or more from the following categories of impact

- [ ] Unexpected nullness warning (false positive in nullness checking, code uses --checknulls and langversion:preview).
- [ ] Missing nullness warning in a case which can produce nulls (false negative, code uses --checknulls and langversion:preview).
- [ ] Breaking change related to older `null` constructs in code not using the checknulls switch.
- [ ] Breaking change related to generic code and explicit type constraints (`null`, `not null`).
- [ ] Type inference issue (i.e. code worked without type annotations before, and applying the --checknulls enforces type annotations).
- [X] C#/F# interop issue related to nullness metadata.
- [ ] Other (none of the categories above apply).

### Operating System

Windows (Default)

### What .NET runtime/SDK kind are you seeing the issue on

.NET SDK (.NET Core, .NET 5+)

### Reproducible code snippet and actual behavior

```fsharp
open System.Text.Json
let x = JsonSerializer.Deserialize<int>("")  // x has type int | null
```

![image](https://github.com/user-attachments/assets/018afb87-3caa-47d2-9ee6-a8ecfd611e91)

### Possible workarounds

I couldn't find any workarounds

**Comment by Lanayx** [comment]
Adding C# code for reference:
```csharp
var x = ctx.Request.ReadFromJsonAsync<int>().Result; // x is of type int
var y = ctx.Request.ReadFromJsonAsync<string>().Result; // y is of type string?
```

**Comment by vzarytovskii** [comment]
> Expose such types (without additional constraints

`| null` is only about nullable reference types, if you declare it as a type, it is inferred as reference. For nullable value types System.Nullable should be used, so adding a constraint is expected.

**Comment by T-Gro** [comment]
This is a consequence of the C# code misleading about the return type - because the returned value is not nullable in the System.Nullable sense (as it would be in C# in a non-generic context), the nullness simply isn't there at all if instantiated by value type.

Without knowing the implementation, one could assume that the C# code returns null for reference types and default for value types - without any indication to the caller that a default value was chosen. It will not crash with NRE, but it might be another source of issues if the absence of information is not communicated via the type system.


Intention-revealing workaround would be to wrap this method in a dedicated generic call restricted to value types, and dealing with absence of information in value types explicitly.

I do understand that C# does allow (T | null) in generic code without it having the right meaning for value types ;; a compromise taken to allow coexistence of NRTs and value types. I do not believe F# should repeat exactly the same, at least not without an approved suggestion.

**Comment by T-Gro** [comment]
My suggestion would be to expose two methods:

Deserialise for reference types returning T | null.
Deserialise for value types returning Nullable of T (or other container for absence of information).

**Comment by vzarytovskii** [comment]
> I do not believe F# should repeat exactly the same

I second that

**Comment by vzarytovskii** [comment]
> A bigger ask would be the unification of NRTs and NVTs in the type system already.

I have discussed it with Don numerous times, and it was decided that we don't want to do it. We don't want to encourage people to use nullable reference types let alone unify nullables under one syntactic structure. It will make it harder to understand what is going on and will be hiding concrete types behind the new construct. In future this can be partially (on the declaration and params side) remediated when we introduce anonymous unions.

That said, I suggest creating a language suggestion w.r.t constraint-by-default, S.Nullable<_> and their interop with nullable references feature.

**Comment by Lanayx** [comment]
> A bigger ask would be the unification of NRTs and NVTs in the type system already.

I have given it a thought and I think this is not required, the ability to speficify or in costraints should be sufficient: 

```fsharp
'T when ('T: not null and 'T: not struct) or 'T: struct
```

As far as I remember while this can't be done in user code, it still can be used in FSharp.Core, so defining
```fsharp
type NRT<'T  when ('T: not null and 'T: not struct) or 'T: struct> = 'T
```
might work

> That said, I suggest creating a language suggestion w.r.t constraint-by-default, S.Nullable<_> and their interop with nullable references feature.

This still doesn't resolve the consuming part right now, e.g. once you use this API you'll get `int | null` type derived while it seems that this should be impossible. So this interop case should be handled anyway.

> My suggestion for now would be to expose two methods:
Deserialise for reference types returning T | null.
Deserialise for value types returning Nullable of T (or other container for absence of information).

This is very unpleasant from consumer's view and also doesn't work
![image](https://github.com/user-attachments/assets/c4689520-b2cc-4609-86b5-4ab4f26d8aa2)

**Comment by T-Gro** [comment]
Syntactically, I do get the ask for "or" in constraints.

However, this does not have an IL equivalent for codegen.
And even in the case of inlining, it would mean typechecking the body of a function with "or" type parameter constraints via the common denominator (so comparison with null would not be possible, assignment to null, binding with " | null" etc.).

**Comment by T-Gro** [comment]
What could be done is removal of the nullness if a generic type allow " | null" is instantiated with a value type.

However, that means also hiding a flaw in the API (the API basically admits that missing information is possible, you just do not know how it is represented at runtime and likely cannot even detect it), whereas current behaviour gives a warning - not with the appropriate wording blaming a generic construct, but a warning at least.


I do not see how F# would support authoring such code, since F# even explicitly makes sure that " | null" in authored generic code automatically enforces a reference type constraint.

**Comment by Lanayx** [comment]
> What could be done is removal of the nullness if a generic type allow " | null" is instantiated with a value type.

I think this has to be done anyway, since there should be a way for user to consume C# Serializer API anyway and it's currently not clear how to deal with `int | null` value (pattern match doesn't work on it since it requires reference type)

> I do not see how F# would support authoring such code, since F# even explicitly makes sure that " | null" in authored generic code automatically enforces a reference type constraint.

Can't we relax enforcing one constraint? I mean keep `'T when 'T: not null`, but don't enforce `'T when 'T: not struct`. This could be known as "compatible with C#" option.

**Comment by T-Gro** [comment]
The added nullness should be subsumed, if you annotate the binding to be without null
`let x : int = ... // json parsing code`

With the constraints it gets tricky - as soon as it is not enforced, it could lead to invalid IL when the generic type/method is instantiated. (imagine the generic code having a `let mutable x : 'T | null = null` - it is not valid to assign null to a value type)
Which means that typechecking rules for mutable null assignment, pattern matching against null or calling into other generic functions would have to adjusted to understand this special mode coming from C# as well.

**Comment by vzarytovskii** [comment]
> it's currently not clear how to deal with `int | null`

`int | null` is not a thing, `System.Nullable<int>` is. How did these APIs work before?

**Comment by Lanayx** [comment]
> int | null is not a thing, System.Nullable<int> is. How did these APIs work before?

Before F# 9 it derived `int`, now `int | null` is derived (I attached screenshots from Visual Studio at the top), so users will need to know how to handle it. 

> The added nullness should be subsumed, if you annotate the binding to be without null
let x : int = ... // json parsing code

This works, thanks, probably should be documented

> With the constraints it gets tricky - as soon as it is not enforced, it could lead to invalid IL when the generic type/method is instantiated. (imagine the generic code having a let mutable x : 'T | null = null - it is not valid to assign null to a value type)
Which means that typechecking rules for mutable null assignment, pattern matching against null or calling into other generic functions would have to adjusted to understand this special mode coming from C# as well.

I agree, that's why I suggested to keep `not null` constraint (which would mean either NRT or value type). I've checked C# and it doesn't allow assigning null to `T?` (errors with [CS0403](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0403))

**Comment by abonie** [comment]
This was already decided during designing of this feature, so if that's to be change it has to be a fully-fledged language suggestion.

**Comment by Lanayx** [comment]
@abonie sorry, what exactly was decided during design of this feature? How do I write the JsonSerializer.Deserialize wrapper without warnings? Is the "already decided" solution to disable warnings for such code?

```fsharp
let tryDeserialize<'T>(value: string) =
    try
        JsonSerializer.Deserialize<'T>(value) |> Some
    with ex ->
        None
```

**Comment by vzarytovskii** [comment]
> @abonie sorry, what exactly was decided during design of this feature? How do I write the JsonSerializer.Deserialize wrapper without warnings? Is the "already decided" solution to disable warnings for such code with #nowarn 3261?
> 
> 
> 
> ```fsharp
> 
> let tryDeserialize<'T>(value: string) =
> 
>     try
> 
>         JsonSerializer.Deserialize<'T>(value) |> Some
> 
>     with ex ->
> 
>         None
> 
> ```
> 
>     

Constraint inference was part of design document, suggestion is needed to omit it.

**Comment by Lanayx** [comment]
> Constraint inference was part of design decision, suggestion is needed to omit it.

With this issue I don't suggest removing constraints or do any other particular suggestion, it is to point out that currently it is impossible to do normal interop with C# (which is undesired behavior), and this ticket shouldn't be closed until the issue is resolved. I agree that the concrete suggestion "how to fix it" might go into suggestion repo, but it's not a reason to close the unresolved issue.

**Comment by vzarytovskii** [comment]
It is currently not actionable for us here. It needs a specific suggestion of what the behaviour currently and what it should be. Suggestions repo is a good place for it, as all discusssions happen there.

**Comment by Lanayx** [comment]
Ok sounds like "currently not a bug", but before closing users like me should get an answer - what to do in current situation. Is the suggested solution to disable nullness warning?

**Comment by vzarytovskii** [comment]
> Ok sounds like "currently not a bug", but before closing the issue users like me should get an answer - what to do in current situation. Is the currently suggested solution to disable nullness warnings?

I would say so, or use optional types where possible

**Comment by brianrourkeboll** [comment]
I do think there is an issue here with the way F# consumes the metadata for generic `'T | null`, although it only really seems to affect the _displayed_ (pseudo-)type, not the actual (?) (pseudo-)type.

```fsharp
// Tooling shows x: int | null. This could never actually be null when 'T is a value type.
let x = Unchecked.defaultof<HttpContext>.Request.ReadFromJsonAsync<int>().Result
// Tooling shows y: int | null. No warning is given.
let y = x + 2
// Tooling shows z: int. No warning is given.
let z = 2 + x
```

Contrast that against

```fsharp
let x: string | null = null
// Warning FS3261. y is inferred to be string | null (even though it will never actually be null due to how + works in F#).
let y = x + ""
// No warning. z is inferred to be string.
let z = "" + x
```

At the very least, it's confusing.

I can see the logic behind the [C# approach](https://sharplab.io/#v2:D4AQzABCBMEMIFgBQBvZENUiALBAigBQCU6maSmVEAlgHYAuEAhhALwQCyAPPQwHwkA3GWq1GAfggAjdl16TBxEZTHiGUgMZyeIAIwA6AHIBXADZnm0swFMFApSrVQ9ABggATHd32vHo6l8pG28g/1UxAKoAFSkeaKV2fk8bADNmcwYnTABfZBygA===): `T?` indicates that the value _could_ be null — if `T` is instantiated to a reference type or `System.Nullable`.

```csharp
int a = M<int>();
int? b = M<int?>();
int? c = M<System.Nullable<int>>();
string d = M<string>();
string? e = M<string?>();

T? M<T>() => default;
```

I think it would make sense for F# to do the same thing here — or at least for the tooling not to show impossible (and inaccurate) types like `int | null`. That part definitely seems like a bug to me.

![image](https://github.com/user-attachments/assets/5231e415-146e-422d-ae77-2bfad2d9235f)

**Comment by T-Gro** [comment]
I will check that.
It should definitely be possible to instantiate such a C#-defined generict type/method with a value type, and work with it without getting warnings.
The display follows the original signature coming from IL, but at this point the type application can remove the constraint.


What remains impossible is authoring null-allowing generic code supporting both reference and value types (authoring does include wrappers). Which does not prevent using them with concrete non-generic instances.

**Comment by T-Gro** [comment]
(if a suggestion is created - a strong point should be raised against modelling the absence of information with `default` for F#-created generic code that includes value types. Doing that blocks that user from determining if the information was really missing, or has a regular value which happens to be equal to default. 

If the solution would be to convert such null-allowing generic code into option/voption, the modelling problem disappears)

**Comment by Lanayx** [comment]
> What remains impossible is authoring null-allowing generic code supporting both reference and value types (authoring does include wrappers). Which does not prevent using them with concrete non-generic instances.

I would add that authoring null-disallowing generic code is also impossible. Any generic code that consumes C# library with `T|null` is impossible to make without disabling warnings. In this case I'd be ready to expose null-disallowing generic type by adding additional null check in function body, but this is not possible, since all null-checking functions are constrained.

```fsharp
let tryDeserialize<'T>(value: string) =
    try
        JsonSerializer.Deserialize<'T>(value) |> Some
    with ex ->
        None
```

**Comment by T-Gro** [comment]
That is correct for the new nullness checking functions.
Some null checking can be done with boxing, either explicit via `box` or implicit via `obj.ReferenceEquals(value,null)` - but that is obviously not meaningful to do in the case of value types.

The proposal could include some relaxed conditions + optimizations for built-in functions specifically for consumption of null-allowing unconstrained generic code.
E.g. I could imagine a version similar to "Option.ofObj", which would be a no-op in case of value types (the emited IL could be a typetest on the generic T argument, which JIT would optimize away at time of generic instantiation).

**Comment by jwosty** [comment]
Just ran into this in the wild but from the other direction, while trying to implement an interface that expects you to author a method with `'T | null` as the return type. Specifically, [IEventContext from SocketIO](https://github.com/doghappy/socket.io-client-csharp/blob/9deebcfe8079164d269ec4f22ba58589366014fb/src/SocketIOClient/IEventContext.cs#L32) (and `<WarningsAsErrors>$(WarningsAsErrors);FS3261</WarningsAsErrors>` set in the project file).

The C# interface (shortened):

```csharp
public interface IEventContext
{
    T? GetValue<T>(int index);
    // ...
}
```

F# implementation:

```fsharp
let fakeContext () =
    {
        new IEventContext with
            // can't implement this without getting hit with FS3261
            member this.GetValue<'T>(_index: int) : 'T = raise (NotImplementedException())
            // other attempts:
            // member this.GetValue<'T>(_index: int) : 'T | null = raise (NotImplementedException())
            // member this.GetValue<'T when 'T : not null and 'T : not struct>(_index: int) : 'T | null = raise (NotImplementedException())
            // member this.GetValue<'T when 'T : null>(_index: int) : 'T = raise (NotImplementedException())
            // ...
    }
```

At least in F# 10 we have a better workaround in scoped `#nowarn`:

```fsharp
#nowarn "3261"
let fakeContext () =
    {
        new IEventContext with
            member this.GetValue<'T>(_index: int) : 'T = raise (NotImplementedException())
            // ...
    }
#warnon "3261"
```

And in simple instances like this where you don't actually need to reference the generic parameter at all, you can actually just omit it enitrely (leaving it implicit):

```fsharp
let fakeContext () =
    {
        new IEventContext with
            member this.GetValue(_index: int) = raise (NotImplementedException())
            // ...
    }
```

Though of course this won't work in all situations.

I'll agree though that C#'s choice here is somewhat unfortunate

**Comment by T-Gro** [comment]
How would a typical implementation derive the return value?
via `Unchecked.defaultof<T>` ?

i.e. we would want that to conform `T?` no matter the structness/meaningfullness?

**Comment by jwosty** [comment]
In my specific case, it is a test fake that doesn't need a real implementation (hence the `raise` - no return at all)

In the library itself, the two real implementations ([NewtonsoftJsonAckMessage](https://github.com/doghappy/socket.io-client-csharp/blob/582282a8b2774a1c99257fc1fa18d8548c59ba83/src/SocketIOClient.Serializer.NewtonsoftJson/NewtonJsonAckMessage.cs#L23) and [SystemJsonAckMessage](https://github.com/doghappy/socket.io-client-csharp/blob/167500202fedc2801e6ee42dfe69b61d0bfc7d25/src/SocketIOClient/Serializer/SystemTextJson/SystemJsonAckMessage.cs#L23)) ultimately call `Deserialize<T>` (from the respective libraries) - it's basically just the exact same scenario that @Lanayx raises, but with inverted control

Probably a relatively niche situation but I figured I'd document it here. If this is left unsupported, it might at least be nice to touch on that in the official docs / articles. I spend a good chunk of time trying to figure out how to appease the compiler, and after moving on it took me a little while to dig up this thread. I would imagine that most people give up earlier and just assume the compiler is broken

**Comment by T-Gro** [comment]
I will prototype an addition to the `Unchecked` module to solve those cases.
There are some rough edges (e.g. when you have such unconstrained `T?` value, it still must not be passed to functions working with regular null-supporting values. Because the call might want to make a mutable cell, and assign `null` to it - and crash at runtime for structs)

**Comment by Lanayx** [comment]
Here's a workaround that I've used for my case:
https://github.com/Lanayx/Oxpecker/blob/20b71802ef71b708ebe85c6860f20fad8ccb55ec/src/Oxpecker/Serializers.fs#L60
