### ISSUE TITLE
Nullness issue - passing nullable value as non-nullable method parameter works without warning

### ISSUE THREAD

**Issue by Lanayx** [dotnet/fsharp#17737]
### Issue description

I expect that passing nullable value as non-nullable method parameter should trigger warning, but it doesn't

### Choose one or more from the following categories of impact

- [ ] Unexpected nullness warning (false positive in nullness checking, code uses --checknulls and langversion:preview).
- [X] Missing nullness warning in a case which can produce nulls (false negative, code uses --checknulls and langversion:preview).
- [ ] Breaking change related to older `null` constructs in code not using the checknulls switch.
- [ ] Breaking change related to generic code and explicit type constraints (`null`, `not null`).
- [ ] Type inference issue (i.e. code worked without type annotations before, and applying the --checknulls enforces type annotations).
- [ ] C#/F# interop issue related to nullness metadata.
- [ ] Other (none of the categories above apply).

### Operating System

Windows (Default)

### What .NET runtime/SDK kind are you seeing the issue on

.NET SDK (.NET Core, .NET 5+)

### .NET Runtime/SDK version

9.0.100-rc.1.24452.12

### Reproducible code snippet and actual behavior

```fsharp
type Test =
    static member X(o: obj) = ""

let x: obj | null = null
let y = Test.X x // warning expected
```

### Possible workarounds

No workaround is needed

**Comment by T-Gro** [comment]
Thanks for this report, this is indeed a serious bug.
In the beginnings of this feature, `obj` has been left out of nullness checks, but that should not be the case anymore.
