### ISSUE TITLE
Nullness issue - cannot assign null to property

### ISSUE THREAD

**Issue by sayurin** [dotnet/fsharp#17733]
Please provide a succinct description of the issue.

**Repro steps**

Enable `nullable`.

```
type T () =
    let mutable v : T | null = null
    member val P : T | null = null with get, set
    member this.M() =
        v <- null
        this.P <- null
```

`let mutable v` can assign `null` as expected.
But `member val P` cannot assign `null`, it causes FS3261.

**Expected behavior**

compile it successfully.

**Actual behavior**

It causes FS3261 warning.

```
Program.fs(6,19): warning FS3261: Nullness warning: The types 'T' and 'T | null' do not have compatible nullability.
```

**Known workarounds**

Use `Uncheked.defaultof<T | null>`.

**Related information**

Provide any related information (optional):

* Windows 11
* .NET 9 RC1
* Visual Studio Professional Preview 17.12.0 Preview 2.0

**Comment by T-Gro** [comment]
This might be related to usage of null in unconstrained generic context.
No matter what, this does need a better diagnostics.

Putting that aside, such code can only work if T is constrained to be a reference type.
Because assignment to null, if T gets instantiated by a value type, would lead to invalid IL code (you cannot assign null to a value type like int or byte).

**Comment by charlesroddie** [comment]
@T-Gro here T is a specific reference type, not generic.

**Comment by vzarytovskii** [comment]
@T-Gro this is what we codegen:
```csharp
[NullableContext(1)]
public class T
{
    [Nullable(2)]
    internal T v;

    [Nullable(2)]
    internal T P@;

    [Nullable(2)]
    public T P
    {
        [CompilerGenerated]
        [DebuggerNonUserCode]
        [return: Nullable(2)]
        get
        {
            return P@;
        }
        [CompilerGenerated]
        [DebuggerNonUserCode]
        [param: Nullable(2)]
        set
        {
            P@ = value;
        }
    }

    public T()
    {
        v = null;
        P@ = null;
    }

    public void M()
    {
        v = null;
        P = null;
    }
}
```

It seems that we generate context correctly, but do not infer nullness?

**Comment by T-Gro** [comment]
Looking at the codegen, I think we even infer it correctly - the attributes are correct, which means C# consumers will see it just fine even.

I suspect this might have to do with how and when we process "member val".

**Comment by T-Gro** [comment]
As a workaround, passing in a "fancified null" makes it work:

```fsharp        type T () =
            let mutable v : T | null = null
            static let nullz : T | null = null
            member val P : (T | null) = v with get, set
            member this.M() =
                v <- null
                this.P <- nullz
```

**Comment by sayurin** [comment]
In addition, `member val P : string | null` can assign `null`.

```
type T () =
    let mutable v : T | null = null
    member val P : T | null = null with get, set
    member val S : string | null = null with get, set
    member this.M() =
        v <- null       // OK
        this.P <- null  // FS3261
        this.S <- null  // OK
```
