### ISSUE TITLE
Nullness - box function from FSharp.Core should return nullable type if argument if nullable and non-nullable type with argument is non-nullable.

### ISSUE THREAD

**Issue by Lanayx** [dotnet/fsharp#17730]
**Repro steps**

```fsharp
let y = box 1
```
**Expected behavior**

y should be of type `obj`

**Actual behavior**

y has type `obj | null`

**Known workarounds**

```fsharp
let y = 
    match box 1 with
    | NonNull i -> i
    | Null -> failwith "never fails"
```

**Related information**

Provide any related information (optional):

* Windows 11
* dotnet 9.0.0-rc.1.24431.7

**Comment by brianrourkeboll** [comment]
`string null` returns `""`, not `null`, though.

**Comment by Lanayx** [comment]
@brianrourkeboll oh, thanks, didn't realize that! Updating the issue

**Comment by kerams** [comment]
`box` is not constrained to value types, so `obj | null` is correct too.

**Comment by Lanayx** [comment]
@kerams it's is correct with current implementation, but it's not a desired solution, that's why I converted it from bug to feature request :)

**Comment by kerams** [comment]
It *is* desired:

```fsharp
> box (null: string);;
val it: objnull = <null>
```

Here's what you want:

```fsharp
let boxv<'a when 'a: struct> (v: 'a) = box v |> Unchecked.nonNull
```

**Comment by vzarytovskii** [comment]
Closing per comments, please raise language suggestion for the libraries/language. Currently we can't change non-generic return type of the function based on value.

**Comment by Lanayx** [comment]
@brianrourkeboll I've just figured out that `string` can return null, so probably type should be changed:

```fsharp
type A() =
    override x.ToString() = null
let y = A() |> string // y is null
```
