### ISSUE TITLE
'Set' related features for fsharp language

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/fsharp#17766]
I propose we are to be blessed with a way to express set in several scenarios, I'm offering my ideas while welcoming other people to say theirs.

For subset :
```F#
let [<EntryPoint>] main _ =
    ["html"] -> ["body"] -> ["font-sizes"] |> someF
    0
```

For intersection :
```F#
let [<EntryPoint>] main _ =
    ["name=cat"] & [3] & [box 0] |> someF
    0
```

**Comment by vzarytovskii** [comment]
All language and corelib proposals should go to fslang-suggestions repo
