### ISSUE TITLE
`CompileBefore`/`CompileAfter` is lost due to the `FSharpSourceCodeCompileOrder` target

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#17786]
Hi,

We use the knowledge about `CompileBefore` and `CompileAfter` extensively in Rider. With the newer SDKs this data is lost because of the new way these files are passed to compiler. Files that were initially added as `CompileBefore` are now added to `Compile` item collection instead. Even though the final file order is correct, the info about the original item type is lost, which introduces regressions in our case.

Could we preserve this knowledge as metadata in the rewritten `Compile` items, please?

**Comment by vzarytovskii** [comment]
https://github.com/dotnet/fsharp/issues/16771 was implemented in
https://github.com/dotnet/fsharp/pull/17103. `<Compile>` item has metadata about order:
<img width="902" alt="image" src="https://github.com/user-attachments/assets/48aaf455-6ec4-4db7-b2ed-85afa9b85567">

**Comment by KevinRansom** [comment]
@auduchinok,
Hey, they weren't really supposed to be used for anything other than: Microsoft.FSharp.Targets build order.  And the change to a metadata version was to address other SDK features that rely solely on compile order.  I expect adding the metadata in the scenario it is currently lost is not that hard.
