### ISSUE TITLE
Adding Fable.Package.SDK confuses Visual Studio Version 17.12.0 Preview 2.1

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#17911]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Adding-FablePackageSDK-confuses-Visual/10772429)._

---
[severity:It bothers me. A fix would be nice]
[Referencing Fable.Package.SDK](https://github.com/Lanayx/Oxpecker/blob/1d3ed1fdf44f4df9172fd01ee3e76f09ea525c75/src/Oxpecker.Solid/Oxpecker.Solid.fsproj#L43-L46) package results in extra project file in solution.
![378050516-b1711e0f-5a3c-425d-82e5-6c2aa5bed318.png](https://aka.ms/dc/image?name=B73a8ff7488bc4911bf5d39a66cb76505638649512797678731_20241019-091439-378050516-b1711e0f-5a3c-425d-82e5-6c2aa5bed318.png&tid=73a8ff7488bc4911bf5d39a66cb76505638649512797678731)

 When clicking on it, I see the following error:
![image.png](https://aka.ms/dc/image?name=B580e23e0de0b408988f3c7e5c4ed2e31638649511867247811_20241019-091306-image.png&tid=580e23e0de0b408988f3c7e5c4ed2e31638649511867247811)
Build from console works fine

Related github issue: https://github.com/fable-compiler/Fable.Package.SDK/issues/9

---
#### Maxime Mangel on 20/10/2024, 01:06 PM: 

<p>It seems like the issues is caused by the <code>&lt;None Include=&quot;$(MSBuildProjectFullPath)&quot; Pack=&quot;true&quot; PackagePath=&quot;fable/&quot;/&gt;</code> rule.</p>
<p>A workaround is to mark it <code>Visible=&quot;false&quot;</code> so people cannot see it.</p>
<p>Affected version of Fable.Package.SDK is version 1.1.0</p>

#### Feedback Bot on 21/10/2024, 04:03 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by psfinaki** [comment]
@Lanayx do we get it right that it's already working? Can this one be closed?

**Comment by Lanayx** [comment]
@psfinaki The package was fixed by @MangelMaxime, so this is no longer an issue for me

**Comment by vzarytovskii** [comment]
Let's close it then, and reopen if it shows to be an issue in future.
