### ISSUE TITLE
unused open when AutoOpen used on type with static members

### ISSUE THREAD

**Issue by joprice** [dotnet/fsharp#17929]
When opening a namespace that contains a type annotated with `[<AutoOpen>]`, the open is identified as being unused even when the static members of the type are referenced. 

Here is a test that triggers the diagnostic: https://github.com/dotnet/fsharp/compare/main...joprice:fsharp:autoOpenType

From a quick inspection of the code, I would guess this has to do with this guard, which only checks for declarations in namespaces and modules, but not static type members: https://github.com/dotnet/fsharp/blob/a7b13037cce774aa978920f1aaaafd45626d08ad/src/Compiler/Service/ServiceAnalysis.fs#L284

**Expected behavior**

Unused open analysis should behave with respect to `[<AutoOpen>]` for types as it does for modules.

**Actual behavior**

The open is marked as unused, even though removing it causes the file to fail to compile.

**Known workarounds**

Fully qualify the member access.

**Comment by edgarfgp** [comment]
Extracted from the repro link.

```fsharp
namespace SomeOtherNamespace

[<AutoOpen>]
type SomeUnusedType =
    static member y = 1

namespace Test

open SomeOtherNamespace

type UseTheThings(i:int) =
    member x.UseSomeOtherNamespaceTypeMember() = y
```

**Comment by psfinaki** [comment]
Looks like a dupe of [this one](https://github.com/dotnet/fsharp/issues/17629).
