### ISSUE TITLE
How to disable embed resource generation of FSharpSignatureCompressedData and FSharpOptimizationCompressedData

### ISSUE THREAD

**Issue by albertwoo** [dotnet/fsharp#17995]
With dotnet 9, when I publish trimmed files for my blazor application, I found the size is became very big. Using ILSpy I found below resources are embeded:

```txt
FSharpOptimizationCompressedData.FunWasm.MudBlazorDemo (Embedded, Public)
FSharpOptimizationCompressedDataB.FunWasm.MudBlazorDemo (Embedded, Public)
FSharpSignatureCompressedData.FunWasm.MudBlazorDemo (Embedded, Public)
FSharpSignatureCompressedDataB.FunWasm.MudBlazorDemo (Embedded, Public)
```

How do I disable those resource been generated? Or can I disable it by set some flag in fsproj or by cli when use dotnet build?

**Comment by kerams** [comment]
#15605

**Comment by vzarytovskii** [comment]
They can be trimmed by having `ILLink.Substitutions.xml` file in your project root directory. Be aware though, if you're publishing library (which is not your case), those will likely be needed for optimizations, inlining and nullabillity:
```xml
<linker>
  <assembly fullname="FSharp.Core">
    <resource name="FSharpOptimizationCompressedData.FSharp.Core" action="remove" />
    <resource name="FSharpOptimizationInfo.FSharp.Core" action="remove" />
    <resource name="FSharpSignatureCompressedData.FSharp.Core" action="remove" />
    <resource name="FSharpSignatureInfo.FSharp.Core" action="remove" />

    <resource name="FSharpOptimizationCompressedDataB.FSharp.Core" action="remove" />
    <resource name="FSharpOptimizationDataB.FSharp.Core" action="remove" />
    <resource name="FSharpSignatureCompressedDataB.FSharp.Core" action="remove" />
    <resource name="FSharpSignatureDataB.FSharp.Core" action="remove" />
  </assembly>
</linker>
```

Replace `FSharp.Core` with your assembly name.

**Comment by albertwoo** [comment]
It is not just for my projects. I am also an author of multiple public libraries, like **Fun.Blazor** and also a lot of sample projects, project templates, my business projects etc. A lot of work needed to be done because of this.

**Comment by vzarytovskii** [comment]
> It is not just for my projects. I am also an author of multiple public libraries, like **Fun.Blazor** and also a lot of sample projects, project templates, my business projects etc. A lot of work needed to be done because of this.

You **should not** generally trim them for libraries, as these resources are essential for compiler when doing typechecking and optimization. For published projects, they should be trimmed in majority of cases, since they aren't needed at runtime. I'll close this issue as dupe, let's continue discussion there, so we can figure out what would be the best default behaviour for each case.
