### ISSUE TITLE
Nullness issue - code using types with AllowNullLiteral attribute doesn't raise warnings

### ISSUE THREAD

**Issue by Lanayx** [dotnet/fsharp#18017]
### Issue description

This attribute is mentioned several types in RFC, however RFC doesn't say if this attribute should be respected by new nullness rules. I suggest that it should be (I don't see a good reason why it shouldn't).

### Choose one or more from the following categories of impact

- [ ] Unexpected nullness warning (false positive in nullness checking, code uses --checknulls and langversion:preview).
- [x] Missing nullness warning in a case which can produce nulls (false negative, code uses --checknulls and langversion:preview).
- [ ] Breaking change related to older `null` constructs in code not using the checknulls switch.
- [ ] Breaking change related to generic code and explicit type constraints (`null`, `not null`).
- [ ] Type inference issue (i.e. code worked without type annotations before, and applying the --checknulls enforces type annotations).
- [ ] C#/F# interop issue related to nullness metadata.
- [ ] Other (none of the categories above apply).

### Operating System

Windows (Default)

### What .NET runtime/SDK kind are you seeing the issue on

.NET SDK (.NET Core, .NET 5+)

### .NET Runtime/SDK version

.NET SDK 9.0.100

### Reproducible code snippet and actual behavior

1. Clone the Oxpecker repro
2. Go to [this line](https://github.com/Lanayx/Oxpecker/blob/3cb052a2e5d75189c344d83c38b72ce4937b3f75/src/Oxpecker.ViewEngine/Tools.fs#L35)
3. Add the following code after it `let z = next.Value`
4. Observe no nullness warning although `NullReferenceException` can be possibly thrown in this case

### Possible workarounds

Ignore the issue

**Comment by kerams** [comment]
My experience is completely the opposite. Not only do I see these warnings, but I also *don't* want them. To me, `AllowNullLiteral` simply means that the compiler will consider `null` to be a valid value for a certain type. Hovewer, this is applied at definition site, not when a type is actually used.

You can think of `string` as having `AllowNullLiteral`, but that doesn't mean `string | null` is implied every time it's used.

**Comment by Lanayx** [comment]
> You can think of string as having AllowNullLiteral

I can't think in that way, because I can write `string | null` and I can't write `MyType | null` where `MyType` is decorated with `AllowNullLiteral`. But you might be right that proper way to fix the issue is to allow that to make `MyType` behave just like `string` when it has attribute decoration.

**Comment by T-Gro** [comment]
> > You can think of string as having AllowNullLiteral
> 
> I can't think in that way, because I can write `string | null` and I can't write `MyType | null` where `MyType` is decorated with `AllowNullLiteral`. But you might be right that proper way to fix the issue is to allow `MyType | null` to make `MyType` behave just like `string` when it has attribute decoration.

If you can and want to annotate `MyType | null`, what else keeps you at using AllowNullLiteral ?
The real solution would really be to get rid of AllowNullLiteral for codebases converted to nullable reference types. I would be curious if any use case remains.

**Comment by Lanayx** [comment]
> If you can and want to annotate MyType | null, what else keeps you at using AllowNullLiteral ?

Wow, I didn't realized that once you write `MyType | null`, `AllowNullLiteralAttribute` is no longer required :) Thanks for the explanation, I'm closing the issue

**Comment by Lanayx** [comment]
Actually, in my particular case I'll be NOT changing `AllowNullLiteralAttribute` to `MyType | null`, because my primary case for it is this code

```fsharp
  seq {
      while isNotNull next do
          yield next.Value
          next <- next.Next
  }
```
which because of the lack of flow analysis will be transformed into
```fsharp
  seq {
      while isNotNull next do
          let nonNullNext = nonNull next
          yield nonNullNext.Value
          next <- nonNullNext.Next
  }
```
so I'd better keep it with attribute for simplicity
