### ISSUE TITLE
Nullness issue - WarningAsError doesn't work for 3261

### ISSUE THREAD

**Issue by Lanayx** [dotnet/fsharp#18016]
### Issue description

WarningAsError doesn't have effect in certain cases

### Choose one or more from the following categories of impact

- [ ] Unexpected nullness warning (false positive in nullness checking, code uses --checknulls and langversion:preview).
- [ ] Missing nullness warning in a case which can produce nulls (false negative, code uses --checknulls and langversion:preview).
- [ ] Breaking change related to older `null` constructs in code not using the checknulls switch.
- [ ] Breaking change related to generic code and explicit type constraints (`null`, `not null`).
- [ ] Type inference issue (i.e. code worked without type annotations before, and applying the --checknulls enforces type annotations).
- [ ] C#/F# interop issue related to nullness metadata.
- [x] Other (none of the categories above apply).

### Operating System

Windows (Default)

### What .NET runtime/SDK kind are you seeing the issue on

.NET SDK (.NET Core, .NET 5+)

### .NET Runtime/SDK version

.NET SDK 9.0.100

### Reproducible code snippet and actual behavior

1) Clone Oxpecker repository, observe [this line](https://github.com/Lanayx/Oxpecker/blob/3cb052a2e5d75189c344d83c38b72ce4937b3f75/src/Oxpecker/Oxpecker.fsproj#L4), nulness warnings are set as errors
2) Go [to this line](https://github.com/Lanayx/Oxpecker/blob/3cb052a2e5d75189c344d83c38b72ce4937b3f75/src/Oxpecker/Streaming.fs#L44), change `(rawRangeHeader[0] |> string)` to just `rawRangeHeader[0]`
3) Build the project
4) Observer the warning that is not an error

### Possible workarounds

Ignore problem

**Comment by abonie** [comment]
Hi @Lanayx , is it possible for you to provide a minimal repro (for our convenience)?

**Comment by Lanayx** [comment]
Oops, as I checked, it appeared that WarningsAsErrors was defined twice and the second one overrode the correct one, sorry for that and thanks for checking
