### ISSUE TITLE
Nullness issue - The type supports 'null' but a non-null type is expected.

### ISSUE THREAD

**Issue by johnnyggalt** [dotnet/fsharp#18028]
### Issue description

I'm trying to port a code base to .NET 9 with `Nullable` enabled and hit an issue when calling `AddSingleton` extension against `IServiceCollection`. 

### Choose one or more from the following categories of impact

- [x] Unexpected nullness warning (false positive in nullness checking, code uses --checknulls and langversion:preview).
- [ ] Missing nullness warning in a case which can produce nulls (false negative, code uses --checknulls and langversion:preview).
- [ ] Breaking change related to older `null` constructs in code not using the checknulls switch.
- [ ] Breaking change related to generic code and explicit type constraints (`null`, `not null`).
- [ ] Type inference issue (i.e. code worked without type annotations before, and applying the --checknulls enforces type annotations).
- [x] C#/F# interop issue related to nullness metadata.
- [ ] Other (none of the categories above apply).

### Operating System

Windows (Default)

### What .NET runtime/SDK kind are you seeing the issue on

.NET SDK (.NET Core, .NET 5+)

### .NET Runtime/SDK version

.NET 9

### Reproducible code snippet and actual behavior

```fsharp
module Repro

open System.Runtime.CompilerServices
open Microsoft.Extensions.DependencyInjection

// The actual interface I'm using is Giraffe.Json.ISerializer, which allows null literals.
[<AllowNullLiteral>]
type ITest =
    interface end

type IServiceCollectionExtensions =
    [<Extension>]
    // not null constraint required to repro even though AddSingleton doesn't have such a constraint
    static member AddSingleton2<'T when 'T: not struct and 'T: not null>(services: IServiceCollection, implementationInstance: 'T) =
        services

let repro () =
    let foo = ServiceCollection()
    foo.AddSingleton<ITest>({ new ITest }) |> ignore
    foo.AddSingleton2<ITest>({ new ITest }) |> ignore
```

Both the `AddSingleton` and `AddSingleton2` lines result in the warnings:

```
Repros.fs(17,5): Warning FS3261 : Nullness warning: The type 'ITest' supports 'null' but a non-null type is expected.
Repros.fs(17,5): Warning FS3261 : Nullness warning: The type 'ITest' supports 'null' but a non-null type is expected.
```

Interestingly, I had to add the `'T: not null` constraint in my implementation to trigger the error, even though the actual `AddSingleton` implementation doesn't appear to have such a constraint:

![Image](https://github.com/user-attachments/assets/06ea5407-9950-434a-814e-ac23680c4e5b)

### Possible workarounds

Not sure other than disabling nullness for that project.

**Comment by T-Gro** [comment]
In C# code in nullable enabled context, "class" constraints means non-nullable reference types only, which is why it complains for a type with "AllowNullLiteral". C# generic code allowing nullable would be constrained as "class?".


I think the workaround is to use the overload taking a System.Type parameter - it is visible in the last screenshot. Will that work for you?

**Comment by johnnyggalt** [comment]
@T-Gro Ah, thank you, that makes sense. Yes, the overload works fine.

So I guess this is more a question for the Giraffe team as to why that interface is marked as nullable. I'll post an issue over there.
