### ISSUE TITLE
dotnet website says .NET 9 only supports F#8

### ISSUE THREAD

**Issue by goswinr** [dotnet/fsharp#18029]
On the dotnet sdk downloads website `net9` is shown to only support ` F# 8` : 
https://dotnet.microsoft.com/en-us/download/dotnet/9.0
I understood F# 9 is supported.
I reported it via the official feedback too:  https://github.com/dotnet/website-feedback/issues/293
![Image](https://github.com/user-attachments/assets/436d0a5a-58fb-4b42-b1ef-f79edc0dc6f8)

**Comment by vzarytovskii** [comment]
Not an issue for this repo, I think it's controlled by sdk

**Comment by baronfel** [comment]
It's just a raw string - @mairaw do you remember where this string is?
