### ISSUE TITLE
Nullness issue - No way to remove warning after e.g. IMemoryCache.TryGetValue, when generic value can be both value type and reference type

### ISSUE THREAD

**Issue by cmeeren** [dotnet/fsharp#18020]
### Issue description

The code below should compile without warnings, but produces a nullness warning. I can find no way to make this code compile properly. If I use `NonNullQuick` or `NonNullQuickV`, the generic type is forced to be either a reference type or a value type, respectively.

```fsharp
let tryGetValue<'a> (key: obj) (c: IMemoryCache) : 'a option =
    match c.TryGetValue<'a>(key) with
    | false, _ -> None
    | true, v -> Some v
```

### Choose one or more from the following categories of impact

- [x] Unexpected nullness warning (false positive in nullness checking, code uses --checknulls and langversion:preview).
- [ ] Missing nullness warning in a case which can produce nulls (false negative, code uses --checknulls and langversion:preview).
- [ ] Breaking change related to older `null` constructs in code not using the checknulls switch.
- [ ] Breaking change related to generic code and explicit type constraints (`null`, `not null`).
- [ ] Type inference issue (i.e. code worked without type annotations before, and applying the --checknulls enforces type annotations).
- [x] C#/F# interop issue related to nullness metadata.
- [ ] Other (none of the categories above apply).

### Operating System

Windows (Default)

### What .NET runtime/SDK kind are you seeing the issue on

.NET SDK (.NET Core, .NET 5+)

### .NET Runtime/SDK version

.NET SDK 9.0.100

**Comment by cmeeren** [comment]
I get the same with `JsonSerializer.Deserialize`, not sure what to do here to make the nullness warning go away:

```fsharp
let deserialize<'a> (str: string) =
    JsonSerializer.Deserialize<'a>(str, options)
```

![Image](https://github.com/user-attachments/assets/9f602e66-8d52-4c6e-ae8a-99fc1796540f)

**Comment by vzarytovskii** [comment]
This is the duplcate of https://github.com/dotnet/fsharp/issues/17734, roslyn has a special behaviour for that, it is not a bug, and needs a language suggestion (as advised in previous issue).

**Comment by vzarytovskii** [comment]
> Ok, so I simply have to disable the warning in the relevant files for now? 

That'll work, yeah.


> There's no way to disable it for a part of a file, right?

Not yet, there's some ongoing work happening around that, driven by community.
