### ISSUE TITLE
Nullness issue - Async.SwitchToContext lacks a null annotation on its parameter

### ISSUE THREAD

**Issue by glchapman** [dotnet/fsharp#18055]
### Issue description

I believe that Async.SwitchToContext should take a parameter of type `System.Threading.SynchronizationContext | null`. Examining the function body, you can see that it treats null as a possible argument and handles it normally (without throwing an exception).

### Choose one or more from the following categories of impact

- [x] Unexpected nullness warning (false positive in nullness checking, code uses --checknulls and langversion:preview).
- [ ] Missing nullness warning in a case which can produce nulls (false negative, code uses --checknulls and langversion:preview).
- [ ] Breaking change related to older `null` constructs in code not using the checknulls switch.
- [ ] Breaking change related to generic code and explicit type constraints (`null`, `not null`).
- [ ] Type inference issue (i.e. code worked without type annotations before, and applying the --checknulls enforces type annotations).
- [ ] C#/F# interop issue related to nullness metadata.
- [ ] Other (none of the categories above apply).

### Operating System

Windows (Default)

### What .NET runtime/SDK kind are you seeing the issue on

.NET SDK (.NET Core, .NET 5+)

### .NET Runtime/SDK version

net9.0

### Possible workarounds

One can write a wrapper function which when given null calls Async.SwitchToThreadPool, otherwise calls SwitchToContext with the non-null syncContext.

**Comment by BoundedChenn31** [comment]
Looks like this annotation and all compiler directives at `CreateSwitchToAsync` can be removed? It is called only by `SwitchToContext` that checks context for null and `PostWithTrampoline` definitely doesn't handle nulls well. 
 
https://github.com/dotnet/fsharp/blob/30d9ea7cd6e8a222e3561c83a854c1632240b7fe/src/FSharp.Core/async.fs#L871-L876
