### ISSUE TITLE
F# 9 Is* Properties not generated for single-case discriminated unions

### ISSUE THREAD

**Issue by tw0po1nt** [dotnet/fsharp#18075]
**Repro steps**

I have the following code:

```fsharp
module Types

open System

type AssetType = Image

type Asset =
  { Type : AssetType 
    SourceURL : Uri }

let onlyImages assets =
  assets
  |> List.filter _.Type.IsImage
```

**Expected behavior**

The `IsImage` DU helper is generated and this compiles

**Actual behavior**

The code does not compile with the following error message:

`The type 'AssetType' does not define the field, constructor, or member 'IsImage'. Maybe you want one of the following: Image`

**Known workarounds**

Add another union case

**Related information**

Here's a sharplab link for the single-case situation:
https://sharplab.io/#v2:DYLgZgzgNAJiDUAfAtgexgV2AUwAQBUBPAB2wgFgAoK1UgO1wGVCIAXbZKq1kvAQQgRsrIqVwBeXAElkAQwDm2LpR5iBQ1hKq5cAbwK9cIXOuGi82nU1QYATgGNsAVQBKAGSO4ntgJa4AvlRAA==

And for adding a second case:
https://sharplab.io/#v2:DYLgZgzgNAJiDUAfAtgexgV2AUwAQBUBPAB2wgFgAoK1UgO1wGVCIAXbZKq1kvAQQgRsrIqVwBeXFVwzciXAElkAQwDm2abPmNUybAHlWAC2wAnAMLKhXSjzEChrCZoDeBXrhC4Hw0Xk0yOhimAMbYAKoASgAynrjhpgCWuAC+AVKUOE6odMCESmpkuFaOEM6UMiXCFBVyAHy40YlsAHRgicDsprgA+i1+LQoQBepUQA

**Comment by vzarytovskii** [comment]
I'm _fairly_ certain, that it's by design.

**Comment by tw0po1nt** [comment]
I wondered. So then my question is... what is the reason? I understand that having it for a single case could be considered redundant since it's guaranteed to always return true. However, having this property not be generated only in the single case seems inconsistent.

Maybe this should be a design suggestion then and not a bug?

**Comment by vzarytovskii** [comment]
> I wondered. So then my question is... what is the reason? I understand that having it for a single case could be considered redundant since it's guaranteed to always return true. However, having this property not be generated only in the single case seems inconsistent.

I guess the reasoning is, as you said, such tester (the one in the single-case DU) will always hold - will always be `true`, so no point in testing it. And if your DU becomes multi-case, then testers will be there.


> Maybe this should be a design suggestion then and not a bug?

Probably yes

**Comment by tw0po1nt** [comment]
Ok. I can close this and open an issue in fslang/fslang-suggestions
