### ISSUE TITLE
After using #r on a non-existent .dll, creating that .dll requires document change to update diagnostics

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#1808]
F# files are not re-checked when changes happen to dependency files such as ``#load``-ed scripts or referenced DLLs.

This greatly affects the usability of the Visual F# Tools as the user has no idea what state the type checking is in, and has to do artificial edits on their source code to clear errors

This is a regression to functionality that has been working since VS2008

For each F# source file (in or out of a project, whether script or otherwise), the compiler service provides a list of files in [the DependencyFiles property](https://github.com/Microsoft/visualfsharp/blob/6afc4f9776a5dba903ca6b11965a206fb8bc23d8/src/fsharp/vs/ServiceUntypedParse.fsi#L35).  These are DLLs and source files.  The IDE should install file watchers for these files, and if a change in a watched file is detected then a re-check of the file should be done, resulting in a refresh of the errors

For example, 
* if an error is corrected in a file referenced by a ``#load``, and that file is saved to disk, then the red-squiggly on the ``#load`` should disappear

* Assume one project references another (e.g. fsc references FSharp.Compiler).  If the DLLs for the referenced did not exist on disk, then there will be red-squigglies in the project.  When the referenced project gets built, DLLs are created by a build.  These DLLs will be in the dependency files.  When the files appear on disk, a re-check should occur, and the red squigglies should be cleared.

#### Repro steps

1. There are many repros. For example, when scripting, create a ``script1.fsx`` with this content and save it to an empty directory.

```fsharp
#load "script2.fsx"

System.Console.WriteLine("Hello")

```

You will see a red-squiggly on ``script2.fsx``

2. Now create an empty ``script2.fsx`` using VS or any other tool.

   **Expected**: the red-squiggly should disappear in ``script1.fsx`` when you return to that file (without making any edits to ``script1.fsx``)

3. Now edit ``script2.fsx`` using so there is an error in the file.  e.g. the contents

       let fail = 1 + 1.0

   Save the file and go back to the ``script1.fsx`` window.  

   **Expected**: the red-squiggly should re-appear in ``script1.fsx`` when you return to that file (without making any edits to ``script1.fsx``)

4. Now edit ``script2.fsx`` to clear the error and save the file.  Go back to the ``script1.fsx`` window. 

   **Expected**: the red-squiggly should disappear from ``script1.fsx`` when you return to that file (without making any edits to ``script1.fsx``)

Similarly for cross-project references to DLLs in project builds

#### Actual behavior

In all the cases above, the red-squigglies are not cleared in ``script1.fsx`` until you actually edit ``script1.fsx`` (which has the effect of forcing a re-check of the file)

**Comment by cartermp** [comment]
Thanks for the detailed bug, @dsyme.  @brettfo and @Pilchie, I think this one should be high on our list of bugs to fix right now.

**Comment by dsyme** [comment]
Here are some notes about the old implementation that has been lost

* Assume file B has been checked and has DependencyFiles A1 and A2.

* In the old language service code, [the DependencyFiles for B were consumed here](https://github.com/Microsoft/visualfsharp/blob/6afc4f9776a5dba903ca6b11965a206fb8bc23d8/vsintegration/src/FSharp.LanguageService/BackgroundRequests.fs#L193) after checking

*  This used the Visual Studio file watching facilities [here](https://github.com/Microsoft/visualfsharp/blob/6ce962e97de24273d167b6c174344e3017a6e4c7/vsintegration/src/FSharp.LanguageService/FSharpSource.fs#L114) to install watchers on A1 and A2

* When a file change to A1 or A2 was detected (but NOT a file deletion) we called [NotifyFileTypeCheckStateIsDirty](https://github.com/Microsoft/visualfsharp/blob/fb67dbfe8f52eded450ddb34ce6b206a7c94d6bd/vsintegration/tests/Salsa/FSharpLanguageServiceTestable.fs#L175) which stored the file away in ``dirtyForTypeCheckFiles``

* NotifyFileTypeCheckStateIsDIrty is also called [when an event is raised by the background checker](https://github.com/Microsoft/visualfsharp/blob/fb67dbfe8f52eded450ddb34ce6b206a7c94d6bd/vsintegration/tests/Salsa/FSharpLanguageServiceTestable.fs#L72)  This is crucial as well to ensure clearing of foreground errors in projects in response to updates to the background build.


* OnIdle processing then [marked any matching files in the RunningDocumentTable as if they had been edited](https://github.com/Microsoft/visualfsharp/blob/fb67dbfe8f52eded450ddb34ce6b206a7c94d6bd/vsintegration/tests/Salsa/FSharpLanguageServiceTestable.fs#L181).  THis would have the effect of marking file B as "edited" from the point of view of the language service, and it would be rechecked, and the errors cleared.

These fixes are also crucial for correctly updating intellisense information in response to changes in dependent files.

**Comment by dsyme** [comment]
Note that the F# way of doing this is not ideal, especially for multi-project solutions (where you shouldn't have to even have referenced DLLs on-disk to check a project). 

But in VS2017 RC we have no updates in response to file events at all....

**Comment by cartermp** [comment]
Agreed.

**Comment by dsyme** [comment]
I'm having a hell of a hard time understanding how to implement this within the Roslyn framework. 

One thing we need is the equivalent of this
```
    member this.OnIdle() = 
        for file in dirtyForTypeCheckFiles do
            let rdt = this.ServiceProvider.RunningDocumentTable
            match this.ProjectSitesAndFiles.TryGetSourceOfFile(rdt, file) with
            | Some source -> source.RecordChangeToView()
            | None ->  ()
        dirtyForTypeCheckFiles <- Set.empty
```
That is, when Idle we want to run through a set of documents and "act as if the document has changed" for the purposes of Roslyn semantic analysis.

Another thing we need is a place where we can register and store VS file tracking handlers.

I hacked about with this sort of thing:
```
        // Add a hook so that when the background builder refreshes the background semantic build for a file, we refresh
        // the editor.
        checker.BeforeBackgroundFileCheck.Add(fun (fileName, extraProjectInfo) ->  
           async {
            try 
                match extraProjectInfo with 
                | Some (:? Workspace as workspace) -> 
                    let solution = workspace.CurrentSolution
                    let documentIds = solution.GetDocumentIdsWithFilePath(fileName)
                    if not documentIds.IsEmpty then 
                        let documentId = documentIds |> Seq.head
                        let document = solution.GetDocument(documentId)
                        let! sourceText = document.GetTextAsync() |> Async.AwaitTask
                        let newSolution = solution.WithDocumentText(documentId, sourceText (* , PreservationMode.PreserveIdentity *))
                        workspace.TryApplyChanges(newSolution) |> ignore
                | _ -> ()
            with ex -> 
                Assert.Exception(ex)
            } |> Async.StartImmediate
        )

```


I'll definitely need help for this

**Comment by vladima** [comment]
you can request projects or documents to be re-checked by importing [IDiagnosticsAnalyzerService](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/IDiagnosticAnalyzerService.cs,11) and calling `Reanalyze`

**Comment by dsyme** [comment]
@vladima  Thanks!!

**Comment by dsyme** [comment]
@vladima @OmarTawfik @brettfo In the old F# Language Service code (actually FSharp.LanguageService.Base, in C#) we implemented our own ``ViewFilter`` type that includes an implementation of ``IVsTextViewEvents`` including an action when the window got the focus:

```
        public virtual void OnSetFocus(IVsTextView view) {
            this.service.OnActiveViewChanged(view);
            ...
        }
```

Do you know what the equivalent should be in the Roslyn code?  We basically want to run ``checker.CheckProjectInBackground`` when a file in a project gets the focus.  This will then make sure all errors eventually get updated.

We don't explicitly implement ``IVsTextViewEvents`` in the new code.

thanks
don

**Comment by vladima** [comment]
I guess something like this might work (browser compiled solution, might contain ~~peanuts~~ errors)

```F#
open System.ComponentModel.Composition
open Microsoft.VisualStudio.Editor
open Microsoft.VisualStudio.Utilities
open Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem
open Microsoft.CodeAnalysis.Diagnostics

[<ContentType(FSharpCommonConstants.FSharpContentTypeName)>]
[<Export(typeof<IVsTextViewCreationListener>)>]
type FSharpTextViewCreationListener 
        [<ImportingConstructor>]
        (
            textViewAdapter: IVsEditorAdaptersFactoryService,
            workspace: VisualStudioWorkspaceImpl, 
            analyzerService: IDiagnosticAnalyzerService
        ) =
    interface IVsTextViewCreationListener with
        member this.VsTextViewCreated(textView) =
            let wpfTextView = textViewAdapter.GetWpfTextView(textView)
            match wpfTextView.TextBuffer.Properties.TryGetProperty<ITextDocument>(typeof<ITextDocument>) with
            | true, textDocument ->
                let filePath = textDocument.FilePath
                let onGotFocus = new EventHandler(fun _ _ ->
                    analyzerService.Reanalyze(workspace, projectIds = null, documentIds = workspace.CurrentSolution.GetDocumentIdsWithFilePath(filePath))
                )
                let rec onViewClosed = new EventHandler(fun _ _ -> 
                    wpfTextView.GotAggregateFocus.RemoveHandler(onGotFocus)
                    wpfTextView.Closed.RemoveHandler(onViewClosed)
                )
                wpfTextView.GotAggregateFocus.AddHandler(onGotFocus)
                wpfTextView.Closed.AddHandler(onViewClosed)
            | _ -> ()
```

**Comment by Pilchie** [comment]
Roslyn already has a service that tracks the active document, and in theory kicks of re-analysis through the Diagnostic analyzer.  @heejaechang - can you point us to that code?

**Comment by heejaechang** [comment]
does F# do error reporting based on roslyn diagnostic service, then it does all dependency checking and priority queue on changes and etc.

**Comment by heejaechang** [comment]
these make sure document that has focus get processed first and then opened files and then modified files and etc.

http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/SolutionCrawler/WorkCoordinator.HighPriorityProcessor.cs,70
http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs,271

**Comment by heejaechang** [comment]
it founds like F# need to abstract this out - http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/SolutionCrawler/WorkCoordinator.SemanticChangeProcessor.cs,32

and make it to enqueue right set of work items to propagate semantic changes.

**Comment by dsyme** [comment]
@vladima Thanks for your code, it worked well, please see PR

**Comment by cartermp** [comment]
@dsyme Is it safe to close this with your PR?

**Comment by dsyme** [comment]
No, there is a still a case of propagating changes even when there's been no change in focus to "kick things off" , but files have come/gone from disk.  

Basically I _believe_ the F# IncrementalBuilder will correctly notice all dependent file changes if activated to run.  But we are relying on regaining the focus to prompt it to run at all.  

But this problem is much less severe after the PR

**Comment by cartermp** [comment]
Tagging this for RTM.  Even if we can't address it in time, we should definitely get this fully fixed ASAP

**Comment by dsyme** [comment]
Closing this as it has been addressed

**Comment by dsyme** [comment]
Reopening with this repro:

I'm trying to repro this, but can't do it yet. @vasily-kirichenko or @cartermp could you write out step-by-step repro steps for me please?

There is a variation of #1808 via these steps:

Create a script with #r "nada.dll" and some code, where that file doesn't exist. Red-squigglies appear
Create the DLL in the background.
Expected: The red-squigglies should disappear automatically, without any movement of the mouse or editing of the file or anything else that triggers an FCS request about the script. At least that's what happened in VS2010-15.

Actual: the red-squigglies hang around until you actually interact with the script, e.g. a mouse hover.

It may be that we can register the proper metadata dependencies for the Roslyn Project for the script (though I'm not sure we actually create one of those yet). And then Roslyn's re-analysis thread will look after reanalyzing when the files appear/disappear.

@Pilchie a question - do you know if Roslyn is "reactive" in this way, listening to changes in the referenced DLL files and re-scheduling error analysis of the files? Or is our language service responsible for listening to changes in those files?

**Comment by heejaechang** [comment]
if moving mouse can cause tagger to change, looks like we don't know the dll has changed (created). looks like file tracker issue.

**Comment by dsyme** [comment]
> if moving mouse can cause tagger to change, looks like we don't know the dll has changed (created). looks like file tracker issue.

@heejaechang Yes, but what I'm wondering is whether Roslyn actually includes a file tracker - e.g. does it react to on-disk file change events for referenced DLLs (e.g. not including cross-project references, which let's assume are handled in-memory).  I haven't checked the Roslyn source code, it's just a general question

In VS2015 the Visual F# Tools used to install Visual Studio file change event listeners as described here : https://github.com/Microsoft/visualfsharp/issues/1808#issuecomment-262290218.  Right now in VS2017 
the Visual F# Tools aren't doing any explicit file-change tracking - what I'm wondering is if we should implement it ourselves like we did in VS2015 or if we get some for free from setting up Roslyn metadata references correctly.

**Comment by Pilchie** [comment]
>e.g. does it react to on-disk file change events for referenced DLLs

Yes see [`VisualStudioMetadataReference`](http://source.roslyn.io/Microsoft.VisualStudio.LanguageServices/R/aac4083bf2f5edb9.html), and it's `_fileChangeTracker` field.

**Comment by dsyme** [comment]
@Pilchie thanks.   A couple of questions

- is the result of a detected change effectively a Reanalzye call?

 - We don't currently set up a Roslyn project for F# scripts. We could do that, ut what about ``#load "SomeFile.fs"`` references in scripts? We should react to changes in ``"SomeFile.fs"`` as well.  But these are normal F# source code files, rather than .NET DLLs.  Does that matter? Should we also use some variation on VisualStudioMetadataReference, or are those only for .NET DLLs?

**Comment by Pilchie** [comment]
> is the result of a detected change effectively a Reanalzye call?

It should (eventually) result in a WorkspaceChanged event with a project updated.  I'm not sure which `Reanalyze` call you mean, so I can't say what the path to that is, and whether it's hooked up for F#.

Note that C# also has `#load` in csx files, and I remember at least talking about how to deal with it, though I'm not sure if we implemented it.  I think they *right* way handle it is to create a language service project, and add the `#load`ed files to it.  We also hook up file change notifications for closed source files, so the rest should work.  Also cc'ing @jasonmalinowski and @tmat to double check my thoughts here.

**Comment by Pilchie** [comment]
Oh, hey, look at https://github.com/dotnet/roslyn/issues/21964.  Maybe we don't handle it properly for C# either.

**Comment by dsyme** [comment]
I'm closing this very old issue - @TIHan implemented this correctly AFAIU
