### ISSUE TITLE
Can't prefix format specifier with '%' in interpolated strings

### ISSUE THREAD

**Issue by b-hodge** [dotnet/fsharp#18103]
Interpolated strings in F# support the format specifiers described in the [F# Plain Text Formatting documentation](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/plaintext-formatting#format-specifiers-for-printf). This includes producing a literal `%` character by prefixing it with another `%`.

This no longer works when the sequence of characters is immediately followed by a format specifier.

**Repro steps**

```fsharp
Microsoft (R) F# Interactive version 12.9.100.0 for F# 9.0

> let x = "abc";;
val x: string = "abc"

> $"%%%s{x}%%";;
val it: string = "abc%"
```

Note that this works as expected in F# 8.0:

```fsharp
Microsoft (R) F# Interactive version 12.8.400.0 for F# 8.0

> let x = "abc";;
val x: string = "abc"

> $"%%%s{x}%%";;
val it: string = "%abc%"
```

**Related information**

Tested with `sdk-9.0.101-macos-arm64`.

**Comment by brianrourkeboll** [comment]
Hmm. I think there might have been a bug in https://github.com/dotnet/fsharp/pull/16556, specifically here:

https://github.com/dotnet/fsharp/blob/f2fe83295721c91d1a1f2372d84bc737f7660f77/src/Compiler/Checking/Expressions/CheckExpressions.fs#L171

Should this be something like

```diff
-s[..i]
+s[..s.Length - 3]
```

?

**Comment by edgarfgp** [comment]
This is a regression right ?
