### ISSUE TITLE
/0 confuses tuple debug display

### ISSUE THREAD

**Issue by psfinaki** [dotnet/fsharp#18132]
Not a big deal.

**Repro steps**

This code:
```fsharp
let zero = (char)0
let tuple1 = (42, zero)
let tuple2 = (zero, 42)
let tuple3 = (zero, zero)
let tuple4 = (42, zero, 42)
```

Somehow crashes tuple display:
![Image](https://github.com/user-attachments/assets/73373814-a20d-4e95-88ae-99338a3570a5)

Printing is fine btw:
![Image](https://github.com/user-attachments/assets/21b95245-884a-4079-8c46-f6b013e79fff)

**Expected behavior**

Display the tuples the same way they are printed.

**Actual behavior**

Display is cut short on first /0 occasion.

**Known workarounds**

N/A.

**Related information**

Repros in VS2019, unlikely a regression.

**Comment by brianrourkeboll** [comment]
I think it's just `System.Tuple<>` and the fact that it uses `StringBuilder` for its `ToString` implementation.

Debugging C# with, e.g., `var tup = Tuple.Create(1, (char)0, 2);`, shows the same thing.

So does something like

```csharp
var q = new Q(1, (char)0, 2);

public sealed record Q(int A, char B, int C)
{
    public override string ToString() =>
        new System.Text.StringBuilder()
            .Append('(')
            .Append(A)
            .Append(", ")
            .Append(B)
            .Append(", ")
            .Append(C)
            .Append(')')
            .ToString();
}
```

![Image](https://github.com/user-attachments/assets/32bc9aa3-805e-493e-98b8-3d9c37b86376)

**Comment by psfinaki** [comment]
Nice, so I just broke .NET :D Somebody else's problem...

**Comment by vzarytovskii** [comment]
It's likely how strings with zero byte is treated in tooling. .NET strings are not null-terminated. Likely when they cross the boundary into unmanaged code (vsdbg?), the problem surfaces.

**Comment by 0101** [comment]
This doesn't seem to be an F# problem.
