### ISSUE TITLE
|> String.Join

### ISSUE THREAD

**Issue by Thorium** [dotnet/fsharp#18130]
I would like to have extension to use String.Join with pipe. I do encounter this task often when starting to evaluate new ideas.

Something like this in the core library:
```fsharp
module String = let Join separator (xs:System.Collections.Generic.IEnumerable<string>) = System.String.Join(separator, xs)
```

So then we could use String.Join in F# idiomatic style:
```fsharp
let x = [1 .. 100000] |> Seq.map(fun x -> "hello") |> String.Join ","
```

**Comment by majocha** [comment]
`String.concat` does this already: 
```fsharp
[1 .. 10] |> Seq.map(fun x -> "hello") |> String.concat ","
```

**Comment by Thorium** [comment]
Thanks, I guess I have to unlearn the C# method name then.
