### ISSUE TITLE
Regular crashes of a single code base

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#18150]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Regular-crashes-of-a-single-code-base/10799222)._

---
[severity:I'm unable to use this version]
Just code in our codebase, keeps crashing every 15 min. Other engineers in the team had same issues. 

---
#### Lisa Gao (CSI Interfusion Inc) [MSFT] on 11/26/2024, 02:51 AM: 

<p>Thanks for your feedback! In order to further investigate this issue, I need to confirm something with you. What programming language do you use with your project? (C#, C++, Visual Basic, JavaScript or other)? It would be very helpful if you could provide some screenshots that has this problem.</p>

#### Simon de Vegt on 12/4/2024, 10:25 AM: 

<p>Hi, we are using F# in most of the projects in this solution, there is a C# project in the solution which is not being modified. There is no way to provide a screenshot of a crash.</p>
<p>Typing code results in VS hanging for a couple of seconds before the process dies/is killed. It is not about modifying a single section of code this happens regularly no matter where I am working.</p>

#### Feedback Bot on 12/4/2024, 07:12 AM: 

<p>We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.</p>

#### Feedback Bot on 12/5/2024, 03:18 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by 0101** [comment]
In order to investigate this further we need either a repro or a memory dump.

**Comment by T-Gro** [comment]
The crashes were caused by a StackOverflow in the compiler service.
This has been fixed this summer, and latest VS version has this fix.

You have to make sure to download the version labelled as "17.12" https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-history#release-dates-and-build-numbers , e.g. this link will work:

https://aka.ms/vs/17/release.ltsc.17.12/vs_professional.exe
