### ISSUE TITLE
No ? on shorthand lambda synthax for dynamic op

### ISSUE THREAD

**Issue by jkone27** [dotnet/fsharp#18183]
lambda shorthand is missing `?` operator from Fsharp.Data or possibly other custom operators might not work?

**Repro steps**

```fsharp
#r "nuget: FsHttp"

open FsHttp
open FsHttp.DslCE

let hostname = "http://127.0.0.1:5000"

http {
    GET $"{hostname}/readiness"
}
|> Request.send
|> Response.toJson
// |> fun x -> x?applicationName.GetString() <<<<<<<<< explores json value dynamically using Fsharp.Data (?) operator
|> _?applicationName.GetString() // ERROR HERE

// check another route
http {
    GET $"{hostname}/log"
}
|> Request.send
```

**Expected behavior**

A shorthand version for dynamic ? should also be possible/applied ?

**Actual behavior**

Error, unable to compile

**Known workarounds**

keep using full lambda synthax

**Related information**

Provide any related information (optional):

* Operating system: MacOS
* .NET Runtime kind : NET9
* Editing Tools : vscode + ionide

**Comment by vzarytovskii** [comment]
(?) and (?<-) are special operators. It can't be applied to a method call (which is a not operator from compiler/lexer/parser standpoint). This should be a language suggestion.
