### ISSUE TITLE
Support Go To Definition/Peek Definition on symbols defined in .NET metadata

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#1939]
@vasily-kirichenko @cloudRoutine what are your thoughts on us taking the implementation in [VFPT](http://fsprojects.github.io/VisualFSharpPowerTools/gotometadata.html) and porting it to extend the existing Go To Definition/Peek Definition commands here?

**Comment by cloudRoutine** [comment]
we've been talking about moving everything we can from VFPT into VFT proper since it'd make it easier to shift the ported and adapted code in VFT to fsharp.editing afterwards.

I had started working on moving all of the more in-depth colorization last week, but I haven't had a chance to get back to it yet. 

The more logic that can go into FSharp.LanguageService decoupled from the VS APIs the easier it'll be to do the stuff we've talked about for xplat editing tools.

**Comment by vasily-kirichenko** [comment]
I think it was @dungpa who implemented it. I'm personally totally happy to have as much VFPT features potred as possible (it turns out not everything needs porting. Peek definition already works automagically, Rename is being rewritten from scratch).

**Comment by dungpa** [comment]
I can try to move it over to VFT.

**Comment by cartermp** [comment]
Awesome, @dungpa!

**Comment by cartermp** [comment]
@dungpa Is this something you're still thinking of trying to move over?  We've got a little less than a month left until the cutoff for features to make it into vs2017 RTM, so if we want it in then it'll have to get implemented quite soon.

**Comment by dungpa** [comment]
Sorry, I'm a bit busy right now. Will try to do it during the holiday (next week).

**Comment by cartermp** [comment]
Sounds good.  If you don't think you can afford the time then we can also take a look at this.

**Comment by dungpa** [comment]
@cartermp I have looked into more details.

It is not so practical to implement this feature right now.

The `IMetadataAsSourceService` interface requires `ISymbol` integration, which is not yet available: http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/MetadataAsSource/IMetadataAsSourceService.cs,efa3025f7d523cd9,references

Moreover, the Roslyn integration part is missing. So it's not easy to reuse the logic at https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/EditorFeatures/Core/IMetadataAsSourceFileService.cs

So I think this should only be done when we have deeper integration with Roslyn workspaces and Roslyn project systems.

**Comment by cartermp** [comment]
Bummer.  @Pilchie is there any light you could shed here?

**Comment by Pilchie** [comment]
We could probably do some work to separate the temp-file management from the rest of Metadata As Source so that F# could use that without symbols, but it's true that the actual work to generate source from metadata would need to be F# specific.

**Comment by vasily-kirichenko** [comment]
@Pilchie We already have the needed logic (as part of Visual F# Power Tools extension), so we could port it easily if the Roslyn API allowed.

**Comment by dungpa** [comment]
@Pilchie If the above interfaces become more general (based on positions instead of `ISymbol`), we can definitely make this happen.

**Comment by Pilchie** [comment]
I'm not against that change happening in Roslyn, but it's unlikely to come from a Roslyn team member before VS 2017 ships.

**Comment by forki** [comment]
related: https://github.com/dotnet/roslyn/issues/16511

**Comment by cloudRoutine** [comment]
@Pilchie any updates on this?

**Comment by saul** [comment]
I've made a bit of progress on navigating to C# projects that are within the same solution:

![go to csharp definition](https://cloud.githubusercontent.com/assets/64654/24476407/0e5af79a-14cb-11e7-8cf2-6fedb2da2ef7.gif)

**Comment by smoothdeveloper** [comment]
@saul curious if you could add a VB.NET project in that solution to confirm if it also works the same?

**Comment by vasily-kirichenko** [comment]
@saul this is fantastic! :) Any chance to make it working the other way around (C# -> F#)?

**Comment by saul** [comment]
@smoothdeveloper yeah I'm sure it would - I'll try it later but as it just uses Roslyn's SymbolFinder I have no reason to believe it wouldn't work. 

And @vasily-kirichenko I haven't investigated that yet - i imagine it'll be quite a bit harder.

**Comment by cartermp** [comment]
This has been implemented as WIP in #2658  by @cloudRoutine.

**Comment by bender2k14** [comment]
Quoting @cartermp from #5523
> The main issue isn't in reading metadata, but writing a palatable representation to a temporary window. There is a closed trial PR that gets this mostly there, but it had too many quirks to accept at the time. I'm interested in trying to take it on for VS 2019, though.

VS Code has this feature.  Is there an opinion here as to whether the behavior of this feature in VS Code has sufficiently few quirks that Visual Studio could take the same approach to solving the problem?

**Comment by levchenko-vl** [comment]
Hey,  the 2020 is here
we are almost done with cancer and AI becomes self-aware, but this can't be still done.
How?

If you need help. - Just say I personally will help whenever I can. 
I am new at f# and looking to the System types will be helpful.

**Comment by vasily-kirichenko** [comment]
@levchenko-vl just use Rider, it has this feature implemented long ago (as well as many others).

**Comment by cartermp** [comment]
This is partially implemented for 16.10. There are several more items to track that fall out of it though:

* Supporting going to F#-defined metadata items
* Print an F# signature file-like view rather than the decompiled view
* Disable diagnostics in the temporary document
* Support navigating to the item in the temporary document

**Comment by TysonMN** [comment]
Are there issues for each of those items?

**Comment by cartermp** [comment]
Yes
