### ISSUE TITLE
Feature Suggestion: F# Editor, F# Interactive: Extend "Execute in Interactive" to execute the current block

### ISSUE THREAD

**Issue by urbanhop** [dotnet/fsharp#2033]
Would wish a feature that allows executing **blocks** of a script file in F# Interactive. Example script file:

```
// ...

let inline increasing (a, b) = a > b

m.temperatures
|> Seq.pairwise
|> Seq.map increasing    // <---- working on this block
|> Seq.indexed
|> print

// ...
```

While editing the block above, I need to 1. select the whole block then 2. press Alt + BkSpce to execute it. The suggestion is about automating the selection step : A new command **Execute current block in Interactive** would automatically detect the boundaries of the block that the editor cursor is in and send the whole block to interactive.

Similar features are available in unit testing tools, were a test can be executed when editor cursor is inside that test code by firing the command "run test in current context".

This feature could be provided by an even simpler sub-step: **Provide a command that selects the current block**. This command could be associated with a key-shortcut, lets say ctrl-b. Then thesequence ctrl-b + alt-bkspce would execute the current block.

**Comment by abelbraaksma** [comment]
I like this idea, I miss it on a daily basis. Would be great if it works recursively, that is, hitting "select current block" multiple times would widen the selected block to the containing statement, function, method, class or even module.

**Comment by urbanhop** [comment]
@abelbraaksma supercool addition. 

If someone would hint about the implementation of this feature I might be able to spend some time trying to implement it.

**Comment by smoothdeveloper** [comment]
@urbanhop you might have a look at Structure service, which manage folding code blocks in the editor:

https://github.com/Microsoft/visualfsharp/blob/98372ab1aeeabc5db6b7eebaab13065ecf887d88/vsintegration/src/FSharp.Editor/Structure/Structure.fs

I think shortcuts for extending the range up or down would make sense besides the expanding the scope based on hierachy (local function, function, module, namespace).

**Comment by vasily-kirichenko** [comment]
Yeah, just grab the structure service ranges and pick the next smallest outer range, translate it to `TextSpan` and select it (no idea how to select a span in a Document, but it must be easy).

**Comment by Pilchie** [comment]
In theory the editor's [`ITextStructureNavigator`](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.text.operations.itextstructurenavigator.aspx) should support this.  Not sure whether F# currently has one, or relies on the old `GetWordExtent` though.
