### ISSUE TITLE
Error in resolving method call to instance method with byref

### ISSUE THREAD

**Issue by jack-pappas** [dotnet/fsharp#2062]
When implementing a class with an instance method accepting a non-generic ``byref`` parameter, and attempting to call that method from another instance method, the compiler does not correctly infer the type of the ``byref`` argument. This occurs even though the same argument is passed to an ``extern`` function earlier in the method and the type is correctly inferred at that call site.

#### Repro steps

Attempt to compile this code; I tried this in both a library and console application project and was able to repro in both. Also available in a [Gist](https://gist.github.com/jack-pappas/339d3ad4e5e45d7184a5c66d2ca2c5f7).

```fsharp
namespace FSharpByrefTypeInferBug

open System.Runtime.InteropServices

#nowarn "9"

type LONG = int32

[<AutoOpen>]
module NativeMethods =
    [<Struct; StructLayout(LayoutKind.Sequential)>]
    type RECT =
        val mutable public left : LONG
        val mutable public top : LONG
        val mutable public right : LONG
        val mutable public bottom : LONG

    [<DllImport("foo.dll")>]
    extern [<MarshalAs(UnmanagedType.Bool)>] bool FooBar (nativeint xyz, RECT& rect)


type Class1() =
    member private __.MyMethod (r : byref<RECT>) =
        printfn "Top: %i" r.top
        ()

    member this.DoStuff () =
        let mutable myRect = Unchecked.defaultof<RECT>
        if FooBar (1234n, &myRect) then
#if ENABLE_WORKAROUND
            // Adding parentheses around the method argument fixes
            // the type resolution for `&myRect`` and allows the
            // program to compile/run as expected.
            this.MyMethod (&myRect)
#else
            // Even though the type of `myRect` is known above, and the compiler
            // infers the type of `&myRect` correctly when calling the FooBar function,
            // attempting to call `MyMethod` with the same argument results in a
            // compiler error:
            // error FS0001: This expression was expected to have type    RECT ref    but here has type    byref<'a>
            this.MyMethod &myRect
#endif
```

#### Expected behavior

The compiler should infer the type of ``&myRect`` at the call site to ``this.MyMethod`` as ``byref<RECT>``.

If the workaround (mentioned below) is what users are *expected* to do here, the error message should be improved to better indicate how to resolve the issue.

#### Actual behavior

The compiler infers the type of ``&myRect`` at the call site to ``this.MyMethod`` as ``RECT ref`` (i.e., a ``ref`` cell holding a ``RECT`` value).

#### Known workarounds

Surrounding the method argument with parentheses fixes the type inference issue and allows the code to compile and run as expected.

#### Related information 

* Windows 7 SP1, x64
* .NET Runtime 4.6.2
* Visual Studio 2015 Update 3

This is a ``byref`` related issue, so I'll mention #862 to link them.

**Comment by dsyme** [comment]
@jack-pappas Yes, looks like a glitch.

**Comment by dsyme** [comment]
I checked the repro and it now compiles with latest, closing
