### ISSUE TITLE
Separate error messages from quick info

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#2091]
As @dsyme already said, it's desirable to separate error/warning messages from normal Quick Info. Here the first line is a Quick Info and the second - error message:

![image](https://cloud.githubusercontent.com/assets/873919/21452614/3bd812b4-c919-11e6-9816-d3565ac4216e.png)

@CyrusNajmabadi We'd like to keep the current behavior (show both errors and quick info at the same time), but highlight errors somehow (show them in brown text or at least separate them in a group). Any ideas?

**Comment by vasily-kirichenko** [comment]
I've checked C# editor, it behaves the same:

![image](https://cloud.githubusercontent.com/assets/873919/21453419/d8bb4a6e-c91f-11e6-846f-e29660fe4148.png)

**Comment by abelbraaksma** [comment]
I wouldn't mind doing it better than C# ;).

One of the things I have always been missing is the error code in the quick-info tooltip. If you were to add just that, it solves two problems: you don't need to compile to see the error code, and it becomes immediately clear you are looking at an error and not the description from the XML Doc comments.

Alternatively, you could simply (?) match squiggly color: red for error, orange for warning etc. If you have a warning, suggestion, info and error in one tooltip, it is then still distinguishable.

**Comment by cartermp** [comment]
Yep, I'd definitely like to see a separation.  The way it looks in VSCode + Ionide is really nice:

![errors-separate](https://cloud.githubusercontent.com/assets/6309070/21484442/7a6138d2-cb47-11e6-9b37-8828a133337a.PNG)

@Pilchie @CyrusNajmabadi @AnthonyDGreen what are your thoughts here?  Is this something that's on the radar for C# and VB?  This is clearly something that's not unique to F# in terms of value gained.

**Comment by dsyme** [comment]
Reopening as this is the canonical issue for this feature request right now

**Comment by AnthonyDGreen** [comment]
Looks awesome. Ship it!
