### ISSUE TITLE
Can't add a reference to a portable C# library for localisation

### ISSUE THREAD

**Issue by SpiegelSoft** [dotnet/fsharp#2113]
This issue is specific to Visual Studio 2017 RC.

My project contains an ASP.NET Core Web project, and two portable F# libraries (Profile 259). The web project references these libraries, and I would like in the future to add Xamarin Forms projects which also reference the same Profile 259 libraries.

[![enter image description here][1]][1]

I would also like to have a localisation resources file (maybe in its own shared project), which can be read by all of the projects in my solution. In Visual Studio 2015, I achieved this by creating a portable C# project and adding the relevant `resx` file.

In Visual Studio 2017, I can't add a portable C# class library. When I attempt to do so, it serves up a modal dialog, which does not accept any of the options it presents me with:

[![enter image description here][2]][2]

I can, however, add a Xamarin Forms library:

[![enter image description here][3]][3]

and although this references Xamarin Forms libraries I'm not really interested in, it can at least be added, and I can add my localisation file `LocalisedStrings.resx` to the project.

However, even though I've changed the access modifier to "Public" in the `resx` file, it is not getting read from my F# library. The code

    module Locales =
        let [<Literal>] private Gender = "Gender"
        let private localisedStringsProperties = typeof<LocalisedStrings>.GetTypeInfo().DeclaredProperties
        let GetStringDictionary(predicate) = localisedStringsProperties |> Seq.filter predicate |> Seq.map (fun p -> (p.Name, p.GetMethod.Invoke(null, [||]).ToString())) |> dict
        let GetGenders() = GetStringDictionary(fun p -> p.Name.StartsWith(Gender) && p.Name.Length > Gender.Length)
        let GetValues(keys) = 
            let values = GetStringDictionary(fun p -> keys |> Array.exists(fun key -> key = p.Name))
            let evaluate key =
                match values.ContainsKey key with
                | true -> values.[key]
                | false -> key
            keys |> Array.map evaluate
        let GetValue(key) = GetValues([|key|]).[0]

does not recognise either the namespace or the class `LocalisedStrings`.

**ISSUES**

 1. I can't add a portable C# library.
 2. When I add a Xamarin Forms C# library, its classes are not picked up by portable F# libraries.

  [1]: https://i.stack.imgur.com/h7YAh.png
  [2]: https://i.stack.imgur.com/kxtln.png
  [3]: https://i.stack.imgur.com/t4I04.png

**Comment by abelbraaksma** [comment]
For reference, this issue [was first raised on StackOverflow](http://stackoverflow.com/questions/41332062/localisation-that-can-be-read-by-a-portable-f-project-profile-259) (and as of yet is unanswered there). I suggested to move it here as I think it is a bug.

**Comment by Pilchie** [comment]
The issue with the portable dialog is that you need to have multiple things checked that actually cause a different surface area to exist - checking just .NET Framework 4.6 doesn't make sense for a portable library, because it's not portable across anything - it would just be a .NET Framework 4.6 class library.

**Comment by SpiegelSoft** [comment]
Thanks for this. That certainly fixed the first issue: I added all of the elements that were included in Profile 259, and that permitted the portable C# library to be added.

However, the classes are still not picked up in the Profile 259 library.

**Comment by Pilchie** [comment]
Can you look at the generated library with ildasm/dotpeek/ilspy/etc and see if the assembly actually contains that type, and that it is public?  Is it in namespace that you need an `open` for?

**Comment by cartermp** [comment]
Given the move to .NET Standard for sharing code across platforms, and the deprecation of PCLs, I think it is unlikely that we will look at this.

@SpiegelSoft If you use ASP.NET Core 2.0 and Xamarin.Forms 2.4+ with VS 15.5.x or higher, do you have issues sharing an F#/.NET Standard 2.0 project? If so, we'll definitely want to address any of those issues.

**Comment by erfankh67** [comment]
you can use application => "Service Reference Generator For .net Standard & Xamarin.Forms"  from : https://files.fm/u/p9cx34ux
first read help in application

**Comment by erfankh67** [comment]
you can use application => "Service Reference Generator For .net Standard & Xamarin.Forms" from : https://files.fm/u/mduffseg

  first read help in application

**Comment by cartermp** [comment]
Creation of PCLs is now deprecated with VS 2019. I'm going to close this as we wouldn't service VS 2017 F# tools for something like this.
