### ISSUE TITLE
Blockstructure lines are a bit weird 

### ISSUE THREAD

**Issue by forki** [dotnet/fsharp#2115]
![image](https://cloud.githubusercontent.com/assets/57396/21500829/17230cc6-cc43-11e6-80dd-022265ac2c81.png)

/cc @cloudRoutine

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/21517999/a20a2e00-cce3-11e6-9706-412b5fdd28da.png)

why is this first line show. we already have a line over there

**Comment by saul** [comment]
Here's two more:

1. Class where the constructor arguments are on a new line.
2. Computation expressions. The guide line seems to start at the opening brace.

![sketch 21](https://cloud.githubusercontent.com/assets/64654/21550895/47d1f518-cdf5-11e6-82be-43d609de0724.png)

**Comment by vasily-kirichenko** [comment]
@saul that was not me, that was @cloudRoutine (and he is the original author of all the code ported from VFPT).

**Comment by saul** [comment]
Sorry - wasn't implying that you broke it - just that you may know of the fix :)

**Comment by cartermp** [comment]
Classifying this set of bugs as `urgency-soon`.  Although it certainly doesn't *break* people, some of the above things look weird enough to justify trying to get this in for release.

**Comment by cartermp** [comment]
If we can't get some of these fixes in for release, we should definitely discuss turning the feature off.

**Comment by vasily-kirichenko** [comment]
@saul are you sure you test the latest version from master? I cannot reproduce you issues:

![1](https://cloud.githubusercontent.com/assets/873919/21554263/213eeeae-ce1f-11e6-9319-b61faa58d998.gif)

**Comment by saul** [comment]
Definitely not on latest master - I've been refraining from updating over the past few days because of #1825

If you can't reproduce on master then please ignore my comment. I can consistently reproduce it on every computation expression.

**Comment by vasily-kirichenko** [comment]
FYI

It turns out, there is a global setting which turns on / off _guidelines_ (not block collapsing, but just guidelines):

![image](https://cloud.githubusercontent.com/assets/873919/21748243/1e25d484-d591-11e6-81c5-8184fc2ca373.png)

So annoyed people will be able to turn it off.

**Comment by saul** [comment]
Vasily have you any idea why the extra guidelines are shown for multi-line pattern match cases? My issue that was closed as dupe has a minimal repro: #2191

**Comment by cartermp** [comment]
I just noticed the same issue as Saul for parameters on the same line, but this time on a static member.

![structure-guidelines-weird](https://cloud.githubusercontent.com/assets/6309070/22139930/36a71ea8-de9e-11e6-847f-b733d9f1076f.PNG)

This is the first line I noticed: https://github.com/bryanedds/Nu/blob/master/Nu/Nu/Render.fs#L206
