### ISSUE TITLE
In FSI, hitting Alt+Up arrow throws error messagebox "The operation could not be completed"

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#2176]
In Visual Studio, in the FSI window, if you hit Alt+Up arrow, you receive a messagebox with the error text "The operation could not be completed".

![image](https://cloud.githubusercontent.com/assets/16015770/21723982/cd2cc704-d432-11e6-9319-8fd7d714abd8.png)

### Repro steps
Open FSI in Visual Studio, hit Alt+Up. It doesn't matter whether the current line has anything on it or not.

Alt+Down does nothing (no error).

### Expected behavior
No error. 

Either a no-op (like with Alt+Down), or the same behavior as C# Interactive (which happens to be the same as UpArrow without Alt).

### Actual behavior
Error modal dialog popup: "The operation could not be completed".

### Known workarounds
None (or don't use this key combi).

### Related information 
* Windows 7, Win10
* F# 4.0
* VS 2015

**Comment by cartermp** [comment]
I can repro on vs2017 as well.

**Comment by abelbraaksma** [comment]
@cartermp, in VS2017 15.3.1.0 Preview 1, and also with the nightlies of August 21 (today), the messagebox is indeed still there. However, the juice unspecified error text is gone at least on my system, I have the old messagebox back:

![image](https://user-images.githubusercontent.com/16015770/29544169-8bd9fd14-86e6-11e7-867c-94c63188781e.png)

**Comment by dsyme** [comment]
I didn't repro this with VS2022
