### ISSUE TITLE
FSI should provide a method to customise syntax highlighting

### ISSUE THREAD

**Issue by saul** [dotnet/fsharp#2179]
(As requested as a result of #2156 being merged)

FSI (command line) should provide a method through which the colours can be customised.

**Comment by KevinRansom** [comment]
Target VS2017 update 1.

**Comment by slang25** [comment]
The latest PR is much better, this looks awesome =) Although prior to Windows 10 Anniversary Update you only have 16 a color palette to play with, you are able to map the standard 16 to whatever colors you want, so you could use this technique to replicate the VS dark theme (ala Colorful.Consul: https://github.com/tomakita/Colorful.Console/blob/master/src/Colorful.Console/ColorMapper.cs). The downside is you are overriding default mappings / terminal color theme. Maybe with a command line parameter + VS setting to control between standard color palette, our custom palette, and colors off.

Another option is to use the 24-bit color support added to Windows 10 Anniversary Update which uses ANSI color support (virtual terminal sequences), this would work cross-plat too (as would the previous suggestion of remapping the 16 palette ). I can see 2 big problems with this 1. You'd need to detect the support of this on windows, and you can only do it by platform, no way to actually interrogate the terminal (for code, see libuv: libuv/libuv#889 (comment)). 2. We don't need a palette greater than 16! So this idea is pointless.

Again, great work, the last few months of PRs have got me very excited for the VS 2017 release, many thanks to all!

**Comment by cloudRoutine** [comment]
@slang25 you can get full 24bit support on windows right now with cmder/ConEmu

![](http://i.imgur.com/xWbi2h9.png)

the syntax pallete can be stored in the fsi.exe.config/fsianycpu.exe.config
