### ISSUE TITLE
Intellisense does not work well in the middle of symbol name

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#2200]
![1](https://cloud.githubusercontent.com/assets/873919/21752436/d3356fb8-d5e8-11e6-82ce-f82cd41604a7.gif)

Suggestions Code Fix works much, much better here :)

**Comment by dsyme** [comment]
@cartermp  @vasily-kirichenko This looks like a regression, is that correct?  I see better behavior in VS2017?

**Comment by cartermp** [comment]
Yup, this is a regression.  Below is vs2015:

![middle-no-work-well](https://cloud.githubusercontent.com/assets/6309070/22564434/5ce4686e-e939-11e6-964d-84ac243b8de6.PNG)

**Comment by vasily-kirichenko** [comment]
It's an upstream Roslyn bug:

![image](https://cloud.githubusercontent.com/assets/873919/22883852/347cdcee-f203-11e6-863c-0a60c6eb2291.png)

**Comment by cartermp** [comment]
@vasily-kirichenko I'm skeptical that it's an issue with Roslyn that's causing this regression.  Likely something we didn't wire up ourselves.  That behavior in C# should be expected.

**Comment by majocha** [comment]
Yeah, C# works fine when "show completion after char deleted" is set. We don't have Intellisense settings.

**Comment by vasily-kirichenko** [comment]
Roslyn completion behavior is adjustable on code level, I'll try to turn on "after char deleted".
