### ISSUE TITLE
Remove internals visible to F# editor in Roslyn.

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#2349]
The XAML team came up with a nifty shim dll that allows roslyn to publish a contract .dll until they have hardened up their public APIs.
Because Roslyn team build this dll, when they refactor an internal API such that XAML gets broken, they see it in the Roslyn build.

We should ensure that we have a similar process so that we don't get stung like we did with the refactoring of:
````
IStreamingFindReferencesService
````
to
````
IFindUsagesService
````

**Comment by cartermp** [comment]
@TIHan How do you want to handle this?

**Comment by TIHan** [comment]
This will be a 16.2 to 16.3(being conservative).

**Comment by cartermp** [comment]
Closing as completed for 16.2.
