### ISSUE TITLE
Folder name must be unique in the entire project

### ISSUE THREAD

**Issue by enricosada** [dotnet/fsharp#246]
When multiple folders with the same name ( but different path ) exist in the project, the following error occurs:

> The project 'Test.fsproj' could not be opened because opening it would cause a folder to be rendered multiple times in the solution explorer. One such problematic item is 'Second\foo.fs'. To open this project in Visual Studio, first edit the project file and fix the problem.

ref:
- fsprojects/VisualFSharpPowerTools#116
- [bug on stackoverflow](http://stackoverflow.com/questions/22845020/visual-studio-f-project-cant-have-two-folders-in-a-file-tree-with-the-same-na)

an example (see  )

``` xml
<ItemGroup>
    <Compile Include="First\Second\File.fs" />
    <Compile Include="Second\File.fs" />
</ItemGroup>
```

instead this is ok:

``` xml
<ItemGroup>
    <Compile Include="First\Second\File.fs" />
    <Compile Include="Third\File.fs" />
</ItemGroup>
```

also invalid:

``` xml
<ItemGroup>
    <Compile Include="First\First\File.fs" />
</ItemGroup>
```

i got a pr to fix this behaviour

**Comment by enricosada** [comment]
btw this check is there to prevent something like this:

```xml
<ItemGroup>
    <Compile Include="A\B\File.fs" />
    <Compile Include="C\File.fs" />
    <Compile Include="A\File.fs" />
</ItemGroup>
```

where folder `A` is rendered two times, before and after folder `C`

**Comment by SpiegelSoft** [comment]
This is happening now in a Xamarin Android project. It's impossible to work with F# here, because of the requirement to have resources with multiple resolutions.

**Comment by SpiegelSoft** [comment]
Visual Studio 2017, V15.6.7

**Comment by mfortunat** [comment]
Thanks @SpiegelSoft 
it worked perfectly even with VS 2015.
(Version 14.25431.01 Update 3)

**Comment by SpiegelSoft** [comment]
The fix I posted earlier does not work for my current project.

**Comment by SpiegelSoft** [comment]
Thanks Philip. What I have found is this. File order is crucial. If you have more than one file, the ordering needs to be as follows:

```
    <AndroidResource Include="Resources\mipmap-hdpi\File1.png" />
    <AndroidResource Include="Resources\mipmap-hdpi\File2.png" />
    <AndroidResource Include="Resources\mipmap-mdpi\File1.png" />
    <AndroidResource Include="Resources\mipmap-mdpi\File2.png" />
    <AndroidResource Include="Resources\mipmap-xhdpi\File1.png" />
    <AndroidResource Include="Resources\mipmap-xhdpi\File2.png" />
    <AndroidResource Include="Resources\mipmap-xxhdpi\File1.png" />
    <AndroidResource Include="Resources\mipmap-xxhdpi\File2.png" />
    <AndroidResource Include="Resources\mipmap-xxxhdpi\File1.png" />
    <AndroidResource Include="Resources\mipmap-xxxhdpi\File2.png" />
```

Any deviation from this ordering will reintroduce the problem.

**Comment by cartermp** [comment]
@SpiegelSoft I don't quite recall how Android Studio lays Android resources out on disk, but I vaguely recall a similar ordering. Do the Android Xamarin tools not order in the manner by default?

**Comment by SpiegelSoft** [comment]
Not using right click with copy and paste.

**Comment by SpiegelSoft** [comment]
This is with Visual Studio 2017

**Comment by cartermp** [comment]
The .NET SDK-style project system fully supports these scenarios:

![image](https://user-images.githubusercontent.com/6309070/58289913-bd74d000-7d6c-11e9-9be5-aa7ce4f7a536.png)

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="First\First\File.fs" />
    <Compile Include="First\Second\File.fs" />
    <Compile Include="Second\File.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
```

We're frozen the legacy project system, so I'll close this. Moving code to the .NET SDK project system will resolve any issues of this nature.
