### ISSUE TITLE
It's impossible to set breakpoints in half of lines inside async blocks

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#2557]
![1](https://cloud.githubusercontent.com/assets/873919/23722068/061d8e20-0455-11e7-8377-2c0cffe05e7f.gif)

**Comment by cartermp** [comment]
@vasily-kirichenko Do you know if this is also reproducible in vs2015?  You and @forki definitely improved breakpoint resolution in various areas but I'm curious if that affected some more complicated structures

**Comment by dsyme** [comment]
I took a look at this and tried to create a repro based on what I see in the screen shot.  I was able to set breakpoints fairly well - though not perfectly

At some point we should try more extensively in more real-world async code 

![image](https://user-images.githubusercontent.com/7204669/30173618-3250e624-93f0-11e7-9cca-dd88bdbf8e35.png)

**Comment by cartermp** [comment]
The code has diverged significantly in the past years, but the remaining lines that are still relevant can all have breakpoints set. Will close as no repro
