### ISSUE TITLE
FSharp.ProjectSystem.PropertyPages does not work properly

### ISSUE THREAD

**Issue by sayurin** [dotnet/fsharp#2564]
Visual Studio 2017 F# project, Project Property Pages does not work properly.
"Other flags" option and "Prefer 32-bit" checkbox are incorrect values.

#### Repro steps

1. Create a F# project.
2. Open project's property pages.
3. Open "Build" tab.
4. Change "Configuration" value to "Debug".
5. Change "Other flags" textbox or "Prefer 32-bit" checkbox value.
6. Change "Configuration" value to "Release".

#### Expected behavior

At 5., "Other flags" and "Prefer 32-bit" are setting for "Debug" configuration. So these controls are reloaded by "Release" configuration. Of course, other settings like "Optimize code" are reloaded.

#### Actual behavior

"Other flags" and "Prefer 32-bit" values are not reloaded and not updated.

#### Known workarounds

Change "Solution Configurations" via "Standard" toolbar or "Active solution configuration" via "Configuration Manager" dialog. "Other flags" and "Prefer 32-bit" values will be updated.

#### Related information 

* Microsoft Visual Studio Enterprise 2017
* Version 15.0.26228.4 D15RTWSVC
* Visual F# 4.1   00369-60000-00001-AA519

**Comment by KevinRansom** [comment]
@sayurin 

I just tried this out on my laptop and I see the Other flags and Prefer 32 bit values change when I switch settings.  Is there something I m missing?

**Comment by sayurin** [comment]
[Sample.fsproj.txt](https://github.com/Microsoft/visualfsharp/files/832324/Sample.fsproj.txt)

**Comment by sayurin** [comment]
Sorry, I missed.
How about this figure?
![buildpage](https://cloud.githubusercontent.com/assets/3615855/23771781/d561c06e-055b-11e7-8a46-bc7332149d12.jpeg)

**Comment by KevinRansom** [comment]
I think I see the issue now.

**Comment by sayurin** [comment]
Still need more info?

**Comment by KevinRansom** [comment]
No I can repro the problem.

Thank you for finding this.

**Comment by cartermp** [comment]
This seems to be resolved for the legacy project system. Switching configurations seems to respect whatever was set for either `Prefer 32-bit` or the `Other flags` settings in the property pages.
