### ISSUE TITLE
Nightly release pipeline: add commit id

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#2631]
Is it possible to have a way to correlate the nightly releases to specific commits from this repository?

I'd like to know which commit corresponds the version I'm running

https://dotnet.myget.org/feed/fsharp/package/vsix/VisualFSharp/15.4.1.17031602

![image](https://cloud.githubusercontent.com/assets/87944/24021561/dfd47faa-0aa1-11e7-935f-4bf732761beb.png)

**Comment by ctaggart** [comment]
@smoothdeveloper, is this for debugging purposes? If #2675 is merged and the pdb files are packaged with the nightly builds, then they will contain the commit id. You should even be able to debug into the exact source code without having a local clone. That is the goal anyhow. Once nightly builds show up with source link enabled, I'll show how to get the commit id.

**Comment by smoothdeveloper** [comment]
@ctaggart, thanks for the update, the main purpose was to know which commit the nightly I'd install is made from (so I know which feature is there or not & else).

Having ability to debug and source link as extra side effects is very nice!

**Comment by cartermp** [comment]
Hmmm. I'm not sure we'd really do this anymore given that the VF# tools are quite stable now, and nightly usage is down significantly as a result. Each build is seeing 0-5 installs which is quite small.
