### ISSUE TITLE
Repository CI: add end-to-end test in CI

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#2633]
I'm thinking adding this integration test will catch issues with tooling:

* compile this repository `build proto net40 release vs`
* deploy vsix in Visual Studio
* get a clean clone of this repository
* compile `proto net40 release`
* open VisualFSharp.sln with devenv (with the VSIX just compiled)
* run VisualFSharpOpenSource project
* open VisualFSharp.sln in new instance
* open a file
* wait 2 minutes for type check and no error
* issue a "Find Usages" on some symbol

If that test passes we gain some confidence about VS tooling being usable to work on this repository

**Comment by cartermp** [comment]
I don't think we'd do something like that in our CI runs. At this point the tooling is quite stable and when there is an issue it tends to get resolved pretty quickly.
