### ISSUE TITLE
Quick info toolbar/code lens from VFPT (VS2015) in VS2017

### ISSUE THREAD

**Issue by s952163** [dotnet/fsharp#2634]
This is an enhancement request.

VFPT in VS2015 provides a very handy quick info toolbar that shows the function signature and is clickable for copy&paste. 

<img width="695" alt="quickinfotoolbar" src="https://cloud.githubusercontent.com/assets/16188516/24036602/8d7d6234-0b3d-11e7-832e-6d23021e2c3b.PNG">

It would be very nice to have the same quick info toolbar and/or codelens style signatures in Visual F# Tools as well in VS2017.

* Win10
* Visual F# Tools 15.4.1.17031503
* Visual Studio 2017 RTW

**Comment by vasily-kirichenko** [comment]
I started porting it from VFPT, but it uses the old way of watching text buffer change, throttling events, getting cursor position and source text via raw VS API and so on. We should not do it. We should find a proper, Roslyn-powered way to do it.

**Comment by s952163** [comment]
Yes, it does seem complicated. If Roslyn is the way to go forward that's best.

**Comment by majocha** [comment]
Looking at Roslyn, it also uses `Caret.PositionChanged` event everywhere.
However, Roslyn does take care of reanalyzing when needed. It would be great to get some callback whenever we have fresh results.

**Comment by theprash** [comment]
This is an important missing piece for me. Note that [the VFPT feature](http://fsprojects.github.io/VisualFSharpPowerTools/quickinfopanel.html) is actually advertised as showing errors, not types, but on my machine it shows types and not errors, and that's what I find the most useful.  However, this means I need reach over to the mouse and hover over errors. Ideally, both types and errors should be shown.

**Comment by cartermp** [comment]
Going though some older requests:

I don't think we'll ever do this. The scenario of "show me type information without having to touch the mouse to hover" can be done by pressing the **ctrl-K+I** chord.

This feature will also be another way to get that info: https://github.com/dotnet/fsharp/issues/10289

I have it working very well from the F# side of things in a PR already, but need to flow through options from Roslyn. It will likely be a VS 16.10 thing.
