### ISSUE TITLE
Incorrect slicing: l.[..(-1)] should give [] not an error

### ISSUE THREAD

**Issue by charlesroddie** [dotnet/fsharp#2643]
## `l.[..j]` does not currently satisfy any reasonable definition
    let l=[1;2]
    l.[0..(-1)] // gives []
    l.[..(-1)] // gives an index out of range error; should give []
    l.[2..] // gives [], correctly but inconsistently with l.[..(-1)]

The same applies to arrays and strings.

The slicing tests at https://github.com/Microsoft/visualfsharp/blob/master/tests/fsharp/core/array/test.fsx explicitly require the curent incorrect error.

## `l.[i..j]` works well.
For example for `l.[0..j]` there are three unambiguous cases:
j=-1 gives `[]`, the natural initial condition
j=0 gives `[1]`
j=1 gives `[1;2]`

Overall `l.[i..j]` satsisfies the definition: take the set `{n:i≤n≤j}`, order it as a list, and look up the elements of that list. So j=2 gives an error, and j=-2 gives `[]`.

There are other reasonable definitions but they will give the same results for -1,0 and 1.

## Resulting problems: gaps in reasoning
As with all failures to use the best initial case (humans before the discovery of 0, difficulty some have with 0!=1, the product of an empty set, etc.) it creates gaps in logic that require workarounds.

For example if `n` is a position in the string `s`, you would expect `s.[..(n-1)]` to be the substring prior to `n` but this is not generally true at the moment (for n=0).

Currently the meaning of `l.[..j]` cannot be stated simply.

**Comment by KevinRansom** [comment]
Thanks for this Analysis, it seems there may even be a few extra issues related to your analysis.


l.[..-1]       //gives a build error intuitively a -1 should work in a slice as well as (-1)



l.[(-1)..] // gives an index out of range error; should give []



Fixing these issues will not be breaking, because currently they will result in runtime errors or a compile error.


Kevin

**Comment by KevinRansom** [comment]
@charlesroddie 

Thanks for this Analysis, it seems there may even be a few extra issues related to your analysis.
\l.[..-1]       //gives a build error intuitively a -1 should work in a slice as well as (-1)

l.[(-1)..] // gives an index out of range error; should give []

Fixing these issues will not be breaking, because currently they currently result in runtime errors or a compile error.

Kevin

**Comment by charlesroddie** [comment]
Yes that is another issue. `let x = -1; l.[0..-x]` works while `l.[..-x]` doesn't. But people who use F# are used to having to put brackets around things if they don't compile :).

I think `l.[(-1)..]` giving an error is OK. It's the same as `l.[-1..2]`, which also gives an error, because it tries to look up the indices -1,0,1,2.

Alternatively you could take `l.[(-1)..]` to mean: take the infinite sequence -1..=-1,0,1,2,..., restrict to the valid indices 0,1 and then look up, giving `[1;2]`.

**Comment by charlesroddie** [comment]
The negative number/operand parsing issue crops up in the increment too:
`[2..-1..0]` gives `[2;1;0]`
`let x = 2 in [x..(-1)..0]` gives `[2;1;0]`
`let x = 2 in [x..-1..0]` gives `error FS0001: The type 'int' does not support the operator '..-'`

**Comment by cartermp** [comment]
Closing as this has now been implemented

**Comment by cartermp** [comment]
So I can't understand why I closed this, since this is _not_ implemented for arrays and strings as per the RFC: https://github.com/fsharp/fslang-design/blob/master/FSharp.Core-4.4.3.0/FS-1036-consistent-slicing.md

**Comment by cartermp** [comment]
I view this as more of a bugfix level thing given that it was implemented by lists but not the others:

```
> let str = "abcdef";;                                                                                                                                                                 
val str : string = "abcdef"                                                                                                                                                            
                                                                                                                                                                                       
> str.[0..(-1)];;                                                                                                                                                                      
val it : string = ""                                                                                                                                                                   
                                                                                                                                                                                       
> str.[..(-1)];;                                                                                                                                                                       
System.IndexOutOfRangeException: Index was outside the bounds of the array.                                                                                                            
  at <StartupCode$FSI_0053>.$FSI_0053.main@ () [0x00024] in <cdb3eb0bad834e868d04fd19cd798999>:0                                                                                       
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)                                           
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalizati
on.CultureInfo culture) [0x00032] in <f3f2aa82c3a04d48845485ce37124803>:0                                                                                                              
Stopped due to error                                                                                                                                                                   
> lst;;                                                                                                                                                                                
val it : int list = [1; 2; 3; 4; 5; 6; 7; 8; 9; 10]                                                                                                                                    
                                                                                                                                                                                       
> lst.[0..(-1)];;                                                                                                                                                                      
val it : int list = []                                                                                                                                                                 
                                                                                                                                                                                       
> lst.[..(-1)];;                                                                                                                                                                       
val it : int list = [] 
```

**Comment by cartermp** [comment]
This is now completed for F# 5 preview - all built-in types with slices have the same behavior.
