### ISSUE TITLE
QuickInfo doesn't show XML doc comment when F# value has default constructor type constraint

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#2742]
1. Enter the following code:

```fs
module Test =
    /// Test comment.
    let bad<'T when 'T : (new : unit -> 'T)> = Unchecked.defaultof<'T>

    /// Test comment.
    let good<'T when 'T : null> = Unchecked.defaultof<'T>
```

2. Hover over `bad`.

#### Expected behavior

"Test comment" is shown in QuickInfo.

#### Actual behavior

No XML comment:

![no-comment](https://cloud.githubusercontent.com/assets/6309070/24521892/91e9873a-1542-11e7-9224-c76f9300afe0.PNG)

Note that it works for `good`:

![yes-comment](https://cloud.githubusercontent.com/assets/6309070/24521897/996496b2-1542-11e7-9a62-69df28c6256c.PNG)

#### Known workarounds

None, aside from not using the default constructor type constraint.

#### Related information 

VS 2017
Nightly - 15.4.1.17032801

**Comment by cloudRoutine** [comment]
@cartermp I don't think quickinfo is the source of the issue, if you compile the module and check the output xml file

```xml
<?xml version="1.0" encoding="utf-8"?>
<doc>
<assembly><name>Library1</name></assembly>
<members>
<member name="M:Library1.Z.good``1">
<summary>
 Test comment.
</summary>
</member>
</members>
</doc>
```

**Comment by cartermp** [comment]
@dsyme Could this be an issue in how MSBuild knows what the output?  The function isn't even output to an XML file if it has a default constructor constraint.

**Comment by dsyme** [comment]
odd. I'm not sure what's going on

**Comment by dsyme** [comment]
The reason for this is that the processing of the declaration construct "new : unit -> 'T" grabs the XML documentation prior to the construct

**Comment by cartermp** [comment]
@TIHan and @agocke more parser goodness

**Comment by dsyme** [comment]
@cartermp It's not so much the parser as the fact that the ``grabXmlDoc`` technique is inaccurate and based on a sloppy use mutable state.  We should store all the XML doc tokens separately, then assign them using a less imperative technique base on ranges from the appropriate token such as the ``NEW`` token in this case.

**Comment by dsyme** [comment]
I checked in latest and the comment is now shown
