### ISSUE TITLE
build test does not work if you have a newer version of nunit console already installed

### ISSUE THREAD

**Issue by jackmott** [dotnet/fsharp#2783]
nunit console will search the pc for the newest version of nunit-console installed, and this can cause a conflict can cause an error when trying to run `build test`

#### Repro steps

1. Install the newest [nunit-console](https://www.nunit.org/index.php?p=download)

2. run `build test`

#### Expected behavior

Should test

#### Actual behavior

Get an nunit error

#### Known workarounds

Uninstall the newer nunit console application

#### Related information 

This issue may have info on workarounds that could be implemented:
https://github.com/nunit/nunit/issues/1348

**Comment by cartermp** [comment]
Closing as this should no longer be an issue. We get all test stuff from packages and just use those.
