### ISSUE TITLE
Re-enable high entropy and subsystem version tests

### ISSUE THREAD

**Issue by brettfo** [dotnet/fsharp#2858]
Re-enable the tests disabled by PR #2857.

**Comment by cartermp** [comment]
Since it's been at least 3 years, I'm not sure we're going to re-enable the, especially as we move to xUnit.

**Comment by KevinRansom** [comment]
These are two command line options that we have, we should probably do something.  I'm not certain these tests were the right one, but while we have the command line options, we should at least be embarrassed we don't test them :-)

**Comment by cartermp** [comment]
Fair enough

**Comment by dsyme** [comment]
Tracking all disabled tests by https://github.com/dotnet/fsharp/issues/10958
