### ISSUE TITLE
Switch to Site Specific Notification Adornments over Modal Dialog Boxes

### ISSUE THREAD

**Issue by cloudRoutine** [dotnet/fsharp#2894]
I know @saul loves these popups and thinks we should use them just because C# does, but I really think we should try another approach. Modal dialog boxes are an obtrusive overkill just to provide a small amount of information.

![](http://i.imgur.com/BoQi2qQ.gif)

I think the criticism of the status bar notification I had it use instead was fair, if someone didn't know to look there they could easily miss the message before it timed out.

![](https://i.imgur.com/hNPI82O.gif)

^ I think VSCode has adopted a nice convention for this kind of notification and we should try to implement something similar.

cc @majocha @vasily-kirichenko

**Comment by saul** [comment]
I don't love popups I just love consistency ;) I think the VS Code behaviour is better - it's more obvious than the status bar change. I don't think we have the capability in the IDE to create those kinds of popups though.

**Comment by cloudRoutine** [comment]
@saul we can do it with adornments, you can make adornments with pretty much any kind of wpf element, position them relative to the viewport or a position in the textbuffer, and you can animate them too.

**Comment by cartermp** [comment]
I think this would be splendid.  Although this sort of thing is ultimately a downlevel concern that the VS editor team could build support for, the most effective way for that to happen is to demonstrate how awesome it can be in F#.

In other words, let's do this.

**Comment by cartermp** [comment]
my shoe ---> my mouth

Let's not do this. We really shouldn't be in the business of changing up core VS UX, even if it's not the best.
