### ISSUE TITLE
Project's direct dependencies missing from dependency graph.

### ISSUE THREAD

**Issue by majocha** [dotnet/fsharp#2902]
For example here FSharp.Editor references LanguageService.Compiler, yet it is not reflected in Roslyn's dependency graph, causing #2895

![dependentprojs](https://cloud.githubusercontent.com/assets/1760221/25303636/8cc56932-2757-11e7-840f-8db8c17d55c9.gif)

**Comment by saul** [comment]
GetDependentProjectIds will return the list of projects that depend on you, won't it? I'm not too familiar with Roslyn APIs, but is there not a GetDependencyProjectIds?

**Comment by majocha** [comment]
Yes, that's the idea. It definitely worked before.

**Comment by majocha** [comment]
`GetDependencyProjectIds` apparently is our own extension wrapping DependencyProjectGraph.

**Comment by cartermp** [comment]
Could this have also affected being able to click in QuickInfo to Go to Def on something in another project?  Noticing that on the nightly from Thursday night, this didn't work for a function defined in a module (though I could f12 to go to definition on it just fine).

**Comment by dsyme** [comment]
@majocha Can we close this?

**Comment by majocha** [comment]
@dsyme the issue is still there, affecting F12 goto definition in some situtations.

**Comment by dsyme** [comment]
@majocha Is this a regression, and is it severe? Feels like relatively low-priority?  thanks

**Comment by majocha** [comment]
A recent regression. I don't think Roslyn's dependency graph is in use anywhere but the navigation service at the moment. Not a show stopper.

**Comment by dsyme** [comment]
I'm closing this very old issue. @TIHan did a lot of work here, it may have solved the issue in any case
