### ISSUE TITLE
Better assertion dialogs

### ISSUE THREAD

**Issue by saul** [dotnet/fsharp#2933]
This is more of a discussion for better assertion dialogs, as I find the ones at the minute very difficult to read and have a poor user experience overall. How do people think that we can make the current one better?

As an experiment I've redesigned the assertion dialog to use the [Task Dialog](https://msdn.microsoft.com/en-us/library/windows/desktop/bb760441(v=vs.85).aspx) that is available in Windows Vista and later: 

![image](https://cloud.githubusercontent.com/assets/64654/25457367/f51e0236-2acd-11e7-86b5-21d528ff37d3.png)

The above is a screenshot raised from the following code:

```c#
Debug.Assert(false, "Example failure here", "Some extra information that I added");
```

The dialog works by disabling [DefaultTraceListener](https://msdn.microsoft.com/en-us/library/system.diagnostics.defaulttracelistener(v=vs.110).aspx)'s AssertUiEnabled property, and then registering its own trace listener that displays the improved assertion dialog.

I'm not sure whether we would be happy to have this in the VF# repo, hence me raising an issue before I go through the effort of merging it in 😄

**Comment by vasily-kirichenko** [comment]
It's pretty for sure, but, as most assertions in this repository does not have messages, such a dialog with a hidden stack trace would be useless most of the time. I mean you'd have to open a stack trace anyway.

**Comment by saul** [comment]
It's easy enough to make the stack trace visible by default (y)

**Comment by vasily-kirichenko** [comment]
Then no point in this change :)

**Comment by dsyme** [comment]
Is the "always ignore" just for that process instance or global?  (Either way it's valuable)

**Comment by saul** [comment]
The always ignore would just be for the process instance. I'm struggling to word it to make that clear (in a succinct way)

**Comment by smoothdeveloper** [comment]
If the stack trace in the new dialog can be copied as text, there is value in this change because right now we just copy a screenshot, which avoid any kind of search to happen.

**Comment by dsyme** [comment]
> I'm not sure whether we would be happy to have this in the VF# repo, hence me raising an issue before I go through the effort of merging it in 😄

What dependencies does it add, to which DLLs?  I'm loathe for FSharp.LanguageService.Compiler (or FSharp.Compiler or FSharp.Compiler.Service) to have any extra dependencies

**Comment by 0x53A** [comment]
@smoothdeveloper All (most) windows default dialogs can be copy-pasted by just focusing the dialog and pressing ctrl+c.

E.g.

![image](https://cloud.githubusercontent.com/assets/4236651/25498879/e07c6086-2b89-11e7-9f1d-731245b849d7.png)


------------------

This is what gets copied with ctrl+c:

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------




   at WpfApp1.MainWindow..ctor() in c:\users\lrieger\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\MainWindow.xaml.cs:line 28

   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)

   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)

   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)

   at System.Activator.CreateInstance(Type type, Boolean nonPublic)

   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)

   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)

   at System......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

----------------

Anyway, I really like the change @saul, and I think it would make sense to expand the stacktrace by default if there is no message supplied, but keep it closed if there is one. That way you can focus people on the message without being overloaded.

And I would maybe add one line explaining that the whole dialog can be copy-pasted, so they don't copy a screenshot, maybe below the github link?

**Comment by dsyme** [comment]
> @smoothdeveloper All (most) windows default dialogs can be copy-pasted by just focusing the dialog and pressing ctrl+c.


I never knew...

**Comment by rojepp** [comment]
The assert UI doesn't live here right?

**Comment by KevinRansom** [comment]
Thanks for this issue, however, it is not really a thing we control.


Kevin
