### ISSUE TITLE
Jump to next symbol usage by Ctrl+Alt+Up/Down

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#2939]
Rider

![1](https://cloud.githubusercontent.com/assets/873919/25524275/94df99e8-2c12-11e7-8946-40f21784bd53.gif)

In VS it works for symbol usages in current file (Ctrl+Shift+Up/Down).

**Comment by dsyme** [comment]
The keystrokes for this in VS is F8/Shift-F8 and they work ok
