### ISSUE TITLE
Suggestion: Improve IntelliSense responsiveness

### ISSUE THREAD

**Issue by saul** [dotnet/fsharp#2964]
I've noticed that compared to other editors, IntelliSense can be quite slow to respond. I've added some timing to various parts of ProvideCompletionsAsync and ProvideCompletionsAsyncAux. It looks like for large files, the vast majority of the time is spent in ParseAndCheckDocument and GetDeclarationListInfo. It may be useful to add some metrics to see just how long is actually spent in ParseAndCheckDocument as opposed to queuing waiting to be serviced by the reactor.

```
[F#][INFO 12:17:21 PM]  ********** COMPLETION **********
[F#][INFO 12:17:21 PM] GetTextAsync: 0 msec
[F#][INFO 12:17:21 PM] GetCompilationDefinesForEditingDocument: 0 msec
[F#][INFO 12:17:21 PM] shouldProvideCompletion: 0 msec
[F#][INFO 12:17:21 PM] TryGetOptionsForEditingDocumentOrProject: 0 msec
[F#][INFO 12:17:21 PM] GetTextVersionAsync: 0 msec
[F#][INFO 12:17:23 PM] ParseAndCheckDocument: 1829 msec
[F#][INFO 12:17:23 PM] ParseAndCheckDocument: 102 msec
[F#][INFO 12:17:23 PM] GetLinePosition etc: 0 msec
[F#][INFO 12:17:23 PM] GetPartialLongNameEx: 0 msec
[F#][INFO 12:17:24 PM] GetDeclarationListInfo: 717 msec
[F#][INFO 12:17:24 PM] More within ProvideCompletionsAsyncAux: 0 msec
[F#][INFO 12:17:24 PM] ProvideCompletionsAsyncAux: 830 msec
[F#][INFO 12:17:24 PM]  ********************************
```

Anyway I hope this can point some people more knowledgeable than me in the right direction to start making some optimisations :) As always I'm happy to help

**Comment by Huqin-China** [comment]
#2422 
the two topics are opened before,i read **autocompletionprovider** code,it's a basic now.
lonide use pattern match,c# use dozens of provider type  to help this.
i do find the same bug #2962 ,#2822

**Comment by vasily-kirichenko** [comment]
In short, we always try to get fresh file check results and wait for them for 1 second, then, if there are no results, we use cached ones. This is the behavior @dsyme proposed to avoid glitches in completion list on small files. In practice I find it annoying and I suggest to add an option to always use cached results, and make it on by default. This logic is here https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/LanguageService/FSharpCheckerExtensions.fs#L33 Maybe you can find bugs in it as well.

**Comment by vasily-kirichenko** [comment]
@saul As an experiment, try to remove waiting logic and always use cached results to see if it solves you issues with "slow intellisense".

**Comment by vasily-kirichenko** [comment]
Oh, it's 2 seconds, not one...

**Comment by saul** [comment]
@vasily-kirichenko I think it's improved... the problem is the time it takes for IntelliSense varies so wildly it's hard to say for certain.

I agree that we should have an option page checkbox "Allow stale completion results (faster but less accurate)"

**Comment by cartermp** [comment]
@saul I think that's a good idea, yes.

**Comment by moloneymb** [comment]
Hi folks, I have tested a variety of code completion delays on a number of users. A rough guideline of the results is as follows:
< 300ms -> Types are the best thing ever
300ms - 1000ms -> Types are OK
1000ms - 2000ms -> I'm vaguely aware that my life is wasting away one second at a time (general sadness inside)
> 2000ms -> I need to consider a career change / I might as well use Python (It takes me less time to google it)

In other words; if anything takes > 2 seconds you might as well not bother.

**Comment by isaacabraham** [comment]
I wasn't sure if this was just because of the size of the FSharp.Core solution (that's the only solution I dare use VS2017 on) but if this is par for the course even on smaller solutions... not great.

**Comment by dsyme** [comment]
@isaacabraham I chatted with @moloneymb and he's working in a 20,000 line file.  So size is an issue here

**Comment by realvictorprm** [comment]
@dsyme People can work with such big files? Interesting. Do we have somewhere a list containing ideas where performance can be improved in code?

**Comment by cartermp** [comment]
There's been a lot of performance work in the past year (some of it specific to completion lists), so it may be worth rebaselining performance here. The April 30th, 2017 experience (VS 15.0!) is very very different to the April 10th, 2019 experience.

**Comment by cartermp** [comment]
I think we can close this out. Sooooo many issues related to IDE perf and specific to generating a completion list have been resolved since this was filed, and things are generally in a pretty good place now.
