### ISSUE TITLE
Suggestion: pressing tab should stop at recommended indent positions

### ISSUE THREAD

**Issue by vivainio** [dotnet/fsharp#2965]
#### Repro steps

Have code:

```fsharp
[<EntryPoint>]
let main argv =
    let foo = match argv with
                
    printfn "%A" argv
    0 
```

When I press TAB on the line after 'let foo', I would want the cursor to stop at the column where "m" in match is, to start entering | _ -> blahblah at the correct position.  Instead, tabbing is "dumb" and stops at 4 char increments, ending up under "t" it "match".

**Comment by slang25** [comment]
I did a workshop on Friday and this caught many people out, I think it would make F# a better experience for beginners, as well as being just a nice feature to have (which is also true).

**Comment by saul** [comment]
Idiomatic F# is generally to put nested expressions on a new line:

```f#
[<EntryPoint>]
let main argv =
    let foo =
        match argv with
                
    printfn "%A" argv
    0 
```

I agree that this can catch many beginners out.

**Comment by dsyme** [comment]
I'm closing this because, as @saul mentions, the code is non-idiomatic in the first place and we wouldn't stop at those points
