### ISSUE TITLE
Cases where display of generic arguments in a tooltip is sub-optimal

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#2979]
I'm not sure they are particular wrong, but they don't make sense for sure

![image](https://cloud.githubusercontent.com/assets/873919/25623747/558cde6c-2f60-11e7-856b-451d4778333c.png)

**Comment by dsyme** [comment]
Yeah, they aren't wrong as such - it's a generic callsite of a generic function - but it's something to improve.  Substitution would be right here.

**Comment by dsyme** [comment]
I'll rename the bug to track cases where we need to improve

**Comment by 0x53A** [comment]
This is the only open issue for generic parameters in tooltips I found (did I miss one?), so I'll just post it here:

Using Option.ofNullable as an example, we may also want to tweak how constraints are displayed:

![image](https://cloud.githubusercontent.com/assets/4236651/25907945/2b23763c-35a9-11e7-881f-674fdbfaaf52.png)

I think as it currently stands, it is a bit confusing.

* One option would be to just drop them completely.
* Another option (currently my favorite) would be to move the constraints to the bottom:
![image](https://cloud.githubusercontent.com/assets/4236651/25908157/ba3ea0da-35a9-11e7-9442-f19e85637311.png)
Line-breaks may be inserted as-appropiate
* Or it could be kept as-is

What do you think?

**Comment by smoothdeveloper** [comment]
@0x53A I'm +1 with your favorite option, listing constraints where we list the generic parameters

maybe in this order instead:

> 'T is nativeint (requires default constructor and value type and 'T :> ValueType ...)

**Comment by dsyme** [comment]
In this case we should just substitute and show ``ofNullable : value:Nullable<nativeint> -> nativeint`` and nothing else.  

There is no reason to show the constraint if it is known to be satisfied in this instance.

**Comment by 0x53A** [comment]
When would you show the constraints? Only when mousing over signature / implementation? Never?

I agree that it is kind of superfluous in this case when looking at complete code, but I'm wondering how that would work during development.

E.g. I type ``Option.ofNullable`` somewhere and mouse over it. Would it show the constraint if it is in error mode? Would it show the constraint if it infers any random type?

For example

```
let f x =
    Option.ofNullable|
                     ^cursor
```
that code is currently valid (but probably not what I want). Would it show the constraints here? I would like to see them, so i know what I need to type next.

So even if it is just for consistency, i vote to always show the constraints.
