### ISSUE TITLE
Suggestion: Improve formatting of signatures in tooltips

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#2998]
I.e. each parameter is placed on each own line.

![image](https://cloud.githubusercontent.com/assets/873919/25779811/89dc3a3a-3327-11e7-9b04-f6201b73ae43.png)

**Comment by majocha** [comment]
Also, docs wrapped to sensible width instead of the abomination that Visual Studio sometimes shows.

**Comment by vasily-kirichenko** [comment]
The problem is that such formatting is possible with monospace fonts only, which are very rarely used by VS users.

**Comment by majocha** [comment]
Hmm... Since we already almost completely implement our own tooltips there should be no obstacle to just make the "code" use editor font and the docs use "tooltip font".

**Comment by vasily-kirichenko** [comment]
This would be totally awesome. I thought about it the other day and forgot to suggest.

**Comment by cartermp** [comment]
Another thing Xamarin does which I like (not sure if you were also looking at this) is they don't list members:

<img width="378" alt="screen shot 2017-05-07 at 8 22 51 am" src="https://cloud.githubusercontent.com/assets/6309070/25782366/773b4c3c-32fe-11e7-9db7-a8bb78de35d0.png">

I quite like that.  The logic about what XML docs to include also works much nicer for things like Deedle.  VS:

<img width="1680" alt="screen shot 2017-05-07 at 8 29 05 am" src="https://cloud.githubusercontent.com/assets/6309070/25782401/6944de76-32ff-11e7-890f-4fdacd559153.png">

VsfM:

<img width="989" alt="screen shot 2017-05-07 at 8 29 16 am" src="https://cloud.githubusercontent.com/assets/6309070/25782404/74647e42-32ff-11e7-8596-ec874cf69267.png">

**Comment by realvictorprm** [comment]
Thanks @vasily-kirichenko I think totally the same.
Any plans on implementation?

**Comment by majocha** [comment]
I can help with the rendering part. But most of the formatting work probably requires digging into niceprint.fs and so on, which is quite scary to me.

**Comment by majocha** [comment]
When everything not tagged as text gets editor font:
<img width="473" alt="editorfont 0" src="https://cloud.githubusercontent.com/assets/1760221/25807184/350d30ba-3406-11e7-8b91-a2b5f753b3fa.png">

**Comment by vasily-kirichenko** [comment]
@majocha is it possible to make the font smaller?

**Comment by majocha** [comment]
@vasily-kirichenko Yes, we can set the fontsize independently. Striking a usable balance might be tricky.

![tooltip](https://cloud.githubusercontent.com/assets/1760221/25809576/b2b508a6-340d-11e7-9f84-04ce853a35bb.gif)

**Comment by realvictorprm** [comment]
I can help with the rendering stuff too :wink:

Am 08.05.2017 3:52 PM schrieb "Jakub Majocha" <notifications@github.com>:

**Comment by vasily-kirichenko** [comment]
@nosami could you point us at the sources where tooltip formatting is implemented? I've always lost in MD/Xamarin repositories and directory structures.

**Comment by vasily-kirichenko** [comment]
They implemented the nice print logic from scratch in MD, see https://github.com/fsharp/xamarin-monodevelop-fsharp-addin/blob/c3b2632255d295da31856648d123f9f7a06eb6ba/MonoDevelop.FSharpBinding/FSharpSymbolHelper.fs#L361. The problem is that it outputs text, not structured text. If we are going to use it, we need to adjust it so that it outputs structured text of some format. I also don't think it's OK to have two implementations of such logic: sformat.fs + NicePrint.fs and this new stuff.

**Comment by nosami** [comment]
Yeah, you found it. It starts from here https://github.com/mono/monodevelop/blob/91d908d727cb60664e9f4b3b71f5a8b1e6c8cf76/main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpSymbolHelper.fs#L817

**Comment by vasily-kirichenko** [comment]
@nosami thanks anyway :)

**Comment by vasily-kirichenko** [comment]
@realvictorprm we need a hero who can port ^^^ and make it output structured text (for coloring) :)

**Comment by realvictorprm** [comment]
@vasily-kirichenko We need a hero who explains Xamarin to _not_ do everything on their own :smile:
I'm voting for integrating this stuff so it can be used by everyone. Would that be possible?

**Comment by nosami** [comment]
> We need a hero who explains Xamarin to not do everything on their own

Easier said than done :)

**Comment by vasily-kirichenko** [comment]
That code is isolated and operates on TAST, so you can port it as is to FSC project, making it available to everyone, and just call it from quick info provider to get not colored tooltips. That's the easy part. The hard part is to change it so that it produces structured output, like niceprint.fs does.

**Comment by dsyme** [comment]
Reopening as this is the canonical issue for this feature request right now
