### ISSUE TITLE
Diagnostic shows in VS IDE for multi-project solution after error recovery

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#3048]
An unlinked type variable seems to cause a NRE across a multi-project solution. This manifests as an NRE, though the problem is actually that a type variable hasn't been "relinked" properly across multiple projects, stemming from this:

          typar_constraints = Unchecked.defaultof<_>

#### Repro steps

Provide the steps required to reproduce the problem

1. Open ``tests\projects\misc\TestProjectChanges\TestProjectChanges.sln``

2. Open "Program.fs" and "Library1\Class1.fs"

3. Change 

        static member PropertyAvailableInProject1DebugConfiguration = "F#"

to

        static member PropertyAvailableInProject1DebugConfiguration = "F#" + 1.0

2. Save the file, then wait a while for the IDE errors to update, and you will see this

![image](https://cloud.githubusercontent.com/assets/7204669/26024834/4d9e5378-37d2-11e7-849d-cbab21b1f626.png)

#### Expected behavior

No extra error "Object reference not eset" shown

#### Actual behavior

NRE extra error shown

#### Known workarounds

The error is not serious, it can be ignored.  It will disappear once you fix your other errors

**Comment by cartermp** [comment]
@dsyme do you still see this?

**Comment by dsyme** [comment]
I'm closing this, it's never been seen again
