### ISSUE TITLE
Add support for acquiring complete declaration location from compiler service

### ISSUE THREAD

**Issue by realvictorprm** [dotnet/fsharp#3104]
For CodeLens I need the start and end of a declaration to retrieve the complete source text. Currently the implementation provides only the location of the binding / variable / member name.
E.g.:
`let a = 0`
If I call on this symbol `func.DeclararionLocation` I'll get the position of the name (so `a`)

What I need is the complete location including everything else too (so `let a = 0`)

PS:
Of course I'm not sure whether it's worth to implement this in the compiler service but I currently see no other way to get my caching system for CodeLens working .

**Comment by dsyme** [comment]
@realvictorprm We tend to track FCS issues in http://github.com/fsharp/FSHarp.Compiler.Service, partly because they clutter this repo, and partly because the docs etc. are still generated from that repo using it as a "packaging repo".

**Comment by realvictorprm** [comment]
I'm sorry, I didn't know that 😞 
So, should I open an issue there too @dsyme ?

**Comment by realvictorprm** [comment]
Nevertheless @dsyme I know its currently not important but its still blocking my work. Please, any suggestions on where I should start would be enough.

**Comment by dsyme** [comment]
> So, should I open an issue there too @dsyme ?

Yes please.

I suppose the complete definition location is available in the syntactic AST (not the symbols). Currently there's no way to get back to the AST declaration however

**Comment by vasily-kirichenko** [comment]
@realvictorprm nav bar uses this function https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/ServiceNavigation.fs#L442 to get a file declarations' signature and body ranges, it may by useful for you.

**Comment by realvictorprm** [comment]
Thank you very much both @dsyme and @vasily-kirichenko
