### ISSUE TITLE
F# and honoring required modifiers?

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/fsharp#3105]
For the upcoming C# feature **readonly references** ([more details](github.com/dotnet/csharplang/blob/master/proposals/readonly-ref.md)), it will give the user to define readonly reference parameters and return types. Example:

```csharp
public class X
{
    public virtual void M(ref readonly int p)
    {
        // Console.WriteLine(p);
    }
}
```

The plan was to poison other compilers like F# and VB (and older versions of C# as well) using required modifiers (`modreq`s in .NET specs) with the type `System.Runtime.CompilerServices.IsConst`, and only for functions that can be overridden in other assemblies.

So for example, if you want to define your own `XChild` and your own implementation of method `M()`, the compiler you're using has to understand that modreq, and subsequently, the feature, and how to enforce the same semantics. If the compiler does not understand the modifier, it should produce an error when trying to reference/overload it.

Attached is a temp assembly that I compiled with the above code. [repro.zip](https://github.com/Microsoft/visualfsharp/files/1020417/repro.zip)
I tried testing the above scenario by creating an F# console application with the below code:

```fs
[<EntryPoint>]
let main argv = 
    let o = new X()
    o.Y(ref 5)
    0 // return an integer exit code
```

And it compiles and runs fine. Is there something I'm missing? or F# does not honor required modifiers?

@dsyme @KevinRansom @brettfo

**Comment by OmarTawfik** [comment]
@dsyme any updates on this? Do we have a target release?
cc @vsadov @jaredpar

**Comment by dsyme** [comment]
@OmarTawfik No, no target release AFAIK.  An RFC and PR would be welcome of course.

**Comment by dsyme** [comment]
Support for `in` parameters has been added quite a long time back
