### ISSUE TITLE
Delegate declarations inherit the bold property from F# Functions/Methods

### ISSUE THREAD

**Issue by asik** [dotnet/fsharp#3111]
EDIT: I ended up writing several bugs with delegate coloring and tooltips here, let me know if this should be split in multiple issues.

**Issue 1**
In Options -> Fonts and Colors, I have "F# Functions/Methods" set to use Bold:
![image](https://cloud.githubusercontent.com/assets/1631157/26417752/1115198c-4088-11e7-8fc4-18a903e04051.png)

When declaring a delegate, part of the declaration seems to inherit that setting:
![image](https://cloud.githubusercontent.com/assets/1631157/26417787/25e7254e-4088-11e7-9b3a-a5eaddb84ae7.png)

Here `delegate of string` is displayed in a bold font for no apparent reason. If I uncheck the bold option for F# Functions/Methods, it is displayed normally.

**Issue 2**
In addition, the type definition uses the color from "User Types - Classes" rather than "User Types - Delegates".

**Issue 3**
In addition, delegates have no coloring at the point of use:
![image](https://cloud.githubusercontent.com/assets/1631157/26417979/a83410d4-4088-11e7-9898-9043bab581a3.png)
They should use the color defined by "User Types - Delegates".

**Issue 4**
In addition, their tooltips are poor and not consistent with tooltips for most types:
![image](https://cloud.githubusercontent.com/assets/1631157/26418176/4096cd8a-4089-11e7-886a-479fbb6d52d1.png)

**Comment by cartermp** [comment]
Issues 2 and 3 will be resolved with https://github.com/dotnet/fsharp/pull/9511

They are colored at use:

![image](https://user-images.githubusercontent.com/6309070/85188368-c3ccc880-b25a-11ea-9d40-e92d58a4c01f.png)

They are also classified as delegates properly in that PR.

However, the tooltips and funkiness with parts of the delegate getting classified incorrectly (e.g., `string` should be teal-colored) are unresolved with that PR
