### ISSUE TITLE
FSC should ignore error diagnostic identifiers that it does not understand.

### ISSUE THREAD

**Issue by livarcocc** [dotnet/fsharp#3207]
This came up in this PR for the .NET SDK: https://github.com/dotnet/sdk/pull/1329.

Specifically: https://github.com/dotnet/sdk/pull/1329/files#diff-7eff410a9a7fafbb40f5405239e45623R106.

We are making NU1605 a default WarningAsError and this fails in F#, because the compiler does not understand the identifier and breaks. Roslyn simply ignores these unknown identifiers. So I am asking for parity here.

**Comment by realvictorprm** [comment]
I'm not sure whether this is fine with the specification. 
CC @cartermp @donsyme

**Comment by cartermp** [comment]
cc @dsyme I don't know what the ramifications of this could be.

**Comment by dsyme** [comment]
@livarcocc If you'd like this behavior implemented, please submit a PR for it, thanks

**Comment by dsyme** [comment]
I have no real sense if this change is a good idea - if Roslyn ignores the IDs then I'd be OK with it, after review by Roslyn team members.

**Comment by maximpashuk** [comment]
@brettfo @dsyme   I think this issue closed by mistake.
In commit https://github.com/brettfo/sdk/commit/f90e51541d9b35c0f723194991260abc7eab13ea message said 'unitill F# fixes' this issue.

But GitHub engine decided that 'fixes' word in that commit actually fixes this issue, not F# team.
So this issue get closed, and this is mistake I think.

So I think this issue should be reopened

**Comment by dsyme** [comment]
This issue is really old and the behaviour seems dubious to add to F#.

**Comment by baronfel** [comment]
@dsyme looking at this again, I think the F# compiler should be resilient to unknown warnings, since MSBuild/NuGet/arbitrary task authors can create error codes and all of those feed into WarningsAsErrors from a user perspective.

**Comment by dsyme** [comment]
> @dsyme looking at this again, I think the F# compiler should be resilient to unknown warnings, since MSBuild/NuGet/arbitrary task authors can create error codes and all of those feed into WarningsAsErrors from a user perspective.

I don't really know how to do this without having detailed repros.  The F# compiler is out of the business of using MSBuild directly - there are some legacy paths . F# Interactive does use MSBuild directly (via a `dotnet` invocation) but I don't think that would be covered automatically by any simple fix.

**Comment by baronfel** [comment]
Here's an example of where it would be useful if this was implemented: https://github.com/dotnet/sdk/pull/26559

**Comment by AppFzx** [comment]
Now that this is "completed", does that mean [this line can go away](https://github.com/dotnet/sdk/blob/cd25d6bbfc2aac61cc790c511900427ac64fdaa8/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.CSharp.props#L20) which is the cause of several issues like https://github.com/NuGet/Home/issues/6141, https://github.com/dotnet/sdk/issues/1913, etc.

... or do you think this should be opened back up? @dsyme

**Comment by codingdave** [comment]
Should the note in [Microsoft.NET.Sdk.CSharp.props](https://source.dot.net/#MSBuildFiles/C/hostedtoolcache/windows/dotnet/sdk/6.0.302/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.CSharp.props,cc2e62edb89ad164) get removed or updated if the case is closed?

` <!-- Remove the line below once https://github.com/Microsoft/visualfsharp/issues/3207 gets fixed -->`
`    <[WarningsAsErrors](https://source.dot.net/MSBuildProperties/R/WarningsAsErrors.html)>$([WarningsAsErrors](https://source.dot.net/MSBuildProperties/R/WarningsAsErrors.html));NU1605</WarningsAsErrors>`

**Comment by Mertsch** [comment]
https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.CSharp.props still contains this weird error which makes CPM annoying to work with!

Please remove this warning as error!

**Comment by baronfel** [comment]
I'm reopening this as it's the cause of many issues still. If the F# compiler itself doesn't want to parse the warning codes, the `Fsc` MSBuild Task should be updated to filter out entries that the compiler doesn't natively understand.  I _do_ think the compiler itself needs to learn to ignore diagnostic codes that do not apply to it _in general_ because if/when analyzers are implemented they will create diagnostics with non-`FS`-prefixed codes that will need to be managed by `NoWarn` and similar MSBuild mechanisms.
