### ISSUE TITLE
[design-time only] Assembly reference was not found or is invalid

### ISSUE THREAD

**Issue by 0x53A** [dotnet/fsharp#3221]
This is only an issue at design time, build is ok.

![image](https://user-images.githubusercontent.com/4236651/27299225-ef92d994-552b-11e7-8a58-42c6987ef3aa.png)

The file exists on disk, and was built by a different (C#) project in the same solution.

![image](https://user-images.githubusercontent.com/4236651/27299271-1768a6a6-552c-11e7-9d51-5f9face2a3a2.png)

![image](https://user-images.githubusercontent.com/4236651/27299293-296232f0-552c-11e7-968c-d8d6ae6c58c9.png)

**Comment by dsyme** [comment]
@0x53A We'll need a step-by-step repro for this.  Does rebuilding the project succeed?  

It could also be a manifestation of https://github.com/Microsoft/visualfsharp/issues/3047

**Comment by 0x53A** [comment]
@dsyme Yeah, thats the great thing about this and https://github.com/Microsoft/visualfsharp/issues/3054#issuecomment-302085371, it's not reproducible in a small isolated project.

Build and Rebuild work fine, but do not clear the error.

**Comment by 0x53A** [comment]
I have this and https://github.com/Microsoft/visualfsharp/issues/3054#issuecomment-302085371 in a base-lib which depends on 5 other projects. If I remove everything except these five projects from the solution, then the error stops happening, even though there _should_ be no change from the view of these projects.

For me it looks like something completely unrelated in the solution fucks VS up.

The whole solution has ~60 projects, so I'm not going to try all permutations and check which of these causes this.

For now I'm dropping VS and using Rider, not because of this bug, but because of https://github.com/Microsoft/visualfsharp/issues/3054#issuecomment-302085371, which now happens always.

**Comment by dsyme** [comment]
> Build and Rebuild work fine, but do not clear the error.

Did you check if switching between "Build" and "Build + Intellisense" clears the error?

Re [#3054 (comment)(https://github.com/Microsoft/visualfsharp/issues/3054#issuecomment-302085371) it feels likes this should be tracked by a separate bug.

**Comment by 0x53A** [comment]
> Did you check if switching between "Build" and "Build + Intellisense" clears the error?

Yes and No. It is visible in the "Error List" for either "Intellisense Only" or "Build+IntelliSense", but is always visible as a red squiggle in the document at location (0,0). Switching does not affect the squiggle in the document.

-----

My previous remark

> The file exists on disk, and was built by a different (C#) project in the same solution.

is not completely true: when VS was started, the file did not yet exist (if the solution was built before opening, I hit https://github.com/Microsoft/visualfsharp/issues/3222), but building the project does not clear the squiggle.

**Comment by plainionist** [comment]
hi,

seems I have similar (same?) use with my project here: https://github.com/plainionist/Plainion.Windows revision 0af9a48.
i tried endless things of clean + rebuild, changing .net version, updating fsharp.core .... the only "workaround" which i was able to apply successfully after several reopens of VS was to unload the fsharp project again and reload it after 2-4 seconds. (i have only one fsharp project among 3 c# ones).

hope that helps ...

regards,
seb

**Comment by dsyme** [comment]
@plainionist OK, thanks, we will try your repro

**Comment by 0x53A** [comment]
Now it repros reliably:

--------------



#### Repro steps


[Solution1.zip](https://github.com/Microsoft/visualfsharp/files/1243207/Solution1.zip)

* Load the solution. It contains one F# lib that references a C# lib. (this repros with any project for me, just create two new libs)
* Open Library1.fs

![image](https://user-images.githubusercontent.com/4236651/29584599-98399594-8784-11e7-9e74-e1c2ea6f9df5.png)

* Build the solution
* Still the same error
* Restart VS
* Everything OK
* Clean Solution
* Restart VS
* Same Error


Note: I think you always needed to build the C# project before F# recognized it, but it should not require a reload of the solution.

#### Known workarounds

Build + Restart VS (or just reload the F# project)

#### Related information 

Provide any related information 

* Operating system: Win10
![image](https://user-images.githubusercontent.com/4236651/29584709-e044d268-8784-11e7-8843-279c9c42d529.png)
![image](https://user-images.githubusercontent.com/4236651/29584723-f0ea1dda-8784-11e7-8143-281ede9cecd7.png)

**Comment by jzabroski** [comment]
I'm running into this error today.  Fun!

What's strange is it worked fine, until I added an override ToString() in a very large, messy F# project in order to step through a strange floating point error more easily.

Can we please add more color in this error message on WHETHER it was (a) not found; (b) invalid

I am not asking for a fix.  I am asking for improved sanity checking.  Problems like these are exactly what prevent me from pushing to use F# more at work.  I just lost 2 hours of time for no good reason.

**Comment by jzabroski** [comment]
Here are several theories as to how this can happen - sorry - not going to spend time repro'ing, just thinking out loud what could have gone wrong today in case anyone else is annoyed as I am today:

1. During debugging, if you expand too many Quick Watch statements, something goes horribly wrong in F# engine, which in turn causes cataclysmic compile errors
2. Referencing a c# static class with a namespace a level deeper than the assembly's root namespace

**Comment by jzabroski** [comment]
Closing the solution in VisualStudio (without closing VisualStudio) appears to fix the problem.

**Comment by jzabroski** [comment]
@dsyme I suggest the simplest way to try to repro this problem is to load a "toxic alpha" verison of F# Plug-in into Visual Studio that crashes on any function named jzabroski (or similar).   I think this will demonstrate the design-time only aspect of this bug.

**Comment by jzabroski** [comment]
I think I put together exactly what happens in my case.

1. I'm right - Quick Watch can cause an unhandled exception, which appears to leave the F# engine in an unknown state
2. I'm also right - when the engine is in an unknown state, the F# <-> C# bridge tooling seems to die, causing compile errors to appear around F# code calling c# code, especially if the c# code is a static class

**Comment by jzabroski** [comment]
@cartermp As per discussion on Twitter, just beeping a horn.  Please don't add me to github-drama :)

**Comment by cartermp** [comment]
@jzabroski Thanks, I think there are two or more separate issues based on what you're describing.

**Comment by cartermp** [comment]
Just to clarify, are these valid for VS 2019 Update 16.4.?

**Comment by jzabroski** [comment]
Most likely.  Definitely for 16.3.8 (I think) - I try not to touch the F# project as its a time sink.  FWIW, These "basic compilation doesn't work smoothly" issues have only gotten worse and worse over time.  It used to be the thing that would piss off my engineers is that the bootstrap of the FSharp.Core.dll and Tools from C# would cause weird nuget restore errors.  Then it precipitated into random runtime crashes while debugging.

I'm not an F# expert, but I also noticed other weird things with F# IntelliSense that I could not understand based on the documentation.  In particular, sometimes the tooltip that displays type inference would change the order of the expression.  Maybe that's an expected behavior, but it went away when I added type annotations.

**Comment by jzabroski** [comment]
@cartermp Also verified I am not utilizing Resharper's Build Speed-up tool (I only use its refactoring engine).

![image](https://user-images.githubusercontent.com/447485/71284764-7d40f480-2331-11ea-8a89-a1e32e2c2071.png)

**Comment by jzabroski** [comment]
I did some tests for you - it does seem a bit more stable.  Can I ask if you have any regression tests against things like referencing a c# static class _in the same project_  (not a nuget package).

```c#
namespace CSharp.FooBarProject.Legacy.CustomEntities
{
  public class FooBarMetadata
  {
    public int Id {get;set;}
  }
}
```

```f#
open CSharp.FooBarProject.Legacy.CustomEntities

let GetRatioNonStandardlyFooBarsUpdateFun (nonStandardlyFooBars : NonStandardlyFooBar list) 
                                               (clientSpecificFooBarRatios : ClientSpecificFooBarRatio list)
                                               (fooBarMetadata : CSharp.FooBarProject.Legacy.CustomEntities.FooBarMetadata) // this would cause problems, especially if referenced without fully qualified namespace+class
                                               (defaultPercent : float)
                                               (fooBarTypes : NonStandardFooBarType list)
                                               (executionContext : ExecutionContext) =
```
