### ISSUE TITLE
Incorrect pattern matching exhaustiveness warning when using :: and the & operators

### ISSUE THREAD

**Issue by mrakgr** [dotnet/fsharp#3294]
```
let f = function
    | [] -> 0
    | (_ :: _) & _ -> 0

Script1.fsx(1,9): warning FS0025: Incomplete pattern matches on this expression. For example, the value '[]' may indicate a case not covered by the pattern(s).
```

In VS2015 this gives me the above warning. As would be expected running the above with [] returns 0. It also gives the same warning when the last case is written out as `_ :: (_ :: _)`. When `&` is replaced by `as` in the above code fragment the warning disappears.

**Comment by forki** [comment]
Failing test in https://github.com/Microsoft/visualfsharp/pull/3378

**Comment by edgarfgp** [comment]
This seems to be fixed by https://github.com/dotnet/fsharp/pull/13020 ?

**Comment by vzarytovskii** [comment]
Yes, should be fixed, closing it for now.
