### ISSUE TITLE
Last assignment in file does not show up in watch list when debugging

### ISSUE THREAD

**Issue by atlemann** [dotnet/fsharp#3305]
When debugging an F# project in VSCode, the last assignment is not shown in the watch list

#### Repro steps
Create a .net core F# project with the following content. Open in VSCode, set the breakpoint on the last line and start debugging.

```
let add1 x = x + 1

[<EntryPoint>]
let main argv =
    let one = add1 42
    let two = add1 42 // two does not appear in watch list
    0 // <-- Set breakpoint here

```

#### Expected behavior

Value 'two' to appear in watch list

#### Actual behavior

Value 'two' does not appear in watch list or when you hover over with the mouse

#### Known workarounds

None

#### Related information 
* Operating system: Windows
* CoreCLR, dotnet 1.0.4
* Editing Tools: VSCode

**Comment by cartermp** [comment]
This no longer repros.

Tooltip:

![image](https://user-images.githubusercontent.com/6309070/110720136-efb22480-81c2-11eb-96d5-e0b007d7ab83.png)

Locals:

![image](https://user-images.githubusercontent.com/6309070/110720155-f6409c00-81c2-11eb-837b-e6c16736eda2.png)

Watch window:

![image](https://user-images.githubusercontent.com/6309070/110720177-fccf1380-81c2-11eb-852f-190cbd8349c3.png)
