### ISSUE TITLE
"Find All References" doesn't show unsaved references

### ISSUE THREAD

**Issue by mattmccutchen-microsoft** [dotnet/fsharp#3308]
"Find All References" doesn't seem to show references that have been added to an open file but not saved.  This is inconsistent with the behavior for C#, which is to show references based on the latest available version of each file (the editor content if the file is open, otherwise the content on disk).  Is this expected?

#### Repro steps

1. Create a new F# library and add the following code to the file, but do not save:
```fsharp
type A = int
type B = A
```

2. Right-click the first `A` and choose "Find All References".

#### Expected behavior

The reference from `type B = A` is shown.

#### Actual behavior

"No references found to 'A'".

#### Known workarounds

Save all files.

#### Related information 

Nightly Visual F# Tools 15.4.1.17070403

```
Microsoft Visual Studio Enterprise 2017 
Version 15.2 (26430.14) Release
VisualStudio.15.Release/15.2.0+26430.14
Microsoft .NET Framework
Version 4.7.02046
```

**Comment by cartermp** [comment]
This is expected, unfortunately.  FCS requires the files to be saved on disk.

**Comment by vasily-kirichenko** [comment]
It should work on private symbols where we use file check results, for example it should work on function arguments and local values and functions.

**Comment by mattmccutchen-microsoft** [comment]
I guess an option would be to prompt the user, "Added references in unsaved files will not be found.  Do you want to save all files first?" with a "Remember my decision".  Do we think that when there are unsaved files, a high enough percentage of "Find All References" requests relate to unsaved references that a prompt would be worthwhile?  I hit this many times over the past few days and decided "Find All References" was unreliable and fell back to a text search, until today when I decided to investigate and file an issue.

**Comment by 0101** [comment]
This has an opt-in fix available: https://github.com/dotnet/fsharp/issues/14033#issuecomment-1408884841
