### ISSUE TITLE
Test failing in localized environment

### ISSUE THREAD

**Issue by ForNeVeR** [dotnet/fsharp#3363]
When compiling and running the tests from this repo, I get one test failure.

#### Repro steps

```console
$ git clone https://github.com/Microsoft/visualfsharp.git
$ cd visualfsharp
$ ./build.cmd debug
$ ./build.cmd test
Errors and Failures

1) Failed : FSharp-Tests-Core+CoreTests.signedtest-17
'test-sha1024-public-cl.sn.out' and 'test-sha1024-public-cl.bsl' differ; "diff between [visualfsharp\tests\fsharp\core\signedtests\test-sha1024-public-cl.bsl] and [visualfsharp\tests\fsharp\core\signedtests\test-sha1024-public-cl.sn.out]
line 4
 - Failed to verify assembly -- Strong name validation failed.
 + Failed to verify assembly -- Сбой при проверке правильности строгого имени.
"
at FSharp-Tests-Core.CoreTests.signedtest(String args, String bslfile) at visualfsharp\tests\fsharp\tests.fs:строка 588

Run Settings
    RuntimeFramework: V4.0
    WorkDirectory: visualfsharp\release\net40\bin
    Verbose: True
    NumberOfTestWorkers: 8

Test Run Summary
    Overall result: Failed
   Tests run: 342, Passed: 341, Errors: 0, Failures: 1, Inconclusive: 0
     Not run: 3, Invalid: 0, Ignored: 3, Explicit: 0, Skipped: 0
  Start time: 2017-07-23 07:35:17Z
    End time: 2017-07-23 07:57:22Z
    Duration: 1324.939 seconds
```

"Сбой при проверке правильности строгого имени" means the same as "Strong name validation failed" but in Russian. It seems like the test have some problems with my OS localization?

#### Expected behavior

Tests should execute without errors no matter what OS localization I have installed.

#### Actual behavior

Tests are consistently failing.

#### Known workarounds

😄 Reinstall Windows and use English localization?

#### Related information 

Provide any related information 

* **Operating system**: Windows 10, Russian
* **Branch**: `master`
* **.NET Runtime, CoreCLR or Mono Version**: net40 (the default)
* **Indications of severity**: minor

**Comment by ForNeVeR** [comment]
Per https://github.com/Microsoft/visualfsharp/issues/4242#issuecomment-359881568: seems that we may use `--preferreduilang:us-EN` to fix that?

**Comment by dsyme** [comment]
Closing this old issue
