### ISSUE TITLE
LanguageService tries to register project twice

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#3364]
1. Open Roslin solution in 15.3
2. F5
3. Open a solution containing a F# project

![image](https://user-images.githubusercontent.com/873919/28498722-d3a2fd90-6fac-11e7-812b-30a5db612617.png)

**Comment by Pilchie** [comment]
Tagging @KevinRansom

**Comment by dsyme** [comment]
It's plausible this is a bug where the F# and C# project systems are both registering the project?

**Comment by vasily-kirichenko** [comment]
It seems "Urgency-Now" is passed several months ago, I'm closing it.

**Comment by dsyme** [comment]
I don't know what this was but it's ancient and hasn't been seen since
