### ISSUE TITLE
Find All References returns nothing for `None` in VFT solution

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#3372]
Execute "Find all references" on `None` symbol anywhere in FSharp.Compiler.Private project:

![image](https://user-images.githubusercontent.com/873919/28537283-f977772e-70b2-11e7-803d-638a7378e100.png)

**Comment by vasily-kirichenko** [comment]
#3387 _has not_ fixed this bug.

**Comment by KevinRansom** [comment]
@dsyme Just revert the change then mate, sorry.

**Comment by cartermp** [comment]
This no longer reproduces:

![image](https://user-images.githubusercontent.com/6309070/90078438-c4616880-dcb9-11ea-96d7-301a9b9403c6.png)

However, the navigation often takes you to a garbage location, e.g. the first item in this list takes you to some random union case in a type definition. Still a bug here, just not the one that's reported.
