### ISSUE TITLE
Dialog for Editor performance options needs improvements

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#3400]
Currently it looks like:

![image](https://user-images.githubusercontent.com/5175830/28693999-47e9d610-72dc-11e7-8866-e23583f36c32.png)

1. Labels appear on left and right for different options., perhaps labels on left, user values on right.  With improved alignment.
2. Text for Project check cache size, might be technically correct but doesn't really say enough.

@brettfo, @cartermp, @dsyme 

Suggestions?

Kevin

**Comment by cartermp** [comment]
This was improved by adding descriptions to the options.
