### ISSUE TITLE
Underscores or special names with backticks are problematic with auto-completion

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#3406]
When you have a name of an identifier, field etc that has an underscore in it, auto-completion does not work as expected:

![xanbdgvbeq](https://user-images.githubusercontent.com/16015770/28757502-e08bf65a-7584-11e7-8841-79088f2db2e8.gif)

Special names (or whatever the term is for escaped names like these):

![t9lnaddbph](https://user-images.githubusercontent.com/16015770/28757541-bcd01c68-7585-11e7-9d30-977c143b600f.gif)

Names in backticks are especially useful when writing unit tests, and auto-complete can help tremendously with those readable, but awkward-to-type descriptive test-case names.

### Repro steps

1. Have an identifier with an underscore (fieldname, class name, let binding etc)
2. Start typing until after the underscore, and hit Ctrl-space
3. Instead of automatic completion, you will get a dropdown list of one item
4. Selecting it will add it to the already typed partial name, instead of completing it.

Similar things happen with escaped names, the backticks are sometimes even doubled.

### Expected behavior

Whether or not there's an underscore in the name, auto-completion should work the same way.

### Actual behavior

As described above and in the vidcap. Ctrl-space doesn't work properly when names have underscores in them or when they are specially escaped with double backticks.

### Known workarounds

None. Or don't use autocomplete when names are created with backticks, or have underscores.

### Related information 

* Visual Studio 2017 any version (VS2015 wasn't much better though)
* F# 4.4.0.0 and F# 4.4.1.0 (didn't check older versions)
* any runtime or Core

**Comment by dsyme** [comment]
@abelbraaksma Thanks for the bug report!

**Comment by ricksladkey** [comment]
A specific case of this general bug report occurs for identifiers that begin with an underscore and contain no further underscores. In that case, typing the initial underscore with brings up a very long list of seemingly every function available:

![image](https://user-images.githubusercontent.com/2680524/42013195-292bedc6-7a6a-11e8-9dc9-aadec0d5fa74.png)

Typing further characters of the identifier does eventually find it:

![image](https://user-images.githubusercontent.com/2680524/42013114-b3520b1c-7a69-11e8-9f80-5db6b77dfa18.png)

but hitting `<Tab>` replaces the characters typed so far and appends an extra leading underscore:

![image](https://user-images.githubusercontent.com/2680524/42013150-e1734fb0-7a69-11e8-877e-76358cc5deb5.png)

**Comment by cartermp** [comment]
This should be addressed by https://github.com/dotnet/fsharp/pull/10500

**Comment by abelbraaksma** [comment]
Wonderful work, thanks!!!
