### ISSUE TITLE
Copy the signature of an identifier

### ISSUE THREAD

**Issue by xavierzwirtz** [dotnet/fsharp#3431]
In VS 2015 with F# Power Tools I was able to click on an identifier, and then the type of the identifier would display in a text box in the lower left hand corner of VS. This feature did not get ported into the mainline F# VS plugin.

I find my self needing to hard code the type of identifiers to help out type inference. Before I could easily grab the type signature of one identifier and paste it onto another, but with all of the type info being moved inside of the hover dialog there is no way to copy and paste that info

#### Repro steps

Provide the steps required to reproduce the problem

1. Click on identifier

2. Try to copy and paste signature

#### Expected behavior

Instead of bringing back the old text box that contained selectable type info, what about some key combo that will copy the type of the current identifier into the clipboard?

#### Known workarounds

Remember the type of the identifier and manually type it in.

#### Related information 

Provide any related information 

* VS 2017 
* Visual F# Tools 15.4.1.17081401

**Comment by vasily-kirichenko** [comment]
I'm afraid nobody wants to touch keyboard handling having such a huge trouble with broken arrow and other keys in VS 2017.2+ :)

**Comment by kkm000** [comment]
Yes, yes, pretty please! Just came here to ask for same, and found that the FR has been made already. I often find myself adding type annotations for readability after having completed code, and it gets tedious at times for complex sigs, especially given you no longer have a tooltip in the middle of writing it, when the type is half-written and IntelliSense has painted it all red. The `--sig` helps, but most of the time I need just a couple of binging annotated, usually major public functions in a module, and running fsc from command line just for that is a hassle.

**Comment by kkm000** [comment]
I'll leave the *binging* typo above. FP is all about binging on types, is not it? Hey, another round of top-shelf Hindley Milner for everyone! :)
