### ISSUE TITLE
Do not show links on tooltips for symbols source for which are not available

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#3439]
![1](https://user-images.githubusercontent.com/873919/29329330-3f5b6ab4-81fe-11e7-8c6b-a4a43ad204e7.gif)

**Comment by cartermp** [comment]
cc @majocha 

Agreed, this could be seen as misleading.

**Comment by majocha** [comment]
The way it works currently is very simplistic. It doesn't really use `SourceCodeServices` to resolve symbols, I'm looking into fixing this. OTOH that's why it sometimes works when F12 fails :smiley:, see #3460
