### ISSUE TITLE
VS2017 - Set breakpoint at line, sets breakpoint at larger scope

### ISSUE THREAD

**Issue by fjoppe** [dotnet/fsharp#3441]
**@cartermp edit - see repro here: https://github.com/Microsoft/visualfsharp/issues/3441#issuecomment-323171236**

--

In Visual Studio 2017, if I set a breakpoint at a line, then the breakpoint is set at a higher scope, and it does not break where I want. This worked in VS2015.

#### Repro steps

Given [this source file](https://github.com/fjoppe/FsYamlParser/blob/master/src/YamlParser/YamlParser.fs)

In Visual Studio 2017, I try to set a breakpoint at line 2505:
![step001](https://user-images.githubusercontent.com/10013556/29331988-b7bf6618-81fe-11e7-899b-2d588950f3a7.PNG)

#### Expected behavior

This is what happens if I set a breakpoint at line 2505, in Visual Studio 2015:
![step003](https://user-images.githubusercontent.com/10013556/29332226-9cc2edf2-81ff-11e7-9c1f-67d375183a90.PNG)

#### Actual behavior

The breakpoint is set at a larger scope in Vsiual Studio 2017:
![step002](https://user-images.githubusercontent.com/10013556/29332130-3d484034-81ff-11e7-9a52-0c5200c9b472.PNG)

#### Known workarounds

Don't use VS2017, but use VS2015 instead.

#### Related information 

Provide any related information 

* Operating system: Windows 10
* Visual Studio 2017 Community
* Visual F# Tools: 15.4.1.17051001
* Indications of severity: high, debugging is not usable in my project

**Comment by cartermp** [comment]
I cannot repro this on 15.4.1.17081501:

![no-repro-yaml-debug-resolution](https://user-images.githubusercontent.com/6309070/29341883-1cb6702a-81dc-11e7-8641-e2049789f38f.gif)

**Comment by fjoppe** [comment]
Quite strange that this works on your machine. Maybe this info helps, from the Visual Studio Help/About:

Microsoft Visual Studio Community 2017 
Version 15.2 (26430.16) Release
VisualStudio.15.Release/15.2.0+26430.16
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA781
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA781
Microsoft Visual C# 2017

Visual F# 4.1   00369-60000-00001-AA781
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.6.00404.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30503.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50303.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30209.0
Azure App Service Tools v3.0.0

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   2.2.0.11
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

NuGet Package Manager   4.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools

TypeScript   2.2.2.0
TypeScript tools for Visual Studio

**Comment by cartermp** [comment]
@fjoppe Can you try this on VS 2017 15.3 with the latest F# nightly installed?

**Comment by fjoppe** [comment]
Hi,

I've upgraded to VS 2017 15.3. Did not upgrade to the nightly build of F# (hopefully not necsary?).

The above now works. ie, setting a breakpoint at line 2505. So it appears as if the upgrade solved that issue. I tried another location though, and it is not perfect.

Same source as above.

When I want to set a breakpoint at line 2467:
![step001](https://user-images.githubusercontent.com/10013556/29429912-a6c625e6-8392-11e7-96a9-fcc1178c1e02.PNG)

Then the breakpoint is set at a higher location:
![step002](https://user-images.githubusercontent.com/10013556/29429945-c876dbe0-8392-11e7-98ab-bac7cd786f48.PNG)

However, when I set the breakpoint at line 2468:
![step003](https://user-images.githubusercontent.com/10013556/29429968-e27792dc-8392-11e7-8b7f-7549ea2df335.PNG)

I get what I want:
![step004](https://user-images.githubusercontent.com/10013556/29429979-ef7188ee-8392-11e7-8ac5-be45af2fe731.PNG)

Not perfect, but workable..

Can you reproduce this one? I still hope I don't need that nightly build (keep my system stable).

Regards, Frank

**Comment by cartermp** [comment]
I can indeed reproduce this!  I also noticed that setting the breakpoint on `ps` via the f9 key works as expected, so this is specific to when a breakpoint is set via clicking in the margin.  That's been the trickier action to handle with VS 2017, unfortunately.  Always seems like a new inconsistency is found every few months.

**Comment by dsyme** [comment]
We need source files for this - what's shown above is a bit hard to repro - what are the exact constructs involved?

**Comment by cartermp** [comment]
Unfortunately the codebase that reproduced this has diverged and the relevant places discussed don't reproduce this issue. I'll close this out as no repro now, but if you do notice it please ping and I'll re-open if you've got a good repro again.
