### ISSUE TITLE
Xamarin for Windows - Non-standard hierarchy nodes not recognized; commands not working

### ISSUE THREAD

**Issue by joj** [dotnet/fsharp#3468]
In iOS we have a few non-standard hierarchy nodes that show up in Solution Explorer (Asset Catalogs, Native References, Components). The problem is that these nodes are not recognized by the Project System, and GetSelectedNodes (https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.ProjectSystem.Base/Project/ProjectNode.cs#L2757) returns an empty List when queried for them (for the itemId of those nodes). This results in the HierarchyNode returning OLECMDERR_E_NOTSUPPORTED (https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.ProjectSystem.Base/Project/HierarchyNode.cs#L1624) in InternalExecCommand when our menu is called, and the menu not showing.

#### Repro steps
1. Create a new iOS project (any type, any device)
2. Right-click on Asset Catalogs 

#### Expected behavior
A menu should show, showing options for creating a new Asset Catalog

#### Actual behavior
Nothing happens

#### Known workarounds
There are no workarounds, or very specific ones for each of the options in the menus.

**Comment by dsyme** [comment]
@joj Could you send a PR for the changes you want please?  I think it's best you contribute and test them directly? We can help advise and code review of course

**Comment by joj** [comment]
@dsyme this change is a little heavier than the previous ones I've been doing, and I don't know project systems that well. I can help, but I'm not sure I'll be able to provide a PR without a lot of guidance :)

On CPS, you'll eventually need to support it but that's a whole different issue. CPS is a breaking change for users and extensions. They will need to migrate unless you support both. We don't have support for them yet (I think C# isn't fully compatible either). If you're planning on supporting them (which is generally speaking a good idea) you'll still need to support this at least for a while. We can discuss internally if you want and then update here.

**Comment by dsyme** [comment]
@joj The POR is to use CPS for all "new style" .NET SDK 2.0 projects where possible.  @KevinRansom and @srivatsn sre looking after that, I'm not really involved except as an occasional observer.  The old project system will also be shipped at least for the time being.

It's probably best you sync up directly with @cartermp, @KevinRansom and @srivatsn to work out a POR for project system support for F# Xamarin projects on Windows.   Moving to CPS would be simplifying if we can manage it.

**Comment by joj** [comment]
I'll sync with them. Thanks :)

**Comment by cartermp** [comment]
F# is now all-in on the SDK-style project system here: https://github.com/dotnet/project-system

Since Xamarin is also going to be transitioning to it for .NET 6, I'll close this out as any work here would be throwaway in nature.
