### ISSUE TITLE
InternalsVisibleTo attribute in recursive module not compiles

### ISSUE THREAD

**Issue by Dolfik1** [dotnet/fsharp#3511]
InternalsVisibleTo attribute not compiles in recursive module

#### Repro steps

Provide the steps required to reproduce the problem

1. Paste the following:
```fsharp
module rec Test

open System.Runtime.CompilerServices

[<assembly: InternalsVisibleTo("System")>]
do()
```

2. Try to compile

#### Expected behavior

No compile errors.

#### Actual behavior

```Error FS0039 The type 'InternalsVisibleTo' is not defined.```

#### Known workarounds

Use a fully qualified name:
```fsharp
module rec Test

[<assembly: System.Runtime.CompilerServices.InternalsVisibleTo("System")>]
do()
```

#### Related information 

Bug reproduced in F# 4.1 Compiler

**Comment by dsyme** [comment]
@Dolfik1 Thanks. Note you can use a fully qualified name:

```fsharp
module rec Test

[<assembly: System.Runtime.CompilerServices.InternalsVisibleTo("System")>]
do()
```

**Comment by Dolfik1** [comment]
I'm thinking about trying to fix this bug. What could be the problem?

**Comment by vzarytovskii** [comment]
Should be fixed as part of https://github.com/dotnet/fsharp/issues/5795 probably
