### ISSUE TITLE
Enable -- warning for mismatched param names by default in new desktop templates and the netsdk

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#3539]
This PR:  https://github.com/Microsoft/visualfsharp/pull/3527  adds a warning for mismatched param names between signatures and implementations.

As a change it's highly breaking as so is not enabled by default in the compiler.  

This issue asks to:

1.  Enable it by default in new desktop projects
2.  Enable it by default in all dotnet sdk projects 
     .... yes it's a break, but those projects should be fresh and should be fixed.
3.  Provide a project sectings options in the ide to enable / disable this.

**Comment by 0x53A** [comment]
Can we please add a single parameter (maybe ``--strict``?), which enables all these off-in-the-compiler-by-default warnings?

Then I would add this one to all my project files.

**Comment by matthid** [comment]
Yes I think typescript has something similar with the contract that you opt in new stuff automatically (and might break you).

**Comment by KevinRansom** [comment]
@0x53a I sort of like it ... How do you  propose that we treat warnings that added in the future?  is strict always strict and always getting tougher and tougher?

**Comment by 0x53A** [comment]
> How do you propose that we treat warnings that added in the future? is strict always strict and always getting tougher and tougher?

Yes. Strict means my code may break at any compiler update. Otherwise we would need --really-strict and --really-truly-strict at later points ;-)

**Comment by 0x53A** [comment]
Roslyn also "fixes" other compiler bugs in strict mode: https://github.com/dotnet/roslyn/search?q=FeatureStrictEnabled&type=Code&utf8=%E2%9C%93

**Comment by KevinRansom** [comment]
I just chatted with @jaredpar.  feature strict enables an ECMA compliance check.

but  we have an option:

**--warnon:<warn;...>**

Perhaps if we enabled:
**--warnon:all** which turned on all warnings except for those explicitly turned off with **--warnoff:**

**Comment by 0x53A** [comment]
I don't remember one at the top of my head, but I think there were a few noisy warnings which are off by default on purpose and not due to backwards compatibility.

In contrast, I imagine ``strict`` to be the behavior we would want the compiler to have if this was version 1.0 and we didn't care about the past. There may well be a few warnings we want off even in strict.

**Comment by KevinRansom** [comment]
@0x53A ... yes I can see that ...

so **--warnon:strict** to enable the stricter warnings for all of the stuff we turn on in the templates.

Sound like a plan?

**Comment by 0x53A** [comment]
Sounds good

**Comment by dsyme** [comment]
👍 from me
