### ISSUE TITLE
Support Code Maps

### ISSUE THREAD

**Issue by realvictorprm** [dotnet/fsharp#3578]
Visualisation of code is always helpful and in visual studio enterprise versions achieved through code maps. Current however those only support C# and VB.NET but not F#. Is there any possibility go get Code Maps working for F# too?

See also [this](https://msdn.microsoft.com/en-us/library/jj739835.aspx) if you don't know Code Maps.

**Comment by dsyme** [comment]
Now a duplicate of more recent https://github.com/dotnet/fsharp/issues/11787
