### ISSUE TITLE
Some tests are extremely slow, is this to be expected?

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#3587]
A bunch of tests run > 1 min on my system. This may be due to system settings, or they are designed that way (i.e., meant as stresstests). 

Also when I run them in parallel (though each test in its process!), they run basically forever (killed the processes after some hours), I have yet to investigate why this is even possible, they should not be in each others way and certainly not cross-process.

### Repro steps

To repro, run any one of the following tests. If they aren't slow for you, I'd like to know, as in that case the slowness may be caused by NCrunch and I need to investigate / report on it / change settings.

This happens when running the tests in Debug mode, x86 compiled and x86 runner.

### Expected behavior

They should not run that long, or be tagged as such. And they should run atomically (that is: not be dependent on each other, though I don't know if that's the case here).

### Actual behavior

I observe several things:

* Run a test on and by itself: it's relatively fast, often within a minute
* Run several tests in parallel (in multiple processes, not in the same process!): it can be slow, often times out, processor is essentially doing nothing, memory is stable (doesn't appear to leak)
* Run all tests in `CollectionModulesConsistency` at once, they don't end for several hours (I killed the processes). Run them with paralellization disabled they run faster, but on each run several time out. 
* Again, running the ones that time out separately makes them end within 1-3 mins.

As an example: the top test in this list timed out on 10 min. Then I ran it again and it didn't time out and finished in 7' 40".

![image](https://user-images.githubusercontent.com/16015770/30452213-3c28f33a-9995-11e7-8588-533a46223cfe.png)

The prime reason when behavior like this happens is when tests rely on resources on disk and take an exclusive lock. For instance if they write to a (log) file and the process holds a lock over it.

I'd like to hear someone more familiar with these tests where I should look, as I believe all tests should be atomic by definition.

### Known workarounds

I'd love to hear of any!

### Related information 

Visual Studio 2017 15.4.0 P2, Windows 7, Debug build of FSharp.sln, x86 host process, x86 compiled assemblies.

**Comment by dsyme** [comment]
Note these may be FsCheck tests, and you may need to disable or control them in some way.  I don't think it's useful to repeatedly run 7 minute FsCheck tests when we're not even changing those functions

**Comment by abelbraaksma** [comment]
@dsyme: yes, these are indeed FsCheck tests running so slowly. I also may have found why tests are hanging, which does not seem to have to do with whether or not they are atomic: the remote task runner reports a signature mismatch. I'll have to investigate what that means.

**Comment by abelbraaksma** [comment]
@dsyme: a follow up. I have found that the instrumentation added to FSharp.Core greatly reduces the executation time. Not too surprising, as the instrumentation can well mean that the tests will not be inlined anymore by JIT, or certain tail recursion may even be hampered (the latter rather unlikely though, because the instrumentation always has void return).

We need the instrumentation for code coverage, but for just running the tests it may not always be required. Removing them makes the slowest four tests on my machine 15-20 seconds, some 20 tests > 5 seconds, rest relatively fast. The 7 minute mark is not reached by any of them anymore.

As a byproduct, this shows that profiling (which also adds instrumentation) is a very tricky business, as the slowest tests with and without instrumentation are not the same. For instance, the `scan` test from my 7 minute example above now runs in 15 seconds.

Still, I will look in how to improve this, as having several dozens of tests running >5 seconds is still suboptimal.

**Comment by cartermp** [comment]
Most of the slow tests are in the FSharp.Control namespace. That's where i'd look.

**Comment by abelbraaksma** [comment]
I totally forgot about this report, I'll close this out. The tests, when run in ncrunch, like above, get some instrumentation added, so that ncrunch can add coverage markers and catch SO exceptions.

In the near future, once everything is configured through xUnit, they'll be more easily tunable.
