### ISSUE TITLE
File re-ordering is slow

### ISSUE THREAD

**Issue by saul** [dotnet/fsharp#3602]
Re-ordering files in the Solution Explorer is unnecessarily slow - each movement causes the project to be reloaded with ComputeSourcesAndFlags. It's not necessary - we know what the new source file layout will look like so we should just use that instead.

Happy to take a look at this this week.

**Comment by dsyme** [comment]
> Re-ordering files in the Solution Explorer is unnecessarily slow - each movement causes the whole project file to be reanalyzed (including references). It's not necessary - we know what the new source file layout will look like so we should just use that instead.

When you say "reanalyzed" are you meaning FCS typechecking reanalysis?  Or project loading?

**Comment by saul** [comment]
I'm referring to ComputeSourcesAndFlags - so project loading.

**Comment by cartermp** [comment]
Now that we're all-in on the [new-style project system](https://github.com/dotnet/project-system), including for new .NET FX-targeted projects, I think we'll close this out.

**Comment by abelbraaksma** [comment]
Let's add to that: it has improved dramatically in terms of speed. I've no problem doing this on large legacy, or large new project file formats.

Sometimes a warning pops up that asks confirmation and warns that it may take a while, but it finishes in seconds.
