### ISSUE TITLE
Parser adds new line symbol to the source being parsed

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#3617]

**Comment by dsyme** [comment]
@auduchinok Could you give more context on why this is a problem

Context I know is

* New line is only added if the file doesn't already end in a new line
* This applies only to ParseAndCheckFileInProject and ParseFileInProject

But I don't know what specific problems it causes to add the new line character.  Equally, I don't know why our tests are so sensitive to the character being there (beyond line number range reports - it's more dramatic than that I believe?)

Thanks!
don

**Comment by auduchinok** [comment]
@dsyme Adding new line changes AST ranges which we rely on. We currently map these ranges to R# document offsets using approach very similar to the one used in [RoslynHelpers.fs](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Common/RoslynHelpers.fs#L25) except getting min of lines count and a range line. It works fine when an empty line isn't added to the source.

**Comment by dsyme** [comment]
@auduchinok OK thanks, that makes sense

**Comment by dsyme** [comment]
@auduchinok I'm labelling this a "Urgency Later" since we workaround it at the moment, but please feel free to submit a fix for it.

**Comment by auduchinok** [comment]
Fixed in https://github.com/dotnet/fsharp/pull/6001.
