### ISSUE TITLE
Cannot put breakpoints inside a CE

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#3623]
![1](https://user-images.githubusercontent.com/873919/30756432-5ea9f172-9fd3-11e7-9453-4a86743eac89.gif)

**Comment by abelbraaksma** [comment]
Is this async-specific? Not so long ago I am sure I have used breakpoints in home-grown computation expressions (though they are hardly ever useful).

**Comment by cartermp** [comment]
From #3758 

![](https://user-images.githubusercontent.com/873919/31587491-42aa5366-b1eb-11e7-8d3f-dcb0ebe8dc2c.png)

**Comment by vasily-kirichenko** [comment]
Oh, cool. It seems I'm reporting the same issue on the same code again and again...

**Comment by dsyme** [comment]
Closing since the latest revamp of debug points addresses much (though not all) of this and other items are tracked separately
