### ISSUE TITLE
No value tooltip for "this" in debugger

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#3624]
![1](https://user-images.githubusercontent.com/873919/30756878-08b1bd70-9fd5-11e7-8822-7687153fdcb7.gif)

**Comment by vasily-kirichenko** [comment]
Rider sees `this` as "obj0`, not perfect, but it works:

![image](https://user-images.githubusercontent.com/873919/30757406-49e714c8-9fd7-11e7-8023-3476c4b907ad.png)

**Comment by dsyme** [comment]
I believe this was related to the recent problem fixed for debug info at the very start of some methods.

I've checked cases related to 'this' and they work ok
