### ISSUE TITLE
Referencing any project that is compiled with --standalone changes returned type of the array index operator and causes FS0001

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#3636]
A simple use of the array index operator (like `[|1; 2; 3 |].[1]`) fails when you use a reference that was compiled with `--standalone`.

**Just referencing is enough. No need to actually use _anything_ from the referenced assembly.**

## Repro steps

Basically: just try to compile the provided solution [FSharpBug#3636.zip](https://github.com/Microsoft/visualfsharp/files/1327376/FSharpBug.3636.zip) (I made it as minimalistic as possible). To get there by hand, just do this:

1. Create a solution with two projects (project type does not matter), let's say `A.fsproj` and `B.fsproj`
2. Make sure `A` contains some code, say `module Foo = ()`
3. Set the `OtherFlags` of `A` to include `--standalone` <sup>(1)</sup>
4. Create a project reference from `B` to `A` (B uses A)
5. Add any function,  member that accesses an array by index, for instance `let x = Array.empty<int>.[0]`
6. Compile for `Release`: error FS0001, wrong type

<sup>(1)</sup> Notes: there is a bug #3637 with setting the other flags, if set through the Properties window it will often _only_ set it for the `Release` build, but appears as if set for both. However, this bug applies to any build type, if you set it manually for the `Debug` build in the `fsproj` file (as is done in the referenced ZIP) it blows up there too.

## Expected behavior

No error should be thrown. Experience with or without `--standalone` flag should roughly be the same, and definitely should effect the result type of operators.

## Actual behavior

Any use of the index operator appears to throw this error. I tried at least with the following usages:

```f#
module IndexOperatorIssue =

    /// Compiling this with --standalone will raise FS0001, saying it expects a tuple a[] * int
    let FailingIndexOperator0 =
        let test = [|1; 2; 3 |]
        test.[10]
    
    /// Compiling this with --standalone will raise FS0001, saying it expects a tuple a[] * int
    let FailingIndexOperator1 =
        let test = Array.create 10 "foo"
        test.[10]
    
    /// Compiling this with --standalone will raise FS0001, saying it expects a tuple a[] * int
    let FailingIndexOperator2 =
        (Array.create 10 "foo").[1]

    /// Compiling this with --standalone will raise FS0001, saying it expects a tuple a[] * int
    let FailingIndexOperator3 =
        Array.empty<int>.[0]

    /// Compiling this with --standalone will raise FS0001, saying it expects a tuple string * int
    let FailingIndexOperator4 =
        "foo".[1]

    /// Compiling this with --standalone will raise FS0001, saying it expects a tuple a[] * int
    let FailingIndexOperator5 =
        "foo"B.[1]
```

The above snippet throws different, but clearly similar errors, like:

```
error FS0001: This expression was expected to have type    ''a [] * int'    but here has type    'int []'
 error FS0001: This expression was expected to have type    ''a [] * int'    but here has type    'string []'
 error FS0001: This expression was expected to have type    ''a [] * int'    but here has type    'string []'
 error FS0001: This expression was expected to have type    ''a [] * int'    but here has type    'int []'
 error FS0001: This expression was expected to have type    'string * int'    but here has type    'string'
 error FS0001: This expression was expected to have type    ''a [] * int'    but here has type    'byte []'
```

## Known workarounds

Do not compile with `--standalone` or do not use the index operator. However, I suspect there's a deeper error causing this behavior, as I got to this error when analyzing a program failing after merely referencing another project, without changing anything else.

## Related information 

It is probably important to know that this behavior can be observed with:

* VS2017, VS2015, RTM and Preview
* F# 3.x, 4.0 and 4.1
* **Probably a severe bug**, as the static types should really not change between types of builds
* Referenced project can be DLL or EXE, can be empty or contain something, compiling it with `--standalone` is enough to wreak havoc on every project that uses it.
* This may or may not be the reason why FParsec cannot be compiled as single assembly (@stephan-tolksdorf)

**Comment by dsyme** [comment]
Thanks for the report

**Comment by dsyme** [comment]
To be clear, this is simply not supported:

"Create a project reference from B to A (B uses A)"

Referencing components compiled with `--standalone` from other F# components is not supported.

**Comment by abelbraaksma** [comment]
Ah, I never thought of it that way. Can’t recall what the docs say (if anything), but I guess it makes sense.
