### ISSUE TITLE
The "other flags" in the properties window shown are always the properties belonging to the RELEASE build

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#3637]
Regardless of whether you select Debug or Release build, setting "Other flags" always shows the settings of the Release build, resulting in confusion if these settings are different.

#### Release view:

![image](https://user-images.githubusercontent.com/16015770/30783789-4c6bf236-a149-11e7-859a-4f82bfd0651e.png)

#### Debug view (should be empty)

![image](https://user-images.githubusercontent.com/16015770/30783937-f421c2c4-a14b-11e7-8a4f-0d19a8fd9099.png)

#### Contents of `fsproj`

```xml
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
  <DebugSymbols>true</DebugSymbols>
  <DebugType>full</DebugType>
  <Optimize>false</Optimize>
  <Tailcalls>false</Tailcalls>
  <OutputPath>bin\$(Configuration)\</OutputPath>
  <DefineConstants>DEBUG;TRACE</DefineConstants>
  <WarningLevel>3</WarningLevel>
  <PlatformTarget>AnyCPU</PlatformTarget>
  <DocumentationFile>bin\$(Configuration)\$(AssemblyName).XML</DocumentationFile>
  <Prefer32Bit>true</Prefer32Bit>
  <OtherFlags>
  </OtherFlags>
</PropertyGroup>
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
  <DebugType>pdbonly</DebugType>
  <Optimize>true</Optimize>
  <Tailcalls>true</Tailcalls>
  <OutputPath>bin\$(Configuration)\</OutputPath>
  <DefineConstants>
  </DefineConstants>
  <WarningLevel>3</WarningLevel>
  <PlatformTarget>AnyCPU</PlatformTarget>
  <DocumentationFile>bin\$(Configuration)\$(AssemblyName).XML</DocumentationFile>
  <Prefer32Bit>false</Prefer32Bit>
  <OtherFlags>--standalone</OtherFlags>
</PropertyGroup>
```

### Repro steps

1. Create any project
2. Set the "Other flags" for this project with Release as target
3. Select target Debug: the same setting is shown
4. Open the `fsproj`, the setting is only there for Release builds

### Expected behavior

Difference between Release and Debug builds should be maintained in the properties window.

### Actual behavior

* When you remove the option, and then reopen the Properties window, it is back (unless you remove it from the Release as well)
* When the options are different in the `fsproj`, only the Release options are shown regardless of selected build.
* When the options are different and you change them for Debug, this will properly be reflected for only the Debug build settings in `fsproj`, but does not show in the properties window and will be overwritten on next safe.
* If you switch between Debug and Release in the properties window (i.e. to change both options) and the last switch was from Release > Debug, the saved setting is the invisible setting that you typed before.

### Known workarounds

Edit this option by hand by editing the `fsproj` file itself. Or "remember" that the settings are different.

### Related information 

VS2017, any version of F# or point-release of VS.

**Comment by cartermp** [comment]
This is resolved for me:

Release:
![image](https://user-images.githubusercontent.com/6309070/58294251-ed789f00-7d7d-11e9-80b1-ea9b1d38780a.png)

Debug:
![image](https://user-images.githubusercontent.com/6309070/58294256-f5d0da00-7d7d-11e9-80c4-d4cd643c2d56.png)

And these are respected when toggling.

**Comment by abelbraaksma** [comment]
Thanks for this!
