### ISSUE TITLE
CoreCLR build script fails on Linux

### ISSUE THREAD

**Issue by ghost** [dotnet/fsharp#3663]
Checking out the visualfsharp repo and running `./autogen.sh && ./build.sh coreclr` results in permissions denied issues. It seems the scripts/ folder does not have the execute bit set on required files.

#### URL/versioning issues
Unfortunately, this isn't the end of the problems, after running `chmod +x scripts/dotnet-install.sh` (then re-running ./buiild.sh coreclr) we then get the following:

```
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview3-003886/dotnet-dev-linux-x64.1.0.0-preview3-003886.tar.gz
curl: (22) The requested URL returned error: 404 
Restoring BuildTools version 1.0.27-prerelease-01001-04...
./init-tools.sh: line 149: /opt/visualfsharp/Tools/dotnetcli/dotnet: No such file or directory
```

I think we need to go thru the build scripts and make sure everything is updated to a more recent and readily available URL, ideally this should involve finding URLs that are pinned by Microsoft (seriously who removed that file...).

#### Download caching
After running `dotnet --version > DotnetCLIVersion.txt && dotnet --version > DotnetCLIToolsVersion.txt` the downloading of tools should be fine. 

This is good for systems that don't have dotnet already installed, but ideally the script should detect tools are already available.
Edit: This appears to be the fault of script/dotnet-install.sh, however it is not helped by init-tools.sh DELETING (line 99) the Tools directory (where the dotnet cli is extracted to) each run, this leads to downloading files taking a loooong time.

#### Related information 

* Debian 9
* Netcore 2.0.0

**Comment by abelbraaksma** [comment]
Let me link this to #3645. I don't have an answer, though (I don't have enough knowledge of Linux), but in light of the other post I am trying to make the build experience smoother, and this is certainly related to that.

**Comment by xenocons** [comment]
Yes agreed, and thank you! I am working on getting it to build today and will post here once I have more. It may very well be similar issues between the windows build and linux.

**Comment by xenocons** [comment]
Ooookay, there goes 5 hours of messing around, no actual build success. I am going to have to throw in the towel and wait til someone who knows the build system can answer. I was expecting at the very least this to work:
` dotnet build /p:Configuration=Proto /p:TargetDotnetProfile=coreclr src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fspro` Unfortunately it dies at 

```/opt/fsharp/packages/FSharp.Compiler.Tools.4.1.23/tools/Microsoft.FSharp.Targets(123,9): error MSB4018: The "CreateFSharpManifestResourceName" task failed unexpectedly. [/opt/fsharp/src/fsharp/FSharp.Core/FSharp.Core.fsproj]
/opt/fsharp/packages/FSharp.Compiler.Tools.4.1.23/tools/Microsoft.FSharp.Targets(123,9): error MSB4018: System.TypeInitializationException: The type initializer for 'Microsoft.Build.Collections.MSBuildNameIgnoreCaseComparer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'kernel32.dll': The specified module or one of its dependencies could not be found. [/opt/fsharp/src/fsharp/FSharp.Core/FSharp.Core.fsproj]```

**Comment by abelbraaksma** [comment]
seems like some build targets are not found. Not sure what the prerequisites are, but possibly you beef to install some build extensions or SDKs.

**Comment by dsyme** [comment]
@abelbraaksma I actually think ``build.sh`` is out of date as well -

@KevinRansom Is ``src/buildfromsource.sh`` the better way to do a build on Linux? (though without testing etc.)?
