### ISSUE TITLE
License text in build tools, SDK files, confusing and license.txt not in RTM setup of build tools

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#3668]
The current license header in, for instance, `Microsoft.FSharp.NetSdk.targets` reads:

```xml
<!-- Copyright (c) Microsoft Corporation.  All Rights Reserved.  See License.txt in the project root for license information. -->
```

The previous (F# 4.1) version was:

```xml
<!-- Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information. -->
```

In both cases it says ***See License.txt in the project root for license information***. But there is no "project root" in the SDK dir `C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0` and while a higher dir has `Licenses`, it does not contain this license.

I am no licenses expert, but 'd suggest that either:

* We change the text to refer to another location where the actual license.txt can be found
* We leave the text (since it is used everywhere) but we add a `license.txt` file to the F# Build Tools distribution MSI and any other distribution where this is missing.

PS: I'm referring to the build tools advocated here: http://fsharp.org/use/windows/, and the direct download link I used was http://download.microsoft.com/download/F/3/D/F3D6045E-4040-4058-ADAD-2698F1793CBC/Microsoft.FSharp.SDK.Core.msi.

**Comment by KevinRansom** [comment]
yes we should do something about that.

**Comment by KevinRansom** [comment]
@abelbraaksma , I am closing this.  What we have is similar to what other dotnet repos.
E.g from a random roslyn source file:https://github.com/dotnet/roslyn/blob/main/src/EditorFeatures/Core/BracePairs/BracePairsTaggerProvider.cs#L3
