### ISSUE TITLE
Add FSharp.Core package reference with IsImplicitlyDefined = true

### ISSUE THREAD

**Issue by Alxandr** [dotnet/fsharp#3678]
I just wrote a tool that extracts `ProjectReference` entries from a msbuild project. It removes any references that is automatically added by the framework by checking for metadata `IsImplicitlyDefined`. This works for C# and VB, but F# does not add this metadata.

Also, looking at [this](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Build/Microsoft.FSharp.NetSdk.targets#L72) it seems the same is true for `System.ValueTuple`.

#### Repro steps

Create a fsharp SDK based project (for instance `dotnet new classlib --language F#`). Extract all `ProjectReferences`.

#### Expected behavior

`FSharp.Core` should be added with metadata `IsImplicitlyDefined` equal to `true`.

#### Actual behavior

`FSharp.Core` is not added with `IsImplicitlyDefined`.

#### Known workarounds

Manually add it, which defeats the purpose altogether.

#### Related information 

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by dsyme** [comment]
@KevinRansom Could you take a look at this please?

**Comment by 0x53A** [comment]
It looks like this would also solve other issues - according to [this comment](http://source.roslyn.io/#MSBuildFiles/C/ProgramFiles/dotnet/sdk/2.0.0/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.DefaultItems.targets,193), PackageReferences without ``IsImplicitlyDefined`` take precedence over ones with it. So this would fix the issue where it is impossible to override the implicit FSharp.Core later, which was an issue in Paket.

**Comment by dsyme** [comment]
@KevinRansom did you take a look at this?

**Comment by jeffkl** [comment]
I'd like to send a PR to fix this, may I submit it?

https://github.com/microsoft/visualfsharp/compare/master...jeffkl:fix?expand=1

**Comment by cartermp** [comment]
@jeffkl absolutely!

**Comment by cartermp** [comment]
Closing out as per the resolution of https://github.com/dotnet/fsharp/pull/6730

**Comment by knocte** [comment]
> Closing out as per the resolution of https://github.com/dotnet/fsharp/pull/6730

So then F# will never be compatible with Central Package Management (Nuget new feature)? See https://github.com/NuGet/Home/issues/11949#issuecomment-1199673083

**Comment by cartermp** [comment]
Things can always change, and you can always just use paket
