### ISSUE TITLE
No member completion when particular namespaces are opened

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#3679]
There's no completions for some values members when particular namespaces from ReSharper.SDK are opened. I've encountered this behaviour when opened these namespaces: `JetBrains.DataFlow` and `JetBrains.Util`.

Here's a small repro solution: [NoCompletionRepro.zip](https://github.com/Microsoft/visualfsharp/files/1350544/NoCompletionRepro.zip).
Commenting `open JetBrains.Util` out makes completions work.
I've tried debugging it and found that types of these values were lost in tast (so no type members and no completions).

**Comment by dsyme** [comment]
@auduchinok Any chance you could put together a failing test under ``tests\service``?  That would make it much easier to debug this.

**Comment by auduchinok** [comment]
@dsyme Sure, I'll try to make such a test. The bad thing is I have this behaviour reproduced only when referencing ReSharper.SDK nuget package which is rather a big thing to restore on a test run.
A small note: I've seen this bug in FCS ~14.x+ only, so it could be some recent regression.

**Comment by dsyme** [comment]
> @dsyme Sure, I'll try to make such a test. The bad thing is I have this behaviour reproduced only when referencing ReSharper.SDK nuget package which is rather a big thing to restore on a test run.
A small note: I've seen this bug in FCS ~14.x+ only, so it could be some recent regression.


Yeah, I figured it would require a big package.  Still, once we have a PR for the failing test we should be able to determine the underlying problem and create a more isolated repro

**Comment by vasily-kirichenko** [comment]
I see this error

![image](https://user-images.githubusercontent.com/873919/40786013-b7af95ee-64f2-11e8-8b06-d4f8a2bab377.png)

@auduchinok Looks like a missing assembly/nuget reference?

**Comment by auduchinok** [comment]
@vasily-kirichenko Yes. We've been using GetDeclarationsAsSymbols at that point and it didn't contain this note if I remember correctly.

**Comment by dsyme** [comment]
Closing this very old issue
