### ISSUE TITLE
netcoreapp library fails to build

### ISSUE THREAD

**Issue by enricosada** [dotnet/fsharp#3680]
First create a console app

```
dotnet new console -lang f#
```

and remove the 

```xml
<OutputType>Exe</OutputType>
```

so is a library targeting .net core runtime. Now trying to build with

```
dotnet build
```

result in the error

```
Build FAILED.

       "e:\temp\fs_console\fs_console.fsproj" (Build target) (1) ->
       (CoreCompile target) ->
         e:\temp\fs_console\Program.fs(7,5): error FS0433: A function labeled with the 'EntryPointAttribute' attribute must be the last declaration in the last file in the compilation sequence. [e:\temp\fs_console\fs_console.fsproj]

    0 Warning(s)
    1 Error(s)
```

I checked and the target type is correct ` --target:library`, but the file order list is wrong.

```
         Program.fs
         C:\Users\e.sada\AppData\Local\Temp\.NETCoreApp,Version=v2.0.AssemblyAttributes.fs
```

Btw the same issue happen with a library who contains a file with `[<EntryPoint>], the `AssemblyAttributes.fs` is always created as the last file.

As a note, i tried to run `fsc` directly switching the file order (so `Program.fs` as last file), and build correctly.

@KevinRansom can be ok to add the generated `AssemblyAttributes.fs` file always at first one, like with console? if is ok, i can fix that

**Comment by dsyme** [comment]
For .NET Framework we use:
```
        <ItemGroup>
            <CompileBefore Include="$(TargetFrameworkMonikerAssemblyAttributesPath)" Condition="'$(AdditionalSourcesText)' != '' AND ('$(OutputType)' == 'Exe' OR '$(OutputType)' == 'WinExe')"/>
            <CompileAfter Include="$(TargetFrameworkMonikerAssemblyAttributesPath)" Condition="'$(AdditionalSourcesText)' != '' AND '$(OutputType)' != 'Exe' AND '$(OutputType)' != 'WinExe'"/>
        </ItemGroup>

```

**Comment by enricosada** [comment]
yes, about best way to fix this:

using `CompileBefore` to place it first, is always better afaik, why use also `CompileAfter` (who generate this issue)? i cannot think a reason atm but maybe there is a scenario where is needed..
If not need, we can just remove the final part of the conditional

**Comment by dsyme** [comment]
> using CompileBefore to place it first, is always better afaik, why use also CompileAfter (who generate this issue)? i cannot think a reason atm but maybe there is a scenario where is needed..
If not need, we can just remove the final part of the conditional

CompileAfter is only needed for FSharp.Core.  Otherwise we could always use CompileBefore

**Comment by KevinRansom** [comment]
@enricosada please use compile before for the assembly attributes.

@dsyme 
history shows that the last fcs integration caused the change ... prior to that it was just CompileBefore.

https://github.com/Microsoft/visualfsharp/blame/ff6aec7a32fe438a667b9c9a1b380c408182edb2/src/fsharp/FSharp.Build/Microsoft.FSharp.targets#L307

I wonder why the fcs repo had this change?

Kevin

**Comment by enricosada** [comment]
https://github.com/fsharp/fsharp/commit/13c90698e0f6e8feb3443aa9a91a5b26183cdfe9

**Comment by enricosada** [comment]
@KevinRansom sure.

i tried to follow the history, seems was added by https://github.com/fsharp/fsharp/commit/948e2c78e4dec774e07b82adfd8f5c240adfb621

diff https://github.com/fsharp/fsharp/commit/948e2c78e4dec774e07b82adfd8f5c240adfb621#diff-49ce6451b286088fc986cb94c6e9abab

**Comment by enricosada** [comment]
The way seems to be in same diff, removed code:

```
  <Target Name="ReorderCompileItems"		
      BeforeTargets="CoreCompile"		
      Condition="'$(GenerateTargetFrameworkAttribute)' == 'true' AND '$(AssemblyName)' == 'FSharp.Core'">  		
    <ItemGroup>		
        <!-- Infrastructure puts AssemblyAttributes.fs at the beginning of the list and this will result and error when compiling FSharp.Core because all primitive types are not defined yet - fixup is required-->		
        <CompileAfter Include="@(CompileBefore)"/>		
        <CompileBefore Remove="@(CompileBefore)"/>   		
    </ItemGroup>		
  </Target>		
```

so seems that was for avoid do ReorderCompileItems, without the FSharp.Core errors

**Comment by KevinRansom** [comment]
Cripes ... that's a bit interesting

what is it about the file that impacts the fsharp.core build.  It just has standard framework types in it.

Why does fsharp.core need it built at the end?

**Comment by dsyme** [comment]
FSharp.Core needs it at the end because the relevant types like "unit" don't exist at the start of the compilation

**Comment by enricosada** [comment]
I can add a property to choose behaviour 

`TargetFrameworkMonikerAssemblyAttributesAtEnd` => true/false

Something like that. by default is false, and put that at start (where should be usually).
the fsharp.core fsproj can just set that property to true.

can be ok?

**Comment by dsyme** [comment]
@enricosada I suppose so.  I hadn't considered the strange case of having a library with a ``[<EntryPoint>]``

**Comment by KevinRansom** [comment]
@enricosada the name is fine.

**Comment by Alxandr** [comment]
I think I just encountered something similar (at least I was linked to this issue). I'm trying to build a library targeting `netcoreapp2.0`. The reason I want a library, is that I don't want to have an entry point, and currently if I don't have an entrypoint, it blows up at runtime because statics aren't initialized (ie. let bindings are `null`). I tried settings `<OutputType>Library</OutputType>`, but that had no perceivable effect.

**Comment by Porges** [comment]
To follow up on @Alxandr's comment, a real bug here seems to be that `<OutputType>Library</OutputType>`  doesn't actually seem to have any effect, at least when targetting `netcoreapp2.0`. I found this while trying to fix https://github.com/Microsoft/visualfsharp/issues/1371.

When compiling my tests as `Library`, the "magic main" is still generated. I still have to add my own fake main to get the correct behaviour with the static constructor.

Further weirdness is that the properties for my `netcoreapp2.0` project still state "Console Application" when `OutputType` is set to `Library`. Changing it from "Console Application" to "Class Library" then has no effect on the project file, and if I re-open the properties page, it's back to "Console Application".

**Comment by ScottShingler** [comment]
@Porges Could you please provide an example of your "fake main" workaround?

**Comment by Porges** [comment]
@ScottShingler  See the commit I linked above, the function marked with `[<EntryPoint>]`: https://github.com/hedgehogqa/fsharp-hedgehog/commit/4f5cdf247eaa1af7c7b48bbca551a073ea790a88#diff-3046bb7a7744b0da2e868c87e896d715R88

**Comment by dsyme** [comment]
THis is now working
