### ISSUE TITLE
Debugger info is incorrect for shadowed bindings

### ISSUE THREAD

**Issue by tldrlol** [dotnet/fsharp#3704]
#### Repro steps

On a windows 10, fresh VS2017 install

```fsharp
[<EntryPoint>]
let main _ =
  let x = 42
  let x = 7
  printfn "%d" x // breaking on this line, watch and tooltip say x=42
  0
```

![illustrated](https://i.imgur.com/YmoubfN.png)

#### Expected behavior

Tooltip will display `x` value of shadowing binding.

#### Actual behavior

Tooltip displays `x` value of shadowed binding.

**Comment by realvictorprm** [comment]
I know this issue..   It should behave the way around.

Am 07.10.2017 09:37 schrieb "Daniel Kirillov" <notifications@github.com>:

**Comment by drvink** [comment]
Adding refs: possibly same bug as #3141, possibly fixed in #3561

And some pretty pictures, just in case it's not the same bug:

vs2015: 

![vs2015-debug](https://user-images.githubusercontent.com/4315061/31306019-fef761d2-ab81-11e7-86a9-549c0f1e9031.png)

vs2017.3:

![vs2017-debug](https://user-images.githubusercontent.com/4315061/31306022-0c355c50-ab82-11e7-9930-5b2f17540095.png)

**Comment by vasily-kirichenko** [comment]
Rider has similar (but not the same on .NET Core projects) issues, I created a bug report https://youtrack.jetbrains.com/issue/RIDER-10227

/cc @auduchinok

**Comment by vasily-kirichenko** [comment]
.NET Core 2.0 in Ionide:

![1](https://user-images.githubusercontent.com/873919/31306159-a27d3582-ab52-11e7-99f3-84072b8f12c6.gif)

**Comment by dsyme** [comment]
@cartermp I presume we need our own debug engine for this in VS.  Unless we restrict the range of the first local.  Perhaps we could reverse the order we emit locals or the like, though I don't think there's any perfect solution

**Comment by BentTranberg** [comment]
Stumbled on this right now. Note that the types doesn't have to be equal for this problem to arise, and in my case it was an argument to the function that was shadowed with a local.

**Comment by vasily-kirichenko** [comment]
Still an issue in 2019 RC.4

![1](https://user-images.githubusercontent.com/873919/55228058-369eed80-522a-11e9-9f30-70a5a6246af2.gif)

**Comment by 2BitSalute** [comment]
I just encountered this in VS Code with Core debugger. Wasted at least an hour thinking that the API I was calling wasn't modifying the value.

**Comment by JordanMarr** [comment]
I chased my tail for a bit on this one last night (VS v16.9.0).

**Comment by dsyme** [comment]
Fixed and in main
