### ISSUE TITLE
hidden variable names leak into normal namespace

### ISSUE THREAD

**Issue by tldrlol** [dotnet/fsharp#3705]
```fsharp
let add _ _ = _arg1 + _arg2

[<EntryPoint>]
let main _ =
  printfn "%d" (add 1 2)
  0
```

The above snippet compiles, runs and works (as expected). I imagine this is an oversight, buggy behavior that was not intended to happen. Specifically, being able to alias the arguments denoted by the ignore pattern with `_arg[n]` syntax.

On the plus side, tooling (vanilla VS2017) does not offer Intellisense or anything of the sort in this situation.

**Comment by tldrlol** [comment]
Apologies, I should clarify.

While they do not appear in the completion lists, hovering over them reveals type information as normal.

**Comment by Krzysztof-Cieslak** [comment]
I can report same in VSCode - no intellisense, tooltips are working, finding usages is working

![image](https://user-images.githubusercontent.com/5427083/31306764-e369f0d6-ab56-11e7-9871-ed33e39fbca0.png)

![image](https://user-images.githubusercontent.com/5427083/31306772-1ef27416-ab57-11e7-9b2c-4babea718141.png)

**Comment by tldrlol** [comment]
I had to calm down before posting this, because this was too funny also: 😄 

I spoke too soon.

![tooling-help](https://i.imgur.com/qD9ylAT.png)
