### ISSUE TITLE
Why is TextWriter called twice in fprintfn?

### ISSUE THREAD

**Issue by goswinr** [dotnet/fsharp#3712]
To me it seems that using the function` fprintfn (textWriter: System.IO.TextWriter) fmt ` first calls
`textWriter.Write(theFormatedString)`
and then 
`textWriter.WriteLine()`

wouldn't it be more idiomatic to just call ` textWriter.WriteLine(theFormatedString)`  once?

The `WriteLine(somestring`)  implementation on TextWriter seem to be not used at all.

My current implementation of TextWriter prints to the UI. It does also context switching and UI update, so calling it just once instead of twice would make sense. or not ?

https://github.com/Microsoft/visualfsharp/blob/81d162ce55bd4c4c8bcd1eb2a0832c442888ec0e/src/fsharp/FSharp.Core/printf.fs#L1346

**Comment by forki** [comment]
Mhm I am not sure about the reason, but a quick way to learn more about it
is to send a Pull request which changes the call. Then we will see if it
breaks something.

Am 08.10.2017 12:00 schrieb "Goswin" <notifications@github.com>:

**Comment by dsyme** [comment]
@goswinr Yes, please just send a PR for this

**Comment by forki** [comment]
I gave it a shot. see https://github.com/Microsoft/visualfsharp/pull/3747

**Comment by forki** [comment]
@goswinr looks like it's calling it a lot more than just twice https://github.com/Microsoft/visualfsharp/pull/3747#issuecomment-336496735

**Comment by goswinr** [comment]
@forki really? I added some prefix to the textwriter and only noticed that it prints twice. I Will test again.

 Using `writline` instead of `write` is potentially breaking other existing applications that worked fine without fully implementing textwriter interface. Maybe just documenting the behavior is better?

**Comment by forki** [comment]
printfn "%s %s" "hello" "world" - will call 5 times write and one WriteLine

**Comment by forki** [comment]
At least this is what I see in debugger. Maybe I'm misunderstanding something

**Comment by dsyme** [comment]
Closing this old issue, there was a rewrite in the meantime, also this doesn't show on perf traces
