### ISSUE TITLE
FSX errors not in Error List after Open Folder

### ISSUE THREAD

**Issue by theprash** [dotnet/fsharp#3726]
1. Create a folder with an FSX file in it
2. Right click on the **folder** and select "Open in Visual Studio" (alternatively, start VS2017 directly, and do Open Folder on that folder)
3. Open the FSX file from the solution explorer
4. Write some non-compiling code

#### Expected behavior

The compile errors should be shown in the Error List.

#### Actual behavior

Errors are underlined red but they don't show in Error List.

#### Known workarounds

If you start VS by opening an FSX file or SLN file, and **then** run Open Folder, then errors appear as expected.

Visual F# Tools v15.4.1.17091801

**Comment by dsyme** [comment]
Could you show a screen shot of the Errors window please?  Do you have "Open Documents" or ... as your setting?

**Comment by theprash** [comment]
No, that's not it.

![image](https://user-images.githubusercontent.com/1362490/31392164-756d2810-add0-11e7-8aa7-39ec9e227351.png)

**Comment by dsyme** [comment]
@theprash Did you try the other settings?

**Comment by theprash** [comment]
@dsyme The other settings don't show the error either. But I would expect it to show for all 4 settings when it's the current document, like it does when I use the workaround mentioned above.

**Comment by dsyme** [comment]
@theprash Yes, I agree,

**Comment by cartermp** [comment]
This is resolved in VS 2019:

![image](https://user-images.githubusercontent.com/6309070/58294324-5eb85200-7d7e-11e9-9983-39a27c5de34a.png)
