### ISSUE TITLE
Assertion while opening Build project settings page

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#3733]
![image](https://user-images.githubusercontent.com/873919/31457682-265bc866-aec6-11e7-9d3e-e6617faa759e.png)

**Comment by cartermp** [comment]
given the switch to https://github.com/dotnet/project-system I'll close this out; the legacy project system will just remain where it is

**Comment by abelbraaksma** [comment]
I haven't seen this error in a while, I think it got resolved along the way (tested both legacy and new project formats).
