### ISSUE TITLE
VS crashes in debugger

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#3735]
Set breakpoint here:

![image](https://user-images.githubusercontent.com/873919/31460137-110eeaa8-aece-11e7-911c-561b46730ac2.png)

Hover over `projectSite.State`.

Result: VS (main instance) crashes.

**Comment by vasily-kirichenko** [comment]
Another repro: hover over `x` 

![image](https://user-images.githubusercontent.com/873919/31576691-7a57d4ca-b108-11e7-94d6-5bebde371823.png)

Debugging session immediately halts, the exp VS instance disappears.

**Comment by cartermp** [comment]
I've noticed certain values doing this as well.  IIRC it's usually on something like `FSharpEntity` or some other really large type.  No idea what could cause that.

**Comment by vasily-kirichenko** [comment]
I think we should try to get a process snapshot on crash and investigate it.

**Comment by cartermp** [comment]
This doesn't repro anymore. The case that used to do this - `FSharpEntity` - does not crash VS and I can get a tooltip for it just fine now. e.g.
![image](https://user-images.githubusercontent.com/6309070/110719435-b4632600-81c1-11eb-8984-728fa60199ad.png)
