### ISSUE TITLE
Class let values are not available in closures when debugging

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#3759]
However, the value is visible via strange `this.__.` qualifier:

![image](https://user-images.githubusercontent.com/873919/31587908-ab5e9bf4-b1f2-11e7-80a0-62246459cf88.png)

**Comment by vasily-kirichenko** [comment]
Another example. This time the path is `this.@this.`:

![image](https://user-images.githubusercontent.com/873919/31588383-bb369214-b1f9-11e7-825b-7a5583ad0e28.png)

**Comment by vasily-kirichenko** [comment]
Rider debugger works the same way.

**Comment by dsyme** [comment]
This is because the captured values are no longer available via the implicit `this` pointer.

We really need to both capture more values and have an F# expression evaluator in order to resolve this.
