### ISSUE TITLE
RoslynHelpers.StartAsyncAsTask should wrap and rethrow exceptions

### ISSUE THREAD

**Issue by brettfo** [dotnet/fsharp#3791]
[This](https://github.com/Microsoft/visualfsharp/blob/915347458cadbb4cd18f1dc0d4c88ddbb8793687/vsintegration/src/FSharp.Editor/Common/RoslynHelpers.fs#L119) helper is swallowing exceptions and should probably be replaced with a failfast or Watson.

**Comment by dsyme** [comment]
Closing out this old issue as the code has changed a lot
