### ISSUE TITLE
The tooltip on the parameter of the interface method is wrong

### ISSUE THREAD

**Issue by hafuu** [dotnet/fsharp#380]
#### Description:

 I define interface method and give same name for the parameter that defined by another place.
Put mouse cursor to the parameter that I defined.
Tooltip displays another definition what I don't expect.
#### Repro Steps:

``` fsharp
type Foo = interface
  abstract Bar: query: string -> int
end
```
#### Expected:

The tooltip displays nothing.
#### Actual:

The tooltip displays `Core.ExtraTopLevelOperators.query`.
#### Version: Language, compiler, library, platform version

VS2013
#### Link:

https://twitter.com/htid46/status/419240351107256320

**Comment by yukitos** [comment]
I can repro on VS2013.
When I define the `Class.Bar` method that accepts a `string` named `query` which has already defined in the core library, the named parameter `query` shows unexpected information when mouseover:

![image](https://cloud.githubusercontent.com/assets/1076180/7320448/8e71a9d0-ead7-11e4-9cdc-33ec14dd227e.png)

Here's another sample:

![image](https://cloud.githubusercontent.com/assets/1076180/7320686/0eb463f2-ead9-11e4-95f5-ddbc9f96c042.png)

**Comment by vzarytovskii** [comment]
Can't see it anymore
<img width="486" alt="image" src="https://github.com/dotnet/fsharp/assets/1260985/50fd7327-e36c-4120-8193-db2ce782e26e">
