### ISSUE TITLE
Move type suggestions out from compiler to an IDE analyzer

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#3886]
It's an expensive feature (comparable to Simplify Name and Unused Opens analyzers) and it should be used in tooling only, not in compilation, and should be turned off by default. As I understand, this feature is completely based on name resolution environment, so it's quite easy to make it an analyzer.

**Comment by cartermp** [comment]
Missed this one. It was done with https://github.com/dotnet/fsharp/pull/6063
