### ISSUE TITLE
Breakpoint set on a very different line

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#3902]
I think it's a new level of breakpoints weirdness:

![1](https://user-images.githubusercontent.com/873919/32513491-6a5c33c0-c40b-11e7-9f20-09f1c423508f.gif)

15.5 pre 3

**Comment by vasily-kirichenko** [comment]
Or try to debug `shouldProvideCompletion` function. Good luck :)

**Comment by dsyme** [comment]
Interesting, must be in our handling of ``a || b`` and ``a && b``. We should at least be committing a breakpoint before the start of these constructs

**Comment by vasily-kirichenko** [comment]
It jumps to _another_ method. This is something new.

**Comment by dsyme** [comment]
@vasily-kirichenko Yes indeed

**Comment by dsyme** [comment]
This is covered by #11980
