### ISSUE TITLE
F# Source Generation for embedded resources on the .NET Core SDK don't appear to work

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#3925]
Repro:
1.  In VS Create a new dotnet sdk F# project
2. In solution explore select the Add New Item context menu and add a new resource
3. Edit the generated .fsproj file and Add:
    <GenerateSource>true</GenerateSource>
    to the EmbeddedResource Item.

Build the solution with the Build verbosity set to normal and observe the response file in the output window.  Notice the source files do not include an entry for the resources.

E.g.
````
  --simpleresolution
1>  --nocopyfsharpcore
1>  C:\Users\kevinr\AppData\Local\Temp\.NETCoreApp,Version=v2.0.AssemblyAttributes.fs
1>  Program.fs
1>
```
Expected source code to be generated.

**Comment by dsyme** [comment]
@KevinRansom Any status on this one?  (Just going through existing Area-DotNetCore bugs)

**Comment by dsyme** [comment]
I'm closing out this old issue. @KevinRansom Please re-open if it's a thing
