### ISSUE TITLE
Setting the Use Standard Resource names option in the F# netstandard project properties does not work.

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#3927]
Setting the Use Standard Resource names option in the F# netstandard project properties does not work.

<img width="342" alt="screen shot 2017-11-10 at 7 53 58 pm" src="https://user-images.githubusercontent.com/5175830/32685969-1df80bc4-c651-11e7-8c3f-93ee4bd0cd9a.png">

Expected:  setting this option needs to set the setting in the project file.

**Comment by dsyme** [comment]
This setting no longer appears in the project properties in VS2022
