### ISSUE TITLE
Printing of type signatures has inaccuracies, especially from --sig:file.fsi

### ISSUE THREAD

**Issue by drvink** [dotnet/fsharp#393]
Printing of type signatures has inaccuracies, especially from --sig:file.fsi

1. See case https://github.com/Microsoft/visualfsharp/issues/2684

2. See case https://github.com/Microsoft/visualfsharp/issues/2685

2. See case https://github.com/Microsoft/visualfsharp/issues/675 

2. The type signatures printed by the compiler in error messages seem to be the most accurate (though not always entirely), but the ones printed by FSI and the signature file generator facility are particularly bad. As an example, try generating a signature file from the code in issue #392--it's almost entirely wrong (the signature file embedded in that issue was written mostly by hand, just to clarify).

**Comment by 0x53A** [comment]
``--sig`` also seems to have issues with quoted identifiers:

I am experimenting with a remoting protocol loosely based on actors (ReplyChannel, ask, tell, etc).

The implementation file looks like this:

```f#

    // two versions of ask, one for consumption from F#, one for consumption from C# (with Func<_> instead of the FSharp callback type)

    // Note: because of the '#' in the compiled name, this function is invisible to C#
    [<CompiledName("askF#")>]
    let ask (send: byte array -> byte array) (f: IReplyChannel<'TResponse> -> 'TMsg) : 'TResponse = // ... 

    [<CompiledName("Ask")>]
    let ``askC#`` (send: Func<byte array, byte array>) (f: Func<IReplyChannel<'TResponse>, 'TMsg>) : 'TResponse = // ...

```

when generating a signature file, it generates this:

```f#
    [<CompiledNameAttribute ("askF#")>]
    val ask :
      send:(byte array -> byte array) ->
        f:(IReplyChannel<'TResponse> -> 'TMsg) -> 'TResponse
    [<CompiledNameAttribute ("Ask")>]
    val ( askC# ) :
      send:System.Func<byte array,byte array> ->
        f:System.Func<IReplyChannel<'TResponse>,'TMsg> -> 'TResponse
```

Instead of ``val ( askC# )`` it should generate 

```
val ``askC#``
```

instead.

**Comment by PaigeM89** [comment]
I ran into an issue with where sig files incorrectly wrap long lines for literals:

```
  [<Literal>]
  let SomeLiteralWithASomewhatLongName = "hi"

  [<Literal>]
  let SomeLiteralWithASomewhatLongName2 = "SomeVeryLongLiteralValueWithLotsOfCharacters"

  [<Literal>]
  let ShortName = "SomeVeryLongLiteralValueWithLotsOfCharacters"
```

Generates

```
  module SomeStuff = begin
    [<LiteralAttribute ()>]
    val SomeLiteralWithASomewhatLongName : string = "hi"
    [<LiteralAttribute ()>]
    val SomeLiteralWithASomewhatLongName2 : string
    = "SomeVeryLongLiteralValueWithLotsOfCharacters"
    [<LiteralAttribute ()>]
    val ShortName : string = "SomeVeryLongLiteralValueWithLotsOfCharacters"
  end
  ```

**Comment by dsyme** [comment]
Closing as addressed by https://github.com/dotnet/fsharp/pull/12072
