### ISSUE TITLE
Symbols API: Empy value is returned for auto-property binding

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#3939]
```fsharp
namespace AutoProperty
               
type Class1() =  
    member val Foo = 123 with get, set
```
Using results of `GetAllUsesOfAllSymbolsInFile()`:

<img width="1067" alt="screen shot 2017-11-13 at 19 55 56" src="https://user-images.githubusercontent.com/3923587/32738089-f0eac992-c8ac-11e7-8f52-6f0097ab7f8e.png">
<img width="1141" alt="screen shot 2017-11-13 at 19 56 23" src="https://user-images.githubusercontent.com/3923587/32738095-f3073abc-c8ac-11e7-89d6-7f9e018e4843.png">

`mfv.EnclosingEntity`, `mfv.IsProperty` return `false`.
`mfv.DisplayName`, `mfv.CompiledName` return `"v"`.

**Comment by cartermp** [comment]
Interestingly enough, #3762 (and another commit that made it into VS 15.4) made it so that autoprop symbols are shown with Find Refs and Inline Rename.  Both appear to be broken on 15.5 Preview 3.

**Comment by T-Gro** [comment]
Existing tests covering auto-property symbol resolution (confirming the fix):

- **AutoProperty with get, set has property symbol 01** — verifies `IsProperty`, `HasGetterMethod`, `HasSetterMethod`, and correct declaration range via `assertRange`:
https://github.com/dotnet/fsharp/blob/d04f46f4d3c2db8ee8dcd050dc56c6987f445e60/tests/FSharp.Compiler.Service.Tests/Symbols.fs#L614-L636

- **Property symbol is resolved for property** — verifies `SignatureLocation` for auto-property:
https://github.com/dotnet/fsharp/blob/d04f46f4d3c2db8ee8dcd050dc56c6987f445e60/tests/FSharp.Compiler.Service.Tests/Symbols.fs#L653-L665

- **AutoProperty with get has get symbol attached to property name** — verifies getter `SignatureLocation`:
https://github.com/dotnet/fsharp/blob/d04f46f4d3c2db8ee8dcd050dc56c6987f445e60/tests/FSharp.Compiler.Service.Tests/Symbols.fs#L689-L699

- **Signature text for auto property** — verifies correct `DisplayName` and signature text:
https://github.com/dotnet/fsharp/blob/d04f46f4d3c2db8ee8dcd050dc56c6987f445e60/tests/FSharp.Compiler.Service.Tests/Symbols.fs#L911-L920
