### ISSUE TITLE
Fix inability to set breakpoints inside lambdas

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#3944]
![image](https://user-images.githubusercontent.com/873919/32801142-44fccf90-c98d-11e7-952a-d445dae6c05f.png)

**Comment by auduchinok** [comment]
Apparently FCS returns correct ranges for the last two lines inside lambda. If it doesn't work for you, I think it may be related to #3902.
<img width="448" alt="screen shot 2017-11-14 at 22 57 49" src="https://user-images.githubusercontent.com/3923587/32801850-5dce224c-c98f-11e7-843a-aec3ee5cca8a.png">

However, if executed on the first line of lambda, there're ranges that shouldn't be returned.

<img width="521" alt="screen shot 2017-11-14 at 23 01 13" src="https://user-images.githubusercontent.com/3923587/32802033-e455f38a-c98f-11e7-9cd2-c6a912e6447a.png">

**Comment by cartermp** [comment]
This is no longer required and breakpoints set in the lamnda expression. Trtying to set one for `r` or `quals` isn't ideal, but this at least isn't required anymore.
