### ISSUE TITLE
Parameter info for auto-quoted Expr<'T> should just indicate 'T

### ISSUE THREAD

**Issue by latkin** [dotnet/fsharp#397]
When using the new auto-quotations feature in F# 4.0, the whole idea is that that caller doesn't need to explicitly create an `Expr<'T>`.

It would be nice if the IDE parameter info was keen on the feature, too.  Today we show the arg type as full `arg : Expr<'T>`, it would be cool if it only showed `arg : 'T` in this case.

![image](https://cloud.githubusercontent.com/assets/5943573/7422055/81eafade-ef3e-11e4-86b2-7ae0e0aa8335.png)

**Comment by dsyme** [comment]
Or at least it could show "ReflectedDefinition" as an attribute (I think it would be a bit misleading to show just 'T because of the cost inherent in calling a ReflectedDefintion method, and also because the semantics of the call are very different)
