### ISSUE TITLE
F# references C# interop not working correctly under dotnet core/sdk

### ISSUE THREAD

**Issue by forki** [dotnet/fsharp#4000]
I sent @cartermp a private zip with a company internal project that shows issues when referencing C# from F# under dotnet sdk in VS. This is only so that we don't forget about it

**Comment by dsyme** [comment]
@cartermp Was this one fixed? (just looking through old bugs...)

**Comment by cartermp** [comment]
Nope. I was hoping to point @TIHan at this after the file ordering business, but given the sweeping changes in VS 15.6 it may be worth re-evaluating. @forki I can't remember where I put the zip 😢  - could you send it again?

**Comment by cartermp** [comment]
Just confirming this one is not fixed:

1. Create .NET Core console app (F#)
2. Create .NET Standard library (C#)
3. Build solution
4. Open Program.fs

![image](https://user-images.githubusercontent.com/6309070/58261115-90a0c880-7d2c-11e9-9c6c-0af400ec52c9.png)

Reloading the project fixes the issue.

**Comment by dsyme** [comment]
@cartermp Any particular reason why you removed the priority label on this?  We should really have a priority on every bug issue shouldn't we?

**Comment by dsyme** [comment]
I did check and this still repros.  It should be fixed.  The F# project builder state should be dependent on a file watcher on the output DLL of the C# project.

**Comment by cartermp** [comment]
@dsyme see here, it's more complicated than that. This does not give deterministic behavior: https://github.com/dotnet/fsharp/issues/9301

**Comment by dsyme** [comment]
This no longer reproduces, I went through the repro steps here: https://github.com/dotnet/fsharp/issues/4000#issuecomment-495243764
