### ISSUE TITLE
Tests for extended completion 

### ISSUE THREAD

**Issue by TIHan** [dotnet/fsharp#4024]
In regards to this merged PR: https://github.com/Microsoft/visualfsharp/pull/4015 - it would be a good idea to have a test against it.

#

The test itself could be as such:

```fsharp
open System

let x = CurrentDire
```

With the cursor at ```CurrentDire```.

#

The original behavior before the merged PR:
![pr4015](https://user-images.githubusercontent.com/1278959/33293907-43d53bb6-d383-11e7-86a4-d4df8c97f96e.png)

Behavior with the merged PR:
![pr4015](https://user-images.githubusercontent.com/1278959/33293993-8b467b04-d383-11e7-8b1e-36a7c554dfa0.png)

**Comment by cartermp** [comment]
Resolved with #9126
