### ISSUE TITLE
Server GC mode for fsc.exe

### ISSUE THREAD

**Issue by latkin** [dotnet/fsharp#404]
I did some testing today, trying out [server GC mode](https://msdn.microsoft.com/en-us/library/ms229357%28v=vs.110%29.aspx) on fsc.exe.  Results look promising:

| Compiler | Target | Trials | Workstation GC | Server GC | % Improvement |
| --- | --- | --- | --- | --- | --- |
| proto debug fsc | Debug FSharp.Core.dll | 10 | 17.4 s | 15.1 s | 13.2% |
| proto debug fsc | Release FSharp.Compiler.dll | 3 | 64.2 s | 54.4 s | 15.3% |
| Release NGENed fsc | Test area fsharp\core\portable | 2 | 75.3 s | 70.5 s | 6.4 % |
| Release NGENed fsc | Test tool FSharp.Compiler.Hosted | 10 | 0.903 s | 0.705 s | 22.0 % |

FWIW the Roslyn command-line compilers use server GC.

Potential downsides:
- On single-core machines, server GC might actually be slower
- With server mode, GCs are less-frequent but bigger. Result is that process working set gets much larger in between GCs.
- Server mode gives higher throughput, but worse responsiveness (collections are more intrusive). That's ok for command-line compiler, but we would not want to change it for IDE language service compiler backend.

Note also that we already have [`GCLatencyMode.Batch`](https://msdn.microsoft.com/en-us/library/system.runtime.gclatencymode%28v=vs.110%29.aspx) enabled now in fsc, which gave us a nice perf boost.

I'll send a PR next week adding this, unless anyone objects.

**Comment by dsyme** [comment]
Well, that looks great :)

**Comment by dsyme** [comment]
@vzarytovskii @KevinRansom I'm reopening as I'd like to revalidate whether using gcServer is a perf win or not.  On bootstrapping the compiler it gives a noticeable slowdown.

**Comment by dsyme** [comment]
I was quite surprised to find out that we use server GC for fsc.exe on .NET Framework [which has an ​fsc.exe.config​ with GC Server enabled](https://github.com/dotnet/fsharp/blob/main/src/fsc/App.config#L6) as well as a few other settings.

You can see this applies in the product here:

    ​C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools\fsc.exe.config​

This surprised me.  My experiments on compiling-the-compiler show a 30% slowdown with this setting.  I think this should never have been re-enabled, despite what's reported above.  Either way we need to revalidate this setting.



When we build our .NET 6/7 compiler in `artifacts` is lays down a ​fsc.dll.config​ with ​<gcServer enabled="true"/>​ as well as a couple of other settings.  However I don't know if .NET 6/7 even takes any notice of these config files at all

**Comment by dsyme** [comment]
Closing in favour of https://github.com/dotnet/fsharp/issues/13739
