### ISSUE TITLE
Tests for a user typing a character to trigger completions

### ISSUE THREAD

**Issue by TIHan** [dotnet/fsharp#4069]
Making an issue for providing tests against ShouldTriggerCompletion that is in CompletionProvider.fs. 

Meaning, we should provide tests that does an accurate simulation of when a user types a character that kicks off ShouldTriggerCompletion and the following completions appear.

**Comment by EddCodesDotNet** [comment]
Hey @TIHan - is this still something you need? If so I'll take a look as my inital contribution!

**Comment by TIHan** [comment]
To answer your question, I don't think we need anything here other than some work.

My initial gut feeling for testing this is to look at Roslyn, https://github.com/dotnet/roslyn, to see if we could do something similar. However, that may be too complicated.

An easier and better route would be to simply try to write unit tests surrounding `ShouldTriggerCompletion`. I would go that route first. I think my original statement on accurate simulation is probably not what we want in the beginning; I now prefer small unit testable pieces. 

I'm happy for you to do this as your first contribution. :) We always and will forever need tests; it helps get your foot in the door to contributions.

If you have any more questions regarding this, feel free to ask here or F# foundation slack.

**Comment by dsyme** [comment]
Closing out this old issue

**Comment by dsyme** [comment]
Searching the codebase there are a load of tests for this API
