### ISSUE TITLE
Completion suggests all symbols in scope at open namespece position

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#4078]
![image](https://user-images.githubusercontent.com/873919/33776802-999a8f82-dc53-11e7-9df1-68f326b0a13d.png)

**Comment by TIHan** [comment]
@vasily-kirichenko I assume this wasn't happening at some point considering I see a CompletionContext for OpenDeclaration. If so, then this is a regression.

**Comment by TIHan** [comment]
Never mind. I see.

```open S^``` will result in the correct behavior of showing namespaces/modules because we have something.
```open ^``` will not and basically the parser gives us nothing.

**Comment by TIHan** [comment]
Let's see how this goes: https://github.com/Microsoft/visualfsharp/pull/4106 - currently this fixes the problem, but the implementation may need to be changed.

**Comment by kerams** [comment]
This is fixed in main thanks to @auduchinok.

![image](https://github.com/dotnet/fsharp/assets/5063478/77dd7c55-bd7b-465b-b04a-bfe29fb2a714)
