### ISSUE TITLE
Rename refactor poor performance

### ISSUE THREAD

**Issue by cmeeren** [dotnet/fsharp#4110]
Often when I rename (F2, or right-click -> Rename), the renaming takes a very long time. Specifically, the symbol (if it's colored) is non-colored for a long while (~2-10 seconds), and if I try to rename something else in the meantime, I often get the "Finding token to rename" dialog, not infrequently ending with an error dialog:

![error](https://user-images.githubusercontent.com/7766733/33873373-fd858fb4-df1a-11e7-9212-46af2b5c333b.png)

Due to the non-determinism inherent to this performance problem, it seems difficult to reliably reproduce. For example, I can't seem to reproduce this with a minimal solution; I experience it in a moderately large solution (a few tens of projects, though only one of them actually reference the project I am usually renaming in, and no other projects reference that project again, so the project dependency graph is very shallow in this particular case).

I'm using VS15.5 and latest VF# nightly. I can't remember the rename performance being this bad in previous versions of VS, but I may be wrong.

**Comment by vasily-kirichenko** [comment]
I don't recommend to use Rename refactoring feature on anything, but local variables and arguments.

**Comment by cmeeren** [comment]
Why not? Even with poor performance it seems to me it catches most usages of symbols now (much better than a few months ago), so AFAIK it's better to use it than to manually track down every single usage of a symbol.

Are there any caveats I don't know about?

**Comment by cmeeren** [comment]
I think so, yes.

**Comment by cartermp** [comment]
Can you try to play around with this with F# Nightlies uninstalled?  You can run this to quickly uninstall:

```
VSIXInstaller.exe /u:VisualFSharp
```

If it seems okay without nightlies, then we can narrow this down a bit.

**Comment by cmeeren** [comment]
Still happens without nightlies.

**Comment by cartermp** [comment]
Thanks @cmeeren.  Well, the good news is that this is probably not due to a recent problem.  The bad news is it could be literally anything at this point 😢

**Comment by piaste** [comment]
Using nightlies, renaming local variables works everywhere, but renaming types and functions doesn't work at all for me (with one exception):

 * The rename popup says "Rename will update 0 references in 0 files"
 * As soon as I type one character, the popup closes and all the other references are unchanged

Exception: for some reason, within the last file in the project (`Program.fs`), renaming types and functions *does* work properly.

**Comment by vasily-kirichenko** [comment]
Don’t forget that all files must be saved to disk before renaming, because FCS cannot get dirty buffers content while performing whole project checking.

**Comment by realvictorprm** [comment]
Sorry for asking the stupid question. Is this the same for C# / Roslyn?
(Which languages perform differently here?)

Am 20.12.2017 20:59 schrieb "Vasily Kirichenko" <notifications@github.com>:

**Comment by cartermp** [comment]
Closing this out with no specific repro. As of VS 16.6 the core routine that finds symbols is significantly faster. That said, when there are a lot of symbols to read through (especially if there is no cache), it will take time. A better solution in the long run is to keep an always up-to-date symbol cache and operate purely on that. But for now, it's about as optimized as it can be with the current design.
