### ISSUE TITLE
VS: Use VSSDK Pattern Matcher

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#4116]
Starting with 15.6, the VS editor is going to have the [Pattern Matcher](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/PatternMatching/PatternMatcher.cs) available as an API.  [MyGet feed here](https://vside.myget.org/gallery/vssdk).

This will allow us to remove our [internal copy](https://github.com/Microsoft/visualfsharp/tree/master/vsintegration/src/FSharp.LanguageService.Base/PatternMatcher) of Roslyn's version from a while ago, and will allow us to remove the dependency on FSharp.LanguageService.Base that FSharp.Editor has.

**Comment by forki** [comment]
What does this thing do exactly?

Am 14.12.2017 05:15 schrieb "Phillip Carter" <notifications@github.com>:

**Comment by vasily-kirichenko** [comment]
@forki it's used in Go to All feature to search symbols. I doubt anybody uses it though.

**Comment by cartermp** [comment]
Also @forki earlier this year, @vasily-kirichenko ported it over (and some of its source-based dependencies) from Roslyn, because the Roslyn version was inaccessible with no plans to open it up. Since then, the editor team has forked the codebase, put it into the editor layer, and are exposing it for consumers starting with 15.6. Since they'll be maintaining this for all users of the assembly it'll be in, we should use that one moving forward.

**Comment by majocha** [comment]
Done in #14746.
