### ISSUE TITLE
Switching configuration doesn't update #defines on .NET Standard

### ISSUE THREAD

**Issue by piaste** [dotnet/fsharp#4145]
Possibly related to #4091.  

If you have the following in a .NET Standard project:

```
#if DEBUG
let x = foo
#else
let x = bar
#endif
```

and you switch from Debug to Release, the `let x = foo` part stays white and keeps Intellisense while  `let x= bar` stays grey and inactive. You need to close and reload the solution for the defines to be updated properly

In old SDK projects this gets updated correctly. The actual compilation behaves correctly either way.

VS2017 15.5.2, VF# Nightly

**Comment by cartermp** [comment]
This was a longstanding issue in the .NET SDK-style project system that was resolved in VS 2019:

![config-works](https://user-images.githubusercontent.com/6309070/58261703-ac589e80-7d2d-11e9-95de-f77abca4d7e3.gif)
