### ISSUE TITLE
fsproj PropertyGroup values not working

### ISSUE THREAD

**Issue by noelmcgrath** [dotnet/fsharp#4157]
PropertyGroup properties set in file do not show up in built dll

#### Repro steps

Steps

1. Create blank solution
2. Create f# .net standard class library
3. Create c# .net standard class library

![image](https://user-images.githubusercontent.com/671790/34291353-d263db0c-e6f3-11e7-8db4-d64d88d7670a.png)
4. For each project, right click, select properties and select Package
 or set via proj file
![image](https://user-images.githubusercontent.com/671790/34291413-0a150878-e6f4-11e7-83ea-8751db2b87c9.png)

5. Set values e.g. Package version, Product Name in each one
6. Build the solution
7. View the dll properties for both dll's

#### Expected behavior

PropertyGroup settings would be reflected in the file details section

#### Actual behavior

Only works in csproj, not in fsproj
csproj
![image](https://user-images.githubusercontent.com/671790/34291698-5c775e4e-e6f5-11e7-84c9-e391ce0a75d3.png)

fsproj
![image](https://user-images.githubusercontent.com/671790/34291726-7c89d626-e6f5-11e7-8035-ee11554e22c5.png)

#### Known workarounds

na

#### Related information 
na

**Comment by cartermp** [comment]
Can reproduce. It's worth noting that the generated nuspec file from pack does indeed have everything, though:

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>ClassLibrary1</id>
    <version>1.0.0</version>
    <authors>Phillip</authors>
    <owners>Phillip</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>I don't have one.</description>
    <releaseNotes>There is no release</releaseNotes>
    <copyright>(c) my kitty</copyright>
    <tags>nope</tags>
    <repository type="nope" url="nope" />
    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <dependency id="FSharp.Core" version="4.2.3" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```

So this is definitely a small bug in how we build. It's unknown to me if this is something handed in the project system or here.  @Pilchie would you have an idea?

**Comment by noelmcgrath** [comment]
Thanks cartermp.
If building on build server as part of a deployment where class library is part of a product deployment and we want to ensure that all dll's are traceable to a build number I think this is kind off important.
Any idea on when this will be fixed?

**Comment by cartermp** [comment]
No timeline for now (most folks are still on holiday break), but given that a pack operation works, I suspect it’s a quick fix. The next major release that could have such a fix will be in a few months. 

That said, you could probably accomplish this with a FAKE script that uses [one or more APIs it supports](http://fake.build/apidocs/) as a part of your build process. I wouldn’t know precisely how to do this best, but even a simple script which writes build info to a file could suffice.

**Comment by cartermp** [comment]
This is now supported as of VS 2019.

![image](https://user-images.githubusercontent.com/6309070/58294482-30874200-7d7f-11e9-856f-a47fa8d4d1ae.png)
