### ISSUE TITLE
Inline generic parameters in tooltips

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#4164]
![image](https://user-images.githubusercontent.com/873919/34319163-17f1db30-e7ec-11e7-87f3-f9a527591c62.png)
![image](https://user-images.githubusercontent.com/873919/34319165-3b635e72-e7ec-11e7-8cc3-6aa639e32f01.png)

It'd be much more readable if the generic parameters concrete types were just inlined into the signature itself, like C# editors do. I.e. the above signature should look like this:

![image](https://user-images.githubusercontent.com/873919/34319183-cc849e2a-e7ec-11e7-92db-8f94e9a75cd1.png)

Or maybe something like `Flow<'t: int, 'u: int, 'mat: obj>` would be even better.

https://github.com/ionide/ionide-vscode-fsharp/issues/685

**Comment by cartermp** [comment]
@dsyme's comments here mirror my own: https://github.com/Microsoft/visualfsharp/pull/2929#issuecomment-297795642

Put differently, I'd definitely be in favor of this, but I think that a prerequisite would be that the way QuickInfo is done in VF# would need to be changed to what Ionide and VS for Mac do.  Otherwise, we'd have a lot of weird line wrap issues with long signatures.

**Comment by 0x53A** [comment]
I agree in this specific case, but still prefer them explicit over-all.

The first reason is that generic types can be nested and become really long, the second is that it is often easier to see the actual types I care about.

Example:

```F#
open System.Linq
open System.Collections.Generic

type MyReallyLongUnion =
| WithSomeLongCase of int

let a = [| 1,"2", WithSomeLongCase 3 |]

let _ = a.GroupBy(fun (x,y,z) -> (y,z))
```

![image](https://user-images.githubusercontent.com/4236651/34737052-31b6069a-f575-11e7-9faa-47fabdc896c8.png)

here I instantly see the three things I care about:
 * It is the linq method GroupBy
 * the input is a 3-tuple
 * the output is a 2-tuple

(My main pc is currently broken, so the screenshot is from [fable.io/repl](fable.io/repl), but afaik it is exactly equal to how VS displays it).

If this was inlined, I would need to mentally parse all this IEnumerable / IGrouping stuff and extract the inputs / outputs mentally.

So, 👍 to make it configurable, 👎 to change it globally
