### ISSUE TITLE
Visual Studio Task List Support (e.g. // TODO: ...)

### ISSUE THREAD

**Issue by Rickasaurus** [dotnet/fsharp#4175]
Please provide a succinct description of the issue.

In VS2015 the VS task list feature worked great, in VS2017 it seems to be completely missing.

#### Repro steps

Provide the steps required to reproduce the problem

1. Make new F# library project
2. Create lines like // TODO: Make the thing
3. Check the task list (under views), there's nothing in it

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

#### Expected behavior

Lists the TODO, HACK and other Task list lines

#### Actual behavior

Empty task list

#### Known workarounds

None.

#### Related information 

Member of my team use this feature heavily while iterating. Would be really nice to have it back. Seems like a small thing.

* Operating system: 
Window 10 Latest
* Branch 
VS 15.5.1
* .NET Runtime, CoreCLR or Mono Version 
4.6.1
* Editing Tools (e.g. Visual Studio Version)
VS 15.5.1
* Links to F# RFCs or entries on https://github.com/fsharp/fslang-suggestions
* Links to performance testing scripts
* Indications of severity
Point of friction in finally getting my team onto VS2017, we're still using VS2015

**Comment by Rickasaurus** [comment]
More info on how this feature should work: https://msdn.microsoft.com/en-us/library/txtwdysk.aspx

**Comment by vasily-kirichenko** [comment]
In VS 2015 it was implemented in VFPT. I suggest to use Rider:

![image](https://user-images.githubusercontent.com/873919/34490573-4a1fcace-eff1-11e7-8a13-60dad6a0246e.png)

**Comment by Pilchie** [comment]
I think if F# implements [`ITodoCommentService`](https://github.com/dotnet/roslyn/blob/932e4243918aae174216230a81056713e92a304b/src/Features/Core/Portable/TodoComments/ITodoCommentService.cs#L43), they will get the rest of the implementation from Roslyn.

@TIHan

**Comment by TIHan** [comment]
I'll look at this.

**Comment by Rickasaurus** [comment]
Heya, any luck?

**Comment by TIHan** [comment]
I only briefly look at this. My priority lately has been file ordering in the sdk project-system.

**Comment by Rickasaurus** [comment]
Team members are still bugging me about this. They used it a lot previously.

**Comment by irie612** [comment]
Any update on this?

**Comment by T-Gro** [comment]
Done via #14944
