### ISSUE TITLE
Single case Discriminated Union in F#, same name for type and label

### ISSUE THREAD

**Issue by CHBen** [dotnet/fsharp#4185]
https://stackoverflow.com/questions/48179998/single-case-discriminated-union-in-f-same-name-for-type-and-label

F# has some difficulty when the TypeName and LabelName for a discriminated union type are the same.

This is not an urgent issue, but I would like to report it.

#### Repro steps

We start with the code in this file:

```F#
module ORDERS

type OrderId =           // TypeName
    | OrderId of string  // LabelName: same as TypeName!
    with 
    static member getValue (OrderId orderId) =
        orderId
```

In a different file, we can use the discriminated union like this:

```F#
// CODE#1: This code works.
module Application
open ORDERS

let x = OrderId "1111"
let extractedValue = 
    x 
    |> OrderId.getValue
```

However, if we remove the `open ORDERS`, and replace the other code with their full name, then we get a code that will not compile:

```F#
// CODE#2: This code fails.
module Application

// This is OK
let x2 = ORDERS.OrderId "11111"

// This has error!
let extractValue2 = 
    x2
    |> ORDERS.OrderId.getValue
```

I believe the reason is that in the second code, F# cannot differentiate the TypeName "OrderId", and the LabelName "OrderId"

#### Expected behavior

Expected the second case to compile as well, or at least either both CODE#1 and CODE#2 both pass or both fail.

#### Actual behavior

Code#1 passes, but Code#2 fails.

#### Known workarounds

If we use different name for the Type and the UnionLabel, then it is easier.

```F#
module ORDERS
type OrderIdType =            // TypeName
    | OrderIdLabel of string  // LabelName: different from TypeName!
    with 
    static member getValue (OrderIdLabel orderId) =
        orderId
```

Also, as mentioned by Fyodor Soikin in the stackoverflow comment, by using an alias, the following code also passes:

```F#
// CODE#3, this passes
module Application

type T = ORDERS.OrderId

let x3 = ORDERS.OrderId "11111"

let extractValue3 = 
    x3
    |> T.getValue
```

Thank you.

**Comment by dsyme** [comment]
This does seem inconsistent

If it helps, another workaround is to use ``RequireQualifiedAccess``:

```
// CODE#2: This code fails.
module ORDERS =

    [<RequireQualifiedAccess>]
    type OrderId =           // TypeName
        | OrderId of string  // LabelName: same as TypeName!
        static member getValue (OrderId orderId) =
            orderId
    // This is OK
let x2 = ORDERS.OrderId "11111"

let extractValue2 = 
    x2
    |> ORDERS.OrderId.getValue
```

**Comment by NatElkins** [comment]
Just want to chime in that I think I hit this bug too.  But it's not just for single case unions where the type and case have the same name (which are super common nowadays BTW...thank Scott Wlaschin).  Here's another example, but the error occurs on the `ControlGroup` case in the type `Test2`.

```fsharp
module Variants =
    type Test1 =
        | ControlGroup of int
        | GroupA of int
    
    type Test2 =
        | ControlGroup of int
        | Test2 of int

let test1Opt = obj() :?> Variants.Test1 option
let test2Opt = obj() :?> Variants.Test2 option

let works =
    match test1Opt with
    | None -> true
    | Some(Variants.Test1.ControlGroup(_)) -> false
    | Some(Variants.Test1.GroupA(_)) -> false

let doesntWork = 
    match test2Opt with
    | None -> false
    | Some(Variants.Test2.ControlGroup(_)) -> true
    | Some(Variants.Test2.TestA(_)) -> true
```

**Comment by gusty** [comment]
For the records: I reported this issue (by email, there was no F# in github at that time) when F# 3.0 was released.

In F# 2.0 it worked fine, I remember because I had to adapt my code in order to compile it in F# 3.0

So, this is a breaking change.

Here's what I reported and the answer I got at that time:

```
type MyType = MyType with
    member this.MyMember x = x
    static member MyStaticMember(MyType,x) = MyType.MyMember x
```

Answer:

Thanks for the report.
 
I don’t think we were previously aware of this; our assessment is that the F# 3.0 behavior is correct and 2.0 was a bug.

I am curious how you discovered it; my assessment is that this only affects single-case unions that carry no data, and I cannot think of a scenario where it is useful to create such a type in practice, so I am wondering how you found it, or if you know of some other more ‘common’ scenario that causes this minor breaking change in name resolution to show up to users.

**Comment by abelbraaksma** [comment]
Is this issue possibly related to / the same as when you hit F12 to go to definition that you hardly ever go to the actual definition, but to the label instead, even though you are standing on an instance of the type?

Normally, hitting F12 on the type (i.e., in `| Foo as Foo`, from the 2nd `Foo`) should go to the definition of `Foo`, but it stays on the same location instead.

If it isn't related, I'll report that separately.

**Comment by abelbraaksma** [comment]
Hmm, probably it isn't related, I reported it here: #4640.

**Comment by amieres** [comment]
I also encountered the same issue.
When trying to access a static member of a generic type produces the message `The instantiation of the generic type 'W' is missing and can't be inferred from the arguments or return type of this member. 
Consider providing a type instantiation when accessing this type, e.g. 'W<_>'.`  :

As expected following the suggestion, adding `<_>` removes the message:

```
type W<'a> = W0 of 'a 
                        with static member WStatic(e:string) = e.ToUpper() |> W0
                        
W        .WStatic "hello" |> print  // The instantiation of the generic type 'W' is missing and can't be inferred from the arguments or return type of this member. 
                                    // Consider providing a type instantiation when accessing this type, e.g. 'W<_>'.
W<_>     .WStatic "hello" |> print  // it works!
W<string>.WStatic "hello" |> print  // it works!

```


But if the Label has the same name as the type, the proposed solution does not work showing the error: `Unexpected type arguments`


```
type X<'a> = X  of 'a 
                        with static member XStatic(e:string) = e.ToUpper() |> X

X        .XStatic "hello" |> print  // The instantiation of the generic type 'W' is missing and can't be inferred from the arguments or return type of this member.
                                    // Consider providing a type instantiation when accessing this type, e.g. 'X<_>'.
X<_>     .XStatic "hello" |> print  // Unexpected type arguments
X<string>.XStatic "hello" |> print  // Unexpected type arguments
```

Using a type alias is a good workaround:
```
type XX<'a> = X<'a>

XX        .XStatic "hello" |> print  // The instantiation of the generic type 'W' is missing and can't be inferred from the arguments or return type of this member.
                                     // Consider providing a type instantiation when accessing this type, e.g. 'X<_>'.
XX<_>     .XStatic "hello" |> print  // it works!
XX<string>.XStatic "hello" |> print  // it works!

```

**Comment by daveyshindig** [comment]
My team has been encountering a case that looks like it's related. When we have identically named a module, LabelName, and TypeName, we see unexpected errors when referencing them from other files. 

**Repro**
Foo.fs:
```
type Foo = Foo of int
module Foo =
    let hello () = "Hello, world!"
```

Baz.fs
```
let x = Foo.1
let y = Foo.hello () //error
```

**Expected :** The value of `y` should be our string.

**Actual:** Compiler error, "field, constructor or member 'foo' is not defined', even though IntelliSense is shows that such a function exists.

**Workaround:** Create an alias of the module such as `let Z = Foo` allows us to use its functions.

**Comment by Happypig375** [comment]
@dsyme The `[<RequireQualifiedAccess>]` workaround doesn't work in this case:
```
> module A =
    [<RequireQualifiedAccess>]
    type B = C of string
    [<RequireQualifiedAccess>]
    type B' = B of B

module Z =
    let y x =
        match x : A.B with
        | A.B.C h -> 1;;

          | A.B.C h -> 1;;
  --------------^

stdin(10,15): error FS1127: This is not a constructor or literal, or a constructor is being used incorrectly
```

**Comment by dsyme** [comment]
I'm closing this in favour of this language suggestion since any changes will need an RFC https://github.com/dotnet/fsharp/issues/4185
