### ISSUE TITLE
InvalidProgramException from Discriminated Union with unclear Units Of Measure (Debug)

### ISSUE THREAD

**Issue by marklam** [dotnet/fsharp#4189]
A DU which is generic over UOM can give an invalid program exception.

#### Repro steps
This type declaration and instance creation caused the problem in a .net framework test case, and in a .netcore console app 

```fsharp
type Foo<[<Measure>]'x> = | Foo of int<'x> list

[<EntryPoint>]
let main _argv =
    let z = Foo []
    0
```

#### Expected behavior

nothing

#### Actual behavior

InvalidProgramException running the debug build

#### Known workarounds

* Build in release
* Add a type declaration to z

#### Related information 

* Operating system Windows 10
* Visual F# 4.1
* .net 4.7.1 or .net core 2
* Visual Studio 2017
* Kills the JIT

**Comment by dsyme** [comment]
Thanks for the report, we must be forgetting to erase a UoM parameter somewhere.

**Comment by dsyme** [comment]
This no longer repros
