### ISSUE TITLE
F# .NET Framework project referencing .NET Standard project is rebuilt every time (never up-to-date)

### ISSUE THREAD

**Issue by loop-evgeny** [dotnet/fsharp#4212]
An F# project targetting .NET Framework 4.6.2 that references a C# class library project targetting .NET Standard 2.0 is rebuilt every time the solution is built in VS, even when nothing changes.

#### Repro steps

Build the solution [FSharpRef-after-upgrade.zip](https://github.com/Microsoft/visualfsharp/files/1644477/FSharpRef-after-upgrade.zip) multiple times. 

#### Expected behavior

After the first build all projects are considered up-to-date and not rebuilt:
```
========== Build: 0 succeeded, 0 failed, 4 up-to-date, 0 skipped ==========
```
#### Actual behavior

Projects FSharpLib and FSharpExe are rebuilt every time:
```
========== Build: 2 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========
```

#### Known workarounds

None

#### Related information 

CSharpLib is a C# .NET Standard 2.0 project that was originally created as a .NET Framework 4.6.2 library ([FSharpRef-before-upgrade.zip](https://github.com/Microsoft/visualfsharp/files/1644478/FSharpRef-before-upgrade.zip)).

Note that this problem does not happen with C# projects - CSharpExe, which remains on .NET Framework 4.6.2 and also references CSharpLib is considered up-to-date, as expected.

* Operating system: Windows 7 x64
* .NET Runtime: 4.6.2
* Visual Studio Version: 15.5.4
* MSBuild: 15.5.180.51428
* fsc.exe: 4.1

**Comment by Pilchie** [comment]
Tagging @panopticoncentral

**Comment by panopticoncentral** [comment]
This is an issue with the non-CPS F# project system (which is what these projects seem to be). Does it even do a fast up to date check? It might be by design for the moment.

**Comment by loop-evgeny** [comment]
I have set U2DCheckVerbosity=1 and here's the output I get from building the solution:

```
1>FastUpToDate: Latest write timestamp on input is 22/01/2018 9:51:35 AM on 'C:\W ork\Bugs\FSharpRef\CSharpLib\obj\CSharpLib.csproj.nuget.g.targets'. (CSharpLib)
1>FastUpToDate: Earliest write timestamp on output is 22/01/2018 9:51:58 AM on 'C:\W ork\Bugs\FSharpRef\CSharpLib\obj\Debug\netstandard2.0\CSharpLib.dll'. (CSharpLib)
1>FastUpToDate: Project is up to date. (CSharpLib)
2>Checking whether FSharpExe needs to be rebuilt:
2>   Output: 22/01/2018 9:52:00 AM C:\W ORK\BUGS\FSHARPREF\FSHARPEXE\OBJ\DEBUG\FSHARPEXE.EXE
2>   Output: 22/01/2018 9:52:00 AM C:\W ORK\BUGS\FSHARPREF\FSHARPEXE\BIN\DEBUG\FSHARPEXE.XML
2>   Output: 22/01/2018 9:52:00 AM C:\W ORK\BUGS\FSHARPREF\FSHARPEXE\OBJ\DEBUG\FSHARPEXE.PDB
2>   Output: 22/01/2018 9:52:00 AM C:\W ORK\BUGS\FSHARPREF\FSHARPEXE\BIN\DEBUG\FSHARPEXE.EXE
2>   Output: 22/01/2018 9:52:00 AM C:\W ORK\BUGS\FSHARPREF\FSHARPEXE\BIN\DEBUG\FSHARPEXE.PDB
2>   Input: 18/01/2018 10:06:03 PM C:\W ORK\BUGS\FSHARPREF\FSHARPEXE\FSHARPEXE.FSPROJ
2>   Input: 18/01/2018 10:02:08 PM C:\W ORK\BUGS\FSHARPREF\FSHARPEXE\ASSEMBLYINFO.FS
2>   Input: 18/01/2018 10:05:33 PM C:\W ORK\BUGS\FSHARPREF\FSHARPEXE\PROGRAM.FS
2>   Input: 18/01/2018 10:02:08 PM C:\W ORK\BUGS\FSHARPREF\FSHARPEXE\APP.CONFIG
2>Declaring project NOT up to date, can't find expected input C:\W ORK\BUGS\FSHARPREF\CSHARPLIB\BIN\DEBUG\NETSTANDARD2.0\
2>------ Build started: Project: FSharpExe, Configuration: Debug Any CPU ------
3>Checking whether FSharpLib needs to be rebuilt:
3>   Output: 22/01/2018 9:52:01 AM C:\W ORK\BUGS\FSHARPREF\FSHARPLIB\OBJ\DEBUG\FSHARPLIB.DLL
3>   Output: 22/01/2018 9:52:01 AM C:\W ORK\BUGS\FSHARPREF\FSHARPLIB\BIN\DEBUG\FSHARPLIB.XML
3>   Output: 22/01/2018 9:52:01 AM C:\W ORK\BUGS\FSHARPREF\FSHARPLIB\OBJ\DEBUG\FSHARPLIB.PDB
3>   Output: 22/01/2018 9:52:01 AM C:\W ORK\BUGS\FSHARPREF\FSHARPLIB\BIN\DEBUG\FSHARPLIB.DLL
3>   Output: 22/01/2018 9:52:01 AM C:\W ORK\BUGS\FSHARPREF\FSHARPLIB\BIN\DEBUG\FSHARPLIB.PDB
3>   Input: 18/01/2018 10:06:50 PM C:\W ORK\BUGS\FSHARPREF\FSHARPLIB\FSHARPLIB.FSPROJ
3>   Input: 18/01/2018 10:02:28 PM C:\W ORK\BUGS\FSHARPREF\FSHARPLIB\ASSEMBLYINFO.FS
3>   Input: 18/01/2018 10:06:50 PM C:\W ORK\BUGS\FSHARPREF\FSHARPLIB\FSHARPLIB.FS
3>Declaring project NOT up to date, can't find expected input C:\W ORK\BUGS\FSHARPREF\CSHARPLIB\BIN\DEBUG\NETSTANDARD2.0\
3>------ Build started: Project: FSharpLib, Configuration: Debug Any CPU ------
2>	FSharpExe -> C:\W ork\Bugs\FSharpRef\FSharpExe\bin\Debug\FSharpExe.exe
3>	FSharpLib -> C:\W ork\Bugs\FSharpRef\FSharpLib\bin\Debug\FSharpLib.dll
========== Build: 2 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========
```

**Comment by cartermp** [comment]
@panopticoncentral It like like it, yes: https://github.com/Microsoft/visualfsharp/blob/aac14d3ca43ee57cae60c1ad9e35c165f559e872/vsintegration/tests/unittests/LegacyProjectSystem/Tests.ProjectSystem.UpToDate.fs#L319

This is based on the old MPF project system.

**Comment by cartermp** [comment]
The F# projects aren't rebuilt as of VS 2019:
![building-uptodate](https://user-images.githubusercontent.com/6309070/58345607-9d491d80-7e0d-11e9-85a6-2328c8515d7c.gif)

Though the CSharpLib project getting rebuilt once is a little strange.
