### ISSUE TITLE
GenerateDocumentationFile not on by default in standard templates

### ISSUE THREAD

**Issue by GregoryGhost** [dotnet/fsharp#4221]
IntelliSense does not display quick info (xml comments) from my F# library after rebuilding in the console project on C#.

#### Repro steps

Steps:
   
1. Create the project "Library F#".

2. Add a console project to C # in this solution.
![image](https://user-images.githubusercontent.com/16402196/35145670-4f8f6e0e-fd3b-11e7-9730-c79d4640aa4e.png)

3. Add a link to the created "Library F#" in the console project in C #.

4. Add a xml comment "Test" for property "X" of Class1 in project "Library F#".

5. Build a project "Library F#".
![image](https://user-images.githubusercontent.com/16402196/35146451-a3acc3b8-fd3d-11e7-80d0-26490d073b66.png)

6. Edit a xml comment "Test Second" for property "X" of Class1 in project "Library F#".

7. Rebuild a project "Library F#".
![image](https://user-images.githubusercontent.com/16402196/35146792-abf2dff2-fd3e-11e7-87a5-4dbbb82b5b15.png)
[ClassLibrary1.zip](https://github.com/Microsoft/visualfsharp/files/1646183/ClassLibrary1.zip)

#### Expected behavior

Updating and showing quick info IntelliSense after rebuild project of "Library F#"  about xml comments for methods, classes, properties in console project on C#.

#### Actual behavior

Not showing quick info IntelliSense about xml comments from "Library F#" in console project on C#.

#### Related information 

Operating system - Windows Server 2012 R2 Standard.
Microsoft Visual Studio Community 2017. Version 15.5.2
VisualStudio.15.Release/15.5.2+27130.2010
Microsoft .NET Framework version 4.7.02558
Microsoft Visual C# 2017
Microsoft Visual F# 4.1

**Comment by cartermp** [comment]
Confirmed - you must indeed rebuild the F# project to regenerate the XML doc comments after it has been previously built. @dsyme any pointers as to where this could be coming from?

**Comment by dsyme** [comment]
@cartermp No, not sure, sorry.  Feels like a possible bug in the C# project system, which must be picking up the DLL and XML files directly.  I'm sure we're writing these files, so the only other issue would be if our project system is not reporting something to the C# project system correctly

**Comment by dsyme** [comment]
This is because GenerateDocumentationFile is not on by default in our standard templates

@cartermp Any idea why this is not on by default?  It's strangely not on for C# either.  But it's more important for F# since C# projects pick up documentation from the XML file

**Comment by cartermp** [comment]
This is entirely a C# issue and not an F# one. We _could_ add this property by default to all libraries to work around that issue. This would not be in this repo though.

**Comment by cartermp** [comment]
I'm not sure if this is a severy-high issue, since this has no effect on F# to F# projects.
