### ISSUE TITLE
QuickAction does not open the relevant module

### ISSUE THREAD

**Issue by asik** [dotnet/fsharp#4223]
#### Repro steps

```
// SomeModule.fs
namespace SomeNamespace

module SomeModule =
    let someFunction () = ()
```
```
// Program.fs
module Program

[<EntryPoint>]
let main argv =
    someFunction()
    0
```

Invoke the first QuickAction on someFunction()
![image](https://user-images.githubusercontent.com/1631157/35158232-8088f0e8-fd04-11e7-8eb3-8fbe21b8b524.png)

#### Expected behavior
Adds `open SomeNamespace.SomeModule` or otherwise fixes the code in a way that makes it compile

#### Actual behavior
Adds `open SomeNamespace`. The code still does not compile.

VS 2017 15.5.4
Visual F# Tools 15.4.1.18011902

**Comment by psfinaki** [comment]
This one is fixed.

https://github.com/dotnet/fsharp/assets/5451366/27f2d265-3797-4ba1-9d3b-4728af53d987

Closing, reopen if needed.
