### ISSUE TITLE
.NET Framework ---> .NET Standard assembly reference results in error in error list

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#4282]
Using 15.6 Preview 3

1. Create a .NET Framework 4.6.1 library.
2. Create a .NET Standard 2.0 library.
3. Add a reference from the .NET Framework library to the .NET Standard library.
4. Build.

Result: 

`FS0084	Assembly reference 'C:\Users\Phillip Carter\source\repos\Library9\ClassLibrary1\bin\Debug\netstandard2.0\ClassLibrary1.dll' was not found or is invalid`

![image](https://user-images.githubusercontent.com/6309070/35534828-894dff6c-04f6-11e8-911f-8df197f4694c.png)

Some other things to note:

* The project can build and run
* If you close the solution and reload it, things seem fine

cc @TIHan

**Comment by cartermp** [comment]
It started magically working after I got halfway through [this video](https://www.youtube.com/watch?v=-VsmF9m_Nt8&feature=youtu.be).

**Comment by cartermp** [comment]
Did this again with a Console app and .NET Standard library; still seeing the same error:

![image](https://user-images.githubusercontent.com/6309070/35535053-3cce9c0e-04f7-11e8-89cc-cd595fd4fb19.png)

**Comment by KevinRansom** [comment]
I watched that entire video from beginning to the end.  3 1/2 minutes of my life I won't get back.

**Comment by cartermp** [comment]
Confirming that I still see this _without_ anything custom installed into my VS

**Comment by cartermp** [comment]
Upon closing and re-opening the solution, the error in error list is not gone. Updating issue

**Comment by KevinRansom** [comment]
@cartermp it just worked fine for me.  Is there some steps, perhaps you missed from the repro?

**Comment by cartermp** [comment]
Nope.

**Comment by KevinRansom** [comment]
Next time you are in the office, can you bring in your laptop and show me pls.

**Comment by cartermp** [comment]
Just got this now on a fresh .NET Framework console app referencing a fresh .NET Standard library:

![image](https://user-images.githubusercontent.com/6309070/35538241-f5c32478-0501-11e8-8453-103804a6f22c.png)

**Comment by KevinRansom** [comment]
@cartermp could you please:
* set the logging to verbose in tools options/projects and solutions/build and run.
* do a build and mail me the logfile, I will take a look.

**Comment by cartermp** [comment]
Still reproduces in 15.8. Manually reloading the .NET Framework project is required.

**Comment by cartermp** [comment]
Fixed by #5698

**Comment by TIHan** [comment]
Reopening as we need to slightly revert cross project referencing of CPS style projects in a legacy project; it causes worse issues such as tooling not working when you open a second solution.

**Comment by cartermp** [comment]
Closing out, as support for the legacy projects is now frozen and all new .NET FX projects use CPS
