### ISSUE TITLE
Test CancellationPropagatesToGroupImmediate is flaky

### ISSUE THREAD

**Issue by brettfo** [dotnet/fsharp#4337]
The [CancellationPropagatesToGroupImmediate](https://github.com/Microsoft/visualfsharp/blob/2bcb342c2687a13e586052de9000d44ad86b156a/tests/FSharp.Core.UnitTests/FSharp.Core/Microsoft.FSharp.Control/AsyncType.fs#L346) test is flaky and hangs in the `master` and `dev15.7` branches.  Test has been disabled to prevent code flow.  Also `CancellationPropagatesToImmediateTask`.

Test was added in #2534.

**Comment by dsyme** [comment]
Tracking disabled tests by https://github.com/dotnet/fsharp/issues/10958
