### ISSUE TITLE
Compiler should print it's version in dotnet build

### ISSUE THREAD

**Issue by forki** [dotnet/fsharp#4344]
we have issues like https://github.com/Microsoft/visualfsharp/issues/4343 and don't easily know which compiler version it is.

#### Expected behavior

Compiler prints its own version during dotnet build

#### Actual behavior

we only see the reported compiler errors in the log

**Comment by KevinRansom** [comment]
@forki, I actually like the suggestion.  

However we don't really control the build output.  That's handled by msbuild. It logs the output and then scrapes the errors and warnings for logging and display.

What we could do, is something in the build task that returns a version value, and add a property that makes the build display it I suppose, but there is not much we can do in the compiler.

Kevin

**Comment by forki** [comment]
that's weird - I have paket printing it's version during dotnet restore.

**Comment by KevinRansom** [comment]
Is paket invoked using Exec ?  or is it a buildtask, invoked using:  https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Build/Fsc.fs#L499

**Comment by forki** [comment]
ah yes. we are calling it as .exe

**Comment by cartermp** [comment]
Hmmm. I'm not so sure about this one. I think this should instead be a feature request on `dotnet --info` to list the version of the F# toolset that it comes with (and the c# toolset).

**Comment by cartermp** [comment]
Closing as external to https://github.com/dotnet/sdk/issues/13246
