### ISSUE TITLE
Uses of active pattern cases inside pattern definition are reported as is from definition

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#4423]
Consider the code below. The first line contains definitions of the cases and the second line contains uses of these definitions.
```fsharp
let (|Foo|Bar|) _ =
    if true then Foo else Bar 
```
<img width="940" alt="screen shot 2018-03-02 at 20 48 24" src="https://user-images.githubusercontent.com/3923587/36913490-3344348c-1e5b-11e8-9292-8cab354f35fa.png">

**Comment by auduchinok** [comment]
The bug is caused by:
https://github.com/Microsoft/visualfsharp/blob/99e307f3a3ef2109ba6542ffc58affe76fc0e2a0/src/fsharp/NameResolution.fs#L3296-L3300

**Comment by dsyme** [comment]
I verified that this has been fixed, but noticed some other problems with the symbols being returned, fixed in #12949
