### ISSUE TITLE
Provide a proper way to `make install` to a custom install directory

### ISSUE THREAD

**Issue by jwosty** [dotnet/fsharp#4449]
It would be nice to have a proper way to install a custom build of F# (through `make`) to an arbitrary location, instead of overwriting the globally-installed F#.

#### Desired behavior

Ideally, to install to a specific location, it would be nice to be able to just do this:

    make
    INSTALL_DIR="/my/custom/fsharp/dir/" make install

And you'd have the new build installed to `/my/custom/fsharp/dir/`, as if this were the fsharp directory of a mono prefix. Theoretically this shouldn't be too hard to do.

#### Known workarounds

Currently, you can do one of two things:
* Don't run `make install`, and manually execute/copy the build binaries in `bin/`
* Use `DESTDIR='/my/prefix/' make install -e`

Each has their own issues. When using the first method, you might miss things (since you're doing it manually), and it just gets tedious if you want to copy things around.

With the second method, it won't install it to `/my/prefix/` -- it will append the Mono prefix to it first. E.g. (using OSX's mono location as an example) you end up with something like `/my/prefix/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp`. Ew. Besides, this is abusing make (see: the `-e` option), and could potentially break things (as the makefile doesn't know you're doing this).

#### Related information 

* Operating system N/A
* Mono
* Minor, contributor pain

**Comment by boloutaredoubeni** [comment]
I just wanna note that a pr was merged that adds a note about `DESTDIR` #4455

**Comment by jwosty** [comment]
@boloutaredoubeni  Right, but it's still a brittle solution. Ideally the makefile should support this directly instead of having to forcefully override the variables

**Comment by cartermp** [comment]
I think this can be closed out since we now build consistently across OSes, with the built binaries going into the `artifacts/` directory. These can then be moved around wherever anyone would like.
