### ISSUE TITLE
ilxgen error FS0971

### ISSUE THREAD

**Issue by juselius** [dotnet/fsharp#4461]
The following snippet fails to compile:
```fsharp
type Test () =
    static member g ([< ReflectedDefinition>] f : Quotations.Expr<unit -> unit>) = ()
let f () =
    let mutable x = 0
    fun _ -> Test.g (fun _ -> x |> ignore)
```
Moving the mutable variable outside the function, removing the extra lambda or the quotation, causes the code to compile like expected. 

#### Repro steps

1. Compiling the above snippet results in:
```
Fail.fs(8,9): error FS0971: Undefined value 'mutable x : int' 
```

2. Compiling the above snippet, *and* adding ``<PackageReference Include="WebSharper.FSharp" Version="4.2.3.236" />`` to .fsproj, results in:
```
Fail.fs(8,9,8,52): ilxgen error FS0971: Undefined value 'mutable x : int'
```
#### Expected behavior

Expected the code to compile without errors.

#### Actual behavior

Compile errors.

#### Known workarounds

Move the mutable variable outside the function:
```fsharp
let mutable x = 0
let f () =
    x <- 0
    fun _ -> Test.g (fun _ -> x |> ignore)
```

#### Related information 

* Operating system: NixOS 18.03pre130558.7270f2139ae (Impala)
* .NET Runtime: .NET Core 2.1.4 and 2.0.3
* Editing Tools: Neovim

**Comment by dsyme** [comment]
I don't repro this, 
```
C:\GitHub\dsyme\visualfsharp>fsc q.fs
Microsoft (R) F# Compiler version 10.1.0 for F# 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

q.fs(5,43): warning FS0988: Main module of program is empty: nothing will happen when it is run

C:\GitHub\dsyme\visualfsharp>debug\net40\bin\fsc q.fs
Microsoft (R) F# Compiler version 10.1.0 for F# 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

q.fs(5,43): warning FS0988: Main module of program is empty: nothing will happen when it is run
```

**Comment by juselius** [comment]
Interesting. I compiled with ``dotnet build -d v``, and started removing flags from the generated RunFsc.sh command line. It seems the offending flag is ``--optimize-``.

**Comment by juselius** [comment]
``--optimize+`` works btw.

**Comment by dsyme** [comment]
@juselius OK, thanks, yes I can repro this
