### ISSUE TITLE
Completion completes too much

### ISSUE THREAD

**Issue by 0x53A** [dotnet/fsharp#4515]
1) ``Area51ProviderX`` is the correct name

![image](https://user-images.githubusercontent.com/4236651/37389202-a7d92d5a-2763-11e8-87a9-c0d23d55ac02.png)

2) Now I press CTRL+Space with the cursor at the end:

![image](https://user-images.githubusercontent.com/4236651/37389222-bb8e1c66-2763-11e8-8438-e12a83c0ae83.png)

![image](https://user-images.githubusercontent.com/4236651/37389251-dc83c65a-2763-11e8-9ac0-d04cd129c73d.png)

**Comment by cartermp** [comment]
@0x53A is there a link to the project you can give?

**Comment by 0x53A** [comment]
```F#
namespace ProviderImplementation

//[<TypeProvider>]
type Area51ProviderX () = class end


namespace Area51
type XX = ProviderImplementation.Area51Provider
```

set the cursor at the end of the last line, press CTRL+SPACE

**Comment by cartermp** [comment]
Seems like something gets thrown off when there's a numeric character:

```fsharp
module M =
    let foo12Bar

M.foo12Ba <<-- caret here
```

ctrl+Space on the end there will result in `M.foo12foo12Bar`.

What's happening is that the span in `item.Span` below corresponds to whatever comes after the numeric char(s). Then it replaces just that span:

https://github.com/Microsoft/visualfsharp/blob/ff61ee5e69d9efa9bb278b75c5e319c6989f864c/vsintegration/src/FSharp.Editor/Completion/CompletionProvider.fs#L279

**Comment by cartermp** [comment]
This should be addressed by https://github.com/dotnet/fsharp/pull/10500
