### ISSUE TITLE
Auto-complete with backtick-escaped identifiers fails, it creates four backticks

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#4602]
If you try to auto-complete a name that is escaped with double backticks, the auto-complete will double the double opening backticks. I.e., ``` ``test-foo`` ``` becomes `````` ````test-foo`` ``````.

### Repro steps

1. Create an identifier, say  ``` ``test-foo`` ```
2. Start typing with backticks, i.e., you type  ``` ``tes ```
3. Select the identifier in the auto-complete list

![9cec40cd-05e8-4c61-b557-fba083a79a19](https://user-images.githubusercontent.com/16015770/37767969-30ff8ee4-2dcc-11e8-9261-0955b0099e48.gif)

### Expected behavior

The resulting identifier should be a valid name, after you select it in the dropdown.

### Actual behavior

The identifier receives two extra backticks prepended.

### Known workarounds

Don't use auto-complete with escaped identifiers, or remove the backticks afterwards (not really a workaround, actually).

### Related information 

Seen in VS 2017 15.6.3 and in Previews.

**Comment by majocha** [comment]
Typing 2 backticks doesn't trigger auto-complete at the moment. Probably it should in some contexts.

Good workaround is to just start typing without backticks.

**Comment by abelbraaksma** [comment]
@majocha, it does in my version of Visual Studio. See the videocapture above ;).

**Comment by majocha** [comment]
@abelbraaksma, hmmm, it's not obvious in the gif because the list shows up so late.
It certainly doesn't trigger for me, but I just installed the vsix built from master.

**Comment by abelbraaksma** [comment]
@majocha, if you mean *only* typing ``` `` ``` (i.e., two backticks) triggers the list, then no, you are right, it starts showing once you type a part of the actual identifier. 

But then, when you select it, you end up with four backticks (i.e., ````` ```` `````) at the start of the name, so the auto-complete doesn't seem to take into account when you already have two backticks written.

**Comment by cartermp** [comment]
This one is fixed:
![no-repro1](https://user-images.githubusercontent.com/6309070/111570286-be58cc00-8761-11eb-8fd5-92f1a1552e85.gif)

**Comment by abelbraaksma** [comment]
Great! 💯
