### ISSUE TITLE
Separator between member and type annotation interpreted as operator

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#4607]
Given the following:

```fsharp
type IFoo<'T> =
    abstract member Bar<'T>: name: string -> unit
```

**Expected:**

Compiles.

**Actual:**

Compiler error.

`
This construct is deprecated: ':' is not permitted as a character in operator names and is reserved for future use
`

**Workaround:**

Put a space after the `>`:

```fsharp
type IFoo<'T> =
    abstract member Bar<'T> : name: string -> unit
```

Thanks to @jaredpar for pointing this out

**Info**

Latest F# compiler in VS Preview

**Comment by abelbraaksma** [comment]
From the linked issue, there’s an open language suggestion that fixes this, here’s the rfc: https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1083-srtp-type-no-whitespace.md

**Comment by edgarfgp** [comment]
@abelbraaksma Just tried with version 7 and  this still happens. |So looks like the SRTP whitespace relaxation did not help here :(

**Comment by abelbraaksma** [comment]
Thanks for trying it out. Fantomas often autocorrects such code, but it’s better if this could still be completely fixed, I think the language spec allows it.
