### ISSUE TITLE
Color bindings which are disposable

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#4618]
See discussion here: https://github.com/fsharp/fslang-suggestions/issues/124

Currently, the F# tools give you the ability to color types which are disposable (default is the same as classes, but they are set to Pink in my settings here):

<img width="640" alt="screen shot 2018-03-23 at 8 07 29 am" src="https://user-images.githubusercontent.com/6309070/37846583-449bd4de-2e8b-11e8-89f4-0430f81e9014.png">

There is motivation to also color bindings to types which are disposable. Today, they are not colored any differently than other bindings.

**Comment by amazingant** [comment]
I'll open a new issue if needed, but is it possible to revisit this and provide separate color bindings for the disposable type names versus disposable let-bound values? I just updated VS to 16.7 and found there's no way to go back to the old coloring, where disposable type names are a blueish green (or greenish blue?) and the let-bound value names are white.

**Comment by cartermp** [comment]
@amazingant Correct, that's the case for 16.7. I've adjusted things here to allow for more customization: https://github.com/dotnet/fsharp/pull/9915

**Comment by amazingant** [comment]
@cartermp Awesome, thank you! 😄
