### ISSUE TITLE
"Unexpected symbol reader error" in a simple F# console application

### ISSUE THREAD

**Issue by parthopdas** [dotnet/fsharp#4643]
[From fsharp/fsharp#831]

"Unexpected symbol reader error" message on an unbound breakpoint in a simple F# console application.

#### Repro steps
1. VS 15.6.4, F#, "Microsoft Visual F# Tools 10.1 for F# 4.1", .NET Fx 4.6.1 console application, FSharp.Core 4.4.3.0
2. Create a new console application with the above configuration/toolset
3. Add the following line before the main function
> let func = sprintf "%d"
4. Set a break point on first line of main
5. F10

#### Expected behavior

Program execution to break at first line of main, the breakpoint should be bound.

#### Actual behavior

Disassembly window shows up, hovering on the breakpoint says "The breakpoint will not currently be hit. Unexpected symbol reader error"

#### Known workarounds

If you instead change func to non-point-free style, the expected behavior occurs. viz.
> let func n = sprintf "%d" n

As you will agree, I am sure, this is not really an acceptable workaround, but noting it here in case it provides a hit regarding where the problem could be.

#### Related information 

VS 15.6.4, F#, "Microsoft Visual F# Tools 10.1 for F# 4.1", .NET Fx 4.6.1 console application, FSharp.Core 4.4.3.0

**Comment by KevinRansom** [comment]
Okay there is a workaround for this, if the debugtype is set to portable, then debugging this works fine.

Kevin

**Comment by cartermp** [comment]
To my knowledge there hasn't been a change, no.

**Comment by jwosty** [comment]
@nosami ah, so it's a totally different engine? I figured as much.
