### ISSUE TITLE
Error highlighting gets stuck after error is fixed, remains visible in error list, but gone in Build Output window; Clean Solution has no effect

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#4645]
Little disclaimer: this is the first time it happened to me and I have (yet) no idea of a repro, but decided to report it anyway in case other people have seen it too.

After editing for a while I fixed some errors and they got stuck, that means: the red squigglies stay, just like the error QuickInfo, plus the error message in the Error List. But it's gone in the Output window.

### Repro steps

Sorry, no repro yet, but here's a screenshot. Doing an F7-Build proves the error is gone (changed it from instance to class method).

![image](https://user-images.githubusercontent.com/16015770/38107877-6ad92aae-3393-11e8-9557-b3401ffec6aa.png)

### Expected behavior

Errors should disappear after you fix them. And when they are stuck (which shouldn't happen in the first place, but happens quite often), a build or rebuild should take them away.

### Actual behavior

The error has remained there for at least 15 minutes, including the squigglies and the error in the Error List. The Output window shows that the error is gone (after a build).

### Known workarounds

Strangely, I do not have a workaround, unless it is restarting Visual Studio. Build, Rebuild, closing/opening file all have no effect. CPU is silent (i.e., not hanging/spinning in some loop, I think).

Not even a Solution-wide Clean -> Rebuild has any discernible effect.

### Related information 

Seen at least once in Visual Studio 15.6.4 and 15.7.2.

**Comment by cartermp** [comment]
Thanks for the report - this is definitely strange and troubling. If you can get this to happen reliably then we need to fix this ASAP

**Comment by abelbraaksma** [comment]
FWIW: it has happened a few times since. 

I found that, when you just ignore this situation and continue editing, that at some point the squigglies are updated. 

This suggests (but I'm guess) that, perhaps for performance reasons, the syntax highlighter and error checker is only run after X keystrokes. Say it's 10 keystrokes, that would imply that, if you are at the 9th keystroke and go on a holiday, nothing will happen.

I don't know how/when the syntax-highlighter services are called, but if the above is how it currently works, a (simple?) fix would be to add one more trigger: after X seconds, provided there's a change.

As an aside, I also noted that the syntax and intellisense services (how are they called normally?) are triggered when you do a non-intrusive change. Say your project structure is X depends on Y depends on Z, if you change a comment or whitespace in X, it will take a while before intellisense works at all (for a while, there won't be any popup in project Z, until X and Y are recompiled).

**Comment by cartermp** [comment]
@abelbraaksma if you turn off all code fixes in settings, does that help?

<img width="308" alt="screen shot 2018-03-31 at 11 50 51 am" src="https://user-images.githubusercontent.com/6309070/38164918-cc1eaed2-34d9-11e8-912a-e4f347237cca.png">

@dsyme recently did some work with later Roslyn bits (not available until 15.7 Preview 3) such that each of the analyzers backing those code fixes are run in a priority order, with the error diagnostic analyzer always being the first. It could be that other analysis is running before error diagnostics are updated.

As for this:

> As an aside, I also noted that the syntax and intellisense services (how are they called normally?) are triggered when you do a non-intrusive change. Say your project structure is X depends on Y depends on Z, if you change a comment or whitespace in X, it will take a while before intellisense works at all (for a while, there won't be any popup in project Z, until X and Y are recompiled).

This is the perf hit from in-memory cross-project references:

<img width="493" alt="screen shot 2018-03-31 at 11 53 32 am" src="https://user-images.githubusercontent.com/6309070/38164937-286c668e-34da-11e8-9e5e-e1dfc068724c.png">

What's happening is that the language service sees you've made a change in X, it goes and re-typechecks Y and X in the order of dependence. We don't have any heuristics for determining when _not_ to re-typcheck (which is something we really, really want to get to this year). If you turn it off, then the IDE will have _much_ improved IntelliSense, but at the cost of some features not working across projects, and the need to recompile a project after a change if you wish to see its changes in a dependent project.

Additionally, the Project Check Cache Size value at 200 is quite a lot, and may also be a contributing factor. It used be be 3 in VS 2015. I'd recommend bringing that back down to 3 and perhaps playing around with the value.

Unfortunately, until we do the work to address this area of language service perf, you'll be stuck with this binary option of better perf for less functionality and a greater need to rebuild changes projects.

**Comment by abelbraaksma** [comment]
@cartermp, this is valuable and insightful information, thanks.

>  I'd recommend bringing that back down to 3 and perhaps playing around with the value.

I have it on three since that option came around (I remember some thread on github discussing why it was 200, I can't remember the reasoning, was somewhere last summer).

> @abelbraaksma if you turn off all code fixes in settings, does that help?

I have it like as follows since our last discussion on a similar matter (first and last checked). The *unused identifiers* is just too worthwhile to switch off. I remember somewhere you telling me that the one that is most risky in terms of performance is *remove unused open statements*.

![image](https://user-images.githubusercontent.com/16015770/38167734-ddcc027c-353a-11e8-8e08-36f0b16daa64.png)

Though I should say: this issue is not reported as a performance thing. I shows that *nothing* happens in some situations. As a test, the other day I left my system on at night in this state, result was: squigglies and error mouse-overs unchanged.

**Comment by abelbraaksma** [comment]
Just an update: the issue mentioned by me in the OP still happens.

**Comment by abelbraaksma** [comment]
Just one more situation, I let this linger for at least two days and this afternoon, many edits and rebuilds later, it's still there. I also shows that it happens with BCL methods just the same as with anything else

Error highlighting on anything else is stuck once this happens. I tried to profile, but there's nothing spinning out of control or slower than usual. I'm not quite sure where to look, but it sounds like something's definitely stuck. **Is there a way to turn on extra logging?** If logging of the syntax error highlighter service stops at some point, it may give a hint?

![image](https://user-images.githubusercontent.com/16015770/39441636-e4244db0-4cae-11e8-8b8a-b8cd81a2733b.png)

**Comment by abelbraaksma** [comment]
@dsyme, this is now happening almost all the time, could you help me with where to look or how to enable tracing or logging so that it becomes easier to pinpoint? My guess is that the language service breaks  or throws or both and doesn't restart itself, but I would need something to look for.

**Comment by cartermp** [comment]
@abelbraaksma Another one with roughly the same message 😄 

Have you seen this with VS 2019 in light of the memory and CPU usage improvements that have been made for it?

**Comment by abelbraaksma** [comment]
@cartermp I know I've seen it until the latest versions of VS 2017. My version of VS 2019 is still broken (Core projects don't load correctly), and I didn't spend enough hours on it (yet) to reliably claim is doesn't happen anymore.

But I've no problem with closing this and I'll reopen only if it happens still in VS 2019.

**Comment by cartermp** [comment]
@abelbraaksma have you had a chance to try out vs2019 (assuming projects are working in it)

**Comment by abelbraaksma** [comment]
@cartermp, sorry for replying so late, it seems that this doesn't happen anymore (occasionally I see errors stuck, even today, which stayed for a half hour, but then I recompiled aha after a few minutes after compilation finished, the squiggles disappeared). Good enough for me.
