### ISSUE TITLE
Make UpdateXlf task work on Mono

### ISSUE THREAD

**Issue by jwosty** [dotnet/fsharp#4667]
We should be able to perform some localization tasks on Mono, specifically `/t:UpdateXlf` on FSharp.Compiler.Private.fsproj. Not being able to do so is a huge hindrance to my (and presumably others') contributions; currently the process looks like:

1. Make change, push to PR branch.
2. Wait ~45min or an hour for CI build to finish. If success, we're done.
2. Mess with the resource files manually, push back to PR.
4. If I don't know what the problem is and/or I can't figure out how to fix it myself, bug someone else (with Windows) to do UpdateXlf. Either way, goto step 2.

This also just ends up creating a bunch of cluttersome, half-baked commits that shouldn't have to be pushed to CI one by one just to see what they break. (I know they're all squashed, by still, trying to read the resulting squash merge message would be awful -- mostly "Fix CI" or "Fix xlf" kind of thing).

For reference, Localization (XLF) task imports are prevented on Mono in [FSharp.Source.Settings.Target (L126)](https://github.com/Microsoft/visualfsharp/blob/0adb8230b3cfcfb561b92a662f891b6608b19998/src/FSharpSource.Settings.targets#L126).

**Comment by jwosty** [comment]
*@brettfo [(conversation in PR 4427)](https://github.com/Microsoft/visualfsharp/pull/4427#issuecomment-370617636):*
> Ahh, good find. On non-Windows machines the $(MonoPackaging) variable is getting set to true which in turn sets $(DisableLocalization) to true which prevents the import of XliffTasks.targets.
> 
> @dsyme added the $(MonoPackaging)=true -> $(DisableLocalization) stuff so I'll ask him if he remembers why localization support was disabled on non-Windows, but I suspect it's because localization requires al.exe which is Windows only.

...

*@dsyme [(conversation in PR 4427)](https://github.com/Microsoft/visualfsharp/pull/4427#issuecomment-371194122):*
> It's only because I and other contributors to the Mono packaging like @directhex, @nosami and @knocte have little idea how localization works, and no real capacity to adjust packaging and investigate issues.

**Comment by directhex** [comment]
I'm happy to make changes to packaging, I just have no idea what needs changing where.

**Comment by cartermp** [comment]
@directhex - @brettfo and @mmitche may be able to help with that.

**Comment by brettfo** [comment]
Build is now SDK-based, so Mono build isn't a thing.
