### ISSUE TITLE
Discriminated union doesn't work with non English type constructor names

### ISSUE THREAD

**Issue by hmnjeon** [dotnet/fsharp#4697]
Discriminated union doesn't work with non alphabet string (e.g., Korean string 개수).

#### Repro steps

Provide the steps required to reproduce the problem

1. Type in the following
type some-type =
    | 개수

#### Expected behavior

Should compile. Korean language doesn't have uppercase/lowercase distinction so it should just work with any Korean string.

#### Actual behavior

Error code FS0053 (Discriminated union cases and exception labels must be uppercase identifiers) emitted on VS 2017

#### Known workarounds

Prefixing the string with uppercase English letter works. e.g. U개수

#### Related information 

Provide any related information 

* Windows 10
* 4.1
* VS 2017 Community

**Comment by abelbraaksma** [comment]
It's my understanding that the parser uses the Unicode properties of code points. If the Unicode chart says it isn't a capital letter, than it isn't. That implies that identifiers that are required to start with a capital letter cannot be created with such characters. 

Since they're neither lower case, it would stand to reason that they cannot be used to capture a value inside a match expression either, at least not without a warning being raised. 

To fix this, we would need to fix the language. Either by removing the upper case requirement or by allowing valid identifier characters that are neither uppercase nor lowercase to be used in one of the two scenarios (and union cases seems the more sensible choice then ).

But changing this, even if consensus can be reached, may lead to backwards compatibility issues were existing compilable code becomes uncompilable .

**Comment by hmnjeon** [comment]
Wow, I thought it would be fixed right away but apparently it's not a simple matter.

Is allowing valid identifier characters and removing pattern matching warnings for those characters impossible? And does that change necessarily introduce backward incompatibility?

**Comment by abelbraaksma** [comment]
I actually don't know for sure why the distinction on uppercase for discriminated union cases was made. Probably to simplify parsing (variables are lower case in match patterns, pattern cases and active patterns start with upper case). 

You will see that if you write the following, you'll get a warning:

```f#
type Foo = Bar | Zed
let f x =
   match x with
      | Bar -> 12
      | SomeValue -> 13  // warning: Uppercase variable id. should not generally be used in patterns and may indicate a misspelt pattern name
```

That warning wouldn't be possible if this distinction wasn't made. Of course, other decisions could have been made with regards to the syntax of pattern match (like prefixing a variable with `var` or something), but a long time ago, and perhaps for compatibility with OCaml, the current rule was introduced that pattern cases must start with an uppercase character.

Relaxing that rule for scripts that do not have uppercase/lowercase seems reasonable, but assuming such change were accepted, it would mean that either:

* In scripts without upper/lower case all characters are considered upper-cased, variables in pattern matches cannot use these characters
* In scripts without upper/lower case, all characters are considered lower-cased, pattern case names cannot be created, but the characters can be used for variables in pattern matches.

I searched, but could not find a legal Unicode modifier character that designates a letter as being uppercase, regardless of its properties, so I think it doesn't exist.

Maybe there's a more creative solution, I don't know.

**Comment by hmnjeon** [comment]
IMHO if the language spec says you should use uppercase for type constructor and lowercase for match expression, there should have been a check in the parser to see if a script belongs to the languages that have that distinction. And it doesn't apparently, and that's a bug in the parser not the language spec. So rather than considering a script lowercase/uppercase as that is mutually exclusive, how about adding a set membership test (to see if a script is a character of the language where there's uppercase/lowercase distinction) before the lowercase/uppercase test of the parser?

**Comment by abelbraaksma** [comment]
> And it doesn't apparently, and that's a bug in the parser not the language spec.

As far as I know, that *does* happen. With "script", I meant how the term is used within the Unicode spec only to create exemptions to the current rules, which already work: whether or not a character is uppercase or lowercase, is defined by the Unicode spec and F# follows the same version of that spec that is implemented by .NET.

It works kind-of like this:

```f#
let nameStartsUpper (s: string) = s.[0] |> Char.IsUpper
let res = nameStartsUpper "개수"
```

When you run that in F# interactive, it gives you this:

```f#
val nameStartsUpper : s:string -> bool
val res : bool = false
```

The characters in your example are neither uppercase nor lowercase, so they cannot be used, since a test on "is this character uppercase" will return false. My assumption is that for variables used in match expressions it simply uses the inverse of that test (which is *not* the same as testing whether a character is lowercase).

I tested that theory and that seems correct, you don't get a warning when using your example, which follows how the spec is currently defined:

![image](https://user-images.githubusercontent.com/16015770/38494035-b0c92d0c-3bf4-11e8-958d-cecfbb2c0a3f.png)

Conversely, if I take some odd language and take a capital letter, say Glagolitic, I get the proper warning (example starts with a capital letter and then two lowercase letters):

![image](https://user-images.githubusercontent.com/16015770/38494028-aa9b6044-3bf4-11e8-9389-622eada891c2.png)

Finally, if I try the Glagolitic names with DU cases, it is allowed:

![image](https://user-images.githubusercontent.com/16015770/38494096-eb27d00c-3bf4-11e8-9806-ccdc196f12d4.png)

From this code:

```f#
type Foo = | Ⱍⰿⱅ   // starting with an uppercase is valid
```

Unless I misunderstand something, but I don't think there's a bug here, otherwise, please give an example (your current example shows that the parser/compiler works as expected).

**Comment by hmnjeon** [comment]
If I say "union case names should begin with uppercase letter" what I actually mean and what I should mean is "union case names should begin with uppercase letter if the first letter belongs to the languages that have upper/lowercase distinction". In that sense the spec is a bit ambiguous but fine but the implementation has a bug. 
So how about doing this?
```F#
let nameStartsUpper (s: string) = s.[0] |> ``test the letter belongs to the languages with upper/lowercase distinction`` |> Char.IsUpper
```
From the brief google search, [`Char.GetUnicodeCategory`](https://msdn.microsoft.com/en-us/library/system.globalization.unicodecategory(v=vs.110).aspx) returning OtherLetter for letters that don't have lower/uppercase distinction seems would be helpful for implementing the test.

**Comment by abelbraaksma** [comment]
> but the implementation has a bug.

still not seeing the bug, the spec is followed exactly. So what is the bug? To be clear: a bug is a bug when the F# specification is not implemented correctly. Anything else is a feature request (which are most welcome, btw ;) ).

I think the spec is clear: whether a char is uppercase or not, is a pretty straight-forward yes/no question if you take the database of Unicode as a lead. And Korean doesn't have uppercase, so the language behaves in a predictable manner: you cannot use purely Korean Hangul syllables for DU Case names (nor Chinese, musical symbols, modifier letters, exclamation marks, start with a digit and so on, these are rules of the language and, imho, not bugs).

> union case names should begin with uppercase letter if the first letter belongs to the languages that have upper/lowercase distinction

How should I interpret the "if"? Do you mean "if and only if", or do you mean "unless"? Sorry, but I'm having trouble understanding your request.

I'm unsure what you mean with your code sample. What does "test with the letter..." do? What does it output? The next function is `Char.IsUpper`, which takes a char, so the `test with...` changes the char? Noe that Char.IsUpper is a test on the character and single characters can belong to multiple scripts, for which some scripts may or may not support uppercase/lowercase.

But more importantly, what are you trying to achieve? If you mean you want to improve the language by adding support for Korean DU case names, then that's a clear question/suggestion, but then we'll have to think how that can fit within the current language design (see spec, see my first and more concretely, my second comment above). Or whether we should rethink the language design (but be aware, that may need convincing of @dsyme, and he can be quite strict ;) ).

**Comment by hmnjeon** [comment]
Sorry I didn't see the part that the spec explicitly mentions `Char.IsUpper` test :) Sadly, no ambiguity there :(

What's the rationale for isUpper test? Doing the following is out of the question? If it's for OCaml compatibility there might be no room for change but if it's just for helping programmer kind of feature, then maybe you can consider changing it? Since Koreans rarely use Korean words for variable names we would rarely need the warning. Not to mention being able to model a domain with actual words domain experts use is really good. (BTW workaround using prefix is still much better than to translate every single words)

```F#
let nameStartsUpper (s: string) = if (Char.GetUnicodeCategory s.[0]) = UnicodeCategory.OtherLetter then true else s.[0] |> Char.IsUpper
```

What I want is to use words in my language without prefixing with English letters in union cases and pattern matching. BTW I don't mind using workaround that much but I thought it would be so much easier to fix this "bug" before posting :) Now I know there is little chance that it would happen :( Anyway thank you for your patience with me @abelbraaksma.

**Comment by dsyme** [comment]
> I think that is reasonable request. In other words, the requested feature is: allow discriminated union names in non-latin scripts that don't support capitalization, like Korean, Mongolian, Chinese, Japanese scripts.

The current rule is 

might-be-pattern-name-or-union-case-name:

    Char.IsUpper(c) && not (Char.IsLower c)

That is, if the above is true then the identifier is categorized as "might be a variable if used in argument position, might be a union/pattern name".  If false, it is categorized as "definitely a variable".

Now, my understanding from a quick test is that Char.IsUpper and Char.IsLower both return false for the Chinese/Korean characters.  Changing to 

might-be-pattern-name-or-union-case-name:

    let isCaseChar = Char.IsUpper(c) || Char.IsLower(c) // does the character have any casing?
    let isUpperCaseChar = Char.IsUpper(c) && not (Char.IsLower c) // if so, is it an upper case?
    not isCaseChar || isUpperCaseChar

seems reasonable.  However we need to consider whether this is a breaking change. In theory I think it is, but only in corner cases where people have existing union cases or pattern labels in scope and are using the same names as variable names.  The change wold cause a reinterpretation of the code.

@cartermp Do you have an opinion about whether we should take this through fslang-suggestions or should we just apply the change? thanks

**Comment by cartermp** [comment]
Let's take it through fslang-suggestions and see what other folks have to say. I suspect that this corner case isn't prominent, but the more eyes, the better. Having a PR which fixes this (if it's easy enough) going on concurrently doesn't hurt, either.

**Comment by abelbraaksma** [comment]
We should be aware that:

* This change would relax the requirement on DU case names to have uppercase. So code that previously fails (as in the OP), will now compile
* This change would turn capturing variables in match expression that are currently considered valid, into a warning (the same warning given when you have a variable with an uppercase start char). That is: this change will discourage the use of start chars that are neither uppercase, nor lowercase.
* As @dsyme mentions, in rare cases, this may lead to existing code to fail, where a DU case name becomes in scope of a match capturing variable by the same name. Having the warning in place is probably a good idea.
* The `Char.IsUpper` etc tests are comparatively expensive, esp on higher chars, it may help a few bits to prioritize the common case (no idea how the real code currently looks like) and to not repeat the test (but this may be an irrelevant micro-optimization)

The above doesn't mean I'm in favor, or against this change. It's just my 2p on things we should consider before moving forward.

**Comment by dsyme** [comment]
I agree to take to fslang-suggestions, and I'd love to see a PR

>  I suspect that this corner case isn't prominent,

I think that's a cultural assumption.  If writing code in Korean or Chinese you could easily hit this all the time.  It would be quite natural, for example, to write or generate union types in those languages.

> This change would relax the requirement on DU case names to have uppercase. So code that previously fails (as in the OP), will now compile

Yes, though it's better to say "relax the requirement to this: case-senstive languages must use uppercase DU case names, case-insensitive characters "

> This change would turn capturing variables in match expression that are currently considered valid, into a warning (the same warning given when you have a variable with an uppercase start char).

I think we need only give the warning for uppercase identifiers in case-sensitive languages?  

> As @dsyme mentions, in rare cases, this may lead to existing code to fail, where a newly added DU case name using these new rules, becomes in scope of a pattern variable by the same name. Having the warning in place is probably a good idea.

It is hard to detect this case I think without giving a warning on valid uses too.  

We may have to introduce the change via a language-level flag in F# 4.5 or 5.0

**Comment by voronoipotato** [comment]
This seems to fail for most? languages. I'm no linguist so I'm sorry to everyone whose language I just butchered, I just yanked these from a dictionary. My goal is to improve accessibility in other languages.

Windows 8
Visual Studio Enterprise 2017
Visual F# 4.1

type WuWei = 无为;; //Fails (Chinese) with error FS0053: Discriminated union cases and exception labels must be uppercase identifiers
type WuWei = 無爲;; //Fails (Chinese) with error FS0053: Discriminated union cases and exception labels must be uppercase identifiers
type WuWei = むい;; //Works (Japanese)

type WuWei = 無為;; //Fails (Japanese) with error FS0053: Discriminated union cases and exception labels must be uppercase identifiers
type WuWei = 무위;; //Fails (Korean) with error FS0053: Discriminated union cases and exception labels must be uppercase identifiers

type WuWei = 無爲;; //Fails (Korean) with error FS0053: Discriminated union cases and exception labels must be uppercase identifiers
type Luck = بالتوفيق;; //Fails (Arabic) with error FS0053: Discriminated union cases and exception labels must be uppercase identifiers
Type Sorry = ཀོང་དགས་།;; //Fails (Tibetan) with Unexpected Character '་' in interaction. Expected incomplete structured construct at or before this point, ';', ';;' or other token.

A work around for everything but tibetan is the extremely dumb prepending of any capital english letter.
type AWuWei = A无为;; //Works (Chinese)
type LuckA = Aبالتوفيق;;

**Comment by abelbraaksma** [comment]
@voronoipotato exactly. That's why we are searching for a solution that makes an exception for languages / scripts that don't have capitals. Good to see more examples of that. As @dsyme mentioned, we'll need a PR and / or RFC and a language suggestion, so that it can be discussed in detail (it's perhaps not as trivial as it may look)

**Comment by zpodlovics** [comment]
What unicode version is supported in the F# source code? Proper unicode support is surprisingly difficult. Take a look at these examples why unicode version could be important (without even mentioning zero-width characters):

https://codeblog.jonskeet.uk/2014/12/01/when-is-an-identifier-not-an-identifier-attack-of-the-mongolian-vowel-separator/
https://codeblog.jonskeet.uk/2014/11/07/when-is-a-string-not-a-string/
