### ISSUE TITLE
FS0073 errrors apparently caused by incorrect compiler inlining

### ISSUE THREAD

**Issue by psantoro** [dotnet/fsharp#4715]
I'm using VS2017 15.6.5 with F# 4.1, but I use the command line for all my development (vim and nmake) and I've been doing this for many years.  My makefiles support release and debug builds.  Today, I got fsc FS0073 errors (see fsc-bug1.txt) only during the release builds. I therefore examined the release and debug generated code using ILSpy (see fsc-bug2.txt, search for NOTE) and found the following differences in my env.set_dates function:

RELEVANT ENV MODULE SOURCE

let mutable private _processing_date:date.T option = None
let mutable private _irs_received_date:date.T option = None
...
let set_processing_date d = Interlocked.Exchange(&_processing_date, Some d)
let set_irs_received_dt d = Interlocked.Exchange(&_irs_received_date, Some d)

ILSPY RELEASE BUILD (marked unsafe and apparent inlining caused by fsc command line optimizations)

internal unsafe static void set_dates(Features feats)
...
		FSharpOption<fs.core.types.date.T> fSharpOption2 = Interlocked.Exchange(ref *(FSharpOption<fs.core.types.date.T>*)(&dcap.ItasRecord._tag), FSharpOption<fs.core.types.date.T>.Some(d2));
		...
		FSharpOption<fs.core.types.date.T> fSharpOption2 = Interlocked.Exchange(ref *(FSharpOption<fs.core.types.date.T>*)(&dcap.ItasRecord._tag), FSharpOption<fs.core.types.date.T>.Some(d2));

ILSPY DEBUG BUILD (not marked unsafe and no inlining - due to different fsc command line options)

internal static void set_dates(Features feats)
...
    FSharpOption<fs.core.types.date.T> fSharpOption2 = env.set_irs_received_dt(d2);
...
    FSharpOption<fs.core.types.date.T> fSharpOption5 = env.set_processing_date(d);
...
 
#### Expected behavior

No FS0073 compiler errors in release or debug builds.

#### Actual behavior

FS0073 compiler errors in release build.

#### Known workarounds

Decorating the affected functions to prevent inlining during release builds stops the FS0073 compiler errors.  I verified, via ILSPY, that the release build generated code was the same as the debug build (i.e. the set_dates function was not marked as unsafe and it did not use inlined methods).

[<MethodImpl (MethodImplOptions.NoInlining)>]
let set_processing_date d = Interlocked.Exchange(&_processing_date, Some d)

[<MethodImpl (MethodImplOptions.NoInlining)>]
let set_irs_received_dt d = Interlocked.Exchange(&_irs_received_date, Some d)

#### Related information 
* Operating system - Issue happens on Windows 7/10 with latest updates
* .NET Runtime Version 4.7.1
* Editing Tools - vim
* Indications of severity - compiler bug

[fsc-bug1.txt](https://github.com/Microsoft/visualfsharp/files/1900540/fsc-bug1.txt)
[fsc-bug2.txt](https://github.com/Microsoft/visualfsharp/files/1900609/fsc-bug2.txt)

**Comment by dsyme** [comment]
@psantoro Could you give us a step-by-step repro please, i.e. sample code that is affected by this that we can compile ourselves?

Many thanks

**Comment by psantoro** [comment]
The attached zip contains a small sample project.  It can be built using a x64 Native Tools Command Prompt for VS2017.

Command to make a debug build:
> nmake debug=1

Command to make a release build:
> nmake

The env.fs module contains 3 commented out lines.  If you un-comment those lines, the release build compiles without the FS0073 errors.

[repro.zip](https://github.com/Microsoft/visualfsharp/files/1905049/repro.zip)

**Comment by psantoro** [comment]
@dsyme Do you need anything else from me on this issue?

**Comment by dsyme** [comment]
@psantoro Thanks

**Comment by dsyme** [comment]
I finally fixed this, see #12910

**Comment by kerams** [comment]
Can we close?

**Comment by psantoro** [comment]
@kerams - I successfully retested my sample code using the Microsoft (R) F# Compiler version 12.5.0.0 for F# 7.0.  So yes, you can close this issue.
