### ISSUE TITLE
Any bug in QueueList?

### ISSUE THREAD

**Issue by zhuangzhuang** [dotnet/fsharp#4722]
https://github.com/Microsoft/visualfsharp/blob/5daaf8294ab0adcf1a19a77935966e5b3a30c32e/src/fsharp/QueueList.fs#L37
``` F#
member x.Append(ys:seq<_>) = QueueList(firstElements, (List.rev (Seq.toList ys) @ lastElementsRev), numLastElements+Seq.length ys))
```

counterexamples:
``` F#
let headQueue = ofSeq [1..5]
let tailQueue = ofSeq [1..100000]
let temp = append headQueue tailQueue
temp.ToList() |>ignore // call List.rev inside
temp.ToList() |> ignore // call List.rev again
```

**Comment by zhuangzhuang** [comment]
miss understand, this is not a bug.
please close this issues.
sorry

**Comment by abelbraaksma** [comment]
@zhuangzhuang you can close your own big by clicking the close button ;)

**Comment by zaaack** [comment]
This is actually a bug here, @zhuangzhuang could you please reopen it?

**Comment by forki** [comment]
@zaaack & @zhuangzhuang how did you spot this? Is there observable behaviour?

Anyway: fix is in https://github.com/Microsoft/visualfsharp/pull/4727

**Comment by zaaack** [comment]
@forki Not me, it's @zhuangzhuang find this, I guess he found it by accident when reading vf's source code?

**Comment by forki** [comment]
mhm looks like I fixed another issue. It still does 2 reverse operations.

**Comment by forki** [comment]
@kevinransom please reopen. The double reverse issue is not fixed.

**Comment by dsyme** [comment]
@forki Closing as this is internal to the compiler and would need an observable external behaviour in order to fix
