### ISSUE TITLE
Dragging files does not work

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#4723]
![_1](https://user-images.githubusercontent.com/873919/38736021-4c9d5348-3f33-11e8-8594-f47722b74001.gif)

15.6.6

**Comment by cartermp** [comment]
Note for posterity - this is in the legacy project system

**Comment by vasily-kirichenko** [comment]
I'm not sure this should be classified as feature request, it's a regression.

**Comment by cartermp** [comment]
Could you describe what the expected behavior is? Click and drag for ordering has never been supported in the legacy project system. It is supported for dropping a file into a folder, though.

**Comment by saul** [comment]
This is another manifestation of dragging/dropping a folder on top of itself resulting in weirdness (can't find the exact issue). This will be a one line fix somewhere in the project system to make sure we don't try copying a file to the same folder.

**Comment by cartermp** [comment]
Given the emphasis on .NET SDK-tyle projects I don't think we'll look at this for legacy projects.
