### ISSUE TITLE
F# files with condition won't show in solution explorer for legacy F# projects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#4739]
If condition attribute is added to project item it won't show in solution explorer.

Example:
&lt;Compile Condition=&quot; '$(Configuration)' == 'Release' &quot; Include=&quot;Program.fs&quot; /&gt;

In C# project file is visible all the time but in F# project it's never visible.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/203597/f-files-with-condition-wont-show-in-solution-explo.html
VSTS ticketId: 572147_
_These are the original issue comments:_

Phillip Carter [MSFT] on 2/28/2018, 09:35 AM (49 days ago): <p>As per Will's suggestion, can you see if this still reproduces for you on the 15.6 Preview?</p>

_These are the original issue solutions:_

Will Smith [MSFT] solved on 2/27/2018, 11:04 AM (50 days ago), 0 votes: 
<p>We believe this has been resolved in 15.6. Can you try the 15.6 preview? https://www.visualstudio.com/vs/preview/</p> 

Niko Autio on 2/28/2018, 10:32 AM (49 days ago): 
<p>Not work with preview either. (15.6.0 prev 6.0)</p> 

Will Smith [MSFT] on 3/1/2018, 10:15 AM (48 days ago): 
<p>Is this happening on legacy F# projects or cps based projects?</p> 

Niko Autio on 3/1/2018, 00:47 PM (48 days ago): 
<p>Legacy projects. Core project (&quot;cps&quot;?) seems to work nicely.</p>

**Comment by cartermp** [comment]
As a note, we'll be closing this out as a WONTFIX if all .NET Framework style projects open with CPS

**Comment by cartermp** [comment]
We won't be adding this support to legacy projects.
