### ISSUE TITLE
multihop #load "file.fsx" result in duplicate declarations

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#4772]
#### Repro steps

* unzip the attached file: [loadfsx.zip](https://github.com/Microsoft/visualfsharp/files/1935868/loadfsx.zip)
* evaluate the `#load` lines at the top of script.fsx
* evaluate the rest of the file

#### Expected behavior

The evaluation completes successfully

#### Actual behavior

```
script.fsx(7,12): error FS0001: This expression was expected to have type
    FSI_0003.Liba.LibA    
but here has type
    FSI_0004.Liba.LibA    
```

#### Related information 

Tested with VS2015 and VS2017, note that if I comment the first line in script.fsx, I get squiggles in VS2015 but not in VS2017 which indicates that something was fixed.

I'm expecting that arrangement to work but I might be missing something.

**Comment by dsyme** [comment]
@smoothdeveloper You have to use this to get guaranteed consistency between the loaded types in interactive evaluation:
```
#load "liba.fsx" "libd.fsx" "libe.fsx"
```

**Comment by smoothdeveloper** [comment]
Thanks, I wasn't aware of this syntax and is indeed a valid workaround.

Is there a way to lay the several files on separate lines to keep it readable if the list is long?

**Comment by smoothdeveloper** [comment]
In fact, several lines with one level of indentation works fine.

```fsharp
#load "liba.fsx" 
  "libd.fsx" 
  "libe.fsx"
```

**Comment by dsyme** [comment]
Closing as the workaround is correct.
