### ISSUE TITLE
Mistake variable tooltip in diffeditor

### ISSUE THREAD

**Issue by zhuangzhuang** [dotnet/fsharp#4813]
Mistake value tooptip in diffeditor

![screenshot_20180502101917](https://user-images.githubusercontent.com/521058/39502300-002a17d0-4df2-11e8-9a45-f4793a8450d4.png)

file value used in https://github.com/Microsoft/visualfsharp/commit/19d4532ed516db58e6098e08dfea03c32d6f37bc#diff-a519212688039ca4a26b2cc46541c976R750

*visualstudio 2017 15.6.3
*Visual F# Tools 15.6.20180501.1

**Comment by dsyme** [comment]
Closing as no repro is given that's simple enough to go through
