### ISSUE TITLE
typecheck error FS0192: error : tcrefOfAppTy

### ISSUE THREAD

**Issue by haraldsteinlechner** [dotnet/fsharp#4825]
We found a combination of extensions and overloads which breaks the compiler.

@krauthaufen  @aszabo314

#### Repro steps

clone the repo: https://github.com/haraldsteinlechner/badCop
and build...

#### Expected behavior

prints compile errors

#### Actual behavior

fails internally with:
```
2>typecheck error FS0192: error : tcrefOfAppTy
2>typecheck error FS0073: error : tcrefOfAppTy (Failure)
2>parameter error FS0192: error : tcrefOfAppTy
2>	Unhandled Exception: System.Exception: tcrefOfAppT
```

#### Known workarounds

not having compile erros. In our setting we have no workaround yet, since we use compilerservice to parse and check projects with errors.

#### Related information 

newest fsharp compiler and compiler services

**Comment by forki** [comment]
interesting. this only happens in VS. it doesn't in ionide

**Comment by haraldsteinlechner** [comment]
well, the problem occurs in pretty printing of potential overloads. is it possible to disable those precise error messages? @forki

**Comment by forki** [comment]
ok I can repro inside the fsc.exe

**Comment by haraldsteinlechner** [comment]
the problem occurs:
 - in ionide when using netcore etc
 - in vanilla msbuild
 - in compiler services
 - in fsc

**Comment by forki** [comment]
yeah it's in TcNormalizedBinding - I'm on it

**Comment by forki** [comment]
found a possible fix:

![image](https://user-images.githubusercontent.com/57396/39623714-d036006a-4f96-11e8-9433-cbfbbaa0e0c8.png)

**Comment by forki** [comment]
lol that comment abot the formatter

   /// Format a method info using "half C# style".

**Comment by forki** [comment]
fix is in https://github.com/Microsoft/visualfsharp/pull/4826

**Comment by haraldsteinlechner** [comment]
nice one!

**Comment by haraldsteinlechner** [comment]
what is the policy regarding duplicate fixes in compiler service?

**Comment by haraldsteinlechner** [comment]
the same problem occurs in f# compiler services (that is the second spot we stumbled across this issue)

**Comment by forki** [comment]
FCS is part of this repo and the fix applies there as well. After it is
merged @dsyme will push the nuget eventually. In other words: nothing is
needed to do for fcs here

Harald Steinlechner <notifications@github.com> schrieb am Fr., 4. Mai 2018,
12:51:

**Comment by haraldsteinlechner** [comment]
awesome, thanks

**Comment by KevinRansom** [comment]
Re-opening per @forki

**Comment by abelbraaksma** [comment]
This was marked "ready", was it solved? Can it be closed?

**Comment by krauthaufen** [comment]
At least on our end the issue didn't occur for a while...
Correct me if I'm wrong @haraldsteinlechner

**Comment by haraldsteinlechner** [comment]
nope never happened and original repo seems to be "solved" as well.

**Comment by abelbraaksma** [comment]
@haraldsteinlechner, sorry, I don't get it. Do you mean "never happened: the issue disappeared and didn't come back after the fix" or "never happened: a fix was never implemented/working or seen"?

**Comment by haraldsteinlechner** [comment]
should have been never happened *again* ;)
