### ISSUE TITLE
Wrong completion on class definition top level 

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#4854]
If you type `member`, then the following completion pops up:

![image](https://user-images.githubusercontent.com/873919/39745002-b96808f4-52ae-11e8-9218-03ab89ca8bf6.png)

VS 15.7 RTW

**Comment by cartermp** [comment]
Just for posterity, the expectation here is that the `member` keyword is the only thing shown when you are typing it in this context. Even with symbols from unopened namespaces turned off, it will include things which won't work:

<img width="408" alt="screen shot 2018-05-08 at 08 39 56" src="https://user-images.githubusercontent.com/6309070/39767850-8edec29c-529c-11e8-9261-c14964a5e528.png">

**Comment by dsyme** [comment]
I checked and this is fixed - only `member` shows now
