### ISSUE TITLE
Completion for query syntax misses keywords when not bound to a value

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#4864]
Code like this will result in `do` not being in the completion list:

```fsharp
// Example 1
let f() =
    query {
        for i in 1..10 do //<<-- typing here
```
<img width="327" alt="screen shot 2018-05-08 at 22 59 20" src="https://user-images.githubusercontent.com/6309070/39798000-8bc6a8dc-5313-11e8-810d-abec12e0330f.png">

```fsharp
let f() =
    query {
        for i in 1..10 do
    }
```
<img width="289" alt="screen shot 2018-05-08 at 23 00 55" src="https://user-images.githubusercontent.com/6309070/39798042-bc209ac4-5313-11e8-8edf-a9f2b3b064f7.png">

However, if you type the query expression as you are binding its result to something, completion is as expected:

```fsharp
let f() =
    let _ =
        query {
            for in in 1..10 do
```
<img width="368" alt="screen shot 2018-05-08 at 23 01 55" src="https://user-images.githubusercontent.com/6309070/39798088-e186c73e-5313-11e8-975d-c71c73478db1.png">

**Comment by dsyme** [comment]
I don't know what's changed, but `do` appears in the completion list now
