### ISSUE TITLE
Adding a new / existing sql file does not work

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#4895]
## 1

![image](https://user-images.githubusercontent.com/873919/39959051-9d474ca2-5614-11e8-85d4-0301aa71c527.png)

## 2

![image](https://user-images.githubusercontent.com/873919/39959055-b003f0d4-5614-11e8-93bc-0a5a2c2bea47.png)

## 3

![image](https://user-images.githubusercontent.com/873919/39959070-d57255f4-5614-11e8-9b5e-1d60a4b5b45e.png)

## 4

![image](https://user-images.githubusercontent.com/873919/39959073-e7eb7fee-5614-11e8-9d63-2f73a76423cb.png)

**Comment by cartermp** [comment]
Note that this works for SDK-style projects
<img width="394" alt="screen shot 2018-07-29 at 10 37 00" src="https://user-images.githubusercontent.com/6309070/43369022-5cef1042-931b-11e8-83f2-b728c47e6af4.png">

Plan is not 100% committed at this point, but if we open projects with the new project system by default in dev16, then we'll close this out as a WONTFIX

**Comment by cartermp** [comment]
We won't fix the legacy project system to support this, given how things have progressed with .NET SDK-style support.
