### ISSUE TITLE
in type declarations, provided types need to be refered through fully qualified name

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#4899]
#### Repro steps

[fsharp.tp.qualifiedname.zip](https://github.com/Microsoft/visualfsharp/files/1998941/fsharp.tp.qualifiedname.zip)

1. to prepare your environment for the sample, clone https://github.com/fsprojects/FSharp.Data.SqlClient and run build.cmd (this makes sure that the AdventureWorks2012 db is installed)
2. open testsql.fsx
3. evaluate it

```fsharp
#load ".paket/load/net462/fsharp.data.sqlclient.fsx"
#load "sqldefs.fs"

open Namespace.Providers
open Namespace.Constants
type P1Result = { result: P1.dbo.MyProc.Table } // tooling OK but can't compile or evaluate in FSI
//type P1ResultQualified = {result: Namespace.Providers.P1.dbo.MyProc.Table} // works with qualified name
let cmd = new P1.dbo.MyProc(connectionString)
{result = cmd.Execute([]) }

let result : P1.dbo.MyProc.Table = cmd.Execute([]) // it works with type annotations on locals
```

#### Expected behavior

Evaluates properly.

#### Actual behavior

This error message appears on the record declaration, when not using fully qualified name

> error FS0039: The type 'Table' is not defined.

Note that the issue doesn't happen if you use the non qualified name for a local declaration.

#### Known workarounds

Define the types with fully qualified name like done in `P1ResultQualified`.

#### Related information 

reproduces with VS2015 and VS2017

**Comment by dsyme** [comment]
Somehow this surprises me, I can't imagine anything on the compiler side that could cause that behaviour.  The type references `P1.dbo.MyProc.Table` are processed by basically identical code.

Do you only see this error in FSI.EXE?

**Comment by smoothdeveloper** [comment]
No, I actually hit the issue in compiled assembly first before trying to reproduce it in this smaller example.

The fact that the type is an erased one could be a track to investigate.

Also, maybe related, I kind of remember unused opens analysis tend to mark `open` statement containing provided types, I need to narrow this down.

**Comment by cartermp** [comment]
@smoothdeveloper any progress in narrowing this down?

**Comment by smoothdeveloper** [comment]
@cartermp I haven't had a chance to step into the debugger regarding this issue.

I'm not familiar with the representation of erased provided types and name resolution against imported namespaces and how it differs in type declaration versus usage in implementation code.

I've been using the work around (fully qualified names) succesfully so the issue wasn't critical although the bug might cause other issues.

**Comment by cartermp** [comment]
@smoothdeveloper Have you run into this recently?

**Comment by dsyme** [comment]
I'm going to close out this old FSI issue as we only have the one repro for it involving a type provider that has changed a lot in th interim.

**Comment by smoothdeveloper** [comment]
Update in vs2019, with latest release of the type provider:

evaluating code in VS FSI works, but the tooling doesn't pickup the types.

![image](https://user-images.githubusercontent.com/87944/85463554-a00bca00-b55b-11ea-97cb-b7bd1eb09ca6.png)


| Severity | Code | Description | Project | File | Line | Suppression State |
| --------- | --------- | --------- | --------- | --------- | --------- | --------- |
| Error | FS0039 | The type 'Table' is not defined. | F# Miscellaneous Files | C:\tmp\fsharptp\testsql.fsx | 6 | Active |
| Error | FS0039 | The type 'Table' is not defined. | F# Miscellaneous Files | C:\tmp\fsharptp\testsql.fsx | 7 | Active |
| Error | FS1133 | No constructors are available for the type 'FSharp.Data.SqlProgrammabilityProvider<...>.dbo.MyProc' | F# Miscellaneous Files | C:\tmp\fsharptp\testsql.fsx | 8 | Active |
| Error | FS0039 | The field, constructor or member 'Execute' is not defined. | F# Miscellaneous Files | C:\tmp\fsharptp\testsql.fsx | 9 | Active |
| Error | FS0039 | The type 'Table' is not defined. | F# Miscellaneous Files | C:\tmp\fsharptp\testsql.fsx | 11 | Active |
| Error | FS0039 | The field, constructor or member 'Execute' is not defined. | F# Miscellaneous Files | C:\tmp\fsharptp\testsql.fsx | 11 | Active |


![image](https://user-images.githubusercontent.com/87944/85463631-b4e85d80-b55b-11ea-9cbd-c93cb1edd334.png)
