### ISSUE TITLE
`elif` allows invalid syntax.

### ISSUE THREAD

**Issue by nikonthethird** [dotnet/fsharp#4960]
Here's a riddle: What does the following F# code print when compiled as a Console application (not run inside F# Interactive)?

```
if false then
    printfn "False"
elif let x = true in x then
    printfn "True"
```

If you guessed `"True"`, that's wrong. The correct answer is: It prints nothing.

#### Repro steps

The code above is broken. It's missing parentheses around `let x = true in x`. If you try to execute it in F# Interactive, it will fail:

    error FS0010: Unexpected symbol ';;' in if/then/else expression

Also, if you try to write an `else` block or any code after it, Visual Studio will complain:

```
if false then
    printfn "False"
elif let x = true in x then
    printfn "True"
else // <- unexpected keyword 'else' in if/then/else expression.
    ()
```

This only happens with `elif`, `if` requires parentheses:

```
if let x = false in x then // <- incomplete conditional. Expected 'if <expr> then <expr>'
    printfn "False"
elif let x = true in x then
    printfn "True"
```

#### Expected behavior

Syntax error.

#### Actual behavior

No syntax error, the code compiles but doesn't work.

#### Known workarounds

Parentheses, as God intended:

```
if false then
    printfn "False"
elif (let x = true in x) then
    printfn "True" // Actually prints "True".
```

#### Related information 

* F# 4.1
* Visual Studio 15.7.1

**Comment by dsyme** [comment]
This is by design. 

In the F# expression grammar there is an expression form `a then b` used in rarely used secondary object constructors only.  This means `let x = true in x then printfn "True"` is parsing as this expression form, which explains the error given.

You simply have to parenthesize here.

**Comment by cartermp** [comment]
This should be re-opened to track giving better diagnostics.

**Comment by cartermp** [comment]
Hmm, i guess adding a diagnostic would be a breaking change
