### ISSUE TITLE
Can't determine property type when type is only stated in setter

### ISSUE THREAD

**Issue by BentTranberg** [dotnet/fsharp#4986]
I stumble on this at regular intervals, and scratch my head for a while each time.

```
open System.Collections.ObjectModel

type MyType() as this =
    let add s = this.MyCollection.Add s
    let mutable myCollection = null
    let dummy() =
        this.MyCollection <- null
    member __.MyCollection
        with get() = myCollection
        and set (v: ObservableCollection<string>) = myCollection <- v

```

The compiler error message is : "Lookup on object of indeterminate type based on information prior to this program point." The problem is "this.MyCollection" in the "add" function.

The problem as I see it is that the problem isn't prior to this point, so in this particular case the error message should have hinted that the type should be stated in the getter instead of the setter.

Alternatively, and even better, the compiler should be smart enough to also examine the setter for type information.

This is not important at all, but I think it would be nice to have this slight improvement.

Latest public VS 2017.

**Comment by abelbraaksma** [comment]
There's a more general issue with type inference in class definitions: sometimes it succeeds and sometimes it doesn't when the order of the member declarations is not in module order (where this is enforced) wrt type inference discovery.

Not sure if changing the order in your case would fix the problem, but I've stumbled on this quite a few times and not only with gettors. If the compiler needs to look back for a definition for inference it often gives up early.

**Comment by dsyme** [comment]
This is by design for how type inference integrates the information from the property getter
