### ISSUE TITLE
VisualFSharp.sln builds everything even though no code changes

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#5015]
1. Ctrl+F5
2. Builds for long time, a VS launched
3. Close the exp instance
4. Ctrl+F5
5. Builds for long time, a VS launched

Expected: the seconds Ctrl+F5 should start an exp VS almost instantly, without building anything.

**Comment by realvictorprm** [comment]
Although it's not exactly the same as #4533 I think it could be reported there too. Anyways, I feel your pain.

**Comment by cartermp** [comment]
Yes, this is quite annoying, and seems to have _always_ happened. I made sure to always have the dialog pop up for "Do you want to build this project?" just so that I can click "No" in situations like this. No idea why it could be. cc @dsyme

**Comment by dsyme** [comment]
@brettfo I think (no proof :) ) that something in your regressed this, for resources or something.

It's really problematic for working on the IDE tools

**Comment by cartermp** [comment]
I've noticed that this has been the case ever since I first cloned this solution, though. I don't ever remember it _not_ rebuilding redundantly.

**Comment by dsyme** [comment]
> I've noticed that this has been the case ever since I first cloned this solution, though. I don't ever remember it not rebuilding redundantly.

For a while it was working.  But it always seems to regress within a month or less (likewise `build net40` incremental build has regressed multiple times).  It's really annoying to have these regress though....

I think only the people doing active development on the IDE can keep an eye on this. It's hard to put under CI though I guess we could try (just do a second build straight after the first one and check the MSBUILD log)

**Comment by realvictorprm** [comment]
Still No solution? :(

**Comment by realvictorprm** [comment]
Listen fellow MS developers, if you give me a pointer towards how I can analyze why it's always doing a full rebuild I could start investigating this.

**Comment by chillitom** [comment]
@realvictorprm I've had some success in the past for C# projects using this tool: https://github.com/KirillOsenkov/MSBuildStructuredLog

I imagine it should work equally well for F# projects.

**Comment by realvictorprm** [comment]
Thank you very much, I'll give this a try for the VisualFSharp.csproj 👍 !

**Comment by realvictorprm** [comment]
OK thanks to the named tool above I was able to extract what is being rebuild and how long which tasks take. What popped up always was the task GenerateSatelliteAssemblies which most of the time takes more than 1 second and is run kind of for every project (I've got no idea what all this stuff is for but I want to share it).

Moreover some projects contain only this task without anything else like FSharpo.UIResources.csproj .
![image](https://user-images.githubusercontent.com/25414896/44142507-a385ebb2-a080-11e8-92c6-ad5afa693ea9.png)

Got someone of the MS devs any clue?

**Comment by rojepp** [comment]
The first project to rebuild in VisualFsharp.sln is FSharp.Compiler.Private.
The reference to System.ValueTuple is causing this. It has a modified date of '2016-11-05 04:57:30' right now, and this is incorrectly making the project output stale. 

The cause should be here: https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.ProjectSystem.Base/Project/ProjectConfig.cs#L1609

I'm not sure what to do about it.

**Comment by rojepp** [comment]
After that, all template projects get rebuilt every time because they have output type 'Class library' so the up-to-date checker goes looking for the output dll which never gets created. 
These are fairly quick but the vsix will get invalidated by them, so would be nice to fix this also.

**Comment by rojepp** [comment]
I reported a bug for the template projects: https://github.com/dotnet/project-system/issues/4059

**Comment by cartermp** [comment]
I guess it's progress? 🤷‍♂ 

![image](https://user-images.githubusercontent.com/6309070/58294967-a096c780-7d81-11e9-88df-cf3709626544.png)

**Comment by realvictorprm** [comment]
Small progress yes. Yay

**Comment by cartermp** [comment]
This one hasn't happened for me in quite a while. It still takes a short while for MSBuild to crawl the solution and check that everything is built, but there's no recompiling done anymore.

**Comment by abelbraaksma** [comment]
I can second that experience, it's been quite stable recently, and projects that aren't changed aren't rebuild indeed.
