### ISSUE TITLE
Discussion: indentation in VS2017

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#5109]
This is a place where we can share little or big annoyances with indentation, VS (with F#) is not as good as emacs (with haskell/hindent)...

This is a vast topic, but I gather we need to draw inspiration from python and haskell centric editors to find the way to indentation bliss.

I'll just share a first example and append more as I encounter them, please feel free to share your indentation stories.

```fsharp
let carrot () =
    printf "in the soup"
   <|>
```

at this place, there is no space yet on that line (is this called "virtual carret position"?), if I shift + home and press enter it will not behave the same as if there are spaces on the line. 

It should always stick to the leftmost position since I used shift + home and replace the selection with a cariage return, I didn't do all this work to just be at same indentation one line under (which I can achieve by, well, pressing enter).

You often need to de-indent, pressing tab many times is not great, this is frequently done to add another top level declaration.

**Comment by cartermp** [comment]
Labeling as external for now. Smart or Block result in the same behavior, so I don't think we control this.

**Comment by dsyme** [comment]
Closing this very old issue out
