### ISSUE TITLE
Debugger aborts: Evaluation function '....' timed out and needed to be aborted in an unsafe way.

### ISSUE THREAD

**Issue by chillitom** [dotnet/fsharp#5129]
Visual Studio 2017 / 15.7.2

Frequently get the following error when stepping through FSharp code in the debugger.

![image](https://user-images.githubusercontent.com/74433/41095427-4d1ff5c8-6a49-11e8-9855-738705b51a0c.png)

Immediately before the crash I see the following progress dialog:

![image](https://user-images.githubusercontent.com/74433/41095378-26015018-6a49-11e8-8866-8f849545c603.png)

Dialog text:
```
---------------------------
Microsoft Visual Studio
---------------------------
Evaluating the function 'XXX.ToString' timed out and needed to be aborted in an unsafe way. This may have corrupted the target process.

If the problem happens regularly, consider disabling the Tools->Options setting "Debugging->General->Enable property evaluation and other implicit function calls" or change the code to disable evaluation of this method. See help for information on doing this.
```

This seems to occur more frequently when within an async computation expression.

In this example the `ToString` method was being called on a regular F# record type containing `string`, `TimeSpan`, a `string list`, a `string option` and a simple discrimated union (all constructors take no arguments).

**Comment by dsyme** [comment]
This is normally due to the default `%+A` formatting kicking in on structural types. Implement ToString and DebuggerDisplayAttribute on one or more of your structural types.

```fsharp
    [<StructuredFormatDisplay("{DebugText}")>]
    type X = 
        { ... }

    [<DebuggerBrowsable(DebuggerBrowsableState.Never)>]
    member x.DebugText  =  x.ToString()

    override x.ToString() = "FreeVars(...)"
```

**Comment by chillitom** [comment]
Is this a case of data structures being too large to walk over for the formatting?  In this particular case I'm pretty sure all of the types in scope had small object graphs, this seems to occur quite regularly in many different parts of our code base.

Is there a way we could get a stack trace so we could determine which branches or our structures are causing the issue? Would you ever consider auto generating these attributes?

**Comment by cartermp** [comment]
@chillitom even if there are small object graphs, if the data is particularly large it could affect this.

**Comment by dsyme** [comment]
I will close this.  It is a real issue, but one that requires good documentation about writing code that behaves well under a typical debugger
