### ISSUE TITLE
[15.8 Pre 2] line lens does not invalidate correctly

### ISSUE THREAD

**Issue by 0x53A** [dotnet/fsharp#5138]
![2446f08c-2433-4cd8-abab-a2dfdb0de09b](https://user-images.githubusercontent.com/4236651/41124935-bf0cd9ee-6aa3-11e8-9db6-cebfba764c46.gif)

![image](https://user-images.githubusercontent.com/4236651/41125087-fb72d3f2-6aa3-11e8-94ec-ef8f97fb6ac0.png)

**Comment by cartermp** [comment]
Just as a note, this is on by default in Preview 2 but will be off by default in Preview 3

**Comment by realvictorprm** [comment]
Side note by me. There are issues right now which shouldn't be there and I hope to be able to investigate them soon. Sorry for any inconvenience

**Comment by realvictorprm** [comment]
The bug is quite weird. I can't remember that this happened before. I guess something changed in Visual Studio internal :(

**Comment by realvictorprm** [comment]
@0x53A fixed with #5145
