### ISSUE TITLE
The new signature comments popup everywhere, over existing members or comments

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#5157]
I really like the 15.8 addition of the signature comments (not sure if that's the name for it), but they often obscure existing code, or comments and make both unreadable. Or they just appear where there isn't any signature or let binding at all.

Not sure this is a VS feature or an F# feature or both, I'll be happy to post the bug to the VS team instead.

In non-compiled (`#if false`) code, in places where there is no signature at all:

![image](https://user-images.githubusercontent.com/16015770/41190859-4b8034fa-6be6-11e8-929d-76dddae0ce33.png)

Over the signature itself:

![image](https://user-images.githubusercontent.com/16015770/41190873-af768a5e-6be6-11e8-8532-8b8c5c287fc7.png)

There are no signatures at all here:

![image](https://user-images.githubusercontent.com/16015770/41190890-eb51b49a-6be6-11e8-82f5-19ccd1e42655.png)

### Repro steps

Seems to happen basically always when a file is significantly large or when you do some edits back and forth.

### Expected behavior

The comments should not obscure existing text and should appear next to the members or let bindings.

### Actual behavior

They popup everywhere.

### Known workarounds

Switching it off (though I haven't found the setting yet, if it is in Editor > F# > Advanced, then it is currently inaccessible as that crashes VS).

### Related information 

Seen in Visual Studio 15.8.0 Preview 2

**Comment by realvictorprm** [comment]
Hey Sorry for any problems with the line lens.

I've already opened a PR which should at least solve caching problems. It doesn't fix all problems yet and I plan to investigate what happens that the line lens aren't invalidated correctly.

**Comment by realvictorprm** [comment]
You can reproduce this problem by fast jumping around in the code. The code lens should actually disappear  (be set to invisible).

**Comment by abelbraaksma** [comment]
> Hey Sorry for any problems with the line lens.

@realvictorprm  No problem, I'm using the Preview, so things are bound to happen ;).

So this is called the Line Lens? Is there a way I can refresh it or disable it for certain (complex) files? It is very helpful, I really like it, but not so much when it covers existing code or comments...

**Comment by realvictorprm** [comment]
To my knowledge with the next preview it's possible again to disable them.

Refreshing them should easily work through closing and reopening the file.

**Comment by cartermp** [comment]
Yes, in the forthcoming preview 3 of 15.8, they are toggle-able.

**Comment by realvictorprm** [comment]
jesus christ I found the bug. A single field access is wrong 🤣. I'm so sorry fellow F# coders.

@cartermp bugfix incoming.

**Comment by realvictorprm** [comment]
@abelbraaksma this is now fixed too with #5145

**Comment by abelbraaksma** [comment]
@realvictorprm, I can confirm that in VS 2017 15.8 P3 this mostly works now, I can scroll wildly and it remains mostly stable. However, when the option "appear above signature" is on, the refreshing goes wrong sometimes:

![image](https://user-images.githubusercontent.com/16015770/42059445-c8194a46-7b23-11e8-9af9-e4819b490947.png)

![image](https://user-images.githubusercontent.com/16015770/42059462-d857aa9c-7b23-11e8-8d1d-ae2dcd100e3c.png)

Tempo of scrolling doesn't seem to matter. The way it happens for me is when you scroll quickly to a "crowded" place and then halt, that the signature-comments overlap.

Though after it happens, scrolling back and forth a bit restores it again, so the impact of this redraw issue is minor in comparison.

**Comment by dsyme** [comment]
Closing old issue
