### ISSUE TITLE
Wrap codelens logging calls with DEBUG directive

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#5188]
Today, if you turn on dev15.8 Preview 2, the logging of the feature will seemingly hijack the output pane. This is because it does not wrap the calls with `if DEBUG`.

This problem is not as severe starting with Preview 3 now that it is turned off by default, but this must still be done.

**Comment by realvictorprm** [comment]
should I add this to my PR @cartermp?

**Comment by cartermp** [comment]
@realvictorprm that would be great, yes.

**Comment by realvictorprm** [comment]
will do! Is it ok if I leave the warning calls outside of DEBUG? My warnings only appear if something really went wrong.

**Comment by cartermp** [comment]
No, I think this should only be in `#if DEBUG`. If there is an unrecoverable failure, then it should most likely be an exception.

**Comment by mikhailshilkov** [comment]
Installed 15.8 and the "Rechecking code due to buffer edit" issue is really nasty, had to switch Code Lens off again

**Comment by realvictorprm** [comment]
My PR to fix this isn't merged yet, sorry.

**Comment by realvictorprm** [comment]
My PR to fix this isn't merged yet, sorry.

**Comment by cartermp** [comment]
Addressed in #6909
