### ISSUE TITLE
Signature data embedded in executable contains absolute source file path

### ISSUE THREAD

**Issue by marklam** [dotnet/fsharp#5213]
The `FSharpSignatureData` resource embedded in the assembly contains absolute paths to the source files. This could include a user's real name etc.
I know this info is in the pdb, but shipping that with an executable is optional.
Executables produced from C# compiler don't contain file paths

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a simple `test.fs` containing, say, `let main argv = 1`
2. `fsc test.fs`
3. `strings test.exe`
4. observe the full path to `test.fs`

#### Expected behavior

No source paths in the exe

#### Actual behavior

Absolute paths are embedded in the `FSharpSignatureData` resource

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Windows
* Microsoft (R) F# Compiler version 10.1.0 for F# 4.1
* .NET Runtime

**Comment by dsyme** [comment]
I believe this is the only place where the file names are stored:
* https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/TastPickle.fs#L1225

Before we just set this to "null", I should add that these file names are utilised by the F# IDE Tools to allow goto-definition and other things to work when 
1. in-memory cross-project references are off and
2. you're referencing DLL components compiled on your machine.

This means go-to-definition will start failing for these cases if the file name information is just removed.

Alternatives might be 
1. add a compiler option to suppress the generation of this information
2. add a compiler option to opt-in to include this information which is set when compiling from visual studio, or only set for Debug code
3. ??

**Comment by cartermp** [comment]
> or only set for Debug code

Seems like the right call to me. Though we'll also want to make sure this doesn't negatively affect other editors (@auduchinok / @Krzysztof-Cieslak / @nosami FYI)

**Comment by dsyme** [comment]
> or only set for Debug code

I think it would be really odd if GTD only worked across compiled assembly boundaries for Debug mode....   No other design-time tooling depends on this like this....

> Though we'll also want to make sure this doesn't negatively affect other editors (@auduchinok / @Krzysztof-Cieslak / @nosami FYI)

I think it would.  Setting for debug mode is really odd though

**Comment by nosami** [comment]
VSMac can't turn off in-memory cross-project references. I would like to add this feature soon though.

**Comment by cartermp** [comment]
Hmmm. Well I think that from a tooling perspective there's no issue in having this info. What I think I'd prefer is a way to specify a default where this info is _not_ present when building, and have things like design-time builds kick with that feature _turned on_.

**Comment by cartermp** [comment]
Here's what should happen:

1. Ensure that in release builds with the F# compiler, this is **OFF** by default.
2. In a tooling environment, this is **ON** by default.
3. Tools can detect when this is off and can offer to turn them on somehow.
4. Docs, etc. so that people know about the switch and can configure it for their environments.

I've labeled this as `Urgency-Soon` for now, but this is arguably `Urgency-Now`.

**Comment by 0x53A** [comment]
Are you sure the c# compiler doesn't embed any absolute paths?

As far as I know the exe contains an absolute path to the pdb, unless you specifically set a few flags.

**Comment by marklam** [comment]
For a file `test.cs`, containing `class test { public static int Main(string[] args) { return 1; } }`
`csc test.cs`
Then opening `test.exe` in the binary editor shows no pathnames.

**Comment by 0x53A** [comment]
yes, F# is a little bit worse. C# only embeds the absolute path if you generate a pdb, F# does it always.

You can try it with [-pdb](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/pdb-compiler-option), then you should also see a path in C#. (``-pdb`` is the default for a csproj)

I see value in having a way to suppress this (mostly for deterministic builds), but I don't think it should be enabled by default (even in release) if tooling suffers.

**Comment by saul** [comment]
Linking https://github.com/Microsoft/visualfsharp/issues/3812

**Comment by NinoFloris** [comment]
@saul I think F# should do deterministic paths by default when compiling with pdb, like C#. Is PathMap implementation the first step towards doing that or, should it be a native compiler feature

**Comment by 7sharp9** [comment]
I just looked in a release build and found this and others:

```
...
Map`2TypeKindTypeResolvergetShortNamefullName	allScopesseq`1
discoverTypes	ProtoFilefile
resolveScalaroption`1_arg1
ptypeToStringresolveNonScalar
targetTyperesolveresolvePTypeA/Users/dave.thomas/Documents/GitHub/falanx/Falanx.Proto.Generator
```

**Comment by NinoFloris** [comment]
Yeah it's everywhere in F# ecosystem, taskbuilder, saturn, giraffe all have (fun localized) user paths in there.

**Comment by cartermp** [comment]
Re-opening as this is not resolved in VS
