### ISSUE TITLE
F# CodeLens 15.8 preview 2 sometimes is underneath code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#5232]
This causes problems becaus clicking into code to insert cursor results in seleting signature item.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/279698/f-signature-158-preview-2-sometimes-is-underneath.html
VSTS ticketId: 637727_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by dsyme** [comment]
I'm closing this out, partly because code lens is off by default, and we could do a separate QA pass to bring it on
