### ISSUE TITLE
F# Library Project Missing Show All Files option in Solution Explorer for Legacy projects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#5245]
F# Library Project created for .net Framework 4.7.1 does not show 'Show All Files' icon on solution explorer. This is an out of the box project created using the below VS version

Microsoft Visual Studio Professional 2017 
Version 15.7.3
VisualStudio.15.Release/15.7.3+27703.2026
Microsoft .NET Framework
Version 4.7.03056

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/282488/f-library-project-missing-show-all-files-option-in.html
VSTS ticketId: 639369_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment]
As a note, the icon is there for .NET SDK projects:

<img width="312" alt="screen shot 2018-06-28 at 09 40 00" src="https://user-images.githubusercontent.com/6309070/42048159-3f1299c6-7ab7-11e8-8f40-7031e8467d48.png">

So this appears to just be an issue with the legacy project system.

**Comment by cartermp** [comment]
We won't be implementing this for the legacy project system.
