### ISSUE TITLE
Compiler cannot infer which method to override

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#5262]
When there are multiple methods with the same count of parameters available to override the compiler cannot chose a method when enough info is given unless all parameter types are specified explicitly.
```fsharp
type T() =
    abstract member M: int * float -> unit
    default x.M(_: int, _: float) = ()

    abstract member M: string * float -> unit
    default x.M(_: string, _: float) = ()

type T2() =
    inherit T()

    override x.M(_: int, _) = ()
```
<img width="530" alt="screen shot 2018-06-30 at 01 57 51" src="https://user-images.githubusercontent.com/3923587/42118048-109de958-7c09-11e8-9e2f-8310930c387a.png">

**Comment by vasily-kirichenko** [comment]
I can reproduce it in VS 2015, so it's not a regression

![image](https://user-images.githubusercontent.com/873919/42122381-a2d14762-7c49-11e8-9b0d-c8c38abd3f5b.png)

![image](https://user-images.githubusercontent.com/873919/42122389-b833b2ca-7c49-11e8-83e8-684a84f8b3c8.png)

**Comment by dsyme** [comment]
This is by design, a full type annotation is needed on the override
