### ISSUE TITLE
F# compiler throws unhandled exception "internal error : primDestForallTy: not a forall type"

### ISSUE THREAD

**Issue by MaxWilson** [dotnet/fsharp#5293]
I am seeing what I think is a bug in the F# compiler. Trying to compile my cloned version of the [SAFE Dojo](https://github.com/CompositionalIT/SAFE-Dojo) repo gives me a cryptic unhandled exception error: "F# compiler error FS0192 : internal error : primDestForallTy: not a forall type"

#### Repro steps

1. Clone https://github.com/MaxWilson/Repro07042018

2. Go to src\Client directory

3. run msbuild

#### Expected behavior

Should compile correctly, or if I have made errors, should tell me what lines are causing the errors.

#### Actual behavior

Throws unhandled exception:

error FS0192 : internal error : primDestForallTy: not a forall type [c:\code\SafeDojo2\src\Client\Client.fsproj]
  
  Unhandled Exception: System.Exception: primDestForallTy: not a forall type
     at Microsoft.FSharp.Compiler.Tastops.primDestForallTy(TcGlobals g, TType ty)
     at Microsoft.FSharp.Compiler.Tastops.destForallTy(TcGlobals g, TType ty)
     at Microsoft.FSharp.Compiler.Tastops.applyForallTy(TcGlobals g, TType ty, FSharpList`1 tyargs)
     at Microsoft.FSharp.Compiler.Tastops.mkAppsAux(TcGlobals g, Expr f, TType fty, FSharpList`1 tyargsl, FSharpList`1 argsl, range m)
     at Microsoft.FSharp.Compiler.Tastops.MakeApplicationAndBetaReduceAux(TcGlobals g, Expr f, TType fty, FSharpList`1 tyargsl, FSharpList`1 argsl, range m)
etc.

#### Known workarounds

None, other than just giving up on compiling the SAFE Dojo for now.

**Edit**: correction, known workaround is "follow SAFE Dojo correctly." It turns out if I specify "/crime/%s" instead of "/crimes/%s" for my format string in apiRouter, it works correctly.

#### Related information 

* Operating system: Windows 10
* Branch: I don't know what this means. I'm using Visual Studio 2017 15.7.4.
* .NET Runtime, CoreCLR or Mono Version: Not sure but I'm using version 2.1.301 of the .NET Core SDK
* Editing Tools (e.g. Visual Studio Version): N/A, this is a command line repro
* Indications of severity: severe when it happens, total blocker.

Alternate repro: clone SAFE Dojo, execute "build.cmd run" to start the dojo, execute step 1.3  ("add a new endpoint") and wait for recompile to occur. Notice that it now throws unhandled exception whereas it didn't before. I've no idea why.

See https://github.com/MaxWilson/Repro07042018/blob/master/repro.txt for full stack trace.

**Comment by forki** [comment]
ok i can repro.

@dsyme 

this is the place where it fails:

![image](https://user-images.githubusercontent.com/57396/42305986-94390536-802d-11e8-8050-cde9a843419a.png)

for some reason in mkAppsAux we assume the fty is a forallTy, but here it is not. So the following makes the internal error go away:

![image](https://user-images.githubusercontent.com/57396/42306043-bf7d2a24-802d-11e8-8744-4113ee413049.png)

**Comment by dsyme** [comment]
@forki Could you make a repro that doesnt involve fable? My guess is you've done that to debug? Thx

**Comment by forki** [comment]
here is what I did:

* run paket restore in repro folder
* open visualfsharp in VS and set FSC as startupproject
* set working dir to [reprofolder]\src\Client
* set fsc command args to:

    -o:obj\Debug\netstandard2.0\Client.dll -g --debug:portable --noframework --define:TRACE --define:DEBUG --define:NETSTANDARD --define:NETSTANDARD2_0 --optimize- -r:C:\Users\Steffen\.nuget\packages\fable.core\1.3.8\lib\netstandard1.6\Fable.Core.dll  -r:C:\Users\Steffen\.nuget\packages\fable.elmish.debugger\1.0.1\lib\netstandard1.6\Fable.Elmish.Debugger.dll  -r:C:\Users\Steffen\.nuget\packages\fable.elmish\1.0.1\lib\netstandard1.6\Fable.Elmish.dll  -r:C:\Users\Steffen\.nuget\packages\fable.elmish.hmr\1.0.0\lib\netstandard1.6\Fable.Elmish.HMR.dll  -r:C:\Users\Steffen\.nuget\packages\fable.elmish.react\1.0.3\lib\netstandard1.6\Fable.Elmish.React.dll  -r:C:\Users\Steffen\.nuget\packages\fable.import.browser\1.1.1\lib\netstandard1.6\Fable.Import.Browser.dll  -r:C:\Users\Steffen\.nuget\packages\fable.powerpack\1.3.5\lib\netstandard1.6\Fable.PowerPack.dll  -r:C:\Users\Steffen\.nuget\packages\fable.react\3.0.0\lib\netstandard1.6\Fable.React.dll  -r:C:\Users\Steffen\.nuget\packages\fable.recharts\0.1.0-beta-002\lib\netstandard1.6\Fable.Recharts.dll  -r:C:\Users\Steffen\.nuget\packages\fsharp.core\4.2.3\lib\netstandard1.6\FSharp.Core.dll  -r:C:\Users\Steffen\.nuget\packages\fulma\1.0.0-beta-007\lib\netstandard1.6\Fulma.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\Microsoft.Win32.Primitives.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\mscorlib.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\netstandard.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.AppContext.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Collections.Concurrent.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Collections.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Collections.NonGeneric.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Collections.Specialized.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.ComponentModel.Composition.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.ComponentModel.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.ComponentModel.EventBasedAsync.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.ComponentModel.Primitives.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.ComponentModel.TypeConverter.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Console.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Core.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Data.Common.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Data.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Diagnostics.Contracts.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Diagnostics.Debug.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Diagnostics.FileVersionInfo.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Diagnostics.Process.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Diagnostics.StackTrace.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Diagnostics.TextWriterTraceListener.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Diagnostics.Tools.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Diagnostics.TraceSource.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Diagnostics.Tracing.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Drawing.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Drawing.Primitives.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Dynamic.Runtime.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Globalization.Calendars.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Globalization.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Globalization.Extensions.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.Compression.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.Compression.FileSystem.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.Compression.ZipFile.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.FileSystem.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.FileSystem.DriveInfo.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.FileSystem.Primitives.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.FileSystem.Watcher.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.IsolatedStorage.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.MemoryMappedFiles.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.Pipes.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.IO.UnmanagedMemoryStream.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Linq.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Linq.Expressions.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Linq.Parallel.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Linq.Queryable.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.Http.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.NameResolution.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.NetworkInformation.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.Ping.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.Primitives.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.Requests.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.Security.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.Sockets.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.WebHeaderCollection.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.WebSockets.Client.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Net.WebSockets.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Numerics.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.ObjectModel.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Reflection.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Reflection.Extensions.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Reflection.Primitives.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Resources.Reader.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Resources.ResourceManager.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Resources.Writer.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.CompilerServices.VisualC.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.Extensions.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.Handles.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.InteropServices.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.InteropServices.RuntimeInformation.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.Numerics.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.Serialization.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.Serialization.Formatters.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.Serialization.Json.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.Serialization.Primitives.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Runtime.Serialization.Xml.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Security.Claims.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Security.Cryptography.Algorithms.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Security.Cryptography.Csp.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Security.Cryptography.Encoding.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Security.Cryptography.Primitives.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Security.Cryptography.X509Certificates.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Security.Principal.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Security.SecureString.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.ServiceModel.Web.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Text.Encoding.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Text.Encoding.Extensions.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Text.RegularExpressions.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Threading.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Threading.Overlapped.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Threading.Tasks.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Threading.Tasks.Parallel.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Threading.Thread.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Threading.ThreadPool.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Threading.Timer.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Transactions.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.ValueTuple.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Web.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Windows.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Xml.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Xml.Linq.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Xml.ReaderWriter.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Xml.Serialization.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Xml.XDocument.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Xml.XmlDocument.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Xml.XmlSerializer.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Xml.XPath.dll  -r:C:\Users\Steffen\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\System.Xml.XPath.XDocument.dll  --target:library  --nowarn:NU1603 --warn:3  --warnaserror:76  --fullpaths  --flaterrors  --highentropyva-  --targetprofile:netstandard  --simpleresolution  --nocopyfsharpcore  "../Shared/Shared.fs"  ViewHelpers.fs  app.fs  Client.fs

(don't forget to s/Steffen/Don ;-) )

**Comment by isaacabraham** [comment]
@forki no, never seen this bizarrely. @bruinbrown does this ring any bells?

**Comment by isaacabraham** [comment]
@forki ok, this might be related to https://github.com/CompositionalIT/SAFE-Dojo/issues/24. I just cleaned the repo and tried to build, you get that error. If you do a "full" build via the `build` command, it all works.

Strangely enough, you can then go back into VS and build and it works.

**Comment by MaxWilson** [comment]
It turns out that if I follow SAFE Dojo *correctly* the error does not arise. Apparently it's due to my entering "/crimes/%s" instead of "/crime/%s" as my format string in apiRouter. That could explain why nobody else has seen this before--everyone else was using the right format string.

**Comment by forki** [comment]
what!? how can a change in a string constant be the reason here!?

**Comment by isaacabraham** [comment]
@MaxWilson Hmmm. Yet I can repro the error on current master. Clean the repo, open it in VS and try to compile - boom. Most people aren't doing that I imagine though.

**Comment by forki** [comment]
No I don't think so. ;-)
It's a clear problem during compile time and I don't think it's the string constant that is the problem.
Anyway we have a good repro. It's just that I'm not sure if I suggested correct fix

**Comment by dsyme** [comment]
I think this was ultimately fixed as tracked in https://github.com/fable-compiler/Fable/issues/2326.

At least we don't have a repro that just involves the F# compiler, and not Fable too
