### ISSUE TITLE
VS 15.8 Preview 3 F# greedy intellisense

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#5299]
This is a regression and has happened on previous releases.

In some cases mouse-over code results in large repeating intellisense pop-up that really has nothing to do with the code the cursor is over.

Cannont provide screenshot because moving cursor closes the intellisense pop-up. 

F# VS 15.8 Preview 3

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/287559/vs-158-preview-3-f-greedy-intellisense.html
VSTS ticketId: 643399_
_These are the original issue comments:_

Jack Fox on 7/5/2018, 09:52 AM (23 hours ago): Seems to happen when current code is in a "broken" state, i.e. current code being edited does not compile.
_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment]
Filed by @jackfoxy - just to clarify, I believe this is about error recovery in the IDE and how that can affect tooltips.

@jackfoxy, if you use the Windows screenshoot utility and set the delay (I usually do 5 sec) then hover over something to get a tooltip, when the screenshot utility triggers, the tooltip will still be there. You can then attach that as an image.

**Comment by jackfoxy** [comment]
@cartermp thanks, I didn't know about delay


![image](https://user-images.githubusercontent.com/1824476/42390063-89bdbb4c-80ff-11e8-9a11-1311cc3fd5a5.png)

**Comment by cartermp** [comment]
Yeah, that's definitely a bug. 😅

**Comment by jackfoxy** [comment]
This did not get fixed in VS 15.8 preview 5

**Comment by jackfoxy** [comment]
This is type provider related.

This can be replicated with the FSharp.ExcelProvider TP and FSharp.Data.CsvProvider.

**Comment by vzarytovskii** [comment]
A bunch of code was rewritten since then, I am going to close it for now, we'll look at it if it becomes a problem for newer VS
