### ISSUE TITLE
Show property values in the debugger tooltips

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#5319]
C#

![image](https://user-images.githubusercontent.com/873919/42501367-42e2567a-843c-11e8-9ca9-7a1d0fba27e1.png)

F#

![image](https://user-images.githubusercontent.com/873919/42501143-bd947aca-843b-11e8-901f-080b82d776d5.png)

I find the C# editor behavior very, very nice.

**Comment by vasily-kirichenko** [comment]
Rider

![image](https://user-images.githubusercontent.com/873919/42502029-b3b63f3c-843d-11e8-83bb-7f903034e475.png)

**Comment by dsyme** [comment]
This is a duplicate of https://github.com/dotnet/fsharp/issues/1003
