### ISSUE TITLE
No UnusedThisVariable warning when type members have errors

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#5384]
```fsharp
type T123(x: int) as this =
    let x = 123
    override private x.ToString() = ""
```
<img width="295" alt="screen shot 2018-07-25 at 14 24 22" src="https://user-images.githubusercontent.com/3923587/43200579-a0e543b6-901e-11e8-85fc-194f5a353ff3.png">
<img width="314" alt="screen shot 2018-07-25 at 14 25 56" src="https://user-images.githubusercontent.com/3923587/43200581-a101cad6-901e-11e8-9c5e-027e2efae59e.png">

**Comment by cartermp** [comment]
Unused value analysis seems to trigger in VS and VSCode, but the warning diagnostic does not appear as mentioned.

<img width="536" alt="screen shot 2018-07-29 at 09 51 45" src="https://user-images.githubusercontent.com/6309070/43368632-2a0a4cb0-9315-11e8-8a1e-5ef9f4efb04e.png">

**Comment by cartermp** [comment]
Separate bug there, though, as either suggestion to rename `this` to `_` will give an error.

**Comment by TIHan** [comment]
The reason why this happens is because the check happens in post inference checks. If there is a type check error then post inference checks will not run; therefore, no warning.

We have a similar issue when you use byrefs. You won't get any byref errors if type checking failed.

**Comment by auduchinok** [comment]
Another repro is type attributes aren't checked when members have errors.
`FooClass` doesn't allow multiple:
<img width="550" alt="screen shot 2018-09-21 at 19 13 51" src="https://user-images.githubusercontent.com/3923587/45893023-a42d1580-bdd2-11e8-956b-e03d0cb9fea3.png">

With error in member attributes commented out:
<img width="545" alt="screen shot 2018-09-21 at 19 14 01" src="https://user-images.githubusercontent.com/3923587/45893024-a42d1580-bdd2-11e8-8f0e-22f2604d1965.png">

**Comment by dsyme** [comment]
> The reason why this happens is because the check happens in post inference checks. If there is a type check error then post inference checks will not run; therefore, no warning.

This is the explanation - some diagnostics are phased - it's just how it is.
