### ISSUE TITLE
Interfaces colored as classes in tooltips

### ISSUE THREAD

**Issue by asik** [dotnet/fsharp#5385]
Interfaces are colored as classes instead of interfaces in different places in tooltips:

![image](https://user-images.githubusercontent.com/1631157/43216819-f75dfe56-900d-11e8-875b-fe1a223db846.png)
![image](https://user-images.githubusercontent.com/1631157/43216893-1e8c0b44-900e-11e8-9a34-16a09a2f734e.png)
![image](https://user-images.githubusercontent.com/1631157/43216958-4fcc0664-900e-11e8-90f9-be2cf5a3c43c.png)

Visual Studio 15.7.5

**Comment by cartermp** [comment]
Looks like if the interface is defined in F# it's fine:

![image](https://user-images.githubusercontent.com/6309070/44289845-d58e5080-a22a-11e8-9c4e-aa2f56cceabd.png)

But if it's non-.NET, it's misclassified:
![image](https://user-images.githubusercontent.com/6309070/44289861-e8a12080-a22a-11e8-867e-2a59e641695b.png)

**Comment by vasily-kirichenko** [comment]
Disposables have their own color. May it be the case?

**Comment by cartermp** [comment]
There are X separate issues in the tooltips here:

* Interface as the type of a value (or return type) not getting tagged properly
* Interface as the type of a property or return type of a member not getting tagged properly
* Interface when show in XML documentation (via xref tags I presume) not getting tagged properly

**Comment by cartermp** [comment]
Using https://github.com/dotnet/fsharp/issues/9606 as the canonical issue for coloring within the text of an XML comment
