### ISSUE TITLE
Cannot use DefaultValue on default constructors

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#5396]
```fsharp
open System.Runtime.InteropServices

type CompactUnionJsonConverter([<Optional; DefaultValue(true)>] tupleAsHeterogeneousArray) = ...
```
Gives:

`error FS0842: This attribute is not valid for use on this language element`

Is this intentional, or was it just missed in the implementation?

**Comment by zanaptak** [comment]
Looks like it's the wrong attribute. The following compiles:

```fs
open System.Runtime.InteropServices

type CompactUnionJsonConverter([<Optional; DefaultParameterValue(true)>] tupleAsHeterogeneousArray:bool) = class end
```

**Comment by cartermp** [comment]
@zanaptak Thanks! Looks like I got confused on the name there.
