### ISSUE TITLE
Unused value analysis on unused this value can suggest uncompilable code

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#5419]
Given the following:

```fsharp
type C() as this = class end
```

`this` will be marked as an unused value:

<img width="406" alt="screen shot 2018-07-29 at 09 55 50" src="https://user-images.githubusercontent.com/6309070/43368661-98884520-9315-11e8-9409-3d091df3d285.png">

But the second option will result in code that will not compile:

<img width="596" alt="screen shot 2018-07-29 at 09 56 23" src="https://user-images.githubusercontent.com/6309070/43368666-aa88a1ac-9315-11e8-882f-263e1b0221e1.png">

**Comment by psfinaki** [comment]
Also partially blocked by #15636 - hard to test
