### ISSUE TITLE
Unable to apply imported/opened assembly extensions inside a recursive module 

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/fsharp#5440]
Unable to apply assembly attributes inside a recursive module when the attribute is in a namespace that needs to be opened first.

```fsharp
module rec Test

open System
open System.Runtime.CompilerServices

[<assembly:Extension>]
do()
```

Removing rec solves the compilation error
https://sharplab.io/#v2:DYLgZgzgNAJiDUAfAtgexgV2AUwAQCdsBjXAFWwgBcBYAKDtQAdsA7XAZQE8rtkHm2XHsgB0AJQwtKAS2TYRAYVTJG0nPnbZ8AN2lEKdOgG0APAEMIEXgCNgnEAFEAHpVYRpqFgD4AunRioABQAlEA==

This should compile right?

**Comment by TIHan** [comment]
My gut says this should compile; but I'm not 100%.

**Comment by dsyme** [comment]
This should compile, yes

**Comment by auduchinok** [comment]
Looks similar to https://github.com/dotnet/fsharp/issues/7931 (a duplicate?).

**Comment by dsyme** [comment]
Yes a duplicate, thanks
