### ISSUE TITLE
TypeLoadException when defining a recursive union type with [<Struct>] and pointers

### ISSUE THREAD

**Issue by lostmsu** [dotnet/fsharp#5450]
#### Repro steps

Just paste the following definitions into F# interactive (F# 4.1, 4.5 repro as of VS 15.8.0 Preview 5):

```fsharp
[<Struct>] type Ptr<'P, 'T when 'T: struct>(ptr: 'P) = member this.Address = ptr;;
[<Struct>] type MyExpr<'P> = Zero | Reference of reference:Ptr<'P, MyExpr<'P>>;;
```

#### Expected behavior

Should be able to use MyExpr

#### Actual behavior

The second one gives

> error FS0193: internal error: Could not load type 'MyExpr`1' from assembly 'FSI-ASSEMBLY, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

#### Known workarounds

Remove `'T when 'T: struct` constraint and the second `[<Struct>]`

Unfortunately, this forces heap allocation for MyExpr instances.

#### Related information 

FYI, [original question on StackOverflow](https://stackoverflow.com/questions/51642874/how-to-debug-typeloadexception-without-details-in-f-code). Does NOT have additional info.

**Comment by lostmsu** [comment]
This severs applicability of my project https://github.com/lostmsu/ShortPointers , that uses recent `byref` features to make pools with custom allocation and pointer sizes (to fit into caches), as they can not store self-referential unions.

**Comment by zpodlovics** [comment]
@lostmsu If you change the type order 

```fsharp
[<Struct>] type Ptr<'T,'P when 'T: struct>(ptr: 'P) = member this.Address = ptr
[<Struct>] type MyExpr<'P> = Zero | Reference of reference:Ptr<MyExpr<'P>,'P>
```

You can have this:

```fsharp
type Ptr<'T,'P when 'T : struct> =
  struct
    new : ptr:'P -> Ptr<'T,'P>
    member Address : 'P
  end

[<Struct>]
type MyExpr<'P> =
  | Zero
  | Reference of reference: Ptr<MyExpr<'P>,'P>
```

**Comment by cartermp** [comment]
@zpodlovics with F# 4.5 and FSI 10.2.1, the order does not matter.

```fsharp
[<Struct>]
type Ptr<'T,'P when 'T : struct>(ptr: 'P) =
    member __.Address = ptr

[<Struct>]
type MyExpr<'P> =
  | Zero
  | Reference of reference: Ptr<MyExpr<'P>,'P>
```

Produces:

```
error FS0193: internal error: Could not load type 'MyExpr`1' from assembly 'FSI-ASSEMBLY, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

Note that you can pass other structs in just fine, but not recursively; i.e., this works:

```fsharp
[<Struct>]
type Ptr<'P, 'T when 'T: struct>(ptr: 'P) =
    member this.Address = ptr

[<Struct>]
type Foo<'T> = One of 'T | Two of 'T * 'T

[<Struct>]
type MyExpr<'P> =
    | Zero
    | Reference of reference:Ptr<'P, Foo<'P>>
```

So the issue is with recursive definitions.

**Comment by lostmsu** [comment]
@zpodlovics 

> If you change the type order

 bha-ha-ha-ha, that's really funny.

**Comment by cartermp** [comment]
@zpodlovics Order likely matters for SRTP, but this example is not using SRTP - the type is constrained in a way that can be directly represented by .NET IL (`struct`).

**Comment by lostmsu** [comment]
@cartermp could it be a runtime issue then?

**Comment by cartermp** [comment]
@lostmsu No, this is likely an F# issue either in FSI or the compiler or both. See https://github.com/Microsoft/visualfsharp/issues/5450#issuecomment-409973396

**Comment by dsyme** [comment]
There have been some long-standing issues with recursive structs in .NET Reflection Emit.

The F# Interactive ilreflect.fs emit code makes some workarounds for these but there are I think still fundamental limtiations, and it's actually a very tricky problem to solve.

I think we can regard https://github.com/dotnet/fsharp/issues/4041 as the canonical issue for this.

**Comment by lostmsu** [comment]
@dsyme I actually think this issue is not related to interactive. If I remember correctly, this happened in a regular F# project with types being defined directly in a namespace.
