### ISSUE TITLE
Byref type inference prioritizes reference cell types

### ISSUE THREAD

**Issue by TIHan** [dotnet/fsharp#5501]
The example here:
```fsharp
module Test =
    type TestClass() =

        static member TestMethod(x: byref<int>) = ()

    let test x =
        let g = TestClass.TestMethod(x)
        ()

    let test2 () =
        let g = TestClass.TestMethod
        ()
```

For the function, `let test x =`, what do you think `x`'s type will be? It turns out, it's `int ref`, a reference cell type. Also for `let test2 () =`, `g` is `int ref -> unit`. Now, F# will not infer a byref type in let-bound functions, e.g. 

`The parameter 'x' was inferred to have byref type. Parameters of byref type must be given an explicit type annotation, e.g. 'x1: byref<int>'. When used, a byref parameter is implicitly dereferenced.
`

So, I guess it makes sense that it would infer a ref cell type because you were not explicit with a byref type since member methods have implicit rules. But this doesn't feel intuitive to me, IMO. I would either expect the error or it infer it as the correct type, `byref<int>`.

Retaining the implicit for reference cells to byrefs for member methods, I've managed to fix this which then gives me the error mentioned above. I feel that is the most correct behavior. However, this would mean it is a **breaking change**. Whether we consider changing this behavior with type inference in this case or not, we at least have an issue talking about it.

**Comment by dsyme** [comment]
This is by design, and would be a breaking change to change
