### ISSUE TITLE
Can RecdField.rfield_name_generated field be safely removed?

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#5534]
The field tells whether a name of a field in a union case or exception was generated due to a missing name (e.g. `Item1`, `Data0`, etc). The field is currently set to `true` for source-defined fields only. There's a public wrapper property `FSharpField.IsNameGenerated` in Symbols API. It was added by me in https://github.com/Microsoft/visualfsharp/pull/4225 as we needed this info in Rider back then.

Starting from 2018.3 we won't need this field anymore (as it seems now). If the field isn't used by anyone else (nor is planned to) I'll open a PR removing the field when we stop using it.

/cc @TIHan @nosami @Krzysztof-Cieslak

**Comment by nosami** [comment]
Not used by me

**Comment by cartermp** [comment]
I don't think we have any plans to use it, and it seems like it's only used in the tests you wrote AFAICT.\

But why remove it? Do you feel that it is better to not be exposed?

**Comment by Krzysztof-Cieslak** [comment]
It doesn't look like it's used in FSAC anywhere.... but yeah, I kinda don't see a reason to remove it.

**Comment by cartermp** [comment]
@auduchinok Let's go ahead and remove this. Sounds like nobody has any use for it 🙂

**Comment by dsyme** [comment]
I'm closing this old issue - I don't think it's necessary to remove this
