### ISSUE TITLE
Intellisense suggests two different names for the same misspelled type

### ISSUE THREAD

**Issue by nikonthethird** [dotnet/fsharp#5537]
When mistyping a type name with a type parameter, Visual Studio also suggests replacing it by the compiled type name with the backtick and number in it.

#### Repro steps

```fsharp
type First<'T> = {
    X : 'T
}

type Second<'T> = {
    Y : Frist<'T> // This type name is wrong.
}
```

`First` is misspelled. When you click the lightbulb that pops up, these are the suggestions:

![first](https://user-images.githubusercontent.com/15893812/44358366-1600ff00-a4b5-11e8-81c2-5a70a326e3b1.png)

The first suggestion (Replace with First) is expected, the second one is not, but actually works, because it's the name the record actually has in CIL:

```fsharp
type First<'T> = {
    X : 'T
}

type Second<'T> = {
    Y : ``First`1``<'T>
}

let test = {
    Y = { X = 1 }
}
```

I'm still amazed that this actually works!

#### Expected behavior

Only the upper suggestion should be displayed, the other one is confusing to anyone who doesn't know what happens under the hood of .NET.

#### Actual behavior

These suggestions for the `First` type are shown:

* `First`
* ``First`1``

#### Related information 

* Visual Studio Community 15.8.1
* F# 4.5

**Comment by cartermp** [comment]
Seems like a quirk, though I don't know if this is a bug so much as something not accounted for in the design of this feature. The rename suggestion basically takes @forki's work in the compiler to generate suggestions and places them in a list. You'll see the same thing in the error list:

![image](https://user-images.githubusercontent.com/6309070/44367724-6b251c80-a485-11e8-81c9-794197215b0a.png)

@forki what are your thoughts?

**Comment by matthid** [comment]
Well at least everything works so I’m not sure this is actually a bug and you can learn a bit about some f# features here ;)

**Comment by forki** [comment]
Well, I would not say it's a bug, since it's a valid suggestion. On the other hand I personally think it would be an improvement if we penalize differences in special chars stronger. I'm not sure if we should filter it completely

**Comment by dsyme** [comment]
I checked in VS2022 and this has been fixed somewhere along the way
