### ISSUE TITLE
Glitches in argument name completion

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#554]
Here are a few glitches in parameter/settable-property completion in VS2015 – the “NO” cases below look like bugs to me.

```
#load "packages/FSharp.Charting/FSharp.Charting.fsx"
open FSharp.Charting

Chart.Point(da)   // OK completion to “data” after "da"
Chart.Point(data=randomPoints,Ti="")   // OK completion to “Title” after "Ti

Chart.Point(data=randomPoints,Ti)   // NO completion after "Ti"
Chart.Point (data=randomPoints,Ti="")   // NO completion after “Ti" - note the extra space after Point
```

I’m aiming to author the code:

```
Chart.Point (randomPoints,Title="Expected Distribution") 
```

Or

```
Chart.Point (data=randomPoints,Title="Expected Distribution") 
```

Also the attribute case mentioned here: https://github.com/dotnet/fsharp/issues/9053

**Comment by cartermp** [comment]
Tagging for vs2017 Updates for now, but this may slip to an as-of-yet-created milestone that's tooling-related.

**Comment by vasily-kirichenko** [comment]
The first bug is not reproduced on VS 2017 anymore:

![image](https://cloud.githubusercontent.com/assets/873919/25610725/079049fc-2f2d-11e7-9361-a5b6183e1493.png)

The second one (space between ctor name and open paren) is still reproduced:

![image](https://cloud.githubusercontent.com/assets/873919/25610801/4bcbeaf4-2f2d-11e7-850e-8712e0aace8e.png)

(about stuff prepended with `@` see https://github.com/Microsoft/visualfsharp/issues/2973)

**Comment by vzarytovskii** [comment]
Going to close that, since it's old. If more issues like that are observed, a new issue for latest VS should be opened.
