### ISSUE TITLE
Show type of unused variable in tooltip

### ISSUE THREAD

**Issue by torbonde** [dotnet/fsharp#5574]
It would be great to see the type of an unused variable in the tooltip.

Currently, the tooltip shows the type for used variables
![type](https://user-images.githubusercontent.com/5451931/44897894-8dc4fa00-acfd-11e8-9079-173119e18b74.PNG)

But not for unused variables
![notype](https://user-images.githubusercontent.com/5451931/44897921-a59c7e00-acfd-11e8-8374-0fe9af5e6ff8.PNG)

Ionide has this feature, which can be quite helpful.

**Comment by cartermp** [comment]
This no longer reproduces in an script or a project on the latest 16.8 preview builds.

Script:

![image](https://user-images.githubusercontent.com/6309070/90190189-67c28400-dd73-11ea-99db-52e721d6b36c.png)

In a function:

![image](https://user-images.githubusercontent.com/6309070/90190208-701abf00-dd73-11ea-9cb8-07f2ee5fd617.png)

So I'll close this as resolved.
