### ISSUE TITLE
[Legacy project system] F# file drag in solution explorer cause file being renamed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#5585]
When dragging file in solution explorer on to itself file will be renamed to &quot;Copy of Orginal.fs&quot; and being thrown to end of folder (file order matter in F# projects).

Draggin on to itself happen often accidentally when clicking and moving mouse a little bit.

Discussion in stackoverflow: https://stackoverflow.com/questions/52145723/f-double-click-on-file-creates-a-copy-in-vs

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/327630/f-file-drag-in-solution-explorer-cause-file-being.html
VSTS ticketId: 677008_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment]
I don't think we'll be fixing this given the general move to SDK-style.
