### ISSUE TITLE
"Internal error or badly formatted metadata"

### ISSUE THREAD

**Issue by matthid** [dotnet/fsharp#5608]
Continuation of https://github.com/ionide/ionide-vscode-fsharp/issues/912

Ionide:
![image](https://user-images.githubusercontent.com/1866463/45227179-64d5d380-b2c0-11e8-8c07-5c5b7aba7952.png)

VS 2017:
![image](https://user-images.githubusercontent.com/1866463/45227635-3c020e00-b2c1-11e8-9aaa-7bdb7b68f399.png)

```fsharp
open Microsoft.Extensions.Logging
open System

let provider =
    { new ILoggerProvider with
        member x.Dispose() = ()
        member x.CreateLogger name =
            { new ILogger with
                member x.Log<'TState>(logLevel: LogLevel, eventId : EventId, state: 'TState, exception: exn, formatter: Func<'TState, exn, string>) =
                    ()
                member x.IsEnabled (logLevel:LogLevel ) = true
                member x.BeginScope<'TState> (State: 'TState) =
                    { new IDisposable with
                        member x.Dispose() = () } } }
```

#### Repro steps

Paste the above code into your project and install the `Microsoft.Extensions.Logging` NuGet package

#### Expected behavior

Only "exception" should be underlined and the error message should be:

![image](https://user-images.githubusercontent.com/1866463/45227724-72d82400-b2c1-11e8-8c25-02b5b94249d3.png)

#### Actual behavior

"Internal error" is shown to the user

#### Known workarounds

None. Notice that you used an keyword.

#### Related information 

Provide any related information 

* Operating system: Windows 10
* .NET Runtime, CoreCLR or Mono Version: Would assume all?
* Editing Tools (e.g. Visual Studio Version): Ionide + VS 15.7.5
* Indications of severity: Annoyance & Adoption (Problem for beginners)

**Comment by cartermp** [comment]
Thanks, agreed on what the error should be.

Hey @TIHan 
![image](https://user-images.githubusercontent.com/6309070/45229735-8eb8d700-b27b-11e8-9861-3dc9f53ea4c8.png)

**Comment by dsyme** [comment]
This is niche enough that I'm going to close this - `exception` is rarely used and the awkward diagnostic hasn't been seen in other cases.
