### ISSUE TITLE
Compiling and running the compiler in ubuntu

### ISSUE THREAD

**Issue by AviAvni** [dotnet/fsharp#5636]
After compiling this repository on linux with buildfromsource.sh
Unable to run the fsc.exe or fsi.exe

#### Repro steps

git clone https://github.com/Microsoft/visualfsharp.git
cd visualfsharp
src/buildfromsource.sh
dotnet BuildFromSource/Debug/bin/netstandard2.0/fsc.exe

#### Expected behavior
Compiler run successfuly

#### Actual behavior
error about missing fsc.runtimeconfig.json

#### Known workarounds
Copy the fsc.runtimeconfig.json, fsc.deps.json, fsi.runtimeconfig.json and fsi.deps.json from the sdk folder

* Operating system: ubuntu 18.04
* Branch: master
* CoreCLR

**Comment by cartermp** [comment]
cc @KevinRansom @brettfo

**Comment by KevinRansom** [comment]
@AviAvni build from source is intended to build a nuget package, that is an input into the redgate build process.  So it's not really intended to work without the stated workarounds.


However, @brettfo is working on making the product build build correctly with nnet sdk project files, and that is indeed intended to support the scenario you tried.  Build and then run and test from the bin directory.


I hope this helps.


Kevin

**Comment by AviAvni** [comment]
@KevinRansom Thanks. I'm doing this as part of preparing to my workshop about contributing to the compiler at openfsharp conference. I'm ok with using Windows and VS. But I think some attendees will have Linux or Mac so I wanted to see how I can debug the compiler on linux too

**Comment by KevinRansom** [comment]
Nice … good luck :-)

**Comment by KevinRansom** [comment]
Your workaround should work fine.
