### ISSUE TITLE
Overgeneralization of inner functions

### ISSUE THREAD

**Issue by TobyShaw** [dotnet/fsharp#5649]
#### Repro steps
Compile the following code using F# Compiler version 10.1.0

```
type Type1() = class end

// outerNormal has inferred type : (Type1 -> unit)
let outerNormal =
    let innerNormal (bar : Type1) = ()
    innerNormal

// outerBugged has inferredtype: int * (#Type1 -> unit)
let outerBugged =
    let innerBugged (bar : Type1) = ()
    5, innerBugged
```
#### Expected behavior

`outerBugged` should have inferred type: `int * (Type1 -> unit)`, as the `innerBugged` function was explicitly annotated with `Type1` rather than `#Type1`

#### Actual behavior

Mentioned above, 

A function object of type `#T -> ...` will be less efficient than the non-generic version, as it does runtime type-checking.

#### Known workarounds

Provide explicit type annotations.

#### Related information 

Windows 10
F# Compiler version 10.1.0
.NET Framework 4.6.1

**Comment by TobyShaw** [comment]
It's unclear to me whether the generalization is intended or not.

Either way, these examples appear to be inconsistent, and would point to a bug in either direction.

**Comment by dsyme** [comment]
This is intended.  F# eliminates and re-inroduces `#` flexibility for things in argument position, e.g. the first example.
