### ISSUE TITLE
Fix dependencies on Microsoft.VisualStudio.Shell.Immutable.*.0.dll

### ISSUE THREAD

**Issue by brettfo** [dotnet/fsharp#5680]
Currently `FSharp.ProjectSystem.FSharp.dll` depends on `Microsoft.VisualStudio.Shell.Immutable.*.0.dll` which is **not** distributed with `VisualFSharpFull.vsix`, but that assembly is scheduled to be removed from the base VS install.  The possibilities for fixing this are:

1. Migrate to consuming `Microsoft.VisualStudio.Shell.Framework.dll`; all types should be available from there.  **Preferred.**
2. Include the `Microsoft.VisualStudio.Shell.Immutable.*.0.dll` assemblies in the VSIX.  This would be the easier option, but is more likely to cause problems.

See internal bug [280708](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/280708).

**Comment by KevinRansom** [comment]
Done
