### ISSUE TITLE
enable SourceLink for FSharp.Core.pdb

### ISSUE THREAD

**Issue by ctaggart** [dotnet/fsharp#5682]
Following up on #294, please enable SourceLink for the published FSharp.Core.pdb files so that we can debug into the source code just like the rest of dotnet core.

![image](https://user-images.githubusercontent.com/80104/45857903-bf831c80-bd0f-11e8-9a52-05b9771887ec.png)

**Comment by 7sharp9** [comment]
We could do with this asap, stepping through F# code as C# is not fun in the debugger.  Im sure people contributing to the compiler and tools find this painful too as you have to read C# code and cross reference it with the repo here to get a clear picture of what happening.

**Comment by baronfel** [comment]
This _should_ just be a matter of adding a dependency to `Microsoft.SourceLink.Github`, version `1.0.0-beta2-19367-01` and setting a few additional properties in the FSharp.Core Project File (or maybe the FSharpBuild.Directory.Props, depending on conventions?):

```xml
    <!-- Optional: Publish the repository URL in the built .nupkg (in the NuSpec <Repository> element) -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
 
    <!-- Optional: Embed source files that are not tracked by the source control manager in the PDB -->
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  
    <!-- Optional: Build symbol package (.snupkg) to distribute the PDB containing Source Link -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
```

**Comment by cartermp** [comment]
I think https://github.com/dotnet/fsharp/pull/9948 should resolve this issue.
