### ISSUE TITLE
Rename refactoring result of base class is repeated twice.

### ISSUE THREAD

**Issue by hafuu** [dotnet/fsharp#5685]
Rename refactoring result of base class that has generic parameters is repeated twice.

#### Repro steps
1. Input the following code.
```
type X<'a>() = class end
type Y() = inherit X<int>()
```

2. Save the file.

3. Rename `X` to `A`

#### Expected behavior
It is renamed to `A`.
```
type A<'a>() = class end
type Y() = inherit A<int>()
```

#### Actual behavior
It is renamed to `AA`, `A` is repeated twice.
```
type A<'a>() = class end
type Y() = inherit AA()
```

#### Known workarounds

Rename manually.

#### Related information 

* Operating system : Windows 10
* Editing Tools (e.g. Visual Studio Version) : Visual Studio 15.8.5

**Comment by rojepp** [comment]
The behaviour I'm seeing in 15.8.5 is that renaming doesn't change the the second line at all. 
I enter rename mode but as soon as I type a character I leave rename mode.

**Comment by dsyme** [comment]
This is now working AFAICS
