### ISSUE TITLE
F# fast up to date check ignores <UpToDateCheckInput>

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#5725]
If I have an F# project that is using the legacy project format (not the new minimal .net core format). Visual Studio does not honor &lt;UptoDateCheckInput Input=&quot;DotfuscatorConfig.xml&quot;&gt;. Visual Studio should call MSBuild when DotfuscatorConfig.xml changes, but rather it incorrectly thinks the project is up to date.

If I use the same &lt;UptoDateCheckInput Input=&quot;DotfuscatorConfig.xml&quot;&gt;in a csproj file or a minimal .net core F# project, Visual Studio correectly invokes MSBuild when the config file changes.

The reason this needs to work is because my project has an AfterCompile target that reads from a config file. I want Visual Studio to invoke MSBuild whenever this config file changes, so my target will run. If I invoke MSBuild manually on the command line, MSBuild correctly runs or skips my target as necessary. 

I have attached a screenshot showing the verbose log for the FastUpToDateCheck, and a zip file of the sample project. The attached repro does not include my custom AfterCompile target since it is not relevate to this bug.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/344761/f-fast-up-to-date-check-ignores.html
VSTS ticketId: 692387_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment]
Closing this out as we won't be addressing bugs in the legacy F# project system. Given that this works in https://github.com/dotnet/project-system the resolution is to use SDK-style projects
