### ISSUE TITLE
Move mono build to target net472

### ISSUE THREAD

**Issue by brettfo** [dotnet/fsharp#5734]
As of the creation of this issue, the `dev16.0-future` branch targets `net472` for many projects, but mono doesn't yet have reference assemblies for that.  As a result the Linux/mono build still targets `net46`.  Once mono/mono#8657 has been fixed, this needs to be addressed here.  See #5719 for details.

**Comment by cartermp** [comment]
@brettfo Is this still a TODO? I don't quite understand where the mono build determines the TFM but the project files are all using net472

**Comment by cartermp** [comment]
mono build got yote
