### ISSUE TITLE
Improve contribution documentation

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#5791]
In a conversation in my FSSF office hours, a few actionable things were brought up:

- [x] Make it easier for someone to get started with this repo by mentioning it in the readme
- [x] Don't require someone read through a giant guide just to get the solution to open in VS
- [x] Add an inclusive message telling people that no change is too small
- [ ] Make it clear what each area you can contribute to is, and how you do that
- [ ] Give a relative gauge on what is easier for newcomers and what is downright difficult
- [ ] Attempt to simplify the DEVGUIDE and TESTGUIDE without losing information
- [ ] Make it abundantly clear how you debug your changes

Assuming there is no strong disagreement with these points, I'll change appropriate documentation to be a bit friendlier for newcomers.

**Comment by cartermp** [comment]
First phase done:

https://github.com/Microsoft/visualfsharp#the-f-compiler-f-core-library-and-f-editor-tools
https://github.com/Microsoft/visualfsharp/blob/master/.vsconfig

* Cleaned up all outdated info in the README
* Added a quickstart with clear prerequisites and how to build
* Added a `.vsconfig` so that contributors using VS don't need to know what all to install up front

**Comment by cartermp** [comment]
Inclusive message added: https://github.com/Microsoft/visualfsharp#no-contribution-is-too-small

**Comment by dsyme** [comment]
Closing out this old planning issue
