### ISSUE TITLE
A bug for [<CallerMemberName>]

### ISSUE THREAD

**Issue by GratianPlume** [dotnet/fsharp#5798]
I write a function to get the caller function name.
```
[<AbstractClass; Sealed>]
type Param =
    static member callerMemberName([<Optional;CallerMemberName>] value: string) = value
```

It work fine when called by C#. 
But when I try to call it in F#, it was wrong folded:

```
[<AbstractClass; Sealed>]
type Test =
    static member foo() = Param.callerMemberName()
```
Test.foo() allways return null.

**Comment by cartermp** [comment]
So this is a bit of a quirk. The default value of a string is `null`, and since we're not supplying a `DefaultParameterValue`, it defaults to that. This code will work:

```fsharp
open System.Runtime.CompilerServices
open System.Runtime.InteropServices

[<AbstractClass; Sealed>]
type Param =
    static member callerMemberName([<Optional; DefaultParameterValue(""); CallerMemberName>] value: string) = value

[<AbstractClass; Sealed>]
type Test =
    static member foo() = Param.callerMemberName()

Test.foo()
```

Output: `val it : string = "foo"`

But this is arguably a bug, since `CallerMemberName` should imply a default parameter value.

**Comment by dsyme** [comment]
I'll treat this as a possible diagnostic improvement
