### ISSUE TITLE
MailboxProcessor with cancellation regressed to 8X performance loss between 4.2.3 and 4.3.1

### ISSUE THREAD

**Issue by elynnstl** [dotnet/fsharp#5805]
When moving from F# 4.2.3 to 4.2.1 it appears that the mailboxprocessor with a cancellationtoken  regressed and is executing approximately 8 times slower.

The difference between the mailbox using cancellation vs. not is approximately 8 times slower.

It seems to me this is a surprising level of cost to anyone using it and feels like it is a bug.

There was a change to the source code that added cancellation to a path that included timeout logic. From looking at the change history it appears the change to cancellation was made in relation to fixing a bug or race condition.

The change occurred moving from 4.2.3 to 4.3.1 and continues to be slow in subsequent releases. This is shown clearly in the tests in the supplied test solution.

#### Expected behavior

I would not expect an 8X cost to adding cancellation ability.

#### Actual behavior

This is what I get.

#### Known workarounds

No workaround.

#### Related information 

* Operating system - Windows 10
* .NET Runtime, CoreCLR or Mono Version - .NET 4.7.2
* Visual Studio 2017
* Links to performance testing scripts
                 https://github.com/elynnstl/FSharpPerfRegression
* Indications of severity
                 High severity.
![unit tests showing perf change](https://user-images.githubusercontent.com/25394901/47317809-15e5c280-d610-11e8-811f-b3393a0b1168.png)

**Comment by TIHan** [comment]
I can confirm that there is a performance regression here, and is reproducible by testing FSharp.Core 4.2.3 and 4.3.1.

**Comment by dsyme** [comment]
> I'm not 100% if it's a library thing, but maybe what compiler was used to compile the library.

It will be a library thing, there were bug fixes here.

**Comment by matthid** [comment]
Is there any definition of what's a perf regreession and what is acceptable loss for a bugfix? I'm asking because the previous behavior was just plain broken.

**Comment by dsyme** [comment]
> Is there any definition of what's a perf regreession and what is acceptable loss for a bugfix? I'm asking because the previous behavior was just plain broken.

No there is no definition. 

But in this case we must definitely look to see if the perf of the case with cancellation enabled can be recovered in some way.

**Comment by dsyme** [comment]
I'm closing out this old issue - the perf regression is old I think we can consider it baked in now.
