### ISSUE TITLE
F# .net core project referencing .net core/standard project, the error list window shows some errors.

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/fsharp#5823]
### Repro steps
Create a new F# .net core console app project;
Add a new F# .net core classlib project；
Set reference from F# console app to F# netcore classlibrary;
Add line similar to: Say.hello "Lily"
### Expected behavior
No errors in error list
### Actual behavior
There is a red squiggly, and the Error List shows some errors as below, but build and run succeeded.
![21](https://user-images.githubusercontent.com/33921754/47484551-8f7aec00-d86e-11e8-8bdb-d00c68182048.PNG)

### Workarounds
Close VS and reopen the project, restore succeeded with no error in error list window.
Not repro on the .net core 2.2 rtm ([2.2.100-rtm-009546](https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-2/20181023-01/final/assets/Sdk/2.2.100-rtm-009546/dotnet-sdk-2.2.100-rtm-009546-win-x64.exe))  against d15.9/28219.56 (15.9 preview 4.0).

### Related information
D16.0/28222.01 (16.0 preview 1.0) + CLI/SDK [2.2.100-rtm-009546](https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdotnetfeed.blob.core.windows.net%2Forchestrated-release-2-2%2F20181023-01%2Ffinal%2Fassets%2FSdk%2F2.2.100-rtm-009546%2Fdotnet-sdk-2.2.100-rtm-009546-win-x64.exe&data=02%7C01%7Cv-yunwei%40microsoft.com%7C6f232b7eed544f00fb6508d63a0b2e9b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636760217065608823&sdata=cbyoeJwxL%2B5IOyFXjtIk4aqTvLY4S5zKoKj2SW8IE4I%3D&reserved=0)
Dotnet --info
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.100-rtm-009546
 Commit:    47ab6bda5f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.100-rtm-009546\

Host (useful for support):
  Version: 2.2.0-rtm-27023-02
  Commit:  49bbd209e5

.NET Core SDKs installed:
  2.1.500-preview-009335 [C:\Program Files\dotnet\sdk]
  2.2.100-rtm-009546 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-rtm-35537 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-rtm-35537 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-rtm-27023-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

_Originally posted by @YunWeiaa in https://github.com/Microsoft/visualfsharp/issues/5244#issuecomment-432617200_

**Comment by YunWeiaa** [comment]
Also repro on plain 16.0 Preview 1 install.

**Comment by TIHan** [comment]
https://github.com/Microsoft/visualfsharp/pull/5833 should resolve the issue once we merge it and is in the final dev16 preview 1 release.
