### ISSUE TITLE
Range Performance Improvements

### ISSUE THREAD

**Issue by TIHan** [dotnet/fsharp#5826]
Created this issue to track that we need possible perf improvements for handling ranges, especially since we merged this PR: https://github.com/Microsoft/visualfsharp/pull/4476

**Comment by cartermp** [comment]
Using this issue to track any future work with ranges, likely in the context of a redesign so that we don't carry file information around.

**Comment by TIHan** [comment]
The `range` type is 16 bytes now, which IIRC, 16 bytes is the upper bound size that a struct is recommended to be. So, we may actually be fine in regards to performance.

**Comment by dsyme** [comment]
I'm closing this as we've no specific need to improve this that we've noticed
