### ISSUE TITLE
Refactor CommonExtensions\Microsoft\FSharp to not contain VS assemblies

### ISSUE THREAD

**Issue by tmat** [dotnet/fsharp#5832]
`CommonExtensions\Microsoft\FSharp` directory is listed in NGEN probing paths in `devenv.urt.config.tt`. This means NGEN is gonna pick up dependencies from that directory when NGEN’ing VS assemblies. This directory contains System.Collections.Immutable and System.Reflection.Metadata. The problem is that the above system inserts updated versions of these binaries to `PrivateAssemblies` that contain IBC data from the training. This is desirable since we want to optimize these binaries based on the scenarios we run. That means however that the binaries in `PrivateAssemblies` are going to be different than the ones in FSharp directory. NGEN might get confused by that (as it happened in past whenever these didn’t match exactly).

To work around, a list of F# assemblies was added to `devenv.urt.config.tt` (in lab/d16.0stg472 VS branch) with code base specifications for NGEN and a list of F# assembly versions was added to `ProductData\AssemblyVersions.tt`:

```
const string FSharpBuildVersion = "10.2.3.0";
const string FSharpCompilerInteractiveSettingsVersion = "10.2.3.0";
const string FSharpCompilerPrivateVersion = "10.2.3.0";
const string FSharpCompilerServerSharedVersion = "10.2.3.0";
const string FSharpCoreVersion = "4.5.0.0";
const string FSharpDataTypeProvidersVersion = "4.3.0.0";
const string FSharpEditorVersion = "16.0.0.0";
const string FSharpLanguageServiceBaseVersion = "16.0.0.0";
const string FSharpLanguageServiceVersion = "16.0.0.0";
const string FSharpPatternMatcherVersion = "16.0.0.0";
const string FSharpProjectSystemBaseVersion = "16.0.0.0";
const string FSharpProjectSystemFSharpVersion = "16.0.0.0";
const string FSharpProjectSystemPropertyPagesVersion = "16.0.0.0";
const string FSharpUIResourcesVersion = "16.0.0.0";
const string FSharpVSFSIVersion = "16.0.0.0";
```

This is a temporary fix. All binaries need to be removed from `CommonExtensions\Microsoft\FSharp` directory that are not meant to be loaded to devenv process. That means moving `fsc.exe` and `fsi.exe` and their dependencies to a subdirectory of FSharp. I believe this is the best solution as it is one-time refactoring with no need for maintaining list of files in `devenv.urt.config.tt`.

**Comment by KevinRansom** [comment]
This is as done as we are likely to achieve
