### ISSUE TITLE
MatchException causes VS to crash when debugging old-style F# .NET Framework project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#5835]
(en) If run debug this code(F#), VS will freezes and falls.
(ru) Если запустить отладку этого кода(F#), VS сначала зависнет а потом упадет.

let a x = 
    match x with
    | 1 -&gt; printf &quot;a&quot;
    | 2 -&gt; printf &quot;b&quot;
    | _ when x &gt; 4 -&gt; printf &quot;c&quot;

a 3
System.Console.ReadLine();

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/368421/vs-crashes-on-debug-when-use-f-pattern-matching-wi.html
VSTS ticketId: 717991_
_These are the original issue comments:_

jk4kostia on 10/26/2018, 01:00 PM (3 days ago): <p>Same problem with VS 15.8.8</p>

_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment]
I cannot reproduce this with VS 15.8.8.

**Comment by jk4kostia** [comment]
> I cannot reproduce this with VS 15.8.8.

I make video with reproducing:
https://youtu.be/Qzj-KGVyLkA

**Comment by jk4kostia** [comment]
MS feedback  not paste my code correctly, the correctly is:

let a x =
    match x with
    | 1 -> printf "a"
    | 2 -> printf "b"
    | _ when x > 4 -> printf "c"

a 3
System.Console.ReadLine();

**Comment by jk4kostia** [comment]
> I cannot reproduce this with VS 15.8.8.

Maybe because when I threw the report the code of a bit changed (tabs were gone), here’s the source code (it is shown in the video):
`let a x =
    match x with
    | 1 -> printf "a"
    | 2 -> printf "b"
    | _ when x > 4 -> printf "c"

a 3
System.Console.ReadLine();`

**Comment by cartermp** [comment]
@jk4kostia Thanks for the video.

* This reproduces with an old-style .NET Framework project, crashing VS
* This does **not** reproduce with .NET Core in any way
* The debugger crashes when using a .NET SDK-style project targeting .NET Framework, but VS itself does not crash

![image](https://user-images.githubusercontent.com/6309070/47665182-cba79880-db5d-11e8-96bf-881f44b2db83.png)

**Comment by cartermp** [comment]
This no longer reproduces with VS 2019. The exception window is correctly shown and nothing crashes.
