### ISSUE TITLE
Odd behavior with editor tabs being duplicated and quadruplicated in VS2017 15.9

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#5920]
Since it has happened a few times in a row now, I am reporting this since it doesn't seem to be a fluke. I am seeing this:

![image](https://user-images.githubusercontent.com/16015770/48666107-7eaf4600-eabb-11e8-8b3a-de068b755b74.png)

Note that all same-named files here point to exactly the same physical location on disk. I have not attempted to open them multiple times. This happened after a Rebuild-All a couple of times. Since I started out with some 12 or so tabs, I now have 40 or so tabs, each with a `:1` or `:2` in the label.

#### Repro steps

What seems to trigger this:

* Have a multi-project solution (I have mixed F#, C#, don't know if that matters)
* Create a different solution which references partly the same projects (say: one with, and one without NUnit tests)
* Open both in VS2017 15.9, you have two instances open.
* Edit in one instance, compile in the other, or vice versa
* After a while, the tab-duplication starts to occur

#### Expected behavior

No tab duplication should occur. Also, the order of tabs should remain fixed.

#### Actual behavior

Order of tabs changes, tab duplication and quadruplication occurs after some time. Not sure it is specific to F# only, but it happens to me only in F# solutions or mixed solutions.

#### Known workarounds

Close all tabs. Close solution. Reopen solution.

#### Related information 

* Windows 7 or 10 (seen on two systems)
* VS 2017 15.9.0 Professional
* .NET Framework 4.7

**Comment by cartermp** [comment]
@abelbraaksma Do you still see this?

**Comment by abelbraaksma** [comment]
The duplication hasn't appeared in a while. But the jumping around of the tabs is still happening (when you left click or right click a tab they seem to get reordered, but that happens inconsistently, even jumping again when clicking the same tab twice)

Not sure it is related though. Also, this jumping behavior is old, has been there for at least a year or so. If I had to guess, ordering is done based on a hash, which apparently changes, and not by declaration order (preferred for F#), or name order.

**Comment by cartermp** [comment]
@abelbraaksma Now that we've done significant perf improvements in VS 2019 and the editor _may_ not be hanging and misbehaving as much due to the F# language service's gluttonous behavior, have you see this happen with VS 2019?

**Comment by abelbraaksma** [comment]
Nope, as of yet it hasn't in 2019, if it does, I'll create a new issue. Tx!
