### ISSUE TITLE
Error List window is ordered by filename, should be compile order

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#5958]
I'm not sure this is by design or a bug, but it seems like the Error List window in Visual Studio shows errors ordered alphabetically by filename, for errors in a single project with filenames in different directories.

This is after a full build.

### Repro steps

EDIT: Repro is provided in the first comment, just open the solution and build.

It seems I reported this before. https://github.com/Microsoft/visualfsharp/issues/4642, as that report's discussion shows, this behavior appears and reappears. This is currently with 15.9.0. In the previous report, a repro was requested, which I've attached below.

### Expected behavior

Order of errors should be in compilation order, which for F# means the order in which the files are declared in the project files. More precisely, I would expect, after a full build:

* With multiple projects, errors that appear in projects that are compiled earliest, should appear earliest
* Within a project, with multiple files, they should appear in declaration order of these files (as declared in `fsproj`, or as shown in the Solution Explorer)
* Within a file, top-to-bottom makes most sense I think
* Within a line, left-to-right
* Single spot, low error code to high error code (lower errors are usually more severe, though certainly not always)

Point of this order is that often the first error in compile order will be the one to fix that solves many other errors down the line. When an edit creates hundreds of errors, it is non-trivial to find that sore spot.

After errors, warnings should be displayed in the same like order.

### Actual behavior

They appear in an initially unclear order, that seems to be ordered by filename (without clicking the column in the Error List window for different ordering)

### Known workarounds

Search by hand and with knowledge of your own project to find the one that appears first in compile order. This can be time-consuming though, esp. in massive solutions.

### Related information 

VS 2017 15.9.0.

**Comment by abelbraaksma** [comment]
Attached is a repro of a small dummy project in .NET Core:

* It has files One.fs, Two.fs, Three.fs, Four.fs, Five.fs, Program.fs in that order
* Each of the numbered files has one or more errors in it
* Expected: Error List shows errors in the same order as the file order mentioned above
* In fact, I see it in the following order, which is clearly alphabetical:

![image](https://user-images.githubusercontent.com/16015770/49121327-5dffa100-f2b0-11e8-995d-3824fd54effa.png)

[FSharpBug#5958.zip](https://github.com/Microsoft/visualfsharp/files/2622397/FSharpBug.5958.zip)

A few observations:

* It doesn't matter whether it is .NET Core of .NET Framework
* It doesn't matter whether parallel build is on or off in Options
* It happens both in multi-project and single-project solutions
* Types of errors, or dependencies of errors don't seem to matter
* In the Output window, the order of the errors is normal (but this is not good as a workaround as in large, complex project this window contains hundreds, if not thousands of lines and it takes time to find the proper failing ones)
* It happens with and without any extensions installed
* It happens in 15.9.0 and 15.9.2 (the only ones I had readily available)

**Comment by cartermp** [comment]
Thanks, I tried this myself and it reproduces. I'm actually not sure where the issue lies. IIRC it's up to a provider of the error list to define a given order, but since we use the DocumentDiagnosticAnalyzer it's not quite so straightforward. I agree that we should be showing them in the order in which the compiler visits constructs, not ordered by file name. @heejaechang, any ideas?

**Comment by cartermp** [comment]
So we ultimately hash the set of errors that come back and then turn it into an array. Somehow, that ends up ordering by file name. But that point is a bit moot; we've already screwed with the order by hashing them. We'll need a smarter way to de-duplicate errors if we want to show errors in the order in which the compiler sees them.

**Comment by abelbraaksma** [comment]
That explains a lot. Perhaps even why I'm the past it seemed to be sometimes randomly ordered. Maybe an ordered hash algorithm? Where the high bits of the hash key are used for the numerical ordering. Or if you can change the data type, a simple tuple would do the trick.

Alternatively, reorder before it's displayed, if that info (fileposition and line) is still available. I haven't looked at the code, just shooting blind ;)

**Comment by dsyme** [comment]
I think this is surely by design - the ordering in the error window depends on the settings in the error window (e.g. have you pressed File etc.) and won't be the build ordering.

**Comment by cartermp** [comment]
Yeah, looking at this again it does seem like it would be by design.

**Comment by abelbraaksma** [comment]
Yeah, I guess I should make this an improvement suggestion, as the error list isn't all that useful when there are a lot of errors, since in F# the default order should be compile order, not file name order (which is the default regardless of clicking a column).

I've meanwhile grown accustomed to this and scroll through the output window instead, but surely, this experience can be improved for F# coders.
