### ISSUE TITLE
Autocomplete appears when declaring DU

### ISSUE THREAD

**Issue by gsomix** [dotnet/fsharp#5974]
Autocomplete appears when typing DU cases both in Ionide and Rider.

#### Repro steps

Type:
```fsharp
module Test
    
type TestDU =
    | Il
```
![autocomplete](https://user-images.githubusercontent.com/832449/49332792-06717600-f5cd-11e8-8034-edc8d2ee4678.png)

![autocomplete2](https://user-images.githubusercontent.com/832449/49332794-096c6680-f5cd-11e8-8e1b-602eebf228b5.png)

#### Expected behavior

No autocomplete at all, it's a declaration, not a general code.

#### Related information 

* Windows
* Ionide 3.30.0
* Rider 2018.3 EAP 7

```
> dotnet --version
2.1.500
```

**Comment by cartermp** [comment]
Listing as a bug because it feels like one when you type, but this is really because we don't have a completion context for DU case declaration: https://github.com/Microsoft/visualfsharp/blob/e709f52b21db479c198aa7a62e5fd941429df4be/src/fsharp/service/ServiceUntypedParse.fs#L69

**Comment by kerams** [comment]
@cartermp, I think in order to determine the context `SyntaxVisitorBase` would need to be extended. `traverseSynTypeDefn` currently only processes `SynTypeDefnRepr.ObjectModel` and `SynTypeDefnSimpleRepr.TypeAbbrev` with the commend `enums/DUs/record definitions don't have any SynExprs inside them`. Would it be acceptable to add 3 new visitor methods to cover these definition types?

**Comment by cartermp** [comment]
Yeah, I think that's going to be pretty much the only way to handle this without writing a different parser. I'd be happy to look at a draft PR for general direction and we can see if that's acceptable as API additions.

**Comment by gsomix** [comment]
Is it fixed in https://github.com/dotnet/fsharp/pull/12351? @kerams

**Comment by kerams** [comment]
In VS it should be. Hopefully the next preview will contain it.

**Comment by gsomix** [comment]
@kerams Thank you! I'm closing it. :)
