### ISSUE TITLE
Signature help requires a new line in order for it to work

### ISSUE THREAD

**Issue by TIHan** [dotnet/fsharp#6008]
With automatic brace completion off, then typing the following code by itself on one line in a blank file:
```
let _ = System.DateTime(
```

On the beginning paren, you expect to see signature help. 

It doesn't work unless we add a new line:
```
let _ = System.DateTime(

```
If there is a new line after the line you are typing on and you start the beginning paren, signature help will work. 

This is a problem within FCS and have not determined the best way to fix it.

For most developers this will not be an issue since there is usually an new line from the line they are typing on, but for writing tests this is troublesome and requires adding a new line at the end of source text.

**Comment by TIHan** [comment]
Closing as it only occured in my PR: https://github.com/Microsoft/visualfsharp/pull/6001 - normal Dev16 is fine.

**Comment by TIHan** [comment]
I'm still keeping this open actually. So it works in Dev16 fine because we forcefully add a newline when we send it across to FCS.  In the PR mentioned, https://github.com/Microsoft/visualfsharp/pull/6001, we stop doing that and this bug occurs.

**Comment by cartermp** [comment]
Fixed :)
