### ISSUE TITLE
Code lens shows tips overlaying each other

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#6066]
In many of my source files, code lens overlaps itself:

![image](https://user-images.githubusercontent.com/16015770/50738537-61524a80-11d5-11e9-92e9-38d209d3db7d.png)

### Repro steps

I see this happen in almost any less-then-trivial file. Scrolling back and forth used to redraw this, but that doesn't happen.

### Expected behavior

Code lens tips shouldn't overlap. 

### Actual behavior

Some tips from unrelated classes from the same file (in the screenshot you can detect `XdmNode.equals` and `XdmNode.compareTo`, some others aren't even intelligible anymore) overlap with the current class (in this screenshot `XsDuration`).

### Known workarounds

Switch off code lens.

### Related information 

 VS 2017 15.9.4 Pro

**Comment by abelbraaksma** [comment]
@realvictorprm, I thought I'd seen it before indeed. Maybe the PR got lost or forgotten? If it's accepted I'd assume it should be merged, right?

**Comment by psfinaki** [comment]
Hey @abelbraaksma do you think this is still an issue? I wanted to look into that and spent 15 mins scrolling like crazy our CheckExpressions.fs (10 KLOC) but didn't this behavior. CodeLens seems to be _slow_ but not _broken_.

**Comment by abelbraaksma** [comment]
@psfinaki it's been many years ago. Per chance, I just enabled it again a few days ago. It's still very buggy (showing the annotations sometimes halfway the file or in a totally unrelated spot), but the "many tips overlaying" issue, no, I haven't seen that.

If anything, most of the time it doesn't show at all anymore nowadays. Sometimes partially after a long enough wait, on some functions.

### Weird places:
![image](https://user-images.githubusercontent.com/16015770/189980559-10a773be-cf60-43d2-bfe2-19175d31b5d2.png)

### Other weird places:
![image](https://user-images.githubusercontent.com/16015770/189981093-a3592974-d985-4e93-9b5e-1bfb3d8ad31b.png)

### Or missing completely
(sorry for the scratching over the code thing, I am not allowed to share this code, even though it's rather trivial)
![image](https://user-images.githubusercontent.com/16015770/189982094-756de61c-370e-4d11-ae10-542960e5cdb8.png)

**Comment by psfinaki** [comment]
@abelbraaksma alright, thanks for getting back to that, trying this out and sharing screenshots :)

I guess I'll be working on that, I really root for this feature. In a while I'll probably close this particular issue but create new ones for the things you specified, with some good repros. And I'll reach out to you to give this a good testing before we take this out of beta!

**Comment by abelbraaksma** [comment]
VSCode does this excellently, which has been one of the main reasons I've been wanting to switch from VS to Code, but so far haven't for other reasons.

Anyway, I kept it on a little longer, but it starts to interfere with everyday work, so I'm going to switch it off again. Here are some more screenshots to show how messy it can get:

![image](https://user-images.githubusercontent.com/16015770/190154619-93c85129-c1f0-4033-a54f-aed708414e08.png)

**Comment by psfinaki** [comment]
@abelbraaksma sure, feel free to switch it off, we now have (more than) enough of bugs to deal with here.
But yeah I'll ask you to switch it on again once the wave of fixes arrives :D

**Comment by vzarytovskii** [comment]
This particular issue should be fixed in #14023 and should be in 17.5+

**Comment by abelbraaksma** [comment]
Awesome stuff @psfinaki! Once that's out (I unfortunately can't install currently due to installing Preview leading to non-Preview installations of VS defaulting to F# 7, side-by-side is currently broken). Hmm, maybe I test using the built-in "compile-and-run-in-visual-studio".

**Comment by psfinaki** [comment]
@abelbraaksma thanks for your eagerness :) no rush though, I think 17.5 should come out in November and by then I also hope to also address the performance [issue](https://github.com/dotnet/fsharp/issues/14034) so that the feature is not only (rather) bug-free but also usable :D
