### ISSUE TITLE
FSharp.Interactive.Session.bufferEvent causing UI delays that are 5 > x >= 2 seconds

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#6077]
From my UI delays:

![image](https://user-images.githubusercontent.com/6309070/51002739-1e4fea00-14e9-11e9-8755-248241bf2219.png)

This function is the source:
https://github.com/Microsoft/visualfsharp/blob/fead0aac540485683f694524eadad79983ec28d9/vsintegration/src/FSharp.VS.FSI/sessions.fs#L80-L124

I believe the whole thing runs on the UI thread which isn't inherently bad, but a >=2 second delay is a bit much.

**Comment by abelbraaksma** [comment]
Does this happen when you type in FSI inside VS? Or is this called when typing in the main code window, inside some large project?

**Comment by cartermp** [comment]
This is inside VS only, and based on my understanding, when you interact with the FSI window there:

https://github.com/Microsoft/visualfsharp/blob/fead0aac540485683f694524eadad79983ec28d9/vsintegration/src/FSharp.VS.FSI/fsiSessionToolWindow.fs#L212-L215

**Comment by jackmott** [comment]
Maybe a concurrentqueue would perform better here?

**Comment by cartermp** [comment]
I doubt a ConcurrentQueue would help. It runs this routine on the UI thread.

**Comment by jackmott** [comment]
What are the locks for?  Just in case the Timer fires off the function at overlapping intervals?  Could we make that impossible and not need locks?

Alternatively could we use the C# Queue here instead of a linkedlist for better memory locality?

**Comment by cartermp** [comment]
I haven't reproduced this at all and my UI delays internally don't show this either. Will close this out since others haven't really noticed anything significant.
