### ISSUE TITLE
FSharp isn't picking up design time targets from experimental hive

### ISSUE THREAD

**Issue by jjmew** [dotnet/fsharp#6093]
_From @davidwengier on Thursday, 03 January 2019 03:36:33_

Whilst the `launchSettings.json` file specifies an `FSharpDesignTimeTargetsPath` variable, it doesn't seem like there is anything that picks it up. Because of this local changes to the design time targets files are not picked up when using the experimental instance. The workaround is to directly modify the design time targets in the VS installation directory.

I assume we would want to see something like this:
https://github.com/Microsoft/msbuild/blob/d42d3504057ef2b88dd4f68c4bfc5591371bd6fe/src/Tasks/Microsoft.CSharp.CurrentVersion.targets#L323-L328

But there isn't anything like that in https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Build/Microsoft.FSharp.Targets

_Copied from original issue: dotnet/project-system#4423_

**Comment by davkean** [comment]
@cartermp Can you close this bug? This is fixed.
