### ISSUE TITLE
Create a new .NET Core 3.0 F# projects produces a warning about double-imports

### ISSUE THREAD

**Issue by jjmew** [dotnet/fsharp#6094]
_From @davkean on Saturday, 29 December 2018 06:21:38_

Create a new F# Console App (.NET Core) 3.0 project:

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	MSB4011	"C:\Program Files (x86)\Microsoft Visual Studio\2019\16.0stg\MSBuild\Microsoft\VisualStudio\v16.0\FSharp\Microsoft.FSharp.NetSdk.targets" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\3.0.100-alpha1-009667\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FSharpTargetsShim.targets (63,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\Users\davkean\Source\Repos\ConsoleApp335\ConsoleApp3\ConsoleApp3.fsproj]	ConsoleApp3		29	
```

_Copied from original issue: dotnet/project-system#4420_

**Comment by jjmew** [comment]
_From @davkean on Saturday, 29 December 2018 06:21:58_

tag @TIHan

**Comment by jjmew** [comment]
_From @TIHan on Thursday, 03 January 2019 01:28:52_

Will look into why. Tagging @KevinRansom and @brettfo as they have more context on the build.

**Comment by jjmew** [comment]
_From @KevinRansom on Friday, 04 January 2019 03:29:59_

@davkean 

I installed the latest build of vs from dev16.0stg, and the most recent dotnet sdk master build.

Created and built a netcoreapp3.0 F# Console APP, and it built without warning:

![image](https://user-images.githubusercontent.com/5175830/50672574-e2b79c00-0f8d-11e9-823c-bb932bb7fb21.png)


Could you share more details about what you did to create this error?

Thanks

Kevin

**Comment by jjmew** [comment]
_From @davkean on Thursday, 10 January 2019 01:55:01_

This still occurs, I created a library project (.NET Standard). Here's the results of pp: https://gist.github.com/davkean/aba6ff7e97b368fae39528cf66cbdfa9, it happens command-line and in VS:

```
C:\Program Files\dotnet\sdk\3.0.100-alpha1-009667\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FSharp.targets(29,3)
: warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2019\16.0stg\MSBuild\Microsoft\VisualStudio\v16.0\FS
harp\Microsoft.FSharp.NetSdk.targets" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk
\3.0.100-alpha1-009667\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FSharpTargetsShim.targets (63,3)". This is most
 likely a build authoring error. This subsequent import will be ignored. [C:\Users\davkean\Source\Repos\ClassLibrary45\
ClassLibrary1\ClassLibrary1.fsproj]
```

**Comment by dsyme** [comment]
I've not seen this, and there have been no further reports of this
