### ISSUE TITLE
Wrong string literal syntax highlighting

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#6102]
![image](https://user-images.githubusercontent.com/873919/51181578-939e2f00-18dc-11e9-9bfc-818679f2d70c.png)

15.9.5

**Comment by cartermp** [comment]
This doesn't reproduce anymore (code fails to compile since I don't have a database to connect to):

![image](https://user-images.githubusercontent.com/6309070/111573218-52796200-8767-11eb-9360-5ef4acf61ef7.png)
