### ISSUE TITLE
What are nodes of typechecking residues in F# TAST?

### ISSUE THREAD

**Issue by LmTinyToon** [dotnet/fsharp#6103]
I am learning f# compiler internals. And I came across on `TyChoose` and  `Link` nodes of TAST. What's the meaning of such nodes? Here is more detailed question https://stackoverflow.com/questions/54179428/what-are-nodes-of-typechecking-residues-in-f-tast

P.S. Is it valid to ask questions of such kind here as issue? I am usually use for such purposes compiler slack room and stackoverflow. But unfortunately they have slow feedback

**Comment by cartermp** [comment]
Closing old discussion
