### ISSUE TITLE
ByRefLike structs can be declared in Anonymous Record types

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#6104]
The following compiles:

```fsharp
open System

let f (r: {| S: Span<int> |})=  r.S.Length

f {| S=Span<int>.Empty |}
```

It should not compile, because `r` is reference type, thus violating the rules of `ByRefLike` structs.

Given that we [cannot declare a ByRefLike struct anonymous record](https://github.com/fsharp/fslang-suggestions/issues/712), ByReflike types such as `Span` should not be allowed inside of an anonymous record at all.

**Comment by thinkbeforecoding** [comment]
Or could it be auto promoted to byreflike in this case ?

**Comment by cartermp** [comment]
Not in this case, no. This isn't a struct anonymous record declaration.

**Comment by thinkbeforecoding** [comment]
True, but would it be promoted if it was:

`let f (r: struct {| S: Span<int> |})=  r.S.Length`

??

**Comment by cartermp** [comment]
In this case it could be, yes.

**Comment by dsyme** [comment]
This has been fixed somewhere along the way
