### ISSUE TITLE
Cannot pass F# function to another F# function in C# code

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#6128]
![image](https://user-images.githubusercontent.com/873919/51384644-ffc3a180-1b2d-11e9-8da7-5e141a9aef16.png)

**Comment by NinoFloris** [comment]
`FuncConvert.FromFunc(x => handler(x))` should do the trick.

Handler is just a normal method in IL. When a normal method is passed into an FSharpFunc function argument within F# files the compiler will generate the accompanying function type that inherits from FSharpFunc. Just like the C# compiler does the something similar for lambda's by generating a DisplayClass. But although the F# compiler also has support for doing that same work for Func and Action, the C# compiler doesn't at all know about FSharpFunc.

Not sure if there's a more elegant way to fix this, method groups aren't really something you could implicitly convert, nor do I think that's a great idea...

**Comment by dsyme** [comment]
This is by design, or a C# language suggestion.
