### ISSUE TITLE
Completion list appears to treat digit/underscore in identifier as a boundary

### ISSUE THREAD

**Issue by chadunit** [dotnet/fsharp#6134]
Completion list invoked after a digit only searches on the characters after the digit, and upon accepting a suggestion it inserts the suggestion after the digit resulting in duplicated characters.

EDIT: Also happens with underscore.

(Note `Show completion list after a character is typed` is disabled, and completion list is manually summoned via Ctrl+Space.)

![vs completion digit](https://user-images.githubusercontent.com/25489524/51413105-65fef300-1b33-11e9-876e-338f8a7e45e1.gif)

#### Expected behavior

Completion invoked on `UTF8E` should search for `UTF8E`, and entire identifier should be updated when accepting suggestion.

#### Actual behavior

Completion invoked on `UTF8E` only searches for `E`, and accepting the suggestion only applies it to the portion after the digit.

#### Related information 

Visual Studio Community 2017 15.9.4
Visual F# Tools nightly 15.8.20181217.1
.NET Core SDK 2.2.101

**Comment by dsyme** [comment]
I've noticed this, there is definitely something quirky mis-interpreting identifier status.  We should remove this glitch

**Comment by cartermp** [comment]
This should be addressed by https://github.com/dotnet/fsharp/pull/10500
