### ISSUE TITLE
vsintegration\update-vsintegration.cmd outdated, does not work

### ISSUE THREAD

**Issue by majocha** [dotnet/fsharp#6137]
`vsintegration\update-vsintegration.cmd` doesn't work anymore because the bin paths changed.
The section about it in DEVGUIDE.md probably needs updating.

**Comment by dsyme** [comment]
I think it's not needed at all anymore, the new compiler is (I think) always used after VSIX installation without clobbering any binaries.  But we should check (@brettfo?)

**Comment by majocha** [comment]
I had the problem with command line fsi.exe only.
The path that is set in Developer Command Prompt, e.g.
```\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\```
points to older binaries than those installed from nightly builds.
The version numbers are the same, but no anonymous records, that's how I found.

So there is side-by-side, but it's not clear how to get to the new binaries from outside of Visual Studio.

**Comment by dsyme** [comment]
Fixed in https://github.com/dotnet/fsharp/pull/10013
