### ISSUE TITLE
Code seems correct but I keep getting this

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#6140]
Severity	Code	Description	Project	File	Line	Suppression State
Warning	FS3186	An error occurred while reading the F# metadata node at position 1 in table 'itycons' of assembly 'WebSharper.Core.JavaScript, Version=4.5.0.0, Culture=neutral, PublicKeyToken=dcd983dec8f76a71'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.	SharperApp	FSC	1	Active

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/432287/code-seems-correct-but-i-keep-getting-this.html
VSTS ticketId: 774372_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment]
Seems like we're getting confused on the binary to pull in.

**Comment by et1975** [comment]
Just hit this as well: trying to add a reference to azure functions project from a test project.

**Comment by dsyme** [comment]
This is almost certainly due to an inconsistent set of assemblies.  In any case we need a specific repro to dig into this

**Comment by xperiandri** [comment]
I have the same issue in the same scenario
> add a reference to an Azure functions project from a test project.

**Comment by abelbraaksma** [comment]
@xperiandri, can you share repro steps? Does it always happen with a given situation? We should probably reopen this @cartermp?

**Comment by xperiandri** [comment]
@abelbraaksma I cannot minimize my solution that reproduces the issue. I tried to remove pieces from my project, but as long as it is a root project I will remove pieces for ages. The only way I see is to give you the full project privately.
