### ISSUE TITLE
Internal error: empty tuple type

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#6145]
![image](https://user-images.githubusercontent.com/873919/51738217-a6b0bc00-209f-11e9-89fe-f34a04418043.png)

**Comment by cartermp** [comment]
Expected bug: something to the effect of, "It is not valid syntax to use a `with` in a type declaration"

**Comment by dsyme** [comment]
We do give "Unexpected keyword 'with' in field declaration. Expected ':' or other token."  in the error list, but the other error should not be shown

**Comment by abelbraaksma** [comment]
Images are not very handy when searching, so to help people find this:

A normal record gives a proper error:

```f#
type S = { Foo with F }
```

![image](https://user-images.githubusercontent.com/16015770/91581352-a1d47e00-e94e-11ea-9999-567662f03760.png)

An anonymous record gives an additional error: "FS0073: Internal error: empty tuple type"

```f#
type S = {| Foo with F |}
```

![image](https://user-images.githubusercontent.com/16015770/91581519-d0525900-e94e-11ea-8528-1445757f5982.png)
