### ISSUE TITLE
Suggestion: add complexities to xml/intellisense of core functions

### ISSUE THREAD

**Issue by charlesroddie** [dotnet/fsharp#6149]
> @jdh30 F# doesn't give asymptotic complexity in the Intellisense docs of core functions so noobs constantly trip up on terrible performance because they haven't memorized what is fast and what is slow yet. Putting O(n) etc. in the docs for these functions would really help.
> From https://www.reddit.com/r/fsharp/comments/ajhxyc/visual_studio_2019_preview_2_has_been_released_f/eeyq0go/

**Comment by cartermp** [comment]
I don't see a negative in doing this. It would have to be in the `<summary>` tags to show up in Visual Studio IntelliSense, though.

**Comment by dsyme** [comment]
Closing out this request - the docs an examples have been written, but it just isn't in the .NET style of docs to put this information in. I think we would accept it if someone did a completely thorough job end to end, but it's quite a significant amount of work.
