### ISSUE TITLE
What does the "Big O" mean in the tooltip of an error?

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#6160]
I just noticed the following in the tooltip of an error in VS 2017:

![image](https://user-images.githubusercontent.com/16015770/51933813-7308c580-2402-11e9-9856-ec3324fa5d65.png)

I doubt this is a bug, but it confused me a little. Does it mean it is waiting for tasks to complete? Or does it signify something otherwise sensible?

### Repro steps

The error can be seen, among others, with this code snippet (the actual error is sound, the bug report is about the mysterious "O"):

```f#
type ObjectWithPrivCtor private (x: string) =
    static member X = ()
    
module SomeModule =
    let Create x = ObjectWithPrivCtor(x)
```

### Expected behavior

Not sure, some text perhaps? On most objects, it would show the declaration, i.e. in this case, it should show this (but then the error underneath):

![image](https://user-images.githubusercontent.com/16015770/51933953-caa73100-2402-11e9-8ea5-16331c929c96.png)

### Actual behavior

The Big O ;)

### Known workarounds

None

### Related information 

VS 2017, 15.9.5

**Comment by TIHan** [comment]
Ok, that is.. very weird. Are you able to reproduce this in a simple ConsoleApp project?

**Comment by cartermp** [comment]
Yep that's definitely a bug. From a script file in vs2019 p2:

<img width="527" alt="image" src="https://user-images.githubusercontent.com/6309070/51989721-89189380-249f-11e9-93eb-a3d30f146404.png">

**Comment by cartermp** [comment]
It should be showing the error glyph, but for some reason that's not happening.

**Comment by abelbraaksma** [comment]
> Are you able to reproduce this in a simple ConsoleApp project?

@tihan, I should have been clearer, I reproduced it in a clean console project before posting. 

Also, I've seen it longer before but don't know exactly when it appeared first. My guess is that it has something to do with scoping rules, but in earlier, pre 15.6 (I think) this didn't happen.

**Comment by TIHan** [comment]
No worries, just wanted to be sure. Seems @cartermp reproduced it easily as well. So this is definitely a bug. :)

**Comment by abelbraaksma** [comment]
I had a quick look at this, and found the part where the icon-glyphs are used, and they seem sound. But then I realized that this is an error, which doesn't show/use those special glyphs. 

@TIHan or @cartermp, could any of you point me or hint me to the location where these tooltips are generated? I placed a bunch of breakpoints at what I thought were reasonable locations, but they weren't it.

(I know this is a very minor thing with near-zero priority, but I like to pick up a few minor things to get a better feel for this part of the compiler).

**Comment by cartermp** [comment]
This is `KnownImageIds.None` from here: https://github.com/dotnet/fsharp/blob/master/vsintegration/src/FSharp.Editor/LanguageService/Tokenizer.fs#L150

It might be a little tricky case, since the `Item` that lives on the FSharpSymbol is internal (probably for good reason) and is the only thing given that can hint at what it is (a CtorGroup). Perhaps some experimentation here would be worth looking into. Since it's a constructor, it should give `MethodPrivate` as the `KnownImageId`.

**Comment by abelbraaksma** [comment]
> Perhaps some experimentation here would be worth looking into. Since it's a constructor, it should give MethodPrivate as the KnownImageId.

I'll experiment some more. But frankly, I think no image should be shown at all, as for any other error, we don't show the image of the item at the cursor (probably because the signature of the item is unknown). For some reason, in this particular case, the tooltip tries to show an image anyway. Since even if I'd change it to `MethodPrivate`, there wouldn't be an interactive signature next to it.

**Comment by cartermp** [comment]
@abelbraaksma I got rid of the glyph when there's nothing reasonable to show in https://github.com/dotnet/fsharp/pull/9563

![image](https://user-images.githubusercontent.com/6309070/87328974-2a0bda80-c4eb-11ea-9177-f036019eaec2.png)

**Comment by abelbraaksma** [comment]
Cool! Thanks!
