### ISSUE TITLE
Cannot stop evaluating variables during debugging, Cancel button doesn't work, debugger crashes

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#6183]
This has been a problem for some time and it seems to appear in different guises. When a complex record type or other variable is evaluated during debugging, the debugger sometimes fails to do such evaluation. This can be for various reasons (I can imagine: recursion, some lengthy operation, self-references, blocked threads due to breakpoint being hit).

While I can understand the problematic nature of evaluating variables, ideally this shouldn't crash the debugger and, given the option to Cancel, it should be able to actually cancel.

### Repro steps

Expand some complex, self-referencing variable. In my case I think this behavior is caused by `lazy` fields which block the thread and lead to deadlock.

### Expected behavior

Visual Studio shows a Cancel screen, hitting the Cancel button should stop further evaluation.

![image](https://user-images.githubusercontent.com/16015770/52192368-d4d58f00-2849-11e9-8de9-ac2bdf63396c.png)

### Actual behavior

After repeatedly clicking the Cancel button in the above screen, and waiting for some 20-30 seconds, the following appears:

![image](https://user-images.githubusercontent.com/16015770/52192438-2d0c9100-284a-11e9-914b-1cbdeaa08400.png)

Quote:

>The debugger's worker process (msvsmon.exe) unexpectedly exited. Debugging will be aborted.

After this, debugging is ended. The process is repeatable. In this case it happens in the Locals window, but it can also happen in tooltip hovering or clicking the "+" signs in the debugger variable inspector.

### Known workarounds

None that I know of, short of being very careful what variables you open for inspection and which you don't. Inside the Locals window, this often leads to it being impossible to scroll down, as when you scroll it starts the evaluation of earlier unseen fields and this problem appears

### Related information 

Any version of VS 2017. Can't remember whether it happened before in VS 2015 or earlier. It is possible that this problem is not unique to F#, but I haven't encountered it (yet) in C#.

**Comment by TIHan** [comment]
What are you settings for `Tools->Options->Debugging->General` ?

**Comment by abelbraaksma** [comment]
@TIHan, here's a screenshot from my current (and yesterday's) settings. Anything out of the ordinary?

![image](https://user-images.githubusercontent.com/16015770/52227737-ac34b000-28b0-11e9-9731-f0efb70afa8c.png)

**Comment by cartermp** [comment]
There are two related points here:

* Complex data structures should have a `DebuggerDisplay` attribute that only evaluates a subset of the data (such as how F# lists only show the count and the list item sup to 5000 items)
* In VS 2019 the debugger itself will finally be a 64-bit out of process component, which should make related quirks generally easier to deal with

Given that VS 2017 15.9.x is the LTS release and the bar is quite high, I wouldn't anticipate any changes for the F# tools there, so comparing with VS 2019 is going to be the path forward.

**Comment by abelbraaksma** [comment]
> Given that VS 2017 15.9.x is the LTS release and the bar is quite high, I wouldn't anticipate any changes for the F# tools there, so comparing with VS 2019 is going to be the path forward.

@cartermp, I wasn't aware we are in LTS already, but seeing the buzz on VS2019 and the previews, it makes sense. I will try run the same code with VS2019 Preview and see how it behaves. You anticipate it shouldn't crash / timeout / break VS / stop the debugger?

**Comment by TIHan** [comment]
@abelbraaksma I would wait for preview 3 given that preview 2 shipped with a performance bug.

Regarding your image, I would check `Suppress JIT optimization on module load`. That's the only thing that stands out for me.

**Comment by abelbraaksma** [comment]
@TIHan , I'll try that. I thought that this:

![image](https://user-images.githubusercontent.com/16015770/52231518-77c5f180-28ba-11e9-8df5-794ebdadd757.png)

might be the cause. Assuming this is something like `ToString()` on the objects. F# types are known to crash with hash (medium size lists, for instance), so I wouldn't be surprised if a large list or large sequence gets fully evaluated when this is executed.

Hence I think that applying `DebuggerDisplay` to a bit more situations than I have currently, would be a good way forward too.

**Comment by abelbraaksma** [comment]
I think recent updates in VS 2019 have prevented this from happening. In fact, I now often see a clear error on a variable that cannot be evaluated, and the types that used to crash for me seem not to crash anymore.

I'll close this as it appears to be fixed with the new way of how VS 2019 deals with debugger variable expansions.
