### ISSUE TITLE
Inserting automatic opens for modules doesn't show right suggestion

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#6186]
As seen here:

![image](https://user-images.githubusercontent.com/16015770/52223464-f6fcfa80-28a5-11e9-991d-045a9c2ddbea.png)

### Repro steps

Copy this code (in a place where you don't already have `LanguagePrimitives` open) and hover over the `GenericXXX`:

```f#
let rec inline factorial n = 
    match n with
    | _ when (n=GenericZero) -> printfn "hi!  %d" n; GenericOne
    | _ -> printfn "howdy!  %d" n; n * (factorial (n - GenericOne))
```

### Expected behavior

The _automatic opens_ feature (if that's how it's called) should open `LanguagePrimitives`

### Actual behavior

But it opens just `Microsoft.FSharp.Core` (which is redundant), after which `LanguagePrimitives` still isn't in focus and the code still won't compile.

### Known workarounds

Type the code yourself ;).

Possibly this has to do with these declarations being `let inline` inside `LanguagePrimitives` or something?

**Comment by matthid** [comment]
Might be related to https://github.com/Microsoft/visualfsharp/issues/6043

**Comment by cartermp** [comment]
Yes, in this case only the module should be opened. FSharp.Core is sort of a weird base case since the namespace is pulled in by default.

**Comment by abelbraaksma** [comment]
> Yes, in this case only the module should be opened. 

Note that not even the module is being opened. After clicking the item in the dropdown, the code still won't compile, because `LanguagePrimitives` was not opened.

**Comment by abelbraaksma** [comment]
Rereading my report in light of what @matthid  linked to, I seem to have been a bit unclear, so:

* Issue #6043 is about `Microsoft` being included when you add an `open` automatically
* This issue is about `LanguagePrimitives` not being added, nor being shown in the options, nor in the Preview window. Result of solving your squiggly after clicking the suggestion: still unsolved, non-compilable code.

**Comment by cartermp** [comment]
Sorry, I should have been more clear, it should have suggested `open Microsoft.FSharp.Core.LanguagePrimitives` as the thing to open.

**Comment by matthid** [comment]
Sorry if the hint was wrong/misleading. I just assumed it might have to do with the special handling of the 'Microsoft.' namespace, but maybe it doesn't.

**Comment by abelbraaksma** [comment]
Np, I actually think it has to do with modules only containing inline members. But I can be wrong also ;)

**Comment by dsyme** [comment]
This is a more general problem, e.g.

```
module M = 
  module N = 
     let xxxxx = 1

xxxxx
```

suggests opening `M` not `M.N`.

**Comment by GennadyGS** [comment]
Is it included in VS 17.1?
It still does not work for me in VS 17.1 so I am trying to find out whether problem is in my fix or it is just not included in release.
Thanks.

**Comment by kerams** [comment]
I don't see the FSharp.Core suggestion from the OP repo in 17.2 Preview, so my guess is it didn't make it into 17.1.

**Comment by GennadyGS** [comment]
@kerams 
Thank you for answer.
Can you please clarify what is "FSharp.Core suggestion from the OP repro"?

**Comment by GennadyGS** [comment]
@cartermp 
Thanks for clarification

**Comment by GennadyGS** [comment]
@kerams 
Thanks.
Do you see correct suggestion "FSharp.Core.LanguagePrimitives" in 17.2?

**Comment by kerams** [comment]
Yup.
