### ISSUE TITLE
.NET Core fsi VS integration : interrupt server 

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#6221]
Related to #2407 

Just to mention that the F# Interactive supported by .NET Core is missing some functionality which is currently relevant to hosting F# Interactive inside Visual Studio.  

* [ ] "Interrupt execution".  This is currently implemented by opening a "back door" .NET remoting connection and calling `Interrupt`.  

* There's also #6185 but that's not particularly VS-related

This corresponds to `FSI_SERVER`.

I don't really care how we implement this functionality - certainly we don't need to use .NET remoting which is not supported in .NET Core - but we should make sure we implement the end-user features as part of the VS integration for .NET Core scripting.

**Comment by vzarytovskii** [comment]
I think this is done by @KevinRansom via the controlled execution.
