### ISSUE TITLE
Pdb2Pdb.exe failed with -532462766

### ISSUE THREAD

**Issue by forki** [dotnet/fsharp#6226]
local build on master (31a98b9c8064a57bc7f0b7d0edc1381efea98a14) after `git clean -xdf` with `build.cmd debug`:

![image](https://user-images.githubusercontent.com/57396/52550057-bbe35580-2dd6-11e9-9d6d-d6b62c7ce8b7.png)

**Comment by forki** [comment]
calling it manuall and we see netstandard can't be found:

![image](https://user-images.githubusercontent.com/57396/52550171-36ac7080-2dd7-11e9-91c3-f426270f3bc3.png)

**Comment by abelbraaksma** [comment]
I linked issue #6182, not sure it's related as that was not a .NET Standard project, but this remarkably unique error number is the same.

**Comment by cartermp** [comment]
@tmat any ideas about this error? I haven't seen it myself

**Comment by tmat** [comment]
No idea :(

**Comment by cartermp** [comment]
I just tried with `dev16.0` branch and it doesn't reproduce on master either 😕

**Comment by forki** [comment]
No it does only reproduce in one of my machines. The other one is fine

Am Mo., 11. Feb. 2019, 23:45 hat Phillip Carter <notifications@github.com>
geschrieben:

**Comment by KevinRansom** [comment]
@forki for the machine that repros the issue, what version of VS is installed.

And can you attach the fsharp.proj.build.binlog from the artifacts\logs\debug directory please

Thanks

**Comment by forki** [comment]
sure.

15.9.6 

[fsharp.proj.build.zip](https://github.com/Microsoft/visualfsharp/files/2854545/fsharp.proj.build.zip)

**Comment by KevinRansom** [comment]
@forki, it would seem as if the runtime can't find netstandard.dll
When running this command:
````
"C:\Users\Steffen\.nuget\packages\Pdb2Pdb\1.1.0-beta1-63314-01\tools\Pdb2Pdb.exe" "d:\code\visualfsharp\artifacts\bin\FSharp.Core\Debug\net45\FSharp.Core.dll" /out "d:\code\visualfsharp\artifacts\SymStore\net45\FSharp.Core.pdb" /srcsvrvar SRC_INDEX=public
````

Gives this message:
````
Unbehandelte Ausnahme: System.IO.FileNotFoundException: Die Datei oder Assembly "netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
````
On my machine it locates it from the GAC:

![image](https://user-images.githubusercontent.com/5175830/52661796-a7c35500-2eb7-11e9-9357-a2a4988cff6a.png)


I suppose the install of the desktop framework might have gone wrong:

To see what versions of netstandard you have in the GAC:

type:
    gacutil -l netstandard
````
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The Global Assembly Cache contains the following assemblies:
  netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL

Number of items = 1

c:\microsoft\visualfsharp\fcs>
````

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/52850705-6bd8fb80-3114-11e9-9b77-ddc1cb0a5149.png)

but why would I habe that? and why does it need it in GAC?

**Comment by KevinRansom** [comment]
@forki, I have no idea .. to both questions.  netstandard.dll is deployed with the desktop dotnet framework into the framework directory, and I believe should load from there.

What version of the desktop framework is installed on your machine:
I am using 4.7.2
![image](https://user-images.githubusercontent.com/5175830/52880408-be1b1c00-3116-11e9-8a85-ed47b7d2a3f4.png)

**Comment by forki** [comment]
ok it looksm like I don't  have 4.7.2 and I can't install it (because WIndows!) - anyway DEVGUIDE only lists 4.6 as requirement.

**Comment by cartermp** [comment]
Ergh, looks like we'll need to update that. Although the projects themselves don't require it in `master`, it looks like we do actually have a dependency on `net472`, since we're now working with netstandard2.0 components. I'll update it.

@forki You should be able to install it from the VS installer as a redistributable. I believe it will cause a reboot if you're on an older version of Windows though.

**Comment by abelbraaksma** [comment]
Glad you found the cause :). Can we conclude that exit code 532462766 means a missing assembly? And if so, is there any way the message can be improved (text instead of number)?

Considering that my linked situation had this error only once it might have been a temp disk failure, hiccup or network interrupt.

**Comment by forki** [comment]
No unfortunately I can't install net472 because I can't update win10,
because reasons.

But it's OK now I know and can just continue to use my laptop instead.

Am Mo., 18. Feb. 2019, 20:46 hat Abel Braaksma <notifications@github.com>
geschrieben:

**Comment by cartermp** [comment]
@forki Have you had the chance to work on a machine with net472? If so, does this reproduce?

**Comment by cartermp** [comment]
@forki Any update? I was unable to reproduce with net472 on my machine

**Comment by forki** [comment]
I think I'll reopen if I see it again. Thanks

**Comment by abelbraaksma** [comment]
While this issue was closed, it still happens. I have reported in the still open connected issue though, that is: #6182.
