### ISSUE TITLE
F# Quick Action "Name can be simplified" breaks logic

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#6227]
See screenshot.

The quick action suggests that &quot;bar2.&quot; be removed, breaking the code logic.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/448919/f-quick-action-name-can-be-simplified-breaks-logic.html
VSTS ticketId: 789046_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment]
Confirmed on Preview 2
<img width="638" alt="image" src="https://user-images.githubusercontent.com/6309070/52582701-a83dec00-2de2-11e9-8409-77f3d97830e0.png">

**Comment by charlesroddie** [comment]
Similar but subtly different issue, found on VS 16.0.1:

If `Y` is a constructor, living inside a class or module `A`, and `A` is open, and `Y` has a different binding, then the expression `A.X` gets the incorrect message "name can be simplified".

![image](https://user-images.githubusercontent.com/19760720/56429928-879b8200-62bc-11e9-9bc7-2be07e93fbde.png)

**Comment by psfinaki** [comment]
Currently doesn't reproduce for any of the above:

![image](https://github.com/dotnet/fsharp/assets/5451366/d0837ad5-b61d-428b-ba76-d906f966caa7)

Code:

```fsharp
type Foo = { myInt: int }
type Bar1 = { test: Foo }
type Bar2 = { foo: Foo }

let test (foo: Foo) (bar1: Bar1) (bar2: Bar2) = 
    if bar1.test.myInt = foo.myInt then ()
    if bar2.foo.myInt = foo.myInt then ()
    ()
```

![image](https://github.com/dotnet/fsharp/assets/5451366/d4438aaa-d116-43f6-8828-698a5fa8e8db)

Code:

```fsharp
module B

module A = 
    let X() = ()
    type Y() = class end

open A

let X = 0
let Y = 0
let AX = A.X
let AY = A.Y

type DU =
    | X
    | Y

    member t.AX = A.X
    member t.AY = A.Y
```

Hence closing, please reopen if this still somehow applies.
