### ISSUE TITLE
Something is referring to 3 strings in the FSharpPackage that cannot be found

### ISSUE THREAD

**Issue by davkean** [dotnet/fsharp#6245]
My ActivityLog states the following:

``` XML
-<entry>
<record>622</record>
<time>2019/02/19 00:11:32.518</time>
<type>Warning</type>
<source>VisualStudio</source>
<description>Performance warning: String load failed. Pkg:{871D2A70-12A2-4E42-9440-425DD92A4116} (FSharpPackage) LANG:0409 ID:6000 </description>
</entry>

-<entry>
<record>623</record>
<time>2019/02/19 00:11:32.520</time>
<type>Warning</type>
<source>VisualStudio</source>
<description>Performance warning: String load failed. Pkg:{871D2A70-12A2-4E42-9440-425DD92A4116} (FSharpPackage) LANG:0409 ID:6001 </description>
</entry>

-<entry>
<record>625</record>
<time>2019/02/19 00:11:32.850</time>
<type>Warning</type>
<source>VisualStudio</source>
<description>Performance warning: String load failed. Pkg:{871D2A70-12A2-4E42-9440-425DD92A4116} (FSharpPackage) LANG:0409 ID:100 </description>
</entry>
```

**Comment by davkean** [comment]
I don't see a package registration in here: https://github.com/Microsoft/visualfsharp/blob/46b758f1142011029d5cd61959c64bf6e3acdb66/vsintegration/Vsix/RegisterFsharpPackage.pkgdef. I can't find that pkg.

**Comment by abelbraaksma** [comment]
What version of FSharp or VS does this apply to?

**Comment by cartermp** [comment]
@davkean looks like it's in the dev16.0 branch: https://github.com/Microsoft/visualfsharp/blob/dev16.0/vsintegration/Vsix/RegisterFsharpPackage.pkgdef#L8

@brettfo would know more.

**Comment by davkean** [comment]
That's a reference to package but I cannot find the actual package definition, I would expect to see that GUID under a Packages key. Bear in mind it mind be auto-generated via the `[PackageRegistration]` attribute - but a search in the code base doesn't show one.

**Comment by davkean** [comment]
It looks like this is the package: https://github.com/Microsoft/visualfsharp/blob/a58d9e6fc5e5499d808cd833af402521c757f23a/vsintegration/src/FSharp.Editor/LanguageService/LanguageService.fs#L83, but I can't see how/when this is registered. I do see this (different) package: https://github.com/Microsoft/visualfsharp/blob/46b758f1142011029d5cd61959c64bf6e3acdb66/vsintegration/Vsix/RegisterFsharpPackage.pkgdef#L15 - but cannot who implements this.

**Comment by dsyme** [comment]
I'm going to close this as we don't know of any serious problem this causes.  @davkean If necessary can you reopen with more information about what might need to be fixed here or what the external manifestation of this might be beyond the activity log?
