### ISSUE TITLE
VS2019 editor scrolls up when entering bracket on last visible line

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#6312]
#### Repro steps

* edit an .fsx file
* put the carret on the last visible line (the file has to have more lines bellow the viewport)
* then enter a bracket

#### Expected behavior

do not have the viewport scroll up, if it has to scroll for some reason, it should scroll down, not up.

#### Actual behavior

![brackets completion last line](https://user-images.githubusercontent.com/87944/54064507-d936f400-41c9-11e9-8d79-22b78ecf3477.gif)

#### Known workarounds

Taller screens 👍 

#### Related information 

![image](https://user-images.githubusercontent.com/87944/54064576-611cfe00-41ca-11e9-9c09-286e0c690717.png)

**Comment by cartermp** [comment]
This seems like an editor behavior since we don't control the viewport. Can you file this with the VS report a problem tool? We ca route it to the appropriate are a from there.

**Comment by smoothdeveloper** [comment]
@cartermp, thanks for the feedback, this issue is only affecting F# editor AFAICS, looked at .sql .txt and .cs files and couldn't reproduce it.

**Comment by dsyme** [comment]
I'll close this as AFAIK it's not something we directly control
