### ISSUE TITLE
F# project netcore 'local' variables window not valid

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#6347]
VSF_TYPE_MARKDOWNUsing a netcore F# console project.

When stopped at a break point, the 'Locals' variables window shows items that don't make any sense. 

For example, instead of the name of the variable in the &quot;Name&quot; column, I see something like:

&quot;DataProcessing.ml.get returned&quot;

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/488569/f-project-netcore-local-variables-window-not-valid.html
VSTS ticketId: 819406_
_These are the original issue comments:_

Visual Studio Feedback System on 3/14/2019, 00:30 AM (6 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment]
Example 
<img width="275" alt="image" src="https://user-images.githubusercontent.com/6309070/54723788-f783e480-4b25-11e9-823c-e95dafed20a8.png">

I expect this is due to some of the oddities in ML.NET cc @dsyme

**Comment by dsyme** [comment]
I don't think this is enough to repro, nor is it anything we control
