### ISSUE TITLE
Nuget package restore crash VS on .NET Standard

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#6367]
To reproduce:

1. Create a new .NET Standard F# class library

2. Type in to the package manager console: Install-Package SQLProvider

3. Observe the VS to come non-responsive while Windows Problem Reporting taking all the CPU.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/489862/nuget-package-restore-crash-vs-on-net-standard.html
VSTS ticketId: 820635_
_These are the original issue comments:_

Visual Studio Feedback System on 3/14/2019, 07:26 PM (7 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment]
It's unclear what the cause of this, but it's 100% reproducible in VS 2019 as well.

**Comment by cartermp** [comment]
This does not reproduce on the latest 16.5 previews. My guess is it was an underlying VS issue, not an F# issue, and it has been fixed.
