### ISSUE TITLE
code action has wrong label when module name contains underscore (minor/vs2019)

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#6397]
![image](https://user-images.githubusercontent.com/87944/55255105-fc782080-5216-11e9-8680-35b37c91ccb2.png)

The code action seems to be labelled with two consecutive underscores, which should be only one.

The actual code insertion is correct.

#### Related information 

![image](https://user-images.githubusercontent.com/87944/55255158-2598b100-5217-11e9-8e2a-7a45ee793e88.png)

**Comment by dsyme** [comment]
I don't repro this, I got the right text:

```
module My_Module =
   type Foo = | Foo

open My_Module

Foo
```
