### ISSUE TITLE
VF# Language Service, syntax coloring glitch due to empty hash directive

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#6400]
In ilpars.fs, usage of empty directives such as `# 3 "..\..\absil\ilpars.fsy"
` messes the colorization:

![empty directive messing syntax coloring](https://user-images.githubusercontent.com/87944/55273085-72b26c80-5283-11e9-9bc5-2421091b857e.gif)

Are those directives equivalent to `#line`?

It is worth enhancing the colorization code for it to complete on this file.

**Comment by TIHan** [comment]
This is actually the same problem from issue #7000 .

**Comment by realvictorprm** [comment]
Finally!
