### ISSUE TITLE
Fix anonymous records tests on netcoreapp2.1

### ISSUE THREAD

**Issue by brettfo** [dotnet/fsharp#6429]
PR #6413 disabled the tests in [`tests/FSharp.Compiler.UnitTests/Language/AnonRecords.fs`](https://github.com/Microsoft/visualfsharp/blob/88d18d99dba8497d073f3c80c9ddee1b3c45bed1/tests/FSharp.Compiler.UnitTests/Language/AnonRecords.fs) because they were failing to find `mscorlib`.  These same tests pass on `net472`.

**Comment by cartermp** [comment]
No longer the case anymore: https://github.com/dotnet/fsharp/blob/master/tests/fsharp/Compiler/Language/AnonRecordTests.fs
