### ISSUE TITLE
"F# Properties" font not applied at the point of usage

### ISSUE THREAD

**Issue by asik** [dotnet/fsharp#6459]
#### Repro steps

In Options -> Environment -> Font and Colors, set "F# Properties" to something visibly different.
![image](https://user-images.githubusercontent.com/1631157/55760505-4ee0ea80-5a2a-11e9-8b42-c54a755243d0.png)

#### Expected behavior

The syntax highlighting applies to properties wherever they are used.
Question: should it apply to record properties?

#### Actual behavior

The syntax highlighting is only applied on declarations.

VS 2019 16.0.0

**Comment by cartermp** [comment]
This is resolved as of VS 16.8 where we revamped classification. F# properties are now just "User properties" and they work as expected:

![image](https://user-images.githubusercontent.com/6309070/111573609-1692cc80-8768-11eb-9465-a134fba4079b.png)
