### ISSUE TITLE
Implement List.choose, Seq.tryPick, etc. for valueoption

### ISSUE THREAD

**Issue by cmeeren** [dotnet/fsharp#6467]
(This post has been edited 2019-04-23 to constrain/concretize the functions I'd like to be implemented.)

The `ValueOption` module now has feature parity with `Option`. That's great! But there's a lot of other functions in other modules that use `Option`, where `ValueOption` might provide better performance by avoiding unneeded allocations. I am primarily concerned with having `ValueOption` equivalents of the following functions:

* `List.choose` / `Seq.choose` / `Array.choose`
* `List.pick` / `Seq.pick` / `Array.pick`
* `List.tryPick` / `Seq.tryPick` / `Array.tryPick`
* `List.unfold` / `Seq.unfold` / `Array.unfold`

These are arguably the most useful to implement, since they (potentially) allocate one `option` object for each item. If further prioritization is needed, then I'd guess `choose` and `tryPick` are the most commonly used.

(For the sake of completeness: Additional functions in these modules that could be implemented too are all the `tryX` functions that *return* an option, but in this issue, I choose to concentrate only on the above.)

I might be able to submit a PR if I get some general guidance on what to add where (never contributed code to FSharp.Core before). For example, should I duplicate existing functions but use `ValueSome`/`ValueNone`, or should old functions delegate to new functions in some way, etc. (I suppose the performance will be best with completely separate definitions.) But I'm more than happy to let other people take it, too.

**Comment by abelbraaksma** [comment]
Wouldn't this lead to an enormous function bloat if we double each function that returns an option or list of options?

Not that I have a better idea...

**Comment by cmeeren** [comment]
> Wouldn't this lead to an enormous function bloat if we double each function that returns an option or list of options?

That depends on how many there actually are. I haven't counted; it might not be that many.

> Not that I have a better idea...

Me neither. I can't see a way around it. If we want `ValueOption` to be as easy to use as `Option` - and why wouldn't we (AFAIK the only reason `ValueOption` was added instead of just making `Option` a struct was to preserve backwards compatibility) - then such generic utility functions must exist.

They could be "hidden" behind some `ValueOption` module (with `List`, `Seq` etc. submodules containing the functions.)

**Comment by dsyme** [comment]
We did discuss this in the RFC (`List.tryPickV` etc.).  I'm open to the idea, it would be good to get performance and code/function-bloat statistics to back up the proposal.

**Comment by cmeeren** [comment]
I can't really help with performance measurements (it would, I guess, depend heavily on the use-case and input size - but in general you'd avoid unnecessary allocations if I understand correctly). But I can probably go through relevant parts of the API to make a more exhaustive list of functions.

However, I'd need to know where to look in the first place, though. I know of `Seq`, `Array`, and `List`. Any other modules I should check?

**Comment by smoothdeveloper** [comment]
In ideal world, is it something that could be solved later via either SRTP (to have same function apply to both), or later on when trait / instance / type class / "extend everything" support will be added to CLR?

In the meantime, maybe the extra modules / functions could be contributed under fsprojects or similar in a third part nuget?

After a while, we should see how `ValueOption` users adopt those functions in the wild.

**Comment by zpodlovics** [comment]
As these abstractions created to address the performance issues (~heap allocation) and as only the compiler allows to **remove** abstractions, it should remain in core.

Option and ValueOption looks similar but not always interchangable, each have their own use-case and sweet-spot, usually ValueOption is preffered but this is not always true. eg.: you cannot do do atomic operations (Exchange/CompareExchange/Increment/etc) with a large ValueOption due the struct tearing.

**Comment by cmeeren** [comment]
I have now edited the OP with the specific functions I'd like to see implemented (as well as some other edits).

**Comment by cartermp** [comment]
@cmeeren Can you file a language suggestion?

I think we'd be fine with a PR that implements these functions for the purposes of benchmarking, but the standard approval process would need to be applied for anything further.

**Comment by cmeeren** [comment]
@cartermp Are you talking about a language suggestion in fsharp/fslang-suggestions and a PR with the implementation here in dotnet/fsharp?

**Comment by cartermp** [comment]
@cmeeren correct. Though if it's easier to just implement them in a simple project that might be easier, so long as that implementation is representative of what would go into FSharp.Core.
