### ISSUE TITLE
Type provider tests are commented out

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#6547]
There are type provider tests commented out, see https://github.com/Microsoft/visualfsharp/blob/master/tests/fsharp/TypeProviderTests.fs#L32

This is my fault, see https://github.com/Microsoft/visualfsharp/pull/4867/files#diff-616d66881094b9f537bcf2a5a4c13f69R33

**Comment by dsyme** [comment]
(I will work on this)

**Comment by KevinRansom** [comment]
Again Don, I will take care of this.

**Comment by dsyme** [comment]
It's done in #6548

**Comment by cartermp** [comment]
They're not commented out anymore
