### ISSUE TITLE
Cannot use indexer syntax on overloaded extension indexer

### ISSUE THREAD

**Issue by varon** [dotnet/fsharp#6669]
The inference seems to not correctly specialize `.Item` extension methods on generic types.

#### Repro steps
```fsharp
module Test

type ``[,]``<'a> with
    member this.Item
        with get(x,y):'a = this.[x,y]
        and set(x,y) (v:'a) = this.[x,y] <- v

let arr:string[,] = Array2D.create 2 2 ""

// try to use our indexer:
arr.[(1,0)] <- "test2" 
```

#### Expected behavior

Presumably it should work? or at least throw an error near the `.Item` extension method if this isn't allowed rather than a type error.

#### Actual behavior
```
error FS0001: This expression was expected to have type
    'a []    
but here has type
    string [,]    
```
#### Known workarounds

You can define separate `.get(x,y)` and `.set(x,y) v` methods, but those are clunky at best.

#### Related information 

* W10
* Net472, F# 4.6.
* Visual Studio 2019

**Comment by zpodlovics** [comment]
C# has an IndexerName attribute for custom indexer [1]. Unfortunately I did not found any IndexerName entry in the F# codebase.

[1] https://stackoverflow.com/questions/5110403/class-with-indexer-and-property-named-item

**Comment by varon** [comment]
Thanks for the feedback and update, @zpodlovics .

That's a solid information and a good workaround. I'll expand a little to try and better highlight where the inconsistency is.

It's entirely possible to define overloaded indexers with different parameters that both use the name `.Item` (and work properly with the expected indexer syntax):
```fsharp
type Foo() =
    member x.Item
        with get(v:int) = v
        
    member x.Item
        with get(v:string) = v
        
let foo = Foo()
let n = foo.[1]
let n2 = foo.["test"]
```

It's also entirely possible to define indexers as extension methods on types that do not have them (and work properly with the expected indexer syntax):
```fsharp
type Byte with
    member x.Item
        with get(v:string) = v

let by:Byte = 1uy
let n = by.["test"]
```

Yet for some reason I can't define a custom overloaded indexer with the 'normal' syntax on a type that already has one defined. This seems like strange and inconsistent behaviour.

**Comment by dsyme** [comment]
I don't really understand the original repro here.  There is already 2D indexing on 2D array types:

    arr.[1,0] <- "test2"
