### ISSUE TITLE
VS2019 autocompletion commits keywords on space

### ISSUE THREAD

**Issue by charlesroddie** [dotnet/fsharp#6695]
### Problem

Completion is committed with space for keywords only. This is annoying behavior in a language where short names are common, as short names (`let a = `) are often replaced with keywords (`let and =`).

### Repro / Actual behavior

1. Create new F# .Net Standard library.
2. Entering 'a' brings up a completion list with selected item "and". Entering space then completes it.
3. Entering 'b' brings up a completion list with selected item "box". Entering space doesn't complete it.
4. A word gets completed by space if and only if it is a keyword (any word highlighted blue in VS by default).

### Expected behavior

Preferably space should not commit a completion for any items.

Alternatively, if some people want space to commit, there should be an option to disable it under Tools -> Options -> Text Editor -> F# -> Intellisense.

### Related information 

- VS 2019 16.0.2, default settings as far as I am aware
- Related issues: https://github.com/microsoft/visualfsharp/issues/6099, https://github.com/microsoft/visualfsharp/issues/3844

**Comment by cartermp** [comment]
@charlesroddie can you give an example of where completion is triggered on `let a`? Doing it as a local binding, script file, in a library, or above the `main` function in a console app doesn't trigger it.

Looking at the code, I think a quick fix might be able to address this, but having a repro would help.

**Comment by charlesroddie** [comment]
Sorry for delay. I can't repro the exact text in the OP. Here is one that happens reliably.

![Completion1](https://user-images.githubusercontent.com/19760720/59424393-d270dc00-8dcb-11e9-9517-0dd3b5ec9059.gif)

**Comment by charlesroddie** [comment]
a-z, space and delete:
![Completion2](https://user-images.githubusercontent.com/19760720/59456165-aa09d180-8e0d-11e9-8d56-b03650ebc8f6.gif)

**Comment by charlesroddie** [comment]
A workaround is Ctrl-Alt-Space to toggle from completion mode to suggestion mode.
https://blogs.msdn.microsoft.com/zainnab/2010/01/22/intellisense-suggestion-mode/

This issue also affects C# so is perhaps a global VS setting? I will close this as not F# specific but if the setting is controlled on a per-language basis then I can reopen @cartermp .

**Comment by cartermp** [comment]
In this case there are a variety of issues here:

* Suggesting when it should not (e.g., `t` for the this-qualifier)
* Suggesting things that don't make sense (e.g., `static` when inside a let binding)

However it's tricky, since many of these suggestions are valid. For example, `match` for `m` makes sense if you're actually going to have a `match` expression. So it's really a lot of small issues that exacerbate the default setting.

**Comment by jdh30** [comment]
That workaround is just what I needed, thanks!!!
