### ISSUE TITLE
Intellisense for overriding methods

### ISSUE THREAD

**Issue by Happypig375** [dotnet/fsharp#6701]
Specifically, I would like to see Intellisense enabled when I type
```fs
[<AbstractClass>] type A() = abstract M : unit -> unit
type B() = inherit A()
           override __.
```

A member list with `M` would be shown, and I can select it. This is super useful to find out which methods can be overridden for a class from a library.

**Comment by dirtybytes** [comment]
This is sorely needed. No intellisense when overriding a member makes discovering APIs in F# a miserable experience.

To demonstrate the problem - define a class in a C# project:

```cs
public class CSharpClass {
    public virtual void DoSomething() { }
    public virtual string DoSomethingElse(int x) => "";
}
```

Then try to inherit from it in an F# project in the same solution:

```fsharp
type CSharpClassDerived() =
    inherit CSharpClass()
    override this.DoSomething() = () // no help from the IDE whatsoever until after you've finished typing the entire line
    override this.DoSomethingElse x = "" // a list of members pops up only after typing the first uppercase D
```
