### ISSUE TITLE
Is there any uwp or wpf template with f# in visual studio? 

### ISSUE THREAD

**Issue by khoshroomahdi** [dotnet/fsharp#6752]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Step A

2. Step B

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

#### Expected behavior

Provide a description of the expected behaviour.

#### Actual behavior

Provide a description of the actual behaviour observed. 

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Operating system
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Editing Tools (e.g. Visual Studio Version)
* Links to F# RFCs or entries on https://github.com/fsharp/fslang-suggestions
* Links to performance testing scripts
* Indications of severity

**Comment by cartermp** [comment]
There aren't any templates for it, no. I don't think we plan on adding them due to the lack of visual designer support.
