### ISSUE TITLE
CLI produces unicode symbols that don't appear correctly in VSCode

### ISSUE THREAD

**Issue by samuela** [dotnet/fsharp#6755]
Moving from https://github.com/fsharp/fsharp/issues/878...

Please provide a succinct description of the issue.

I have a file with a few compile errors. That's all fine. Here's the output from `dotnet run`:

```
cloudbuild [master !?] -> dotnet run
/Users/skainswo/dev/kumo/new-world/src/cloudbuild/Program.fs(89,8): error FS0365: No implementation was given for 'Newtonsoft.Json.JsonConverter.WriteJson(writer: Newtonsoft.Json.JsonWriter, value: Status, serializer: Newtonsoft.Json.JsonSerializer) : unit' [/Users/skainswo/dev/kumo/new-world/src/cloudbuild/cloudbuild.fsproj]
/Users/skainswo/dev/kumo/new-world/src/cloudbuild/Program.fs(89,8): error FS0365: No implementation was given for 'Newtonsoft.Json.JsonConverter.ReadJson(reader: Newtonsoft.Json.JsonReader, objectType: System.Type, existingValue: Status, hasExistingValue: bool, serializer: Newtonsoft.Json.JsonSerializer) : Status' [/Users/skainswo/dev/kumo/new-world/src/cloudbuild/cloudbuild.fsproj]
/Users/skainswo/dev/kumo/new-world/src/cloudbuild/Program.fs(89,8): error FS0054: This type is 'abstract' since some abstract members have not been given an implementation. If this is intentional then add the '[<AbstractClass>]' attribute to your type. [/Users/skainswo/dev/kumo/new-world/src/cloudbuild/cloudbuild.fsproj]
/Users/skainswo/dev/kumo/new-world/src/cloudbuild/Program.fs(92,19): error FS3213: The member 'WriteJson<'a0,'a1> : 'a0 * Status * 'a1 -> unit' matches multiple overloads of the same method.Please restrict it to one of the following:   WriteJson : Newtonsoft.Json.JsonWriter * obj * Newtonsoft.Json.JsonSerializer -> unit   WriteJson : Newtonsoft.Json.JsonWriter * Status * Newtonsoft.Json.JsonSerializer -> unit   WriteJson : Newtonsoft.Json.JsonWriter * obj * Newtonsoft.Json.JsonSerializer -> unit. [/Users/skainswo/dev/kumo/new-world/src/cloudbuild/cloudbuild.fsproj]

The build failed. Please fix the build errors and run again.
```

Note the question marky things after "method.", "following:" and "-> unit".

Now here's what that looks like in the VSCode integrated terminal on macOS:
![screen shot 2018-10-11 at 10 17 31 pm](https://user-images.githubusercontent.com/226872/46849256-7de01180-cda3-11e8-8339-58f514c072b6.png)

Now the question marky things are backspace "e"s. Notice "followinge" and "unite".

#### Related information 

Provide any related information 

* Operating system: macOS 10.14
* Branch: n/a
* .NET Runtime, CoreCLR or Mono Version: .NET Core 2.1.403
* Editing Tools (e.g. Visual Studio Version): Version 1.29.0-insider (1.29.0-insider) (f151c46b1783cf4f9a4ca934a85f78846f08688e)

**Comment by cartermp** [comment]
This is probably the newline characters in the message: https://github.com/dotnet/fsharp/blob/master/src/fsharp/FSComp.txt#L1349

Not sure how to reconcile that with the VSCode terminal.

**Comment by auduchinok** [comment]
I've previously reported it in https://github.com/dotnet/fsharp/issues/4516.
The resolution was to leave corrupted output as it was. I'd be glad if it's being revisited.

**Comment by samuela** [comment]
@auduchinok That doesn't really sounds like a resolution haha

**Comment by cartermp** [comment]
This one no longer reproduces in VSCode for me in VSCode. Will close as no repro

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/6309070/89497317-f4b47e80-d770-11ea-8c3f-ca56da3ee512.png">
