### ISSUE TITLE
`string` can throw for voptions

### ISSUE THREAD

**Issue by ntwilson** [dotnet/fsharp#6782]
`string` doesn't seem to have the same support for voptions that it has for options.  For both voptions and options, using the .ToString() method can throw: (`None.ToString()` & `ValueNone.ToString()`), but `string` handles None by somewhat elegantly returning an empty string (and has the same behavior for `null`).  When calling `string ValueNone` though, it throws an exception.  Interestingly, `string [None]` and `string [null]` both return "[null]", but `string [ValueNone]` throws an exception as well.  
I apologize if this is intended behavior and I just can't find the discussion of it. 

#### Repro steps

1. open fsi 
2. type `string ValueNone;;` and witness the exception
3. type `string [ValueNone];;` and witness the exception

#### Expected behavior

I expected it to return "" and "[null]" or some other sensible values.

#### Actual behavior

It throws exceptions.

#### Known workarounds

Use `sprintf "%A"` or pattern match before attempting to call `string`.

#### Related information 

Windows 10 Pro
.NET Core SDK: 2.2.204
Visual Studio 2019: 16.0.4
fsi is from "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\FSharp\fsi.exe"
(I'm using whatever FSharp.Core comes bundled with fsi)

**Comment by debugnik** [comment]
Apparently, [the implementation of `.ToString()` got copied from the `Option` implementation](https://github.com/dotnet/fsharp/blob/858642d53cfe68c9f161ad651a364c118cea64d0/src/fsharp/FSharp.Core/prim-types.fs#L3112), which works on the premise that a non-null option can only be `Some`. This obviously throws when accessing the `Value` property on `ValueNone`.

[This `DebuggerDisplay` attribute](https://github.com/dotnet/fsharp/blob/858642d53cfe68c9f161ad651a364c118cea64d0/src/fsharp/FSharp.Core/prim-types.fs#L3092) requires attention too, as it relies on the same premise.

**Comment by ntwilson** [comment]
I suspect it might actually be due to the [anyToString](https://github.com/dotnet/fsharp/blob/858642d53cfe68c9f161ad651a364c118cea64d0/src/fsharp/FSharp.Core/prim-types.fs#L765) function.  Even with regular options I can do:
```
> None.ToString();;
System.NullReferenceException: Object reference not set to an instance of an object.
   at <StartupCode$FSI_0002>.$FSI_0002.main@()
Stopped due to error
> string None;;
val it : string = ""
```
So it has to do with the magic of the `string` function, and not the `.ToString()` method.
Indeed, I can see that:
```
> match box None with
- | null -> "it's null"
- | _ -> "it's not null";;
val it : string = "it's null"

> match box ValueNone with
- | null -> "it's null"
- | _ -> "it's not null";;
val it : string = "it's not null"
```
so `anyToString` isn't capturing the fact that ValueNone should be treated as null.  I don't know if that makes the difference when a list contains ValueNone though...

**Comment by debugnik** [comment]
The reason that's relevant for Option is that [`None` is actually null in disguise](https://github.com/dotnet/fsharp/blob/858642d53cfe68c9f161ad651a364c118cea64d0/src/fsharp/FSharp.Core/prim-types.fsi#L1801), so it gets handled like any other null reference.

That can't possibly apply to ValueOption, as it is a value type. In fact, the correct representation of `string ValueNone` should be "ValueNone" or similar, not anything related to null.

**Comment by ntwilson** [comment]
Oh I understand your point now, thanks for clarifying.

**Comment by cartermp** [comment]
Closing in favor of #7693, since I apparently missed this one and I'd like to consolidate
