### ISSUE TITLE
Feature request: command line switch to output compiler version and exit

### ISSUE THREAD

**Issue by VTJDailey** [dotnet/fsharp#6783]
Hello,

I'd like a command line switch to display the compiler version to add to certain scripts.

./fsc.exe --displayversion

I would expect this to behave similarly to './fsc.exe --help' except only output the first line.

I can supply a pull request for this if it would be accepted.

- is '--displayversion' the ideal text to use?  '--version' appears to already be in use as a deprecated option.  My next thought was '--display-version' but it looks like most other options just run the words together (with the exception of '--quotations-debug').  
- Should an identical switch be added to fsi.exe?  I personally would have no use for that but I don't see any reason not to have them synchronized.
- How does multiple languages work when submitting pull requests?  I see that the build autogenerates entries for every language with a 'state="new"' attribute.  Do I just leave it at that?
- What is the process for timing the update of related documentation such as https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/compiler-options

**Comment by cartermp** [comment]
Sorry for not getting back on this - I think a PR implementing this would be accepted. We could subsume the old `--version` and have it just do this. The same switch should be added to fsi,exe. We have infrastructure for translations; if you follow the process in `devguide.exe` it should be fine. Running a `build.cmd` before and after your changes should kick things off. Docs are updated separately, and can be done as a PR against the dotnet/docs repo.

**Comment by dsyme** [comment]
This was implemented in https://github.com/dotnet/fsharp/pull/10099
