### ISSUE TITLE
Move to VSSDK HyperLink and bold/italic support in QuickInfo

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#6797]
In the coming months, the VSSDK will have built-in support for what we do today with QuickInfo. Being able to offload the view stuff to the VSSDK would be a good long-term thing to do.

**Comment by dsyme** [comment]
>  In the coming months, the VSSDK will have built-in support for what we do today with QuickInfo. Being able to offload the view stuff to the VSSDK would be a good long-term thing to do.

@cartermp Please reopen with more info if you have it.  Otherwise it's hard to action this
