### ISSUE TITLE
build fails on missing dotnet core

### ISSUE THREAD

**Issue by forki** [dotnet/fsharp#6819]
I did a git clean -xdf and tried build.cmd on master

![image](https://user-images.githubusercontent.com/57396/58232249-5c7fd480-7d39-11e9-997b-d6836fda9bd7.png)

**Comment by forki** [comment]
@brettfo ideas?
`.dotnet` folder is there and contains the correct version, but even if I add that one explicitly to PATH - it does not fix it

**Comment by brettfo** [comment]
You need a machine-wide install of both the 3.0.100-preview5-011568 SDK as well as 2.1.503.

A possible local hack is to run `build.cmd -ci -binaryLog`.  The `-ci` flag will allow it to download 3.0 and 2.1 SDKs and the `-binaryLog` flag is just to make `-ci` happy.

**Comment by forki** [comment]
But it downloaded the 3.0 sdk and put it into the .dotnet subfolder. So it's already there. Why should I install it globally? Why doesn't it just pick it up from there?

**Comment by forki** [comment]
Also I wonder why the global.json does not set the sdk version.

**Comment by forki** [comment]
I installed 3.0.100-preview5-011568 SDK globally - it did not fix things.

**Comment by forki** [comment]
using CI build actually brings me a step further:

![image](https://user-images.githubusercontent.com/57396/58308624-5d306d80-7e02-11e9-9985-3ed33da5b73b.png)

**Comment by forki** [comment]
Nobody able to help?

**Comment by cartermp** [comment]
@forki I can't reproduce this on either my work box nor my laptop (parallels) once I have the .NET Core 3.0 SDK installed on my machine.

Though it's absolutely a regression that we need a machine-installed dependency here rather than whatever comes in the download script. @brettfo that seems to have been an Arcade dependency, is it possible to work around that somehow?

**Comment by forki** [comment]
@cartermp I have dotnet core 3.0 installed.

![image](https://user-images.githubusercontent.com/57396/58453980-4c8f3880-811d-11e9-87d9-1b3bd789f05e.png)

As written above the error is now around hostfxr.dll.  I googled this: https://stackoverflow.com/questions/50644730/failed-to-load-the-hostfxr-dll-after-install-net-core but it's only a fix for Win 7 (I'm on Win10)

**Comment by forki** [comment]
Ping

**Comment by realvictorprm** [comment]
@forki change the netcore 3 preview version in the file `global.json` in the root directory. That fixed the problem for me. I can make a PR which states that in the Developing.md if you guys want.

**Comment by realvictorprm** [comment]
@forki see this line in this file
https://github.com/dotnet/fsharp/blob/master/global.json#L3

**Comment by cartermp** [comment]
This doesn't appear to be an issue anymore; I haven't reproduced before.
