### ISSUE TITLE
F# compiler should set major version of Embedded PDB

### ISSUE THREAD

**Issue by eerhardt** [dotnet/fsharp#6832]
When using `DebugType=embedded` with F# projects, and then trying to load the resulting library with `PEReader`, I am getting an exception. This is because `PEReader` is validating that the version is at least the expected version:

https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEReader.EmbeddedPortablePdb.cs#L52-L70

**Repro steps**

Provide the steps required to reproduce the problem:

1. Set `<DebugType>embedded</DebugType>` in a .NET Standard .fsproj
2. Build
3. Pass the built `.dll` into the following code:

```C#
string filename = ...;
using (var fileStream = File.OpenRead(filename))
{
    PEReader reader = new PEReader(fileStream);

    foreach (var entry in reader.ReadDebugDirectory())
    {
        if (entry.Type == DebugDirectoryEntryType.EmbeddedPortablePdb)
        {
            reader.ReadEmbeddedPortablePdbDebugDirectoryData(entry);
        }
    }
}

```

**Expected behavior**

`PEReader` shouldn't throw on the assembly.

**Actual behavior**

```
System.BadImageFormatException
  HResult=0x8007000B
  Message=Unsupported format version: 0.0
  Source=System.Reflection.Metadata
  StackTrace:
   at System.Reflection.PortableExecutable.PEReader.ValidateEmbeddedPortablePdbVersion(DebugDirectoryEntry entry) in F:\workspace\_work\1\s\src\System.Reflection.Metadata\src\System\Reflection\PortableExecutable\PEReader.EmbeddedPortablePdb.cs:line 62
```

**Known workarounds**

Don't use embedded PDBs.

cc @KevinRansom @tmat

**Comment by KevinRansom** [comment]
@eerhardt,
This is a bug in the validation code.

the portable pdb specification says this about version: 
https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PE-COFF.md#embedded-portable-pdb-debug-directory-entry-type-17

Version Major=**### any**, Minor=0x0100 of the data format:
````
Declares that debugging information is embedded in the PE file at location specified by PointerToRawData.
Version Major=any, Minor=0x0100 of the data format:
````
@brettfo, @tmat
