### ISSUE TITLE
API Documentation link on the wiki home page points to a personal Medium site

### ISSUE THREAD

**Issue by amgaera** [dotnet/fsharp#6877]
Repro steps:
- open the [home page](https://github.com/dotnet/fsharp/wiki) of the project's wiki
- hover over the _API Documentation_ link and check its destination

Expected behavior:
- the _API Documentation_ link points to a page with API documentation

Actual behavior:
- the _API Documentation_ link points to a personal Medium site, https://shahmeeramir.com/

**Comment by cartermp** [comment]
Wow, our wiki can just be updated by anyone like that.

Thanks, I've reported the user for abuse and I'll revert the change. Actually I wonder if we should still have a wiki; most of the info in there is very oudated now.

**Comment by cartermp** [comment]
I've disabled the wiki, as all the important info it contained is captured in our README
