### ISSUE TITLE
Unexpected FS1178 with CustomComparison records

### ISSUE THREAD

**Issue by Happypig375** [dotnet/fsharp#6909]
An unexpected FS1178 occurs when using a record with custom comparison.
Warning level 5 is used.

**Repro steps**

```fs
namespace global

[<CustomComparison; CustomEquality>]
type CustomEquatable = { thingy:unit }
    with override __.Equals _ = failwith "..."
         override __.GetHashCode() = failwith "..."
         interface System.IComparable<CustomEquatable> with
            override __.CompareTo _ = failwith "..."

type Warning = { Available:CustomEquatable }
```
`Warning	FS1178	The struct, record or union type 'Warning' is not structurally comparable because the type 'CustomEquatable' does not satisfy the 'comparison' constraint. Consider adding the 'NoComparison' attribute to the type 'Warning' to clarify that the type is not comparable`

[FS1178.zip](https://github.com/dotnet/fsharp/files/3240931/FS1178.zip)

**Expected behavior**

No warning.

**Actual behavior**

![image](https://user-images.githubusercontent.com/19922066/58700353-5beadc00-83d2-11e9-9125-af839dce0134.png)

**Known workarounds**

Use StructuralComparison instead.

<details>
<summary>Related Information</summary>
Microsoft Visual Studio Community 2017 
Version 15.9.12
VisualStudio.15.Release/15.9.12+28307.665
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA735
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.14.20131.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.61435.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Dotfuscator Community Edition   5.36.0.7050-e77ce80a6
PreEmptive Protection - Dotfuscator CE

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub.VisualStudio   2.9.1.7781
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Mono Debugging for Visual Studio   4.13.12-pre (9bc9548)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61903.01040
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

TypeScript Tools   15.9.30410.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Unity   3.9.0.3
Visual Studio Tools for Unity

Visual Studio Tools for Universal Windows Apps   15.0.28307.665
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.12.3.83 (d15-9@23fa80172)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.30 (e0af99a34)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.7.0 (HEAD/ba9da7a76)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.4.0.64 (9c8d8e0)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
</details>

**Comment by cartermp** [comment]
This is by design at warning level 5; using the default or manually setting the warning level back will no longer emit this.

https://github.com/dotnet/fsharp/blob/4a695e798a05c8139c3cba89a7d971055bdd3160/src/fsharp/CompileOps.fs#L376-L392

**Comment by Happypig375** [comment]
A CustomComparison record, is by definition, comparable. Therefore, the warning is wrong. Please improve when the warning is emitted to give more uses for the warning level 5.

**Comment by cartermp** [comment]
Note that this is about being _structurally_ comparable (or structurally equatable). By specifying `CustomComparison` and/or `CustomEquality` you're now opting out of a property that F# types and structs hold.

As with other level 5 warnings, this is not inherently bad (e.g., the compiler making a defensive copy). But it is a violation of a property of these types that is generally assumed to hold. If you have no desire for that property to hold, then recommendation is to explicitly NoWarn this error code in a project file or `Directory.build.props` file.
