### ISSUE TITLE
Integer Conversions have no consistency.

### ISSUE THREAD

**Issue by sayurin** [dotnet/fsharp#6914]
At src/fsharp/FSharp.Core/prim-types.fs, following integer conversions have no consistency.

- [`uint32` and `int32`](https://github.com/dotnet/fsharp/blob/4702abbf7c452671f2fd52c927aae6a4c6c9db7c/src/fsharp/FSharp.Core/prim-types.fs#L3812-L3859)
  - int32 to uint32: no-op.
  - uint32 to uint32: `conv.u4` (should be no-op?)
  - int32 to int32: no-op.
  - uint32 to int32: no-op.
- [`uint64` and `int64`](https://github.com/dotnet/fsharp/blob/4702abbf7c452671f2fd52c927aae6a4c6c9db7c/src/fsharp/FSharp.Core/prim-types.fs#L3882-L3929)
  - int64 to uint64: no-op.
  - uint64 to uint64: no-op.
  - int64 to int64: `conv.i8` (should be no-op?) 
  - uint64 to int64: no-op.
- [`unativeint` and `nativeint`](https://github.com/dotnet/fsharp/blob/4702abbf7c452671f2fd52c927aae6a4c6c9db7c/src/fsharp/FSharp.Core/prim-types.fs#L3996-L4044)
  - nativeint to unativeint: no-op.
  - unativeint to unativeint: no-op.
  - nativeint to nativeint: `conv.i` (should be no-op?)
  - unativeint to nativeint: no-op.
- [`unativeint` and `nativeint`](https://github.com/dotnet/fsharp/blob/4702abbf7c452671f2fd52c927aae6a4c6c9db7c/src/fsharp/FSharp.Core/prim-types.fs#L3996-L4044)
  - sbyte to unativeint: `conv.i`
  - byte to unativeint: `conv.u`
  - sbyte to nativeint: `conv.i`
  - byte to nativeint: `conv.i` (should be `conv.u`?)

**Comment by cartermp** [comment]
I agree that it looks inconsistent in the code. @dsyme probably wrote it all, so he'd know more 🙂 

I wonder if making any change here is a breaking change.

**Comment by dsyme** [comment]
All three could be changed to noop, none should have an observable effect.

The last could also be changed, and it also won't have an observable effect.

**Comment by cartermp** [comment]
@sayurin We'll happily accept a PR that addresses this.

**Comment by dsyme** [comment]
I'll close as it's not an actual proble, and the PR https://github.com/dotnet/fsharp/issues/6914 eventually failed some tests
