### ISSUE TITLE
Can I delete this code?

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#6921]
@KevinRansom @dsyme 

https://github.com/dotnet/fsharp/blob/9b1287c90c61328c399ff14bb55b243185b286ad/src/fsharp/SimulatedMSBuildReferenceResolver.fs#L187-L199

This is only applicable for people using MSBuild v12 (VS 2012), probably only works on Windows at this point, modern VS doesn't even install this anymore, and offers _at best_ some slightly better error diagnostics for directives in scripts.

**Comment by KevinRansom** [comment]
@cartermp, probably not.

RESHAPED REBUILD is still a thing on coreclr at the moment.   I got rid of reshaped reflection a few weeks ago, and I will do the same for reshaped msbuild before long.

**Comment by cartermp** [comment]
But how does that relate to the SimulatedMSBuildReferenceResolver? I'm not asking to get rid of all of RESHAPED_MSBUILD, just this code that probably doesn't work

**Comment by dsyme** [comment]
Yes this code can go, it is ancient and I agree it will fail
