### ISSUE TITLE
Auto-indent where appropriate

### ISSUE THREAD

**Issue by Happypig375** [dotnet/fsharp#6962]
**Is your feature request related to a problem? Please describe.**
The cursor should indent after creating a new function, a pattern match, etc.
```fs
let f x = | //<-- cursor
```
(Enter)
```fs
let f x =
| //<-- cursor
```
--------------------------
```fs
let f x =
    match x with
    | 1 ->| //<-- cursor
```
(Enter)
```fs
let f x =
    match x with
    | 1 ->
    | //<-- cursor
```
**Describe the solution you'd like**
```fs
let f x = | //<-- cursor
```
(Enter)
```fs
let f x =
    | //<-- cursor
```
-------------------------
```fs
let f x =
    match x with
    | 1 ->| //<-- cursor
```
(Enter)
```fs
let f x =
    match x with
    | 1 ->
        | //<-- cursor
```
**Describe alternatives you've considered**
Doing nothing. Extra tab keys / space keys need to be hit.

**Comment by cartermp** [comment]
This is already implemented, but you need to set your tab setting to "Smart":
![image](https://user-images.githubusercontent.com/6309070/59147708-158e1200-89bc-11e9-8c52-64ab88644db3.png)
