### ISSUE TITLE
Indent when hitting enter inside a function

### ISSUE THREAD

**Issue by Happypig375** [dotnet/fsharp#6963]
**Is your feature request related to a problem? Please describe.**
The cursor should auto-indent when enter is hit inside a function.
```fs
    let f x = printf "Hello "| //<--cursor
              printf "World"
```
(Enter)
```fs
    let f x = printf "Hello "
    | //<--cursor
              printf "World"
```
**Describe the solution you'd like**
```fs
    let f x = printf "Hello "| //<--cursor
              printf "World"
```
(Enter)
```fs
    let f x = printf "Hello "
              | //<--cursor
              printf "World"
```

**Describe alternatives you've considered**
Doing nothing. The developer will need to use his/her own eyesight and hit some combination of tabs and spaces.

**Comment by saul** [comment]
I know this isn't a solution, but the following is automatically indented correctly:

```f#
let f x =| //<-- cursor
    printf World"
```

(Enter)

```f#
let f x =
    | //<-- cursor
    printf World"
```

Personally I'd argue that this style of indentation is far easier to read as it results in predictable indentation when you have multiple levels of nesting. That's just my opinion though.

**Comment by Happypig375** [comment]
I commonly use these for 2-to-3-liners. A new line for the first line of code inside a function works well for longer functions, but for 2-to-3-liners it's unnecessary space wasted.

**Comment by dsyme** [comment]
I'm going to close this - the code is too non-idiomatic to make this a case we should consider, and the idiomatic case works
