### ISSUE TITLE
fsi --readline weird backspace drawing

### ISSUE THREAD

**Issue by johannes-climacus** [dotnet/fsharp#6969]
When running fsi with readline flag, backspace / delete jumps from the prompt to cursor.

Provide the steps required to reproduce the problem:

1. `$ dotnet fsi --readline`
2. enter text
3. attempt to delete / backspace
4. enjoy the trip

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

**Expected behavior**

Backspace through text normally

**Actual behavior**

Psychedelic cursor jumping

**Known workarounds**

None

**Related information**

video: https://asciinema.org/a/Htd0ETKUwfvx63XBb2YRgxcv9

This does not occur unless using `--readline`

* macOS Mojave 10.14.5
* tested under Terminal.app, iTerm2, and kitty

**Comment by cartermp** [comment]
Thanks, I noticed this myself but never bothered to file the issue. We should get this resolved for .NET Core 3.0.

cc @KevinRansom

**Comment by Heimdell** [comment]
Observing the same behaviour on linux.

**Comment by cartermp** [comment]
This no longer reproduces for me either on WSL (ubuntu LTS) or macOS with the latest .NET Core SDK.

**Comment by cartermp** [comment]
This used to be a problem a while ago, but I don't see it anymore.

Furthermore, it used to be the case that `--readline` was needed because the cursor wouldn't move with arrow keys. That's not the case anymore either.
