### ISSUE TITLE
VS: Remove use of Roslyn ProjectExternalErrorReporter.ctor(ProjectId, string, IServiceProvider)	

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/fsharp#6981]
Roslyn removed then added back the constructor in https://github.com/dotnet/roslyn/pull/36328. Possibly the use of the constructor will be removed when switching to the ExternalAccess assembly.

**Comment by dsyme** [comment]
@JoeRobich @cartermp Could we have more context here please?  Is this part of some larger work with a larger useful goal that can be summarised please?

**Comment by JoeRobich** [comment]
@dsyme We are wanting to transition this bit of code (https://github.com/dotnet/fsharp/blob/516d7f91fdb09cd48706fd5c3f894da599a8121c/vsintegration/src/FSharp.LanguageService/ProjectSitesAndFiles.fs#L177) to use a different constructor (https://github.com/dotnet/roslyn/blob/fdd40b21d59c13e8fa6c718c7aaf9d50634da754/src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs#L43) so that we can remove the one that is currently being used.


```csharp
public ProjectExternalErrorReporter(ProjectId projectId, string errorCodePrefix, string language, VisualStudioWorkspaceImpl workspace)
```

**Comment by dsyme** [comment]
What should be provided for "language"?

**Comment by dsyme** [comment]
@JoeRobich I guess this is the fix you want: https://github.com/dotnet/fsharp/pull/12954

**Comment by KevinRansom** [comment]
The date of the ask is particularly humerous.  We are now on the external access assembly.
