### ISSUE TITLE
Seq.mapFold isn’t evaluated while iterating over the sequence

### ISSUE THREAD

**Issue by AdhemarVandamme** [dotnet/fsharp#7009]
`Seq.mapFold` isn’t evaluated while iterating over the sequence.

The input sequence is eagerly evaluated instead.

**Example — Repro steps**

Consider a sequence generated with side effects

```fsharp
let onetwothree =
    seq {
        for i = 1 to 3 do
            // Thread.Sleep 1000
            printf "%d" i
            yield i
    }
```

and a `folder` and `mapFolder` function, also with side effects

```fsharp
let folder s j =
    printf "%c" (char (int '@' + j))
    s + j

let mapFolder s j =
    printf "%c" (char (int '@' + j))
    char (int '`' + j), s + j
```

When you `fold` or `scan`, the folder is executed while iterating over the sequence.

The output of

```fsharp
printf "Seq.fold:    side effects: "
printfn " - result: %A" (Seq.fold folder 0 onetwothree)

printf "Seq.scan:    side effects: "
printfn " - result: %A" (Seq.scan folder 0 onetwothree)

printf "Seq.mapFold: side effects: "
printfn " - result: %A" (Seq.mapFold mapFolder 0 onetwothree)
```

is — for the first two lines

    Seq.fold:    side effects: 1A2B3C - result: 6
    Seq.scan:    side effects: 1A2B3C - result: seq [0; 1; 3; 6]

as expected

**Expected behavior**

so I would expect the third line of the output to be

    Seq.mapFold: side effects: 1A2B3C - result: (seq ['a'; 'b'; 'c'], 6)

since the point of using `seq`s is to evaluate as much as possible the results of the folding and mapping while iterating over the sequence.

**Actual behavior**

But the third line of the output is actually

    Seq.mapFold: side effects: 123ABC - result: (seq ['a'; 'b'; 'c'], 6)

with the side effects of the eager evaluation of the input sequence (`123`) entirely printed before the side effects of the evaluation of the `mapFolder` (`ABC`).

**Current implementation**

The current implementation is (from <https://github.com/fsharp/fsharp/blob/master/src/fsharp/FSharp.Core/seq.fs#L1438>):

```fsharp
[<CompiledName("MapFold")>]
let mapFold<'T,'State,'Result> (mapping: 'State -> 'T -> 'Result * 'State) state source =
    checkNonNull "source" source
    let arr,state = source |> toArray |> Array.mapFold mapping state
    readonly arr, state
```

You can see that the source sequence is first kept in memory in an `array` before it is iterated, which to me defeats the point of using `seq`s.
Also, if the sequence consists of big objects, but the mapping and the folding are light-weight, keeping the whole input sequence in an `array` could needlessly consume a lot of memory.

**Proposed implementation**

I would implement this rather along the lines of:

```fsharp
type MappedOrFolded<'U, 'State> =
    | Mapped of 'U
    | Folded of 'State

let mappedOrFoldeds mapping state source =
    let optionalFirst mapFolder (_, s) e =
        let mappedElementAndNextStatePair = mapFolder s e
        Some (fst mappedElementAndNextStatePair), snd mappedElementAndNextStatePair
    let pairWithFirstNone initialState =
        None, initialState
    let scannedToMappedOrFoldeds scanned =
        // Returns a sequence with as many MappedOrFolded.Mappeds containing mapped elements as there are source elements,
        // followed by a single MappedOrFolded.Folded containing the final state
        seq {
            let mutable lastState = None
            // lastState will not remain None, since the output of Seq.scan starts with initial state, hence is never empty
            for v, s in scanned do
                match v with
                    | None ->
                        () // Initial state is not paired with a mapped element
                    | Some u ->
                        yield Mapped u
                lastState <- Some s
            yield Folded (Option.get lastState)
        }
    scannedToMappedOrFoldeds (Seq.scan (optionalFirst mapping) (pairWithFirstNone state) source)

let mapFold mapping state source =
    // Returns a pair consisting of firstly a sequence with the mapped elements, and secondly the final state
    let mapFoldTransform mofs =
        let alwaysFalse _ =
            false
        let mutable lastState = None
        // lastState will not remain None, since the output of Seq.scan starts with initial state, hence is never empty
        let mapped = 
            seq {
                for mof in mofs do
                    match mof with
                        | Mapped u ->
                            yield u
                        | Folded s ->
                            lastState <- Some s
            }
        let cached = Seq.cache mapped
        ignore (Seq.tryFind alwaysFalse cached) // Iterates over cached, and thus over mapped, until it its end
                                                // so that the last (Folded) element is reached, and the side effect is executed
        // The 2 preceeding code lines (as well as the alwaysFalse function definition) can be replaced by: let cached = Seq.ofArray (Array.ofSeq mapped)
        // or (in seq.fs) by: let cached = readonly (Array.ofSeq mapped)
        cached, Option.get lastState
    mapFoldTransform (mappedOrFoldeds mapping state source)
```

**Comment by cartermp** [comment]
Note the remark:

`This function digests the whole initial sequence as soon as it is called. As a result this function should not be used with large or infinite sequences.`

Your suggestion would likely have a higher CPU and memory cost due to constructing three additional sequences. The current implementation is far more optimized by turning it into an array and scanning over that once.

So the question comes down to: should this function preserve the order of effectful code when called?

**Comment by AdhemarVandamme** [comment]
You’re right: the actual behavior is documented in the remarks in [seq.fsi](https://github.com/fsharp/fsharp/blob/master/src/fsharp/FSharp.Core/seq.fsi). It still feels like a mistake, but it _is_ documented.

I missed that.

**Comment by dsyme** [comment]
> @cartermp You’re right: the actual behavior is documented in the remarks in seq.fsi. It still feels like a mistake, but it is documented.

Yes, it is a design mistake.  I'm not sure we should change it now though.

**Comment by cartermp** [comment]
I'm leaning towards not doing this (hence the close).

I think we'd be more than happy to accept a PR that improves the performance of `Seq.mapFold`, but preserving the execution order of effectful code means that we're forever locked with that decision. If we have to go back, we're likely to have people depend on that behavior.

Additionally, it's technically a breaking change to move to make this function preserve that order, though I believe very few (if any) people depend on the fact that it does _not_ preserve order.
