### ISSUE TITLE
Latest master crashes hive in dogfood 16.2

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#7020]
**Requires latest 16.2 dogfood build**

1. Clone master
2. Build
3. set VisualFSharpFull as startup
4. ctrl+f5
5. Open an F# project

Observe that VS will crash.

**Comment by TIHan** [comment]
16.2 preview 4 has changes made in Roslyn that removes IVTs to FSharp.Editor. Our master branch still relies on those IVTs, which is the reason why it crashes. This should be fixed when release/16.2 flows back into master once 16.2 is released.
