### ISSUE TITLE
Parse error? Using `async` as a function name gives poor error and parses incorrectly

### ISSUE THREAD

**Issue by adz** [dotnet/fsharp#7058]
I was writing a small stubbing module for testing -- just wanted to return unit for various args/workflows. When calling the function `async` the compiler appeared to parse incorrectly, and gave an unexpected error.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Step A

Compile a file with this content:

```
module Stub =
    let async _ = async { return "any kind of async" }
    let subsequent = async.Return ()
```
or
```
module Stub =
    let async _ = async.Return ()
    let subsequent = async.Return ()
```

2. Step B

Compile:

Test.fs(7,28): error FS0039: The field, constructor or member 'Return' is not defined. 

(the error is referencing the `Return` in the subsequent let)

**Expected behavior**

The code compiles successfully, or an error is given about using `async` is not allowed as a let binding.

**Actual behavior**

The compiler seems to interpret `async` as a valid function name in the module. However, the indent of the subsequent let seems to be scoped to the previous let binding.

**Known workarounds**

A) Don't make a function called `async`.

B) Indent incorrectly to match compiler parse failure

```
module Stub =
    let async _ = async { return "any kind of async" }
   let subsequent = async.Return () // this is de-indented
```

**Related information**

Provide any related information (optional):

* Operating system
* .NET Core 2.2.203
* Linux

**Comment by cartermp** [comment]
This is intended behavior. You can name things in your own code (provided they're not a reserved word) and the compiler will bind to that name. It's a backwards-compatibility thing: if we introduce a future library routine that has the same name as something in user code, we cannot override someone's user code, otherwise it's a source breaking change.
