### ISSUE TITLE
fsharpqa test suite is not reporting error details

### ISSUE THREAD

**Issue by forki** [dotnet/fsharp#7066]
If a fsharpqa test (Perl test suite) runs into an error then CI doesn't show details anymore.
This makes it extremely hard to understand what's going on.

Example from https://github.com/dotnet/fsharp/pull/6820:
![error](https://user-images.githubusercontent.com/57396/60101763-a440b400-975c-11e9-9b5f-b7ce33b6f3f5.png)

**Comment by cartermp** [comment]
@TIHan @dsyme Can either of you look into this?

**Comment by cartermp** [comment]
Closing as we are migrating these tests to be normal xUnit tests. In the meantime, the logs are available in CI in the artifacts.

**Comment by abelbraaksma** [comment]
In addition to that, since it's not trivial to find these logs, I've added a little video in the test guide to help locate them.
