### ISSUE TITLE
FSI doesn't work in OSX with XPlot.Plotly

### ISSUE THREAD

**Issue by leolorenzoluis** [dotnet/fsharp#7074]
FSI throws an exception when running an FSX script with Plotly.

**Repro steps**

Provide the steps required to reproduce the problem:

```

// #r "packages/XPlot.Plotly/lib/netstandard2.0/XPlot.Plotly.dll"
open XPlot.Plotly


let layout = Layout(title = "Basic Bar Chart")

let data = ["giraffes", 20; "orangutans", 14; "monkeys", 23]

data
|> Chart.Bar
|> Chart.WithLayout layout
|> Chart.WithHeight 500
|> Chart.WithWidth 700
|> Chart.Show
```

**Expected behavior**

Opens up the chart

**Actual behavior**

```
> 
- data
- |> Chart.Bar
- |> Chart.WithLayout layout
- |> Chart.WithHeight 500
- |> Chart.WithWidth 700
- |> Chart.Show
- ;;
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.

File name: 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at XPlot.Plotly.PlotlyChart.GetInlineHtml()
   at XPlot.Plotly.PlotlyChart.GetHtml()
   at XPlot.Plotly.PlotlyChart.Show()
   at <StartupCode$FSI_0022>.$FSI_0022.main@()


Stopped due to error
> 
```

**Known workarounds**

Run in dotnet CLI

**Related information**

Provide any related information (optional):

* Operating system - OSX
* .NET Runtime kind (.NET Core, .NET Framework, Mono) - .NET CORE 2.2.300
* Editing Tools (e.g. Visual Studio Version, Visual Studio) - VS CODE

**Comment by thinkbeforecoding** [comment]
On a windows machine, when I test with the code as is, at the point where you get an error, it's working and FSI is writting:
`Binding session to 'C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\bin\plugins\Diagnostics\Newtonsoft.Json.dll'`...

So it seems XPlot.Plotly is loading it from PATH or something like that which will fail for machines where it's not present.

I added the following at the begining of the file, to add the path for resolution: 
#I "packages/Newtonsoft.Json/lib/netstandard2.0"

Now, it's resolving from specified location:
Binding session to 'c:\Development\Tests\plotly\packages/Newtonsoft.Json/lib/netstandard2.0\Newtonsoft.Json.dll'...

I think it should probably solve your problem.

**Comment by leolorenzoluis** [comment]
Same error even if I tried to do #I for Newton. I'm on OSX.

**Comment by cartermp** [comment]
@KevinRansom  FYI

**Comment by s991116** [comment]
A workaround that seems to work for me was installing Mono MDK.
After installing Mono MDK 5.18.1 (https://www.mono-project.com/download/stable/#download-mac) it seems to work.
