### ISSUE TITLE
Intellisense tooltip for local functions should show argument names

### ISSUE THREAD

**Issue by Happypig375** [dotnet/fsharp#7080]
**Is your feature request related to a problem? Please describe.**
A function defined globally has its argument names shown in Intellisense tooltip, but not for functions in functions.

![image](https://user-images.githubusercontent.com/19922066/60379524-c42aed00-9a66-11e9-862c-dfeb6abb5baf.png)
![image](https://user-images.githubusercontent.com/19922066/60379533-005e4d80-9a67-11e9-957e-67b6701606e1.png)

**Describe the solution you'd like**
Argument names should appear for functions in functions.

**Describe alternatives you've considered**
Nah

**Additional context**
Nope

**Comment by psfinaki** [comment]
Reopening to keep the track of the other case we still need to work on:
```
do
    let func x = ()
    ()
```

**Comment by vzarytovskii** [comment]
> Reopening to keep the track of the other case we still need to work on:
> ```
> do
>     let func x = ()
>     ()
> ```
> 

If it fixes the case described in the original issue, we probably should close it and open a separate one for the  one in 'do'. If not, let's leave it open.
