### ISSUE TITLE
Restore.cmd Bug

### ISSUE THREAD

**Issue by jdm7dv** [dotnet/fsharp#7090]
![fsharp_issue](https://user-images.githubusercontent.com/8218836/60461409-70f69d00-9c14-11e9-9786-d7482cc68a8f.png)
I'm getting "(NETCORE_ENGINEERING_TELEMETRY=InitializeToolset) Exception calling ".ctor" with "1" argument(s): "Input string was not in a correct format."

Get the same error with 'Build.cmd' too and .NET Core 2.x

1. Powershell on PATH 
2. from a Visual Studio 2017 CMD Prompt run 'Restore.cmd'

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

**Expected behavior**
 Restore complete 

Provide a description of the expected behavior.

**Actual behavior**
"(NETCORE_ENGINEERING_TELEMETRY=InitializeToolset) Exception calling ".ctor" with "1" argument(s): "Input string was not in a correct format."

**Known workarounds**
 None
Provide a description of any known workarounds.

**Related information**

Provide any related information (optional):

* Operating system 
Windows 10 2019 LTSC Enterprise
* .NET Runtime kind (.NET Core, .NET Framework, Mono)
.Net 4.7.2 .NET Core 2.x

* Editing Tools (e.g. Visual Studio Version, Visual Studio)
Visual Studio 2017 Community

**Comment by cartermp** [comment]
@jdm7dv Can you try the following:

* Install .NET Core 3.0 preview
* Install VS 2019

Development (via VS) on this repo is not supported with VS 2017.

**Comment by KevinRansom** [comment]
Closing, we require VS 2019 for this repo.
