### ISSUE TITLE
Reenable flakey test  ``RaceBetweenCancellationAndError.Parallel``() =

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#7112]
Merges into fsharp47 have been failing because of this test:
    member this.``RaceBetweenCancellationAndError.Parallel``() =

Disabling the test for now in order to make progress:

**Comment by cartermp** [comment]
What's the significant of the `:`?

**Comment by KevinRansom** [comment]
It's a list with one entry … or poor grammer you choose.

**Comment by KevinRansom** [comment]
grammar

**Comment by cartermp** [comment]
Unless I am mistaken, this test is not disabled: https://github.com/dotnet/fsharp/blob/main/tests/FSharp.Core.UnitTests/FSharp.Core/Microsoft.FSharp.Control/AsyncModule.fs#L665
