### ISSUE TITLE
Assess use of layered TcImports 

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#7212]
The compiler has a key data structure called "TcImports".  This is split between a "base" TcImports for "framework references" and a "derived" TcImports for "non-framework references". The single TcGlobals is stored in the base TcImports.  The ImportMap is, IIRC, in the derived. 

This split and layering was done a loooong time ago in an attempt to share resources common between multiple projects. 

* It is really unclear if this split is remotely worth the considerable complexity it brings.  
* We've no actual data to confirm if this is saving us memory
* If you came along today and told me "let's add this split" to the codebase I'd be really skeptical, and want good evidence that it was worth it
* It's unclear, in the days of NET Standard and .NET Core, if the base TcImports **ever** gets actually shared between multiple incremental project builders
* The split prevents us from simplifying the codebase in key ways.  For example, it would be great if "ImportMap" was actually just in "TcGlobals" - it may as well be really.  But this can't be the case today because the TcGlobals might in theory be shared between multiple projects.

My gut intuition is that we should remove this split and just have one TcGlobals and one (unlayered) TcImports per project builder, and no "framework TcImports cache" at all.

@TIHan If I made a draft PR to remove this split do you think you would you be able to perf test it w.r.t memory usage?

**Comment by TIHan** [comment]
Yes, I can do a test.

I think this sounds reasonable. We have the FrameworkTcImportsCache to handle this sharing for us, but it turns out there can be many different combinations with dlls for netstandard and netcore that make this not worth it most likely, but not 100% sure. That's only based on what I have seen when I was debugging it.

TcGlobals being shared would be interesting, but what we really want shared are the Entities and Vals. For example: we should never have more than one (specific TFM) System.Object Entity in memory; or no more than one Newtonsoft Json 9.0.1 (JObject) Entity in memory.

I understand the `base` part of TcImports was a way to sort of compose TcImports together so we could share information.

But in regards to getting rid of the split, yes the complexity will go down. In fact, in my compilation model, I opted to just pass all references (including non-framework dlls) to the call `BuildFrameworkTcImports` for every compilation. 

The TcImports base was a way to compose

**Comment by dsyme** [comment]
> I think this sounds reasonable. We have the FrameworkTcImportsCache to handle this sharing for us, but it turns out there can be many different combinations with dlls for netstandard and netcore that make this not worth it most likely, but not 100% sure. That's only based on what I have seen when I was debugging it.

That's right.

> TcGlobals being shared would be interesting, but what we really want shared are the Entities and Vals. 

The split TcImports shares one TcGlobals **and** all associated Val and Entity nodes and their children between all projects with the exactly the same set of "framework DLL references"

> For example: we should never have more than one (specific TFM) System.Object Entity in memory; or no more than one Newtonsoft Json 9.0.1 (JObject) Entity in memory.

Yes, though this proposal would actually go the other way and eliminate the only means we currently have for getting this kind of sharing.

The above is also very hard to achieve because cross-assembly references are done by direct pointers.  If one project references a A.DLL and B.DLL (cross-referencing each other) and another project references only A.DLL then we can't share the A.DLL resources as the second project wouldn't give accurate errors when "B.DLL" things are used form that project.

**Comment by TIHan** [comment]
> The split TcImports shares one TcGlobals and all associated Val and Entity nodes and their children between all projects with the exactly the same set of "framework DLL references"

Oh that's right. If that's the case, then having a `langVersion: LanguageVersion` on `TcGlobals` means if Project A references Project B, but Project B uses 4.6 and A uses 4.7, it's possible they will both be either 4.6 or 4.7 which is wrong. This would only happen for tooling in type checking. This is now a bug for us. I'll report it.

> Yes, though this proposal would actually go the other way and eliminate the only means we currently have for getting this kind of sharing.
That's fine that we would go the other way if it doesn't make a significant memory increase and it reduces complexity. We can figure out the sharing of Entities and ValRefs later; I have some ideas on it, such as a `RetargetedModuleOrNamespaceType`.

You should definitely get a draft PR soon so we can get rid of the langversion bug.

**Comment by KevinRansom** [comment]
@dsyme, as @tihan just pointed out language version is busted because of this split.  So can we go ahead and make the change?  Or should I look at plumbing language version on something else?

**Comment by dsyme** [comment]
> @dsyme, as @TIHan just pointed out language version is busted because of this split. So can we go ahead and make the change? Or should I look at plumbing language version on something else?

I'm ok with trialling the split but we need to have some methodology in place to assess memory usage.

(If we found memory usage exploded for lots of projects sharing the same Framework Imports then we could easily fix the lang version thing by keying the FrameworksImport cache on that).

**Comment by cartermp** [comment]
@TIHan Has a good framework by which to measure memory usage. This isn't necessarily automatable, though. Just need to put our stress solution under PerfView after changes and assess.

**Comment by dsyme** [comment]
Closing out this old issue
