### ISSUE TITLE
Question: preferred way to add an error number

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#7238]
I'd like to make `FunctionValueUnexpected` warning have a separate error number so it could be recognised by tooling using FCS.

There're different places where these numbers are specified and there're cases where a single number is used for multiple errors (e.g. `20`) or an error not having it's own number, currently returning a magic number `193`.
https://github.com/dotnet/fsharp/blob/master/src/fsharp/FSComp.txt
https://github.com/dotnet/fsharp/blob/master/src/fsharp/CompileOps.fs#L240

How a number should be chosen for existing errors? Is there any way to ensure using a particular number is safe?

**Comment by cartermp** [comment]
@dsyme would be best to answer this.

**Comment by dsyme** [comment]
Those error codes in CompileOps date from old code. The current approach is to just add new numbers at the end of FSComp.txt, and never try to use any intermediate numbers

**Comment by auduchinok** [comment]
@dsyme Thank you. It seems to work fine in #7246.
