### ISSUE TITLE
Unexpected downgrade using TargetFramework < net470 on .net core 3.0 preview6

### ISSUE THREAD

**Issue by hsorbo** [dotnet/fsharp#7265]
**Repro steps**
create a project `foo.fsproj` with content
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Reactive" Version="4.1.5" />
  </ItemGroup>
</Project>
```

then run `dotnet restore foo.fsproj`

**Expected behavior**
No warnings

**Actual behavior**
```
/[REDACTED]/foo.fsproj : warning NU1605: Detected package downgrade: System.ValueTuple from 4.5.0 to 4.4.0. Reference the package directly from the project to select a different version. 
/[REDACTED]/foo.fsproj : warning NU1605:  foo -> System.Reactive 4.1.5 -> System.ValueTuple (>= 4.5.0) 
/[REDACTED]/foo.fsproj : warning NU1605:  foo -> System.ValueTuple (>= 4.4.0)
```

**Known workarounds**
Upgrade to net470 (which i believe bundles valuetuple)

**Related information**
Tried explicitly referencing downgraded package without luck.
dotnet tools `3.0.100-preview6-012264` on both Mac and Windows
Works just fine if you rename file  to `.csproj`

Here is a simple terminal-workflow showing the problem
<img width="657" alt="Screenshot 2019-07-22 at 16 00 56" src="https://user-images.githubusercontent.com/1906744/61639474-d847c000-ac9b-11e9-864e-142658216ce3.png">

**Comment by cartermp** [comment]
This is expected because F# on .NET Framework < net47 references version 4.4.0. https://github.com/dotnet/fsharp/pull/7158 attempts to rectify this, but it's a bit tricky. We'd be happy to accept a contribution to that PR to move it forward.
