### ISSUE TITLE
Cannot reference static fields in static classes when opening that static class

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#7274]
See the following F#:

![image](https://user-images.githubusercontent.com/6309070/61823308-693fa800-ae10-11e9-9c30-636d5d9810ed.png)

The equivalent C# works:

![image](https://user-images.githubusercontent.com/6309070/61823250-444b3500-ae10-11e9-8bea-dbe95ed75c09.png)

`PI` is defined as follows:

```csharp
public const double PI = ...
```

https://referencesource.microsoft.com/#mscorlib/system/math.cs,37

F# sees this as a field, and requires qualification:

![image](https://user-images.githubusercontent.com/6309070/61823395-9c823700-ae10-11e9-9f0b-7a621e697fc6.png)

This should arguably not be required.

**Comment by cartermp** [comment]
Another example: `ColumnSize` from the `DbMetaDataColumnNames` static class

**Comment by dsyme** [comment]
My understanding is that this has definitely been fixed 

@TIHan can you double-confirm?

```
C:\GitHub\dsyme\fsharp-core-docs>..\fsharp\artifacts\bin\fsi\Debug\net472\fsi.exe --langversion:preview

Microsoft (R) F# Interactive version 11.0.0.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> open type System.Math;;
> PI;;
val it : float = 3.141592654

>
```

**Comment by cartermp** [comment]
This is fixed now
