### ISSUE TITLE
F# IDE integration classification not working on 16.3 preview 2 master branch, latest bits.

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#7290]
F# IDE integration classification not working on 16.3 preview 2 master branch, latest bits.
![image](https://user-images.githubusercontent.com/5175830/62073309-50ab0580-b1f5-11e9-99bc-ddee3affbc0f.png)

**Comment by cartermp** [comment]
Doesn't repro on 29130.203 (today's build).

![image](https://user-images.githubusercontent.com/6309070/62235450-db207000-b381-11e9-80bc-58f1274d067f.png)
