### ISSUE TITLE
Set.maxElement and Set.minElement should return 'T option instead of raising with empty Set

### ISSUE THREAD

**Issue by Ciantic** [dotnet/fsharp#7354]
**Is your feature request related to a problem? Please describe.**
I think the standard library should embrace the Option when possible.

```
> Set.maxElement Set.empty<int>;;
System.ArgumentException: Set contains no elements.
```

**Describe the solution you'd like**
Instead of throwing ArgumentException Set.maxElement and Set.minElement should return `'T option` instead of raising exception.

I think the backwards compatibility may be a problem. But in my opinion type change in this case is worth the trouble.

I guess there also could be tryMinElement and tryMaxElement. 

However I think that these "try" versions are wrong way in whole FSharp library. To me it's *more* important to know if the function may throw. Right now you can't know from the function name if it can raise an exception. 

E.g. List.exactlyOnce may raise, and List.tryExactlyOnce does not raise. It should be in reverse, like in Swift if you call a function that may throw you must type `try` in front.

**Comment by cartermp** [comment]
Unfortunately this would be a breaking change, so we won't take this. A `try` variant of the two functions that gives an option is worth it. Please file a language suggestion here if that's of interest to you: https://github.com/fsharp/fslang-suggestions/
