### ISSUE TITLE
Visual Studio for Mac doesn't have structness inference

### ISSUE THREAD

**Issue by Happypig375** [dotnet/fsharp#7367]
```fs
let f x = match x with struct(1, 2) -> 0 | _ -> 1
let g x = f (1, 2)
```
On Windows (VS16.2.1): Successfully compiles
On Mac (VSMac8.2.1):
<img width="506" alt="image" src="https://user-images.githubusercontent.com/19922066/62680008-cd559500-b9e8-11e9-9e4a-20763e7c0937.png">

**Comment by dsyme** [comment]
@nosami One more motivation for VSMac F# bits update

**Comment by cartermp** [comment]
Closing as an external issue, I suspect this is just an old FCS being used in VSMac

**Comment by nosami** [comment]
@dsyme I am no longer working on the team that deals with F# updates /cc @sgmunn

**Comment by nosami** [comment]
@charlesroddie what do you mean exactly? Editor sluggishness or something else?

**Comment by Happypig375** [comment]
From the context of this issue, the "lag" here probably means "slowness to update F# dependencies".
