### ISSUE TITLE
VS crashes when using IF-OCAML/ENDIF-OCAML directives

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#7374]
Given the following:

```fsharp
(*IF-OCAML*)
// CODE HERE
(*ENDIF-OCAML*)
```

Type `Format.printfn "`

And VS will crash.

**Comment by dsyme** [comment]
We should somehow remove/more-actively-deprecate this old, old, old feature.

**Comment by cartermp** [comment]
I think we could put it behind a warning for F# 5 (behind the LangVersion flag) and ship that ASAP

**Comment by KevinRansom** [comment]
@dsyme, I took it out once but put it back in, because someone noticed it. 
 https://github.com/dotnet/fsharp/issues/3021
We should just make the editor not crash, the feature isn't actually much of a burden.

**Comment by cartermp** [comment]
This doesn't reproduce anymore.
