### ISSUE TITLE
fs files with Link are sometimes not rendered in VS

### ISSUE THREAD

**Issue by 0x53A** [dotnet/fsharp#7390]
![image](https://user-images.githubusercontent.com/4236651/62891293-a16a4480-bd45-11e9-8da9-87c32743f948.png)

Note: If you create the project and edit it, then it renders correctly.
When you save, close and reopen, the file is missing.

This worked in VS2017.

![image](https://user-images.githubusercontent.com/4236651/62891259-8bf51a80-bd45-11e9-932f-575a0b929acd.png)

**Comment by cartermp** [comment]
@davkean Is this a project system concern? I don't think we handle anything to do with links in our language service

**Comment by davkean** [comment]
This is a underlying project system issue, it seems to only occur when you have a linked item that points to itself - do you have another repro other than above?

I've opened https://devdiv.visualstudio.com/DevDiv/_workitems/edit/965214 internally. If you want to track the bug, please Report a Problem and I can that bug against yours.

**Comment by 0x53A** [comment]
> it seems to only occur when you have a linked item that points to itself - do you have another repro other than above?

Yes that's also what I observed so far.
