### ISSUE TITLE
Arbitrary nonsense attributes can be added to type extensions

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#7394]
Consider the following:

```fsharp
open System

[<Hello.my.name.is.Don.Syme>]
type String with
    member this.Doot() = this.Length

```

![image](https://user-images.githubusercontent.com/6309070/62986849-3fb3e400-bdf2-11e9-8630-c2f24e23fa34.png)

This should emit an error.

**Comment by dsyme** [comment]
Yup

**Comment by KevinRansom** [comment]
@cartermp, @dsyme.

Theoretically this is a breaking change.   Given that the attributes are garbage, we should be prepared to tell developers to fix their code.  If they see the error.

Kevin

**Comment by cartermp** [comment]
Agreed
