### ISSUE TITLE
The compiler fails to understand FSharpFunc if it's used directly

### ISSUE THREAD

**Issue by Arshia001** [dotnet/fsharp#7397]
If FSharpFunc is used directly in code, the compiler's type checks fail to understand it. This is a very odd case and shouldn't be that common. I had to do it so I can specialize functions at runtime, and I know of no way to do it with normally defined functions.

**Repro steps**

Having

```
type MyFunc() =
    inherit FSharpFunc<int, int>()
    override __.Invoke(x: int) = x + 1
```

both of these fail to compile with "This expression was expected to have type 'int -> int' but here has type 'MyFunc'":

```
let f1 : int -> int = MyFunc()
let f2 : FSharpFunc<int, int> = MyFunc()
```

which is understandable, given that F# doesn't do polymorphic assignments by default. However, you can normally do a cast, so this should work:

```
let f1 = MyFunc() :> int -> int
let f2 = MyFunc() :> FSharpFunc<int, int>
```

but it doesn't. Now it complains that "The type 'int -> int' does not have any proper subtypes and need not be used as the target of a static coercion." and that "Type constraint mismatch. The type 'MyFunc' is not compatible with type 'int -> int'"

But it clearly is compatible, and int -> int *does* have a subtype under these circumstances. I can understand why the warning would be suitable in most cases and should probably stay, but the cast has no reason not to work.

**Expected behavior**

The cast should work...

**Actual behavior**

… but it doesn't.

**Known workarounds**

It can be worked around by doing a runtime cast:

```
let f1 = MyFunc() :> obj :?> int -> int
```

But I believe this adds runtime overhead:

```
f1@45 = IntrinsicFunctions.UnboxGeneric<FSharpFunc<int, int>>((object)new MyModule.MyFunc());
```

* Operating system: Windows 10 1809
* .NET Runtime kind: dotnet core version 3.0.100-preview5-011568
* Editing Tools: VS 2019 v 16.2.0

**Comment by dsyme** [comment]
I'm going to close this as by-design. We do support defining nominal subtypes of `FSharpFunc` but in order to make them usable as true F# function values you do have to do the unbox mentioned above.  If you like open a language suggestion for this.  

Note the cost of the unbox (really a type test) should be quite low considering you are also allocating (and presumably later invoking) a function value
