### ISSUE TITLE
"function" cannot be implicitly converted the same way "fun x" does.

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#7401]
I found this case where function can't be substituted, in relation to implicit conversion to `Func<,>` delegate.

**Repro steps**

```fsharp
open System
let ae = new AggregateException()
    
ae.Handle(fun e ->
    match e with
    | :? OperationCanceledException -> true
    | _ -> false        
    )

ae.Handle(function
    | :? OperationCanceledException -> true
    | _ -> false        
    )

ae.Handle(
    Func<exn,bool>(
        function
        | :? OperationCanceledException -> true
        | _ -> false        
    ))
```

I'd expect those three calls to be the same, but the second one doesn't compile.

**Actual behavior**

> This function takes too many arguments, or is used in a context where a function is not expected

The error seems incorrect in that particular context.

**Expected behavior**

Not sure, but it would make sense if it could compile the same as (fun x -> match x with ...) in that context.

If this can't be fixed in the language, the error could be detected to point user to the preferred solution.

related: #2907

**Comment by cartermp** [comment]
Just feels like a bug to me.

**Comment by dsyme** [comment]
Yes, this is a bug
