### ISSUE TITLE
Nameof on a generic type allows specifying bogus type arguments

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#7416]
Given this:

```fsharp
type C<'T>() = class end

let name = nameof C<int, string, PhillipCarter>
```

The code compiles and `name` is given `"C"`.

This should fail to compile, since `C<int, string, PhillipCarter>` is not valid.

**Comment by dsyme** [comment]
Updated the issue :)

**Comment by dsyme** [comment]
Thanks for this report.  The fix is now part of the update to the preview feature at https://github.com/dotnet/fsharp/pull/8754

I'll close this for now since it's tracked in https://github.com/dotnet/fsharp/pull/8754
