### ISSUE TITLE
Use singleton objects to represent functions that do not capture external variables

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/fsharp#7429]
**Is your feature request related to a problem? Please describe.**

Let's take a look at a simple function. It adds 1 to each member of a list:

``` fsharp
let f x = List.map ((+) 1) x
```

This function gets compiled to the IL equivalent of this C# code (some code was removed for clarity):

``` csharp
public static class _
{
    internal sealed class f@1-5 : FSharpFunc<int, int>
    {
        internal f@1-5()
        {
        }

        public override int Invoke(int y)
        {
            return 1 + y;
        }
    }
    public static FSharpList<int> f(FSharpList<int> x)
    {
        return ListModule.Map(new f@1-5(), x);
    }
}
```

The problem here is that every time `f` gets called, it creates an object representing a function. This object does not contain any kind of data, it only overrides a method that adds 1 to a number and returns it. If the function inside `List.map` was capturing any variables, creating an object would have been It might be a small allocation, but here, it is a totally unnecessary one.

**Describe the solution you'd like**

I would like this function to be compiled like this:

``` csharp
public static class _
{
    internal sealed class f@1-5 : FSharpFunc<int, int>
    {
        private f@1-5()
        {
        }

        public static readonly f@1-5 Instance = new f@1-5();

        public override int Invoke(int y)
        {
            return 1 + y;
        }
    }
    public static FSharpList<int> f(FSharpList<int> x)
    {
        return ListModule.Map(f@1-5.Instance, x);
    }
}
```

The `f@1-5` class implements the Singleton pattern: only one instance thereof exists, and this one gets used every time `f` is called, without any unnecessary allocations.

This solution would still work when the function was a generic one, because a only single function object per generic type would be created.

**Describe alternatives you've considered**

I tried to cheese the compiler by writing something like this:

``` fsharp
let fFunc = fun x -> x + 1
let f2 x = List.map fFunc x
```

But I still couldn't avoid the allocation.

**Additional context**

I used [SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEAzAzgHwxgBcACbUhUgXlIBkBLXYgOgFsBDAB1IApeA1AEpSARhEIAsACgZRMtgBiAVwB2YGuTWVScAHw6BYuSXIAmHbUbN23civWUgA) to perform my experiments.

**Comment by auduchinok** [comment]
>  tried to cheese the compiler by writing something like this:

In some cases a mutable binding would do the trick.
```fsharp
let mutable fFunc = fun x -> x + 1
```

**Comment by Frassle** [comment]
This reduces allocations but there's also no way to collect those singleton functions so your trading for increased memory pressure. That's probably not always the right tradeoff.

**Comment by teo-tsirpanis** [comment]
I understand that it's a problem, but how big are these function objects? How big would the total footprint be?

Besides, the number of these function types is constant per running program.

And they will not be created until they are needed that first time.

**Comment by Frassle** [comment]
> I understand that it's a problem, but how big are these function objects? How big would the total footprint be?

I think 8 (x86) or 12 (x64) bytes. There's also overhead to having static fields (see beforefieldinit) but I'm not sure the details for that.

**Comment by dsyme** [comment]
>  There's also overhead to having static fields (see beforefieldinit) but I'm not sure the details for that.

It does need to be perf-checked, particularly for this reason.  There's also a potential volatile read if we insist on never double-allocating the object.

**Comment by matthid** [comment]
@dsyme IIRC the C# compiler is doing something very similar here. Shouldn’t we just mirror that? (I mean it probably has been battle tested)
If C# potentially double allocates we could go down the same road?

If we do our own analysis we should at least ask those guys over in C# land what they learned or would do differently ...

**Comment by dsyme** [comment]
> @dsyme IIRC the C# compiler is doing something very similar here. Shouldn’t we just mirror that? (I mean it probably has been battle tested) If C# potentially double allocates we could go down the same road?

Yes AFAIK they do similar things in various cases

**Comment by teo-tsirpanis** [comment]
I have recently noticed that since some time, the F# compiler has started doing that in Release mode. Great job!
