### ISSUE TITLE
Deprecate optdata and sigdata generation in FSharp.Core?

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#7433]
See this section in FSharp.Core:

https://github.com/dotnet/fsharp/blob/8dd81c6424bfafd02b31b2ddd92c20fc7cd0e817/src/fsharp/FSharp.Core/FSharp.Core.fsproj#L223-L234

Is this really necessary to do given that this was added so long ago? Is it really realistic that compilers that are at least 6 years old will need to reference newer FSharp.Core versions?

**Comment by dsyme** [comment]
> Is this really necessary to do given that this was added so long ago? Is it really realistic that compilers that are at least 6 years old will need to reference newer FSharp.Core versions?

I'm not sure it's 6 years - was it VS2015 or VS2017 where we integrated the optdata and sigdata?

I guess it's still possible, but people could pin to a particular FSharp.Core

**Comment by cartermp** [comment]
At leas the GitHub history suggests that target was added 6 years ago, see here: https://github.com/dotnet/fsharp/blame/584093c6bcac8f4e67d1d2d588138be32e76310d/src/fsharp/FSharp.Core/FSharp.Core.fsproj#L221

**Comment by cartermp** [comment]
Though I think the current setup for that task was 5 years ago: https://github.com/dotnet/fsharp/commit/5d2651340ffa088e2bfbe0ae7188222cc02f3cfc#diff-645ab24ebf833246dac267d78727cb18R218

**Comment by cartermp** [comment]
Weird. Git history shows that task is much older. Are we referring to the same thing here?

Also note this:

> An alternative would be have all tools always find FSHarp.Core via an FSharp.Core nuget package. That's fine for compilation/analysis tools that understand nuget - but quite a few don't and the churn in msbuild/nuget/project.json doesn't make it an attractive dependency. In any case making tools download a large nuget package is not a great solution, since it's even worse for tool correctness (the nuget feeds consistently go down) and performance (the download is large).

Has become far more prevalent now that we officially distribute FSharp.Core via NuGet, even for legacy projects.

**Comment by dsyme** [comment]
The comment was added here: https://github.com/dotnet/fsharp/commit/4fcfb8b6e16804105cab8d7500e82530cd1b8500

Yes the task is older

**Comment by KevinRansom** [comment]
I am expecting to do this for FSharp.Core 5.0.  If they rely on an old FSharp.Core then they are required to also supply the sigdata and optdata files.  All new tooling for a lot of years has looked in fsharp.core for those files.

I don't think there are any popular tools that rely on very old FSC tooling.
