### ISSUE TITLE
Function tooltip shows documentation for its parameter

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#7455]
Original issue: [RIDER-27979](https://youtrack.jetbrains.com/issue/RIDER-27979).

```fsharp
/// Function
let f (
          /// Param
          p: int
      ) = ()

f 1
```

<img width="257" alt="Screenshot 2019-08-27 at 22 59 25" src="https://user-images.githubusercontent.com/3923587/63803833-6e67a980-c91e-11e9-8041-c1d4fd5d35f4.png">

**Comment by cartermp** [comment]
Fixed by https://github.com/dotnet/fsharp/pull/9117
