### ISSUE TITLE
[Feature request] Top-down programming support

### ISSUE THREAD

**Issue by goldimax** [dotnet/fsharp#7457]
(Sorry for my poor English writing)
As the complex `let` binding is hard to read, it’s common to refactor with `let` binding inside the previous binding. Just like this:
```fsharp
let calc arg1 arg2 =
    let x = ...
    let y a = ...
    let z a b =
        let q c = ...
        ...
    ...
```
But if the `let` binding body is really really long, it’s hard to find the main expression of the `let` binding immediately. You need to scroll and scroll. If there is a top-down key word, it would be easier to read. I give a example here using `where` as keyword.
```fsharp
let calc arg1 arg2 = ...
    where z a b = ...
        where q c = ...
    where y a = ...
    where x = ...
```
Thus, the main expression is placed just after the `let` definition. Just read the first line of the binding to know what it returns. Also, with the top-down keyword we can write a function from top to the bottom. Just write the main expression and then write what the dependencies.

**Comment by smoothdeveloper** [comment]
@goldimax thanks for the suggestion, I think it belongs to https://github.com/fsharp/fslang-suggestions as this repository would be for compiler and VF# issues.

Please have a look and consider posting it there.

**Comment by goldimax** [comment]
@smoothdeveloper thx, and I will open an issue there.
