### ISSUE TITLE
Error messages are, in general, unhelpful

### ISSUE THREAD

**Issue by Heimdell** [dotnet/fsharp#7473]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I see an error like this:
```
/home/kir/git/games/godot/tetris/Tetris.fs(261,15): error FS0039:
  The field, constructor or member 'Item' is not defined.
```
on the code like that:
```fsharp
glass.[row, col]
```
I know that it means that the type of `glass` object doesn't declare any indexer; but for a newcomer it is a big _wat_.

**Describe the solution you'd like**

I want the error message like that to show the type of the object in question. It very well might be that I unintentionally used the wrong object. Saying that it is a `'a glass` instead of `anything indexable` will help to understand the cause.

Even if the type to output is a type variable or a `... where ...`-mess or something inferred and non-repesentable.

**Comment by forki** [comment]
I just looked at this. It's not easy to do since in many of the FS39 cases you don't actually have type information available at this position.

**Comment by cartermp** [comment]
Fixed in https://github.com/dotnet/fsharp/pull/8346
