### ISSUE TITLE
FS0193 internal error: Specified argument was out of the range of valid values. Parameter name: span

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#7498]
Type this into a script file:

```fsharp
let _ = [] |> List.map (sprintf @"\\%d")
```

Until there are no symbols after this line, an error is shown:

![1](https://user-images.githubusercontent.com/873919/64345092-5b2c9c00-cff8-11e9-9bef-d2c64f1b2986.gif)

VS 2019, Rider

**Comment by TIHan** [comment]
Good find. I may know what is going on.

**Comment by dsyme** [comment]
This no longer repros, it must have been fixed

**Comment by vasily-kirichenko** [comment]
I love the way bugs are fixed here :)
