### ISSUE TITLE
List of anonymous records cannot be used in `for` expression inside computation expressions

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#7586]
The following code, being written in a script, is not highlighted as erroneous, but sending it to FSI produces the following error:

```fsharp
let xs = [ {| Id = 1 |} ]

async {
    for x in xs do printfn "%d" x.Id
}
|> Async.RunSynchronously
```
```
...\scratch_20.fsx(4,14): error FS0193: Type constraint mismatch. The type 
    '{|Id : int|} list'    
is not compatible with type
    'seq<{|Id : int|}>'    
```
Note that VS editor does not show the error.

Changing the first line to `let xs = seq [ {| Id = 1 |} ]` fixes the error.

VS 16.2.5

**Comment by cartermp** [comment]
On the latest .NET Core SDK this doesn't reproduce. Likely some bug fix in the past year. Will close this out

<img width="407" alt="image" src="https://user-images.githubusercontent.com/6309070/87238716-e0bc6d80-c3ba-11ea-87bd-ab60c42f9929.png">
