### ISSUE TITLE
`[||]` should compile to System.Array.Empty<object>

### ISSUE THREAD

**Issue by chinwobble** [dotnet/fsharp#7595]
Array clamps should compile to `System.Array.Empty<T>()` instead of `new T[0]`;

This causes unnecessary object allocations.
In fact FsharpList already compiles to `FSharpList.Empty`

Provide the steps required to reproduce the problem:

1. Create a new project with .net core 2.1 and fsharp.core 4.7

Create a type like this
```fsharp
type TestType =
    member __.EmptyArray() = [||]
```

**Expected behavior**
Should compile to 
```csharp
System.Array.Empty<T>()
```

**Actual behavior**
inspect the generated C# and it looks like this
```csharp
public b[] EmptyArray<b>()
        {
            return new b[0];
        }
```

**Known workarounds**

None

**Related information**

Provide any related information (optional):

* Win 10 x 64
* .NET core 2.1 Fsharp Core 4.7
* VS 2019 16.2

**Comment by forki** [comment]
Maybe dumb question but what's the benefit?

Benney Au <notifications@github.com> schrieb am Do., 19. Sep. 2019, 06:02:

**Comment by rojepp** [comment]
@forki `Array.Empty<T>` caches the array which helps reduce allocations. 
The empty array is immutable so this is perfectly safe.

**Comment by forki** [comment]
Thanks

Robert Jeppesen <notifications@github.com> schrieb am Do., 19. Sep. 2019,
08:47:

**Comment by smoothdeveloper** [comment]
Wondering if `String.Empty` versus `""` is exhibiting the same issue?

**Comment by rojepp** [comment]
@smoothdeveloper They should be equivalent due to string interning. https://stackoverflow.com/questions/263191/in-c-should-i-use-string-empty-or-string-empty-or-to-intitialize-a-string?rq=1

**Comment by smoothdeveloper** [comment]
thanks @rojepp I guess I'll turn to you on allocation issues :)

**Comment by chinwobble** [comment]
@smoothdeveloper @rojepp  @forki I checked FSharpList and it uses the optimised static member FSharpList.Empty

**Comment by forki** [comment]
Yes I know we do it for lists. Just wanted to make sure it's the same pattern

**Comment by auduchinok** [comment]
It's currently done this way due to we'd had to target `net45` in compiler and FCS for a broader reach and ``EmptyArray`1`` type was only introduced in `net461`. Since we've switched to a newer target framework in the compiler we can now use the singleton, it's just need to be done by someone. :)

**Comment by chinwobble** [comment]
@auduchinok would be happy to contribute if you gave some pointers on where to look to improve this?

**Comment by cartermp** [comment]
This could be done for F# 5.0, since we're going to drop the `net45` binary from FSharp.Core and move to be .NET Standard 2.0-only.

**Comment by forki** [comment]
Well it could already be done now if we ifdef it, right?

Phillip Carter <notifications@github.com> schrieb am Sa., 21. Sep. 2019,
18:25:

**Comment by cartermp** [comment]
Yes, though I'd prefer to avoid any and all ifdefs given how many of those horrible things we have

**Comment by forki** [comment]
They are not horrible. Just little creepy. It's all fine if we don't feed
them after midnight.

Phillip Carter <notifications@github.com> schrieb am Sa., 21. Sep. 2019,
18:32:

**Comment by chinwobble** [comment]
@forki bump

**Comment by forki** [comment]
@chinwobble I think you can try to send a pull request.

**Comment by forki** [comment]
maybe @dsyme can point you to the correct location in the source

**Comment by dsyme** [comment]
> maybe @dsyme can point you to the correct location in the source

I guess in IlxGen.fs `GenNewArray` and/or `GenNewArraySimple` (the latter being used for small arrays)

**Comment by Happypig375** [comment]
Bump

**Comment by cartermp** [comment]
All done, thanks @kerams
