### ISSUE TITLE
Can't raise exceptions when returning byref or IsByRefLike types

### ISSUE THREAD

**Issue by debugnik** [dotnet/fsharp#7606]
When a function returns a byref or IsByRefLike type, `raise : exn -> 'a` can't be called because that instantiates `'a` as the byref type. This issue thus extends to any function returning `'a` to signal non termination, such as `failwith` or even `exit`.

**Repro steps**

```F#
[<Struct; System.Runtime.CompilerServices.IsByRefLike>]
type Resource = Resource of Handle: nativeint

let obtainHandle () = 0n

let createResource () =
    match obtainHandle () with
    | 0n -> failwith "Error creating resource."
    | handle -> Resource handle
```

**Expected behavior**

The code above compiles.

**Actual behavior**

The compiler marks `failwith` with error FS0412:

> A type instantiation involves a byref type. This is not permitted by the rules of Common IL.

**Known workarounds**

Ignoring the return value and returning instead a dummy value; this path would never be reached.

```F#
    | 0n -> failwith "Error creating resource."; Resource 0n
```

Another workaround, inspired by #6607 and #6133, is to alias the IsByRefLike type and constraint `'a` to the alias.

```F#
type Res = Resource
```
```F#
    | 0n -> failwith "Error creating resource." : Res
```

This can be used even if you don't have access to a constructor or function that returns the IsByRefLike type, but seems fragile to future compiler versions.

**Related information**

Tested on .NET Core 3.0.100-preview7-012821.

**Comment by cartermp** [comment]
See here: https://github.com/dotnet/fsharp/issues/5776

This is by design, as `failwith` is a generic function that would imply boxing.

**Comment by debugnik** [comment]
Sorry for the duplicate! I didn't find that issue in my first search.

I understand why this is by design for byref types, but I'm surprised this affects IsByRefLike types too, unless they have some unnecessary CLR limitations. I'll take a deep look at this.

**Comment by cartermp** [comment]
@debugnik In this case, ByRefLike structs have the same semantics as byrefs. They're stack-only types that cannot be boxed.

**Comment by debugnik** [comment]
@cartermp I understand the limitations of byrefs. I just think it would be safe to instantiate a generic method with a byref-like when it appears **only** in the return position (or not at all, like the phantom type in `typeof`). The method can't box a byref-like or store it in an object it doesn't have one in the first place.

But I've learned that this is enforced at the CLR level, so don't mind me.
