### ISSUE TITLE
Visual Studio "Go To Defition" broken, on symbols defined in file used in several projects.

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#7608]
**Reproduction steps**

* clone https://github.com/fsprojects/FSharp.Data.SqlClient
* build.cmd 
* open SqlClient.sln
* try go to definition on `Name` https://github.com/fsprojects/FSharp.Data.SqlClient/blob/37a6ae50b69c97e9f9c875feec52f550640fa1b4/src/SqlClient.DesignTime/DesignTime.fs#L443

Screencast (the tooltip and context menu don't show)

![vs go to def versus tooltip](https://user-images.githubusercontent.com/87944/65385818-3bed7880-dd33-11e9-97b6-a776a8c4b550.gif)

The navigation via tooltip works.

**Expected behavior**

can go to definition with usual keyboard shortcut / without using tooltip assistance.

**Actual behavior**

![image](https://user-images.githubusercontent.com/87944/65385866-072df100-dd34-11e9-83dc-db25eba325ef.png)

**Known workarounds**

Mouse and enhanced tooltip support enabled

**Related information**

VS 2019 16.2

**Comment by cartermp** [comment]
This was fixed by #7376 (in addition to a few other issues stemming from the same problem). You can use the VS 16.3 previews today to confirm, or wait until tomorrow when it'll release.

**Comment by smoothdeveloper** [comment]
Great, I'll check it out, thanks for the notice!
