### ISSUE TITLE
add Fsharp.Core to https://docs.microsoft.com/en-us/dotnet/api/

### ISSUE THREAD

**Issue by chinwobble** [dotnet/fsharp#7610]
**Is your feature request related to a problem? Please describe.**
As a developer I cannot easily discover all the functions available in the core library.

**Describe the solution you'd like**
Add FSharp.Core docs to https://docs.microsoft.com/en-us/dotnet/api/

**Describe alternatives you've considered**
- Reference FSharp.Core in a C# project and look at object explorer
![image](https://user-images.githubusercontent.com/18226001/65422774-beb52700-de4a-11e9-885d-58e3af6e73b7.png)

- look at old versions of the FSharp.Core docs on here 
https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/fsharp-core-library-reference?f=255&MSPPError=-2147217396

**Comment by cartermp** [comment]
Closing out as this is external. The API reference is here: https://fsharp.github.io/fsharp-core-docs/

eventually it will be incorporated into the MS docs site
