### ISSUE TITLE
Multiple reports that fsi does not work in dotnet core 3 without mono

### ISSUE THREAD

**Issue by forki** [dotnet/fsharp#7614]
https://twitter.com/asp_net/status/1176385562225364992

**Comment by forki** [comment]
duplicate of https://github.com/dotnet/fsharp/issues/7277#issuecomment-534222213

**Comment by cartermp** [comment]
Just to clarify: it works, there's just an error emitted due to an old reflection hack whose fix isn't shipped yet.

**Comment by aspnetde** [comment]
Starting with `dotnet fsi` I end up here:

<img width="762" alt="image" src="https://user-images.githubusercontent.com/1322584/65523608-cdecb100-deec-11e9-8db0-09e070efa180.png">

Pressing enter brings me to:

<img width="762" alt="image" src="https://user-images.githubusercontent.com/1322584/65523780-11471f80-deed-11e9-9e77-5b325232bc5f.png">

Typing `#help;;`, however, brings me in.

**Comment by rmunn** [comment]
For anyone who finds this: typing anything would have worked as well as typing `#help;;`. The `-` prompt is the indication of a continuation line, but if your first input line was blank (i.e. you just pressed Enter) then any expression will still be valid.

**Comment by cartermp** [comment]
@aspnetde It works if you just type out code:
![image](https://user-images.githubusercontent.com/6309070/65524957-91489780-dea3-11e9-93c5-b6a30103f220.png)

**Comment by aspnetde** [comment]
Correct. My mistake.
