### ISSUE TITLE
Struct / struct Anonymous Records constraint inconsitency

### ISSUE THREAD

**Issue by thinkbeforecoding** [dotnet/fsharp#7618]
Span<'t> and ReadOnlySpan<'t> usage for the following constraints on 't :

```fsharp
let inline head<'t when 't: (new: unit -> 't)
                     and  't: struct
                     and  't:> ValueType >
                (s: ReadOnlySpan<byte>) =
                &(cast<'t> s).[0]
```
When using it with a struct record (not anonymous, it works as expected:

```fsharp
[<Struct>]
type Delta =
    { SkipX: byte
      Control: sbyte }
    let delta = head<Delta> ctx.Chunk
```

But it doesn't work with an anonymous struct record:

```
    let delta = head< struct {| SkipX: byte; Control: sbyte |} > ctx.Chunk
```
The compiler complains for a missing constraint:
```

Error	FS0001
The type 'struct {| Control: sbyte; SkipX: byte |}' is not compatible with the type 'ValueType'	nomemalloc

```

Not sure the default constructor constraint and ValueType constraint should actually be required on the generic function, since struct should make them implicit. 
Anyway, the struct Anonymous Record should pass these constraints if necessary.

**Known workarounds**

Define the type explicitly.

**Comment by cartermp** [comment]
Proposed behavior:

```fsharp
let inline head<'t when 't: struct>
                (s: byte ReadOnlySpan) =
                &(cast<'t> s).[0]
```

This should be all that is needed, which is also true for C#. As with C#, if you try to do something with the `'t` that is not compatible with byref-like structs, the compiler should complain about that just like in other code that uses these kinds of structs.

**Comment by TIHan** [comment]
Agreed that these should be consistent.

**Comment by dsyme** [comment]
There are two issues here

1. struct tuples and struct anon records are not currently considered subtypes of System.ValueType.  I'm fixing that

2. the second question about simplifying constraints that imply each other (struct, System.ValueType etc.)

Here we should just fix (1)

(2) would be a language suggestion and must be done with care.

**Comment by dsyme** [comment]
let inline head<'t when 't: (new: unit -> 't)
                     and  't: struct
                     and  't:> ValueType >
                () = ()
