### ISSUE TITLE
With .net core 3, debug sequence points can be lost

### ISSUE THREAD

**Issue by SteveGilham** [dotnet/fsharp#7643]
Sequence points, and hence debug breakpoints, code coverage information and other diagnostic information is missing from .net core 3.0 builds, that was present in earlier SDK versions

**Repro steps**

I compile this project
[Sample4.zip](https://github.com/dotnet/fsharp/files/3662039/Sample4.zip)
with particular interest in this function
```
    member this.as_bar() =
      try
        match this with
        | Foo n -> Bar(string n)
        | Baz d -> Bar(string d)
        | Bop t -> Bar(string t)
        // New cases go in here
        | _ -> this
      with _ -> Bar "none"
```
using .net core SDK 2.1.801, and then inspect in ILSpy -- the IL is annotated with sequence points
[sample4.2.il.zip](https://github.com/dotnet/fsharp/files/3662076/sample4.2.il.zip)

do the same with SDK 3.0.100 and the sequence point annotations are missing
[sample4.3.il.zip](https://github.com/dotnet/fsharp/files/3662084/sample4.3.il.zip)

This manifests in VS 2019 16.3.1 as allowing breakpoints to be set in the quiescent state

![image](https://user-images.githubusercontent.com/7460854/65760005-189c4200-e114-11e9-9b1f-9ea197e511fb.png)

but when debugging, most of them vanish

![image](https://user-images.githubusercontent.com/7460854/65760110-41bcd280-e114-11e9-8fed-102274bb16cf.png)

**Expected behavior**

Breakpoints can be set and coverage information extracted on the leaf expressions of a `match` expressions

**Actual behavior**

You can't any more

**Known workarounds**

Downgrade to earlier tool versions

**Related information**

Provide any related information (optional):

* Operating system - WinX Home
* .NET Runtime kind (.NET Core, .NET Framework, Mono) - .net core SDK versions 2.1.801 and 3.0.100
* Editing Tools (e.g. Visual Studio Version, Visual Studio) - breakpointing in Visual Studion 16.3.1

**Comment by cartermp** [comment]
@KevinRansom can you take a look? Seems kinda serious

**Comment by dsyme** [comment]
I checked and the code debugs ok with .NET 5.0 (apart from the glitch with #11978 )
