### ISSUE TITLE
Installing F# on Ubuntu 19.04

### ISSUE THREAD

**Issue by robbyb74** [dotnet/fsharp#7663]
Problem encountered on https://dotnet.microsoft.com/learn/languages/fsharp-hello-world-tutorial/create
Operating System: Linux Ubuntu 19.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by cartermp** [comment]
@robbyb74 could you describe the problem you encountered? Thanks!

**Comment by cartermp** [comment]
Closing as no repro
