### ISSUE TITLE
Module-level code missing debug information

### ISSUE THREAD

**Issue by mydogisbox** [dotnet/fsharp#7667]
Please provide a succinct description of the issue.

Variable inspection isn't available when running module-scope code when the module is first opened.

**Repro steps**

Provide the steps required to reproduce the problem:

1. In VS 2019, create an F# console application project
2. Insert the following code:
```
open System

module test =
  let test = 5
  let teststring = test.ToString()
  let testArray = [|teststring|]

  let printString () =
    printfn "%s" teststring

  printString()

[<EntryPoint>]
let main argv =
    printfn "%s" test.teststring
    0 // return an integer exit code
```

3. Put a breakpoint on printString()
4. Run the application and hover over `test`, `teststring`, and `testArray`

**Expected behavior**

Expected Result:
I should be able to inspect the values of all three variables when the application is stopped on the `printString()` breakpoint.

**Actual behavior**

Only `test` can be inspected until the debugger has stepped into `printString`.

**Related information**

* Operating system
Windows

* .NET Runtime kind (.NET Core, .NET Framework, Mono)
Tried with .net core 2.2, .netcore 3.0 and .net framework 4.7.2

* Editing Tools (e.g. Visual Studio Version, Visual Studio)
Visual Studio 2019

**Comment by abelbraaksma** [comment]
IIRC, These are not available because the initialization of the module has not yet completed. Evaluating them for the debugger would then undoubtedly create a recursive initialization. However, you can put breakpoints on the individual assignments and they'll appear in the locals window, I believe.

It could perhaps be improved, though.

**Comment by mydogisbox** [comment]
I could see that being the case since my understanding is that they get compiled down to static methods, but the behavior I was seeing is inconsistent with that theory (although it still might be correct!).

When the breakpoint was on `printString()`, `teststring` and `testArray` were unavailable, but the moment I stepped _into_ `printString` they were suddenly available despite the fact that `printString()` is clearly still part of the module initialization (unless maybe there is some magic where the module knows no other properties are getting initialized?).

**Comment by abelbraaksma** [comment]
> unless maybe there is some magic where the module knows no other properties are getting initialized?

All let bindings in a module are initialized top down on first access. I'm not aware of any exceptions, and this is consistent with what you are experiencing.

**Comment by cartermp** [comment]
@abelbraaksma is correct in his analysis here. Even though it's possible, I generally wouldn't recommend having module-bound _values_. They're static data floating around and are initialized independently as mentioned here.
