### ISSUE TITLE
`FSharpCompiler.SourceCodeServices.FSharpChecker.ParseFile` tracing takes a long time

### ISSUE THREAD

**Issue by chinwobble** [dotnet/fsharp#7669]
Upon doing a performance investigation of Fantomas I found that `FSharpCompiler.SourceCodeServices.FSharpChecker.ParseFile` tracing takes a long time on net framework targets. 

**Repro steps**
run the following code in a console app
Get the source file 
https://raw.githubusercontent.com/fable-compiler/fable-recharts/master/sample2/src/Charts.fs

```fsharp
async {
  let parsingOptions = 
  {{ SourceFiles = [|"/tmp.fsx"|]
    ConditionalCompilationDefines = []
    ErrorSeverityOptions = 
                         { WarnLevel = 3
                           GlobalWarnAsError = false
                           WarnOff = []
                           WarnOn = []
                           WarnAsError = []
                           WarnAsWarn = [] }
    IsInteractive = false
    LightSyntax = None
    CompilingFsLib = false
    IsExe = false }}
    CompilingFsLib: false
    ConditionalCompilationDefines: Length = 0
    ErrorSeverityOptions: {{ WarnLevel = 3
    GlobalWarnAsError = false
    WarnOff = []
    WarnOn = []
    WarnAsError = []
    WarnAsWarn = [] }}
    IsExe: false
    IsInteractive: false
    LightSyntax: null
    SourceFiles: {string[1]}
  let sourceText = FSharp.Compiler.Text.SourceText.ofString source
  let! untypedRes = checker.ParseFile("/tmp.fsx", sourceText, parsingOptions)
}
```
**Expected behavior**

Trace logging / diagnostics should not take much time (<10 ms)

**Actual behavior**
Notice that tracing in jetbrains dotTrace shows that TraceEvent method takes a lot of time.
![image](https://user-images.githubusercontent.com/18226001/65810785-7acb7480-e1f2-11e9-95a4-0b61617957eb.png)

**Related information**

* Win 10 x64
* dotnet framework 4.6.1
* FSharp.Compiler.Services 31.0.0

**Comment by chinwobble** [comment]
@forki bump

**Comment by forki** [comment]
I'm not sure how I can help here. @cartermp did you folks looked into this?

**Comment by cartermp** [comment]
I'm not sure if this is inherent to the compiler, since there's no guarantee that a given tracing library is going to incur significant performance drawbacks on a given target. For example, running `msbuild /bl` can incur a massive performance cost such that timings are almost all going to be wrong, making that kind of diagnostic not useful for timings. Perhaps the same is true for what was being used in your environment.

**Comment by cartermp** [comment]
Given that this is coming from System.Diagnostics I don't think there's anything actionable here. ETW tracing is quite useful in the tools and isn't the bottleneck. I still think that what you saw was rather high and unexpected, perhaps a fluke? At any rate I'll close this out, but if you notice similar things with a newer compiler then we can re-open.
