### ISSUE TITLE
QuoteIdentifierIfNeeded with single underscore

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#7681]
**Repro steps**

```fsharp
FSharp.Compiler.SourceCodeServices.PrettyNaming.QuoteIdentifierIfNeeded "_"
```

**Expected behavior**

I was expecting the function to return `_`

**Actual behavior**

&grave;&grave;_&grave;&grave;

Is this correct?

**Related information**

Bug found in Fantomas: https://github.com/fsprojects/fantomas/issues/493

Provide any related information (optional):

* Windows
* .NET 461
* F# interactive repl

**Comment by abelbraaksma** [comment]
The identifier "_" is not a valid identifier. It is a valid pattern. This allows it to be used in let bindings, but not in places (like member names, function names) where a so-called `ident` is expected.

If you wanted to use the underscore as valid identifier, it needs to be back-quoted. Up I think this output is correct. 

Don't confuse it with the recently newly allowed `_` for the self identifier in instance member declarations. That is still not a valid `ident`, it's a special value that says "I don't need the self reference in the body of my member".

**Comment by cartermp** [comment]
Given this history of this line: https://github.com/dotnet/fsharp/blob/6a648d8bceb011000b1a7c7151af227b1347c5c8/src/fsharp/lexhelp.fs#L280

The answer is probably, "yes" it should be expected. However, it might be good to special cause discards for member declarations in tools.

**Comment by NinoFloris** [comment]
I wanted to start using _ for members but with ionide now having fantomas support I'm not very keen on ``_`` everywhere. How should we best fix this?

**Comment by abelbraaksma** [comment]
Is this a bug with Fantomas, Ionide or F#? I'm confused.

**Comment by auduchinok** [comment]
@abelbraaksma It's a limitation in the current FCS API. `_` is not a valid identifier, so it actually works as designed. FCS users want to use this API to check if something on an identifier place is allowed as is and it should probably be a separate API.
