### ISSUE TITLE
Debugger crashes when debugging F# code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#7690]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/417798/debugger-crashes-when-debugging-f-code.html)._

---
Appears to be related to debugger visualiser for underlying type.

---
#### Phillip Carter [MSFT] on 1/10/2019, 10:18 AM: 

<p>Hey there, we'll take a look at this. Generally speaking, if an underlying type is very large (or contains other very large data), then a custom debug visualizer is needed. But there could be something else going on.</p>
#### Matthew Peacock on 1/10/2019, 01:14 PM: 

<p>Thanks Phillip.  Currently it's impossible to know exactly what is causing the crash, so if it is indeed the lack of a custom debug visualizer for some type, it would be good if there was some way of knowing exactly which is the offending type.  Is it also possible to handle the underlying exception more gracefully instead of aborting the process being debugged?</p>

---
### Original Solutions
(no solutions)

**Comment by dsyme** [comment]
Closing as there is no repro
