### ISSUE TITLE
Fix Linux_FCS build

### ISSUE THREAD

**Issue by brettfo** [dotnet/fsharp#7698]
A recent update to the ADO VM image `ubuntu-16.04` causes mono/fake to crash when running the Linux_FCS leg of the build.  Since this is blocking all work and given that nearly identical coverage is given via the MacOS leg, Linux_FCS has been disabled in #7697.

When re-enabling Linux_FCS, it may be worth trying to not use mono, especially since we have no say over what version is installed on the ADO VMs.

**Comment by baronfel** [comment]
This can be closed, we've since converted the FCS build to FAKE 5 and .net core: https://github.com/dotnet/fsharp/blob/master/azure-pipelines.yml#L356-L366
