### ISSUE TITLE
How do I dispose a Mailbox processor?

### ISSUE THREAD

**Issue by boeremak** [dotnet/fsharp#7707]
Hi,

I am not really sure if this is the right place to ask this, but I've been searching for a while now and I can't really get a definitive answer.

How do I dispose a Mailbox Processor so that it gets garbage collected? I want to have a processor for a connection that my server handles but after a timeout I want it to just stop and get garbage collected freeing up the used memory.

Is this even possible?

**Comment by saul** [comment]
Cast the MailboxProcessor to an IDisposable, and then dispose that. For example: `(mailbox :> IDisposable).Dispose()`

**Comment by BentTranberg** [comment]
@boeremak, I don't remember what the rules are, but I can't imagine questions in general on F# are welcome here. If you're convinced you've found a bug or some nastiness in the compiler itself, then this is the place - if you can deliver a helpful report. But for questions on use of F#, I suggest you join us on **F# Slack**, where you're likely to get answers fast to questions like this one. You'll also find pretty much all the cool people and enthusiasts in the F# community there. Stackoverflow also has F# tags.

**Comment by cartermp** [comment]
Closing as this isn't a product issue. As @saul mentions, yes, you can dispose it as an IDisposable.

**Comment by boeremak** [comment]
Apologies for posting it here, I did not know about the Slack channel.

Thanks for answering it though, that is really helpful.

**Comment by bmitc** [comment]
Is there a reason why we can't add a `Dispose` method to `MailboxProcessor`?

**Comment by bmitc** [comment]
I'm not sure I understand. `MailboxProcessor` already implements `IDisposable`, and it's sealed. So for my current understanding, the question remains why `MailboxProcessor` doesn't provide a `Dispose` method. I suppose one answer could be that the usual thing to do with a `MailboxProcessor` is to wrap it with a class such that it isn't exposed, but it seems a little weird to have to constantly cast it to `IDisposable` to call `Dispose` on it.
