### ISSUE TITLE
`fst`, `snd` don't work on struct tuples

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#7715]
```fsharp
let t = struct (1, 2)
 let i1 = fst t
```

<img width="525" alt="Screenshot 2019-10-09 at 13 24 56" src="https://user-images.githubusercontent.com/3923587/66473671-6875f400-ea98-11e9-8d64-fe6c1906df27.png">

**Comment by TheJayMann** [comment]
Given that `fst` and `snd` are defined for two element reference tuples, they can't work for two element struct tuples.  One would have to define a `vfst` and `vsnd` (or possibly use better names) defined as below.
```fsharp
let inline vfst struct (a, _) = a
let inline vsnd struct(_,b) = b
```
This is simple enough to define in your own project, but would likely be beneficial to be included in fsharp core library alongside `fst` and `snd`.

**Comment by auduchinok** [comment]
I'd expect the existing functions to work, though. The reason is these functions are quite well-known to everyone and having different ones could end up in almost no one using them due to not knowing their names.
It's _probably_ possible to workaround using SRTP and/or having a special case in the compiler.

**Comment by TheJayMann** [comment]
My initial attempt at creating an SRTP version failed.  The reason appears to be that struct tuples do not defined `get_Item1` or `get_Item2`, as `Item1` and `Item2` are public read only fields, not properties, and it appears to me that SRTPs only work with properties and methods.

The reason I suggested `vfst` and `vsnd` is that it follows the pattern of new "struct option" which is named as `ValueOption` and aliased as `voption`, with the cases of `ValueSome` and `ValueNone`.  Perhaps the compiler can special case the functions similar to how it special cases the `nameof()` function, but that would then be an issue for [fsharp/fslang-suggestions](https://github.com/fsharp/fslang-suggestions/).

**Comment by 0x53A** [comment]
You can do it with SRTP, see https://github.com/fsharp/fslang-suggestions/issues/628#issuecomment-357291385

**Comment by abelbraaksma** [comment]
Apart from SRTP, with the new static opens, wouldn't a possible solution be to create two  static member overloads of `fst` and `snd`, and then just open the static class?

Didn't try it myself, but seems like a simpler solution perhaps.

**Comment by TheJayMann** [comment]
Given that you are already attempting to convert the Operator functions to static methods, you could just use static method overloading and be done.

```fsharp
static member inline fst (a, _) = a
static member inline fst struct (a, _) = a
static member inline snd (_, b) = b
static member inline snd struct (_, b) = b
```

**Comment by auduchinok** [comment]
I could probably be really great it was possible to write functions supporting both cases out of the box somehow.

**Comment by abelbraaksma** [comment]
@auduchinok, you mean, in general, for any function? Sure, that would be nice, but one is a reference type and the other a value type. They don't mix in .Net, unless you accept boxing. Which kind of negates the purpose, I guess. Other way might be with generics, or with SRTP, but that easily gets out of hands.

**Comment by dsyme** [comment]
This is by design.  They work on reference tuples, that's it really.

We won't add `vfst` or `fstv` or anything like that.  Using `fst` and `snd` are a bit smelly to be honest.  If we had a general mechanism we'd either embrace `tup.3` and `_.3` for the first class operator.
