### ISSUE TITLE
System.MissingMethodException : Method not found: 'Microsoft.FSharp.Core.FSharpFunc`2

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#7718]
I'm receiving the following error since I upgraded my VS 2019 instance to the latest version:

>   ----> System.MissingMethodException : Method not found: 'Microsoft.FSharp.Core.FSharpFunc\`2<FParsec.CharStream\`1<!!1>,FParsec.Reply\`1<!!0>> FParsec.Primitives.op_DotGreaterGreater(Microsoft.FSharp.Core.FSharpFunc\`2<FParsec.CharStream\`1<!!1>,FParsec.Reply\`1<!!0>>, Microsoft.FSharp.Core.FSharpFunc\`2<FParsec.CharStream\`1<!!1>,FParsec.Reply\`1<!!2>>)'.

This may have to do with recent changes about `FSharpFunc` (the implicit operators), and the FParsec library being compiled against an earlier version (latest is of 2017). 

This may be a regression, or an acceptable backwards compatibility issue. It may be tricky to find the exact version where this started to happen, as I've upgraded all my instances of VS already. The error certainly didn't occur in earliest versions of VS 2019 (around april 2019, I believe).

What is surprising is that this error occurred with FSharp.Core 4.3.4 loaded, where it previously didn't. This suggests this is a compiler or CLR issue instead of a really missing method.

I have tried:

* Using the 4.3.4 version of FSharp.Core
* Using the 4.6 and 4.7 version of FSharp.Core
* Made sure that bindingredirects were correct
* Checked at runtime that the proper FSharp.Core was loaded

**Repro steps**

This is part of a large project, but I will try to create a small repro that illustrates this behavior. Meanwhile I'm already posting this in case somebody comes out telling me this is expected behavior (and hopefully with a workaround).

**Expected behavior**

The `MissingMethodException` should never happen on methods that are available at compile time in one version of FSharp.Core to a newer version.

**Actual behavior**

The method is not available anymore, apparently.

**Known workarounds**

None yet. Though I will look into compiling FParsec against a newer version of FSharp.Core.

**Related information**

* Win7 / Win10 / Server 2016
* .NET 4.7 and .NET 4.6 and all versions in-between (tested)
* Visual Studio 2019 16.3.1 Professional
* FSharp.Core 4.3.4, 4.6.x, 4.7

**Comment by cartermp** [comment]
I think this is likely to do with FParsec, since we've only re-introduced the missing types and members for FSharp.Core in F# 4.7, since it now targets .NET Standard 2.0.

**Comment by abelbraaksma** [comment]
@cartermp, thanks, I did a little more research. It seems that prior to FSharp.Core moving to NuGet, and being installed as part of .NET Framework (in my case, `C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.4.0.0\FSharp.Core.dll`), it fails with the aforementioned error, regardless of whether a bindingredirect is present.

If I compile FParsec with any of the NuGet versions, i.e. 4.3.4, or 4.6 or 4.7, the error disappears. I'm not sure if 4.3.4 (having internal version 4.4.3.0) came before or after 4.4.0.0 (in the past, there was no parity in the versions, I believe).

> since we've only re-introduced the missing types and members for FSharp.Core in F# 4.7

That would suggest I would have to see the error in every version prior to F# 4.7. But if I compile everything, including the test project and FParsec, with 4.3.4, it just works (checked the runtime loaded assemblies to be sure).

It only fails when FParsec is build against the 4.4.0.0 version mentioned above.

I can understand if this is a bug that is too fringe to be fixed, if that is even possible, but I think it is worth putting it out here regardless ;). Also, it happens with other configurations, in this case, a C# project, reported here: https://stackoverflow.com/questions/56744395/getting-f-core-method-not-found-with-or-without-assembly-redirect-what-else-ca.

**Comment by cartermp** [comment]
@abelbraaksma is this issue still relevant?

**Comment by abelbraaksma** [comment]
@cartermp, the issue has been resolved in the linked issue: https://github.com/stephan-tolksdorf/fparsec/issues/47. I'll close this one out.
