### ISSUE TITLE
ServiceStructure doesn't report scopes for (*-style comments

### ISSUE THREAD

**Issue by baronfel** [dotnet/fsharp#7719]
**Is your feature request related to a problem? Please describe.**

Per https://github.com/dotnet/fsharp/blob/master/src/fsharp/service/ServiceStructure.fs#L628 (and my sample tests using the code) the structure service doesn't understand the ocaml-style (* <comment> *) code comments.

**Describe the solution you'd like**
I'd like the structure service to learn to parse these comments into scopes as well.

**Describe alternatives you've considered**
A manual second-layer of parsing over the text to find and report (* comment scopes.

**Additional context**
Here's some sample comments in VSCode, where I'm using the StructureService to report folding ranges.  You can see the little down-caret for the triple slash and double-slash comments.  None for poor, sad ol' ocaml comments.

![image](https://user-images.githubusercontent.com/573979/66597492-b48e6a80-eb64-11e9-8153-7fed22b600ea.png)

**Comment by cartermp** [comment]
Took a quick look, it'll require restructuring the existing ad-hoc parsing of the comments done to also try and fine the end comment bracket. Kinda icky,

**Comment by baronfel** [comment]
That was my take on it too. I'd like to take a pass at it, perhaps this weekend.

**Comment by kerams** [comment]
This has been completed in https://github.com/dotnet/fsharp/pull/14808.
