### ISSUE TITLE
Using line-continuation backslash causes editor to report FS0001 errors and red squigglies, or non-compilable code

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#7734]
This is an old bug, but I couldn't find the original report. Perhaps there was a moment that it was fixed, but at least for the most recent version of Visual Studio 2019 15.3.4 it still shows an error in the editor when you use `\` as line-continuation.

In files with a lot of string constants defined, this leads to next-to-impossible searching for actual errors in your code.

**Repro steps**

Just copy/paste the following in your code and you'll see the error appear:

        let s = sprintf "this is a string with \
            line continuations in \
            it causing errors in the %i editor" 42

**Expected behavior**

No error in the editor, or in the editor window. The errors reported should be equal to the errors reported by the compiler when actually compiling the solution (and admittedly, the compiler can catch more errors than the editor, but the reverse should not be true).

**Actual behavior**

Error show, like in this case:

![image](https://user-images.githubusercontent.com/16015770/66834005-27308900-ef5d-11e9-9212-68e5854c7650.png)

> FS0001	This expression was expected to have type
>    ''a -> 'b'    
> but here has type
>    'string'

Note that the error does not occur if the `%i` is in the first line. It also does not occur if it isn't a magic `printf`-style string. However, when you have defined combinators that work with `kprintf` for better readable logging statements in your code, this error becomes truly untenable.

**Known workarounds**

Ignore the error. Or use `+` (but this is not optimized for constant strings, so it isn't ideal).

Using a resource file is not an option, as the error only occurs with `printf` style strings as far as I can tell.

**Related information**

Happens on any version of F# with Visual Studio that I know of. Possibly also on other editors that use the compiler services.

This seems to me to be a problem with the lexer, but I'm guessing, of course ;)

**Comment by abelbraaksma** [comment]
@cartermp, just a ping, as in the most recent versions this is still happening (build succeeds, but for shows errors when opened).

**Comment by cartermp** [comment]
Looks like a (fun) core parser bug.

**Comment by dsyme** [comment]
Fixed in #10003
