### ISSUE TITLE
Updating to new FSharp.Core version does not update TargetFSharpCoreVersion, nor does it remove old style referencing

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#7738]
I am updating a bunch of older projects to FSharp.Core 4.7 and noticed that the `TargetFSharpCoreVersion`, which seems to be used for automatically adding binding redirects, is not updated consequentially when you use NuGet. I should probably update to the newer methods for referencing FSharp.Core, but I don't know if that would alleviate this problem.

Note also that changing the version from the dialog properties window has been greyed out for a while now. Perhaps that is by design (forcing people to use NuGet), but it is confusing and perhaps some text in that screen could help guide people.

**Repro steps**

Take any project that has an older version of FSharp.Core refernced and make sure you have `<TargetFSharpCoreVersion>` in your `fsproj` file. Update through NuGet the FSharp.Core version. 

**Expected behavior**

The `TargetFSharpCoreVersion` in the `fsproj` file should alse be updated.

**Actual behavior**

The `TargetFSharpCoreVersion` is not updated.

**Known workarounds**

The only workaround I know of is editing the `fsproj` file by hand. Possibly, the `TargetFSharpCoreVersion` is no longer necessary, but I'm reluctant to remove it as it appears to be the definitive rule on what is placed in `bindingRedirect`: if I leave the version in place, the binding redirect has the old version, which leads to assembly loading errors. If I update it, the binding redirects are correct.

**Related information**

Seen on VS 2019 16.3.1 (can't install newer because of known issues when switching configuration).

**Comment by cartermp** [comment]
@abelbraaksma How are you referencing FSharp.Core today? Since we use the NuGet package for delivery, it should just be a normal NuGet reference. It's also worth seeing how much work is involved in converting your project file over to .NET SDK-style. Then you'll never have to worry about binding redirects again.

**Comment by abelbraaksma** [comment]
I agree to the latter, but before I attempt any conversion, I like to have a working base line with all packages up to date.

I noticed that some of my projects have `TargetFSharpCoreVersion`, others don't. Perhaps it's simply not needed anymore. And maybe it was never changed by installing FSharp.Core through nuget and I just didn't notice before (I've had versioning issues before).

You are right that in the past many of these projects used older style reference (they have been maintained since F# 2.0).

**Comment by cartermp** [comment]
This shouldn't be needed anymore, yes. I believe it's an artifact of how the VS tooling used to deploy FSharp.Core on your machine (and in the GAC, and then _not_ in the GAC).

**Comment by cartermp** [comment]
Closing this out since I don't think this property is relevant anymore, at least not in something we're investing in.

**Comment by abelbraaksma** [comment]
I agree, besides, there are now other ways to override the default library.
