### ISSUE TITLE
Allow for setting of AutoGenerateBindingRedirects from the properties page, like other VS projects

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#7739]
**Problem description**
To change the `AutoGenerateBindingRedirects`, as far as I know, one can only edit the project file manually. 

**Proposed solution**
Add the setting to the Application tab of the Properties page of a project file, just like it is available for C# and F# projects, as described here: https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection

**Alternatives**
There are no alternatives other than doing it by hand.

**Comment by cartermp** [comment]
I don't think we'll add this ourselves since we've effectively frozen the legacy F# project system, but I think we'd probably accept a pull request that added the checkbox. It does requiring writing some VB.NET, though.

**Comment by abelbraaksma** [comment]
I'll have a look at it perhaps, as I think there are still enough legacy projects out there that could benefit from it.

However, for me the setting, when I set it manually doesn't seem to work. At least for NUnit it does not automatically update the config file. The only setting that seems to be honored was `TargetFSharpCoreVersion`, which changes the automatic bindings. So perhaps I'm doing something fundamentally wrong or I am expecting this setting (I mean, `AutoGenerateBindingRedirects`) to work for F# where it is only ever supposed to work for C#/VB.

**Comment by dsyme** [comment]
Closing per this comment: https://github.com/dotnet/fsharp/issues/7739#issuecomment-543280891
