### ISSUE TITLE
Can't use underscore in a type test pattern of a pattern match

### ISSUE THREAD

**Issue by bender2k14** [dotnet/fsharp#7740]
**Problem description and Actual behavior**

In this code...
```
let f (a: obj) =
  match a with
  | :? string as x -> ()
  | _ -> ()
```

...the value `x` is unused.  This gives a warning since I am using `--warnon:1182`.
> Warning FS1182 The value 'x' is unused

![Screenshot 2019-10-17 22 19 52](https://user-images.githubusercontent.com/34664007/67063457-85f82d00-f12c-11e9-94bc-b442936ed4e7.png)

A typical change to deal with this warning is to replace the identifier with `_`.  However, the resulting code...
```
let f (a: obj) =
  match a with
  | :? string as _ -> ()
  | _ -> ()
```

...doesn't compile.
> Error FS0010 Unexpected symbol '_' in pattern. Expected identifier or other token.

![Screenshot 2019-10-17 22 27 28](https://user-images.githubusercontent.com/34664007/67063744-73322800-f12d-11e9-9e38-0772123a6c95.png)

**Expected behavior**

I expected that `_` would be a valid identifier in that case; I expected that the second code sample above would compile.

**Related information**

* Operating system: Windows 10 Enterprise, version 10.0.18362 Build 18362
* .NET Runtime kind: .NET Core 3.0.100
* Editing Tools: Visual Studio Enterprise 2019, version 16.3.5

**Comment by dsyme** [comment]
I don't think this is expected, here `_` is a wildcard pattern and you can't use a full pattern in that position, just an identifier

**Comment by abelbraaksma** [comment]
> Note that the as x is (AFAIK) an optional appendix to any match in order to bind it to a value, e.g.

Us is correct, and you can have multiple such clauses inside a single pattern. It's not limited to match patterns either, for instance, they can also be used on the lh side in a let binding and are imo useful that way with deconstructing records.

**Comment by bender2k14** [comment]
Wow!  Thanks everyone for the quick and helpful replies :)

I see where I got confused.  I was only looking at the [Type Test Pattern section](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/pattern-matching#type-test-pattern) of the [Pattern Matching documentation](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/pattern-matching).  Naturally, all of the examples include `as identifier`.  Now I see that the [Remarks section](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/pattern-matching#remarks) includes syntax for each case, and the syntax for the type test pattern is `:? type [ as identifier ]`.

**Comment by abelbraaksma** [comment]
@bender2k14 I think those examples could benefit from more variety. You can suggest a documentation update at the bottom of the page.

**Comment by bender2k14** [comment]
Good idea @abelbraaksma.  I create [this issue](https://github.com/dotnet/docs/issues/15329).
