### ISSUE TITLE
Only unused parameters, but not let-bindings, are reported with --warnon:1182

### ISSUE THREAD

**Issue by xandkar** [dotnet/fsharp#7753]
Hi,

I cannot tell if this is a missing feature, a bug or PBKAC, but I am unable to get a warning for anything unused other than a parameter.

In the following example I expected to get warnings for `unusedNumberPrivate`, `unusedNumber`, `unusedFunction` and `unusedParameter`, but only got one for the `unusedParameter`, (note the empty signature file):

```sh
$ ls -1
Foo.fsproj
Program.fs
Program.fsi

$ cat Foo.fsproj
```
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RootNamespace>Foo</RootNamespace>
    <OtherFlags>$(OtherFlags) --warnon:1182</OtherFlags>
    <WarningLevel>5</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fsi" />
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
```
```sh
$ cat Program.fsi
```
```fsharp
namespace Foo
```
```sh
$ cat Program.fs
```
```fsharp
namespace Foo

module Main = begin
    let private unusedNumberPrivate =
        5

    let unusedNumber =
        2

    let unusedFunction unusedParameter =
        "UNUSED"

    [<EntryPoint>]
    let main _ =
        printfn "Hi"
        0
end
```
```sh
$ dotnet build && dotnet run
Microsoft (R) Build Engine version 16.2.32702+c4012a063 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 141.64 ms for fsharp-unused-values/Foo.fsproj.
fsharp-unused-values/Program.fs(7,24): warning FS1182: The value 'unusedParameter' is unused [fsharp-unused-values/Foo.fsproj]
  Foo -> fsharp-unused-values/bin/Debug/netcoreapp2.1/Foo.dll

Build succeeded.

fsharp-unused-values/Program.fs(7,24): warning FS1182: The value 'unusedParameter' is unused [fsharp-unused-values/Foo.fsproj]
    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.90
Hi
```

I put the reproducible example into this repo: https://github.com/khandkar/fsharp-unused-values

**Comment by abelbraaksma** [comment]
I believe this is correct behavior. The let bindings in your module are public, and therefor cannot be considered for whether they've been used or not, as they may be used in another project or module.

If you create private let bindings in a function (private by default) or private bindings in your module, I believe you'll get the warnings. Same is true for public vs private members of types, but I haven't checked if the exhaustiveness tests are done on all kinds of (private) identifiers. 

Also, unused opens will be marked (but in my recollection, they are often reported, even when you cannot safely remove the open statement).

**Comment by khandkar** [comment]
@abelbraaksma Please note 2 things:
1. The empty signature file, specifying that nothing is public;
2. `let private unusedNumberPrivate = ...`.

**Comment by dsyme** [comment]
Yes, this is by design for `--warn:1182` - it just warns on locals, not module-defined things.

I believe IDE tooling reports these?

**Comment by khandkar** [comment]
@dsyme  Ah! Understood. Would you consider adding this, if proposed as a new feature?

IME such a feature is so fundamentally useful (for both local dev and CI) that having the compiler provide it would be significantly less complex (to use) and more reliable and trustworthy than having to integrate a linter into the build cycle.

I personally do not use VS (and only very occasionally VS Code, when examining legacy code), but aside from that - the use case that is at the top of my concern is batch-processing of (a large number of) interdependent projects during/upon refactoring - the ergonomics of an IDE here are unappealing and the feedback from the compiler is far more trustworthy than from some linter (where the failure mode may just be the integration itself).

**Comment by cartermp** [comment]
Unused value and function analysis done by IDE integration uses the compiler directly, so it's not as if it's some third-party tool that incorrectly analyzes F# code.

**Comment by khandkar** [comment]
@cartermp  In the case of _not_ using an IDE, how would one access this information? Would it not require an integration layer between one's build tool and compiler services (or some such)?

**Comment by cartermp** [comment]
Yes, in this case you'd have to use the F# compiler services yourself. Though I am a bit confused about how you're applying refactorings without IDE tooling. Typically that would be viewed as a prerequisite to get richer semantic information that a batch compilation process does not normally supply.

**Comment by khandkar** [comment]
@cartermp  I use the word "refactoring" in its general meaning, not specific to any particular technology. The re-design, edit, build cycle. That said, the not-usage of an IDE is axiomatic in my inquiry :)

I just want to know whether this warning extension can be considered or if it conflicts with the design.

**Comment by abelbraaksma** [comment]
> Please note 2 things:

@khandkar, I see now, I didn't read carefully enough, thanks.

**Comment by khandkar** [comment]
@abelbraaksma No worries :)

**Comment by cartermp** [comment]
I don't think we'd extend this warning to more places outside of editor tooling.

**Comment by xandkar** [comment]
Thank you for the update, @cartermp. Could you or @dsyme say a few words to help me understand the (design) conflicts such an extension would cause?

**Comment by cartermp** [comment]
There's no way to know if something is really being used or not unless the compiler implements some kind of backtracking system to mark things as unused after the fact. This can be seen by tooling because tooling hosts an entire codebase and thus gets a different view of things. Revisiting this is a fundamental change to batch compilation, which we're not really keen on doing for the little benefit this would provide.

**Comment by xandkar** [comment]
I see. This sounds like whole-program analysis, which is not what I mean.

I'm talking about something simpler: a compilation unit ends-up with some symbols exposed/exported (either implicitly or explicitly) and anything that is not reachable from these exposed points - is "unused".

Does that make sense or am I missing something about how things work in .NET? Like, is it not really possible to truly hide things in an object (which I presume is what a "module" is compiled to)? Is everything in reality exposed, despite what the type says?

Please forgive my ignorance and thank you for being patient with me...

**Comment by abelbraaksma** [comment]
@xandkar, at least when inside Visual Studio 2019, the `private` let-binding does actually show up as unused. This is also true for a `let` or `val` inside a class. But when I build it, F# does not report it (with highest warnings setting), which backs @dsyme's observations. So I think this is a feature from tooling. I don't know why you don't have it in your editor, though.

If you want to have this warning in the build output, perhaps it is possible to include FSharpLint as part of the build, I believe it will report such issues and more.

![image](https://user-images.githubusercontent.com/16015770/71259486-dc563780-2338-11ea-957f-98790c3999db.png)

About `unusedFunction`, the empty `fsi` doesn't seem to have effect here.

**Comment by xandkar** [comment]
@abelbraaksma Including `FSharpLint` in the build chain can be a useful option, thanks! Also interesting that even _it_ doesn't care about an empty signature... :/

That said, I am not just trying to get something to work and move-on - I am very interested in understanding what this means in relation to the language design.

**Comment by cartermp** [comment]
@xandkar What you're referring to _is_ tantamount to whole program analysis.

**Comment by xandkar** [comment]
@cartermp To find unused _public_ code, one needs whole-program analysis. This is dead code elimination and is a completely different beast - it does indeed work with information which _cannot_ be known at library-compile time (i.e. knowing which public endpoints were called by the client).

Unused _private_ bindings are already visible at the same time as type-checking (at least in theory), since no more information is needed than what has been defined and what has been used. Remember: exposed = used.

This is already done for functions, so the question is: what makes doing it for modules different?

Here's an illustration of how I see it (using an ad-hoc notation):

```
Lib:
    a  // pub
    b  // pub
    _c // priv
    _d // priv
    a -> _c
    b -> _c

Prog1:
    main
    main -> Lib.a

Prog2:
    main
    main -> Lib.b
```

When compiling `Lib`, one cannot know in advance that `Prog1` will not use `b` nor that `Prog2` will not use `a`. To answer these questions - knowledge of either `Prog1` or `Prog2` is essential. These are the cases you are referring to.

However, the fact that `_d` is unused is already known when compiling `Lib`. This is the case I'm referring to.

What am I missing here?

**Comment by abelbraaksma** [comment]
Maybe it should be made into a language suggestion? Or fsharplint could perhaps be expanded?

**Comment by xandkar** [comment]
@abelbraaksma Sounds good. Will submit as a language suggestion.

**Comment by pirrmann** [comment]
Hi, I know this is a closed issue and I can understand why some binding are left out of this warning, but I was surprised to find an other situation where I don't get any warning, for a local `let` binding inside an expression, in the context of a type augmentation:
```
    type MyExistingType with
        member this.MyMethod(param1 : string) =
            use ms = new MemoryStream()
            use writer = new BinaryWriter(ms)
            [...] // no use of writer anywhere in here
            "result"
```
There was an obvious bug in my code, where I forgot to write to the writer, and the warning would definitely have spotted it... I wonder what your thoughts were on that one?

**Comment by pirrmann** [comment]
Forget it, my bad, `use` bindings are never reported as unused, probably because they're eventually going to be "used" by the `Dispose` call, and we can't know in advance whether they need to be used in any other way... I was confused because it's another case where the tooling is reporting it as unused, but I can see why there is no warning here.
