### ISSUE TITLE
Compare function with exhaustive pattern matching

### ISSUE THREAD

**Issue by citizen428** [dotnet/fsharp#7769]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but I often find myself wanting a `compare` function that's similar to the one defined in Haskell's Prelude, which returns `LT`, `EQ` or `GT` respectively. The reason I want this is that the `compare x y |> sign` workaround leads to incomplete match warnings and the `if...elif..else` construct does not feel particularly elegant.

**Describe the solution you'd like**
Something like the following:

```fsharp
type Ordering = 
    | LT 
    | EQ 
    | GT

let compare x y = 
    if x < y then LT
    elif x > y then GT
    else EQ
```

**Describe alternatives you've considered**
The most obvious alternative is doing nothing, as I'm not sure anyone else is bothered by this.

**Comment by cartermp** [comment]
@citizen428 can you please open this here? https://github.com/fsharp/fslang-suggestions

Thanks!

**Comment by abelbraaksma** [comment]
For reference, he did, it's: https://github.com/fsharp/fslang-suggestions/issues/801
