### ISSUE TITLE
Consuming C# 8.0 IAsyncEnumerable function from C#

### ISSUE THREAD

**Issue by mmc41** [dotnet/fsharp#7773]
**Is your feature request related to a problem? Please describe.**

C#8 has a new async stream feature that allows functions like this. I would like to be able to call such a C# async stream function (in a c# library) from f# 

public static async System.Collections.Generic.IAsyncEnumerable<int> GenerateSequence()
{
    for (int i = 0; i < 20; i++)
    {
        await Task.Delay(100);
        yield return i;
    }
}

**Comment by cartermp** [comment]
@mmc41 can you open this here please? Thanks! https://github.com/fsharp/fslang-suggestions
