### ISSUE TITLE
`use!` doesn't make value considered used

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#7775]
```fsharp
open System  

do
    let d = { new IDisposable with member x.Dispose() = () }  

    let x1 = d
    use x2 = d

    async { 
        use! x3 = async { return d }
        return () 
    } |> ignore

```

<img width="502" alt="Screenshot 2019-10-28 at 12 53 04" src="https://user-images.githubusercontent.com/3923587/67668889-dc156d80-f981-11e9-83ca-82c99aa12bc5.png">

**Comment by cartermp** [comment]
Interestingly, in FSAC it's reported as unused:

<img width="263" alt="image" src="https://user-images.githubusercontent.com/6309070/67778292-3238ee00-fa20-11e9-935d-0587de718adc.png">

But the compiler definitely ignores `x2`:

```
/Users/phillip/scratch/console/Program.fs(6,9): warning FS1182: The value 'x1' is unused [/Users/phillip/scratch/console/console.fsproj]
/Users/phillip/scratch/console/Program.fs(10,14): warning FS1182: The value 'x3' is unused [/Users/phillip/scratch/console/console.fsproj]
/Users/phillip/scratch/console/Program.fs(15,10): warning FS1182: The value 'argv' is unused [/Users/phillip/scratch/console/console.fsproj]
/Users/phillip/scratch/console/Program.fs(16,9): warning FS1182: The value 'x' is unused [/Users/phillip/scratch/console/console.fsproj]
    4 Warning(s)
```

@Krzysztof-Cieslak any ideas why this would report correctly in Ionide?

**Comment by auduchinok** [comment]
> @Krzysztof-Cieslak any ideas why this would report correctly in Ionide?

@cartermp Please note it's about binding in a CE, i.e. `use!` is used. It looks like a bug in Ionide/FSAC.

**Comment by cartermp** [comment]
I see, sorry. Looks I misread this as `use` and was confused about why `use!` was emphasized in your screenshot.

**Comment by TysonMN** [comment]
Worse let, the identifier in a `use!` binding cannot be the discard identifier `_`.

### With identifier `d`
![2020-11-29_20-33-16_399](https://user-images.githubusercontent.com/34664007/100562897-9e6ccd80-3282-11eb-9053-307c2baabea3.png)

```fsharp
use! d = async { return { new IDisposable with member x.Dispose() = () } }
```
> FS1182: The value is unused

### With identifier `_`
![2020-11-29_20-33-39_400](https://user-images.githubusercontent.com/34664007/100562906-a167be00-3282-11eb-80b7-dbe2dc749e2b.png)
```fsharp
use! _ = async { return { new IDisposable with member x.Dispose() = () } }
```
> FS1228: `use!` bindings must be of the form `use! <var> = <expr>`

**Comment by cmeeren** [comment]
> Worse yet, the `use!` binding cannot be the wildcard pattern `_`.

I always use `__` (double underscores). That works fine and communicates the same intent.

**Comment by TysonMN** [comment]
Nice comparison.

I just wanted to add that information to this issue.  I would not like if this issue were fixed in such a way that the identifier caused `FS1182` (the unused value warning) _and_ it was still not possible to use the discard pattern.

**Comment by dsyme** [comment]
I checked and this is now consistent in VS2022 - must have been fixed somewhere along the way 

![image](https://user-images.githubusercontent.com/7204669/161670600-8c69e9a7-4a0a-4220-9ff5-9bd8f254c193.png)
