### ISSUE TITLE
Generic functions in recursive modules typecheck errors

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/fsharp#7806]
This issue has existed in F# for as long as I've been using it, and is probably well-known:

**Repro steps**

```fsharp
module rec Program

    let f() = g<int>()
    let g<'T>() = 42
```

**Expected behavior**

Should typecheck without issue.

**Actual behavior**

The typechecker erroneously attempts to unify `'T` with `int`
```
error FS0043: The type ''T' does not match the type 'int'
```

**Known workarounds**

* Move the generic function to the top of the module
* Add an explicit type annotation to the generic function.

**Related information**

The issue has long manifested itself in `let rec ... and ...` declarations, which I have generally tolerated since it really only impacts involved parts of a codebase. However, in the context of recursive modules I'm merely looking for a way to push helper code to the bottom of a source file.

**Comment by TIHan** [comment]
I believe this is intended design.

I experimented on a fix. I hit something interesting.
Example:
```fsharp
let rec a<'T> isIt =
    if isIt then
        a<int> (not isIt)
    else
        Unchecked.defaultof<'T>
```
Cannot be compiled today.

With my experimental fix, that example started compiling. It highlighted a problem: What is the return type going to be inferred as? `int` or `'T` ?
The part where it checks: `a<int> (not isIt)` it does not know the return type until we hit `Unchecked.defaultof<'T>`, then unifies `?` and `'T` - becomes `'T`. The example should still not compile or just give a warning as `'T` is forced to be `int`, but how can you determine that if you don't unify `int` and `'T` at the call site?  As soon as the typechecker checks the last branch with `Unchecked.defaultof<'T>`, where is our information about `int` ?

Another complex example:
```fsharp
let rec a<'T> isIt =
    if isIt then
        b<int> (not isIt)
    else
        Unchecked.defaultof<'T>
and b<'T> isIt = 
    if isIt then
        a<'T> (not isIt)
    else
        Unchecked.defaultof<'T>
```

It's not impossible, but *I think* it will require either doing multiple passes to determine inference, or a change to the type system. Typechecking is single-pass, so adding multiple passes may be out of the question.

**Comment by dsyme** [comment]
This is by-design, to use the generic function before it is fully analysed you will need an explicit type annotation:

```
module rec Program

    let f() = g<int>()
    let g<'T>() : int = 42
```
