### ISSUE TITLE
FSI fails to start (now only on Nanonserver)

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/fsharp#7813]
@basvdlinden commented on [Sat Nov 02 2019](https://github.com/dotnet/dotnet-docker/issues/1433)

## Steps to reproduce the issue
1. `docker run --rm -it mcr.microsoft.com/dotnet/core/sdk:latest`
2. `dotnet fsi`

## Expected behavior
Able to use fsi

## Actual behavior
`Unhandled exception. System.PlatformNotSupportedException: The system does not support the STA thread apartment.`

## Output of `docker version`

```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:55:51 2019
  OS/Arch:          windows/amd64
  Experimental:     false```

## Output of `docker info`

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 19.03.4
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18362 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1903 (OS Build 18362.449)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.95GiB
 Name: Black
 ID: ZD6S:MG2G:LMPS:FI4Q:PGAX:PJJ2:CG5B:5YN6:RDUC:AM4E:MJC5:3MGM
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 28
  System Time: 2019-11-02T20:57:47.439352+01:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```


---

@mthalman commented on [Mon Nov 04 2019](https://github.com/dotnet/dotnet-docker/issues/1433#issuecomment-549354075)

I wonder if this is related to https://github.com/dotnet/coreclr/issues/26947.  I know that's VB but it could be the same underlying cause.

---

@MichaelSimons commented on [Mon Nov 04 2019](https://github.com/dotnet/dotnet-docker/issues/1433#issuecomment-549402007)

Setting `COREHOST_TRACE=1` indicates the failure is coming from the fsharp fsi.exe.  Moving to the fsharp repo.

A workaround would be to use a Windows Server Core based image.  The .NET Framework Docker SDK images include the .NET Core SDK and may be a suitable substitute for you - e.g. `mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-1903`

**Comment by dsyme** [comment]
THis no longer repros, it must have been fixed

**Comment by KevinRansom** [comment]
@dsyme , I thought I had fixed it, but I was going to check, thanks for taking care of it.

**Comment by MichaelSimons** [comment]
I was still able to reproduce this using 5.0.100-rc.1.20431.10.  It only appears to reproduce within a Windows container environment.  This may be Nano Server specific, I didn't try it with a Server Core image.  The original report was from a Windows container environment as indicated by the _Docker version_ info. @dsyme, were you using a Windows container environment or Linux?

**Comment by KevinRansom** [comment]
Thanks Michael, I will verify the issue still exists, and when it repros will fix it.  I don't think there is any need for the coreclr to automatically support fsi.  I imagine that the dotnet 5.0 work to support UI stacks, made the apartment threaded flags work again.

**Comment by KevinRansom** [comment]
@MichaelSimons 

Your repro now succeeds.
````
c:\kevinransom\fsharp>docker pull mcr.microsoft.com/dotnet/framework/sdk:4.8
4.8: Pulling from dotnet/framework/sdk
295f12394c4f: Pull complete
fbc68affb523: Pull complete
54909e05a1be: Pull complete
975f8c606567: Pull complete
b21585eb8358: Pull complete
bbae1d41701e: Pull complete
18ee85b10aab: Pull complete
a5328ef0a3ee: Pull complete
9e74e57e9490: Pull complete
e230f8b664e7: Pull complete
834d0e44405e: Pull complete
d2af7ce8fbb0: Pull complete
032dc9a47c57: Pull complete
06c31b7dc3f2: Pull complete
Digest: sha256:59cacbfe38ec5a7c476aa192b76b09ee1ee2091fa9392ca8dd2d16a384903472
Status: Downloaded newer image for mcr.microsoft.com/dotnet/framework/sdk:4.8
mcr.microsoft.com/dotnet/framework/sdk:4.8

c:\kevinransom\fsharp>dotnet fsi

Microsoft (R) F# Interactive version 10.10.0.0 for F# 4.7
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> #quit;;

c:\kevinransom\fsharp>
````

I will close this but I will look at the nanoserver issue.

Please re-open if you still see this issue.

Thanks

Kevin

**Comment by MichaelSimons** [comment]
@KevinRansom, for clarity, using `mcr.microsoft.com/dotnet/framework/sdk` is a .NET Framework image was not the original repo.  The original repo was using `mcr.microsoft.com/dotnet/core/sdk` which is a .NET Core image.  The difference is the .NET Core image is based on Nano Server while the .NET Framework image is based on Windows Server Core.

**Comment by basvdlinden** [comment]
I just tested the latest version of ```mcr.microsoft.com/dotnet/core/sdk``` and still see the same behavior.
