### ISSUE TITLE
fsharpc generates invalid ANSI control codes when connected to pty

### ISSUE THREAD

**Issue by Xyene** [dotnet/fsharp#7818]
**Repro steps**

Provide the steps required to reproduce the problem:

1. Run `unbuffer fsharpc --nologo | tee output` (where [`unbuffer`](http://man7.org/tlpi/code/online/dist/pty/unbuffer.c.html) is the command from `expect-dev`; any other communication over pty works too).

3. `cat output`

**Expected behavior**

The following error message appears in red text.

```
error FS0207: No inputs specified
```

**Actual behavior**

The screen is cleared, then the text appears, followed by ";1R" appearing in the prompt.

`xxd output` shows:

```
00000000: 1b5b 3f31 681b 3d1b 5b36 6e1b 5b48 1b5b  .[?1h.=.[6n.[H.[
00000010: 324a 1b5b 3931 6d0a 6572 726f 7220 4653  2J.[91m.error FS
00000020: 3032 3037 3a20 4e6f 2069 6e70 7574 7320  0207: No inputs
00000030: 7370 6563 6966 6965 640a 1b5b 3937 6d1b  specified..[97m.
00000040: 5b3f 316c 1b3e 1b5d 3130 3407            [?1l.>.]104.
```

`strace -e write` shows:

```
write(1, "\33[?1h\33=", 7^[[?1h^[=)              = 7
write(1, "\33[6n", 4^[[6n)                   = 4
write(1, "\33[H\33[2J", 7^[[H^[[2J)              = 7
write(1, "\33[91m", 5^[[91m)                  = 5
write(2, "\nerror FS0207: No inputs specifi"..., 34
error FS0207: No inputs specified) = 34
write(2, "\n", 1
)                       = 1
write(1, "\33[97m", 5^[[97m)                  = 5
write(1, "\33[?1l\33>\33]104\7", 13^[[?1l^[>^[]104^G)    = 13
```

`1b 5b36` (`.[6n]`) corresponds to the clear command. `1b5b 3f31 6c1` (`[?1l`) seems to be [`DECCKM`](https://vt100.net/docs/vt510-rm/DECCKM.html). It seems like none of these should be outputted.

This breaks integration with tools like build systems that rely on techniques like that used by `unbuffer` to get ANSI output into log files.

**Related information**

Provide any related information (optional):

* Operating system
Debian GNU/Linux 10 (buster)

* .NET Runtime kind (.NET Core, .NET Framework, Mono)
Mono

* Editing Tools (e.g. Visual Studio Version, Visual Studio)
N/A

**Comment by Xyene** [comment]
(Feel free to close this issue as it seems the root is actually in Mono, and I don't think working around it is feasible / worth it.)

**Comment by cartermp** [comment]
@Xyene does this also happen if you try `dotnet build`? That's the way to do things moving forward with .NET Core.

**Comment by Xyene** [comment]
@cartermp thanks, it looks like the .NET Core implementation of the console driver doesn't have the same issue, and works fine.

**Comment by cartermp** [comment]
Thanks for confirming it's a mono issue!
