### ISSUE TITLE
IsByRefLike structs don't work in tail recursive loops or pipe operator

### ISSUE THREAD

**Issue by Horusiath** [dotnet/fsharp#7828]
### Motivation

One of the common scenarios in programming languages is situation when we want to iterate over the elements of the collection up to a given point, when our expectation has been satisfied and we don't need to iterate any longer. In many languages (like C#) this can be easily done with foreach loop combined with break/early return.

However in F# this is not the case. To achieve that the common patter is to use recursive loop, eg.:

```fsharp
let tryFind item array =
    let rec loop item array i =
        if i >= Array.length array then -1
        elif array.[i] = item then i
        else loop item array (i+1)
    loop item array 0
```

Which will be unrolled by F# compiler into equivalent implementation with early return included.

### Problem 1

While this code works for old reference type collections, it causes a compiler problems when we talk about ref structs (like i.e. `ReadOnlySpan`). If we use example from the above and replace Array with span, what we get in the result is:

> error FS0412: A type instantiation involves a byref type. This is not permitted by the rules of Common IL.

The same happens when we want to pass it explicitly using `ReadOnlySpan<'a> inref` type parameter.

### Problem 2

Exactly the same error happens when, we try to pipe functions working over ref structs. Here I'm using a helper function:

```fsharp
let inline slice offset len (s: ReadOnlySpan<_>) = s.Slice(offset, len)

let run (s) =
    s 
    |> slice 0 10
    |> slice 0 5
```

**Comment by dsyme** [comment]
This is by design, you just have to write core code involving Span in a first order, flat way. Can you convert this to a language suggestion please? Though technically it is hard to make progress on this without considerably increasing our promises if exactly how F# will compile code, which in turn will have many edge cases and other consequences.

**Comment by Horusiath** [comment]
@dsyme I'm sorry, but I don't know, what's needed to change that into feature suggestion. 

As I guess, missing early loop escape mechanism working with ref-struct collections is not something, that happened by design. While it's possible to work around it with some flag variable gymnastics, it quite possibly comes with its own performance implications (which is the primary reason to use ref structs). 

As span API and ref-struct enumerators will (hopefully) grow in popularity, people in some areas will be missing this more and more.

**Comment by abelbraaksma** [comment]
Language suggestions can go here: https://github.com/fsharp/fslang-suggestions, I think that's what @dsyme meant.

**Comment by cartermp** [comment]
@Horusiath please file a suggestion here for recursive loops: https://github.com/fsharp/fslang-suggestions

There is a suggestion in place for handling use of functions like `|>` that are declared as inline: https://github.com/fsharp/fslang-suggestions/issues/688

The issue with Problem 2 is that the general problem is not possible to solve.

**Comment by dsyme** [comment]
> As I guess, missing early loop escape mechanism working with ref-struct collections is not something, that happened by design. While it's possible to work around it with some flag variable gymnastics, it quite possibly comes with its own performance implications (which is the primary reason to use ref structs).

Yes. It's possible this could lead us to add `break`/`continue` support, even if it's just for writing concrete, first-order loop code like this and is not entirely satisfactory, e.g. `__break` syntax etc.

**Comment by TIHan** [comment]
If we can have a feature suggestion issue soon, I can comment on this. I experimented with local functions and byref parameters last week; I have thoughts for a possible design.

**Comment by abelbraaksma** [comment]
Isn't that this one basically, where you indeed commented? https://github.com/fsharp/fslang-suggestions/issues/688

**Comment by TIHan** [comment]
@abelbraaksma that is referring to inline functions that can have their generic type parameter be a byref-like. What I was talking about, is local functions that can have byref parameter/argument:
```
let topLevel () =
    let local (p: byref<int>) = p
    let mutable x = 1
    local &x
```
