### ISSUE TITLE
[FCS] FSharpCheckFileResults.GetDeclarationLocation returns nonsensical DeclFound for external symbols

### ISSUE THREAD

**Issue by baronfel** [dotnet/fsharp#7838]
**Repro steps**

In Ionide, attempt to go-to definition on `printfn` in a script or source file.  The `FSharpCheckFileResults.GetDeclarationLocation` API returns a `DeclFound` of `/Users/chethusk/oss/scratch/F:\workspace\_work\1\s\src\fsharp\FSharp.Core\fslib-extra-pervasives.fs (229,8--229,15) IsSynthetic=false` that doesn't exist on the user's system.  You can see the build machine's file path in there, but that's not relevant here.  It also happens with libraries like Giraffe, and the net result is that we don't get the expected ExternalDecl with assembly and symbol information, which we use to decompile the DLL to a form the user can view.

This issue is documented at https://github.com/fsharp/FsAutoComplete/issues/485, and I've begun a workaround at https://github.com/fsharp/FsAutoComplete/pull/494, but it's quite hacky and it would be better to fix this at the source.

**Expected behavior**

An ExternalDecl result is returned for `printfn` which we can use to decompile the ExtraTopLevelOperators container type.

**Actual behavior**

A DeclFound is returned as detailed above, which points to a nonexistent file so the user is unable to see the implementation.

**Known workarounds**

As I've done in the mentioned PR, I've started checking for this case and manually finding the symboluse at that location, then extracting out the assembly and ExternalSymbol-like information we need to decompile.

**Comment by Krzysztof-Cieslak** [comment]
Interestingly enough `ExternalDecl` is reported correctly if the symbol comes from C# assembly. So the problem exists only for external symbols coming from F# libraries

**Comment by baronfel** [comment]
Dupe of #7918
