### ISSUE TITLE
Unable to update FSharp.Core to version 4.7.0

### ISSUE THREAD

**Issue by brianary** [dotnet/fsharp#7842]
I'm unable to explicitly add FSharp.Core as a dependency to a project, and the fixes mentioned in #7464 don't work.

**Repro steps**

1. `cd (mkdir TestLib)`
2. `dotnet new classlib -lang F#`
3. `dotnet add package FSharp.Core -v 4.7.0`

**Expected behavior**

Adding the package reference should succeed.

**Actual behavior**

```samp
  Writing C:\Users\███████\AppData\Local\Temp\tmp96AC.tmp
info : Adding PackageReference for package 'FSharp.Core' into project 'C:\temp\TestLib\TestLib.fsproj'.
info : Restoring packages for C:\temp\TestLib\TestLib.fsproj...
info : Package 'FSharp.Core' is compatible with all the specified frameworks in project 'C:\temp\TestLib\TestLib.fsproj'.
error: Error while performing Update for package 'FSharp.Core'. Cannot edit items in imported files -
error:   Item 'PackageReference' for 'FSharp.Core' in Imported file 'C:\Program Files\dotnet\sdk\3.0.100\FSharp\Microsoft.FSharp.NetSdk.props'.
```

**Related information**

* Windows 10.0.18362
* .NET Core SDK 3.0.100

My PowerShell binary module project [brianary/SelectXmlExtensions](https://github.com/brianary/SelectXmlExtensions) creates a nuget package with `dotnet pack`, but when I try to import it, it complains `Could not load file or assembly`. I can `dotnet publish`, but then I get hundreds of files included that I may not have redistribution rights to. I can't really publish my module until I can add a version to FSharp-based DLLs once 3.1 is released, though (see [dotnet/cli #12910](https://github.com/dotnet/cli/issues/12910) and [A .NET Core/Standard Versioning Odyssey](http://webcoder.info/version-odyssey.html)).

**Comment by cartermp** [comment]
FSharp.Core is referenced by default when you create an F# project. #7464 is not a fix to an issue; it's an alternative way to reference FSharp.Core if you're referencing it explicitly to support older compilers (in which case referencing 4.7.0 goes against those aims). So I don't think this is a bug, at least not on the F# compiler or tools side of things.

**Comment by brianary** [comment]
It doesn't seem to get functionally referenced, unfortunately. I'm not sure
how else to include the reference in a way that succeeds when I try to
import the module.

**Comment by abelbraaksma** [comment]
> Item 'PackageReference' for 'FSharp.Core' in Imported file 'C:\Program Files\dotnet\sdk\3.0.100\FSharp\Microsoft.FSharp.NetSdk.props'.

I think it's already there, but indirectly, through that properties file.

**Comment by brianary** [comment]
It does look that way, but that dependency is getting lost somewhere.

From [Writing PowerShell Modules in F# - Nate Lehman - Medium](https://medium.com/@natelehman/writing-powershell-modules-in-f-ed52704d97ed):

>You build the project with `dotnet build`, which will create a `MyPSModule.dll` under `src/MyPSModule/bin/Debug/netstandard2.0/`, however, importing this may not work! This is because an F# assembly needs to reference `FSharp.Core.dll` in order to work. Thankfully, `dotnet publish` will include this necessary assembly.

The problem with using `dotnet publish` is that it includes a lot more than that DLL, and also that using `dotnet pack` to generate a nupkg to publish to the PowerShellGallery uses `dotnet build` to generate the package, not `dotnet publish`.

**Comment by cartermp** [comment]
Have you tried not adding the package manually? FSharp.Core is automatically referenced in the F# targets that come with the SDK you use, which has been the case since .NET Core 2.0.

**Comment by brianary** [comment]
Yes:

1. `cd (mkdir TestLib)`
2. `dotnet new classlib -lang F#`
3. update _Library.fs_ to

    ```fsharp
    namespace TestLib
    
    open System.Management.Automation
    [<Cmdlet("Get", "Foo")>]
    type GetFooCommand () =
        inherit PSCmdlet ()
        [<Parameter>]
        member val Name : string = "" with get, set
        override x.EndProcessing () =
            x.WriteObject ("Foo is " + x.Name)
            base.EndProcessing ()
    ````
4. `dotnet build`
5. `Import-Module (Resolve-Path .\bin\Debug\netstandard2.0\TestLib.dll)`

```samp
Import-Module : Could not load file or assembly 'FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the
file specified.
At line:1 char:1
+ Import-Module (Resolve-Path .\bin\Debug\netstandard2.0\TestLib.dll)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

#### Assembly Binding Log Viewer logs

(for PowerShell 5.1, nothing seems to be captured in PS6, but the error is the same)

```log
*** Assembly Binder Log Entry  (11/12/2019 @ 09:56:44) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/WINDOWS/System32/WindowsPowerShell/v1.0/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = powershell.exe
Calling assembly : TestLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/WINDOWS/System32/WindowsPowerShell/v1.0/FSharp.Core.DLL.
LOG: Attempting download of new URL file:///C:/WINDOWS/System32/WindowsPowerShell/v1.0/FSharp.Core/FSharp.Core.DLL.
LOG: Attempting download of new URL file:///C:/WINDOWS/System32/WindowsPowerShell/v1.0/FSharp.Core.EXE.
LOG: Attempting download of new URL file:///C:/WINDOWS/System32/WindowsPowerShell/v1.0/FSharp.Core/FSharp.Core.EXE.
LOG: Attempting download of new URL file:///C:/temp/TestLib/bin/Debug/netstandard2.0/FSharp.Core.DLL.
LOG: Attempting download of new URL file:///C:/temp/TestLib/bin/Debug/netstandard2.0/FSharp.Core/FSharp.Core.DLL.
LOG: Attempting download of new URL file:///C:/temp/TestLib/bin/Debug/netstandard2.0/FSharp.Core.EXE.
LOG: Attempting download of new URL file:///C:/temp/TestLib/bin/Debug/netstandard2.0/FSharp.Core/FSharp.Core.EXE.
LOG: All probing URLs attempted and failed.
```

**Comment by cartermp** [comment]
I don't think this is an F# bug. This is an issue with writing PowerShell commandlets as per what the log was saying. We don't deploy to the GAC and we package FSharp.Core as a NuGet package (which is loaded by the .NET SDK by default).

**Comment by abelbraaksma** [comment]
From the log, it seems to me that the file is missing in the build output. You can try copying it manually, or update the `app.config`, for instance by adding a private search path. But I don't know if PS will read the config file.

**Comment by brianary** [comment]
Let me see if I can repro with a simple classlib.

**Comment by cartermp** [comment]
There's no app.config for .NET Core; `appsettings.json` and the Configuration APIs shown here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?view=aspnetcore-3.0

But I'm surprised this would be an issue, since FSharp.Core is no different to any other NuGet package with respect to this kind of problem

**Comment by brianary** [comment]
I can't seem to repro this outside a PowerShell binary, and the nuspec within the nupkg created by `dotnet pack` does seem to reference the **FSharp.Core** dependency, and I can just manually add it if I need to, and that seems to work, too. Thanks for checking.
