### ISSUE TITLE
Performance Profiler crashes on F# projects

### ISSUE THREAD

**Issue by ntwilson** [dotnet/fsharp#7846]
The Visual Studio Performance Profiler crashes on F# projects with the new project format.

I have reproduced this targeting both "netcoreapp3.0" (the default for a new project) and "net471" (the actual target I was wanting to profile)

The issue is also related to F# because in a mixed C#/F# solution, all C# projects are processed by the profiler without error, while all F# projects throw the error described below.

**Repro steps**
1. In any folder: `dotnet new console -lang f#`
2. Open the brand new fsproj file in an elevated Visual Studio window (run as admin)
3. Open the Performance Profiler
4. Select "Instrumentation" (and set the target to the startup project if not already selected)
5. Click "start" and see the error pop up:
> PRF0002: Instrumentation failed with these options: /u "<path to .dll or .exe>"   /excludesmallfuncs.  Please check the output window for additional details.

Also note in the output window it says:
> The file does not contain a recognized executable image.

**Known workarounds**

None

**Related information**

* Windows 10 Pro (10.0.18362 Build 18362)
* .NET 4.7.1 & .NET Core 3.0
* Visual Studio Professional 2019 (observed on both 16.3.9 and 16.3.5)
* Latest .NET version installed: 4.8.03752

**Comment by cartermp** [comment]
I think this might be best looked at by the profiler team - unfortunately, the VS profiler is not open source so it won't be quite as easy. Could you submit a new problem using the Visual Studio Report a Problem tool in the upper right-hand side? It should get routed to the VS profiler team. I'll keep this open in the interim.

**Comment by ntwilson** [comment]
https://developercommunity.visualstudio.com/content/problem/817363/performance-profiler-crashes-on-f-projects.html

**Comment by ntwilson** [comment]
Oh sorry I forgot this was open.  I'll close this.  You can see in the comments of the linked problem that they've fixed a bug in VS 16.5 that resolves this.
