### ISSUE TITLE
What's the story with docs, it seems that visualfsharpdocs is abandoned, but that's where MSDN takes you

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#7852]
I have to admit that recently I have been tempted to help fix documentation issues, but confusion over what documentation set should be updated and which one should be used prevents me from actively participating.

The way I understand it there's the [Visual F# Docs](https://github.com/MicrosoftDocs/visualfsharpdocs) repo and the [Dotnet Docs repo](https://github.com/dotnet/docs/). Both contain pull requests and issues, but the latter seems the more active one (the former hasn't seen any activity in 4 months).

However, when I'm reading documentation I find myself [on MSDN](https://msdn.microsoft.com/en-us/visualfsharpdocs), or on [docs.microsoft.com](https://docs.microsoft.com/en-us/dotnet/fsharp/), and sometimes the texts overlap, oftentimes the MSDN has the documentation, but the docs version has naught.

Just as an example, search for `CompiledNameAttribute` attribute on either resource, and you find [zero results on docs](https://docs.microsoft.com/en-us/search/?search=CompiledNameAttribute&scope=.NET), and [11 articles through search on MSDN](https://social.msdn.microsoft.com/Search/en-US?query=CompiledNameAttribute&pgArea=header&emptyWatermark=true&ac=4#refinementChanges=&pageNumber=1&showMore=true) (of which surprisingly _zero_ articles point to the primary MSDN source on `CompiledNameAttribute`, though it does find some hits under `visualfsharpdocs/conceptual`, which seems very, very odd).

Only way to search seems to be Duck, Google, or whatever you prefer, but not docs or MSDN, which is unfortunate.

When I suggest an edit, I have a nice summary of open issues under [each article in docs](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/symbol-and-operator-reference/), but not on MSDN, though it link goes to github, where it's quiet.

I think I read somewhere one or two years ago, that MSDN is going to move to Docs, but it feels like we're in a limbo between the two.

So, to cut to the chase: where and how should we update documentation, or should we wait? And if MSDN docs should be updated in a place for the new "docs", how can I find the corresponding link for a given MSDN article? 

As a PS, there's a disclaimer on some articles, but that isn't helping very much:

![image](https://user-images.githubusercontent.com/16015770/68726450-c7f87f80-05c1-11ea-9e38-71d21ff4f7cb.png)

And I noticed that the inverse is also true: clicking on links on MSDN can bring you to Docs and vice versa.

**Comment by cartermp** [comment]
This is being tracked here: https://github.com/dotnet/docs/issues/15779

**Comment by abelbraaksma** [comment]
@cartermp Ah, thanks, that guy seems to have exactly the same experience ;)
