### ISSUE TITLE
Selecting text in FSI in Visual Studio erases same-like text in the same window

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#7856]
This seems to be a feature: you select text and automatically elsewhere you can see the same text selected. This works well in the general F# editor of Visual Studio, but in the FSI window, it makes text unreadable.

![image](https://user-images.githubusercontent.com/16015770/68821346-5a665500-068e-11ea-84c9-eb916901d06d.png)

**Repro steps**

Just type a nice statement, up-key and alter, up-key and alter and then select a part of the text that is equal elsewhere on the screen.

**Expected behavior**

Text should remain readable.

**Actual behavior**

When selecting text, part of the screen is not readable anymore. This is more of nuisance than anything else, I don't think it is a bug per se, but just something with the default settings of the VS IDE.

**Known workarounds**

I'd love to hear them.

**Related information**

At least seen on VS 2019 Pro 16.3.1 through to 16.3.9.

**Comment by abelbraaksma** [comment]
This actually also happens in the output window, so it's probably not specific to FSI.

**Comment by cartermp** [comment]
Yeah, this is an external thing. I don't think we'd do much about it here unless we moved to a different editor for VFSI, which could make it less of a problem.

**Comment by abelbraaksma** [comment]
This only happens when you have shadow-selections on. It is possible to change the colors for these selections somewhat (for the output/fsi windows specifically, though the feature is a bit buggy). I suggest to close this out, no need to keep it hanging around until VS 2021 or what have you ;).
