### ISSUE TITLE
Enhance Result module with additional method

### ISSUE THREAD

**Issue by Wkalmar** [dotnet/fsharp#7857]
**Is your feature request related to a problem? Please describe.**
Hi. As you know, when you use `Result.bind` and your first function returns `Restult<'T, 'TError>` your second function should have input type `'T`. Recently I was playing with my pet-project and I've discovered a case when my second function doesn't care about the output of the first one but just cares about the successful fact of its execution. I haven't found a suitable method in `Result` module so I had to use nested pattern-matching.

**Describe the solution you'd like**
Eventually, I've came up with something like this
```
let bindArg binder x result = match result with Error e -> Error e | Ok _ -> binder x
```
You may also take a look at how it [allowed me to reduce nestedness of my code](https://github.com/Wkalmar/stationwalk.server/commit/b6f2e0ec082cab12b11eced8a76654530505b681#diff-51033a8f7afd0009d82ce14077ad2032)

**Describe alternatives you've considered**
In case you'll decide not to pollute standart library with this I'll be perfectly fine with your decision. Anyways I've declared module `Result` in my code too so it looks like a low-ceremony alternative to C# extension methods.

But after this encounter, I was under the impression that all this Railway-oriented thing is suitable only for a limited amount of cases so it would be good to extend this amount.

I hope you're having a good day :)
Regards,
Bohdan

**Comment by abelbraaksma** [comment]
Isn't this just the same as:

```f#
Result.bind (fun _ -> binder x) 
```

**Comment by abelbraaksma** [comment]
And looking at your code, that would be:

```f#
|> Result.bind (fun _ -> DAL.deleteRoute id) 
```

BTW, side note: it's usually better not to shadow the `id` function...

**Comment by Wkalmar** [comment]
Makes sense. Thank you
