### ISSUE TITLE
Why call EnableHeapTerminationOnCorruption twice?

### ISSUE THREAD

**Issue by zhuangzhuang** [dotnet/fsharp#7859]
Please provide a succinct description of the issue.

**Repro steps**

Provide the steps required to reproduce the problem:

`
if not runningOnMono then Lib.UnmanagedProcessExecutionOptions.EnableHeapTerminationOnCorruption() (* SDL recommendation *)
    Lib.UnmanagedProcessExecutionOptions.EnableHeapTerminationOnCorruption() (* SDL recommendation *) /// ??? call again
`
https://github.com/dotnet/fsharp/blob/master/src/fsharp/fscmain.fs#L80-L81

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

**Expected behavior**

Provide a description of the expected behavior.

**Actual behavior**

Provide a description of the actual behaviour observed. 

**Known workarounds**

Provide a description of any known workarounds.

**Related information**

Provide any related information (optional):

* Operating system
* .NET Runtime kind (.NET Core, .NET Framework, Mono)
* Editing Tools (e.g. Visual Studio Version, Visual Studio)

**Comment by forki** [comment]
related: https://github.com/dotnet/fsharp/pull/7858

**Comment by cartermp** [comment]
Seems like a bug to me. @zhuangzhuang would you be interested in submitting a pull request?

**Comment by zhuangzhuang** [comment]
@cartermp no, I just distrust it. i still learning F# .

**Comment by forki** [comment]
See #7874

**Comment by abelbraaksma** [comment]
This thread got me curious about what this setting is for. The way I understand it, historically this was needed to protect the heap when created with `HeapCreate`, by exiting a process of corruption is detected.

This may be of topic for this discussion, but putting it here anyway ;). From a post by Raymond Chen (from Microsoft), this setting is enabled for all user mode processes for major windows version 6 (Vista) and up. It cannot be switched off. See https://devblogs.microsoft.com/oldnewthing/?p=2243. 

Furthermore, it has no effect on the managed heap. 

The code only sets this when Vista or higher is used. And when CLR is lower than 3. I may misunderstand something, but it appears to be that this call is now redundant? The OS's it detects have it on by default.
