### ISSUE TITLE
unclear how to install fsharpi, fsharpc

### ISSUE THREAD

**Issue by jwaldmann** [dotnet/fsharp#7879]
Hi. Please improve documentation on configuration and installation. Of the classical "./configure; make; sudo make install", I am missing steps one  and three. 

I am building on GNU/Linux with 
```
export DOTNET_CLI_TELEMETRY_OPTOUT=1         
./build.sh -c Release 
```
After a while, it prints
```
Build succeeded
```
but I have no idea how to use the results. DEVGUIDE says
"You can then open `FSharp.sln` in your editor of choice". I don't know what this is supposed to achieve. I don't want to open a file. I want to be able to (install and then) call the compiler and  the interactive system. 
There used to be shell scripts `fsharpc` and `fsharpi` for that?

I am guessing that `fsharpi` is
```
mono artifacts/bin/fsi/Release/netcoreapp2.1/fsi.exe
```
but this fails with
```
error FS0078: Unable to find the file '/opt/mono/mono-6.4.0.198/lib/mono/4.5/netstandard.dll' in any of
 /opt/mono/mono-6.4.0.198/lib/mono/4.5
 /opt/mono/mono-6.4.0.198/lib/mono/4.5/Facades
...
```
while the file is actually present at "/opt/mono/mono-6.4.0.198/lib/mono/4.5/Facades/netstandard.dll"

**Comment by cartermp** [comment]
@jwaldmann this repo does not build the mono version of F#. If you're interested in that, the mono repo should have what you need: https://github.com/mono/mono

F# on .NET Core is invoked via `dotnet build` and `dotnet fsi`.

**Comment by jwaldmann** [comment]
Thanks!

> should have what you need ..

It should, but it does not? https://github.com/mono/mono/issues/16763#issuecomment-550497230

**Comment by cartermp** [comment]
There are some unfortunate issues with how mono builds F# that makes it difficult to update. I would recommend not using mono and instead use .NET Core. The latest released F# 4.7 is available as a download, but if you're prefer building from source I recommend this: https://docs.microsoft.com/en-us/dotnet/core/build/

FWIW I'd also highly recommend a Jupyter environment instead of "raw" FSI for interactive programming. All that takes is two steps once you have .NET Core:

```
dotnet tool install -g dotnet-try
dotnet try jupyter install
```

Then you can run F# in a Jupyter environment.

**Comment by auduchinok** [comment]
@cartermp Being able to compile a single F# file may be very valuable in some scenarios.
Something like `dotnet fsc foo.fs` or `dotnet fsharpc foo.fs` would be really great.
Should we create tools like that?

**Comment by cartermp** [comment]
I'd defer to @KevinRansom on this, the actual work isn't that much but it's not 100% clear to me what people would really use it for, since you still need to pass in references via `-r`
