### ISSUE TITLE
An error occurred while reading the F# metadata

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#7881]
While building [JetBrains/fsharp-support](https://github.com/JetBrains/fsharp-support) I've noticed the following warning:
```
/Users/eugene/Developer/resharper-fsharp/ReSharper.FSharp/test/src/FSharp.Common.Tests/unknown(1,1):
    warning FS3186: An error occurred while reading the F# metadata node at position 1 in table 'itycons' of assembly
        'JetBrains.ReSharper.Plugins.FSharp.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=333a98252ac829ae'.
    The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
    [/Users/eugene/Developer/resharper-fsharp/ReSharper.FSharp/test/src/FSharp.Common.Tests/FSharp.Common.Tests.fsproj]
```

It reproduces on both macOS and Windows with following `dotnet`
```
eugene@Eugenes-MacBook:ReSharper.FSharp$ dotnet --version
3.0.100
```

**Comment by cartermp** [comment]
@dsyme any ideas?

**Comment by auduchinok** [comment]
I've tried to look into it a bit. According to the comment inside TaskPickle.fs it's possible to print the missing entity declaration info if it's enabled in compiler:
https://github.com/dotnet/fsharp/blob/1dddfef53d5fbe4e87943ded6d09a005c2f8a366/src/fsharp/TastPickle.fs#L830-L835


So I've modified `p_osgn_ref` as following, using `1` as the index and `itycons` as the table name, i.e. values initially reported in the initial warning:
```fsharp
let p_osgn_ref (_ctxt: string) (outMap : NodeOutTable<_, _>) x st =
    let idx = outMap.Table.FindOrAdd (outMap.NodeStamp x)
    if ((idx = 1) && outMap.Name = "itycons") then
    // uncommented code from `p_osgn_ref`
```

Then I've set the compiler path to the one built with this info printing enabled via `DotnetFscCompilerPath` property and validated that the modified compiler was used.

Unfortunately, it didn't fail so it's still not clear what entity it fails on.

**Comment by marklam** [comment]
I get this happening on a clean build of [Giraffe.AzureFunctions](https://github.com/giraffe-fsharp/Giraffe.AzureFunctions) (building the [v2 changeset](https://github.com/giraffe-fsharp/Giraffe.AzureFunctions/commit/74669b0fd34b2ead97fe30a6083b9507566675cc)).
I cloned the repo, checked out that changeset and ran
```bat
dotnet tool install paket --tool-path .paket
.paket\paket install
dotnet build demo -binaryLogger
```
This produced a warning _(about an error)_
```
An error occurred while reading the F# metadata node at position 1 in table 'itycons' of assembly 'Startup, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.  \
The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
```
The .binlog file indicates the compiler was
```
C:\Program Files\dotnet\sdk\3.1.100\FSharp\fsc.exe
Microsoft (R) F# Compiler version 10.7.0.0 for F# 4.7
```
The warning **does** go away if I run build again.

If the same code is used in a Visual Studio project with warnings as errors, it (obviously) fails the first time, but doesn't go away with another build (presumably because the ``Startup`` assembly isn't rebuilt)

**Comment by dsyme** [comment]
#12195 suppresses this warning by default, as it has long proved harmless. If we get a repro where it causes a problem we will fix it
