### ISSUE TITLE
Many 'do's allowed

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#7882]
```fsharp
let c =
    let mutable c = 0
    fun () ->
        do do do do do do do do do do do do do do c <- c + 1
        c
```

The following silly code will compile and run as you'd expect it to. I'm not sure it's a bug, but it certainly is an oddity.

**Comment by voronoipotato** [comment]
Don't take away my new toy @cartermp  :P

**Comment by abelbraaksma** [comment]
Hilarious! Never thought of it, but it makes sense. `do` expects unit and returns unit. If anything, it should be by design.

**Comment by BentTranberg** [comment]
De do do do de da da da
Is all I want to say to you
De do do do de da da da
Their innocence will pull me through
De do do do de da da da
Is all I want to say to you
De do do do de da da da
They're meaningless and all that's true

(The Police - De Do Do Do, De Da Da Da)

**Comment by forki** [comment]
I think this should be closed as by design. It's similar to other languages where you can create as many nested blocks as you want.

**Comment by cartermp** [comment]
@forki Not quite. I bet there's a limit before the F# compiler crashes 🙂
