### ISSUE TITLE
FSC : error FS0226: The file extension of 'C:\Program Files\dotnet\sdk\3.0.100\FSharp\fsc.exe' is not recognized. Source files must have extension .fs, .fsi, .fsx, .fsscript, .ml or .mli.

### ISSUE THREAD

**Issue by DavidSSL** [dotnet/fsharp#7904]
I am currently unable to build my project using the[ instructions regarding SqlProvider and Postgres](https://github.com/fsprojects/SQLProvider/tree/master/tests/SqlProvider.Core.Tests/Postgres) which seem to be [out of date](https://github.com/dotnet/fsharp/issues/6326) since it was using the fsc workaround.

Here's the output of dotnet --info

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

Are there any up to date instructions on what to do in order to get SqlProvider running with Postgres on .net core/.net framework on Microsoft/Linux?

**Comment by Thorium** [comment]
https://github.com/dotnet/fsharp/issues/6326
