### ISSUE TITLE
Quotations: Expr.NewTuple missing options for struct tuples

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/fsharp#7914]
**Is your feature request related to a problem? Please describe.**

Quotations seem to be missing a way to construct struct tuples. The `Expr.NewTuple` constructor will always assume reference tuples. There is no clear workaround, except for splicing into quotation literals (e.g. `<@ struct(%x, %y) @>`), but that only really works when the types and arity are fixed.

On the other hand, the `Patterns.NewTuple` active pattern will readily recognize both struct and reference tuple constructors, however the two kinds are not distinguished unless the user performs additional reflection tests on their own.

**Describe the solution you'd like**

I propose the addition of an `Expr.NewStructTuple : Expr list -> Expr` constructor. It's a trivial addition which would require adding an `isStruct` boolean parameter to [this internal function](https://github.com/dotnet/fsharp/blob/bd667c522cb6c00ef25d698326243e7ed5c156c5/src/fsharp/FSharp.Core/quotations.fs#L746-L748).

At the same time, it would probably make sense to expose an equivalent `Patterns.NewStructTuple` active pattern. To avoid breaking changes, the `NewTuple` active pattern would still have to recognize struct tuple types.

**Comment by dsyme** [comment]
Yes, this should be added.

**Comment by eiriktsarpalis** [comment]
I'm looking at the corresponding code in `FSharp.Reflection`, and it looks like [the public API requires passing the `Assembly` instance containing the System.ValueTuple declarations](https://github.com/dotnet/fsharp/blob/613d69c58d35099c9d3a4437e4568982ac766f5d/src/fsharp/FSharp.Core/reflect.fs#L735-L739). I'm assuming this was done to address pre-netcoreapp2.0 runtimes? And if so, is there still a need to reflect a similar api shape in `Expr.NewStructTuple : Assembly * Expr list -> Expr`?

**Comment by eiriktsarpalis** [comment]
Closing since this has already been implemented.
