### ISSUE TITLE
Changing the SRTP of an inline operator in the same expression results in compile error.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/fsharp#7917]
Today, I encountered a strange compiler error while working with operators that use SRTPs. It can be best explained by the following snippet I created:

``` fsharp
type MyString = MyString of string
with
  member x.Append(s) =
    let (MyString x) = x
    x + s |> MyString
  member x.Append(d) = x.Append(sprintf "%d" d)
  member x.FinalAppend(s: string) =
    let (MyString x) = x.Append(s)
    x

type MyOtherString = MyOtherString of string
with
  member x.Append(s) =
    let (MyOtherString x) = x
    x + s |> MyOtherString
  member x.Append(d) = x.Append(sprintf "%f" d)
  member x.FinalAppend(s: string) =
    let (MyOtherString x) = x.Append(s)
    x

// This function is generic.
// It performs ms.Append(x),
// for any two values whose
// types have this member.
let inline (.>>) ms x = (^TMyString : (member Append: ^TMyOperand -> ^TMyString) (ms, x))

// These functions are _not_ generic.
let inline (=%) (ms: MyString) x = ms.FinalAppend x
let inline (=@) (ms: MyOtherString) x = ms.FinalAppend x

// These examples work.
// The type at the left of .>> is always the same.
let works1 = MyString "This" .>> " chain" .>> 6 =% " works."
let works2 = MyOtherString "Working" .>> " as" .>> 6.0 =@ " well."

// Removing the final operator
// however causes errors as soon
// as we use a type different than
// the string we were using until now...
let notworks = MyString "Doesn't" .>> " work." .>> 6
```

At the final example, we omit the `=%` operator and it should return the `MyString` object directly. However, the compiler expects the `6` to have been a string, instead of an int.

At the first example, the `=%` operator at the end makes sure that the left operand is a `MyString`, the right operand is a string, and the result is a string as well.

The question is: __Didn't the compiler already know that already?__ Let's take a look at his deductive process:

* `MyString "Doesn't"` is surely of type `MyString`.
* `MyString "Doesn't" .>> " work"` must be a `MyString`, from the definition of `.>>`.
* `MyString "Doesn't" .>> " work." .>> 6`, is again a `MyString`. The final `.>>` should resolve to `MyString.Append(int)`, but our compiler falsely resolves it to `MyString.Append(string)` instead.

Using `.>>` like that does not seem to be prohibited; it works above, when we used the `=%` operator, _and made the compiler feel safe that he was dealing with an object of type `MyString`_.

I made a couple of theories about this bug:

* In `^TMyString : (member Append: ^TMyOperand -> ^TMyString)`, don't these `^TMyString`s refer to the same type? Doesn't that guarantee that the method's return type is the same with the type the method resides?

* `let x = MyString "Doesn't" .>> " work" in x .>> 6` works, which led me to wonder if the compiler mistakenly believes that `.>>`'s `^TMyOperand` must remain the same in the entire `let` block. But this does does not hold, since there is no problem when we added `=%`.

**Comment by dsyme** [comment]
I've added this to #6805 to inviestigate as part of that feature branch work.

**Comment by dsyme** [comment]
I've looked at this and while the behaviour is odd, it is by design as things stand.

A type parameter can't generally be constrained by more than one instance of a particular trait.  In the above examples, the input `^TMyString` gets constrained by both an integer and string version of the constraint. These are reduced to one constraint.

This is done to ensure much simpler error messages in the common cases where SRTP is used.  It's similar to the way F# reports an error for `'T :> seq<int>` and `'T :> seq<string>` - this simplifies type inference in common coding patterns and improves error messages though also restricts code that can be written

**Comment by teo-tsirpanis** [comment]
Thanks for your feedback @dsyme, I found a solution to this. Instead of SRTP operators, I can write slightly more code and define each operator overload on each type. My problem can be solved this way. The working example is the following:

``` fsharp
type MyString = MyString of string
with
  member x.Append(s) =
    let (MyString x) = x
    x + s |> MyString
  member x.Append(d) = x.Append(sprintf "%d" d)
  member x.FinalAppend(s: string) =
    let (MyString x) = x.Append(s)
    x
  static member (.>>) (x: MyString, y: string) = x.Append y
  static member (.>>) (x: MyString, y: int) = x.Append y

type MyOtherString = MyOtherString of string
with
  member x.Append(s) =
    let (MyOtherString x) = x
    x + s |> MyOtherString
  member x.Append(d) = x.Append(sprintf "%f" d)
  member x.FinalAppend(s: string) =
    let (MyOtherString x) = x.Append(s)
    x
  static member (.>>) (x: MyOtherString, y: string) = x.Append y
  static member (.>>) (x: MyOtherString, y: double) = x.Append y

// These functions are _not_ generic.
let inline (=%) (ms: MyString) x = ms.FinalAppend x
let inline (=@) (ms: MyOtherString) x = ms.FinalAppend x

// These examples work.
// The type at the left of .>> is always the same.
let works1 = MyString "This" .>> " chain" .>> 6 =% " works."
let works2 = MyOtherString "Working" .>> " as" .>> 6.0 =@ " well."
let nowWorksToo = MyString "Doesn't" .>> " work." .>> 6
```
