### ISSUE TITLE
Spurious assert when running debug compiler

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#7932]
Compiling the following code using the debug compiler raises an assert on [this line](https://github.com/dotnet/fsharp/blob/master/src/fsharp/IlxGen.fs#L5092)
```fsharp
let f (x: obj) = 
            if not (isNull x) then
                ()
```

I believe the assertion is spurious as the generated code is ok.

Repro with `artifacts\bin\fsc\Debug\net472\fsc.exe code.fs`.  Note optimizations must be on

**Comment by cartermp** [comment]
What is `code.fs`?

**Comment by cartermp** [comment]
Closing as there isn't much info here and the referenced line is whitespace
