### ISSUE TITLE
FSharp.Compiler.Interactive.Settings seemingly not part of script references

### ISSUE THREAD

**Issue by baronfel** [dotnet/fsharp#7950]
@kevmal on the F# foundation slack shared an image of a typecheck error he had in a fsx script. He's on 2019 16.4, and after looking at the `DotNetFrameworkDependencies.fs` file I think I see what the problem is.

![image (1)](https://user-images.githubusercontent.com/573979/70571086-bf647c00-1b62-11ea-958b-d336b9863dfb.png)

I believe the issue comes from [here](https://github.com/dotnet/fsharp/blob/e7597deb7042710a7142bdccabd6f92b0840d354/src/fsharp/DotNetFrameworkDependencies.fs#L233), where the string "FSharp.Compiler.Interactive.Settings" is passed as one of the dependencies to be resolved by `getDependenciesOf`.  `getDependenciesOf` has some handling for 'simple names', that is assembly names that are not full file paths: it prepends the framework directory to the simple name and attempts to resolve that reference.

In this case I think this logic is incorrect, because the "FSharp.Compiler.Interactive.Settings" reference is colocated with the compiler, not with the rest of the framework references. I think that in this case, the assembly should be manually resolved by joining the simple name with the already-defined `getFSharpCompilerLocation` path, which should be correct.

**Repro steps**

1. Create an fsx script in VS 2019 16.4
2. use any member of the `fsi` binding.

**Expected behavior**

The fsi binding's members are available in-editor.

**Actual behavior**

The fsi binding's members are not available.

**Known workarounds**

The user can always provide an explicit #r reference to the dll, but this is non-portable.

**Related information**

Provide any related information (optional):

* Operating system: Windows
* .NET Runtime kind: .NET Core 3.x
* Editing Tools: Visual Studio 2019 16.4

**Comment by dsyme** [comment]
As far as I can tell this is a regression in Visual Studio 16.4.1

**Comment by dsyme** [comment]
Script files are now missing implicit references to `FSharp.Compiler.Interactive.Settings.dll` when editing.  It also seems impossible to workaround this by adding `#r “FSharp.Compiler.Interactive.Settings”`

**Comment by dsyme** [comment]
so this is definitely covered by the language service testing, what's happened....

https://github.com/dotnet/fsharp/blob/4363f4cfdb060d63da23be9e216a1124eef449f9/vsintegration/tests/UnitTests/LegacyLanguageService/Tests.LanguageService.Script.fs#L1162

https://github.com/dotnet/fsharp/blob/4363f4cfdb060d63da23be9e216a1124eef449f9/vsintegration/tests/UnitTests/LegacyLanguageService/Tests.LanguageService.Script.fs#L1179

https://github.com/dotnet/fsharp/blob/4363f4cfdb060d63da23be9e216a1124eef449f9/vsintegration/tests/UnitTests/LegacyLanguageService/Tests.LanguageService.Script.fs#L1203

**Comment by dsyme** [comment]
You can workaround this to some extent by the following (adjust the path as necessary)

```fsharp
#if EDITING
#r @"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp\FSharp.COmpiler.Interactive.Settings.dll"
#endif
```

The good thing about this workaround is that it doesn't affect the execution of scripts, though the hard coded path is obviously problematic for editing across teams.
