### ISSUE TITLE
TcSymbolUseData array LOH allocations

### ISSUE THREAD

**Issue by TIHan** [dotnet/fsharp#7983]
![Untitled](https://user-images.githubusercontent.com/1278959/70891826-e379f000-1f9c-11ea-94d7-b205e55ba917.png)
Seems we still have some issues with TcSymbolUseData array, might be an easy fix.

**Comment by cartermp** [comment]
Interesting. @baronfel implemented the chunking here: https://github.com/dotnet/fsharp/blob/master/src/absil/illib.fs#L439-L479

Should the chunk size be decreased? It's below 85k.
