### ISSUE TITLE
TcSymbolUseData copying 

### ISSUE THREAD

**Issue by TIHan** [dotnet/fsharp#7997]
`TcSymbolUseData` is a large struct, 36 bytes in 64-bit! The rule of thumb for a struct is no larger than 16 bytes.

We get a lot of them when type checking files in the IDE. They are stored in a collection and sometimes we do operations on the collection. Because it's a value type, it's getting copied over and over again with these operations.

I can't say how much this is affecting performance, but it's a concern as we should not have a struct that large without being super careful with it.

I don't know a solution to this as it would be heavily involved.

**Comment by dsyme** [comment]
Closing as it's not directly actionable.
