### ISSUE TITLE
Product version in Visual Studio incorrectly says F# 4.6, not F# 4.7

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#8018]
From 16.5 previews:

![image](https://user-images.githubusercontent.com/6309070/71112250-f0a30480-217f-11ea-8202-34d445c08970.png)

From 16.4:

![image](https://user-images.githubusercontent.com/6309070/71112281-031d3e00-2180-11ea-8ddf-77de274e47fc.png)

**Comment by abelbraaksma** [comment]
I know, I reported it some time ago, let me see if I can find it back ;)

**Comment by abelbraaksma** [comment]
@cartermp, found it, it's probably from the same InformationalAssemblyVersion: https://github.com/dotnet/fsharp/issues/7726

**Comment by abelbraaksma** [comment]
Considering your comment in the other thread, with 'incorrect', you weren't referring to the presence of 'beta' in the string?

**Comment by cartermp** [comment]
The `beta` is expected. The issue is that the tools state it's for F# 4.6, but the compiler is for F# 4.7.
