### ISSUE TITLE
Values captured in closures are sometimes broader than necessary

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/fsharp#8034]
When creating a lambda that accesses the members of an object, its compiled closure code sometimes captures the object itself, instead of its members, even when the object's mention is not apparent in the F# code. This can lead to memory leaks, when the object in question also holds other objects that are no longer used, but remained captured by a function that will never use them.

Let's take a look at the following code:

``` fsharp
open System

type MyClass(smallObject, bigObject) =
  // This object is supposed to be very simple and small in size.
  member __.SmallObject = smallObject
  // This object is supposed to be large and hold a complex graph of objects.
  member __.BigObject = bigObject
  member this.CreateSmallObjectPrintAction() = (fun () -> printf "%O" smallObject)
    
type MyRecord = {SmallObject: obj; BigObject: obj}
with
  member this.CreateSmallObjectPrintAction() = (fun () -> printf "%O" this.SmallObject)

// We use a .NET delegate to avoid optimization into a two-parameter function.
let createPrintAction mr = new Action(fun () -> printfn "%O" mr.SmallObject)

let createPrintAction2 {SmallObject = so} = new Action(fun () -> printfn "%O" so)
```

We have four functions that capture the small object of a `MyClass` (or `MyRecord)`.

* The first one is defined within `MyClass`, and directly references the `smallObject` constructor argument. However, the compiled code for the closure references the entire object, despite the `this` variable is not referenced.
* The second one is defined within an equivalent record type and references `this` object, just to access its small object. The entire record is held again, which I kind of understand, since we explicitly mention it in the code.
* The third one is defined in a function outside of any object. It is equivalent to the second function, and the closure performed is similar for the same reasons.
* The fourth function however, is like the third one, but uses an inline match over the `MyRecord` parameter. This time, _only the small object_ is kept inside the closure, and the record itself can be freed from memory if not referenced anywhere else.

My proposal is to make the first function reference only the constructor parameter that uses. The next two cases is easier to understand, but should have been optimized as well.

As a workaround, we can load the values we need to local variables, and not directly (or indirectly) reference the holding object.

**Comment by Frassle** [comment]
> The first one is defined within MyClass, and directly references the smallObject constructor argument. However, the compiled code for the closure references the entire object, despite the this variable is not referenced.

`this` is implicitly reference though. I guess this would still be a safe optimization to make as long as `smallObject` wasn't mutable. But then that could apply to the second and third case as well (it's a record property and the compiler knows that's immutable)

**Comment by dsyme** [comment]
This is by design.  If you want only the smaller object captured you should do as you have done.

The current behaviour of capturing the free variables (rather than the values extracted from them by the closure code) is simple and practical, and easy to predict and tune.
