### ISSUE TITLE
Overly strict limitations for nominally equivalent static and instance methods 

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/fsharp#8092]
Error: The method 'Foo' has curried arguments but has the same name as another method in type 'Bar'. Methods with curried arguments cannot be overloaded. Consider using a method taking tupled arguments.

```fs
type Bar = 
   member _.Foo x y = x + y // err
   static member Foo x y = x + y // err
```

Changing one of the methods to be tupled only drops one error
```fs
type Bar = 
   member _.Foo(x, y) = x + y 
   static member Foo x y = x + y // err
```
At a minimum if this check is to stay the error message could use a tweak to include static and instance members are both considered curried overloading (maybe just add that if the error surfaces as a result of involvement of >1 instance method and >1 static method)

Mostly I'm wondering why this check is being done over both static and instance members, they are never considered together during resolution as far as I know (static Bar vs instance variable access)?

**Comment by abelbraaksma** [comment]
Not really related, but your type omits `()`, which means it cannot be instantiated, which in turn means it would be impossible to ever call the instance method.

But i assume your bug report applies equally to instantiable types (and I agree, the overload check seems redundant between instance and type members).

**Comment by charlesroddie** [comment]
> Mostly I'm wondering why this check is being done over both static and instance members, they are never considered together during resolution as far as I know (static Bar vs instance variable access)?

> Guillaume Sasdy's answer [here](https://stackoverflow.com/questions/59609673/why-instance-methods-cant-be-called-as-static-methods):
> "But note that in C# a class can't have a static and an instance method with the same signature."
