### ISSUE TITLE
Shouldn't a constructorless type have a private/internal constructor in IL

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/fsharp#8093]
Shouldn't a constructorless type have a private/internal constructor in IL?

Looking at these two types in sharplab https://sharplab.io/#v2:DYLgZgzgNAJiDUAfALgTwA4FMAEAxA9vgIzYC8AsAFDY3YTICGyAlgMbYC2mHARpgE7ZmMbAA8yYqlTRY8hAEzZ0/ZgDcmOABQBKMlVp1GLdl14ChI8aTFA=

```
type Foo1 =
    static member id x = x

type Foo2 private () =
    static member id x = x
```

Foo1 can't be constructed in F# similar to Foo2 but only Foo2 has an internal constructor in IL, leaving Foo1 to be constructed from C# without issue, is this by design?

**Comment by abelbraaksma** [comment]
Somewhat surprisingly, I couldn't find this mentioned in the [documentation on constructors](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/members/constructors) or [classes](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/classes).

However, this behavior has been like this for as long as I can remember, and you aren't the first to be surprised by it.

As a rule of thumb, I use the following rules:

* If you need a non-static class that cannot be instantiated, use private or internal constructors
* If you need a static class (technically, the CLR does not have that notion, it is a class without instance members, abstract and sealed), mark the class `[<AbstractClass; Sealed>]`. This is used for interop with C#, which will then recognize it as static. The documentation again [doesn't seem to mention](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/core.abstractclassattribute-class-%5bfsharp%5d) this (nor [here](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/core.sealedattribute-class-%5bfsharp%5d)), though it follows from both definitions.
* if you're not interop'ing, you can stick with omitting the `()` from the definition (as you showed).

None of these options will disallow creating instance members, which is a little odd, as you won't have any way (that I know of) of calling an instance member (unless through reflection):

![image](https://user-images.githubusercontent.com/16015770/71782554-9ad1b780-2fdb-11ea-96d5-cc5febc55525.png)

**Comment by abelbraaksma** [comment]
> as you won't have any way (that I know of) of calling an instance member

Interestingly, you can inherit from an F# class that has no constructors, but you won't be able to add additional constructors to the inheriting class, as each requires either a call to the superclass's constructor, or it should initialize all its own fields *and* call the superclass's constructor (implicitly or explicitly).

You can fool the compiler, but no need to say that this will blow up very quickly ;)

```f#
type TestMe =
    member _.Foo() = 1
        

type InheritTest =
    inherit TestMe
    new () = InheritTest()   // oh oh!...

    static member callFoo() = (new InheritTest()).Foo()  // yay! managed to call an instance member!
```

**Comment by cartermp** [comment]
Yeah I think a constructor should be emitted. @dsyme maybe has more detail here

**Comment by dsyme** [comment]
I suppose it should, yes

**Comment by abelbraaksma** [comment]
Do note that the F# Spec specifically says that if the default constructors are omitted that default constructors are not created. So technically this seems to me to be a change to the spec.

If I understand the issue at hand correctly, the absence of a default ctor allows C# to create an instance. But adding a default (private) ctor, while fixing the C# issue, will allow creating instances in F#, wouldn't it (though only in private scope)?

**Comment by dsyme** [comment]
I do think that we should take this to fslang-suggestions given 

1. this is called out explicitly in the spec

2. could be a breaking change to reflection code (e.g. code that gets the first result of GetConstructors)

**Comment by dsyme** [comment]
Now a language suggestion at https://github.com/fsharp/fslang-suggestions/issues/906
