### ISSUE TITLE
Run a 3.1 F# project via CLI, restore failed with error : '{{FSharpCoreShippedPackageVersion}}' is not a valid version string.

### ISSUE THREAD

**Issue by yunwei00q** [dotnet/fsharp#8192]
Affected Branch: rel/d16.5
Affected Build:  D16.5/29713.99 (16.5.0 preview 2.0)

**Steps to Reproduce:**

1. Create a .net core 3.1 F# project via CLI

**Expected:**
Restore and build successfully.

**Actual:**
Restore failed with error: '{{FSharpCoreShippedPackageVersion}}' is not a valid version string.
![image](https://user-images.githubusercontent.com/57380211/72325130-6cdd2900-36e7-11ea-86ab-68127b0d8c12.png)

Note: 
1. Create a .net core 3.1 f# project via VS, it can work well.
2. Only install SDK: [3.1.200-preview-014879](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/3.1.2xx/dotnet-sdk-latest-win-x64.exe), it can repro.

Dotnet --info:

.NET Core SDK (reflecting any global.json):
 Version:   3.1.200-preview-014879
 Commit:    c373605d3f
 
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200-preview-014879\
 
Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db
 
.NET Core SDKs installed:
  3.1.200-preview-014879 [C:\Program Files\dotnet\sdk]
 
.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
 
To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by cartermp** [comment]
cc @KevinRansom

**Comment by brettfo** [comment]
Thanks for reporting this!  We had some complicated merges and we missed some string replacements.  #8207 fixes the issue and the artifact flow is set up such that as soon as that PR is merged and built it'll create an update to the 3.1.2xx toolset.

**Comment by cartermp** [comment]
@brettfo this is now merged and in

**Comment by cartermp** [comment]
Closing this out since it is good on our end
