### ISSUE TITLE
FSI: cannot reference native dependencies on Linux 

### ISSUE THREAD

**Issue by mathias-brandewinder** [dotnet/fsharp#8236]
In FSI, when using a library that depends on a native library, on Windows the native resource needs to be added to the path to be discovered, along these lines:

https://github.com/mathias-brandewinder/mldotnet-fsi/blob/master/script.fsx#L20-L37

Trying to do the same thing on Linux, adding the Linux specific directories to `LD_LIBRARY_PATH`, does not seem to work. As a result, running an F# script that depends on native libraries seems to work only on Windows.

Assuming this worked, another issue then would be to make such a script cross platform, because it would need to detect what OS is used to run it to handle dependencies properly.

**Repro steps**

The following repo has an example using ML.NET, which works on Windows, but which I could not get to work on Ubuntu:
https://github.com/mathias-brandewinder/mldotnet-fsi/blob/master/script.fsx

**Expected behavior**

By replacing the Windows-specific native dependencies with the equivalent Linux path, we should be able to run the script on another OS:
https://github.com/mathias-brandewinder/mldotnet-fsi/issues/1

**Actual behavior**

Cannot figure out how to get this script to run on Ubuntu.

**Known workarounds**

Work in a console application, where the resolution works.

**Related information**

Provide any related information (optional):

* Windows 10, Ubuntu 18.04
* .NET Core 3.1
* VS Code + Ionide

**Comment by cartermp** [comment]
TBH I'm not sure if we'll fix this as-written. here's a script that does execute on Ubuntu here: 

```fsharp
#r "nuget:Microsoft.ML"
#r "nuget:Microsoft.ML.FastTree"

open System
open System.IO

open Microsoft.ML
open Microsoft.ML.Data

// native libraries
// let path = Environment.GetEnvironmentVariable("PATH")

// let nativeDllsPaths = 
//     [
//         "Microsoft.ML/runtimes/win-x64/native"
//         "Microsoft.ML.CpuMath/runtimes/win-x64/nativeassets/netstandard2.0"
//         "Microsoft.ML.FastTree/runtimes/win-x64/native"
//     ]
//     |> List.map (fun subPath -> 
//         Path.Combine(__SOURCE_DIRECTORY__, "packages", subPath)
//         |> Path.GetFullPath
//         )

// path :: nativeDllsPaths
// |> String.concat ";"
// |> fun expandedPathReferences -> 
//     Environment.SetEnvironmentVariable("PATH", expandedPathReferences)

type WineDescription = {
    [<LoadColumn(0)>]
    Sulphates: float32
    [<LoadColumn(1)>]
    Alcohol: float32
    [<LoadColumn(2)>]
    Quality: float32 
    }

let context = MLContext (seed = Nullable 0)

let dataPath = 
    Path.Combine (__SOURCE_DIRECTORY__, "dataset.csv")

let dataView = 
    context.Data.LoadFromTextFile<WineDescription>(
        path = dataPath,
        hasHeader = true,
        separatorChar = ','
        )

let testTrain = 
    context.Data.TrainTestSplit(
        data = dataView, 
        testFraction = 0.5, 
        seed = Nullable 0
        )

let train = testTrain.TrainSet
let test = testTrain.TestSet

let dataProcessPipeline =
    EstimatorChain()
        .Append(context.Transforms.CopyColumns("Label", "Quality"))
        .Append(
            context.Transforms.Concatenate(
                "Features",
                "Sulphates", 
                "Alcohol"
                )
            )

let trainer = 
    context.Regression.Trainers.FastForest(
        labelColumnName = "Label", 
        featureColumnName = "Features"
        )

let modelBuilder = dataProcessPipeline.Append trainer
let trainedModel = modelBuilder.Fit train

let trainEvaluation = 
    let predictions = trainedModel.Transform train
    context.Regression.Evaluate(predictions, "Label", "Score")

printfn "MAE: %f" trainEvaluation.MeanAbsoluteError
printfn "MSE: %f" trainEvaluation.MeanSquaredError

let testEvaluation = 
    let predictions = trainedModel.Transform test
    context.Regression.Evaluate(predictions, "Label", "Score")

printfn "MAE: %f" testEvaluation.MeanAbsoluteError
printfn "MSE: %f" testEvaluation.MeanSquaredError
```

This can be verified in the Binder link here, which runs on an Ubuntu container: https://mybinder.org/v2/gh/dotnet/try/master?urlpath=lab

That is to say, `#r "nuget:..." seems to solve this problem entirely and will be the preferred way to specify dependencies from here on out. When the .NET 5 previews come out it will be available.

**Comment by cartermp** [comment]
Though I think @KevinRansom should chime in here to see if it's possible to do this with the "old way" to reference third-party libs

**Comment by mathias-brandewinder** [comment]
The "new way" definitely looks better :)
So if I understand correctly, unless there is a trick/workaround, the resolution is to wait for .NET 5 then?

**Comment by KevinRansom** [comment]
In the new codebase:
````
    #I "some directory containing native dependencies"
````
and we'll probe for it, platform specific, and we support the alias mechanisms that [<DllImport>] supports.

With the current codebase set the path environment variable to the directory and it should work.  However, no platform dependent probing occurs.  I suspect you can do it programatically, but I haven't tried it.

#r nuget generates a #I for the package root for packages that carry native dependencies, and so works pretty decently.

The next release Dev16.5 does not containing the new codebase however, Dev 16.6 and it's previews will. the new #I behavior should not require the langversion:preview switch I think.  #r nuget however, will.

**Comment by cartermp** [comment]
This one is now resolved in the latest .NET 5 preview.
