### ISSUE TITLE
Compiler generates instance method while creating Action from static member

### ISSUE THREAD

**Issue by gsomix** [dotnet/fsharp#8295]
Consider following code:
```fsharp
open System
type C =
    static member M() = ()
    static member CreateAction() =
        new Action(C.M)
```

Compiler generates a closure object for `C.M` reference and changes static member in `Action` for instanced one. Please see decompiled C# code:
```csharp
public static class _
{
    public class C
    {
        public static void M()
        {
        }

        public static Action CreateAction()
        {
            return new Action(new CreateAction@5().Invoke);
        }
    }

    internal sealed class CreateAction@5
    {
        internal void Invoke()
        {
        }
    }
}
```

While it doesn't capture anything generated code could use reference to static member itself. It is not clear if such behavior has any performance impact but it may affect use of .NET libraries. 

E.g. [ILGPU](http://www.ilgpu.net/) requires static methods for describing computational kernels and compiles it to GPU code via `Action` delegates. Please [see example](https://github.com/m4rs-mt/ILGPU.Samples/blob/master/Src/SimpleKernel/Program.cs#L66-L67).

**Comment by NatElkins** [comment]
More context for ILGPU here: 

https://github.com/m4rs-mt/ILGPU.Samples/issues/7
https://github.com/NatElkins/Scratchpad/pull/1

**Comment by cartermp** [comment]
@dsyme any thoughts on this?

**Comment by dsyme** [comment]
I'm sure this can be fixed.

**Comment by gsomix** [comment]
@cartermp Could you please add labels to the issue? I'm afraid that it might get lost from sight. Thanks!

**Comment by cartermp** [comment]
You betcha

**Comment by abelbraaksma** [comment]
@gsomix, @MoFtZ, your example is a void function returning void. Is the issue specific to that, or is it related to any number of arguments (but still returning void)?

And is the issue the same (does it also create an instance method reference as opposed to static) when creating a `delegate` type in F# from a void-returning function? It would be great if a fix covers both cases.

**Comment by gsomix** [comment]
@abelbraaksma [Yes, it's same](https://sharplab.io/#v2:DYLgZgzgPg9gDgUwHYAIDKBPCAXBBbAWAChjsNEUBZDAQQGNsBLGJAJhQF4UATBYBAOYBDXChhgUjJNhQBaAHwoArkkbZS5BFVoNmSAMycefQSK3iUACikyAVJOkBKOYpVriGigGFOxFP5QcEUY6FDx8ACMEACcqVksADxAHbGcuS0c/AKCmUPC8KNjKfUTkmwAaFAwypyMMrP8GwOxgvMiYlC9ohDN6JhZ4tKaAlCQEAHcUPr0AHht5Sy8AOkpWTKIRppyQsPbYrp7caZYSoY2RgLHJ46Q56Ur5yzAVFASql06VkoTyjEd1i4BLYtXK7AodA5mag3Qa+c6Aq7aGGLFZrYZA+HNVpgwqdbpQnT9AwZOGA/yI6G6E4o4qOIA=). Note also it's not possible to create `Action<T1', T2'>` without involving lambda function.

**Comment by TIHan** [comment]
> Note also it's not possible to create multi-arguments delegate without involving lambda function.

Yea, that is kinda of unfortunate. You would think it could be tupled: `(x, y)` because of the signature `int * int -> unit` - I remember @KevinRansom and I looked at this before and it does feel a little confusing.

**Comment by gsomix** [comment]
Thank you! [It works fine](https://github.com/gsomix/ilgpu-fsharp-sample).
