### ISSUE TITLE
No syntax error for primary constructor in delegate definition

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#8299]
No error is reported for the following code:
```fsharp
type T(x: int) =
    delegate of int -> int
```

When sending this code to fsi, an error is produced:
```
error FS0193: internal error: Illegal definition for runtime implemented delegate method.
```

**Comment by dsyme** [comment]
@auduchinok Thanks for the good catch, this should of course give an error.

**Comment by edgarfgp** [comment]
@vzarytovskii  I been looking into adding a unit test for this and I came up with this .

```fsharp
    [<Fact>]
    let ``Illegal definition for runtime implemented delegate method.`` () =
        FSharp """
namespace FSharpTest
    type T(x: int) =
        delegate of int -> int
"""
        |> compile
        |> shouldFail
        |> withErrorCode 193
        |> withErrorMessage "Illegal definition for runtime implemented delegate method."
```

Questions : 
 - Is this a valid test 
 - Were should this be inside of the ComponentsTests
 

Thanks in advance

**Comment by vzarytovskii** [comment]
> @vzarytovskii I been looking into adding a unit test for this and I came up with this .
> 
> ```fsharp
>     [<Fact>]
>     let ``Illegal definition for runtime implemented delegate method.`` () =
>         FSharp """
> namespace FSharpTest
>     type T(x: int) =
>         delegate of int -> int
> """
>         |> compile
>         |> shouldFail
>         |> withErrorCode 193
>         |> withErrorMessage "Illegal definition for runtime implemented delegate method."
> ```
> 
> Questions :
> 
> * Is this a valid test
> * Were should this be inside of the ComponentsTests
> 
> Thanks in advance

Yep, test looks fine to me, you can put the test to somewhere in the `Conformance` (https://github.com/dotnet/fsharp/tree/main/tests/FSharp.Compiler.ComponentTests/Conformance), either create a new directory or use existing, how you see fit :)
