### ISSUE TITLE
Intrinsic type extension is allowed to mismatch type parameters count

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#8300]
```fsharp
type A<'T1, 'T2> = class end
type A<'T1, 'T2, 'T3> = class end

type A<'T1> with member x.Foo = 123

```
In the code above the last definition is preferred:
<img width="774" alt="Screenshot 2020-01-21 at 17 29 41" src="https://user-images.githubusercontent.com/3923587/72813069-c6a79b00-3c73-11ea-9b52-bcd8d00ecfc1.png">

F# 4.1 spec doesn't say anything about this situation.

**Comment by dsyme** [comment]
We should resolve this by simply raising an error when there is a type parameter count mismatch after the resolution chooses the second type. As in https://github.com/dotnet/fsharp/pull/12938
