### ISSUE TITLE
suggestion for improving CI: report [current/total] or % during test run

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#8321]
I noticed nice improvements on the test output running tests from console or on the CI.

Can the test output also carry the [current/total] on each line indicating test outcome:

![image](https://user-images.githubusercontent.com/87944/72936992-955cc700-3d68-11ea-9dd4-72a4954e52ba.png)

This should be possible as before running, there is a summary of the total tests to run being printed.

cc @brettfo

**Comment by cartermp** [comment]
Since we're moving to standardized test frameworks I think we'll not try to do something bespoke on top of them like this.
