### ISSUE TITLE
Incorrect usage path when used via dotnet command

### ISSUE THREAD

**Issue by drguildo** [dotnet/fsharp#8350]
`#help` says `See 'dotnet --help' for options` which should probably be `See 'dotnet fsi --help' for options`.

`dotnet fsi --help` says `Usage: dotnet <options> [script.fsx [<arguments>]]` which should probably be `Usage: dotnet fsi <options> [script.fsx [<arguments>]]`.

**Comment by cartermp** [comment]
@KevinRansom is this set of strings ours, or are they in the CLI?

**Comment by AndreasHassing** [comment]
@cartermp the problem can be found here:
https://github.com/dotnet/fsharp/blob/cba6e1b8ce8e931f288f63ae0e27a2fb02a458e7/src/fsharp/fsi/fsi.fs#L757

Cloning the repo to try and see if I can fix it :).

**Comment by cartermp** [comment]
Thanks @AndreasHassing for addressing this!
