### ISSUE TITLE
Silent conversion to nativeint for nativeptr in generic arguments

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/fsharp#8414]
C# example and error 

https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgJgIwFgBQyDMABGgQMIEDeOB1RhyALAQLIAUAlBVTdwG4CGAJwIAPAgF4CwAJ4AHAKYB7AGYtk6VAB4ARlOByAVAD42Abi7UAvjgtA

`error CS0306: The type 'byte*' may not be used as a type argument`

F# 

`typeof<byte nativeptr>` => `ldtoken Action<native int>`

https://sharplab.io/#v2:DYLgZgzgNALiCWwoBMQGoA+B7ADgUwDsACAZQE8IY8BbAWACgYz8iBhACgEoiBeBogUWo0ARngBORGAAt4EAHQBZLrynM8WMAB4AggGMY8LAS0iyVIgQCGhgG54cMcQD5nQA

With https://github.com/dotnet/fsharp/issues/8413 converting to IntPtr I'm surprised here native int is chosen instead.

Is this working as intended?

**Comment by cartermp** [comment]
> Is this working as intended?

Probably not :)

**Comment by dsyme** [comment]
This is by-design, we erase `nativetr` to `IntPtr` when used in this position - the emit of `int*` pointer types is only for interop
