### ISSUE TITLE
Change ty.Equals(typeof<'T>) to Type.op_Equality(typeof<'T>, ty) to please RyuJIT

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/fsharp#8447]
There are some dynamic type checks here and there in FSharp.Core that all use Type.Equals instead of Type.op_Equality. Only the latter is optimized by the JIT for branch elimination (reference vs value type) and lookup table transformation for shared reference type checks. That's some easy free perf on the generic equality.

https://github.com/dotnet/fsharp/blob/db2ba9ea52560fac9f37a27016f82af830a39383/src/fsharp/FSharp.Core/prim-types.fs#L2341-L2357

https://sharplab.io/#v2:DYLgZgzgNALiCGEC2AfA9gBwKYDsAEAygJ4QxZICwAUJroQBbwBOGAMvAEYB0ASgK44YASyRZq1GEWx4AwgAoAlHgC81POrwBtADwApITADiuLEyEBjOZOxow2oYIB8CxwF01G0vGHm8opBymhMBoAO7aAOQAKo6KKngeGhpI3ub0eNZYtpExeKEG6YlJeCgZRHn0dJJcAKIAjnzwwBBWUll2DjDOeAC0jngAjEVJpZIVVUS1DU0tmdkcaGjA3X14AEzDGqPloZX41fWNza02dhxEZCv9AMyb6qUA+r39ACx3CVRJOvpGJmaWcw6Thc7k+nhg3gsfnIgSYeAAYogYDlYkplB9islUulASi8gUMZiShlxvgom0uJgHocmgYiFYoGVTvZgc9Bu9RqS8OTsJSMNTpsA6Qyme1tAslld1hySbs6DysHyBUdhTBGbjzpclKtbmDMY82W8qEA=

Ideally I'd like to see a static optimization for `(=) (x:Type, y:Type)` to use `Type.op_Equality` @dsyme is this something you're ok with?

**Comment by cartermp** [comment]
This would make for a good PR I think. Can't think of a downside here.

**Comment by TIHan** [comment]
`Type` can be inherited from, so we can't automatically optimize `Type` equality with `Type.op_Equality`, but code shown could be changed to use `Type.op_Equality`.

**Comment by NinoFloris** [comment]
Right...  It's a shame Type is a non-framework inheritable class. 

I suppose you could still do a static optimization when typeof appears on the left hand side but all that is probably more trouble than it's worth.

Judicious use of `NonStructuralComparison` it is then.

**Comment by TIHan** [comment]
We could do optimization of `typeof<>` I think.

**Comment by NinoFloris** [comment]
Same for `instance.GetType()` appearing on lhs, as it's non virtual. Starts to look a lot like the CLR optimization ;)
