### ISSUE TITLE
Can Async.Catch return Result instead of Choice?

### ISSUE THREAD

**Issue by replicaJunction** [dotnet/fsharp#8454]
**Is your feature request related to a problem? Please describe.**
Async.Catch is used for error handling, but the Choice type is cryptic and not immediately intuitive (partly because the Choice type has so many variants like Choice1Of2, Choice1Of3, etc.).

The Result type is designed for exactly this situation, and it's much more expressive.

**Describe the solution you'd like**
Modify Async.Catch so that instead of returning Choice<'T, exn>, it returns Result<'T, exn>.

**Describe alternatives you've considered**
The other alternative is to leave the current behavior. It works just fine, but it's not as explicit and clear.

**Additional context**

Here is a side-by-side comparison of the current state using Choice, and the proposed future state with Result:

```fsharp
// Current state
let! result = doAsyncItem |> Async.Catch
match result with
| Choice1Of2 ok -> // Success case
| Choice2Of2 err -> // Failure case

// Proposed future state
let! result = doAsyncItem |> Async.catch
match result with
| Ok ok -> // Success
| Error err -> // Failure
```

**Comment by cartermp** [comment]
I agree that `Result` is the better type here. However, doing this would be a breaking change. Additionally, F# does not overload based on the return type, so there is no workaround aside from adding a different static member.

I'd recommend adding this use case to the following language suggestion: https://github.com/fsharp/fslang-suggestions/issues/820

**Comment by brettrowberry** [comment]
I just filed https://github.com/fsharp/fslang-suggestions/issues/930
