### ISSUE TITLE
[loc][Query][fsharp] Localizability of 0; "fromEndSlicingRequiresVFive"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/fsharp#8457]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
From the end slicing with requires language version 5.0, use /langversion:preview.

File Name:
fsharp\xlf\FSComp.txt.xlf

==========================================
Query:
can it be rephrase to "Slicing from the end requires language....?

**Comment by cartermp** [comment]
Hello @PDostalek, yes this works: "Slicing from the end requires language....?".

The feature is called "from end" or "from the end" slicing, but the wording itself is kind of tricky even in English. I think "Slicing from the end" is the least ambiguous.

**Comment by PDostalek** [comment]
Thank you for your reply.
