### ISSUE TITLE
F# .NET Core console projects don't allow you to choose "CPU Usage" and ".NET Object Allocation"

### ISSUE THREAD

**Issue by TIHan** [dotnet/fsharp#8461]
@dsyme mentioned this to us:

![Untitled](https://user-images.githubusercontent.com/1278959/73784429-4fc9d200-474a-11ea-8ecd-adbfcdf2ee0e.png)

Compare to C# .NET Core console project:

![Untitled2](https://user-images.githubusercontent.com/1278959/73784466-5b1cfd80-474a-11ea-906b-1791ead01c28.png)

**Comment by dsyme** [comment]
I'd really like this one fixed... :-) The VS profiler is still my go to tool for profiling, and likewise for most of customers...  I'm sure this used to work

**Comment by dsyme** [comment]
@cartermp Any idea who I should talk to in the would of VS to get this fixed?

I'm sure it's just a very simple fix of some kind.  The underlying technology doesn't depend on C# I'm sure

cc @TIHan

**Comment by dsyme** [comment]
I checked in VS2022 and this is fixed, you can now profile F# .NET Core programs again
