### ISSUE TITLE
Not able to add System.Data.SQLLite with an F# project

### ISSUE THREAD

**Issue by samikrc** [dotnet/fsharp#847]
I am using VS 2015 Community Update 1. When I try adding the EF6 using Nuget (as part of trying to install System.Data.SQLite package), I get an error and an exception, and the installation starts rolling back - which also fails. 

Relevant lines:

Adding package 'EntityFramework.6.0.0' to folder 'C:\TestProject\packages'
Added package 'EntityFramework.6.0.0' to folder 'C:\TestProject\packages'
Added package 'EntityFramework.6.0.0' to 'packages.config'
Executing script file 'C:\TestProject\packages\EntityFramework.6.0.0\tools\init.ps1'...
Executing script file 'C:\TestProject\packages\EntityFramework.6.0.0\tools\install.ps1'...
Exception calling "SetData" with "2" argument(s): "Type 
'Microsoft.VisualStudio.FSharp.ProjectSystem.Automation.OAProject' in assembly 'FSharp.ProjectSystem.Base, 
Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable."
At C:\TestProject\packages\EntityFramework.6.0.0\tools\EntityFramework.psm1:633 char:5
-     $domain.SetData('project', $Project)
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : SerializationException

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.Entity.ConnectionFactoryConfig.InitializeEntityFrameworkCommand.Execute()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
Install failed. Rolling back...
Removed package 'EntityFramework.6.0.0 : ' from 'packages.config'
Removing package 'EntityFramework.6.0.0 : ' from folder 'C:\TestProject\packages'
Access to the path 'C:\TestProject\packages\EntityFramework.6.0.0\tools\EntityFramework.PowerShell.Utility.dll' is denied.
Access to the path 'EntityFramework.PowerShell.Utility.dll' is denied.
Removed package 'EntityFramework.6.0.0 : ' from folder 'C:\TestProject\packages'
System.Management.Automation.RuntimeException: Object reference not set to an instance of an object. ---> System.Management.Automation.RuntimeException: Object reference not set to an instance of an object.
   --- End of inner exception stack trace ---

While this is being looked into, is there any other workaround? For e.g., I see that "Entity Framework 6.1.3 Tools for VS Update 1" is already installed and shows up in "Programs and Features" window. Can I use that directly?

Thanks.

[Update] Attached full stack trace.
[Full STack Trace.txt](https://github.com/Microsoft/visualfsharp/files/76138/Full.STack.Trace.txt)

**Comment by dsyme** [comment]
@cartermp @brettfo  This bug still exists.  It seems kind of problematic, we should be able to add a reference to EF6

The problem is some missing automation support in the F# project system.  Do we think the new project system will help with this?

**Comment by cartermp** [comment]
I have no idea, but I assume any issue would be less severe.  @srivatsn, would you know?

**Comment by srivatsn** [comment]
The missing automation support will need to be implemented in the new PS as well but depending on which interfaces, it may be implemented for C# already in which it'll be easy to just share that component.

**Comment by cartermp** [comment]
Renaming issue - this still reproduces, but not for the EF6 package itself. This is for the System.Data.SQLLite package.

**Comment by cartermp** [comment]
This is now supported for F# targeting .NET Core or .NET Framework via the .NET SDK. Closing this out, as we won't be making any modifications to the legacy project system to enable this.

![image](https://user-images.githubusercontent.com/6309070/58290087-560b5000-7d6d-11e9-98ae-20f919c87af3.png)
