### ISSUE TITLE
F# projects automatically add 'open' declarations outside of module

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#8472]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/552356/f-projects-automatically-add-open-declarations-out.html)._

---
When using a namespace as well as a module name, automatically resolving a reference adds the open declaration under the namespace but above the module name.

This didn't happen in VS 2017, and it is undesirable as it obviously opens that reference for the entire namespace rather than just the module you are working in.

---
#### Visual Studio Feedback System on 5/1/2019, 09:49 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Ryan Palmer on 8/9/2019, 02:53 AM: 

Hi, any news on this? I just got the latest major update and it is still happening. It really is a major pain. Thanks.

---
### Original Solutions
(no solutions)

**Comment by abelbraaksma** [comment]
This is already an option, you can chose module-level or top-level. This was a a feature request in 2017, https://github.com/dotnet/fsharp/issues/2827 and implemented https://github.com/dotnet/fsharp/pull/2875.

![image](https://user-images.githubusercontent.com/16015770/73879684-3a919800-485d-11ea-9b0e-e0ba36acd03b.png)

**Comment by cartermp** [comment]
Thanks!
