### ISSUE TITLE
Problem with F# in .NET Core 3.0 - cannot access type in another Module

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#8474]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/840693/problem-with-f-in-net-core-30-cannot-access-type-i.html)._

---
I created a F# class library with 2 modules and tried to access a type defined in one module from another module. It returned the error message "namespace or module ... not defined". This error occurs only in .NET Core, not in .NET framework.

I have included the 2 source programs.

Can you please tell me if I'm doing something wrong here

Many thanks

Hugh Grant

---
#### Visual Studio Feedback System on 12/3/2019, 02:09 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 1/9/2020, 06:38 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by dsyme** [comment]
Sadly the repro for this isn't included at https://developercommunity.visualstudio.com/content/problem/840693/problem-with-f-in-net-core-30-cannot-access-type-i.html, at least as far as I can see

As a result I will close this, but please reopen if we get a repro
