### ISSUE TITLE
Fsx archive files doesnt appear on Add Menu. Also Alt+Enter for F# Interactive isnt Working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#8475]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/896832/fsx-archive-files-doesnt-appear-on-add-menu-also-a.html)._

---
On Add Menu the Script File for F# (.fsx) doesnt appear. However i could change any file to .fsx file and is recognized by Visual Studio. 
Also when i active F# interactive with Alt+Control+F the windows appears normally but when i use Alt+Enter to run a line of the .fsx file nothing happens

---
#### Visual Studio Feedback System on 1/28/2020, 04:41 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by cartermp** [comment]
Tagging as `needs repro` since the UI command and the key command seem to work as expected in VS.

**Comment by cartermp** [comment]
Closing as no repro, never seen this happen across multiple VS releases
