### ISSUE TITLE
F#: Extra closing bracket added when auto-completion disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#8478]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/882129/f-extra-closing-bracket-added-when-auto-completion.html)._

---
If you _disable_ auto-completion of brackets for F#, when you type a closing bracket, the bracket is doubled. When enabled,  auto-completion works correctly.

let a = f()**)**
let b = [ 1; 2; ]**]**
let c = { 1, 2, }**}**

---
#### Visual Studio Feedback System on 1/13/2020, 01:44 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Ferd Barfarkle on 1/27/2020, 00:11 PM: 

<p>Happens with C# as well when typing '&gt;' and '/'.</p><p>public Task&lt;FredData&gt;<strong>&gt;</strong></p><p>GetFredData("fred/<strong>/</strong>");</p><p>Using Microsoft Visual Studio Community 2019 Preview Version 16.5.0 Preview 2.0. </p><p>Seems this was a problem in an earlier version with C++ (IntelliSense breaks with slash in #include statement).</p><p><strong></strong><u></u><sub></sub><sup></sup><strong></strong><strong></strong><u></u><sub></sub><sup></sup><strong></strong><u></u><sub></sub><sup></sup><strong></strong><u></u><sub></sub><sup></sup></p>

---
### Original Solutions
(no solutions)

**Comment by dsyme** [comment]
I don't repro this
