### ISSUE TITLE
Adding more signature files

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#8505]
There are some files in the compiler codebase that could do with signature files to help for the usual encapsulation reasons.  I'm thinking

* [ ] infos.fs
* [ ] MethoddCalls.fs
* [ ] TypeRelations.fs

and a few others in the "Logic" section

I made a gist of the complete signature dump from the compiler build here: https://gist.github.com/dsyme/ff9e39cfff879f49dea2a95afdc4b12f

We should be able to cut these out and make signatures.

**Comment by cartermp** [comment]
this one was done
