### ISSUE TITLE
Another repro of LocallyAbortOperationThatFailsToResolveOverload

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/fsharp#8520]
This seems to be the smallest sample to get `LocallyAbortOperationThatFailsToResolveOverload`. 

```fs
type Foo = 
    static member Bar (x: int) = ()
    static member Bar (x: bool) = ()

    static member inline Invoke source = 
        let inline call (_: ^M, _: ^N, a: ^a) =
            ((^M or ^N): (static member Bar: _ -> _)(a))

        call (Unchecked.defaultof<Foo>, Unchecked.defaultof<_>, source)

        // or similarly but gives a different error location at null
        call (Unchecked.defaultof<Foo>, null, source)

        // no inference here so this returns a nice overload ambiguity error
        call (Unchecked.defaultof<Foo>, Unchecked.defaultof<obj>, source)
```

```
    error FS0071: Type constraint mismatch when applying the default type 'obj' for a type inference variable. internal error: Exception of type 'FSharp.Compiler.ConstraintSolver+LocallyAbortOperationThatFailsToResolveOverload' was thrown. Consider adding further type constraints
```
It was fairly educational to see handling of this differ between `Unchecked.defaultof<_>` `null` and `Unchecked.defaultof<obj>`.

I assume this is fixed in https://github.com/dotnet/fsharp/pull/8294

**Comment by cartermp** [comment]
@NinoFloris this now emits an [overload error](https://sharplab.io/#v2:DYLgZgzgPgLgngBwKYAIBiB7DKC8KCwAUCiShDAIYwCWAxigLZIMBGSATigEIWcAUADxApqAOxgBKXCj4SipMpRr0mrDt14yhKFlmBS8sovNLkqdRszacxwMagCSogG4YA1qggYAru1qo8EwUSYCQYEVE7UVRaCmBgGQB9YQA9AFkAGhRklBSAOSyKVIoDIOCFPj50lAxOfIlhPjNlSzVOHnZhRJQAWgA+bIk+ErlCMoVY+JkAVVFaAAskWg8AEwA6FaQwCm9gGAwwAB5MDD6s2YWl1Y2tnb2Dw8Szsh8/JFHx0gB6L5rOCGoDGowF4wDgOm84QA5tRnEgICgKCgVtQwGAOEhxCgOOxaihgBhYjQMKJEeFRLtgJ8SJMEnwLotlkh1pttrt9kcTs8KfEsl5fP4PsRyigfihRNgxOj2Jj/ChFjKXigYPNqAiZTBfKIEUjRHRUBg4ewCRQVojWNQod5qPBsexcexqShaTM5ozrqy7hzjlhngyrsybmz7kcMCwAFbPflvCRAA===)

`
    error FS0043: A unique overload for method 'Bar' could not be determined based on type information prior to this program point. A type annotation may be needed. Candidates: static member Foo.Bar : x:bool -> unit, static member Foo.Bar : x:int -> unit
`

So I believe this can be closed unless you expect something different 🙂

**Comment by NinoFloris** [comment]
Nice, closing.
