### ISSUE TITLE
Using a method prior to its definition in the same class causes code to be less generic than expected

### ISSUE THREAD

**Issue by vincenzoml** [dotnet/fsharp#8550]
Please provide a succinct description of the issue.

Using a method prior to its definition in the same class causes code to be less generic than expected. For instance: the following program does not compile:
```F#
type T(x : int) =
    static member GetInt (t : T) = t.Transform (fun x -> x)
    static member GetString (t : T) = t.Transform (fun x -> x.ToString())
    member this.Transform fn = fn x
```
The error is:

```
test.fs(4,35): error FS0001: This expression was expected to have type
    'string'    
but here has type
    'int'
```
whereas the following program compiles and works as expected

```F#
type T(x : int) =
    member this.Transform fn = fn x
    static member GetInt (t : T) = t.Transform (fun x -> x)
    static member GetString (t : T) = t.Transform (fun x -> x.ToString())
```
**Known workarounds**

Just define methods prior to their usage if possible (but what about mutually recursive methods?)

* Operating system

Tested on ubuntu 19.10, but OS independent.

* .NET Runtime kind (.NET Core, .NET Framework, Mono)

.NET Core 3.1

**Comment by abelbraaksma** [comment]
@vincenzoml The code is quite hard to read, could you edit the question, select the code fragments, age click the `<>` button in the editor?

Or surround it with ` ```f# ` on a line before the code block, and ` ``` ` on a line after the code block.

This will add syntax highlighting and make it easier to understand what the issue is about.

**Comment by vincenzoml** [comment]
Done!

**Comment by cartermp** [comment]
My intuition is that this is by design, since type inference is at play here. You can see a similar problem here:

```fsharp
module rec Foo =
    let f1 x = g (fun _ -> x)
    let f2 x = g (fun _ -> x.ToString())
    let private g f = f
    
open Foo

f2 12
```

But @dsyme should probably chime in here

**Comment by dsyme** [comment]
Yes, this is by design.  If you fully type-annotate the forward-call method you can recover the full genericity
