### ISSUE TITLE
`dotnet fsi` in linux handles Backspace in a funny way

### ISSUE THREAD

**Issue by Heimdell** [dotnet/fsharp#8565]
The handling of backspace makes `dotnet fsi` unusable.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Run `dotnet fsi` in a linux terminal emulator.
2. Enter some text.
3. Press Backspace.

**Expected behavior**

I expect Backspace to remove last char w/o any ceremony.

**Actual behavior**

Cursor is reset to the start of the line, then it goes right _through all the text_, replaces last char by space, goes left 1 pos; all of that with a speed of 3-4 chars per sec.

**Known workarounds**

Use `fsharpi` instead of `dotnet fsi`.

**Related information**

Provide any related information (optional):

* Operating system: `Linux kir-notebook 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

* .NET Runtime kind (.NET Core, .NET Framework, Mono)
  ```bash
  $ dotnet --version
  2.2.402
  ```
* Editing Tools (e.g. Visual Studio Version, Visual Studio):
  None.

**Comment by cartermp** [comment]
@Heimdell I see you're using an old version of .NET Core. Can you try this with the latest (.NET Core 3.1)? I don't observe this behavior on WSL 2 (ubuntu LTS) and latest .NET Core

**Comment by cartermp** [comment]
I also tried this on macOS and haven't seen it.

**Comment by Heimdell** [comment]
It does work on `sdk-3.1`.

**Comment by cartermp** [comment]
Awesome! Glad to hear it.
