### ISSUE TITLE
Go to Definition does not take me to the definition of F# list type abbreviation

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#8582]
1. Open `ast.fs`, line 1184
2. Hover over `SynValInfo`
3. Click the `list` type in the VS tooltip

![image](https://user-images.githubusercontent.com/6309070/74571262-6e8e4c80-4f32-11ea-84b1-71b5414f0629.png)

Expected:

navigates to prim-types.fs, line 3020.

Actual:

navigates to prim-types.fs, line 3013

![image](https://user-images.githubusercontent.com/6309070/74571389-98e00a00-4f32-11ea-80ca-259fb537e8f4.png)

**Comment by dsyme** [comment]
This is minor enough that I'm closing it
