### ISSUE TITLE
Can take native address of immutable local value

### ISSUE THREAD

**Issue by TIHan** [dotnet/fsharp#8599]
The following code gets the native pointer of an immutable value, it compiles today:
```fsharp
let test () =
    let x = 1
    let y = &&x // get a nativeptr<int>
    ()
```

This used to not compile. AFAIK, we don't have this documented anywhere and is probably an artifact of span and friends. I noticed this months ago but didn't think much of it until I thought about it again today.

We should not allow this to compile. This for sure breaks any immutability assumption on a value; has very unintended consequences due to optimizations that happen on immutable values.

**Comment by cartermp** [comment]
Yep, that should definitely not be allowed.
