### ISSUE TITLE
Interfaces in anonymous records

### ISSUE THREAD

**Issue by ncave** [dotnet/fsharp#8640]
Should anonymous record types be augmented with `IStructuralEquatable`/`IStructuralComparable`, like the normal record types are?

**Comment by dsyme** [comment]
In the compiled code they are augmented.

For static typing they are not.  Yes it's reasonable for this to be added.  Please add a suggestion (consider it approved in principle) and an RFC 

```fsharp
type R = { X: int; Y: int }

let f2 (x:R) = (x :> System.Collections.IStructuralEquatable)
let f x y = ({| X = x; Y = y |} :> System.Collections.IStructuralEquatable) // fails
```

**Comment by cartermp** [comment]
Closing in favor of a language suggestion. When it's filed, I'll tag it with `approved-in-in-principle` if it hasn't been tagged already
