### ISSUE TITLE
Localization files are changed on build

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#8660]
```
Eugene.Auduchinok@UNIT-1032 MINGW64 /c/Developer/fsharp (master)
$ git status
On branch master
Your branch is up to date with 'origin/master'.
  Changes not staged for commit:   (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   src/fsharp/xlf/FSComp.txt.cs.xlf
        modified:   src/fsharp/xlf/FSComp.txt.de.xlf
        modified:   src/fsharp/xlf/FSComp.txt.es.xlf
        modified:   src/fsharp/xlf/FSComp.txt.fr.xlf
        modified:   src/fsharp/xlf/FSComp.txt.it.xlf
        modified:   src/fsharp/xlf/FSComp.txt.ja.xlf
        modified:   src/fsharp/xlf/FSComp.txt.ko.xlf
        modified:   src/fsharp/xlf/FSComp.txt.pl.xlf
        modified:   src/fsharp/xlf/FSComp.txt.pt-BR.xlf
        modified:   src/fsharp/xlf/FSComp.txt.ru.xlf
        modified:   src/fsharp/xlf/FSComp.txt.tr.xlf
        modified:   src/fsharp/xlf/FSComp.txt.zh-Hans.xlf
        modified:   src/fsharp/xlf/FSComp.txt.zh-Hant.xlf
```

<img width="1536" alt="Screenshot 2020-03-05 at 14 05 12" src="https://user-images.githubusercontent.com/3923587/75975868-5a62bd00-5eea-11ea-8975-3e692506ce07.png">

It's quite annoying to clean it up after build.

**Comment by abelbraaksma** [comment]
Isn't this supposed to happen? Whenever you change a localizable string, it needs to be reviewed or updated by the translation team.

Meaning: I can be wrong, but I think you're supposed to commit these updated files as well.

**Comment by auduchinok** [comment]
I did not change any localizable string. It was a build and a test suite run in a fresh working copy.

**Comment by abelbraaksma** [comment]
Ah, then it suggests that perhaps someone committed incomplete data for localization (I've done that too, but that was caught before merging)

**Comment by auduchinok** [comment]
It looks like it's result of #8584.

**Comment by KevinRansom** [comment]
@auduchinok, I carried a fix in with this PR:  https://github.com/dotnet/fsharp/pull/8606
