### ISSUE TITLE
Use of nameof changes name resolution rules

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#8661]
It seems using `nameof` makes symbol resolved using type name resolution rules first.

```fsharp
let f (obj: obj) =
    nameof obj
```

In this example `obj` inside the function is resolved to type, which is unexpected, making local `obj` value unused:

<img width="216" alt="Screenshot 2020-03-05 at 16 58 35" src="https://user-images.githubusercontent.com/3923587/75988474-b2a5b900-5f02-11ea-93ea-2fff74d9d2e8.png">

Without `nameof` it works as expected:

<img width="233" alt="Screenshot 2020-03-05 at 17 07 17" src="https://user-images.githubusercontent.com/3923587/75989145-cbfb3500-5f03-11ea-9aaa-b58bd71b2bd9.png">

When there's no matching type to resolve to is found, it also works as expected:

<img width="222" alt="Screenshot 2020-03-05 at 16 58 44" src="https://user-images.githubusercontent.com/3923587/75988477-b33e4f80-5f02-11ea-857c-3349e21c52d7.png">

**Comment by cartermp** [comment]
@dsyme @TIHan we'll want to look at this one in the next sprint I think, especially if we can focus on finishing up some design concerns around `nameof`

**Comment by abelbraaksma** [comment]
But is it really an issue in practice? `obj` as variable is still accessible, and the returned string should be "obj" in either case; alternatively one might consider the ambiguity an error, after all, there's no way to know whether the user intended one over the other.

**Comment by auduchinok** [comment]
> But is it really an issue in practice?

It can be. This is a close to minima repro which doesn't look too bad on it's own indeed. But it clearly shows a different behavior which, together with a more subtle names clash, can make features like Rename refactoring work very wrong.

**Comment by abelbraaksma** [comment]
> can make features like Rename refactoring work very wrong.

Didn't think of that, good point.

**Comment by dsyme** [comment]
Thanks for this bug report

**Comment by dsyme** [comment]
Thanks again for this report, I made the appropriate fix and update to the RFC, see https://github.com/fsharp/fslang-design/pull/488

**Comment by dsyme** [comment]
I'll close this report as it is now part of the RFC update at https://github.com/dotnet/fsharp/pull/8754
