### ISSUE TITLE
Internal error when specifying invalid name for the `this` binding of a member.

### ISSUE THREAD

**Issue by nikonthethird** [dotnet/fsharp#8671]
The F# compiler displays *internal error: GetInstanceMemberThisVariable: instance member did not have expected internal form (Failure)* instead of a proper error when specifying a certain invalid name for the `this` binding of a member.

**Repro steps**

```fsharp
type R = { X : int32 }
with member ({X}).Test () = ()
```

**Expected behavior**

A better error message perhaps? The whole file gets red-squiggled.

**Actual behavior**

Internal F# compiler error.

**Known workarounds**

Not applicable, since I was just trying to see if a pattern like `{ X = x }` could be used for the `this` binding, since `_` is now allowed.

**Related information**

Provide any related information (optional):

* Windows 10, Ubuntu 18.04
* .NET Framework 4.7.2, F# runtime 4.7.0.0
* Visual Studio 2019

**Comment by abelbraaksma** [comment]
> since `_` is now allowed.

True, but in this special case it's not a pattern wildcard, it's a placeholder for the this pointer, preventing you from referring to the instance. In previous style, people used `__` instead, but that could still be accessed in code.

Using `_` won't prevent you from accessing instance fields, though, provided they're declared in the constructor.

**Comment by nikonthethird** [comment]
Thank you for clarifying, but I was just goofing around and came across this internal error.

```fsharp
type MyRecord { One : int32; Two : string; Three : float }
with override { One = one; Three = three}.ToString () = sprintf "%d %f" one three
```

But to be honest, at first I would be disgusted if something like this worked, but then I would also be in awe :)

**Comment by Happypig375** [comment]
Here is the suggestion: https://github.com/fsharp/fslang-suggestions/issues/752

**Comment by psfinaki** [comment]
Yeah, can confirm. Thanks Edgar, closing this.
