### ISSUE TITLE
Should `async.TryFinally` register the `finally` block before checking for cancellation?

### ISSUE THREAD

**Issue by rob-earwaker** [dotnet/fsharp#8675]
Outside of a computation, it's safe to assume that if the statement before a `try ... finally` completes successfully then the `finally` block will always be executed (except in extreme - and usually fatal - circumstances such as OOM). This means that in the following code, if the `SemaphoreSlim.Wait` call completes, the `SemaphoreSlim.Release` method should always be called.

```fsharp
use semaphore = new SemaphoreSlim(1)
semaphore.Wait()
try
    printf "Doing some work"
finally
    semaphore.Release() |> ignore
```

This is not true inside an `async` computation when the computation has been cancelled, because `async.TryFinally` checks for cancellation before registering the `finally` block. This means that in the async equivalent of the snippet above, if the `SemaphoreSlim.WaitAsync` call completes the `SemaphoreSlim.Release` will only be called if the computation has not been cancelled. This can be demonstrated using the following (slightly contrived) sample:

```fsharp
open System.Threading

[<EntryPoint>]
let main _ =
    use semaphore = new SemaphoreSlim(1)
    printfn "Semaphore count available: %i" semaphore.CurrentCount
    try
        Seq.init 3 (fun index ->
            async {
                printfn "[%i] Waiting to enter semaphore" index
                let! cancellationToken = Async.CancellationToken
                do! semaphore.WaitAsync(cancellationToken) |> Async.AwaitTask
                printfn "[%i] Entered semaphore" index
                try
                    printfn "[%i] Within try-finally" index
                    for _ in [ 1 .. 4 ] do
                        do! Async.Sleep 1000
                        printfn "[%i] Looping" index
                    printfn "[%i] Error" index
                    failwith "Something bad happened!"
                finally
                    semaphore.Release() |> ignore
                    printfn "[%i] Semaphore released" index
            })
        |> Async.Parallel
        |> Async.Ignore
        |> Async.RunSynchronously
    with
    | exn ->
        printfn "Unhandled exception: %s" exn.Message
        printfn "Semaphore count available: %i" semaphore.CurrentCount
    0
```

This will usually produce output similar to the following:

```
Semaphore count available: 1
[0] Waiting to enter semaphore
[1] Waiting to enter semaphore
[2] Waiting to enter semaphore
[0] Entered semaphore
[0] Within try-finally
[0] Looping
[0] Looping
[0] Looping
[0] Looping
[0] Error
[0] Semaphore released
[2] Entered semaphore
[2] Within try-finally
[2] Semaphore released
[1] Entered semaphore
Unhandled exception: Something bad happened!
Semaphore count available: 0
```

The third computation to enter the semaphore (in this case `[1]`) does not enter the `try ... finally` statement because the exception raised by the first computation to enter the semaphore (in this case `[0]`)  has resulted in cancellation. This means that the semaphore is not released.

There is a workaround for this, which involves checking for cancellation of the current token before entering the `try ... finally` block, i.e. adding `if cancellationToken.IsCancellationRequested then semaphore.Release() |> ignore` after the call to `SemaphoreSlim.WaitAsync`. This relies on the assumption that if cancellation is detected here then the `try ... finally` block is not entered, which I _think_ is valid(?).

I'm raising this because it was the source of some confusion on my part, and the behaviour could be be considered unexpected or even undesirable. It's not causing me any issues as such, but I thought it was something worth bringing up as there may be situations (not necessarily involving semaphores) in which this _is_ problematic.

Should `async.TryFinally` register the `finally` block before checking for cancellation?

**Comment by dsyme** [comment]
This is a good question.  I believe you are right - it is better to "enter" the try/finally (registering the finally clause) and then check for cancellation.

There is another workaround I believe:
```
open System.Threading

[<EntryPoint>]
let main _ =
    use semaphore = new SemaphoreSlim(1)
    printfn "Semaphore count available: %i" semaphore.CurrentCount
    try
        Seq.init 3 (fun index ->
            async {
                printfn "[%i] Waiting to enter semaphore" index
                let! cancellationToken = Async.CancellationToken
                let mutable acquired = false
                try
                    printfn "[%i] Within try-finally" index
                    do! semaphore.WaitAsync(cancellationToken) |> Async.AwaitTask
                    acquired <- true
                    printfn "[%i] Entered semaphore" index
                    for _ in [ 1 .. 4 ] do
                        do! Async.Sleep 1000
                        printfn "[%i] Looping" index
                    printfn "[%i] Error" index
                    failwith "Something bad happened!"
                finally
                    if acquired then 
                        semaphore.Release() |> ignore
                        printfn "[%i] Semaphore released" index
            })
        |> Async.Parallel
        |> Async.Ignore
        |> Async.RunSynchronously
    with
    | exn ->
        printfn "Unhandled exception: %s" exn.Message
        printfn "Semaphore count available: %i" semaphore.CurrentCount
    0
```
