### ISSUE TITLE
There is an issue running a netstandard2.0 build of dependencymanager on the desktop clr

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#8676]
Reported by @auduchinok 
Thread:
here: https://github.com/dotnet/fsharp/pull/8606#discussion_r388871005

<Snip>
This breaks when using netstandard2.0 FCS build in a .NET Framework host process.
</snip>

**Comment by KevinRansom** [comment]
Oh lordy this is actually pretty tricky.  not sure how to fix in a non hacky way.

Simply building this netstandard2.0 and then running it on desktop fails:

````
namespace Interactive.DependencyManager

open System
open System.Collections.Generic
open System.IO
open System.Reflection
open System.Runtime.InteropServices

open System.Runtime.Loader

// Cut down AssemblyLoadContext, for loading native libraries
type NativeAssemblyLoadContext () =
    inherit AssemblyLoadContext()

    member this.LoadNativeLibrary(path: string): IntPtr =
        base.LoadUnmanagedDllFromPath(path)

    override _.Load(_path: AssemblyName): Assembly =
        raise (NotImplementedException())

    static member NativeLoadContext = new NativeAssemblyLoadContext()

module myMain =
    [<EntryPoint>]
    let main argv =
        printfn "Hello World from F#!: '%s'" (typeof<AssemblyLoadContext>.FullName)
        0 // return an integer exit code
````
with this:
````
C:\Users\kevinr\source\repos\AssemblyLoadContextApp\AssemblyLoadContextApp\bin\Debug\netstandard2.0>AssemblyLoadContextApp.exe

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.   at Interactive.DependencyManager.myMain.main(String[] argv)

C:\Users\kevinr\source\repos\AssemblyLoadContextApp\AssemblyLoadContextApp\bin\Debug\netstandard2.0>
````
The correct thing to do is to deploy the desktop version of System.Runtime.Loader.dll, which simply contains a type forward of assemblyloadcontext to mscorlib.

I suppose the second best thing to do … is to ensure the code adapts based on the underlying platform to the desktop and the coreclr.

I think the reason that FCS used to work despite having a dependency on System.Runtime.Loader, is that the load context dependent code was switched back to APIs that are natively in the desktop too.

**Comment by auduchinok** [comment]
@KevinRansom Just to confirm, this is exactly the error I've seen today.

**Comment by KevinRansom** [comment]
@auduchinok, yes, I'm guessing that all the code we had that used assemblyLoadContext has gone away due to our efforts to re-align the codebase.  Anyway, I'm pretty sure I can make most of it adaptive which is probably the least intrusive solution.
