### ISSUE TITLE
Some tests require net48

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#8679]
Namely, `ML - use assembly with ref dependencies` test fails if net48 targeting pack is not installed:
<img width="882" alt="Screenshot 2020-03-04 at 14 16 59" src="https://user-images.githubusercontent.com/3923587/76142448-edccf700-607e-11ea-891b-f400ab70b998.png">

Installing the targeting pack fixed it.

Is is possible to make it depend on net472/netstandard2.0, like the most of the things in the compiler/tests?

If not, what would be a better place to add a note to? [Here](https://github.com/dotnet/fsharp/blob/master/TESTGUIDE.md#prerequisites)?

**Comment by cartermp** [comment]
The test project is net472 and the package is NS2.0, so this seems surprising. @KevinRansom thoughts?

**Comment by cartermp** [comment]
Will close this out as it's not within our control and it's a valid test scenario. Since VS installs this targeting pack by default now I think it's fine.
