### ISSUE TITLE
Is it possible to reference ASP.Net Core framework in dotnet fsi?

### ISSUE THREAD

**Issue by masq6r** [dotnet/fsharp#8688]
To build an ASP.Net Core application, one should make sure `FrameworkReference` tag in the `.fsproj` file. But what is the correct directive to get this dependency ready in `dotnet fsi`? Should I `#r` all the DLLs under `/usr/share/dotnet/shared/Microsoft.AspNetCore.App/version`, or is there a better solution for this?

**Comment by cartermp** [comment]
I would be surprised if this worked at all today. In .NET 5 it will be possible to reference the package like this:

<img width="432" alt="image" src="https://user-images.githubusercontent.com/6309070/76168565-342d5f00-612e-11ea-8b55-5147ca8faedd.png">

But I'm not sure the scenario fits, though. ASP.NET Core is far more complex than just a simple library, which means it's not going to be very scriptable even though `#r "nuget:...` will be supported.

**Comment by baronfel** [comment]
@cartermp that package only goes up to aspnetcore 3.0, because after the move to framework refs the aspnetcore team stopped publishing nuget packages for a large chunk of the framework. Maybe this makes sense for another dependency provider? `#r frameworkRef "Microsoft.AspNetCore.App"`?

Although I must admit I'm not familiar with any other frameworkRefs aside from the ones that come with the current SDK distribution.

**Comment by Happypig375** [comment]
@baronfel It should be `#r "framework:Microsoft.AspNetCore.App"` to align with the current syntax.

**Comment by cartermp** [comment]
There would probably need to be another provider, yes. cc @KevinRansom

**Comment by masq6r** [comment]
Would it be possible to have `#r "project:Yet.Another.Project.fsproj"` as well, which basically loads all the references recursively in that project?

**Comment by Happypig375** [comment]
@masq6r https://github.com/fsharp/fslang-design/blob/master/tooling/FST-1027-fsi-references.md#example---projects

**Comment by masq6r** [comment]
> @masq6r https://github.com/fsharp/fslang-design/blob/master/tooling/FST-1027-fsi-references.md#example---projects

That is perfect. Thanks for your information.

**Comment by cartermp** [comment]
`#r "project:` is currently not an implemented provider, but it's certainly not being explicitly scoped out of .NET 5 at this time. Additionally, once the mechanism for `#r` providers stabilizes some more, a community implementation could be reasonably accomplished.

**Comment by dsyme** [comment]
Current status on this:

```
E:\GitHub\dsyme\dsharp-models>dotnet fsi

Microsoft (R) F# Interactive version 11.0.0.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> #r "nuget: Microsoft.AspNetCore.App";;
C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(151,5): warning NETSDK1080: A PackageReference to Microsoft.AspNetCore.App is not necessary when targeting .NET Core 3.0 or higher. If Microsoft.NET.Sdk.Web is used, the shared framework will be referenced automatically. Otherwise, the PackageReference should be replaced with a FrameworkReference. [C:\Users\Administrator\AppData\Local\Temp\nuget\26812--20fcf5f9-ba42-4eae-bdea-3643a72b72be\Project.fsproj]
C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(151,5): warning NETSDK1080: A PackageReference to Microsoft.AspNetCore.App is not necessary when targeting .NET Core 3.0 or higher. If Microsoft.NET.Sdk.Web is used, the shared framework will be referenced automatically. Otherwise, the PackageReference should be replaced with a FrameworkReference. [C:\Users\Administrator\AppData\Local\Temp\nuget\26812--20fcf5f9-ba42-4eae-bdea-3643a72b72be\Project.fsproj]
[Loading C:\Users\Administrator\AppData\Local\Temp\nuget\26812--20fcf5f9-ba42-4eae-bdea-3643a72b72be\Project.fsproj.fsx]
namespace FSI_0002.Project
```

**Comment by dsyme** [comment]
This (or perhaps some other problems?) also affect referencing Saturn, Falco, Giraffe from `dotnet fsi`, e.g.

```
 #r "nuget:Saturn";;
```

gives
```
> #r "nuget:Saturn";;
C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(151,5): warning NETSDK1080: A PackageReference to Microsoft.AspNetCore.App is not necessary when targeting .NET Core 3.0 or higher. If Microsoft.NET.Sdk.Web is used, the shared framework will be referenced automatically. Otherwise, the PackageReference should be replaced with a FrameworkReference. [C:\Users\Administrator\AppData\Local\Temp\nuget\26812--20fcf5f9-ba42-4eae-bdea-3643a72b72be\Project.fsproj]
C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(151,5): warning NETSDK1080: A PackageReference to Microsoft.AspNetCore.App is not necessary when targeting .NET Core 3.0 or higher. If Microsoft.NET.Sdk.Web is used, the shared framework will be referenced automatically. Otherwise, the PackageReference should be replaced with a FrameworkReference. [C:\Users\Administrator\AppData\Local\Temp\nuget\26812--20fcf5f9-ba42-4eae-bdea-3643a72b72be\Project.fsproj]
[Loading C:\Users\Administrator\AppData\Local\Temp\nuget\26812--20fcf5f9-ba42-4eae-bdea-3643a72b72be\Project.fsproj.fsx]
namespace FSI_0003.Project

> Saturn.Router.Get;;

  Saturn.Router.Get;;
  ^^^^^^^^^^^^^^^^^

stdin(3,1): warning FS0035: This construct is deprecated: The union type for union case 'Get' was defined with the RequireQualifiedAccessAttribute. Include the name of the union type ('RouteType') in the name you are using.

Binding session to 'C:\Users\Administrator\.nuget\packages\saturn\0.14.1\lib\netcoreapp3.1\Saturn.dll'...


unknown(1,1): error FS3216: type 'Saturn.Router+RouteType' not found in assembly 'Saturn, Version=0.14.1.0, Culture=neutral, PublicKeyToken=null'. A possible cause may be a version incompatibility. You may need to explicitly reference the correct version of this assembly to allow all referenced components to use the correct version.

```

Something looks fishy here, adding tests for #r on Saturn, Falco and Giraffe would be great.

**Comment by KevinRansom** [comment]
@dsyme , asp.net is not a framework or a set of nuget packages it is actually an sdk.  Currently we have no support for specifying that type of stuff in #r "nuget: " It will take some thought about how to add that in.  I assume it is because they do more than just add assembly references to the build.

It is going to take some time to figure out what we want to do for this scenario.

This is an ASP.NET Web project.

````
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Startup.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
````

**Comment by cartermp** [comment]
Yeah, we'll have to consider directly referencing vs. implicitly referencing through a transitive dependency (e.g., Saturn, Giraffe)

**Comment by dsyme** [comment]
See also https://github.com/dotnet/interactive/issues/861

**Comment by ronaldschlenker** [comment]
For other people who would like to use AspNetCore / Saturn / Giraffe in FSI (5.0) today, [here is a gist](https://gist.github.com/ronaldschlenker/18e7523a604e86036db177c5a06c8c24) that seems to work for a demo case. 

Please note that this _is only a workaround_ and a kind of _hack_ until this issue is solved. The version in the linked gist is hardcoded any may vary depending on the version installed on the machine running FSI as well as the set of dlls referenced.

**Comment by jkone27** [comment]
and what about this package for dotnet interactive?
https://www.nuget.org/packages/Microsoft.DotNet.Interactive.AspNetCore/

is it a better fit for fsharp scripting?

**Comment by dsyme** [comment]
Closing as tracked by https://github.com/dotnet/fsharp/issues/8688

**Comment by rstm-sf** [comment]
> Closing as tracked by #8688

@dsyme Hi, did you want to specify some other link for tracking?

**Comment by dsyme** [comment]
Thanks, yes, the correct link is https://github.com/dotnet/fsharp/issues/9417

**Comment by jkone27** [comment]
<img width="778" alt="image" src="https://user-images.githubusercontent.com/10419217/221413684-6e61be22-0036-474e-ad30-0bbad6dc1a1f.png">

any news on this one, or how to add aspnetcore to .fsx >? workarounds?

**Comment by jkone27** [comment]
also tried this to see if it could work..

```
#r "nuget: Microsoft.AspNetCore.App.Ref, 7.0.3"
```

but got this error

```
error FS3217: /Users/admin/.packagemanagement/nuget/Projects/58859--cfaf25f3-ec64-4389-974a-55538cab5132/Project.fsproj : 

error NU1213: The package Microsoft.AspNetCore.App.Ref 7.0.3 
has a package type DotnetPlatform 
that is incompatible with this project. 
```

**Comment by cartermp** [comment]
Don't rely on chatgpt for features that don't exist yet :)

**Comment by jkone27** [comment]
yeah true, i was playing around with it, wondering if it could find any work arounds

**Comment by vzarytovskii** [comment]
> yeah true, i was playing around with it, wondering if it could find any work arounds

Out of curiosity, have you tried manually referencing aspnetcore dlls in the script?

**Comment by TheAngryByrd** [comment]
I just ended up coming up with:

```fsharp
open System
open System.IO

let contains (x: string) (y: FileInfo) = y.Name.Contains x

let blockedDlls = [ contains "aspnetcorev2_inprocess" ]

module Seq =
    let filterOut predicate =
        Seq.filter (
            predicate
            >> not
        )

    let filterOutAny predicates xs =
        xs
        |> filterOut (fun x ->

            predicates
            |> Seq.exists (fun f -> f x)
        )

let dir =
    DirectoryInfo(@"C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\7.0.3")

let isDLL (f: FileInfo) = f.Extension = ".dll"

let reference (f: FileInfo) = $"#r \"{f.Name}\""

let fileReferences =
    dir.GetFiles()
    |> Seq.filter (isDLL)
    |> Seq.filterOutAny blockedDlls
    |> Seq.map (reference)

let printable = [
    $"#I @\"{dir.FullName}\""
    yield! fileReferences
]

File.WriteAllLines("Microsoft.AspNetCore.App-7.0.3.fsx", printable)
```

**Comment by jkone27** [comment]
@TheAngryByrd  was trying to debug this, but noticed we miss `.pdb` files? do they impact debug capabilities, or they are just for jumping into source DLLs. 
Are there any 2023 solutions to this one? @vzarytovskii mentioned the idea of referencing .net framework sdks as nuget packages?
