### ISSUE TITLE
C# interop - code compiles that shouldn't

### ISSUE THREAD

**Issue by Tomius** [dotnet/fsharp#8702]
When using F# objects from C# code, I've noticed a bug that the C# compiler is unable to detect uninitialised objects within switch statements.

Retro steps
--------------
Let's have a module called `FSharpLib` with the following conents:
``` F#
namespace FSharpLib

[<Struct>]
type public FSharpStringRecord = 
    {
        Value : string
    }
```

And a C# console app using the class above this way:
``` C#
using System;
using FSharpLib;

namespace CSharpApp
{
    class Program
    {
        static void Main(string[] args)
        {
            switch (true)
            {
                case false:
                    var fsharpString = new FSharpStringRecord("foobar");
                    break;
                case true:
                    Console.WriteLine($"fsharpString.Value='{fsharpString.Value}'");
                    break;
            }
        }
    }
}

```
See the attached zip for the setup: 
[UninitializedVariableDetectionBugRepro.zip](https://github.com/dotnet/fsharp/files/4323216/UninitializedVariableDetectionBugRepro.zip)

Expected behavior
-----------------------

The above C# code should not compile. It wouldn't compile if FSharpStringRecord was a C# object.

Actual behavior
--------------------

The `fsharpString` variable is defined as a local with the scope of the entire function in the IL, and the program compiles and  prints out `fsharpString.Value=''`.

Related information
-------------------------

The behaviour seems to be optimization related. If the F# record contains an integer instead a string, I get the correct compiler error. Sometimes a code compiles in Roselyn but not with msbuild (I forgot how to reproduce that).

**Comment by Happypig375** [comment]
Why is this an F# issue but not a C# issue?

**Comment by Tomius** [comment]
I am not enitrely sure if this is a bug on the C# or F# side. This doesn't happen without F# involved. It could be something wrong with generated `FSharpLib.dll` that makes the C# compiler go bad, or the compiled `FSharpLib.dll` could be perfectly valid and it could be just a C# compiler issue. 
But if it was the later, I don't understand why I can't repreoduce this bug if the library is written in FSharp. So the former seems a bit more likely to me.

**Comment by realvictorprm** [comment]
Could be something on both sides. Can you attach the corresponding C# definition?
A comparison of the IL should give some explanation what the difference is and if the C# compiler either fails to interpret something correctly or F# is missing anything.

However my gut feel is that this is a C# issue.

**Comment by Tomius** [comment]
I've found a C# only repro, so it's definitely not an F# bug. Will reopen this on the C# side.
