### ISSUE TITLE
[F#] Renaming operation should execute when pressing Ctrl + S

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#8720]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/924696/renaming-operation-should-execute-when-pressing-ct.html)._

---
[regression]
Exepected:
 Renaming operation should execute when pressing Ctrl + S.

Actual:
Renaming operation executes only when performing pressing Enter key.

This behavior use to work.

---
#### Visual Studio Feedback System on 2/20/2020, 06:10 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Sara Shi [MSFT] on 2/23/2020, 07:50 PM: 

<p>Thanks for your feedback! Could you provide your project language and template? Do you try it on other language and see if can also repro?</p>

#### Visual Studio Feedback System on 3/3/2020, 06:28 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.
#### Scott Nimrod on 3/4/2020, 01:25 AM: 

<p>Hi,</p><p>I was using F# with .Net Standard template.</p><p>I didn't observe it with C#.</p>

#### Visual Studio Feedback System on 3/4/2020, 06:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 3/5/2020, 01:01 PM: 

Thank you for reporting this issue to us. We have changed the title to better describe the problem so others can find and engage with it.
#### Visual Studio Feedback System on 3/13/2020, 07:51 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by cartermp** [comment]
Closing this out - I don't think this has ever been supported. Rename committing is also dependent on Roslyn as well; not something we control in the F# tools.
