### ISSUE TITLE
Questions about surface area API changes in recent commits

### ISSUE THREAD

**Issue by baronfel** [dotnet/fsharp#8723]
I was doing an integration of FCS (see https://github.com/fsharp/FSharp.Compiler.Service/pull/933) and as part of the post-release checks I've started doing an API Surface Area diff, to help prevent breaks in the downstream consumers of FCS and help me determine what kind of version bump is necessary.

This integration brought some new members to the API and one troublesome one that I'd like to discuss reverting. The detailed output is attached below, but the new members are:

* FSharp.Compiler.Ast.rangeOfNonNilAttrs :  attrs: FSharp.Compiler.Ast.SynAttributeList list -> FSharp.Compiler.Range.range
* FSharp.Compiler.Ast.unionRangeWithListBy : projectRangeFromThing:('A -> FSharp.Compiler.Range.range) * m:FSharp.Compiler.Range.range * listOfThing: 'A list -> FSharp.Compiler.Range.range
* FSharp.Compiler.PrettyNaming.isTildaOnlyString: s:System.String -> System.Boolean
* FSharp.Compiler.SourceCodeServices.FSharpErrorInfo: new Start and End members of type `pos`

The changed member is:
* FSharp.Compiler.PrettyNaming.IsActivePatternName : nm:System.String -> System.Boolean
  * The prior version has the parameter name as `name`, not `nm`.

These new changes for a 'Minor' version change, but the changed member requires a 'Major' change so that we don't break binary compatibility.

I'd like to discuss:

* fixing the type in `isTildaOnlyString` => `isTildeOnlyString`
* changing the name of the parameter back to `name`

<details>
<summary>detailed output of the `synver` tool</summary>

```
Version bump invalid.
  Version packaged was 34.1.2
  Version computed due to API diffs was 35.0.0
  Allowed version magnitude change is Major
  The full set of API diffs is:
        
* FSharp.Compiler.Ast

        + FSharp.Compiler.Ast.rangeOfNonNilAttrs : 
                attrs:FSharpList<FSharp.Compiler.Ast.SynAttributeList>
                -> FSharp.Compiler.Range.range

        + FSharp.Compiler.Ast.unionRangeWithListBy : 
                projectRangeFromThing:FSharpFunc<'A,FSharp.Compiler.Range.range> * m:FSharp.Compiler.Range.range * listOfThing:FSharpList<'A>
                -> FSharp.Compiler.Range.range

        
* FSharp.Compiler.PrettyNaming

        + FSharp.Compiler.PrettyNaming.IsActivePatternName : 
                name:System.String
                -> System.Boolean

        - FSharp.Compiler.PrettyNaming.IsActivePatternName : 
                nm:System.String
                -> System.Boolean

        + FSharp.Compiler.PrettyNaming.isTildaOnlyString : 
                s:System.String
                -> System.Boolean
        
* FSharp.Compiler.SourceCodeServices.FSharpErrorInfo

        + (Instance of FSharp.Compiler.SourceCodeServices.FSharpErrorInfo).End : 
                FSharp.Compiler.Range.pos

        + (Instance of FSharp.Compiler.SourceCodeServices.FSharpErrorInfo).Start : 
                FSharp.Compiler.Range.pos
``` 
</details>

**Comment by auduchinok** [comment]
#8724 fixes the `tilde` typo.

I don't entirely agree we should revert `name` to `nm`, since we've been doing lots of similar changes and it hasn't lead to a reported problem in practice once.

**Comment by cartermp** [comment]
Even though it's probably a harmless name change, let's revert it to `name` just to avoid an intentional major version rev.

**Comment by auduchinok** [comment]
@cartermp Does it imply we should avoid making such improvements in future (so the major version can stay untouched), unless there are other changes qualifying for a major version increment in the same PR?

**Comment by auduchinok** [comment]
> let's revert it to name just to avoid an intentional major version rev.
It was before `nm`, and the suggestion is to revert `name` to it.

**Comment by cartermp** [comment]
I think in general, yes, we should avoid parameter name changes unless there's a breaking change going out alongside it. Maybe a more sweeping name change across the whole API would work too.

**Comment by dsyme** [comment]
>I think in general, yes, we should avoid parameter name changes unless there's a breaking change going out alongside it. Maybe a more sweeping name change across the whole API would work too.

As we only update FCS via bulk integration from dotnet/fsharp --> fsharp/FSharp.Compiler.Service, each time we did this previously we bumped the major revision number on the assumption that something had changed.  There's never been any attempt to avoid major version bumps and keep binary compat. This technique is blunt but effective and it keeps revision updates reasonable, and people working on the compiler didn't need to worry about binary compat.

I think this approach should likely just be followed and we do a major bump in the FCS repo on each integration.

Until we do an end to end sweep over the whole FCS API including a mass deprecation the prospect of binary compat looks unlikely.

**Comment by baronfel** [comment]
@dsyme I'd agree except then I'm stuck doing updates for all the tooling across the ecosystem to keep regular updates to FSAC flowing (beacuse FSAC takes library dependencies on fsharplint, fantomas, etc). In an attempt to limit the amount of additional work I have to do I started looking at these diffs. This is very much a selfish endeavor for me personally :)

**Comment by dsyme** [comment]
> @dsyme I'd agree except then I'm stuck doing updates for all the tooling across the ecosystem to keep regular updates to FSAC flowing (beacuse FSAC takes library dependencies on fsharplint, fantomas, etc). In an attempt to limit the amount of additional work I have to do I started looking at these diffs. This is very much a selfish endeavor for me personally :)

Perhaps we could script the auto-creation of FCS update PRs for these?

**Comment by baronfel** [comment]
Closing as discussion was sufficient for me, thanks everyone.
