### ISSUE TITLE
Single postfix type argument cannot be parsed in a `new` expression

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#8725]
When there are multiple prefix type arguments, a `new` expression is parsed successfully (emitting a warning). When there's a single argument, the parser fails, like in the `List` cases below.

```fsharp
open System.Collections.Generic

let d1: (int, string) Dictionary = null
let d2 = new (int, string) Dictionary ()

let l1: int List = null
let l2 = new int List ()
let l3 = new (int) List () 
```

<img width="471" alt="Screenshot 2020-03-16 at 19 35 50" src="https://user-images.githubusercontent.com/3923587/76780007-5e7dbd00-67bd-11ea-8543-252e3bf35854.png">

**Comment by cartermp** [comment]
This smells like by design to me given the nature of the warnings. @dsyme?

**Comment by auduchinok** [comment]
The issue it not about the warnings, it's about errors in parser in the end of the snippet. I've updated the issue description.

**Comment by cartermp** [comment]
Aha, yes indeed. I suppose that would count as a bug then.

**Comment by dsyme** [comment]
I don't think we should fix this.  We strongly discourage the used of postfix type arguments - espcially in `new` - and the fact that one case gives an error and the other a warning is pretty much ok by me.

**Comment by auduchinok** [comment]
It would be really great to have a consistency here: either both cases are errors, or both are warnings. The current way looks unpredictable unless you know the parser rules and other things here.

**Comment by abelbraaksma** [comment]
In title and comments I see "postfix", but surely this is about "prefix", right? The type arguments are _before_ the identifier or statement.

(side note, this is the first time I see this syntax, at least consciously, and that's after 8 years F# ;)

(side note 2, I sometimes accidentally try to use a cast with C# syntax, it appears to me that that's essentially this prefix syntax, though I've always seen some error, as in your last example)
