### ISSUE TITLE
Invoking `dotnet fsi` with langversion:preview is order dependent

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#8749]
Assuming you have an F# script called `script.fsx`, the following command works:

```
dotnet fsi --langversion:preview script.fsx
```

However, the following does not:

```
dotnet fsi script.fsx --langversion:preview
```

It's not uncommon for people to place flags that don't associate with an argument at the end of a command, so this should probably work.

**Comment by KevinRansom** [comment]
No!!!!!!!!!!!!!!!!!! you must be mistaken

**Comment by KevinRansom** [comment]
Look at the help:

I see the behaviour too.
````
Usage: dotnet.exe <options> [script.fsx [<arguments>]]
````
It clearly states that options are before files.  So ... I guess it's by design.  I suppose this is less ambiguous than deciding what this should do:
````
dotnet fsi script.fsx --langversion:preview script1.fsx --langversion:4.7
````

**Comment by cartermp** [comment]
Tagging as a feature improvement rather than a bug in case others come across this. Since it's by design I'm not too tickled by the behavior. But figuring out a better design would be pretty neat. Any interested community members should feel free to submit a PR!

**Comment by dsyme** [comment]
It is by design
