### ISSUE TITLE
Slow down in Visual Studio Preview with Package references for F# scripts

### ISSUE THREAD

**Issue by toburger** [dotnet/fsharp#8757]
The editor of Visual Studio Preview gets extremely (at this stage unusable) slow after referencing a NuGet package in a F# script file.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Enable preview language features:
![image](https://user-images.githubusercontent.com/728782/77147515-b4888400-6a8d-11ea-9e2c-effa77d3bc07.png)

2. Reference a NuGet package, e.g. ``#r "nuget: ML"``

3. Certain actions cause the editor to slow down very noticeably (hit enter, wait for the auto completion list)

**Expected behavior**

![BOVi6RlVl4](https://user-images.githubusercontent.com/728782/77148324-99b70f00-6a8f-11ea-8e5f-6d8b75c3a422.gif)

**Actual behavior**

*It's hard to tell from the screen capture, but I deliberately typed very slow to wait for the auto completion to kick in...*

![A5siiOcMAT](https://user-images.githubusercontent.com/728782/77148671-48f3e600-6a90-11ea-9aa2-266d0d0ba408.gif)

**Related information**

* Windows 10 Insider; Version 2004 (Build 19041.153)
* .NET 5 Preview
* Microsoft Visual Studio Preview Community
* Surface Laptop Gen1 i5

**Comment by cartermp** [comment]
Thanks for the report @toburger. We'll need to make sure the IDE support is in good shape before going live with F# 5. Right now we've only been focused on getting the core mechanism right, so IDE support will likely follow in the next set of previews.

**Comment by MaxWilson** [comment]
This issue is driving me mad, but fortunately if I comment out the nuget reference the issue goes away. I have a feeling that the issue may be that it's doing actual IO (talking to Nuget.org) during intellisense checking.

An alternate workaround that I tried was to enable "Enable stale data for Intellisense features" and turn the time down to 10 ms, but that did not help.

**Comment by jonsagara** [comment]
Hi, is this scheduled to be fixed before the full release of VS 16.8.0?

**Comment by cartermp** [comment]
We would like to get this resolved by VS 16.8, yes. @KevinRansom was looking into this before a more urgent bug arose.

**Comment by cartermp** [comment]
This is unlikely to get resolved by 16.8. Sorry. The feature is not ready for use within VS. Moving out.
