### ISSUE TITLE
Can we use a placeholder(_) to partially apply a function?

### ISSUE THREAD

**Issue by greatim** [dotnet/fsharp#8767]
ex:
```
let foo a b c = a - b - c
let foo2 a c = foo _ 4 

foo2 10 2 // it return (10 - 4 - 2)
```

**Comment by Happypig375** [comment]
The code is now very ambiguous. I don't support this.

**Comment by cartermp** [comment]
@greatim could you search for a similar suggestion, or if ones doesn't exist, file one here? github.com/fsharp/fslang-suggestions/ Thanks!
