### ISSUE TITLE
F# project/properties/debug change does not take affect until VS restart

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#8818]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/907936/f-projectpropertiesdebug-change-does-not-take-affe.html)._

---
Visual Studio16.4.4

In F# running debug on a default netcoreapp3.0, once you have run it once, changing the Application arguments in project/properties/debug, the new arguments do not take affect, even though they get saved to <project>\Properties\launchSettings.json. 

You have to close and reopen VS.
Possibly close and reopen Solution also works.

---
#### Visual Studio Feedback System on 2/5/2020, 11:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 3/12/2020, 07:27 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by cartermp** [comment]
Could this be probably related to the workspace-level issue we have where you need to close/re-open a solution to get certain P2P changes from C# propagated through? cc @TIHan

**Comment by dsyme** [comment]
I don't repro this, i tried just now both savnig and not-saving the changes to the project settings.
