### ISSUE TITLE
ContactServiceModePacckage package did not load

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#8821]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/701995/contactservicemodepacckage-package-did-not-load.html)._

---
What steps will reproduce the problem?
1. load solution after building in powershell from https://github.com/aardvark-platform/aardvark.docs

---
#### Visual Studio Feedback System on 8/21/2019, 03:31 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/8/2019, 02:23 AM: 

I have detected that for the last 35 days, this issue didn't have any product team activity and a very small amount of new votes or comments.&nbsp;Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Jack Fox on 10/22/2019, 10:07 AM: 

opening solution in 16.3.0 Preview 4 triggered this<br>from ActivityLog.xml<br> <br>  SetSite failed for package [ContactServiceModelPackage]Source: 'mscorlib' Description: Collection was modified; enumeration operation may not execute.<br>System.InvalidOperationException: Collection was modified; enumeration operation may not execute.<br>   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)<br>   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()<br>   at System.Collections.Generic.List`1.Enumerator.MoveNext()<br>   at Microsoft.VisualStudio.LiveShare.ContactServiceModel.ContactServiceProviderModeld__44.MoveNext()<br>--- End of stack trace from previous location where exception was thrown ---<br>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>   at Microsoft.VisualStudio.LiveShare.ContactServiceModel.ContactServiceModeld__61.MoveNext()<br>--- End of stack trace from previous location where exception was thrown ---<br>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>   at Microsoft.VisualStudio.LiveShare.ContactServiceModel.ContactServiceModelPackaged__16.MoveNext()<br>--- End of stack trace from previous location where exception was thrown ---<br>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)<br>   at Microsoft.VisualStudio.LiveShare.ContactServiceModel.ContactServiceModelPackaged__15.MoveNext()<br>--- End of stack trace from previous location where exception was thrown ---<br>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>   at Microsoft.VisualStudio.Shell.AsyncPackage<>c__DisplayClass19_0
#### Visual Studio Feedback System on 3/27/2020, 11:49 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by cartermp** [comment]
Might have been a misake to dupe this one to GitHub, since the posted log implicates a failure in live share. @srivatsn any thoughts? https://developercommunity.visualstudio.com/content/problem/701995/contactservicemodepacckage-package-did-not-load.html

**Comment by srivatsn** [comment]
@BrunoGuardia @mlacouture

**Comment by mlacouture** [comment]
We fixed this issue recently, you can get the fix by downloading the latest version of the [Live Share extension](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsls-vs) in the VS Marketplace or upgrading VS to the latest version.

**Comment by cartermp** [comment]
Thanks @mlacouture for confirming!

**Comment by mlacouture** [comment]
someone in the team just made me realize that the fix may not yet be available in VS but it is available in the extension in the VS marketplace ...

**Comment by cartermp** [comment]
That's probably fine. Will it make 16.6? I can just tag it as such here and anyone who has a question can just refer to the milestone.

**Comment by mlacouture** [comment]
Yes, it should be in for 16.6 Preview 2

**Comment by Hefaistos68** [comment]
This bug definitely was not resolved and its not even related to fsharp as I see this in my C# solution in VS 2022 17.4.3. 
I just opened a ticket on  https://developercommunity.visualstudio.com/t/The-ContactServiceModelPackage-packag/10246265
Seemingly it has something to do with permissions, or does it? Who knows what the heck this package even does.
