### ISSUE TITLE
VS 16.4 preview fails build of F#  .NET 4.7.2 project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#8822]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/794816/vs-164-preview-fails-build-of-f-net-472-project.html)._

---
[regression] [worked-in:16.3.6]
Some combination of VS 16.4 previews 1 & 2 and the installation of dotnet sdk 3.1.100-preview causes problems for build of an F# .NET 4.7.2 project building from FAKE build program, even when building with dotnet 3.0.100 sdk (not 3.1.100).

Building internally in VS 16.4 preview works, because it uses a different version of MSBuild.

The resulting error looks like a variation of this problem:

https://stackoverflow.com/questions/56862089/cannot-find-command-dotnet-ef/56876020#comment103285631_56876020

the output messages are:

Could not execute because the specified command or file was not found.
         Possible reasons for this include:
           * You misspelled a built-in dotnet command.
           * You intended to execute a .NET Core program, but dotnet-@C:\Users\jackf\AppData\Local\Temp\tmp75c598ec34944633925ed32feffbe40f.rsp does not exist.
           * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
		   
C:\Program Files\dotnet\sdk\3.0.100\FSharp\Microsoft.FSharp.Targets(277,9): error MSB6006: "dotnet.exe" exited with code 1. 

Uninstalling VS 16.4.0 preview 2, which also uninstalls dotnet sdk 3.1.100-preview fixes the problem

---
#### Visual Studio Feedback System on 10/27/2019, 11:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 11/28/2019, 06:54 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Jon Sequeira [MSFT] on 3/27/2020, 11:58 AM: 

<p>It appears that the script you’re using to build your command line invocation, something like <code>dotnet $PATH_TO_FSC $RESPONSE_FILE</code> is getting an empty value for <code>$PATH_TO_FSC</code>.</p>

---
### Original Solutions
(no solutions)

**Comment by cartermp** [comment]
Tagging as `nee more info`, this is not likely to be an F# bug

**Comment by jackfoxy** [comment]
I've long moved on from this problem and so has the VS version. @cartermp  you should close this. I don't know how to recreated it.

**Comment by cartermp** [comment]
Thanks @jackfoxy
