### ISSUE TITLE
Setting --tailcall- in FSI commandline options is ignored in VS2019

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#8831]
Whatever combination of FSI startup options I try, none of them seems to have any effect. All I'm trying to do is to see the difference between TCO and non-TCO effects on some functions, but it appears that the settings are ignored.

I tried _Reset Interactive Session_, `#quit` + return, and restarting VS.

![image](https://user-images.githubusercontent.com/16015770/77850740-be6c5e80-71d4-11ea-936f-ba643f04baae.png)

**Repro steps**

Change any settings by adding [commandline arguments](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/fsharp-interactive-options), reset and observe behavior.

**Expected behavior**

Commandline options should work, after all they're advocated as _"Additional command line arguments passed tot he F# Interactive executable"_. That doesn't appear to happen.

**Actual behavior**

No observable change in FSI.

**Known workarounds**

Probably: run it by hand from the commandline instead of from VS. But that defeats the purpose. Otherwise, none that I know of.

I'm probably missing something obvious here as I'm quite certain that in the past I was able to run it with different settings, but I can't replicate that in any way. In fact, it appears to always run in RELEASE mode, except when I select to enable debugging.

**Related information**

* OS: Windows 7/10
* VS Version 16.4.1 Pro. Also observed in VS2017 Pro

**Comment by abelbraaksma** [comment]
A little more research shows that running it in a cmd window, the `consolecolors` option _does_ work, so that one only works outside of VS. It also showed that:

* `-g+` or `-g-` throws error FS0243, unrecognized option (docs say it is equiv. to `--debug`)
* `--debug+` or `--debug:full` has no effect on TCO
* `--tailcall-` has no effect on TCO, also not when combined with `--debug:full`

In all cases, TCO seems to be performed. I used the following function to test TCO. It blows up when compiling with `fsc.exe` using standard `DEBUG` settings. But I cannot get it to blow up with `fsi.exe`.

```f#
let map (func: 'a -> 'b) (input: 'a list): 'b list = 
    let rec loop cont = 
        function 
        | [] -> cont [] 
        | x::xs -> loop ( fun acc -> cont (func x::acc) ) xs 
           
    loop id input 
```
Calling it with something like `map id [1..10000000] |> List.last;;` should blow up.

**Comment by cartermp** [comment]
I've never used these before, but I assume they used to work in VS 2015 or earlier.

**Comment by kevmal** [comment]
Don't think this is an issue with VS. Tested "16.6.0 Preview 6.0" and "16.5.5", the parameters get passed, and I don't think `consolecolors` was ever supported in VS. That still leaves the potential issues  with fsi itself (`-g` option unrecognized,  `--tailcall`, ...)

**Comment by abelbraaksma** [comment]
Glad this is fixed. If I understand the resolution correctly, running fsi from within VS will still exhibit this bug, but running it on the commandline is fixed.
