### ISSUE TITLE
Regression: indexing with type annotation fails to parse

### ISSUE THREAD

**Issue by Tarmil** [dotnet/fsharp#8844]
The following code:

```fsharp
let a = [| 1 |]
let f y = a.[y:int]
```

fails to compile when using .NET SDK 3.1.200 (fsc 10.8 for F# 4.7):

```
C:\my\tests\net30\Program.fs(6,19): error FS0010: Unexpected symbol ']' in expression [C:\my\tests\net30\net30.fsproj]
C:\my\tests\net30\Program.fs(6,13): error FS0598: Unmatched '[' [C:\my\tests\net30\net30.fsproj]
```

whereas it succeeds with SDK 3.0.100 (fsc 10.6 for F# 4.7).

I'm guessing there were changes in the parser to implement reverse indexes?

**Comment by TIHan** [comment]
@Tarmil you might be right that it could be the result of the reverse index parser changes. I'm making this top priority to investigate and fix the issue.
