### ISSUE TITLE
Memory mapped file fails to be created with byte length of zero

### ISSUE THREAD

**Issue by TIHan** [dotnet/fsharp#8851]
ASP .NET Core assemblies contain resources with no data in them. Because I changed the way we handle memory in our compiler, we have a bug that doesn't take into account the byte length being zero when creating memory mapped files. AFAIK, this does not occur when compiling, but only for tooling.

Offending code is in `bytes.fs` on `ByteMemory.CreateMemoryMappedFile`.

**Comment by auduchinok** [comment]
@TIHan Is it the same error you've seen?
<img width="1593" alt="Screenshot 2020-04-02 at 16 02 52" src="https://user-images.githubusercontent.com/3923587/78254205-3b157a80-74fe-11ea-8cb6-e2d8e6908b41.png">
