### ISSUE TITLE
COVID-19 impact on this repository

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#8879]
Hey folks,

The COVID-19 pandemic has impacted nearly all aspects of society, and this repository is also not free from that. The Microsoft contributors to F# are all working remotely as opposed to being in office spaces. Since most of us don't normally work remotely, and children are also home from school, this means there has been and will continue to be a loss of productivity. We'll do our best to stay on top of issues and PRs, in addition to landing the F# 5 feature work we have in mind. But it may take us longer to get some things done, including reviews of OSS contributions, fixing up CI issues, etc. Hopefully we can get into a better groove in the coming months.

This can be inconvenient for OSS contributors, and we want to acknowledge and apologize if it feels like we're ignoring some of your contributions.

Thanks for your patience!

**Comment by abelbraaksma** [comment]
Stay home, stay safe!

(if anything, I had the feeling the repository was getting more traction, not less, as of late, which I attributed to people working from home)
