### ISSUE TITLE
Missing method exception, .NET 5

### ISSUE THREAD

**Issue by kerams** [dotnet/fsharp#8881]
Create a console application targeting `netcoreapp5.0`, install the 5.0.100-preview.2.20176.6 SDK, and reference https://www.nuget.org/packages/FSharp.Data.Npgsql/0.2.6-beta. Finally make sure to have a live instance of Postgres available.

```fsharp
type P = FSharp.Data.Npgsql.NpgsqlConnection<"host=localhost;port=5432;username=postgres">

[<EntryPoint>]
let main argv =
    let x = P.CreateCommand<"select 1">("localhost:5432")
    let r = x.Execute()
    0
```

`dotnet run` this.

**Expected behavior**

Program executes fine.

**Actual behavior**

```
Unhandled exception. System.MissingMethodException: Method not found: 'System.Type System.Type.GetType(System.String, System.Boolean)'.
   at Tests.main(String[] argv)
```

* Windows 10
* .NET 5.0.100-preview.2.20176.6

Apologies if this turns out to be a problem in the type provider.

**Comment by abelbraaksma** [comment]
In the rare cases that I had such exceptions, they were due to problems with assembly resolution (for instance, nugetting System.Memory and referencing System.Collections.Generic.Immutable leads to similar problems). Is it possible that that's the case here? 

The resolution on such cases can be to check if a specific version is referenced. Then make it generic, and add a binding redirect.

(that's as a workaround, the error as displayed shouldn't appear at all, I think)

**Comment by kerams** [comment]
I don't think so? This sample only references FSharp.Data.Npgsql, which depends on Npgsql and Npgsql.LegacyPostgis.

**Comment by cartermp** [comment]
Possibly related as well: https://github.com/dotnet/fsharp/issues/8913

I suspect there is a regression going on the core type provider mechanism that is leading to these issues

**Comment by OnurGumus** [comment]
I have observed the same behavior with VS 2019 preview, not using. Net 5, along with fsharp sql provider. Same code runs with normal vs and vs preview compiled code doesn't work.

**Comment by KevinRansom** [comment]
@OnurGumus ,
could you give us a small repro, the FSharp.Data type provider seems to work fine on DotNet 5.0.

So I will need to see the failure to try and figure out wht SqlDataProvider and perhaps NPgsql have an issue.

@kerams, I have not used postgressql in my life, however, I downloaded and installed it, but it complained about not having the postgres role.

Could you provide me with a simple from the start set of install instructions, that will allow me to reproduce your issue.

Thanks

Kevin

**Comment by KevinRansom** [comment]
Actually Phillip, seems to have provided one here:  https://github.com/dotnet/fsharp/issues/8743.

**Comment by kerams** [comment]
@KevinRansom, yes, that one's for FSharp.Data. For FSharp.Data.Npgsql, just launch a Docker container (in WSL for instance) using `docker run --rm -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres:12-alpine` and change the connection string in the sample on the top `"host=localhost;port=5432;username=postgres; password=postgres"`

**Comment by OnurGumus** [comment]
@KevinRansom it's not dotNet problem. It's Visual studio preview problem. I have never installed dotnet 5. Same code runs fine when compiled with rtm but not when compiled with preview. Sample project https://github.com/OnurGumus/FBlazorShop

**Comment by KevinRansom** [comment]
@OnurGumus, I think the bug is in master branch and dev16.6 branch, the dev 16.5 branch doesn't have it.  I have a suspicion about what caused it, and I will work on a fix this week.

Kevin
