### ISSUE TITLE
Non deterministic base dir in stack traces

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/fsharp#8883]
SDK: 3.1.102

```
System.InvalidOperationException: ValueOption.Value
   at Microsoft.FSharp.Core.FSharpValueOption`1.get_Value() in E:\A\_work\130\s\src\fsharp\FSharp.Core\prim-types.fs:line 2934
```

It seems something broke in this area which caused non deterministic paths to be shipped.

**Comment by cartermp** [comment]
@NinoFloris can you share a repro? I assume you're using `PathMap`?

**Comment by NinoFloris** [comment]
Ha yes there were clues in the trace but, `ValueNone.Value` should do the trick 😃 (probably any exception from Fsharp.core)

**Comment by NinoFloris** [comment]
Any luck here @cartermp ?

**Comment by cartermp** [comment]
Sorry, I initially misunderstood the bug here. Yes, there's no PathMap getting applied to FSharp.Core and it's just including the path of the CI machine it was built and shipped on. cc @brettfo @jonsequitur

**Comment by baronfel** [comment]
@KevinRansom per the discussion on #9379 (and the deeper issue linked in https://github.com/dotnet/msbuild/issues/5398), would it make sense to copy/paste or translate the existing MapSourceRoot task + target file changes into here, including tests? If so, I can have those changes ready to go shortly.
