### ISSUE TITLE
Async.Sleep with TimeSpan

### ISSUE THREAD

**Issue by stmax82** [dotnet/fsharp#8896]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I write `do! Async.Sleep(10)` and it doesn't sleep for 10 seconds.

**Describe the solution you'd like**

I'd prefer Async.Sleep to take a TimeSpan because with `do! Async.Sleep(TimeSpan.FromHours(1.25))` the intention is clear.

**Describe alternatives you've considered**

I always use `do! Async.Sleep(TimeSpan.FromSeconds(10).TotalSeconds |> int)` and then change it to `do! Async.Sleep(TimeSpan.FromSeconds(10).TotalMilliseconds |> int)` a few seconds later.

**Comment by cartermp** [comment]
I think an overload to `Sleep` that calls the existing `Sleep` would be fine. One potential point of contention is that overloads to the `Async` static class holder aren't common but I don't see much an issue with that. Would you be interested in contributing this addition?

**Comment by stmax82** [comment]
> Would you be interested in contributing this addition?

I can try, first time building this project though.. I managed to run build.sh and build.sh --test successfully.. so I guess I'm good to go.

What would it take.. adding the overload to Sleep in async.fs and async.fsi and a few tests in AsyncModule.fs.. anything else?

> I think an overload to Sleep that calls the existing Sleep would be fine.

It looks like this can break some existing code due to missing type annotations. Here's some code that I found in AsyncModule.fs:

```
let returnAfter time f = async {
  do! Async.Sleep time
  let _ = Interlocked.Increment completed
  return f ()
}
```

For this to compile again a type annotation around `(time:int)` had to be added.

Any recommendations how this should be handled?

One more thing that comes to mind is that TimeSpans can handle much longer delays than milliseconds stored in Int32 (about 25 days).

Would it be fine to use a Checked.int32 conversion? This would throw an OverflowException if a TimeSpan with TotalMilliseconds > Int32.MaxValue is passed in.

Alternatively the current Sleep code could be changed to use int64 and then be called from both overloads of Sleep. An OverflowException could still be thrown, but only if someone tried to sleep for more than 290M years.

**Comment by abelbraaksma** [comment]
I'd wonder if adding an overload might break existing code (outside of the f# compiler). If so, whether that would be considered a breaking change, or small enough to allow the addition.

I'd assume that binary compat remains the same, as overloads are resolved at compile time afaik. 

If it's indeed a breaking change, we might consider a different name for the overload instead, then there wouldn't be any problem.

**Comment by cartermp** [comment]
@abelbraaksma  Any time an overload to a method with a single parameter is added anywhere, it is a potential breaking change for F#. This is because some F# programmers will use type inference for the input parameter. So that means code like this could break:

```fsharp
open System

type C =
    static member M (x: int) = ()
    static member M (x: TimeSpan) = ()

let f x =
    C.M x // Error, type annotation is needed

f 12
```

But of course code that simply calls a overloaded member will be fine:

```fsharp
open System

type C =
    static member M (x: int) = ()
    static member M (x: TimeSpan) = ()
    
C.M 12
C.M (TimeSpan(12L))
```

However I don't think there are enough of these cases in the wild to justify never adding an overload. These members are static members instead of module-bound functions because of the flexibility with adding overloads and optional parameters. So I'm not too concerned.

**Comment by abelbraaksma** [comment]
> So I'm not too concerned.

Good to hear that. Then I'm not concerned either ;). 

Just realizing that the .NET Core libraries constantly get new overloads in new versions, that potentially lead to similar issues. If it fine there, it should be fine here.

**Comment by cartermp** [comment]
This one is done.

**Comment by siwatanejo** [comment]
What's the first version of FSharp.Core that includes this as non-experimental/preview?
