### ISSUE TITLE
Invalid comparison code generated when anonymous record has more than 4 fields

### ISSUE THREAD

**Issue by nasserbrake** [dotnet/fsharp#8908]
If you create a normal F# Map using an anonymous record with five fields as the key, using Release build, the application fails:

```fsharp
let good = Map [ {| A = ""; B = ""; C = ""; D = ""; |}, () ]
good.TryFind {| A = ""; B = ""; C = ""; D = ""; |} |> printfn "%A"

let bad = Map [ {| A = ""; B = ""; C = ""; D = ""; E = "" ;|}, () ]
bad.TryFind {| A = ""; B = ""; C = ""; D = ""; E = "" ; |} |> printfn "%A"
```
This is the error message:

```
Unhandled exception. System.FieldAccessException: Attempt by method '<StartupCode$Migration>.$Program+clo@1-1<TA,TB,TC,TD,TE>.Invoke(Microsoft.FSharp.Core.Unit)' to access field '<>f__AnonymousType107323762`5<System.__Canon,System.__Canon,System.__Canon,System.__Canon,System.__Canon>.A@' failed.
   at <StartupCode$Migration>.$Program.clo@1-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Collections.MapTreeModule.tryGetValue[TKey,TValue](IComparer`1 comparer, TKey k, TValue& v, MapTree`2 m) in E:\A\_work\130\s\src\fsharp\FSharp.Core\map.fs:line 142
   at Program.main(String[] args)
```

If you use a normal F# record, it all works.

**Comment by DalekBaldwin** [comment]
Related? https://github.com/xunit/xunit/issues/2088

**Comment by nasserbrake** [comment]
Yes, this is the same issue.

**Comment by cartermp** [comment]
This doesn't reproduce with VS 2019 16.5 in a .NET Core app for me:
![image](https://user-images.githubusercontent.com/6309070/79260440-1fd23580-7e43-11ea-8aa5-98498b1bf09c.png)

Could you share some more information about your environment?

**Comment by cartermp** [comment]
This also doesn't fail for me with .NET Core 3.1 (SDK 3.1.201) on macOS either.

**Comment by nasserbrake** [comment]
Hi,
I can reproduce this if I run the project in Release configuration.  In Debug it works fine. 

Best

**Comment by 0x53A** [comment]
It reproduces for me

![image](https://user-images.githubusercontent.com/4236651/80024793-e1daae80-84df-11ea-8aec-d156831df15a.png)

VS 16.5.4, netcoreapp3.1, .net sdk 3.1.201

**Comment by cartermp** [comment]
Thanks, I hadn't seen the Release bit.

**Comment by cartermp** [comment]
cc @dsyme

**Comment by isaacabraham** [comment]
I think this is related to comparison / equality checks. This is I think the same as what is happening [here](https://compositional-it.visualstudio.com/Farmer/_build/results?buildId=3877&view=logs&j=022b0a5d-2698-5f72-7610-a845972a8b4c&t=f00c60ef-f0e1-5faf-62eb-3410b25fc2a4&l=175) on Farmer

**Comment by isaacabraham** [comment]
Indeed, moving to a formal record fixed the issue.

**Comment by dsyme** [comment]
Yes, this is a bug. The optimizer is applying a rule to split the anonymous record comparison and equality methods into multiple smaller methods to avoid large code size.  However the anonymous record fields are `private` (while record fields are `internal` along with most other generated constructs - partly to allow this kind of code transformation).

We have to either

1. make the anonymous record fields internal 

2. don't apply the code transformation to these methods
