### ISSUE TITLE
None Update ignored in F# projects

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#8914]
Create a console app similar to this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Update="test.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
```

then build it.

Note that under the bin folder, `test.json` is not included. In a C# project, it is included. This doesn't require VS to reproduce, so it's likely us.

**Comment by cartermp** [comment]
This results in some problems when using Azure stuff like Functions: https://github.com/Azure/Azure-Functions/issues/1177

**Comment by abelbraaksma** [comment]
I've a bunch of these in my projects, I use it for test data files for instance, but AFAIK, they still work (my VS is one or two months behind), so this may be a recent regression.

**Comment by 0x53A** [comment]
I think F# does not have the default includes, so you need  ``<None Include=``. Update only works if the thing is already included, otherwise it's a no op

**Comment by abelbraaksma** [comment]
You're right, I have None Include. My bad.

**Comment by pihai** [comment]
Is there any chance that F# gets default includes for this? If not then the Azure Functions Project template should simply be changed to use `<None Include=>`.

[Azure Functions Project Template](https://github.com/Azure/azure-functions-templates/blob/dev/Functions.Templates/ProjectTemplate/FSharp/Company.FunctionApp.fsproj)

**Comment by aaronpowell** [comment]
@pihai - I've opened a PR today for this: https://github.com/Azure/azure-functions-templates/pull/954

**Comment by vjraitila** [comment]
Is having explicit includes for individual files really the best approach? This causes a problem for files where the need to include them is situational e.g. local.settings.json for Azure Functions - you want it during local development, but said file is not available during a CI build, for example.

To me there seems to be two conflicting goals of both keeping the project definition terse - hence the default includes - as well as wanting to be explicit. While far from being an expert on this matter, I sort of understand the compilation order aspect when it comes to F# (source files), but I'm not entirely convinced the same principle should be applied to other project artifacts as well.

**Comment by cartermp** [comment]
@KevinRansom any thoughts on this? It's definitely in our camp since this can reproduce outside of VS. It means that F#-defined azure functions bundle up files that shouldn't be required for a deployment.

**Comment by KevinRansom** [comment]
I will take a look.

**Comment by Kurren123** [comment]
Just had this issue in an azure functions app template. Would be great if `<None Include=` did the same thing in a `.fsproj` as a `.csproj`.

**Comment by davkean** [comment]
@cartermp Why doesn't F# SDK glob None/Content? Only Compile items need to be specified explicitly.

**Comment by KevinRansom** [comment]
@davkean -- it has been pointed out recently.  I imagine we will address this, when we get some bandwidth.

**Comment by KevinRansom** [comment]
Now we know why we don't glob None and Content.  Gloobbing impacts the order that the project system finds folders, which impacts the file ordering displayed in the solution explorer.
