### ISSUE TITLE
Ngen and GAC

### ISSUE THREAD

**Issue by ThermalLan** [dotnet/fsharp#8951]
I try to save some changes to a game that I'm trying to mod but when I go to save the module it tells me to run NGEN.exe, I've been trying to install it but I haven't had any luck, is there a way for me to fix this and get Ngen installed?

**Comment by cartermp** [comment]
@ThermalLan this issue doesn't seem to be related to F# at all, since it sounds like you're not able to install NGEN? If so, I recommend StackOverflow for questions like this.

**Comment by ThermalLan** [comment]
I'm sorry, I just got into this kind of stuff so I don't really know what I'm doing all that much.
