### ISSUE TITLE
F# language feature status ?

### ISSUE THREAD

**Issue by leandromoh** [dotnet/fsharp#8952]
C# has a list of [language feature status](https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md) to give visibility of what is being implemented. 

Does we have something similiar? [Language version history](https://github.com/dotnet/fsharp/blob/master/Language-Version-History.md) is nice but the purpose is another.

**Comment by cartermp** [comment]
F# language features are tracked here: https://github.com/fsharp/fslang-design

And current work-in-progress PRs that are candidates for inclusion are tagged like this: https://github.com/dotnet/fsharp/pulls?q=is%3Apr+is%3Aopen+label%3A%22Candidate+for+F%23+vNext%22

Does that help?

**Comment by cartermp** [comment]
I'll close this out. I don't think we intend on tracking status in this repo.
