### ISSUE TITLE
[Optimization] Infer or respect IsReadOnly on all structs to remove unnecessary copies

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/fsharp#8970]
C# has the possibility to mark types and members as readonly on structs to signal to roslyn no defensive copies have to be performed. F# with its immutable by default semantics should take advantage of this to gain end users some automatic perf improvements.

Relevant language feature docs:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct#readonly-struct

**Comment by NinoFloris** [comment]
Update: `IsReadOnly` on a method *is* optimized today in the compiler https://github.com/dotnet/fsharp/blob/6b1af129b798d0b3b7c296b27e8c2a5ad4f1dad8/src/fsharp/infos.fs#L1280-L1281 (thanks @baronfel). However for methods that are part of a `readonly struct` roslyn does not emit the attribute for every method, and the compiler seems to be missing a lookup on the struct itself for readonly to mark all members as such.

**Comment by T-Gro** [comment]
@NinoFloris  you are right, and it is actually even worse.

If a struct is marked as readonly, Roslyn removes the readonly attribute on method level, and only keeps the top level one on the struct itself.
This is definitely helpful, I will have a look and what can be done.

![image](https://user-images.githubusercontent.com/46543583/193015717-b30b9e01-2a26-4796-bf73-847bbf74f5e0.png)
