### ISSUE TITLE
Go to Definition via f12 fails - Linked file to Linked file

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#8994]
Latest dogfood build.

Open `AugmentWithHashCompare.fs`, line `638`. Hit f12 on `mkCallGenericHashWithComparerOuter`.

Expected:

Navigates to `TypedTreeOps.fs`, line `6789`.

Actual:

![image](https://user-images.githubusercontent.com/6309070/79601483-b7cb5b80-809d-11ea-99fa-9d3723e41796.png)

Something's probably not quite right here again, since we do get the correct ranges from QuickInfo and can navigate from there.

**Comment by cartermp** [comment]
I think this has to do with navigating between linked files. The following works:

Normal file --> linked file
Normal file --> normal file

**Comment by cartermp** [comment]
Ugh, unfortunately it's not that simple. A simple repro project like this works:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Files/File2.fs">
      <Link>File2.fs</Link>
    </Compile>
    <Compile Include="Files/File1.fs">
      <Link>File1.fs</Link>
    </Compile>
    <Compile Include="Program.fs"></Compile>
  </ItemGroup>

</Project>
```

I hope this isn't more F# codebase exceptionalism...

**Comment by dsyme** [comment]
This is same as #13986
