### ISSUE TITLE
build.cmd hexadecimal value 0x00 error

### ISSUE THREAD

**Issue by ingted** [dotnet/fsharp#8995]
Please provide a succinct description of the issue.

**Repro steps**

Provide the steps required to reproduce the problem:

1. git clone and execute build.cmd

**Expected behavior**

build finished

**Actual behavior**

Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 34.1 ms for M:\fsharp\src\fsharp\FSharp.Core\FSharp.Core.fsproj.
  Restore completed in 34.07 ms for M:\fsharp\src\fsharp\FSharp.Build\FSharp.Build.fsproj.
  Restore completed in 15.27 ms for M:\fsharp\src\fsharp\FSharp.Core\FSharp.Core.fsproj.
  Restore completed in 2.77 ms for M:\fsharp\src\fsharp\FSharp.Build\FSharp.Build.fsproj.
M:\fsharp\.dotnet\sdk\3.1.100\NuGet.targets(123,5): error : '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1. [M:\fsharp\src\fsharp\fsc\fsc.fsproj]
  Restore completed in 1.75 ms for M:\fsharp\src\fsharp\FSharp.Compiler.Server.Shared\FSharp.Compiler.Server.Shared.fsproj.
  Restore completed in 6.99 ms for M:\fsharp\src\fsharp\FSharp.Core\FSharp.Core.fsproj.
M:\fsharp\.dotnet\sdk\3.1.100\NuGet.targets(123,5): error : '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1. [M:\fsharp\src\fsharp\fsi\fsi.fsproj]
Command failed to execute with exit code 1: M:\fsharp\.dotnet\dotnet.exe build M:\fsharp\proto.proj -c Proto -v m -f net472
System.Management.Automation.RuntimeException: Command failed to execute with exit code 1: M:\fsharp\.dotnet\dotnet.exe build M:\fsharp\proto.proj -c Proto -v m -f net472
at Exec-CommandCore, M:\fsharp\eng\build-utils.ps1: line 50
at Exec-Console, M:\fsharp\eng\build-utils.ps1: line 119
at Make-BootstrapBuild, M:\fsharp\eng\build-utils.ps1: line 265
at <ScriptBlock>, M:\fsharp\eng\build.ps1: line 432
at <ScriptBlock>, <No file>: line 1
(NETCORE_ENGINEERING_TELEMETRY=Build) Failure building bootstrap compiler

**Known workarounds**

None

**Related information**

Provide any related information (optional):

* Operating system
Windows Server 2019
* .NET Runtime kind (.NET Core, .NET Framework, Mono)
.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-preview.2.20176.6
 Commit:    d752c3e07b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.2.20176.6\

Host (useful for support):
  Version: 5.0.0-preview.2.20160.6
  Commit:  d12f79a4d1

.NET Core SDKs installed:
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.2.20176.6 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.2.20167.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.2.20160.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.2.20160.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
* Editing Tools (e.g. Visual Studio Version, Visual Studio)
VS2019 & VS2019 Preview
16.5.0 & 16.6.0 preview 2.1

**Comment by abelbraaksma** [comment]
> M:\fsharp.dotnet\sdk\3.1.100\NuGet.targets(123,5): error : '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1

This error possibly hints at a BOM at the top of an UTF8 file. Can that be the reason here? Though you're using a Windows system for building, and Windows 2019 is also used on the CI environment.

@ingted  Is this still an isue? I cannot repro it after a clean clone.

**Comment by cartermp** [comment]
This sounds like a weird issue with something being malformed. I'll close this out since it hasn't been reported by anyone else nor have I see it on Windows with latest master of the repo.
