### ISSUE TITLE
FS-1053: c# operator with inref does not work with F#

### ISSUE THREAD

**Issue by 0x53A** [dotnet/fsharp#9018]
This is related to [_FS-1053: voidptr, IsReadOnly structs, inref, outref, ByRefLike structs, byref extension members_](https://github.com/fsharp/fslang-design/blob/master/FSharp-4.5/FS-1053-span.md)

In C#, you can mark the parameters of an overloaded operator as ``inref``:

```c#
public readonly struct C
{
    public readonly int I {get;}
    public C(int i)
    {
        I = i;
    }
    
    public void M()
    {
        var c1 = new C(1);
        var c2 = new C(2);
        
        var c3 = c1 + c2;
    }
    
    public static C operator+ (in C a, in C b)
    {
        return new C(a.I + b.I);
    }
}
```

This operator seems to be not directly usable in F#:

```f#
    let c1 = C(1)
    let c2 = C(1)
    let c3 = c1 + c2;
```

>error FS0001: Type constraint mismatch. The type     'C'    is not compatible with type    'inref<C>'
error FS0043: Type constraint mismatch. The type     'C'    is not compatible with type    'inref<C>'

As a workaround, you can explicitly call ``op_Addition``:

```f#
let c3 = C.op_Addition(&c1, &c2)
```

**Comment by 0x53A** [comment]
Also, I have another question:

From the RFC it sounds a bit like implicit conversion to ``inref`` should work like in C#, for example here is a mention about overloading:

---------

Overloading

When an implicit address is being taken for an inref parameter, an overload with an argument of type SomeType is preferred to an overload with an argument of type inref<SomeType>. For example give this:

    type C() = 
         static member M(x: System.DateTime) = x.AddDays(1.0)
         static member M(x: inref<System.DateTime>) = x.AddDays(2.0)
         static member M2(x: System.DateTime, y: int) = x.AddDays(1.0)
         static member M2(x: inref<System.DateTime>, y: int) = x.AddDays(2.0)
    let res = System.DateTime.Now
    let v =  C.M(res)
    let v2 =  C.M2(res, 4)

In both cases the overload resolves to the method taking System.DateTime rather than the one taking inref<System.DateTime>.

------------

But in practice there doesn't seem to be _any_ implicit conversion to ``inref``?

If I change the ctor in the C# example above to ``public C(in int i)``, then I get an error ``error FS0001: This expression was expected to have type    'inref<int>'    but here has type    'int'``.

This makes usage of any API using ``in`` in C# quite convoluted, because I need to let-bind everything.

**Comment by dsyme** [comment]
For the first part (now the question), this is by design as things currently stand.  

- `a + b` is not a method call but a call to the F# library operator for `(+)` with its SRTP constraint

- the `inref` version of the op_Addition member provided by C# does not satisfy this SRTP constraint 

We could consider a language suggestion where members taking `inref` arguments can be considered to satisfy such constraints but it would need an RFC. I'm not sure of its technical feasiblity.

**Comment by dsyme** [comment]
I've created the language suggestion here https://github.com/fsharp/fslang-suggestions/issues/912

**Comment by dsyme** [comment]
Regarding the question - yes, this is currently by design, there is no implicit inref conversion
