### ISSUE TITLE
FSharp.Core nuget 4.7.1 has assembly version 4.7.0 

### ISSUE THREAD

**Issue by goswinr** [dotnet/fsharp#9062]
Is the assembly version of the FSharp.Core Nuget 4.7.**1** correct?
Is it supposed to be set to 4.7.**0** ?

![image](https://user-images.githubusercontent.com/884885/80484031-5a65c300-8957-11ea-89fe-79e0eaf11988.png)

( I am trying to find out why I have an invalid reference to FSharp.Core in https://github.com/fsharp/FSharp.Compiler.Service/issues/935 )

**Comment by cartermp** [comment]
This is expected, the assembly version has been MAJOR.MINOR.0.0 since F# 4.5 (and before then was DESKTOP_CLR_VERSION.MAJOR.MINOR.0). I don't think the issue you're seeing is related to this.
