### ISSUE TITLE
msbuild path is None when not in VS debug mode

### ISSUE THREAD

**Issue by ingted** [dotnet/fsharp#9102]
**Repro steps**

if someone really want to take a look, please reply and I will post the source files.

**Expected behavior**

using #r @"nuget: xxxxx"
open xxxxx

(everything is fine)

**Actual behavior**

(when execute exe file instead of use VS debug)
unable to open the module because the msbuild path is None so nuget package not built

**Known workarounds**

change code in src\fsharp\FSharp.DependencyManager.Nuget\FSharp.DependencyManager.Utilities.fs

last line of msbuildExePath
        let msbOpt = roots |> Array.tryFind(fun root -> msbuildPathExists root) |> msbuildOption
        match msbOpt with
        | Some _ -> msbOpt
        | None ->
            printfn "msbuildPathMissingIssue"
            Some @"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe"

**Related information**

**Comment by cartermp** [comment]
@ingted Unfortunately without any repro information here it's impossible to understand where the issue could be coming from. The dependency manager component has undergone a considerable amount of churn in the past few months though.

**Comment by ingted** [comment]
Let me prepare the reproduce project and upload it!! Thank you for the reply!!

**Comment by ingted** [comment]
@cartermp 
Hi Philip,
I upload the vhdx to [https://vpon365-my.sharepoint.com/:u:/g/personal/anibal_yeh_vpon_com/EYKG0YWdKdNOqRYMPSI9YUgBS7YfhRaYehiCa_0HAul4cw?e=MMnaIv](url)

and in the vhdx, there would be projects:

https://github.com/ingted/f- checked out with branch onlyDebugOK
this comes from f# project with commit fb3fc8e5865497098a3f6ccd8ff47f1b6fba5ff4
https://github.com/ingted/ws2
this comes from project dotnet-websharper/owin.websocket

open the solution file FSharp.sln in F- and debug project ClientServer
after the console shows "Serving http://localhost:8080"
and open web at http://localhost:8080/fsi
and paste 

#r @"nuget: Akka"
open Akka
456

and press "send" button, then the open key works fine

but if we execute ws2\ClientServer\bin\Debug\net48\ClientServer.exe
it would not work fine


I know this is really ugly 
(I mean the reproduce process, no one would like a vhdx thing...)
so I just report this issue and waiting for the final release about the nuget dependency manager.
Before this, I think the workaround is very fine...

But if you are fine with it, then maybe you could try it...


Thank you so much!!

**Comment by ingted** [comment]
![image](https://user-images.githubusercontent.com/4289161/81568323-2e732480-93d0-11ea-9301-7e899fb64071.png)

**Comment by ingted** [comment]
The image above is in VS debug mode

**Comment by ingted** [comment]
![image](https://user-images.githubusercontent.com/4289161/81568501-72662980-93d0-11ea-83f9-7e5c0b00a852.png)

**Comment by ingted** [comment]
And this is a direct execution result.

**Comment by ingted** [comment]
![image](https://user-images.githubusercontent.com/4289161/81568627-a0e40480-93d0-11ea-8c84-749a9e924eda.png)

**Comment by ingted** [comment]
The workaround is forced specify the msbuild path for the dependency manger
if not then the nuget reference would not work

**Comment by cartermp** [comment]
@KevinRansom any thoughts here?

**Comment by KevinRansom** [comment]
@ingted, if the environment is not set up correctly, and it should have been by the vsinstaller,  you can set the environment variable in order to ensure that the nuget package manager finds msbuild when executing on the desktop clr.

VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\

You can also set the variables for the current process by using Environment.SetEnvironment( ... ) function.

msbuild must have been installed by a either Visual Studio, or by the VS build sku installer.

**Comment by ingted** [comment]
Hi @KevinRansom,

I followed your instruction and after the environment variable added, everything are fine now.

Thanks for your help and I think it could be closed... should I close it?


Regards
Anibal

**Comment by KevinRansom** [comment]
Please do.
