### ISSUE TITLE
Set GenerateDocumentationFile to true by in F# SDK project templates

### ISSUE THREAD

**Issue by charlesroddie** [dotnet/fsharp#9162]
### The VS GUI doesn't support GenerateDocumentationFile in F#/C#

Currently:

![image](https://user-images.githubusercontent.com/19760720/81496522-17d5ac00-92b0-11ea-8300-e5bd42411da4.png)

This takes an absolute path instead of a bool which was a problem with the old style project format.

The CSharp project editor GUI is only marginally better than the F# one, in that it gives a default path that works. But the output is still incorrect as there should be no path in SDK style projects. https://github.com/dotnet/project-system/issues/368

Until this issue is solved it's extra important to have the right default.

### `true` is a better default than `false`

`true` enables F# projects to give intellisense to C# projects, and also to F# projects when in-memory cross-project references is disabled.

![image](https://user-images.githubusercontent.com/19760720/81496842-8b78b880-92b2-11ea-87ee-40e5e6216230.png)

https://twitter.com/JamesMontemagno/status/1172267120320811008

**Comment by charlesroddie** [comment]
Alternatively https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/xml-documentation could be updated to include something like:

`<GenerateDocumentationFile>true</GenerateDocumentationFile>` should be set in .fsproj files to enable intellisense in referencing projects.

**Comment by cartermp** [comment]
I think this could be reasonably done for library projects, barring some profiling showing a very adverse effect on build. I did a quick `dotnet msbuild /clp:PerformanceSummary` on the XPlot project with and without this set to true and it didn't seem to matter. The library template is here: https://github.com/dotnet/templating/ if you'd be interested in contributing a fix

**Comment by cartermp** [comment]
Closing as this is external, the PR is up here: https://github.com/dotnet/templating/pull/2502

**Comment by charlesroddie** [comment]
Thanks @cartermp and sorry I was too slow to get to this!
