### ISSUE TITLE
Allow documenting primary constructor

### ISSUE THREAD

**Issue by charlesroddie** [dotnet/fsharp#9163]
Problem: There is no way to document a primary constructor in F# code.

> <img src="https://user-images.githubusercontent.com/19760720/81497423-5bcbaf80-92b6-11ea-94b2-8f7afa91b6e2.png" width="70%">
> 
> https://stackoverflow.com/questions/15121814/documenting-f-code

Also reported at http://apollo13cn.blogspot.com/2012/04/xml-document-on-f-primary-constructor.html

What would be the best syntax for this? Perhaps:

```fsharp
/// MyType is my type
type MyType
    /// You can make it using an int
        (a:int) =
    class end
```

**Comment by dsyme** [comment]
This has been addressed somewhere along the way, XML file for the above shown below
```xml
<?xml version="1.0" encoding="utf-8"?>
<doc>
<assembly><name>a</name></assembly>
<members>
<member name="M:A.MyType.#ctor(System.Int32)">
<summary>
 You can make it using an int
</summary>
</member>
<member name="T:A.MyType">
<summary>
 MyType is my type
</summary>
</member>
</members>
</doc>
```
