### ISSUE TITLE
AttributeUsage AllowMultiple and AttributeTargets  is not inherited

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/fsharp#9256]
AttributeUsage AllowMultiple is not inherited
HttpGet is failing, HttpMethod works (this mirrors the attributes from aspnet mvc)

```fs
open System

[<AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = true)>]
type HttpMethodAttribute() = inherit Attribute()
type HttpGetAttribute() = inherit HttpMethodAttribute()

[<HttpGet; HttpGet>] // this shouldn't error like 
[<HttpMethod; HttpMethod>] // this doesn't
type C() =
    member _.M() = ()
```

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEAzAzgHwgAcYA7AAgGUBPXAFxgFsBYAKDYG0AeAQTrqgBLYAFcGAVVwBDAOYwAFHwHCxMACpSocurgB0AYQxTcuNOR4YMEAO4BZERjqCiGGOQC85ASJhmAkqQAFjBCDAAmHl5QPgCUAHwAumx01CTkABL8RLYwdIEQYUpCogzyMZGCQSGCdOb8xaplyalumXREAOK5RSql5Z6VwaEZWTl5BT0lCjFsnFxtnbkA3CPtXXSJcwtj+WEr27m7m6wpafplHmzk1+SMTMAh5AD6urYXnmVAA=

**Comment by dsyme** [comment]
Agreed we should be looking at the inherited `AttributeUsage`

**Comment by ErikSchierboom** [comment]
I've been looking into fixing this issue, but I have some issues understanding exactly how to do this. I know that the `AllowMultiple` check is being done in the `CheckAttribs` function ([source](https://github.com/dotnet/fsharp/blob/main/src/fsharp/PostInferenceChecks.fs#L1708)). That function then calls the `TryFindAttributeUsageAttribute` function which is defined [here](https://github.com/dotnet/fsharp/blob/main/src/fsharp/TypedTreeOps.fs#L3122), which itself depends on `TryBindTyconRefAttribute` ([source](https://github.com/dotnet/fsharp/blob/main/src/fsharp/TypedTreeOps.fs#L3088)). It does indeed look like the code never checks if the attribute itself has inherited attributes. My main question is: how can I best approach this? I've tried to get to an attribute's parent type, but so far have failed in my attempts.

**Comment by baronfel** [comment]
@ErikSchierboom take a look at [PR 10834](https://github.com/dotnet/fsharp/pull/10834/files#diff-612ef51eab0f5ec166033e7f8fdc532e302919db65b9cdb1e07ef67465f5a828R3017), I made a helper function that walks the inheritance hierarchy for a type that seems to do the job.

**Comment by ErikSchierboom** [comment]
@baronfel Ah interesting! Thanks for the heads-up.
