### ISSUE TITLE
AttributeUsage AttributeTargets is not inherited

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/fsharp#9257]
AttributeUsage AttributeTargets is not inherited.
HttpGet shouldn't be allowed on AttributeTargets.Class, just as HttpMethod isn't.

```fs
open System

[<AttributeUsage(AttributeTargets.Method, AllowMultiple = true, Inherited = true)>]
type HttpMethodAttribute() = inherit Attribute()
type HttpGetAttribute() = inherit HttpMethodAttribute()

[<HttpGet>] // this should error like
[<HttpMethod;>] // this
type C() =
    member _.M() = ()
```

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEAzAzgHwgAcYA7AAgGUBPXAFxgFsBYAKDYG0AeAQTrqgBLYAFcGAVVwBDAOYwAFHwHCxMACpSocurgB0AWRh0AFhAAmacjwwYIAd30iMdQUQwxyAXnICRMSwCSpMYwQgxmXj5QfgCUAHwAumx01CTkABL8RIYm5kpCogzyMZGCwaGCdFb8BarFyakemXREAOJG+SpFJd5lIWEZWTmmZp2FCjFsnFzNbUaJ07PD5gDcC6wpaQDCxV5s5AfkjEzAoeQA+ga73sVAA=

**Comment by dsyme** [comment]
Will track with #9256
