### ISSUE TITLE
Missing method exception .NET 5

### ISSUE THREAD

**Issue by kerams** [dotnet/fsharp#9265]
One of these again, possibly related to #8881, but the design part of the TP is having a problem this time around. I think the issue started appearing after I'd updated from a preview of VS 16.6 to 16.7 Preview 1.

**Repro steps**

Just like in #8881.

**Expected behavior**

Application compiles and does not throw at runtime.

**Actual behavior**

Squiggly lines and build failing when started from within VS:
`The type provider 'FSharp.Data.Npgsql.NpgsqlProviders' reported an error: Method not found: 'Microsoft.Extensions.Configuration.IConfigurationBuilder Microsoft.Extensions.Configuration.UserSecretsConfigurationExtensions.AddUserSecrets(Microsoft.Extensions.Configuration.IConfigurationBuilder, System.String)'`

Compiles and runs just fine with `dotnet run`.

**Related information**

* Windows 10
* 5.0.100-preview.6.20272.8
* VS 16.7 Preview 1

**Comment by kerams** [comment]
Is there a chance this will be addressed before .NET 5 releases?

**Comment by abelbraaksma** [comment]
Does this happen with Preview 5, still? (considering the related issue was merged and closed, I'd expect it to be part of latest preview).

**Comment by kerams** [comment]
Yes, it does still happen in the latest preview of VS but not with `dotnet build`, so it's different from the other issue.

**Comment by cartermp** [comment]
This sounds like it might be an issue with the type provider itself and not the compiler mechanism for hosting one. Specifically, the F# compiler looks for the design-time `.dll` that a type provider registers, and inspects that for information. This results in code in that `.dll` executing. It could be that there's an error on our side here but my inclination is to check with the type provider itself.

**Comment by kerams** [comment]
I have double checked that the problem does not manifest in VS 16.6. Does that rule out anything?

**Comment by dsyme** [comment]
Given that `FSharp.Data.Npgsql` has successfully moved on to version 2.0.2 by now I'm going to close this as I assume this has been resolved

@kerams Please re-open if not, thanks
