### ISSUE TITLE
behavior change in string slicing in fsharp 4.7

### ISSUE THREAD

**Issue by sylvainouel** [dotnet/fsharp#9266]
With FSharp.Core 4.6, 
"".[0..1]
throws OutOfRangeException. In 4.7, it returns empty string.

It's a pretty big behavior change. Was it intentional?
Thanks

**Comment by baronfel** [comment]
Yep! You can read the [RFC](https://github.com/fsharp/fslang-design/blob/master/preview/FS-1077-tolerant-slicing.md) for tolerant slicing to find out more, or check out [this F# team blog post](https://devblogs.microsoft.com/dotnet/announcing-f-5-preview-1/) for a walkthrough (search for 'Enhanced Slicing' on that page).

**Comment by cartermp** [comment]
@sylvainouel This is correct, it's intentional. We're moving towards making all built-in slices consistent in terms of their behavior and more tolerant (since empty list/array/string compose with non-empty ones). But we're certainly open to feedback on this!

**Comment by sylvainouel** [comment]
thanks.
