### ISSUE TITLE
Oddities with FSI package management

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#9270]
I'm just starting to use FSI package maangement and noticed a few things.  I'll use this issue to document oddities or bugs as I notice them.  

#### Delayed feedback on executing `#r "nuget..."`

1. run `dotnet artifacts\bin\fsi\Debug\netcoreapp3.0\fsi.exe /langversion:preview`

2. Type `#r "nuget: FSharp.Data";;`

Expected: some kind of feedback
Actual: the feedback comes after your next non-nuget interaction, e.g. type `1+1;;` and then you get a project loaded.

I think we could print `FSharp.Data registered for nuget processing` or something.  Just so you know something happened.  

#### Syntax differences with `fsi` and notebooks

In .NET Interactive Jupyter notebooks I do this for extra package sources:

```fsharp
#i "nuget: https://donsyme.pkgs.visualstudio.com/TorchSharp/_packaging/packages2/nuget/v3/index.json"
#r "nuget:libtorch-cpu,0.3.52118"
#r "nuget:TorchSharp,0.3.52118"
```

but in F# Interactive I do this:

```fsharp
#r "nuget:RestoreSources=https://donsyme.pkgs.visualstudio.com/TorchSharp/_packaging/packages2/nuget/v3/index.json"
#r "nuget:libtorch-cpu,0.3.52118"
#r "nuget:TorchSharp,0.3.52118"
```

Why the difference in the first line?

#### Native DLL not found

See this error: https://github.com/dotnet/interactive/issues/464

**Comment by KevinRansom** [comment]
@dsyme, 

the lazy activation of #r "nuget: " has been it's behaviour since the very first prototype.  The #r collects the arguments, but package resolve does not happen until code compilation happens.

notebook has a different and better experience because we run the resolve up in the host before we invoke fsi to execute the script.

I too prefer the notebook behavior and have on my personal backlog the desire to experiment how to reproduce this behavior in fsi.

**Comment by dsyme** [comment]
> the lazy activation of #r "nuget: " has been it's behaviour since the very first prototype. The #r collects the arguments, but package resolve does not happen until code compilation happens.

My feeling is resolution should be forced by 

1. `;;` when the interaction is entered into F# interactive `stdin`
2. A single Alt-Enter execution.

That's what the `;;` terminator is present in F# for - it says "commit everything and do your thing".  

People expect feedback after execution. The complete absence of feedback is really, really confusing.  

The absence of feedback even after a successful `#r` is also problematic I think.  For example

```
>  #r "nuget: DiffSharp-reference,Version=0.9.5-preview-2006210200";;
> 1;;
[Loading C:\Users\dsyme\AppData\Local\Temp\nuget\13352--dfe928cd-07f4-42c7-91b0-b6148e8088ac\Project.fsproj.fsx]
namespace FSI_0005.Project
```
The feedback given is about the auto-generated `13352--dfe928cd-07f4-42c7-91b0-b6148e8088ac\Project.fsproj.fsx` but that's not meaningful to the user.

I think we should go over this and spec out the interactions and feedback we expect and support for different incremental executions (both succeeding and failure) in Console and Script-Alt-Enter modes and see what we can sort out.  At the moment it feels like we're seeing too much implementation.

**Comment by dsyme** [comment]
Also I'd really like us to align the syntax for referencing between `fsi.exe` and .NET Interactive if possible.  What do we need to change to do this?   I'm finding it really confusing switching between the different syntaxes.

**Comment by jonsequitur** [comment]
We've been experimenting with syntax at the .NET Interactive level before pushing it down to CSI and FSI, hence the current inconsistency. 

An interesting difference is that magic commands in .NET Interactive (much like in IPython/Jupyter) are parsed as POSIX-like command lines. In that context this helps unify the behavior, and we get a good extensibility story via System.CommandLine, but it clashes a bit with the compiler directives.

But unburdened of history, a syntax like this would likely be cleaner and better support tooling such as completion and hover text:

```console
#!nuget add-source https://donsyme.pkgs.visualstudio.com/TorchSharp/_packaging/packages2/nuget/v3/index.json
#!nuget DiffSharp -v 1.2.3
```

**Comment by dsyme** [comment]
Closing this as it's covered by https://github.com/dotnet/fsharp/pull/9652 and https://github.com/dotnet/fsharp/issues/9540
