### ISSUE TITLE
Rename duplicates the name when multitargeting

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#9275]
Latest dogfood

Got o `ServiceDeclarationLists` and renam` ParamOfParamData`:

Before:

![image](https://user-images.githubusercontent.com/6309070/82718714-06e64c80-9c59-11ea-956e-ec2259d3fd64.png)

After:

![image](https://user-images.githubusercontent.com/6309070/82718718-0fd71e00-9c59-11ea-8f3d-70b32c7931d6.png)

I'm also pretty sure that the number of references and files listed is incorrect.

**Comment by cartermp** [comment]
cc @TIHan

**Comment by abelbraaksma** [comment]
Hmm, I've also seen rename to totally screw up the whole line, where the new name replaces a different column position entirely, leaving everything garbled, esp when you run a few renames after each other. Not sure it's the same cause though, but it's why I've stayed away from rename, and just stick with find and replace (which is also faster).
