### ISSUE TITLE
Access to tokens through FCS FSharpChecker

### ISSUE THREAD

**Issue by jgardella** [dotnet/fsharp#9280]
**Is your feature request related to a problem? Please describe.**
F# language tools like FSharpLint make use of the `FSharpChecker` in FCS to get the AST for source code. Sometimes these tools also need the tokens of the file; currently in order to get these a separate call has to be made to the tokenizer, which can be slow.

**Describe the solution you'd like**
Assumedly the `FSharpChecker` is performing some kind of tokenizing internally. Is it possible to expose or allow interaction with these tokens, so that one could call the FSharpChecker and get a list of tokens, and not have to call both the checker and the tokenizer?

**Describe alternatives you've considered**
We can call the tokenizer separately, but being able to access tokens if they are already available as a result of parsing could avoid doing repeated work.

**Additional context**
- [FCS tokenizer docs](http://fsharp.github.io/FSharp.Compiler.Service/tokenizer.html)
- [FCS parser docs](http://fsharp.github.io/FSharp.Compiler.Service/untypedtree.html)

**Comment by dsyme** [comment]
The general approach is to put Syntax Tree Trivia on the syntax trees, see #12418
