### ISSUE TITLE
[<RequireQualifiedAccess>] members should not show in intellisense unless fully qualified

### ISSUE THREAD

**Issue by isaacabraham** [dotnet/fsharp#9290]
Repro of https://github.com/ionide/ionide-vscode-fsharp/issues/1364.

Given the following code:

```fsharp
namespace Blah
    [<RequireQualifiedAccess>]
    type Foo = Bar | Baz | Bop
```

When I access the `Blah` namespace, I would **not** expect `Bar`, `Baz` or `Bop` to show in intellisense, but they do:

![image](https://user-images.githubusercontent.com/1781813/81748993-1c19e900-94ab-11ea-8595-0dc0ec4326fe.png)

If you then reference one, the compiler (correctly) gives you a warning:

![image](https://user-images.githubusercontent.com/1781813/81749042-33f16d00-94ab-11ea-8dc7-bc20ce8ff897.png)

IDEs (this affect VS2019 as well as Ionide and Rider) should not present suggestions that are "wrong" and / or will lead to warnings or errors. This is also important from a discoverablility point of view for library authors - if I mark something with RQA, I also don't want intellisense clogged up with suggestions of each union case.

The only workaround I can think of is to enclose the DU in a module of the same name:

```fsharp
namespace Blah
    [<RequireQualifiedAccessAttribute>]
    module Foo =
        type Foo = Bar | Baz | Bop
```

This then behaves more-or-less as expected:

![image](https://user-images.githubusercontent.com/1781813/81749300-abbf9780-94ab-11ea-9044-420f7c3959d4.png)

However this is totally unidiomatic and I would not want to do this.

**Comment by cartermp** [comment]
Looked into this briefly and it seems that name resolution isn't filling in all the correct data. The union case info for these cases looks like this:

![image](https://user-images.githubusercontent.com/6309070/83997783-01089080-a914-11ea-8dd7-6bad8b521b17.png)

That flag should be true, so unfortunately filtering by it doesn't do anything.

**Comment by forki** [comment]
Yeah I debugged this multiple times and found couple of very weird things
happening. Basically RQA is lost in some situations when things get passed
down the tree. But I didn't find a way to fix it

Phillip Carter <notifications@github.com> schrieb am Mo., 8. Juni 2020,
08:10:

**Comment by cartermp** [comment]
Yeah this looks surprisingly tricky. I pushed a branch here if anyone is interested: https://github.com/dotnet/fsharp/compare/master...cartermp:rq-completion?expand=1

Unfortunately there are many places where this data is generated in name resolution, and most don't fill in this data. I could have also missed something in my branch, since it filling in the data doesn't appear to have an effect

**Comment by safesparrow** [comment]
FWIW I don't think this affects the latest Rider 2021.2:
![image](https://user-images.githubusercontent.com/2478401/128598767-0ac2a10e-d2ce-498e-a02e-7f68c5f44e33.png)

**Comment by dsyme** [comment]
It's fixed in VS too
