### ISSUE TITLE
Valid code using quotation doesn't build

### ISSUE THREAD

**Issue by TysonMN** [dotnet/fsharp#9291]
**Summary**
The code doesn't build but Visual Studio's "Error List" is empty.

**Repro steps**
Try to build this code.
```F#module MyModule
let foo =
  seq {
    let mutable x = 0
    let f () =
      x <- 0
    f |> ignore // ensure that f isn't reported as an unused let binding
    <@ x @> |> ignore
  } |> ignore
```

[ZIP of MWE](https://github.com/dotnet/fsharp/files/4677674/MWE.zip)

**Expected behavior**

I actually expected this code to build.  Maybe it is correct that it doesn't build though.

Either way, I really expected the build output and the "Error List" in Visual Studio to be consistent.

**Actual behavior**

The build output and the "Error List" in Visual Studio are inconsistent.  The build fails but the "Error List" in Visual Studio is empty, even when "Build + IntelliSense" items are being displayed.

Here is a screenshot.
![screenshot](https://user-images.githubusercontent.com/34664007/82923239-4bffcc80-9f40-11ea-9351-148e09b6cd13.png)

**Known workarounds**

Here is the work around (applied to this MWE) that I am using in my real code.  Instead of referencing the mutable value in the expression, a workaround is to first copy that mutable value to an immutable value and then reference the immutable value in the expression.  After applying this workaround, the code builds, and Visual Studio's "Error List" is empty, which is consistent.

```F#
module MyModule
let foo =
  seq {
    let mutable x = 0
    let f () =
      x <- 0
    f |> ignore // ensure that f isn't reported as an unused let binding
    let y = x
    <@ y @> |> ignore
  } |> ignore
```

Because of this workaround, I expect that the original code should also compile, but my expectations could be off.

**Related information**

Here is the output of the execution of `dotnet build` from the "Package Manager Console" in Visual Studio.

```
PM> dotnet build
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 269.24 ms for C:\Temp\Temp\Temp.fsproj.
C:\Temp\Temp\Program.fs(4,17): error FS0971: Undefined value 'mutable x : int' [C:\Temp\Temp\Temp.fsproj]
C:\Temp\Temp\Program.fs(4,17): error FS0971: Undefined value 'mutable x : int' [C:\Temp\Temp\Temp.fsproj]
C:\Temp\Temp\Program.fs(4,17): error FS0971: Undefined value 'mutable x : int' [C:\Temp\Temp\Temp.fsproj]
C:\Temp\Temp\Program.fs(4,17): error FS0971: Undefined value 'mutable x : int' [C:\Temp\Temp\Temp.fsproj]

Build FAILED.

C:\Temp\Temp\Program.fs(4,17): error FS0971: Undefined value 'mutable x : int' [C:\Temp\Temp\Temp.fsproj]
C:\Temp\Temp\Program.fs(4,17): error FS0971: Undefined value 'mutable x : int' [C:\Temp\Temp\Temp.fsproj]
C:\Temp\Temp\Program.fs(4,17): error FS0971: Undefined value 'mutable x : int' [C:\Temp\Temp\Temp.fsproj]
C:\Temp\Temp\Program.fs(4,17): error FS0971: Undefined value 'mutable x : int' [C:\Temp\Temp\Temp.fsproj]
    0 Warning(s)
    4 Error(s)

Time Elapsed 00:00:03.63
```

**Related information**

* Operating system: WIndows 10 Enterprise Version 10.0.18362 Build 18362
* .NET Runtime kind: The MWE targets .NET Core and my most recent version of that is 3.1.202 (x64)
* Editing Tools: Visual Studio Enterprise 2019 Version 16.5.5

**Comment by bender2k14** [comment]
[Here](https://github.com/elmish/Elmish.WPF/blob/a42856e2f6c23f7b78cf6cd4d6ce9f422ca694ba/src/Elmish.WPF.Tests/MergeTests.fs#L255-L280) is my actual use case along with the workaround I mentioned.

**Comment by seanamos** [comment]
Just ran into the exact same issue while unit testing with Unquote.

**Comment by dsyme** [comment]
This was fixed by https://github.com/dotnet/fsharp/pull/12911
