### ISSUE TITLE
Native Dependency Resolution Bug

### ISSUE THREAD

**Issue by matthewcrews** [dotnet/fsharp#9294]
Please provide a succinct description of the issue.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Clone this repo: https://github.com/matthewcrews/fsharpNotebookTesting
2. Run this notebook: https://github.com/matthewcrews/fsharpNotebookTesting/blob/master/FlipsTest.ipynb

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

**Expected behavior**: 

That all of the cells run successfully

**Actual behavior**

There is an error saying that it is unable to load a DLL.

```
System.TypeInitializationException: The type initializer for 'Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'google-ortools-native' or one of its dependencies: The specified module could not be found. (0x8007007E)
```

**Known workarounds**

None at this time

**Related information**

Provide any related information (optional):

Operating system: Windows 10 Home Version 10.0.18363 Build 18363
.NET Core 5.0.100-preview.4.20258.7

Jupyter Notebooks
Library Versions:
jupyter core     : 4.6.1
jupyter-notebook : 6.0.3
qtconsole        : 4.6.0
ipython          : 7.12.0
ipykernel        : 5.1.4
jupyter client   : 5.3.4
jupyter lab      : 1.2.6
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3

**Comment by KevinRansom** [comment]
@matthewcrews , hi, I just fixed a bug in FSI that impacts native dependency loading.  I expect it to fix this one too.  

I planned on migrating the fix to notebook this week.  I will get back to you with more info shortly.

Kevin

**Comment by KevinRansom** [comment]
@matthewcrews 

Thanks for the bug report, I just tested the fix on the notebook and it seems to work for your scenario:

![image](https://user-images.githubusercontent.com/5175830/83222624-998d5c80-a12d-11ea-8d77-e2884fe1a17d.png)

The PR to update interactive is here:  https://github.com/dotnet/interactive/pull/485

I am going to close this as the F# part of it is complete :-)  As soon as Jon or Diego, merges the PR all will good with the world.

**Comment by matthewcrews** [comment]
Bless you!

**Comment by matthewcrews** [comment]
When will this update be available in the dotnet-interactive bits? I tried updating my install but it doesn't look like the fix is in there yet. Thanks for the help!
