### ISSUE TITLE
Static method causes closure alloc during method group conversion 

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/fsharp#9299]
```fs
open System
type C() =
    static member Foo(i: int) = ()
    static member Bar(i: int) = i
    
let fooAction = Action<_>(C.Foo)
let barFunc = Func<_,_>(C.Bar)
```

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEAzAzgHwgAcYA7AAgGUBPXAFxgFsBYAKDupPIGEAKASnIBeNuTHl6AQzoBLMOUZNgMKOQBiECLxkhyM0nUFDyA0eKmz5ixstUAhSVG279h4XrNi2GGHXLZNAEEwWQgKY2DQ0gAeAH0APl5uADoNCH5vX3JgRzUAV1J5Y3zCuLQEpOSHKH4gA

Decompilation to C# shows an internal class has been created for this static member.

```c#
fooAction@6 = new Action<int>(new @_.fooAction@6().Invoke);
barFunc@7 = new Func<int, int>(new @_.barFunc@7().Invoke);
```

@TIHan this might interest you considering your recent work on the inlined lambda allocations.

**Comment by NatElkins** [comment]
@NinoFloris Is this not resolved by https://github.com/dotnet/fsharp/pull/9017 ?

**Comment by NinoFloris** [comment]
Oh, really nice!

So this seems to happen in more cases, which I'm not sure are all covered by the PR of @MoFtZ 

```f#
open System
    
let foo x = ()
let fooAction = Action<_>(foo)
let lambdaFooAction = Action<_>(fun x -> ())
```

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEAzAzgHwgAcYA7AAgGUBPXAFxgFsBYAKHI/LYxjvOwgRyCcgF5yACgCU3Xv0EBBMHQCWECuKWr1AHgD6APgkCIM1jz4YAho2AATKwDFFytRvJa3+o9gCuFETgDSSkpIA

These all generate inner classes, specifically curious about the static lambda, would that case be picked up by your fix as well?

**Comment by MoFtZ** [comment]
@NinoFloris, I ran your sample code using the F# commit 596f3d73f7fec4d9cae2b273b92c16206909bf52, where the changes from #9017 were merged.

The decompiled C# output shows no allocation for the closure:
```csharp
fooAction@6 = new Action<int>(Program.fooAction@6.Invoke);
barFunc@7 = new Func<int, int>(Program.barFunc@7.Invoke);
```
... and the corresponding closure classes are:
```csharp
[CompilationMapping(SourceConstructFlags.Closure)]
[Serializable]
internal static class fooAction@6
{
	internal static void Invoke(int arg00);
}

[CompilationMapping(SourceConstructFlags.Closure)]
[Serializable]
internal static class barFunc@7
{
	internal static int Invoke(int arg00);
}
```

As long as there are no variables captured by the closure, all delegates will use the new alloc-less code path.

**Comment by NinoFloris** [comment]
Thanks for checking, and well done on the PR!

As that was all I'll close this issue.
