### ISSUE TITLE
Cannot reference C# .NET Standard project from F# .NET Core project in VS dogfood build

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#9301]
Using latest dogfood:

![image](https://user-images.githubusercontent.com/6309070/82931467-d1cd4900-9f3b-11ea-85df-5ecb58d3860d.png)

Workaround:

Close and re-open the entire solution.

**Comment by cartermp** [comment]
Also any changes in the C# project won't get picked up unless you close and re-open the solution.

**Comment by cartermp** [comment]
The whole thing is complete busted:

* Any updates to the depending C# project are sometimes unseen by tools
* Closing/re-opening a project or solution does nothing
* Making changes and then explicitly rebuilding causes this error again:

![image](https://user-images.githubusercontent.com/6309070/82936654-c5e58500-9f43-11ea-89f4-97826f644262.png)

We regressed really badly here.

**Comment by KevinRansom** [comment]
Check this out:
It says the file don't exist, and yet explorer says it does ....  bless it's heart it got confused.
![image](https://user-images.githubusercontent.com/5175830/82966212-2fcf5000-9f7f-11ea-8691-bb13aee7e382.png)

**Comment by TIHan** [comment]
I don't think this is a regression. It's always been like this. F# referencing C# projects have never worked for in-memory cross project referencing. We have never done the work to use C# compilation's `Emit` method and forward it FCS. So, basically, the behavior is as-if in-memory cross project referencing was disabled for F#-to-F# project referencing.

**Comment by cartermp** [comment]
No, this doesn't have to do with in-memory cross project references. It's always been the case that you first need to _build_ the C# project to "see" its symbols, which is exactly what I did. But after that it's always worked.

**Comment by KevinRansom** [comment]
So this is what I see in dev 16.6:  Which looks about right to me, so as the report suggests dogfield build is a bit wonky.

![image](https://user-images.githubusercontent.com/5175830/82968147-7e7de980-9f81-11ea-8f0d-494c16e0b216.png)

**Comment by cartermp** [comment]
I think something is very busted here. I just tried this again with a fresh project in Dogfood and there's no issue - same steps: create F# project, create C# project, add reference from C# to F#, build C# project, type ccode. Then I did it in 16.6 and saw the same problem.

**Comment by KevinRansom** [comment]
So ,,, dogfood use to fail and now succeeds, and dev16.6 which did work now fails?

**Comment by KevinRansom** [comment]
@cartermp I followed this process
1. open dev16.6
2. Create new C# standard library project
3. Add new F# Console App
4. Add Reference to C# Standard Library
5. Open ClassLibrary2 namespace
6. Perform Build
7.  Observe no errors

Followed the same process on dogfood build saw an error can't find ClassLibrary3.dll

**Comment by cartermp** [comment]
Chatting with @TIHan here, there might be a timing/listening to events issue happening. Since I saw exact opposite behavior in both VS installations today, it makes sense that there's something odd with timing going on here :)

**Comment by KevinRansom** [comment]
could be ....

**Comment by TIHan** [comment]
I think I know what's going on and there is inconsistent behavior most likely due to timing; which is why this has become confusing.

What we could do to improve the experience and hopefully get rid of *some* in-consistency, is cause an invalidation to occur on a F# project when a referenced C# project's file output path has changed.

**Comment by cartermp** [comment]
will close as a dupe of https://github.com/dotnet/fsharp/issues/4000
