### ISSUE TITLE
Float32 without dot raises error on compile, but no error in editor

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#9338]
The following code does not show red squigglies, but throws when compiled:

```f#
let test = 1f
```

No red underline:

![image](https://user-images.githubusercontent.com/16015770/83247780-59b58c00-a1a4-11ea-9034-3867beeef575.png)

**Expected behavior**

If it's an error, it should show as an error.

**Actual behavior**

No error is shown, but when compiling, it shows:

> error FS1153: Invalid floating point number

**Known workarounds**

Just use a dot in the number. I think it'll compile if you set the `Preview`-flag in the project (as dotless float32 literals are going to be allowed), but I haven't tried that.

**Related information**

This is probably just a glitch from implementing https://github.com/fsharp/fslang-suggestions/issues/750, i.e. this PR: https://github.com/dotnet/fsharp/pull/7839.

I don't expect this to be fixed, as this syntax is expected to be allowed in F# 5 in a few months anyway, but it's a gotcha we should look out for when implementing stuff with the Preview-switch. I mean: in this case, the IDE error-check seems to have been removed and isn't under the Preview-switch, and the rest is, leading to inconsistencies in behavior.

**Comment by KevinRansom** [comment]
@abelbraaksma , I believe the IDE always uses the preview syntax, whereas the compiler requires a developer to specify a language version of preview to activate that code.  If I remember the early discussions on this, it was to match what we believed roslyn did.

**Comment by abelbraaksma** [comment]
Ah, ok. If that's the case, surprises like the one above when someone uses new syntax in the IDE (not a Preview of VS) are to be expected. I reckon this can be closed then.

Btw, @KevinRansom, would you happen to have some time to look into my repro of "our big issue" of locking-up of VS? Last week I posted a rather small repro, but it seems the issue has walked off the radar. I'd totally understand if you can't, but it'd be nice to have some feedback on the repro (i.e.: does it repro for you too?). I mean this issue: #9201.

**Comment by KevinRansom** [comment]
closing per @abelbraaksma
