### ISSUE TITLE
Indexed property on discriminated union causes pretty printing exception

### ISSUE THREAD

**Issue by bmitc** [dotnet/fsharp#9399]
When defining an [indexed property](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/members/indexed-properties) on a discriminated union type, an exception is raised during pretty printing when you try and construct a type value.

The error (see below) states to report the exception.

**Repro steps**

Define a simple single-case discriminated union by:

```
type Test = Test of int array with
    member this.Item
        with get index =
            let (Test x) = this
            x.[index]
```

This yields no errors or warnings in the Visual Studio Community 2019 (version 16.5.5) editor, where the project is targeting .NET Core 3.1. Sending this to F# Interactive (version 10.8.0.0 for F# 4.7) yields no complaints:

```
> 
type Test =
  | Test of int array
  with
    member Item : index:int -> int with get
  end

>
```

Then running `Test( [| 1; 2; 3 |] )` will generate the following exception:

```
> Test( [| 1; 2; 3 |] );;


Exception raised during pretty printing.
Please report this so it can be fixed.
Trace: System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.FSharp.Reflection.Impl.getUnionCaseRecordReader@262.Invoke(Object obj) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\reflect.fs:line 262
   at Microsoft.FSharp.Reflection.FSharpValue.GetUnionFields(Object value, Type unionType, FSharpOption`1 bindingFlags) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\reflect.fs:line 903
   at Internal.Utilities.StructuredFormat.ReflectUtils.Value.GetValueInfoOfObject$cont@405(BindingFlags bindingFlags, Object obj, Type reprty, Unit unitVar) in F:\workspace\_work\1\s\src\utils\sformat.fs:line 406
   at Internal.Utilities.StructuredFormat.Display.anyL[a](ShowMode showMode, BindingFlags bindingFlags, FormatOptions opts, a x, Type ty) in F:\workspace\_work\1\s\src\utils\sformat.fs:line 1156
   at FSharp.Compiler.Interactive.Shell.FsiValuePrinter.PrintValue(FsiValuePrinterMode printMode, FormatOptions opts, Object x, Type ty) in F:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 388
val it : Test = 

> 
```

**Expected behavior**

No exception. If indexed properties should not work on discriminated unions, then the type checker or compiler should generate the error. It seems like they should work though given that neither the type checker or compiler complains and seems to allow things to work as I would expect after reading the documentation.

After no exception, I would have expected the value:
```
> Test([|1;2;3|]);;
val it : Test = Test [|1; 2; 3|]

> 
```

Then I would expect the following to work:
```
> let t = Test( [| 1; 2; 3 |] );;
val t : Test = Test [|1; 2; 3|]

> t.[0];;
val it : int = 1

>
```

**Actual behavior**

An exception during pretty printing occurs when trying to construct a value.

**Known workarounds**

None.

**Related information**

Versions of Visual Studio, .NET, and F# Interactive given above. This is on Windows 10.

Also, note that indexed properties (see the documentation linked at the top) can support multiple indices.

**Comment by cartermp** [comment]
Thanks, confirmed on latest released FSI as well. Worth noting that the `printfn "%A"` equivalent of this does not fail, so this problem appears to be scoped to FSI.

**Comment by bmitc** [comment]
I am revisiting this since I started revisiting the project where I discovered the issue. The context was that I was trying to use a single-case discriminated union as a way to build a matrix type. So rather than using a class, like that shown [here](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/arrays#array-slicing-and-multidimensional-arrays), I was using a single-case discriminated union to wrap a 2d array but also add the relevant members to get element access and slicing. I note that this same bug does not exist for records since I tried that as well.

For example, the type definition:
```
type Test = {elements : int array} with
     member this.Item
         with get index = this.elements.[index]
```
can be used as:
```
> { elements = [| 1; 2; 3 |] };;
val it : Test = { elements = [|1; 2; 3|] }
```

Although, I feel the single-case discriminated union is cleaner, so I'm stuck by this.

If its possible, I would not mind helping to fix this bug. However, I haven't ever contributed to F# before and am not sure where to start. I'd be happy to help if someone pointed me somewhere, but I also know the challenge of by the time someone shows me the ropes, it'd probably be easier for them to fix it. Haha.

**Comment by cartermp** [comment]
Thanks for offering to take a look! Unfortunately, debugging FSI is kinda tricky. I'm not sure what the best approach is. The reflected definition of this object is clearly quirky, since it's ultimately failing in reflection internals.

@dsyme or @KevinRansom any ideas?

**Comment by vzarytovskii** [comment]
Can't see it on main anymore:
<img width="428" alt="image" src="https://github.com/dotnet/fsharp/assets/1260985/d7bcaa67-6458-4323-a2e2-cc2d4cc53b96">
