### ISSUE TITLE
Cannot use string or printfn on Span or byref type, while `ToString` works, causes FS0412

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#9402]
I understand the cause of this issue, but it is rather surprising. For `string` I think we have a way to fix this (I forgot where my issue was, I'll link it later) the solution being to make it not-inline.

In general, I think we should be able to create the least possible surprises when it comes to often-used functions like `printfn` and `string`. I don't know if this is in any way easy, but when prototyping one often just does a `printfn "%A"` to check what's in there, and FSI does the same.

This fails with byref-like types and `Span` and `ReadOnlySpan`, it throws the error: 

> error FS0412: A type instantiation involves a byref type. This is not permitted by the rules of Common IL.

**Repro steps**

Several ways to get this error, here's one of the simplest:

```f#
let x = "foo".AsSpan() in printfn "%A" x  // FS0412
let x = "foo".AsSpan() in string x  // FS0412
let x = "foo".AsSpan() in printfn "%O" x // FS0412
let x = "foo".AsSpan() in x.ToString()  // no error, prints "foo"
```

**Expected behavior**
There shouldn't be an error with certain library functions. I understand the limitation on `string`, but not sure for `printfn` family functions.

It is very unclear for a novice user when seeing "a type instantiation involves a byref type". It suggests that he is not allowed to instantiate his own byref type, while that is perfectly fine. While I think it is because the compiler thinks that a closure needs to be build and it assumes that that closure class will expose byref types (which is not allowed).

This can be observed here:

```f#
> let x = "".AsSpan() in (fun s -> s.ToString()) x;;

  let x = "".AsSpan() in (fun s -> s.ToString()) x;;
  ----------------------------^
stdin(52,29): error FS0412: A type instantiation involves a byref type. This is not permitted by the rules of Common IL.
```

But the byrefs are not part of the closure, so this should not be a problem

**Known workarounds**

None.

**Comment by cartermp** [comment]
So the root cause behind this is that they're generic functions, and since generics imply boxing, scoping rules disallows this. There's a very real problem with this here: https://github.com/fsharp/fslang-suggestions/issues/872

I think some more careful analysis of which functions be specialized could be done, but this is  tricky also because the functions live in FSharp.Core. So there would have to be work in the compiler to recognize when those functions are called with that data type and apply custom rules based on that. @dsyme tends to want to avoid this sort of thing from a principles standpoint. Unfortunately, much of core F# programming and Span are sort of at odds with one another.

The scoping rules w.r.t lambdas is also tricky business. I think that @tihan initially tried to figure out a way to be smart about some lambdas vs. others. Could also just be misremembering things.

**Comment by abelbraaksma** [comment]
Wasn't aware that it was such a potential can of worms. When you write such code (as also in the referenced proposal) my brain just goes like: hey, I'm just passing the ref like span on the stack, why do you forbid this?

But given this context, I understand a bit more the challenges involved. Perhaps a way out is a compiler attribute that's visible/used only internally in the Core, that hints that passing refs is possible because the function can deal with them, and/or it will be inlined anyway, so the IL limitations don't apply. That way, complex heuristics may be, well, a little less complex.

**Comment by NinoFloris** [comment]
What you're suggesting is hard to do as inlining isn't considered during type checking, see: 
https://github.com/fsharp/fslang-suggestions/issues/688

Not saying there are no solutions, especially if they're internal to the compiler, just that this is a known and difficult issue.

**Comment by abelbraaksma** [comment]
@NinoFloris, thanks for the link, it was surprising to find that I made basically the same suggestion there. Only half a year ago and I totally forgot. I'm getting old :stuck_out_tongue_closed_eyes:

**Comment by dsyme** [comment]
> much of core F# programming and Span are sort of at odds with one another.

Well, really much .NET programming and Span are at odds with each other :-) It's just people don't notice this as much in C# because you have to make more things explicit, and there's less reliance on generic coding for things like string formatting.

Anyway, this is indeed by-design.
