### ISSUE TITLE
Add type extension to System.Collections.List for GetReverseIndex

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#9425]
Currently, if you use a `ResizeArray` you can't use from-the-end indexes. This is trivial to add:

```fsharp
type System.Collections.Generic.List<'T> with
    member this.GetReverseIndex(_, idx) = this.Count - idx - 1
```

But it should probably be in the core library.

**Comment by Happypig375** [comment]
Or just accept the C# way of getting indexes from the end.

**Comment by cartermp** [comment]
@Happypig375 not sure what you mean here. We have an API `GetReverseIndex` for creating reverse indexes for F# 5 preview. We'll have to consider what interop with `System.Index` and `System.Range` means for F#, and that could affect what we do for this. But these are also unavailable for .NET Standard 2.0, so it's not straightforward to "just use what was shipped in .NET Core 3", if that's what you're hinting at.

**Comment by dsyme** [comment]
I'll track this in the RFC for reverse-indexing
