### ISSUE TITLE
When running a dotnet app "Not enough storage is available to process this command"

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#9463]
This just happened, while working on a very small project, and with working set of devenv.exe below 400MB, so it kind of comes as a surprise. Not sure if this is triggered by something in F#, but it certainly was an F# dotnetcore project.

![image](https://user-images.githubusercontent.com/16015770/84821135-ecff1600-b01a-11ea-8ab7-e8a7164bdee4.png)

**Repro steps**

While this devenv.exe is open, I can do <kbd>Ctrl-F5</kbd> and get the same error (~edit; not anymore~ edit 2: and it's back), but I've no idea how I got here as I've been doing compile-and-run for several hours now.

Commit size is rather high, though:

![image](https://user-images.githubusercontent.com/16015770/84821493-7d3d5b00-b01b-11ea-80f6-4d78e97806e2.png)

**Expected behavior**

There's no memory shortage (14GB free overall), no disk shortage (plenty free) and `devenv.exe` seems to have plenty too. So expected behavior: this message should not come.

**Actual behavior**

I did notice a certain sluggishness, which by itself was unexpected due to the small size and straightforwardness of the project, but then the messagebox popped up.

Of note:
* Compiling is fine, just running isn't
* Running with just <kbd>F5</kbd> (with debugger) also works
* afaik, "run" as opposed to "debug" runs out of process, so I'm very surprised to get that message

**Known workarounds**

Probably just restart VS. Or just wait a bit, because after typing this and hitting <kbd>Ctrl-F5</kbd> again it worked normal again.

**Comment by abelbraaksma** [comment]
OK, something's really iffy here, another first for me:

![image](https://user-images.githubusercontent.com/16015770/84821868-1b312580-b01c-11ea-98e5-c05795d2a926.png)

And indeed, I can't close it the normal way, nor can the IDE. Time to restart. Just posting here in case others have seen it and have some sense of what's going on.

**Comment by abelbraaksma** [comment]
LOL, and now this (while I endeavor to close VS):

![image](https://user-images.githubusercontent.com/16015770/84822022-56335900-b01c-11ea-884b-8ddd5d1ab5ab.png)

**Comment by KevinRansom** [comment]
Thats a scary looking set of messages.

There is this on support.microsoft.com   --- https://support.microsoft.com/en-us/help/106167/error-message-not-enough-server-storage-is-available-to-process-this-c

**Comment by cartermp** [comment]
@abelbraaksma wow, that seems wrong for simple programs and obviously for the low memory usage. Does this reproduce at all?

**Comment by KevinRansom** [comment]
@cartermp it's not really low memory, the link above sort of explains.

**Comment by abelbraaksma** [comment]
@KevinRansom, I'm not sure that link applies, as this is an isolated workstation, not part of a domain or any network. Also, the word "server" is not in my message (though that may have changed over the years).

It does look as if it's some non memory related resource though.

**Comment by dsyme** [comment]
I'll close this as it looks unrelated to F#

**Comment by abelbraaksma** [comment]
Yeah, also, it hasn't happened again, it was real weird though. Maybe something was very amiss on that workstation.
