### ISSUE TITLE
Is anyone still using the FSharpNetSdk mechanism for integrating F# into the dotnet cli

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#9471]
I have been asked by the project team about the target and props support for the old FSharpNetSdk.  Since they didn't understand it's purpose they questioned why we need to still support it.

What I would like to know, is there anyone still using it?  The answer definitely should be no, because we added FSharp directly into the Dotnet sdk way before DotNETSdk 2.0.

Anyway ... I would like to remove support for the FSharpNETSdk, is this likely to inconvenience anybody?

Thanks

Kevin

**Comment by Happypig375** [comment]
Do Xamarin projects depend on this?

**Comment by KevinRansom** [comment]
@Happypig375 , no they depend on either legacy mono projects or the netsdk.

**Comment by KevinRansom** [comment]
The latest version of the FSharpNetSdk is 1.05, released on 5/25/2017
https://www.nuget.org/packages/FSharp.NET.Sdk/

Which if memory serves, is about the same time that I added or was adding FSharp directly into the DotNetSdk.

**Comment by abelbraaksma** [comment]
In the last 6 weeks roughly 20k downloads: https://www.nuget.org/stats/packages/FSharp.NET.Sdk?groupby=Version. The user base is certainly not zero.

I do use legacy-style projects (unfortunately), but I don't think that has any dependency on `FSharp.NET.Sdk`. I admit I don't even know if any existing template depends on it.

**Comment by cartermp** [comment]
We should just remove it. All of the .NET versions that was built for are now out of servicing.

**Comment by KevinRansom** [comment]
I will add it to the list of things to do.  Yay!!!

**Comment by KevinRansom** [comment]
@abelbraaksma developers will still be able to use it.  Its just not with the latest tooling.

**Comment by dsyme** [comment]
Closing this old discussion issue
