### ISSUE TITLE
General question on PR's, when several PR's have a dependency on a commone one

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#9480]
Not a bug, just a question on expected _best practice_ in this repo. Suppose you prepared a few PR's, but some of these are dependent on a different change (in my case: I just need to move a function up in a module so it gets in scope for others), how best go about it? I can think of:

1. Create a separate branch + PR for the common change, then start new branches off this branch for the next PR's. 
   * Downside: each dependent PR will show the changes of the common PR which may confuse reviewers
   * Upside: I can submit all PR's without necessarily waiting for agreement
2. Create a separate branch + PR for the common change. Wait until this is merged into master, then start other PR's off this branch.
   * Downside: you'll need to wait before the common PR is accepted. If you continue with new PR's locally, you'll have to rebase.
   * Upside: cleaner history, easier review as each PR is isolated
3. If it's a small common change, do that change for each PR and let merging fix it.
   * Downside: each PR will have this change, merging may show conflicts, reviewers may be confused seeing the same change
   * Upside: no added PR-dependency complexity

I'm sure this stuff happens all the time and I'm not Git-whiz, so perhaps / hopefully there's a simple(r) answer here.

(I'm currently assuming `#1`  or `#2` to be the proper way, which I started https://github.com/dotnet/fsharp/pull/9481)

**Comment by smoothdeveloper** [comment]
I've used 1 myself for #8352 which is depended upon in #8354, 8352 was useful on it's own to add a new test.

If the base PR doesn't have use in itself, I think only doing the "leaf" PRs off a common branch would be the approach.

I don't think option 1 is confusing for reviewer as it contains all the changes that are to be reviewed against master, in case the base PR gets merged, the diff automatically disappear (assuming they are the same commits).

**Comment by abelbraaksma** [comment]
> I don't think option 1 is confusing for reviewer as it contains all the changes that are to be reviewed against master, in case the base PR gets merged, the diff automatically disappear (assuming they are the same commits).

@smoothdeveloper, tx! Yes, that's the idea. I didn't think of the disappearing diff after merge-into-master, that makes sense. I already started this way, glad it is the right approach (now just re-do the PR where I _didn't_ do it this way).

**Comment by NinoFloris** [comment]
Thanks for tagging in FSSF

If you know it's going to be in quickly I'd wait, otherwise rebase on the common change and clearly communicate up to which commit the common change goes, github doesn't really facilitate here sadly

**Comment by abelbraaksma** [comment]
@cartermp & @NinoFloris, ok, that's how I did it now, with a line in the PR pointing at the dependency. Thanks @all!
