### ISSUE TITLE
Cannot build latest master

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#9499]
FSharp.UIResources does not build on my machine, from the command line or the CLI.

Something to do with the Xaml:

![image](https://user-images.githubusercontent.com/6309070/85062002-9dc0fe80-b15c-11ea-8175-527120594588.png)

Rebuild, `git clean -xdf`, etc. all have no effect. It is not possible to build the F# tooling and try out any changes with them.

**Comment by KevinRansom** [comment]
@brettfo fixed this.

**Comment by cartermp** [comment]
Though it's not actually fixed when using dogfood builds. But I'll wait a bit, perhaps there's something weird going on with dogfood VS
