### ISSUE TITLE
"Track active item in solution explorer" doesn't work for FSharp.sln

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#9514]
This is possibly a well-know fact, apologies if this is just one of those "we'll have to live with it". I usually have the following setting switched on, as it's one of the few ways to keep my sanity in large projects:

![image](https://user-images.githubusercontent.com/16015770/85205318-02c25300-b31b-11ea-8b5b-3b0e0c34f579.png)

However, when I have the `FSharp.sln` open from Github, through my fork, it doesn't follow the active item at all. In the past there used to be a button in Solution Explorer that could sync, but that's not there anymore, so I don't have a workaround.

In any other project I tried so far, it "just works", whether or not it is an F# prj or not.

**Repro steps**

Seems to happen always, regardless how many restarts I do, yet only for solutions in the F# repo.

**Expected behavior**

Active item should be followed in Solution Explorer window.

**Actual behavior**

Nothing changes in the Solution Explorer, which makes it sometimes very hard to find the actual item. Using "Search" seems to be the fastest way, by typing the file name, but that isn't ideal at all.

**Known workarounds**

Use "Search", which isn't really a workaround.

**Comment by cartermp** [comment]
I've never used that feature before, but I wonder if it has to do with linked files? The codebase makes very heavy use of linked files and "magic" folders that don't look anything at all like what you see on disk. I don't like it because it's so nonstandard, hard to make sense of relative to what's on disk, and I believe affects some tools like the Test Explorer's test discovery and selection UI. But I suspect this is why it is the way it is.

**Comment by abelbraaksma** [comment]
@cartermp, it's actually a very handy feature ;). In my own projects I also use linked files (mainly for "same version everywhere", nothing really fancy) and there it just works.

But now that I had a peak into some of the prj files, they are indeed structured in a somewhat surprising way, which may well be the cause of this behavior.

**Comment by abelbraaksma** [comment]
@cartermp, you were indeed correct, this was caused by the linked files. I can now confirm that the issue does not arise for the files in the solution that have normal include semantics.

I'll go ahead and close this, as it's not an issue with F#.

**Comment by cartermp** [comment]
@abelbraaksma might be worth submitting via the VS report a problem.
