### ISSUE TITLE
#r "nuget: ..." doesn't give diagnostic for invalid package reference

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#9540]
Please provide a succinct description of the issue.

**Repro steps**

1. `dotnet artifacts\bin\fsi\Debug\netcoreapp3.1\fsi.exe --langversion:preview`

2. `#r "nuget: Random Failure= %%490-b42m31";;`

3. `1+1;;` to force resolution 

Expect: error message of some kind

Actual: the pseudo-project is loaded and no error is reported:
```
[Loading C:\Users\dsyme\AppData\Local\Temp\nuget\18032--86f60457-541c-4456-82b3-74205fef7697\Project.fsproj.fsx]
namespace FSI_0002.Project

val it : int = 1
```

**Known workarounds**

Don't make mistakes in package references

**Related information**

Windows master

**Comment by dsyme** [comment]
@KevinRansom this one is important to fix.  Currently there's no feedback at all on bad references

```
C:\GitHub\dsyme\fsharp>dotnet artifacts\bin\fsi\Debug\netcoreapp3.1\fsi.exe --langversion:preview

Microsoft (R) F# Interactive version 11.0.0.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

>
-
- #r "nuget: Random Failure= %%490-b42m31";;
[Loading C:\Users\dsyme\AppData\Local\Temp\nuget\31332--84882ce8-d56d-402f-a9d4-5a437ecf54b8\Project.fsproj.fsx]
namespace FSI_0002.Project

>
-
```

**Comment by KevinRansom** [comment]
@dsyme ... yes that seems like a pretty rubbish experience.

**Comment by KevinRansom** [comment]
merged:  https://github.com/dotnet/fsharp/pull/9950
