### ISSUE TITLE
Redundant local variables sometimes apear

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/fsharp#9547]
Consider the following snippet (taken from #9153):

``` fsharp
open System
open System.Globalization

let anyToString nullString str =
    match box str with
    | :? IFormattable as x -> x.ToString("", CultureInfo.InvariantCulture)
    | null -> nullString
    | x -> x.ToString()
```

It gets compiled into

``` csharp
public static string anyToString<a>(string nullString, a str)
{
    object obj = str;
    IFormattable formattable = obj as IFormattable;
    if (formattable != null)
    {
        IFormattable formattable2 = formattable;
        return formattable2.ToString("", CultureInfo.InvariantCulture);
    }
    if (obj != null)
    {
        object obj2 = obj;
        return obj2.ToString();
    }
    return nullString;
}
```

Notice the unexplained and unnecessary defensive copies in `obj2` and `formattable2`. It can be argued that the JIT will optimize thems away, but we cannot be always sure, and there might be times they won't. Besides, removing these two locals will produce more compact code.

**Comment by abelbraaksma** [comment]
> It can be argued that the JIT will optimize thems away, but we cannot be always sure, and there might be times they won't. 

I noticed that too in several researches (and in that code I posted), so I've checked the disassembly from JIT, and it actually does do a good job in eliminating redundant variable assignment, or unused variables. In fact, it was better at it than I expected. 

But u agree with your point and maybe this can go in the last of the optimizations passes.

**Comment by dsyme** [comment]
In the absence of performance numbers I'm closing this as the JIT will indeed optimize these away.  Removing them would likely cause as many problems as it helps

**Comment by smoothdeveloper** [comment]
Maybe it is still important we track the constructs that rely on those generating intermediates in the IL, it doesn't mean that we would solve it, but document it, for later design consideration.

IIRC @kerams worked on stuff that are closely similar, like tuple elision, saving some locals and allocation (here it is not the case, due to JIT), so such issue may still be something one may contribute.

@dsyme, is it ok to mark those as "up for grabs" still?

**Comment by dsyme** [comment]
@smoothdeveloper In the absence of actual performance numbers we wouldn't actually know if a change here was an improvement - and for this one in particular I expect it wouldn't be.

The .NET JIT basically reverses the removal of IL locals, creating a JIT tree full of  JIT locals, and then labels them for registers.  So removing the IL locals never really does much
