### ISSUE TITLE
Using for-loops with the ".." operator produces suboptimal code

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/fsharp#9548]
Consider the following snippet:

``` fsharp
open System

let f() =
  for x in 0 .. 15 do
    Console.WriteLine x
```

It produces a nice, C#esque for-loop. Now consider this one:

``` fsharp
open System

let g() =
  for x in 0 .. 2 .. 15 do
    Console.WriteLine x
```

It creates a sequence and then enumerates it. And it also has a consecutive pair of `ldnull; pop;` twice, as well as a needless `unit` local.

Producing a `for (int i = 0; i < 15; i += 2)` in the second case would have been much more efficient. We could even generalize it to arbitrary types with an addition operator, not just ints. Furthermore, in the first example, replacing the loop with `for x in 0.0 .. 15.0` creates a sequence too.

In addition, using like `for x in [0 .. 15]` does correctly produce a list, but the compiler should warn to better remove the brackets when using a ranged list literal in a loop.

**Comment by abelbraaksma** [comment]
> for x in 0 .. 15 do

It creates a sequence. It's twice as fast if you use the `for.. to ` syntax.

I believe there's a feature underway that allows for such optimizations, though, which would blur the performance differences more.

**Comment by teo-tsirpanis** [comment]
> It creates a sequence. It's twice as fast if you use the `for.. to` syntax.

No, it doesn't. The compiler generates identical code.

![image](https://user-images.githubusercontent.com/12659251/85528418-824e6b80-b614-11ea-9538-1578508a82ef.png)

This happens only on integers, and not when the double `.. ..` operator is used.

**Comment by abelbraaksma** [comment]
That's interesting. For sure, only a few days ago, I noticed the opposite. I'll try to find that back, as that may suggest that it depends on the situation.

**Comment by abelbraaksma** [comment]
Hmm, it can be subtle. Consider this:

```f#
> let f y x = for _=0 to y do for i in x do String.length i |> ignore;;
val f : y:int -> x:seq<string> -> unit
> let g y (x: array<_>) = for _=0 to y do for i in x do String.length i |> ignore;;
val g : y:int -> x:string array -> unit
```

Now, when you call `f` with an array, the optimization will _not_ kick in, and the enumerator is called. In this case leading to about 4x perf loss. If you call `g` (which, of course, cannot be called with any sequence), the difference becomes clear.

If, instead, you were to do a type-test before entering the loop and use two paths for sequence and arrays, you get the original perf of `g` back again.

There's something to be said to optimize this in the compiler too (though not directly your original request, sorry for digressing).

```f#
> f 10_000_000 values;;
Real: 00:00:00.846, CPU: 00:00:00.842, GC gen0: 51, gen1: 1, gen2: 0
> g 10_000_000 values;;
Real: 00:00:00.113, CPU: 00:00:00.124, GC gen0: 0, gen1: 0, gen2: 0
```

**Comment by cartermp** [comment]
Note that the optimization does not happen for other numeric types: https://sharplab.io/#v2:DYLgZgzgPmD2BOACAHoglgO0QBgDIDp8BGbPRAE1kQAd5MAXMLAIgAsBTYYWZoA=

Though it is admittedly not as straightforward, since you can't index into an array unless it's an int.

**Comment by teo-tsirpanis** [comment]
> If, instead, you were to do a type-test before entering the loop and use two paths for sequence and arrays, you get the original perf of g back again.

These two paths would require the entire loop body code to be duplicated. I'm not sure whether it's worth it. After all, the developer is fully aware of the performance implications the `for in` loop entails. The optimization that occurs when iterating a known IEnumerable subtype (it also works on lists as well) is good but should need no generalization.

Something better we could do is to perform type tests on `Seq.iter` but we have to consider the cost of a type test (or many type tests; if the `seq` to be `iter`ed is a real `seq`, it will first be tested against whether it is an array, a list, a `Set` and then it will be `iter`ed), and the fact that there are so many implementations of IEnumerable and we cannot specially treat them all.

> you can't index into an array unless it's an int

@cartermp your snippet should be optimized into `for x = 0L to 100L` but we can't even do a `for to` loop with types other than integers.

**Comment by abelbraaksma** [comment]
> and the fact that there are so many implementations of IEnumerable and we cannot specially treat them all.

I'd only be interested in the following cases, which I think make sense:

* list and array
* when the compiler can detect it statically, or the type test does not degrade performance 

People should not be punished when using an array in a function that accepts a sequence.
