### ISSUE TITLE
F# debugger / .net core: pattern matching variable to not work in locals, watch or immediate

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#9554]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/826573/f-debugger-net-core-pattern-matching-variable-to-n.html)._

---
F# pattern matching variables do not show up in the debugger at all.

---
#### Visual Studio Feedback System on 11/19/2019, 10:06 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 12/5/2019, 10:39 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by dsyme** [comment]
@cartermp I think we should close this, we don't have enough information to know the repro
