### ISSUE TITLE
F# .net core debugger: Inline functions don't work as expected in debugger even in Debug builds

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#9555]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/826574/f-net-core-debugger-inline-functions-dont-work-as.html)._

---
Breakpoints on inline functions do not work, even in Debug builds. 
(Maybe have an option to ignore "inline" in Debug if type-specialization is not required?)
Stepping into inlines does work sometimes.

---
#### Visual Studio Feedback System on 11/19/2019, 10:06 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 12/5/2019, 10:39 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by abelbraaksma** [comment]
Indeed, there's an issue open somewhere to enable stepping through inline functions, but it's non-trivial (but not too hard either).

**Comment by abelbraaksma** [comment]
Found it: https://github.com/fsharp/fslang-suggestions/issues/824

**Comment by dsyme** [comment]
@abelbraaksma Thanks yes that is the same issue
