### ISSUE TITLE
Could not execute because the specified command or file was not found.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#9557]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/996285/could-not-execute-because-the-specified-command-or.html)._

---
using SDK 3.1.201 

This is a regression I last experienced over 6 months ago, and never found a good solution for, with a subsequent SDK it just stopped happening.

Attempting a build in powershell

`dotnet build -v n`

I get this build error:

```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
   * You misspelled a built-in dotnet command.
   * You intended to execute a .NET Core program, but dotnet-@C:\Users\Jack\AppData\Local\Temp\tmp9303a3278df649d085f804e8e653d16a.rsp does not exist.
   * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
5>C:\Program Files\dotnet\sdk\3.1.201\FSharp\Microsoft.FSharp.Targets(279,9): error MSB6006: "dotnet.exe" exited with code 1. [E:\GitRepos\dataphysicsetl\DataPhysicsETL.Core\DataPhysicsETL.Core.fsproj]
```

If I build inside Visual Studio, then I can successfully build in powershell again.

---
#### Kim Reardon on 4/17/2020, 10:39 AM: 

<p>I'm seeing the same problem</p>

#### Visual Studio Feedback System on 4/19/2020, 10:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Phillip Carter [MSFT] on 4/23/2020, 04:40 PM: 

<p>Hey there, that one sounds confusing for sure. I don’t think there’s inherently something to do with F# here, since the F# targets don’t really touch anything related to the build command. But there’s clearly something wonky going on.</p>
<p>Do you have a project where this reproduces that you could share? That would be helpful. Thanks!</p>

#### Jack Fox on 4/27/2020, 02:43 PM: 

<p>It's a mix of F# netstandard2.0 and netcoreapp3.1 projects. We have other solutions like that, but do not have this problem.<br>I cannot post the solution, but I'm happy to get on a screen share anytime. <a rel="user" href="https://developercommunity.visualstudio.com/users/8434/1046a66a-2c84-4109-a7c3-3b10d3e657ed.html" nodeid="8434">@Phillip Carter [MSFT]</a> </p>

#### Jon Sequeira [MSFT] on 6/24/2020, 11:15 AM: 

<p>A screen share would be useful. We’ll reach out to you directly to set up a time.</p>

---
### Original Solutions
(no solutions)

**Comment by jackfoxy** [comment]
We finally resolved this by adding an import project element to the F# projects
```

<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\fsc.props" />
```

We still have no idea why this F# solution was special and had same problem in Azure Devops without the fsc.props. We maintain several other F# projects without this issue.

```
<?xml version="1.0" encoding="utf-8"?>
<Project>
  <!-- Type providers currently can't run inside the .NET Core 2.0 hosted compiler, see https://github.com/Microsoft/visualfsharp/pull/3658#issuecomment-334773415 -->
  <PropertyGroup>
    <IsWindows Condition="'$(OS)' == 'Windows_NT'">true</IsWindows>
    <IsOSX Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))' == 'true'">true</IsOSX>
    <IsLinux Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' == 'true'">true</IsLinux>
  </PropertyGroup>  
  <PropertyGroup Condition="'$(IsWindows)' == 'true' AND Exists('C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\FSharp\fsc.exe')">
    <FscToolPath>C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\FSharp</FscToolPath>
    <FscToolExe>fsc.exe</FscToolExe>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsWindows)' == 'true' AND Exists('C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\fsc.exe')">
    <FscToolPath>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp</FscToolPath>
    <FscToolExe>fsc.exe</FscToolExe>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsWindows)' == 'true' AND Exists('C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\FSharp\fsc.exe')">
    <FscToolPath>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\FSharp</FscToolPath>
    <FscToolExe>fsc.exe</FscToolExe>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsWindows)' == 'true' AND Exists('C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp\fsc.exe')">
    <FscToolPath>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp</FscToolPath>
    <FscToolExe>fsc.exe</FscToolExe>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsOSX)' == 'true'  AND Exists('/Library/Frameworks/Mono.framework/Versions/Current/Commands/fsharpc')">
    <FscToolPath>/Library/Frameworks/Mono.framework/Versions/Current/Commands</FscToolPath>
    <FscToolExe>fsharpc</FscToolExe>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsLinux)' == 'true' AND Exists('/usr/bin/fsharpc')">
    <FscToolPath>/usr/bin</FscToolPath>
    <FscToolExe>fsharpc</FscToolExe>
  </PropertyGroup>
</Project>
```

**Comment by dsyme** [comment]
It feels to me like we don't have a strong active repro for this and that the high likelihood is that it was to do with some point-in-tim change in the way SDK projects are processed.

@cartermp @jackfoxy  am closing, please double check?

**Comment by jackfoxy** [comment]
@dsyme @cartermp  having to use a fsc.props file has just become a regular thing for us.
Just tried testing one of our solutions without it, and `dotnet build` failed (on my local machine).
I have no explanation and no time this week to investigate further


`C:\Program Files\dotnet\sdk\3.1.401\FSharp\Microsoft.FSharp.Targets(279,9): error MSB6006: "dotnet.exe" exited with code 1. [E:\GitRepos\dataphysicsetl\DataPhysicsETL.Core\DataPhysicsETL.Core.fsproj]`

**Comment by jackfoxy** [comment]
Partial explanation is I have all kinds of crazy paths to msbuild.exe and fsc.exe after installing Visual Studio for the past 7 years on this machine.

**Comment by cartermp** [comment]
> Partial explanation is I have all kinds of crazy paths to msbuild.exe and fsc.exe after installing Visual Studio for the past 7 years on this machine.

That would probably be the most relevant part of this. Custom paths to varying toolsets can ultimately mess with things.

**Comment by jackfoxy** [comment]
@cartermp I don't think any of them are custom, but rather MS changing paths over framework/dotnet releases.

Could be this path:

`C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\fsc.exe`

which I don not include in the `fsc.props`

**Comment by cartermp** [comment]
There should be no reason to include that path or others like it in any of your projects unless you have a hard requirement to use an older F# toolset for some reason. Nor for any paths to MSBuild SDKs or the like. It may be that you have something specified in a project file somewhere that effectively says, "compile me with this older compiler" and the fsc.props file gets the right path in MSBuild inputs to make it happen. The fix here would be to ultimately clean that kind of stuff out of your project files or props files elsewhere and allow your codebase to be built under different toolsets over time. This state would be the normal, default for the vast majority of F# codebases out there so I don't think there would be anything wrong with doing that.

**Comment by jackfoxy** [comment]
You were right. There was some old obsolete patch in the project files.

```
    <!-- required for https://github.com/Microsoft/visualfsharp/issues/6326 -->
    <DisableAutoSetFscCompilerPath>true</DisableAutoSetFscCompilerPath>
    <DotnetFscCompilerPath></DotnetFscCompilerPath>
```
