### ISSUE TITLE
Regex Literal and Expression

### ISSUE THREAD

**Issue by no1melman** [dotnet/fsharp#9571]
This is my first request, any help would be appreciated...

```fsharp
type Face = Ace | Two | Three | Four // ...etc
type Suit = Spades | Hearts | Diamonds | Clubs

let parsingFaceMap =
  [ // etc....
    ("3", Three); ("2", Two); ("A", Ace) ] |> Map.ofList

let parsingSuitMap = [ ("H", Hearts); ("D", Diamonds); ("S", Spades); ("C", Clubs) ] |> Map.ofList

let parseCard (card: string) =
  let possibleCard =
    let cardRegex = Regex("^(?<face>(\\d+|a|j|q|k))(?<suit>[a-z])$", RegexOptions.IgnoreCase)
    let matchedGroups = cardRegex.Match(card)
    let faceGroup = matchedGroups.Groups.["face"]
    let suitGroup = matchedGroups.Groups.["suit"]
    if suitGroup.Success && faceGroup.Success then
      Some (faceGroup.Value, suitGroup.Value)
    else
      None

  match possibleCard with
  | Some (face, suit) ->
      face |> parsingFaceMap.TryFind |> Option.bind (fun first -> // real value here
        suit |> parsingSuitMap.TryFind |> Option.map (fun second -> // real value
          first,second
        ))
  | None -> None

```

I feel like there is a lot of code just to establish some matches with the regex and to do it safely.

**Describe the solution you'd like**

Regex could become a literal and also have a module like List or Seq or Option.

Taking inspiration from JavaScript

```fsharp
let parseCard (card: string) =
  let possibleCard =
     card
    |> /^(?<face>(\\d+|a|j|q|k))(?<suit>[a-z])$/i.match
    |> RegExp.mapGroups // RegExp -> Groups
    |> RegExp.filter (fun groupName -> groupName = "face" || groupName = "suit") // Groups -> Groups
    |> RegExp.toList // Groups -> string option list
    |> Seq.foldBack (Option.map2 (fun x y -> x::y)) list (Some []) // string option list -> string list option
    |> Option.map (fun parts -> (parts.[0], parts.[1])) // string list option -> (string * string) option)
  
  match possibleCard with
  | Some (face, suit) ->
      face |> parsingFaceMap.TryFind |> Option.bind (fun first -> 
        suit |> parsingSuitMap.TryFind |> Option.map (fun second ->
          first,second
        ))
  | None -> None
```

[Group](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.group?view=netcore-3.1) is similar to an option type,` if success Some value else None`

Here the literal is `/{REGEX}/{FLAGS}` this could be complex literal type and there for dot from it

```fsharp
/\d/i.test "2" // -> true
/\d/i.match "2" // -> Matches
```

`type Matches = Match list` could be a special type that then allows for the `RegExp` module to perform functions over. But at anytime you could do `RegExp.toList` to do `Matches -> Match list` or `Matches -> string option list`, you could have `RegExp.toOption` to do `Match -> string option`

So in the above example, `RegExp.mapGroups` could extract all the named groups from the matches allowing to the user to further select over them. Either by doing something like `RegExp.filter` to select matching groups (if they appear or not). Then using `RegExp.toList` it will turn a `Group` type into `string option list` which is more F# friendly. 

`RegExp.mapGroups` is just synonymous to `Regex().Groups`, you could have `RegExp.map` which does `Regex().Matches`. Then the type you're passed for each one is the `Group` or `Match` respectively.

Before defining the behaviour, I wanted to get feedback, to see if this was something already thought about - or if this is going in the wrong direction.

**Comment by Happypig375** [comment]
C# went for syntax coloring of Regex strings instead of regex literals. We may want this too: Syntax coloring for the string argument to `Regex.create`.

**Comment by TheJayMann** [comment]
This is also something that can be made even easier with a type provider rather than a language change.  In fact, such a type provider already exists.  https://fsprojects.github.io/FSharp.Text.RegexProvider/
The idea of adding syntax coloring to literals which are known to be a regex string literal would still be helpful, especially if it can be made such that the type provider can make use of it.

**Comment by no1melman** [comment]
I think making that Regex literal that does what the Type provider does would be an awesome solution!!

**Comment by cartermp** [comment]
I don't think we'll do a language suggestion or integrate with a type provider in the tools. We can expose the Roslyn machinery through our F# bindings on the Roslyn side, and when those APIs are updated in our own codebase we can consume them and get a similar experience as C#.

If you're interested in regex literals within the language itself, please file a language suggestion here: https://github.com/fsharp/fslang-suggestions

Though I'm not sure how likely it is to be accepted.
