### ISSUE TITLE
FS0041: does not prefer an overload with exact type match due to an unrelated argument

### ISSUE THREAD

**Issue by lostmsu** [dotnet/fsharp#9620]
F# does not prefer an overload with exact type match for argument 1, when argument 2 is an instance of class implementing corresponding parameter type (an interface).

**Repro steps**

```fsharp
type TestClass private() =
    static member M(baseOrDerived: obj, enumerable: IEnumerable<obj>) = ()
    static member M(baseOrDerived: Uri, enumerable: IEnumerable<obj>) = ()

[<EntryPoint>]
let main argv =
    TestClass.M(
        baseOrDerived = Uri("42"),
        enumerable = (*Seq.cast<obj>*) [obj()])
```

Curiously, making 2nd argument match type exactly by uncommenting the `Seq.cast` resolves the issue for this specific case.

[SharpLab](https://sharplab.io/#v2:DYLgZgzgNALiCGEC2AfA9gBwKYDsAEAygJ4QxZICwAUJroSWUgHQDCawwWAxjAJZo4ITAOK4sAJ15dq1GEWx4AKllItgiCHgySAbvDIAKAJR4AvNTyW8pfVLxJyAIwl4AsgceIsAeXEARCV4dLAATEDw0RwArKDxcAFcHcXhHTnCASQBRHESJFM4AHkiogD4TUzxjCysbPi57Jxd3Twgff0DgsLwAVUlYhKT8rAzs3OTUrCLosrNKoxkqAG0C7JhxIgAFNF4cGBKAXWpOGHt4Hbx4cQBzHTNqy2VVdQghd3urSxa2gN1Q2d7eAYAEQAFgATECjFB3h8BnkJrMDAAqAhYACOTC4iBgU1KSJMi2Kxn2RiAA===)

**Expected behavior**

No error

**Actual behavior**

> A unique overload for method 'M' could not be determined based on type information prior to this program point. A type annotation may be needed.
> Known types of arguments:
> - baseOrDerived:Uri * enumerable:obj list
> Candidates:
> - static member TestClass.M : baseOrDerived:Uri * enumerable:IEnumerable<obj> -> unit
> - static member TestClass.M : baseOrDerived:obj * enumerable:IEnumerable<obj> -> unit

**Related information**

* .NET Core SDK 3.1.400-preview-015178

**C# behavior**

In C# the overload with the strongest matching derived type is always used.

**Comment by cartermp** [comment]
This behavior would be considered by design. F# just doesn’t do the same kind of type hierarchy crawling as C# when considering overloads.

**Comment by lostmsu** [comment]
@cartermp the hierarchy part is not as much concerning as _having_ vs _not having_ an exact type match on parameter 2 affecting ability to choose an overload based on parameter 1 type being exact vs not exact match. Are there overload resolution rules I can refer to?

**Comment by abelbraaksma** [comment]
I haven't tried your code, but I think it's because you pass a list, and not a sequence. Normally, you'll need to instruct F# by telling you want a specific interface, for instance `enumerable = [obj():> _])`.

I suspect the code would fail too if you wouldn't have the overloads. 

Also, your overloads are typed as `IEnumerable`, it's usually clearer to just use `seq`, which is the same, but clearer.

**Comment by lostmsu** [comment]
> I suspect the code would fail too if you wouldn't have the overloads.

That is not the reason. It compiles:

```fsharp
open System
open System.Collections.Generic

type TestClass private() =
    static member M(enumerable: IEnumerable<obj>) = ()
    //static member M(baseOrDerived: Uri, enumerable: IEnumerable<obj>) = ()

[<EntryPoint>]
let main argv =
    TestClass.M(
        //baseOrDerived = Uri("42"),
        enumerable = (*Seq.cast<obj>*) [obj()])
    42
```

[SharpLab](https://sharplab.io/#v2:DYLgZgzgNALiCGEC2AfA9gBwKYDsAEAygJ4QxZICwAUJroSWUgHQDCawwWAxjAJZo4ITAOK4sAJ15dq1GEWx4AKllItgiCHgySAbvDIAKAJR4AvNTyW8pfVLxJyAIwl4AsgdwBXB+PiPOIHgAkgCiON4SfpwAPGiOAFYAfCameMYWVgD0mTZ8XPZOLu6OiFgA8uIAIhK8OlgAJoEAqpJQeF4+UViBoeGd/lixCclmaUYyVADa0WEw4kQACmi8ODCJALrUnDD28Ct48OIA5jpmGZbKquoQQu7nVpbZJRDlVTV19aMtvAYARAAsACZfkYoPcHh1IgNRgYAFQELAARyYXEQMCGSVhJkmcXixnW4yoDyBQA=)

**Comment by abelbraaksma** [comment]
@lostmsu, you are right, I was confused with covariance for first order functions:

```f#
module TestMe =
    let M f (e: obj seq) = f e

let main argv =
    TestMe.M (fun (x: obj list) -> ())  [obj()]   // fail
```

However, @cartermp, I think there's a bug here after all. If we remove the parameter name assignment syntax, it "just works", but with the parameter names, it fails:

```f#
type TestClass private() =
    static member M(baseOrDerived: obj, enumerable: obj seq) = ()
    static member M(baseOrDerived: Uri, enumerable: obj seq) = ()

let main argv =
    TestClass.M(Uri(""), enumerable = [obj()]) // works
    TestClass.M(baseOrDerived = Uri(""), enumerable = [obj()]) // fails
```

If we change both parameter names, it works in both cases:

```f#
type TestClass private() =
    static member M(baseOrDerived1: obj, enumerable: obj seq) = ()
    static member M(baseOrDerived2: Uri, enumerable: obj seq) = ()

let main argv =
    TestClass.M(Uri(""), enumerable = [obj()]) // works
    TestClass.M(baseOrDerived2 = Uri(""), enumerable = [obj()]) // works
```

Which means that using the parameter name assignment syntax leads to different overriding rules than without. That doesn't seem to be right. Perhaps reopen after all?
