### ISSUE TITLE
Dotnet fsi shows wrong line for error, points to non-error line

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#9631]
Basically, just this:

![image](https://user-images.githubusercontent.com/16015770/86602422-e6711800-bfa2-11ea-8e33-f59445da2919.png)

The same behavior **does not** happen inside VS.

**Comment by abonie** [comment]
Fixed by https://github.com/dotnet/fsharp/pull/14334

**Comment by abelbraaksma** [comment]
Great stuff, thanks!
