### ISSUE TITLE
Tabs are not allowed error in VS2019

### ISSUE THREAD

**Issue by halcwb** [dotnet/fsharp#9662]
#### Please provide a succinct description of the issue.

Using a tab in an FSX file suddenly started displaying the tabs are not allowed error in VS 2019. I did subsequently the latest update with no luck. I checked the settings (see figure), but the setting is correct.

#### Provide the steps required to reproduce the problem:

Suddenly started happening, no idea what caused it.
When using a tab, this is not replaced by spaces, and an error is shown.

#### Provide a description of the expected behavior.

Should replace tabs with spaces automatically.

Provide a description of the actual behaviour observed. 

<img width="1290" alt="VS Tabs issue" src="https://user-images.githubusercontent.com/683631/87143057-cb095400-c2a5-11ea-80b2-4cfc1a5955ed.png">

#### Provide a description of any known workarounds.

Use the space bar to indent, but this is really impractical.

#### Provide any related information (optional):

Microsoft Visual Studio Community 2019
Version 16.6.3
VisualStudio.16.Release/16.6.3+30225.117
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Community

ASP.NET and Web Tools 2019   16.6.954.58314
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2020603+b3ac44798c16fff5b95dbcfe62dea84aa9a1bd72
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.6.954.58314
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.6.954.58314
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.6.954.58314
Azure Functions and Web Jobs Tools

C# Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.6.20100.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30212.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.50+g25aae5a24a.R
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.6.20100.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.6.20100.1
Conda support for Python projects.

Python - Django support   16.6.20100.1
Provides templates and integration for the Django web framework.

Python - IronPython support   16.6.20100.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.6.20100.1
Profiling support for Python projects.

SQL Server Data Tools   16.0.62006.03190
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.20417.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.9.1.0 for F# 4.7   16.6.0-beta.20217.4+1c969cac25e2d38d71872efe6c8226029e42bb59
Microsoft Visual F# Tools 10.9.1.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]

**Comment by cartermp** [comment]
@halcwb did this occur after pasting something in and getting an exception in the editor? There is a bug where the VS editor somehow errors out when paste certain things. I noticed this once in a non-script but that was the only indicator. Otherwise I've never been able to reproduce this. Nothing in the F# tools has any say in tabs or the default settings for them, so I think this is more likely to be an issue in the editor than in the F# tools.

**Comment by halcwb** [comment]
@cartermp. Thanks for the quick reply. It is a really strange problem. It is know constant! I tried updating VS2019, restarting the computer. But still, whenever I use a tab, I get the error.

**Comment by xperiandri** [comment]
I experience the same bug in Visual Studio 2022

**Comment by xperiandri** [comment]
Why not just replace leading tabs on paste?
