### ISSUE TITLE
Cant make finally blocks run under .net core on macOS

### ISSUE THREAD

**Issue by hsorbo** [dotnet/fsharp#9663]
Cant make my finally blocks run under .net core on macOS (works on windows)

```
[<EntryPoint>]
let main argv =
    try
        failwith "where is my finally?"
    finally
        printfn "here is my finally"
    0
```
The example shows printfn, I have tried with saving a file (`System.IO.File.WriteAllText`) with same result (created on windows, not on macOS) (in case it was terminal-flushing-issues)
In the happy case of no exceptions, the finally block runs

**Expected behavior**

Windows
```
dotnet run
Unhandled exception. System.Exception: where is my finally?
   at Program.main(String[] argv) in c:\Users\hsorbo\tmp\Program.fs:line 4
here is my finally
```

**Actual behavior**

```
dotnet run
Unhandled exception. System.Exception: where is my finally?
   at Program.main(String[] argv) in /Users/hsorbo/tmp/a/Program.fs:line 4
```

**Known workarounds**

Use catch-all-exception

**System information**
```
uname -a
Darwin macabre.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

dotnet --version
3.1.301

dotnet --list-runtimes
Microsoft.AspNetCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

```

**Comment by hsorbo** [comment]
Another example:
```
[<EntryPoint>]
let main argv =
    try
        failwith "where is my finally?"
    finally
        printfn "sleeping....."
        System.Threading.Thread.Sleep(2147483647)
    0```

runs "forever" on windows, terminates immidiately on macos

**Comment by hsorbo** [comment]
Runs fine under xunit/dotnet test.
```
module Tests
open Xunit
[<Fact>]
let ``TestFail`` () =
    let mutable fail = false
    try
        failwith "error"
    finally
        fail <- true
    Assert.True(fail)
```
Seems to be only when run as standalone/dotnet run.

**Comment by cartermp** [comment]
Thanks for filing, this is bizarre. Can reproduce.

**Comment by dsyme** [comment]
@cartermp @TIHan @KevinRansom This seems like a major bug.  But I can't believe any tests would be passing without executing finallys.  Any idea what's what on this?

**Comment by KevinRansom** [comment]
@hsorbo suggests it's platform specific, so perhaps non of the mac tests show, it.

I will add it to my list of things to look at.

**Comment by KevinRansom** [comment]
@hsorbo 
The finallys operate correctly, the issue you are seeing is to do with how the macos implementation of the coreclr handles console IO in the presence of unhandled exceptions.

To demonstrate this, if your example is wrapped in a try catch things behave as one would expect.

````
open System

[<EntryPoint>]
let main _ =
    let mutable result = 0
    try
        try
            Console.WriteLine("Here is my try")
            failwith "where is my finally?"
        finally
            Console.WriteLine("In the finally")
    with | _ -> ()

    Console.WriteLine("The end of all things")
    0
    ````

Produces this output:
````
Here is my try
In the finally
The end of all things
Kevins-MBP:AnApp kevinr$ 
````

**Comment by hsorbo** [comment]
@KevinRansom I don't quite see how [this earlier example](https://github.com/dotnet/fsharp/issues/9663#issuecomment-671552824) isnt working because of console IO. (quits immediately vs runs forever).

Is https://github.com/dotnet/runtime/issues the correct repo for raising bug with coreclr team?

**Comment by 0x53A** [comment]
This looks similar to this SO question / answer: https://stackoverflow.com/a/44076534
The important part is the  _[...] on __unhandled__ exception [...]._

That is, it's not that ``finally`` doesn't work at all, it's that on some platforms, on an unhandled exception, the process is killed immediatly instead of running finally blocks etc.

This is documented behavior: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-finally

> However, if the exception is unhandled, execution of the finally block is dependent on how the exception unwind operation is triggered.

**Comment by hsorbo** [comment]
@0x53A  Thank you so much!
