### ISSUE TITLE
Third navigation dropdown closes prematurely

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#9664]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/719083/third-navigation-dropdown-closes-prematurely.html)._

---
So far as I can tell, this is a problem in F# files but not C# files.

There are three navigation dropdowns at the top of a file. The rightmost one (I don't know what to call it), exhibits some odd scroll behavior. Assuming I'm on a module with sufficient items so that the list portion of the dropdown is big enough that a scrollbar appears.... here is what happens:

I click between the thumb and the bottom of the scrollbar (to "page down"), and the drop down list closes.

Or, lets say I grab the thumb and scroll to the bottom of the list. No problem. But then I click between the thumb and the top of the scroll bar (to "page up") and again the list just closes.

Sometimes, that is. Sometimes it behaves as expected. Since it doesn't happen consistently, it might be happening on C# files as well, and I'm just not noticing it, because I spend much more time in F# than C#.

---
#### Feedback Bot on 9/2/2019, 00:42 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/8/2019, 02:25 AM: 

I have detected that for the last 35 days, this issue didn't have any product team activity and a very small amount of new votes or comments.&nbsp;Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Feedback Bot on 2/5/2020, 11:04 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by cartermp** [comment]
The only reason I could see this happening is some kind of outdated data being displayed, then it getting updated, and the list in the dropdown getting replaced with a new list. I've never observed the behavior as-described, thouhg.

**Comment by jimfoye** [comment]
I just tried reproducing in 16.6.3 without success. I reported this in 16.2 - perhaps it's no longer an issue.

**Comment by cartermp** [comment]
Closing as no repro
