### ISSUE TITLE
Compiler failure when inlining static method

### ISSUE THREAD

**Issue by Shmew** [dotnet/fsharp#9702]
When compiling code that inlines a call to a static member with a method parameter type of `obj` it throws with 

```console
Fsc: error FS0192(0,0): error : the anonymous record <>f__AnonymousType3440295454`2 has not been
 generated in the pre-phase of generating this module
```

**Repro steps**

I tried to extract many various parts from the Fable repo and my library to produce a more compact reproduction, but I can't reproduce the failure when I do that.

* Clone this [repo](https://github.com/Shmew/Feliz.Recoil).
* Remove the `FABLE_COMPILER` directives [here](https://github.com/Shmew/Feliz.Recoil/blob/master/src/Feliz.Recoil/RecoilRoot.fs#L75) and [here](https://github.com/Shmew/Feliz.Recoil/blob/master/src/Feliz.Recoil/RecoilRoot.fs#L90).
* Build the [docs application](https://github.com/Shmew/Feliz.Recoil/tree/master/docs) (via dotnet/vs not fable).

**Known workarounds**

Removing the inline allows the compilation to succeed (see compiler directives in repro steps).

**Related information**

Tested with both dotnet cli `3.1.101` and `3.1.302`

Visual Studio 16.6.4

Might be related to #6434?

**Comment by cartermp** [comment]
I believe @isaacabraham ran into this somehow in Farmer as well as per https://twitter.com/isaac_abraham/status/1292124826522603524

**Comment by cartermp** [comment]
Tagging this with `urgency-now` since the message is absolutely awful and clearly blocks people from progressing without sheer guesswork.

**Comment by dsyme** [comment]
There's a likely fix for this here: https://github.com/dotnet/fsharp/pull/9996

**Comment by cartermp** [comment]
Should be fixed by https://github.com/dotnet/fsharp/pull/9996
