### ISSUE TITLE
Support showing decompiled source definitions in F# source files

### ISSUE THREAD

**Issue by kerams** [dotnet/fsharp#9713]
I'd like to see [this](https://docs.microsoft.com/en-us/visualstudio/ide/go-to-and-peek-definition?view=vs-2019#view-decompiled-source-definitions-instead-of-metadata-c) available from .fs files in VS too.

With the feature enabled, pressing F12 on a type or member whose source is unavailable would peek its decompiled definition (perfectly fine by me if it's reconstructed in C#) instead of the ol' `Cannot navigate to the symbol under the caret.` message box.

**Comment by dsyme** [comment]
F12 support for external F# definitions was implemented quite a while back
