### ISSUE TITLE
Evaluating a static field in a class also evaluates the static fields of all classes in the same file.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/fsharp#9719]
Consider this program:

``` fsharp
module First =
    let foo = 59

module Second =
    let bar: int = failwith "Don't touch it!"

printfn "The magic number is %d" First.foo
```

It evaluates the value from the `First` module but also evaluates the value from the `Second` one, and an exception was thrown.

The same happens if we used nested modules:

``` fsharp
module Outer =
    let foo = 59

    module Inner =
        let bar: int = failwith "Don't touch it!"

printfn "The magic number is %d" Outer.foo
```

An exception was also thrown when I tried to move the two modules and the entry point in their own namespace.

Now consider this C# program:

``` csharp
using System;

namespace StaticConstructorTest
{
    static class Outer
    {
        private static readonly int Foo = 59;

        static class Inner
        {
            public static readonly int Bar = CreateBar();

            private static int CreateBar() => throw new Exception();
        }

        static void Main() => Console.WriteLine($"The magic number is {Foo}");
    }
}
```

`Inner`'s class constructor is not run: the program completes without throwing an exception.

---

The problem is that all fields of a module in a file are initialized from a static class located in a `<StartupCode$MyAssembly>` namespace. Is there a reason we don't initialize the fields in the static constructor _of the same module_? Besides crashing contrived examples like this one and generating excessive IL, grouping the initialization of all the file's values at once renders the developer unable to easily determined when expensive `let`-bound values are going to be created.

**Comment by abelbraaksma** [comment]
Iirc, the general rule is that module level let bindings are evaluated when anything of that module gets accessed. This seems to make them sense for nested modules as well, though I wasn't aware that it happened to other modules at the same level in the same file.

I'd be worried that if this behavior is changed, that libraries relying on this behavior could fail, though I agree with the observation that initialization could potentially be done on a strict per module basis.

**Comment by teo-tsirpanis** [comment]
Breaking changes to the generated IL code are less of a concern with the `LangVersion` property.

**Comment by abelbraaksma** [comment]
Hmm my understanding was that it got introduced to be able to weed out bugs of new features. I don't think it was meant to open the doors for backward compat issues.

That said, maybe something can be done here that isn't a backward breaking change?

**Comment by teo-tsirpanis** [comment]
As this issue illustrates, F# does some things in its own way, directly contradicting what a person with C# experience would expect. I am glad we agree that nested modules' values could not be initialized when members of their parent module are evaluated. Moreover I don't think many libraries would be affected by that change in the evaluation order; relying on the implied order side-effects appear is already a terrible practice.

You asked for a change that is backwards compatible. Opting-in the C#-esque behavior on `LangVersion`s after a specified one _is_ backwards compatible. Still have we to be careful about major and widely dusruptive breaking changes, but if we don't allow small corrections that _might_ affect some edge cases at major cases, we are leaving some untapped potantial to the `LangVersion` property. And languages like Haskell use similar compile-time switches to control breaking changes that were introduced at later language versions.

My general belief is that the compiler output and behavior of C# and F# must more closely converge, to increase interoperability and predictability. An example is this issue: modules are in essence static classes and should behave like static classes in C#.

C# (at least before LINQ and `async`/`await`) is to IL what C is to assembly; that's why decompiling C# programs is such an easy and reliable task. It also means that C# doesn't have problems like this one: the C# developer has more control of the IL they produce. But F#, owing to its higher level takes more liberties with the IL it generates, making decompilation back to F# a non-trivial task, and letting the F# developer's generated IL at the mercy of the compiler with little to no control.

Loss of control over the generated code is a consequence of using a higher-level language, but mistakes like this one do occur and we shouldn't let these mistakes bind us forever.

**Comment by abelbraaksma** [comment]
> Loss of control over the generated code is a consequence of using a higher-level language, but mistakes like this one do occur and we shouldn't let these mistakes bind us forever.

I agree. And there's probably a big difference between something that's slightly backwards compatible only if certain code relied on undocumented or undefined behavior, as opposed to breaking something that is well-defined (like changing the overload resolution order or something).

But, whatever fix we end up agreeing on, and provided that the powers that be agree this needs fixing, it has to be something stable and predictable as it currently is (the described behavior may not be desirable, but it is certainly predictable). 

----

As an aside, I'm not sure the comparison with C# is 100% sound. First off, you can write classes, including static constructors in F# and they behave the same. Modules, while often compared with static classes, are not precisely that and they are designed to initialize only once. 

Furthermore, you compare `let` values in F# with the calling of the cctor in C#. But since you cannot write a cctor in a module, the example doesn't really compare. The C# code should have a static field that initialized to an exception to be somewhat comparable (I didn't test this, and perhaps this still won't throw in C#, but it would be more closely related to the F# code).

----

As for a possible fix, we'd need some kind of dependency graph, as an inner module in F# can access any `let` binding in the outer module, and the outer module can access the inner module directly _after_ their declarations:

```f#
module Main =
    let beforeNested = 41

    module Nested =
        let x = 42 + beforeNested

        module NestedDeeper =
            let y = 43 + beforeNested

        module NestedDeeper2 =
            let z = 44 + NestedDeeper.y

    module SameNested =
        let a = 45

    let afterNested = 46 + SameNested.a
```

Just saying: the current way runtime evaluation is executed, guarantees that this code works. If we change this behavior, we need a more complex way to track this initialization. Perhaps that's possible by relying on the runtime (which does this for C#), but there are serious gotchas with inter-related fields in C# in static cctors that can go horribly wrong in practice.

**Comment by cartermp** [comment]
> Breaking changes are less of a concern with the LangVersion property.

This is not true. We most certainly would not take a breaking change to a core mechanism like this.

**Comment by teo-tsirpanis** [comment]
Oh, we can have static constructors in F#? I had already known about `static let` but only now did I learn about `static do` inside classes. Good.

I might have missed something obvious but I don't understand what would go wrong if @abelbraaksma's modules were lazily evaluated (i.e. only when needed).

Regardless of the answer I feel more inclined to close the issue, now that it has been clear to me that modules are not just a fancy syntactic sugar for static classes and that a behavior for them can be accepted.

**Comment by abelbraaksma** [comment]
@teo-tsirpanis, maybe the example wasn't the best to come up with. The idea was to show that if it was compiled with delayed initialization that it wouldn't work (it shouldn't be compilable that way, so in the example given, the compiler would have to opt-in to eagerly evaluate).

A simpler way is perhaps the following (contrived, but it illustrates my point, I hope):

```f#
module X =
   let arr = Array.zeroCreate<int> 3
   let mutable idx = 0
   
   module Y =
      do arr.[idx] <- 42

      module Z =
         do idx <- idx + 1
         do arr.[idx] <- 43

   module A =
      do arr.[idx + 1] <- 44
```

In the example above, if compiled now, it would have `arr = [|42; 43; 44|]`. This is deterministic. But if module `Y`, `Z` or `A` gets lazily evaluated, or even if `X` gets evaluated independently and potentially _after_ the inner modules, then there's no telling what the order of the array would be.

**Comment by abelbraaksma** [comment]
Btw: there's another option besides using static constructors to lazily get a value inside a module evaluated: you can simply use `let z = lazy(expr)`. Anything in `expr` will be evaluated only once, and only at first use.

There's some delay in evaluation & change in evaluation order that you can introduce by using `let rec x = y ... and z = ...`, and perhaps with `module rec`, but that'll quickly get rather unpredictable.

**Comment by teo-tsirpanis** [comment]
Neither static field initializations across classes declared in the same file are isolated. Consider this snippet:

``` fsharp
type C() =
    static let foo = 59
    static member Foo = foo

type C2() =
    static let bar = failwith "Don't touch it!"

printfn "The magic number is %d" C.Foo
```

Despite not using `C2` at all, its field was nevertheless initialized, resulting in an exception being thrown.

This issue will be repurposed.

**Comment by abelbraaksma** [comment]
@teo-tsirpanis, while I sympathize with the unexpected trouble this may cause, I took the liberty to check the F# Specification 4.1 and in section "12.5.1 Execution of Static Initializers" it states, literally (emphasis mine):

> At runtime, the static initializer evaluates, in order, the definitions in the file that have observable 
initialization according to the rules that follow. **Definitions with observable initialization in nested 
modules and types are included in the static initializer for the overall file.**  

And, specifically for scripts:

> For scripts, F# Interactive executes the static initializer for each program fragment immediately

It should be noted that "definitions that have observable initialization" discount a number of things, among which are literals, let-bindings where the expression is a constant expression (like `let foo = 59` in your example) and functions. Your `static member`, however, is not exempt.

Generally speaking, I would try to refrain from raising exceptions inside static initializers (be it modules or types). This is the same as the common best-practice rule in C# to never throw exceptions in static constructors (see for instance [this post by Eric Lippert](https://ericlippert.com/2013/02/11/static-constructors-part-two/)). Likewise, expensive initialization shouldn't go in static let bindings, static do-statements or module let-bindings that are not functions.

I'm not sure if there is any bug here and whether it'll be worthwhile trying to change this behavior (what's the gain?). The moment of execution of static initializers cannot be predicted in situations with multiple threads (I believe this is a .NET CLR feature, not an F# rule, but it's certainly true for C#, VB and F# alike). You can break this rule with reflection: you can read a static field without kicking off the static initializers.

**Comment by teo-tsirpanis** [comment]
I see, thanks for the reference @abelbraaksma. This issue was more of a theoretical observation and was not affecting any actual code of mine. The main point of the issue is that F# was differently behaving from C#; given that the difference is subtle and already codified in the language specification, there is no reason to change it.
