### ISSUE TITLE
[Test Framework] Publish tests categorization guide

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#9722]
Publish a guide, which will be descibing migrating of existing (old suites) and creating new test cases.

Guide should describe where do certain categories of the tests belong (i.e. Test Suite, category, subcategories, etc.).

**Comment by abelbraaksma** [comment]
Could we add a "how to run"? For instance, the contributors guide currently says things like `build -testFSharpQA`, but doing that either crashes or hangs (or other weird stuff happens). I'd assume that after the migration these commands may work better (and perhaps even without `Perl`), but just putting this out here so we don't forget that tests should be runnable again from the commandline  ;).

**Comment by vzarytovskii** [comment]
> Could we add a "how to run"? For instance, the contributors guide currently says things like `build -testFSharpQA`, but doing that either crashes or hangs (or other weird stuff happens). I'd assume that after the migration these commands may work better (and perhaps even without `Perl`), but just putting this out here so we don't forget that tests should be runnable again from the commandline  ;).


Sure, will add section about running tests as well

The ultimate goal is to have zero magic involved in running tests, just plain 'dotnet test', and suites themselves being just normal dotnet ones :)

**Comment by dsyme** [comment]
Closing out this old tracking issue for the test framework
