### ISSUE TITLE
AssemblyContentProvider duplicates lots of strings

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#9727]
AssemblyContentProvider is used in two scenarios:

* The add `open` code fix
* Extended completion

It ends up dominating string duplication.

Here's memory usage in a ~700MB dump file of devenv.exe with VisualFSharp.sln loaded. Only some files are open and some basic editing was done in a long VS session, then it was left idle for a while. 19.24MB of the whole object set comes primarily from here.

![image](https://user-images.githubusercontent.com/6309070/88012088-db070c00-cacd-11ea-82ed-362af820cce7.png)

Diving into the three biggest yields:

![image](https://user-images.githubusercontent.com/6309070/88012103-e8bc9180-cacd-11ea-85cb-f6ca5243adbc.png)

![image](https://user-images.githubusercontent.com/6309070/88012119-f245f980-cacd-11ea-88d4-73e6ff20d701.png)

![image](https://user-images.githubusercontent.com/6309070/88012136-fbcf6180-cacd-11ea-81d6-5d1ea87b741a.png)

It is a similar pattern for many other strings.

**Comment by cartermp** [comment]
Probably not worth trying to optimize this. The strings are all parts of fully qualified namespaces. These parts could be pooled and then pieced together when accessed, but that feels like a lot of work.

An ideal approach would pull pieces of a namespace from a cache that's also accessible to all other analysis engines in FCS, reconstructing things only when needed.

**Comment by abelbraaksma** [comment]
@cartermp You beat me to it, reporting this, I noticed it too while profiling with dotMemory. I find it easier to use than some other tools (and it creates nice graphs ;), and these analyses are very useful. 

I had the same conclusion. There are also many very small duplicated strings that aren't in the namespaces. 

There's a library out there on github, called ZString, which should make this pooling easier. It guarantees zero extra allocations of strings and only ever stores a string once. It claims to be much faster than default string treatment (searching, splitting etc), and its techniques might be worth checking into, as we have a lot of such tasks.

See https://github.com/Cysharp/ZString
