### ISSUE TITLE
[Test Framework] Add a cleanup for files/projects created in %TEMP% after testrun

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#9748]
Right now, in the new test framework (Compiler.fs), %TEMP% is not geting cleaned up after the test.
We will need to figure out a way of cleaning it up after test suite run.

Update: We also need to have an option for preserving test artifacts after the run, for troubleshooting/debugging purposes.

**Comment by jonsequitur** [comment]
Assuming the test artifacts are useful for writing new tests or debugging existing tests, is there a mechanism to keep it from being deleted? A dedicated test artifacts folder can be useful here with some controls over when it should be deleted.

**Comment by vzarytovskii** [comment]
> Assuming the test artifacts are useful for writing new tests or debugging existing tests, is there a mechanism to keep it from being deleted? A dedicated test artifacts folder can be useful here with some controls over when it should be deleted.

Good point. We should have an option to preserve test artifacts, I will update the initial comment.

**Comment by abelbraaksma** [comment]
I'd propose to use a dedicated dir under the temp dir. This can be FsTests or something. The idea being that each user's temp dir will be littered with many temp files from many applications and finding the files a test output is pretty hard. 

Have a look at how I changed ExprTests, these are now done in their own dir and cleaned. Not yet an ideal method there, but it can give some pointers. 

The real challenge will be to make tests as much self contained as possible. Quite a few depend on global state, or files that are generated once. Ideally, each test creates its files, compiles etc, does its comparisons and cleans up. The cleaning up itself can easily be blocked by adding a breakpoint or, for a little more work, by using an environment variable or something.

**Comment by T-Gro** [comment]
Check if done (@KevinRansom  did this?).
