### ISSUE TITLE
F# 5.0 preview: FSI behvior different from compiled project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#9749]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1007592/f-50-preview-fsi-behvior-different-from-compiled-p.html)._

---
I am running simple code that references Microsoft.ML using the newly supported package references in FSI.

The code runs in the compiled project targeting net48 but not in .fsx script.

==== code ===
#r "nuget: Microsoft.ML.AutoML"
#load "Test.fs"

MLNetTest.TestML.test()

================

I have attached a repo.

This issue may be related to native dlls not being referenced correctly. ML.Net has many native DLLs.

(Also fsi is slow in vs 2019 preview but hopefully that will get fixed later)

---
#### Feedback Bot on 4/26/2020, 06:40 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Jon Sequeira [MSFT] on 5/6/2020, 04:12 PM: 

<p>Can you please provide Test.fs as well as any errors you’re seeing, or describe the expected behavior you’re not seeing.</p>
<p>Thanks.</p>

---
#### CZ8GB9 solved on 5/7/2020, 07:11 PM, 0 votes: 

<p>added solution, data file and tests.fs</p>

**Comment by KevinRansom** [comment]
The ML.Auto  package works well now with fsi. on coreclr on desktop, mac and linux.  Here is a testcase that verifies this:

https://github.com/dotnet/fsharp/blob/master/tests/FSharp.Compiler.Private.Scripting.UnitTests/FSharpScriptTests.fs#L121
