### ISSUE TITLE
Tabs are not replaced with spaces if there is a tab in a string literal

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#9751]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1109841/tabs-are-not-replaced-with-spaces-if-there-is-a-ta.html)._

---
When you have code like this in you'r F# file, then tabs are no longer replaced with spaces, as should happen.

````fsharp
let someText = """
<tab> Some text
""'
````

Where of course the `<tab>`. is an actual tab. This happened to me when I pasted some text as a multiline text string. And then suddenly with every tab indentation I got a tab not allowed error. 

This is quite a nasty bug and difficult to discover what caused it!

---
#### Feedback Bot on 7/12/2020, 09:33 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by abelbraaksma** [comment]
This is interesting, and weird. Iiuyc, this means that whenever there's a (valid or not) existing tab, any new tab (from hitting the tab key) is not replaced anymore?

**Comment by cartermp** [comment]
Yeah, the F# compiler shouldn't care about whatever is in the string literal. Surprised it does this.

**Comment by abelbraaksma** [comment]
I don't think this is the F# compiler, I think the OP means that the editor gets confused and starts inserting more tabs once it sees a single one.

Then, when you compile, you find the compiler complains, but that's because now there's a tab outside of quoted literals.

**Comment by dsyme** [comment]
> Where of course the <tab>. is an actual tab. This happened to me when I pasted some text as a multiline text string. And then suddenly with every tab indentation I got a tab not allowed error.

I've tried to repro this and I think this must have been because the Visual Studio mode for the file got switched from spaces to tabs. I checked and you can have tab charactersin the string, you just need to make sure your editor is set up to create and edit them

I don't think it's an F# language thing, or even a VS F# tooling thing, it's just how the VS editor works.
