### ISSUE TITLE
UI unresponsive to Mouse (and keyboard partially) VERY VERY often

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#9755]
Internal bug [1119151](https://devdiv.visualstudio.com/DevDiv/_queries/edit/1119151/?triage=true)

_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1021650/ui-unresponsive-to-mouse-and-keyboard-partially-ve.html)._

---
[regression] [worked-in:16.6 Preview 5]
Hello,

As i use Visual studio depending on how I debug / Alt Tab / run / debug / code or test
It seems to that i can use the Mouse annymore

Workaround :
Alt Tab / Alt Tab
=> keyboard now OK

=> Press Alt (to force the "accessiblity" in the menu)
=> the _ shows in the menu 
=> mouse is OK 

if you click in a "dead zone" of the banner (where there is no button / icons ...)
=> it goes dead again
=> press `Alt` again to release the mouse

---
#### Feedback Bot on 5/8/2020, 00:07 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 6/11/2020, 07:31 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Phillip Carter [MSFT] on 7/1/2020, 11:06 AM: 

<p>Hello, does this still happen with the VS 16.6 release?</p>

#### Feedback Bot on 7/7/2020, 11:19 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.

---
### Original Solutions
(no solutions)

**Comment by cartermp** [comment]
Closing out as there had been no response and it doesn't appear to be at all related to F# tools
