### ISSUE TITLE
Cannot create a loose file in VS

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#9756]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/990212/cannot-create-a-loose-file-in-vs.html)._

---
Opening VS without a solution, File > New File > F# Script (or any loose file)

Creates a dialog box saying, "Cannot access a disposed object" with ITemplateProviderInternal. See attached screenshot.

---
#### Feedback Bot on 4/14/2020, 08:08 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 5/6/2020, 04:15 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by cartermp** [comment]
This one was 100% not an F# bug since it was filed on a dogfood build and the error message was from the templating engine. But it's fixed now in dogfood builds of 16.8.
