### ISSUE TITLE
F# Interactive Window Editor Zoom doesn't support custom values

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#9758]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/866599/f-interactive-window-editor-zoom-doesnt-support-cu.html)._

---
Problem:
In 2019 16.5.0 Preview 1, changing Editor Zoom in the normal editor works as expected and is bound to the F# Interactive Window Editor Zoom. It can be changed at will by typing a valid percentage and pressing enter. However, the same doesn't apply to the F# Interactive Window, there you can only use one of the preset values.

Steps to repeat:
1. Create an F# Project
2. Open the F# Interactive Window
3. Try to change the Zoom Value manually by typing and observe the behaviour as described above

Workaround:
Set the zoom in the normal Editor Window as it is bound to the F# Interactive Window

---
#### Feedback Bot on 12/24/2019, 11:25 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/6/2020, 07:32 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Feedback Bot on 3/13/2020, 07:48 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by cartermp** [comment]
Realistically I don't think we'll do this. It's sufficient to just use the F# editor because people don't really use FSI within VS without an F# file open already.
