### ISSUE TITLE
Simpler way of getting ^?1234567 in an error, without SRTP

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#9768]
Normally, those weird `^?345678` that popup every now and then are the result of SRTP behavior (#9717, #3508, #9633). But here's a way without any complexity. Basically:

```f#
[<Struct>]
type MyStructDU =
    | Value1 of (Value1: int)   // weird error here
    | Value2 of int
```

![image](https://user-images.githubusercontent.com/16015770/88351056-66de9980-cd55-11ea-9d6d-d4a954787206.png)

What's extra weird is, that when you compile it, you only get one error:

>  error FS0010: Unexpected symbol ':' in union case. Expected ',' or other token.

But in the Error List you see both, and in the popup you only see the first one:

> FS0715: Anonymous type variables are not permitted in this declaration

But there is no anonymous type variable here...

(as an aside, I actually think the above syntax should be allowed, but that's a different discussion)

**Comment by vzarytovskii** [comment]
FS0715 is gone in `main`, gonna close this one

**Comment by abelbraaksma** [comment]
I can confirm, it is also gone in RTM.
