### ISSUE TITLE
What is the significance of FX_NO_WINFORMS? Is it required?

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#9788]
We've got a lot of defines in our props. FX_NO_WINFORMS stood out to me since it feels odd that we care about if winforms is/isn't available. Is it necessary?

**Comment by cartermp** [comment]
@dsyme @KevinRansom

**Comment by KevinRansom** [comment]
FSI on the desktop pumps windows messages, it means that a script can pop up a dialog box, and it gets messages.  The Coreclr doesn't allow that, because no winforms.

And before you ask ... yes we will do something for NET5.0 we haven't yet, reason priorities.
