### ISSUE TITLE
FS0039 when accessing a static member

### ISSUE THREAD

**Issue by aspnetde** [dotnet/fsharp#9807]
I've got the following script:

```fs
module A =
    type Foo =
        | Foo of int
        static member Zero = 0
        
    let getZeroFoo () =
        Foo.Zero // Works
        
module B =
    let getZeroFoo () =
        A.Foo.Zero // Does not work
        
B.getZeroFoo()
```

Which results in:

> (8,15): error FS0039: The field, constructor or member 'Zero' is not defined.

Is there a valid reason why this member isn't accessible, or is this a bug?

(macOS & netcore3.1)

**Comment by abelbraaksma** [comment]
Looks like a bug to me. If you open `A`, it works. I don't see a reason why there's a conflict here.

Workaround: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEAzAzmgFxAEsM0ATEAagB8BbCcgVwxgAIBBNgXgFgAoNkLYEAngAd2AMQgQeA4YrY02MuRGxtiAOwIKlQ3AQCGBYmDZ0YdYDChsAWnbnc2ABn0HPbVgTYBzGAInKAg1NgAKAEp5QQNVWQA6ELkAelS2AHVoAGtcb0UBBmZWNgAhWMUISW1Ob18AoJTw6Mr4tWTnNnS2ABEIGFw2bQg/AHdcguEBMsTA4Oc1aKA==

**Comment by TIHan** [comment]
@aspnetde @abelbraaksma Opening the type does work but also note that feature is in preview; but we are working getting it out of preview soon.

In the example `A.Foo.Zero`, the identifier `Foo` is getting resolved to the union case even though it's used in a context where `dot`ing off union case name doesn't make sense.

This is a consistency issue and a bug. I've been diving in name resolution for about a month now so I may be able to fix this.

**Comment by TIHan** [comment]
I do think this is a bug; but you could consider it a 'feature improvement' depending on how you look at it. I vote bug.

**Comment by aspnetde** [comment]
My example is a bit unfortunate, by the way. The real context I was using it, is more like that:

```fs
type SomeId =
    | SomeId of Guid
    static member Empty = SomeId(Guid.Empty)
    static member New() = SomeId(Guid.NewGuid())
```

So I've got a single-case discriminated union with some convenient factory methods attached to it which are then used "dotting through" (e.g. `SomeId.New()`).

**Comment by johannesegger** [comment]
Another "workaround" is using a separate module with the same name:

```fsharp
type SomeId =
    | SomeId of Guid

module SomeId =
    let empty = SomeId(Guid.Empty)
    let new() = SomeId(Guid.NewGuid())
```

I didn't decide for myself what approach I like more and why, oftentimes they are identical.

**Comment by aspnetde** [comment]
Another side note: Static doesn't mean what I expected it to mean: https://twitter.com/realparadyne/status/1288072129351684102

**Comment by auduchinok** [comment]
@aspnetde in this context `static` means it's accessed on a type and not on a particular object. If you want a "calculate once" behaviour, consider using auto properties: http://fssnip.net/8B.

**Comment by abelbraaksma** [comment]
Or the module approach, which gives you the static "eval once" behavior out of the box ;).

**Comment by dsyme** [comment]
I suspect this will be resolved as a known difference in how module-qualified paths `A.Foo.Zero` and unqualified paths `Foo.Zero` get resolved in the presence of both a union case and a type `Foo`

In module-qualified paths, the union case always takes precedence.

In unqualified paths, for the `Foo` in `Foo.Zero` the type name takes precedence.

Whether one of the other appears correct is partly dependent on whether the union cases takes arguments, e.g. consider

```
module A =
    type Foo =
        | Foo
        member _.Zero = 0
        
    let getZeroFoo () =
        let foo = Foo
        foo.Zero 
```

however this doesn't compile when you might think it would:

```
module A =
    type Foo =
        | Foo
        member _.Zero = 0
        
    let getZeroFoo () =
        Foo.Zero 
```

Here again the `Foo` in `Foo.Zero` will resolve `Foo` as a type name.

I suspect this will be an unresolvable issue where two code paths in name resolution gives different results, though I might be wrong.  

The workaround in each case is to either apply `RequireQualifiedAccess` to the union type or else don't use identical names for union case and type.

**Comment by dsyme** [comment]
I have recorded this as a language suggestion here: https://github.com/fsharp/fslang-suggestions/issues/907
