### ISSUE TITLE
Typeinference fails when let-deconstructing record

### ISSUE THREAD

**Issue by 0x53A** [dotnet/fsharp#9812]
The following code will fail on the last line

```f#
type SomeOtherUnrelatedRecord = { A: int; B: string }

type Record = { A : int }

let r = { A = 1 }

match r with
| { A = ra } -> ()

let { Record.A = ra } = r

let { A = ra } = r
```

![image](https://user-images.githubusercontent.com/4236651/88644696-94b03f00-d0c3-11ea-8b3f-fc1732bd7208.png)

This is a little bit surprising because the type should already be fully determined by the right side of the expression, and it works in the match.

----------

* Editing Tools: ``VS 16.6.4``

**Comment by TIHan** [comment]
I think it's surprising too as it's not consistent with the behavior of match. Don't know if it's a bug yet or by-design. Will need to investigate more.

**Comment by heronbpv** [comment]
It failed on my machine because of the duplicate naming of ra, using Rider 2020.3 in a netcoreapp3.1 library project. In case you rename it like this, then:
```
type SomeOtherUnrelatedRecord = { A: int; B: string }

type Record = { A : int }

let r = { A = 1 }

match r with
| { A = ra } -> ra

let { Record.A = ra1 } = r

let { A = ra2 } = r
```
You only receive warning FS0667 at the last line.

**Comment by 0x53A** [comment]
> You only receive warning FS0667 at the last line.

Ah, we have warnings as errors active, so I didn't realize it was "just" a warning

**Comment by dsyme** [comment]
This is by-design, in the case of `let` the pattern is checked before the right-hand-side expression
