### ISSUE TITLE
[loc][Query][dotnet_fsharp] Localizability of string 

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/fsharp#9829]
For the file: "fsharp\xlf\FSComp.txt.xlf" and resource id: 0; "featureWitnessPassing"
For the string "witness passing for trait constraints in F# quotations"

Question is: This string is uncapitalized, does something precede it? Please provide the full sentence.

**Comment by cartermp** [comment]
Looks like this should be `Witness Passing for trait constraints in F# quotations`. Does that work?

**Comment by cristianosuzuki77** [comment]
If nothing precedes Witness, would it be possible to alter in the source as well?

**Comment by cartermp** [comment]
Yep, absolutely
