### ISSUE TITLE
For custom operation (ForEach) defines Source translation, why?

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/fsharp#9860]
Going through the spec and TypeChecker.fs after getting some strange CE compiler errors I noticed `For` has `Source` translation on the passed in 'enumerable'. However I'm at loss as to why? To me `Source` is something that happens around monadic bind sites, not normal ones; is it because when you squint the signature of `For` looks a lot like `Bind`? Or is it perhaps because it was a good fit for `query {}` where `Source` found its birth?

In any case `Source` is a very useful mechanism to combat `Bind` overload explosion, serving as an implicit inject/return at bind sites. On the other hand, when used in general purpose CEs source translation on `For` requires you to either: 
- Deal with lifted enumerables (when defining `member _.Source(x: 'T) = Monad.ret x`), this is not ideal from a performance standpoint, and it frankly shouldn't be necessary just as normal let, use, and yield bindings are spared too. 
- Add a weird identity overload just for `For` `member _.Source(x: 'T) = x` this works 'ok' but again, it feels like it shouldn't be necessary. 
The solution in all cases is to define this very general overload (though you could potentially scope it to just `seq<'T>`) which can often interfere with other overloads and produce ambiguity errors.

To me - from a conceptual standpoint - it does not quite click why you'd want Source translation of `For` enumerables in the general case, though surely I'm missing something @dsyme?

In any case tweaking the mechanism or allowing per builder configuration would be helpful.

```
T(for x in e do ce, V, C, q) = T(ce, V{x}, v.C(b.For(src(e), fun x -> v)), q)
```

https://github.com/dotnet/fsharp/blob/master/src/fsharp/TypeChecker.fs#L8241

**Comment by dsyme** [comment]
Yes, the source translation on For will be used for query syntax, e.g. https://github.com/dotnet/fsharp/blob/master/src/fsharp/FSharp.Core/Query.fs#L53-53

This is a language suggestion - can you move to fslang-suggestions?  I do see the issue

**Comment by dsyme** [comment]
(I'll close here, please do make a language suggestion on this)

**Comment by abelbraaksma** [comment]
@NinoFloris  did you end up making the language suggestion? If so, could you link back?

**Comment by NinoFloris** [comment]
I don't believe I did.
