### ISSUE TITLE
Program crashes when opening Excel

### ISSUE THREAD

**Issue by JohnyL** [dotnet/fsharp#9864]
I am trying to open Excel 2016 application:
```f#
open Microsoft.Office.Interop

[<EntryPoint>]
let main argv =
    let app = new Excel.ApplicationClass(Visible = true)
    0
```
However, I get the following error:
> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Office.Interop.Excel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'.

My project contains following COM reference:
```xml
<ItemGroup>
    <COMReference Include="Microsoft.Office.Excel.dll">
        <Guid>00020813-0000-0000-c000-000000000046</Guid>
        <VersionMajor>1</VersionMajor>
        <VersionMinor>9</VersionMinor>
        <WrapperTool>tlbimp</WrapperTool>
        <Lcid>0</Lcid>
        <Isolated>false</Isolated>
    </COMReference>
</ItemGroup>
```

Also tried:
```xml
<ItemGroup>
    <COMReference Include="Microsoft.Office.Excel">
        <Guid>00020813-0000-0000-c000-000000000046</Guid>
        <VersionMajor>1</VersionMajor>
        <VersionMinor>9</VersionMinor>
        <WrapperTool>primary</WrapperTool>
        <Lcid>0</Lcid>
        <Isolated>false</Isolated>
        <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
</ItemGroup>
```
But this didn't help either. Moreover, when I type `app.` on the next line, I get the following:

![image](https://user-images.githubusercontent.com/7391680/89217674-40322580-d5d5-11ea-9631-e0e3b0ba4962.png)

It's strange that F# tries to load Excel 2013. It was never installed on my system.

**Related information**

Provide any related information (optional):

* Windows 10 x64 Pro 1909
* .NET 5.0.100-preview.7.20366.6
* Visual Studio 2019 Preview 16.7.0 Preview 6.0

**Comment by dsyme** [comment]
Can you link a working C# example with an identical project file?

**Comment by JohnyL** [comment]
@dsyme Here's the link to [sample C# project](https://1drv.ms/u/s!AvqfUD6Rp0UCnzTBeSmHsZRODG3h?e=si5OiL).

**Comment by cartermp** [comment]
Feels like it's related to how the compiler processes assemblies, since there's certainly no code in the compiler or tools that says, "only load excel 2013" 🙂

**Comment by JohnyL** [comment]
@cartermp And this is strange since Office 2013 was never installed on my system. ![smile](https://www.yaplakal.com/html/emoticons/sm_biggrin.gif)

**Comment by dsyme** [comment]
Hmmm I was able to start an Excel 365 application using this
```
open Microsoft.Office.Interop

[<EntryPoint>]
let main argv =
    let app = new Excel.ApplicationClass(Visible = true)
    let book = app.Workbooks.Add();
    let sheet = book.Worksheets.[1] :?> Excel.Worksheet;
    //sheet.Range["A1"].Value <- "Hello from .NET 5!";
    0
```

It might be hard for us to make progress on this.  It feels like it's not specifically F# but a lot to do with the Excel installation and referenced assemblies etc.

I suggest you

1. compare compiled C# and F# DLLs for identical "main" 

2. compare command lines (esp. referenced assemblies)

**Comment by cartermp** [comment]
Closing out as external
