### ISSUE TITLE
[FS0250] - 'ModuleSuffix' needs to be added explicitly

### ISSUE THREAD

**Issue by JaggerJo** [dotnet/fsharp#9868]
When a module (`module A = ()`) and a type (`type A = { a : string }`) have the same name a "Module" suffix is automatically added to the name of the module. This seems to only work if the type and the module are located in the same file.

**Repro steps**
Create a Project with two Files

Lib.fs
```fsharp
namespace Repro

type A = { a: string }
```

Program.fs
```fsharp
namespace Repro

module A = ()
```

**Expected behavior**

Compilation works and and a `ModuleSuffix` is added implicitly. This works when both types are declared in the same file.

Program.fs
```fsharp
namespace Repro

type A = { a: string }

module A =
    ()
```

**Actual behavior**

Compilation fails with: 
`Lib.fs(3, 6): [FS0250] A module and a type definition named 'A' occur in namespace 'Repro' in two parts of this assembly`

**Known workarounds**

`[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]` needs to be added manually.

**Comment by abelbraaksma** [comment]
Isn't this "by design" or was this relaxed at some point? I still have plenty of code with that attribute.

**Comment by cartermp** [comment]
This is currently by design, though the RFC mentions a "compilation unit" instead of explicitly talking about per-file. I think this could be filed as a language suggestion here: https://github.com/fsharp/fslang-suggestions

**Comment by JaggerJo** [comment]
@cartermp Thanks, wasn't sure but suspected that.
