### ISSUE TITLE
Please resolve Microsoft.Windows.SDK.Contracts support

### ISSUE THREAD

**Issue by boyedarat** [dotnet/fsharp#9922]
`Microsoft.Windows.SDK.Contracts` is completely unusable with F# on .Net Core SDK 3.1.400.
Works perfectly fine with C# projects built on the same .Net Core SDK.
This is an issue that was previously reported in https://github.com/dotnet/fsharp/issues/7727, but was not adequately resolved.

**Repro steps**
Steps:
```
dotnet new console -lang F# -o uwp-test
cd uwp-test
dotnet add package Microsoft.Windows.SDK.Contracts --version 10.0.19041.1
dotnet build
```
Error output:
[error_log.txt](https://github.com/dotnet/fsharp/files/5062006/error_log.txt)

**Expected behavior**

It should build successfully.

**Actual behavior**

Produces errors that it could not find references to the `Microsoft.Windows.SDK.Contracts` package.

**Known workarounds**

The workarounds provided here does not seem to work:
https://github.com/dotnet/fsharp/issues/7727

Besides the `msbuild` hack, the other workaround is to use the `Microsoft.Windows.SDK.NET` package that is in "preview".
This package is very unstable and many of the APIs are plagued with type casting issues.

**Related information**

Operating system: `Microsoft Windows [Version 10.0.19041.450]`
.NET Runtime: `.Net Core 3.1.6 (SDK 3.1.400)`
Editing Tools: `Command Prompt`, `VS Code`

**Comment by cartermp** [comment]
Unless there's some information about the `Microsoft.Windows.SDK.NET` _not_ being intended as the future package to use, I don't think this is something we'll resolve. The `Microsoft.Windows.SDK.Contracts` is an older artifact that packages up tons of winmd files and the Windows team has been working to move away from that model. Given that their efforts are no longer aligned with that kind of architecture I don't think it's worth putting in the effort to ensure the F# compiler can handle those assets.

**Comment by boyedarat** [comment]
> Unless there's some information about the `Microsoft.Windows.SDK.NET` _not_ being intended as the future package to use, I don't think this is something we'll resolve. The `Microsoft.Windows.SDK.Contracts` is an older artifact that packages up tons of winmd files and the Windows team has been working to move away from that model. Given that their efforts are no longer aligned with that kind of architecture I don't think it's worth putting in the effort to ensure the F# compiler can handle those assets.

The `Microsoft.Windows.SDK.NET` is far from ready to be used, it is still in **preview**. If you were to look at their GitHub issues list, there are many API type casting issues. There continue to be bugs being reported about this even in the last couple of days.
In comparison, `Microsoft.Windows.SDK.Contracts` is a stable package that is ready to be used for production. The F# compatibility issue has been around since last year, with no fix in sight. While `Microsoft.Windows.SDK.NET` may be ready in due time, what are F# devs to use for now, since it is still not ready?

**Comment by cartermp** [comment]
Currently, nothing. We have no plans to enable consumption of winmd files in the way that the packages expects. Sorry that it's an issue, but we just don't have the bandwidth to treat it with any priority, and given that there's a replacement package with no problems from the F# compiler's side of things, our choice here is to go with that.
