### ISSUE TITLE
Find References incorrect output in VS 16.7

### ISSUE THREAD

**Issue by zanaptak** [dotnet/fsharp#9924]
**Comparison 1:**

Version 16.6.5:
![image](https://user-images.githubusercontent.com/53196138/90034508-5b143200-dc86-11ea-8650-95fc4a4deba6.png)

Version 16.7.1:
![image](https://user-images.githubusercontent.com/53196138/90034537-623b4000-dc86-11ea-92cf-db223dc1a989.png)

Issues:
- Two nodes for `Data`
- Bottom node invisible code line, only shows in hover tooltip

**Comparison 2:**

Version 16.6.5:
![image](https://user-images.githubusercontent.com/53196138/90034787-ac242600-dc86-11ea-9ac9-aecb24ed24fc.png)

Version 16.7.1:
![image](https://user-images.githubusercontent.com/53196138/90034843-be05c900-dc86-11ea-8d41-9858ce266225.png)

Issues:
- Two nodes for `Increment`
- Invisible code line
- No references found message

**Repro steps**

- Clone: https://github.com/zanaptak/references.git
- Open solution
- Open View.fs
- Find All References on `Data`
- Find All References on `Increment`

**Related information**

Provide any related information (optional):

* Operating system: Windows 10
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .NET Core SDK 3.1.302 vs 3.1.401
* Editing Tools (e.g. Visual Studio Version, Visual Studio): Visual Studio 16.6.5 vs 16.7.1

**Comment by cartermp** [comment]
There are at least two distinct issues here:

* The definition symbol is getting picked up, but in the display it says "no references". That's clearly incorrect, since there are multiple references.
* The display in the Window itself is completely off. When hovering, you can see in the hover that there is text and you'll see the reference there.

**Comment by TIHan** [comment]
Been investigating; I thought I had a fix but it turns out the text appearing is dependent on if the document is open or not. This is really strange as it does have all the correct information. This might be a bug in Roslyn, but not sure yet.

**Comment by TIHan** [comment]
Not a bug in Roslyn. Something must have changed in regards to ranges for the lexer API.

**Comment by TIHan** [comment]
This has been resolved.
