### ISSUE TITLE
Some values marked as unused do not become warnings when using --warnon:1182

### ISSUE THREAD

**Issue by TysonMN** [dotnet/fsharp#9936]
There are some cases in which values are correctly distinguished in Visual Studio as being unused but they do not become warnings when using `--warnon:1182`.

**Reproduction Steps**

Consider the following code ([zip of solution](https://github.com/dotnet/fsharp/files/5070307/MWE.zip)) in which `x`, `y`, and `z` are all unused.
```F#
module Top
type Foo =
  { Bar: Unit }
  member x.Baz() = ()
let private y = ()
let f z = ()
```

Visual Studio correctly displays them as unused via the darker font color and tool tips mention FS1182.

[x tooltip](https://user-images.githubusercontent.com/34664007/90162006-9af81980-dd59-11ea-90ee-80fa07285f42.png)
> val x : Foo
> FS1182: The value is unused

[y tooltip](https://user-images.githubusercontent.com/34664007/90162034-a3505480-dd59-11ea-8c00-d398e888d5fc.png)
> val private y : unit
> Full name: Top.y
> FS1182: The value is unused

[z tooltip](https://user-images.githubusercontent.com/34664007/90161680-19a08700-dd59-11ea-84ff-9d8f86bb55f2.png)
> val z : 'a
> FS1182: The value is unused

Now to the project file, add
```xml
<OtherFlags>$(OtherFlags) --warnon:1182</OtherFlags>
```

**Expected Behavior**

I expected there to be three warnings...one for each unused value.

**Actual Behavior**

There is only one warning ([screenshot](https://user-images.githubusercontent.com/34664007/90160601-9d597400-dd57-11ea-9d24-01a119548b8d.png)), and it is for `z`.  The tooltip for `z` also changes slightly.

[new z tooltip](https://user-images.githubusercontent.com/34664007/90161214-6fc0fa80-dd58-11ea-8375-5a52855a6621.png)
> val z : 'a
> FS1182: The value is unused
> FS1182: The value 'z' is unused

**Known workarounds**

None

**Related information**
* Operating system: Windows 10
* .NET Runtime kind: .NET Core 3.1
* Editing Tools: Visual Studio Enterprise 2019 version 16.7.1

**Comment by abelbraaksma** [comment]
The warnings in the editor use a different method than the one from the compiler. The editor actually shows more unused items (like a private member), that the compiler won't.

In other cases, when both the editor and compiler agree, you can see two warnings in the warnings window, but one warning when you compile. 

Ik actively working on this as part of wider issues saith warnings related to compiler directives.

**Comment by cartermp** [comment]
Yeah, this is kind of tricky. Historically the compiler switch was only ever designed for local `let`-bound values. The unused value analysis came afterwards and is more complete. I suppose the two could be unified somehow, but they're done in very different ways and it could also be that the compiler switch doesn't operate on enough data to make the kind of decisions that the analyzer does.

**Comment by dsyme** [comment]
I'm going to close this as the compiler switch is working as expected

**Comment by TysonMN** [comment]
I didn't mean to suggest that there is something wrong with the complier switch.

Should I open separate issues for `x` and `y` as not being reported as warnings?  How should I describe the problems so that the issues don't get closed because "working as expected"?
