### ISSUE TITLE
Compiler fails to infere type if it is located in a different module

### ISSUE THREAD

**Issue by Wkalmar** [dotnet/fsharp#9949]
Hello. 
I'm struggling to make project compile while the compiler can't infere types from another module.

**Repro steps**
1. Have module with target types
```
module TagetTypes =
    type Location2 = {
        lat: float
        lon: float
    }

    type Route2 = {
        id: string
        checkpoints: Location2 seq
    }
```
2. Have some transformation code
```
module Demo =
    type Location = {
        lattitude: float
        longitude: float
    }

    type Route = {
        id: string
        name: string
        stationStartId: string
        stationEndId: string
        checkpoints: Location seq
    }

    let routeToDbRoute (route : Route) : TagetTypes.Route2 =
        let mappedCheckpoints =
            route.checkpoints
            |> Seq.map (fun (i) -> {
                lat = i.lattitude
                lon = i.longitude
            })
        {
            id = route.id
            checkpoints = mappedCheckpoints
        }
```
Zip file
[BrokenTypeInferenceDemo.zip](https://github.com/dotnet/fsharp/files/5080320/BrokenTypeInferenceDemo.zip)
 
**Expected behavior**

This code compiles

**Actual behavior**

When trying to compile the project I get "The record label 'lat' is not defined."

**Known workarounds**

When I put target types in the same module as the rest of the code it compiles.

**Related information**

Provide any related information (optional):

* OS Windows 10
* .NET standard 2.1
* VS 2019 community edition

Thank you in advance!
Bohdan

**Comment by abelbraaksma** [comment]
I'm on mobile, and I couldn't open the zip for some reason, but in the example code I don't see any `open TagetTypes`. Since the types are in a module, you either need to open the module, or add `AutoOpen` as an attribute.

Another alternative is to place the types directly in a namespace, instead of a module. If both files are then in the same namespace, they'll be in scope.

**Comment by cartermp** [comment]
That's correct, there is a missing `open TagetTypes` declaration in the repro.
