### ISSUE TITLE
FS0192 the anonymous record has not been generated in the pre-phase of generating this module

### ISSUE THREAD

**Issue by vilinski** [dotnet/fsharp#9962]
Following DU if defined in a __referenced project__ and compiled in __release mode__ brings error in the subject, without calling the particular module by name.

```
open System

type Data =
    | FooBar of {| foo: Guid; bar: string; values: float[] |}
```

> error FS0192 : internal error : the anonymous record <>f__AnonymousType3327721423`3 has not been generated in the pre-phase of generating this module

Compiler didn't explicit called project or module causes the error, found it only with gradual code exclusion

**Repro steps**

Provide the steps required to reproduce the problem:

1. Create a library F# ReferencedProject containing the DU with anonymous record
2. Create another F# UsingProject, which references the ReferencedProject
3. Compile solution in release mode

In the attachment is the ready solution
[FS192.zip](https://github.com/dotnet/fsharp/files/5092615/FS192.zip)

**Expected behavior**

Both projects should be compiled without errors

**Actual behavior**

Error occurs only if DU is defined in another (referenced project) and only in release mode:

- Attemt to compile `ReferencedProject` alone is successful
- Attempt to compile `UsingProject` is also successful (`dotnet build` without options)
- `dotnet build --configuration Release` on `UsingProject` brings the compiler error:

**Known workarounds**

Replace anonymous record in DU with explicit record type

**Related information**

repro solution is in the attachment

* Operating system MACOS 10.15.6 Catalina
* .NET Runtime kind  - .NET Core 3.1.302
* Editing Tools - VSCode, dotnet cli

**Comment by cartermp** [comment]
Should be fixed by https://github.com/dotnet/fsharp/pull/9996
